### ISSUE TITLE
[Forms] input type="range" 

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#10008]
The native input type range had great support now http://caniuse.com/#feat=input-range

The styles should be updated to look like the Foundation Range Slider.
JS version
![screen shot 2017-05-04 at 8 34 30 am](https://cloud.githubusercontent.com/assets/5652085/25711761/8d7ef540-30a4-11e7-8d56-36b7df752be6.png)

Native
![screen shot 2017-05-04 at 8 34 36 am](https://cloud.githubusercontent.com/assets/5652085/25711780/96c7594e-30a4-11e7-8114-0d178303fdde.png)

They are apparently style-able and we may be able to pull form some of the existing variables. We should also update the examples to match the JS version.

Resources: 
- http://www.html5tutorial.info/html5-range.php
- https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/

**Comment by glen-84** [comment]
Should this be closed now?

**Comment by kball** [comment]
@rafibomb do you know the status of this?

**Comment by andycochran** [comment]
Let's revisit this for v7.
