### ISSUE TITLE
Scss file appears in dist folder

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation-sites#10000]
#### How to reproduce this bug:

1. Remove dist folder
2. Start npm
3. Review new dist folder

#### What should happen:
Dist folder haven't `scss` folder.

#### What happened instead:
`scss` folder appears in dist folder.
![seleccion_334](https://cloud.githubusercontent.com/assets/5034215/25568470/35a8a48c-2e0c-11e7-8458-1f0349aca6d8.png)

#### Browser(s) and Device(s) tested on:
x86_64 Linux 4.10.11-1-ARCH
"foundation-sites": "~6.3.0",

**Comment by ncoden** [comment]
# ⭐️ ⭐️ ⭐️  #10000 ⭐️ ⭐️ ⭐️

**Comment by IamManchanda** [comment]
Congrats @SalahAddin for being no 10,000!

Coming to your request, can I know your workflow? 
Are you facing this within zurb template, basic template or something else?

**Comment by SalahAdDin** [comment]
I'm working within Zurb Starter Template, i create mi project using Foundation CLI 2.1.0.

Where is my award? ✌️

**Comment by Deckluhm** [comment]
The issue has already been reported (https://github.com/zurb/foundation-cli/issues/47) and a pull request opened (https://github.com/zurb/foundation-zurb-template/pull/57).

**Comment by IamManchanda** [comment]
Thanks @Deckluhm .... closing this in favour of orignal!

-----------------------------------------------------------------

> Where is my award? :v:

cc @kball :stuck_out_tongue_winking_eye:
