### ISSUE TITLE
.menu.nested vs dropdowns while on medium/large screens

### ISSUE THREAD

**Issue by BicanMarianValeriu** [zurb/foundation-sites#10002]
#### How to reproduce this bug:

See the menu in the pen!

#### What should happen:
When you have a dropdown in your menu, it will add a margin to the sub-items ul and will not look ok for large screens. 

#### What happened instead:
It should add the margin only for small devices.

#### Test case link:
https://codepen.io/wecodeart/pen/xddBZz

**Comment by IamManchanda** [comment]
@BicanMarianValeriu would you like to create a PR for this ??

**Comment by BicanMarianValeriu** [comment]
Not capable of properly fixing this. Someone with better knowledge about F core should do it. Sorry for late answer.

**Comment by IamManchanda** [comment]
Fixed in #9670 ..... See this [comment](https://github.com/zurb/foundation-sites/pull/9670#issuecomment-303499741) 
Hopefully in 6.4 ..... sorry i dont think i will be able to create a patch for 6.3.2!
