### ISSUE TITLE
Table border not working

### ISSUE THREAD

**Issue by designchief** [zurb/foundation-sites#10004]
#### How to reproduce this bug:

I updated Foundation on a project from 6.2.4 to 6.3.1 and my table borders did not display any more.
I also tried a fresh version of 6.3.1 and added the default table markup and got the same result - no border even though a 1px border is specified in the settings:

$table-border: 1px solid smart-scale($table-background, $table-color-scale);

#### What should happen:

Border should be visible.

#### What happened instead:

Border not visible.

#### Browser(s) and Device(s) tested on:

Mac OS 10.12.4, Safari, Chrome, Firefox

#### Troubleshooting:

The framework adds the table border to the thead, tbody and tfoot, but I could not get any change by trying to override this css. I had to add a border declaration to the table directly to make this work. Again this border was working fine for me in 6.2.4 but not now.

**Comment by rafibomb** [comment]
Can you please share an example where this is happening? Here is a codepen with Foundation: http://codepen.io/rafibomb/pen/YVxpGQ

**Comment by designchief** [comment]
Here is my [example pen](http://codepen.io/designchief/pen/RVZvyx).

In the settings file, the table has a 1px border specified:
$table-border: 1px solid $light-gray;

Which outputs the following CSS:
`table thead,
  table tbody,
  table tfoot {
    border: 1px solid #e6e6e6; }`

But this is having no effect on the table, I have had to add:
`table {
	border: 1px solid $light-gray;
}`
to get a border included.

**Comment by IamManchanda** [comment]
Eureka found the issue http://codepen.io/IamManchanda/pen/gWxVpp

```scss
table {
  border-collapse: collapse;
}
```

@designchief thanks for reporting... as you reported would you like chime in and create a PR for this fix.
Creating a PR is easy as 1 2 3 =>https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by designchief** [comment]
@IamManchanda thanks for that. I had added that border-collapse to my own project to fix the issue.
I have now created a pull request #10009  as you suggested, hope it’s in the correct place etc..
