### ISSUE TITLE
foundation.min.css is not packaged for 6.3.1 on github, so cdnjs.com is broken

### ISSUE THREAD

**Issue by j000** [zurb/foundation-sites#10013]
#### How to reproduce this bug:
1. Download https://github.com/zurb/foundation-sites/raw/v6.3.1-rc1/dist/css/foundation.min.css
2. Download https://github.com/zurb/foundation-sites/raw/v6.3.1/dist/css/foundation.min.css
3. Check for changes

OR
    Go to https://github.com/zurb/foundation-sites/tree/v6.3.1/dist/css and look for prev changes for .min.css files
#### What should happen:
Files should be different
#### What happened instead:
Files are identical

#### Why it matters?
https://cdnjs.com/libraries/foundation uses version from github, so 6.3.1 and 6.3.1-rc1 are exactly the same. You post link to that *broken* cdn from [install page](http://foundation.zurb.com/sites/docs/installation.html).
Trying to test *data-closable="slide-out-right"* was really bad experience and I almost gave up on this amazing framework.

-----
I missed bug about it or nobody noticed?

**Comment by IamManchanda** [comment]
Yup seems true cc @kball !

![631rc](https://cloud.githubusercontent.com/assets/4970624/25775130/906e6baa-32bb-11e7-8d0a-28d0b65daaec.png)

**Comment by j000** [comment]
I'm a noob, completly new to Foundation...
There are no changes there: https://github.com/zurb/foundation-sites/compare/v6.3.1-rc1...zurb:v6.3.1

My issues are unrelated: https://github.com/zurb/foundation-sites/issues/8618#issuecomment-268864659

Sorry about that.

**Comment by j000** [comment]
Not sure why reopen, so let me put it more clearly.
Only *foundation-flex.css* got changed between 6.3.1-rc1 and 6.3.1 and minified version is different too.
Other *.css* files were unchanged, except version number in comments, so *.min.css* are exactly the same.
Most changes between this two versions were in javascript.

I'm new to Foundation, but I'm sure about this.

*data-closable="slide-out-right"* is working with downloaded complete version.

**Comment by IamManchanda** [comment]
Yup @j000 seems like there no changes 
(as there was only one css change in b/w and that was with flexbox which doesn't include these two files)
Maybe this isn't an issue and wont hurt anything!
But,
Seems like we forgot to add them in the release commit. 

Poke @kball but maybe we dont have to do anything here and keep thing as it is and this most probably will be closed without any actions!

**Comment by IamManchanda** [comment]
Update: This just maybe how git works (no changes so didn't add in commit) ... This might not be an issue at all!
