### ISSUE TITLE
Setting properties for all the tooltips

### ISSUE THREAD

**Issue by siddhant92** [zurb/foundation-sites#10024]
Hello all,

I am trying to add properties to all the tooltips present on the page. According to the documentation, the Foundation.Tooltip instance only affects the first tooltip on the page. How do I get it to affect all the tooltips without having to go through a foreach loop?

```
$(document).foundation();
var tooltip = new Foundation.Tooltip($('[data-tooltip]'), {
	hoverDelay: 1000
});
```

In Foundation 5.3, they suggested something like this but having tried that it gives a console error that we cannot pass objects as parameters.

```
$(document).foundation({
  tooltip: {
    selector : '.has-tip',
    hoverDelay: 1000
    }
  }
});
```
What's the best way to add attributes to all the tooltips without defining each of them inline?

**Comment by Owlbertz** [comment]
Hi,

you could go with something like this to set global options:
```javascript
Foundation.Tooltip.defaults.hoverDelay = 1000;
$(document).foundation();
```
See [this pen as an example](http://codepen.io/Owlbertz/pen/wdjjqE?editors=101).

**Comment by kball** [comment]
I think @Owlbertz's answer addresses this. Closing. Please reopen if this did not address your issue
