### ISSUE TITLE
Flexbox - Responsive Toggle & Menu Issues

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10025]
1. https://github.com/zurb/foundation-sites/issues/9871
2. https://github.com/zurb/building-blocks/pull/182#issuecomment-298813144
3. https://github.com/zurb/foundation-sites/pull/10021#issuecomment-300921192

**Comment by IamManchanda** [comment]
With 6.4 being flexbox first.... this needs to get resolved ... asap!
Some docs correction also maybe!

**Comment by andycochran** [comment]
@IamManchanda Is this issue still relevant? Looks like 1 and 3 have been resolved. And 2 is handled in a separate repo. Are you using this issue just to round up the three other issues? Can we close this?

**Comment by IamManchanda** [comment]
sure @andycochran
