### ISSUE TITLE
Magellan distroy() not removing all events

### ISSUE THREAD

**Issue by grantcarthew** [zurb/foundation-sites#10020]
#### How to reproduce this bug:

1.   Clone the [vue-foundation](https://github.com/vue-foundation/vue-foundation) repository.
   `git clone https://github.com/vue-foundation/vue-foundation`
2.   Change directory into the new clone.
   `cd vue-foundation`
3.   Install dependencies.
   `npm install`
4.   Run the project.
   `npm start`
5.   Open a browser to `http://localhost:8080`
6.   Open the dev tools on the browser and switch to the console.
7.   Click `Menu` on the right-hand side.
8.   Click the `Magellan` link.
9.   Click `Menu` again.
10.   Click any other component.
11.   Click `Menu` once more.
12.   Click any other component and watch the console.

#### What should happen:

Everything works well from the graphical browser perspective.

#### What happened instead:

The browser console displays the following error:

```

Uncaught TypeError: Cannot read property 'deepLinking' of null
    at eval (eval at <anonymous> (app.js:972), <anonymous>:5304:28)
    at dispatch (eval at <anonymous> (app.js:996), <anonymous>:5206:27)
    at elemData.handle (eval at <anonymous> (app.js:996), <anonymous>:5014:28)
    at pushHash (eval at <anonymous> (app.js:1253), <anonymous>:2191:24)
    at eval (eval at <anonymous> (app.js:1253), <anonymous>:2133:7)
    at eval (eval at <anonymous> (app.js:1253), <anonymous>:1668:19)
    at eval (eval at <anonymous> (app.js:1253), <anonymous>:1776:7)
    at step (eval at <anonymous> (app.js:1253), <anonymous>:1615:7)
    at step (eval at <anonymous> (app.js:1253), <anonymous>:1622:9)
    at runQueue (eval at <anonymous> (app.js:1253), <anonymous>:1626:3)

```

#### Browser(s) and Device(s) tested on:

Windows 10: Build 1703
Chrome: Version 57.0.2987.133 (64-bit)
The project is running on Debian Linux in a virtual machine on Windows.
The [package.json](https://github.com/vue-foundation/vue-foundation/blob/master/package.json) for the vue-foundation project. I updated them before posting this issue.

#### Test case link:

None

#### Notes

I suspect that the [distroy() method](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.magellan.js#L191) on the [Magellan](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.magellan.js) component is not cleaning up all resources. Specifically I think it is leaving an event registered. I could be wrong.

**Comment by grantcarthew** [comment]
I should add that the [vue-foundation](https://github.com/vue-foundation/vue-foundation) project is using Vuejs components.

The Vuejs component with the initialization code and tear down is located here:
https://github.com/vue-foundation/vue-foundation/blob/master/src/components/Magellan.vue

You will notice in the `<script>` section of the `.vue` file that I am using the `mounted()` and `destroyed()` Vuejs hooks to initialize the Magellan JavaScript and call `destroy()`.

Also notice that I am Initializing the Magellan JavaScript by using the `new Foundation.Magellan($el, options)` call rather than the jQuery `$el.foundation()` call.

**Comment by IamManchanda** [comment]
cc / @kball

**Comment by kball** [comment]
I think the assessment of this as a likely cleanup issue is correct.  @DaSchTour, @Owlbertz, or @coreysyms do any of you have time to tackle this before the 6.4 rc? (next 2 weeks)
