### ISSUE TITLE
[Card] - docs issue

### ISSUE THREAD

**Issue by bjornbjorn** [zurb/foundation-sites#10038]
http://foundation.zurb.com/sites/docs/card.html

The "Edit in Browser" link under "Card Divider" links to https://codepen.io/ZURBFoundation/pen/XRBZyM?editors=1000

.. which is a slider example, not a card divider example.

**Comment by IamManchanda** [comment]
Thanks for reporting 
Will fix it soon!

**Comment by IamManchanda** [comment]
FTFY #10044
