### ISSUE TITLE
6.3.1 Off-Canvas not working as expected in IE9 

### ISSUE THREAD

**Issue by designchief** [zurb/foundation-sites#10032]
#### How to reproduce this bug:
1. Install 6.3.1
2. Add new off-canvas markup from docs (or use old off-canvas 6.2.4 markup)
3. Off-canvas doesn’t hide on load, it is visible. Cannot close off-canvas either.

#### What should happen:
Off-canvas should be hidden on page load.

#### What happened instead:
Off-canvas is visible and will not close.

#### Browser(s) and Device(s) tested on:
IE9

#### Test case link:
[Test Link](http://ai-sites-test-01.designchief.ie/offcanvas-test-01.html)

**Comment by kball** [comment]
@brettsmason can you take a look?

**Comment by brettsmason** [comment]
@designchief thanks for raising this issue.
After inspecting your link in IE9 and some other projects I've worked on I've found the issue.
Off canvas should work just fine in IE9, but it seems like Autoprefixer isn't adding the needed `-ms-translateX...` to all of the transforms. In the mean time if you need a quick fix, go through your stylesheet and add `-ms-transformX` versions of all the transforms.

@kball any ideas why this would be? Looks like Autoprefixer is setup correctly as far as I can tell, but they aren't being generated like they should.

I'll see if I can find anything online about this issue.

**Comment by designchief** [comment]
Thanks, I had seen that the -ms- prefixes were not there so I had checked an older version 6.2.4 and the css prefixes looked pretty much the same.

Would the prefixing issue affect any other foundation elements in IE9 do ye think? Just ran a recent update and thankfully hadn’t deployed before snagging this. My client uses IE9 only so they informed me!

**Comment by brettsmason** [comment]
Prior to 6.3 off canvas didn't use transforms, so the issue wouldn't be present.
There may well be other prefixes missing too. How are you using Foundation - one of the Zurb stacks or something else? I have noticed a few mentions of cssnano causing prefixing issues so I'll test that out.

**Comment by designchief** [comment]
Ok, I will try your fix and let you know.

My test link is a Zurb Stack command line install.

**Comment by brettsmason** [comment]
So I've just ran a test with a personal project. I created 2 files, one not passed through cssnano (.css), and one goes through it (.min.css).

The version that isn't passed through cssnano has the prefixes there, but the version that goes through cssnano doesn't have the prefixes.

So I switched out cssnano for clean-css (https://github.com/scniro/gulp-clean-css) and setup the task like so: `.pipe($.cleanCss({ compatibility: 'ie9' }))` and the resulting minified stylesheet includes the correct prefixes.

@kball any reason you can think of that cssnano would be doing this? I haven't found any info. Also from my quick tests, clean-css is actually quicker... (http://goalsmashers.github.io/css-minification-benchmark/)

**Comment by brettsmason** [comment]
Looks like this is an issue with the distributed css files to:
https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.css
vs https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.min.css
The `-ms-` prefixes are missing in the minified file.

At a glance this will be effecting:

- Off canvas
- Orbit
- Progress bar
- Reveal
- Slider
- Tooltips
- Accordion
- Drilldown

**Comment by designchief** [comment]
Ok, thanks for that.
I would need to update this correctly as I have most of those components running.
So I would need to install clean-css via npm I assume,
and is that the only line I need to change in the gulp file?

Do you recommend I try this or wait to hear about best way to fix?

**Comment by brettsmason** [comment]
Yep that's correct, just install via NPM: `npm install gulp-clean-css --save-dev`
Then in your `gulpfile.babel.js` file you need to change this line: https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js#L89
to `.pipe($.if(PRODUCTION, $.cssClean({compatibility: 'ie9'})))`

If you wanted to get this working now I would go for it, as a fix wont be available until the next Foundation version. You can always revert back, but from my testing it works fine.

**Comment by designchief** [comment]
Added and installed gulp-clean-css via npm.
Then added the line suggested to gulpfile.babel.js.
But when I try to run "npm run build" I get this error:

TypeError: $.cssClean is not a function.

Full log:
[14:21:07] TypeError: $.cssClean is not a function
    at sass (gulpfile.babel.js:209:30)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (/Users/kieran/Documents/DC/WORK/DC SITES/ai-sites-01/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[14:21:07] 'build' errored after 318 ms
[14:21:07] The following tasks did not complete: pages, icons, javascript, images, copy, copyfavicon
[14:21:07] Did you forget to signal async completion?

**Comment by brettsmason** [comment]
Sorry typo in my code, it should of been:
`.pipe($.if(PRODUCTION, $.cleanCss({compatibility: 'ie9'})))` (got the words the wrong way around 😄 )

**Comment by designchief** [comment]
Thanks @brettsmason - that seems to have fixed the issue for me

**Comment by brettsmason** [comment]
@designchief Thanks for confirming.
@kball Did you want me to create a new issue for this or is this enough to go on? My suggestion would be to move to clean-css.
