### ISSUE TITLE
[Responsive Navigation] Documentation errors on JavaScript reference

### ISSUE THREAD

**Issue by diniscorreia** [zurb/foundation-sites#10040]
The Responsive Navigation component includes examples of both the responsive menu and responsive toggle - but on the JavaScript reference section it only states that `foundation.responsiveMenu.js` is required.

It should be clarified that `foundation.responsiveToggle.js` is required for the toggle menus.

**Comment by rafibomb** [comment]
Good call! That should be fixed with the 6.4 release coming soon. Can you add a Pull Request for this?

**Comment by ncoden** [comment]
It should be fixed by https://github.com/zurb/foundation-docs/pull/18

**Comment by andycochran** [comment]
Closing, as this was addressed in the doc repo.
