### ISSUE TITLE
h1 > small > abbr does not look good

### ISSUE THREAD

**Issue by fulldecent** [zurb/foundation-sites#10041]
#### How to reproduce this bug:

Sample code:

```html
<h2>ACLS, PALS and BLS training
    <small>for <abbr title="Emergency Medical Services">EMS</abbr> professionals</small>
</h2>
```

#### What should happen:

`abbr` is given appropriate weight and color.

#### What happened instead:

Rendering:

![screen shot 2017-05-18 at 12 13 10 pm](https://cloud.githubusercontent.com/assets/382183/26212452/9a8ee9dc-3bc3-11e7-8764-807efed7595a.png)

#### Browser(s) and Device(s) tested on:

macOS / Chrome

#### Test case link:

http://codepen.io/anon/pen/pPxJLm

**Comment by rafibomb** [comment]
So it should inherit the font weight and color?

Makes sense to me - are you able to submit a PR for this so we can add it to the framework?

**Comment by fulldecent** [comment]
PR sent, https://github.com/zurb/foundation-sites/pull/10067

**Comment by rafibomb** [comment]
You rock!
