### ISSUE TITLE
[Responsive Menu] Bug with Drilldown Accordion Combo

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10055]
Another Regression : Similar to #10031

If you set up a responsive menu with accordion on small, then drilldown for medium up, and resize to small and then back to medium the accordions will not work.

**Update**:
Bug: https://codepen.io/IamManchanda/pen/mmQXWO
Bug Patch: https://codepen.io/IamManchanda/pen/BRGJGL

**Comment by brettsmason** [comment]
That's a weird issue. Looking at inspector on your CodePen, the submenu is getting the class `.invisible` which is hiding the submenu. I think that comes from the drilldown menu, and isn't being removed by the responsive menu plugin on resize, or possible when the drilldown is destroyed. @kball does that sound correct?

**Comment by IamManchanda** [comment]
@brettsmason Yup and here is the fix
https://codepen.io/IamManchanda/pen/BRGJGL

```js
// Patch for bug in v6.3.1
$(window).on('changed.zf.mediaquery', function() {
    $('.is-accordion-submenu.invisible').removeClass('invisible');
 });
```

Maybe we need to do similar to accordion and dropdown
what's been done here in drilldown #9949 (https://git.io/vHUXn) 
cc @kball @designerno1

**Comment by kball** [comment]
The actual bug is the same underlying bug as https://github.com/zurb/foundation-sites/issues/10031 and has been fixed in develop and the 6.3.2 release line, so no need for additional bugfixing. The workaround looks right.

**Comment by IamManchanda** [comment]
Ohk @kball .... If it is so .... closing .... BTW do you recommend adding 1-2 more responsive combo's to docs instead of just the one combo there is in the docs??

**Comment by kball** [comment]
@IamManchanda more examples are probably good. If you want to add some, great! That said, as a follow up to the docs release @rafibomb and some of the other ZURBians did an audit of the current state of the content and are following through with more/updated written content for all of the pages over the next few weeks (and videos - we got better as we went, so the later vids are better than the earlier ones, and we want to bring them all up to par)

**Comment by rafibomb** [comment]
@IamManchanda Yes there should be - I've noted this in our audit thanks to your comment :)

**Comment by IamManchanda** [comment]
@rafibomb i already have a PR for it 
https://github.com/zurb/foundation-sites/pull/10058
