### ISSUE TITLE
[js] Tooltip for lables should prevent default on touch

### ISSUE THREAD

**Issue by robsdedude** [zurb/foundation-sites#10066]
To open a tooltip on a touch device one needs to touch the tooltip trigger. If this trigger is a label the touch event causes the default action of the label (i.e. click the input the label belongs to).

#### How to reproduce:

Consider this HTML
```html
<form>
  <label for="myCheckbox">
    <span  class="has-tip" data-tooltip aria-haspopup="true" data-disable-hover="false" title="Tooltips are awesome, we should totally use them!">
      Touch me I'm a label
    </span>
  </label>
  <input type="checkbox" id="myCheckbox" />
</form>
```
1. Touch the label

#### What should happen:
Just the tooltip should pop up

#### What happened instead:
The tooltip pops up and the checkbox changes it's value.

#### Try it:
https://codepen.io/anon/pen/RVvGXz

**Comment by andycochran** [comment]
This seems like an edge case. I'm not sure I'd recommend mixing labels that have `for` parameters with Tooltips. We should not change the default behavior of the label, which in this case is to change the checkbox value. I would recommend a different UI, perhaps an ℹ️ icon following the label which triggers the Tooltip.
