### ISSUE TITLE
Equalizer and web fonts causing layout issues in Safari

### ISSUE THREAD

**Issue by designchief** [zurb/foundation-sites#10072]
Hi all,

Is it possible to re-open #10005 as I cannot get the problem resolved, i have left a new comment in that issue but not sure if it will be seen...

Need some urgent help if anyone can help, the issue is too advanced for my head,
and new updates/deployment is waiting on a resolution to this...

Thanks, Kieran.

**Comment by IamManchanda** [comment]
I reopened that, closing this one...
