### ISSUE TITLE
[Orbit] external bullets and controls

### ISSUE THREAD

**Issue by sashabeep** [zurb/foundation-sites#10073]
Docs page doesn't contain any information about external orbit controls.
How to move bullets outside of orbit wrapper and make it work?

**Comment by DanielRuf** [comment]
Hi @sashabeep, thanks for reporting this.
Do you plan to provide a PR for this or do you have a working example?

Generally this is more like a specific implementation which has to use https://foundation.zurb.com/sites/docs/orbit.html#changeslide
```js
	$('.gallery .orbit-next, .gallery .orbit-previous').on('click', function(){
            var index = $(this).closest('[data-orbit]').find('.orbit-slide').filter('.is-active').index()
            ...
	});
```

isLTR | Boolean | flag if the slide should move left to right.
-- | -- | --
chosenSlide | jQuery | the jQuery element of the slide to show next, if one is selected.
idx | Number | the index of the new slide in its collection, if one chosen.

**Comment by sashabeep** [comment]
No, i didn't found a solution at the time of creating this issue, used trick with click on slide without use of bullets at all
```javascript
$(document).on('click','.portfolio-orbit .port-slide', function () {
		$(this).parent().find(".orbit-next").trigger("click");
	});
```

**Comment by DanielRuf** [comment]
@colin-marshall @ncoden is this a feature request / example implementation request?
I think this is already doable with the JS methods and should not be part of the general component documentation.

**Comment by colin-marshall** [comment]
@DanielRuf I would say this falls under feature request. Seeing this made think it would be helpful to have a method that returns the index of the active slide. So you don't have to write all this out:

```js
var index = $(this).closest('[data-orbit]').find('.orbit-slide').filter('.is-active').index()
```

That's not something that we probably need in v6 though.

**Comment by DanielRuf** [comment]
> That's probably not something that we need in v6 though.

Right. I've used a similar approach with the `index()` call.

**Comment by DanielRuf** [comment]
We will revisit this when we start the work on v7.
