### ISSUE TITLE
FOUNDATION CSS FILE - FIREFOX 53.0.3  - indicating some css style issues

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites#10076]
I'm not sure if this is a viable issue or not. But Firefox is showing some css issues in the MOTION UI CSS.

Line 4275
Expected RBRACE AT 4286 COLUMN 24

Line 4286
Expected RBRACE AT 4286 COLUMN 23

Line 4221
Expected RBRACE AT Line 4221, COL 26

Line 4222
Expected RBRACE AT Line 4222, COL 26

Line 4202
Expected RBRACE AT 4202, COL 25

Line 4203
Expected RBRACE AT 4203, COL 25

Line 4195
Expected RBRACE AT LINE 4195, COL 25 

Line 4196
Expected RBRACE AT LINE 4196, COL 25

Line 4195
Expected RBRACE AT LINE 4176, COL 26

Line 4196
Expected RBRACE AT LINE 4177, COL 26

#### How to reproduce this bug:

1. Use Firefox  FIREFOX 53.0.3 
2. Download FOUNDATION latest version -  CUSTOM DOWNLOAD - ALL FOUNDATION COMPONENTS

USE BASIC FOUNDATION INDEX FILE -- set up it up with the foundation CSS 

#### What should happen:
There should be no errors shown ?

#### What happened instead:

Firefox highlights issues in RED

#### Browser(s) and Device(s) tested on:
Use Firefox  FIREFOX 53.0.3 

#### Test case link:

- [CodePen with Foundation 6.3.0 and MotionUI](http://codepen.io/IamManchanda/pen/vgemXR)
- [CodePen with Foundation 6.3.0, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/xgXdRq)

- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

**Comment by blynnc** [comment]
I think it's a good idea to get it right in css first -- then switch.

**Comment by JeremyEnglert** [comment]
I'm having a difficult time replicating this. Where are you seeing these errors? When I pop open the web console in Firefox, I see a few CSS related errors, but none related to the above.

**Comment by blynnc** [comment]
Try Real Time Preview -

**Comment by IamManchanda** [comment]
@blynnc Can you share the screenshot with us ??

**Comment by JeremyEnglert** [comment]
Real Time Preview appears to be a Adobe Dreamweaver feature - maybe there's an issue there. I looked at the specific lines of code referenced in your original post and did not see the missing RBRACE.

**Comment by andycochran** [comment]
I can't replicate this either. Going to close this for now. Please reopen if you can provide more detail as to how we can replicate this.
