### ISSUE TITLE
Jquery >= 3.0.0 (Security issue) 

### ISSUE THREAD

**Issue by mcifani** [zurb/foundation-sites#10087]
There is various security issues with the current Jquery version (2.2.4) any reason not been updated?  Could we have a release to update this dependency?  

Thank You

https://nodesecurity.io/advisories/328

**Comment by kball** [comment]
with 6.3 we upped the allowed but maintained permitted back below, I think there's enough changing in 6.4 on the JS side definitely makes sense to up the required to 3.0+ if there's security concerns

**Comment by mcifani** [comment]
Thanks @kball, any eta on the 6.4 release with this bump?

**Comment by kball** [comment]
We're doing the first release candidate tomorrow @mcifani
