### ISSUE TITLE
[The Grid] Block grids missing column class

### ISSUE THREAD

**Issue by dimbak** [zurb/foundation-sites#10084]
Hi, in your [docs ](http://foundation.zurb.com/sites/docs/grid.html#block-grids)you missed mentioning that the 'column' class is required for block grids to work/activated.

Please correct me if i am wrong.

Thanks

**Comment by Owlbertz** [comment]
Well, the example reads `<div class="column column-block">` so that should be fine. The text above the example references the "regular" grid and tells you to add the `.column-block` class accordingly.

**Comment by dimbak** [comment]
if you don't add the 'column' the size-up is not activated, if i am not mistaken, the 'column-block' is used 'apply a bottom margin equal to the width of gutters' 

no?

**Comment by rafibomb** [comment]
I think the documentation here can be updated. Explicitely mentioning the use of `.column` as your content container would be nice.

Separating the `.column-block` example to another section would be better too.

@dimbak It would really be awesome if you can submit these updates to docs. Can you help us with that?

**Comment by dimbak** [comment]
Sure no problem : )

**Comment by DanielRuf** [comment]
Hi @dimbak, do you still plan to submit a PR? Let us know if you need any help.

**Comment by DanielRuf** [comment]
In general we have `column / columns` and also `cell`.

**Comment by DanielRuf** [comment]
I think this is still clear enough as this is the normal float grid.
