### ISSUE TITLE
Several type errors after initializing foundation on doc ready

### ISSUE THREAD

**Issue by drnkwati** [zurb/foundation-sites#10083]
I get eight type errors in my console
TypeError: this.empty(...).Each is not a function 
After initializing foundation. I traced it to foundation plugin instantiation but could not figure out why.
Am using build 6.3.1
Have anyone​ had this issue.

**Comment by Owlbertz** [comment]
Hi @drnkwati, could you copy us the whole stack trace so we can see the line numbers?
If possible, please create a CodePen example that reproduces the issue, you can use [this template](http://codepen.io/IamManchanda/pen/LWGZxR).

At a first glance I can only say that `Each()` should most likely be `each()` (with lower case).

**Comment by drnkwati** [comment]
Hi i figured out it happens when am trying to include just the plugins i need in my build system.
When i include foundation.js or the minified version the errors go away. It happens no plugin is initialized when i use just a few as explained in the docs. As for the Each in uppercase it's the github editor attempting to correct my grammar.
For the moment i am going with the default foundation.min.js build
But i think the documentation should be improved 
Thanks

**Comment by drnkwati** [comment]
Sorry guys the errors came as a result of a function i copied from the locotus project,
And registered it on the jquery object as a plugin.
It was over riding a jquery function used by the foundation tooltip plugin. 
As a result unexpected results gave those errors.
Thus it's not a Foundation issue.
