### ISSUE TITLE
Docs tabs Deep linking example problem

### ISSUE THREAD

**Issue by MaartenvanSpil** [zurb/foundation-sites#10090]
In the docs for the foundation sites tabs (http://foundation.zurb.com/sites/docs/tabs.html#deep-linking) is an example with 
 data-deep-link-smudge="true" data-deep-link-smudge="500"

The second smudge attribute should be:   data-deep-link-smudge-delay="500"

**Comment by wfehr** [comment]
The same mistake is in the doc for the accordion (http://foundation.zurb.com/sites/docs/accordion.html#deep-linking).

**Comment by DanielRuf** [comment]
Closing as https://github.com/zurb/foundation-sites/pull/11039 is merged.
