### ISSUE TITLE
prototype css not packaged in dist for 6.4.0-rc1

### ISSUE THREAD

**Issue by kball** [zurb/foundation-sites#10107]
It builds just fine, but somehow got missed in setting up the dist folder.

**Comment by IamManchanda** [comment]
Yup can't find it here :disappointed: 
https://cdnjs.com/libraries/foundation/6.4.0-rc1

**Comment by IamManchanda** [comment]
Fixed in RC2 ... closing this, Cheers!
https://cdnjs.com/libraries/foundation/6.4.0-rc2
