### ISSUE TITLE
Add default npm entry for new foundation approach

### ISSUE THREAD

**Issue by kball** [zurb/foundation-sites#10108]
Essentially the foundation everything entry, but in dist with appropriate paths and set up for automatic import. See how bootstrap does it https://github.com/twbs/bootstrap/blob/v3.3.7/dist/js/npm.js and https://github.com/twbs/bootstrap/blob/v3.3.7/package.json#L23

**Comment by andycochran** [comment]
@kball, is this something you still want to work on for v6? Or should we revisit this for v7?

**Comment by kball** [comment]
This was actually included in 6.4. This has been fixed
