### ISSUE TITLE
Order classes on XY grid

### ISSUE THREAD

**Issue by kball** [zurb/foundation-sites#10109]
Responsive ordering classes (`small-order-1`, etc) should either get moved out of the flex-grid (it's generic flexbox, no?) or added explicitly to the new XY grid.

I'm leaning towards the former, just make them generic flex helpers. Thoughts @brettsmason @rafibomb?

**Comment by brettsmason** [comment]
@kball Yep agreed, they should be part of the flex helpers rather than the grid directly (though maybe an example on the grid page would be good).

Should they be something like `[size]-first/last` though, or do we include more than just 2 possible order values?

**Comment by IamManchanda** [comment]
I have a vision around all of this... Will give a brief tonight IST once I reach home.

**Comment by brettsmason** [comment]
Think we can close this now as the PR was merged adding the ordering classes as flexbox utilities!
