### ISSUE TITLE
[Prototyping] Docs: No such docs on responsive breakpoints

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10106]
Current docs is short on documentation about responsive breakpoints 
Step 1. https://git.io/vHIki
Step 2. https://git.io/vHII8
Step 3. https://git.io/vHII1

Assigning myself to do the same in coming days!

**Comment by DanielRuf** [comment]
What is the current state of this?

**Comment by DanielRuf** [comment]
Should be already done.
