### ISSUE TITLE
Vision - Flexbox Utilities (XY Grid)

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10117]
Since the rework of grid .... i was very certain that the docs need to improve with grid and its integration with flexbox helper classes. But at the same time, working with prototypes I have realized that these flexbox helper classes are not good css practices and really they are just only one step away from inline styles. 
At the same time, flexbox is not supported in every browser and for css only projects, people need these classes inbuilt as they give those vendor prefixes.
Moreover, flexbox is still new to the web and i think we need to support these helpers atleast for now 

So, Here is my Vision
1. Rename the docs page title to **Flexbox Utilities** (Url can remain the same as its old/SEO/Bookmarks) 
2. From Scss, Remove `flex.scss` and create a separate folder `flexbox` and move all those classes there.
3. Revamp them to the same values that we followed at [Prototype PR](https://github.com/zurb/foundation-sites/pull/10091)... Eg. Responsive breakpoints.
4. Keep them **Enable by default** but allow an option to disable 
5. Add some more helper classes as discussed in #10109 and #9814
6. **Most Importantly**, update that docs page/codepen examples to (on par) with something like http://frowcss.com/frow-shortcuts.html. Here is the example codepen with an example of these helper classes with the grid => https://codepen.io/IamManchanda/pen/WONvGz?editors=1000

Thoughts @kball @brettsmason @rafibomb @andycochran @zurb/yetinauts ??

**Comment by brettsmason** [comment]
@IamManchanda You raise some good points here. I'll properly go through this in more detail tomorrow when I'm a bit fresher...

1. Agreed
2. Why not just rename the partial to `flexbox-utilities.scss`?
3. Don't understand, but I havent caught up on your excellent work on the prototype stuff yet 😄 
4. As long as it doesn't add bloat then I think there may be use in doing that
5. There's a bit of grid crossover with `.auto/`shrink` classes, though order classes might be helpful
6. I think the difficulty is that's not really how our docs are setup to work, but I agree they work really well and are very clear. I personally prefer looking at the examples first and if I'm interested in it I'll look at the code, so the code is just taking up space to me unless I want to look at that particular example.

**Comment by IamManchanda** [comment]
@brettsmason 

> Why not just rename the partial to flexbox-utilities.scss?

Yes possible but for me they need to be separated as firstly we want to add more classes, Moreover it can help people to enable disable specific helpers ... just like [prototypes](http://foundation.zurb.com/sites/6.4.0-rc1/docs/prototyping-utilities.html#enabling-prototype-mode) . Specific file for alignment classes (both [horz](http://foundation.zurb.com/sites/docs/flexbox.html#horizontal-alignment) and [vert](http://foundation.zurb.com/sites/docs/flexbox.html#vertical-alignment) in one file and these [Vanilla flexbox helper classes](http://foundation.zurb.com/sites/docs/flexbox.html#vanilla-flexbox-helper-classes) with another file and same way we can add more classes like order!

> Don't understand, but I havent caught up on your excellent work on the prototype stuff yet

Let me clear that up .... for responsive breakpoints. Currently there is a [bloat]((https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_flex-grid.scss#L194-L285)) going out there. Specially there in Vanilla Helper classes aka `flex-grid.scss` ... We have actually responsive breakpoints which shouldnt be there by default. But then hey there is no such mention of responsive breakpoints in the docs which kinda sucks more. 

What i would like is this below :arrow_double_down: 
Step 1. https://git.io/vHIki
Step 2. https://git.io/vHII8
Step 3. https://git.io/vHII1

**Comment by IamManchanda** [comment]
Here is the bloat btw which is currently happening => https://git.io/vHgmX

**Comment by rafibomb** [comment]
> 1. Rename the docs page title to **Flexbox Utilities** (Url can remain the same as its old/SEO/Bookmarks) 

Maybe instead we move them into the Prototyping separation? I would use them to rapid prototype then move to CSS for production.

> 2. From Scss, Remove `flex.scss` and create a separate folder `flexbox` and move all those classes there.

See answer 1

> 3. Revamp them to the same values that we followed at [Prototype PR](https://github.com/zurb/foundation-sites/pull/10091)... Eg. Responsive breakpoints.

Yes, but this will require a migration (breaking changes), so we'll need to support bith classnames at least for one version - or Foundation 7

> 4. Keep them **Enable by default** but allow an option to disable 

Yup, same as prototype separation update

> 5. Add some more helper classes as discussed in #10109 and #9814

I agree we can save some bloat by allowing these prototype classes to be used in the grid, problem is that if they are disabled, then they can't be used on the grid. So maybe the Sass needs to be in the grid and documented as a flex helper.

> 6. **Most Importantly**, update that docs page/codepen examples to (on par) with something like http://frowcss.com/frow-shortcuts.html. Here is the example codepen with an example of these helper classes with the grid => https://codepen.io/IamManchanda/pen/WONvGz?editors=1000

Yes - improve the grid demo styles and same for Flex utils

**Comment by rafibomb** [comment]
@IamManchanda Here is the description of responsive breakpoints for helper classes.
![screen shot 2017-06-02 at 2 49 47 pm](https://cloud.githubusercontent.com/assets/5652085/26746135/db81ba92-47a2-11e7-8226-8dde6d55312b.png)

Are we on the same page:
- these classes are important 
- should be part of prototyping classes
- grid based modifier classes should be shared with flex utilities

**Comment by IamManchanda** [comment]
> these classes are important

Yes very important ... specially looking at current state of flexbox

> should be part of prototyping classes

Not right now ... as we need this to be enabled by default!
By the way, they are a prototyping classes only!

> grid based modifier classes should be shared with flex utilities

Yes because if we want to get on par with this then yes => http://frowcss.com/frow-shortcuts.html
Example Codepen =>  https://codepen.io/IamManchanda/pen/WONvGz?editors=1000

**Comment by IamManchanda** [comment]
@rafibomb ... sorry last night i just read your last comment and not before that ... human error!

> Maybe instead we move them into the Prototyping separation? I would use them to rapid prototype then move to CSS for production.
> 
> Yes, but this will require a migration (breaking changes), so we'll need to support bith classnames at least for one version - or Foundation 7

In that case here is option 2

For 6.4, Lets Add depreciation notice for [Flexbox Helper Classes](http://foundation.zurb.com/sites/docs/flexbox.html#helper-classes) and [Vanilla Flexbox Helper Classes](http://foundation.zurb.com/sites/docs/flexbox.html#vanilla-flexbox-helper-classes)

For 6.5, 
Just do it, Move them into the Prototyping separation as you mentioned rafi! Thoughts ?? @kball @rafibomb @brettsmason ??

**Comment by IamManchanda** [comment]
Closing this as major points covered in #10224
