### ISSUE TITLE
Variables listed in _settings.scss are outdated

### ISSUE THREAD

**Issue by oxyc** [zurb/foundation-sites#10114]
During the rework of the menu styling in #9670 the variables in `_settings.scss` were not updated.

Currently in master `_settings.scss`:

```scss
$menu-margin: 0;
$menu-margin-nested: 1rem;
$menu-item-padding: 0.7rem 1rem;
$menu-item-color-active: $white;
$menu-item-background-active: get-color(primary);
$menu-icon-spacing: 0.25rem;
$menu-item-background-hover: $light-gray;
$menu-border: $light-gray;
```

While `components/_menu.scss` defines:

```scss
$menu-margin: 0 !default;
$menu-nested-margin: $global-menu-nested-margin !default;
$menu-items-padding: $global-menu-padding !default;
$menu-simple-margin: 1rem !default;
$menu-item-color-active: $white !default;
$menu-item-background-active: get-color(primary) !default;
$menu-icon-spacing: 0.25rem !default;
$menu-item-background-hover: $light-gray !default;
```

**Comment by oxyc** [comment]
Actually it seems to go beyond `_menu.scss`, there's several variables missing from `_global.scss` as well. eg. `$global-menu-nested-margin`.

I'm guessing it's partly because https://github.com/zurb/foundation-sites/issues/9492 was postponed to 6.5

**Comment by brettsmason** [comment]
@oxyc I assume you are talking about 6.4 rc1? If so I'm guessing the new settings file wasn't generated before packaging it up. Poke @kball does that sound correct?

**Comment by oxyc** [comment]
Yes, 6.4 rc1.

**Comment by IamManchanda** [comment]
Dang!

**Comment by brettsmason** [comment]
Hmm I've just downloaded [rc1 from here](https://github.com/zurb/foundation-sites/archive/v6.4.0-rc1.zip) and all of the variables you mentioned are in the settings file. How did you get rc1, is it definitely that version you are using?

**Comment by oxyc** [comment]
Damn sorry my bad. I was copying them from the `develop` branch not the `6.4.0-rc1` branch. I apologize.

**Comment by brettsmason** [comment]
@oxyc No worries glad you got it sorted 😄
Had me worried there that we had messed up 😉

**Comment by IamManchanda** [comment]
I was same worried too brett :smile:

**Comment by kball** [comment]
Sorry that was confusing. Just merged the release branch back into develop.
