### ISSUE TITLE
Foundation relies on auto-globalization of the Foundation object

### ISSUE THREAD

**Issue by htto** [zurb/foundation-sites#10113]
Foundation-sites relies on the Foundation object being automatically put into global object space, when added to the window object. Thus in each plugin foundation-sites just does
```
!function ($) {
Foundation.<accessor>
```
,though actually the object was created within an anonymous function with
```
var Foundation = { ... };
...
window.Foundation = Foundation;
```
so that there technically is an assignment to the window object and not the global space. Thus one should probably use that assigned window object instead of the global one, i.e.
```
!function ($) {
var Foundation = window.Foundation;
Foundation.<accessor>
```

This fixes inclusion of foundation for me, and would get me closer to automated headless testing of foundation-sites using code. The browser doesn't choke on it either, so it might be worth thinking about it.

I am aware, that I'm basically on unsupported grounds here, but it does make sense to me, to properly use the assigned object, rather than relying on it getting globalized. Plus this would allow for easier, less hacky, foundation inclusion in custom js projects, that don't provide the browser-like auto-globalization of objects assigned to the window-object.

Btw. a naïve approach to auto-convert is this sed-call
```
sed -e 's|^\(!function\s*(\$)\s*{\)|\1\n  var Foundation = window.Foundation;|g' foundation.js
```

Thanks for listening and kind regards, Heiko

#### How to reproduce this bug:

1. Have a nodejs-project that requires foundation-sites (e.g. with npm in package.json "foundation-sites": "^6.3.0")
2. Have a js-file that requires foundation (e.g. require('node_modules/foundation-sites/dist/js/foundation.js') or just require('foundation-sites); properly set up the requirements for Foundation before inclusion)
3. Run the js-file

#### What should happen:
including foundation-sites should work. Whether it runs, is another story ;)

#### What happened instead:
```
node_modules/foundation-sites/dist/js/foundation.js.orig:391
  Foundation.Box = {
ReferenceError: Foundation is not defined
```
This happens for every access to the Foundation object in the anonymous plugin initialization functions

#### Browser(s) and Device(s) tested on:
nodejs-7

**Comment by kball** [comment]
@htto this was very much the motivation behind https://github.com/zurb/foundation-sites/pull/9965

We're addressing this in 6.4. You can see & try out the first release candidate here: https://github.com/zurb/foundation-sites/releases/tag/v6.4.0-rc1

We need to fix the default import but you should be able to get what you're looking for with 

`import 'foundation-sites/js/entries/foundation';`

**Comment by andycochran** [comment]
Was this addressed in the [move to webpack](https://github.com/zurb/foundation-sites/pull/9965) and v6.4? Please reopen if this is still an issue.
