### ISSUE TITLE
Discussion on naming convention of prototype utilities  

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10119]
Poke =>  @tdhartwick, @lgcallahan , @canterberrie , @rafibomb, @kball 

My first reactions! 

[Margin](http://foundation.zurb.com/sites/6.4.0-rc1/docs/prototyping-utilities.html#margin-helpers) - `m-a-0`, `m-x-0`, `m-y-0`, `m-l-0`, `m-r-o`.. etc
[Padding](http://foundation.zurb.com/sites/6.4.0-rc1/docs/prototyping-utilities.html#padding-helpers) - `p-a-0`, `p-x-0`, `p-y-0`, `p-l-0`, `p-r-o`... etc
[Width](http://foundation.zurb.com/sites/6.4.0-rc1/docs/prototyping-utilities.html#width) - `w-25`, `w-50`... and `mx-w`
[Height](http://foundation.zurb.com/sites/6.4.0-rc1/docs/prototyping-utilities.html#height) - `h-25`, `h-50`... and `mx-h`

**Comment by tdhartwick** [comment]
Awesome! 
I think that the `a` is implied similar to how it's written in CSS, so i'd drop that:

```
//affects all
margin: 1px;

//affects right
margin-right:1px;
```

**Comment by IamManchanda** [comment]
`I think that the a is implied similar to how it's written in CSS, so i'd drop that:`

Agreed! Let drop it!

Other class to look at which should be modified is this 

[Separator](http://foundation.zurb.com/sites/6.4.0-rc1/docs/prototyping-utilities.html#separator) `separator-left` =>  `sep-left` ... 

Other classes good for me as classes like `display-none`, `position-static`, `overflow-scroll` follow the foundation convention and i dont think there is any need to change!

**Comment by IamManchanda** [comment]
https://github.com/zurb/foundation-sites/pull/10017#issuecomment-305882408

> @IamManchanda Glad those prototyping classes are finally here! Been wanting official padding & margin classes for a while

Thank you @canterberrie but there are many more. Infact which really excites me actually are not classes but mixins like [Relational Mixins](http://foundation.zurb.com/sites/6.4.0-rc1/docs/prototyping-utilities.html#relational-mixins-aka-nth-child-mixins-)

**Comment by tdhartwick** [comment]
🤔 hmmm that's an interesting one. I think the format that I think of for the classes are `abbreviated css rule | modifier (like x,y) | value`

Butttt for the `.separator-left` that's an interesting on since it's not an actual css rule so abbreviations would probably be less understood immediately. I'm thinking if it's not a css rule it should be spelled out?

**Comment by tdhartwick** [comment]
Referring to @corysimmons https://github.com/zurb/foundation-sites/pull/10017#issuecomment-305896731

I think these helper classes are meant to only work in prototyping. I'm wondering if we'd want to include a linter or alert when `watching` that would warn people they're using prototyping classes.

Also on `npm run build` we could convey a more firm message if there are still prototyped classes?

**Comment by IamManchanda** [comment]
Sure @tdhartwick .... same thoughts ... 100% sir .... 
@kball can you help us here in these build messages ??

**Comment by IamManchanda** [comment]
But these messages should be only for classes. 
For mixins, it shouldnt be there!

**Comment by tdhartwick** [comment]
Agreed!

**Comment by IamManchanda** [comment]
@tdhartwick so what's the final verdit on `separator` ... ??
Reason i put it like this is because i have seen `sep` in some themes for the same or around similar purpose!

**Comment by tdhartwick** [comment]
I would vote for keeping `separator`. `sep` isn't easily guessable even though it's easier to type.

**Comment by corysimmons** [comment]
Match syntax to Emmet?

But also, how will `.m-7` work? Shouldn't it be something like `.m-sm`?

**Comment by IamManchanda** [comment]
`m-7` ... sorry but very careful here to not add many classes ... `m-0` to `m-3` only by default! (but can be customized)

**Comment by IamManchanda** [comment]
> Shouldn't it be something like .m-sm?
I like your idea but
No because we use sm (small) for responsive breakpoints!

**Comment by IamManchanda** [comment]
Added a PR  #10122

**Comment by kball** [comment]
So... I may be an outlier here, as I'm not really the target audience for prototyping classes, but I find these super terse classnames pretty aversive and hard to read.

Can we clarify a little who our target audience is for these?  Are we expecting these to only be used by power users like @tdhartwick? Or is this intended for beginners?

**Comment by IamManchanda** [comment]
Yes i understand this .... Yup a tough line to walk ... i have added a PR ... happy to get that PR rejected too!

> Are we expecting these to only be used by power users like @tdhartwick? Or is this intended for beginners?

Its for both ... power users and beginners!

**Comment by kball** [comment]
Hmm... would like some more opinions on this... @lgcallahan, @LaurelBCodin as some of our newer coders at ZURB what do you think?

Also lets tag in folks involved in the original prototype PR and issue... @IllusionPerdu @natewiebe13 @brettsmason @DaSchTour

**Comment by IamManchanda** [comment]
> If people want aliases or even namespacing, they're simple enough to create with preprocessors:

I am liking the sound of this the most. 

-----------------------------------------------------------------------------------------------------------------

Hey i am Newbie,
`margin-horizontal-0` ... so cool lets use it !

Hey i am Harry/@tdhartwick /@rafibomb  ,
`margin-horizontal-0` ... oh its so bad ... so long to type!
Lets correct this up

```scss
.m-x-0 {
  @include margin(null, $spacer, null, $spacer);
}
```

**Comment by tdhartwick** [comment]
The situation I use these is early in a client project to convey nicer scaffolds quicker. Instead of having to do the correct steps of thinking about naming conventions, creating partials, and loading into `_app.scss` it's more effective to get stakeholder buy-in early on visually (at least in our workflow at ZURB).

Also maybe I didn't understand the helper classes as far as the values, how does `1-3` work. Like where do those map?

Also, it jogged my memory that we've landed on an interesting approach for managing the grays for projects. We treat them like font weight values, and it's been suuuuper nice. 

Something like this:
```
$gray-100: $off-white;
$gray-200: $lightest-gray;
$gray-300: $light-gray;
$gray-400: $gray;
$gray-500: $dark-gray;
$gray-600: $darkest-gray;
```
It's fantastic for prototyping. Interested  in hearing your thoughts on this too!

**Comment by IamManchanda** [comment]
@tdhartwick A lot has been discussed here on this ( #9671 )
Right way is the color pallete instead => #9683 

------------------------------------------------------------------------------------------

```scss
$gray-100: $off-white;
$gray-200: $lightest-gray;
$gray-300: $light-gray;
$gray-400: $gray;
$gray-500: $dark-gray;
$gray-600: $darkest-gray;
```

See http://sass-lang.com/documentation/Sass/Script/Functions.html#scale_color-instance_method

**Comment by IamManchanda** [comment]
> Also maybe I didn't understand the helper classes as far as the values, how does 1-3 work. Like where do those map?

`$prototype-spacers-count: 3 !default;`

**Comment by corysimmons** [comment]
https://github.com/zurb/foundation-sites/issues/10119#issuecomment-305917859 seems like it would be a nice accessory library (for power users).

```html
<link href="foundation.css">
<link href="foundation-utils.css">

<p class="m-x-lg">
```

tbh, I'd just avoid this. Let Tachyons serve that crowd and Foundation serve everyone else.

**Comment by IamManchanda** [comment]
@corysimmons 
On http://foundation.zurb.com/sites/6.4.0-rc/docs/prototyping-utilities.html 

I have my 3 cents

1. **I might be wrong but i am getting a little feeling (with your Tachyons example you gave) that you might not concur with the development which has happended regarding prototypes.**
   
   I want to clear that first, I fully understand very well that these helper classes are a bad css practices and is really just one step away of inline css. But, i will be practical here... as a designer, we would know that while prototyping, we don't sell the code but instead sell the concept, the design, the interactivity. Infact in most situations, you need to show multiple designs to get one approved.
   
   For that scenario, i think they are not bad because they are **disabled by default** and biggest part of the current development is that they can be easily swapped by the [Sass Mixins](http://foundation.zurb.com/sites/6.4.0-rc/docs/sass-mixins.html#prototyping-utility-mixins) which for me is huge. 
   
   Infact to make it more better, I totally agree with @tdhartwick that we should look to include a linter or alert when watching that would warn people when they're using prototyping classes. I also agree on `npm run build` to convey a more firm message if there are still using prototyped classes. Infact would urge @kball or @paxperscientiam to make that happen!

2. **My another vision to this is with the dist build aka normal css projects (non modern web) where developers only code the design and they dont know CSS well**
	
   Well personally, As I live in India aka developing country, i can tell you the situation pretty well on this. In developing countries, 95% of the web if not more dont use Sass or even a good css methodology and moreover mostly developers(Php, Java Background) are the one who design the web and they just dont know css well. They want to just read the docs, get classes... add in code... repeat!
   For them i think this is a huge development, I have just compared the [css](https://cdnjs.com/libraries/foundation/6.4.0-rc2) and this is what i get
   
   a. [foundation.min.css](https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.0-rc2/css/foundation.min.css) - **101kb**
   b. [foundation-prototype.min.css](https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.0-rc2/css/foundation-prototype.min.css) - **109kb**
   
   I strongly believe that I have taken care of the code pretty well and have made the css as minimal as possible and I have no doubt in my mind that **8kb** of extra code is not bad for such a cool and **optional** feature like [Prototyping classes](http://foundation.zurb.com/sites/6.4.0-rc/docs/prototyping-utilities.html). Believe me or not, I personally think of this as a big reason why frameworks like bootstrap are so popular. 

3. **I now will come to the current discussion about renaming of sizing and spacing classes on whether its worth it or not!**

	I do think that It can be on first look... pretty difficult to understand the suggested naming but then I also have no doubt in mind that if we are showing these classes proper usage within the docs like below example :arrow_double_down:  then it wont be that difficult for a **newbie** to get into there minds pretty quickly!

![margin-docs](https://cloud.githubusercontent.com/assets/4970624/26752625/e464041a-4871-11e7-9aa7-3e61fb30fb1c.png)

**Comment by corysimmons** [comment]
Man, I appreciate the effortpost, but this is so much to read and I keep catching myself doing free consulting. Can someone please ban me from this repo/org so I can focus on getting a job?

**Comment by IamManchanda** [comment]
No issue, I understand... Thanks for all you have done with helping out get us ideas with new grid.

**Comment by IamManchanda** [comment]
Hey @tdhartwick @kball ... do we have a consensus on it ??

**Comment by canterberrie** [comment]
I'm all for margin & padding helpers, but personally I've never felt the need for height & width classes. Doesn't the grid already do this? 🤔

**Comment by rafibomb** [comment]
I've only used the margin-bottom classes before for prototyping. 

Example:
```
.mb0 {
  margin-bottom: $global-margin;
}

.mb1 {
  margin-bottom: $global-margin;
}

.mb2 {
  margin-bottom: $global-margin * 2;
}
```

Don't think I'd use any others.

**Comment by IamManchanda** [comment]
The way it's coded you are allowed to choose  which helper classes you want and which you don't want

**Comment by IamManchanda** [comment]
It's already mentioned in the docs on how to choose specific utilities

**Comment by IamManchanda** [comment]
But yes sizing classes are debatable!

**Comment by IamManchanda** [comment]
https://github.com/zurb/foundation-sites/pull/10122#issuecomment-310976107
