### ISSUE TITLE
Grid frame not working properly in Safari

### ISSUE THREAD

**Issue by kball** [zurb/foundation-sites#10123]
Reported by @zurbrandon via twitter. Reproduced it on https://codepen.io/kball/pen/vZBeLy

**Comment by kball** [comment]
So this appears to be due to a difference in the way Safari is handling height calculations of flex children.... the grid is being sized appropriately to fit in the space, but the child cells with `.medium-cell-block-y` are not, they end up too big and thus don't scroll internally, and we've deliberately disabled externals scroll in this situation (that's what 

I think it is tied into this bug: https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items in that the max-height declaration is being ignored. 

A workaround is to disable flex wrapping on the grid in this situation. We can't do that globally because the automatic wrapping to the next line is a key function of the grid, but in this usecase that behavior would actually be more "expected" because we're explicitly laying out our space in the viewport and saying we want these blocks to handle scrolling internally... thats what the `.cell-block-container` class is for.  So I *think* that if we add this as one of the effects of the `.cell-block-container` on its immediate child grid, we will both resolve this problem and not have any unexpected side effects.

I've put together a quick PR at https://github.com/zurb/foundation-sites/pull/10124 but would love it if someone checked my thinking above @brettsmason and @zurbrandon

**Comment by kball** [comment]
Tagging @corysimmons based on his extensive flexbug experience to also review my thinking and if there's another way to address this that he happens to know

**Comment by corysimmons** [comment]
Sorry man, I need to focus on getting a job. Unsubscribing from all this stuff.

fwiw, I have cross-browser success with the panel stuff via padding grid.

**Comment by brettsmason** [comment]
I've looked this over and the logic behind this makes sense. I think we can assume this would be for app style layouts, and setting this to `nowrap` for the child grid sounds perfectly reasonable for this sort of layout. 👍
