### ISSUE TITLE
In RTL mode align-right is not set correctly

### ISSUE THREAD

**Issue by mozaffar** [zurb/foundation-sites#10125]
When you generate a customized css in RTL mode the value for class ".align-right" is not set correctly:

Currently:
`.align-right {
     -ms-flex-pack: end;
      justify-content: flex-end;
}`

and It should be:
`.align-right {
     -ms-flex-pack: start;
      justify-content: flex-start;
}`

Because the content should be started from right and be stick to the right side of the container ;)

**Comment by IamManchanda** [comment]
cc @abdullahsalem

**Comment by abdullahsalem** [comment]
Thanks @mozaffar for reporting this issue, and @IamManchanda for the mention.

**Comment by rafibomb** [comment]
Closing in favor of #10676
