### ISSUE TITLE
Error after upgrading to Node 8.0.0

### ISSUE THREAD

**Issue by michaelfriedman** [zurb/foundation-sites#10127]
#### Error after upgrading to Node 8.0.0
```
warning gulp-uncss > uncss > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
warning browser-sync > localtunnel > request > node-uuid@1.4.8: Use uuid module instead
...
...
'javascript' errored after 560 ms
'build' errored after 569 ms
'default' errored after 571 ms
The following tasks did not complete: pages, sass, images, copy
Did you forget to signal async completion?
```
**This could be related to the deprecation of node-uuid which is not compatible with 8.0.0.**

#### How to reproduce this bug:
Install Node v >= 8.0.0
foundation new
web site
zurb template
yarn
foundation watch

#### What should happen:
Server should boot on localhost:8000

After switching to Node 7.10.0 using NVM I was able to build successfully.

#### What happened instead:
Above error message.

**Comment by IamManchanda** [comment]
First of all, thanks for letting me know ... that Node 8.0 has arrived ... wasn't aware ... :)

On the issue, cc @kball !

**Comment by kball** [comment]
A quick lookthrough makes me believe this is coming through the sassdoc dependency... will try updating that on Monday, unless someone wants to get to it before me

**Comment by michaelfriedman** [comment]
@IamManchanda @kball  Yes, and NPM 5 is also released! Thanks for the quick reply... Enjoy the weekend.

**Comment by colin-marshall** [comment]
I tried to reproduce and could not with the latest version of node (8.1.2). Is this still a problem @michaelfriedman?

**Comment by codetheorist** [comment]
I'm with @colin-marshall, I've tested using Node 8.1.2 and unable to reproduce the issue.

Maybe node-uuid dependency has been updated in the package that depends on it?

**Comment by kball** [comment]
Sounds like this was fixed downstream. Closing.
