### ISSUE TITLE
[6.4 RC1] data-offset not working in smooth scroll

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#10121]
Adding data-offset does not offset page - example:

```
<ul class="menu align-center" data-smooth-scroll data-offset="50">
  <li><a href="#setup">Setup</a></li>
  <li><a href="#javascript-reference">Javascript Reference</a></li>
</ul>
```

**Comment by IamManchanda** [comment]
cc @denisahac @kball

**Comment by denisahac** [comment]
Is the issue present in **develop** branch, or the **6.4.0-rc1** tag? Which of the two should I test it against?

**Comment by IamManchanda** [comment]
Though i dont know as i didnt tested it @rafibomb did ... but i guess yes present in develop!
As develop is updated to 6.4.0 RC3 aka the latest! @denisahac

**Comment by denisahac** [comment]
Tested against **v6.4.0-rc3** adding **data-offset** on **SmoothScroll** module is working as expected. 

Also, I'd suggest, that on the documentation right sidebar magellan navigation, we should increase the data-offset; as you click on the link section, the title of the page section is covered by the Search bar. Adding **data-offset="100"** solves the usability issue.

**Comment by mattbag** [comment]
Hello, it seems like the active class is not assigned on scroll, latest foundation 6.4.1 build (picking plugins only smoothscrolling and magellan). Am I missing something (due to basic docs, and old version) or would it be a bug? I couldn't find a codepen with v6.4, I'll try to make one asap.
Cheers

**Comment by kball** [comment]
From what I'm seeing it looks like this is resolved... closing, please reopen if you're still seeing problems.

**Comment by MauriceBuiten** [comment]
For Magellan you need to set: data-bar-offset="50"  for it to work. not data-offset...   That is why its not working

**Comment by leo3po** [comment]
Please update the documentation https://foundation.zurb.com/sites/docs/magellan.html

**Comment by denisahac** [comment]
@MauriceBuiten @leo3po  we've renamed the `bar-offset` to just `offset` to simplify the name; see **Magellan** [defaults][Magellan].

[Magellan]: https://github.com/zurb/foundation-sites/blob/develop/js/foundation.magellan.js#L254
