### ISSUE TITLE
[Revisit] List Group components

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10132]
I think we should to revisit PR #9947 for the [list group component](http://foundation.zurb.com/building-blocks/blocks/list-group.html) to push it into core instead.

Reasons:

1. Super uselful for sidebars, off-canvas, or mobile menus. 
2. Generic Component instead of handful tasks!
3. [Bootstrap](https://v4-alpha.getbootstrap.com/components/list-group/) have it.
4. [Bulma](https://github.com/jgthms/bulma/issues/772) is thinking about to have it.
5. [Material Design Components](https://material-components-web.appspot.com/list.html) have it!

**Comment by brettsmason** [comment]
Isn't this just a vertical menu with borders? Could we simply not have a modifier class for menu to apply the correct borders, eg 'menu-bordered' or something? Not sure this needs be another new component, but just my opinion :smile:

**Comment by IamManchanda** [comment]
Dang no issue @brettsmason ... 

Yup `.menu-bordered` combined with [Active](http://foundation.zurb.com/sites/docs/menu.html#active-state) ... is an another option too .... 
But there is one issue in that scenario, 
**List groups are mostly for menu but not just for menu!**

**Comment by IamManchanda** [comment]
List group can be useful for stuff's like where things like cards or panel is so popular
Example: Notification Panel

**Comment by JeremyEnglert** [comment]
I think this may be best as part of the new prototyping classes. In fact, it's perfect for that. 

A big part of the reason Foundation is popular is because it ISN'T Bootstrap or Material. Foundation gives you a much cleaner canvas to start from. If we start providing too many of these design related elements, a big reason for using Foundation is lost.

**Comment by IamManchanda** [comment]
@JeremyEnglert 
> I think this may be best as part of the new prototyping classes. In fact, it's perfect for that.

Hmmmnnn... sounds good but i am not sure about that 
@kball @rafibomb can i get a word from one of you before doing an action ??

**Comment by kball** [comment]
This almost sounds more like a building block, no?

**Comment by IamManchanda** [comment]
I feel this like a component rather than a prototype utility first and foremost 
But I don't concur that it doesn't deserve to be in the core component sections! 

Secondly I personally think for f7 to {theme up}
We would want components of material design to be a part of the components in the core section (of course as a flat design) like this one and #9645 ??

**Comment by andycochran** [comment]
Let's revisit this for v7.
