### ISSUE TITLE
[Feature Request] Inverted Buttons  

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10131]
https://codepen.io/IamManchanda/pen/KqKbdM

Credits: [jgthms/bulma](https://github.com/jgthms/bulma)

**Comment by JeremyEnglert** [comment]
I think this should be part of "prototype mode". Seems like an extremely specific use case.

**Comment by IamManchanda** [comment]
Why want to handle this differently than Hollow buttons??

**Comment by JeremyEnglert** [comment]
Honestly, I'd be okay with hollow moving into the prototyping features as well. 

I guess we have to decide where we draw the line. These types of "quick styling" classes could become endless.

My other concern would be accessibility. It would be hard to find a light colored background that is WCAG compliant with the default Foiundation colors.

**Comment by IamManchanda** [comment]
Hmmnn cc @kball
