### ISSUE TITLE
[Feature Request] Sass-centric Docs & Pens 

### ISSUE THREAD

**Issue by Timoti** [zurb/foundation-sites#10136]
Given Zurbians are (rightly) big on promoting a semantic sass approach, why is it that the sass help and now the pens too are the poor cousins of the class-ridden non-semantic-markup approach.  Mixins are bundled together down the bottom, rather than with code examples = in fact they have no  code examples.  Same with the pens. 

Case in point: the new X-Y grids - I'm really excited by this – particularly as previously I've always ended up replacing foundation's grid with susy to have the flexibility of margin or pad gutters AND to avoid having to insert extra markup for rows. And i've been using native gridcss on projects but would prefer to do it in an organized frameworked manner.  

But i digress - XY grids are not at all intuitive and so some semantic sass docs, code examples and pens would be super handy.   

I think we can agree sass is now a thing and not about to disappear soon - how about it gets the love it deserves in the docs? (which might also encourage many classymarkup people to get semantic)

BTW thanks for the pens - they're a way cool idea - just need to get sassy!

**Comment by brettsmason** [comment]
@Timoti Thanks for the very constructive feedback. As a user who uses primarily Sass myself rather than the classes I'd agree it could use some love. I'll label this and make sure its discussed and see what we can do. Do you have any suggestions or thoughts on what you would like to see?

Also I'd really appreciate your feedback on the XY grid seeing as how you expressed an interest! Would you mind adding some [feedback here](https://github.com/zurb/foundation-sites/pull/10017)? If you think the classes aren't intuitive I'd love to hear what you think would improve them, and also as a Sass user how you would like normally use mixins for the grid. The mixins still need a bit of work before the full release, so there's time to polish them up a bit. I was also a Susy user, so I figure we would have similar goals.

@kball should we have an open issue for XY grid so its easier to find and leave feedback?

**Comment by rafibomb** [comment]
@Timoti Right on! Luckily - this is on the docs roadmap. There is a technical hurdle with the way the Sass docs are auto generated but it should be do able. We have working Sass codepens. We can figure out how to add the pens into the Sass docs.

We'll need help creating the pens, would you be able to help with some of those?

**Comment by IamManchanda** [comment]
Sorry to be a villain :smile: 
but, Sass Imported Codepen's are very slow because so much code already there in it!
I have faced this issue so i am sure about it ... 

https://blog.codepen.io/documentation/editor/limitations/

> One of the limitations of the CodePen editor is sheer volume of code. You may never run across this issue, as the editor should be fine with hundreds or even thousands of lines of code. But when they start hitting 5,000 - 10,000 or more lines of code, you'll see the editor start to fail. Things like:
> 
> - CodePen becomes slow and unresponsive
> - The Pen may not save
> - The browser crashes

**Comment by rafibomb** [comment]
Hmm, that is something to consider. Right now the Sass pens we have made take about 4 seconds to refresh. I think it could work if people know and expect that.

**Comment by IamManchanda** [comment]
I have 30-50 mbps connection and its still takes atleast 10sec ... The reason would be maybe because the server in US and for a cdn also ... they are using cloudflare instead of aws or akamai ... so its not great for every part of the world!

**Comment by Timoti** [comment]
Dang! But sass pens would still be valuable if we have some  control over _when_ code compiles (not sure if that's an option) .  FWIW, when I started with sass I was getting 40sec  compiles in ruby / susy - (yeah that did get fixed.. eventually :( ) so I have a sense of relativity here. But even that was still SOME use. 

Conversely if Codepen folks knew that  was a dealbreaker or at least crippling the UX, then praps they might be motivated to improve performance?  Particularly as they're now focussed on Codepen as a project dev environment.

Otherwise.. Sassmeister? 

Or a zepto-esque  'foundation-lite'?  Would be a great nice to have in codepen in anycase - though I have no idea what could be dropped that would increase pen performance enough without breaking ecosystem.

**Comment by Shipwreck** [comment]
I have been writing semantically for a while now but still struggle with more complex arrangements. 

I agree the docs are very lacking when it comes to semantic explanations and examples, and find the forums are not very active. 

Where are people finding good examples of semantic grid markup?

**Comment by colin-marshall** [comment]
Thanks for this feature request. We’re going to close out this ticket, as we will not be adding more features to Version 6, but your request is being considered for Version 7.

**Comment by IamManchanda** [comment]
@Timoti Thank you for your time. As colin said, we will try to make it a top priority for F7 so this needs serious considerations!
