### ISSUE TITLE
[XY Grid] Unexpected wrapping issue.

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#10138]
Just setting a basic `.grid-x` revealed an unexpected behavior. 

Using this markup
```
<div class="grid-x margin-gutters">
  <div class="medium-auto cell">
    <img src="http://placehold.it/300" alt="" />
  </div>
  <div class="medium-auto cell">
    <img src="http://placehold.it/300" alt="" />
  </div>
  <div class="medium-auto cell">
    <img src="http://placehold.it/300" alt="" />
  </div>
</div>
```
Results in this
![5ydznka4ce](https://cloud.githubusercontent.com/assets/5652085/26770397/68caf20a-496b-11e7-8907-92926c947a90.gif)

But what is expected is 
![aowda3ez6s](https://cloud.githubusercontent.com/assets/5652085/26770432/ac52307e-496b-11e7-9603-99c0071d90a1.gif)

**Comment by brettsmason** [comment]
@rafibomb Can you try with padding gutters and see how that works? I'm going to hazard a guess its to do with margin and `calc()` use, but not sure without testing. I'll try and look this evening.

**Comment by rafibomb** [comment]
Ahh - could be.

Here is a pen https://codepen.io/rafibomb/pen/zzxPaB?editors=1100

padding or margin both work the same here

**Comment by brettsmason** [comment]
Here's a CodePen for this: https://codepen.io/brettsmason/pen/gRbXXK
Found the issue. The `.auto` classes are receiving the flex property: `flex: 1 1 auto` but they should have `flex: 1 1 0px`.

**Comment by rafibomb** [comment]
yes good catch! flex: 1 1 0;

**Comment by rafibomb** [comment]
Confirmed that's it by comparing to previous flex grid - do you want me to PR or you got it?
