### ISSUE TITLE
[Tabs] Missing documentation for required attributes

### ISSUE THREAD

**Issue by nladd** [zurb/foundation-sites#10147]
The F6 docs for tabs do not start that the data-tabs and id attributes are required on the element with the .tabs class not that the data-tabs-content attribute is required on the element with the .tabs-content class.

As written the documentation seem to imply the only thing necessary to use tabs is to apply the .tabs, .tabs-title, .tabs-content, and .tabs-panel classes but other attributes are required to get tabs to work properly. Documentation should be updated to include this additional information

#### Browser(s) and Device(s) tested on:
Opera 45.0

#### Test case link:
https://jsfiddle.net/tsdqa2my/

**Comment by andycochran** [comment]
Looks like the docs now mention this. 🎉
 
> Each content pane also has a unique ID, which is targeted by a link in the tabstrip.
