### ISSUE TITLE
Deeplinking to another accordion within an accordion on the page closes first accordion and doesn't close second

### ISSUE THREAD

**Issue by garrett-eclipse** [zurb/foundation-sites#10148]
#### How to reproduce this bug:

1. Create Two Accordions set-up for Deeplinking.
2. Within a content block on the first accordion add a deeplink to one of the second accordion items
3. Load Page
4. Open second accordion to a section other than the one that's deeplinked from the first.
4. Open first accordion to section with deeplink
5. Click deeplink
6. Note the first accordion will close, the second accordion will open to the deeplink section and scroll to, but the second accordion section you opened in step 4 will still be opened.

#### What should happen:

The first accordion should stay open and the second accordion should close before it scrolls to and opens the deeplink section within the second accordion.

#### What happened instead:

The first accordion closes and the second doesn't close and just opens the deeplink section so you end up with two sections open in the second accordion.

#### Browser(s) and Device(s) tested on:

Chrome on MacOSX

#### Test case link:

https://codepen.io/garrett-eclipse/pen/vZOpMP
NOTE: The foundation.js used in my codepen was stolen from this page (http://foundation.zurb.com/sites/docs/accordion.html) because deeplink accordion js was missed in the 6.3.1 bundle see #10096 for details on missing deeplink.

**Comment by garrett-eclipse** [comment]
To get Accordion Deeplinking to work when there's two accordions and the contents of the first deeplink into the second and vice versa I had to make the following changes;

1. Properly target the link,
Previous - `var $link = this.$element.find('[href$="'+anchor+'"]'),`
Fixed - `var $link = this.$element.find('.accordion-title[href$="'+anchor+'"]'),`
*This makes sure you are targeting the accordion title and not the actual deeplink.

2. Close the target accordion before opening deeplink section, added;
```
// Close the right accordion stuff
if (!this.options.multiExpand && !this.firstTimeInit) {
  var $activeSibling = $link.closest('[data-accordion]').find('.is-active').find('[data-tab-content]').not($anchor);
  if ($activeSibling.length) {
    this.up($activeSibling.not($anchor));
  }
}
```
*This needs to be placed within the `if ($link.length && $anchor) {` conditional before the code that triggers this.down to open the anchored/deeplinked section.

3. Scrollto section when link clicked without pageload. To do this I simply commented out the window.load function that wrapped the scrollTop animate.

4. Switch from _this.$element.offset to using $link.offset() so as to scroll to the right accordion section. If you had the deeplink to the second accordion in the first accordion it wouldn't scroll past the link down to the accordion section.
Previous - var offset = _this.$element.offset();
Should be - var offset = $link.offset();

5. The first account with link to second accordion in content kept closing and found it's an issue with the  down function and the targetting of $currentActive because it used this.$element it kept closing the accordion where the deeplink was and not the destination, changing from use of $element to using $target resolved this;
```
if (!this.options.multiExpand && !firstTime) {
  var $currentActive = $target.closest('[data-accordion]').find('.is-active').find('[data-tab-content]').not($target);
  if ($currentActive.length) {
    this.up($currentActive.not($target));
  }
}
```

I've created a gist of the entire foundation.accordion.js that I've modified here;
https://gist.github.com/garrett-eclipse/de2e312ff8cda86ad9eb93e18d5a3f13

Let me know if anything doesn't make sense or if I can help test/troubleshoot.

Cheers

**Comment by garrett-eclipse** [comment]
I had to do one final tweak to get the scrollto working onload as well as onpage. To do that I added a window.loaded check, if true just scrollto otherwise wrap the scrollto in a window.load.
Gist - https://gist.github.com/garrett-eclipse/de2e312ff8cda86ad9eb93e18d5a3f13

**Comment by kball** [comment]
@garrett-eclipse do you want to submit a PR with this change?

**Comment by garrett-eclipse** [comment]
Made another update to the Gist as it didn't support IE.
https://gist.github.com/garrett-eclipse/de2e312ff8cda86ad9eb93e18d5a3f13

I had grabbed the original source rather than the distribution code which goes through some gulp tasks to convert the classes to functions for IE support.

**Comment by andycochran** [comment]
@garrett-eclipse Could you create a pull request with your patch? It'd be great to get this into the next release.

**Comment by garrett-eclipse** [comment]
@andycochran I'll take a stab this month while I tackle a few other F7 items on my list. You can assign this to me

**Comment by DanielRuf** [comment]
PR: https://github.com/zurb/foundation-sites/pull/11686

Replaced by #11685
