### ISSUE TITLE
aria-expanded not accepatble with role="menuitem"

### ISSUE THREAD

**Issue by getvijayji** [zurb/foundation-sites#10158]
I am using foundation6 data-accordion-menu, and the accordion is working fine too. but it seems that foundation6 is injecting the ARIA attributes dynamically, where it is putting aria-expanded and role="menuitem" together in <li> elements which  isn’t allowed by the ARIA spec. Is there any fix for this. And also when i am putting the role="none" in my code, this is overridden when code gets rendered.

Please help.

here is the code generated

> <ul class="vertical menu" data-accordion-menu="cskdpg-accordion-menu" role="menu" aria-multiselectable="true">
	<ul class="vertical menu">
		<li role="menuitem">
			<a href="/store/guys/xxxx>Graphic Tees</a></li>
	</ul>
	<ul class="vertical menu">
		**<li role="menuitem" class="is-accordion-submenu-parent" aria-haspopup="true" aria-label="Short Sleeve Tees" aria-controls="m818zy-acc-menu" aria-expanded="false" id="78jn9n-acc-menu-link">**
			<a href="/store/guys/xxxx>Short Sleeve Tees</a>
			<ul class="vertical menu nested submenu is-accordion-submenu" data-submenu="" role="menu" aria-labelledby="78jn9n-acc-menu-link" aria-hidden="true" id="m818zy-acc-menu" style="display: none;">
				<li role="menuitem" class="level2Cat is-submenu-item is-accordion-submenu-item"><a href="/store/guys/xxxxx">View All</a></li>
				<li role="menuitem" class="level2Cat is-submenu-item is-accordion-submenu-item"><a href="/store/guys/xxxxx">Henley</a></li>
				<li role="menuitem" class="level2Cat is-submenu-item is-accordion-submenu-item"><a href="/store/guys/xxxxx">Crew Neck</a></li>
				<li role="menuitem" class="level2Cat is-submenu-item is-accordion-submenu-item"><a href="/store/guys/xxxxx">V-Neck</a></li>
			</ul>
		</li>
	</ul>
</ul>

>

**Comment by brettsmason** [comment]
@getvijayji thanks for reporting this. Can you let me know how this should be setup in order to pass?

**Comment by brettsmason** [comment]
@getvijayji Having looked at this again I can see its actually been fixed in the upcoming 6.4 release, see here: https://github.com/zurb/foundation-sites/pull/10064. I'm going to close this.

**Comment by getvijayji** [comment]
Thanks I got that info in other tag and the foundation site.
