### ISSUE TITLE
[Drilldown Menu] Missing infos for initializing a new Drilldown Menu 

### ISSUE THREAD

**Issue by Daniel-Wiedemann** [zurb/foundation-sites#10154]
In the documentation for the Drilldown Menu, in the section for initializing a new Drilldown Menu, there is missing a js library. To work alone, you have also to add the **foundation.util.box.js** plugin.

So you need:

foundation.core.js
foundation.util.keyboard.js
foundation.util.motion.js
foundation.util.nest.js
foundation.util.box.js
foundation.drilldown.js

#### How to reproduce this bug:

Follow the [instructions](http://foundation.zurb.com/sites/docs/drilldown-menu.html#javascript-reference) from the documentation to use only the Drilldown Menu.

#### What should happen:
The Drilldown Menu should work the same as on the documentationsite.

#### What happened instead:
The Drilldown Menu does not work.
It get´s a javascript error.
The Error:
> Uncaught TypeError: Cannot read property 'GetDimensions' of undefined at HTMLUListElement. 

#### Browser(s) and Device(s) tested on:
Tested on Chrome 58

#### Foundation Version(s) you are using:
Version 6.3.1

#### Test case link:
You can test it here: https://codepen.io/mediatrash/pen/VWvaNY
(Please ignore the style)
Just remove the **foundation.util.box.js** in the **Add External JavaScript** section to get the error.

**Comment by andycochran** [comment]
Looks like the docs now contain `foundation.util.box.js`. 🎉
