### ISSUE TITLE
PositionClass option is ignored by Dropdown 6.3.1

### ISSUE THREAD

**Issue by Lazerproof** [zurb/foundation-sites#10178]
'this.options.positionClass' is set to the value of _getPositionClass without checking for the prior existance of the option during init of Dropdown

#### How can we reproduce this bug?

1. Set the positionClass option
2. It has no effect

#### What did you expect to happen?
The position should respect the positionClass option

#### What happened instead?
The position is regexed from the classname instead

**Comment by andycochran** [comment]
Is this still an issue in 6.4.3?

**Comment by DanielRuf** [comment]
> DEPRECATED: Class applied to adjust open position.

https://github.com/zurb/foundation-sites/blob/477563de08ae39c69ebf40b87f10f871696956c4/js/foundation.dropdown.js#L371-376

**Comment by DanielRuf** [comment]
Closing as https://github.com/zurb/foundation-sites/pull/11038 is merged.
