### ISSUE TITLE
using foundation CLI build

### ISSUE THREAD

**Issue by thatvideowebguy** [zurb/foundation-sites#10177]
Hi, 
I'm using foundation to create a website and I'm new with the command line tool and functions.

For now I can Watch and compile all my files but I was wondering how at the end of the project I'll be able to Build (There's a function for that but nothing append, it's seems to have the same effect as Watch function) the project and get only the necessary files to upload on the production server.

Can you help me on this ?

Thanks

**Comment by IamManchanda** [comment]
Although this thread should be moved here 
https://github.com/zurb/foundation-zurb-template/

But you raised a very important question... current docs lack that!

**Comment by IamManchanda** [comment]
or wait 
http://foundation.zurb.com/sites/docs/starter-projects.html#zurb-template
> The biggest difference between this and the basic template is the folder structure. In the ZURB Template, your project has a `src/` folder which contains your source files, and a separate `dist/` folder with your finished website. As you work on your project, Gulp continuously updates your `dist/` folder with new versions of files. To compile a production build, run **`npm run build`.**

**Comment by IamManchanda** [comment]
BTW the heart of the matter is 
you should be using `npm run build` 

I hope your issue was resolved?

**Comment by DanielRuf** [comment]
What can we do better in the docs?

**Comment by DanielRuf** [comment]
Ping @IamManchanda

**Comment by DanielRuf** [comment]
The watch taks is for incremental builds while being in the development mode or a development environment.

@thatvideowebguy was your question answered and is now clear what each npm script and Gulp task does?

**Comment by DanielRuf** [comment]
@ncoden do you think that the initial question is answered or should we wait for feedback (if we get any)?
