### ISSUE TITLE
iOS: scroll to accordion li > a top on open

### ISSUE THREAD

**Issue by octlabs** [zurb/foundation-sites#10170]
We could see a very strange behavior with the event trigger down.zf.accordion under iOS:

The $target (called "event") does not provide the DOM element (LI), which is clicked by event.currentTarget.activeElement, but returns to the BODY.

    $(document).on('down.zf.accordion', function (event) {
      let $link = $(event.currentTarget.activeElement);
    
      // XXX we tried to fix this as follows:
      if (event.currentTarget.activeElement.tagName === 'BODY') {
        $link = $(event.target);
      }
    
      let top = $link.offset().top;
      let $menu_sticky_elements = $('[data-sticky]');
      $menu_sticky_elements.map((i, dom) => {
        top -= $(dom).outerHeight() * 1.5;
      });
      if (top > 0)
        $('html, body').animate({scrollTop: top}, 'slow');
    });

Have you noticed this before?

**Comment by andycochran** [comment]
Are you still seeing this in version 6.4.3?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback and have no codepen for testing this.
