### ISSUE TITLE
Orbit doesn't work in 6.4-RC3

### ISSUE THREAD

**Issue by tristant** [zurb/foundation-sites#10189]
#### How to reproduce this bug:

Copy Orbit example from the documentation

#### What should happen:

- You should be able to navigate back and forth through the slides
- Automatic slide should go through all images

#### What happened instead:

- Gets stuck on second slide
- Can't navigate back and forth

#### Browser(s) and Device(s) tested on:

Latest FF & Chrome

#### Foundation Version(s) you are using:

Foundation 6.4.0-rc3

#### Test case link:

https://codepen.io/anon/pen/QgKVGq

**Comment by IamManchanda** [comment]
Maybe we need to update docs example because codepen (edit in browser) example is working for 6.4 RC3 
https://codepen.io/IamManchanda/pen/rwMgxX?editors=1100

**Comment by IamManchanda** [comment]
Dang you forgot to add motion ui 
Here is working example ... i forked your codepen and just included motion ui from settings - css
https://codepen.io/IamManchanda/pen/BZLgQg

Closing this and marking this as resolved... Feel free to reopen/reply if you still having issues :)

**Comment by tristant** [comment]
Fair enough, but shouldn't it be included in the foundation.min.css ? 
The JS utility is included in the "Foundation everything" javascript file, I assumed it would be for the CSS too. 
If including it isn't a good idea, maybe put clearly in the documentation that one shouldn't expect the css to be included too, only the JS ?

**Comment by IamManchanda** [comment]
Fair enough doing it now! 
(Adding an alert on motion ui requirement)
