### ISSUE TITLE
.progress-meter should use $progress-radius instead of $global-radius

### ISSUE THREAD

**Issue by idolab** [zurb/foundation-sites#10184]
in _progress-bar.scss line22. Using $global-radius result in odd appearance of progress bar.

#### How to reproduce this bug:

1. Set $global-radius = 0
2. Set $progress-radius = .5rem
3. Make a progress bar on html

#### What should happen:
beautiful border-radius appears 

#### What happened instead:
odd square with round progress bar appeared

#### Browser(s) and Device(s) tested on:
Chrome

#### Foundation Version(s) you are using:
6.3.1

**Comment by rafibomb** [comment]
Sounds like it should be changed - can you submit a Pull Request for this and we'll merge it in
