### ISSUE TITLE
XY Grid - align-stretch has no effect with grid-margin-y

### ISSUE THREAD

**Issue by oxyc** [zurb/foundation-sites#10180]
#### How to reproduce this bug:

1. Create a horizontal grid with vertical margins: `grid-x grid-margin-y`.
2. Add `align-stretch`.

#### What should happen:

The cells height should stretch.

#### What happened instead:

The height is enforced to by `.grid-margin-y > .cell` and therefore do not stretch.

#### Browser(s) and Device(s) tested on:

Chrome

#### Foundation Version(s) you are using:

`develop`-branch

#### Test case link:

https://codepen.io/anon/pen/xrOMNP?editors=1100

Related: https://github.com/zurb/foundation-sites/pull/10157

> @brettmason One remaining issue that I can think of with this. The base .cell class is linked to .grid-margin-x/y - specifically their width/height whish is outputted at 100% (minus the margin). Could this cause issues in certain configurations?

<img width="1233" alt="screen shot 2017-06-13 at 11 53 51" src="https://user-images.githubusercontent.com/302736/27094250-178da624-502f-11e7-984b-3aeb84d0b899.png">

**Comment by IamManchanda** [comment]
See @brettsmason, that's why i said we need to integrate flex alignments with the grid ( #10117 )
This way we will get to know the bugs too!
