### ISSUE TITLE
Missing docs for old versions...

### ISSUE THREAD

**Issue by airtonix** [zurb/foundation-sites#10190]
Trying to find documentation for `6.2.3`. but you've deleted it.

Might I suggest that you leave documentation around not just for major versions `6.x.x` but also for minor versions `6.2.x`

technically speaking the `minor` in semver shouldn't change existing functionality. but looking through your changelog, there is quite a lot of functionality changed in existing modules withing a `minor` release. If I were to update to 6.3, I'd be facing hundreds of hours of work to fix things your new changes breaks.

From a agency point of view time is money and using new features means upgrading to new versions of foundation, we don't want to be facing the horrifying task where large teams are involved that we might break existing features based on modules you've changed the behaviour of (equalised heights has a opt out feature change between 6.2 and 6.3).

anyway. tl;dr keep documentation around for both major and minor releases... and provide links to those versioned documentation.

**Comment by IamManchanda** [comment]
I think this is a very valid point and we should start from now 
Aka 6.3-6.4 ( if possible other 6.x also) 
cc @kball

**Comment by kball** [comment]
👍  will put this together as a part of packaging up 6.4... we will definitely have 6.3 and 6.4 versions, but I'll see if I can get a 6.2 version as well.

**Comment by IamManchanda** [comment]
Great @kball...

**Comment by sirianni** [comment]
> we will definitely have 6.3 and 6.4 versions

Where are the `6.3` version of the docs?  I've spent an hour searching and can't find them...

**Comment by webuxr** [comment]
I too have been looking for 6.3.1 doc pages. Gave up, installed a vanilla copy of F6.3.1, built my own docs locally. Quite the PITA but it worked.

Looking forward to seeing a permanent home for 6.3.x and 6.4.x documentation.

Even better if this permanent home for these doc sites be accessible via Zurb’s current doc site (via the/a version select list).

**Comment by ncoden** [comment]
Closing this in favor of https://github.com/zurb/foundation-sites/issues/10190

Also @airtonix, I fully agree with you about semver. I pushed in this direction one year ago in https://github.com/zurb/foundation-sites/issues/9576, and we are now taking care of the changes we are releasing in patch versions.

There is two versions planned for now:
`v6.4.4` should contains only non-breaking bug fixes.
`v6.5.0` should contains all new features and breaking changes (without too much work needed to upgrade).

**Comment by jimbobger** [comment]
End of 2018 and still no docs of the older Foundation 6 versions available -very frustrating and not very future-proof for the comming versions.

**Comment by DanielRuf** [comment]
@jimbobger  It's discussed in https://github.com/zurb/foundation-sites/issues/9512

Any help is very welcome.

**Comment by calebkeene** [comment]
Any resolution on this? I'm still trying to find docs for 6.2.3 in the hope that i"m not going to have to undertake a full upgrade to 6.5...

**Comment by DanielRuf** [comment]
Hi @calebkeene, you can use Dash by Kapeli or Zeal to get the old docs.

**Comment by nivred** [comment]
Zeal doesn't carry older versions of Foundation. I work for a large and highly recognized corporation that relies on v6.3.1 and v6.4.2. Can someone please provide a link to reliable documentation for these.

**Comment by DanielRuf** [comment]
> Zeal doesn't carry older versions of Foundation. I work for a large and highly recognized corporation that relies on v6.3.1 and v6.4.2. Can someone please provide a link to reliable documentation for these.

Zeal has many old versions of Foundation Sites. Which exact version do you need?

**Comment by DanielRuf** [comment]
v6.3.1: https://kapeli.com/feeds/zzz/versions/Foundation/6.3.1/Foundation.tgz
v6.4.2: https://kapeli.com/feeds/zzz/versions/Foundation/6.4.2/Foundation.tgz

All available versions:

https://github.com/Kapeli/feeds/blob/master/Foundation.xml

**Comment by maurusrv** [comment]
I was able to find the docs for `6.1.1` by the example links @DanielRuf provided.

Thank you!

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/sticky-bottom-for-foundation-6-3-1/4029/2

**Comment by mveenstra** [comment]
Hello! Looking for F6.4.3 documentation. Dash is not available for windows. Is there another option to access older documentation? Thank you!
