### ISSUE TITLE
button-background-hover should use smart-scale by default

### ISSUE THREAD

**Issue by oxyc** [zurb/foundation-sites#10198]
#### How to reproduce this bug:

1. Set `$button-background: #000`

#### What should happen:

The hover effect should increase the lightness of the background.

#### What happened instead:

The hover effect decreases the lightness.

#### Foundation Version(s) you are using:

`develop`-branch

**Comment by andycochran** [comment]
Absolute black buttons are an edge case. But you're right, the color change of the button background should be easily configurable. Let's make sure we do this right in v7.

**Comment by oxyc** [comment]
Fix would be to use `smart-scale()` rather than `scale-color()` directly.

**Comment by andycochran** [comment]
I considered reopening this, 'cause you're right — `smart-scale()` _would_ enable all button colors to have a hover effect. But wouldn't this make a hard-coded assumption about whether the hover effect is darker or lighter. As is, the hover effect is configureable, which I think is better. I might want relatively dark buttons to be even darker on hover. For v7, maybe we add the ability to pass a lighter or darker hover to the button mixin.

**Comment by oxyc** [comment]
True, unless the default `$button-background-hover` was set to `auto` and this line used `smart-scale()` instead of `scale-color()`.

https://github.com/zurb/foundation-sites/blob/7f2d2079391a9897950b1cf461e1669dc51dc1a3/scss/components/_button.scss#L196-L198

**Comment by andycochran** [comment]
It's possible to change `$button-background-hover` in your `_settings.sass` to use `smart-scale()`, which would allow you to use `$button-palette` how you like. But this is great feedback, so lets be sure to get this right in v7.

**Comment by oxyc** [comment]
> It's possible to change $button-background-hover in your _settings.sass to use smart-scale(), which would allow you to use $button-palette how you like

It would for the default button style, but not for the styles in `$button-palette`.

Currently foundation iterates over the palette and applies the `button-fill-style()` mixin with `$background-hover` hardcoded as auto.

```scss
        @each $name, $color in $button-palette {
          &.#{$name} {
            @include button-fill-style($filling, $color, auto, auto);
          }
        }
```

When `$background-hover` is set to `auto` it defaults to a hardcoded `scale-color()` value.

```scss
  @if $background-hover == auto {
    $background-hover: scale-color($background, $lightness: $background-hover-lightness);
  }
```
