### ISSUE TITLE
XY Grid - grid-margin-x on parent row overrides children

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#10194]
.grid-margin-x on .row is applying negative margin even when not nested.

Example pen https://codepen.io/rafibomb/pen/QgGBPE?editors=1000
See that there are no outer margins on content cells.

Issue here:
<img width="1118" alt="screen shot 2017-06-16 at 9 13 10 am" src="https://user-images.githubusercontent.com/5652085/27214447-2f500732-5275-11e7-8e48-d6c151713ebf.png">

**Comment by rafibomb** [comment]
@brettsmason @kball This fixes it but There is for sure a better way to do it https://github.com/zurb/foundation-sites/issues/10194

**Comment by brettsmason** [comment]
@rafibomb Sorry I dont' understand.

Is your issue that there is a negative margin on `.grid-x` and so is no left/right margin on the end cells? If that's the case then that is the correct behaviour. Margin grids aren't the same as padding grids - they should align flush. If you wanted a space either side then adding padding to the grid would be the correct approach.

See [this comment](https://github.com/zurb/foundation-sites/issues/10141#issuecomment-308300758) and the following discussion about this.

**Comment by brettsmason** [comment]
@rafibomb Sorry re-read it and checked the CodePen again and see the problem. However this isn't a problem with the `develop` branch, so is likely something that's been fixed since RC3.

**Comment by brettsmason** [comment]
@rafibomb I've checked with your example in the develop branch and it works correctly so going to close this.
