### ISSUE TITLE
[Drilldown Menu] not working at all in 6.4

### ISSUE THREAD

**Issue by aaronjpitts** [zurb/foundation-sites#10203]
http://foundation.zurb.com/sites/6.4.0-rc/docs/drilldown-menu.html drilldown is not working at all in 6.4.

**Comment by IamManchanda** [comment]
Thanks @aaronjpitts ... i dont know when it happened... Quite sure this was not with the first drilldown menu release ... Let me check

**Comment by Divine1** [comment]
is this drilldown issue fixed? i tried a **drill down** example program from foundation documentation page. it is not working
