### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import at line import $ from 'jquery';

### ISSUE THREAD

**Issue by jashwant** [zurb/foundation-sites#10202]
I was including few javascript plugins of `foundation 6.3` in my website with my custom gulp, I have setup for my website.

Since, I need not to support ie 9 anymore, I updated foundation to `6.4.0-rc3`.

Now, page is throwing error `Uncaught SyntaxError: Unexpected token import` at line  `import $ from 'jquery';`

Is it because of the new webpack build system ?

Is there anyway to fix this with gulp. I really do not want to spend time learning webpack.

Also, I see that 'flex-grid' has a 'legacy' tag in docs. 

Does it mean that it won't be supported / updated in future ?

`x-y grid` does not suite my requirements and I would love to stick to flex-grid , if it won't be ditched soon.

**Comment by kball** [comment]
HI @jashwant Can you clarify how you're building & importing? From the error it looks like you're probably not using babel... probably the simplest if you're not needing the module imports is just to simply drop in the compiled JS from `dist`...

Can you paste your gulpfile so I can take a look?

On flex grid, it will be supported through the 6.X series but not continued through in Foundation 7. Can you explain a little more about how the XY Grid falls short for you?  Our intent was to handle every case the previous grids handled

**Comment by jashwant** [comment]
Updating to 6.4.0-rc2 and using `webpack` and `webpack-stream` ( like foundation-zurb-template-6.4 ), fixed the issue.

About flex grid, transition was easier from float to flex grid.  There was no need to change class names.

Also, it appears to me that x-y grid has more css rules than flex grid and also x-y grid seems complex to maintain. I do not need `y-grid` and `margin-grid` ( though I see that it is easier to turn those off in sass ), so was considering flex-grid. 

But if it won't be supported in foundation 7, I'll use x-y grid instead.

**Comment by brettsmason** [comment]
@jashwant Yeah I wrote the main Sass mixin so that elements could be easily included or not, as like you I dont need `grid-y` for most projects. 

Long term it should be far better than the current flex grid, promise 😄

If you want to mimic the current flex grid, all you need is `.grid-x`, `.grid-padding-x` and `.grid-container` and you should be good to go. It may seem more complex, but I think you will find its actually less code than the current flex grid if you only need a few elements.
