### ISSUE TITLE
Issue with Magellan scroll bar on small screen

### ISSUE THREAD

**Issue by taiinaa** [zurb/foundation-sites#10210]
I currently have a fixed magellan nav menu, however when viewing the page on a smaller screen, I can't scroll through my nav menu's content. Is there a way to implement an overflow: scroll or something similar?

**Comment by brettsmason** [comment]
@taiinaa Sorry for the delay in a response on this.
Are you able to put together a CodePen with your issue then maybe we can try and help a bit more.

**Comment by IamManchanda** [comment]
@taiinaa We are awaiting your reply? Does this issue still exists ... Please let us know!
