### ISSUE TITLE
Link to building blocks tutorials are broken

### ISSUE THREAD

**Issue by davestyp** [zurb/foundation-sites#10215]
Where is this tutorial slash building block?
http://zurb.com/building-blocks/top-bar-with-off-canvas

Referenced here from official source:
http://foundation.zurb.com/sites/docs/off-canvas.html

This is probaly the case with all links to building blocks since it was redone but I'm primarily most interested in that one right now :)

**Comment by IamManchanda** [comment]
Though i am not sure but this might help you 
http://foundation.zurb.com/building-blocks/blocks/multilevel-offcanvas-menu.html

**Comment by davestyp** [comment]
@IamManchanda That's a real nice menu, thanks!

**Comment by IamManchanda** [comment]
@davestyp I am glad i could help ... Closing this 

but also poke @kball .... is there any way those old building blocks can still be used/redirected ??
(though i was not around at that time or have any idea so i dont know the full matter)

**Comment by kball** [comment]
We can definitely redirect and/or port them.... in fact I think @rafibomb was going back through and porting some.  If you notice more missing items like this maybe open that on the BB repo?
