### ISSUE TITLE
foundation 6 Off Canvas and it's Links not working as expected on Samsung Galaxy Tab 3

### ISSUE THREAD

**Issue by getvijayji** [zurb/foundation-sites#10213]
I see issues on this device with mega menu/Hamburger menu, Zoom page, Click event etc issue in the whole site. 

Need your help in resolving or a solution for the current problem that we are facing, we have used the foundation 6 offcanvas and it seems to be not working on samsung tab 3, and links are not working..

It works on all other devices except samsung tab 3... Looking forward to your support.. 

Also adding the specification below of the tablet Samsung Galaxy Tab 3 7.0
Dimensions 188 x 111.1 x 9.9 mm (7.40 x 4.37 x 0.39 in)
Size 7.0 inches (~66.0% screen-to-body ratio)
Resolution 600 x 1024 pixels (~170 ppi pixel density)

Tried to look on the page http://foundation.zurb.com/sites.html also and it also has same issues on Tab 3.

Thanks.

**Comment by brettsmason** [comment]
@getvijayji Is this purely for the link you mentioned, or also on the docs? http://foundation.zurb.com/sites/docs/off-canvas.html

What about off canvas isn't working? Can you be more specific?

**Comment by andycochran** [comment]
Tested this in BrowserStack `os=android&os_version=4.4&device=Samsung+Galaxy+Tab+4&device_browser=chrome` and Off-canvas and its links seem to work fine. Closing.
