### ISSUE TITLE
[6.4 RC] Accordion menu getting unwanted styling in develop branch

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10218]
![menu-getting-styling](https://user-images.githubusercontent.com/4970624/27348267-121730d8-5611-11e7-9ed8-8c0eab5acfed.png)

**Comment by brettsmason** [comment]
@IamManchanda This is actually tied to the submenu toggle that I and others introduced in a PR. This is tied to the `.accordion-menu` class, which is added and removed using the responsive menu plugin. If using an accordion menu by itself then its not needed if that makes sense.

This was all to do with the styling for the submenu toggle: https://github.com/zurb/foundation-sites/pull/9348

Cant remember details now as it was a while ago.

**Comment by IamManchanda** [comment]
Its coming from here ( this should be null by default )
https://github.com/zurb/foundation-sites/blob/develop/scss/components/_accordion-menu.scss#L29-L31

Its getting called here BTW 
https://github.com/zurb/foundation-sites/blob/develop/scss/components/_accordion-menu.scss#L76-L88
