### ISSUE TITLE
Incorrect usage for the Cite element

### ISSUE THREAD

**Issue by glennphilp** [zurb/foundation-sites#10226]
#### How to reproduce this bug:

When using a blockquote or q element the developer should include a cite attribute or cite element. However, the current usage for [cite](http://foundation.zurb.com/sites/docs/typography-base.html#blockquotes) by Foundation is incorrect.

#### What should happen:

According to: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite) and [HTML 5 Doctor](http://html5doctor.com/element-index/#cite) the cite should be:

> A creative work may include a book, a paper, an essay, a poem, a score, a song, a script, a film, a TV show, a game, a sculpture, a painting, a theater production, a play, an opera, a musical, an exhibition, a legal case report, a computer program, a web site, a web page, a blog post or comment, a forum post or comment, a tweet, a written or oral statement, etc.

#### What happened instead:

Foundation is currently using a person's name.

#### Recommendation for fixing issue:

Person name:
`<span class="cite">Person Name</span>`
Citing a piece of work:
`<cite>[Book Title|Movie Title...]</cite>`

**Comment by AndrewKvalheim** [comment]
Seems consistent with the [specification][]; its first example is:

```html
<p>In the words of <cite>Charles Bukowski</cite> -  
<q>An intellectual says a simple thing in a hard way. An artist says a hard thing in a simple way.</q></p>
```

Presumably the person's name serves as a proxy to the "written or oral statement" being cited.

---

That example highlights another issue, though. Foundation naively styles all citations as blocks, interfering with simple inline usage. That behavior should probably be scoped to block quotes.

[specification]: https://www.w3.org/TR/html5/text-level-semantics.html#the-cite-element

**Comment by kball** [comment]
I think @AndrewKvalheim you are probably correct that cite should probably not be a block element. Looking to see when that was introduced, it appears to have been pulled over from Foundation 5.  Wonder if any of @brettsmason @gakimball @andycochran or other old guard folks know why that was the case, or have opinions on this subject?

**Comment by plweil** [comment]
+1!

"That example highlights another issue, though. Foundation naively styles all citations as blocks, interfering with simple inline usage. That behavior should probably be scoped to block quotes."

**Comment by glennphilp** [comment]
Although the W3C shows examples of using a person's name, they contradict themselves in the opening two statements.

> The cite element represents a reference to a **creative work**. It must include the title of the work or the name of the author(person, people or organization) or an URL reference, which may be in an abbreviated form as per the conventions used for the addition of citation metadata.

They then explain what a creative work is, which does not include a person.
> **Creative works** include a book, a paper, an essay, a poem, a score, a song, a script, a film, a TV show, a game, a sculpture, a painting, a theatre production, a play, an opera, a musical, an exhibition, a legal case report, a website, a web page, a blog post or comment, a forum post or comment, a tweet, a written or oral statement, etc.

And then with more research, I came across "[Examples of block quote metadata](http://oli.jp/example/blockquote-metadata/)" which bases its structure on the Chicago Manual of Style. Also using HTML5Doctor.com [cite reference](http://html5doctor.com/element-index/#cite) it states as the W3C does about what is Creative Works.

My suggestion is Foundation should just remove the styling on the cite element allowing the user to style how he/she see's fit. This would allow anyone to use it in the manner they desire, without doing the dreaded overwrites.

**Comment by AndrewKvalheim** [comment]
What about that "or the name of the author" part?

**Comment by glennphilp** [comment]
@AndrewKvalheim that is why I stated the W3C contradicted themselves. They say "the cite element represents a reference to a creative work", in the first sentence after the data. Then the very next sentence they define what is **creative work**. Which does _NOT_ include an author or person name.

**Comment by andycochran** [comment]
I'm going to close this. But let's definitely consider all this input for v7.
