### ISSUE TITLE
Version 6.3.1 on NPM doesn't match up with version tagged 6.3.1 on GitHub

### ISSUE THREAD

**Issue by scoland** [zurb/foundation-sites#10223]
When installing version 6.3.1 of foundation-sites from NPM I'd expect to get the codebase from the version of foundation-sites on GitHub tagged 6.3.1 (https://github.com/zurb/foundation-sites/tree/6.3.1), yet the two codebases are different.

As an example, I'm trying to use the deep linking accordion functionality added in the following PR [#9664](https://github.com/zurb/foundation-sites/pull/9664).

Yet, if I `npm install foundation-sites@6.3.1` and view the file `foundation-sites/js/foundation.accordion.js`, there is no `_checkDeepLink` function.

If I navigate to the [same file](https://github.com/zurb/foundation-sites/blob/6.3.1/js/foundation.accordion.js) in the release tagged 6.3.1 on GitHub the function is indeed there.

Is this a mistake? Or am I misunderstanding how versioning/releases work between github and npm? I'm on NPM5 if it makes any difference.

**Comment by kball** [comment]
@scoland it looks like there is an issue and mistake - we're about to be releasing 6.4.0, and will follow up quickly with a 6.3.2 patch release with the bugfixes, so hopefully that will resolve.

**Comment by natewiebe13** [comment]
@scoland, @kball, we are experiencing this as well. It is due to having a `6.3.1` tag and a `v6.3.1` tag. For now, we are referencing commit `fc578179ab1718c18216f88b2ff5b04c70532d53`. @kball, can this not just be resolved by removing the incorrect tag, or would this cause more issues?

**Comment by kball** [comment]
@natewiebe13 that will not resolve it for npm unfortunately, but we should resolve this very soon. 6.4.0 coming out TOMORROW and should be able to get 6.3.2 out pretty quickly following that

**Comment by andycochran** [comment]
Closing this. As kball mentions, it should be resolved with the new version(s). Please reopen if you're still experiencing this issue.
