### ISSUE TITLE
Accordion Menu in Off-Canvas v6.4.0 RC4 - Submenu flashes menu items inline

### ISSUE THREAD

**Issue by tsquez** [zurb/foundation-sites#10220]
I added the new v6.4.0 RC4 release, which corrected a lot of issues and I did add the accordion menu menu to the Off-Canvas Menu.

However when you look at it mobile, the sub menu items flash inline before display properly. Hope that makes sense.

If you like I uploaded the v6.4.0 RC4 WP-Forge to its site. You can view it here https://themeawesome.com/themes/wpforge/ (switch to mobile view) and you will see what I mean.

What do you think it is?

**Comment by brettsmason** [comment]
@tsquez This is down to this issue: https://github.com/zurb/foundation-sites/issues/10150
I'll put a PR together really quickly to address this so it gets included in 6.4 final.

**Comment by tsquez** [comment]
Sorry about that...I checked if an issue existed and didn't see anything.
