### ISSUE TITLE
Close button doesn't work in 6.4.0-rc3 

### ISSUE THREAD

**Issue by canterberrie** [zurb/foundation-sites#10227]
#### How to reproduce this bug:

Copy Close Button example from docs, or try to close the examples from the docs: http://foundation.zurb.com/sites/6.4.0-rc/docs/close-button.html

#### What should happen:

Callout should close when I click on the close button

#### What happened instead:

Nothing

#### Browser(s) and Device(s) tested on:

Firefox & Chrome

#### Foundation Version(s) you are using:

Foundation 6.4.0-rc3

#### Test case link:

https://codepen.io/canterberrie/pen/WOOjVZ

**Comment by IamManchanda** [comment]
@canterberrie i think by mistake you added a wong codepen :)

**Comment by canterberrie** [comment]
@IamManchanda Whoops, I was using another codepen that had the 6.4 as a template and forgot to save :P it's updated.
