### ISSUE TITLE
Forget put rem in line 1666

### ISSUE THREAD

**Issue by netobr05** [zurb/foundation-sites#10225]
.menu > li > a {
    display: block;
    padding: 0.7rem 1rem;
    line-height: 1;
}

**Comment by IamManchanda** [comment]
@netobr05 can you be more brief 
i mean the version you are using and whats missing ??

**Comment by netobr05** [comment]
Hi

/**
 * Foundation for Sites by ZURB
 * Version 6.3.1
 * foundation.zurb.com
 * Licensed under MIT Open Source
 */

Line: 1666

.menu > li > a {
    display: block;
    padding: 0.7rem 1rem;
    line-height: 1; }

**Comment by netobr05** [comment]
Hi

/**
 * Foundation for Sites by ZURB
 * Version 6.3.1
 * foundation.zurb.com <http://foundation.zurb.com/>
 * Licensed under MIT Open Source
 */

Line: 1666

.menu > li > a {
    display: block;
    padding: 0.7rem 1rem;
    line-height: 1; } 

// forget rem ->  line-height: 1rem;

**Comment by netobr05** [comment]
Forget... sorry my mistake.
