### ISSUE TITLE
Sticky doesn't work correctly if used within an iframe in Firefox

### ISSUE THREAD

**Issue by Harti** [zurb/foundation-sites#10238]
#### How to reproduce this bug:

1. Use Mozilla Firefox
2. Use the Sticky plugin within an iframe that's `display:none`
3. `_setSizes `will throw an exception because `window.getComputedStyle()` returns null.

#### What should happen:
The sticky plugin should work within the iframe

#### What happened instead:
Media queries plugin is messed up and displays smallest breakpoint for the stickied element.

An error is thrown:
> TypeError: comp is null 
>	_setSizes 
>	_init/< 
>	d 
>	dispatch 
>	add/r.handle

``` 
newElemWidth = this.$container[0].getBoundingClientRect().width,
            comp = window.getComputedStyle(this.$container[0]),
            pdngl = parseInt(comp['padding-left'], 10),
            pdngr = parseInt(comp['padding-right'], 10);
```

This bug is related to [this known Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=548397).

#### Browser(s) and Device(s) tested on:
Firefox 53

#### Foundation Version(s) you are using:
6.3.1

#### Test case link:
[CodePen](https://codepen.io/anon/pen/YQxxmj) - don't mind the iframe reveal link not working, all you need to do is open the console.
I noticed this bug on a local developer build using OctoberCMS in combination with the Page Preview plugin which opens up an iframe modal via AJAX that you can resize.

**Comment by DanielRuf** [comment]
Closing as this is a browser bug. And it's probably fixed now.
