### ISSUE TITLE
[Drilldown Menu] Buggy(Not Broken) - Blue outline while open/close in MAC Safari

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10231]
https://drive.google.com/file/d/0B4EN5uGMUjoZZ2ZrbHA0SFpKRTg/view
https://drive.google.com/file/d/0B4EN5uGMUjoZVmhuV2xRYUg1Rm8/view

Is this a bug... I am not sure ??
If yes can we solve this @kball / anyone ??

**Comment by IamManchanda** [comment]
Please note that this is related to safari ... i just now tested in chrome and it works!

**Comment by brettsmason** [comment]
I'm not sure I can see what you are talking about? The Blue outline?
I notice a lot of outlines on components but I'm not sure they should be there or not.

**Comment by IamManchanda** [comment]
Why only on safari and not in chrome etc for mac ,,, This makes me think though ??

PS: Even i am not sure that this is a bug or not :stuck_out_tongue_winking_eye:

**Comment by IamManchanda** [comment]
Please note that i have not mentioned this in the **QA** as more or so a Browser Reset Issue!

**Comment by kball** [comment]
Interesting... I don't see this on safari 9 either, so it's pretty browser specific... and I just verified the current 6.3.1 has the same behavior for safari 10, so this is a browser reset issue, but not a regression so I think it can slip out past release

**Comment by DanielRuf** [comment]
Do you mean `outline` or `-webkit-tap-highlight-color`?

**Comment by DanielRuf** [comment]
We need more info here. The screenshots from the initial comment are not accessible anymore.

**Comment by DanielRuf** [comment]
Closing as not relevant anymore. Safari 12.1 is the lates version and the information is not accessible anymore.
