### ISSUE TITLE
[XY-Grid] responsive auto classes do not evenly distribute the space.

### ISSUE THREAD

**Issue by oxyc** [zurb/foundation-sites#10244]
#### How to reproduce this bug:

1. Create a `grid-x`
2. Add 2 cells, both with `large-auto` classes.
3. Add varying content to the cells.

#### What should happen:

They should split 50/50 just like `auto` does.

#### What happened instead:

The cell with longer content takes up more space than the other.

#### Browser(s) and Device(s) tested on:

Chrome 59

#### Foundation Version(s) you are using:

v6.4.0-rc5

#### Test case link:

https://codepen.io/anon/pen/pwrXmx?editors=1000

Related to https://github.com/zurb/foundation-sites/pull/10222

**Comment by oxyc** [comment]
Added another bug where `auto` overrides any cell count specified on a larger breakpoint. Meaning you can't do `cell medium-auto large-4`. I'm guessing this is related.

**Comment by IamManchanda** [comment]
Oh dang this Bug fix https://github.com/zurb/foundation-sites/pull/10222/files
created a bug!

==> https://drive.google.com/file/d/0B4EN5uGMUjoZWlNEeTNDdHE1T28/view

**Comment by kball** [comment]
Bother... so it looks like the situation is that the `:not` values from #10222 are actually adding specificity, which makes that fix far less useful. I believe we were operating under the assumption that they would not do that. Need to dig into alternatives.
