### ISSUE TITLE
New Mastercard cards do not pass validation of the Abide plugin

### ISSUE THREAD

**Issue by slepets-a** [zurb/foundation-sites#10240]
Hey, guys.
Mastercard had released new cards starting with 2. Current regex don't let them pass ATM.

Place to fix -> https://github.com/zurb/foundation-sites/blob/develop/js/foundation.abide.js#L538

Thanks.

**Comment by kball** [comment]
Thanks for the report @slepets-a! Would you like to submit a PR to fix?

**Comment by slepets-a** [comment]
@kball Yeah, sure

**Comment by IamManchanda** [comment]
I think this regex fix not only should be 6.3.2 and 6.4
But also this should be documented a fix for earlier versions

**Comment by slepets-a** [comment]
I hope I did it right. I'm not sure about ?: at the start of the group. I've tried to figure this out, but it didn't help.
Online regex tester helps me with understanding that "?:" must be added.
