### ISSUE TITLE
[Menu] IE9 - Responsive menu not working - float grid - Fully Broken!

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10249]
Visit http://localhost:3000/menu/responsive-menu-float.html
( Visual Testing )

**Comment by broros** [comment]
This is just pissing me off....


![screen shot 2017-06-25 at 1 30 54 am](https://user-images.githubusercontent.com/598228/27514686-624c5712-5946-11e7-9662-93ba9aaedeec.png)

**Comment by IamManchanda** [comment]
**@broros This is unrelated to the issue i mentioned after the cross browser testing we are having for the tuesday release for 6.4.**

But i would like to help you 
It Seems like (from the url) that you are using an old version of foundation
Can you download the latest release => https://github.com/zurb/foundation-sites/releases
and let us know if the issue still exists and which browser ??

**Comment by Vuurvlieg** [comment]
Who cares about IE9 anyway

**Comment by IamManchanda** [comment]
I also now don't care with browser usage being frankly zero, but the thing is we need to keep it till 6 

Legacy Float Grid (and even legacy flex grid) will be removed in F7
That being said @kball... Can't we have a dep notice now and remove it in 6.5?

**Comment by broros** [comment]
I am using version 6.3.1, I think this is the latest version, I also downloaded the flex grid option.

**Comment by IamManchanda** [comment]
@broros Yup the top bar issue https://github.com/zurb/foundation-sites/issues/9871

I [fixed](https://github.com/zurb/foundation-sites/pull/10056) this actually, it mainly a wrong flexbox example of a top bar. The html for flex version of a top bar is this => https://codepen.io/IamManchanda/pen/OmBVZE?editors=1100

**Comment by rafibomb** [comment]
This issue is about this problem:
![screen shot 2017-06-26 at 10 17 44 am](https://user-images.githubusercontent.com/5652085/27551567-c8f622c8-5a58-11e7-9a19-cf3d0d197448.png)

The sub-menu items are not hidden by default nor vertical.

**Comment by IamManchanda** [comment]
Yup! @rafibomb ... sorry for not having a screenshot ... i forgot :disappointed:

**Comment by rafibomb** [comment]
Looks like it's not a CSS issue as both Flex and Float version have similar issue. There was some recent work to update this plugin and could have been introduced there: https://github.com/zurb/foundation-sites/commit/d9b2a5cbf242d68ca3165c8878c99c7a5f32db18

@kball can you take a look?

**Comment by IamManchanda** [comment]
Just for the records : I didnt check flex grid and marked it as **N/A** on QA as flex version doesnt support IE 9!

**Comment by rafibomb** [comment]
yeah - what I'm trying to do is locate the issue - since the js is not hiding the submenus it is a JS issue
