### ISSUE TITLE
var_dump with xdebug won't show the result

### ISSUE THREAD

**Issue by overlapjho** [zurb/foundation-sites#10243]
#### How to reproduce this bug:

1. After you create a simple layout 
2. use var_dump() inside <html>
3. inspect element on the blank space area

#### What should happen:

it should show the result of the var_dump

#### What happened instead:

created a blank wide space

#### Browser(s) and Device(s) tested on:

pc, google chrome, firefox

#### Foundation Version(s) you are using:

foundation 5

**Comment by Deckluhm** [comment]
[`var_dump()`](http://php.net/manual/en/function.var-dump.php) being a server side function, I don't see how this can be a Foundation bug?

Or maybe I'm missing something.

**Comment by overlapjho** [comment]
it might not be a bug directed to the foundation but it is incovenient to use var_dump with foundation because it wont show the result unless the default value for overflow css of <pre> is visible

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 24, 2017 at 3:43 PM, Arnaud Thomas Desessarts<notifications@github.com> wrote:   
var_dump() being a server side function, I don't see how this can be a Foundation bug?

Or maybe I'm missing something.

**Comment by IamManchanda** [comment]
@overlapjho ... can you send some code (maybe a zip or a github repo).... maybe i would be able to help you!

**Comment by DanielRuf** [comment]
We do not support Foundation Sites 5 anymore and `var_dump` normally just outputs plain text without any tags.

I'm closing this issue.

Feel free to reopen if you have more info for us (your `var_dump` implementation) and if the issue still exists in Foundation Sites 6.
