### ISSUE TITLE
[Forms] Unnecessary background color on <legend>?

### ISSUE THREAD

**Issue by Odaeus** [zurb/foundation-sites#10254]
A styled `fieldset > legend` element currently [has the background color set to `$body-background`](https://github.com/zurb/foundation-sites/blob/develop/scss/forms/_fieldset.scss#L35). This is confusing as I don't expect a legend to pick up the page background colour. The form may be in an area with a different background colour, for example.

#### How to reproduce this bug:

1. Add a `<div>`
2. Inside the `div` add `<fieldset class="fieldset"><legend>Test</legend></fieldset>`
3. Change the background colour of the div.

#### What should happen:

Background colour of legend should be "none".

#### What happened instead:

Background colour is the same as body background colour.

#### Browser(s) and Device(s) tested on:

Chrome 59, Safari 10.1.1

#### Foundation Version(s) you are using:

6.3.1

#### Test case link:

https://codepen.io/Odaeus/pen/QgqzGB

**Comment by rafibomb** [comment]
Makes sense since padding is creating the spacing that background can be set to none. Are yo able to submit a PR for it?

**Comment by Odaeus** [comment]
@rafibomb will do! :)

**Comment by rafibomb** [comment]
Awesome! I'll look for it then we'll merge it in!
