### ISSUE TITLE
6.4.0 mixin xy-cell-breakpoints gone?

### ISSUE THREAD

**Issue by Moonbase59** [zurb/foundation-sites#10276]
I’m about to try the xy-grid for a new site, using semantic HTML and as few "presentation classes" as possible. Meaning, I try to pack most of it into the CSS using SASS.

A few days ago, I could find (and was happy about) a mixin "xy-cell-breakpoints" in the docs (http://foundation.zurb.com/sites/docs/xy-grid.html#responsive-grids), but it seems to have gone:

```bash
Error in plugin 'sass'
Message:
    src/assets/scss/gridtest.scss
Error: no mixin named xy-cell-breakpoints

       Backtrace:
       	src/assets/scss/gridtest.scss:38
        on line 38 of src/assets/scss/gridtest.scss
>>   @include xy-cell-breakpoints((small: full, medium: 9));
   -----------^
```

What’s the status of this one?

Just asking because I feel we tend to get lazy, by including all these fancy Foundation classes in the HTML markup and thus effectively mix up content and presentation again.

Personally, I’d very much prefer "simple" semantic HTML5 like
```html
<header class="pageheader">
  <nav>
  </nav>
</header>

<main>
  <article class="article">
  </article>
</main>

<aside class="aside">
  <section class="aside__section">
  </section>
</aside>

<footer id="pagefooter" class="pagefooter">
  <section class="pagefooter__section">
  </section>
</footer>
```

and then do the main part in SASS, more or less like

```sass
body {
  @include xy-grid-container(1200);
}

/* PAGE HEADER */
header.pageheader {
  background-color: red;
  @include xy-grid(horizontal, true);
}

/* MAIN CONTENT */
main {
  background-color: yellow;
  @include xy-grid(horizontal, true);
  @include xy-gutters();
}

.article {
  background-color: lightyellow;
  @include xy-grid(horizontal, true);
  @include xy-gutters();
}

.article__hero-image {
  @include xy-cell-breakpoints((small: full));
}

.article__info {
  @include xy-cell-breakpoints((small: full, medium: 9));
}

.article__content {
  @include xy-cell-breakpoints((small: full, medium: 9));
}

.article__end {
  @include xy-cell-breakpoints((small: full, medium: 9));
}
```

What do you think?

**Comment by IamManchanda** [comment]
cc @kball @brettsmason ?

**Comment by kball** [comment]
Bother I think this made it into the docs at some point but the final PR for this was never merged as we did not get it working with responsive gutters yet (handling responsive gutters with the margin-based grids is unfortunately quite complex).

@Moonbase59 would you be interested in helping get PR across the line? (https://github.com/zurb/foundation-sites/pull/10171)

**Comment by Moonbase59** [comment]
@kball I might be able to offer some testing maybe, but still consider myself quite a Foundation beginner, especially regarding the xy-grid.

**Comment by bmarshall511** [comment]
Curious what the status of this is?

**Comment by guci0** [comment]
//Error: no mixin named xy-cell-breakpoints
