### ISSUE TITLE
foundation update

### ISSUE THREAD

**Issue by Chillwabbitt** [zurb/foundation-sites#10277]
I suspect foundation update command not working as intended

#### How to reproduce this bug:

1. cd into a project created with the previous version of Foundation (6.3.1)
2. run command foundation update

#### What should happen:
The foundation project should be updated to 6.4.0

#### What happened instead:
unsure but when trying to use the new xy mixin I got the following error:

> Error in plugin 'sass'
Message:
    src/assets/scss/hero-sections.scss
Error: no mixin named xy-grid-frame

       Backtrace:
       	src/assets/scss/hero-sections.scss:164
        on line 164 of src/assets/scss/hero-sections.scss
>>     @include xy-grid-frame(false,false);
   -------------^

#### Browser(s) and Device(s) tested on:
N/A
#### Foundation Version(s) you are using:
6.4.0
#### Test case link:
N/A

- [CodePen with Foundation 6.3.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Float Grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/bRYOMv)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

- [CodePen with Foundation 6.4.0, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.0, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.0, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.0, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)

**Comment by colin-marshall** [comment]
@Chillwabbitt you probably need to manually update your `app.scss` file to include the new XY grid. This doesn't get automatically updated when you run `foundation update`. Copy over the latest version of `app.scss` to your project:
https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/scss/app.scss

Let me know if this fixes it for you.

**Comment by Chillwabbitt** [comment]
@colin-marshall that broke my design completley, there are no errors but the site renders without any style now.

**Comment by colin-marshall** [comment]
Can you please put your old app.scss in this thread so i can have a look at what is different? Thanks!

**Comment by DanielRuf** [comment]
@Chillwabbitt hi, can you share your project settings with us?

**Comment by colin-marshall** [comment]
@DanielRuf I think it's safe to close this one out. @Chillwabbitt if you would still like to follow up on this, feel free to reopen the issue with the requested information. Thank you.

**Comment by Chillwabbitt** [comment]
Hi @colin-marshall, please close it, thank you.
