### ISSUE TITLE
Sites 6.4.0 ResponsiveAccordionTabs when updating

### ISSUE THREAD

**Issue by colinmackinlay** [zurb/foundation-sites#10271]
#### How to reproduce this bug:
1. 6.3.1 project
2. Update foundation sites dependency in bower.json: "foundation-sites": "~6.4.0",
3. bower update / foundation update / npm update -g foundation-cli
4. npm build

#### What should happen:
should build with no errors
#### What happened instead:
fails because config.yml still contains - "bower_components/foundation-sites/js/foundation.zf.responsiveAccordionTabs.js"

#### Foundation Version(s) you are using:
6.3.1 updating to 6.4.0

#### SOLUTION
comment out this line in config.yml

Looks to me that this has been merged into other files. Perhaps release notes could be updated to say this needs to be done if upgrading a project?

**Comment by kball** [comment]
Thanks for the report @colinmackinlay! Will update release notes later today, as updating the JS from 6.3.X to 6.4.0 definitely has a couple nonobvious pieces - I don't think simply commenting this out is sufficient.

For a reference for now check out how we're handling the JS build now in the 6.4.0 template: https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js#L112

**Comment by thewebmastercom** [comment]
> SOLUTION
> 
> comment out this line in config.yml

I just had this error. Confirmed that commenting out the line in the config.yml solved the problem.

Looks like it should refer to: /bower_components/foundation-sites/js/foundation.responsiveAccordionTabs.js ?

**Comment by kball** [comment]
Updated the release notes here: https://github.com/zurb/foundation-sites/releases/tag/v6.4.0
