### ISSUE TITLE
Error in plugin webpack-stream

### ISSUE THREAD

**Issue by Chillwabbitt** [zurb/foundation-sites#10274]
Hi

I've just installed the newest version of foundation-cli, when using it with my existing project I don't seem to have an issue, however after creating my new project, I cannot use the commands build or watch without receiving an error as follows:

#### How to reproduce this bug:
1. Open terminal
2. cd to sites directory
3. exec foundation new
4. ? What are you building today? **A website (Foundation for Sites)**
5. ? What's the project called? (no spaces) **mynewsite**
6. ? Which template would you like to use? **ZURB Template: includes Handlebars templates and Sass/JS compilers**
7. cd mynewsite
8. exec foundation watch

#### What should happen:
1. A new project called mynewsite is created
2. Bowser window should open and site should be displayed

#### What happened instead:
You're all set!

 ✓ New project folder created.
 ✓ Node modules installed.
 ✓ Bower components installed.

Now run foundation watch while inside the mynewsite folder.

➜  Sites cd mynewsite
➜  mynewsite foundation watch

> foundation-zurb-template@1.0.0 start /Users/lindsay/Sites/mynewsite
> gulp

[11:15:04] Requiring external module babel-register
[11:15:08] Using gulpfile ~/Sites/mynewsite/gulpfile.babel.js
[11:15:08] Starting 'default'...
[11:15:08] Starting 'build'...
[11:15:08] Starting 'clean'...
[11:15:08] Finished 'clean' after 3.43 ms
[11:15:08] Starting 'pages'...
[11:15:08] Starting 'sass'...
[11:15:08] Starting 'javascript'...
[11:15:08] Starting 'images'...
[11:15:08] Starting 'copy'...
[11:15:09] Finished 'images' after 943 ms
[11:15:09] Finished 'pages' after 1.08 s
[11:15:09] Finished 'copy' after 1.11 s
[11:15:16] Finished 'sass' after 7.34 s
[11:15:16] 'javascript' errored after 7.43 s
[11:15:16] Error in plugin 'webpack-stream'
Message:
    ./src/assets/js/app.js
Module not found: Error: Can't resolve 'jquery' in '/Users/lindsay/Sites/mynewsite/src/assets/js'
resolve 'jquery' in '/Users/lindsay/Sites/mynewsite/src/assets/js'
  Parsed request is a module
  using description file: /Users/lindsay/Sites/mynewsite/package.json (relative path: ./src/assets/js)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/lindsay/Sites/mynewsite/package.json (relative path: ./src/assets/js)
    resolve as module
      /Users/lindsay/Sites/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      /Users/lindsay/Sites/mynewsite/src/node_modules doesn't exist or is not a directory
      /Users/lindsay/Sites/mynewsite/src/assets/node_modules doesn't exist or is not a directory
      /Users/lindsay/Sites/mynewsite/src/assets/js/node_modules doesn't exist or is not a directory
      looking for modules in /Users/lindsay/Sites/mynewsite/node_modules
        using description file: /Users/lindsay/Sites/mynewsite/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/lindsay/Sites/mynewsite/package.json (relative path: ./node_modules)
          using description file: /Users/lindsay/Sites/mynewsite/package.json (relative path: ./node_modules/jquery)
            as directory
              /Users/lindsay/Sites/mynewsite/node_modules/jquery doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/Sites/mynewsite/node_modules/jquery doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/Sites/mynewsite/node_modules/jquery.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/Sites/mynewsite/node_modules/jquery.json doesn't exist
      looking for modules in /Users/lindsay/node_modules
        using description file: /Users/lindsay/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/lindsay/package.json (relative path: ./node_modules)
          using description file: /Users/lindsay/package.json (relative path: ./node_modules/jquery)
            as directory
              /Users/lindsay/node_modules/jquery doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/node_modules/jquery doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/node_modules/jquery.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/node_modules/jquery.json doesn't exist
[/Users/lindsay/Sites/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/lindsay/Sites/mynewsite/src/node_modules]
[/Users/lindsay/Sites/mynewsite/src/assets/node_modules]
[/Users/lindsay/Sites/mynewsite/src/assets/js/node_modules]
[/Users/lindsay/Sites/mynewsite/node_modules/jquery]
[/Users/lindsay/Sites/mynewsite/node_modules/jquery]
[/Users/lindsay/Sites/mynewsite/node_modules/jquery.js]
[/Users/lindsay/Sites/mynewsite/node_modules/jquery.json]
[/Users/lindsay/node_modules/jquery]
[/Users/lindsay/node_modules/jquery]
[/Users/lindsay/node_modules/jquery.js]
[/Users/lindsay/node_modules/jquery.json]
 @ ./src/assets/js/app.js 3:14-31
 @ multi ./src/assets/js/app.js./src/assets/js/app.js
Module not found: Error: Can't resolve 'what-input' in '/Users/lindsay/Sites/mynewsite/src/assets/js'
resolve 'what-input' in '/Users/lindsay/Sites/mynewsite/src/assets/js'
  Parsed request is a module
  using description file: /Users/lindsay/Sites/mynewsite/package.json (relative path: ./src/assets/js)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/lindsay/Sites/mynewsite/package.json (relative path: ./src/assets/js)
    resolve as module
      /Users/lindsay/Sites/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      /Users/lindsay/Sites/mynewsite/src/node_modules doesn't exist or is not a directory
      /Users/lindsay/Sites/mynewsite/src/assets/node_modules doesn't exist or is not a directory
      /Users/lindsay/Sites/mynewsite/src/assets/js/node_modules doesn't exist or is not a directory
      looking for modules in /Users/lindsay/Sites/mynewsite/node_modules
        using description file: /Users/lindsay/Sites/mynewsite/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/lindsay/Sites/mynewsite/package.json (relative path: ./node_modules)
          using description file: /Users/lindsay/Sites/mynewsite/package.json (relative path: ./node_modules/what-input)
            as directory
              /Users/lindsay/Sites/mynewsite/node_modules/what-input doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/Sites/mynewsite/node_modules/what-input doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/Sites/mynewsite/node_modules/what-input.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/Sites/mynewsite/node_modules/what-input.json doesn't exist
      looking for modules in /Users/lindsay/node_modules
        using description file: /Users/lindsay/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/lindsay/package.json (relative path: ./node_modules)
          using description file: /Users/lindsay/package.json (relative path: ./node_modules/what-input)
            as directory
              /Users/lindsay/node_modules/what-input doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/node_modules/what-input doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/node_modules/what-input.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/lindsay/node_modules/what-input.json doesn't exist
[/Users/lindsay/Sites/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/lindsay/Sites/mynewsite/src/node_modules]
[/Users/lindsay/Sites/mynewsite/src/assets/node_modules]
[/Users/lindsay/Sites/mynewsite/src/assets/js/node_modules]
[/Users/lindsay/Sites/mynewsite/node_modules/what-input]
[/Users/lindsay/Sites/mynewsite/node_modules/what-input]
[/Users/lindsay/Sites/mynewsite/node_modules/what-input.js]
[/Users/lindsay/Sites/mynewsite/node_modules/what-input.json]
[/Users/lindsay/node_modules/what-input]
[/Users/lindsay/node_modules/what-input]
[/Users/lindsay/node_modules/what-input.js]
[/Users/lindsay/node_modules/what-input.json]
 @ ./src/assets/js/app.js 7:17-38
 @ multi ./src/assets/js/app.js
Details:
    domain: [object Object]
    domainThrown: true
[11:15:16] 'build' errored after 7.43 s
[11:15:16] 'default' errored after 7.44 s
Error: foundation-zurb-template@1.0.0 start: `gulp`
Exit status 1
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/lifecycle.js:217:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/foundation-cli/node_modules/npm/lib/utils/spawn.js:24:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
➜  mynewsite

#### Browser(s) and Device(s) tested on:
N/A
#### Foundation Version(s) you are using:
6.4.0
#### Test case link:
N/A

**Comment by Chillwabbitt** [comment]
I did notice that the command foundation watch still works on my existing projects that I ran update on.

**Comment by Vout** [comment]
I noticed the watch command isn't available in the gulp file anymore.

Add the following lines to the gulpfile and it should work again,

`gulp.task('default',
  gulp.series('build', watch));`

and 

`// Watch for changes to static assets, pages, Sass, and JavaScript
function watch() {
  gulp.watch(PATHS.assets, copy);
  gulp.watch('src/scss/**/*.scss').on('all', sass);
  gulp.watch('src/js/**/*.js').on('all', gulp.series(javascript));
  gulp.watch('src/img/**/*').on('all', gulp.series(images));
}`

**Comment by Chillwabbitt** [comment]
That didn't work for me and my files look identical.

**Comment by Vout** [comment]
I tried your steps, and you are correct. Solved it however by doing the following,

`npm install jquery`

Then the next error will come up... what-input so,

`npm install what-input`

Foundation build and watch are properly running again.

**Comment by ttyson99** [comment]
+1 on that solution

**Comment by Chillwabbitt** [comment]
Thanks @Vout that got it sorted.

**Comment by 1415926535** [comment]
My main machine borked so I switch and installed cli and installed zurb stack. `foundation watch` just did nothing. `bower install` just gave me `bower ENOENT        No bower.json present`. After searching in circles for something that worked and creating 5 or 6 new zurb stacks I decided to just remove `foundation-cli` and install it again. That fixed my problem. That install was only 6 hours old so no idea why that worked.

`node 8.6.0`
`npm 5.4.2`
`xenial`
