### ISSUE TITLE
Error: Base-level rules cannot contain the parent-selector-referencing character '&'

### ISSUE THREAD

**Issue by Utakka** [zurb/foundation-sites#10279]
I try to use Foundation 6.4 (sass) with xy grid.

Error message:

`Error: Base-level rules cannot contain the parent-selector-referencing character &.
on line 311 of lib/foundation/scss/xy-grid/_classes.scss, in xy-vertical-grid-classes
from line 449 of lib/foundation/scss/xy-grid/_classes.scss, in foundation-xy-grid-classes
from line 10 of css/main.scss`

System:

Windows 10
Ruby
Sass 3.4.24

**Comment by kball** [comment]
Interesting, this appears to be a real bug, but node-scss did not catch it (silently doing the "right thing" by outputting a top level class. Putting together a PR to fix it, we'll get out a patch release soon once we have any more items like this straightened out

**Comment by coetry** [comment]
The same thing happens on line 65 of /scss/components/_accordion-menu.scss in 'zf-accordion-menu-left-right-arrows'

**Comment by kball** [comment]
@coetry good catch... @IamManchanda @brettsmason within drilldown and dropdown the arrows are included only within parent classes (`.drilldown` and `.is-dropdown-submenu-parent` respectively)... do you think that should be the case for accordion menu as well?

**Comment by IamManchanda** [comment]
Yes it should be ... let me see! @kball

**Comment by BernhardWebstudio** [comment]
I am facing the same issue. What do I have to do to get npm to fetch the newest, fixed version? 
`npm update` seems not to be ready yet...

**Comment by kball** [comment]
We're going to package up fixes for this and a couple others either later today or early tomorrow
