### ISSUE TITLE
[Welcome to Foundation 6] full width

### ISSUE THREAD

**Issue by genesis-wp** [zurb/foundation-sites#10281]
Hello!
I'm tring display full width image, but work not. Have is it some code for help me this? Look the img below:
http://prntscr.com/fp5v06

My code:
#banner-homepage {width: 100%; padding-left: 0; padding-right:0!important;margin-left:0;margin-right:0 !important; }

**Comment by smithjoelt** [comment]
What browser is displaying this image?

**Comment by codetheorist** [comment]
@genesis-wp This does require more information, possibly a working link.

Have you put the image inside a row or container of some sort? Does the image have a max-width? Does the body have padding on? The list of possibilities with this are endless.

**Comment by IamManchanda** [comment]
@genesis-wp I am sorry but i will close this 
Please move this thread to http://foundation.zurb.com/forum

As we like to keep this place for feature requests and bug fixes!
