### ISSUE TITLE
Reveal animation issue

### ISSUE THREAD

**Issue by lukeyouell** [zurb/foundation-sites#10283]
#### How to reproduce this bug:

1. Create Reveal modal with animation
2. Open modal
3. Attempt to close modal

#### What should happen:

1. Animations should be visible
2. Modal should be closable

#### What happened instead:

2. No animations visible
3. Cannot close modal

#### Browser(s) and Device(s) tested on:

Chrome, iMac

#### Foundation Version(s) you are using:

6.4.0

**Comment by IamManchanda** [comment]
You must be missing **motion ui** 

For installing motion ui, here are the options 
1. If you are using zurb template, motion ui is already included
2. If you are not using zurb template, download motion ui from here https://github.com/zurb/motion-ui
3. Use a web cdn https://cdnjs.com/libraries/motion-ui

**Comment by lukeyouell** [comment]
I'm using the bundled version which *should* have motion ui included (the last version did) unless something has changed in that regard?

**Comment by kball** [comment]
Hi @lukeyouell can you clarify how you installed/downloaded Foundation?  

The bundles from the customized downloads should include motion UI, and I've just double checked that they are... That said, if you downloaded *right* after the release maybe try again, as we fixed some issues in the customizer yesterday

**Comment by brettsmason** [comment]
@lukeyouell Did you have any luck with trying this again with a fresh download?

**Comment by lukeyouell** [comment]
@kball @brettsmason sorry for the late reply, kball's comment worked a treat. I must have just been unlucky with the initial download.

Thanks!

**Comment by kball** [comment]
Closing based on the above. Thanks @lukeyouell!
