### ISSUE TITLE
Vertical slider with two handles doesn't behave as expected

### ISSUE THREAD

**Issue by WnP** [zurb/foundation-sites#10284]
#### How to reproduce this bug:

1. Create a "two handles" slider like discribed in [foundation 6 documentation](http://foundation.zurb.com/sites/docs/slider.html#two-handles)
2. Add `vertical` class and `data-vertical="true"` as describe in [foundation 6 vertical slider documentation](http://foundation.zurb.com/sites/docs/slider.html#vertical)

#### What should happen:

"Two handles" should behave the same way vertically and horizontally.

#### What happened instead:

Cannot drag first slider to lower value, also cannot drag second slider to higher value.

#### Browser(s) and Device(s) tested on:

Tested on chrome 57.0.2987

#### Foundation Version(s) you are using:

Foundation 6.3.1

#### Test case link:

- [CodePen issue demo](https://codepen.io/WnP/pen/dRJNpq)

**Comment by IamManchanda** [comment]
Updated your codepen to 6.3.1 (you were using 6.2.4) 
https://codepen.io/IamManchanda/pen/YQYrNx

Yes the issue exists seems like... (cc @kball )
