### ISSUE TITLE
Manage dynamic z-index for multiple open off-canvas

### ISSUE THREAD

**Issue by klihelp** [zurb/foundation-sites#10304]
#### How to reproduce this bug:
1. Have two off-canvas panels; add triggers inside off-canvas contents to trigger each-other
2. Open first-off-canvas; with any trigger from the page
3. From off-canvas content trigger the second-off-canvas
3. Second-off-canvas is  open,  from it's content trigger back the first-off-canvas

#### What should happen:
4. Last triggered off-canvas should be on top by changing Z-index.

#### What happened instead:
4. Both off-canvas panels are open, last off-canvas on Dom is on top, as they have fixed z-index

#### Browser(s) and Device(s) tested on:
MBA/Chrome

#### Foundation Version(s) you are using:
6.4

**Comment by DanielRuf** [comment]
Is this a real bug or feature request?

**Comment by DanielRuf** [comment]
Hi @klihelp, can you provide a codepen or some more clear instructions how we can test and reproduce this?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
