### ISSUE TITLE
Grid-margin doesn't work with grid-frame

### ISSUE THREAD

**Issue by OndrejVasicek** [zurb/foundation-sites#10305]
#### How to reproduce this bug:
1. Set up grid-y with some children
2. Add class `grid-frame` to spread the size to 100% of the screen
3. Add class `grid-margin-y` to add margin gutters between the children

I used grid-y, because the class `grid-frame` has bigger meaning here. When using grid-x the width is 100% by default already. But the bug is present in grid-x as well.

#### What should happen:
The margin gutters should be between the children but not on the edges.

#### What happened instead:
There is some weird spacing in the bottom of the page. It seems like the negative margins from the grid-margin-y class doesn’t work, when the element I 100vh.
![grid-frame](https://user-images.githubusercontent.com/3864012/27740136-321e0b5c-5db1-11e7-97b9-c6e5aa8169c4.png)

#### Browser(s) and Device(s) tested on:
Current Chrome and FF.

#### Foundation Version(s) you are using:
6.4
#### Test case link:
https://codepen.io/OndrejVasicek/pen/weyOoZ

**Comment by kball** [comment]
Thanks @brettsmason - this is not actually sufficient - the outcome is about the same as we only have 1 gutters worth of spacing but the height calc is taking into account 2 gutters worth...

I *think* this may actually be a related problem to https://github.com/zurb/foundation-sites/issues/10297

For the margin grid to work properly we may need to insist on having a container which containers the overflow, and have the frame in that case add the gutter height in.

**Comment by kball** [comment]
I've started a branch to work on this with a simple visual test using the codepen code here: https://github.com/zurb/foundation-sites/tree/fix-grid-frame-with-margin

**Comment by brettsmason** [comment]
@kball I think I've worked out a fix (atleast a CSS solution - not sure how to handle with mixins).
Take a look at this CodePen: https://codepen.io/brettsmason/pen/LLBoNB
Basically we can set the height using `calc()` at `100vh + gutter`.

What do you think?

**Comment by IamManchanda** [comment]
@brettsmason That's dope!

**Comment by kball** [comment]
Looks great to me, you're the man @brettsmason! Want to put together a PR?

**Comment by brettsmason** [comment]
@kball sorry yes I'll put a pr together for this today or tomorrow depending on time.
