### ISSUE TITLE
[docs] OffCanvas autoFocus

### ISSUE THREAD

**Issue by sebastiansulinski** [zurb/foundation-sites#10312]
In docs it says that `autoFocus` / `data-trap-focus` is set to `false` by default but it appears it is actually set to `true` - I had to manually disable it when instantiating the class to make sure it doesn't focus on the first item in the container:

```javascript
new window.Foundation.OffCanvas(element, {
    autoFocus: false
});
```

I've checked `foundation.offcanvas.js` and on line `519` found:

```javascript
/**
   * Force focus to the offcanvas on open. If true, will focus the opening trigger on close.
   * @option
   * @type {boolean}
   * @default true
   */
  autoFocus: true,
```

**Comment by codetheorist** [comment]
Hey @sebastiansulinski 

Had a look at the docs and code base of 6.4.1 this morning and 'data-auto-focus' and 'data-trap-focus' are not the same.

`[data-auto-focus]` merely forces the focus to the off-canvas on open.

`[data-trap-focus]` triggers optional focus trapping when opening an off-canvas, automatically setting tab index of [data-off-canvas-content] to -1 for accessibility purposes.

The docs & code base in this respect are aligned with one another.

**Comment by sebastiansulinski** [comment]
Oh I see - you're right. Thanks @codetheorist.

**Comment by codetheorist** [comment]
No problem @sebastiansulinski, happy to help.
