### ISSUE TITLE
Border of Accordion disappears when .hide is specified as the last item

### ISSUE THREAD

**Issue by kyoshidajp** [zurb/foundation-sites#10321]
Hi.

I am using foundation-rails, and I would like to chage dynamically display the item in Accordion. 

For several reasons, I decided to enable all items display in Accordion by template engine. Next, added .hide class into specified items just before rendering finish.

However, border of Accordion disappeared when .hide is specified as the last item.

I think this would be CSS setting. But I have no idea. Could you tell me how to solve this problem.

#### How to reproduce this bug:

For example.

```html
<ul class="accordion" data-accordion>
  <li class="accordion-item" data-accordion-item>
    <a href="#" class="accordion-title">Accordion 1</a>
    <div class="accordion-content" data-tab-content>
      1st
    </div>
  </li>
  <li class="accordion-item" data-accordion-item>
    <a href="#" class="accordion-title">Accordion 2</a>
    <div class="accordion-content" data-tab-content>
      2nd
    </div>
  </li>
  <!-- The following item -->
  <li class="accordion-item hide" data-accordion-item>
    <a href="#" class="accordion-title">Accordion 3</a>
    <div class="accordion-content" data-tab-content>
      3rd
    </div>
  </li>
</ul>
```

#### What should happen:
![accordion_ok](https://user-images.githubusercontent.com/3317191/27790699-995c4234-602c-11e7-8087-5226e2cc79b5.png)

#### What happened instead:

![accordion](https://user-images.githubusercontent.com/3317191/27790707-a08b9dac-602c-11e7-857e-d4ecd719ee68.png)

#### Browser(s) and Device(s) tested on:
- Google Chrome 59.0.3071.115
- macOS 10.12.4

#### Foundation Version(s) you are using:

~~6.4.0~~ 6.3.1

**Comment by codetheorist** [comment]
Foundation version in the Rails gem is 6.3.1 at this time, rather than 6.4.0

**Comment by kyoshidajp** [comment]
@codetheorist Thanks. Fixed it.

**Comment by codetheorist** [comment]
I feel this works as intended and any workaround would be 'hacky' as the border of the bottom accordion item is set using :last-child. The only option would be to use `:not(.hide):last-child:not(.is-active)`, however the CSS selector 4 specs do not currently allow such functionality, nor is any such functionality drafted to be included in the near future.

The only 'automatic' workaround would be hacky, using jQuery. I don't believe that this would be warranted in Foundation Sites as it is typically quite a rare use case and would be best solved on a per-use basis.

This could possible be done by applying a `.visible` class to the other accordion items and using `.visible:last-child:not(.-is-active)` in your projects CSS file.

**Comment by codetheorist** [comment]
How did you work around this @kyoshidajp?

Can this issue be closed now?

**Comment by kyoshidajp** [comment]
@codetheorist OK, thank you for your reply.
