### ISSUE TITLE
package.json devDependencies

### ISSUE THREAD

**Issue by codetheorist** [zurb/foundation-sites#10322]
I forked and pulled a fresh copy of foundation-sites yesterday and when I ran `npm install`, it failed installing gulp-postcss. It seems that gulp-postcss 6.4.1 has been removed from the NPM repo.

![gulp-postcss-6 4 1-error](https://user-images.githubusercontent.com/22813671/27793953-00b40384-5ff8-11e7-8bdf-a662235c1647.jpg)

The problem can be replicated by simply pulling a fresh copy of foundation-sites from the repo and running `npm install` however, you must make sure that gulp-postcss 6.4.1 is not already in your NPM package cache otherwise it will install correctly.

The 2 options available are:

1. Rollback to version 6.4.0
2. Upgrade to version 7.0.0

I have checked both versions and they both seem to be working correctly.

**Comment by codetheorist** [comment]
Pull request has now been submitted [here](https://github.com/zurb/foundation-sites/pull/10323).

**Comment by IamManchanda** [comment]
Closing this as added in #10325 :+1:
