### ISSUE TITLE
Wrong link in Off-canvas docs

### ISSUE THREAD

**Issue by OndrejVasicek** [zurb/foundation-sites#10327]
#### How to reproduce this bug:

1. Open the Off-canvas page in docs (http://foundation.zurb.com/sites/docs/off-canvas.html)
2. Check the section Responsive Off-Canvas (http://foundation.zurb.com/sites/docs/off-canvas.html#responsive-off-canvas-putting-it-all-together-)
3. Click on the link http://zurb.com/building-blocks/top-bar-with-off-canvas

#### What should happen:
Open proper page in building blocks.

#### What happened instead:
Opens the main page of building blocks.

I'm not able to find a proper page in building blocks. Is it possible that there isn't such a building block anymore?

**Comment by codetheorist** [comment]
Had a look at the building blocks page and I can't see a page that this should link to either.

**Comment by IamManchanda** [comment]
@OndrejVasicek @codetheorist Would anyone of you want to submit a PR 

A goodie link that could replace this would be http://foundation.zurb.com/building-blocks/blocks/multilevel-offcanvas-menu.html

**Comment by codetheorist** [comment]
YES! I hadn't seen that layout yet but that looks amazing.

@IamManchanda A PR has now been submitted.

**Comment by OndrejVasicek** [comment]
You were faster :) Thank you.

**Comment by IamManchanda** [comment]
Its amazing that all of you new guys are coming up with your skills :+1: 
Keep coming up with your feedback... Its great for the framework's future! :)

**Comment by codetheorist** [comment]
@IamManchanda I'm sorry to say I'm an old guy, I just haven't been active for a while due to other issues. It's great to be able to contribute again.

**Comment by IamManchanda** [comment]
hahaaa in that case i am a newbie (which i am though :wink: )

**Comment by IamManchanda** [comment]
Closing this as fixed in #10329 !
