### ISSUE TITLE
Javscript error Foundation 6.4 (MVC)

### ISSUE THREAD

**Issue by ferronsw** [zurb/foundation-sites#10334]
Hello,

I've added foundation 6.4 to my mvc application. I've deleted bootstrap and change the _layout.cshtml (menu) to a foundation menu. Some of the style component are loaded, but not the one initiated with js. 
When I inspect the site I see this error:

foundation.js:11621 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1__home_deployer_sites_node_foundation_customizer_node_foundation_customizer_foundation_sites_js_foundation_core__.a.addToJQuery is not a function
    at Object.<anonymous> (foundation.js:11621)
    at __webpack_require__ (foundation.js:20)
    at module.exports (foundation.js:66)
    at foundation.js:69
(anonymous)	@	foundation.js:11621
__webpack_require__	@	foundation.js:20
module.exports	@	foundation.js:66
(anonymous)	@	foundation.js:69

#### How to reproduce this bug:

1. Create MVC application in Visual studio (not core)
2. Add the foundation files to the BundleConfig.cs
3. change _Layout.cshtml to foundation menu
4. Include Jquery in the head of _Layout.cshtml
5. run the code

#### What should happen:

Foundation style should be applied

#### What happened instead:
Jquery Error and style is not fully loaded

#### Browser(s) and Device(s) tested on:
Chrome, Windows 10

#### Foundation Version(s) you are using:
6.4.0 zip from the site with js and css files

#### Test case link:

https://github.com/ferronsw/FoundationMVC

**Comment by kball** [comment]
Hi @ferronsw, thanks for the report!

I think this is related to a bug that was fixed in the 6.4.1 patch release that went out last Friday. I realized upon your filing the report that the downloader had not been updated properly, so I just updated it - can you try redownloading with Foundation 6.4.1 and see if the error persists?

**Comment by ferronsw** [comment]
Hi @kball,

I've found the 6.4.1 version on cdnjs, but i'm glad it's now also available on the site.
Thanks for the information!

p.s. 6.4.1 fixed the problem.

**Comment by kball** [comment]
Excellent, thanks for following up @ferronsw
