### ISSUE TITLE
[Installation] No update on older projects possible, no bower components when installing via CLI or manually, different node modules

### ISSUE THREAD

**Issue by zitrusblau** [zurb/foundation-sites#10337]
First I try a update from version 6.2.4 to 6.4.1, terminal saying update was sucessfull but cannot see any modifications in the files, version here stills 6.2.4
Then try to install a new instance at first manually and get:
bower                           ENOENT No bower.json present
then with CLI and get:
You're all set!
 ✓ New project folder created.
 ✓ Node modules installed.
 ✓ Bower components installed.

But no bower_components installed!

Also wondering about the difference by the node modules. Exec `npm install` on a manual install and I get 32 node module folder, but do this on a CLI install will serve 788 (!!!) node module folder.

It seems your framework get more messy with every update!

So how can I get a working Zurb Template?

**Comment by codetheorist** [comment]
@zitrusblau As far as I'm aware, all of the dependencies in the CLI projects are now NPM modules. Foundation is still available on the Bower ecosystem, however for a CLI generator, it doesn't make sense to have the dependencies spread across multiple package ecosystems.

**Comment by zitrusblau** [comment]
@codetheorist Sure this make no sense.
But it would make a big sense to document such essential changes. So that a simple templater like me must not search hour for hour to understand how to get this working.

However, I still don't know how to update existing projects. After bower update in a project folder the bower_components still the same as before update. There is no section in documentation which explain the update procedure, only in the forum are some articles which all mention to use bower update.

**Comment by rabimx** [comment]
Additionally, now I don't know how to select and exclude libraries. Someone know what is the new method? I think that I have to configure /node_modules/foundation-sites/webpack.config.js, but I don'n know how.

**Comment by kball** [comment]
The simplest way to update while still using one of the older builds approaches is to skip the webpack build entirely and use the compiled javascript files from `/node_modules/foundation-sites/dist/js`.

Alternatively, you could update your build system to look similar to the new zurb stack... see

**Comment by zitrusblau** [comment]
@kball 
For me this is really not simple!
I was trying to update the foundation framework within an existing WordPress theme via bower_update which doesn't work. The terminal result you can read in my first post here. **I got no foundation-sites folder within the node_modules!**

**Comment by kball** [comment]
I think I'm a little confused about what's happening here... are you attempting to update the *framework*, the *template*, or both?  Unfortunately the templates themselves are not really set up well to be updated after you've set up a project - they're templates, not libraries - so if that's what you're doing that may well be the problem. 

If you're updating an older project, it probably would make sense to simply update your bower reference and then point your config.yml to the distfiles... I'm happy to help you work through this, is the project somewhere you can share?

**Comment by zitrusblau** [comment]
Ha ha, if you're confused, what should I say?! ;)

I want to update the framework of course. I've an existing project of a WordPress Theme, build with Foundation 6.2.4 basic template, which comes with bower_components folder. I want to update to Foundation 6.4.1. So I edited the bower.json within the bower_components and made a bower update with the following result:
`bower cached        https://github.com/FortAwesome/Font-Awesome.git#4.7.0
bower validate      4.7.0 against https://github.com/FortAwesome/Font-Awesome.git#^4.7.0
bower cached        https://github.com/zurb/motion-ui.git#1.1.1
bower validate      1.1.1 against https://github.com/zurb/motion-ui.git#~1.1.0
bower cached        https://github.com/zurb/foundation-sites.git#6.4.1
bower validate      6.4.1 against https://github.com/zurb/foundation-sites.git#~6.4.1
bower cached        https://github.com/jquery/jquery-dist.git#2.1.4
bower validate      2.1.4 against https://github.com/jquery/jquery-dist.git#~2.1.4
bower cached        https://github.com/jquery/jquery-dist.git#3.2.1
bower validate      3.2.1 against https://github.com/jquery/jquery-dist.git#>= 3.0.0
bower cached        https://github.com/ten1seven/what-input.git#4.1.6
bower validate      4.1.6 against https://github.com/ten1seven/what-input.git#~4.1.3

Please note that,
    motion-ui#1.1.1 depends on jquery#~2.1.4 which resolved to jquery#2.1.4
    foundation-sites#6.4.1 depends on jquery#>= 3.0.0 which resolved to jquery#3.2.1
Resort to using jquery#>= 3.0.0 which resolved to jquery#3.2.1
Code incompatibilities may occur.

bower extra-resolution      Unnecessary resolution: what-input#~4.1.3`

All Foundation files still the same as before and I've no foundation-sites within the node_modules and also I've no config.yml! So how can I update the framework with this project?

**Comment by colin-marshall** [comment]
@zitrusblau you have no `foundation-sites` within `node_modules` because you need to update your `package.json` file:
https://github.com/zurb/foundation-sites-template/blob/master/package.json

You also need to copy files like `config.yml` from the template manually and update the `gulpfile.js` and run `npm install`. 

I'm going to close this out since it's old, but feel free to reopen if you need more help or what I said wasn't clear. If that's the case, please provide a link to your repo so I can give you exact directions. Thanks!
