### ISSUE TITLE
Foundation Docs mobile browsers crashes

### ISSUE THREAD

**Issue by pine3ree** [zurb/foundation-sites#10338]
Hello,

when I open the site docs in latest FF and Chrome for iPad, the browser just crashes. No crash with Safari.
Does this happen to anyone else?

kind regards

**Comment by codetheorist** [comment]
Just tested it now and I'm unable to reproduce the issue. It maybe a cache issue with the browser perhaps.

![19748883_1786558024719566_2446906235696144072_n](https://user-images.githubusercontent.com/22813671/27837408-f64681c6-60db-11e7-8ccd-ec1bb91ff4d7.jpg)

**Comment by IamManchanda** [comment]
Sometimes the devices are the issue ... it happens in my old mobile also ... Sony Xperia C

**Comment by DanielRuf** [comment]
Not reproducible. Can anyone provide a crash report and try to profile the website before it crashes?

**Comment by DanielRuf** [comment]
I guess this did not happen anymore and we can close this.

Feel free to reopen if it happens in a current browser again.
