### ISSUE TITLE
6.4.1 - Block grids

### ISSUE THREAD

**Issue by kevin-lesterius** [zurb/foundation-sites#10349]
Hi,

I started working on a project with the 6.3 version.
I switched to 6.4 using npm and then I saw that some parts of the website was broken.

After some search, I found that the styles selectors was different on some components of Foundation.
Block grids is an example, but I got styles lost also on the arrow of a accordion menu.

The docs still ask for .column as children of block grids. but the CSS of 6.4.1 is waiting for .cell children.

Can someone confirm what I saw ?

**Comment by Deckluhm** [comment]
XY Grid is now the default Grid in Foundation 6.4 (it was the now called Float Grid before this release).

You should read the 6.4 changelog: https://github.com/zurb/foundation-sites/releases/tag/v6.4.0

**Comment by IamManchanda** [comment]
If you were using the default version aka float grid 
Then this link might be just you looking for 
https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.1/css/foundation-float.min.css

**Comment by kevin-lesterius** [comment]
Ok thanks you, my bad. I though it was still possible to use float grid by default.

**Comment by Deckluhm** [comment]
@kevin-lesterius I haven't tested Foundation 6.4 but from what I can see (in sources/docs), you can still use the Float Grid like you use to do before (even using NPM).

The Float Grid docs is now here: http://foundation.zurb.com/sites/docs/grid.html

**Comment by kevin-lesterius** [comment]
@Deckluhm loading foundation.css 6.4.1 from NPM, I found that you can't use anymore the float grid, it doesn't include the styles for the .row class.

However it's still possible to use the float grid using the foundation-float.css.

I don't understand why the foundation.css(XY grid) bring styles like ".medium-up-1 > .cell" for the old block grids(float) as long as there is no more block grids defined in the docs for the XY grid.

**Comment by IamManchanda** [comment]
I think we need to reopen this as we miss docs

**Comment by roysix** [comment]
If I may ask, specifically about block grids: So, is support being dropped for the block grid [CSS classes (e.g. "small-up/medium-up/large-up" classes) ](http://foundation.zurb.com/sites/docs/grid.html#block-grids)in the new xy grid? Is it possible to add them back in? This is a bit of an issue for me at the moment to upgrade from the 6.3 float grid to the 6.4 xy grid.

I see there[ is support for a "custom block grid" in the xy grid,](http://foundation.zurb.com/sites/docs/xy-grid.html#custom-block-grid) but it uses mixins. Unfortunately I am not using SASS/SCSS in my project at the moment, but I guess I'll try that route if there is no alternative.

**Comment by kball** [comment]
Hi @kevin-lesterius,
The block grid classes exist in in the XY grid. You should be able to simply add `small-up-n`, `medium-up-n`, and `large-up-n` to a `grid-x` or `grid-y` and have it work as you'd expect.

I believe @IamManchanda is working on adding this to the docs right now.

**Comment by IamManchanda** [comment]
This is fixed guys ... We missed the docs ... now added 

Also if you care, #9776 proves why flex is better than float for block grid

**Comment by IamManchanda** [comment]
**Update**: This is [Deployed!](http://foundation.zurb.com/sites/docs/xy-grid.html#block-grids)
Thanks for reporting @kevin-lesterius
