### ISSUE TITLE
XY Grid with gutters incorrect at various breakpoints in custom download

### ISSUE THREAD

**Issue by brgrz** [zurb/foundation-sites#10343]
When customizing the download and selecting XY grid, the custom gutters don't get applied at certain breakpoints - they are being reset back to the default 1.875rem although we specifically set 1.25rem total for gutters.

Please see the attached photo showing the overrides at certain breakpoints.

![xy-grid-gutters](https://user-images.githubusercontent.com/193816/27842233-6fa831fa-6108-11e7-9624-313602c4939b.png)

**Comment by hikouki** [comment]
Hi! @brgrz
Are you changing `$grid-column-gutter` not `$grid-margin-gutters` ?
Please try following ✈️ 

```diff
// 56. Xy Grid
// -----------

$xy-grid: true;
$grid-container: $global-width;
$grid-columns: 12;
 $grid-margin-gutters: (
  small: 20px,
- medium: 30px
+ medium: 20px
);
$grid-padding-gutters: $grid-margin-gutters;
$grid-container-padding: $grid-padding-gutters;
$grid-container-max: $global-width;
$block-grid-max: 8;
```

**Comment by brgrz** [comment]
@hikouki Neither. I was changing the Total Gutter value at Customize Foundation download page: http://foundation.zurb.com/sites/download.html/

**Comment by hikouki** [comment]
I see.

**Comment by hikouki** [comment]
@kball @IamManchanda

It seems like a bug in Customize Foundation download page.
Also, It seemed not to be managed in this repository.
Could you fix it?

**Comment by IamManchanda** [comment]
Thanks guys let me see
will look into it soon

**Comment by IamManchanda** [comment]
I remember similar bug reported few days back

**Comment by kball** [comment]
This was indeed a bug in the customizer page, it wasn't appropriately handling the new grid gutters... I've done a basic fix, so if you redownload it should work as expected. Would love to extend and improve that customizer... it's currently not open but I think we should be able to open source it, will figure out what needs to be done to do so when a little more time opens up.
