### ISSUE TITLE
6.4.1 – `src/assets/js/custom.js` not included anymore like in 6.3.1?

### ISSUE THREAD

**Issue by Moonbase59** [zurb/foundation-sites#10353]
The docs still say that all custom javascript files in `src/assets/js/` automatically get included into `app.js` (6.3.1 did) but it seems not to? Anything changed due to webpack?

[F6.4.1/SASS on Ubuntu]

**Comment by kball** [comment]
Hi @Moonbase59 - can you clarify, are you talking about in the ZURB stack? If so, the answer is yes it has shifted b/c it's moved to using true module dependency, and we need to update the docs. Can you highlight the ones in particular you're seeing the outdated info on? Thanks!

**Comment by Moonbase59** [comment]
@kball http://foundation.zurb.com/sites/docs/starter-projects.html#javascript-compilation

Any easy way to do this correctly in 6.4.1, a link maybe?

**Comment by kball** [comment]
@Moonbase59 essentially you'll want to simply import/require the files you want to include. I believe webpack allows you to do either node style require/exports (http://openmymind.net/2012/2/3/Node-Require-and-Exports/) or ES6 modules: http://exploringjs.com/es6/ch_modules.html

Will hopefully have time to update docs soon, but if you get things working well and want to submit a PR to update those, that would be AWESOME :)

**Comment by kball** [comment]
Going to close this based on the initial docs improvement, but we'll be continuing to work on those docs as we go.

**Comment by udf2457** [comment]
@kball 

A little nudge to see if you're getting any nearer improving those docs ?  I stumbled across this problem today trying to work with the "new" FontAwesome 5. 

Putting `fontawesome-all.js` into `src/assets/js/` doesn't get compiled, I also tried `src/assets/js/lib/` So getting the modern FA5 SVG w/JS is proving to be tedious.

**Comment by scottshuffler** [comment]
Same issue as @udf2457

**Comment by ncoden** [comment]
@scottshuffler @udf2457 @Moonbase59 I updated the docs. See https://github.com/zurb/foundation-sites/pull/10925.

Does it solves your problem ? Is the docs clear enough now ?

**Comment by scottshuffler** [comment]
@ncoden LGTM
