### ISSUE TITLE
[Tabs] Tabs Documentation: data-tabs-target="#panel2"

### ISSUE THREAD

**Issue by hsmett** [zurb/foundation-sites#10372]
In the documentation dealing with tabs:
http://foundation.zurb.com/sites/docs/tabs.html

there seems to be an error with the data-tabs-target attribute.
The correct specification is
```
data-tabs-target="panel2"
```
instead of 
```
data-tabs-target="#panel2"
```

isn't it?

**Comment by IamManchanda** [comment]
Correct solution already added in #10368
Request you @kball to deploy the same :)

**Comment by hsmett** [comment]
If data-tabs-target is no more an alternative, you shoud also correct the upper paragraph :)
```
There are two pieces to a tabbed interface: the tabs themselves, and the content for each tab. The tabs are an element with the class `.tabs`, and each item has the class `.tabs-title`. Each tab contains a link to a tab. The `href` of each link should match the ID of a tab. Alternatively, the ID can be specified with the attribute `data-tabs-target`.
```
Thank you for your amazing work

**Comment by kball** [comment]
no longer have access to deploy these... @rafibomb can you?

**Comment by DanielRuf** [comment]
> no longer have access to deploy these... @rafibomb can you?

I guess this is not needed anymore.
The current docs use `<li class="tabs-title"><a data-tabs-target="panel2" href="#panel2">Tab 2</a></li>`

**Comment by DanielRuf** [comment]
It was done in https://github.com/zurb/foundation-sites/commit/914540df33621ad5fcc7474677accaf78bfe1494#diff-30d9f0df3455006a8080213cd07d9cd2

We should check if https://github.com/zurb/foundation-sites/pull/10368 produces a conflict later when we merge both.

**Comment by DanielRuf** [comment]
Can we close this? cc @ncoden

**Comment by DanielRuf** [comment]
Closing as this should be already fixed.
