### ISSUE TITLE
Foundation 6 and Rails 5 - can't get JS to work

### ISSUE THREAD

**Issue by joshzandman** [zurb/foundation-sites#10379]
Hi, I've tried many solutions found here and on SO and I can't get JS to work. I've never had this issue before when using earlier versions of Rails (< 5).

I've removed turbolinks and references to it. I recently put it back as it didn't solve the issue.

In console I get this error message: `Uncaught TypeError: $(...).foundation is not a function`

My repo: https://github.com/joshzandman/steven-wright-jokes

Any help would be awesome, thanks!!

**Comment by stephendolan** [comment]
This appears to be an issue with the newly released 6.4.1 version. Try reverting back to Foundation 6.3.1, if you're not already using it.

`gem 'foundation-rails', '~> 6.3.1''`

That did the trick for me when I was having the same issue this evening. Didn't have time to look into the asset pipeline to figure out exactly where the problem originated from.

**Comment by joshzandman** [comment]
That worked, thank you!!

**Comment by BrandonRoehl** [comment]
This is an issue with rails asset pipeline is unable to compile es6 js from 6.4.1 just serve up the distilled variant, no need to revert, there is a fix for this at zurb/foundation-rails#232
