### ISSUE TITLE
[Switch] Don't function out of the box in React

### ISSUE THREAD

**Issue by benjaminadk** [zurb/foundation-sites#10378]
#### How to reproduce this bug:

1. Render 3 radio style switch components in react
2. Try to click a switch...no animation or movement...click event occurs 
3. In same app place 3 radio style switches in the index.html
4. Click and they work like they are supposed to
5. Also, they will toggle with $("#switchID").prop("checked",true/false) in the console
6. This code does not work when attempted in React, at least for me
7. Tried to reInit even though switches don't get initialized
8. I am stumped

#### What should happen:
radio switches could work on click
#### What happened instead:
nothing
#### Browser(s) and Device(s) tested on:
chrome browser chromebook codepen
#### Foundation Version(s) you are using:
6.4
#### Test case link:
https://codepen.io/benjaminadk/pen/dRgbEr?editors=1000

- [CodePen with Foundation 6.3.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Float Grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/bRYOMv)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)

**Comment by Deckluhm** [comment]
Your pen works fine for me (Firefox 54, Chromium 59, both on Linux).

I can change both sliders values by clicking anywhere on them or by dragging the slider handler, both methods work as expected.

**Comment by benjaminadk** [comment]
that is because i removed the SWITCHES that didnt work.  sorry i should
have made a copy. my bad.

**Comment by Deckluhm** [comment]
Can you provide a pen that reproduces the bug you describe (and only that)?

**Comment by benjaminadk** [comment]
https://codepen.io/benjaminadk/pen/weQGBR?editors=0010
I have made pen you asked for
Two switch groups
The only things I have done are:
- give each switch input unique id
- use className in react components

I am not smart enough to figure out what is happening :|

**Comment by Knight-Yoshi** [comment]
Your labels are missing the "for" attribute.

**Comment by benjaminadk** [comment]
YES!  so i did some research and i changed the "for" to "htmlFor" and it
works!  i knew about class => className but had never heard of for =>
htmlFor    https://codepen.io/benjaminadk/pen/weQGBR?editors=0010   thanks
for pointing out the problem, now i can use Foundation switches in react!

**Comment by benjaminadk** [comment]
CHANGE "for" to "htmlFor"
