### ISSUE TITLE
XY-Grid grid-margin-x causes horizontal scrolling

### ISSUE THREAD

**Issue by Knight-Yoshi** [zurb/foundation-sites#10385]
So when using the `grid-margin-x` class to add spacing between the cells
This demonstrates that.
[https://codepen.io/KnightYoshi/pen/RgqJMY](url)

**Comment by jashwant** [comment]
@Knight-Yoshi , refer https://github.com/zurb/foundation-sites/issues/10297

**Comment by brettsmason** [comment]
Closing this as its duplicate of the above - please follow along there to see the fix etc.
