### ISSUE TITLE
[Magellan] Update event fires constantly

### ISSUE THREAD

**Issue by mattbag** [zurb/foundation-sites#10384]
I wasn't able to find a solution online, and I'm not confident in fiddling with this event, but most of all I'm sure with the rebuild solving this issue might be easy enough...
I imported in my js triggers,smoothscroll and magellan. It works great, but since I'm attaching a few functions it seems a bit of a waste.
Cheers!

#### How to reproduce this bug:

1. Step one: any magellan instance
2. Step two: show the magellan event in console
3. Step three: ponder a solution

#### What should happen:
magellan event should fire after the active magellan section as been updated

#### What happened instead:
the magellan event fires on every scroll motion

#### Browser(s) and Device(s) tested on:
Chrome

#### Foundation Version(s) you are using:
6.4.1

#### Test case link:
https://codepen.io/mattbag/pen/LLXJVP?editors=1111

#### Older version possibile solution
https://github.com/zurb/foundation-sites/issues/9068

**Comment by kball** [comment]
@IamManchanda can you take a look at this one as part of your entre into the JS world?

**Comment by IamManchanda** [comment]
Will look into it ... cool!

**Comment by mattbag** [comment]
I don't know if it relates at all, while studying vanilla js I came up with this solution
https://codepen.io/mattbag/pen/WZvoPo?editors=0101

Basically gets the index of the section to check the trigger. Hope it helps somehow. Thanks!
