### ISSUE TITLE
6.4.1. Complete Download foundation.css missing important classes like align-center

### ISSUE THREAD

**Issue by roysix** [zurb/foundation-sites#10400]
#### How to reproduce this bug:

1. Visit http://foundation.zurb.com/sites/download.html/
2. Download the Complete version (click the "Download Everything" button)
3. In the foundation.css file, try looking for the singular `.align-center` class (it is not there and it is missing the `justify-content: center` definition)

#### What should happen:

The align-center class should be defined in the CSS file

#### What happened instead:

There is no align-center class defined in the CSS file

#### Browser(s) and Device(s) tested on:

Chrome / Windows Desktop PC

#### Foundation Version(s) you are using:

6.4.1 (Complete Download Version)

#### Test case link:

Compare the two code pens of this menu that has the `align-center` class. One code pen is using the "Complete" download's foundation.css (no align-center class) and the second codepen is using the "CDN" foundation.css (which has the align-center class).

- [Codepen with the Complete download's foundation.css (with no align-center class)](https://codepen.io/sixs/pen/VWgQdW)
- [Codepen with the CDN's foundation.css (with align-center class)](https://codepen.io/sixs/pen/QgYQYP)

**Comment by brettsmason** [comment]
@roysix Thanks for reporting the bug.
It looks like it gets included with a custom build, but not with the complete download.

@kball Any ideas on this? I did notice there is no `flexbox utilities` option on the customiser, and in 6.4 we moved this out of the legacy flexbox grid into its own component. Maybe something to do with this?

**Comment by kball** [comment]
@brettsmason almost certainly - will take a look

**Comment by kball** [comment]
Do ya'all think flexbox utilities should be explicitly turned on/off or just imported by default if you're using xy or legacy flex grid?

**Comment by IamManchanda** [comment]
@kball @brettsmason Right now where the project and flexbox browser support stands 
It should be just imported by default if using xy or legacy flex grid?

**Comment by brettsmason** [comment]
I think if using the Customizer then definitely. However when using sass I think it should be split still. Atleast I think so...

**Comment by kball** [comment]
k, for customizer I'll just make it a strict dependency

**Comment by IamManchanda** [comment]
Yeah i also mean customizer :stuck_out_tongue:
