### ISSUE TITLE
Off-canvas and reveal-for-large ... bug

### ISSUE THREAD

**Issue by NoreagoCan** [zurb/foundation-sites#10407]
#### How to reproduce this bug:

There is a bug when using reveal-for-large and the off-canvas together. It displays as should for large screens and small screens. The column hides for medium screens as it should but the space does not shrink, leaving a blank space (extra margin-left). This issue is only in the new 6.4 xygrid version. Ive tried it on my own fresh installed projects and in codpen, foundation version 6 and 6.4 and it happens only in the 6.4.

#### What should happen:
the off canvas menu should shrink/hide on medium screens and lower and reveal on large screens only

#### What happened instead:
the off canvas shows for large, hides for small and medium, but in medium only it leaves a blank space (extra margin-left) and collapses only when in small screen size
#### Browser(s) and Device(s) tested on:
chrome, Microsoft Edge
#### Foundation Version(s) you are using:
6.4
#### Test case link:
[CodePen with Foundation 6.4.1, XY Flexbox grid](https://codepen.io/NoreagoCan/pen/dRaBoZ?editors=1000)

**Comment by NoreagoCan** [comment]
@kball @rafibomb I am just wondering why know one here or in the foundation forums has acknowledged this problem/bug? can you please verify if the above is in fact a bug in Foundation 6.4.1. I need to use this in my project and need to get it corrected so I can move on.

**Comment by brettsmason** [comment]
@NoreagoCan Thanks for reporting this bug. I haven't seen this posted anywhere else, but can confirm this looks like a bug.

@SassNinja Any chance you could take a look at this? It looks like this is to do with the work you did - specifically the reveal classes aren't being removed when off canvas is hidden. I could be wrong, but thats my hunch.

**Comment by SassNinja** [comment]
@brettsmason sure I'll take a look at this

**Comment by NoreagoCan** [comment]
@SassNinja @brettsmason  any chance for a quick fix or suggestion? I really need this to work in my project. 

i tried:
`@media print, screen and (min-width: 40em){
.off-canvas-content.has-reveal-left {
    margin-left: 0;
}
}`

but no go.

**Comment by SassNinja** [comment]
@brettsmason you were right, it is related to my work. Precisely the problem here was a missing update of the reveal content classes.
I've made a PR with a fix https://github.com/zurb/foundation-sites/pull/10421

@NoreagoCan if you can't wait until my fix is released you can do a quick & dirty fix via JS that toggles the `has-reveal-left` class

```javascript
$(window).on('changed.zf.mediaquery', function() {
    // Removes has-reveal-left class for medium down and adds it for large
    $('.off-canvas-content').toggleClass('has-reveal-left', Foundation.MediaQuery.atLeast('large'));
});
```
or instead of this, if you prefer a sass solution, disable the reveal for medium down
```scss
.off-canvas-content.has-reveal-left {
  @include breakpoint(medium down) {
      margin-left: 0 !important;
  }
}
```
Anyway, remember to undo the quick fix after the next update of foundation!
