### ISSUE TITLE
Foundation off canvas not works in facebook's in-app browser 

### ISSUE THREAD

**Issue by erick-gazi** [zurb/foundation-sites#10409]
Foundation off canvas not works in facebook's in-app browser.
Sometimes its just opening up on page load and cant be closed, sometimes not shows up and cant be opened.

To reproduce the bug:

Just try to open the foundation 6 off canvas page (http://foundation.zurb.com/sites/docs/off-canvas.html) with facebooks in-app browser and you will see.

I'm using foundation 6.3.1

**Comment by colin-marshall** [comment]
@erick-gazi are you on Android or iOS?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
