### ISSUE TITLE
Cannot try prototyping utilities

### ISSUE THREAD

**Issue by helio-correia** [zurb/foundation-sites#10417]
Hi, i'm trying to test the new feature prototyping utilities (http://foundation.zurb.com/sites/docs/prototyping-utilities.html) without success.

When I add @include foundation-everything($prototype: true); I have this error

```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js?{"includePaths":["/Users/heliocorreia/Dev/sandbox/css/foundation64/node_modules/foundation-sites/scss"]}!./src/main.scss
    Module build failed:
        h1 {
       ^
          You may not @extend an outer selector from within @media.
    You may only @extend selectors within the same directive.
    From "@extend h1" on line 15 of node_modules/foundation-sites/scss/prototype/_typescale.scss

          in /Users/heliocorreia/Dev/sandbox/css/foundation64/node_modules/foundation-sites/_vendor/normalize-scss/sass/normalize/_normalize-mixin.scss (line 105, column 5)
```

I am running the foundation 6.4.1 with web pack 3. 

My config in sass loader are like the documentation explains here (http://foundation.zurb.com/sites/docs/sass.html#compiling-manually) 

```
options: {
    includePaths: [
       path.resolve(__dirname, 'node_modules/foundation-sites/scss')
    ]
}
```

My main sass is this

```
@charset 'utf-8';

@import 'settings';
@import "foundation";
@include foundation-everything($prototype: true);
```

With the prototype in false it runs normally

Any ideas?

**Comment by IamManchanda** [comment]
Hey thanks for considering this feature and thanks for reporting!

This is solved in here ( https://github.com/zurb/foundation-sites/pull/10351 ) 
We are releasing path release (6.4.2) soon, most prob early next week

cc @kball @rafibomb for the patch release !

**Comment by helio-correia** [comment]
Oh ok, I thought I was doing something wrong. I'll be waiting for the release

Thanks for the feedback

**Comment by IamManchanda** [comment]
Welcome... gonna close the issue... but still let us know if you are still facing issue after the release is released :D
