### ISSUE TITLE
Make $accordion-plusminus a parameter on accordion-title

### ISSUE THREAD

**Issue by brentdodell** [zurb/foundation-sites#10413]
#### How to reproduce this bug:
Use accordion mixins (`accordion-item` in particular)

#### What should happen:
It would be nice to be able to override [$accordion-plusminus](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_accordion.scss#L103) as a parameter on [@mixin accordion-title](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_accordion.scss#L75-L81).

It would also be nice if you could specify what the *plus* and *minus* content is, so that different characters could be used

#### What happened instead:
Cannot override default setting of `$accordion-plusminus` when including `accordion-title` mixin, because no parameter is available for that value.

#### Foundation Version(s) you are using:
 6.4.1

#### Test case link:
- [accordion-item mixin without $plusminus parameter generates SASS error](https://codepen.io/brentdodell/pen/VWRMdP)
- [accordion-item mixin with $plusminus parameter](https://codepen.io/brentdodell/pen/YQgrjZ)

**Comment by IamManchanda** [comment]
This looks good @brentdodell ... Would you like to do a PR for it ??

**Comment by brentdodell** [comment]
> This looks good @brentdodell ... Would you like to do a PR for it ??

Sure! I will when I have a chance. I didn't want to jump into it too quickly because I hadn't looked over Zurb's contribution guidelines.

Are you thinking just parameterizing `$accordion-plusminus`, or also allowing for specifying custom `content` in place of `+`/`-` like I also suggested?

**Comment by IamManchanda** [comment]
Hey @brentdodell thanks for considering contributing guidelines 
For the core,
i would think that just parameterizing `$accordion-plusminus` would be fine  

But then we have this too (http://foundation.zurb.com/sites/docs/prototyping-utilities.html) 
So for my thought adding a class where an accordion will have arrow instead of plusminus will be great too for optional prototypes!

Again, this is just very personal opinion and maybe other yetinauts may consider different
So i will cc @kball for his opionion ??

**Comment by kball** [comment]
I would actually prefer the ability to set arbitrary content for open & closed states

**Comment by IamManchanda** [comment]
@kball You mean to choose b/w plusminus and arrows ?? 
Yup that was on my mind too!

**Comment by IamManchanda** [comment]
I think that will be good one choice also!

**Comment by IamManchanda** [comment]
Hey @brentdodell ... Any updates on this ??

**Comment by brentdodell** [comment]
No @IamManchanda, I've been on vacation with my family for the past week and will probably be catching up at work this next week, so I haven't had a chance to look at it.

**Comment by DanielRuf** [comment]
Hi @brentdodell, do you still want to provide a PR?

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11025 (@jellisii)

**Comment by DanielRuf** [comment]
I guess we can close this then?
