### ISSUE TITLE
Mistake in @else if directive

### ISSUE THREAD

**Issue by KirillPd** [zurb/foundation-sites#10410]
#### How to reproduce this bug:

1. Install foundation-sites:
`npm install foundation-sites`
2. Open node_modules/foundation-sites/scss/util/mixins.scss

#### Problem:
In mixins.scss file there is inner-side-shadow mixin which has @elseif directives (without a space between @else and if statements).

![1](https://user-images.githubusercontent.com/14921077/28208080-b7366ba2-6894-11e7-9037-99fc378cc21e.png)

Sass documentation: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_if

#### Foundation Version(s) you are using:
I am using the 6.4.1 version

**Comment by IamManchanda** [comment]
Digging it in right now!

**Comment by KirillPd** [comment]
Thanks guys!

**Comment by IamManchanda** [comment]
sorry @KirillPd bad on my part that i didnt asked you if would like to have a PR for this but we are having patch release soon and i wanted to fix it as soon as i saw it :smile: 

Again thanks for reporting... Kudos Buddy!

**Comment by KirillPd** [comment]
@IamManchanda Hello again!
After `npm install foundation-sites` in the _mixins.scss file i still notice this error.

Have you updated npm package?

**Comment by colin-marshall** [comment]
@KirillPd I believe this was implemented in a release a few days after you reopened it. I am closing this, but if you still experience the issue, feel free to reopen. Thanks!
