### ISSUE TITLE
Complete pack css not working, and different from CDN files in starter templates

### ISSUE THREAD

**Issue by carolix** [zurb/foundation-sites#10418]
I'm a beginner with Foundation 6 and downloaded the "Complete" pack from http://foundation.zurb.com/sites/download.html/ and the templates from http://foundation.zurb.com/templates.html  to learn from them. In the templates, the css file is linked via CDN. However, when I replaced that with the local css file, the one I had just download (latest version, 6.4.1), the layout collapsed. 

This is what the template news-magazine.html looks like with css via http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css:

![template-with-css-via-cdn](https://user-images.githubusercontent.com/30197823/28240195-faeaa03c-697c-11e7-8b77-4b01b12f9fce.jpg)

And this is what the same template looks like when the css file is exchanged for the latest css in a local folder:

![template-with-css-local](https://user-images.githubusercontent.com/30197823/28240428-09a5bb8e-6982-11e7-9d1d-542d26f01775.jpg)

I've already e-mailed the people from ZURB about this, but Rafi from ZURB said I should report things here.

Well, that's what I'm doing now ... and there are some more issues: 

- the template "news-magazine.html" is not working at all as downloaded -- as downloaded, the entire head, html and body tags are missing (I've copied these from one of the other templates, and now it works) ... 

- on the docs page http://foundation.zurb.com/sites/docs/menu.html the class for a nested menu or submenu is "nested" -- in the template "product-page.html" it's "submenu" inside the ul tag and "has-submenu" inside the li preceding it (this looked somewhat familiar to me, but if I've seen it before, it would have to mean it's an older version???)

As there are obviously not just differences in functionality in general, but also to do with very specific code items, I was wondering which versions the css files linked via CDN were ... but couldn't find a version number anywhere (I changed from foundation.min.css to foundation.css, but still no version number). 

I hope the people form ZURB FOUNDATION are looking at this page and these issues, and can get the incosistencies fixed as soon as possible. Like it is, I cannot work with the downloaded css. Because the same problems, of course, occur with anything, like when I insert code from blocks. Elements stack when they should display horizontally!

And one more thing on a personal note: I've never encountered problems with basic stuff like this with Bootstrap before, and I'm already thinking of going back. The ZURB people are constantly trying to sell their webinars for $300 dollars in their newsletters and videos, and I couldn't even download the templates without subscribing to their newsletter. And now the stuff isn't even doing what it should ... I came to Foundation, because I was hoping to find better submenu options with it, as I wasn't very happy with bootstrap submenus, particularly non-clickable parent items. But now ... well ... :-)

Still hoping, Carol

**Comment by IamManchanda** [comment]
cc @kball 
BTW https://github.com/zurb/foundation-sites/pull/10406 fixes some part to my best of knowledge!

-----

@carolix We are sorry you are facing such issues, we will try to solve the issue you as soon as we could do! Please understand that we had a big major release (6.4) and it had new grid so some issue have came but we are trying our best to resolve the issues!

**Comment by carolix** [comment]
@IamManchanda Thank you so much for your reply and for pointing me to #10406. I'd seen #10406 before, but at this this stage of my career didn't know what "flex classes" are and mistook the post to mean something specific to just those classes ... Ok, now I've downloaded the "Complete" pack again, exchanged the files for the previous ones, and tried again ... same result. Elements still stack. 
But your reply gave me my patience back and I'm happy to wait now :-)

**Comment by Nzrad** [comment]
Hello, I'm encountering exactly the same situation as carolix... But 5 months passed.

Everything looks so neat about Foundation, yet when trying even that simplest step of downloading a template and using with latest CSS release, it doesn't work at all. Do we even know what is causing this ?

Thanks

**Comment by ncoden** [comment]
Hello.

Templates at http://foundation.zurb.com/sites/download.html are using the Float Grid. This was replaced in Foundation v6.4 by the new XY Grid. This is why using these templates with a downloaded version of Foundation does not work: the template are out of date.

You can either:
* Replace the float grid (`.row`, `.column`) with the XY grid (`.grid-x`, `.cell`)
* Import the non-flex version of Foundation: `foundation-float.css` instead of `foundation.css`.

I added more informations about the differents grids in https://github.com/zurb/foundation-sites/pull/10866 and https://github.com/zurb/foundation-sites/pull/10847.

**Comment by Nzrad** [comment]
Thanks a lot, I'll dig into this !

**Comment by ncoden** [comment]
I'm closing this issue since complete pack / template _work_, but use different versions of Foundation.
