### ISSUE TITLE
Scope of the "webpackConfig" object passed to webpackStream() is limited

### ISSUE THREAD

**Issue by pandymic** [zurb/foundation-sites#10424]
Currently the `webpackConfig` variable being [passed to `webpackStream()`](https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js#L98-L109) is itself nested as a child of an object being statically declared within the function call itself. Is this intentional? Would it not be more practical to pass the entire configuration as a single variable?

The variable could be changed as follows:
````
let webpackConfig = {
  module: {
    rules: [
      {
        test: /.js$/,
        use: [
          {
            loader: 'babel-loader'
          }
        ]
      }
    ]
  }
}
````
This would allow for the easy addition of extra options if needed. For example [externals](https://webpack.js.org/configuration/externals/)

The function call on [Line 121](https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js#L121) would then become `webpackStream(webpackConfig, webpack2)`

**Comment by kball** [comment]
I'm happy to accept improvements in this domain... @pandymic would you like to take a pass and submit a PR?

**Comment by pandymic** [comment]
Glad to oblige. A pull request has been made on the foundation-zurb-template repo. I've referenced this issue in the comments of the request to help link things together.

**Comment by kball** [comment]
Closing this based on the PR by @pandymic. Much appreciated!
