### ISSUE TITLE
[Flex Grid] .row and .column classes aren't receiving default styles

### ISSUE THREAD

**Issue by designerdean** [zurb/foundation-sites#10425]
#### How to reproduce this bug:

Simply create a div.row with a nested div.column. Notice that there is no longer a max-width set by default.

#### What should happen:

The div.row should have the max-width equal to whatever is defined as $global-width.

#### What happened instead:

Neither the div.row nor div.column are receiving any styles like they were in v6.3.

#### Browser(s) and Device(s) tested on:

Chrome on Macbook Pro.

#### Test case link:

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](https://codepen.io/joshdean/pen/QgRKJK)

**Comment by rafibomb** [comment]
The XY Gris uses different syntax. Since you are looking to use the flex-grid, you'll want to change this in app.scss

```
@include foundation-flex-grid;
//
// @include foundation-xy-grid-classes;
```

**Comment by designerdean** [comment]
Well this is what I have had in app.scss:

![screen shot 2017-07-18 at 10 03 43 am](https://user-images.githubusercontent.com/729893/28327395-80b5490e-6ba0-11e7-9a2b-ceeca202a67e.png)

If I add `@include foundation-flex-grid;` after `@include foundation-everything($flex: true);` then it works. But it seems like that defeats the purpose of `($flex: true)`...doesn't it?

**Comment by brettsmason** [comment]
@designerdean you can set `$xy-grid: false;` in your settings file and that will use the flex grid rather than the XY grid when using the everything mixin. Probably needs better documentation on that.

**Comment by designerdean** [comment]
Ohhhhh...so if I swet `$xy-grid: false;` in my settings file, I assume my app.scss file should look like this?

![screen shot 2017-07-18 at 10 36 50 am](https://user-images.githubusercontent.com/729893/28328858-179df8da-6ba5-11e7-9b44-c9cad139ca1f.png)

**Comment by brettsmason** [comment]
Yep exactly.

**Comment by designerdean** [comment]
Perfect. Thank you so much for the help!

**Comment by brettsmason** [comment]
Great glad its working now. I think we need some docs changes to make this clearer so going to leave this open for now.

**Comment by idevtech** [comment]
I had the same problem and the fix worked. Documentation definitely needs updating to indicate if

@include foundation-everything(true)

which is what would be present to turn flexgrid on prior to 6.4 will be use the new XYGrid.

**Comment by DanielRuf** [comment]
Closing as https://github.com/zurb/foundation-sites/pull/10962 is merged so the docs are a bit more clear about this.
