### ISSUE TITLE
@include xy-grid; causing sass compiler errors ( ZF 6.4.1 )

### ISSUE THREAD

**Issue by Veraxus** [zurb/foundation-sites#10420]
`npm install` is now showing me some errors downloading Foundation components:

```
> node-sass@3.13.1 install /path/to/project/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall /path/to/project/node_modules/node-sass
> node scripts/build.js
```

## Pertinent Particulars
* foundation-for-sites 6.4.1
* npm 5.0.3
* node 8.1.4
* gulp CLI 1.3.0
* gulp Local 3.9.1

**Comment by IamManchanda** [comment]
cc @kball

**Comment by brettsmason** [comment]
@Veraxus thanks for reporting this. 
It looks like this is an error within the site template. The mixin should be `xy-grid-classes`. Can you change it to that and confirm it works? `xy-grid` is the mixin for applying grid properties to an element and was accidentally included in the docs for 6.4.

**Comment by kball** [comment]
I'm confused, probably because the original ticket has been edited... what I see now is an npm install error for `node-sass`? That is likely an upstream issue and my guess would be it will be resolved shortly

**Comment by brettsmason** [comment]
Yeah my reply was to a different issue - control the seems to be different now.

**Comment by Veraxus** [comment]
Sorry, I realized after I posted that those were two unrelated issues. I couldn't remember where I got `@include xy-grid;` from and assumed it was my mistake. If that slipped into the docs on accident, it makes sense.

I resolved the node sass issue by changing my project's node-sass dependency from `3.13.1` to `4.5.3`. All seems to be well, now.

**Comment by brettsmason** [comment]
@Veraxus Great glad all is working. Going to close this.
