### ISSUE TITLE
$block-grid-max variable in settings twice

### ISSUE THREAD

**Issue by bwydev** [zurb/foundation-sites#10432]
$block-grid-max is in settings.scss under both "3. The Grid" and "56. XY Grid". When using Float Grid whatever $block-grid-max is under The Grid will be overwritten by the XY Grid value (later in the file).

Suggestion:
$block-grid-max setting should occur only once and be moved to a separate heading until Float Grid is  removed. Or at least 1 or both commented out and notated.

**Comment by brettsmason** [comment]
@bwydev Thanks for reporting this. I'm thinking we should change the variable the xy grid uses to `xy-block-grid-max` - I'll get a PR up for it.
