### ISSUE TITLE
Introduce Lower media-query breakpoint for all

### ISSUE THREAD

**Issue by alokpant** [zurb/foundation-sites#10442]
Hello everyone,

This is not an issue but a general breakpoint concern I have which is bit confusing.

Provided breakpoints in Foundation is listed as follows:

// $small-breakpoint:  em-calc(640);
// $medium-breakpoint: em-calc(1024);
// $large-breakpoint:  em-calc(1440);
// $xlarge-breakpoint: em-calc(1920);

when user writes:
@media (min-width: $medium-breakpoint) it refers to 1024px and above.
@media (max-width: $medium-breakpoint), it refers to 1024px and below.

So when writing css such as:
```
<h1 class="style-on-breakpoint">CSS is awesome</h1>

.style-on-breakpoint {
  @media (min-width: $medium-breakpoint) {
    color: red;
  }
  
  @media (max-width: $medium-breakpoint) {
    color: blue;
   }
}

```
https://codepen.io/gorkhali/pen/xrvobm

Color of "CSS is Awesome":
1023px: blue
1024px: blue
1025px: red

Similarly for:
```
.style-on-breakpoint { 
  @media (max-width: $medium-breakpoint) {
    color: blue;
   }

  @media (min-width: $medium-breakpoint) {
    color: red;
  }
}

```
Color of "CSS is Awesome":
1023px: blue
1024px: red
1025px: red

So whether color is actually red or blue depends upon positioning of css.

Another use-case is:
```
// colors
$black:                     #000
$atlantis:                  #79d536
$candlelight:               #ffdf23
$dodger-blue:               #2dbbf9

// media querie breakpoint
// from foundation
$small-breakpoint:  640px
$medium-breakpoint: 1024px
$large-breakpoint:  1440px
$xlarge-breakpoint: 1920px

$width-of-sidebar: 230px

.main-container
  width: 100%
  
  @media (min-width: $medium-breakpoint)
    float: right
    margin-left: -230px

.inner-container
  background: $dodger-blue  

  @media (min-width: $medium-breakpoint)
    margin-left: 230px
    height: 100vh

.sidebar
  background-color: $black
  height: 100vh
  width: $width-of-sidebar
  
  @media (max-width: $medium-breakpoint)
    display: none
    
<div class="wrapper">
<div class="main-container">
  <div class="inner-container">
    MAIN CONTENT OF WEBSITE
  </div>
</div>

<div class="sidebar"></div>
</div>

```
https://codepen.io/gorkhali/pen/yXmddG

When working with two column layouts, the behavior may be that for bigger screens both columns are visible but for smaller devices (provided example: 1024px), sidebar will be hidden (and potentially only triggered by hamburger menu or so). Here is what happens at 1024px:

![screen shot 2017-07-21 at 12 11 36](https://user-images.githubusercontent.com/6135761/28459634-883f2a44-6e0e-11e7-99b2-ef28119b9cca.png)

Both media queries will be activated: 
- sidebar as expected will be hidden
- container will have margins as expected to fit sidebar

Because of this behavior there is a space where sidebar exists. Browser is working correctly as it should have. But definition of breakpoint is causing this behavior.

This is only an example at 1024px. It can be reproduced at each exact breakpoint.

As a user of Foundation, I have been provided breakpoints. I feel this behavior should automatically be handled by Foundation (behind the scenes).

Potential solutions (my approach to this):

Introduce lower-bound-breakpoint:

```
$small-lower-breakpoint: em-calc(639)
$medium-lower-breakpoint: em-calc(1023)
$large-lower-breakpoint: em-calc(1439)
$xlarge-lower-breakpoint: em-calc(1919)

current breakpoints:
$small-breakpoint:  em-calc(640);
$medium-breakpoint: em-calc(1024);
$large-breakpoint:  em-calc(1440);
$xlarge-breakpoint: em-calc(1920);

```

Having alot of breakpoints would be very confusing. This is something perhaps Foundation can do in the breakpoint to facilitate something like:
So when there is a media query:

```
@media (max-width: $medium-breakpoint)

```

it would work like ( < 1024px ) and not ( <= 1024px )

https://codepen.io/gorkhali/pen/XgvvxK

So until 1024 sidebar is visible. 1023 and sidebar is hidden.

Would this make sense? Or perhaps there is already better solution to this, if there is any I would love to know how you approach it.

Thank you.

**Comment by IamManchanda** [comment]
:+1:

**Comment by brettsmason** [comment]
@alokpant The code you posted is from version 5 of Foundation. Are you talking about Foundation 5 or 6? The CodePen you posted is using version 6 (with your added version 5 breakpoint code).

In version 6 breakpoints are handled differently: http://foundation.zurb.com/sites/docs/media-queries.html#the-breakpoint-mixin Basically you can do exactly wht you described in v6 by writing `@include breakpoint(medium down)` (notice the `down` keyword.

Can you confirm which version of Foundation you are using?

**Comment by alokpant** [comment]
@brettsmason Sorry for confusion. I am using previous version of Foundation. 5.5.3. I have updated codepen.

**Comment by alokpant** [comment]
@brettsmason I just tried it with new version of Foundation (following the instruction: https://github.com/zurb/foundation-sites-template#manual-setup). 

I just added following code:

```
// colors
$black:                     #000;
$atlantis:                  #79d536;
$candlelight:               #ffdf23;
$dodger-blue:               #2dbbf9;

$width-of-sidebar: 230px;
.main-container {
  width: 100%;
  @include breakpoint(large) {
    float: right;
    margin-left: -230px;
    }
  }

.inner-container {
  background: $dodger-blue;
  @include breakpoint(large) {
    margin-left: 230px;
    height: 100vh;
  }
}

.sidebar {
  background-color: $black;
  height: 100vh;
  width: $width-of-sidebar;

  @include breakpoint(large down) {
    display: none;
  }
}

TRANSLATED VALUES TO CSS ARE:

@media screen and (min-width: 64em)
.main-container {
    float: right;
    margin-left: -230px;
}

@media screen and (min-width: 64em)
.inner-container {
    margin-left: 230px;
    height: 100vh;
}

@media screen and (max-width: 74.9375em)
.sidebar {
    display: none;
}

```

(Sorry, i tried setting up using mixin on codepen, didn't succeed. this was easier for me).

For sidebar, I think the value should have been:
@media screen and (max-width: 63.9375em)
https://github.com/alokpant/foundation6-lowerbreakpoint/blob/master/src/assets/scss/_code.scss

I even tried:
```
@media screen and  #{breakpoint(xlarge down)} {
}
```
but still get same result (max-width: 74.9375em).

<img width="926" alt="screen shot 2017-07-22 at 13 56 53" src="https://user-images.githubusercontent.com/6135761/28490903-a6e9a1b8-6ee5-11e7-8302-6313b5240251.png">

HTML FOR IT:

```
<div class="wrapper">
<div class="main-container">
  <div class="inner-container">
    MAIN CONTENT OF WEBSITE
  </div>
</div>

<div class="sidebar"></div>
</div>
```

<img width="1280" alt="screen shot 2017-07-22 at 13 31 27" src="https://user-images.githubusercontent.com/6135761/28490770-927c7f28-6ee2-11e7-900e-49d770980251.png">

At 1024px, i get the empty space. Logically (large down) should work.

**Comment by colin-marshall** [comment]
@alokpant can you confirm this if is still an issue in Foundation 6 please? Thanks!

**Comment by alokpant** [comment]
@colin-marshall this was only an issue in Foundation 5.5.3. I have created own breakpoints to solve the problem. Please feel free to close the issue as the problem no longer exists on Foundation 6. Thank you.

**Comment by colin-marshall** [comment]
Thanks @alokpant!
