### ISSUE TITLE
Sass Imports

### ISSUE THREAD

**Issue by johnylaravel** [zurb/foundation-sites#10458]
# Import everything, or just a components we need?

I'm little confused, **why should I import everything**, and just include components I want, when in inspect element I see that all those imports are **slowing down** my site?

For example: I want to use just **_grid_**, **_accordion_**, and **_drilldownMenu_**. So, I don't understand why would I import badge, callout, orbit, pagination, tabs etc, when I'm not using them?

### Proof

-This is the image **with all imports**:
![foundation-sa-svim-importima](https://user-images.githubusercontent.com/30267900/28520153-ab15985c-706e-11e7-85b8-427ce01187d9.png)

------------------

-And, this is the image **with just few imports** for components I'm using(I imported global-styles and typography too, just to look nice)
![foundation-sa-samo-nekim-importima](https://user-images.githubusercontent.com/30267900/28520244-01bb73d4-706f-11e7-9e9b-7f630dfd9b61.png)

## Conclusion
Maybe I got something wrong here, I would like if someone could explain me why should I import everything when it's **slowing down** my site

NOTES: 
-I see that it's not generating any CSS from imports I don't use, but it still loads the files, which is slowing down the site. Or I got something wrong?
-I'm using it with Laravel, if somebody wants to know...

Thanks!

**Comment by SassNinja** [comment]
@johnylaravel I'm afraid I don't understand your issue.

Foundation's `@import` doesn't output any CSS.
```scss
@import 'settings';
@import 'foundation';
@import 'motion-ui';
````

To get actual CSS code you have to use `@include` to include the desired components.
If you only include what you mentioned you wouldn't get more than expected.
```scss
@include foundation-xy-grid-classes;
@include foundation-accordion;
@include foundation-drilldown-menu;
```

I've tested this with the zurb template and the generated app.css is 192kb (unminified) and 32kb (minified). There doesn't appear any `@import` in the app.css and there are not any additional files loaded.

Would please provide further details regarding your setup?

**Comment by IamManchanda** [comment]
Gonna close this based on above comment but feel free to reply if you are still facing issues

**Comment by johnylaravel** [comment]
I found what was the problem. It was webpakcs dev mode. When I'm in production, everything is fine.

Thanks anyway!
