### ISSUE TITLE
npm run prod. Gulp error

### ISSUE THREAD

**Issue by Daaner** [zurb/foundation-sites#10455]
npm run prod
Not compiled 

/js/app.js from UglifyJs
Unexpected character '`' [./~/foundation-sites/js/foundation.util.core.js:24,0][

**Comment by stonehz** [comment]
same error here when using create-react-app

**Comment by kball** [comment]
umm can you give a little more detail about what you're doing here? Perhaps a link to a codebase or something other way to reproduce?

**Comment by JeremyEnglert** [comment]
No response. Closing.
