### ISSUE TITLE
[Forms] Page Need to be updated with XY Grid Classes!

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10452]
http://foundation.zurb.com/sites/docs/forms.html

Anybody would like to take this up ??

**Comment by colinmackinlay** [comment]
I'll have a look - need a little project to learn XY grid anyway!

**Comment by sonicdivx** [comment]
Just saw your change. doesn't that break the intent of the row class? wonder if way to modify the row class to function differently within context of XY grid.  

But, really like that you figured out a way to fix. I am using XY grid for a project and was getting frustrated with form layout

**Comment by colinmackinlay** [comment]
Not sure what you mean @sonicdivx. My PR #10462 removes all references to the row class as I believe was requested.
What do you think @IamManchanda? Happy to tweak if I've got your intent wrong. If it's right then I'll do #10565 as well.

**Comment by IamManchanda** [comment]
@colinmackinlay I am busy with some tasks but will soon review up your PR 
Ofcourse, Go ahead with the PR for cards ... you don't need your code to be 100% correct to make a Pull request!

**Comment by sonicdivx** [comment]
yeah i was talking about carrying the row class into the XY grid. but if that is deprecated in XY grid then carry on :D
