### ISSUE TITLE
XY grid - grid frame, full height issue

### ISSUE THREAD

**Issue by brgrz** [zurb/foundation-sites#10457]
There's an issue with .grid-frame and .cell-block-y which don't get height: 100% (they only have the max-height: 100% set), which kinda defeats the point of a grid frame/app frame. The issue is that if the content within .cell-block-y doesn't overflow then it never hits the 100% height, which, if you have background applied results in columns that are too short and gives weird look.

The issue can be demonstrated if you delete some paragraphs from the official docs grid frame example. I'm attaching the photo for you to visualize what I mean:

![xy-grid-frame-height](https://user-images.githubusercontent.com/193816/28514399-21450b1c-705a-11e7-997b-89ab6d57df6d.png)

Imho most users will require those columns to take up 100%, especially when background is applied.

**Comment by brgrz** [comment]
I don't know if it's just me but I'm having huge issues with nesting those XY grids and keeping everything in line, especially full height but not having overflows cut off

see https://github.com/zurb/foundation-sites/issues/10571, it has a lot in common with this issue

**Comment by brgrz** [comment]
It's still required to manually put `height: 100%` to the `.cell-block-y` cells when you want them to be 100% height when there's not enough content in the cells. So this issue remains open even though I closed the related issue.

**Comment by kball** [comment]
Hmm... I think you're probably right that cell blocks should naturally expand to get to 100%, but would love to get some more opinions. What do you think @oxyc @JeremyEnglert @brettsmason @rafibomb?

**Comment by oxyc** [comment]
I actually subscribed to this issue as it hit me as well and I thought it was a bug.

**Comment by rafibomb** [comment]
Yeah - that's right, first child nested .medium-cell-block-container > .grid-x - merged PR!

**Comment by DanielRuf** [comment]
I guess https://github.com/zurb/foundation-sites/issues/10766 is about the same.

**Comment by DanielRuf** [comment]
> Yeah - that's right, first child nested .medium-cell-block-container > .grid-x - merged PR!

This did not really fix anything as far as we can see.

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/challenge-getting-a-full-height-sidebar/2391/3

**Comment by DanielRuf** [comment]
This is why I mentioned / linked it @davewsmith.

**Comment by davewsmith** [comment]
Adding that a manual style of `height: 100%` does not achieve the desired result. `height: 100vw` does.

**Comment by DanielRuf** [comment]
`100vw` is 100% of the viewport width, that is probably not correct. The `100%` worked in my cases. I also linked an issue by me regarding such a helper class.

**Comment by davewsmith** [comment]
Bizarre as it sounds, `100vw` makes my example work (on Chrome 81.0.4044.113). `100vh` works as well. But `100%` causes the sidebar and content area to collapse vertically to the maximum of their respective content sizes. Happy to send a complete, 'working' example.

**Comment by davewsmith** [comment]
Same odd behavior on Firefox 75.0

**Comment by DanielRuf** [comment]
100% may be different in your case depending on your box model (paddings) so `max-height: 100%` should work. Please let's continue in the forum.
