### ISSUE TITLE
XY Grid Offset Not Working According To Docs For .grid-y

### ISSUE THREAD

**Issue by klipie245** [zurb/foundation-sites#10454]
#### What should happen:
According to the Foundation Docs applying the class .small-offset-2 is supposed to offset with a margin top when using .grid-y
[XY Grid Offsets](http://foundation.zurb.com/sites/docs/xy-grid.html#offsets)

#### What happened instead:
The element is shifted over horizontally instead.

#### Browser(s) and Device(s) tested on:
Chrome

#### Foundation Version(s) you are using:
6.4.1

#### Test case link:
https://codepen.io/anon/pen/xLKyRL?editors=1100#anon-signup

**Comment by brettsmason** [comment]
@klipie245 Thanks for reporting this. The docs were written before the grid was 100% complete so this might be a bit of an oversight - there are currently now classes to vertically offset cells in a `y` grid.

@kball @IamManchanda  do you think we need to add some classes, or remove the docs mention? My feeling is there wouldn't be a need for offset on a vertical grid, but I could be wrong on this.

**Comment by IamManchanda** [comment]
We should be adding classes for it!

**Comment by brettsmason** [comment]
@IamManchanda OK I'll get onto it this week. WIll require a bit of a rework to the core offset classes as at the moment they will apply left margin to vertical grids, which we dont want.

**Comment by IamManchanda** [comment]
Vertical grid need to support offsets, source ordering and all other flex classes

**Comment by HARVS1789UK** [comment]
@brettsmason / @IamManchanda - This still seems to be an issue in Foundation 6.4.3?

Seeing as Float Grid and Flex Grid are now marked as "Legacy" and XY Grid is the only non-legacy grid type, this seems like a pretty big oversight? Are there still plans to fix this?

**Comment by JeremyEnglert** [comment]
@brettsmason - should we fix in F6 or wait for F7?

**Comment by IamManchanda** [comment]
@JeremyEnglert Seems like we should be fixing this up in v6 :)

**Comment by JeremyEnglert** [comment]
I'll leave it up to @brettsmason unless someone else wants to tackle it. This could be seen as a "feature request", as it's functionality that does not currently exist.

**Comment by jonathan-g** [comment]
Since this is not considered a bug, it would be good to fix the documentation to make it clear that this is functionality that does not currently exist. 

Otherwise, users just get confused and think it's our fault that we can't get `offset` to work as documented for `grid-y`.
