### ISSUE TITLE
Included example page shows horizontal scrolling

### ISSUE THREAD

**Issue by gmclelland** [zurb/foundation-sites#10459]
#### How to reproduce this bug:

1. Step one
Generate a new example site with foundation-cli using foundation new.  cd into the new project folder and run foundation watch to build the files.
2. Step two
View the generated example page in Google Chrome and resize the browser to a mobile size and notice the horizontal scrollbars. 

#### What should happen:
The page shouldn't show horizontal scrollbars

#### What happened instead:
The page showed horizontal scrollbars

#### Browser(s) and Device(s) tested on:
This happens in Google Chrome, Firefox, and Safari

#### Foundation Version(s) you are using:
6.4.1

The following seems to fix the problem:
```css
.grid-container {
overflow:auto;
}
```

Hope that helps

**Comment by gmclelland** [comment]
Actually to fix it, you have to use:
```css
.grid-container {
  overflow-x:hidden;
}
```

**Comment by brettsmason** [comment]
@gmclelland Actually grid container has been reworked for the next release (due out today I believe).
See the PR here: https://github.com/zurb/foundation-sites/pull/10371

Going to close this as it will be fixed and better documented with that release 😄
