### ISSUE TITLE
Switch Round Deprecated?

### ISSUE THREAD

**Issue by ryanjavens** [zurb/foundation-sites#10460]
Tell me I'm not crazy, but I believe that switches used to have a `round` class to add a radius to the container and inner button 😟 . I went back to a previous app that I was working on and noticed the class in my code but the feature seems to be lost in my current version (looks like I'm using 6.3.1). 

I dug a little bit through the issues in here and couldn't find anything about it. I just wanted to see if there was a reason why it was deprecated, potentially incompatibility issues on certain browsers, etc, so I don't make the same mistake by overriding the border radius' myself 😃 .

Thanks!

**Comment by Deckluhm** [comment]
You were probably using Foundation 5: http://foundation.zurb.com/sites/docs/v/5.5.3/components/switch.html

In Foundation 6, there is no more rounded switches: http://foundation.zurb.com/sites/docs/switch.html

**Comment by IamManchanda** [comment]
hhmmnnn... i think this should be integrated with this 
http://foundation.zurb.com/sites/docs/prototyping-utilities.html#component-styling

**Comment by rafibomb** [comment]
Yes this is a F5 class not in F6. It's easy enough to round a switch - this could be a prototyping style for sure but not core.
