### ISSUE TITLE
Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by lyndonkieljerymiah** [zurb/foundation-sites#10482]
Tab Foundation doesn't work when I  tried to bind it on the vue components I got an error. 
Cannot read property 'hash' of undefined.

//this is the directives
Vue.directive('ftab',{
    inserted(el) {
        $(el).foundation();
    },
    unbind(el) {
        $(el).destroyed();
    }
})

 
`<ul class="vertical tabs" data-tabs :id="tabId" v-ftab>`
`  <li class="tabs-title" v-for="(tab,index) in tabs" :class="tab.active ? 'is-active' : ''">`
`                         <a :href="'#'+tab.tabkey" aria-selected="true">{{tab.name}}</a>`
`                     </li>`
`</ul>`

**Comment by tw-maustin** [comment]
as a workaround I believe you can change your 'href' attribute to 'data-tabs-target'
```<a :data-tabs-target="'#'+tab.tabkey" aria-selected="true">{{tab.name}}</a>```

**Comment by DanielRuf** [comment]
Which line of the unminified foundation.js file throws this error?
Is it `window.location.hash` or `...link[0].hash.slice(1)`?

**Comment by joshuajonah** [comment]
I'm not the OP but I'm having the same issue, it's the line with

    hash = $tabLink.attr('data-tabs-target') || $tabLink[0].hash.slice(1),

**Comment by DanielRuf** [comment]
It should be probably fixed in the develop branch. Can you test it?

**Comment by joshuajonah** [comment]
Sure. I'm still looking a this problem.

**Comment by joshuajonah** [comment]
The thing that gets me if above that is says `$tabLink = $target.find('[role="tab"]'),`, It does not mention role="tab" anywhere in the documentation. I remember it used to back in 5 but that has not been in there for at least a year.

**Comment by ncoden** [comment]
All links should get `[role="tab"]` added at initialization. See https://github.com/ncoden/foundation-sites/blob/89a6f09f270b43ebcacbc1f4fb968f8cc3817be5/js/foundation.tabs.js#L64

@joshuajonah @lyndonkieljerymiah
* Do you have any link added dynamically ?
* Does links have `[role="tab"]` set after Tabs are initialized ?

**Comment by joshuajonah** [comment]
I didn't really recompile, I just npm installed the `develop` branch. 

And yes, I'm loading data from JSON with Vuejs to generate the HTML. Honestly, I've new switched to a vanilla JS Vue component instead as whole idea was to get off jquery.

**Comment by ncoden** [comment]
Yeah I did not seen `v-for="(tab,index)` in the example above.

@lyndonkieljerymiah You have to initialize the component by yourself after the link list is fully rendered.
```js
const $tabs = new Foundation.Tabs($('#tabId'), options);
```

Closing. Feels free to reopen if this is not working.

**Comment by K9Advantix53** [comment]
@ncoden 

> Do you have any link added dynamically ?

Does the tabs not work if they are added dynamically? (e.g., populated via an ajax call to an api?)

**Comment by DanielRuf** [comment]
> Does the tabs not work if they are added dynamically? (e.g., populated via an ajax call to an api?)

Not yet but in the next release as far as I remember.
In general no, you have to reinitialize your component then.
