### ISSUE TITLE
Docs assets sometimes unable to load

### ISSUE THREAD

**Issue by SassNinja** [zurb/foundation-sites#10489]
I'm often facing the issue the docs page is unable to load the assets. 
Either most of the CSS & JS is missing or the iconfont is missing. After reloading the page a few times everything works fine again.

Not sure if this is related to my network / location (Germany) or a general assets server issue.

Does anyone else have the same problem?

![screen1](https://user-images.githubusercontent.com/19912475/28829108-0e143ade-76d3-11e7-8c38-9407194a682a.png)
![screen2](https://user-images.githubusercontent.com/19912475/28829113-113c28b6-76d3-11e7-97a5-142d184acf82.png)

**Comment by Deckluhm** [comment]
I don't (France).

**Comment by SassNinja** [comment]
After some extensive testing we've discovered it's related to our internal network because it only occurs when connected with it.
The admins were able to detect the error but haven't found the reason yet.

Since it's no general issue I'm closing it.

@Deckluhm  thanks for your feedback
