### ISSUE TITLE
[Responsive Navigation] Responsive menu documentation is confusing, sketchy

### ISSUE THREAD

**Issue by fburleigh** [zurb/foundation-sites#10481]
I've spent the better part of a day getting a realistic responsive menu into shape. Along the way I ran into troubles like the "<- Back" affordance being on top of the (vertical) menu LI that opened it and stack traces (in browser console) from foundation.js parsing data-responsive-menu for the ResponsiveMenu plugin. I think these troubles are in part because the page:

http://foundation.zurb.com/sites/docs/responsive-navigation.html

leaves a lot to be guessed. Chiefly:

* What are the allowed values and their combinations for data-responsive-menu and what do these values actually do? Are the values related to CSS classes?

* The section on "Responsive Toggle" uses data-dropdown-menu but makes no reference to data-responsive-menu. That's perplexing. In practice, I needed the latter.

* The CodePens linked from the documentation (very nice!) make use of classes and data-* items whose relevance isn't clear: submenu, has-submenu, data-submenu for example. Their removal from the CodePen seems not to break anything; their presence encourages a kind of magical thinking then.

I do not mean to devalue the work of contributors to the Foundation project. Indeed, I hope to see the framework's value enhanced by making clearer how to use it most effectively.

Thanks!

**Comment by JeremyEnglert** [comment]
We're always happy to accept PR's to improve the docs. In F7 the docs will be vastly improved.



> What are the allowed values and their combinations for data-responsive-menu and what do these values actually do? Are the values related to CSS classes?

https://foundation.zurb.com/sites/docs/responsive-navigation.html#responsive-menu



> The section on "Responsive Toggle" uses data-dropdown-menu but makes no reference to data-responsive-menu. That's perplexing. In practice, I needed the latter.

This could be improved. Would make for a great first pull request! ;)




> The CodePens linked from the documentation (very nice!) make use of classes and data-* items whose relevance isn't clear: submenu, has-submenu, data-submenu for example. Their removal from the CodePen seems not to break anything; their presence encourages a kind of magical thinking then.

I believe those classes are added via JS when the page loads, so they are not needed in the markup.
