### ISSUE TITLE
XY Grid - Why to use it?

### ISSUE THREAD

**Issue by johnylaravel** [zurb/foundation-sites#10483]
Hey guys, I was super excited to see the **power of new XY Grid**, and I just finished all your tutorials, but I don't really see why it's better then **original css flexbox property**? I have a feeling that it is just new syntax for same things to get done. Maybe I'am wrong, so I would love to hear from you what I've missed.

-Basic Float Grid was awesome, it really saved a lot of pain. I would love to hear what **real problems of flexbox** this new XY Grid solves?

P.S. I saw Grid Frame, well done for that, but I don't see it useful for me

<br>

**Thanks guys, you are awesome**

**Comment by IamManchanda** [comment]
Vertical Grid, Margin-Padding Grid!

**Comment by Knight-Yoshi** [comment]
Future compatible with CSS Grid.

**Comment by rafibomb** [comment]
The margin spacing is really an upgrade, separating the container from the row helps reduce nesting issues. The auto shrink sizing now has responsive classes and lots more.
