### ISSUE TITLE
[Equalizer] Bottom White Space...why?

### ISSUE THREAD

**Issue by biapar** [zurb/foundation-sites#10485]
Hi,

I attach equalizer on a row, but when I load the page I've the columns with same height, but with a lot white bottom space. The space disappear after a while or try to resize the page.
Why?

Foundation 6.4.1

**Comment by Deckluhm** [comment]
Correct me if I'm wrong but this is the exact same issue than https://github.com/zurb/foundation-sites/issues/10005.

**Comment by biapar** [comment]
Yes. It's it.

**Comment by Deckluhm** [comment]
Can you close this one then please?

**Comment by biapar** [comment]
Related to #10005
