### ISSUE TITLE
Feature Request: PHP Supplementation

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation-sites#10480]
NOTABUG

I've got some great ideas for non-integrative PHP support. However, given that Foundation for Sites is a front-end library, would it be "incompatible" to add such support?

Here's the experiment I've been tinkering with:
https://github.com/paxperscientiam/foundation-sites/tree/composer-package

After cloning, just run `./test.sh` from the `./php-test` directory.

**Comment by Knight-Yoshi** [comment]
Add PHP support for what exactly, adding the classes/additional HTML that the JS adds? Some of that is determined dynamically from user events or resolution/view port size.

Doesn't seem practical if that's the case. Plus Foundation is server-side language agnostic. This seems like it would be better as a standalone PHP library/package that should be agnostic of PHP frameworks as well.

**Comment by paxperscientiam** [comment]
Hi @Knight-Yoshi , thanks for commenting.

As suggested, the package I have in mind would be *supplemental* as opposed to interchangeable.

One idea that I am keen on is dynamically generated grids / galleries.

For example:
````php
 $menu = new Menu();

  $menu->align("expanded")
    ->orient("vertical");

  $menu->setLinks([
    "home" => "/home",
      "cartography" => "/ca",
      "logos" => "/ld",
      "concepts" => [
        "british" => "#",
          "american" => [
            "NY" => "#"
          ]
      ],
      "projects" => "/dp",
      "original" => "/oi",
      "univision" => "/uv",
      "united-nations" => "/united-nations",
      "about" => "/am",
      "dropdown1" => [
        "one" => "#",
          "two" => "#",
          "three" => "#"
      ],
      "dropdown2" => [
        "A" => "#",
          "B" => "#",
          "C" => [
            "X" => "#",
              "Y" => "#"
          ]
      ]
  ]);
  echo $menu->getHTML();
````

Now, I'm just trying to gauge interest. It may make more sense to do this work independently. In fact, as you suggest, anything server-side related wouldn't jive with Foundation's front-end focus.

Hmmmm.

**Comment by Knight-Yoshi** [comment]
This is really more project-specific cases. These should be done in your project as either a widget or in a view. For instance, the framework I'm using has a Nav widget, but it uses Bootstrap. So, I made a PHP Menu widget for my project that's used to generate dynamic, Foundation-compatible menus.

However, it's not something that belongs in the Foundation project itself since it's dependent on the framework I use and my table structure.

**Comment by paxperscientiam** [comment]
> I made a PHP Menu widget for my project that's used to generate dynamic, Foundation-compatible menus

Have you made that code available?

> However, it's not something that belongs in the Foundation project....

Yeah, I agree. Thanks.

**Comment by Knight-Yoshi** [comment]
I have not. It's specific to the Yii2 framework and my table structure; i.e. requires an Active Record object - so it can't do static arrays. It's not something that's really able to be shared because of how tightly coupled it is with the framework and tables. :|
