### ISSUE TITLE
Huge margin problem with the XY Grid

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#10499]
Even just a simple use case like the one @rafibomb uses, produces a horizontal scrollbar, when using `grid-margin-x`. Firefox on Windows does not seem to have a problem with it. Chrome on Mac and Windows, as well as Safari show the scrollbar. 

https://codepen.io/anon/pen/ZJpRzp

here is a video from @rafibomb doing the exact same thing: 
https://youtu.be/Xl5DjEzKn1g?t=11m21s

maybe @brettsmason or @IamManchanda can comment on this as well.

**Comment by brettsmason** [comment]
@phifa This has been addressed in the latest RC. Basically you need to wrap your grid in `.grid-container` (with optional `.fluid` or `.full` classes to modify container behaviour).

If you want a full width grid but still want a gutter between cells, then the only way around this is to hide the overflow - [see here](https://github.com/zurb/foundation-sites/blob/develop/docs/pages/xy-grid.md#grid-container-full) in the docs (which will be live once 6.4.2 comes out).

Does that make sense?

**Comment by phifa** [comment]
ok, i see. glad it works with `.fluid`.  `body {overflow-x: hidden;}` seems like a hack though. is this really recommended practise?

**Comment by brettsmason** [comment]
@phifa There are a few options.

If the grid only had left margin (so gutters were applied as a whole on the left) this doesn't cause overflow. This would of been my personal preference with XY grid, but it was decided to keep split gutters instead. for V7 maybe, who knows?

Other options:
You could remove the right margin on the element yourself with an override class of some sort. We are limited to what we can do without limiting a single row of cells in a grid, and that wasn't desired behaviour either.

If you have any other suggestions let me know.

**Comment by phifa** [comment]
ok, i see. i like your idea - but maybe for v7 then. do i understand this correct, `.container-padded` is gone?

**Comment by brettsmason** [comment]
@phifa Yep correct.
The default `grid-container` class now adds the padding automatically unless you pair it with `.full`.

Also just to illustrate my left gutter only point, here's a hacked together pen to illustrate: https://codepen.io/brettsmason/pen/GvjPzY

**Comment by phifa** [comment]
interesting! looks promising! 
now i am using the rc2. there seems to be a bug now with this line

`grid-x grid-margin-x grid-margin-y small-up-1 medium-up-2`

on large I only get one element. if i add `large-up-3 ` I get three. Just a minor issue. If I use instead:
`grid-x grid-padding-x grid-margin-y small-up-1 medium-up-2` it seems to work. So something with the margin-x going on here.

**Comment by brettsmason** [comment]
@phifa Thanks for reporting. Could you paste your exact markup you are seeing the error with?
We are doing RC testing at the moment so I'll add a test and make sure we fix the issue.

**Comment by phifa** [comment]
sure!

```
	<div class="grid-container">
		<div class="grid-x grid-margin-x grid-margin-y">
			<div class="cell">
				<div>
					<div class="grid-x grid-margin-x grid-margin-y small-up-1 medium-up-2">
						<div class="cell flex-container">...</div>
					</div>
				</div>
			</div>
		</div>
	</div>

```

**Comment by brettsmason** [comment]
@phifa Thanks for posting the markup.

I've downloaded a fresh copy of the develop branch and ran your test case. This works as it should do now so looks like whatever bug this was has been fixed since RC2 (there has been a number of XY grid bug fixes since).

I'm going to go ahead and close this now, but any other issues you find please do add a new issue 😄 👍
