### ISSUE TITLE
Sticky Responsive Navigation "jumps slightly" in current Chrome

### ISSUE THREAD

**Issue by pablopaul** [zurb/foundation-sites#10496]
#### How to reproduce this bug:

1. Setup a new project with `foundation new` -> Zurb Template
2. Wrapped the [Responsive Toggle](http://foundation.zurb.com/sites/docs/responsive-navigation.html#responsive-toggle) markup into [Sticky](http://foundation.zurb.com/sites/docs/sticky.html#sticky-navigation)

```
<div data-sticky-container>
  <div class="" data-sticky data-options="marginTop:0;" style="width:100%">

    <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle="example-menu"></button>
      <div class="title-bar-title">Menu</div>
    </div>

    <div class="top-bar" id="example-menu">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text">Site Title</li>
          <li>
            <a href="#">One</a>
            <ul class="menu vertical">
              <li><a href="#">One</a></li>
              <li><a href="#">Two</a></li>
              <li><a href="#">Three</a></li>
            </ul>
          </li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li><input type="search" placeholder="Search"></li>
          <li><button type="button" class="button">Search</button></li>
        </ul>
      </div>
    </div>

  </div>
</div>
``` 

#### What should happen:
No "flickering" (1px jump) on the first scroll

#### What happened instead:
"Flickering" (1px jump) on the first scroll.
Download (the browser preview will not show the visual effect in favor of video compression) the following screencast, watch the upper left "Site Title": https://www.dropbox.com/s/jj5lnxc8i7umfzn/topbar-jump.mov?dl=1

#### Browser(s) and Device(s) tested on:
* Env: Mac OS X 10.15.5, Chrome Version 59.0.3071.115 (Offizieller Build) (64-Bit)
* Also Safari, not appearing in FireFox

#### Foundation Version(s) you are using:
* 6.4.1

#### Test case link:
- https://codepen.io/bassgang/pen/LjRpjV --> in the Codepen view this not happens

**Comment by brettsmason** [comment]
@pablopaul Judging by your markup I think this is due to lack of an anchor for the sticky element.
Assuming your page has a wrapper around it, simply give it an id and then add the `anchor: yourid` to your `data-options`, eg: `<div data-sticky data-options="marginTop:0; anchor: page;" style="width:100%">`

I tried this in Safari and this solved the jump. Can you try and let me know?

**Comment by pablopaul** [comment]
@brettsmason Thanks for the input, your suggestion fixed my problem. Any idea how to make that part more clear in http://foundation.zurb.com/sites/docs/sticky.html#sticky-navigation ?

**Comment by brettsmason** [comment]
@pablopaul Great glad that's working. I think perhaps a dedicated section detailing the need for an anchor might be helpful. I'll keep this issue open as a reminder for me to add something.
