### ISSUE TITLE
Orbit slider fallback for no javascript users

### ISSUE THREAD

**Issue by MarineLB** [zurb/foundation-sites#10493]
Hi, I just noticed that orbit sliders don't work without javascript (duh...) 
Now I'm wondering if there's a known CSS fallback for no js users. For example displaying only the first slide, or something.
Does anyone know how to do that ?

**Comment by kball** [comment]
@MarineLB There isn't a builtin fallback, but if you wanted to you could take advantage of the `no-js` class... the way that works is you put a `no-js` class on your html tag, and then the JS if it runs removes it... you can then have styling logic based on if that class exists.  So you could have something like

```
<div class="orbit" data-orbit">
///...
</div>
<img class="orbit-fallback" src=".."/>
```
and then in your css

```
.no-js .orbit, .orbit-fallback {
  display: none;
}
.no-js .orbit-fallback {
  display: block;
}
```

Anyway gonna close this issue as I don't think this behavior is something the framework needs to specify, but I think something along the above should get you where you want to go
