### ISSUE TITLE
[Orbit] CSS only version of Image Slider? Why Not?

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10508]
**Inspiration**: https://codepen.io/AMKohn/pen/EKJHf

---

Any Objections?
If yes, I really would like to know why ?

**Comment by rafibomb** [comment]
No reason not to other than:
- there's no timer
- images need to be the same size https://codepen.io/rafibomb/pen/mMwxXz

So no reason to not create a building block for this and see how it helps people.

**Comment by IamManchanda** [comment]
@rafibomb i would say in the **core** and specify the limitations of css only version!

Thoughts? @kball @brettsmason ??

**Comment by colin-marshall** [comment]
@IamManchanda closing out this feature request to be reconsidered in v7.
