### ISSUE TITLE
Invalid US-ASCII character &quot;\xE2&quot;

### ISSUE THREAD

**Issue by webels** [zurb/foundation-sites#10515]
foundation/scss/prototype/_relation.scss:94

The comment:
/// Will only select the child if it’s unique. That means that if there are at least 2 children, the style will not be applied.

Is giving an error, when I change the word "it’s" to "it's" (see apostrophe). It will work again.
Maybe someone else has this same issue?

**Comment by kball** [comment]
@IamManchanda I think this is probably yours

**Comment by IamManchanda** [comment]
Ohk sure will do it !

**Comment by IamManchanda** [comment]
Done #10551
