### ISSUE TITLE
Menu: white-space: nowrap

### ISSUE THREAD

**Issue by brgrz** [zurb/foundation-sites#10517]
What would be the reason for `.menu a { white-space: nowrap }` ? Seems pretty rigorous to have this in place on all menus. I guess it'd make sense in fully horizontal menus but not in accordion or other vertical navs.

**Comment by brgrz** [comment]
Also on the same issue, when we wrap the line-height should be reset to default (not 1).

**Comment by brettsmason** [comment]
@brgrz There is already an open PR to address the wrap: https://github.com/zurb/foundation-sites/pull/10512 which will be included in the release this week. I haven't touched the line height as this has been included for ages and I'm not sure the reason for it being there.

**Comment by brettsmason** [comment]
The PR has now been merged so this will be included in the next release.
Going to close this but feel free to raise a new issue if you have any other problems.
