### ISSUE TITLE
[Menu] Class .menu.icon-top no working

### ISSUE THREAD

**Issue by repoles** [zurb/foundation-sites#10518]
#### How to reproduce this bug:

1. Create a ul.menu.icon-top like in the documentation http://foundation.zurb.com/sites/docs/menu.html#icons

#### What should happen:

The icons should be oriented above the text.

#### What happened instead:

Nothing changes when the class .icon-top is added and and the icons stays positioned at the same row of the text.

#### Browser(s) and Device(s) tested on:

Safari - Version 10.1.2 (12603.3.8)
Chrome - Version 59.0.3071.115 (Official Build) (64-bit)

#### Foundation Version(s) you are using:

6.4.1

#### Test case link:

https://codepen.io/repoles/pen/VzPOzQ

**Comment by brettsmason** [comment]
@repoles This has actually been addressed in the upcoming 6.4.2 version, though its actually just a docs update. All you need to do is add `icons` as a class (as well as `icon-top`) in order for this to work correctly.

```
<ul class="menu icons icon-top">
  <li><a href="#"><i class="fa fa-list"></i> <span>One</span></a></li>
  <li><a href="#"><i class="fa fa-list"></i> <span>Two</span></a></li>
  <li><a href="#"><i class="fa fa-list"></i> <span>Three</span></a></li>
  <li><a href="#"><i class="fa fa-list"></i> <span>Four</span></a></li>
</ul>
```

See this thread for details: https://github.com/zurb/foundation-sites/issues/10290

Going to close this but the above should give you all the info you need 😄
