### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in ...

### ISSUE THREAD

**Issue by skruglikov** [zurb/foundation-sites#10511]
I try to connect the module Handlebars via app.js

app.js
`import Handlebars    from 'handlebars';`

I get an error when starting the project:
`[17:59:21] Error in plugin 'webpack-stream'
Message:
    ./~/handlebars/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/s.kruhlikov/Server/zurb.greeceyachts/node_modules/handlebars/lib'
resolve 'fs' in '/Users/s.kruhlikov/Server/zurb.greeceyachts/node_modules/handlebars/lib'
  Parsed request is a module
  using description file: /Users/s.kruhlikov/Server/zurb.greeceyachts/node_modules/handlebars/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/s.kruhlikov/Server/zurb.greeceyachts/node_modules/handlebars/package.json (relative path: ./lib)
    resolve as module`

**Comment by kball** [comment]
This looks like an issue with webpack or handlebars... I found this issue on the handlebars project that might help: https://github.com/wycats/handlebars.js/issues/1174
