### ISSUE TITLE
Grid Container is limited to 1440px regardless of Settings

### ISSUE THREAD

**Issue by ttyson99** [zurb/foundation-sites#10514]
<div class="grid-container grid-container-padded">
  <div class="grid-x">
    <div class="cell">
      <img src="http://via.placeholder.com/1600x150" alt="">
    </div>
  </div>
</div>

Change Settings:

$global-width: rem-calc(1600);
$breakpoints: (
  small: 0,
  medium: 640px,
  large: 1600px
);
$print-breakpoint: large;
$breakpoint-classes: (small medium large);

Resize browser.  Observe container above 1440px is padded.  Flush at 1440px and proper container padding below 1440px.

**Comment by brettsmason** [comment]
@ttyson99 Grid container has been reworked for 6.4.2 (out soon, currently in testing). 
The docs for the changes aren't live until the patch goes live, but you can [read the details here](https://github.com/zurb/foundation-sites/blob/develop/docs/pages/xy-grid.md#grid-container). 

I've tested in the latest RC and changing `$global-width` correctly changes the width of the grid container. However there is also the `$grid-container` variable which is what sets the width (defaults to `$grid-container: $global-width` unless you have changed that).

I'm going to close this as it should be working much better with the patch, but feel free to reopen/post a new issue if it doesn't fix it for you.

**Comment by ttyson99** [comment]
Thanks.  Yes I cloned the repo and it works on the current develop branch.

[Door IT Partners]<https://www.reddoorit.com/>Tony Tyson
CTO
Red Door IT Partners, Inc.
2201 Francisco Dr. #140-130, El Dorado Hills, CA 95762
M: +1 415 279 3610 | tony@reddoorit.com<mailto:tony@reddoorit.com>
