### ISSUE TITLE
Fresh clone fails on 'npm start'

### ISSUE THREAD

**Issue by Yugloocamai** [zurb/foundation-sites#10521]
#### How to reproduce this bug:

1. Step one 
Clone foundation-sites repo

2. Step two 
run npm install

3. Step three 
run npm start

#### What should happen: 
browser sync should load and the gulp tasks should run, including sass build

#### What happened instead:  
Missing dependency errors piled up...
```
Error: Cannot find module 'immutable'
Error: Cannot find module 'dev-ip',
Error: Cannot find module 'mime',
Error: Cannot find module 'base64id',
```
etc...

#### Browser(s) and Device(s) tested on: 
Chrome, MacOS

#### Foundation Version(s) you are using: 
6.4.1

**Comment by NaeemBinAhmed** [comment]
similar problem albeit with some other files missing.

**Comment by DanielRuf** [comment]
What is your Node.js and npm version?

**Comment by DanielRuf** [comment]
Hi @Yugloocamai and @NaeemBinAhmed, this may have been due to your Node.js or npm version and the installed dependencies. Sometimes peer dependencies are / were not correctly installed.

Can you still reproduce this issue with the latest releases?

**Comment by DanielRuf** [comment]
Can we close this? The issue is not reproducible and I guess this was some npm issue @ncoden.
