### ISSUE TITLE
off-canvas automatically scroll on first link

### ISSUE THREAD

**Issue by WnP** [zurb/foundation-sites#10523]
#### How to reproduce this bug:

1. Create an off-canvas like describe in [foundation off-canvas documentation](http://foundation.zurb.com/sites/docs/off-canvas.html)
2. Add a link at overlay bottom -out of screen height
3. Click on off-canvas trigger button

#### What should happen:

Off canvas overlay should opened and not scroll

#### What happened instead:

Off-canvas overlay directly scroll to first link -`a` tag- found in overlay

#### Browser(s) and Device(s) tested on:

Chrome Version 59.0.3071.115 (Developer Build) (64-bit)

#### Foundation Version(s) you are using:

6.4.1

#### Test case link:

- [codepen issue demo](https://codepen.io/WnP/pen/EvWEQL)

**Comment by brettsmason** [comment]
@WnP All you need to do is add `data-auto-focus="false"` to your off canvas. By default it focuses the first link in the off canvas so you have to disable this open.

Does that work for you?

**Comment by WnP** [comment]
@brettsmason that's great, sorry for the inconvenience I didn't figuring it out while reading the doc.

Thanks

**Comment by brettsmason** [comment]
@WnP No problem glad its working 👍
