### ISSUE TITLE
Missing semicolon in xy-grid/_classes.scss

### ISSUE THREAD

**Issue by Siqu** [zurb/foundation-sites#10529]
#### How to reproduce this bug:

1. Step one
Compile Foundation scss with xy-grid enabled.

#### What should happen:
Css should generate properly.

#### What happened instead:
error  (Line 415 of foundation-sites/scss/xy-grid/_classes.scss: Invalid CSS after "...grid-margin-y')": expected "}", was ".grid-frame.gri...").

At Line 414 a Semicolon is missing.

#### Foundation Version(s) you are using:
6.4.2

**Comment by brettsmason** [comment]
@Siqu Thanks for pointing this out. I've added a PR to fix this here: https://github.com/zurb/foundation-sites/pull/10531
