### ISSUE TITLE
Responsive Accordion Tabs: TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by arjendejong12** [zurb/foundation-sites#10520]
I'm using Foundation 6.4.2-rc2 in combination with npm, gulp-babel@6.1.2 (including source maps) and JointsWP 5. I get the following error when trying to use the Responsive Accordion Tabs component:
`TypeError: Right-hand side of 'instanceof' is not an object
    at e.value (foundation.responsiveAccordionTabs.js:304)
    at e.value (foundation.responsiveAccordionTabs.js:239)
    at e.value (foundation.responsiveAccordionTabs.js:200)
    at e.t (foundation.core.js:553)
    at new e (foundation.responsiveAccordionTabs.js:175)
    at HTMLUListElement.<anonymous> (foundation.core.js:356)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at String.<anonymous> (foundation.core.js:338)
    at Function.each (jquery.js?ver=1.12.4:2)
    at Object.reflow (foundation.core.js:330)
    at a.fn.init.t.fn.foundation (foundation.core.js:385)
    at init-foundation.js:1`

The code I've used can be found here: [Pastebin](https://pastebin.com/dbGYxtTX). I'm using Accordion as the base for this component. The accordion works only on small when using: `data-responsive-accordion-tabs="accordion medium-tabs large-tabs"`.
The component works on small AND medium when using `data-responsive-accordion-tabs="accordion medium-accordion large-tabs"` instead, so it seems the plugin fails when converting the accordion to tabs. This code is working inside the codepen examples found here when filing an issue, so I'm not sure why it's not working on my site.

**Comment by arjendejong12** [comment]
I'm still having this issue with 6.4.3 and gulp-babel@7.0.0. It would be great if anyone could give me a helping hand.

**Comment by maderesponsively** [comment]
I have the same issue. Did you manage to fix it @arjendejong12?

**Comment by arjendejong12** [comment]
I've replaced babel with webpack and pointed it to use the .js files in the /js/ folder, which fixed this issue for me.

**Comment by KiwiCreative** [comment]
@arjendejong12 could you possibly explain how you replaced babel with webpack in a way a noob like me could understand. I'm fairy new to web dev, so while I know how to write SASS/CSS, HTML, PHP and basic JS/jQuery, I've never used tools like babel and webpack. And honestly, I have to use CodeKit to compile my SASS as I kept getting errors trying to setup my environment manually per Foundation's instructions. 

I too use JointsWP and are getting the same errors you were when trying to use the responsive accordion tabs.

Any help would be greatly appreciated.

**Comment by JeremyEnglert** [comment]
This was solved in the JointsWP repo. You have to load the responsive accordion tabs after the other JS files.

https://github.com/JeremyEnglert/JointsWP/issues/273
