### ISSUE TITLE
Multiple Grids on XY Grid

### ISSUE THREAD

**Issue by kvinlambert** [zurb/foundation-sites#10539]
Just recently switched from the Float Grid to the XY Grid on 6.4.2 and I struggle to find a way to implement multiple grid semantically as Float Grid was capable of. 

It used to be possible through the grid-row() function as in this example:

    .container {
      @include grid-row(10) {
        .main-content {
          @include grid-column(7);
        }
        
        .sidebar {
          @include grid-column(3);
        }
      }
    }

How am I supposed to create a new grid-x with a custom number of columns with the new grid system? Seems to be also problematic with the Flexbox Grid, so I'm pretty sure I'm missing the functionality which is somewhere I imagine.

**Comment by brettsmason** [comment]
@kvinlambert You are right there isn't a mixin for doing what you describe from the float grid.
However you could easily do it like so:

```
.container {
  @include xy-grid;

    .main-content {
      @include xy-cell(7 of 10); // or 7/10
    }

    .sidebar {
      @include xy-cell(3 of 10); // or 3/10
    }
  }
}

Here's the function that the `xy-cell` mixin uses for its size calculation: http://foundation.zurb.com/sites/docs/xy-grid.html#xy-cell-size

The `xy-cell` mixin could use a slight docs update though to list you can use it in this way.

Does this help?

**Comment by kvinlambert** [comment]
Hi @brettsmason! Thanks for the help, that's what I ended up doing just after posting, and I guess it's the same result! ;)
