### ISSUE TITLE
Compilation error for 6.4.2 with Ruby Sass gem

### ISSUE THREAD

**Issue by BernhardWebstudio** [zurb/foundation-sites#10535]
#### How to reproduce this bug:

1. Install foundation-sites via npm
2. Create a *.scss stylesheet and @import "foundation";
3. Try to compile the stylesheet with Ruby/Compass/Sass

#### What should happen:

The stylesheet should be compiled just fine.

#### What happened instead:

The compilation fails with the following error:

```
error /Users/.../assetic_compassSyEUTp.scss (Line 415 of /Users/.../node_modules/foundation-sites/scss/xy-grid/_classes.scss: Invalid CSS after "...grid-margin-y')": expected "}", was ".grid-frame.gri...")
Compilation failed in 1 files.
```

#### Foundation Version(s) you are using:

Happens since 6.4.2

**Comment by katie1348** [comment]
I am also using Compass and have the same error.

Is this Compass related?
