### ISSUE TITLE
Orbit not working

### ISSUE THREAD

**Issue by lukeyouell** [zurb/foundation-sites#10530]
#### How to reproduce this bug:

1. Use orbit example from the documentation

#### What should happen:

1. You should be able to navigate between the slides

#### What happened instead:

1. Gets stuck on second slide
2. Can no longer navigate back and forth

#### Browser(s) and Device(s) tested on:

Latest Firefox and Chrome

#### Foundation Version(s) you are using:

6.4.2

#### Test case link:

https://codepen.io/lukeyouell/pen/BdZErK

**Comment by lukeyouell** [comment]
I've just noticed that Orbit behaves as expected after disabling animations. Potential issue with Motion UI?

**Comment by brettsmason** [comment]
@lukeyouell you have to make sure you have Motion UI loaded - its not included in the default download I don't think. Can you try adding it from here: https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.2.2/motion-ui.min.css and see if that solves your issue? It sounds like that's all it is.

**Comment by lukeyouell** [comment]
@brettsmason that looks to have sorted it, strange as Motion UI works in other cases (reveal for example)

Surely if the js is bundled into foundation.js, the css should be bundled into foundation.css also?

**Comment by brettsmason** [comment]
@lukeyouell glad its working!
@kball I am right in thinking the dist build doesn't have motion ui included right?

**Comment by kball** [comment]
@brettsmason that is correct. @lukeyouell the JS included has an adapter for the lib, not the lib itself, but yes it is still odd. We need to fix this for 7.
