### ISSUE TITLE
xy-grid gutters deprecation warning when updating to 6.4.2

### ISSUE THREAD

**Issue by jcuotpc** [zurb/foundation-sites#10534]
I installed foundation-sites 6.4.2 as a node module. 
I am using sass 3.5.1 and after uprading to 6.4.2 I get the following error:

    /usr/local/bin/sass` --no-cache --update base_foundation.scss:base_foundation.css

DEPRECATION WARNING on line 33 of ../../node_modules/foundation-sites/scss/xy-grid/_gutters.scss:
#{} interpolation near operators will be simplified in a future version of Sass.
To preserve the current behavior, use quotes:

  unquote("#{$operator}#{$gutter}")

You can use the sass-convert command to automatically fix most cases.

DEPRECATION WARNING on line 42 of ../../node_modules/foundation-sites/scss/xy-grid/_gutters.scss:
#{} interpolation near operators will be simplified in a future version of Sass.
To preserve the current behavior, use quotes:

  unquote("#{$operator}#{$gutter}")

You can use the sass-convert command to automatically fix most cases.

error ../../node_modules/foundation-sites/scss/xy-grid/_classes.scss (Line 415: Invalid CSS after "...grid-margin-y')": expected "}", was ".grid-frame.gri...")

Reverting to 6.4.1 makes the problem disappear.

**Comment by IamManchanda** [comment]
Wish `Z` was involved but even css grid cant do that!

FWIW, 
I have renamed the title to correct the typo.
