### ISSUE TITLE
XY grid - Margin issue with fixed position

### ISSUE THREAD

**Issue by johnylaravel** [zurb/foundation-sites#10532]
When I add "**grid-margin-x**" to grid, my **fixed div**(which has no connection to grid) just go up/down **out of the window** when scrolling. Why this happens and how to fix it?

**Simple code proof:**

```
<div style="position: fixed; top: 0; left: 0; background: red; width: 100%;">

    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, ducimus.

</div>


<div class="grid-x grid-margin-x">
   .cell*15
</div>
```

**NOTES:** look on small size screen, it's easier to realize the problem

**Comment by brettsmason** [comment]
@johnylaravel I've setup a CodePen with your code example: https://codepen.io/brettsmason/pen/MvOdWp

Could you explain the issue in more detail? I'm not understanding your problem.

**Comment by johnylaravel** [comment]
I'm 15 commits away from that, so now when I add "grid-margin-x" it give me scroll x, like whole website can move right and left. Website is out of window.

You can see that example in your pen, look at bottom scroll X. 

That problem can be solved for large screens by adding ".grid-container" as a wrapper. But the problem is now on small screen size, it don't work on small screen.. Do you have any solution for that?

Thanks for reply!

**Comment by JeremyEnglert** [comment]
@johnylaravel, can you provide a new test link and an explanation of what you're trying to do?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
Please let us know if there is new feedback and we will reopen the issue.
