### ISSUE TITLE
Why does reveal scroll on mobile?

### ISSUE THREAD

**Issue by SassNinja** [zurb/foundation-sites#10543]
I'm using a modified reveal on small screen size that doesn't have the default height of 100vh.
But then I've detected the plugin scrolls up on opening and restores the original scroll position after having closed the reveal.
This only occurs on mobile devices which are identified via user agent instead of media query.

I'm wondering why is this scrollTop reset & restoration necessary at all?
It isn't visible with the default height and looks weird if the reveal's height is less than 100vh.

**Can this 'feature' just be removed or is there any particular reason for this I'm missing?**

**Comment by SassNinja** [comment]
Here's a codepen to show what I mean:
https://codepen.io/KaiTheGreat/pen/xLPQJw

If you open it on a mobile device (or in dev tools with mobile user agent), scroll down a bit, click the button and the close the reveal, you can see the mentioned behavior.

**Comment by SassNinja** [comment]
I wasn't able to resist :smile: 
I've made a PR that adds a new option to disable this behavior: https://github.com/zurb/foundation-sites/pull/10546

But if this mobile behavior isn't desired at all / needed anymore, I would adjust my PR and remove it completely.

**Comment by kball** [comment]
It's not a desirable behavior - I believe it was inserted to try to capture scroll state as at some point on mobile (particularly ios) that was being lost... if this bug is no longer present (ie opening & closing reveal after scrolling stays at the same place) across ios and android by all means let's just ditch the behavior.

**Comment by patrick-huber** [comment]
I'm seeing the same behavior on my mobile reveals. I've added in a temporary workaround in my app js code (below), but would love to see pull request #10546 or a similar update make it in

```
// Fixing bug in reveal on mobile devices
var scrollPosition = 0;
var modalOpen = false;
var $reveal = $('.reveal');
$reveal.on('closeme.zf.reveal', function() {
  if(!modalOpen) scrollPosition = $(document).scrollTop();
});
$reveal.on('open.zf.reveal', function() {
  modalOpen = true;
});
$reveal.on('closed.zf.reveal', function() {
  $(document).scrollTop(scrollPosition);
  modalOpen = false;
});;
```

**Comment by SassNinja** [comment]
I'm closing this as the current code in develop seems to be fixed: the scrollTop is preserved in my tests.

I only had a problem on iOS. But I've made a PR for this:
https://github.com/zurb/foundation-sites/pull/10786
