### ISSUE TITLE
Code Snippet Missing 'left' for Off-Canvas

### ISSUE THREAD

**Issue by mandimey** [zurb/foundation-sites#10548]
Yo Rafi! 

In the code snippet for the off-canvas panel and button, the IDs don't match. As a result, the button doesn't trigger the panel to slide. The panel ID is offCanvas and the button toggle is offCanvasLeft. See http://foundation.zurb.com/sites/docs/off-canvas.html#complete-example + Click Trigger section. 

<3

**Comment by JeremyEnglert** [comment]
@mandimey - would you like to submit a Pull Request to fix this?

**Comment by DanielRuf** [comment]
Hi @mandimey would you have the time to provide a PR and need any assistance or can I provide a PR?

**Comment by DanielRuf** [comment]
Closimg as this was fixed with https://github.com/zurb/foundation-sites/pull/10981
