### ISSUE TITLE
Add an option to specify additional breakpoint classes to the customizer page

### ISSUE THREAD

**Issue by brgrz** [zurb/foundation-sites#10542]
Often enough the customizer works fine for most projects but lacks one crucial feature which is the ability to either specify which breakpoint classes should be generated or turn on the additional two for larger screens (xlarge and xxlarge).

I'm currently working on a project where I have to change the settings and compile manually (which I have troubles with, see https://github.com/zurb/foundation-sites/issues/10541) only to enable those two additional breakpoints (everything else I need is already covered by the customizer).

This would be a nice feature to have.

**Comment by JeremyEnglert** [comment]
We'll consider this for F7.

Check out the Sass version. You can easily adjust these.
