### ISSUE TITLE
Please fix the docs re: visibility

### ISSUE THREAD

**Issue by udf2457** [zurb/foundation-sites#10540]
Hello,

The current docs are confusing on the topic of visibility !

Head on over to `http://foundation.zurb.com/sites/docs/visibility.html` and you get told:

> Depreciation Notice: From v6.5.x, we are moving visibility classes to Prototype specific mode and thus visibility classes will be disabled by default. You can re-enable it though, with a simple @include.

Ok, great, so we head on over to `http://foundation.zurb.com/sites/docs/prototyping-utilities.html` and we get told:

> Prototyping classes like these below should only be used for prototyping tasks. Also if you are using Sass, we encourage you to use Prototyping Mixins instead. 

and

> Not all projects require Prototyping Utilities and adding utility classes like these increase your CSS file size especially if you're not using all of them. For these reasons Prototype mode is disabled by default.

and

> For display: none use .hide. or Foundation's Visibility Classes

So the documentation is both confusing ("use prototyping... but don't use prototyping") and in an infinite loop ("for none or hide, use visibility classes" ... whose doc page then points you back to prototyping !).

So, please guys, make your minds up.   Is Visibility going or not ?  

If it is going then please clarify the current preferred way to do visibility in prototyping (and if that is the case, perhaps tweak the wording so that prototyping classes sound less like something you would only use for prototyping, but actually have real-life uses like visibility).

If visibility is not going anywhere, then fix the wording on the visibility page. 

Thank you. ;-)

**Comment by IamManchanda** [comment]
I think it makes sense that we don't depreciate visibility classes!
Moreover, I think we need a separate Utility section...

Float classes, and text alignment should be moved though

**Comment by IamManchanda** [comment]
Please check #10632 

BTW I was the only one who added dep notice to visibility classes at first place ... but I have to say I agree with you!

**Comment by DanielRuf** [comment]
I guess this is already solved as the PR is merged or is something missing or some more feedback needed here?

**Comment by Bakuryu** [comment]
This is still very confusing. Are visibility classes being moved to prototype class and if so why?

**Comment by ncoden** [comment]
@Bakuryu. No, visibility classes are not moved to prototype classes. The warning is incorrect and I am looking at why it is still visible.

**Comment by ncoden** [comment]
I found why this notice is still there.

https://github.com/zurb/foundation-sites/pull/10632 did removed this notice, merged in september 2017 in https://github.com/zurb/foundation-sites/commit/647a42f28ca6d7b080c37992499727c7716a046d on `develop`...

But a change has been made on the same spot in August 2017 in https://github.com/zurb/foundation-sites/pull/10519 on `master`, and `master` got merged into `develop` this April (https://github.com/zurb/foundation-sites/pull/11175#issue-181668644).

My bad, I made some mistake in conflict resolution and did not removed the notice while merging.
