### ISSUE TITLE
Switch to Popper.js for tooltips/dropdowns positioning?

### ISSUE THREAD

**Issue by FezVrasta** [zurb/foundation-sites#10544]
I see you have a lot of logic to handle the tooltips and popovers position, but still the result is far from optimal.  
For instance, I see the tooltips won't flip to stay into viewport area if they overflow it.

Have you considered the idea to drop all your custom logic and rely on something like Popper.js?

Bootstrap v4 makes use of it and everything works nicely.

Project page: https://popper.js.org
Repo: https://github.com/FezVrasta/popper.js

**Comment by IamManchanda** [comment]
Ah we like to use our own code for this type of stuff 

See 
Thread => https://github.com/zurb/foundation-sites/issues/9989
Inspiration => https://github.com/zurb/foundation-sites/issues/9799
PR => https://github.com/zurb/foundation-sites/pull/10053

**Comment by IamManchanda** [comment]
> Have you considered the idea to drop all your custom logic and rely on something like Popper.js?

cc @kball but if you ask me I dont think so...

**Comment by IamManchanda** [comment]
Btw just saw that you are the creator of the popper framework... So what are the benefits of Popper over current [JS](http://foundation.zurb.com/sites/docs/dropdown.html#explicit-positioning) code of ours @FezVrasta ??

**Comment by FezVrasta** [comment]
I already provided a little explanation on the initial post. I'm going to write a comprensive list tomorrow is it's not a problem for you. It's a bit late here right now

**Comment by IamManchanda** [comment]
No issye i will be waiting!

**Comment by FezVrasta** [comment]
So, one of the problems I see is that the popovers/dropdowns/tooltips (poppers) don't attempt to appear (and stay) in the viewport, as you can see from this gif, they just appear in a non visible portion of the page.

![1](https://user-images.githubusercontent.com/5382443/29409053-dd4e00b8-834a-11e7-8dce-ef165365263f.gif)

I don't exactly know what's happening here, but looks like your algorithm have some problems detecting the correct place where to place the dropdowns:

![2](https://user-images.githubusercontent.com/5382443/29409151-411a191a-834b-11e7-9de0-1889dc34ffd8.gif)

Form my tests, I see that your algorithm doesn't support scrolling containers:
![3](https://user-images.githubusercontent.com/5382443/29409236-9f829914-834b-11e7-8c5b-d84faf6769c3.gif)

And last but not least, the PR that introduced the smart positioning in foundation added ~1500 rows of code you have to test and maintain.

Popper.js is ~2000 rows, included huge JSDocs comments, and has a code coverage of ~90% with lot of automated tests.

I think a switch to it would save you a lot of hassle and would provide a better experience to your users.

**Comment by IamManchanda** [comment]
Thanks a lot @FezVrasta ... This satisfies me ... 
Althought we like to keep our dependency very low and short but me and even @kball (had a talk for the same today morning) are very open about it... 

But will need other people thoughts also 
cc @brettsmason @SassNinja @rafibomb @paxperscientiam

**Comment by SassNinja** [comment]
I agree to the downsides @FezVrasta has described regarding the current plugin.
The reposition doesn't seem to work 100% reliable to me for all scenarios, it doesn't get reset if possible (I've already made a [PR](https://github.com/zurb/foundation-sites/pull/10522) for this) and it doesn't consider scrolling outside the viewport while being opened.

So in my eyes it's not wrong to use a well-tested positioning engine instead of a custom solution if it can be integrated into the current code without breaking backwards compatibility (or at least without the need to change a lot).

**Comment by IamManchanda** [comment]
> Yeah there is nothing bad in having a single positioning library instead of bunch of custom implementations that never reach a mature state. 

We have to agree that not many tests/work have gone through our explicit positioning and it wont even happen coz foundation need to think broad and not just positioning 
If there is something good as popper that can be used as positioning library then why not!

**Comment by kball** [comment]
Would happily accept a PR for this, but as @SassNinja points out backwards compatibility is important.

**Comment by IamManchanda** [comment]
@FezVrasta Would you like to do a PR for this ?

@kball I would say dont target this on 6.5 but 7 (Nov Release)

**Comment by FezVrasta** [comment]
I don't know if I'll have time in these weeks. If I manage to finish my work I'll see if I'm able to work on this.

**Comment by IamManchanda** [comment]
I don't think there is any rush if its targeted for F7...

**Comment by IamManchanda** [comment]
V7 requests are being closed for the time being. We have them labeled so we can readdress them in the future.
