### ISSUE TITLE
compilation issue with node-sass and foundation version 6.4.2 from npm

### ISSUE THREAD

**Issue by brgrz** [zurb/foundation-sites#10541]
When I add Foudation for Sites through npm there's a file `foundation.scss` inside the `scss` folder which seems to include everything needed but when I compile it using `node-sass` it just renders out the following CSS

```
/**
 * Foundation for Sites by ZURB
 * Version 6.4.2
 * foundation.zurb.com
 * Licensed under MIT Open Source
 */
```

So obviously something's not working right. I also uncommented the `settings.scss` import resulting in the same output.

What's the correct way to compile Foundation as quick as possible (without a custom build process)? The docs at http://foundation.zurb.com/sites/docs/sass.html are a bit vague.

**Comment by brgrz** [comment]
There's also an issue with util import in setting.scss

@import 'util/util';

which should be

@import '../util/util';

Still, after correcting that only the comment I posted above gets rendered in the resulting CSS.
I guess I must be doing something wrong.

Please note, I really don't want to implement a full blown build process for my case.

**Comment by BernhardWebstudio** [comment]
Have you followed the steps described in [Adjusting CSS Output](http://foundation.zurb.com/sites/docs/sass.html#adjusting-css-output)? When I create my own .scss stylesheet, `@import 'foundation';` and `@include foundation-everything;`, it works as expected.

**Comment by brgrz** [comment]
Oh my. Thanks for that. I created a new scss file and did as you said and it worked. I was under impression I could just compile the foundation.scsss file, which apparently is not the case.

**Comment by RiZKiT** [comment]
If someone else stumbles upon this issue, take a look at this: https://github.com/zurb/foundation-sites/blob/develop/meteor-README.md#3-overwrite-foundation-settings
