### ISSUE TITLE
An input inside an .input-group is higher than an ordinary input

### ISSUE THREAD

**Issue by repoles** [zurb/foundation-sites#10554]
#### How to reproduce this bug:

1. Use a grid to position an input and an input-group side by side (CodePen code bellow).
2. Use Chrome or Safari inspect element tool to check the height of both inputs.

#### What should happen:

Both inputs should have the same height.

#### What happened instead:

The ordinary input is 39px height.
The input inside input-group is 42px height.

![screen shot 2017-08-18 at 13 29 11](https://user-images.githubusercontent.com/1004592/29468792-13c25226-841c-11e7-95ed-c6bb8bcc3116.png)

#### Browser(s) and Device(s) tested on:

Safari Version 10.1.2 (12603.3.8)
Chrome Version 60.0.3112.101

#### Foundation Version(s) you are using:

6.4.2

#### Test case link:

https://codepen.io/repoles/pen/rzJpBg

#### Fix suggestion:

Maybe this is not the best solution, but to adjust the height of an input inside an input-group, I edited Foundation _input-group.scss and:

1. Inside `.input-group` selector, added `height: $height;` in line 31.
2. Changed line 25 `$height: ($input-font-size + $form-spacing * 1.5);` to `$height: ($input-font-size + $form-spacing * 1.44);`.

**Comment by kball** [comment]
@gskaplan I know you were recently working on inputs & input groups, is this something you could/would like to take a look into?

**Comment by gskaplan** [comment]
I don't know if I have enough time to jump into this - I am in a crunch right now. For the record, input fields, buttons, anchors, and selects all need to be looked at very closely. I may try and put together a pen that illustrates all of these controls living together.

**Comment by DanielRuf** [comment]
Already fixed in the latest releases.
See https://codepen.io/DanielRuf/pen/eYOvENL
