### ISSUE TITLE
[Sticky] sticky erroring out for simple layout

### ISSUE THREAD

**Issue by 8uddishh** [zurb/foundation-sites#10557]
#### How to reproduce this bug:

1. Download and setup zurb template
2. under partials folder add tobBar.html and include that in default.html using {{> topBar }}
Content of the topbar.html is
```
<div data-sticky-container>
  <div class="title-bar" data-sticky data-options="marginTop:0;" style="width:100%" data-top-anchor="1" data-btm-anchor="content:bottom">
    <div class="title-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Site Title</li>
      <li>
        <a href="#">One</a>
        <ul class="menu vertical">
          <li><a href="#">One</a></li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </li>
      <li><a href="#">Two</a></li>
      <li><a href="#">Three</a></li>
    </ul>
    </div>
    <div class="title-bar-right">
        <ul class="menu float-right">
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>
    </div>
  </div>
</div>
```
3. npm start will create the files and load the browser

#### What should happen:
1, Sticky should work

#### What happened instead:
1. We will see that there is one console error and sticky is not sticky anymore
```
pt = anchor.offset().top;

```
#### Browser(s) and Device(s) tested on:
Google chrome on Mac

#### Foundation Version(s) you are using:
"foundation-sites": "~6.4.1"

**Comment by mattbag** [comment]
@8uddishh 
You're using anchor that apparently you don't set in the page, so those attributes break it.
The docs are just chucking everything in the example but if you look at the codepen demo:

https://codepen.io/IamManchanda/pen/aWaJpM?editors=1010

**Comment by JeremyEnglert** [comment]
Thanks @mattbag! Closing.
