### ISSUE TITLE
Native Range Slider not styled properly on `-webkit...` browsers

### ISSUE THREAD

**Issue by farrago** [zurb/foundation-sites#10553]
The Native Range Slider - http://foundation.zurb.com/sites/docs/slider.html#native-range-slider - does not appear to be rendering properly on Chrome, Safari, or iOS Safari.

In particular, the _thumb_ is not positioned over the middle of the _track_.  Instead the top of the _thumb_ aligns with the top of the _track_, causing most of the _thumb_ to hand below the track.

> Screenshot from Windows + Chrome
![f6-native-range-bug](https://user-images.githubusercontent.com/995072/29466404-b1acd71e-8434-11e7-8b73-41f68ef09124.png)

#### How to reproduce this bug:

1. Open Chrome on Windows, Chrome or Safari on OSX, or Safari on iOS.
2. Go to http://foundation.zurb.com/sites/docs/slider.html#native-range-slider
3. Check the look of the native range input

#### What should happen:

I assume it should be styled similar to how it looks for the JS Slider - big blue square thumb, etc.
This is also how the native slider looks on Windows + Firefox and Edge.

#### What happened instead:

- The thumb is in the wrong place.  Not centred on the track.
- The thumb appears to just be the browser default style (e.g small rectangle on Windows+Chrome, small circle on OSX+Chrome and both Safaris

- Windows Chrome
Screnshot as above

- Safari, iPhone SE, iOS 10.3.3
> Screenshot from iOS Safari
![f6-native-range-bug-ios](https://user-images.githubusercontent.com/995072/29468029-8a9cc37c-843a-11e7-9ad1-acb7f9837b8c.png)

#### Browser(s) and Device(s) tested on:
❌ = styling doesn't appear to work correctly
👍 = styling does appear to work correctly

- Windows 10, x64
  - ❌ Chrome 60.0.3112.90 (Official Build) (64-bit)
  - 👍 Firefox 54.0.1 (32-bit) and 55.0.2 (32-bit)
  - 👍 Microsoft Edge 40.15063.0.0
  - 👍 Internet Explorer 11.0.45

- iOS, iPhone SE, iOS 10.3.3
  - ❌ Safari

- OSX (sorry, don't know versions, but should be up to date)
  - ❌ Safari
  - ❌ Chrome 

#### Foundation Version(s) you are using:
Foundation 6.4.2

#### Test case link:
http://foundation.zurb.com/sites/docs/slider.html#native-range-slider

**Comment by farrago** [comment]
Fixed by merged PR #10562.

**Comment by rushikeshk-gdb** [comment]
I have implemented rangeslider in chrome browser but without passing input value parameter "overflow- hidden" it doesn't work properly.

**Comment by DanielRuf** [comment]
@rushikeshk-gdb please create a new issue and fill out the issue template.
