### ISSUE TITLE
Hovering Delay issue with Responsive Navigation

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [zurb/foundation-sites#10559]
#### How to reproduce this bug:

I've used "Drilldown Dropdown Responsive Menu" and I am facing this issue:
![foundation-responsive-menu-issue](https://user-images.githubusercontent.com/12660951/29509818-eede94ac-8672-11e7-92b3-1edeb7116a21.png)

https://codepen.io/IamManchanda/pen/jmKPdM?editors=1010

Could anyone please tell me how to stop hover delay?

**Comment by IamManchanda** [comment]
Couldn't reproduce! 
See video screenshot => https://drive.google.com/file/d/0B4EN5uGMUjoZeUZJdTBLN3pNT1k/view

( PS: Video attached is getting processed right now, so you may need to check back 5 minutes later from now )

**Comment by kashifullahwebdeveloper** [comment]
Thank you, @IamManchanda for your quick reply.

  If you observe closely, there is a small delay, when you hover over **Item1B** the **Item1A sub-menu** still show, but I actually want to make **Item1A submenu** to hide more quickly, when hovering over Item1B.

Let me know in case, I am not conveying it correctly.

**Comment by IamManchanda** [comment]
I understand... I am not sure if that can happen or not!
cc @kball

**Comment by kball** [comment]
@kashifullahwebdeveloper try setting `data-closing-time` to a small (or 0) number on your menu. see https://codepen.io/kball/pen/vJzjwY?editors=1010

This is utilizing the options from dropdown menu (see http://foundation.zurb.com/sites/docs/dropdown-menu.html#js-options) as the responsive menu is made up of the individual menu pieces, so their options work.

Going to close this as I believe it resolves your issue, please reopen if you're still having trouble.

**Comment by kashifullahwebdeveloper** [comment]
@kball, Thank you so much.

Yes, that fixed my issue. 👍
