### ISSUE TITLE
[Smooth Scroll] Not included in 6.4.2

### ISSUE THREAD

**Issue by webfed** [zurb/foundation-sites#10564]
The js file foundation.smoothScroll.js is not present so it does not work. Several reports in [forum](http://foundation.zurb.com/forum/posts/53650-no-smooth-scroll-on-64)

**Comment by IamManchanda** [comment]
cc @kball

**Comment by webfed** [comment]
My fault, didn't update with bower to last version

**Comment by IamManchanda** [comment]
No issue @webfed
