### ISSUE TITLE
[Accordion Menu] text over opne/close icon

### ISSUE THREAD

**Issue by amagdic** [zurb/foundation-sites#10560]
think about adding in:

.accordion-title {
  padding-right: 2.5rem;
}

#### How to reproduce this bug:
add long text in .accordion-title

#### What should happen:
text dont cover +/- button

#### What happened instead:
text cover +/- button

#### Browser(s) and Device(s) tested on:
FF, chrome, opera
#### Foundation Version(s) you are using:
6.4.2

**Comment by JeremyEnglert** [comment]
I think this needs to be handled on a case by case basis. The exact side of the margin will depend on how large the icon is. We'll think of better ways to implement this in F7.
