### ISSUE TITLE
[Dropdown Menu] Incorrect documentation

### ISSUE THREAD

**Issue by Karl456** [zurb/foundation-sites#10563]
Just been racking my brains out as to why the events for Dropdown menu weren't working, seems like this is because the documentation is incorrect.

The documentation (found here: http://foundation.zurb.com/sites/docs/dropdown-menu.html#Item-2) says:
```
show.zf.dropdownMenu
hide.zf.dropdownMenu
```

When this should be (notice the lower-case M):
```
show.zf.dropdownmenu
hide.zf.dropdownmenu
```

**Comment by DanielRuf** [comment]
This will be finally fixed by https://github.com/zurb/foundation-docs/pull/24
