### ISSUE TITLE
Zurb Template Issue - Settings File outdated

### ISSUE THREAD

**Issue by HansUXdev** [zurb/foundation-sites#10574]
#### How to reproduce this bug:
Use the CLI...

#### What should happen:
Ideally the settings file and app.scss file should compile correctly by either copying the settings file from node packages or created from scratch using octophant.

#### What happened instead:
```
he map $offcanvas-sizes instead
Backtrace:
	node_modules/foundation-sites/scss/components/_off-canvas.scss:78, in mixin `off-canvas-basics`
	node_modules/foundation-sites/scss/components/_off-canvas.scss:439, in mixin `foundation-off-canvas`
	src/assets/scss/app.scss:32

WARNING: $offcanvas-vertical-size is deprecated and not used anymore! Please update your settings and use the map $offcanvas-vertical-sizes instead
Backtrace:
	node_modules/foundation-sites/scss/components/_off-canvas.scss:82, in mixin `off-canvas-basics`
	node_modules/foundation-sites/scss/components/_off-canvas.scss:439, in mixin `foundation-off-canvas`
	src/assets/scss/app.scss:32
```
#### Browser(s) and Device(s) tested on:
N/A
#### Foundation Version(s) you are using:
"foundation-sites": "~6.4.1"

**Comment by kball** [comment]
This has been fixed in https://github.com/zurb/foundation-zurb-template/pull/69
