### ISSUE TITLE
Responsive Typography technique

### ISSUE THREAD

**Issue by dlewand691** [zurb/foundation-sites#10573]
This isn't an issue so much as it is a request. With all the discussion around responsive typography, a new solution has emerged that seems to be a solid solution. Take a look at RFS (Responsive Font Sizes) by Martijn Cuppens:

[https://blog.intracto.com/rfs-automated-scss-responsive-font-sizing](https://blog.intracto.com/rfs-automated-scss-responsive-font-sizing)

**Codepen demo:**
[http://codepen.io/MartijnCuppens/pen/ZBjdMy](http://codepen.io/MartijnCuppens/pen/ZBjdMy)

Overall the flexibility is excellent and allows for smooth sizing of fonts across any browser size. This is especially nice because it eliminates the media-query "jump" between breakpoints. 

Take a look and see if this might be worth integrating into a future release of world's best framework!

**Comment by colin-marshall** [comment]
Thanks for this feature request. We’re going to close out this ticket, as we will not be adding more features to Version 6, but your request is being considered for Version 7.
