### ISSUE TITLE
[Abide] Flags for color pattern?

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10588]
I am regular expression these days and I am amazed why aren't we using flags 
See => [Regular Expressions - Advanced searching with flags](https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions#Advanced_searching_with_flags) 

What i mean here is for example => [foundation.abide.js#L562](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.abide.js#L562)
The current regex is redundant => `/^#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$/`
The correct Regex would be => `/^#?([a-f0-9]{6}|[a-f0-9]{3})/i`

and secondly why aren't we using the `g` flag ... Is it intentional ?
cc @kball

**Comment by DanielRuf** [comment]
Related https://github.com/zurb/foundation-sites/issues/10590
