### ISSUE TITLE
[Build Error] Getting error on running foundation locally

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10584]
```
harman@manchanda: 06:28 am foundation-sites (develop) $ npm start

> foundation-sites@6.4.3 start /opt/lampp/htdocs/zurb/fork/foundation-sites
> gulp

[06:28:18] Using gulpfile /opt/lampp/htdocs/zurb/fork/foundation-sites/gulpfile.js
[06:28:18] Starting 'clean'...
[06:28:18] Finished 'clean' after 5.18 ms
[06:28:18] Starting 'copy'...
[06:28:18] Finished 'copy' after 8.36 ms
[06:28:18] Starting 'docs:all'...
[06:28:18] Starting 'sass:deps'...
[06:28:18] Starting 'javascript:plugin-core'...
[06:28:18] Starting 'javascript:deps'...
[06:28:18] Starting 'javascript:docs'...
[06:28:18] Starting 'watch'...
[06:28:18] Finished 'watch' after 217 ms
[06:28:19] Finished 'javascript:deps' after 694 ms
[06:28:20] Supercollider: processed abide.html in 0.75 s with sass, js
[06:28:20] Supercollider: processed accessibility.html in 0.54 s

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./js/foundation.core.js
Module parse failed: /opt/lampp/htdocs/zurb/fork/foundation-sites/node_modules/babel-loader/lib/index.js!/opt/lampp/htdocs/zurb/fork/foundation-sites/js/foundation.core.js The keyword 'undefined' is reserved (212:26)
You may need an appropriate loader to handle this file type.
|         var plugClass = this.data('zfPlugin'); //determine the class of plugin
| 
|         if (plugClass !== undefined && plugClass[method] !== undefined) {
|           //make sure both the class and method exist
|           if (this.length === 1) {
 @ ./js/entries/plugins/foundation.core.js 3:0-51
 @ multi ./js/entries/plugins/foundation.core.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-sites@6.4.3 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundation-sites@6.4.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/harman/.npm/_logs/2017-08-27T00_58_20_968Z-debug.log

```

**Comment by IamManchanda** [comment]
**and here is the log** 

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/heroku/bin/node', '/usr/local/bin/npm', 'start' ]
> 2 info using npm@5.3.0
> 3 info using node@v8.3.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle foundation-sites@6.4.3~prestart: foundation-sites@6.4.3
> 6 info lifecycle foundation-sites@6.4.3~start: foundation-sites@6.4.3
> 7 verbose lifecycle foundation-sites@6.4.3~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle foundation-sites@6.4.3~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/opt/lampp/htdocs/zurb/fork/foundation-sites/node_modules/.bin:/usr/local/heroku/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/lampp/bin:~/.composer/vendor/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/harman/git-apps/hub-linux/bin/:/home/harman/.config/composer/vendor/bin
> 9 verbose lifecycle foundation-sites@6.4.3~start: CWD: /opt/lampp/htdocs/zurb/fork/foundation-sites
> 10 silly lifecycle foundation-sites@6.4.3~start: Args: [ '-c', 'gulp' ]
> 11 silly lifecycle foundation-sites@6.4.3~start: Returned: code: 1  signal: null
> 12 info lifecycle foundation-sites@6.4.3~start: Failed to exec start script
> 13 verbose stack Error: foundation-sites@6.4.3 start: `gulp`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
> 13 verbose stack     at emitTwo (events.js:125:13)
> 13 verbose stack     at EventEmitter.emit (events.js:213:7)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> 13 verbose stack     at emitTwo (events.js:125:13)
> 13 verbose stack     at ChildProcess.emit (events.js:213:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:927:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 14 verbose pkgid foundation-sites@6.4.3
> 15 verbose cwd /opt/lampp/htdocs/zurb/fork/foundation-sites
> 16 verbose Linux 4.4.0-77-generic
> 17 verbose argv "/usr/local/heroku/bin/node" "/usr/local/bin/npm" "start"
> 18 verbose node v8.3.0
> 19 verbose npm  v5.3.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error foundation-sites@6.4.3 start: `gulp`
> 22 error Exit status 1
> 23 error Failed at the foundation-sites@6.4.3 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
>

**Comment by kball** [comment]
This looks like a babel configuration problem, have you recently changed anything about your babel config?

**Comment by IamManchanda** [comment]
I mean where you mean ?

Outside of Foundation Folder? ... Yes I tweaked babel.rc for learning generators... But that's it to my best of knowledge

```bash
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 Chrome versions"]
      }
    }]
  ]
}
```

**Comment by IamManchanda** [comment]
Apart from this @kball ... There is one thing more ... 2 days back I installed Meteor on my system!

**Comment by kball** [comment]
This turns out to be showing up in newer versions of node, due to an interaction between the code webpack is emitting and a change in the behavior of `undefined` in ES7. The fix is updating webpack, PR incoming
