### ISSUE TITLE
off-canvas in-canvas: on resize move from off-canvas to in-canvas without adding class .is-closed

### ISSUE THREAD

**Issue by kbachl** [zurb/foundation-sites#10585]
#### How to reproduce this bug:

1. Step one: go to http://foundation.zurb.com/sites/docs/off-canvas.html, section In-Canvas to Off-Canvas

2. Step two: look at classes for the item that has 
class="off-canvas in-canvas-for-large position-right is-transition-overlap is-closed"

3. Step three: resize viewport to trigger the off-canvas button, open this off-canvas element with button so it looks like in code: 
class="off-canvas in-canvas-for-large position-right is-transition-overlap is-open"

4. Step four: resize the viewport with still open off-canvas menu window to large again, css code should now read:
class="off-canvas in-canvas-for-large position-right is-transition-overlap is-closed"
instead it reads:
class="off-canvas in-canvas-for-large position-right is-transition-overlap is-open"
while the in-canvas-for-large is already in effect, effectively breaking anything that relies on proper is-open/ is-closed state

#### What should happen:
on viewport resize it has to recalculate if it is still off-canvas open or closed

#### What happened instead:
see above

#### Browser(s) and Device(s) tested on:
chrome; IOS; 

#### Foundation Version(s) you are using:
6.4.3

Main problem I see here that on viewdirection (rotate) change on mobile it breaks layouts;

**Comment by kball** [comment]
@SassNinja can you take a look at this?

**Comment by SassNinja** [comment]
@kball sure, I'll take a look at it this evening (quite busy at the moment)

**Comment by SassNinja** [comment]
@kbachl I'm not a full-time freelancer but I might help you on this nevertheless. I've done quite a lot off-canvas-in-canvas transformations for my company because it was required to avoid duplicate content.

Whether it's going to end up in a PR depends on how useful the final component is for the majority of the users and how large the code is since we aim to keep the framework as lightweight as possible.

However, since this is not related to the issue here I'd suggest you contact me via email to discuss the details of that component
kai.falkowski@gmail.com

**Comment by kbachl** [comment]
@SassNinja thanks, I've already written to you 

Regarding the issue: it also seems that the drilldown-component is not working in an in-canvas to off-canvas scenario in case it is in a hidden state e.g.: .show-for-small-only

reason seems also that the _resizing doesnt get fired on viewport resizing because the element stays at      max-width: 0px;

**Comment by SassNinja** [comment]
I've taken a deeper look and the missing update of the classes `is-opened` and `is-closed` is not the only problem here: The overlay itself remains visible!

So what's actually missing is a trigger of the close event once the in-canvas override isn't active any more. At the moment the in-canvas feature is CSS only and doesn't affect the JS in any way.

@kball what do you think? Is it fine for you if I extend the JS accordingly so it considers the in-canvas classes?

@kbachl regarding the drilldown issue you've mentioned: this is not related to the off-canvas.
The issue occurs outside of any off-canvas as well if the drilldown menu has `display: none` on document ready (when it gets initialized).

You should create a new issue for this.
