### ISSUE TITLE
[Abide] Most Regular expressions need to refactor

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10590]
1. `i` flag for both cases .. so that code is not reduntant
2. `\w` instead of `a-zA-Z0-9` ... See => https://www.w3schools.com/JSREF/jsref_regexp_wordchar.asp ... as Less code helps shorten bugs, first rule of programming

Concerned Code => [foundation.abide.js#L533-L570](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.abide.js#L533-L570)

**Comment by SassNinja** [comment]
less code (not [Less](http://lesscss.org/) code) is usually a good idea!
So `\w` instead of `a-zA-Z0-9` sounds good to me.
But I wouldn't always use the `i` flag because there are patterns where case sensitivity matters.

**Comment by IamManchanda** [comment]
>  (not [Less](http://lesscss.org/) code)

We use Sass :stuck_out_tongue_winking_eye:

**Comment by DanielRuf** [comment]
Especially the url and email patterns have to be updated.

PS: w3fools is not a good resource.
I'll prepare different solutions for the patterns (new ones) and benchmark them.

**Comment by DanielRuf** [comment]
@SassNinja what had you in your mind? Let's get this forward together.

**Comment by DanielRuf** [comment]
Also unicode chars are not supported by these. We need new and better rules here.

**Comment by SassNinja** [comment]
@DanielRuf are you talking abt working over the whole abide regex?

This issue & the related PR (https://github.com/zurb/foundation-sites/pull/10593) were supposed to simplify the current regex – but not change the logic.

To answer your question: I didn't have anything in mind except of the simplification.
I think if we're going to work over regex logic we should close the current PR and create a new one.

**Comment by DanielRuf** [comment]
Imho it makes sense to update all of them.

> domain : /^([\w]([\w\-]{0,61}[\w])?\.)+[a-z]{2,8}$/i

There are new gTLDs which are longer than 8 characters.

**Comment by DanielRuf** [comment]
Also a -z will not be sufficient.
