### ISSUE TITLE
theme for wordpress with foundation 6.

### ISSUE THREAD

**Issue by pedro1958** [zurb/foundation-sites#10596]
Hola
Estoy constuyendo un tema para wordpress con foundation 6.
Al configurar el menu con este código:

`<?php
$args = array(
	'theme_location' => 'menu-1',
	'menu_id'        => 'primary-menu',
	'items_wrap'     => '<ul id="%1$s" class="%2$s vertical medium-horizontal expanded text-center">%3$s</ul>',
);
wp_nav_menu($args);
?>`

Al visualizar el tema en un navegador solo se ven los items del menu y de los submenu, estos estan a la izquierda y en forma vertical.
La version que uso para generar el proyecto con foundation cli es 2.2.3.
Necesito ayuda urgente, soló falta el menú para entregar el proyecto.
Saludos desde Chile
PD: Estoy usando Google Traductor.
-----------------------------------------------------------------------------------------------
Hello
I am building a theme for wordpress with foundation 6.
When configuring the menu with this code:

`<?php
$args = array(
	'theme_location' => 'menu-1',
	'menu_id'        => 'primary-menu',
	'items_wrap'     => '<ul id="%1$s" class="%2$s vertical medium-horizontal expanded text-center">%3$s</ul>',
);
wp_nav_menu($args);
?>`

When viewing the topic in a browser only the items of the menu and submenu are visible, these are on the left and vertically.
The version I use to generate the project with foundation cli is 2.2.3.
I need urgent help, only the menu to deliver the project is missing.
Greetings from Chile
PS: I'm using Google Translator.

**Comment by mattbag** [comment]
@pedro1958 it is probably a css issue, can you provide a screenshot?
I think your goal is not translated well enough by google, can you try to explain it more?

**Comment by pedro1958** [comment]
Hola mattabag

![capturapantalla](https://user-images.githubusercontent.com/6249763/29899179-4a0612d4-8dc0-11e7-8acf-9ece8dd1eb00.png)

Esto es lo que ocurre, acá te dejo el código css:
li{
    float: none;
}

Saludos desde Chile

**Comment by pedro1958** [comment]
Hello @mattbag
What difference is there in the _setting.scss file that is in the scss folder that is created in the root of the project generated with foundation-cli version 2.1.0 and version 2.2.3 ?.
Copy the file mentioned above, generated in version 2.1.0 in the project generated with version 2.2.3 and the difficulty that comments on 08-29-2017 was solved.
regards
