### ISSUE TITLE
[Reveal] Focusses on last anchor point on the page

### ISSUE THREAD

**Issue by rinseringma** [zurb/foundation-sites#10604]
#### How to reproduce this bug:

1. Step one
Create a one Reveal modal with some content.

2. Step two
Create multiple buttons with data-open="MODAL_ID" on the same page. Example:
- Button in the navbar
- Button somewhere in the content
- Button in the footer

3. Step three
Click on the first button (navbar) and close the modal with the close button or by clicking on the body.

#### What should happen:
Just close the modal and not jump down to the last anchor on the page.

#### What happened instead:
The page jumps down to the last anchor with "data-open="MODAL_ID" and focusses it.

#### Browser(s) and Device(s) tested on:
- Google Chrome
- Mozilla Firefox
- Safari

#### Possible solution:
https://stackoverflow.com/a/45511863

**Comment by Lazerproof** [comment]
Have this issue too

**Comment by rinseringma** [comment]
Any progress regarding this bug?

**Comment by kball** [comment]
This looks similar to https://github.com/zurb/foundation-sites/issues/9766 which @hikouki fixed in https://github.com/zurb/foundation-sites/pull/10360

I suspect the fix would be similar. @hikouki or any of the others on this issue want to take a crack at implementing it?

**Comment by bryananthonylewis** [comment]
I'm having this same issue too. Any progress on this?

**Comment by Owlbertz** [comment]
Problem here is that we need to set back the focus to the anchor that opens the modal to ensure best experience for keyboard users. The current implementation seems to not respect multiple anchors for one modal (`this.$anchor.focus();` is used here, which simply sets focus to the last element of the collection of anchors).

Possible workaround would be of course what @bryananthonylewis suggested above. I will create a PR that addresses this issue.

**Comment by JeremyEnglert** [comment]
A fix was submitted for this. Closing.

**Comment by DanielRuf** [comment]
> My code is updated (I'm on 6.5-RC1), so it includes the code from the patch 9fce99e in my foundatino.reveal.js.

Is it really the file that is used and imported?

**Comment by kristiansp** [comment]
I didn't import this actual branch, but my file has those changes in them. On line 235 I have:
`this.$activeAnchor = $(document.activeElement).is(this.$anchor) ? $(document.activeElement) : this.$anchor;`

On line 479 I have:
`this.$activeAnchor.focus();`

Commenting out the last line (with `focus()`) works as a temporary fix.

I could send a link to a practical example, if that would be helpful, but as the site is not finished and public, I'd prefer to send that by email.

**Comment by Legym** [comment]
I am experiencing the same issue as @kristiansp when I am using firefox dev edition (latest). This problem does not happen in chrome

**Comment by ahukkanen** [comment]
Same issue here too using `6.4.3`.

**Comment by kristiansp** [comment]
Hm, `npm update` doesn't seem to find the `6.5.0-rc.4` version. It's also not listed in the available versions: https://www.npmjs.com/package/foundation-sites

**Comment by DanielRuf** [comment]
cc @Owlbertz

**Comment by DanielRuf** [comment]
@Bakuryu you can use `patch-package` to make a patch or any other path strategy.

**Comment by andmej** [comment]
Seems to be fixed in 6.5.0-rc3: https://codepen.io/Rinse06/pen/eEbjGb

**Comment by kristiansp** [comment]
@andmej Doesn't seem that way for me. Also in your codepen, if you open the Reveal with Button 1 and close it, you will see the page still jumps to the bottom.

**Comment by nbeers22** [comment]
It's still doing it for me on `6.5`. I overwrote it with this:

`
    $('button').on('click',function(){
      $(this).focus();
    });`

with `$('button')` being the modal toggle

**Comment by illycz** [comment]
When I'm using open method this problem still exist.

**Comment by nbeers22** [comment]
Did you try changing the focus?

**Comment by illycz** [comment]
With custom close button?

**Comment by nbeers22** [comment]
Change the focus to focus on your button that opens the modal. If you're
opening it some other way then change the focus to whichever element on the
page you want.

**Comment by illycz** [comment]
OK, thanks, but I think that is bug.

**Comment by ahukkanen** [comment]
> OK, thanks, but I think that is bug.

I agree with @illycz, should be considered a bug when this happens by default.
