### ISSUE TITLE
Wrong version for meteor + wrong dependancy for fourseven:scss

### ISSUE THREAD

**Issue by mackgorski** [zurb/foundation-sites#10606]
Foundation wont work properly with meteorjs. In latest version of the package from atmosphere there is not latest version of foundation - what I get is zurb:foundation-sites@6.4.1 instead of zurb:foundation-sites@6.4.3 and what's more it is tied to very old fourseven:scss@3.4.1 instead of fourseven:scss@4.5.4 - this prevents the meteor server from auto refreshing on scss file change and many more if even anyone can be successful in in installation.
#### How to reproduce this bug:
1. `$ meteor add fourseven:scss@4.5.4`
2. `$ meteor add zurb:foundation-sites`

#### What should happen:
Should install packages without any problems. And properly refresh browser automatically on every scss file change.

#### What happened instead:
```
meteor add zurb:foundation-sites
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint fourseven:scss@3.4.1 is not satisfied by fourseven:scss 4.5.4.
Constraints on package "fourseven:scss":
* fourseven:scss@4.5.4 <- top level
* fourseven:scss@3.4.1 <- zurb:foundation-sites 6.4.1
```

#### Foundation Version(s) you are using:
I want the latest one 6.4.3 but meteor shows 6.4.1 :/ no option of change.

Please make it work! Also please provide a path where the foundation files are stored in meteor after downloading.

**Comment by danwild** [comment]
This is still a major issue, the atmosphere pkg is quite outdated at this point, to the point of being unusable. 

However; thankfully by following @juliancwirko's [great example](https://github.com/juliancwirko/meteor-npm-foundation-test) I have been able to use foundation `v6.4.3` + `fourseven:scss@4.9.0`.

I'm guessing npm might be preferred approach going forward to eliminate overhead of maintaining atmosphere pkgs...

**Comment by juliancwirko** [comment]
@danwild yes, in newest versions of Meteor there is no need to use package from atmosphere. It was built before it was possible to simply use npm packages and imports.

**Comment by ncoden** [comment]
@danwild @juliancwirko See https://github.com/zurb/foundation-sites/pull/10825#issuecomment-399265805

> Actually, this introduced an issue: Foundation is considered as compatible anymore with older Meteor versions (but it should be).
>
> I think we can use the following version range instead:
> ```
> fourseven:scss@3.4.1 || 4.0.0'
> ```
> 
> I lost a lot of time searching for this "version range" thing in Meteor so I hope this will works. The Atmosphere ecosystem has serious issues with compatibility management compared to npm.
