### ISSUE TITLE
Sticky unexpected behaviour

### ISSUE THREAD

**Issue by lukeyouell** [zurb/foundation-sites#10609]
For some strange reason the sticky plugin works on the homepage but nowhere else. I've included the code that is outputted on the homepage compared to another page below:

Homepage (working)

`<div class="navigation sticky is-anchored is-at-top" data-sticky="" data-anchor="body" data-margin-top="0" data-resize="soest9-sticky" data-mutate="soest9-sticky" data-e="r9vs4j-e" style="max-width: 1170px; margin-top: 0px; bottom: auto; top: 0px;" data-events="resize">`

Different page (not working)

`<div class="navigation sticky" data-sticky="" data-anchor="body" data-margin-top="0" data-resize="tv07in-sticky" data-mutate="tv07in-sticky" data-e="ck7s6p-e">`

As you can see the code is missing classes as well as the hard-coded styling. What could be causing this?

#### Browser(s) and Device(s) tested on:

Chrome (latest)

#### Foundation Version(s) you are using:

6.4.3

**Comment by lukeyouell** [comment]
Anyone?

**Comment by mattbag** [comment]
Well it definitely depends on what else you're running on those pages...
I suggest to strip it down with the working version/codepen, make a unified layout, then add the different pieces

**Comment by lukeyouell** [comment]
@mattbag @kball it doesn't work here either - https://codepen.io/lukeyouell/pen/RLWXKo

**Comment by mattbag** [comment]
You're missing $(document).foundation(); in your js

**Comment by colin-marshall** [comment]
@lukeyouell I believe @mattbag's advice resolved this issue. If it is still an issue, feel free to reopen. Thanks!
