### ISSUE TITLE
drilldown menu wont work in case it has no visibilit on render

### ISSUE THREAD

**Issue by kbachl** [zurb/foundation-sites#10607]
see discussion here: 
https://github.com/zurb/foundation-sites/issues/10585

Problem is that on tag a max-width:0 gets put by js as the dimensions are 0:0 on initial view render as its invisible; I at least suggest that never a max-width:0 shall be rendered (makes never sense) and that the JS has to re-run each time the viewport size changes

**Comment by JeremyEnglert** [comment]
Can you provide more details on what you're trying to achieve and provide a test link? I'll be happy to reopen this ticket.
