### ISSUE TITLE
defer loading javascript: sticky not working

### ISSUE THREAD

**Issue by tobyhage** [zurb/foundation-sites#10618]
Hello,

Sticky is not working when javascript is loaded with function below.
When loaded via `<script src="/assets/js/src.min.js"></script>` Sticky is working.

   see also: [https://varvy.com/pagespeed/defer-loading-javascript.html](https://varvy.com/pagespeed/defer-loading-javascript.html) 

`<script>`  
    `function downloadJSAtOnload() {`
   `var element = document.createElement("script");`
   `element.src = "/assets/js/src.min.js";`
    `document.body.appendChild(element);`
    `}`
    `if (window.addEventListener)`
    `window.addEventListener("load", downloadJSAtOnload, false);`
    `else if (window.attachEvent)`
    `window.attachEvent("onload", downloadJSAtOnload);`
    `else window.onload = downloadJSAtOnload;`
`</script>`
  
Is this a bug or can i change something to make this working?

**Comment by zauni** [comment]
The sticky plugin is waiting for the `load` event on the window, and in your code, the `load` event already fired when you insert foundation in the document. So you have to insert foundation earlier that the plugins recognize the `load` event.

**Comment by colin-marshall** [comment]
@tobyhage I'm closing this out. If @zauni's advice didn't help you resolve the problem, feel free to reopen. Thanks!
