### ISSUE TITLE
[Feature Request] Pills

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10612]
I know foundation focuses on structure rather than styles 
and pills are just styled tabs... etc. etc. but still 

https://codeburst.io/part-2-bootstrap-4-vs-foundation-6-4-responsive-navigation-containers-f691cff8f06e

> **Tabs & Pills**
> _Unfortunately, pills isn’t supported yet within Foundation Framework._

Examples 
1. https://codepen.io/IamManchanda/pen/VzRPVY 
2. https://codepen.io/IamManchanda/pen/qXojLz

**Comment by IamManchanda** [comment]
Also want you guys to look at this => http://bulma.io/documentation/components/tabs/#styles

**Comment by colin-marshall** [comment]
@IamManchanda closing out this feature request to be reconsidered in v7.

P.S. Great job on the articles on codeburst.io! I had not seen these yet.
