### ISSUE TITLE
Select arrow disappears when changing browser colours

### ISSUE THREAD

**Issue by danmitchell-** [zurb/foundation-sites#10619]
#### How to reproduce this bug:

*This is just one method of changing the colours of a website there are several plugins that to do too*

1. Step one
Open Firefox and visit `about:preferences#content`

2. Step two
Change the background to any dark color

3. Step three
De-select "Use system colors"

4. Step four
Go to Override the colours specified by the page with your selections above and select "Always". 

#### What should happen:
The arrow should render

#### What happened instead:
The arrow is not loaded and the white background is removed -
<img width="787" alt="screen shot 2017-09-06 at 16 00 51" src="https://user-images.githubusercontent.com/3071606/30119083-93332418-931c-11e7-882a-4b85841f5b1d.png">

#### Test case link:
http://foundation.zurb.com/sites/docs/forms.html

**Comment by colin-marshall** [comment]
@danmitchell- sorry for the late response. This thread there are some explanations for the problem:
https://support.mozilla.org/en-US/questions/1193062

Not really anything we can do about it, as it appears to intentionally remove background-images when the override is set to always. You can even see arrows and the search icon removed from the page when you do it on that Mozilla link above. Closing this out.
