### ISSUE TITLE
[Sticky] Sticky navbar container height recalculation on scroll makes the content jump up & down

### ISSUE THREAD

**Issue by thomasfrobieter** [zurb/foundation-sites#10620]
#### How to reproduce this bug:

1. Step one
Open http://foundation.zurb.com/sites/docs/sticky.html#sticky-navigation
2. Step two
Scroll up and down

#### What should happen:
The navbar container height should just reserve the initial height of the navbar
Like this: https://codepen.io/zurbchris/pen/rxMaoX

#### What happened instead:
The container height get's updated if scrolled down

#### Browser(s) and Device(s) tested on:
Windows 10, Firefox

#### Foundation Version(s) you are using:
6.4.2

#### Test case link:
http://foundation.zurb.com/sites/docs/sticky.html#sticky-navigation

**Comment by thomasfrobieter** [comment]
PS: If i set data-check-every="-1" manually makes no difference, setting it to "0" is exactly the same behavoir.

"Number of scroll events between the plugin's recalculating sticky points. Setting it to `0` will cause it to recalc every scroll event, setting it to `-1` will **prevent recalc on scroll.**"

**Comment by Arredatore** [comment]
So, "data-top-anchor='1'" just makes the sticky element sticky forever. What isn't my case. And the weird behaviour of the page under the reveal still there.
I didn't understand where I can tweak the data-check-every="-1" though.
Anyway, I think the problem somewhere in the initialization because it works perfectly when started on a big screen, and doesn't when open on the small screen

**Comment by Arredatore** [comment]
Sorry, I have answered in wrong place. Just sound similar, I also have problem with sticky

**Comment by mattbag** [comment]
Sorry if you don't want the height to change, you just have to removed the event that fires on sticky stuck?
https://codepen.io/mattbag/pen/zEOLmq?editors=1111

**Comment by colin-marshall** [comment]
@thomasfrobieter did @mattbag's advice resolve this issue? If so, please close this out. Thanks!

**Comment by DanielRuf** [comment]
Closing as we did not receive any further information. Feel free to reopen if it still exists.
