### ISSUE TITLE
Custom download build doesn't utilize selected grid system

### ISSUE THREAD

**Issue by sashabeep** [zurb/foundation-sites#10636]
Despite the selected grid system index.html in the package always contains only XY grid markup

**Comment by rafibomb** [comment]
There is no logic right now that can import different HTML for the customizer based on the grid chosen. The Customizer is compiling a version of Foundation with certain imports.

Not sure what the answer is though luckily not a framework code issue.

**Comment by sashabeep** [comment]
@rafibomb why did not include just 3 lightweight html files for every grid system in the archive

**Comment by rafibomb** [comment]
Hmm, the index.html page is made to just quickly introduce some concepts of the framework. Most people delete the contents right away.

Even if we include 2 other versions, the index with is opened by default could still look broken to someone who downloads the float grid version.

**Comment by sashabeep** [comment]
As for me, i frequently use index.html as a cheatsheet and for checking if the selected options in customizer was correct :)

**Comment by colin-marshall** [comment]
@sashabeep I think the solution for now would be for you to keep a local copy of `index.html` that uses the grid you use, and switch it out after you download a customizer build.

**Comment by ncoden** [comment]
> There is no logic right now that can import different HTML for the customizer based on the grid chosen -- @rafibomb 

Couldn't we use Handlebar templates to generate `index.html` ?

**Comment by ncoden** [comment]
poke @colin-marshall

**Comment by colin-marshall** [comment]
@ncoden this seems low priority to me. Maybe revisit the idea for F7?

**Comment by ncoden** [comment]
@colin-marshall agreed. Done.
