### ISSUE TITLE
Add Reveal closing event

### ISSUE THREAD

**Issue by isapir** [zurb/foundation-sites#10634]
Currently Reveal has the following events:

`closeme.zf.reveal` - Fires immediately before the modal opens. Closes any other modals that are currently open
`open.zf.reveal` - Fires when the modal has successfully opened.
`closed.zf.reveal` - Fires when the modal is done closing.

But there is no event like 

`closing.zf.reveal` - Should fire just before the modal closes.

The reason that I need that event is that I want to slide Reveals in succession, i.e. 
1. Slide in Reveal with content X
2. On `next` button click:
  a. Slide out Reveal
  b. Update Reveal content to Y
  c. Slide in Reveal with content Y

The problem is that the `data-animation-in` and `data-animation-out` attributes do not allow to set a callback at the end of the animation.

I can do the first part with Motion UI, e.g.

    $(document).on("closeme.zf.reveal", function(e){
      Foundation.Motion.animateIn(e.target, "slide-in-right");
    })

    $(document).on("closing.zf.reveal", function(e){
      Foundation.Motion.animateIn(e.target, "slide-in-right", function(e){
        // currently there is no such event so I can not animate and provide a callback
      });
    })

I can provide a PR if approved.

**Comment by mattbag** [comment]
Can you add the close-modal to the click of the button?

`$('.custom-close-btn').click(e=>{
// trigger event before or function
// close modal (or close it in the event or callaback)
})`

**Comment by colin-marshall** [comment]
We're not adding features to F6, but this seems like a fairly simple request that could possibly accommodated in F6.

@ncoden @brettsmason @JeremyEnglert thoughts?

**Comment by JeremyEnglert** [comment]
If the original poster can send in a PR, I can see it being useful. 

But it also brings up the question: should all components have a similar event? It could lead us down a path of (even more) inconsistency. 

Also, beyond the case listed above, are there many instances where this event would be useful?

**Comment by isapir** [comment]
@JeremyEnglert I can submit a PR

**Comment by colin-marshall** [comment]
@JeremyEnglert yes all components should probably have a similar event. We already need to fix inconsistency in event casing, as described in #10155. These could both be addressed in a cleanup of events for 6.5.
