### ISSUE TITLE
Custom download page doesn't work

### ISSUE THREAD

**Issue by sashabeep** [zurb/foundation-sites#10635]
waring message after choosing components:
```
ENOENT: no such file or directory, stat '/tmp/tmp.6.4.2.80701b5e70f6b7dfea468df60016fb5c.zip'
```
![2017-09-11 10 45 21](https://user-images.githubusercontent.com/5689796/30263659-8587f292-96de-11e7-83a8-d0afd1f0ce4b.jpg)

**Comment by sashabeep** [comment]
Floating bug. Refreshing page and resending form won't help. Only choosing components from blank window

**Comment by DanielRuf** [comment]
Not reproducible anymore. Might have been a server issue.
