### ISSUE TITLE
Forms should have separate section!

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10633]
Section Name: **Forms**

Page 1: Base Layout http://foundation.zurb.com/sites/docs/forms.html
Page 2: Abide Validation http://foundation.zurb.com/sites/docs/abide.html

cc @kball

**Comment by rafibomb** [comment]
Your suggestion is to move forms into it's own sidebar subsection?

I can get behind it but Abide lives in Plugins now. What's the reasoning to make a change?

**Comment by colin-marshall** [comment]
@IamManchanda closing out this feature request to be reconsidered in v7.
