### ISSUE TITLE
Foundation 6.4.1: Changing $grid-column-count value in _settings.scss doesn't work?

### ISSUE THREAD

**Issue by ginocremer** [zurb/foundation-sites#10640]
Hello Zurb-Team,

we're using Foundation 6.4.1 with the new xy-grid. We need a 16 columns grid and wanted to change the value of the variable $grid-column-count in the file settings.scss - like it worked like a charm in the past. When we built our markup and we wanted e.g. to create a 2-col-layout for medium up, we still have to use "medium-6" for both cells - even if the value of $grid-column-count has already been changed to 16. Is this a known issue (I couldn't find anything in all Github Issues) or are we doing something wrong?

Thank you very much and kind regards

**Comment by brettsmason** [comment]
@ginocremer For XY grid you need to change `$grid-columns` [found here](https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss#L860).

`$grid-column-count` is for the old 2 grids. Hope that helps!

**Comment by ginocremer** [comment]
You're right, thank you very much for your help and your fast answer! Perhaps it could be helpful for others to write a short comment behind like "// Legacy - Use $grid-columns for XY instead" - I just read "3. The Grid" and for me the grid is...the grid :D

**Comment by rafibomb** [comment]
You might be referring to a settings file that you had previously - carried over form 6.3.1. This can be bettered handles through migration notes since a news settings file wouldn't have the old settings.

We'll be adding this specificity for the next major release.

**Comment by cucocreative** [comment]
I too just got confused by this and googling got me here. As @ginocremer said a comment section 3 pointing to section 56 would be helpful. FYI I'm using a fresh install of F6.4.3
