### ISSUE TITLE
Equalizer bugged on new release

### ISSUE THREAD

**Issue by pieter-janDB** [zurb/foundation-sites#10646]
#### How to reproduce this bug:

1. make new project
foundation new

2. use equalizer
```
<div class="row" data-equalizer>
     <div class="column small-6" data-equalizer-watch style="background-color: red;">test</div>
     <div class="column small-6" data-equalizer-watch>tester<br>tester<br>tester<br>tester<br>tester<br></div>
   </div>
```

3. include only the files we need (not full foundation.js which works)
assetsPath + 'bower_components/foundation-sites/dist/js/plugins/foundation.core.js',
            assetsPath + 'bower_components/foundation-sites/dist/js/plugins/foundation.equalizer.js',
            assetsPath + 'bower_components/foundation-sites/dist/js/plugins/foundation.util.mediaQuery.js',
            assetsPath + 'bower_components/foundation-sites/dist/js/plugins/foundation.util.timerAndImageLoader.js',
            assetsPath + 'bower_components/foundation-sites/dist/js/plugins/foundation.util.triggers.js',

4. get error
TypeError: Cannot read property '_init' of undefined
    at Equalizer._init (app.min.js:1122)

#### What should happen:
Copy pasting my foundation folder from an older project fixed it so I think something went wrong with a new release.

#### Browser(s) and Device(s) tested on:

chrome mac osx

#### Foundation Version(s) you are using:

Foundation CLI version 2.2.3

**Comment by DanielRuf** [comment]
Can you provide a full working codepen?

**Comment by DanielRuf** [comment]
Closing as we did not receive any further information.
