### ISSUE TITLE
Scope for improvements on dropdown menu (top-padding) ?

### ISSUE THREAD

**Issue by udf2457** [zurb/foundation-sites#10641]
Hi,

Let's say I've got a menu that looks something like this:

```
<ul class="dropdown vertical medium-horizontal menu"  data-responsive-menu="drilldown medium-dropdown"  data-auto-height  data-animate-height >
<li class="menu-text"><img class=“my-logo my-X-hidesmall"  src="/templates/X_webtemplate_2017/assets/img/30px.png" ></li>
<li ><a href="/index.php">Home</a>
<li class=“myTestpad" ><a href=“/bob">Test</a></li>
</ul>
```

My "issue" with horizontal dropdown menus is probably best described by the following screenshot:

<img width="429" alt="navbar" src="https://user-images.githubusercontent.com/6958684/30343163-501efd78-97f4-11e7-84bd-08c324d488bd.png">

What you see with "Home" is the default behaviour.

What you see with "Test" is the result of me adding  a class item that does `padding-top:1rem;` in order to force the menu to vertical align with the logo in a more centered manner.

Do you think there is justifiable scope for improvement in Zurb here ?  Or at least the addition of a suitable variable ?  I've looked through the docs but can't see much there.

**Comment by mattbag** [comment]
If you use the latest flex version, it does that already.
https://codepen.io/mattbag/pen/KXwqMo?editors=1100
Provide a more accurate example with codepen if you're question is different than I assumed.
Cheers

**Comment by udf2457** [comment]
@mattbag 

Fairly sure I tried that already, but leave it with me, I'll try again in the next day or so and update you.

**Comment by rafibomb** [comment]
@udf2457 +1 on your suggestion. We cannot always assume that the menu items would line up vertically centered. The flex utilities make this an easy solution.
