### ISSUE TITLE
data-close-on-click option on dropdown does not work correctly

### ISSUE THREAD

**Issue by u671175** [zurb/foundation-sites#10657]
#### How to reproduce this bug:

1. Open a dropdown with data-close-on-click="true"
2. Click inside the dropdown 

#### What should happen:
dropdown should not close
#### What happened instead:
dropdown closed
#### Browser(s) and Device(s) tested on:
Chrome
#### Foundation Version(s) you are using:
6.4.3
#### Test case link:
Inside _addBodyHandler method, following code need to be changed:
if(_this.$element.find(e.target).length) {
              return;
            }

it should be

if(_this.$element.is(e.target) || _this.$element.find(e.target).length) {
              return;
            }

**Comment by rafibomb** [comment]
Closing for PR https://github.com/zurb/foundation-sites/pull/10658**

**Comment by kball** [comment]
@rafibomb typically we don't close until the PR is merged...
