### ISSUE TITLE
Feature Request: more types for `loc` parameter of SmoothScroll.scrollToLoc

### ISSUE THREAD

**Issue by mexn** [zurb/foundation-sites#10651]
Hey,

it would be great, if it's possible to pass several types as the `loc` parameter for the `scrollToLoc`  method. Currently, it's only a jQuery selector, but jQuery-/DOMElements or pixel values would also be very handy!

**Comment by colin-marshall** [comment]
@mexn thanks for your feature request. Closing this out as we are not adding features to Foundation 6. We will consider this when we start work on Foundation 7. Thanks!
