### ISSUE TITLE
[Slider] is slider renamed range-slider in FOUNDATION 6?

### ISSUE THREAD

**Issue by simsong** [zurb/foundation-sites#10656]
The code posted on [this page](http://foundation.zurb.com/sites/docs/slider.html) doesn't work, but it does work if 'slider' is replaced with 'range-slider' 

#### How to reproduce this bug:

On the page is this code for a slider:

```
<div class="slider" data-slider data-initial-start="50" data-end="200">
  <span class="slider-handle"  data-slider-handle role="slider" tabindex="1"></span>
  <span class="slider-fill" data-slider-fill></span>
  <input type="hidden">
</div>

```

Strangely, it doesn't work if the class is `slider`, but it works if the class is changed to `range-slider`. 

But it does work in codepen.io.

**Comment by Deckluhm** [comment]
What page are you talking about?

**Comment by Deckluhm** [comment]
Your error is probably that you are using Foundation 5 (instead of 6).

**Comment by simsong** [comment]
Actually, I am using Foundation 6.

**Comment by Deckluhm** [comment]
Can you share a sample project reproducing the issue?

**Comment by simsong** [comment]
Yes. 

This one is with `range-slider`: https://simson.net/foundation/range_slider.html

This one is with `slider`: https://simson.net/foundation/slider.html

**Comment by DaSchTour** [comment]
The first line of your `docs.css` is

```
meta.foundation-version {
  font-family: "/5.5.3/"; }
```

**Comment by simsong** [comment]
How about that. I’ll fix and try again.
Thanks.

(Sent from my laptop.)

__________________________
Simson L. Garfinkel
https://simson.net/
202-649-0029
