### ISSUE TITLE
[Progressive Enhancement] CSS Variables with Sass Fallback for older browsers

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10655]
**Inspiration**: https://codepen.io/jakealbaugh/post/css4-variables-with-fallbacks-using-sass
**Demo (with JS Combined Power)**: https://codepen.io/IamManchanda/full/aLvvzj

**Reasons**: 
**1. Theme switcher for templates (Occasional Situations)** 
For Example check, this randomly chosen template from ThemeForest
This theme has a color picker
http://pixelosaur.com/preview/altius/theme/index-creative.html

This below is how it's getting that code aka Real Bloat 

```html
<div id="styleOptions" class="versions clearfix">
  <a href="#" rel="css/colors/colors.css" class="bgRed"></a>
  <a href="#" rel="css/colors/blue-grey.css" class="bgBlueGrey"></a>
  <a href="#" rel="css/colors/blue.css" class="bgBlue"></a>
  <a href="#" rel="css/colors/bright-green.css" class="bgBGreen"></a>
  <a href="#" rel="css/colors/cyan.css" class="bgCyan"></a>
  <a href="#" rel="css/colors/deep-orange.css" class="bgOrange"></a>
  <a href="#" rel="css/colors/green.css" class="bgGreen"></a>
  <a href="#" rel="css/colors/indigo.css" class="bgIndigo"></a>
  <a href="#" rel="css/colors/light-brown.css" class="bgBrown"></a>
  <a href="#" rel="css/colors/purple.css" class="bgPurple"></a>
  <a href="#" rel="css/colors/yellow.css" class="bgYellow"></a>
</div>
```

BTW that's how all templates fetch it, nothing like bad practice (**till now**)
In fact a good practice, but now as 
CSS variables has 80% browser support, further 20% has an easy fallback,

So, I think above code is a bad practice right now which can be superbly improved by CSS variables!

---

**2. Style switcher for websites and Accessibility (Should be used always)** 
![another-examples](https://user-images.githubusercontent.com/4970624/30514242-bf047ef6-9b2e-11e7-9bf5-c2abd8f791ff.png)

**Comment by IamManchanda** [comment]
As this is a big requested feature and may have some cons (though I can't see any cons)
Will poke some Sass/CSS and JS ninja's 

cc @kball @rafibomb @tdhartwick @brettsmason @SassNinja @codetheorist @ncoden @DaSchTour 
{ Other's also please give a feedback }

This will look something like this 

In a pseudocode, 
We can have a mixin like this

```scss
body { @include var(color, primary); }
```

which will generate something like this

```css
body {
  color: #1779ba;
  color: var(--color-primary);
}
```

After which, websites or template (by their own) can use stuff like modernizer 
and implement a Style Switcher or Theme Switcher to only supported (all latest) browsers (80%)
and on rest browsers (IE, Opera Mini, UC Browser) things will work normally aka without a Switcher but also without that so many CSS files bloat! 


Something like that so called: **Progressive Fallback/Enhancement** :stuck_out_tongue: 
Something like https://codepen.io/IamManchanda/full/aLvvzj

FWIW, this is the only vanilla JS used to make this aka can be an easy stuff to make this up

```js
const inputs = document.querySelectorAll('.controls input');

function handleUpdate () {
  const suffix = this.dataset.sizing || '';
  document.documentElement.style.setProperty(`--${this.name}`, this.value + suffix);
}

inputs.forEach((input) => {
  input.addEventListener('change', handleUpdate);
  input.addEventListener('mousemove', handleUpdate);
});
```

**Orignal Source of demo**: @wesbos tutorials, TY Wes!

**Comment by colin-marshall** [comment]
@IamManchanda closing out this feature request to be reconsidered in v7.

**Comment by IamManchanda** [comment]
This is already labelled as v7 only!!!

**Comment by IamManchanda** [comment]
It seems like that this is already labelled by v7 and we closed it by mistake so we are reopening it... Thanks!

**Comment by IamManchanda** [comment]
V7 requests are being closed for the time being. We have them labeled so we can readdress them in the future.
