### ISSUE TITLE
[Reveal] Close button makes page skip to last occurence of data-open button

### ISSUE THREAD

**Issue by reinhardmohr** [zurb/foundation-sites#10654]
Hi, I hope I am right here and explain everything properly …

I use reveal to open a modal on my page:
`<div id="ProbeessenModal" class="reveal rm-rounded" data-reveal data-animation-in="slide-in-left" data-animation-out="hinge-out-from-right"> ………`
There are three buttons (and a link) with data-open="ProbeessenModal":
`<button class="button secondary hollow rm-rounded" data-open="ProbeessenModal">Hochzeits-Probeessen</button>`
One button in the top part of the page, one in the middle, one near the bottom. Everything works fine.
But when the modal is called from the topmost button and the user clicks the close button
`<button class="close-button" data-close aria-label="Close reveal" type="button">
		    <span aria-hidden="true">&times;</span>`
the modal is closed. But the page skips to the last occurence of the button near the bottom.
So the users might be confused and might miss important parts of the page.

I could probably make four identical modals with four different IDs. But this would bloat my code and would be error-prone.
Is there anything I can do to have the modal close at the part of the page where it was called?

Thanks for helping

Reinhard

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/commit/9fce99e34709e5ec5a2dc1e0ac98e5f1e8c6af84#diff-5b5e0861de0a3864db2c3c28919700b7

I guess this fixes it. You can test it [here](https://codepen.io/DanielRuf/pen/zWMrMZ)

**Comment by ineptian** [comment]
Best fix I have seen for this yet. Thanks Daniel.
