### ISSUE TITLE
Zurb Foundation Version

### ISSUE THREAD

**Issue by jgacuca567** [zurb/foundation-sites#10669]
@IamManchanda I went on the Foundation Website and it still shows `6.4.2`, please update so that docs show `6.4.3`

<img width="1280" alt="screen shot 2017-09-21 at 6 50 34 pm" src="https://user-images.githubusercontent.com/4000076/30722199-d537983e-9efd-11e7-8fac-b021b92c73b4.png">

**Comment by IamManchanda** [comment]
Thanks ... Quite late here... Will update tomm morning

**Comment by IamManchanda** [comment]
@jgacuca567 Good morning... This is updated and merged!
Will be deployed soon ... 

Closing this, but feel free to let us know with any more issues you are facing!
