### ISSUE TITLE
When I using off-canvas component with the foundation v6.4.0,there was no animation in my off-canvas class ...how to deal with it?

### ISSUE THREAD

**Issue by csuZipple** [zurb/foundation-sites#10665]
#### How to reproduce this bug:

1. Step one
2. Step two
3. Step three

#### Test case link:

- [CodePen with Foundation 6.3.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Float Grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/bRYOMv)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)

**Comment by SassNinja** [comment]
@csuZipple would you please describe more detailed how to reproduce the issue? (e.g. by filling out the issue template you've just posted unmodified...)

It would be helpful to know
- did you update an existing project or create a new one?
- your markup code

**Comment by rafibomb** [comment]
Closing here - please reopen with more details, steps to reproduce and a demo codepen. Thanks!
