### ISSUE TITLE
Suggestion: Remove throwaway reference to "girl!" in Foundation Zurb Template 

### ISSUE THREAD

**Issue by ajpiano** [zurb/foundation-sites#10663]
I am a brand-new Foundation user giving it a go for the first time. I came here because I wanted to note the double-take I did upon initially spotting this section on the default Foundation Zurb Template that's generated when you spin up a new project (and that repo said this repo is the right place to file issues). 

<img width="382" alt="screen shot 2017-09-19 at 1 30 30 pm" src="https://user-images.githubusercontent.com/155599/30606284-31b73b48-9d3f-11e7-86ec-0595bca727bd.png">

I understand that this is just meant to be a "light" and "fun" heading, but... none of the other headings have this "light" and "fun" "narrator" tone, they are simply declarative. I don't really see much use for this throwaway reference and can only see it doing inadvertent harm. I'd be happy to file a PR to fix it or to go deeper into why I feel that way depending on the response this issue receives. Thanks.

**Comment by kball** [comment]
Absolutely, file a PR to fix. Hadn't seen/noticed this, it predates me, but lets definitely fix it.

**Comment by rafibomb** [comment]
You mentioned injecting fun, we can replace with something else fun without removing all personality. Thanks!

**Comment by ajpiano** [comment]
Folks? People? Y'all? What do you prefer @rafibomb
