### ISSUE TITLE
Rounded buttons - Prototype Utilities

### ISSUE THREAD

**Issue by RinatValiullov** [zurb/foundation-sites#10673]
#### How to reproduce this bug:
1. Included last version *.min.css of framework in *.html file
2. Set class on buttons - _.rounded_
3. Nothing was changed...
4. Tried to find this class on official docs, but didn't find this one there...

#### What should happen:
Wanted to set buttons with rounded corners

#### What happened instead:
Couldn't set rounded corners on buttons with helper class: _.rounded_

#### Browser(s) and Device(s) tested on:
Chrome  61.0.3163.100  (64 bit) (Windows 7)
#### Foundation Version(s) you are using:
6.4.2

**Comment by IamManchanda** [comment]
Just to be clear he faced issue while making this => https://codepen.io/IamManchanda/pen/GMJxXN

**Comment by IamManchanda** [comment]
cc @kball prototype utilities are not well mentioned in the docs!

**Comment by RinatValiullov** [comment]
Ok, thanks

**Comment by Deckluhm** [comment]
This is the part of the docs you are looking for: https://foundation.zurb.com/sites/docs/prototyping-utilities.html#component-styling

But note that you also need to enable prototype mode if you want to use this (and any prototype utilities): https://foundation.zurb.com/sites/docs/prototyping-utilities.html#enabling-prototype-mode

I also recommend you to read the introduction part of the **Prototyping Utilities** section. It's pretty important to understand why these utilities exist but also why you shouldn't use them in production.

Happy coding!

**Comment by Deckluhm** [comment]
This is the part of the docs you are looking for: https://foundation.zurb.com/sites/docs/prototyping-utilities.html#component-styling

But note that you also need to enable prototype mode if you want to use this (and any prototype utilities): https://foundation.zurb.com/sites/docs/prototyping-utilities.html#enabling-prototype-mode

I also recommend you to read [the introduction part of the **Prototyping Utilities** section](https://foundation.zurb.com/sites/docs/prototyping-utilities.html). It's pretty important to understand why these utilities exist but also why you shouldn't use them in production.

Happy coding!

**Comment by IamManchanda** [comment]
@Deckluhm But man the thing is that he was facing issue as didn't know how to replace
**foundation-prototype.min.css** file with **foundation.css**
We have to agree that we are not making things clear! 

Secondly I would argue that,
Component Styling Section should be also in respective component section
( with an alert that this is part of prototype utility and disabled by default )

**Comment by IamManchanda** [comment]
Plus the prototype introduction page is so long ( and I am sorry to say this @rafibomb ) that the demo get's hidden. I have to scroll to 5 pages to get to the first demo 
{ I would suggest that introduction part should be moved to an article by zurb or at medium } 
@kball Would love your thoughts on this!

**Comment by RinatValiullov** [comment]
it would be well, Iam!

**Comment by IamManchanda** [comment]
Awaiting reply @rafibomb ... I think we need a video tutorial here!

**Comment by rafibomb** [comment]
I am open to moving the intro section somewhere else, for launch of a new major feature it helps to have it on the docs page for a few releases.

@IamManchanda Since you know the most about the feature, can you help with a small outline of what this page needs in terms of a tutorial video?

**Comment by rafibomb** [comment]
Also - I don't see any foundation-prototype.min.css, where does this come from?

As far as I know, the custom download allows you to include in the prototype classes into the main foundation.min.css

**Comment by IamManchanda** [comment]
@rafibomb This is coming from here 
https://github.com/zurb/foundation-sites/tree/develop/dist/css

**Comment by IamManchanda** [comment]
> @IamManchanda Since you know the most about the feature, can you help with a small outline of what this page needs in terms of a tutorial video?
 
**For Classes,** 

1. Button ( Radius/Rounded, Bordered, Shadow )
2. Switches ( Rounded ) - Coming in [v6.4](https://github.com/zurb/foundation-sites/blob/develop/docs/pages/prototyping-utilities.md#switches)
3. Cards  ( Radius, Bordered, Shadow )
4. Tables ( Radius, Bordered, Shadow )
5. Images ( Radius )
6. Arrow Utility ( Top, Right, Bottom, Left )
7. Separator ( Left, Center, Right ) 
8. Font Styling - [here](https://foundation.zurb.com/sites/docs/prototyping-utilities.html#font-styling)
9. List Styling - [here](https://foundation.zurb.com/sites/docs/prototyping-utilities.html#list-styling)
10. Text Helpers - [here](https://foundation.zurb.com/sites/docs/prototyping-utilities.html#text-helpers)
11. Margin & Padding Helpers
12. Sizing
13. Border None ( Callout )
14. Display, Positioning & Overflow

**For Mixins,**
1. Box Mixin - [here](https://foundation.zurb.com/sites/docs/prototyping-utilities.html#box-mixin)
2. Rotate Mixin - [here](https://foundation.zurb.com/sites/docs/prototyping-utilities.html#rotate-mixin)
3. Relational Mixins - [here](https://foundation.zurb.com/sites/docs/prototyping-utilities.html#relational-mixins-aka-nth-child-mixins-)

**Comment by IamManchanda** [comment]
Also when you do @rafibomb ... Please would be greatfull if you add the codepen's too as this page is missing that too :D 

( Component Styling should surely have the codepen's )


> I am open to moving the intro section somewhere else

Would it be ohk if I move Introduction, and Enabling Prototype Mode section to medium articles and start with just 1 scroll for the demo?
