### ISSUE TITLE
Modal(Reveal component) on mobile

### ISSUE THREAD

**Issue by johnylaravel** [zurb/foundation-sites#10692]
Is there a way for modal **not to be Full-screen** on mobile? Is there any option for that?

And can we set position **from bottom**, not from top?

And is there a way to **set speed in miliseconds**? Because "fast" is not fast enough, I need it much faster than that

**I would like Modal to be like this:**
![github-modal-problem](https://user-images.githubusercontent.com/30267900/31132887-3e8652da-a85e-11e7-84a5-717518ec17f6.png)

**Thanks a lot for any help!**

**Comment by rafibomb** [comment]
You could see how the sizing works with this building-block: https://foundation.zurb.com/building-blocks/blocks/mobile-ios-modal.html

The motion-ui library has it's own settings in node_modules -> motion-ui -> _settings.scss 

```
$motion-ui-delays: (
  default: 0,
  short: 300ms,
  long: 700ms,
) !default;

```
