### ISSUE TITLE
[The Grid] Misspelling in documentation

### ISSUE THREAD

**Issue by arteenfox** [zurb/foundation-sites#10694]
#### How to reproduce this bug:

1. Step one
Read the docs (:

## Collapse/Uncollapse Rows
The `.collapse` class lets you remove column gutters (padding).

There are times when you won't want each media query to be collapsed or uncollapsed. In this case, use the media query size you want and collapse or uncollapse and add that to your row element. **Example shows no gutter at _LARGE_ media size and then adds the gutter to columns at medium.**
```
<div class="row medium-uncollapse large-collapse">
  <div class="small-6 columns">
    Removes gutter at large media query
  </div>
  <div class="small-6 columns">
    Removes gutter at large media query
  </div>
</div>
```
## Collapse/Uncollapse Rows
The `.collapse` class lets you remove column gutters (padding).

There are times when you won't want each media query to be collapsed or uncollapsed. In this case, use the media query size you want and collapse or uncollapse and add that to your row element. **Example shows no gutter at _SMALL_ media size and then adds the gutter to columns at medium.**
```
<div class="row medium-uncollapse large-collapse">
  <div class="small-6 columns">
    Removes gutter at large media query
  </div>
  <div class="small-6 columns">
    Removes gutter at large media query
  </div>
</div>
```
#### Foundation Version(s) you are using:
6.4.3 documentation

**Comment by rafibomb** [comment]
Thanks! https://github.com/zurb/foundation-sites/commit/eaa79c89a8c5dc89f8fa1e6916ce5dea6cc55866
