### ISSUE TITLE
Push, Pull, Offset aren't optional 

### ISSUE THREAD

**Issue by DusanMilko** [zurb/foundation-sites#10701]
Using latest Foundation with SASS

@include foundation-grid(
  $pull: false,
  $push: false,
  $offset: false
);

pull, push, and offset aren't optional with foundation-grid. They should be... instead setting these variables renames the attribute...

By default the grid creates for example:

```
  .medium-1 {
    width: 8.33333%; }
  .medium-push-1 {
    position: relative;
    left: 8.33333%; }
  .medium-pull-1 {
    position: relative;
    left: -8.33333%; }
  .medium-offset-0 {
    margin-left: 0%; }
```

I only need, thus the other options should be optional

```
  .medium-1 {
    width: 8.33333%; }
```

**Comment by colin-marshall** [comment]
Looks like this got merged so I'm closing out this issue.
