### ISSUE TITLE
Sentence Overflow

### ISSUE THREAD

**Issue by idpokute** [zurb/foundation-sites#10705]
#### How to reproduce this bug:
1.make a long sentence. I tested li, p, h1 and span.
2.when the width of sentence is wider than a width of current column, it overflow.

I'm not sure this behavior is on purpose. In my opinion if they have a css property such as word-wrap:break-word, it would be safe.

#### What should happen:
I expected the content of column is in the column, not overflow.

#### What happened instead:
Text overflow

#### Browser(s) and Device(s) tested on:
Chrome on desktop and mobile.

#### Foundation Version(s) you are using:
6.4.1

#### Test case link:
https://codepen.io/idpokute/pen/boLeyP

**Comment by brettsmason** [comment]
I think this should be down to the designer to set `word-wrap`, not up to the framework - its not always going to be the desired behaviour.

If used with actual real world content the text flows just fine. This would apply to all sorts of content, not just the grid.
