### ISSUE TITLE
[Foundation 7] Move fully to webpack! - Not half like current 

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#10714]
- [ ] Remove Gulp
- [ ] Move fully to webpack

**Reason**: All these app frameworks now use/supports webpack

1. Angular - https://angular.io/guide/webpack
2. React - https://scotch.io/tutorials/setup-a-react-environment-using-webpack-and-babel
3. Vue - Well here its awesome actually 

> - [Vue + Webpack for Prototyping stuff](https://github.com/vuejs-templates/webpack-simple/)
> - [Vue + Webpack for Advanced stuff](https://github.com/vuejs-templates/webpack/)
> - [Vue + Webpack for PWA stuff](https://github.com/vuejs-templates/pwa/)

**Comment by DaSchTour** [comment]
Maybe we should get rid of gulp and webpack and try to make the build environment as small as possible?

**Comment by IamManchanda** [comment]
(If you ask me personally)
Being loving Vue and Webpack day by day
This is the last thing I would like!

**Comment by IamManchanda** [comment]
Webpack is the present and future of module bundling.

**Comment by DaSchTour** [comment]
I guess the future of module bundling is no module bundling at all

**Comment by IamManchanda** [comment]
I don't agree! 
Maybe because I like webpack simplicity!

**Comment by DaSchTour** [comment]
And I don't see any simplicity in webpack 🤣

**Comment by marvinhuebner** [comment]
If we move completly to webpack, will panini also migrated to webpack? 

Currently this is the biggest blocker for me to fully move because i love panini for prototyping and simple html pages. 

Maybe @gakimball can help here.

**Comment by gakimball** [comment]
> If we move completly to webpack, will panini also migrated to webpack?

Do you mean making a Webpack loader for it?

It's possible, but I don't know that the entire library can be overloaded to support the Webpack model of importing files. For example, in Panini, if you create a partial at `src/partials/nav.js`, it's available as just `{{> nav }}`. Contrast this with the Webpack loader for Handlebars, [handlebars-helper](https://github.com/pcardune/handlebars-loader), which uses Webpack's full module resolution system to manage loading helpers.

On top of that, since the HTML files are likely the Webpack entries, you'd probably also want loaders to pull in images, CSS, JS, etc. referenced in the HTML, at least assuming you want the entire build process to be Webpack-based.

I might be misunderstanding something, but I think that's a completely different library from Panini. It's definitely possible to build, although I don't have enough Webpack experience to be the one to build it.

**Comment by IamManchanda** [comment]
cc @thelarkinn ... Can you help us a bit sir ;)

**Comment by IamManchanda** [comment]
Sharing this link which makes my case more solid
https://wptavern.com/wordpress-replaces-browserify-with-webpack-for-build-process

**Comment by DaSchTour** [comment]
I remember the times everybody used bower for frontend dependencies 😉 
Sorry but do not over estimate such things. Frontend technology moves that fast.

**Comment by phifa** [comment]
@IamManchanda is it possible to move fully to webpack? less dependencies makes sense to me.

**Comment by IamManchanda** [comment]
@DaSchTour Just had the poll in my circle
and here's what they thought about Webpack - see below
I really think webpack is easy and should be the default stuff
I don't think it's confusing
cc @ncoden 

<img width="609" alt="screen shot 2018-01-22 at 2 24 08 am" src="https://user-images.githubusercontent.com/4970624/35198894-a74cdc4e-ff1b-11e7-83df-afaad9aea8aa.png">

**Comment by ncoden** [comment]
@IamManchanda This study seems to have a lot of biais.
* Small sample
* Differents tons and formulations for the proposed answer
* Small number of answer
* Selection biais due to Facebook non-random algorithmes.
* Partiality of the author of the study.

**Comment by IamManchanda** [comment]
But still do you really think we should not move to webpack??

on the top of Foundation 7 webpack template we can make various webpack templates for various technologies like angular, react, vue, laravel, wordpress etc etc and ship it over 

Kind of https://github.com/vuejs-templates

**Comment by IamManchanda** [comment]
Then user can simply do this below and boom

```
foundation-cli init webpack-vue # Swap `vue` with your platform
```

**Comment by ncoden** [comment]
Yeah, we could switch to webpack. I have nothing against that.

**Comment by phifa** [comment]
If we switch to webpack, we need to create resources on how to properly work with foundation and webpack. I am almost daily running into problems. Otherwise many folks will pick BS or other frameworks that are easier to adopt and we loose people. That would suck. At this point the framework is called "foundation" and not "foundation+webpack". Again, I see the advantages of webpack, but we need to make sure to give examples, docs, tutorials, etc.

**Comment by kuzvac** [comment]
And make webpack loader or something for panini :D

**Comment by IamManchanda** [comment]
@phifa @ncoden 
Well there is a short course on udemy. (Yup that 10$ beast)
https://www.udemy.com/webpack-beyond-the-basics/

The author of that tutorial Lawrence, apart from being a web developer is a film maker too and thus  has made a great resource for learning webpack with ease. If we can add that link in the docs for same or resources then that will be great

or else, if we can't pinch in some paid course then well there is https://webpack.academy/ by the creator of Webpack that we can add as a resource

**Comment by marvinhuebner** [comment]
I think if we move to webpack it won't heart newbies from using foundation if we have good toolset around. We should don't remove the basic template. So the basic template will use simple html/css/js without the need of any tooling and the zurb (advanced) template should prepared with a working webpack configuration.

So if anybody who has not much knowladge about webpack but will use the sass version of foundation will simply use the zurb (advanced) template. And if `npm start` and `npm run build` works out of the box it should be no big thing for anybody who is not really into these topics to use foundation with sass etc..

And if we move to webpack it there should be an officially panini-loader for webpack.

**Comment by DaSchTour** [comment]
I don't like were this discussion is heading. Webpack should be used as an internal toolset to create a distribution build that can be used with all other toolsets. The worst a framework could to to chain itself to a certain build tool and force others to use a certain toolchain just to use a certain framework.

**Comment by brettsmason** [comment]
I tend to agree with @DaSchTour on this. The good thing about Foundation is its flexible in how the user wants to work and we don't force a way of working upon them.

**Comment by IamManchanda** [comment]
> We should don't remove the basic template. So the basic template will use simple html/css/js without the need of any tooling and the zurb (advanced) template should prepared with a working webpack configuration.

> So if anybody who has not much knowladge about webpack but will use the sass version of foundation will simply use the zurb (advanced) template. And if npm start and npm run build works out of the box it should be no big thing for anybody who is not really into these topics to use foundation with sass etc..

> And if we move to webpack it there should be an officially panini-loader for webpack.

I agree

> Webpack should be used as an internal toolset to create a distribution build that can be used with all other toolsets. The worst a framework could to to chain itself to a certain build tool and force others to use a certain toolchain just to use a certain framework.

I don't agree

**Comment by IamManchanda** [comment]
V7 requests are being closed for the time being. We have them labeled so we can readdress them in the future.
