### ISSUE TITLE
[Responsive Navigation] Error in the doc

### ISSUE THREAD

**Issue by sacrejohn** [zurb/foundation-sites#10717]
On the page : https://foundation.zurb.com/sites/docs/responsive-navigation.html

Concerning Events Section

'toggled.zf.responsiveNavigation' ==> I think the right name is 'toggled.zf.responsiveToggle'

I did not find how to correct the document myself.

Thank you.

**Comment by colin-marshall** [comment]
Duplicate. Closing in favor of #9191.
