### ISSUE TITLE
Make jQuery an optional

### ISSUE THREAD

**Issue by InquisitiveDevelopment** [zurb/foundation-sites#10716]
I was looking at frontend frameworks and had hoped Foundation wouldn't list jQuery as a required dependency.

Please move towards making jQuery an optional piece instead of being required!

**Comment by IamManchanda** [comment]
Yes we are on it for foundation 7 roadmap 
Don't worry!

**Comment by qdbdbp** [comment]
https://github.com/zurb/foundation-sites/issues/10686

I'm afraid it will not be as planned.
November already ahead of us, and the answer is that they have no product in time.
I also look forward to free itself from jQuery

**Comment by fawmi** [comment]
Sorry for irrelevant question, but according to roadmap foundation 7.0 is about to release in November, will it really get released on November, as i can not see much progress in Jquery free javascript plugins.

**Comment by colin-marshall** [comment]
As @IamManchanda stated, we are planning on this for F7. No reason to keep this open so I'm closing it out to keep things tidy.
