### ISSUE TITLE
zurb foundation unknown word error

### ISSUE THREAD

**Issue by dhisharma** [zurb/foundation-sites#10723]
#### How to reproduce this bug:

1. Step one
2. Step two
3. Step three

#### Test case link:

- [CodePen with Foundation 6.3.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Float Grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/bRYOMv)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)

I am using foundation for the first time its throwing error some inavlid word u can see that in the image file i am attaching I dont know whats happening here .this is my webpack config file i am setting the entry point. I am also setting externals and plugins but still it is not working. i have installed this dependencies css-loader@0.23.1 script-loader@0.6.1 style-loader@0.13.0 jquery@2.2.1 foundation-sites@6.2.0.
-- | --
webpack.config.js -

          var webpack = require('webpack');
         module.exports = {
            entry:[
                  'script!jquery/dist/jquery.min.js',
                  'script!foundation-sites/dist/foundation.min.js',
            './app/app.jsx'
              ],
                 externals:{
                  jquery: 'jQuery'
                },
                 plugins : [
                   new webpack.ProvidePlugin({
                 '$' : 'jquery',
                    'jQuery' : 'jquery'
                  })

             ],
               output:{
             path:__dirname,
               filename:'./public/bundle.js',
              },
            resolve:{
               root:__dirname,
               alias:{
            Main:'app/components/Main.jsx',
            Nav: 'app/components/Nav.jsx',
            Weather : 'app/components/Weather.jsx',
            WeatherForm : 'app/components/WeatherForm.jsx',
            WeatherMessage : 'app/components/WeatherMessage.jsx',
            About : 'app/components/About.jsx',
            Examples: 'app/components/Examples.jsx',
            openWeatherMap : 'app/api/openWeatherMap.jsx'
        },
        extensions:['','.js','.jsx']
       },
       module:{
        loaders:[
            {
                loader: 'babel-loader',
                query:{
                    presets:['react','es2015']
                },
                test:/\.jsx?$/,
                exclude:/(node_modules|bower_components)/
            }
        ]
    },
      devtool: 'cheap-module-eval-source-map'
   }

app.jsx : -

    var React = require('react');
    var ReactDOM = require('react-dom');
    var {Route, Router, IndexRoute, hashHistory} = require('react-router');
    var Main = require('Main');
    var Weather = require('Weather');
    var About = require('About');
    var Examples = require('Examples')
    //load foundation
      require('style!css!foundation-sites/dist/foundation.min.js');
        $(document).foundation();
      ReactDOM.render(
     <Router history={hashHistory}>
     <Route path="/" component={Main}>
       <Route path="about" component={About}/>
       <Route path="examples" component={Examples}/>
         <IndexRoute component={Weather}/>
       </Route>
      </Router>,
       document.getElementById('app')
          );
![foundationerror](https://user-images.githubusercontent.com/23400648/31557557-e49e38c6-b066-11e7-8577-ec968ae331d7.png)

**Comment by ncoden** [comment]
Probably fixed in https://github.com/zurb/foundation-sites/pull/10864. This sould be released in `v6.4.4`.
