### ISSUE TITLE
[Interchange] How do you reflow after ajax

### ISSUE THREAD

**Issue by CHEWX** [zurb/foundation-sites#10726]
Hi,

As per title, the docs seemed to have disappeared.

There is no obvious way how to do this?

Thanks,
Tom

**Comment by Deckluhm** [comment]
`reflow` is now called `reInit` and is slightly different: https://foundation.zurb.com/sites/docs/javascript.html#adding-content-to-plugins

**Comment by CHEWX** [comment]
Thanks @Deckluhm 

Kinda feel like there should be reference to this in each plugin.
