### ISSUE TITLE
[XY Grid] Are we supposed to use use grid-x, grid-y classes on elements that also have cell class specified?

### ISSUE THREAD

**Issue by brgrz** [zurb/foundation-sites#10727]
I am looking for guidance on how to combine the cell and grid classes within nested grids. The docs don't give any guidance on this. In fact there is very little said about nested grids in the docs besides the grid-frame example.

Specifically I'm trying to understand if I can cut some levels by putting the grid-x and grid-y classes to cells.

I was able to use it like this to some degree but I inevitably run into various issues after some time: 

```
<div class="grid-y grid-padding-y cell-block-container">

<div class="cell grid-x grid-margin-x"> <!-- MIND THE CLASSES -->

	<div class="cell">

<h1>Foo</h1>

	</div>

	<div class="cell">

Bar

	</div>

</div>

</div>
```

Or should we always use it like this (with an extra div level):

```
<div class="cell">

	<div class="grid-x grid-margin-x"> <!-- MIND THE EXTRA DIV FOR THE GRID HERE -->

		<div class="cell">

<h1>Foo</h1>

		</div>

		<div class="cell">

Bar

		</div>

	</div>

</div>

```
As I said, there seem to be certain issues with positioning, margins and paddings if I use the first option, though it'd be nice if it worked.

**Comment by brgrz** [comment]
Also what's interesting is that if we put the "auto" class on the "Foo" and "Bar" cells the grid renders the same while this is not the case if the "auto" class is missing.

**Comment by mattbag** [comment]
I would always go with the second scheme.

**Comment by ncoden** [comment]
Globally, this is not recommanded to use different component in a single tag. Properties used by both components may vary and the combo may become incompatible with time without a warning if it was not documented and explicitely stated as supported.

In this case, both `grid-*`/`cell` classes would have no trouble with `flex`, but both uses `margin`/`padding` properties, so bugs might appear. If it is not documented then it should be considered as not supported, not tested and thus not recommanded.

Having additional `<div>` is only a problem where a CSS dependency between parents and childrens is broken (like `:first-child`). But in this case it is recommanded to use additional classes to apply properties (like `my-component--first`).

I'm closing this issue. @brgrz Sorry for the late reply and please let my know if I did not replied correctly to your question.

**Comment by brgrz** [comment]
Thanks for the clarifications @ncoden .
