### ISSUE TITLE
Sticky not working

### ISSUE THREAD

**Issue by lukeyouell** [zurb/foundation-sites#10732]
#### How to reproduce this bug:

1. Set up sticky navigation as per docs

#### What should happen:

Navigation should stick

#### What happened instead:

Navigation doesn't stick

#### Browser(s) and Device(s) tested on:

Chrome (latest)

#### Foundation Version(s) you are using:

6.4.3

#### Test case link:

https://codepen.io/lukeyouell/pen/dVQqBo

**Comment by lukeyouell** [comment]
I've just noticed that this is a duplicate of #10289 and has been fixed in the 6.4.4-rc1

**Comment by nadyafebi** [comment]
This happens because you haven't declared the bottom anchor. So what you can do is either:

1. Delete this part `data-btm-anchor="content:bottom"`.

or

2. Add `id=content` somewhere in your code (but not in the title bar).

**Comment by dospuntocero** [comment]
mine does not work either... not sure what im doing wrong
https://codepen.io/dospuntocero/pen/NXqGed

**Comment by brettsmason** [comment]
@dospuntocero I fixed your CodePen here: https://codepen.io/brettsmason/pen/qpdbQb
Basically you had `data="data-sticky"` instead of `data-sticky` on the main sticky element, and your `data-options` also need to be on the same element.

**Comment by dospuntocero** [comment]
love you @brettsmason, you saved me hours of headaches.

**Comment by colin-marshall** [comment]
Looks like this one is resolved. Thanks @brettsmason @nadyafebi!
