### ISSUE TITLE
[6.4.3] foundation.scss - "$xy-grid: false" parameter missing in foundation-everything mixin

### ISSUE THREAD

**Issue by franklang** [zurb/foundation-sites#10742]
Current source :
@mixin foundation-everything(
  $flex: true,
  $prototype: false
) {

Corrected source :
@mixin foundation-everything(
  $flex: true,
  $prototype: false,
  $xy-grid: false
) {

**Comment by DanielRuf** [comment]
Thanks for reporting. Will check that soon.

**Comment by DanielRuf** [comment]
`$xy-grid: true` is the default in Foundation Sites 6.4.
