### ISSUE TITLE
Broken link in Foundation for Sites homepage

### ISSUE THREAD

**Issue by isaniomoraes** [zurb/foundation-sites#10740]
I am not sure if here is the correct place to send this issue, but here we go:

#### How to reproduce this bug:

1. Access https://foundation.zurb.com/sites.html
2. Click on Docs anchor in thebottom of hero.

![foundation-for-sites-error-404](https://user-images.githubusercontent.com/3224086/31798406-421c3dfe-b512-11e7-8ddc-0f92e26c2bb1.png)

#### What should happen:
Should open https://foundation.zurb.com/sites/docs/

#### What happened instead:
Error `404 page not found` (https://foundation.zurb.com/docs/)

![screenshot from 2017-10-19 21-14-25](https://user-images.githubusercontent.com/3224086/31798497-d57d4bd8-b512-11e7-92df-dea6680447bd.png)

Where can I fix that? I can try to help with this little issue.

**Comment by IamManchanda** [comment]
cc @rafibomb

**Comment by colin-marshall** [comment]
This appears to be resolved. Closing.
