### ISSUE TITLE
_range.scss

### ISSUE THREAD

**Issue by darkpagan** [zurb/foundation-sites#10745]
Small issue in the code 

line: 76

&::-webkit-slider-handle {
      width: $slider-handle-width;
      height: $slider-handle-height;
      margin-top: -$margin;

Should be 

&::-webkit-slider-thumb {

**Comment by denisahac** [comment]
This has been fixed -- see [range.scss](https://github.com/zurb/foundation-sites/blob/develop/scss/forms/_range.scss#L76)

**Comment by colin-marshall** [comment]
Thanks @denisahac. Closing this one out.
