### ISSUE TITLE
Regular anchor links break Orbit layout if the Orbit is not in the current viewport

### ISSUE THREAD

**Issue by markhowellsmead** [zurb/foundation-sites#10751]
#### How to reproduce this bug:

1. Place a regular HTML anchor link target low the page (using `id="myAnchor"`), so that when you go there, an Orbit element at the top of the page isn't visible in the current viewport.
2. The Orbit element doesn't contain any IDs.
3. Link to the page from somewhere else using e.g. _http://mysite.com/#myAnchor_.
4. Click on the link, so that you come to the current page.
5. The anchor works, but the layout of the Orbit (which is out of sight higher up the page) is completely broken. Autoplay seems to work though, which indicates that it has been correctly initialized.

#### What should happen:

The layout of the Orbit should be correct, even if it's not within the current viewport bounds.

#### What happened instead:

The layout of the Orbit is not correct.

#### Browser(s) and Device(s) tested on:

Chrome, Safari, Firefox on Mac. (All newest versions.)

#### Foundation Version(s) you are using:

6.4.3

**Comment by colin-marshall** [comment]
@markhowellsmead can you please provide a test case from CodePen, as our issue template requests? Thanks!

**Comment by DanielRuf** [comment]
Closing as we did not receive a reproducible testcase.
