### ISSUE TITLE
Off-canvas menu cannot close with toggle on menu icon with off-canvas-wrapper

### ISSUE THREAD

**Issue by alexcsandru** [zurb/foundation-sites#10753]
#### How to reproduce this bug:

1. Simple Off-canvas menu with off-canvas-wrapper with top bar outside of canvas
2. (https://codepen.io/alexcsandru/pen/wrVedM)
3. Press the menu icon to open the menu and then click again for close (toggle)

#### What should happen:
When I open the menu on the button, I should be able to close the menu on the same button (toggle)

#### What happened instead:
The menu does not close

#### Browser(s) and Device(s) tested on:
Chrome, Desktop windows 10.

#### Foundation Version(s) you are using:
6.4.3

#### Test case link:

- [CodePen Reproduce code](https://codepen.io/alexcsandru/pen/wrVedM)

**Comment by fawmi** [comment]
you are using `data-open="offCanvasLeft"` which can only open the off-canvas. use `data-toggle="offCanvasLeft"` this will toggle (open and close) off-canvas.

This question should be asked in forum.

**Comment by alexcsandru** [comment]
Auci, i'm so dumb, I thought it was a bug.
Thanks @fawmi !
