### ISSUE TITLE
Event "deeplink.zf.tabs" doesn't seem to work

### ISSUE THREAD

**Issue by glen-84** [zurb/foundation-sites#10750]
#### How to reproduce this bug:

(see test link)

#### What should happen:

Should log `Deep-link ... doesn't`, unless I'm misunderstanding something?

#### What happened instead:

Nothing.

#### Browser(s) and Device(s) tested on:

Windows 10, Chrome

#### Foundation Version(s) you are using:

6.4.3

#### Test case link:

https://codepen.io/glen-84/pen/wrVGoN#panel3d

#### Notes

Someone else also reported this [here](https://foundation.zurb.com/forum/posts/51736-tabs-events).

**Comment by DanielRuf** [comment]
You have to register for the event before it is triggered by foundation.js.

See https://codepen.io/DanielRuf/pen/YeoGZr#panel3d
