### ISSUE TITLE
Problems minifying sass

### ISSUE THREAD

**Issue by helio-correia** [zurb/foundation-sites#10760]
Hi, i'm having some problems on minifying the sass in version 6.4 (tested in 6.4.2 and 6.4.3, with chrome on macOs)

They add this on styles (example below) and every div on hover they change the background. Besides that I had another problem with links. I've tried to comment some files to see the problem and they are in the files @include foundation-button-group; and @include foundation-button;.

:focus, :hover {
    background-color: #cbcbcb;
    color: #0a0a0a;
}

Anyone has this problem?

Best, 
Hélio

**Comment by rafibomb** [comment]
When do you see this happening?
What series of steps do you take to replicate it?

**Comment by helio-correia** [comment]
Forget, I discover the problem, I was using LoaderOptionsPlugin on web pack but i discover that I need to minify the css on the css-loader with an option

**Comment by helio-correia** [comment]
Forget, I discover the problem, I was using LoaderOptionsPlugin on web pack but i discover that I need to minify the css on the css-loader with an option
