### ISSUE TITLE
Possible bug with align-center-middle class in Safari

### ISSUE THREAD

**Issue by dioogbento** [zurb/foundation-sites#10761]
Very simple landing page with footer and centered (vertically and horizontally) main content.

Only in Safari the main content is not centered vertically, but stays on top.

I'm using the XY grid and Flex classes. Please refer to the test case link bellow.

#### Browser(s) and Device(s) tested on:
Firefox, Chrome and Safari on Mac OS 10.10.5
#### Foundation Version(s) you are using:
6.4.3
#### Test case link:
https://codepen.io/koiastudio/pen/ZaQBXv

**Comment by rafibomb** [comment]
Looks like it works fine here. Make sure you have autoprefixer or you add vender prefixes to your project.

<img width="850" alt="screen shot 2017-11-03 at 8 36 06 am" src="https://user-images.githubusercontent.com/5652085/32382343-314c4350-c072-11e7-80b3-4ae5cae24082.png">

**Comment by dioogbento** [comment]
Hi Rafi,

Still doesn't work for me, even with autoprefixer enabled. And how does that apply to Foundation, anyway? Shouldn't Foundation handle possible need of vender prefixes?

![screen shot 2017-11-04 at 10 19 10](https://user-images.githubusercontent.com/8176105/32404912-ea61dada-c149-11e7-9422-a11f2d020e3d.png)

**Comment by rafibomb** [comment]
Yes, Foundation uses Autoprefixer so the CSS download (and the CDN you have loaded) and Sass version both use it. 

Cannot replicate this on Mac OS Sierra 10.12, Using latest FF, Safari 11, or Latest Chrome.

**Comment by dioogbento** [comment]
I am on Mac OS Yosemite 10.10.5 and Safari 10.0.3.
Any known conflicts with these versions? Any possible workaround?

Thank you!

**Comment by dioogbento** [comment]
I've found a workaround for my issue: https://github.com/philipwalton/flexbugs/issues/197

Thank you!
