### ISSUE TITLE
XY Grid (F6.4) does not work on ios 7

### ISSUE THREAD

**Issue by Valduc** [zurb/foundation-sites#10777]
In the documentation Zurb claims that XY Grid is compatible with iOS7+, but it is not.

I have an old iPad3 and an iPhone4s (that I keep for testing).
They have both iOS7, but none show XY Grid correctly.

ps: works fine on my iPhone 6. (with iOS11)

**Comment by Valduc** [comment]
I kept digging and first installed ios8 and then ios9 on the old ipad.
XY Grid only works from ios9 on.  So the Docs should claim: XY Grid supports iOS9+ (and not iOS7+)

**Comment by lbineau** [comment]
Actually I think it is the flex wrap that have a bug on iOS <= 8 (it also uses the old specification of of flexboxes)
https://stackoverflow.com/questions/25360526/row-wrap-in-flex-box-not-wrapping-in-safari/30792851#30792851

**Comment by DanielRuf** [comment]
So far we also have issues. But on Safari < 11. On desktop and mobile devices. I guess this is a webkit related issue?

**Comment by synaesthesia** [comment]
It's not just "XY Grid", even if you choose to download only the version with "Float Grid" (F6.4 too), you still have flexbox used for example by input-group/input-group-button... I have a problem with that and I think that each component that use "display flex" must have this "browser support warning" in the documentation.

I have tested on iPad iOS 8.1.3, Flexbox are not supported at all. So, the documentation must be updated.

User agent: Mozilla/5.0 (iPad; CPU OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B466 Safari/600.1.4

**Comment by DanielRuf** [comment]
webkit / Safari 10 has some serious flexbugs. Currently only Safari 11 is supported by Apple. All old devices can get OS updates and Safari updates afaik.

**Comment by DanielRuf** [comment]
https://foundation.zurb.com/sites/docs/compatibility.html says (last two versions) for Safari mobile so we should probably remove `'ios >= 7'` then? @colin-marshall

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-sites/issues/10299

**Comment by DanielRuf** [comment]
https://foundation.zurb.com/sites/docs/xy-grid.html#browser-support

https://caniuse.com/#feat=flexbox

What should we do here? @colin-marshall

**Comment by DanielRuf** [comment]
Closing as we and Apple do not support older Safari versions.
