### ISSUE TITLE
Float Grid broken in 6.4.3

### ISSUE THREAD

**Issue by ringe** [zurb/foundation-sites#10776]
#### How to reproduce this bug:

1. Install Ruby on Rails
```
$ gem install rails
# File: Gemfile
gem 'rails', '~> 5.1.4'
```

2. Add Foundation 6.4.3 with yarn
```
$ yarn add foundation-sites
# File: package.json
  "foundation-sites": "^6.4.3",
```
3. Copy `_settings.scss` to `app/assets/stylesheets/_settings.scss`
Use Foundation with Sprockets:
```
# File: app/assets/application.css
 *= require foundation-sites/scss/foundation
```

4. Use the following HTML in a template

```    <div class="row">
      <div class="small-4 columns">
          <h6>Kontaktinformasjon</h6>
      </div>

      <div class="small-4 columns">
          <div class="input-group">
            <h6>Sign up for our newsletter</h6>
            <input class="input-group-field" type="email" placeholder="Email address">
          </div>
          <a class="button expanded" href="#">Submit</a>
      </div>

      <div class="small-4 columns">
          <img class="thumbnail" src="http://placehold.it/100">
          <h6>Opening times</h6>
          <p>Mon - Fri 9:00am - 5:00pm</p>
          <p>Sat 9:00am - 8:00pm</p>
          <p>Sun 9:00am - 4:00pm</p>
      </div>
    </div>
```

#### What should happen:
The three .columns containers should have a total width of 1200px with standard settings.
The three .columns should float next to each other.

#### What happened instead:
The three .columns containers have a total width of 1290px, pushing the third .column to the next line.

#### Browser(s) and Device(s) tested on:
Firefox 56 and Chrome 62.0.3202.7 on Ubuntu 17.10

#### Foundation Version(s) you are using:
6.4.3

I switched to the foundation-rails gem, version 6.4.1.2 - this solved the problem.

#### Test case link:

Couldn't reproduce in CodePen.

**Comment by ncoden** [comment]
Hello @ringe. Sorry for the late reply.

For performance reasons, all grids are not availaible at the same time. With Foundation 6.4.3, the "float grid" is disabled by default, and we recommand to use the new XY-grid instead.

To get only the float grid:
* If you use the pre-build Foundation CSS, use `.../css/foundation-float.min.css`.
* If you import the Foundation SCSS, import `.../assets/foundation-float.scss`
* If you want to compile Foundation by yourself, see below:
```scss
$global-flexbox: false;

@import 'path/to/foundation';

@include foundation-everything($flex: false);
```

**Comment by jusefb** [comment]
@ncoden thank you for this solution. Could the Foundation docs be updated to reference this solution as the current documentation does not seem to give correct instructions for people who use the sass version of Foundation?

**Comment by ncoden** [comment]
@jusefb The documentation already have instructions for this, in both installation and grids sections. See https://foundation.zurb.com/sites/docs/grid.html#importing
