### ISSUE TITLE
changing grid-column-count on breakpoint (Zurb-Foundation)

### ISSUE THREAD

**Issue by AlexGraphicDesign** [zurb/foundation-sites#10772]
Hi everybody,

(Sorry for my bad english, i apologize in advance)

I would like to modify foundation to be able to generate a different number of columns on mobile (4 cols), tablet (6 cols) and desktop (10 cols) ... I'm sure it's possible by changing the mixin generation columns but I fails ... Someone can help me?

Thanks a lot !

Alexandre

**Comment by colin-marshall** [comment]
@AlexGraphicDesign you can do this by using the `breakpoint` mixin. So if you were using the XY-Grid, you would do it like this:

```scss
.some-cell {
	@include breakpoint(small) {
		@include xy-cell(4);
	}
	@include breakpoint(medium) {
		@include xy-cell(6);	
	}
	@include breakpoint(large) {
		@include xy-cell(10);		
	}
}
```

Closing this out. If this doesn't answer your question, feel free to reopen. Thanks!
