### ISSUE TITLE
deep linking to tabs seems not to work in MSIE 11

### ISSUE THREAD

**Issue by hubert-ried** [zurb/foundation-sites#10771]
#### How to reproduce this bug:
In f6 it should be possible to set an anchor link to a tabpanel. Clicking on it should open the referenced tab. This works fine in chrome and ff, but not in msie 11 (see jsfiddle-link, click on the "go to panel"-links)

#### What should happen:
Linked tab should open

#### What happened instead:
nothing

#### Browser(s) and Device(s) tested on:
Internet Explorer 11 (11.0.9600.17843), Windows 7 Professional Service Pack 1

#### Foundation Version(s) you are using:
6.4.3

#### Test case link:
https://jsfiddle.net/1zptbLbm/

ADD:
I found a workaround, that seem to work at least in regular tabs: when I select the target tab onclick via "selectTab", everything is fine, smth like:

    $(function() {
        $('.deeplinks').on('click',function(ev){
            $("#example-tabs").foundation('selectTab',ev.currentTarget.hash.substr(1),true);
        });
        $(document).foundation();
    });

Unfortunately we use a responsive accordion tab, where "selectTab" is not implemented:
https://jsfiddle.net/3u172fdb/

**Comment by DanielRuf** [comment]
https://developer.mozilla.org/en-US/docs/Web/Events/popstate#Browser_compatibility

> [3] IE & Edge do not fire the popstate event when the URL's hash value changes, see the bug report.

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/YeMwrJ

This includes a fix which I will provide as PR very soon.

For responsive accordion tabs component see https://github.com/zurb/foundation-sites/pull/10961
