### ISSUE TITLE
Reveal returns focus to last instance of data-open="<reveal id>"

### ISSUE THREAD

**Issue by clcrutch** [zurb/foundation-sites#10780]
#### How to reproduce this bug:

1. Create a button referencing a reveal named "Reveal1"
2. Create a second button referencing a reveal named "Reveal1"
3. Click on the first button
4. Close the reveal
5. Focus is put on the second button.
(See JSFiddle)

#### What should happen:

After closing the reveal, focus should be returned to the HTML element that opened it.

#### What happened instead:

After closing the reveal, focus is returned to the last element on the page that references the reveal.

#### Browser(s) and Device(s) tested on:

Chrome 62, Internet Explorer 11, Firefox 56

Chrome Mobile and Safari Mobile

#### Foundation Version(s) you are using:

Test on latest from develop branch.

#### Test case link:

[JSFiddle](https://jsfiddle.net/clcrutch/1LoLnwud/)

**Comment by DanielRuf** [comment]
You might have to unfocus it with blur.

**Comment by DanielRuf** [comment]
Try

```
    $('#language-reveal').on('closed.zf.reveal', function(){
		setTimeout(function(){
			$('button[data-open="language-reveal"]').blur();
		}, 0);
	});
```

**Comment by clcrutch** [comment]
I added code to unfocus with `blur()`, but now none of the buttons are focused.  I would expect the button that opened the modal to be in focus.

[JSFiddle](https://jsfiddle.net/clcrutch/8464xje1/1/)

**Comment by clcrutch** [comment]
Looking over the code for the reveal, the issue comes about from lines 52 and 424 of foundation.reveal.js (in the master branch).

```javascript
this.$anchor = $(`[data-open="${this.id}"]`).length ? $(`[data-open="${this.id}"]`) : $(`[data-toggle="${this.id}"]`);
```
and
```javascript
anchor.focus();
```

In other words, if there is only one element which matches the query that sets up `$anchor`, then the proper element will be returned to focus.  On the other hand, if there are more than one element returned for the query, the last element returned will be put into focus.

Would it make more sense to store the element that opened the reveal and then put it into focus?  If so, I can submit a pull request implementing that functionality.

**Comment by DanielRuf** [comment]
The last trigger wins and gets the focus. You might want to store the trigger on `open.zf.reveal` and retrieve the value on `closed.zf.reveal?

**Comment by DanielRuf** [comment]
Isn't there already a data attribute which stores this?

**Comment by grgcnnr** [comment]
Just went to make a PR for this but looks like someone else has already committed a solution. Look out for it soon i guess @clcrutch :)

**Comment by DanielRuf** [comment]
@grgcnnr can you provide a link to the PR / commit where this should be solved?

**Comment by grgcnnr** [comment]
@DanielRuf 9fce99e34709e5ec5a2dc1e0ac98e5f1e8c6af84

**Comment by DanielRuf** [comment]
This will land in the next (rc) 6.4.4 release.

**Comment by DanielRuf** [comment]
I guess we can close this issue then?

**Comment by grgcnnr** [comment]
SHUT IT DOWN!

**Comment by DanielRuf** [comment]
Closing as it will be fixed in the next release. Reference: https://github.com/zurb/foundation-sites/commit/9fce99e34709e5ec5a2dc1e0ac98e5f1e8c6af84
