### ISSUE TITLE
Documentation: Visibility classes do not work

### ISSUE THREAD

**Issue by maszynka** [zurb/foundation-sites#10784]
#### How to reproduce this bug:

1. https://foundation.zurb.com/sites/docs/kitchen-sink.html#visibility-classes
2. All visibility classes do not work.

#### What should happen:

Visibility classes should hide/display content depending on viewport (and/or other settings).

#### What happened instead:

They do not work.

#### Browser(s) and Device(s) tested on:

1. Chrome  62.0.3202.94
2. Microsoft Edge 40.15063.674.0
3. FF Quantum 57.0

**Comment by Deckluhm** [comment]
Can you be more specific about what doesn't work?

For me everything looks fine.

**Comment by maszynka** [comment]
> You are definitely not on a small screen.
> 
> You are definitely not on a medium screen.
> 
> You are definitely not on a large screen.

So I'm on what?

If there is one more breakpoint than It's a bit missleading.

**Comment by Deckluhm** [comment]
There are actually 5 breakpoints as you can see here: https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss#L107

But [documentation says that there are only 3 breakpoints](https://foundation.zurb.com/sites/docs/media-queries.html#default-media-queries) so it needs to be updated.

Maybe you want to open a PR to fix that?

**Comment by JeremyEnglert** [comment]
There are three **core** breakpoints. Which I admit, is a bit confusing. For V7, lets keep an eye on a better way to handle that.
