### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by char0n** [zurb/foundation-sites#10783]
Documentation on following [url](https://foundation.zurb.com/sites/docs/button.html#button-disabled) contains a typo.

```scss
@include button-disable);
```
should be
```scss
@include button-disable;
```

**Comment by mminer** [comment]
I too ran into this typo. I'd be happy to fix it, but after some searching I'm unclear where this documentation is generated. Any tips?

**Comment by Owlbertz** [comment]
After looking into this I found [where the mixin is defined](https://github.com/zurb/foundation-sites/blob/db0f5ab0699d55f6fd2553bfbabe84f3da8743eb/scss/components/_button.scss#L206) and believe it should be
```scss
@include button-disabled
```

**Comment by ncoden** [comment]
This seems to be a bug with SassDoc when it encounter `@param [Color]...` instead or `@param {Color}...`.
