### ISSUE TITLE
xy grid broken in Safari 10 (automatic height of cell is wrong)

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#10789]
On Safari 10 we get an empty page. It seems like a cell takes the whole screen dimension and the other cells are not visible.

The issue is not reproducible in Safari 11 and Chromium.

Is this a known issue and are there solutions?
We use Foundation Sites 6.4.3.

**Comment by DanielRuf** [comment]
It seems Safari 10 needs some `height: 100%` for some cells as Safari 10 does not apply it automatically like it is in other browsers and after the spec.

In Safari 11 this is not needed anymore and it works directly without this workaround.

**Comment by colin-marshall** [comment]
@DanielRuf could you please provide us with a test case of this bug? Thanks!

**Comment by colin-marshall** [comment]
Sounds good @DanielRuf. I'll assign this one to you so you can decide what needs to happen.

**Comment by DanielRuf** [comment]
Probably related to https://bugs.webkit.org/show_bug.cgi?id=137730 so I close this for now.
