### ISSUE TITLE
tooltips don't stay open

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#10796]
They always close when I hover over the tooltip text / bubble. Even in the official docs.

**Comment by Deckluhm** [comment]
Please give more info:
- What example of the docs?
- Do you click on the anchor or just hover it?
- What browser/version/OS are you using?

**Comment by DanielRuf** [comment]
I jsut hover it. Generally I would like to see a behavior like in tippy.js.
Without clicking people do not know that they have to click to keep it open and click on the html in the tooltip.

**Comment by DanielRuf** [comment]
I mean https://foundation.zurb.com/sites/docs/tooltip.html#tooltip-clicking

**Comment by DanielRuf** [comment]
My browser is Chrome 62 on macOS 10.12

**Comment by SassNinja** [comment]
@DanielRuf I personally prefer the current behavior and don't see it as a bug.

But I agree there might be cases where the auto close on mouseleave is not desired.
So an additional option to get a similar behavior as the interactivity of [tippy.js](https://atomiks.github.io/tippyjs/) makes sense in my eyes.

@kball what so you think about this?

**Comment by DanielRuf** [comment]
> So an additional option to get a similar behavior as the interactivity of tippy.js makes sense in my eyes.

Definitely. A link in the tooltip is not uncommon and users should be able to select or click content in there like it is possible with tippy.js.

**Comment by Deckluhm** [comment]
Tooltips are supposed to be like the HTML `title` attribute, that means simple and non-interactive.

[Dropdowns](https://foundation.zurb.com/sites/docs/dropdown.html) are what you are looking for if you want interactivity.

**Comment by DanielRuf** [comment]
Well I don't fully agree with that as there are valid usecases for the example mentioned by tippy.js.

I know that popper.js and tooltip.js were suggested for Foundation and it makes sense to keep it open in specific use cases while hovering over the element and the tooltip itself.

A dropdown is not a tooltip and does not have the logic of it (automatic arrows, positioning, reading from title and so on).

So far tippy.js is the only viable solution for us here.

**Comment by colin-marshall** [comment]
Thanks for this feature request. We’re going to close out this ticket, as we will not be adding more features to Version 6, but your request is being considered for Version 7.
