### ISSUE TITLE
[Visibility Classes] Problem with show-for-large-only

### ISSUE THREAD

**Issue by Jankyz** [zurb/foundation-sites#10795]
#### How to reproduce this bug:

1. Step one
a class="alert button tiny show-for-large-only
                            figure
                                p class="fi-upload" /p
                            /figure
                            span Something /span br 
                            p Something Something /p
a
2. Step two
3. Step three

#### What should happen:
the button should to disappear on medium and small and to show only on large screen
#### What happened instead:
the button wont to show on large screen it disappear on medium and small
#### Browser(s) and Device(s) tested on:
Chrome, W10
#### Foundation Version(s) you are using:
Im using latest FoundationPress for Wordpress theme
#### Test case link:
Im working on localhost

- [CodePen with Foundation 6.3.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Float Grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/bRYOMv)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)

**Comment by Deckluhm** [comment]
You are probably on a `xlarge` or `xxlarge` screen and may want to use `show-for-large` (without the `only`).

Check this issue for more info about breakpoints: https://github.com/zurb/foundation-sites/issues/10784
