### ISSUE TITLE
grid xy grid-frame scrolling panel stopped working

### ISSUE THREAD

**Issue by octaviou** [zurb/foundation-sites#10793]
When using grid yx grid-frame, the scrolling panel (sidebar , body) stopped working. It does some sort of overflow: hidden. 

#### How to reproduce this bug:

1. Step one
copy the grid code example from 
https://foundation.zurb.com/sites/docs/xy-grid.html#grid-frame
2. Step two
- try to scroll on the "Independent scrolling sidebal" panel on any browser

#### What should happen:
the panel should scroll down/up
#### What happened instead:
its fixed and the content is cropped 
#### Browser(s) and Device(s) tested on:
Chrome latest, mac
#### Foundation Version(s) you are using:
6.4.4-rc1

**Comment by rafibomb** [comment]
Seems to work here: https://codepen.io/rafibomb/pen/mXeaZK

Is this specific to the RC version?

**Comment by Nagogus** [comment]
Same for me. Stopped working in Chrome 63 and Safari 11 on macos on 6.4.4-rc1 but works on 6.4.3.
Works fine in Firefox

**Comment by DanielRuf** [comment]
@ncoden should I do some bisecting here then when I find the time or someone else?

**Comment by ncoden** [comment]
The first that find the time for this issue will assign himself to it ;)

**Comment by DanielRuf** [comment]
Result of the bisecting:

```
$ git bisect bad
b1924e099540e4e7411a948d776691e1e5746fbf is the first bad commit
commit b1924e099540e4e7411a948d776691e1e5746fbf
Author: Kevin Ball <kmball11@gmail.com>
Date:   Thu Sep 14 12:26:09 2017 -0700

    Add height pinning to cell-block-y

:040000 040000 7ebe7118fa943345d71b494005a86a690065e32a 39bafb6936863eafbc4b53bd7a034fad30f80d49 M      scss
```

**Comment by robslotboom** [comment]
I have re-installed foundation-sites@6.4.4-rc1 but it is still not working.
The strange thing is that the example at codepen does work.

Did I missed something???

**Comment by DanielRuf** [comment]
> I have re-installed foundation-sites@6.4.4-rc1 but it is still not working.
> The strange thing is that the example at codepen does work.
> 
> Did I missed something???

The change / bugfix was introduced later and is only in the develop branch. Released versions are not changed afterwards.

**Comment by DanielRuf** [comment]
Why not just `.cell-block-y {}`?

**Comment by robslotboom** [comment]
Because of the example :-)

<div class="cell medium-4 medium-cell-block-y">
