### ISSUE TITLE
Change OffCanvas width from javascript

### ISSUE THREAD

**Issue by Gambero81** [zurb/foundation-sites#10794]
Hi, is possible to change offcanvas width from javascript? in my page i have different offcanvas and i would like to change the width only for a specific one.

I tried setting the width property but the animation don't work well with this solution.

Thanks

**Comment by klihelp** [comment]
Update the class which have the css styles for width, translate-x..

**Comment by SassNinja** [comment]
It's only possible to change the off-canvas width per breakpoint not individually per elem.
Besides the sizes are CSS-only and not built to be changed via JS.

If you really need different sizes for the same breakpoint and use the overlap transition I'd suggest to to use the greatest width for the settings and work with e.g. `max-width` to limit it for a specific elem.

(that's the way I did it before I've added the `$offcanvas-sizes` feature to the off-canvas component ;) )

**Comment by Gambero81** [comment]
Hi, if anyone is interested i solved the problem with css:
($pnlWidth can be percent or fixed size)

`<div id="pnlAssetHistory" class="off-canvas position-right is-closed" data-content-overlay="false">
...
</div>`

`$pnlWidth: 100%;

    #pnlAssetHistory {
        width: $pnlWidth;
    }

    #pnlAssetHistory.position-right:not(.is-open) {
        transform: translateX($pnlWidth);
    }

    #pnlAssetHistory.is-closed {
        transform: translateX($pnlWidth);
    }`

**Comment by SassNinja** [comment]
@Gambero81 just wondering why you're using the `#pnlAssetHistory.is-closed` since you've already set the translateX via `:not()`.
However glad you could solve your problem (although it has been done in a very unflexible way)

**Comment by Owlbertz** [comment]
Since the issue has been solved above using CSS and there isn't really active anymore, I will close it.
