### ISSUE TITLE
[Installation] Redundant Commands for manuall Install for Templates?

### ISSUE THREAD

**Issue by kunst-der-informatik** [zurb/foundation-sites#10790]
The Installation Steps on https://foundation.zurb.com/sites/docs/starter-projects.html for the manual install have an addional command "bower install", which is not used on https://foundation.zurb.com/sites/docs/installation.html. There is only a "npm install" and no "bower install". So i think, this command is redundant.

#### Foundation Version(s) you are using:

6.4.3

**Comment by DanielRuf** [comment]
Why should it be redundant? Bower is something different than npm, even if it is currently dead.

**Comment by DanielRuf** [comment]
Bower like npm can install any Git / npm repo.

**Comment by colin-marshall** [comment]
@DanielRuf is correct. It's not redundant, because they install different dependencies. Coincidentally, we actually do need to remove `bower install` from the docs for a different reason altogether. We stopped using bower in 6.4.

**Comment by ncoden** [comment]
I am currently updating the installation doc. I'll remove `bower install`

**Comment by colin-marshall** [comment]
@ncoden I realized last night that we are actually still using `bower` in the `foundation-sites-template`. I never use that template and had assumed it was removed in 6.4 when we switched to webpack.

**Comment by ncoden** [comment]
So I'll add it back 😜

**Comment by DanielRuf** [comment]
Hm, the bower info for https://github.com/zurb/foundation-sites-template is missing.

I'll prepare some PRs to move all deps to npm as package manager.
