### ISSUE TITLE
Off-canvas doesn't work on iPad Air / iPad Air 2

### ISSUE THREAD

**Issue by maz123** [zurb/foundation-sites#10797]
#### How to reproduce this bug:

Go to here: https://goo.gl/ythHWw 

View on iPad Air or iPad Air 2

#### What should happen:

Toggle button doesn't shut off-canvas panel

#### What happened instead:

Stays open

#### Browser(s) and Device(s) tested on:

All browsers on this list (using BrowserStack) - https://www.browserstack.com/test-on-the-right-mobile-devices (the big list)

#### Foundation Version(s) you are using:

6.4.2 float layout

#### Test case link:

- [CodePen with Foundation 6.3.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Float Grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/bRYOMv)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)

**Comment by DanielRuf** [comment]
Where can we see your codepen or some more info about your code?

**Comment by maz123** [comment]
Link is in the text.... https://goo.gl/ythHWw

**Comment by SassNinja** [comment]
@maz123 still not a codepen, but at least we can see some code

I've tested the page but for me the off-canvas toggle works without any problem.
First click opens, second click closes.

Did you also test on a real device or only browserstack?

**Comment by maz123** [comment]
Thanks for your reply @SassNinja ,

There is too much code for a code pen, it's too complex, hence why i sent the link.

Did you test it on iPad Air or iPad Air 2?

Cheers

**Comment by SassNinja** [comment]
iPad Air 2 with iOS 11.2

And as I said, I can't reproduce the issue

**Comment by JeremyEnglert** [comment]
No response in 2 weeks. Closing out this ticket. Please feel free to respond with additional details and I'll be happy to reopen it.
