### ISSUE TITLE
Reveal overlays don't have inertia scrolling on iOS

### ISSUE THREAD

**Issue by nitrokevin** [zurb/foundation-sites#10804]
#### How to reproduce this bug:

1. Create a reveal overlay with more content than will fit on screen
2. Visit page on iOS device
3. Overlay scrolls but lacks inertia

#### Browser(s) and Device(s) tested on:
iOS safari
#### Foundation Version(s) you are using:
6.4.3
#### Test case link:

This can be fixed with 
`overflow-y: scroll; /* has to be scroll, not auto */
  -webkit-overflow-scrolling: touch;`

Should this be added by default to the reveal component?

**Comment by colin-marshall** [comment]
@nitrokevin if you wouldn't mind, could you please create a codepen test case? Thanks!

**Comment by DanielRuf** [comment]
We saw the same. See https://github.com/zurb/foundation-sites/issues/10781

**Comment by DanielRuf** [comment]
Should we close this as duplicate and tackle all at once?

**Comment by colin-marshall** [comment]
@DanielRuf yes let's close this one and keep the discussion over at #10781.
