### ISSUE TITLE
Orbit's timer pause function does not work as expected

### ISSUE THREAD

**Issue by simongcc** [zurb/foundation-sites#10806]
I tried to add a pause button to control the orbit.
I manually create an orbit object. And I use the timer's object pause function to pause the slider.
Like this:

`window.slider = new Foundation.Orbit( $('.orbit'), {
        timerDelay: 500
    });`

However, it does not pause and continue to slide although the console log show that the pause is in `true` status. If you test in local environment without iframe, you may try to run `window.slider.timer` again which show different status as shown when click on the pause button.
If you run `window.slider.timer.pause() in the console, it work. I am not sure if it is related to context or scope.

#### How to reproduce this bug:
1. add foundation css/js
2. add the slider copied from example 1 in [Foundation Orbit Docs](https://foundation.zurb.com/sites/docs/orbit.html)
3. add`window.slider = new Foundation.Orbit( $('.orbit'), {
        timerDelay: 500
    });`
4. add a button and event handler to invoke: `window.slider.timer.pause();`
5. click the button

#### What should happen:
The orbit should stop because the timer should be cleared.

#### What happened instead:
The orbit slider timer is keep running.

#### Browser(s) and Device(s) tested on:
Macbook Pro Sierra 10.12 with Chrome Version 63.0.3239.84 (Official Build) (64-bit)

#### Foundation Version(s) you are using:
development version: 6.3.1 js installed by npm
demo version: 6.4.3 js

#### Test case link:
I have created an example to demonstrate the problem.
[Example in CodePen with Foundation 6.4.3](https://codepen.io/simongcc/project/editor/DYykOm)

**Comment by DanielRuf** [comment]
It works when the button is outside of the orbit element because `data-pause-on-hover` resets it.

See https://codepen.io/DanielRuf/project/editor/ZOWxGn
