### ISSUE TITLE
Webpack LibraryTarget - export UMD

### ISSUE THREAD

**Issue by tomm1996** [zurb/foundation-sites#10800]
Hey, I have a question regarding the module format foundation is exported to. Why doesn't foundation use `libraryTarget` to export to UMD? Currently, no libraryTarget is configured in [webpack.config.js](https://github.com/zurb/foundation-sites/blob/develop/webpack.config.js) which means it will default to `libraryTarget: "var"`. 

Now, we are building a project using webpack and CJS sources. We would rather not implement babel for this project and want to use the already transpiled and built es5-version of foundation. <del>Thus, in my understanding, we would have to use the [script-loader](https://webpack.js.org/loaders/script-loader/) to execute Foundation in global scope before we can use it.</del>

**Edit**
I just found out about the `window.Foundation.addToJquery($);`-method so using the script-loader might not be necessary. 
**/Edit**

So my question is: Why was the decision not to export UMD made? Are there any downsides to it?

Thanks in advance

**Comment by ncoden** [comment]
Fixed in https://github.com/zurb/foundation-sites/pull/10864. This sould be released in `v6.4.4`.
