### ISSUE TITLE
Foundation new with Zurb template error on start.

### ISSUE THREAD

**Issue by mattbag** [zurb/foundation-sites#10816]
This is happening but I cannot find out which step of the build is causing it.

#### How to reproduce this bug:

1. Step one: create a new zurb template
2. Step two: $ gulp
3. Step three: error in javascript

#### What should happen:
gulp starts and watch

#### What happened instead:
error written below

#### OSX tested on: 
Sierra 10.12.6 (16G1114)

#### Foundation Version(s) you are using: Latest with foundation cli-as today ( and for some previous days)

This happens:
<img width="817" alt="screen shot 2017-12-22 at 12 27 34 pm" src="https://user-images.githubusercontent.com/17114329/34281540-8ca3c80a-e713-11e7-83d3-3ac47daeba03.png">
 
I also had issues with node-sass, and apparently this gulp setup is it's using 3, while now version 4 is the stable one. It shouldn't be related but maybe it is? Cheers

**Comment by philip-spark5** [comment]
Same here - tried on Mac, Fedora and Windows 10.

**Comment by mattbag** [comment]
It works with one of my projects but, I was not able to pinpoint the difference in the source, the package json is the same. I will be able to give another look on the 27th...

**Comment by Techinfocomp** [comment]
`Foundation watch` works for my old project, but for new project, i am facing the same issue :(
Can it be resolved soon?

**Comment by philip-erben** [comment]
Seems to be a problem with gulp: 

`node_modules/gulp/bin/gulp.js -v`

throws the same error..

**Comment by denisales** [comment]
I have the same error.
<img width="570" alt="sem titulo" src="https://user-images.githubusercontent.com/34402631/34340896-87440322-e973-11e7-8de2-96292d6231d1.png">

**Comment by gricelsepulveda** [comment]
Same error on mac osx, and isn't working on my pc with windows 10. Extremely slow when I tried to install. Since a week ago...

**Comment by ncoden** [comment]
Thanks @gricelsepulveda @denisales @philip-erben @mattbag for the bug reports. I'll take a look at this.

**Comment by Techinfocomp** [comment]
@ncoden can you please let us know that, till when we get this in working mode again?

**Comment by ncoden** [comment]
Ok, this comes from: https://github.com/gulpjs/gulp/issues/2065

Gulp updated their vinyl version to `v3`, and this break some gulp plugins. I'll make a PR.

**Comment by ncoden** [comment]
Fixed I think. See https://github.com/zurb/foundation-zurb-template/pull/76
