### ISSUE TITLE
Turn off awkward "feedback" when click

### ISSUE THREAD

**Issue by johnylaravel** [zurb/foundation-sites#10810]
When I **click** on any link(button, tab...) on mobile, it shows some awkward blue feedback on a second, do you know how to **turn that off**?
![untitled1](https://user-images.githubusercontent.com/30267900/34253883-c135a1c6-e649-11e7-8cf1-531a536120ad.png)

![untitled](https://user-images.githubusercontent.com/30267900/34253887-c694938e-e649-11e7-93a4-ab6e632e6120.png)

On this picture is screenshot how that looks in dev tools, but it's same thing on mobile

**Thanks!**

**Comment by ncoden** [comment]
Hello @johnylaravel. I do not see what link or button your are talking about. Could you provide a codepen with the link on it ?
See: https://codepen.io/IamManchanda/pen/EXbGKJ

**Comment by gtreviranus** [comment]
I know you're still waiting for a reply @ncoden, but in case this helps: @johnylaravel maybe you can directly manipulate the active state of your button with `:active` CSS selector? I would test that first, and if no dice, then I know Android and iOS both have their own native element selection style that could be worth testing against: https://css-tricks.com/snippets/css/remove-gray-highlight-when-tapping-links-in-mobile-safari/

**Comment by johnylaravel** [comment]
@geotrev You are freaking awesome. That's it, problem was webkit selection. **Thank you so much!**

So for anyone, **solution** is to add this peace of code in your css:
```
// Remove tap highlight on iOS
input,
textarea,
button,
select,
a {
  -webkit-tap-highlight-color: rgba(0,0,0,0);
}
```

@ncoden Thanks for trying :D

**Comment by geotrev** [comment]
Glad to help! Cheers.
