### ISSUE TITLE
[tabs] add generated data-index to tabs (and accordions)

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#10812]
It's helpful to get the current active element but also in the core tabs plugin.

I did it like this:
```
$('.tabs').on('change.zf.tabs', function(container, elem){$(container.target).attr('data-index',$(elem).index()+1);});
$('.tabs').each(function(index,item){$(item).attr('data-index',$(item).find('.is-active').index()+1)});
```

**Comment by ncoden** [comment]
@DanielRuf I don't understand why this would be useful, how this could be used. Could you give an example ?

**Comment by DanielRuf** [comment]
The problem was that Edge and IE11 have issues to detect changes and the current active element and so I had to track the current active by some value to get the index of the current active element.

So far I saw no option or value in the core tabs plugin to get the current index of the active / shown element / content.

**Comment by colin-marshall** [comment]
Thanks for this feature request. We’re going to close out this ticket, as we will not be adding more features to Version 6, but your request is being considered for Version 7.
