### ISSUE TITLE
[Reveal] Opening modal create additional scrollbar to body element in Foundation v6.4.4-rc1 (doesn't happen in v6.4.3)

### ISSUE THREAD

**Issue by Rand0mGuy** [zurb/foundation-sites#10824]
#### How to reproduce this bug:

1. Create a Reveal component normally (code from docs also applicable)
2. Open the modal

#### What should happen:
Modal open normally

#### What happened instead:
Modal open and add 2 scrollbars to the body

#### Browser(s) and Device(s) tested on:
Chrome Version 63.0.3239.84 and Firefox Version 56.0 (probably all browser)

#### Foundation Version(s) you are using:
6.4.4-rc1 (the issue doesn't exist on 6.4.3)

#### Test case link:
https://codepen.io/lukeyouell/pen/VrGvQP

![bug](https://user-images.githubusercontent.com/14888588/34392676-3fe309c4-eb80-11e7-914f-fbdd49e8bce9.JPG)

**Comment by ncoden** [comment]
I cannot reproduce it on Firefox & Chrome on macOS, but I can reproduce on Windows.
Also, i have an other bug for Firefox on macOS: the gradient background disapear when the modal is open.

**Comment by ncoden** [comment]
This comes from `html.is-reveal-open` and `.reveal-overlay` that both have `overflow-y: scroll`. So a scrollbar is showed on these two elements even if it is not necessary.

However, I seen there was way more complicated issues on this before, like: https://github.com/zurb/foundation-sites/pull/10583. So if the easy solution would be to replace `overflow: scroll` by `overflow: auto`, I don't think this would be the right thing to do.

@isapir Could you give me some help there ?

**Comment by ncoden** [comment]
For the background bug on Firefox, see https://github.com/zurb/foundation-sites/issues/10791

**Comment by isapir** [comment]
@ncoden I don't remember the details and have no time to look deep into this, but given the information that you already know, why not simply add:

```
.reveal-overlay {
  overflow: inherit;
}
```

See https://codepen.io/isapir/pen/EoWjdb

**Comment by ncoden** [comment]
I am afraid on the `simply` word there. The PR you made should have fixed this bug, and I don't understand everything in it. But in the worst case I'll go the the __too obvious__ idea of `overflow: auto`.

**Comment by isapir** [comment]
My tests showed that it did fix the issue, but there are too many factors here (e.g. other patches by other developers) and I really do not remember the details.

I will try to look into it at a later time, but can't ATM.

**Comment by ncoden** [comment]
Don't worry, it can wait. And thank you.

**Comment by DanielRuf** [comment]
Do we need some more testing here?

**Comment by ncoden** [comment]
poke @isapir

**Comment by ncoden** [comment]
See #11065
