### ISSUE TITLE
ENOENT: no such file or directory, rename ansistyles

### ISSUE THREAD

**Issue by holisticnetworking** [zurb/foundation-sites#10826]
#### How to reproduce this bug:

1. Attempt to install Zurb Foundation CLI by issuing the following command:
npm install --global foundation-cli
2. Error

#### What should happen:
The Foundation CLI should install without errors

#### What happened instead:
Got the following error message:
npm ERR! code ENOENT

npm ERR! errno -2

npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/tomb/npm-global/lib/node_modules/foundation-cli/node_modules/npm/node_modules/ansistyles' -> '/Users/tomb/npm-global/lib/node_modules/foundation-cli/node_modules/npm/node_modules/.ansistyles.DELETE'

npm ERR! enoent This is related to npm not being able to find a file.

npm ERR! enoent

#### Browser(s) and Device(s) tested on:
Mac El Capitan

#### Foundation Version(s) you are using:
Latest stable build

#### Test case link:
Here is a complete log file from my installation:
https://gist.github.com/holisticnetworking/efb6e065cedb43d6467e8e5b5f1de148

**Comment by ncoden** [comment]
I'm working on this.

**Comment by ncoden** [comment]
This only happens where we try to install `foundation-cli` twice. But it doesn't seem related to `foundation-cli`. See: https://github.com/npm/npm/issues/17444

Try:
```
npm uninstall --global foundation-cli
npm install --global foundation-cli
```

**Comment by holisticnetworking** [comment]
That, along with rebuilding node-sass, seems to be working.

**Comment by liamse** [comment]
It is happen after I try to install rimraf package.
**To solve** the problem, I rename **node_modules** to **node_modules_2** and run `npm install`. this download all packages again but it solve the problem form me. After check that everything is work fine, I remove my corrupted **node_modules_2** folder.

**Comment by ncoden** [comment]
@liamse You can simply uninstall then reinstall `foundation-cli`.

**Comment by liamse** [comment]
Thanks @ncoden but I don't have `foundation-cli` at all. 
I think this is NPM issue, and it happens when we want to install more than one packages with same dependencies, I think dependencies make conflict and NPM think that it has a file that does not exist at all. Uninstalling any package, clear something (that I don't know exactly what) in NPM and this solve issue, and we then can install any other package with NPM.

**Comment by webuxr** [comment]
@liamse Have you tried `npm dedupe` (https://docs.npmjs.com/cli/dedupe)? I’m not sure how this might affect your `package.json` but it may be worth a test.

**Comment by jomesili** [comment]
Using npm dedupe solved this issue for me

**Comment by mzunigau** [comment]
not working:
Unistalling / reinstalling 
installing node-sass , gulp-sass
npm dedupe
reinstalling nodejs
so sad, i think i'm gonna quit foundation cli...

**Comment by ncoden** [comment]
@mzunigau This is not a problem with Foundation CLI.

Can you try deleting the global `foundation-cli` folder ? Use `npm ls -gl foundation-cli` to find where it is installed.
```shell
$ npm ls -gl foundation-cli

│ /Users/ncoden/.nvm/versions/node/v8.9.1/lib
│
└── foundation-cli@2.2.5
    Command-line interface for the Foundation family of frameworks.
    git+https://github.com/zurb/foundation-cli.git
    https://foundation.zurb.com
```

**Comment by henryhobhouse** [comment]
We have a similar problem with our internal CLI at the moment. First install perfect. Second time the same error is popping up. Folder has to be deleted before reinstall/update can happy. Let me know if you find a solution as all options found so far haven't seem to fix the issue. I should add that the issue seems to only be on Linux.

**Comment by torican** [comment]
Uninstall/reinstall worked for me.... Ubuntu 16.04.3 LTS

**Comment by DanielRuf** [comment]
> along with rebuilding node-sass

If this is the case try `npm rebuild node-sass --force`

**Comment by DanielRuf** [comment]
Shoul we reopen this one here or create a new issue?

**Comment by DanielRuf** [comment]
```sh
$ npm install --global foundation-cli
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
C:\Users\Daniel\AppData\Roaming\npm\foundation -> C:\Users\Daniel\AppData\Roaming\npm\node_modules\foundation-cli\bin\foundation.js
+ foundation-cli@2.2.5
updated 2 packages in 48.586s

$ npm install --global foundation-cli
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
C:\Users\Daniel\AppData\Roaming\npm\foundation -> C:\Users\Daniel\AppData\Roaming\npm\node_modules\foundation-cli\bin\foundation.js
+ foundation-cli@2.2.5
updated 1 package in 11.122s


$ npm install --global foundation-cli
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
C:\Users\Daniel\AppData\Roaming\npm\foundation -> C:\Users\Daniel\AppData\Roaming\npm\node_modules\foundation-cli\bin\foundation.js
+ foundation-cli@2.2.5
updated 1 package in 13.129s
```

```sh
$ node --version
v8.8.1

$ npm --version
5.3.0
```


Not reproducible (anymore).

Please provide more info about your environment.

**Comment by Anke** [comment]
Getting this message trying to download custom build (only forms, changed grid's max-width to 60 as well as colors) from your download page: 
ENOENT: no such file or directory, stat '/tmp/tmp.6.5.1.c4d2f0efbeb98b1c44ef947b272a60f9.zip'

**Comment by DanielRuf** [comment]
Hi @Anke,

please see https://github.com/foundation/node-foundation-customizer/pull/13 and https://github.com/foundation/foundation-sites/issues/11795 and also https://github.com/foundation/foundation-sites/issues/11826
