### ISSUE TITLE
Failed to load external module @babel/register with cli 

### ISSUE THREAD

**Issue by ralts00** [zurb/foundation-sites#10828]
Help, I start the project with cli, and it gives me this error, in the end if it starts the server but it always gives me this error and I do not know if it's something very bad.

![captura de pantalla 2017-12-29 13 21 26](https://user-images.githubusercontent.com/5034252/34445714-38b19424-ec9b-11e7-811d-95d3d5faabda.png)

**Comment by gtreviranus** [comment]
Hmm, interesting. I'm getting the same problem after a fresh install of Foundation CLI and then setting up a new foundation email project. Wasn't expecting this to be so easy to reproduce!

Considering babel has gone through some significant changes in the last year, it wouldn't surprise me if a package previously used in foundation emails isn't available anymore.

**Comment by gtreviranus** [comment]
Found a similar issue here: https://github.com/gulpjs/gulp/issues/1631

Looks like `babel/register` is there as a fallback, in case `babel-register` fails to work (which is the default in this case). Just a hypothesis, though, based on that link.

The whole thing ends with this comment for more clarification:
```
Your project is still working, it's just attempting to use the "new" babel thing before it uses the old one you are depending on. 
```

**Comment by ncoden** [comment]
```
Not an issue, as it states on the next line down, it required babel-core/register. Babel now suggests you use a module called babel-register so we try that first with the fallback. Please read your entire log before creating an issue.
```

**Comment by ralts00** [comment]
but it is a problem, because an error appears in red, they should eliminate that error in red @ncoden

**Comment by phated** [comment]
@ralts00 it's only an issue if you are deathly allergic to the color red.  However, I've opened an issue at https://github.com/gulpjs/gulp-cli/issues/142 to consider changing the color.

**Comment by ralts00** [comment]
@phated I thank you very much for taking the comments of the community :)
