### ISSUE TITLE
Email inliner does not work

### ISSUE THREAD

**Issue by antoniogarcez** [zurb/foundation-sites#10841]
#### How to reproduce this bug:

1. Access [https://foundation.zurb.com/emails/inliner.html]();
2. Copy a large HTML string;
3. Click on "Convert Email".

#### What should happen:

After clicking on "Convert Email", your application should return my HTML with inline styles.

#### What happened instead:

Shows the message "Loading...",
![image](https://user-images.githubusercontent.com/5618128/34679420-d166d180-f48d-11e7-9077-67da834a75c4.png)

and, if I open developer tools, it will show this error:
![image](https://user-images.githubusercontent.com/5618128/34679514-217821ce-f48e-11e7-9b8b-425c6d996f38.png)

If I put a smaller HTML string, it works perfectly.

**Comment by DanielRuf** [comment]
That is the wrong project. You mean https://github.com/zurb/foundation-emails
