### ISSUE TITLE
[Feature Request] !important rules on 'show-for-sr'

### ISSUE THREAD

**Issue by diniscorreia** [zurb/foundation-sites#10850]
The only CSS property on `.show-for-sr` with an '!important' rule is `position`. However, there are several cases where it would be more fail-proof to add `!important` to most (all?) properties: if you use this class you definitely want to hide the text, no matter if another class on the same element changes any of these properties. 

It also shouldn't be dependent on the cascade – on one of my projects I have some CSS rules as part of the critical path (and the rest of the CSS loaded after that), which means, for example, that the `forms` CSS rules are loaded after the visibility classes, causing some issues on a `<input type="file">` with the `show-for-sr` class.

**Comment by ncoden** [comment]
Most of our classes should depends on cascade. Our components must be customizable (in Sass AND in CSS) so their properties must be overridable without having to increase the specificity.

However, I agree that some classes can have a "deterministic and uncustomizable behavior", and so can use `!important` on their properties to ensure that. But we should be careful about this, explicit in the documentation, and not begin to use `!important` everywhere to make things "work" quickly.

In a perfect CSS architecture, this would be an entirely separated type of classes. A sort of "stand-alone `state`" with a particular prefix.

So 👍 for `show-for-sr`.

**Comment by ncoden** [comment]
@diniscorreia See https://github.com/zurb/foundation-sites/pull/10851

Thank you for having reported this issue 😉
