### ISSUE TITLE
[Magellan] active class when scrolling to section?

### ISSUE THREAD

**Issue by anephew** [zurb/foundation-sites#10857]
Hello!

Does the plug-in support the use of the active class when scrolling the page?
Now the class is applied when we click on the menu link only.

Thank you

**Comment by ncoden** [comment]
Hello @anephew,

Magellan should currently add a `.is-active` class on the targetted link, on click _and_ on scroll. Could you provide a codepen with the bug you describe ?

Note: from Foundation v6.4.0, `.is-active` in the default classe instead of `.active`.

**Comment by anephew** [comment]
@ncoden 

https://codepen.io/anephew/full/QarPdr/

**Comment by ncoden** [comment]
hmmm There is `.is-active` classes on links when scrolling.
* Were you talking about classes in sections ?
* Otherwise, on what browser & OS are you testing ?

**Comment by anephew** [comment]
@ncoden 

1) Yes, I'm talking about a "is-active" class, that was not apply when scrolling a page (when click - yes)

2) Vivaldi 1.14.1064.3 (Official Build) (64-bit)

![bug](https://user-images.githubusercontent.com/551514/34869076-de96ef78-f796-11e7-822a-52faaad85d99.gif)

**Comment by anephew** [comment]
@ncoden

Yes, in Firefox it works for example...

**Comment by ncoden** [comment]
I made some research. The problem seems to come from Vivaldi which does not provide `attributeName` in the `MutationRecord` object after a change of `[data-events]` (see  function `Triggers.initializers.addMutationEventsListener`).

**Comment by anephew** [comment]
@ncoden 

Big thank you! I will write about this bug in the Vivaldi bugreport

**Comment by DanielRuf** [comment]
@anephew is there any update or link to the bug report?

**Comment by reeslo** [comment]
There is a problem here https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.triggers.js#L185

Sometimes $nodes.length = 0 sometimes no, with Firefox Quantum 63.. on Safari 10.1.2 too

**Comment by DanielRuf** [comment]
@reeslo please create a new issue, provide a codepen that reproduces / demonstrates this and provide all relevant information.

**Comment by ncoden** [comment]
Closing this issue as Vivaldi is not supported.
