### ISSUE TITLE
[Accordion Menu] $accordionmenu-padding not working properly

### ISSUE THREAD

**Issue by goerba** [zurb/foundation-sites#10854]
**Foundation version 6.4.3**

The easiest way to check this out, is by going to the [Accordion Menu](https://foundation.zurb.com/sites/docs/accordion-menu.html) page on the Foundation Docs site. Scroll down to an example accordion menu and inspect 'Item 1' with your developer toolbar.

You will see the following:

`.menu a, .menu .button {`
    `line-height: 1;`
    `text-decoration: none;`
    `display: block;`
    `padding: 0.7rem 1rem;`
`}`

`.accordion-menu a {`
   `padding: 0.7rem 1rem;`
`}`

The `.accordion-menu a` style is being overruled by the `.menu a` style, because of the order in which the SCSS mixins are loaded in `foundation.scss`.

So even when you change the `$accordionmenu-padding` variable in the settings, it will never be used on this level, because of that.

**Comment by ncoden** [comment]
Currently, import in `foundation.scss` are sorted alphabetically.

**This is a very bad idea**.

Import order in Sass matters a lot as the last CSS properties declared will override the first ones. So components should be sorted in a more "generic" to more "specific" components. When a component relies on others (like `accordion-menu` with `menu`), these dependencies should be imported before.

**Comment by ncoden** [comment]
@goerba See https://github.com/zurb/foundation-sites/pull/10856
