### ISSUE TITLE
Top Bar not showing in Chrome v64 (Beta)

### ISSUE THREAD

**Issue by jitens** [zurb/foundation-sites#10853]
However if you are viewing the Top Bar in incognito / private browsing mode the Top Bar shows.

Anyone got any ideas for a fix?

#### How to reproduce this bug:

1. Open https://foundation.zurb.com/sites/docs/top-bar.html 

#### What should happen:

The Top Bar menu should be visible and functioning

#### What happened instead:

The Top Bar menu disappears, not visible on screen but markup is in source code.

Any feedback would be great.

#### Browser(s) and Device(s) tested on:

Chrome Browser Version 64.0.3282.85 (Beta) (64 Bit) on Windows 10.

#### Foundation Version(s) you are using:

6.3
6.4.3

#### Test case link:

- [Zurb Foundation Document - Top Bar](https://foundation.zurb.com/sites/docs/top-bar.html)

**Comment by ncoden** [comment]
Hi @jitens.

I cannot reproduce the bug. Could you provide a codepen, or at least a screenshot ?

Thank you

**Comment by jitens** [comment]
Hi @ncoden,

The screen shot below is from Chrome Beta, the Top Bar is not visible just a grey background colour:

![l_1374 tmp](https://user-images.githubusercontent.com/26116231/34829339-4ef81022-f6d8-11e7-9524-1eec56384559.png)

The screen shot below is from Chrome stable, with the Top Bar visible:

![top-bar-visible](https://user-images.githubusercontent.com/26116231/34829447-a0a7d1c8-f6d8-11e7-9719-8cb8b034ec11.PNG)
 

I hope this helps.

Thanks.

**Comment by ncoden** [comment]
Thank you @jitens

**Comment by ncoden** [comment]
Hmmm I cannot reproduce with BrowserStack:

Chrome Browser Version 64.0.3282.15 (Beta) (64 Bit) on Windows 10.

Do you have any extension installed ?
Could you give more details about the CSS properties applied on the topbar, that would make its content invisible ?

**Comment by jitens** [comment]
Hi @ncoden looks like I've got the Top Bar to load fine, appears to be one of the extensions/plugins causing the page to not render correctly. I've disabled all plugins.

Thank you for your help.
