### ISSUE TITLE
[Feature request] CSS selector in `data-toggle`

### ISSUE THREAD

**Issue by bpierson** [zurb/foundation-sites#10855]
It seems like the toggle component would be a lot more effective and easy to use for multi-targeting if it allowed CSS standard selectors instead of id values. For example instead of this:

`data-toggle="some-id"`

it would be better to allow syntax like this:

`data-toggle="#some-id, #other-id"`
`data-toggle=".my-class"`

Currently, these both fail with a Sizzle syntax error: "Syntax error, unrecognized expression: "

**Comment by ncoden** [comment]
I like this feature. The main problem is to not introduce breaking changes.

Maybe something like this:
* `some-id` -> target `$("#some-id")`
* `some-id another-id` -> target `$("#some-id")` and `$("#another-id")`
* `#some-id ` -> special character delected: target `$("#some-id")`
* `.class a ` -> special character delected: target `$(".class a")`

Or:
* `some-id` -> target `$("#some-id`
* `some-id another-id` -> target `$("#some-id")` and `$("#another-id")`
* `$(#some-id) ` -> target `$("#some-id")`
* `$(.class a)` -> target `$(".class a")`

**Comment by bpierson** [comment]
@ncoden the way the selector is right now, it looks like an "element" selector (because it's just the id value without the hash). I suppose this behavior could be maintained as it's unlikely (though not unheard of) that you'd want to collapse a whole set of elements based on their tag name! I like your first set of options. I think the main thing is to allow the "#" and "." without crashing Sizzle, and to simply treat `"#some-id"` and `"some-id"` the same way.

Or perhaps introduce a replacement attribute that mimics `data-toggle`, but uses completely standard CSS selectors?

`data-toggle-selector="#id1, #id2"` (note the comma indicating an `or` selector). This way you could maintain the current behavior of `data-toggle`, then deprecate it in a future version.

**Comment by ncoden** [comment]
> `data-toggle-selector`

That's a solution. But I would like to add more attributes for what is basically the same feature. A lot of things (inside and outside Foundation) relies on `data-toggle`, and we would have to update all that to support both attributes (and make some code duplication).

**Comment by bpierson** [comment]
True. I suppose it will be enough work just making it work with (most) CSS selectors. Thanks!

**Comment by colin-marshall** [comment]
Thanks for this feature request @bpierson, this sounds useful. We’re going to close out this ticket, as we will not be adding more features to Version 6, but your request is being considered for Version 7.
