### ISSUE TITLE
Error after I run founation watch

### ISSUE THREAD

**Issue by npardon** [zurb/foundation-sites#10863]
I recently installed foundation 6.4.3 on my computer using the foundaton cli, however when I run foundation watch I get this error:

`C:\Users\N. Ardon\Documents\my stuff\foundation-flexbox\myprojects>foundation watch

> foundation-zurb-template@1.0.0 start C:\Users\N. Ardon\Documents\my stuff\foundation-flexbox\myprojects
> gulp

>[23:42:02] Failed to load external module @babel/register
>[23:42:02] Requiring external module babel-register
>[23:42:27] Using gulpfile ~\Documents\my stuff\foundation-flexbox\myprojects\gulpfile.babel.js
>[23:42:27] Starting 'default'...
>[23:42:27] Starting 'build'...
>[23:42:27] Starting 'clean'...
>[23:42:27] Finished 'clean' after 306 ms
>[23:42:27] Starting 'pages'...
>[23:42:27] Starting 'sass'...
>[23:42:27] Starting 'javascript'...
>[23:42:27] Starting 'images'...
>[23:42:27] Starting 'copy'...
>[23:42:31] 'sass' errored after 3.48 s
>[23:42:31] Error: Node Sass does not yet support your current environment: Windows 64-bit with >Unsupported runtime (59)
>For more information on which environments are supported please see:
>https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (C:\Users\N. Ardon\Documents\my stuff\foundation-flexbox\myprojects\node_modules\gulp-sass\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\N. Ardon\Documents\my stuff\foundation-flexbox\myprojects\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)`

'
I have already tried npm babel/register, npm gulp 
I have used the the basic did not seem have a probem 
I have sass version 3.5.5 
I have a windows 10 64bit 

I am not sure what to do any help would be appreciated thanks.

**Comment by DanielRuf** [comment]
You can ignore the babel/register warning which is just a warning from Babel.

Did you try `npm rebuild node-sass --force`?
What does `node --version` say?

**Comment by DanielRuf** [comment]
And try `npm install --global --production windows-build-tools` before this so node-sass can be compiled.

**Comment by colin-marshall** [comment]
@npardon @DanielRuf this is more than likely the same issue described here:
https://github.com/olefredrik/FoundationPress/issues/1148

`node-sass` 3.x has no binaries for node.js 8.x or newer. To fix it, you need to bump the `gulp-sass` version in `package.json` to `3.1.0`, so it depends on version 4 of `node-sass`.

I think we can bump this in the templates, but will have to test first.

**Comment by DanielRuf** [comment]
I don't think that this is the issue. We use node 8.9 and npm 5 and our projects work with the default templates and dependencies.

**Comment by colin-marshall** [comment]
@DanielRuf I've actually seen inconsistencies with this where sometimes it worked for me and other times it didn't (using various Node 8+ versions). In the thread I linked you can see that I mention it worked for me.

Also, a contributor to `node-sass` said this:
> Node 8 is only supported with node-sass 4.5.3
Source: https://github.com/sass/node-sass/issues/2017#issuecomment-308267657
 
Why it works sometimes, I have no idea. No matter what, I would like @npardon to try bumping it and see if it fixes the issue.

**Comment by DanielRuf** [comment]
Like I said, on Windows (and many other platforms) you (often) have to build it with node-gyp.
There are not all binaries on GitHub, just a few.

```
...
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\Users\Daniel\GITHUB\sass-win10\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Daniel\GITHUB\sass-win10\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
...
```

**Comment by colin-marshall** [comment]
@DanielRuf sounds like you are right, however, I don't see any reason to not bump it to 3.1.0. `gulp-sass` 3.1.0 was released just over a year ago. I have a feeling the longer we hold out on it, the more issues like this will pop up.

For the long term, I agree that we should move to webpack to build the Sass as you mentioned in my PR on the template.

**Comment by npardon** [comment]
@DanielRuf sorry I took so long to reply.  My node version is 9.4, my npm version is 5.60. I also tried a fresh gulp sass like you did it did not seem to work I still got an error.
