### ISSUE TITLE
[Magellan] Get the section id when we scroll to it?

### ISSUE THREAD

**Issue by anephew** [zurb/foundation-sites#10865]
Is it possible to get the section id when we scroll to it? Any data in magellan events?

**Comment by ncoden** [comment]
See the [Javascript Reference](https://foundation.zurb.com/sites/docs/magellan.html#js-events) of Magellan:

> Name | Description
> -- | --
> update.zf.magellan | Fires when magellan is finished updating to the new active element.

**Comment by anephew** [comment]
@ncoden

Error in console:
`$elem.attr is not a function`

Also, I do not see the id in the object. for example:


```
$('#magellan').on('update.zf.magellan', function(elem) {
 console.log(elem);
});

```

**Comment by ncoden** [comment]
You can try:
```js
$('#magellan').on('update.zf.magellan', function(elem) {
   elem[0].getAttribute('id');
});

**Comment by anephew** [comment]
@ncoden

`elem[0] is undefined`   8(

**Comment by anephew** [comment]
`console.log(elem[0].getAttribute('href'));`

**Comment by anephew** [comment]
@ncoden 

This work, check it

`$('#magellan').on('update.zf.magellan', function (ev, elem) {
  console.log(elem[0].getAttribute('href'));
});`

**Comment by anephew** [comment]
It's bad that the "update.zf.magellan" event happens more than once (4 and more more...) with manual scrolling (not by the menu link). UPD: with click on menu - it happens 2 times.. 
![image](https://user-images.githubusercontent.com/551514/34947969-d3d1fa0a-fa1c-11e7-918b-cf452c435f21.png)

I have full height section of window. If I do a check on the id section (for example - to show/hide some block when we switched to it), then this block is hide/show several times. It looks like i need to use a third-party plug-in to determine what's in the browser vieweport now 8(
