### ISSUE TITLE
[Improvement] Add align-evenly to the flexbox utility classes

### ISSUE THREAD

**Issue by mwinkelm** [zurb/foundation-sites#10878]
Hi folks,

I came across a use case where I wanted to use `justify-content: space-evenly`. I recognized that there are some utility classes for this kind of horizontal alignment. See: https://foundation.zurb.com/sites/docs/flexbox-utilities.html#horizontal-alignment 
Unfortunately they are not "complete" from my perspective. Maybe there is a reason why this setting is not in the list? 

But I think it is very useful when you want to have the same space between the elements and at the edges in a row.

Although it's a no brainer to build this class on your own, I think it would make Foundation a tiny bit more complete. ;-)

Please let me know if it's worth to create a PR.

Thanks,
Markus

**Comment by ncoden** [comment]
Hi @mwinkelm,

`space-evenly` is only supported by the latest versions of Chrome and Firefox and does not seems to be standard (see https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content).

Also, there is no mention of it in the [W3C flexbox specification](https://www.w3.org/TR/css-flexbox-1/#justify-content-property). So I don't think we should add it in Foundation.

**Comment by mwinkelm** [comment]
Thank you! I **fully** agree with you.

Question can be closed.

**Comment by mikepostma** [comment]
Might be worth revisiting this as space-evenly is now widely supported (see https://caniuse.com/#feat=justify-content-space-evenly).

**Comment by DanielRuf** [comment]
Hi @mikepostma,

Foundation Sites targets IE 9/10+ so this is currently not an option for the framework ;-)
