### ISSUE TITLE
Stop sticky item from going past a point

### ISSUE THREAD

**Issue by DNA-Matt** [zurb/foundation-sites#10872]
More of a question than issue, is it possible to stop a sticky item from going past a point, for example bottom of a column

**Comment by ncoden** [comment]
Hi @DNA-Matt,

See the first example in the documentation: https://foundation.zurb.com/sites/docs/sticky.html
The sticky element will stop at the bottom of its container set with `[data-sticky-container]`.

Does this answer your questions ? :)

**Comment by JeremyEnglert** [comment]
@ncoden answered this. Closing for now.

Feel free to re-open if the above didn't answer your question.

**Comment by IamManchanda** [comment]
@DNA-Matt we are awaiting your reply
