### ISSUE TITLE
failing unit tests

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#10886]
jQuery 3.3.0 introduced some deprecations which also cause that 40 unit tests fail because the new implementations of jQuery.type, jQuery.isFunction and so on seem to be wrong.

https://github.com/jquery/jquery/commit/a16339b8933f115da3661f3d3f64854c3fa60bdc causes this.

**Comment by DanielRuf** [comment]
cc @ncoden and other Zurbians

**Comment by colin-marshall** [comment]
I don't have time to look into this at the moment, but really appreciate you helping us get to the bottom of this @DanielRuf. Since there is no description for this issue, do we find all info we need about this in the PR you opened on the jQuery repo?

**Comment by DanielRuf** [comment]
Exactly. I did a `git bisect` and the new deprecations and the (wrong) checks for `isFunction` and `isTyp` are definitely rhe cause that the unit tests (40 in total) are suddenly failing.

**Comment by DanielRuf** [comment]
https://github.com/jquery/jquery/pull/3956#issuecomment-361017671
> but if you can provide a reduced case in gh-3955

Well, I'm not sure but so far the unit tests should be enough or what do they need?
For me it was pretty clear when I did `git bisect` in node_modules/jquery.

Also their other unit tests seem to be wrong.

I need some support with this.
I know that jQuery 3.3 lets the unit tests fail.
I know this is due to the deprecations which change the behavior of the methods.
I know that fixing this to get the testsuite succeeding again (the only change was jQuery 3.2.1 > 3.3.1) broke unit tests of jQuery so I tried to fix these also (well, they are partially wrong as they were before imo).

**Comment by DanielRuf** [comment]
Added link to the commit which causes this.

**Comment by colin-marshall** [comment]
@DanielRuf for the short term should do you think we should change `package.json` from `"jquery": ">=3.0.0"` to `"jquery": "~3.2.1"` so we can utilize our tests? 

@zurb/yetinauts

**Comment by DanielRuf** [comment]
Definitely. I would lock it to 3.2.x as the highest version.

**Comment by colin-marshall** [comment]
@DanielRuf sorry I missed this earlier:
> I need some support with this.

What can we do to help you?

**Comment by DanielRuf** [comment]
I have a reproducible test case:
https://github.com/jquery/jquery/issues/3955#issuecomment-364768805

reproducible testcase:
https://github.com/DanielRuf/mocha-jquery-test

try it with `npm install && npm run test`
then `npm install jquery@3.2.1 && npm run test`

Ok, here are my test results:

`$html = $('<form data-abide novalidate></form>').appendTo('body');`

The issue starts at the `append` and `domManip` method.
There we have `scripts = jQuery.map( getAll( fragment, "script" ), disableScript );`
A short test yields that `getAll( fragment, "script" ).length` is `0`.
In `jQuery.map` we use `if ( isArrayLike( elems ) ) {` which contains
```javascript
var length = !!obj && "length" in obj && obj.length,
	type = toType( obj );

if ( isFunction( obj ) || isWindow( obj ) ) {
	return false;
}
```

`console.log(type, isFunction( obj ))` results in `object true`.

Reverting it to
```javascript
var length = !!obj && "length" in obj && obj.length,
	type = toType( obj );

if ( type === "function" || isWindow( obj ) ) {
	return false;
}
```

fixes it

> We move deprecated APIs to the deprecated module which can be excluded in a custom build.
> 
> Deprecation is unrelated to this issue, though. We still need a test case.

I did not see any change in the `deprecated` module also isn't jQuery.migrate meant for this or did I misinterpret its mission?
> Upgrading libraries such as jQuery can be a lot of work, when breaking changes have been introduced. jQuery Migrate makes this easier, by restoring the APIs that were removed, and additionally shows warnings in the browser console (development version of jQuery Migrate only) when removed and/or deprecated APIs are used.

**Comment by DanielRuf** [comment]
I guess we should switch to puppeteer, chromeless or some other solution. We can also try to use a pure phantomjs 2 for testing.

At least I have ported the testsuite (just as an example, I know that js-tests.js is generated) to jasmine as mocha is also looking for maintainers.

https://github.com/DanielRuf/foundation-sites-unit-tests

**Comment by JeremyEnglert** [comment]
@DanielRuf - do you have an email I can reach you at?

**Comment by DanielRuf** [comment]
> do you have an email I can reach you at?

You can use the one that I have on my personal website under "legal".

**Comment by DanielRuf** [comment]
Closing as we have solved this by moving to a Chrome headless implementation instead of PhantomJS.
