### ISSUE TITLE
[Interchange] Support for background images without file extension

### ISSUE THREAD

**Issue by diniscorreia** [zurb/foundation-sites#10883]
I know this is an edge case, but is there any way to have Interchange support background images without a file extension? 

On one of my projects I have to use the company's image server, which returns the images with a URL without an actual file extension. I basically modified the regex on Interchange to match the image server's subdomain.

**Comment by ncoden** [comment]
@diniscorreia See: https://github.com/zurb/foundation-sites/pull/10884

**Comment by JeremyEnglert** [comment]
@diniscorreia, see @ncoden's message above. It looks like it may meet your needs.

In the meantime, I'm going to close out this ticket. Expanding upon this idea will be considered for the next version of Foundation - thanks for the idea!
