### ISSUE TITLE
Foundation 6.4.3 Tabs don't work with pagination?

### ISSUE THREAD

**Issue by cordial** [zurb/foundation-sites#10882]
hey,

Apologies for posting here, I tried the forums but no replies. This might be a feature request more than an issue (unless something is wrong and it is in fact an issue). My question is - can foundation tabs have pagination out of the box or does this require manual use of AJAX to accommodate? For reference, the site I am making is Wordpress and I have tabs set up correctly to display custom post types (news articles) and each tab is the results for each of the terms of a custom taxonomy (news categories). However, I now need to add pagination. I think I might have to back out foundation tabs (and use an unordered list instead), as it isn't going to work with that.

nb. I have deep linking set to true but it doesn't have to be if that helps my issue. 

https://foundation.zurb.com/forum/posts/55778-pagination-with-foundation-643-tabs
for more details. 

I'd be happy with a 'You can't do that with foundation tabs', so that I can try to focus on doing it another way and then we can call this a feature request. 

cheers
David

**Comment by JeremyEnglert** [comment]
I think this is an extreme edge case. But let me see if I can point you in the right direction.

- You can query all posts and then load them into tabs (for example, 10 posts per tab). This will take a bit of PHP knowledge.
- You could use the WP API to query posts and then dynamically add them to tabs using JS.

Hope this gets you going in the right direction!

**Comment by Syed51214** [comment]
[best routers under 100](https://bestreviewsproducts.com/router-under-100/)
). ISP-provided cable modem/router combos usually suck, which is why we've come up with a list of the 3 best cable modem routers you can get for under $100.
