### ISSUE TITLE
drilldown doesn't show all submenu-LIs on iPad

### ISSUE THREAD

**Issue by vincentvermeer** [zurb/foundation-sites#10919]
#### How to reproduce this bug:
```
<ul class="menu vertical xlarge-horizontal" data-auto-height="true" data-responsive-menu="drilldown xlarge-dropdown" data-back-button='<li class="js-drilldown-back"><a tabindex="0">back</a></li>'>
<li>First navigation
   <ul class="menu">
	<li>Second navigation 1</li>
	<li>Second navigation 2</li>
	<li>Second navigation 3</li>
	<li>Second navigation 4</li>
	.....
```

#### What should happen:
When i click on a navigation point with subnavigation in the drilldown menu, i want to see the back button and ALL subnavigation points

#### What happened instead:
The first navigation is shown correct, but when i click on a navigation point with children, i see only a few or no subnavigation points (only the "back"-button) on an iPad or iPhone
In the debugger, the navigation points exists.

#### Browser(s) and Device(s) tested on:
native iPhone, native iPad, Chrome Device Toolbar
It works when i decrease desktop screen-size to iPad-size or iPhone-size (not using the chrome device-toolbar)

#### Foundation Version(s) you are using:
6.4.4 rc1

**Comment by ncoden** [comment]
Hi @vincentvermeer. I don't understand the problem. Could you provide screenshots or a codepen ?

**Comment by vincentvermeer** [comment]
Page on a (small) desktop:
![desktop](https://user-images.githubusercontent.com/3296055/35960235-367558fc-0ca9-11e8-9bd1-2c1594632dac.jpg)

The same page on Desktop (with chrome device toolbar 'ipad') OR on native iPad:
![ipad](https://user-images.githubusercontent.com/3296055/35960268-58c45ee4-0ca9-11e8-8544-37acff2972db.jpg)

The subnavigation points are there, but they aren't shown.
I think because of wrong calculation of the height:
Desktop: <div class="is-drilldown" style="height: 314px; max-width: 1005px;">
Device Toolbar: <div class="is-drilldown" style="height: 76.75px; max-width: 1008px;">

**Comment by DanielRuf** [comment]
iOS uses webkit. Please provide the version of iOS and Safari / webkit so we can test this better.

**Comment by DanielRuf** [comment]
And a real codepen example would be very helpful to reproduce it with the surrounding markup.

**Comment by vincentvermeer** [comment]
Okay, here is a codepen-example: https://codepen.io/vincentvermeer/pen/mXZoYW
Two navigation points, the second has 7 submenu points. But this submenu isn't shown in iphone or on Chrome Device Toolbar (when you switch to device toolbar, select iPhone 8 p.e.  AND reload the page)

**Comment by vincentvermeer** [comment]
![screen](https://user-images.githubusercontent.com/3296055/37036286-789e5c1e-214f-11e8-8697-4804f9749c5c.png)
That's what i see: Only one subnav point

**Comment by DanielRuf** [comment]
This is a general issue with the markup / code as it seems.

**Comment by DanielRuf** [comment]
Please check https://codepen.io/DanielRuf/pen/GQbLEy?editors=1000

**Comment by vincentvermeer** [comment]
Is it right? Only "vertical" on submenu-ULs was missing? Now it works!
Thank you!
You can close the isse, it was no bug but a missing class... Sorry.

**Comment by DanielRuf** [comment]
Thanks for the feedback that it works now.
