### ISSUE TITLE
udocumented click.zf.drilldown

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#10920]
It seems there is `click.zf.drilldown` internally used but not documented.

Can this be listened on using jQuery or is it just internal?

**Comment by ncoden** [comment]
`click.zf.drilldown` is not triggered by Foundation. This is a jQuery `click` event on the drilldrown element that we listen using the `zf.drilldown` namespace to clear it when the drilldown is destroyed. So there is no reason to document it.

**Comment by DanielRuf** [comment]
Ah ok, so this is a completely internal event.

So far we have to add custom elements to catch click events and prevent bubbling. Because splitting the next button and link does not work as the href is removed.
