### ISSUE TITLE
[Tooltip] Allow to display tooltip by default

### ISSUE THREAD

**Issue by ncoden** [zurb/foundation-sites#10922]
Feature request: Allow to display a tooltip without any interactions required, with all interactions ignored.

This could be controlled with a new `data-show` option like in the following example:
```html
<span
    data-tooltip
    data-show="true"
    data-show-on="medium"
    data-disable-hover="true"
    title="Fancy word for a beetle." 
    ...>
    ...
</span>
```

The above tooltip would:
* be visible by default on medium+ breakpoints
* ignore hover events

**Comment by JeremyEnglert** [comment]
Closing this and we can revisit for V7. ;)

**Comment by ncoden** [comment]
@JeremyEnglert Don't forgot the tag :D
