### ISSUE TITLE
Mixin XY Grid - How to create simple semantic Grid with margin-x / gutter?

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#10931]
This is what I write regularly: 
```
        <div class="grid-container">
            <div class="grid-x grid-margin-x">
                <div class="cell">
                        <h3>Content</h3>
                </div>
            </div>
        </div>
```

How can I achieve this semantically? 
When I do this, `margin-x` seems to be missing: 

```
.news {
    @include xy-grid-container();
    &__wrapper {
        @include xy-grid();     
    }
    &__item {
        @include xy-cell();
    }
}  
```

**Comment by brettsmason** [comment]
@phifa You just need to add `@include xy-gutter($negative: true)` to the `.news__wrapper` and that should add the correct negative margins to the grid element. That was a bit of an oversight when creating the mixins for the grid.

**Comment by phifa** [comment]
@brettsmason nice! Thank you, and when I want to add margin-y? I tried doing this, but no success: 

```
        @include xy-gutters($negative: true);        
        @include xy-gutters($gutter-position: bottom);        

```

**Comment by brettsmason** [comment]
@phifa Do you mean as well as `margin-x` or instead of?
If you could explain the desired result I might be able to help a bit more.

**Comment by phifa** [comment]
Yeah I need additional margin-y in my current case, like so: 

```
        <div class="grid-container">
            <div class="grid-x grid-margin-x grid-margin-y">
                <div class="cell">
                        <h3>Content</h3>
                </div>
            </div>
        </div>
```

**Comment by brettsmason** [comment]
So you want a margin on top and bottom too?
In that case I'd probably write it something like this:

```
@include xy-gutters($gutter-position: 'left right', $negative: true);      
@include xy-gutters($gutter-position: 'top bottom');
```
That's assuming you want the margin on the `.news__wrapper` rather than the cell. If you wanted the top and bottom margin on each cell, then you can use the `$gutter-position` arguement on the [`xy-cell` mixin too].(https://github.com/zurb/foundation-sites/blob/develop/scss/xy-grid/_cell.scss#L109)

**Comment by phifa** [comment]
ah ok, i will try this. weird, i hard trouble understanding the docs here.

**Comment by phifa** [comment]
@brettsmason i found a bug: 
when using this 
`@include xy-gutters($gutter-position: 'top bottom');` the following happens: 
`margin-left right: -1rem;` That cannot work 😄 So the browser ignores it.  I use only `bottom` that works like a charm.

**Comment by brettsmason** [comment]
@phifa Sorry for the delay.
They do actually work correctly, but I wrote the above incorrectly (from my phone 😉).

If you pass it as a list rather than a string then it will work fine:
`@include xy-gutters($gutter-position: top bottom);`

**Comment by DanielRuf** [comment]
What is the current state? 

@phifa did the mixins work for you and solve your case?

**Comment by phifa** [comment]
yes. they work, can be closed.
