### ISSUE TITLE
the current state of unit tests

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#10945]
* standalone chai and mocha in test directory and other (unused) files
* browserstack tests running on IE11 producing wrong calculation of width and height values
* ~~a few failing unit tests in the browserstack tests~~
* ~~triggered events can produce race conditions under some circumstances as the DOM is not fast enough in the testing env~~
* in general: inconsistent event names (open/opened, close/closed)
* ~~currently the testsuite is only tested on Node.js 6. We should also test it on Node.js 4, 8 and 9.~~
* ...

Todo:
* [x] cleanup directories
* [x] update deps
* [x] create build matrix for Travis (just add more Node.js versions)

**Comment by ncoden** [comment]
Agreed with all that.

Related PR:
* https://github.com/zurb/foundation-sites/pull/10944  tests: migrate to mocha-headless-chrome (@DanielRuf)

Also related to this issue:
* https://github.com/zurb/foundation-sites/pull/10936
* https://github.com/zurb/foundation-sites/pull/10941

**Comment by DanielRuf** [comment]
So far so good. Now we just need new testrunner files, IE11 fixes and better event names https://github.com/zurb/foundation-sites/pull/10949

**Comment by DanielRuf** [comment]
> browserstack tests running on IE11 producing wrong calculation of width and height values

https://github.com/zurb/foundation-sites/pull/11078

**Comment by DanielRuf** [comment]
> update deps

https://github.com/DanielRuf/foundation-sites-greenkeeper/pull/1 (partly)

**Comment by ncoden** [comment]
🎉
