### ISSUE TITLE
Broken docs link

### ISSUE THREAD

**Issue by atilkan** [zurb/foundation-sites#10946]
Docs link is broken on the link below.
https://foundation.zurb.com/sites/getting-started.html

<img width="326" alt="screen shot 2018-02-15 at 15 09 40" src="https://user-images.githubusercontent.com/1254613/36256051-49852dd2-1262-11e8-8be6-b54f58b32c20.png">

**Comment by DanielRuf** [comment]
And there is also `See Upcomming Classes` hwich should be `See Upcoming Classes`.

Not sure where the templates for the website can be edited here. Did not find them in the zurb org on GitHub.

**Comment by JeremyEnglert** [comment]
I don't think the site lives inside this repo.

Tagging and assigning to @rafibomb.

**Comment by DanielRuf** [comment]
Seems to be fixed. Closing.
