### ISSUE TITLE
[Drilldown Menu] error on resize window

### ISSUE THREAD

**Issue by Chipsterjulien** [zurb/foundation-sites#10958]
Hello
First, sorry for my poor english.

I have a bug with a little code and i can't find any solution. So I dev with django under linux and i can reproduce it without django:

1. yarn init --yes
2. yarn add --dev foundation-cli
3. ./node_modules/.bin/foundation new

1. I put test_dropdown_and_drill_menu
2. my choice is first (little install with only sass preprocessor)

the foundation-sites is 6.4.3

inside the test_dropdown_and_drill_menu, i change index.html as below (i put my app.scss):

https://codepen.io/anon/pen/QQmdRL

After launch gulp to compile .scss to .css, i have this error when i resize shortly chromium/firefox:

> TypeError: Right-hand side of 'instanceof' is not an object
    at ResponsiveMenu._checkMediaQueries (foundation.responsiveMenu.js:289)
    at ResponsiveMenu._init (foundation.responsiveMenu.js:242)
    at ResponsiveMenu._setup (foundation.responsiveMenu.js:205)
    at ResponsiveMenu.Plugin (foundation.core.js:553)
    at new ResponsiveMenu (foundation.responsiveMenu.js:184)
    at HTMLUListElement.<anonymous> (foundation.core.js:356)
    at Function.each (jquery.js:354)
    at jQuery.fn.init.each (jquery.js:189)
    at String.<anonymous> (foundation.core.js:338)
    at Function.each (jquery.js:354)

Normaly, dropdown menu is disable and drill menu is activated as on doc

**Comment by DanielRuf** [comment]
I can not reproduce this with a codepen with Foundation Sites 6.4.3

https://codepen.io/DanielRuf/pen/gveWaP

**Comment by DanielRuf** [comment]
Can you provide a complete codepent with your markup and styles?

**Comment by Chipsterjulien** [comment]
there is no problem with codepen but with local installation, i have it

**Comment by DanielRuf** [comment]
If it is not reproducible in any of the codepen modes (full, debug and so on) it might be an issue with your integration or some thirdparty code.

You can download the codepen with all files at the bottom right and test if the code works on your machine too without codepen around it.

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/share/zip/gveWaP/
https://codepen.io/DanielRuf/full/gveWaP/
https://codepen.io/DanielRuf/debug/gveWaP

**Comment by Chipsterjulien** [comment]
the solution is here:
https://github.com/zurb/foundation-sites/issues/10520#issuecomment-364719137

**Comment by DanielRuf** [comment]
Thanks for the update and reporting this.
