### ISSUE TITLE
Collapsing Responsive-accordion Tabs? (Foundation 6)

### ISSUE THREAD

**Issue by jinch** [zurb/foundation-sites#10953]
So I'm having a really hard time figuring out why I can't collapse my accordion tabs using the Foundation 6.3 responsive tabs. The javascript provided in the foundation docs only seems to work with regular accordion setup and not the responsive-accordions tabs. 

Is this a bug with the responsive accordions? Does anyone know of a reason why this does not work or a possible solution to get responsive accordion-tabs to collapse initial load?

#### How to reproduce this bug:
1. Use the responsive accordion setup
> https://foundation.zurb.com/sites/docs/responsive-accordion-tabs.html
2. Use the javascript to close accordion: `$('#element').foundation('up', $target);`
> https://foundation.zurb.com/sites/docs/accordion.html#up

#### What should happen:
Responsive accordion-tabs should close.

#### What happened instead:
Nothing

#### Browser(s) and Device(s) tested on:
Testing on Chrome / Safari/ Firefox - Mac OS

#### Foundation Version(s) you are using:
Foundation v6.3.1

#### Test case link:
CODE PEN TO DEMONSTRATE:
https://codepen.io/jinch/pen/RQxQNG

**Comment by ncoden** [comment]
Hi @jinch,

There is no `up` method in ResponsiveAccordionTabs or anything like that. I agree with you that this is clearly a missing feature.

**Comment by DanielRuf** [comment]
Also it seems the markup for accordions is confused with the markup for tabs.

**Comment by DanielRuf** [comment]
You can use the breakpoint utilities to trigger the code when it is needed.

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/KQQKGV?editors=1010

The general problem is that the plugins are not fully initialized when you run your code.

**Comment by DanielRuf** [comment]
Hm, shouldn't the component fire an `init` event somewhere? I see no `@event` annotation or `trigger()` call. And I guess the generated docs should output an anchor which jumps to the right event.

**Comment by jinch** [comment]
So i found a VERY strange workaround just now and not sure why this works (but) if you place a duplicate DIV in the markup with the same id as your responsive accordion ~ than the up method actually works!?

NOT SURE WHY?
https://codepen.io/jinch/pen/dddywj?editors=1010

Is there a better way to do this without the extra markup?

**Comment by ncoden** [comment]
> Hm, shouldn't the component fire an init event somewhere.

It is done by `Foundation.Plugin`.

**Comment by DanielRuf** [comment]
> It is done by Foundation.Plugin.

Ah ok. I'm currently checking to add the needed methods in there.

**Comment by DanielRuf** [comment]
```
this.rules[matchedMq].plugin(this.$element, {});
      this.storezfData = this.currentPlugin.$element.data('zfPlugin');
      this.up = this.currentPlugin.up();
```

would work in the source. I'll prepare a PR and add all missing methods.

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/wyyBPW

Not sure how we can solve this in the best way.

Currently I have for testing
```diff
  }
+  up(target){
+	  if( typeof this.currentPlugin.up === 'function'){
+		this.currentPlugin.up(target);
+	} else {
+		return;
+	}
+  }
+
  _handleMarkup(toSet){
```

**Comment by DanielRuf** [comment]
This is just a rough idea. Any suggestions how we can tackle this or register the methods and unregister them is welcome. I'm open for discussions about the best solution.

**Comment by ncoden** [comment]
Sounds dirty but `_destroy` works that way:

https://github.com/zurb/foundation-sites/blob/0f6cfd2763e5cd2836483b83dcd8ab176f605a63/js/foundation.responsiveAccordionTabs.js#L232-L235

This is the way the component works 😷 .

**Comment by jcraitz** [comment]
What is the timeline like for merging #10961?  I'm currently using responsiveAccordionTabs to show tabs on medium+ and accordions on small screens. In my use case it would make sense to be able to initially open all the accordions on small screens.  Currently this isn't possible with no 'down' method available for ResponsiveAccordionTabs.

**Comment by DanielRuf** [comment]
@jcraitz download https://github.com/DanielRuf/patches/blob/master/foundation-sites/responsive-accordion-tabs-methods/foundation-sites%2B6.4.3.patch, create `patches` folder in the same level like package.json and install `patch-package`.

**Comment by DanielRuf** [comment]
See https://www.npmjs.com/package/patch-package

And don't forget
```
"scripts": {
  "prepare": "patch-package"
}
```

in package.json.

**Comment by DanielRuf** [comment]
If you need in more files, please let me know. I just patched a few single files for this. Not the full bundled foundation(.min).js files.

**Comment by jcraitz** [comment]
@DanielRuf Thank you for the offer!  However, my project is still in development and, unfortunately, the final version will not have direct control of the foundation includes that the main site is pulling in.  The workaround from @ncoden is enough for me, for now. I'll be able to reevaluate before product launch to see if either this PR has been merged at that time or if I need to petition the local team responsible for pulling in the foundation includes to include your patch. 

Thank you for your help!  I learned a good bit from reading through your patch and documentation! Cheers!

**Comment by DanielRuf** [comment]
The patch would be applied on each `npm install`.

**Comment by Backoo** [comment]
Any news on this and/or https://github.com/zurb/foundation-sites/pull/10961?

**Comment by DanielRuf** [comment]
Hi @Backoo. No news.
