### ISSUE TITLE
Is there an ETA for a 6.4.4 release?

### ISSUE THREAD

**Issue by nicolasv** [zurb/foundation-sites#10955]
Hi

I tried [asking in the Foundation Forum](https://foundation.zurb.com/forum/posts/55535-eta-for-foundation-sites-644-release) without any luck.

There's some fixes we'd like to incorporate into our website :)

**Comment by DanielRuf** [comment]
We have no exact ETA until now.

**Comment by DanielRuf** [comment]
Which specific fixes do you mean?

**Comment by DanielRuf** [comment]
You can see the current state and plan for 6.4.4 at https://github.com/zurb/foundation-sites/milestone/37

**Comment by nicolasv** [comment]
> Which specific fixes do you mean?

#10833 and #10837, please.

**Comment by ncoden** [comment]
@nicolasv We are still working on v6.4.4. It should be released in March.

**Comment by nicolasv** [comment]
Thanks, @ncoden!
