### ISSUE TITLE
[Sticky] don't work with drilldown/dropdown menu

### ISSUE THREAD

**Issue by Chipsterjulien** [zurb/foundation-sites#10974]
Hello

i try to have a sticky menu with drilldown menu on small screen. I put an example here:
https://codepen.io/anon/pen/QQmdRL
If you resize html view, drilldown will show and dropdown menu will be disable. Now go down with wheelmouse and you see drilldown menu is not sticky.

On local i have this error:

> Tried to initialize responsive-toggle on an element that already has a Foundation plugin.

Have you any idea to solve my prob ?

Best regards

**Comment by brettsmason** [comment]
@Chipsterjulien I created a new working CodePen for you here: https://codepen.io/brettsmason/pen/gvKdbv

Basically you had 2 issues. You cant initialize more than one Foundation plugin on the same element (as per the error you are seeing).
In your example you have `data-sticky` and `data-responsive-toggle` on the same div which is the first issue.

The 2nd issue is because sticky by default only sticks on medium and above.
To change that just add `data-sticky-on="small"` and element will always be sticky from small upwards.

Hope that helps! Going to close the issue, but if you still get stuck feel free to comment.

**Comment by Chipsterjulien** [comment]
Thx for you help
I apply somes changes and it's working on codepen ( and i see after, you give me the solution :D )
But on my computer, i load precompiled sass and js since i am not load all the foundation's lib. The menu don't stick on top and i seach what i missed

my style.scss:
```
@charset 'utf-8';

@import 'settings';
@import 'foundation';

@include foundation-global-styles;
@include foundation-typography;
@include foundation-button;
@include foundation-forms;
@include foundation-callout;
@include foundation-menu;
@include foundation-menu-icon;
@include foundation-drilldown-menu;
@include foundation-dropdown-menu;
@include foundation-sticky;
@include foundation-title-bar;
@include foundation-top-bar;
@include foundation-visibility-classes;

.container {
  @include grid-row;
}

.main, .sidebar {
  @include grid-column;
  margin-top: 16px;
}

.top-bar{
  .menu-text {
    color: white;
  }
}

@include breakpoint(medium){
  .main{
    @include grid-column-size(8);
  }
  .sidebar {
    @include grid-column-size(4);
  }
}
```

my end file.html:

```
<script src="vendor/jquery/dist/jquery.js"></script>
<script src="vendor/what-input/dist/what-input.js"></script>
<script src="vendor/foundation-sites/dist/js/plugins/foundation.core.js"></script>
<script src="vendor/foundation-sites/dist/js/plugins/foundation.util.keyboard.js"></script>
<script src="vendor/foundation-sites/dist/js/plugins/foundation.util.box.js"></script>
<script src="vendor/foundation-sites/dist/js/plugins/foundation.util.nest.js"></script>
<script src="vendor/foundation-sites/dist/js/plugins/foundation.util.triggers.js"></script>
<script src="vendor/foundation-sites/dist/js/plugins/foundation.util.mediaQuery.js"></script>

<script src="vendor/foundation-sites/dist/js/plugins/foundation.sticky.js"></script>
<script src="vendor/foundation-sites/dist/js/plugins/foundation.drilldown.js"></script>
<script src="vendor/foundation-sites/dist/js/plugins/foundation.dropdownMenu.js"></script>
<script src="vendor/foundation-sites/dist/js/plugins/foundation.responsiveToggle.js"></script>
<script src="vendor/foundation-sites/dist/js/plugins/foundation.responsiveMenu.js"></script>
<script src="js/app.js"></script>
```

my app.js:

```
$(function() {
  $(document).foundation();
});
```

If you see any mistakes, i will take it

Best regards

**Comment by Chipsterjulien** [comment]
@brettsmason 
I post this issue here. No help on forum and slack :/
