### ISSUE TITLE
accourdion-menu and is_active class

### ISSUE THREAD

**Issue by ivanff** [zurb/foundation-sites#10973]
```
accourdion-menu - options data-multi-open=false

`Tag <li class="is_active">  in .sub-menu <ul> list set display: none like <ul tree>`

```

**Comment by DanielRuf** [comment]
Please describe your issue more detailed.

**Comment by DanielRuf** [comment]
Hi @ivanff, please provide some more info so we can address this issue.
Without any further changes we may close this as it is currently not clear what the issue is.

**Comment by DanielRuf** [comment]
@ncoden what should we do here? The issue is not clear to me.

**Comment by splitmango-duy** [comment]
Hi @DanielRuf ,

I think i got the same problem with @ivanff here, I can further explain the issue.

When you have data-multi-open set to false, there's some javascript that add display: none to the current menu item.

Hope that helps.

Thanks,

**Comment by DanielRuf** [comment]
Please provide a working codepen @splitmango-duy

**Comment by splitmango-duy** [comment]
This happens on a wordpress site, using foundation 6.4.3, not sure how I can reproduce the issue with codepen. Because it wont have the class names, such as current-menu-item & current-menu-ancestor attached with wordpress.

**Comment by DanielRuf** [comment]
Can you provide an URL or copy the relevant html code from theb"view source" contextmenu?

**Comment by ncoden** [comment]
No reply. Closing.
