### ISSUE TITLE
Remove Dependency of JQuery

### ISSUE THREAD

**Issue by hismichael** [zurb/foundation-sites#10975]
Is it time to remove dependency of JQuery?

**Comment by DaSchTour** [comment]
I may be time, but reworking all JS now doesn't make any sense

**Comment by ncoden** [comment]
@hismichael We are currently working on Foundation 7, with a new architecture that would allow you to work rely or not on jQuery (or any other framework).

**Comment by arxpoetica** [comment]
@ncoden when will that be released? There are some fabulous patterns in Foundation. As a long time advocate of NOT using frameworks, Foundation may be the ONLY one I ever recommend to people, with this MAJOR drawback—it relies on an antiquated, monstrous library which I never want to include in any repository.

So removing jQuery would be a major win. When will Foundation 7 be released?

**Comment by DanielRuf** [comment]
@arxpoetica  the work on v7 has not yet started but we will start with it very soon.

**Comment by panique** [comment]
It's 2 years later now, can you please drop some info about the current status of Foundation 7 ? I'm writing here into this closed ticket as it's the #1 Google hit for "Foundation 7" for me, and I cannot see a v7 branch or so.

Do you need any volunteers, I'm all-in ? :)
Thanks for an great framework, love it!

**Comment by DanielRuf** [comment]
Hi @panique 

> It's 2 years later now, can you please drop some info about the current status of Foundation 7 ?

No news so far.

> Do you need any volunteers, I'm all-in ? :)

Any help is very welcome.
