### ISSUE TITLE
[The Grid] documentation has broken link

### ISSUE THREAD

**Issue by nigelm** [zurb/foundation-sites#10985]
#### How to reproduce this bug:

The initial alert callout under https://foundation.zurb.com/sites/docs/grid.html#importing has a link (from `XY Grid`) to https://foundation.zurb.com/xy-grid.html

This link `https://foundation.zurb.com/xy-grid.html` gives a 404

#### What should happen:

I see sweet documentation

#### What happened instead:

I see a slightly less contextually sweet 404

**Comment by ncoden** [comment]
But 404 is still sweet. Won't fix.

**Comment by ncoden** [comment]
I'm joking. Thanks for the issue @nigelm

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/10986

**Comment by DanielRuf** [comment]
Closed by https://github.com/zurb/foundation-sites/pull/10986
