### ISSUE TITLE
Expose vendor JS from webpack

### ISSUE THREAD

**Issue by CGTS** [zurb/foundation-sites#10983]
I'm trying to use a third party JS file to add [Feather Icons](https://feathericons.com) [ [Git Repository](https://github.com/feathericons/feather) ] to my site. If I just add the JS separately I'm able to  use the icons. However, when I add them to the webpack bundle

```
import { feather } from 'feather-icons';
```

and try to call the function with `feather.replace()';`

I get the following error

```
Uncaught ReferenceError: feather is not defined
```

I see the JS added to bundle, but I can't seem to access it. Any ideas on how to do this?

**Comment by ncoden** [comment]
Hi @CGTS 

See the [Feather main file](https://github.com/feathericons/feather/blob/master/src/index.js). There is no `feather` exported.

Please use:
```js
import { icons } from 'feather-icons';
```

Also to see what their in in a package, you can use:
```js
import * as package from 'feather-icons';

console.log(package);
```

**Comment by CGTS** [comment]
That was it. Thank you.

**Comment by absilva** [comment]
Thank you for this! After two year still useful!
