### ISSUE TITLE
[Customizer] Out-of-date Foundation versions

### ISSUE THREAD

**Issue by sofiageo** [zurb/foundation-sites#10991]
#### How to reproduce this bug:

1. Go to https://foundation.zurb.com/sites/download.html/
2. Click any download button
3. Verify the version downloaded is 6.4.3 but the filename is 6.4.2 - This can lead to confusions.

#### What should happen:
Filename downloaded should have 6.4.3 version

#### What happened instead:
Filename has 6.4.2 version

#### Browser(s) and Device(s) tested on:
Firefox, Linux

**Comment by DanielRuf** [comment]
Thanks for catching this.

`data-src-download`is also confusing in the source.

**Comment by DanielRuf** [comment]
As this is in the marketing site which is not in one of the repos who can we assign here @ncoden @JeremyEnglert ?

**Comment by sofiageo** [comment]
Actually it's not just the filename, it's just an older version on the website, I was looking at the wrong file. Sorry :)

**Comment by ncoden** [comment]
@sofiageo I'm renaming the issue.

**Comment by DanielRuf** [comment]
@ncoden I guess I also have to change some JS entries there (because of internal name changes) or am I wrong?

**Comment by ncoden** [comment]
@DanielRuf I don't understand. Are you writting on the right issue ?

**Comment by DanielRuf** [comment]
Yes. I changed the internal names of some components (or was it just jsdoc related?).

**Comment by ncoden** [comment]
@DanielRuf I don't get it

**Comment by DanielRuf** [comment]
I camelcased some component names in the JS files (class names?).

Anyway, will also check the customizer.

**Comment by ncoden** [comment]
You camelcased events names and the corresponding documentation. I do not see how this could have any effect on the customizer or download links (no Sass or file names changed).

**Comment by DanielRuf** [comment]
And some class names or something else at the very top of the files. ;-)

**Comment by ncoden** [comment]
Yes. For the docs only ;-)

**Comment by DanielRuf** [comment]
Ah ok =)

**Comment by despecial** [comment]
any idea when this will be fixed?

**Comment by bellwood** [comment]
Over a month to sort a download link?

Could the proper link for 6.4.3 be posted here at least please?

Thank you =)

**Comment by DanielRuf** [comment]
It is on the serverside @ncoden

**Comment by ncoden** [comment]
The customizer is not updated to Foundation v6.5.1.
https://foundation.zurb.com/sites/download.html/
