### ISSUE TITLE
CSS unnecessary sourcemap declaration

### ISSUE THREAD

**Issue by sofiageo** [zurb/foundation-sites#10997]
#### How to reproduce this bug:

1. Download latest release from https://github.com/zurb/foundation-sites/archive/v6.4.3.zip
2. Go to dist/css directory
3. Verify that foundation.css last line has a sourcemap declaration, but sourcemap file doesn't exist.

#### What should happen:
It depends. From my point of view the Github release is used by other packages, like webjars, so it would be better if the result CSS has no sourcemap ? I'm not a CSS expert, so I might be wrong.

#### What happened instead:
CSS file has a sourcemap declaration, which results in a 404 error in browser.

#### Browser(s) and Device(s) tested on:
Firefox, Linux

#### Foundation Version(s) you are using:
6.4.3

**Comment by DanielRuf** [comment]
Thanks for reporting. Will check this.

**Comment by DanielRuf** [comment]
Unminified files are for development normally and have sourcemap files in webdevelopment. Only minified are for production. You can import the unminified css file and ignore the sourcemap comment using other modules.
