### ISSUE TITLE
top-bar-right without top-bar-left does not align right in rtl flex

### ISSUE THREAD

**Issue by shadysamir** [zurb/foundation-sites#10992]
#### How to reproduce this bug:

1. Set $global-text-direction: rtl
2. Use flex grid
2. Create a topbar and place only a top-bar-right section inside it

#### What should happen:
The top-bar-right section should align to the right even if it's the only section in the topbar

#### What happened instead:
The top-bar-right section is aligned to the left, but when I add a top-bar-left section the top-bar-right aligns to the right properly.

#### Foundation Version(s) you are using:
6.4.4-rc1

**Comment by DanielRuf** [comment]
Can you provide a codepen to demonstrate this?

**Comment by DanielRuf** [comment]
Not reproducible: https://codepen.io/DanielRuf/pen/GxgLgV

**Comment by DanielRuf** [comment]
@shadysamir please provide some more info as we can not reproduce it with a correct codepen.

**Comment by shadysamir** [comment]
I've had problems trying to replicate on codepen as it inherits only rtl framework. I will try to host my own example.

**Comment by DanielRuf** [comment]
Codepen as an `export` button at the bottom right.

https://github.com/zurb/foundation-sites/issues/10992#issuecomment-372056285
https://codepen.io/DanielRuf/share/zip/XEJQYP/

**Comment by DanielRuf** [comment]
Closing as we did not receive any further information.
