### ISSUE TITLE
[Magellan] data-offset KO // data-bar-offset OK

### ISSUE THREAD

**Issue by jbonlinea** [zurb/foundation-sites#10994]
Hi, 

This might not be the best example as I use foundation with grav and some inherited templated, however that's how I bump into it, and foud a [solution on the forum](https://foundation.zurb.com/forum/posts/38908-foundation-6-magellan-top-offset-not-working).

Basically foundation documentation is not right 

#### How to reproduce this bug:

1. add data-offset="xx" to a navigation bar combining data-magelan and sticky 

#### What should happen:
According to the doc, there should be an offset of xx pixels

#### What happened instead:

as if the option wasn't set 

#### Browser(s) and Device(s) tested on:

firefox dev edition up to date, macbook pro 15"

#### Foundation Version(s) you are using:

6.2.4

#### solution 

use data-bar-offset instead of data-offset ; it work's

**Comment by DanielRuf** [comment]
The docs are for the latest 6.x release which is 6.4.3

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/v6.2.4/js/foundation.magellan.js
https://github.com/zurb/foundation-sites/blob/v6.4.3/js/foundation.magellan.js

**Comment by ncoden** [comment]
Related to https://github.com/zurb/foundation-sites/issues/9512

**Comment by jbonlinea** [comment]
Hi, 
yes I had seen that the documentation was for 6.4.3, but how are we supposed to know that a given parameter name has changed !

I had seen that data-magelan was updated between 6.2.4 to  6.4.3, but we can't expect users to assume changes and check the code for every changes from version to version, especially since certain changes are mentionned in the documentation and some others aren't, for instance tooltip doc precises that absolute positioning is only usable with 6.4.3.

I totally advocate for multiple version documentation.

Good to see it's on it's way

Thank's for your answers !

**Comment by DanielRuf** [comment]
> I had seen that data-magelan was updated between 6.2.4 to 6.4.3, but we can't expect users to assume changes and check the code for every changes from version to version, especially since certain changes are mentionned in the documentation and some others aren't, for instance tooltip doc precises that absolute positioning is only usable with 6.4.3.

In short, we have changelogs ;-)
