### ISSUE TITLE
SRI is wrong

### ISSUE THREAD

**Issue by fulldecent** [zurb/foundation-sites#11004]
See here 

<img width="1922" alt="screen shot 2018-03-02 at 3 34 43 pm" src="https://user-images.githubusercontent.com/382183/36920618-3ebb6aa0-1e2f-11e8-812e-28d59cdfb494.png">

That SRI is stale. Anybody copying that code will NOT be able to access the CSS file. Chrome will block it.

The process that caused the incorrect SRI to get onto this website is because that SRI was added for a past version of Foundation Sites. Then the version number was updated without the SRI being recalculated.

The SRI value is not set-it-and-forget-it. You must recalculate it with each release. That's the whole point!

**Comment by DanielRuf** [comment]
Thanks for reportig the invalid SRI hash.

**Comment by DanielRuf** [comment]
Closing as this should be solved by https://github.com/zurb/foundation-sites/pull/11005
