### ISSUE TITLE
Documentation: less video, more meat and potatoes

### ISSUE THREAD

**Issue by fulldecent** [zurb/foundation-sites#11007]
Here is the documentation for cards...

<img width="2160" alt="screen shot 2018-03-02 at 5 10 47 pm" src="https://user-images.githubusercontent.com/382183/36924507-cd7404d4-1e3c-11e8-89b7-4c07f1dfca2a.png">

I'm sure the guy in the video is a nice guy. And I'm sure if it was reasonable for me to play sound in my office and I clicked on the video and I waited through some intro and some nerd stuff it might answer the question.

But instead of all that, why not just show me, right up top, what is a card?

**Comment by DanielRuf** [comment]
This is the default template for documentation pages afaik where the video in the frontmatter is shown at the top as intro.

**Comment by DanielRuf** [comment]
The actual demos with codepens are underneath the video.

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-docs/blob/master/templates/component.html#L5-L7

**Comment by ncoden** [comment]
I think the point of @fulldecent is more _why did we choose to display a big video on top_ instead of _how it is implemented_.

I agree with @fulldecent that the video is not the first resources people will go for in the Foundation documentation and that it's more like a _nice side bonus_ for beginners.

The documentation site UI/UX can be improved a lot in tons of aspects and we will try to consider this for the next design (probably coming alongside Foundation 7).

**Comment by DanielRuf** [comment]
> I agree with @fulldecent that the video is not the first resources people will go for in the Foundation documentation and that it's more like a nice side bonus for beginners.
> 
> The documentation site UI/UX can be improved a lot in tons of aspects and we will try to consider this for the next design (probably coming alongside Foundation 7).

Maybe add a switch `| beginner | pro mode` on the top right and store the setting in a JS cookie and hide the videos then? Just an idea.

**Comment by ncoden** [comment]
> Maybe add a switch [ beginner | pro ] mode on the top right and store the setting in a JS cookie and hide the videos then? Just an idea.

If only webdesign were that simple 😄. More seriously, no one want to having to customize the website he/she just landed on. If the video is not the more import on the website, move it away, on the sidebar for example. Both pros beginners want to see the code/example first.

**Comment by DanielRuf** [comment]
Or yeah, `videos [ on | off ]`.

**Comment by colin-marshall** [comment]
Maybe instead we could have a smaller thumbnail with some text to the side of it that says something like "New to Foundation? Watch this video lesson to get familiar with Foundation's Card component." Then have the thumbnail open up a Reveal with the video embedded.

That way there is more context to the video's purpose and it takes up less real estate.

**Comment by JeremyEnglert** [comment]
Tagging @IamManchanda as he is the docs lead. 

Lets revisit this for V7.
