### ISSUE TITLE
Should the search cancel buttons in Chrome and Safari on macOS really be removed by default? If so, why?

### ISSUE THREAD

**Issue by gburning** [zurb/foundation-sites#11015]
I was troubleshooting why the WebKit cancel buttons for search inputs don't show up and found that they've been explicitly removed in the CSS.

https://github.com/zurb/foundation-sites/blob/26475ef192727333d8ad8c0e5cbff4be06ea15e4/dist/css/foundation.css#L332-L335

Should this really be the case?

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-sites/blob/1a7af341bccd571b65aa2a96b10bd0884576fb5a/_vendor/normalize-scss/sass/normalize/_normalize-mixin.scss#L529-L535

**Comment by DanielRuf** [comment]
https://github.com/necolas/normalize.css/blob/7369f566898b8cefc2649b6a66e112857de4c46f/CHANGELOG.md

```
8.0.0 (February 2, 2018)
Remove support for older browsers Android 4, lte IE 9, lte Safari 7.
Don't remove search input cancel button in Chrome/Safari.
Form inputs inherit font-family.
Fix text decoration in Safari 8+.
```

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/develop/package.json#L86

**Comment by DanielRuf** [comment]
https://github.com/necolas/normalize.css/issues/685

**Comment by DanielRuf** [comment]
@ncoden should we file an issue at normalize-scss or overwrite this in our global styles?

**Comment by ncoden** [comment]
Why not both ?

Also I'll take care of a cleaner version of https://github.com/zurb/foundation-sites/pull/11016 tomorrow.
