### ISSUE TITLE
proposal: switch / link to unpkg / jsDelivr

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#11019]
I think it is a good idea to switch to unpkg which uses the npm ecosystem and has a few advantages over cdnjs (where I also saw downtimes and other issues in the past).

https://metafizzy.co/blog/switching-out-cdnjs-for-unpkg/

And we should probably include the jsDelivr badge

[![jsDelivr](https://data.jsdelivr.com/v1/package/npm/foundation-sites/badge)](https://www.jsdelivr.com/package/npm/foundation-sites)

```markdown
[![jsDelivr](https://data.jsdelivr.com/v1/package/npm/foundation-sites/badge)](https://www.jsdelivr.com/package/npm/foundation-sites)
```

**Comment by MartinKolarik** [comment]
jsDelivr and unpkg are two different CDNs (which work similarly but jsDelivr is more focused on production usage and has larger network) so if you want to show the badge, you should also use jsDelivr links, otherwise there's no point in having the badge (since unpkg hits won't be included there).

**Comment by DanielRuf** [comment]
Sure, I am aware of the difference.
But it seems there are no jsDelivr badges, even on shields.io.

**Comment by MartinKolarik** [comment]
Sorry but in that case I don't understand why you want to add a badge for one CDN and use the other.

**Comment by DanielRuf** [comment]
It is better to have two than one which was sometimes unreliable in the past (cdnjs).
unpkg and delivrjs use the npm ecosystem and people can use both.
So we (can) use both.

jsDelivr provides statistics about the usage which unpkg does not.
The jsDelivr part was just another suggestion and not the main part of this issue.
We could also show the npm stats using npms / npm.

**Comment by DanielRuf** [comment]
Your opinions @colin-marshall @ncoden @JeremyEnglert

**Comment by DanielRuf** [comment]
Bump.

**Comment by ncoden** [comment]
There is only the README and installation documentation to update, right ?
Also because it seems to be used in two different way (unpkg is more convenient for dev, and I guess that jsDelivr is better for an usage in production), why not both ?

**Comment by DanielRuf** [comment]
Hm, not sure if we even need the badges.
But the documentation for the usage could be updated then?

**Comment by DanielRuf** [comment]
https://unpkg.com/foundation-sites/dist/ (latest)
https://www.jsdelivr.com/package/npm/foundation-sites?path=dist (latest)

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/commit/b3252acddd95eec496be8affc996c480d53ebb2a#diff-04c6e90faac2675aa89e2176d2eec7d8 so the badge is already in the readme in the master branch.
