### ISSUE TITLE
Update examples to use XY Grid

### ISSUE THREAD

**Issue by dogpatchmedia** [zurb/foundation-sites#11028]
In the documentation for Foundation 6.4.1 it starts by saying how XY Grid is the new grid and that Float Grid and and Flex Grid are now legacy features and how XY Grid is enabled by default. Thats great, however, every example in the documentation for every feature still uses the old legacy Float Grid as the grid for the examples. Please update the documentation because this makes the examples unusable in a XY Grid project.

**Comment by DanielRuf** [comment]
Can you show specific examples which use the old grid instead of the new xy grid?

**Comment by colin-marshall** [comment]
[Equalizer](https://foundation.zurb.com/sites/docs/equalizer.html#basics) is the only one I could find.

@dogpatchmedia also may be referring to the grid used to build examples (e.g. [thumbnail example](https://foundation.zurb.com/sites/docs/thumbnail.html) with 3 columns) and not the actual code you can copy/paste of the examples. If that's what is being referred to, yes they probably should all be XY-Grid eventually, but it's low priority at the moment.

**Comment by dogpatchmedia** [comment]
Hey @colin-marshall and @DanielRuf, I think colin is right that Equalizer is the one that got my attention. I appreciate you being so attentive and yeah its low priority for sure I understand, it just irritated me since this is the first project I've worked on using the XY Grid and Im not used to it quite yet.

**Comment by rafibomb** [comment]
Technically, equalizer was a viable solution before flexbox created equal height children. Since using flexbox, we have not needed it on any of our projects.

Perhaps we just label this example as such and close the issue?

**Comment by ncoden** [comment]
Thanks for the bump @rafibomb
