### ISSUE TITLE
Initialising Foundation.Tooltip with JavaScript fails 

### ISSUE THREAD

**Issue by tyteen4a03** [zurb/foundation-sites#11027]
Constructing a new `Foundation.Tooltip` is impossible if you have more than one tooltip.

See Pen: https://codepen.io/anon/pen/bvGRgN

Variations I have tried:
`new Foundation.Tooltip($(".has-tip"));` - only one tooltip will be generated, all tooltips will link to the first one the script sees
`$(".has-tip").each((e) => new Foundation.Tooltip(e))` - Uncaught TypeError: this.$element.data is not a function
`$(".has-tip").each((e) => new Foundation.Tooltip($(e)))` - Uncaught TypeError: Cannot read property 'className' of undefined

**Comment by DanielRuf** [comment]
jQuery.each has the signature `each(index, element)` and you initialize them twice: https://codepen.io/DanielRuf/pen/RMwgMm

**Comment by DanielRuf** [comment]
See http://api.jquery.com/each/

**Comment by DanielRuf** [comment]
And the titles were the same.

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/WzNOqp

**Comment by tyteen4a03** [comment]
I just copied off something from the net, didn't realise how old it was - oops.

Your solution worked perfectly, thanks!
