### ISSUE TITLE
chore: check websites and docs for broken links

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#11043]
I'll check the docs and marketing sites for broken links with Screaming Frog (will buy a license for this).

Or does anyone have a better solution than the Screaming Frog software?

**Comment by colin-marshall** [comment]
@DanielRuf maybe you can work with @JeremyEnglert, as I believe he is in helping migrate the Foundation marketing site.

**Comment by DanielRuf** [comment]
That would be great.

@JeremyEnglert let me know how I can help and if it makes sense to scan the current website(s) for broken links of if I should wait a bit.

**Comment by Seanom** [comment]
The following pages have broken doc links, might requires it's own ticket but this seems like a good place to start.

The Docs links on the following pages goes to https://foundation.zurb.com/docs/ and not to https://foundation.zurb.com/sites/docs/

 - https://foundation.zurb.com/sites/getting-started.html
 - https://foundation.zurb.com/sites/download.html/
 - https://foundation.zurb.com/templates.html
 - https://foundation.zurb.com/sites/resources.html

![image](https://user-images.githubusercontent.com/331839/38025908-009911de-3282-11e8-9dde-04b02cca83fd.png)

**Comment by jamesstoneco** [comment]
@rafibomb I was taking a look at this for #docsthursday and I think it is closed source on ZURB. If you provide access I am happy to fix it. I can also look into some sort of automated tooling to avoid broken links in the future.

**Comment by rafibomb** [comment]
@jamesstoneco That would be super helpful! I'm adding you to it.

**Comment by DanielRuf** [comment]
> **though we can certainly open-source if the team feels this would be the way forward**.

Definitely if we want to make more steps.
