### ISSUE TITLE
build: use Husky for Git hooks

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#11042]
It makes sense to run some checks when working with the develop branch.
We should use [husky](https://github.com/typicode/husky) for this.

* [ ] eslint
* [ ] sasslint / stylelint
* [x] unit tests
* [ ] ...

Can we adapt airbnb coding guidelines for Foundation Sites? https://github.com/zurb/foundation-sites/pull/9333#issuecomment-259777119

**Comment by colin-marshall** [comment]
Seems like a good addition as long as our tests are all up-to-date.

**Comment by DanielRuf** [comment]
Will schedule this for this week.
