### ISSUE TITLE
proposal: use Greenkeeper to keep all dependencies updated

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#11046]
It may make sense to use the service of Greenkeeper to ensure that all dependencies are not outdated.

**Comment by DanielRuf** [comment]
See https://github.com/DanielRuf/foundation-sites-greenkeeper/pull/1

**Comment by DanielRuf** [comment]
cc @ncoden @JeremyEnglert what do you think? Please checkout the branch of my fork and test if it is ok so far.

**Comment by rafibomb** [comment]
We're now setup with dependabot - does this resolve the use case for this issue? Can we close here?

**Comment by DanielRuf** [comment]
Never used dependabot so far. Does it also update the lockfile(s)? If it does so we can close this issue.

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11157/files for example. It updates the two lockfiles.

**Comment by DanielRuf** [comment]
Perfect 👍
