### ISSUE TITLE
input-number-group looks  off

### ISSUE THREAD

**Issue by GildedHonour** [zurb/foundation-sites#11055]
I copied/pasted an example from https://foundation.zurb.com/building-blocks/blocks/input-number-group.html and its layout is a bit off:

![_2018-03-15_10-53-33](https://user-images.githubusercontent.com/2032888/37442119-9225c298-283f-11e8-867e-fab76ab23b34.png)
![_2018-03-15_10-52-37](https://user-images.githubusercontent.com/2032888/37442121-925bcec4-283f-11e8-8bec-43e04e0aa805.png)

I've tried many things to fix it to no avail

**Comment by GildedHonour** [comment]
![_2018-03-15_11-01-26](https://user-images.githubusercontent.com/2032888/37442288-6a07ef38-2840-11e8-9cd3-a6cf63627ab5.png)

**Comment by GildedHonour** [comment]
![_2018-03-15_11-01-26](https://user-images.githubusercontent.com/2032888/37442312-87a58780-2840-11e8-8cab-b7321ccb64bc.png)

**Comment by DanielRuf** [comment]
What exactly do you mean with "a bit off"?

**Comment by DanielRuf** [comment]
Ah you mean the missing `minus` on the left?

**Comment by GildedHonour** [comment]
нуы

**Comment by GildedHonour** [comment]
yes

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/NYNoNG
<img width="1105" alt="bildschirmfoto 2018-03-15 um 10 07 24" src="https://user-images.githubusercontent.com/827205/37453658-b1c3cc8c-2838-11e8-82ca-efc4f2d7ccaa.png">

**Comment by DanielRuf** [comment]
I think this is an issue withb the markup and code of the building block, see https://codepen.io/DanielRuf/pen/NYNoNG

**Comment by GildedHonour** [comment]
thx
