### ISSUE TITLE
removing gutters on cells (semantically) 

### ISSUE THREAD

**Issue by nitrokevin** [zurb/foundation-sites#11059]
Hi I'm not sure if this is an issue or expected behaviour, but when I set the gutters to false on a cell the margin values are removed but the width rem-cal that takes into account the gutters remains
#### How to reproduce this bug:

1. Set the cell to have no gutters using false @include xy-cell(3,false); 
2. Check in browser, margin still appears due to width calculation
3. Change code to keep gutters but with 0 size  @include xy-cell(3,true,0);
4. Margins have now been removed completely

#### What should happen:
I would expect setting gutters to false would completely remove the gutters
#### Browser(s) and Device(s) tested on:
All
#### Foundation Version(s) you are using:
6.4.3

**Comment by AtlantaJones** [comment]
@nitrokevin  I'm seeing the same thing. Did you find a solution?

**Comment by DanielRuf** [comment]
Please test the linked PR.

**Comment by AtlantaJones** [comment]
I'll try to test as well tonight. Is there an easy way to test something like that when you already have the latest pulled in via NPM?

**Comment by DanielRuf** [comment]
@AtlantaJones you can manually clone my fork into the directory and checkout the branch.

**Comment by DanielRuf** [comment]
Hi @AtlantaJones, do you need any help or are there some questions left about how you can test it on your side?
