### ISSUE TITLE
[Sticky] [Reveal]

### ISSUE THREAD

**Issue by MarcinSano** [zurb/foundation-sites#11069]
Hi! Have you ever place sticky inner reveal? For me sticky is does not hook.

See for yourself: https://codepen.io/sonasmar/pen/vRXbGj 

Any idea that could help me get to work it? 

Thanks!

**Comment by DanielRuf** [comment]
It seems `data-anchor` is not in the sticky component anymore.

**Comment by DanielRuf** [comment]
We will revisit this when we start working on v7.
