### ISSUE TITLE
[Tooltip] deprecated positionClass

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#11066]
Can we remove the deprecated `positionClass` option?

Tooltip: positionClass

**Comment by ncoden** [comment]
It was never supported since `v6.4.3` and is already removed from the docs. https://github.com/zurb/foundation-sites/pull/11038 remember ? 😄

**Comment by DanielRuf** [comment]
> [Tooltip]

**Comment by DanielRuf** [comment]
This is not the dropdown component ;-)

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-sites/blob/master/js/foundation.tooltip.js#L382-L387

**Comment by ncoden** [comment]
Ah f***
