### ISSUE TITLE
[Revea] double scrollbar

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#11064]
Using reveal adds a double scrollbar as `overflow: scroll` is used. We should use `overflow: auto` instead.

https://codepen.io/DanielRuf/pen/RMRVjO

https://codepen.io/DanielRuf/debug/RMRVjO

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/0caa4752effbccdda8666b077db242d1622524be/scss/components/_reveal.scss#L129
https://github.com/zurb/foundation-sites/blob/0caa4752effbccdda8666b077db242d1622524be/scss/components/_reveal.scss#L65

https://codepen.io/DanielRuf/pen/RMRgNN

**Comment by ncoden** [comment]
@DanielRuf  Duplicate of https://github.com/zurb/foundation-sites/issues/10824 ?

**Comment by DanielRuf** [comment]
> @DanielRuf Duplicate of #10824 ?

Right. Was searching for a PR but did not find one.
