### ISSUE TITLE
Feature request: Foundation 6.4 XY Grid in an Angular 4 app

### ISSUE THREAD

**Issue by fperezgaliana** [zurb/foundation-sites#11063]
I'm using Foundation for sites in an Angular 4 application and it was working perfectly until I added the router for navigating in the app. It seems that the DOM elements inserted by Angular broke the hierarchy of the CSS classes and the layout isn't working anymore. Here you can see the differences in the DOM before and after adding the router:

![imagen](https://user-images.githubusercontent.com/28951240/37478475-9f23138e-287a-11e8-8264-19498636730c.png)

I've tried to create new classes to mimic the relationship between them, like this:

```
/* FOR cell shrink header*/
.grid-y > .ng-star-inserted > .auto, .grid-y > .ng-star-inserted > .shrink {
  height: auto;
}

.grid-y > .ng-star-inserted > .cell {
  width: auto;
}

/* FOR cell medium-auto medium-cell-block-container */
.grid-y > .ng-star-inserted > .ng-star-inserted > .cell {
  width: auto;
}

.grid-y > .ng-star-inserted > .ng-star-inserted > .medium-auto {
  -webkit-box-flex: 1;
  -ms-flex: 1 1 0px;
  flex: 1 1 0px;
  height: auto;
}

/* FOR cell medium-3 footer */
.grid-y > .ng-star-inserted > .ng-star-inserted > .medium-3 {
  height: 25%;
}
```

But it didn't make any change in the layout.  Would it be possible to change the CSS selectors not to depend on direct children relationships to make the layout work even when used in such scenario, with added divs inbetween?

**Comment by DanielRuf** [comment]
We do not add new features to Foundation Sites 6.

**Comment by DanielRuf** [comment]
I guess it is only a misconfiguration with the router.

Are these an option?

https://github.com/yalabot/angular-foundation

https://github.com/circlingthesun/angular-foundation-6

**Comment by fperezgaliana** [comment]
Hi,

Thanks for the suggestions, but I'm developing in Angular 4 and they are for AngularJS. More than a feature request, it's an special case that is not supported by the framework. To see it better, I've prepared 2 samples, so you can see the problem:

Full page layout using XY Grid BEFORE adding Angular 4 router:
https://codepen.io/felipRR/pen/LdZgQJ

Full page layout using XY Grid AFTER adding Angular 4 router:
https://codepen.io/felipRR/pen/GxqYXV

The problem seems to be that adding an extra DIV that encapsulates some others breaks the parent-child relationships and the CSS rules are not applied. 
One possible solution would be adding an special class to the added DIV to make it didn't affect to the layout... Any ideas, please? Thanks a lot!

**Comment by DanielRuf** [comment]
In my opinion it seems to be a problem caused by the router and I would ask the developers if this behavior (the injection of the div and how this can be prevented or solved).

You can try the Sass version of Foundation Sites and using an adjusted xy-grid scss file instead of the default one.

**Comment by fperezgaliana** [comment]
Hi, the problem is that the router needs to inject the new elements because it's the way it works, and can't be changed. It allows to add classes to the injected DIV, and I've tried adding some of the XY Grid classes to see how it affected to the layout, but I couldn't fix it... I'll install the Sass version and I'll do some tests to see if I can find a solution.

**Comment by ncoden** [comment]
Hi @fperezgaliana. I confirm this is a problem with the router. Even if CSS libraries should provides components that can be customized and moved around in the DOM, we are restrained by the way CSS works and sometimes some elements _have to_ be the direct childrens of others without others solutions.

So it is definitely a problem with the router that change the DOM between others components without caring about their relations.

**Comment by fperezgaliana** [comment]
Thank you very much, this also confirms that, unfortunately, I have to discard Foundation for this project and look for another solution (perhaps pure Grid CSS will work in this case, I don't know... I'll do some tests). Cheers,
