### ISSUE TITLE
[Reveal] No option to allow page scroll with reveal open

### ISSUE THREAD

**Issue by diniscorreia** [zurb/foundation-sites#11061]
More of a suggestion than a bug, but: shouldn't Reveal have an option to allow full page scroll (i.e., not add the `is-reveal-open` to the `body`)? 

I was under the impression that removing the overlay would allow page scroll, but that doesn't seem to be the case.

**Comment by DanielRuf** [comment]
The open reveal has the focus to it does not make sense to allow scroll on the body then.

**Comment by diniscorreia** [comment]
@DanielRuf Yeah, makes seem – I'm using the Reveal component to build a sort of notification widget (stuck to the corner of the viewport), but it is a very specific case. 

Thanks – closing this.

**Comment by fantasticrice** [comment]
@diniscorreia I have the same use case. What solution did you end up using?
