### ISSUE TITLE
for webpack4 builds, including req'd "foundation-explicit-pieces.js" causes fatal eslint build fail

### ISSUE THREAD

**Issue by hal869** [zurb/foundation-sites#11068]
when setting up Foundation-sites
```
yarn list | grep -i foundation-sites
	├─ foundation-sites@6.4.4-rc1
```

for use in webpack 4.1.1, it's currently 'necessary' to manually/locally include an instance of "foundation-explicit-pieces.js"

https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/lib/foundation-explicit-pieces.js

the final line in that instance,
```
module.exports = Foundation;
```

eslints, as seen in browser console as:
```
TypeError: "exports" is read-only[Learn More]   foundation-explicit-pieces.js:85

./assets/js/lib/foundation-explicit-pieces.js/< foundation-explicit-pieces.js:85
./assets/js/lib/foundation-explicit-pieces.js   foundation-explicit-pieces.js:1
__webpack_require__                             bootstrap:74
./assets/js/main.js/<                           https://example.com/build/js/main.js:308:89
./assets/js/main.js                             https://example.com/build/js/main.js:306:29
__webpack_require__                             bootstrap:74
[0]                                             https://example.com/build/js/main.js:467:1
__webpack_require__                             bootstrap:74
checkDeferredModules                            bootstrap:43
webpackJsonpCallback                            bootstrap:30
<anonymous>                                     universalModuleDefinition:11
webpackUniversalModuleDefinition                universalModuleDefinition:7
<anonymous>                                     universalModuleDefinition:1
```

at Gitter, @sokra commented

https://github.com/webpack/webpack/issues/4039#issuecomment-273804003

> You can mix require and export. You can't mix import and module.exports.

Unless I exclude that file from eslint, the webpack build fails/bails as an error, not a warning.

What I do not yet know, is what problems that causes, if any, by ignoring ...

**Comment by DanielRuf** [comment]
Did you try to use `export {Foundation};` ?

**Comment by DanielRuf** [comment]
The next release will be compatible.

See https://github.com/zurb/foundation-sites/blob/4e21634356da296edd2f1c3e65d91140f991008b/js/foundation.core.js#L337 and https://github.com/zurb/foundation-sites/pull/10930 regarding bundling.

foundation-explicit-pieces.js shows just one way to use Foundation.

**Comment by hal869** [comment]
Slight confusion ...

that reference has
```
Package up 6.4.3
develop (#1)       v6.4.4-rc1 v6.4.3
@kball committed on Aug 18, 2017
```
and I'm *on* 6.4.4-rc1.

so I do *NOT* need the explicit-pieces.js bit?

**Comment by hal869** [comment]
fwiw, simply

```
-	module.exports = Foundation;
+	export {Foundation};
```

both

(a) eliminates the lint/console error

&

(b) fixes a bunch of pesky artifacts I was seeing in my site frontend

And, it all webpack4 builds & watches with no apparent, related issues.

So if that's "the fix", worksforme. (tho, haven't tested thoroughly by any strecth)

**Comment by DanielRuf** [comment]
> so I do NOT need the explicit-pieces.js bit?

You can still use it. It is part of the templates and shows how you can import just the components that you need.

You can write your own solution and change the last line if you want to. It is just an example implementation of the Foundation framework.

**Comment by DanielRuf** [comment]
Like I wrote =) https://github.com/zurb/foundation-sites/issues/11068#issuecomment-373940058

If you want you can share your setup with us and the problems that you face(d).

You can close the issue if it is working now for you.

**Comment by hal869** [comment]
> You can close the issue if it is working now for you.

Appears to be, thx.  Still unclear what the recommended install is, or will be.

**Comment by DanielRuf** [comment]
@hal869 see https://github.com/zurb/foundation-zurb-template/pull/84
