### ISSUE TITLE
Cursor misplaced in form inputs on reveal modal and off canvas components on iOS 11

### ISSUE THREAD

**Issue by mfronczyk** [zurb/foundation-sites#11071]
We're experiencing same issues with our forms placed in fixed elements (reveal modal, off-canvas)  as reported here:

https://stackoverflow.com/questions/46567233/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug
https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8
https://stackoverflow.com/questions/46339063/ios-11-safari-bootstrap-modal-text-area-outside-of-cursor

However, the fixes suggesting setting 'position: fixed' on the body don't seem to always work (they don't for us). It might be because our modals are quite big and have many inputs. Could we have the Foundation components using 'position: absolute' on iOS 11? Possibly with some JS making them behaving similar to fixed elements? Changing to position absolute seems to be the most robust workaround.

**Comment by DanielRuf** [comment]
Can you provide a codepen to have a better understanding of the issue?

Is it just about using another position value on iOS 11?
CSS and JS can target also specific platforms with a few tricks.

**Comment by mfronczyk** [comment]
Yes it is, but it's the newest version of a major browser, so maybe it's worthy to have a fix for that included in the framework? It could be optional, enabled by a SASS config or a special class.

Unfortunately, the solutions we found don't fully work for us. Probably because our form is quite long and scrolling is unavoidable.

Please let me know if you're willing to include a fix in the framework and I can work on a codepen.

**Comment by DanielRuf** [comment]
Not sure if and how the fix should look like.

**Comment by DanielRuf** [comment]
cc @SassNinja

**Comment by mfronczyk** [comment]
I'm not sure as well. I was thinking about positioning modals and offcanvas absolutely instead of making the fixed. It'd be slightly different experience, because users could scroll away from the modal, but it should be OK in most cases.

**Comment by mfronczyk** [comment]
I can confirm that disabling the overlay in reveal (which is fixed), removing "is-reveal-open" styles and forcing "position: absolute" on the modal itself fixes the problem. However, it gives slightly different user experience.

**Comment by DanielRuf** [comment]
> it gives slightly different user experience.

Well, I am unsure if and how we should solve this in the framework as this is an iOS specific bug.

cc @ncoden should we add a note about this with an example how this can be solved in projects or what should we do here?

**Comment by mfronczyk** [comment]
It seems that foundation already has some code that significantly reduces the bad effects of the bug (in _reveal.scss):

```
mixin foundation-reveal {
  // [TODO] Is this necessary?
  body.is-reveal-open { // sass-lint:disable-line no-qualifying-elements
    overflow: hidden;
  }

  // html gets this class only in iOS
  html.is-reveal-open,
  html.is-reveal-open body {
    min-height: 100%;
    overflow: hidden;
    position: fixed;
    user-select: none;
  }
```

Without this, the issue gets worse. However, it's not a complete fix, because the cursor gets misplaced on longer forms, on 6 or 7th field.

It looks like the complete fix is to disable the classes above, use "position: absolute" on the modal and disable overlay, or implement it without using "position: fixed".

**Comment by DanielRuf** [comment]
> // [TODO] Is this necessary?
Is this in our code?
Yes, this is needed to remove scrollbars from the body when a reveal is open.
Disabling `user-select` is bad UX.

**Comment by mfronczyk** [comment]
When I look at master, I don't see it, but it's in foundation-sites 6.4.3.

I used the reveal component from master, but it doesn't help.

**Comment by DanielRuf** [comment]
> When I look at master, I don't see it, but it's in foundation-sites 6.4.3.
> 
> I used the reveal component from master, but it doesn't help.

The next release will use the code of the current develop branch.

**Comment by DanielRuf** [comment]
There is a reason for `position: fixed`.

**Comment by DanielRuf** [comment]
As far as I remember Apple fixed thus in the last releases so I close this.

Feel free to reopen if it still occurs with 6.5.3 and the latest Safari and iOS version.
