### ISSUE TITLE
[Feature request] LTR/RTL helpers

### ISSUE THREAD

**Issue by ncoden** [zurb/foundation-sites#11070]
Sass & CSS helpers to control visibility (or others properties) according to the current `[dir]` attribute.

For example:
```scss
<i class="show-for-rtl my-arrow-left"></i>
<i class="show-for-ltr my-arrow-right"></i>
```

```scss
<i class="flip-for-rtl my-arrow-left"></i>
```

See https://github.com/zurb/foundation-sites/pull/11017

**Comment by DanielRuf** [comment]
Closes https://github.com/zurb/foundation-sites/issues/11008
