### ISSUE TITLE
enter key in IE does not trigger changed.zf.slider on input field

### ISSUE THREAD

**Issue by ckrausko** [zurb/foundation-sites#11096]
#### How to reproduce this bug:
Using data binding with the slider control. Type any new number into the input field and hit enter. changed.zf.slider will not be triggered until you click out of the input box. Enter works correctly for chrome and firefox but not IE.

#### What should happen:
changed.zf.slider should trigger when the enter key is pressed in the input field

#### What happened instead:
changed.zf.slider is not triggered until you click out of the input field

#### Browser(s) and Device(s) tested on:
IE 11

#### Foundation Version(s) you are using:
Foundation 6.4.3

#### Test case link:
This doesn't even work properly on the foundation docs site 
https://foundation.zurb.com/sites/docs/slider.html

**Comment by DanielRuf** [comment]
We have to add a `keyup` event listener which checks for the enter key (key 13).

https://codepen.io/DanielRuf/pen/OvOVMK?editors=0010
```
      this.inputs.off('keyup.zf.slider').on('keyup.zf.slider', function (e) {
        if(e.keyCode == 13) {
        var idx = _this.inputs.index(__WEBPACK_IMPORTED_MODULE_0_jquery___default()(this));
        _this._handleEvent(e, _this.handles.eq(idx), __WEBPACK_IMPORTED_MODULE_0_jquery___default()(this).val());
        }
      });
```

But I guess this also fires twice (onchange + keyup) in other browsers @ncoden.

**Comment by DanielRuf** [comment]
It seems to be fine, `changed` is triggered after a while but the jsdoc contains some not so good wordings.
