### ISSUE TITLE
[Customizer] is down

### ISSUE THREAD

**Issue by sashabeep** [zurb/foundation-sites#11095]
When i try to build package on https://foundation.zurb.com/sites/download.html/

![2018-03-26 16 58 04](https://user-images.githubusercontent.com/5689796/37910750-f7fd2ff4-3116-11e8-9d02-025296101384.png)

**Comment by DanielRuf** [comment]
Did you retry it?

**Comment by DanielRuf** [comment]
Works on my machine.

**Comment by ncoden** [comment]
Same. Maybe a compilation error but we will need the logs. I'm waiting for accesses to Foundation servers from Zurb, this could help.

Closing this for now. @sashabeep please provide more informations (version, settings) if you are unable to download it after several tries.

**Comment by sashabeep** [comment]
Customizer f-d  up again...
![2018-11-26 12 42 04](https://user-images.githubusercontent.com/5689796/49005905-f4c94200-f178-11e8-9d3a-7670385fec57.png)

https://foundation.zurb.com/sites/download.html/custom-f6

**Comment by sashabeep** [comment]
components used:
![2018-11-26 12 45 09](https://user-images.githubusercontent.com/5689796/49006026-30fca280-f179-11e8-87d3-460db393c19a.png)
![2018-11-26 12 45 17](https://user-images.githubusercontent.com/5689796/49006029-30fca280-f179-11e8-8dd2-287e6eb9970b.png)

**Comment by ncoden** [comment]
It happens time to time when the archive is not generated fast enough.

**Comment by sashabeep** [comment]
Looks like, some hash assigned with browser session to prevent duplicates or so, but in all of my browsers nothing works for now

**Comment by DanielRuf** [comment]
See https://github.com/foundation/node-foundation-customizer/pull/13
