### ISSUE TITLE
XY grid align-center-middle isn't cascading to children

### ISSUE THREAD

**Issue by katieywu** [zurb/foundation-sites#11092]
https://codepen.io/anon/pen/qoPjLN

#### How to reproduce this bug:
Look at the codepen

#### What should happen:
Should center all children under the parent with the align-center-middle class

#### What happened instead:
Does not do that - child remains default aligned

#### Browser(s) and Device(s) tested on:
Chrome 62.0.3, Mac OS X El Capitan

#### Foundation Version(s) you are using:
6

#### Test case link:
https://codepen.io/anon/pen/qoPjLN

- [CodePen with Foundation 6.3.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Float Grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/bRYOMv)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)

**Comment by DanielRuf** [comment]
Please make sure to use Foundation Sites 6.4.(3), see https://codepen.io/DanielRuf/pen/mxBMOK

**Comment by katieywu** [comment]
@DanielRuf Oh actually the issue also includes why the nested text child isn't centered within the cell parent. Is that intentional behavior because I can't get it to center?

**Comment by DanielRuf** [comment]
Your codepen example just works in 6.4 and newer where these classes and mixins were added. Please try if the issue also exists in Foundation 6.4.3.

I can not reproduce it with the latest releases.

The docs are for the latest release.

**Comment by katieywu** [comment]
Yes I'm on 6.4.3 on my local project, the nested child that has the text "Align center not working" does not align to the center. It is nested in a div with the .cell class, (which DOES align properly), just the text child does not work

**Comment by DanielRuf** [comment]
I guess you mistake the flexbox helpers for the typography helpers.

Try `text-center` on the cell.

https://codepen.io/DanielRuf/pen/geGxBE

See https://foundation.zurb.com/sites/docs/typography-helpers.html

**Comment by DanielRuf** [comment]
The second just works on the cell boxmodel, not the content of it.

**Comment by katieywu** [comment]
Okay but say instead of having text as a child of the .cell I have another div, how would I get it to center then?

**Comment by DanielRuf** [comment]
With the same class. If you want to center the position use the grid with a cell and the align-middle class.

For content / text use the text-center / text-align solution.

And there are some mixins too.

The simplest and straight approach is `text-align` in webdesign.

**Comment by DanielRuf** [comment]
But keep in mind that a div has `display: block` and so uses `width: 100%` per default unless `inline-block` or another solution is used to change the boxmodel.

**Comment by ncoden** [comment]
@DanielRuf Is there anything to resolve here ?

**Comment by DanielRuf** [comment]
@ncoden not that I knew.

**Comment by ncoden** [comment]
@katieywu If you need any help to center an element in CSS or with Foundation, see:
* http://howtocenterincss.com/
* https://foundation.zurb.com/sites/docs/flexbox-utilities.html 
* https://css-tricks.com/snippets/css/a-guide-to-flexbox/

Keep in mind that unline `display: table-cell;`, flexbox does not center grandchildren. `grid-x align-center-middle` must be used on all parents of the element you want to center.
