### ISSUE TITLE
Dead link on Website grid page

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation-sites#11109]
The button with the text "Grid docs" leads to a dead link -- see this page https://foundation.zurb.com/grid.html

It points to this link `https://foundation.zurb.com/docs/components/grid.html`, which is dead.

**Comment by rtpHarry** [comment]
I just came here to report this as well. I guess it should be pointing at https://foundation.zurb.com/sites/docs/grid.html

**Comment by DanielRuf** [comment]
cc @JeremyEnglert because of scanning the website for dead links =)

**Comment by DanielRuf** [comment]
Closing as fixed.
