### ISSUE TITLE
Admin dashboard isn't rendering properly

### ISSUE THREAD

**Issue by GildedHonour** [zurb/foundation-sites#11105]
The example isn't rendering properly.

![_2018-03-29_09-58-46](https://user-images.githubusercontent.com/2032888/38065908-254ddca6-3338-11e8-9cb5-16d15c1ff907.png)

Everything has been loaded: styles, js.

No errors in the chrome console.

**Comment by ncoden** [comment]
Hi @GildedHonour. What version of Foundation are you using ?
This example is using the Float Grid, so for Foundation <= 6.3.

See https://foundation.zurb.com/sites/docs/grid.html#importing

**Comment by DanielRuf** [comment]
I guess there are some stylesheets not loaded (network tab?).

**Comment by GildedHonour** [comment]
yes
