### ISSUE TITLE
[Feature request] [Tabs] Jump to last scrolled position when re-opening tab

### ISSUE THREAD

**Issue by drionix** [zurb/foundation-sites#11143]
So.. As far as I know, you always start from the top of the content every time you open a tab.
I want to request a feature so that when you re-open a tab, you can jump to the last position you scrolled before you left that particular tab.

Example:
1. Open the "A" tab
2. Scroll halfway down through the content of the "A" tab
3. Open the "B" tab
4. Re-open the "A" tab and jump to the last position before you open the "B" tab.

Is it possible?

**Comment by DanielRuf** [comment]
You would have to track the scroll positions (scrollTop and so on) by yourself.
This feature is not supported by Foundation by default.

**Comment by Rand0mGuy** [comment]
Lets say I've tracked the scroll positions with js. How can I jump to the position when I a re-open the "A" tab? I don't see any way to do it now.

**Comment by ncoden** [comment]
>  This feature is not supported by Foundation by default.

His point is to _add_ this feature.

**Comment by DanielRuf** [comment]
You can listen for `change.zf.tabs` and use the first and second argument of the event to get the tab that is opened.

See https://foundation.zurb.com/sites/docs/tabs.html#js-events

**Comment by DanielRuf** [comment]
> His point is to add this feature.

Which would be for Foundation 7 then I guess.
Not sure if this makes sense in the core of Foundation.

**Comment by DanielRuf** [comment]
See https://codepen.io/DanielRuf/pen/PRXwpR?editors=0010

**Comment by Rand0mGuy** [comment]
`change.zf.tabs` fires everytime the tabs changed, right? Not only when I re-open the "A" tabs. If so, it will jumps to weird position if i open the "C" tab after the "B" tab assuming that I jump to certain position on `change.zf.tabs`.

**Comment by Rand0mGuy** [comment]
Thanks. Will see if I can make it work.
But according to me, it needs to be integrated with foundation, as foundation is a mobile-first framework, and for mobile device, scrolling to much is a big no-no.

**Comment by Rand0mGuy** [comment]
I find an easy solution for the moment, rather than implementing lots of js. Just make all tabs panel have their own independent scroll. It can be achieved with simple css like:
> .tabs-panel{
> 	overflow: auto;
> 	height: 100vh;
> }
