### ISSUE TITLE
integrity issue using firefox 

### ISSUE THREAD

**Issue by Herlderlord** [zurb/foundation-sites#11151]
Hi ! 

I've encountered an issue when i tried to use CDN link on my simple local Web page.

Here is the beginning of my code: 
```
<!doctype html>
<html class="no-js" lang="fr">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css" integrity="sha256-itWEYdFWzZPBG78bJOOiQIn06QCgN/F0wMDcC4nOhxY=" crossorigin="anonymous" />
```
Using this code, the Web page didn't displayed well. I tried to know "why" and then i found an answer: removing integrity attribute on the *link node* makes the page displaying well. 
Here is my computer configuration: 
- Firefox 59.0.2
- Ubuntu Mate 16.04
- (i don't think you really need more information; but you can ask me if you want)

I don't know if it's a known feature/issue, so i preferred create a *issue*, hopping i'm not bothering you.
Best regards.

**Comment by DanielRuf** [comment]
Hi, please check if Firefox developer tools shows another hash in the console.

**Comment by DanielRuf** [comment]
It should be
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css" integrity="sha256-GSio8qamaXapM8Fq9JYdGNTvk/dgs+cMLgPeevOYEx0= sha384-wAweiGTn38CY2DSwAaEffed6iMeflc0FMiuptanbN4J+ib+342gKGpvYRWubPd/+ sha512-QHEb6jOC8SaGTmYmGU19u2FhIfeG+t/hSacIWPpDzOp5yygnthL3JwnilM7LM1dOAbJv62R+/FICfsrKUqv4Gg==" crossorigin="anonymous">`

**Comment by Herlderlord** [comment]
It works ! :) Thank you for your reactivity. I think you can close the issue.

**Comment by DanielRuf** [comment]
For future usage: I've used https://report-uri.com/home/sri_hash by Scott Helme
