### ISSUE TITLE
Stream.On not a function

### ISSUE THREAD

**Issue by nPowers** [zurb/foundation-sites#11159]
NPM install works with no errors getting packages. Running foundation build or npm run build fails with an error that ' TypeError: stream.on is not a function' 

C:\Users\ulric\source\repos\xxxx-kentico-website\CMS\PatternLibrary>npm run build

> foundation-zurb-template@1.0.0 build C:\Users\ulric\source\repos\xxxx-kentico-website\CMS\PatternLibrary
> gulp build --production

[19:22:05] Failed to load external module @babel/register
[19:22:05] Requiring external module babel-register
[19:22:09] Using gulpfile ~\source\repos\shea-kentico-website\CMS\PatternLibrary\gulpfile.babel.js
[19:22:09] Starting 'build'...
[19:22:09] Starting 'clean'...
[19:22:09] Finished 'clean' after 66 ms
[19:22:09] Starting 'pages'...
[19:22:09] Starting 'sass'...
[19:22:09] Starting 'javascript'...
[19:22:09] Starting 'images'...
[19:22:09] Starting 'copy'...
[19:22:10] 'images' errored after 1.34 s
[19:22:10] TypeError: stream.on is not a function
    at Readable.wrap (C:\Users\ulric\source\repos\xxxx-kentico-website\CMS\PatternLibrary\node_modules\readable-stream\lib\_stream_readable.js:817:10)
...
[19:22:10] 'build' errored after 1.42 s
[19:22:10] The following tasks did not complete: pages, sass, javascript, copy
[19:22:10] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundation-zurb-template@1.0.0 build: `gulp build --production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-zurb-template@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ulric\AppData\Roaming\npm-cache\_logs\2018-04-10T23_22_10_624Z-debug.log

#### Foundation Version(s) you are using:
foundation -v
Foundation CLI version 2.2.5
Node v9.10.1
Gulp CLI version 3.9.1
Gulp Local version 4.0.0-alpha.3
Ruby Sass 3.5.6
Windows 10 Pro Version 10.0.16299.309
Python 2.7.9 (client requirement)
NPM 5.6.0
GIT version 2.16.2.windows.1

#### Client Package json:
{
  "name": "foundation-zurb-template",
  "version": "1.0.0",
  "description": "Official ZURB Template for Foundation for Sites.",
  "main": "gulpfile.babel.js",
  "scripts": {
    "start": "gulp",
    "build": "gulp build --production"
  },
  "author": "ZURB <foundation@zurb.com>",
  "license": "MIT",
  "dependencies": {
    "access-sniff": "^3.1.0",
    "foundation-sites": "~6.4.1",
    "imagemin-jpegtran": "^5.0.2",
    "jquery": ">=3.0.0",
    "motion-ui": "~1.2.2",
    "node-sass": "^4.8.3",
    "what-input": "^4.1.3"
  },
  "devDependencies": {
    "babel-core": "^6.24.1",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-register": "^6.26.0",
    "browser-sync": "^2.10.0",
    "colors": "^1.1.2",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-accessibility": "^3.0.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-babel": "^6.1.2",
    "gulp-clean-css": "^3.3.1",
    "gulp-cli": "^1.2.1",
    "gulp-color": "0.0.1",
    "gulp-concat": "^2.5.2",
    "gulp-extname": "^0.2.0",
    "gulp-htmlhint": "^2.0.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.4.0",
    "gulp-load-plugins": "^1.1.0",
    "gulp-sass": "^2.1.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.2.0",
    "gulp-uncss": "^1.0.1",
    "gulp-util": "^3.0.8",
    "gulp-wcag-accessibility": "0.0.1",
    "imagemin-pngquant": "^4.2.2",
    "js-yaml": "^3.4.6",
    "panini": "^1.3.0",
    "rimraf": "^2.4.3",
    "style-sherpa": "^1.0.0",
    "vinyl-named": "^1.1.0",
    "webpack": "^2.6.1",
    "webpack-stream": "^3.2.0",
    "yargs": "^3.8.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/zurb/foundation-zurb-template.git"
  },
  "bugs": {
    "url": "https://github.com/zurb/foundation-sites/issues",
    "email": "foundation@zurb.com"
  },
  "babel": {
    "presets": [
      "es2015"
    ]
  },
  "private": true
}

**Comment by DanielRuf** [comment]
Please try switching to NodeJS 8. The issue is in reable-stream and its dependencies.
