### ISSUE TITLE
How can I create an exactly vertically centered div or form?

### ISSUE THREAD

**Issue by GildedHonour** [zurb/foundation-sites#11169]
How can I create an exactly vertically centered div or form? ".offset" can't do that.

**Comment by DanielRuf** [comment]
Do you mean `text-align` as class and centering cells with flexbox?

Please provide a codepen with your code and usecase.

**Comment by GildedHonour** [comment]
Not text, but a column of a grid

Something like
```

<div class="small-4 column">
</div>
<div class="small-4 column">
My Content I want to be in the center, table or something else
</div>
<div class="small-4 column">
</div>

```

That doesn't work as intended

**Comment by DanielRuf** [comment]
In a 12 grid it should be in the middle. So you use the float-grid? There you can use the offset classes.

**Comment by GildedHonour** [comment]
Ok, that's working. But I don't want to calculate how many columns the content in the center needs and adjust the 1st and 3rd ones accordingly. I want it to take all it needs and it to be in center.

**Comment by DanielRuf** [comment]
`text-align:center` or `margin: 0 auto`

How does the containers around the codesnippet look like so I can create a codepen for you?

Also I think you mean horizontal ventering as vertical is top - middle - bottom.

**Comment by GildedHonour** [comment]
Thx
