### ISSUE TITLE
Notch support ?

### ISSUE THREAD

**Issue by udf2457** [zurb/foundation-sites#11188]
I did a very unscientific search of the github repo for `safe-area-inset-top` and couldn't find anything.

So any plans in this area ?  I believe the typical CSS recommendation is something along the following lines:

`padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);`

I'm not going to repeat all the stuff already out there on the internet, so I'll leave you with a couple of links....

http://stephenradford.me/removing-the-white-bars-in-safari-on-iphone-x/
https://booking.design/how-we-adapted-the-booking-com-mobile-site-for-the-iphone-x-notch-e880fa00e989

**Comment by SassNinja** [comment]
@udf2457 did you have anything specific in mind or rather where did you expect to find sth?

Notch support is nothing for the framework imo because it consists of
- meta tag in markup
- iOS constants for the CSS which depends on the project

**Comment by udf2457** [comment]
@SassNinja 

Surely, for example, ways to tweak `grid-container` would not be stupid idea ?

Something like `grid-notch-all` could be a shorthand for:
`padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left)`

With, for example `grid-notch-top` `grid-notch-left` `grid-notch-right` `grid-notch-bottom` for those who want more granular options.

Sure you could tell me I could stick it into a CSS file and compile it into `app.css`, but incase you forgot, Foundation does call itself:

> The most advanced responsive front-end framework in the world.

So surely said aforementioned "most advanced responsive framework"  should have a suitably intelligent "most advanced" answer to the "responsive" problem of the notch. :)

**Comment by udf2457** [comment]
@SassNinja 

Just be careful with that sort of _"doesn't mean we're putting everything into the framework that few people need"_ thinking.  You might end up like your friends over at Bootstrap, they infamously decided that _"few people need"_ sub-menus.

But I digress !

Optional support that can be easily turned on sounds like a reasonable compromise for now.

**Comment by SassNinja** [comment]
> Optional support that can be easily turned on sounds like a reasonable compromise for now.

Glad to hear you agree @udf2457 :)
Would you like to make a PR for this feature?

**Comment by udf2457** [comment]
Not sure I'd go as far the word "agree" but I thought I'd be generous. :)

Normally I'd love to consider a PR, but I've got a horrific backlog at work at moment, so I can't take on any non-work work for the foreseeable future, certainly not this month and unlikely next month either. I'm drowning in code at the moment !

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback and we do not need this as part of Foundation imo as the mobile market is rapidly changing (the notch is removed) and we never had to use this in any of our client projects.
