### ISSUE TITLE
Is there a way to set additional properties for header styles in settings.

### ISSUE THREAD

**Issue by asolopovas** [zurb/foundation-sites#11195]
Hi,

I have been using foundation for a while now and would like to suggest a feature, I am not sure if it can work but if it would that would be awesome.

Currently, we have variable $header-styles, where we set 'font-size' at different breakpoints. It would be cool if we could place additional properties such as colour and padding. This would give great flexibility as you could change your heading paddings and colors right from settings.scss file. Like so

```scss
$header-styles: (
  sm: (
    'h1': ('font-size': 19, 'padding': 10),
  ),
  md: (
    'h1': ('font-size': 38, 'padding': 30),
  ),
);
```

**Comment by ncoden** [comment]
Hi @asolopovas,

Thank you for your issue.
There is already discussions about this in https://github.com/zurb/foundation-sites/issues/9483. So I'm closing this for now. Please reopen if you think this is different.
