### ISSUE TITLE
top nav

### ISSUE THREAD

**Issue by JMKP** [zurb/foundation-sites#11218]
so this is my top nav but for some reason the are not on the same right i feel like its right please see if missing something thats making the second part not to be on the top nav, the list right

```html
    <div class="top-nav">
      <div class="row">
        <div class="columns large-6 medium-6">
          <ul class="top-list">
            <li><i class="fa fa-map-market"></i>Cape Town, WC, ZA</li>
            <li><i class="fa fa-phone"></i>(+27) 844-602098</li>
            <li><i class="fa fa-envelope-o"></i> <a href="">info@dekam.com</i>
          </ul>
        </div>
        <div class="columns large-6 medium-6">
          <ul id="menu-topmenu" class="top-list-right">
            <li><a href="#" data-open-"loginModal">Client Login</a></li>
            <li><a href="about.html">About Us</a></li>
            <li><a href="contact.html">Support</a></li>
          </ul>
        </div>
      </div>
    </div>
```

**Comment by DanielRuf** [comment]
Please fill out the issue template and provide a codepen to describe your issue better.

**Comment by DanielRuf** [comment]
Not sure where you got the `top-nav` class from but we use `top-bar`.

Did you use the float-grid?
https://codepen.io/DanielRuf/pen/yjgrOr

**Comment by JMKP** [comment]
hi @DanielRuf i am trying to post the full index html. i have a class top bar but trying to have a nav section on top`<body>
    <div class="top-nav">
      <div class="row">
        <div class="columns large-6 medium-6">
          <ul class="top-list">
            <li><i class="fa fa-map-market"></i>Cape Town, WC, ZA</li>
            <li><i class="fa fa-phone"></i>(+27) 844-602098</li>
            <li><i class="fa fa-envelope-o"></i> <a href="">info@dekam.com</i>
          </ul>
        </div>
        <div class="columns large-6 medium-6">
          <ul id="menu-topmenu" class="top-list-right">
            <li><a href="#" data-open-"loginModal">Client Login</a></li>
            <li><a href="about.html">About Us</a></li>
            <li><a href="contact.html">Support</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="top-bar">
    <div class="top-bar-left">
      <h3><span>JMK</span> Web Hosting</h3>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><a class="current" href="index.html">Home</a></li>
        <li><a href="shared.html">Shared Hosting</a></li>
        <li><a href="vps.html">VPS Hosting</a></li>
        <li><a href="dedicated.html">Dedicated Servers</a></li>
      </ul>
    </div>
  </div>`

**Comment by JMKP** [comment]
`<body>
    <div class="top-nav">
      <div class="row">
        <div class="columns large-6 medium-6">
          <ul class="top-list">
            <li><i class="fa fa-map-market"></i>Cape Town, WC, ZA</li>
            <li><i class="fa fa-phone"></i>(+27) 844-602098</li>
            <li><i class="fa fa-envelope-o"></i> <a href="">info@jmkwebhosting.com</i>
          </ul>
        </div>
        <div class="columns large-6 medium-6">
          <ul id="menu-topmenu" class="top-list-right">
            <li><a href="#" data-open-"loginModal">Client Login</a></li>
            <li><a href="about.html">About Us</a></li>
            <li><a href="contact.html">Support</a></li>
          </ul>
        </div>
      </div>
    </div>`

**Comment by DanielRuf** [comment]
Can you provide a working codepen with your code?

With your code it would look like this:
https://codepen.io/DanielRuf/pen/rvjbQL

**Comment by DanielRuf** [comment]
A screenshot + codepen is useful. Without this we can not help much.

**Comment by JMKP** [comment]
![code](https://user-images.githubusercontent.com/38734532/39418540-46dcc0f8-4c5b-11e8-9dc4-0b5c9171664d.PNG)
![co](https://user-images.githubusercontent.com/38734532/39418545-4f295898-4c5b-11e8-9bec-85eec847ddf0.PNG)

**Comment by DanielRuf** [comment]
Which Foundation Sites version do you use and did you add the `viewport` meta tag?

**Comment by DanielRuf** [comment]
Also make sure to use the float-grid version of Foundation, not the default xy-grid.

**Comment by JMKP** [comment]
JMK@JMK-PC MINGW64 ~
$ foundation -v
Foundation CLI version 2.2.5 i have the meta tag yes not sure if i am using the float foundation

**Comment by DanielRuf** [comment]
This is not the version of Foundation Sites but Foundation CLI.

**Comment by JMKP** [comment]
$npm install foundation-sites is that the one i should install

**Comment by JMKP** [comment]
global?

**Comment by DanielRuf** [comment]
What does `npm ls foundation-sites` output?
Do you use the sass version of Foundation?

See https://foundation.zurb.com/sites/docs/grid.html#importing for details about the float-grid usage.

**Comment by JMKP** [comment]
thank you @DanielRuf

**Comment by DanielRuf** [comment]
Is your issue resolved? If so please close this issue.
