### ISSUE TITLE
Only first click do action on Orbit slider

### ISSUE THREAD

**Issue by geosenna** [zurb/foundation-sites#11224]
## Expected Behavior
When clicking on "next, "previous" or any "dots", the slider should go the right slide
## Current Behavior
The first click is working fine anywhere (navigation or dots). Next clicks will have no impact, the slider is stuck to its current slide. No error is logged into the console.

## Test Case and/or Steps to Reproduce (for bugs)
On this Codepen, I copy paste the HTML of the official website. The issue is reproducible.
https://codepen.io/anon/pen/VxpZMV

## Context
This is very problematic as you wan understand. Right now .I can't use this slider on my website.

## Your Environment
I use the last stable version 6.4.3

**Comment by DanielRuf** [comment]
You have to include motion-ui.

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/WJpegx

See the sources in the settings of the css tab.

**Comment by DanielRuf** [comment]
https://foundation.zurb.com/sites/docs/orbit.html#basics
> Please note that apart from Javascript, Motion UI is a dependency for Orbit to work properly. If in case, you don't want any animations within your Carousel, you can always disable the animation.

**Comment by geosenna** [comment]
Thanks, I figured that out just after posting the ticket...

It might helpful to include this part in Sass and Javascript reference, where all files that need to be included to have the slider working correctly, are listed.

Because clearly I have missed it!

Thanks anyway, ticket closed

**Comment by DanielRuf** [comment]
> It might helpful to include this part in Sass and Javascript reference, where all files that need to be included to have the slider working correctly, are listed.

You mean on the same page in the docs? What exactly do you have in mind how we can improve the docs here?

**Comment by geosenna** [comment]
What I mean is usually in the SASS and Javascript reference sections are listed all the modules that are needed to have the component work as expected. 
In the Orbit case, the motion UI module include is mention in "Using Animation". 
But apparently Motion UI is not only use for animation, but to have a slider that work correctly.

This is what happened to me, everytime I want to use a foundation component, I check in the reference in bottom all modules that are needed it. This is why i missed it for Orbit.
