### ISSUE TITLE
Use new GitHub "Checks" integrations

### ISSUE THREAD

**Issue by ncoden** [zurb/foundation-sites#11247]
![39668191-ae972818-5094-11e8-83f3-85023c799444](https://user-images.githubusercontent.com/9939075/39727224-2c9ecb30-5252-11e8-91e6-f995d8f1a0a7.png)

> ### Travis CI integration
>
> As a leading provider of hosted CI, Travis CI has been helping build and test open source and private projects for more than seven years. Travis CI recently adopted GitHub Apps and now includes Checks as a way for your team to share the results of your project’s branch and pull request builds. View your build’s stages, jobs, and results, including the config associated with them to get a complete picture of the health of your projects directly from GitHub. You can also rerun builds from within the GitHub Checks UI.

See https://blog.github.com/2018-05-07-introducing-checks-api/

We could use the new GitHub "Check" tools for at least Travis CI.

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is fully and correctly filled.

**Comment by DanielRuf** [comment]
> You can also rerun builds from within the GitHub Checks UI.

https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

Sounds great =)
