### ISSUE TITLE
GetYoDigits() causing IE to fail 'invalid character'

### ISSUE THREAD

**Issue by glennphilp** [zurb/foundation-sites#11248]
## Expected Behavior

IE 11 should load JavaScript.

## Current Behavior

IE 11 script error `invalid character` in app.js (character 125) of the following line
```
return Math.round((Math.pow(36, length + 1) - Math.random() * Math.pow(36, length))).toString(36).slice(1) + (namespace ? `-${namespace}` : '');
```

## Possible Solution

There needs to be a transpile step

How to reproduce:
1. Running a Foundation for sites using app.js open in IE 11

## Context

*This is haulting my development team from releasing products*

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): IE 11
- Operating System and version (desktop or mobile): Desktop

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is fully and correctly filled.

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/develop/dist/js/foundation.js#L108
https://github.com/zurb/foundation-sites/blob/develop/dist/js/plugins/foundation.core.js#L108

**Comment by glennphilp** [comment]
I am using a Zurb stack Foundation for Sites. I uploaded my modified files for config.yml, gulpfile.babel.js, package-lock.js, and package.json to my [OneDrive](https://1drv.ms/f/s!ArzrF8-mG5DR0KZjTZ7qqgh72TYIrA)

**Comment by DanielRuf** [comment]
Do you have a `.babelrc` file in your project?

**Comment by DanielRuf** [comment]
Your `copyJS` function and so on do not make much sense as these copy from src to dist.
There is a javascript function at the bottom which uses webpack for the compilation and transpilation.

**Comment by glennphilp** [comment]
Yes. It only contains the following lines:
```javascript
{
  "presets": ["es2015"],
  "compact": false
}
```

**Comment by DanielRuf** [comment]
And which functions / tasks did you run?

**Comment by DanielRuf** [comment]
```
let webpackConfig = {
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!(dom7|swiper|vanilla-datatables)\/).*/,
        loader: 'babel-loader'
      }
    ]
  }
}
```

This does not apply the babel-loader to foundation-sites. Did you forget to add it? I highly advice to not exclude any files from the babel-loader which does the transpilation.

**Comment by DanielRuf** [comment]
And it does also not apply to your setup as you copy the js files from there manually without any transpilation (what should not be done normally). And the webpack config is only used in the javascript task.

Better copy the dist files directly.

**Comment by DanielRuf** [comment]
webpack has a globals / externals setting for such things.
See https://webpack.js.org/configuration/externals/

**Comment by glennphilp** [comment]
I was excluding swiper and vanilla-datatables as I have been unsuccessful at adding them to the Zurb stack with Webpack. I figured if I could get those working I could eventually add ScrollMagic, as it too fails to get INIT when incorporated into the stack.

What is missing for foundation-sites?

**Comment by DanielRuf** [comment]
> What is missing for foundation-sites?

Try to remove this line with the `exclude` and use the `externals` setting.

**Comment by glennphilp** [comment]
@DanielRuf did you see the normal javascript() function is still there running for all Foundation JS. The only reason for the copyJS was to include 3rd party plugins like headroom.js, vanilla-datatables, swiper.js, scrollmagic, and gsap. Which I have setup using the config.yml file to list the dependencies to copy

**Comment by DanielRuf** [comment]
Sure. And this is why the exclude is not needed. It is just used in the `javascript` task.
If you import these dependencies in your entry file use `externals` to extract/exclude them from the generated bundle.

**Comment by glennphilp** [comment]
@DanielRuf, thank you that fixed one issue. Now created another. I will open a new ticket if needed.

How should one add a new Swiper.js dependency? For instance this is what I have:

*app.js*
``` javascript
import { mySlider, galleryTop } from './lib/decoded-swiper.js';
```

*lib/decoded-swiper.js*
```javascript
// Add Swiper JS for Sliders
import Swiper from 'swiper';

  // Initialize a Swiper
  var mySwiper = new Swiper ('.swiper-container', {
    // Optional parameters
    direction: 'horizontal',
    cssWidthandHeight: true,
    containerModifierClass: 'swiper-container',
    slideClass: 'slide',
    slideActiveClass: 'slide--active',
    slideVisibleClass: 'slide--visible',
    slideDuplicateClass: 'slide--duplicate',
    slideDuplicatedNextClass: 'slide--duplicate-next',
    slideDuplicatedPrevClass: 'slide--duplicate-prev',
    slideNextClass: 'slide--next',
    slidePrevClass: 'slide--prev',
    wrapperClass: 'slides',
    // loop: true,

    // autoplay
    autoplay: {
      delay: 5000,
    },

    // Disable preloading of all images
    // preloadImages: false,

    // lazy: {
    //   loadPrevNext: true,
    // },
    
    // If we need pagination
    pagination: {
      el: '.swiper-pagination',
    },
    
    // Navigation arrows
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
    
    // And if we need scrollbar
    scrollbar: {
      el: '.swiper-scrollbar',
      draggable: true,
      hide: true,
    },
  });
```
After building, IE 11 Windows 10 still throws an error 
```javascript
if (params.resistance) data$$1.currentTranslate = swiper.minTranslate() - 1 + (-swiper.minTranslate() + data$$1.startTranslate + diff) ** resistanceRatio;
```
I realize the error might be outside the scope of Zurb stack, however, I am curious if I need to exclude Swiper.js from babel or if I setup my files incorrectly.

**Comment by DanielRuf** [comment]
Better create an issue at https://github.com/nolimits4web/Swiper as this is not directly related.

I close this issue as the initial problem seems to be solved.

Feel free to reopen if this is not the case and Foundation Sites does not work as expected.

**Comment by colecmc** [comment]
@glennphilp we need to modify the gulpfile. Something like the following:

`let webpackConfig = {
    module: {
      rules: [
        {
          test: /\.js$/,
          loader: 'babel-loader'
        }
      ]
    },
    externals: {
        jquery: 'jQuery'
    }
};`

**Comment by DanielRuf** [comment]
@colecmc that's what I tried to explain.

https://github.com/zurb/foundation-sites/issues/11248#issuecomment-388161477

**Comment by colecmc** [comment]
Hopefully that takes care of our issue. Thanks for your help!
