### ISSUE TITLE
Handlebar creation for obtaining full path to the index pages inside subfolders

### ISSUE THREAD

**Issue by nikitasol** [zurb/foundation-sites#11266]
## What is missing?

Panini handlebar to provide relative path of the page including folder name

## Why is it important?

This would provide a better option for situations when using folder_name hierarchy as opposed to file_name hierarchy

## Possible Solution

Create a handlebar helper that might provide. Something like {{root}} + {{url}} that would obtain a path like this: {{root}}/subfolder/subfolder/

## Context

At the moment the only solution for this website structure is doing each page manually. Previously I was using file_name.html hierarchy and was able to pass the issue using #ifpage and #unlesspage which doesn't work in this hierarchy as all the pages are index.html.

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): irrelevant
- Operating System and version (desktop or mobile): irrelevant

## Checklist (all required):

- [ x] I have read and follow the CONTRIBUTING.md document.
- [ x] There are no other issues similar to this one.
- [ x] The issue title is descriptive.
- [ x] The template is correctly filled.

**Comment by DanielRuf** [comment]
> Panini handlebar

Then this is the wrong repository. Please file this issue at https://github.com/zurb/panini/issues
