### ISSUE TITLE
foundation needed eyeglass ^0.8.0, current eyeglass version is 1.5.0

### ISSUE THREAD

**Issue by ThePeach** [zurb/foundation-sites#11263]
## What should happen?

no error or warning about eyeglass support

## What happens instead?

I receive the followin:

```
The following modules are incompatible with eyeglass 1.5.0:
  foundation needed eyeglass ^0.8.0
```

## Test Case and/or Steps to Reproduce

How to reproduce:
1. add foundation-sites and eyeglass
2. `@import foundation;`
3. compile sass

## Context

just trying to use foundation with Eyeglass

## Your Environment

- Foundation version(s) used: `"foundation-sites": "^6.4.4-rc1"`
- Browser(s) name and version(s): N/A
- Operating System and version (desktop or mobile): Linux

## Checklist (all required):
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11268
