### ISSUE TITLE
Misspelling on Accordion Submenu Toggle example

### ISSUE THREAD

**Issue by gettimothy** [zurb/foundation-sites#11271]
## Expected Behavior
Misspelling 

## Current Behavior
"Accordion menus can have a **seperate** submenu toggle. "

## Possible Solution
https://www.grammarly.com/blog/separate-seperate/

"Accordion menus can have a **separate** submenu toggle. "

**Comment by ncoden** [comment]
There is no small contributions. Thank you @gettimothy 👍
