### ISSUE TITLE
`gulp-util` is deprecated and their is a new version with upgrade instructions.

### ISSUE THREAD

**Issue by tobiashochguertel** [zurb/foundation-sites#11282]
## What should happen?

```
$ npm install gulp-util --save
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
+ gulp-util@3.0.8
added 58 packages in 2.135s
```

```
$ npm ls gulp-util
foundation-sites-template@1.0.0 /Users/hochguertelto/documentation-concept/part-spring-rest-docs/github/tobiashochguertel/intranet
└── gulp-util@3.0.8 

```

## Possible Solution
The Webpage: https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5 describes why and what is to do.

## Test Case and/or Steps to Reproduce

```
foundation new --framework sites --template basic
```

## Your Environment
- Foundation version(s) used: foundation-sites-template@1.0.0
- Operating System and version (desktop or mobile): Mac OS X High-Sierra

## Checklist (all required):

- [ ] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title is descriptive.
- [X] The template is correctly filled.

**Comment by DanielRuf** [comment]
We do not use `gulp-util` as direct dependeny in the develop branch of foundation-sites and we already upgraded to gulp 4. Only the templates still use gulp-util which is used by gulp plugins.

Please do a normal `npm i` instead of installing `gulp-util` and do a `npm ls gulp-util`.
