### ISSUE TITLE
Add property to avoid Foundation Tabs conflicting with AngularJS's ui-router

### ISSUE THREAD

**Issue by rchavarria** [zurb/foundation-sites#11296]
## What is missing?

I'd like to have a way to avoid conflicts between Foundation Tabs and other libraries that manage hashes in the URL, like [AngularJS's ui-router](https://ui-router.github.io/ng1/)

## Why is it important?

In most popular frameworks (Angular, React, Vue,...), it is very common to use some them with some kind of routing feature. In most cases, their routers use hashes in the URL to about the configured route.

Foundation Tabs also uses hashes in URLs to know about what tab should be active.

Setting tab's `deep_linking` option to `false` solves some problems. But I found a use case where `deep_linking` is not enough and I get JavaScript errors because router and Tabs conflict with each other.

Those errors happen everytime I navigate from a route where the HTML template has some Foundation Tabs to a route where there are no Tabs. They are caused because Tabs are always listening to changes in the browser's location hash (that changes with every route), and navigating to a route without tabs cause Tabs to try to use HTML elements that are no longer present.

## Possible Solution

My proposed solution would be to have a configurable option to stop listening to hash change events.

Another option could be to use the `deep_linking` option to decide if Tabs should be listening to hash change events or not. If the developer doesn't want to use `deep_linking`, it means she is not interested in the URL value. So, we can assume she is not interested in hash changes either.

## Context

I have an AngularJS application. And I have configured several routes. One of them, shows a component with several Foundation Tabs. While others don't show any Tab.

Navigating from one route to another causes the browsers URL to change. When the route with the Tabs is visited, Tabs start listening for hash changes. When I navigate to another route, Tabs react to the hash change event, but it fails because Tabs no longer exists.

I created a sample app on JS Bin to demonstrate it, [Demo ui-router - foundation tabs](https://jsbin.com/qamogaxuce). It has 3 routes, one of them with Tabs. Navigate between routes, take a look at the browser console.

## Your Environment

- Foundation version(s) used: 5.5.2
- Browser(s) name and version(s): latest Chrome and Firefox. I didn't try on other browsers.
- Operating System and version (desktop or mobile): Windows 10
- Other libraries versions:
1. AngularJS v1.5.9
2. AngularJS ui-rouer v1.0.10

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
New features are only added to Foundation Sites 6.

**Comment by ncoden** [comment]
Sorry @rchavarria. This is a great issue but as @DanielRuf said Foundation 5 is not supported anymore.
