### ISSUE TITLE
`xy-grid-layout` mixin missing a parameter in Sass Reference documentation

### ISSUE THREAD

**Issue by jeremylind** [zurb/foundation-sites#11297]
## Description
The `xy-grid-layout` mixin documentation at https://foundation.zurb.com/sites/docs/xy-grid.html#xy-grid-layout is missing the `$breakpoint` parameter. The default value for `$breakpoint` is `$-zf-zero-breakpoint`, which is equal to `small` (I think this is also an issue, but it looks like it's addressed here: https://github.com/zurb/foundation-sites/pull/11145). However, the user can define the `$breakpoint` parameter when including `xy-grid-layout`. In fact, it's necessary in order to get responsive gutters (until the pull request I linked to is released anyway).

## Possible Solution
Add the `$breakpoint` parameter to the parameter list for `xy-grid-layout` in the Sass Reference section of the XY Grid documentation page.

## Checklist (all required):

- [ X] I have read and follow the CONTRIBUTING.md document.
- [ X] There are no other issues similar to this one.
- [ X] The issue title is descriptive.
- [ X] The template is correctly filled.

**Comment by ncoden** [comment]
Hi @jeremylind,

You are right, this was fixed at https://github.com/zurb/foundation-sites/pull/11145. For the missing parameter in documentation, I think the doc server is out-of-date. The Sass reference is automatically generated. It should be resolved at the next release.
