### ISSUE TITLE
error ../framework/node_modules/foundation-sites/scss/components/_top-bar.scss (Line 47: Base-level rules cannot contain the parent-selector-referencing character '&'.)

### ISSUE THREAD

**Issue by shareitknowledge** [zurb/foundation-sites#11307]
## What should happen?
When I used `C:\Ruby25-x64\bin\scss.bat --no-cache --update style.scss:style.css` command. SCSS return me this error : `error ../framework/node_modules/foundation-sites/scss/components/_top-bar.scss (Line 47: Base-level rules cannot contain the parent-selector-referencing character '&'.)`. 

My SCSS file :
@import '../framework/node_modules/foundation-sites/scss/foundation';

@include foundation-global-styles;
@include foundation-xy-grid-classes;
@include foundation-typography;

@include top-bar-container;
@include top-bar-stacked;

## Your Environment

- Foundation version(s) used: foundation-sites@6.4.4-rc1
- Operating System and version (desktop or mobile): Windows 10 1803
- Ruby version : ruby 2.5.1p57 (2018-03-29 revision 63029)

## Checklist (all required):

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
The mixin `top-bar-container ` should be used in a selector (well, any mixin should, they are to "mix in" styles into CSS rules).

Please show us your style.scss file.

**Comment by DanielRuf** [comment]
Same with `top-bar-stacked`.

**Comment by shareitknowledge** [comment]
Thanks for you answer. I close this issue.
