### ISSUE TITLE
ResponsiveAccordionTabs doesn't work

### ISSUE THREAD

**Issue by anvucodespot** [zurb/foundation-sites#11309]
I use the foundation-sites 6.4.4-rc1 from npm, import it to my webpack. Every function of it works well, but  ResponsiveAccordionTabs doesn't work. It just only added id for data-responsive-accordion-tabs element then stop, no console error. You can check the after code here http://prntscr.com/johex9
The solution for me right now is initializing a accordion, then destroy it, change HTML DOM, then initialize a tab. But I don't know how to do that, I can't find out your API to do that.

Thankyou.

**Comment by DanielRuf** [comment]
Please provide a full working codepen with your code so we can test this better.

It also seems you deleted our issue template which is very helpful for us.

**Comment by anvucodespot** [comment]
Hello @DanielRuf ,

My code is very complex to bring it to codepen. You can check the online website site here https://cs-marco-1.myshopify.com/products/men-s-office-t-shirts
Scroll down, you will see the ResponsiveAccordionTabs. Tell me if i'm wrong.
Thank you.

**Comment by DanielRuf** [comment]
A codepen is meant to contain a very simple but reproducible example which reproduces the issue.

You just need a part of your html of the accordion tabs and initialize foundation on it on Codepen.


Let us know if you need help with creating a simple reproducible example.

**Comment by anvucodespot** [comment]
Hello @DanielRuf ,

I think I found the reason of this issue. But I don't know why. This is my codepen https://codepen.io/anvucodespot/pen/YvPxqj
When I use your CSS CDN, it works well, when I replace the CSS link with my CSS, it doesn't work. I really need your help. Which is I missing in my CSS?

Thank you.

**Comment by DanielRuf** [comment]
> when I replace the CSS link with my CSS, it doesn't work.

Try to remove thirdparty code and your custom code.
