### ISSUE TITLE
Anchor in dropdown link follows on the second click in Firefox 60.0.1

### ISSUE THREAD

**Issue by aronvandervalk** [zurb/foundation-sites#11327]
## What should happen?
An anchor in a dropdown should follow the link on the first click.

## What happens instead?
It only follows on the second click.

## Possible Solution
...

## Test Case and/or Steps to Reproduce
- Go to https://codepen.io/aronvandervalk/pen/OENePL
- Click on the link 'Item 2'
- On hover you see the anchor link in the hint bar below
- On every other browser but Firefox 60.0.1 in Windows 10 it does follow directly

## Context
...

## Your Environment
- Foundation version(s) used: Foundation 6.4.3
- Browser(s) name and version(s): Firefox 60.0.1
- Operating System and version (desktop or mobile): Windows 10 desktop

## Checklist (all required):
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
I think it is a browser bug.
Did you create a bugreport for Firefox too?

**Comment by DanielRuf** [comment]
Can you download mozregression and test between release 55 or 58 and 60?

**Comment by aronvandervalk** [comment]
I have run tests in Firefox 55, 58 and 59 using mozregression and the behaviour is the same.

**Comment by DanielRuf** [comment]
I can not reproduce it in Firefox 59 on Windows 10.

**Comment by DanielRuf** [comment]
> I can not reproduce it in Firefox 59 on Windows 10.

And on Firefox 60.

**Comment by DanielRuf** [comment]
It directly opens the page in a new window. Did you already try disabling all addons?

**Comment by aronvandervalk** [comment]
Hmm, it seems inconsistent. A client reported the bug initially. I can reproduce the bug on two machines locally, but another machine seems to work fine. All are clean installs of Firefox and have no add-ins. All are Windows 10.

**Comment by DanielRuf** [comment]
Well, as far as we can not reproduce it we suggest opening an issue on https://bugzilla.mozilla.org/

**Comment by DanielRuf** [comment]
Closing as not reproducible.
