### ISSUE TITLE
Abide "Passwords do not match" error if using special characters

### ISSUE THREAD

**Issue by jinch** [zurb/foundation-sites#11324]
## What should happen?

Passwords should verify if the "Password" and "Re-enter Password" fields match

______________________________

## What happens instead?

An error "Passwords do not match" is triggered if the password contain any special characters (even if those passwords do indeed match)

______________________________

## Possible Solution

Perhaps expanding the default pattern "alpha_numeric" to include these characters by default and / or creating a special "password" pattern that allows these characters?

Another option is not allowing those characters to be entered at all in the initial password field to give people fair warning that there password will not pass validation. 

______________________________

## Test Case and/or Steps to Reproduce

Test Case: https://codepen.io/jinch/pen/YvqzYP
1. Type: "test!" as the password
2. Re-type: "test!" to confirm password
3. Notice error saying the fields do not match

______________________________

## Context

I understand that custom patterns may be required for special characters however these types of symbols are commonly used in password creation so it may be worth making them apart of the default set alpha_numeric pattern ~ or maybe a special "password" pattern that is more extensive?

I'm not seeing much in the help docs on how I might be able to add these particular characters so if not apart of the defaults, maybe adding more clarification on this topic could be beneficial. Ideally any keyboard character available for a person to create a custom password should pass abide validation. From what I gather these types of characters will not properly work on default: `~!@#$%^&*()-_=+[]{}\|;:'",<.>/?

______________________________

## Your Environment

- Foundation version(s) used: 
I'm using v6.3.1 but this is also in the most recent up to v6.4.3

- Browser(s) name and version(s):
Tested in Chrome

- Operating System and version (desktop or mobile): 
Tested on Mac OS

______________________________

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
Just override the pattern.

https://codepen.io/DanielRuf/pen/jKqWqv

```js
Foundation.Abide.defaults.patterns['alpha_numeric'] = /^.*$/;
$(document).foundation();
```

**Comment by jinch** [comment]
Thanks Daniel - I wasn't sure how to go about that but your example works perfectly! I think this would be a nice addition to the framework as a default as I don't see a reason why you wouldn't want that out of the box. Regardless, thanks for your help and tip on this - appreciated!

**Comment by DanielRuf** [comment]
As this is not a very hard and senseful pattern (allow anything) it is still documented (custom patterns). I see no big advantage in adding this to the core and would say that this should be sufficient.

So far no other users or many users requested the addition of such a default pattern. Also the default patterns are for specific use cases. Your use cases may vary.

Can we close this issue here or do you see any big benefit in adding this as some default pattern?

**Comment by jinch** [comment]
I hear you and yes, this is definitely sufficient. I was unclear initially how this was done in this particular scenario but it seams straight forward enough. My only issue was that the characters are allowed to be inputed initially so it creates confusion when the error is triggered. As long as there is a documented work around I guess i's not important if thats directly integrated. I'm not the deciding factor on this of course but this issue is closed as far as I'm concerned with your solution.
