### ISSUE TITLE
OffCanvas Event Names on Documentation Did Not Match What Written on the Code

### ISSUE THREAD

**Issue by denisahac** [zurb/foundation-sites#11339]
I'm working on a project that uses **OffCanvas** component and I'm using **v6.4.3**. I wanted to listen to the event when the **OffCanvas** menu closes. right of bath I used the documentation for reference, and it didn't work. Upon browsing the code for **OffCanvas** it turned out that the event names doesn't matched what specified on the documentation.

The [documentation](https://foundation.zurb.com/sites/docs/off-canvas.html#js-events) uses the **camelCase** format for the events:

1. opened.zf.**offCanvas**
2. closed.zf.**offCanvas**

However the code uses all **lowercase** for event names, as:

1. [**opened.zf.offcanvas**](https://github.com/zurb/foundation-sites/blob/develop/dist/js/plugins/foundation.offcanvas.js#L493)
2. [**closed.zf.offcanvas**](https://github.com/zurb/foundation-sites/blob/develop/dist/js/plugins/foundation.offcanvas.js#L557)

**Comment by DanielRuf** [comment]
This is already fixed in the develop branch and will be changed in the docs for 6.5.

**Comment by ncoden** [comment]
Already fixed in https://github.com/zurb/foundation-docs/pull/24
