### ISSUE TITLE
typescript/react initialise js

### ISSUE THREAD

**Issue by Ctaque** [zurb/foundation-sites#11331]
## What should happen?
foundation js initialize correctly

## What happens instead?
compiler throws error : 
```
TypeError: __WEBPACK_IMPORTED_MODULE_9_jquery__(...).foundation is not a function
HTMLDocument.<anonymous>
src/index.tsx:13
  10 | import * as $ from 'jquery';
  11 | 
  12 |
> 13 | $(document).foundation();
  14 | 
  15 | 
  16 |
```

## Possible Solution

maybe improve documentation on how to initialize foundation's js in a typescript/react app?

How to reproduce:

1) create a typescript/react app
2) install jquery, @types/jquery, foundation-sites via npm
3) import jquery in index.ts
4) try to initialize foundation on document : 

```js
$(document).foundation();
```

## Your Environment

- Foundation version(s) used: 6
- Browser(s) name and version(s): chrome 67.033
- Operating System and version (desktop or mobile): ubuntu

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
> import * as $ from 'jquery';

You did not import foundation as it seems.

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/app.js for a usage example.

**Comment by Ctaque** [comment]
I followed the instructions on how to import foundation : 
```js
import * as $ from 'jquery';
import Foundation from 'foundation-sites';

$(document).foundation();
```


 I have a different error now : 
```
/home/cyprien/tmp/vad-api/client/node_modules/@types/foundation/index.d.ts
(329,13): Subsequent variable declarations must have the same type.  Variable 'Foundation' must be of type 'FoundationSitesStatic', but here has type 'FoundationStatic'.
```

**Comment by Ctaque** [comment]
@types\foundation version: 5.5.30
typescript version 2.8.1

**Comment by mattbag** [comment]
try only
import 'foundation-sites';

**Comment by rbrisita** [comment]
To resolve this error with Foundation v6.3.1+:

`Subsequent variable declarations must have the same type.  Variable 'Foundation' must be of type 'FoundationSitesStatic', but here has type 'FoundationStatic'.`

Remove `@types/foundation` and:

`import './path/to/node_modules/foundation-sites/dist/js/foundation'`

into the file you would like to access `Foundation`. It will have the correct type.
