### ISSUE TITLE
Production build removes last semicolon from each CSS block, and other characters

### ISSUE THREAD

**Issue by michellechild** [zurb/foundation-sites#11338]
## What should happen?
When running 'npm run build' on a foundation-cli project, the the app.css in the distribution folder is a minified compiled version of scss files in the project.

## What happens instead?
The production build of app.css is missing the last semicolon of each CSS block. 

<img width="1031" alt="screen shot 2018-06-15 at 10 23 15 am" src="https://user-images.githubusercontent.com/9676840/41473081-482cd8a4-7086-11e8-868a-368eba2d2e9c.png">

Also stripped '%' from a "calc(0% + 7w)" value in clip-path, (changed to 'calc(0 + 7w) causing styles to break. 

## Test Case and/or Steps to Reproduce

Test Case:

How to reproduce:
1. Install the Foundation CLI 
2. Run foundation new to create a new project with the latest version
3. Once created, run 'npm start' then 'npm run build' to run a production build.
4. Open app.css in the dist folder to see missing semi-colons 
(including screen shot of dist/css/app.css from new project - beautified for easier viewing)

## Context

First noticed this when using calc() in clip-path polygons, my local version worked fine but when I ran the production build I am missing percentage signs, causing the styles to break.

I'm trying to produce a production build of my code that matches my local foundation project.

## Your Environment

- Foundation version(s) used: Foundation CLI 2.2.5
- Browser(s) name and version(s): Chrome 67
- Operating System and version (desktop or mobile): Mac OS Sierra

## Checklist (all required):

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title is descriptive.
- [X] The template is correctly filled.

**Comment by DanielRuf** [comment]
This is not a bug but a feature of the nanocss / uncss. The last semicolon is not needed in CSS.

**Comment by michellechild** [comment]
@danielruf 🤦🏻‍♀️ Well I feel dumb. Thank you. Any thoughts as to why it might be stripping the % from some calc() elements?

**Comment by DanielRuf** [comment]
I guess this is a feature of node-sass in production (strip characters if there is 0) as 0(%) is 0.

But you can quote / prevent it maybe with `#{0%} - 7w`

`font-size: calc(#{0%} - 7w);`

But I guess the unitless presentation is a production feature.

**Comment by michellechild** [comment]
Got it, makes sense. Thank you so much!

**Comment by xTcoops** [comment]
I understand the remove of the last semicolon is intended, however, I am wondering if there is a way to stop that from happening. We use an email editor that adds CSS to the end of the style tag when you make changes, but it's throwing errors because the end of the tag is left unclosed with a semicolon. Easy for myself to fix as a dev, but not easy to explain to the people actually editing the emails.
