### ISSUE TITLE
Accordion data option allowAllClosed not working

### ISSUE THREAD

**Issue by heyflo** [zurb/foundation-sites#11343]
## What should happen?
All the panes in the accordion should be closed by default when using the `data-allow-all-closed="true"` option according to the doc here : https://foundation.zurb.com/sites/docs/accordion.html#all-closed

## What happens instead?
There is still one pane opened.
As you can see, even on the doc : https://foundation.zurb.com/sites/docs/accordion.html#all-closed

## Test Case and/or Steps to Reproduce
Test Case: https://foundation.zurb.com/sites/docs/accordion.html#all-closed

## Your Environment
- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): Firefox Dev Edition 61.0b14 (64 bits) - Chrome Version 67.0.3396.87 (Build officiel) (64 bits)
- Operating System and version (desktop or mobile): MacOSX High Sierra

**Comment by DanielRuf** [comment]
It just means that you can close all. Try removing the `is-active` class.

**Comment by DanielRuf** [comment]
See https://codepen.io/DanielRuf/pen/WyXLwZ?editors=1000

**Comment by heyflo** [comment]
I am facepalming right now... Really tired today didn't even noticed that 😔
Thanks ! 🎉

**Comment by DanielRuf** [comment]
No problem. I'm happy that I could help and that the initial question is solved.
Have a great week!

**Comment by heyflo** [comment]
Have a great week too!
