### ISSUE TITLE
[Magellan] seems to be broken with 6.5.0-rc.1

### ISSUE THREAD

**Issue by jcs224** [zurb/foundation-sites#11355]
Just noticed on the website that the Magellan feature doesn't seem to work on the online documentation at all. It worked with 6.4.3 docs. Using Firefox.

**Comment by DanielRuf** [comment]
Can you provide an URL? Works here in Chrome.

**Comment by jcs224** [comment]
https://foundation.zurb.com/sites/docs/xy-grid.html#auto-sizing
Once the page is loaded, I can't navigate with the links on the right.
![screenshot at 2018-06-27 00-40-51](https://user-images.githubusercontent.com/6226188/41957023-ce840e20-79a2-11e8-9414-b3445ec52998.png)
Actually, when I look at the console, this is what I see:
![screenshot at 2018-06-27 00-42-50](https://user-images.githubusercontent.com/6226188/41957117-235016ce-79a3-11e8-8d49-8469a35dfa27.png)

**Comment by ncoden** [comment]
Resolved in #11356. Thank you @jcs224 for the report.

**Comment by christianstclair** [comment]
Is there anyway to reference the 6.4.3 docs until this issue is resolved? I'm still not able to jump to sections on the current docs and I utilize the documentation frequently throughout the day. Might try to install Dash again and see if I can access the 6.4.3 documentation there.

**Comment by jcs224** [comment]
@christianstclair I'll reopen this until it's actually pushed onto the website.

**Comment by ncoden** [comment]
We just deployed v6.5.0-rc.2, this should be fixed on the website.

**Comment by DanielRuf** [comment]
> We just deployed v6.5.0-rc.2, this should be fixed on the website.

It is fixed, tested it and it works again.
