### ISSUE TITLE
[Welcome to Foundation 6] ISSUE NAME HERE

### ISSUE THREAD

**Issue by jesusceballos** [zurb/foundation-sites#11357]
## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Your Environment

- Foundation version(s) used:
- Browser(s) name and version(s):
- Operating System and version (desktop or mobile):
- Link to your project:

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [ ] This is a bug report or a feature request.
- [ ] There are no other issues similar to this one.
- [ ] The issue title is descriptive.
- [ ] The template is fully and correctly filled.

**Comment by jesusceballos** [comment]
Foundation 6 did not download completly in muy computer so it would not work correctly. I had to download Foundation 5 and this one was complete and solved my problem.

**Comment by DanielRuf** [comment]
Please edit your intial commend and tell us what you did and where you downloaded it from.

**Comment by ncoden** [comment]
No formatting at all -> closing.
