### ISSUE TITLE
Error uglifying foundation JS with grunt

### ISSUE THREAD

**Issue by mjatharvest** [zurb/foundation-sites#11351]
## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

Hi there, I am using grunt to concatenate and uglify the Foundation js files for only the components that I need in a build. (Keeps the JS as small as possible)

I'm concatenating the following the following files:
'node_modules/foundation-sites/dist/js/plugins/foundation.core.js',
'node_modules/foundation-sites/dist/js/plugins/foundation.util.*.js',
'node_modules/foundation-sites/dist/js/plugins/foundation.abide.js',
'node_modules/foundation-sites/dist/js/plugins/foundation.accordion.js',

In the 6.5 release candidate I'm getting this error when trying to uglify the concatenated Foundation JS.

```
Warning: Uglification failed.
Unexpected token: punc (}). 
```

there error is occurring on line 11407 in the concatenated file

am I posted this request in the right place?

![screen shot 2018-06-26 at 9 10 02 am](https://user-images.githubusercontent.com/285877/41919231-9a943bbe-7923-11e8-996a-9f8fc615c4a3.png)

**Comment by DanielRuf** [comment]
> Warning: Uglification failed.
> Unexpected token: punc (}).

Please try uglify-es.

**Comment by mjatharvest** [comment]
Thanks, using the [grunt-contrib-uglify-es](https://www.npmjs.com/package/grunt-contrib-uglify-es) package instead of grunt-contrib-uglify has fixed the issue.

**Comment by DanielRuf** [comment]
In general it seems like something is mangled. Can you please check if there is really `punc (})` which is wrong?

I guess the concatenation has issues with the long eval lines generated by webpack.

**Comment by DanielRuf** [comment]
Clearly an issue with eslint and the used plugins and not Foundation Sites, see https://www.google.de/search?q=%22Unexpected+token%3A+punc+(%7D)%22

**Comment by DanielRuf** [comment]
Related:
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/205#issuecomment-355854328

https://stackoverflow.com/questions/42375468/uglify-syntaxerror-unexpected-token-punc

https://github.com/nuxt/nuxt.js/issues/1668

https://github.com/webpack/webpack/issues/1542#issuecomment-357714047

Looks like some production setting which is merged with some other code.

Please provide more info like your configuration and setup, the used commands and so on.

**Comment by DanielRuf** [comment]
Please also check if there are .map files concatenated (which should not be the case)

https://github.com/gruntjs/grunt-contrib-uglify/issues/337#issuecomment-136063037

**Comment by mjatharvest** [comment]
Sure thing. Regarding my setup, I am using the following modules installed with yarn in package.json.

`{
  ...
  "dependencies": {
    "foundation-sites": "^6.5.0-rc.1",
    "grunt": "1.0.3",
    "grunt-contrib-concat": "1.0.1",
    "grunt-contrib-uglify": "3.3.0",
    "grunt-contrib-uglify-es": "^3.3.0",
    "jquery": "^3.3.1",
    "motion-ui": "^2.0.3",
    "what-input": "^5.1.0"
  }
}`

Here is the portion of my grunt file which concats and uglifies the JS.

`module.exports = function(grunt) {

	grunt.initConfig({

	pkg: grunt.file.readJSON('package.json'),

	// Add some of configs to make life easier
	srcPath: 'src/',
	cssDistPath: 'public_html/css/',
	jsDistPath: 'public_html/js/',

	/* ----------------------------------------------------
	 * Concatenate (Combine) all JS files into one
	 * ----------------------------------------------------
	 */
	concat: {
		options: {
			separator: ';'
		},
		site: {
			src: [
				// Libraries
				'node_modules/jquery/dist/jquery.js',

				// Individual Foundation Components
				'node_modules/foundation-sites/dist/js/plugins/foundation.core.js',
				'node_modules/foundation-sites/dist/js/plugins/foundation.util.*.js',
				'node_modules/foundation-sites/dist/js/plugins/foundation.abide.js',
				'node_modules/foundation-sites/dist/js/plugins/foundation.accordion.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.accordionMenu.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.drilldown.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.dropdown.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.dropdownMenu.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.equalizer.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.interchange.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.magellan.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.offcanvas.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.orbit.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.responsiveMenu.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.responsiveToggle.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.reveal.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.slider.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.sticky.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.tabs.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.toggler.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.tooltip.js',
				//'node_modules/foundation-sites/dist/js/plugins/foundation.zf.responsiveAccordionTabs',

				// My Scripts
				'<%= srcPath %>js/site.js'
				],
			dest: '<%= jsDistPath %>site.js',
			nonull: true
		}
	},



	/* ----------------------------------------------------
	 * Uglify (Minify) the concatenated file
	 * ----------------------------------------------------
	 */
	uglify: {
		site: {
			src: '<%= jsDistPath %>site.js',
			dest: '<%= jsDistPath %>site.js'
		}
	},`

**Comment by DanielRuf** [comment]
Thanks, I'll test this now.

**Comment by DanielRuf** [comment]
There seem to be multiple issues.
In general uglify-js and uglify-es are not maintained anymore.

But also babel-minify has this issue (I'll create an issue there).

Then you already use the production builds. We recommend using the minified ones as they are already optimized.

I would suggest the following setup:
```
module.exports = function(grunt) {
grunt.initConfig({

    pkg: grunt.file.readJSON('package.json'),
    
    // Add some of configs to make life easier
    srcPath: 'src/',
    cssDistPath: 'public_html/css/',
    jsDistPath: 'public_html/js/',
    
    /* ----------------------------------------------------
     * Concatenate (Combine) all JS files into one
     * ----------------------------------------------------
     */
    concat: {
        options: {
            separator: ';'
        },
        site: {
            src: [
                // Libraries
                'node_modules/jquery/dist/jquery.min.js',
    
                // Individual Foundation Components
                'node_modules/foundation-sites/dist/js/plugins/foundation.core.min.js',
                'node_modules/foundation-sites/dist/js/plugins/foundation.util.*.min.js',
                'node_modules/foundation-sites/dist/js/plugins/foundation.abide.min.js',
                'node_modules/foundation-sites/dist/js/plugins/foundation.accordion.min.js',
                //'node_modules/foundation-sites/dist/js/plugins/foundation.accordionMenu.js',
                //'node_modules/foundation-sites/dist/js/plugins/foundation.drilldown.js',
                //'node_modules/foundation-sites/dist/js/plugins/foundation.dropdown.js',
                //...other commented out modules
    
                // My Scripts
                '<%= srcPath %>js/site.js'
                ],
            dest: '<%= jsDistPath %>site.js',
            nonull: true
        }
    },
    
    
    
    /* ----------------------------------------------------
     * Uglify (Minify) the concatenated file
     * ----------------------------------------------------
     */
    uglify: {
        site: {
            src: '<%= jsDistPath %>site.js',
            dest: '<%= jsDistPath %>site.js'
        }
    }
    
    });

    grunt.loadNpmTasks('grunt-contrib-concat');

    grunt.registerTask('default', ['concat']);
};
```

And in general Grunt is also old and we recommend using webpack like we do. See https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/js/lib/foundation-explicit-pieces.js for an example setup.

**Comment by mjatharvest** [comment]
Thanks for taking a thorough look at this! I will use the minified files for now. And can explore webpack for the future.
