### ISSUE TITLE
proposal: change checks for undefined

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#11363]
## Description
Currently we have checks like `val === undefined` which is not correct in general
Correct would be `typeof val === 'undefined'` as this could fail on some systems.

Should we change this to use `typeof`?

## Possible Solution

Use `typeof` check.

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by ncoden** [comment]
Nice idea. But just to be sure, could you provide some references or tell on which systems `val === undefined` would fail ?

**Comment by DanielRuf** [comment]
> on which systems val === undefined would fail ?

It failed on a local setup with some Node versions with foundation-sites 6.4.3 (not sure if 6 or 8 or 10, was on Friday at work).

**Comment by ncoden** [comment]
https://stackoverflow.com/a/4725697/4317384

> For undeclared variables, typeof foo will return the string literal "undefined", whereas the identity check foo === undefined would trigger the error "foo is not defined".

https://stackoverflow.com/a/4726198/4317384

> For example, the following is used in IE for parsing XML:
> ```js
> var x = new ActiveXObject("Microsoft.XMLDOM");
> ```
> 
> To check whether it has a loadXML method safely:
>
> ```js
> typeof x.loadXML === "undefined"; // Returns false
> ```
> 
> On the other hand:
> 
> ```js
> x.loadXML === undefined; // Throws an error
> ```
> 
> **UPDATE**
> 
> Another advantage of the typeof check that I forgot to mention was that it also works with undeclared variables, which the foo === undefined check does not, and in fact throws a ReferenceError. Thanks to @LinusKleen for reminding me. For example:
> 
> ```js
> typeof someUndeclaredVariable; // "undefined"
> someUndeclaredVariable === undefined; // throws a ReferenceError
> ```

**Comment by ncoden** [comment]
So good idea. Label it as a fix if there is a particular issue you can reproduce and resolve. As a refactor otherwise.
