### ISSUE TITLE
6.5.0 RC1: responsive accordion tabs do not work anymore

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#11360]
## Expected Behavior

responsive accordion tabs should work, they should switch between tabs and accordions.

## Current Behavior

It does not change between tabs and accordions.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/DanielRuf/pen/MXzvMM?editors=1100

How to reproduce:
1. https://codepen.io/DanielRuf/pen/MXzvMM?editors=1100
2. resize viewport
3.

## Your Environment

- Foundation version(s) used:
- Browser(s) name and version(s):
- Operating System and version (desktop or mobile):
- Link to your project:

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is fully and correctly filled.

**Comment by ncoden** [comment]
This comes from the `resize.zf.mediaquery` event listenner being removed after the component initialization. I really don't understand where.

**Comment by DanielRuf** [comment]
Should we do some bisecting?

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11366
