### ISSUE TITLE
responsive menu does NOT work on android chrome

### ISSUE THREAD

**Issue by broros** [zurb/foundation-sites#11369]
I am testing the responsive top bar with device toolbar on chrome 

## Expected Behavior
I am expecting to see a hamburger icon

## Current Behavior
the menu just crumbles together
 
## Possible Solution
need fixing
![mobile](https://user-images.githubusercontent.com/598228/42141578-d9da06ca-7d5e-11e8-804a-12075b61f0e3.png)

**Comment by DanielRuf** [comment]
Please provide a codepen so we can reproduce this.

**Comment by broros** [comment]
my mistake just needed to add

```
<script>
      $(document).foundation();
    </script>
```
