### ISSUE TITLE
Responsive Accordion Tabs bug  in Foundation v6.5.0-rc-1

### ISSUE THREAD

**Issue by anvucodespot** [zurb/foundation-sites#11370]
## What happen?
When use the Responsive Accordion Tabs function, every another Foundation functions will be shutdown, I can't open a Reveal,  Off-Canvas,...etc. And the Responsive Accordion Tabs function doesn't work well with responsive when I change the width of screen. But no error is printed in console of browser.

You can check the codepen here https://codepen.io/anvucodespot/pen/YvPxqj
I use your official example, your original CSS and your original JS, so you can check it easier.

I will publish my project in the nex few days, so hope you fix it as soon as you can.

Thank you.

## Test Case and/or Steps to Reproduce

Test Case:
- [ ] Try to open a Reveal, Off-Canvas, Dropdown,...etc
- [ ] Check the responsive fucntion

How to reproduce:
1. Console the error if anything is wrong
2. Prevent function conflict
3. Make sure it works with responsive

## Your Environment
- Foundation version(s) used: 6.5.0-rc-1 from npm
- Browser(s) name and version(s): Google Chrome v67.0.3396.99
- Operating System and version (desktop or mobile): Windows 10, iOS 10, Android 7

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.

**Comment by ncoden** [comment]
Probably a duplicate of https://github.com/zurb/foundation-sites/issues/11360. I'll double-check that tomorrow.

**Comment by ncoden** [comment]
Note: This issue uses `v6.5.0-rc.1`, not `v6.5.0`

**Comment by sickdaflip** [comment]
1+
the same error with offcanvas + accordion, offcanvas not work.

**Comment by DanielRuf** [comment]
I can also create a patch for `patch-package` if this is needed.

**Comment by ncoden** [comment]
Duplicate of #11360. Already resolved on `develop` and `develop-6.5`.
