### ISSUE TITLE
Mention foundation-global-styles in the JavaScript section

### ISSUE THREAD

**Issue by gforcada** [zurb/foundation-sites#11374]
## Description
At work we spent quite a lot of time to debug *why* something as simple as getting the current media query, i.e:

```
Foundation.MediaQuery.current
```
was not working for us.

## Possible Solution
After debugging a lot, what we noticed was that the ``<meta class="foundation-mq">`` was not properly initialized, which pointed us to ``SCSS``, and indeed there was the problem.

We were missing:
```
@include foundation-global-styles;
```
in our main ``app.scss``.

After that was done, ``.foundation-mq`` had all the media queries.

Still there was a small thing to change: rather than calling ``Foundation.MediaQuery.current`` we had to do:

```
import {MediaQuery} from 'foundation-sites/js/foundation.util.mediaQuery';
MediaQuery.current;
```
The equivalent
```
import {Foundation} from 'foundation-sites/js/foundation.core';
MediaQuery.current;
```
was also not working.

In general, the [JavaScript setup section](https://foundation.zurb.com/sites/docs/javascript.html) needs some love, as I guess we are not the only ones that are not importing the full Foundation CSS, but just the small subset that we are need.

## Checklist (all required):
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by ncoden** [comment]
Hi @gforcada,

I agree that we could add some explantations in the Media Query documentation about `.foundation-mq` and `foundation-global-styles` (this is unrelated to the Javascript installation).

I think we should also move the `.foundation-mq` into its own mixin to let folks like you that are "are not importing the full Foundation CSS" importing just the necessary CSS and not having to deal with additonal global styles.

About `MediaQuery.current` vs `Foundation.MediaQuery.current` and import paths, we switched in v6.5.0 (RC1 for now) to UMD bundling and now expose ready-to-use plugins for ES6 imports (like `import { Dropdown } from 'foundation-sites';`). This should resolve your issue.

**Comment by ncoden** [comment]
> I think we should also move the .foundation-mq into its own mixin 

Would introduce a breaking change for for those that are importing Foundation plugins themselves in Sass. Delaying this for v6.6.0

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11382

**Comment by gforcada** [comment]
@ncoden thanks!
