### ISSUE TITLE
Typescript + webpack encore + foundation [syntax error on IE 11]

### ISSUE THREAD

**Issue by alex83130** [zurb/foundation-sites#11375]
Hello all, 

## What happen?

I have a problem for many hours now and i can't find the solution...

On my Symfony 3 project I've decided to use webpack-encore to manage my assets. I use ES6 JS and Typescript to develop in a modern javascript code. Then Babel transpile the code in ES2015 to be interpreted by all browsers. I use also the framework Foundation CSS.

My first issu is a Syntax Error, everythink is ok on Chrome/Firefox/Edge but on IE 11 I have many error ....

![capture](https://user-images.githubusercontent.com/15250423/42218922-6c8babf6-7eca-11e8-91cf-e677102fef8a.PNG)

1. First error: Error Syntax
2. Second error: Unable to get the "call" property of a null or undefined reference
3. Third error: The object does not handle the property or method "each"

The error syntax comes from a "class" tag that is still present. I don't understand because the code should be in ES2015 and so there should not have this tag...

![capture2](https://user-images.githubusercontent.com/15250423/42218931-797b7828-7eca-11e8-979a-b22b5911ce80.PNG)

I put you the code of the foundation import, Maybe I don't have the right way :

        // webpack.config.js
       const  Encore = require('@symfony/webpack-encore');
       const webpack = require('webpack');
       const  path = require("path");
       const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
       const ResponsiveSharp = require("responsive-loader/sharp");
       const DashboardPlugin = require('webpack-dashboard/plugin');

    Encore

    // enable source maps during development
    .enableSourceMaps(!Encore.isProduction())

    // the project directory where all compiled assets will be stored
    .setOutputPath('web/dist/')

    // the public path used by the web server to access the previous directory
    //Todo: In production remove web
    .setPublicPath('/dist')
    .setManifestKeyPrefix('dist')

    .createSharedEntry('vendor', [
        './web/assets/ts/app.ts',

        //vendor.css
        './web/assets/fonts/foundation-icons/foundation-icons.css',
        './web/assets/scss/app.scss',
    ])

     //Script
    .addEntry('polyfill', ["babel-polyfill"])
    .addEntry('home_page', ['./web/assets/ts/home_page.ts'])
    .addEntry('common', ['./web/assets/ts/common.ts'])
    .addEntry('essentiel_page', ['./web/assets/ts/essentiel_page.ts'])
    .addEntry('essentiels_mosaic_page', ['./web/assets/ts/essentiels_mosaic_page.ts'])
    .addEntry('creation_page', ['./web/assets/ts/creation_page.ts'])
    .addEntry('creations_mosaic_page', ['./web/assets/ts/creations_mosaic_page.ts'])
    .addEntry('creer_recette_page', ['./web/assets/ts/creer_recette_page.ts'])
    .addEntry('favoris_page', ['./web/assets/ts/favoris_page.ts'])
    .addEntry('login_page', ['./web/assets/ts/login_page.ts'])
    .addEntry('test', ['./web/assets/ts/test.ts'])

     //Style
     .addStyleEntry('home_style',[
     './web/assets/scss/home.scss'
    ])
    .addStyleEntry('common_style',[
        './web/assets/scss/common.scss'
    ])
    .addStyleEntry('essentiels_style',[
        './web/assets/scss/essentiels.scss'
    ])
    .addStyleEntry('creations_style',[
        './web/assets/scss/creations.scss'
    ])
    .addStyleEntry('creer_recette_style',[
        './web/assets/scss/creer_recette.scss'
    ])
    .addStyleEntry('custom_style',[
        './web/assets/scss/custom.scss'
    ])
    .addStyleEntry('var_style',[
        './web/assets/scss/var.scss'
    ])
    .addStyleEntry('login_style',[
        './web/assets/scss/login.scss'
    ])
    .addStyleEntry('print_style',[
        './web/assets/scss/print.scss'
    ])

    //Enable Typescri^t
    .enableTypeScriptLoader(function (typeScriptConfigOptions) {
        typeScriptConfigOptions.transpileOnly = true;
        typeScriptConfigOptions.configFile = 'tsconfig.json';
    })

    // allow legacy applications to use $/jQuery as a global variable
    .autoProvidejQuery()

    // empty the outputPath dir before each dist
    .cleanupOutputBeforeBuild()

    // show OS notifications when dists finish/fail
    .enableBuildNotifications()

    // allow sass/scss files to be processed
     .enableSassLoader(function(sassOptions) {}, {
             resolveUrlLoader: false
     })
    .enablePostCssLoader()
    .enableVersioning(Encore.isProduction())//Todo : Correct bug

     /*** Uglify accept ES6 ****/
     const webpackConfig = Encore.getWebpackConfig();

     /******************************/

    // Remove the old version first
    webpackConfig.plugins = webpackConfig.plugins.filter(
        plugin => !(plugin instanceof webpack.optimize.UglifyJsPlugin)
    );

    // Add the new one
    webpackConfig.plugins.push(new UglifyJsPlugin({
    /*    sourceMap: true*/
    }));
    /*********************/

    /** Watch options **/
    webpackConfig.watchOptions = { ignored: [/node_modules/] };
    /*******************/

    global.$ = global.jQuery = require('jquery');

    // export the final configuration
    module.exports = webpackConfig;

And my .babelrc :

    {
      "presets": [
         ["env", {
    /*      "modules": false,*/
          "targets": {
            "browsers": ["last 2 versions", "ie >= 10"]
          },
          "useBuiltIns": true,
          "debug": false,
          "sourceMaps": true
        }]
      ],
      "plugins": ["transform-runtime", "add-module-exports", "transform-property- 
     literals", "transform-member-expression-literals", "syntax-class- 
    properties","transform-class-properties","transform-es2015-template- 
    literals"]
    }

 view a similar issu : [https://foundation.zurb.com/forum/posts/39766-ie9-ie10-ie11-getting-a-syntax-error-in-plugins-code](url) but it's always not resolved in my case.

## Test Case and/or Steps to Reproduce

How to reproduce:
1. Create a typescript + webpack (with babel) + foundation css environment
2. Include "foundation_site"  (The not compiled code, directly classes) in a .ts file
3. Open IE 11, view console, normaly you have many "Syntax error"

## Your Environment

- Foundation version : 6.4.4-rc1
- Webpack version : 0.20.0
- Babel version : 7.0.0-beta.0
- Typescript version : 2.8.1
- Browser: IE 11

Thank you in advance for your held, I need it greatly -_-

**Comment by ncoden** [comment]
Hi @alex83130,

Thank you for your issue. I would need some nore informations to help you:
- How do you import Foundation into your project ?
- What version of Foundation are you using ?

Could you update your issue with the [Bug report issue template](https://github.com/zurb/foundation-sites/issues/new?template=1-bug-report.md) we provide ? Thank you!

**Comment by alex83130** [comment]
Hi @ncoden,
- I import diretly the foundation js not compiled (In foundation-sites/js/foundation.core) and not the dist folder.
The reason is that I need to use the classe to change/add parameter (Example: add a validators in  Foundation.Abide.defaults.validators) and it's not possible diretly with the dist/fundation.js (Maybe I'm wrong)

- My foundation version is 6.4.4-rc1

After several research, I find the problem and a possible solution : 
- Problem : code in foundation_sites/js is in ES2015, so not compatible with IE 11. Even if I have Babel plugin in webpack, by default it transpile only my own code and unknown the code in "node 
_modules" folder.
- Possible solution : Force the loader to transpil a module in "node_modules" with this code :
`{ test: /\.js$/, loader: 'babel-loader', include: [/node_modules\/MODULE_NAME/]}`

It works but I do not know if it is the best solution.

**Comment by DanielRuf** [comment]
> Problem : code in foundation_sites/js is in ES2015, so not compatible with IE 11. Even if I have Babel plugin in webpack, by default it transpile only my own code and unknown the code in "node
> _modules" folder.

You have to use the `include` property to apply it to the needed node_modules or `babel-plugin-transform-runtime`. This is mainly a babel configuration issue.

**Comment by ncoden** [comment]
This is what I have in mind but I thought Babel would compile `node_modules/foundation-sites` too as it is imported in your project via ES6. I guess it doens't work that way.

This is the best solution and I would recommend to do it for all your dependencies to ensure a total compatibility with non-ES5 browsers. This may not be required for v6.5.0-rc.1 as we now provide transpiled files by default.
