### ISSUE TITLE
Make the menu link selector more specific (.menu a vs. .menu > li > a)

### ISSUE THREAD

**Issue by thomasfrobieter** [zurb/foundation-sites#11386]
## What is missing?
The menu link selector selects all links inside a menu.

## Why is it important?
Everyone using a megamenu with (none menu-)links in it will have a serious problem.

## Possible Solution
Simply use a child selector:
`.menu > li > a`
or if you dont want to specify the element
`.menu > * > a`

## Context
Using megamenu structures inside regular Foundation menus.

**Comment by ncoden** [comment]
What's funny with specificity is that you're never resolving problems, just moving them elsewhere, deeper, making them even more difficult to resolve.

We shouldn't increase our specificity only to ensure that our styles are applied. This would make usage of nested elements and complex component unreliable, and deeply tied the the Foundation internal structures and arbitrary specificities.

However, I understand the issue you are facing that comes from an other bad practices: uncontrolled scope, the bad habit to automatically apply styles to childreens, preventing the user to choose weitheir these styles should be applied or not, how and where.

We already planned to work on these issues on Foundation 7 with a new CSS architecture close to BEM, and there will be probably no refactor on the menu in the v6, so I'm closing this issue for now.

**Comment by thomasfrobieter** [comment]
Thank's for the very fast reply. Yes, sadly i know specifity issues very well, but i used a Foundation Fork with the mentioned fix for some months without any issues. But i understand your point absolutely.

I will simply it fork again, and i'm very, very happy to hear you will use something like BEM in Foundation 7 👍

**Comment by DanielRuf** [comment]
@thomasfrobieter you can also use `patch-package` instead of a fork which you have to keep in sync
