### ISSUE TITLE
Responsive toggle cannot be setup without data-responsive-toggle attribute

### ISSUE THREAD

**Issue by simongcc** [zurb/foundation-sites#11385]
## What should happen?
if someone run
```
var responsiveTitleBar = new Foundation.ResponsiveToggle($('#title-bar' ), {
      hideFor: 'medium',
      responsiveToggle: 'mobile-menu',
 });
```
This should work properly, howerver

## What happens instead?
Error
```
Your tab bar needs an ID of a Menu as the value of data-tab-bar.
```
will be shown instead.
Because in the source `foundation.responsiveToggle.js`
```
var targetID = this.$element.data('responsive-toggle');
```
The targetID is only considering data-responsive-toggle tag without considering the options.

## Possible Solution
The suggested way is to consider the options also so that the attribute come first, if no attribute, options will be considered before showing error.
```
var targetID = this.$element.data('responsive-toggle') || this.options.responsiveToggle
```

## Test Case and/or Steps to Reproduce
Test Case: https://codepen.io/simongcc/pen/NzVOjb
6.4.3 is chosen in the test which is the closest previous available version

## Context

The reason I discover this because I want to add sticky feature while using the responsive-toggle in the title-bar. I tried to use tag instead of custom function to invoke. However the default attribute setup with `$(document).foundation();` does not work. I haven't found out why yet. Then I try to setup sticky and responsiveToggle manually.
Then I found that responsiveToggle does not work without attribute.

## Your Environment
- Foundation version(s) used: foundation-sites@6.4.4-rc1 (package.json)
- Browser(s) name and version(s): Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Mac OS Sierra 10.12.6 (16G1408)

## Checklist (all required):

- [/] I have read and follow the CONTRIBUTING.md document.
- [/] There are no other issues similar to this one.
- [/] The issue title is descriptive.
- [/] The template is correctly filled.

**Comment by simongcc** [comment]
@ncoden Thanks for your response.
May I know why you say that Responsive Toggle have no such option as `responsiveToggle`?
Because, when I find out this, I just trace the `this.options` for a normal creation.
'responsiveToggle' is the default option inside options object so I come to the idea by extending the choice. Maybe there is some more official or better way to do it.
Anyway, glad that it is inspired as a new feature so as to other components.

**Comment by simongcc** [comment]
@DanielRuf did you mean Revisit for version 7 in the future?

**Comment by DanielRuf** [comment]
> @DanielRuf did you mean Revisit for version 7 in the future?

Hi @simongcc,

exactly. We are currently preparing the next 6.x release so we have to prioritize things.
