### ISSUE TITLE
Get rid of jQuery

### ISSUE THREAD

**Issue by broros** [zurb/foundation-sites#11404]
its hard to incorporate foundation with diffrent frameworks, jQuery should not be required for foundation 6+

**Comment by DanielRuf** [comment]
We already plan this for Foundation Sites 7.

**Comment by broros** [comment]
that will take too long

**Comment by SassNinja** [comment]
> that will take too long - @broros 

The whole JS would have to be reworked, every single component!
Anything but a new major version (Foundation 7) doesn't make sense.

Many people would like to get rid of the jQuery dependency (me included) but we have to be realistic.

**Comment by mattbag** [comment]
As above is all correct, personally jquery can't be removed as most of the work is done within wordpress etc. Very keen to see a vanilla 7, but surely the css part is already reliable for webapps right now, and the js part can be easily added with the framework used.
Adding also that zf has very advanced and configurable components, for simple/basic similar components as accordions you don't need a framework, the web is full of examples.

**Comment by DanielRuf** [comment]
> personally jquery can't be removed as most of the work is done within wordpress etc

Not sure what you mean but this issue is about removing one big required dependency of Foundation for all projects. It's not related to a specific platform.

**Comment by DanielRuf** [comment]
> and the js part can be easily added with the framework used

It's much more as we havve many JS components. You do not want to reinvent the wheel or reimplement the components. Foundation is a frontend framework and this is out of scope of v6.

**Comment by DanielRuf** [comment]
> and the js part can be easily added with the framework used

It's much more as we have many JS components. You do not want to reinvent the wheel or reimplement the components. Foundation is a frontend framework and this is out of scope of v6.

**Comment by ncoden** [comment]
Closing this issue as it is already planned for Foundation 7.

**Comment by ArondeParon** [comment]
@ncoden 

Is it possible to update the roadmap in the wiki?

I've searched the issues for information more recent than last January regarding the Foundation 7 timeline, but was not able to find anything. I realize that giving setting an actual release date might be a bit too much to ask, but as it is now, I really don't know what the overall timeline is.

Perhaps I missed something, so in that case, please let me know.

**Comment by ncoden** [comment]
@ArondeParon There is no roadmap for v7 yet. We had a lot of discussions about it and we know what direction it should take, but we still have work to do before being able to say, depending on the availaible people, how much time it would take to work on it. This is quite a heavy project.

**Comment by phifa** [comment]
Looks like the roadmap got updated. Great to see jQuery support drop. Anybody already started rewriting js? I know Typescript was for discussion too. @ncoden What are your current thoughts on this?

**Comment by lkraav** [comment]
Interesting discussion. I just recently proposed Web Components to @ncoden on Slack, but never got around to filing an issue.

https://stenciljs.com (or https://github.com/Polymer/lit-element, or alternatives) + TypeScript would be a massively strong success result hypothesis.
