### ISSUE TITLE
Building Block Dashboard Number Card if/else in div attributes?

### ISSUE THREAD

**Issue by gettimothy** [zurb/foundation-sites#11400]
## Current Behavior

> <div class="dashboard-number-card{{#if positive}} positive{{/if}}{{#if negative}} negative{{/if}}">

I cannot find any examples of this as HTML (it looks like an unexpanded macro to me)

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

https://foundation.zurb.com/building-blocks/blocks/dashboard-number-card.html

How to reproduce:
1. go here: https://foundation.zurb.com/building-blocks/blocks/dashboard-number-card.html
2. look at HTML block

## Context

I am building out an example of the Kit https://foundation.zurb.com/building-blocks/kits/dashboard.html
for a project. This Building Block is listed as a component of the kit. 

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is fully and correctly filled.

**Comment by gettimothy** [comment]
Resolved the issue by examining the CSS code.

One simply adds (or omits) a 'positive' , 'negative' class to the 'dashboard-number-card' class.



>  <  div class="dashboard-number-card"  >
> <  div class="dashboard-number-card positive"  >
> <  div class="dashboard-number-card negative"  >
>

**Comment by DanielRuf** [comment]
Hi @gettimothy, is your issue resolved? If so, please close it.

**Comment by gettimothy** [comment]
Well, for me, I figured out the bug. The bug still exists on the Zurb site. https://foundation.zurb.com/building-blocks/blocks/dashboard-number-card.html

So, if posting my work around qualifies as solved, then let me know.

Thx

---- On Tue, 17 Jul 2018 01:54:39 -0400 notifications@github.com wrote ----

Hi @gettimothy, is your issue resolved? If so, please close it.

**Comment by gettimothy** [comment]
Hi Daniel, I read your comment on Stack Exchange. Yes, it is resolved. I am not sure how to close an issue though. cheers. t ---- On Tue, 17 Jul 2018 01:54:39 -0400 Daniel Ruf <notifications@github.com> wrote ---- Hi @gettimothy, is your issue resolved? If so, please close it. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
