### ISSUE TITLE
Website section for 3.x.x documentation doesn't load assets

### ISSUE THREAD

**Issue by alsoknownasdrew** [zurb/foundation-sites#11402]
## What should happen?

[Documentation website](https://foundation.zurb.com/sites/docs/v/3.2.5/) of version 3 should load assets properly

## What happens instead?

CSS and JS assets are not loaded

## Test Case and/or Steps to Reproduce

Test Case: Navigate to https://foundation.zurb.com/sites/docs/v/3.2.5/

How to reproduce:
1. Navigate to https://foundation.zurb.com/sites/docs/v/3.2.5/

## Your Environment

- Foundation version(s) used: 3.2.5
- Browser(s) name and version(s): Google Chrome 67.0.3396.99
- Operating System and version (desktop or mobile): OSX Sierra

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
> Documentation website of version 3 should load assets properly

These are very old docs and we do not support Foundation Sites 3 anymore.
