### ISSUE TITLE
Default CSS for Foundation 6.5.2-rc.2 breaks menu background (regression from 6.4.3)

### ISSUE THREAD

**Issue by toebes** [zurb/foundation-sites#11412]
## What should happen?
The menu should be visible, particularly the active item.  Note that if you use 6.4.3 it works properly.

## What happens instead?
The default CSS overrides the color for the menu background

## Test Case and/or Steps to Reproduce

Test Case:
https://codepen.io/anon/pen/VBKKNx
Note that if you remove the reference to 6.5.0 and let codepen load up 6.4.3, it works as expected. 
 
## Context
Trying to implement a responsive toggle using the default CSS and JS based on the example at https://foundation.zurb.com/sites/docs/responsive-navigation.html#responsive-toggle

## Your Environment

Foundation 6.5.0-rc.2
Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
Windows 10 Pro

## Checklist (all required):

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title is descriptive.
- [X] The template is correctly filled.

**Comment by DanielRuf** [comment]
6.5.0-rc.1 also works so this is inbetween RC 1 and RC 2.

**Comment by ncoden** [comment]
Hi @toebes,

Sorry for the late reply. This bug were introduced in https://github.com/zurb/foundation-sites/pull/11377. I took care of this in https://github.com/zurb/foundation-sites/pull/11433.
