### ISSUE TITLE
[Dropdown Menu] Dropdown closes when user tries to select an email address suggestion from a child email input browser dropdown

### ISSUE THREAD

**Issue by mkivikoski** [zurb/foundation-sites#11410]
## Expected Behavior
When a user focuses on an email input in a form inside of a dropdown menu (https://foundation.zurb.com/sites/docs/dropdown-menu.html#js-options), the user should be able to select a previous email address provided by the browser, without the dropdown closing. 

## Current Behavior
When using a form inside of a dropdown menu, if an input is a `type="email"`, when the user focuses on the input, the browser shows the past email address used. When a user hovers over that list of email addresses, the dropdown seems to consider this a `mouseleave` event and closes the dropdown. 

## Possible Solution

Potential reason for the bug: The dropdown seems to consider accessing this dropdown as a `mouseleave` event. 

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: This is reproducible in this codepen : https://codepen.io/mikekivikoski/pen/XBdMrK

How to reproduce:
1. Hover on the username
2. Select the 'Email field'
3. Try to hover/select an email suggestion that is shown from the browser of a past email used
4. Dropdown closes

## Context

We're trying to use this dropdown as a login form for a web app, where users' email address are their usernames. 

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): Chrome 67
- Operating System and version (desktop or mobile): High Sierra, desktop
- Link to your project: n/a

## Checklist (all required):

- [X] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [X] This is a bug report or a feature request.
- [X] There are no other issues similar to this one.
- [X] The issue title is descriptive.
- [X] The template is fully and correctly filled.

**Comment by arloduff** [comment]
I've implemented a partial fix at https://github.com/zurb/foundation-sites/pull/11411 however, it will cause the dropdown menus to no longer auto-close on Firefox if the user navigates away using Alt-Tab, due to the way `document.hasFocus()` behaves on Firefox. I'm open to other suggestions how to resolve this, but have opened this PR as a possible solution.

**Comment by arloduff** [comment]
Added a commit to my above PR which resolves the above-mentioned issue. Only remaining bug I'm seeing is that if a user on Firefox is hovered over one of the input suggestions and then uses the keyboard to navigate to a different window, the dropdown will remain open, but will auto close again once focus is returned to the browser. As long as the user is hovered over a different part of the menu, auto closing will behave as normal.
