### ISSUE TITLE
IE/Edge Orbit Flicker Bug

### ISSUE THREAD

**Issue by claytonium239** [zurb/foundation-sites#11414]
## Expected Behavior
Using Orbit In IE/Edge should be a fluid motion when clicking through the images.

## Current Behavior
In IE/Edge images will randomly flicker as you click through the slider.  It does not happen consistently.

## Test Case and/or Steps to Reproduce (for bugs)
Open oribit in IE or Edge and start clicking through the slider, you will notice the images vanish for a second which causes a flicker.
Test Case: https://codepen.io/IamManchanda/pen/GmGzWY?editors=1100

## Your Environment
- Foundation version(s) used: Foundation 6.4.3
- Browser(s) name and version(s): IE 11 Edge 15,16,17

## Checklist (all required):
- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is fully and correctly filled.

**Comment by DanielRuf** [comment]
Does it also occur here?

https://codepen.io/DanielRuf/pen/yqVgjj?editors=1100

**Comment by claytonium239** [comment]
Hey Daniel, thank you for the quick response as always. Yes I am still seeing it, on my system and a colleague's. I attached a video of it happening. Thanks again for your attention.
[Flicker-issue.zip](https://github.com/zurb/foundation-sites/files/2211289/Flicker-issue.zip)

**Comment by DanielRuf** [comment]
I've updated the codepen with the latest Foundation Sites files. Can you check again?

**Comment by claytonium239** [comment]
Hey Daniel, that does fix it. It looks like that version is in release candidate, do you know (approximately) when that goes gold? This will for be for a production site, so want to wait for it to be the official version.

**Comment by DanielRuf** [comment]
That's good. The relase candiates are already available through npm. We do not yet have a specific date when 6.5.0 stable will be released. We will release a RC 3 very soon.

Can we close this issue or should we keep it open?

**Comment by claytonium239** [comment]
Thanks again Daniel, we can close this.
