### ISSUE TITLE
Style sherpa includes

### ISSUE THREAD

**Issue by sensaetions** [zurb/foundation-sites#11415]
## What is missing?

Is it possible to use partials in Markdown? Our website is massive, and I'd like to split up different portions of the style guide into partials. Is this possible?

## Why is it important?

Similar to how panini works, it would be helpful to be able to split up the style guide contents into partials to be imported for easier maintainability (instead of a single Markdown file).

## Your Environment

- Foundation version(s) used: 6.0.2.rc-2
- Browser(s) name and version(s):
- Operating System and version (desktop or mobile):

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
I guess this is here the wrong repository.

**Comment by DanielRuf** [comment]
Please ask this on https://github.com/zurb/style-sherpa to prevent confusion between the projects.

And there should be more in the docs.
