### ISSUE TITLE
<colgroup> styles don't work

### ISSUE THREAD

**Issue by lirael** [zurb/foundation-sites#11413]
## What should happen?
When you use <colgroup> in the html table, it should apply specific styling on all column:
https://codepen.io/olena-pastushenko/pen/PBGyGg

## What happens instead?
When using all the same html, but with Foundation css applied, colgroup styles are being ignored:
https://codepen.io/olena-pastushenko/pen/ZjpqBL

## Possible Solution
Looks like styles are being overwritten at some point, but I couldn't find out where exactly does it happen

## Test Case and/or Steps to Reproduce

Test Case:

https://codepen.io/olena-pastushenko/pen/mjrQWV

How to reproduce:
1. Create any html table which uses colgroup 
2. Apply styling for a specific column -> It works
3. Connect foundation css -> It doesn't work anymore

## Context

I'm trying to create a styling (background and border) for a specific column in a nested table. Maybe Foundation has anything else for this purpose? But I couldn't find anything in docs

## Your Environment

- Foundation version(s) used:
- Browser(s) name and version(s): Safari, Chrome
- Operating System and version (desktop or mobile): macOS

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
The CSS selector for rows might have a higher priority than column styles.

We will check that.

**Comment by DanielRuf** [comment]
![image](https://user-images.githubusercontent.com/827205/63805518-ea132780-c919-11e9-9544-d858e27bc398.png)

**Comment by DanielRuf** [comment]
This is expected by the official CSS specification.

https://www.w3.org/TR/CSS21/tables.html#columns
> 'background'
> The background properties set the background for cells in the column, but only if both the cell and row have transparent backgrounds. See "Table layers and transparency."
