### ISSUE TITLE
Orbit goes blank when resizing browser

### ISSUE THREAD

**Issue by mi5studio** [zurb/foundation-sites#11428]
## What should happen?
Orbit should show an image slider

## What happens instead?
When I resize the browser, after the last slide the orbit container goes black and all the orbit bullets goes to the left vertically. I have downloaded foundation last month from the website the complete manual instalation. 

I have been searching, noticed that many guys have the same issue but didn't find a solution at all.

## Test Case and/or Steps to Reproduce

Test Case:

How to reproduce:
1.
2.
3.

## Your Environment

- Foundation version(s) used:
- Browser(s) name and version(s):
- Operating System and version (desktop or mobile):

## Checklist (all required):

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title is descriptive.
- [ ] The template is correctly filled.

**Comment by DanielRuf** [comment]
Thanks for reporting this.

> Test Case:
> 
> How to reproduce:

Please fill out these steps.

But I think this was already fixed in 6.5.0 RC1.
Can you test RC2?

**Comment by DanielRuf** [comment]
> I have been searching, noticed that many guys have the same issue

Where did you find more reports about this exact same issue?

**Comment by DanielRuf** [comment]
The website still delivers 6.4.2, you can either install the latest releases with yarn / npm or download them from https://github.com/zurb/foundation-sites/releases

**Comment by DanielRuf** [comment]
It depends on which file you include / use at the moment.

**Comment by mi5studio** [comment]
Thanks, I'm using foundation.js and this it seems to have all the js inside (orbit for example) should I delete orbit inside the js or call all the js separately?

**Comment by mi5studio** [comment]
I just add the foundation.orbit.js to my website but the problem remains.

**Comment by DanielRuf** [comment]
Did you try https://github.com/zurb/foundation-sites/releases/download/v6.5.0-rc.2/foundation.js?

**Comment by DanielRuf** [comment]
> I just add the foundation.orbit.js to my website but the problem remains.

Where did you get it from?

**Comment by mi5studio** [comment]
yes sir I have tried the one you provided me and the problem remains and also downloaded the entire zip in the resources web https://github.com/zurb/foundation-sites/releases

If I delete the foundation.js from my website the page still works, it's really confusing

**Comment by DanielRuf** [comment]
Please create a codepen so we can reproduce this.

**Comment by mi5studio** [comment]
Shure, here is the pen code, it is not working properly https://codepen.io/MI5Studio/pen/pZWVBR

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/gjvZaW

Did you forget to include Motion UI?

**Comment by mi5studio** [comment]
yes sir. I just added Motion UI. Now in my example if you expand and collapse the browser repeatedly you will notice that the orbit does not work anymore and goes blank

**Comment by DanielRuf** [comment]
Please test https://codepen.io/DanielRuf/pen/gjvZaW, I can not reproduce it there.

**Comment by DanielRuf** [comment]
> Foundation version(s) used:
> Browser(s) name and version(s):
> Operating System and version (desktop or mobile):

Also please fill out all the requested information.

**Comment by SassNinja** [comment]
> yes sir. I just added Motion UI. – @mi5studio 

No, not completely. You added only the CSS part.

> Shure, here is the pen code, it is not working properly [codepen.io/MI5Studio/pen/pZWVBR](codepen.io/MI5Studio/pen/pZWVBR) – @mi5studio 

Your codepen has two problems:

1. Motion UI is missing – to fix this add it
https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.2.3/motion-ui.min.js
2. Foundation's JS is missing – instead you added this in your JavaScript settings
https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css

After doing this your codepen was working for me.
You can also check the codepen from @DanielRuf which is working (and using v6.5.0-rc2 instead of v6.4.3)

I'll close this issue as it's obviously a problem of your implementation and not of Foundation.
