### ISSUE TITLE
Reveal modal forces table to scroll down to bottom

### ISSUE THREAD

**Issue by aloh86** [zurb/foundation-sites#11420]
## What should happen?
When a reveal modal is dismissed, a table with **class="table-scroll"** should not be affected in terms of its scroll position.

## What happens instead?
When there is a table on the page contained within a **class="table-scroll"**, and the content is high enough so that the table has vertical scrolling, the scrolling will always be pushed all the way to the bottom when a reveal modal is dismissed.

## Possible Solution
No workaround yet.

## Test Case: 
https://codepen.io/aloh86/pen/BPwpLY

## Context

I have a table with many rows, so it is contained within a table-scroll. I wanted a user to click on a row, and the reveal modal would vertically list the row data. However, when the modal is dismissed, the table is now scrolled all the way to the bottom, which is inconvenient for user to scroll back to where they were since my tables can be very large in height because of the many rows.

## Your Environment

- Foundation 6.4.2
- Firefox 61.0.1.
- Windows 10, both desktop and mobile.

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
I think we already fixed the issue that the focus was changed after closing a reveal.

I can not reproduce it with the latest release (6.5.0 RC2): https://codepen.io/DanielRuf/pen/BPwgMP

**Comment by aloh86** [comment]
Ok, great. Thanks DanielRuf.
