### ISSUE TITLE
Reveal component depends on breakpoint (throws warning)

### ISSUE THREAD

**Issue by alexanderjakob** [zurb/foundation-sites#11424]
## What should happen?
I would like to use my own breakpoint map. In this map breakpoint "medium" is missing due to naming my breakpoints. Now I expect, that I am able to set the reveal "medium" breakpoint manually in my settings.scss to prevent outputtet warning.

## What happens instead?
Taskrunner is giving a warning that medium is missing. If I want to remove this warning I have to add medium to my breakpoints map.

Running "sass:base" (sass) task
WARNING: breakpoint(): "medium" is not defined in your $breakpoints setting.
         on line 73 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in function `breakpoint`
         from line 143 of node_modules/foundation-sites/scss/util/_breakpoint.scss, in mixin `breakpoint`
         from line 44 of node_modules/foundation-sites/scss/components/_reveal.scss
         from line 58 of node_modules/foundation-sites/scss/foundation.scss
         from line 10 of src/styles/main.scss

## Possible Solution
Maybe, there's the possibility to add a settings-var for defining the reveal breakpoint. (see in _reveal.scss)

## Steps to Reproduce
How to reproduce:
1. Remove all breakpoints from breakpoints map and use custom breakpoints instead
2. Include reveal component
3. Build :)

## Your Environment
- Foundation version(s) used: 6.4.3
- npm, grunt, sass

## Checklist (all required):
- [X] I have read and follow the CONTRIBUTING.md document.
- [X] There are no other issues similar to this one.
- [X] The issue title is descriptive.
- [X] The template is correctly filled.

**Comment by DanielRuf** [comment]
Hi, thanks for reporting this.

Does this still happen with 6.5.0 RC2?

**Comment by aj1991** [comment]
Yes, in this component, the medium breakpoint is very static implemented - line 45, 83, 107, see https://github.com/zurb/foundation-sites/blob/v6.5.0-rc.2/scss/components/_reveal.scss

**Comment by ncoden** [comment]
I agree that the Reveal component could be refactored to make it more customizable or usable semantically.

A first step could be a maps to set sizes at each breakpoint like:
```scss
$reveal-widths: (
  small: full,
  medium: default
);
```

We can also change `$reveal-width` but this would be a breaking change: Reveal with a custom width set would lost the "full" behavior on the small breakpoint.

**Comment by aj1991** [comment]
Map sounds great!
