### ISSUE TITLE
Mega Menu Dropdown hover flash of content

### ISSUE THREAD

**Issue by vcarneiro** [zurb/foundation-sites#11421]
## Expected Behavior
I've created a mega menu using foundation drop down and when I hover really quickly from "Standards" to "Advocacy" the mega menu drop down should flow smoothly. Similar to what happens between "Standards" and "Analytics". 

## Current Behavior
Right now when I hover really quickly from "Standards" to "Advocacy" the mega menu drop down will cause a flash                                          

## Possible Solution
I know a way to solve my problem is to set data-hover-delay to 0 although then that eliminates the user forgiveness

## Test Case and/or Steps to Reproduce (for bugs)
[https://codepen.io/anon/pen/RBLOwM](https://codepen.io/anon/pen/RBLOwM)

## Checklist (all required):

- [x] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is fully and correctly filled.

**Comment by ncoden** [comment]
@vcarneiro I am sorry, I don't know such examples. But the DropdownMenu is definitely the appropriate Foundation plugin to implement it.
