### ISSUE TITLE
[Forms] Abide does not work correctly in conjunction with input-group

### ISSUE THREAD

**Issue by jmartsch** [zurb/foundation-sites#11431]
## Expected Behavior
If there is an error for the field in the input-group, the Abide error message should be displayed on the next line.

## Current Behavior
The error message appears inline behind the last element

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/jmar/pen/GBdoaM
The test is based on your https://foundation.zurb.com/sites/docs/forms.html#inline-labels-and-buttons codepen demo.
Click on the submit button, to see the errors.

## Your Environment

- Foundation version(s) used: Foundation LATEST (6.3.1) CSS Build (Flex)

**Comment by DanielRuf** [comment]
> Foundation version(s) used: Foundation LATEST (6.3.1) CSS Build (Flex)

The latest releases are 6.4.3 and 6.5.0 RC2. Please try them to see if it also happens there.

**Comment by DanielRuf** [comment]
https://codepen.io/DanielRuf/pen/NBMRoz

**Comment by DanielRuf** [comment]
> When the Form Errors cannot be placed next to its field, like in an Input Group, the relation can be declared with [data-form-error-for] attribute.

https://foundation.zurb.com/sites/docs/abide.html

**Comment by DanielRuf** [comment]
So not a bug imho.

**Comment by jmartsch** [comment]
OK, this seems to be fixed in version 6.4.3 an higher
