### ISSUE TITLE
Gulp serve task blocks watch; browser.reload blocks watch

### ISSUE THREAD

**Issue by aorinevo** [zurb/foundation-sites#11443]
## What should happen?

When running `npm start` the project should build, the server should start, and browser should automatically reload on changes.

## What happens instead?

Project gets built, server starts, but browser does not reload on changes.

## Possible Solution

Use the done callback in watch task and wrap browser.reload in a callback that executes the gulp done callback after reload.

## Test Case and/or Steps to Reproduce

Test Case:

How to reproduce:
1.  Run `npm start`
2.  Edit a file that's targeted by one of the watch globs (i.e. docs/pages/welcome.md
3.  Watch does not pick up the changes and browser does not reload

## Context

Slows development.

## Your Environment

- Foundation version(s) used:  6.4.3 (develop branch)
- Browser(s) name and version(s): Chrome, Safari, Firefox
- Operating System and version (desktop or mobile): Mac High Sierra v10.13.6

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by ncoden** [comment]
Hi @aorinevo, thank you for your issue and pull request. I will take a look at it later.
