### ISSUE TITLE
[Accordion] bottom border is missing on last item

### ISSUE THREAD

**Issue by jmartsch** [zurb/foundation-sites#11447]
## Expected Behavior
A bottom border should be displayed on the last item when the accordion is collapsed.

## Current Behavior
Right now the border does not display and so it looks wrong.
You can see it on your demo page https://foundation.zurb.com/sites/docs/accordion.html
![accordion](https://user-images.githubusercontent.com/551551/44032015-215f8ace-9f06-11e8-923a-9fcad5ae892c.png)

## Possible Solution
remove `border-bottom: 0` from .accordion-title
add `margin-top: -1px` to .accordion-title and .accordion-content

## Your Environment

- Foundation version(s) used: 6.5.0-rc2

## Checklist (all required):

- [X] I have read and follow the [CONTRIBUTING](CONTRIBUTING.md) document.
- [X] This is a bug report or a feature request.
- [X] There are no other issues similar to this one.
- [X] The issue title is descriptive.
- [X] The template is fully and correctly filled.

**Comment by ncoden** [comment]
Hi @jmartsch,

Thank you for the issue. `border-bottom: 0` should be override on the last element, but I think the selector for that was broke in #11227 ([scss/components/_breadcrumbs.scss:102](https://github.com/zurb/foundation-sites/pull/11227/files#diff-c67a9e7b038c3dd33c89c63c4f28fbddL102)).

Poke @DanielRuf. With the way Sass handles `&`, it is not always safe to split selectors.

**Comment by DanielRuf** [comment]
> With the way Sass handles &, it is not always safe to split selectors.

I doubt this but I will check it then. Did you already do a `git bisect`?

**Comment by DanielRuf** [comment]
It's just the `  :last-child   &:not(.is-active) > &`, I'll revert this single line.

**Comment by DanielRuf** [comment]
Hm, was there a reason to remove `border-#{$global-left}-width: 0`?

**Comment by SassNinja** [comment]
> With the way Sass handles `&`, it is not always safe to split selectors. – @ncoden 

It's simply the result of having used the `&` selector wrongly.
By nesting `:not` in `:last-child` the scope has been changed and thus the result of the `&` changed too.

```scss
.accordion-title {
  
  :last-child:not(.is-active) > & {}
  // => :last-child:not(.is-active) > .accordion-title {}
  
  :last-child {
    &:not(.is-active) > & {}
  }
  // => .accordion-title :last-child:not(.is-active) > .accordion-title :last-child {}
}
```

But when you revert this I'd recommend to also make the selector more concrete.
Currently it (first) targets all `:last-child` elems on the page.
I think it would be better to use this instead 

```scss
.accordion-title {
	.accordion-item:last-child:not(.is-active) > & {}
}
```

**Comment by ncoden** [comment]
@SassNinja Yes this is the error I had in mind.

**Comment by jmartsch** [comment]
Thanks for fixing this so quickly :)

**Comment by technotip** [comment]
I'm using the latest version of mui and I still have this issue.

**Comment by DanielRuf** [comment]
> I'm using the latest version of mui and I still have this issue.

Hi, not sure if you mean material ui or foundation-sites. These are two totally different frontend frameworks and this repository here is for foundation-sites. Also I see no further mention of mui in this usse here.

**Comment by technotip** [comment]
Oh I'm extremely sorry. I didn't cross check it, my bad. I'm having this issue with latest mui version. I'll go check their site or git repo. Thank you ..
