### ISSUE TITLE
Inconsistent data attribute conventions

### ISSUE THREAD

**Issue by mindfullsilence** [zurb/foundation-sites#11446]
## What is missing?
[data-drilldown-menu]

## Why is it important?
There is an inconsistency in the naming convention for the data attributes of the various types of menus. To hook the javascript functionality for the 3 types of menus, we add the 
following data attributes: 

```
<ul data-accordion-menu>
<ul data-dropdown-menu>
<ul data-drilldown>
```

These should be consistent with each other, but drilldown does not have the -menu suffix.

## Possible Solution
Set data-drilldown as an alias to data-drilldown-menu for backwards compatibity, making data-drilldown-menu the preferred attribute, and warn of future deprecation. 

## Context
I have a select field in the CMS dashboard for selecting how a menu should be displayed that returns one of "drilldown", "dropdown", or "accordion". Without this discrepency, my html output could appear as:

```
<ul data-{{ display_type }}-menu class="menu {{display_type}}">
```

However because of the discrepancy, it becomes more like:

```
{% if display_type == 'drilldown' %}
<ul data-{{display_type}} class="menu {{display_type}}">
{% else %}
<ul data-{{display_type}}-menu class="menu {{display_type}}">
{% endif%}
```

## Your Environment
- Foundation version(s) used: 6.5.0-rc2

## Checklist (all required):
- [ x] I have read and follow the CONTRIBUTING.md document.
- [ x] There are no other issues similar to this one.
- [ x] The issue title is descriptive.
- [ x] The template is correctly filled.

**Comment by ncoden** [comment]
Hi @mindfullsilence. Despite the way we call it in the documentation, the name of the plugin is `Drilldown`. It would cost too much to change it with almost no benefits.

You could use an object instead to store Foundation plugin names according to your value `display_type`.
```js
const zfMenuPlugins = {
  accordion: "accordion-menu",
  dropdown: "dropdown-menu",
  drilldown: "drilldown",
}
```
