### ISSUE TITLE
I-11441: appearance: none; on input tags is not cross browser

### ISSUE THREAD

**Issue by aorinevo** [zurb/foundation-sites#11441]
## What should happen?
The appearance property is used to either add or remove styling of an element using a platform-native styling based on the users' operating system's theme.

This property is applied to search, text, password, etc... using the mixin exposed by `util/_selector.scss`.  

For instance, input tags with attribute`type` set to `search` in WebKit browsers will, by default, be rendered with rounded corners.  

When `$global-radius` or `$input-radius` is set to zero, input tags of type search should have 90 degree corners.

## What happens instead?

Input tags of type search have rounded corners on iOS devices.

## Possible Solution
Add cross-browser styling support for appearance:
```css
        -webkit-appearance: none;
        -moz-appearance: none;
        -o-appearance: none;
        appearance: none;
```

## Test Case and/or Steps to Reproduce

Test Case:

How to reproduce:
1.  Load foundation.min.css
2. Load foundation.min.js
3. Add input tag with type equal to search
4. Open page on iOS device
5. Observer round corners on search input

Alternatively, open https://jsfiddle.net/aorinevo/wLz9ovk1/3/ on an iOS device.

## Context

We have to add cross-browser appearance rules to our css.

## Your Environment

- Foundation version(s) used: 6.4.4-rc1
- Browser(s) name and version(s): Safari, iOS v11.4.1
- Operating System and version (desktop or mobile): mobile

## Checklist (all required):

- [x ] I have read and follow the CONTRIBUTING.md document.
- [x ] There are no other issues similar to this one.
- [x ] The issue title is descriptive.
- [x ] The template is correctly filled.

**Comment by ncoden** [comment]
> Foundation requires [Autoprefixer](https://github.com/postcss/autoprefixer) that will take care of all vender prefixes. See the [Sass installation documentation](https://foundation.zurb.com/sites/docs/sass.html#autoprefixer-required).

https://github.com/zurb/foundation-sites/pull/11442#pullrequestreview-145473304

**Comment by aorinevo** [comment]
Makes sense.  

Then there's still the separate issue of inputs of type search having rounded corners on iOS browsers.  

Should I open a separate issue for that?

**Comment by DanielRuf** [comment]
> Should I open a separate issue for that?

Yes, please open a new issue with a codepen.

**Comment by aorinevo** [comment]
Opened #11476
