### ISSUE TITLE
Tab component stopsPropagation on tab element click

### ISSUE THREAD

**Issue by alfuken** [zurb/foundation-sites#11457]
## What happens?
When you attach your own js events to elements that are used as tab switchers, your events will not be fired.

## What should happen instead?
Your events should be executed normally.

## Possible Solution
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.tabs.js#L162
Person who did this should be kicked in the nuts until they turn into an omelet, and then some more.
Also, remove all `.stopPropagation()` code from Foundation source. That smells.

## Context
I've spent 2 hours trying to figure out why my `$('.tab').on('click')` events are not firing. That's bloody ridiculous.

## Your Environment

- Foundation version(s) used: 6.2.4
- Browser(s) name and version(s): All JS capable browsers are affected
- Operating System and version (desktop or mobile): All JS capable browsers are affected

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by ncoden** [comment]
Hi @alfuken.

I agree with you, this is not a bad practice and we should get rid of it. This is not easy, it requires some cleaning and refactor, but this is something we should go to.

Until then, if you watch for clicks on tabs to detect changes in tabs, you can use the `change.zf.tabs` event.

I'll try to take care of this this weekend.

**Comment by ncoden** [comment]
@alfuken Fixed in https://github.com/zurb/foundation-sites/pull/11465

**Comment by alfuken** [comment]
Wow, that was fast. Thanks! 👍 Though I don't understand why it wasn't brought up for so long - this piece of code is there since the very beginning, I believe.

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/foundation-v6-6-1-v6-6-0-breaks-nested-dropdown-menus/1012/3
