### ISSUE TITLE
XY-Grid grid frame footer sticks to bottom and body content doesn't scroll

### ISSUE THREAD

**Issue by RyanSnodgrass** [zurb/foundation-sites#11459]
I'm trying to build a new greenfield app in line with the "Golden Layout" with a header, auto sizing body, and a footer that sticks to the bottom of the page and is pushed when body content extends past the page.

I assume my solution involves the grid-frame class. Here is the simple example that I found in one of Foundation's videos:
```html
<div class="grid-y grid-frame">
  <div class="cell shrink header">
  </div>
  <div class="cell auto body">
  </div>
  <div class="cell shrink footer">
  </div>
</div>
```
That looks great! Real simple- wrap the whole site in the grid frame and all the header and footer elements work properly.

But they don't.

What ends up happening is the content extends past the view and gets cut off without a scroll. In addition the footer is sticky but overlays ontop

<img width="780" alt="screen shot 2018-08-17 at 10 36 45 am" src="https://user-images.githubusercontent.com/7104855/44272246-4cffb800-a20a-11e8-894e-72115cbc241f.png">

The docs' only example is for independently scrolling margins and elements. I don't want that. I want a simple page that has a header, a footer, and content in the body that scrolls the whole window like a normal website.

I've created a [Codepen](https://codepen.io/ryansnodgrass/pen/vaomqm) to show the problem. The footer does stick to the bottom of the page, but I can't get it to be pushed when body content extends past the view. In addition, if body content extends past the view- it cuts off without a window scroll. In playing around I was able to get the footer to be pushed, but the window still doesn't scroll.

**Comment by ncoden** [comment]
Hi @RyanSnodgrass 👋,

The scroll issue has been already reported in https://github.com/zurb/foundation-sites/issues/10793 and fixed in https://github.com/zurb/foundation-sites/pull/11085. It should be availaible in Foundation 6.5 Release Candidate 2 (`v6.5.0-rc.2`).

If you do not want your Footer to stay under the Content when it is growing, then the XY Frame is not the good component for this use case and you should rather rely on the standard XY cell and a custom layout.

Does this help ?

**Comment by RyanSnodgrass** [comment]
@ncoden Thanks for responding. Looking again it looks like I was trying to make `.grid-frame` do something it's not meant to. 

I'll stop using `.grid-frame` and instead use this [css-tricks link](https://css-tricks.com/couple-takes-sticky-footer/) to get my footer sticky.

Thanks again

**Comment by DanielRuf** [comment]
Also see https://foundation.zurb.com/building-blocks/blocks/sticky-footer-css.html and https://foundation.zurb.com/building-blocks/
