### ISSUE TITLE
Foundation 6.5 Release

### ISSUE THREAD

**Issue by tsquez** [zurb/foundation-sites#11455]
Hi guys,

Just curious as to when we can expect the actual F6.5 to be released? 

Last I remember, it was slated for June release but the only thing released were the rc versions.

Just wanted to know is all. Thanks for all you do.

Keep being AWESOME!

**Comment by ncoden** [comment]
Hi @tsquez, 👋 

I am sorry, it took some time to stabilize the v6.5 version. There is some pull requests waiting for peer review (at least https://github.com/zurb/foundation-sites/pull/11445). Your review is welcome 😉 

Foundation v6.5.0 (stable) should be ready after that.
Thank you for your support !
