### ISSUE TITLE
Block Grid not working in Y-direction

### ISSUE THREAD

**Issue by joey-c** [zurb/foundation-sites#11463]
## What should happen?
Cells in a Grid-Y with [size]-up-[n] should be constrained appropriately.

## What happens instead?

Cells are displayed in a single column.

## Test Case and/or Steps to Reproduce
How to reproduce:
1. Use [CodePen provided in the docs](https://codepen.io/IamManchanda/pen/PjBLxE)
2. Change `grid-x grid-margin-x` to `grid-y grid-margin-y`

## Context
Trying to display two vertically stacked cells when the size is small, and horizontally otherwise.

## Your Environment
- Foundation version(s) used: 6.4
- Browser(s) name and version(s): Firefox 61.0.2 (64-bit)
- Operating System and version (desktop or mobile): macOS 10.12.6, Desktop

## Checklist (all required):
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by ncoden** [comment]
Hi @joey-c,

Thank you for your report. The documentation is incorrect. Block Grid is not supported for Y Grid and will not be implemented. It adds too much code for a feature that is will not be used in most projects.

I'll update the documentation. You can use the standard Y Grid with `[size]-[n]` at each cell instead.

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11464

**Comment by joey-c** [comment]
Thanks for the speedy update and explanation!
