### ISSUE TITLE
Accordion menu: disable the keyboard interaction?

### ISSUE THREAD

**Issue by lautiamkok** [zurb/foundation-sites#11479]
How can I **disable** the keyboard interaction with the [accordion menu][1]?

I can disable it in jQuery accordion in the following way:

```
      $('.accordion').accordion({
        heightStyle: "content",
        collapsible: true
      })
      $('.ui-accordion [role=tab]').unbind('keydown')
```

But I have no idea how to do so in Foundation. Any ideas? Something that can be done in Foundation?

  [1]: https://foundation.zurb.com/sites/docs/accordion-menu.html

**Comment by DanielRuf** [comment]
This is a bad idea as these are important accessibility features.

**Comment by ncoden** [comment]
Do not disable keyboard interaction on any component of your page. A lot of people can only navigate through your website this way.

**Comment by Esensats** [comment]
What if it conflicts with more important keyboard interactions, e.g. something like a Tags input inside an Accordion form. When you press `DownArrow` in hopes to trigger the combobox, it instead scrolls down to the next AccordionTrigger. The fact that we can't change the keybind to something else results not only in incredibly bad accessibility and UX, but also hinders functionality of other Radix components.

**Comment by DanielRuf** [comment]
@Esensats not sure what Radix components are.

Regarding other event listeners, you can prevent their propagation and bubbling (up and down) with the correct event handler settings.
