### ISSUE TITLE
run npm build - issue

### ISSUE THREAD

**Issue by julliechaumard** [zurb/foundation-sites#11473]
Hello,
I have an issue with **npm run build**.

- Error when copy files from src/assets to dist

OK => Finished 'clean' after 33 ms
**FAILED => Starting 'copy'...**
'images' errored after 951 ms
 Error in plugin 'gulp-imagemin:'

### _

> Message:
>     spawn /Users/julie/Documents/Web/Sites web/wopi/wp-content/themes/FoundationPress/node_modules/optipng-bin/vendor/optipng ENOENT
> Details:
>     code: ENOENT
>     errno: ENOENT
>     syscall: spawn /Users/julie/Documents/Web/Sites web/wopi/wp-content/themes/FoundationPress/node_modules/optipng-bin/vendor/optipng
>     path: /Users/julie/Documents/Web/Sites web/wopi/wp-content/themes/FoundationPress/node_modules/optipng-bin/vendor/optipng
>     spawnargs: -strip,all,-clobber,-force,-fix,-o,2,-out,/var/folders/jx/xkm2yysx39zgd54ymvlv_bj00000gn/T/05846c17-27e1-49ac-8977-a1d47a328bfe,/var/folders/jx/xkm2yysx39zgd54ymvlv_bj00000gn/T/3906ae9c-a4f5-4cc1-bd49-f0d38036102b
>     cmd: /Users/julie/Documents/Web/Sites web/wopi/wp-content/themes/FoundationPress/node_modules/optipng-bin/vendor/optipng -strip all -clobber -force -fix -o 2 -out /var/folders/jx/xkm2yysx39zgd54ymvlv_bj00000gn/T/05846c17-27e1-49ac-8977-a1d47a328bfe /var/folders/jx/xkm2yysx39zgd54ymvlv_bj00000gn/T/3906ae9c-a4f5-4cc1-bd49-f0d38036102b
>     fileName: /Users/julie/Documents/Web/Sites web/wopi/wp-content/themes/FoundationPress/src/assets/images/logo_odp.png
>     domainEmitter: [object Object]
>     domain: [object Object]
>     domainThrown: false

2 info using npm@3.10.10
3 info using node@v6.14.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle foundationpress@2.10.4~prebuild: foundationpress@2.10.4

Thank you for your help
Julie

**Comment by DanielRuf** [comment]
> Error in plugin 'gulp-imagemin:'

Not an error in Foundation Sites.

Please check and report at https://github.com/sindresorhus/gulp-imagemin/issues

**Comment by julliechaumard** [comment]
Hi Daniel, thank you for your answer.
In theme directory `FoundationPress/node_modules/optipng-bin`, there is no `vendor` directory. Do you know haw I can put it?

**Comment by DanielRuf** [comment]
I never had this issue or used this gulp plugin but there are some relevant issues: https://github.com/imagemin/optipng-bin/search?q=vendor&type=Issues

**Comment by DanielRuf** [comment]
https://github.com/imagemin/optipng-bin/issues/84

I suggest upgrading to Node.js 8 and npm 6.

**Comment by DanielRuf** [comment]
I guess https://github.com/olefredrik/FoundationPress/issues is better for your questions and support needs.
