### ISSUE TITLE
Input tag of type search displayed with rounded corners in iOS

### ISSUE THREAD

**Issue by aorinevo** [zurb/foundation-sites#11476]
## What should happen?

When $global-radius or $input-radius is set to zero, input tags of type search should have 90 degree corners.

## What happens instead?

Search input tags display with rounded corners on mobile iOS devices.

## Possible Solution

Add a css rule to target input boxes of type search that sets border radius to 0.

## Test Case and/or Steps to Reproduce

Test Case:

How to reproduce:
1. Load foundation.min.css
2. Load foundation.min.js
3. Add input tag with type equal to search
4. Open page on iOS device (make sure to use a physical device.  Chrome emulator does not show rounded corners).
5. Observe rounded corners on search input
Alternatively, open https://jsfiddle.net/aorinevo/wLz9ovk1/3/ on an iOS device.

## Context

Project teams using foundation need to add css rules for search inputs to control the border radius.

## Your Environment

- Foundation version(s) used: 6.4.4-rc1
- Browser(s) name and version(s): Safari, iOS v11.4.1
- Operating System and version (desktop or mobile): mobile

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
Please try 6.5.0 RC 2

https://jsfiddle.net/qtcbhud7/
https://codepen.io/DanielRuf/pen/BOKBqv

**Comment by DanielRuf** [comment]
Your jsfiddle uses 6.2.4.

**Comment by aorinevo** [comment]
I am able to reproduce the in version 6.4.3 (see https://jsfiddle.net/aorinevo/187qa04n/).  Same for 6.4.4-rc1.

**Comment by DanielRuf** [comment]
> Please try 6.5.0 RC 2

**Comment by DanielRuf** [comment]
> see jsfiddle.net/aorinevo/187qa04n

This still uses 6.2.4. Did you save the changes?

**Comment by aorinevo** [comment]
I didn't save it with the updated url for 6.4.3. 

I am still able to reproduce in 6.4.4-rc1, but it's an rc version.  

Closing this issue.
