### ISSUE TITLE
Running "foundation new" installs wrong boilerplate code. 

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#11489]
## What should happen?
Calling `foundation new` should create a new foundation for sites project. 

## What happens instead?
A foundation for apps project was created (or some old boilerplate). 

## Test Case and/or Steps to Reproduce (for bugs)
How to reproduce:
1. Follow the instructions to install foundation for sites with the foundation-cli 
2. Call `foundation new`
3. Check the code 

## Your Environment
Win 10 Pro with WSL 

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one. (I found this one in the foundation-cli repository: https://github.com/zurb/foundation-cli/issues/106) 
- [x] The issue title and template are correctly filled.

**Comment by phifa** [comment]
exactly this: 
https://github.com/zurb/foundation-cli/issues/106

**Comment by SassNinja** [comment]
@phifa please don't remove the issue template but fill it out when creating a new issue

https://github.com/zurb/foundation-sites/issues/new?template=1-bug-report.md

**Comment by phifa** [comment]
@SassNinja i updated the issue, you can reopen

**Comment by DaveLivesey-Salience** [comment]
@phifa @SassNinja I'm also having this issue - will this issue be reopened?

**Comment by DanielRuf** [comment]
Can you clarify which options you took?

**Comment by DanielRuf** [comment]
I've got 6.4.3 with the current cli.

**Comment by DaveLivesey-Salience** [comment]
-`foundation new`
- Selected `A Website`
- Entered desired project name
- Selected `ZURB Template: includes Handlebars templates and Sass/JS compilers`
(Also pulls Foundation for Apps if `Basic Template: includes a Sass compiler` is selected, email projects load the correct boiler plate).

I'm running:
node (8.9.4)
npm (6.3.0)
gulp (3.9.1 - cli version)
bower (1.8.4)
foundation-cli (2.2.5)

**Comment by DanielRuf** [comment]
```
➜  foundation-test foundation new
? What are you building today? A website (Foundation for Sites)
? What's the project called? (no spaces) test-project
? Which template would you like to use? ZURB Template: includes Handlebars templates and Sass/JS compilers

            .
           /|     ,
      , /|/  \/| /|       Thanks for using ZURB Foundation for Sites!
     /|/       |/ |       -------------------------------------------
 |___|            |___|   Let's set up a new project.
 \___|  ^^   ^^   |___/   It shouldn't take more than a minute.
     | -[O]--[O]- |
     |    ___,    |
     |    ...     |
      \__________/


Downloading the project template...
Done downloading!

Installing dependencies...
```

```
yarn list --depth=0 --pattern foundation-sites
yarn list v1.9.4
└─ foundation-sites@6.4.3
```

```
npm ls foundation-sites
foundation-zurb-template@1.0.0 /Users/druf/projects/foundation-test/test-project
└── foundation-sites@6.4.3 
```

**Comment by DanielRuf** [comment]
Not reproducible on macOS so far. Can you both try to uninstall and reinstall the foundation-cli?

**Comment by DanielRuf** [comment]
The list commands show nothing for `foundation-apps`.

**Comment by DaveLivesey-Salience** [comment]
I've uninstalled, installed latest version, rolled back to 2.0.0, setup everything from scratch on a clean machine, every time the outcome is the same.

**Comment by DanielRuf** [comment]
> setup everything from scratch on a clean machine

Was the npm cache cleared or were it really clean machines without prior npm install?

**Comment by DanielRuf** [comment]
We use Node.js 10.6.0 and npm 6.4.1 / Yarn 1.9.4.

**Comment by DaveLivesey-Salience** [comment]
It was an absolutely clean machine - fresh MacOS install.

**Comment by DanielRuf** [comment]
Can you share the generated package.json + package-lock.json and the output when you create a new test project?

**Comment by DaveLivesey-Salience** [comment]
From a new sites project using ZURB template:
[package-lock.txt](https://github.com/zurb/foundation-sites/files/2371059/package-lock.txt)
[package.txt](https://github.com/zurb/foundation-sites/files/2371060/package.txt)

**Comment by DanielRuf** [comment]
There is only foundation-sites in there and the files look fine.

```
"foundation-sites": {
      "version": "6.4.3",

```

**Comment by DanielRuf** [comment]
Where do you see `foundation-apps`?

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-zurb-template/tree/master/src/pages

**Comment by DanielRuf** [comment]
So this is correct ;-)

**Comment by DanielRuf** [comment]
This one has no templates: https://github.com/zurb/foundation-sites-template

**Comment by DaveLivesey-Salience** [comment]
Hmmm... think it's just thrown me as everything changed without any warning 😂 thanks so much for your time.

**Comment by DanielRuf** [comment]
Keep in mind that foundation-sites is the new Foundation and is also the new foundation-apps.
https://github.com/zurb/foundation-zurb-template/commit/61426143fbe4a6606786dcf49fdb209d03d289d2

https://github.com/zurb/foundation-apps#deprecation-notice

**Comment by DanielRuf** [comment]
I'll close here as everything seems fine here. At least the dependencies and examples are correct so far (but there is no info about the changes).

cc @rafibomb

**Comment by phifa** [comment]
Well, I dont get this. Why are dashboard and all these libraries now in the template? 

for example this was not in there before: 
```
import AOS from 'aos';
import svgInjector from 'svg-injector-2';
import slick from 'slick-carousel';
```

Now when I set up a new foundation project I have to first uninstall a bunch of things. This must have been added recently as I create new projects fairly often.

**Comment by DaveLivesey-Salience** [comment]
I did like the lightweight nature of the previous incarnation - now it just feels like it's making more work to get a project spooled up.

**Comment by DanielRuf** [comment]
> Well, I dont get this. Why are dashboard and all these libraries now in the template?

This is a question for @rafibomb and the rest at @zurb ;-)

**Comment by DanielRuf** [comment]
> Now when I set up a new foundation project I have to first uninstall a bunch of things. This must have been added recently as I create new projects fairly often.

See https://github.com/zurb/foundation-zurb-template/commit/61426143fbe4a6606786dcf49fdb209d03d289d2 and previous commits.

**Comment by phifa** [comment]
Looks like this got fixed here 
https://github.com/zurb/foundation-zurb-template/commit/2cdc469d947a3ecea8b50fc0c74687e75f4dcd4b
