### ISSUE TITLE
Accordion Menu (is-active) bug? - F6

### ISSUE THREAD

**Issue by jinch** [zurb/foundation-sites#11480]
## What should happen?

When using the .is-active class on a nested menu inside an accordion-menu, it should remain open.

## What happens instead?

I am noticing that the .is-active class is removed if you click the accordion-menu closed, than re-open it. This in turn closes all nested menues and does not retain the is-active state.

## Possible Solution

Perhaps custom Javascript will be needed to force the .is-active class to remain even after an accordion menu is closed?

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/jinch/pen/aamzYa?editors=1010

How to reproduce:
1. Click to open the Accordion Menu
2. Notice the Nested Menu that is OPEN
3. Click to close the Accordion Menu
4. Click to open the Accordion Menu Again
5. Notice the Nested Menu that was once OPEN is now CLOSED

## Context

This is a secondary navigation for me and I would like to open the menu and display a marker as to the page the visitor is currently on. This is why I was hoping to use the active class to help the UI and highlight it in a menu once it is opened.

## Your Environment

- Foundation version(s) used: 6.3.1
- Browser(s) name and version(s): Chrome Version 68.0.3440.10
- Device, Operating System and version: Mac Mini, Mac OS High Siera
- Link to your project: https://codepen.io/jinch/pen/aamzYa?editors=1010

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
In general by adding the `is-active` to the path. The `down` method does not really work here.

https://codepen.io/DanielRuf/pen/PdGjMg?editors=1010

**Comment by DanielRuf** [comment]
I had a similar issue, see https://github.com/zurb/foundation-sites/issues/10671

`parentsUntil` might be helpful here: https://api.jquery.com/parentsUntil/

**Comment by ncoden** [comment]
Hi @jinch,

An Accordion Menu item, like in all Foundation menus, is considered as "opened" _because_ `is-active` is set. If all sub-menus should be closed when the main menu is closed, then those with `is-active` initially set are threated like others and should be closed too.

So this is not a bug, this is the expected behavior. However, we could add an option to keep the sub-menu opened when the main menu is closed.
