### ISSUE TITLE
Drilldown menu does not work with latest version of Google Chrome

### ISSUE THREAD

**Issue by luigiedil** [zurb/foundation-sites#11504]
## What should happen?

The second menu should be visible when I click on list item. The first menu will be hidden, and the second should go over the first.  

## What happens instead?

Drilldown menu does not working well with the latest version of Google Chrome. The first menù is ever visible, even if I click an item. So menu and his submenu go in overlap.

## Possible Solution

Maybe something class are not correctly added in submenu DOM element.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/IamManchanda/pen/JNZodd?editors=1000
You can test this problem in official foundation documentation and his related codepen

## How to reproduce:
1. Create a drilldown menu with Foundation
2. Test with Google Chrome version 69.0.3497.92

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): Google Chrome 69.0.3497.92 (64 bit)
- Device, Operating System and version:  Mac, iOS, Android and Windows
- Link to your project: -

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by kejSirio** [comment]
I have the same problem on my site

Any advice to solve the problem?

**Comment by heyflo** [comment]
Download the latest version of Chrome, they fixed it.

**Comment by luigiedil** [comment]
Yes @heyflo it works with Google Chrome 69.0.3497.100 (64 bit)
Thanks!

**Comment by heyflo** [comment]
No problem @luigiedil we had a lot of our sites impacted here, it was because they did mess up with the z-index attribute.
