### ISSUE TITLE
[Smooth Scroll] Prevents navigation to relative or absolute urls

### ISSUE THREAD

**Issue by rzontar** [zurb/foundation-sites#11506]
## What should happen?
Smooth Scroll should only apply to anchor tags with a href attribute starting with '#'. If you provide an absolute or relative url instead, the plugin should not prevent the browser's navigation to that url.

## What happens instead?
The click event handler prevents the event and the browser doesn't navigate away. This affects all anchor tags inside a container marked with the `data-smooth-scroll` attribute.

## Possible Solution

https://github.com/zurb/foundation-sites/blob/26aad1140820275e48d48676f5d5b4e09a127192/js/foundation.smoothScroll.js#L53

Returning false from an event handler prevents the default action for that event and stops the event bubbling up the DOM. In this case it prevents the browser navigating to another url.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/anon/pen/EedJEr

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): all
- Device, Operating System and version: all
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
Hi @rzontar :wave:,

Thank you for your issue. It makes sense to me and we could consider this as a bug:   SmoothScroll only makes sense on internal anchors but it affects (and break) other types of links.

We try to remove `.stopPropagation()` from Foundation as it is a bad practice and may prevent the user to listen to events (see https://github.com/zurb/foundation-sites/pull/11465). We should replace this `return false;` by a simple `.preventDefault()`.

**Comment by ncoden** [comment]
Fixed in https://github.com/zurb/foundation-sites/pull/11510. It should be availaible in `v6.5.0` soon.
