### ISSUE TITLE
[XY Grid] Gutters apply only if they are in the breakpoint mixin

### ISSUE THREAD

**Issue by geosigno** [zurb/foundation-sites#11507]
Follow up of [#10743](https://github.com/zurb/foundation-sites/issues/10743)

Let's say I have this block:

```
.block {
  @include xy-cell(6);
}
```

and my grid gutters are like this:

```
$grid-margin-gutters: (
    small: 48px,
    medium: 64px,
    large: 96px;
    xlarge: 24px
);
```

The gutter will be set to 24px on each side (small 48px / 2) in all breakpoints. It shouldn't be the case, every breakpoint should have it's own gutter. The only way I can achieve this right now is:

```
.block {
  @include xy-cell(6);
  @include breakpoint(medium) {
    @include xy-cell(6);
  }
  @include breakpoint(large) {
    @include xy-cell(6);
  }
  @include breakpoint(xlarge) {
    @include xy-cell(6);
  }
}
```
This way, on large breakpoint for example, my gutters will be set to 48px on each side (large 96px / 2)
This is a lot of unnecessary code here. Am i missing something here? 

I'm not sure if it is a bug of a feature request.

**Comment by ncoden** [comment]
Hi @geosenna,

Thank you for your issue. We had the expected behavior in the standard Grid but it got lost (or forgotten) in the XY Grid. This is not a bug, we simply don't expect a simple cell to generate gutters for all breakpoints.

I recently reworked the XY cell interface at https://github.com/zurb/foundation-sites/pull/11405, and will add a way to generate all gutters (for example with `$breakpoint: auto` or `$breakpoint: all`).

For now you can use:
```scss
.block {
  @include xy-cell(6, $gutter-output: false);
  @include xy-gutters();
}
```

**Comment by geosenna** [comment]
Thanks @ncoden, that mixin xy-gutters saves me :)

**Comment by ncoden** [comment]
> Your rework will be added in 6.5 release?

This is a new feature and maybe a change in the API so no it will be availaible in v6.6.0

**Comment by peterwcm** [comment]
```
.block {
  @include xy-cell(full, $gutter-output: false);
  @include xy-gutters();
}
```
note: while @ncoden solution can generate responsive gutters for an element, it doesn't re-calculate the calc width (depends on margin) when `full` is used for the size.

**Comment by jreynolds13** [comment]
@ncoden @peterwcm
> note: while @ncoden solution can generate responsive gutters for an element, it doesn't re-calculate the calc width (depends on margin) for larger breakpoints
Gah! Any way to achieve the width re-calc before 6.6 drops with the full fix? This single issue is preventing me from using semantic grids unless I alter settings to have a single gutter width for all breakpoints.

**Comment by durchanek** [comment]
Not perfect but prevents the unnecessary code before 6.6 is out:

```scss
// I do not need any extra options besides $gutter-type
@mixin xy-responsive-cell($small-width, $medium-width, $large-width, $gutter-type: margin) {
  @include breakpoint(small down) {
    @include xy-cell($small-width, $gutter-type: $gutter-type);
  }
  @include breakpoint(medium only) {
    @include xy-cell($medium-width, $gutter-type: $gutter-type);
  }
  @include breakpoint(large up) {
    @include xy-cell($large-width, $gutter-type: $gutter-type);
  }
}
```

**Comment by DanielRuf** [comment]
Hi @durchanek,

It's currently planned for v7.

**Comment by geosigno** [comment]
is anything change with the 6.6.0 release?

**Comment by DanielRuf** [comment]
> It's currently planned for v7.

I would say this is still the case.

**Comment by geosigno** [comment]
I'm a bit lost with the new 6.6.0 version. How to manage a very simple grid with responsive gutters?

sass file:
```
.box--big {
  @include xy-cell(12);
}
.box--medium {
  @include xy-cell(6);
}
```

setting.scss
```
$grid-margin-gutters: (
    small: 32px,
    medium: 48px,
    large: 64px,
);
```

With the above I only get the small gutter apply on all resolution. I tried to played with the xy-gutters(); but nothing conclusive.

I'm still a bit surprised that a so simple grid is that complex to manage via sass mixins. I couldn't find anything in the doc.

**Comment by DanielRuf** [comment]
> I'm a bit lost with the new 6.6.0 version. How to manage a very simple grid with responsive gutters?

Can you show me the css file that you use? Is it from some CDN?

https://github.com/foundation/foundation-sites/blob/develop/scss/xy-grid/_cell.scss#L43

Maybe you can debug with `@debug`.

See https://github.com/foundation/foundation-sites/blob/develop/scss/xy-grid/_cell.scss#L206

```
/// @param {String} $breakpoint [null] - The name of the breakpoint size in your gutters map to get the size from. If `auto`, generates responsive gutters. If using with the `breakpoint()` mixin this will be set automatically unless manually entered.
/// @param {Boolean} $vertical [false] - Set to true to output vertical (height) styles rather than widths.
/// @param {List} $output [(base size gutters)] - Cell parts to output. You will need to generate others parts of the cell seperately, it may not work properly otherwise.
@mixin xy-cell(
  $size: full,
  $gutter-output: null,
  $gutters: $grid-margin-gutters,
  $gutter-type: margin,
  $gutter-position: null,
  $breakpoint: null,
  $vertical: false,
  $output: (base size gutters)
) {
```

So you may want to use it with the `breakpoint()` mixin or set `auto` or statically define the needed `breakpoint`.

**Comment by geosigno** [comment]
I omitted the $breakpoint... thanks :)
