### ISSUE TITLE
Is `foundation-cli` abandonware?

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation-sites#11511]
title

**Comment by ncoden** [comment]
If you consider as `abandonware` a software on which nobody planed to work for future bugfixes or improvements, then no it is not. I am just focusing right now on `foundation-docs`. But as soon as a stable version of v6.5.0 is released, I will take a look at the issues, like `foundation-rails`, `foundation-zurb-template` and `foundation-sites-template`.
