### ISSUE TITLE
Foundation Sites Node Modules are not transpiled from ES6 to ES5 which breaks in IE 11

### ISSUE THREAD

**Issue by sthennarasan** [zurb/foundation-sites#11514]
## What should happen?
Foundation node modules which are in ES6 javascript is not transpiled to ES5 which breaks in IE 11
...

## What happens instead?
In IE 11, we still see template literals and other ES6 features. 
...

## Possible Solution

 foundation-sites should build and give the es5 version of javascript in the node modules
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Check out the website in IE 11, https://www.soaplush.com/, will get invalid character error for backtick symbol `

## Context

Due to the problem, the site does not open in IE 11
...

## Your Environment

- Foundation version(s) used: "foundation-sites": "6.4.3", Ruby on Rails
- Browser(s) name and version(s): IE 11
- Device, Operating System and version: Windows OS
- Link to your project: https://www.soaplush.com/

## Checklist

- [ x] I have read and follow the CONTRIBUTING.md document.
- [x ] There are no other issues similar to this one.
- [x ] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
Hi @sthennarasan 👋 

Thank you thank your issue. This is fixed in v6.5.0-rc.1. Since v6.5.0-rc.4, all entries (even for rollup/webpack) are transpiled. See https://github.com/zurb/foundation-sites/pull/11508.

**Comment by sthennarasan** [comment]
Hi @ncoden, Cool, Will use v6.5.0-rc.1 and check. Thanks for the update!
