### ISSUE TITLE
Accordion anchors' ID attributes get overwritten

### ISSUE THREAD

**Issue by lcichanowicz** [zurb/foundation-sites#11513]
## What should happen?

If I specify the anchor IDs, for each accordion "pane", Foundation should not change them.

## What happens instead?

When I specify the anchor IDs, for each accordion "pane", Foundation changes them, in one of two ways that I've discovered.

1. If the anchor's parent list item has an ID set, Foundation sets the child anchor's ID to the same value.  This is illegal/invalid HTML.  IDs must be unique for the entire document.  Worse, Foundation does this even when I have an ID already set on the anchor.  In other words, Foundation changes my anchor elements' IDs.

2. If the anchor's parent list item does not have an ID set, Foundation sets the child anchor's ID to a "generated" value.  This is problematic, because the anchor's ID will change over time, depending on server-side and client-side caching.  Worse, again, Foundation does this even when I have an ID already set on the anchor.  In other words, Foundation changes my anchor elements' IDs.

Here is the code I suspect to be the issue:
![image](https://user-images.githubusercontent.com/4871064/45963523-56dabf00-bff1-11e8-84e3-cff9a348119d.png)

This seems to be related to:
https://github.com/zurb/foundation-sites/issues/7923

**Comment by tayler-ramsay** [comment]
@lcichanowicz found this #10871  looks like and update is on its way in 6.5. But for now you can just make the update to the accoridion plugin.
https://github.com/zurb/foundation-sites/pull/10871/files

**Comment by lcichanowicz** [comment]
Thanks, @tayler-ramsay.  I was hesitant to modify the code when I found it, because it is "processed" by webpack.  I updated that very line of code, and it works!  Foundation no longer overwrites my anchors' IDs.
