### ISSUE TITLE
Regression: Accordion scrolls to first anchor even if no deeplink was supplied

### ISSUE THREAD

**Issue by jnns** [zurb/foundation-sites#11527]
## What should happen?

When an accordion is created with `data-deep-link=true data-deep-link-smudge` and no deep link is supplied, there should not be any automatic scrolling.

## What happens instead?

The active tab is scrolled into view even though no deep link has been supplied.

## Possible Solution

It seems to me that this bug has been introduced by https://github.com/zurb/foundation-sites/pull/11477 while fixing the return to the initial state. After this fix Foundation goes to the initial tab on page load but this hasn't been the case before.  

## Test Case and/or Steps to Reproduce (for bugs)

It wasn't possible for me to create a codepen because the URL hashes seem to not get passed down to the sandbox that the code examples are running in. Still, you can go to [Foundation's current Accordion documentation pages](https://foundation.zurb.com/sites/docs/accordion.html) (note that there's no deep link [i.e. hash]) and see that a scrolling animation is triggered for every accordion on that page. 

A minimal working example can be obtained [here](https://gist.github.com/jnns/39fbf3f1ee3aeda0ccabad64c27ac8db). 

## Context

We're using Accordions to display a table of content at the bottom of our index page and since 6.5.0-rc3 the viewport is automatically scrolled down to the accordion, hiding the header of the page.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
Hi @jnns 👋,

Thank you for your issue. I noticed that we have the same bug on the Tabs page. This definitely comes from #11477. I'll take a look at it.

**Comment by ncoden** [comment]
@jnns See https://github.com/zurb/foundation-sites/pull/11530.
