### ISSUE TITLE
Dead Link on Installation Integrations (Vue)

### ISSUE THREAD

**Issue by Some-Guy-from-Canada** [zurb/foundation-sites#11520]
Link to learn more about the Vue integration does not work. There was no issue with the links for Angular, React, or Wordpress. I'm sure it's an easy fix. Thanks.
[https://foundation.zurb.com/sites/docs/](url)

**Comment by SassNinja** [comment]
@Some-Guy-from-Canada don't delete the issue template!

Please open a new ticket and fill the template
https://github.com/zurb/foundation-sites/issues/new/choose
