### ISSUE TITLE
[Magellan] Active class isn't added when scrolling

### ISSUE THREAD

**Issue by diniscorreia** [zurb/foundation-sites#11524]
On 6.4.3, the active class is only added to Magellan links when clicking on them – scrolling through the page doesn't add the class. 

[Example on CodePen.](https://codepen.io/diniscorreia/pen/QZKBLb?editors=1010)

I don't really get what's causing the issue, but it seems that `data-events="scroll"` isn't being added to the Magellan element.

**Comment by DanielRuf** [comment]
Please test it with the `is-active` class: https://codepen.io/DanielRuf/pen/EdgpOe

**Comment by DanielRuf** [comment]
I guess we might have fixed the async initialization issues in the latest RC release.
