### ISSUE TITLE
webkit style from normalize overrides button style in chrome and safari

### ISSUE THREAD

**Issue by siwood** [zurb/foundation-sites#11539]
## What should happen?

When you add the out-of-the box "button" class to an element that has type="button", you should see the default Zurb button style (blue with white text.) 

## What happens instead?

In some bowsers (chrome and safari), the -webkit-appearance: button style overrides the .button style and makes the buttons look silver with white text.  This does not happen in Firefox.

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: <https://codepen.io/anon/pen/MPrqdR>

How to reproduce:
1. Open the codepen example in Firefox
2. Open the codepen example in Safari
3. Open the codepen example in Chrome
4. Compare the appearances of the button

## Context

Rather than being able to use the out-of-the-box zurb component with cross-browser consistency, I have to overwrite the -webkit-appearance attribute in my custom theme.

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): Chrome 69.0.3497.100, Safari 12.0 (13606.2.11), Firefox 62.0.3 (64-bit)
- Device, Operating System and version: MacOS High Sierra 10.13.6

## Checklist

- [X ] I have read and follow the CONTRIBUTING.md document.
- [ X] There are no other issues similar to this one.
- [ X] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
Hi @siwood 👋, thank you for the issue.

This is already fixed in the latest versions of Foundation, with updates of Normalize. See https://codepen.io/ncoden/pen/XxVOLM.
