### ISSUE TITLE
scrollme.zf.trigger not working in F6 Template Build

### ISSUE THREAD

**Issue by logopogo** [zurb/foundation-sites#11533]
## What should happen?

scrollme.zf.trigger should fire

## What happens instead?

scrollme.zf.trigger doesn't fire

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

With Foundation 6.4.3 using the CLI Framework/Template build, with all JS included in the build, I'm finding the 'scrollme.zf.trigger' doesn't fire.

Here is a Pen with my set up and linking to the template build of the Foundation JS:

The code should output the window scroll offset value to the console on window scroll event.

https://codepen.io/logopogo/pen/mGxzMb

Here is an identical Pen but switching out the built JS for a CDN version:

https://codepen.io/logopogo/pen/dqeeqJ

The CDN version works as expected but the Template Build does not.
I haven't modified any of the JS supplied with the template framework and am including all components in the build process.

How to reproduce:
1.
2.
3.

## Context

Just trying to have the same framework functionality when using the build template/stack as I had with the direct CDN version.

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): n/a
- Device, Operating System and version: n/a 
- Link to your project: as above

## Checklist

- [x] There are no other issues similar to this one.
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
Hi @logopogo 👋,

You forgot to include jQuery in your CodePen.
I added jQuery and upgraded to the latest beta version of Foundation (v6.5.0-rc.4), and `scrollme.zf.trigger` is correctly triggered. See https://codepen.io/ncoden/pen/OBzGyb?editors=1111

**Comment by ncoden** [comment]
Hi @logopogo 👋,

Could you share your template configurations files (or the whole repo) ? Globaly, if it works on the CDN, then it should works with the template. Otherwise, something is wrong with the build process.

**Comment by SassNinja** [comment]
> Globaly, if it works on the CDN, then it should works with the template.

That's exactly what I thought.

@logopogo we need to see your entry point and/or the relevant files (before starting your webpack build). Your `app_copy.js` is not easy to debug.

**Comment by logopogo** [comment]
Hi @ncoden .
So I started a new, clean template build and tested the output and the JS worked fine.
When comparing my previous setup to the new one all the config files were quite different... so not sure what was happening there. But all good now.
Thanks for pointing me in the right direction.

**Comment by SassNinja** [comment]
> But all good now.

Good to hear :)
