### ISSUE TITLE
Separate Modules Into Different Packages via Lerna

### ISSUE THREAD

**Issue by KnightYoshi** [zurb/foundation-sites#11537]
Have you considered splitting the project into multiple and manage it with Lerna so that it's cleaner?
You could then namespace Foundation on NPM `@foundation-sites/esm`, `@foundation-sites/cjs`, `@foundation-sites/es6`. Effectively they're independent code bases and this would make more sense.

Babel is a prime example and does this for all of their projects starting with Babel 7. I think it's a better move long term for management. 

With regards to Babel 7+ they use a namespace structure
```
{
"devDependencies": {
	"@babel/core": "7.1.0",
	"@babel/plugin-proposal-class-properties": "7.1.0",
	"@babel/plugin-proposal-export-namespace-from": "7.0.0",
	"@babel/plugin-proposal-object-rest-spread": "7.0.0",
	"@babel/plugin-syntax-dynamic-import": "^7.0.0",
	"@babel/plugin-transform-modules-commonjs": "7.1.0",
	"@babel/preset-env": "^7.1.0",
}
```

https://lernajs.io/

**Comment by KnightYoshi** [comment]
Hmm. Okay, I looked at the source for 6.5-rc4. It's the `/dist` directory that has the different builds.

So it applies less to that, but going forward for having different builds as mentioned in the past for vanilla JS/ES6, jQuery, Vue, React, Angular, and whatever else, this would still be the practical approach imo.

**Comment by ncoden** [comment]
Hi @KnightYoshi 👋 ! Thank you for the suggestion.

Like you said, this doesn't apply to us because we don't have different _codebase_ but only different _distributions_ that are generated together. So there would be no benefits in terms of maintainance or clarity.

Actually, this would add work, confusion, and require a migration for all projects relying on migration.

But I stay open to the idea, if we find real reasons to do it.

**Comment by DanielRuf** [comment]
In general I would also prefer Yarn workspaces / monorepo instead of something special like lerna which has its own flaws.

**Comment by DanielRuf** [comment]
Also the drama with jamiebuilds and how the maintainers reacted was not a great experience: https://github.com/lerna/lerna/pull/1633

**Comment by KnightYoshi** [comment]
Yeah, I don't really see that as being much of an issue. It was one guy that went rouge and was quickly rolled back.

Lerna isn't too special/complicated and is used to manage monorepos: [Monorepos By Example: Part 1](https://codeburst.io/monorepos-by-example-part-1-3a883b49047e)
