### ISSUE TITLE
Slider Data Binding does not trigger input change function

### ISSUE THREAD

**Issue by jinch** [zurb/foundation-sites#11534]
## What is missing?

On the slider component when using data binding (https://foundation.zurb.com/sites/docs/slider.html#data-binding) I noticed that although the input value updates, for some reason it does not register a change function of the input when adjusting the slider. **_Ideally it would be great to have away to have a change function be bound to both the slider and the input._**

CodePen demonstrating the issue:
https://codepen.io/jinch/pen/WajvGE
...

## What is wrong now ?

I have code to disable a select dropdown if the input value reaches a certain number. This works but only works if you make the change in the input field / does not work when adjust the slider.
...

## Possible Solution

From the docs it looks like you can monitor the slider change with the "moved.zf.slider" event however this does not seem to work in hooking the input value.
...

## Context

I hope to make a measurement slider with set fractions that are only displayed on certain values.
...

## Your Environment

- Foundation version(s) used: 6.3.1
- Browser(s) name and version(s): Chrome (Version 69.0.3497.100)
- Device, Operating System and version: Mac Mini, macOS High Sierra

## Checklist

- [X ] I have read and follow the CONTRIBUTING.md document.
- [ X] here are no other issues similar to this one.
- [ X] The issue title and template are correctly filled.

**Comment by jinch** [comment]
Scratch... 

I figured out the work around by targeting the .slider-handle attribute "aria-valuenow".
Example: https://codepen.io/jinch/pen/Lgjzoo?editors=10

This is not so much a bug as just bad code on my part.
Apologies for that.

Not sure if this is the most straight forward way to achieve this but it seems to work.

**Comment by ncoden** [comment]
Hi @jinch :wave:,

This is not a bug. This is not up to Foundation to trigger the `change` event on the input when we modify its value. It's actually dangerous as it has side effects (change is a generic browser event) can easily lead to infinite loop.

What you can do otherwise is listening to the `changed.zf.slider` event on the slider instead, then do your stuff. This works with `moved.zf.slider` too, like in your 2nd codepen.
