### ISSUE TITLE
Mixin Parse error: $breadcrumbs-item-separator-item-rtl using leafo/scssphp

### ISSUE THREAD

**Issue by zzplab** [zurb/foundation-sites#11557]
## What should happen?
I'm using https://github.com/leafo/scssphp to compile the foundation scss.
I get the final css properly rendered.

## What happens instead?

Parse error with mixin for components > breadcrumbs:
```
Parse error: parse error: failed at `$breadcrumbs-item-separator-item-rtl: '\\' !default;` components/_breadcrumbs.scss on line 52
```
## Possible Solution

If I change it to this, it works fine:
```
$breadcrumbs-item-separator-item-rtl: "\\" !default;
```
I can always adjust it myself, but would be great if it can be solved in the Foundation mixin.
Same fragment is in _settings file too.
I know foundation explicitly changed to single quotes, but these give different results:
```'\\' != "\\"```

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Your Environment

- Foundation version(s) used: 6.5.0
- Browser(s) name and version(s): Safari 12
- Device, Operating System and version: Mac
- Link to your project: compiled by scssphp v0.7.6 
## Checklist

- [ x] I have read and follow the CONTRIBUTING.md document.
- [ x] There are no other issues similar to this one.
- [x ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
`_settings` is generated from the other files for each release

**Comment by ncoden** [comment]
Related to https://github.com/zurb/foundation-sites/issues/7204

I would agree with @gakimball that said the following 3 years ago:
> Unfortunately the only two Sass compilers we support are Ruby Sass and Libsass. There is a PHP port of Libsass, but it doesn't appear to be under active development.
>
> I would report this issue to the scssphp developers, as the behavior is inconsistent with Ruby Sass.

There is enough difficulties with trying to support both RubySass, libSass and now Dart Sass. We cannot add to this scssphp. Our Sass code is valid, please report the issue to scssphp (poke @robocoder).

**Comment by ncoden** [comment]
Won't fix. Closing.
