### ISSUE TITLE
Grid with overlapping cell in Flexbox

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#11552]
I am using the flexbox grid and I want to create the following structure:
![grid](https://user-images.githubusercontent.com/3159095/47295504-12523b80-d610-11e8-84e9-69f955ee70f0.png)

I haven't found any documentation as to how to stretch that one cell over two heights so I tried to have one row with left and right cells. The left one holds 4 images via grid and the right one holds a row with two cells - first one holds the stretched image and the second one holds the last two images.

I was able to achieve the look but the horizontal spacing is off and does not align for all images, which makes sense since the cells are not in one single row.

Is it possible to somehow achieve this grid "properly"?

**Comment by DanielRuf** [comment]
In general these are 4 columns, 3 x 6 / 6 y-grid and 1 x 12 y-grid.

**Comment by lkraav** [comment]
@ivanjaros did you come up with a solution on your own, or?

**Comment by ncoden** [comment]
@ivanjaros Daniel described how to do it with the XY Grid:

```
|     |     |     |     |
|     |     |     |     |
|  6  |  6  |     |  6  |
|     |     |     |     |
| --- | --- |  12 | --- |
|     |     |     |     |
|  6  |  6  |     |  6  |
|     |     |     |     |
|     |     |     |     |
```

**Comment by ivanjaros** [comment]
@ncoden was I talking about XY grid?

FYI: @lkraav I ended up using css grid(https://www.w3schools.com/css/css_grid.asp).
