### ISSUE TITLE
@mixin breakpoint > Parse error: Undefined variable $str: line: -1

### ISSUE THREAD

**Issue by zzplab** [zurb/foundation-sites#11556]
## What should happen?

I'm using https://github.com/leafo/scssphp to compile the foundation scss.
I get the final css properly rendered.

## What happens instead?

I get the error:
Parse error: Undefined variable $str: line: -1

I can relate that to the breakpoint mixin line 159:
```
  // If $str is still an empty string, no media query is needed
  @if $str == '' {
    @content;
  }
```

It looks a false or null value or some value gives the error.

## Possible Solution

1. When I put this at the very beginning of my css, it is fixed, no error and rendering gets finished:
```
$str: '';
```
Gives result like:
```
@media print,screen and (min-width:40em){
.reveal,.reveal.large,.reveal.small,.reveal.tiny{right:auto;left:auto;margin:0 auto}}
html{line-height:1.15;-webkit-text-size-adjust:100%}
body{margin:0}
h1{font-size:2em;margin:.67em 0}
```
2. I tried this:
```
 // If $str is still an empty string, no media query is needed
  @if not unitless($str) {
    $str: '';
  }
  @if $str == '' {
    @content;
  }
```
Gives result like:
```
.reveal,.reveal.tiny,.reveal.small,.reveal.large{right:auto;left:auto;margin:0 auto}
html{line-height:1.15;-webkit-text-size-adjust:100%}
body{margin:0}
h1{font-size:2em;margin:0.67em 0}
```
That also renders the css but different result from solution 1. Some media queries are missing.

Can this be solved within Foundation with a different @if statement or otherwise?
Is this a type cast error or FALSE/NULL not being accepted.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 6.5.0 / rc4
- Browser(s) name and version(s): Safari 12
- Device, Operating System and version: Mac
- Link to your project:  /* compiled by scssphp v0.7.6 on Tue, 23 Oct 2018 22:14:24 +0000 (1.9175s) */
Using php 7.2 (latest stable version)

## Checklist

- [ x] I have read and follow the CONTRIBUTING.md document.
- [x ] There are no other issues similar to this one.
- [ x] The issue title and template are correctly filled.

**Comment by zzplab** [comment]
Thanks @ncoden.

I don't know if I can add another issue here with leafo/scssphp or better open a new issue.

Another mixin error I get is this one with components > breadcrumbs:
```
Parse error: parse error: failed at `$breadcrumbs-item-separator-item-rtl: '\\' !default;` components/_breadcrumbs.scss on line 52
```
If I change it to this, it works fine:
```
$breadcrumbs-item-separator-item-rtl: "\\" !default;
```
I can always adjust it myself, but would be great if it can be solved in the Foundation mixin.
I know foundation explicitly changed tot single quotes, but these give different results:
'\\' vs "\\"

**Comment by ncoden** [comment]
@zzplab Thanks for reporting this. This is an other bug in Sass but still an other bug, so it should be reported in an other issue.
I'll look at this tonigh.

**Comment by DanielRuf** [comment]
Sounds more like bugs / issues in scssphp as the official Sass compiler supports both cases but we might change this to make it compatible for scssphp.

**Comment by ncoden** [comment]
Like @DanielRuf said, it seems to be an issue with scssphp. `$str` is defined just above and should not cause the `Undefined variable` error. Also, the error message is not reliable as it gives `-1` for error line.

https://github.com/zurb/foundation-sites/blob/735e3c1a7de11e8cf43b992e97e2c3685263f64a/scss/util/_breakpoint.scss#L152

Just to be sure, could you share the result of `@debug type-of($str);` just above the `@if` statement?

**Comment by zzplab** [comment]
```@debug type-of($str);```
I just get this scssphp error format:
```Parse error: Undefined variable $str: line: -1```
Both type (and more) of issues have been reported at scssphp for example [/leafo/scssphp #446](https://github.com/leafo/scssphp/issues/446) including workarounds.
Tonight I've been looking at both scss and php but didn't get any further.
I cannot tell yet whether or not foundation or scssphp issue. Just looking which path will lead to hack free solution.

**Comment by ncoden** [comment]
So this is definitely a scssphp issue. The Foundation SCSS is correct and do not use advanced SCSS features.

Like for https://github.com/zurb/foundation-sites/issues/11557, we cannot support more bugged compilers, please move to RubySass, libSass or Dart Sass.

Won't fix. Closing.
