### ISSUE TITLE
ZURB Template needs reviewing!

### ISSUE THREAD

**Issue by nanu-miguel** [zurb/foundation-sites#11568]
## What should happen?
Hi guys, the ZURB template (https://github.com/zurb/foundation-zurb-template) has significantly changed for the worse in my opinion.  When doing a base install previously I would get a nice index.html home page with some of the Foundation components used.
...

## What happens instead?
Now I get a the following:
----
<div class="index-menu">
  <ul class="menu vertical">
    <li class="aos-init" data-aos="zoom-in-up" data-aos-delay="0"><a href="dashboard.html" target="_blank">Dashboard</a></li>
    <li class="aos-init" data-aos="zoom-in-up" data-aos-delay="250"><a href="#" target="_blank">Page 2</a></li>
    <li class="aos-init" data-aos="zoom-in-up" data-aos-delay="500"><a href="#" target="_blank">Page 3</a></li>
    <li class="aos-init" data-aos="zoom-in-up" data-aos-delay="750"><a href="#" target="_blank">Page 4</a></li>
    <li class="aos-init" data-aos="zoom-in-up" data-aos-delay="1000"><a href="#" target="_blank">Page 5</a></li>
    <li class="aos-init" data-aos="zoom-in-up" data-aos-delay="1250"><a href="styleguide.html" target="_blank">Styleguide</a></li>
  </ul>
</div>
----
This doesn't exactly encourage first perceptions of Foundation and just looks broken.  Can anyone shed any light as to when/why this was changed?
...

## Possible Solution
Change it back!

...

## Test Case and/or Steps to Reproduce (for bugs)
Download the ZURB Template and run locally.

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-zurb-template/pull/90.

**Comment by nanu-miguel** [comment]
Thank you for the comment/tag @ncoden - I did suspect that this was an accidental commit but wanted to check as I thought the repository was private and could only be pushed to by Foundation developers. 

I am a keen user and promoter of the framework and my worry was that those downloading for the first time would get a negative impression.  Glad to see the default install restored.

Michael.
