### ISSUE TITLE
[MediaQuery] Foundation.MediaQuery.current return undefined in Firefox

### ISSUE THREAD

**Issue by geosenna** [zurb/foundation-sites#11563]
Since the 6.5.0.rc-4 (at least); it seems the media query are not working anymore on Firefox.

```
import { Foundation } from 'foundation-sites/js/foundation.core';
import { MediaQuery } from 'foundation-sites/js/foundation.util.mediaQuery';

Foundation.MediaQuery = MediaQuery;

Foundation.MediaQuery._init();

console.log(Foundation.MediaQuery.current);
```

On chrome it print 'xxxlarge', but in firefox it prints 'undefined'. I am pretty sure it is the same on IE.

**Comment by DanielRuf** [comment]
Can you provide a working codepen so we can reproduce it against the latest RC?

**Comment by ncoden** [comment]
Related to https://github.com/zurb/foundation-sites/issues/10363.

Please see the discussion after https://github.com/zurb/foundation-sites/issues/10363#issuecomment-412360167.

**Comment by geosenna** [comment]
Sorry mistake on me. My code was executing too soon, I guess the meta with media query was not loaded yet, so query was empty.
