### ISSUE TITLE
closebutton-size of closebutton not correctly used

### ISSUE THREAD

**Issue by DanielRuf** [zurb/foundation-sites#11569]
## What should happen?

`$closebutton-size` can not be extended / has no effect.

## What happens instead?

Just small and medium are hardcoded and used by the mixin `foundation-close-button`, see https://github.com/zurb/foundation-sites/blob/v6.5.0/scss/components/_close-button.scss#L100

## Possible Solution

Support the map and generate the classes from it.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. add another size to `$closebutton-size` and check the generated CSS

## Context

...

## Your Environment

- Foundation version(s) used: 6.4.3, 6.5.0
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/issues/11569
