### ISSUE TITLE
"clear button dropdown" has a white arrow

### ISSUE THREAD

**Issue by dylanlawrence** [zurb/foundation-sites#11576]
## What should happen?

It should follow the [documented pattern for clear](https://foundation.zurb.com/sites/docs/button.html#clear-style)

## What happens instead?
It's white or unset for all

It's probably just an oversight

How to reproduce:
1. create a <button class="button dropdown clear success"
2. the arrow is white

Fix 

_button.scss [line #391](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_button.scss#L391);

      @include button-dropdown;

      &.clear{
        &::after {
          @include css-triangle(0.4em, $button-background, down);
        }
        @each $name, $color in $button-palette {
          &.#{$name} {
            &::after {
              @include css-triangle(0.4em, $color, down);
            }
          }
        }
      }

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11581
