### ISSUE TITLE
[Forms] ISSUE NAME HERE

### ISSUE THREAD

**Issue by vantaiphanthi** [zurb/foundation-sites#11587]
## Expected Behavior

...

## Current Behavior

...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] This is a bug report or a feature request.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Please fill out the whole issue template.
