### ISSUE TITLE
dist/js not updated for 6.5.0

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites#11583]
## What should happen?

The JS files in dist/js/plugins should be updated to Foundation 6.5.0

## What happens instead?

The files are at 6.4.3.

## Test Case and/or Steps to Reproduce (for bugs)
Test Case: https://github.com/zurb/foundation-sites/tree/develop/dist/js

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
> Test Case: [/dist/js@`develop`](https://github.com/zurb/foundation-sites/tree/develop/dist/js)

We have a different branch for this release. See https://github.com/zurb/foundation-sites/tree/develop-v6.5

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/blob/develop/CONTRIBUTING.md#git-workflow

**Comment by JeremyEnglert** [comment]
Which branch is NPM pulling from? When I pull 6.5.0 from NPM, the package.json says 6.5.0 but the JS files are still 6.4.3.

**Comment by JeremyEnglert** [comment]
> See https://github.com/zurb/foundation-sites/blob/develop/CONTRIBUTING.md#git-workflow

"Develop: Used to prepare the next minor/major version. It always contains all the new features and bug fixes, and is the most up-to-date version of Foundation. Almost every pull request should be opened on this branch (fixes, features, documentation...). When a new version is released, it is merged on master, a dedicated develop-v... branch is created, and develop now targets the next version."

The current "develop" branch has 6.4.3 JS files. I guess that's where my confusion comes from.

**Comment by ncoden** [comment]
Fixed in [v6.5.1](https://github.com/zurb/foundation-sites/pull/11584). Closing.
