### ISSUE TITLE
[Tabs] TabIndex -1 on non-active tabs

### ISSUE THREAD

**Issue by vivodigital** [zurb/foundation-sites#11590]
## Expected Behavior
TabIndex attribute on non-active tabs-title anchor elements is set to 0 or non existent to allow for keyboard tabbing to navigate to the next tab. 

## Current Behavior
Foundation sets all non-active tabs to tabIndex -1 so they are removed from the natural tab flow and cannot be navigated to via keyboard tabbing.  

## Possible Solution
Remove the javascript that sets the non-active tabs tabIndex to -1. 

## Test Case and/or Steps to Reproduce (for bugs)
Test Case: (https://foundation.zurb.com/sites/docs/tabs.html)

How to reproduce:
1. Attempt to navigate through the tab example using keyboard tab.

**Comment by DanielRuf** [comment]
Hi @vivodigital 👋 , thanks for the report.

Please test the linked PR.
Let me know if you need any assistance with applying the change to your files for testing.

**Comment by ncoden** [comment]
Hi @vivodigital 👋,

This is not a bug but the expected behavior.

Preventing selection of all non-active tabs allow the user to focus the content with <kbd>tab</kbd> or to go back on the title with <kbd>sift</kbd> + <kbd>tab</kbd>. Others tabs can be selected with <kbd>Left arrow</kbd> and <kbd>Right arrow</kbd>.

I don't think this behavior should be changed.

**Comment by DanielRuf** [comment]
> This is not a bug but the expected behavior.

Not sure where this is documented but all focusable elements should have `0` as tabindex to be accessible using the keyboard.

**Comment by DanielRuf** [comment]
I guess you mean https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html then?

**Comment by ncoden** [comment]
I updated my comment. See https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html. Others tabs have `tabindex="-1"` and the content is changed with [Left arrow] and [Right arrow].

**Comment by DanielRuf** [comment]
Hm, so seems to be right then according to w3c.
But the docs should have `tabindex="0"` in the example html code as fallback probably.

**Comment by DanielRuf** [comment]
W3C ARIA examples have the `tabindex="0"` in the html examples but you are probably right that this is not needed.

cc @Owlbertz

**Comment by vivodigital** [comment]
@DanielRuf @ncoden Thanks for your prompt assistance. I was skipping the `ul` and `li` elements in the tablist and just specifying them as `divs`. As as result my list was not navigable using <kbd>Left Arrow</kbd> or <kbd>Right Arrow</kbd> hence going down the `tabindex=0` route. Thanks for the demo @DanielRuf which helped me figure this out 👍

**Comment by vivodigital** [comment]
@DanielRuf @ncoden Is there a way to overwrite the JS that sets the `tabindex` on the `tabs-title` anchor?

My CMS doesn't allow me to code the `is-active` tab on the first tab title. It would appear on them all. I am therefore setting it dynamically using JS. This does not make the `tabindex` on the first tab title anchor change to `0`, instead it stays at `-1`. I have tried using both vanilla Javascript and jQuery to change the `tabindex` attribute but it seems to get overwritten by the Foundation Tabs JS. 

[Demo](https://codepen.io/benvivo/pen/rQQVmZ?editors=1010)

**Comment by DanielRuf** [comment]
> @DanielRuf @ncoden Is there a way to overwrite the JS that sets the `tabindex` on the `tabs-title` anchor?

Basically by changing it in the used files and creating a patch using `patch-package`.

https://github.com/ds300/patch-package
https://npmjs.com/package/patch-package

**Comment by DanielRuf** [comment]
Is this a cross post? https://stackoverflow.com/questions/53535554/zurb-foundation-tabs-tabindex-for-keyboard-accessibility
