### ISSUE TITLE
Documentation on Gutters in the XY Grid doesn't mention the y-axis

### ISSUE THREAD

**Issue by stuart897** [zurb/foundation-sites#11601]
## Description

Documentation on Gutters in the XY Grid (https://foundation.zurb.com/sites/docs/xy-grid.html#gutters) describes how you can adjust the margin or padding in the x-axis. However, it doesn't explicitly mention there are also classes for adjusting margin/padding in the y-axis too.

## Possible Solution

Mention `.grid-margin-y` and `.grid-padding-y` in the documentation.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
Hi @stuart897 👋,

See https://github.com/zurb/foundation-sites/pull/11610
