### ISSUE TITLE
Class name changes not documented

### ISSUE THREAD

**Issue by leenyburger** [zurb/foundation-sites#11609]
## Description
 I've been upgrading from Foundation 4 to 6 and it seems it's basically been rewritten. I've encountered several class name changes that aren't documented. The only way I know a class has been dropped or a name has been changed is opening the code for 4 and then comparing it to 6. As so much has been changed this is incredibly time consuming. The release notes don't adequately describe the changes (example: pagination-centered). Is there any comprehensive resource that lists the old class names and the new names?

## Possible Solution
Share a document showing class name changes. When upgrading classes aren't touched unless the need arises, so I need to know which class names were changed and confirm I don't have any removed classes in my code. 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Major versions also include breaking changes (SemVer). Which classes exactly are problematic.

In general Foundation 6 is something different compared to 4.

So far I am not aware of a complete overview of such cganges from one major to another major version.

Most devs start from scratch using F6.
Also 6.4 compared to 6.5/6 will also have such (breaking) changes but thsy are now better documented in the release descriptions and changelog.

**Comment by ncoden** [comment]
Only the changelog/release notes can be helpful for a so big jump. Foundation 4 is more than 5 years old. 

The best we could provide is the changelog and major migration guides. See:
- [Migrating from v4 to v5](https://foundation.zurb.com/sites/docs/v/5.5.3/upgrading.html)
- [Migrating from v5 to v6 (unofficial compilation)](http://www.alwaysrightinstitute.com/foundation6/)
- [All Foundation releases](https://github.com/zurb/foundation-sites/releases)
