### ISSUE TITLE
Cell Auto Collapses in Chrome 70

### ISSUE THREAD

**Issue by Bakuryu** [zurb/foundation-sites#11602]
## What should happen?
Cell should be sized auto height and width to take up whats left of the grid. This allows me to align the a tag element to the bottom of the cell.

## What happens instead?
Cell collapses (I think?).  Since it no longer fills the rest of the grid it has no room to position the a tag.

## Possible Solution

Tried trouble shooting this a lot and so far have not come up with a solution.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://codepen.io/Bakuryu/pen/eQVdNO

## Context

Trying to make the last link element always stay on the bottom regardless if the cells around its text makes the cards bigger. It works on Firefox, IE, and Edge.

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): Chrome 70
- Device, Operating System and version: Windows 10

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by ncoden** [comment]
I can reproduce the issue with Foundation 6.5.1.

On Firefox:
<img width="809" alt="screenshot 2018-11-21 at 21 34 36" src="https://user-images.githubusercontent.com/9939075/48867115-6f8b0980-edd5-11e8-945f-56bffcf15d8a.png">

On Chrome:
<img width="812" alt="screenshot 2018-11-21 at 21 34 30" src="https://user-images.githubusercontent.com/9939075/48867124-787bdb00-edd5-11e8-8c37-8575df19539d.png">

**Comment by ncoden** [comment]
This is not a bug in Foundation but with the properties you use to make the grid inside the `.card-section` taking the whole height.

See https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent

I set up a working example with the 4th solution: using flex properties instead of `height: 100%` https://codepen.io/ncoden/pen/Jeprxe.
