### ISSUE TITLE
.foundation-mq font-family returns Times instead of "small=0&xsmall=450px&medium=750..."

### ISSUE THREAD

**Issue by simonknittel** [zurb/foundation-sites#11616]
_I want to post this on the Foundation Forums, but I can't register there. The register form just redirects to itself without any error or success._

## What should happen?
`window.Foundation.MediaQuery.atLeast('medium')` should always return `true` when we are above the `medium` breakpoint.

## What happens instead?
We are calling `window.Foundation.MediaQuery.atLeast('medium')` on page load which returns sometimes `false` even though we are above our `medium` breakpoint.

While debugging I found out that when Foundation initializes and reads the `font-family` property of the `.foundation-mq` element it's value is sometimes `Times` and sometimes the correct `small=0&xsmall=450px&medium=750...` (this line: https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.mediaQuery.js#L97).

I noticed that it only happens when I reload the page without clearing the cache. I also noticed that it only happens on randomly on some specific test server of us. Locally or a different test server of us it happens extremely rarely. We can't reproduce it with 100% certainty on every page reload.

## Test Case and/or Steps to Reproduce (for bugs)
I have a hard time to get only a part of the application which I can post standalone so you can test without all the other stuff. Maybe the description works for now, if not I will try to post only the necesssary stuff to reproduce it.

## Your Environment

- Foundation version(s) used: 6.5.0
- Browser(s) name and version(s): Google Chrome 70
- Device, Operating System and version: macOS 10.14.1

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Please test if Foundation Sites 6.5.0 fixes your issue.

**Comment by DanielRuf** [comment]
Hi @simonknittel 👋 
thanks for your report.

Please test if Foundation Sites 6.5.0 fixes your issue.

**Comment by simonknittel** [comment]
My mistake. We already use 6.5.0. I checked only the package.json and not the package-lock.json.

On further debugging I found out, that the issue is that our JS bundle loads faster than our CSS bundle. This happens because Chrome shows it loads the CSS bundle from "Memory cache" and the JS bundle from "Disk cache". That also explains why we don't have that issue when we reload the page with cleared cache (our CSS bundle is smaller than the JS bundle and therefore loads faster).

Since it looks like Foundation caches the value returned by font-family is there maybe a way to refresh that cache when the CSS bundle has fully reloaded?

**Comment by DanielRuf** [comment]
So do you load your JS files in the head? JS files should be always loaded at the end of `</body>` (right before it), only styles are in `<head>`.

**Comment by DanielRuf** [comment]
The caches are not the problem.

**Comment by DanielRuf** [comment]
Afaik you can not control the browser caches (there are many) across different browsers in such a way.

**Comment by simonknittel** [comment]
We load it in the head but with the `defer` tag applied.

**Comment by simonknittel** [comment]
I didn't want to suggest to refresh the browser cache but more like to say Foundation: "Hey Foundation, the CSS of our .foundation-mq has changed. Could you please use the new value?". Propably not the smartest way, but we don't really want to slow down the loading of our JS till the CSS bundle is there.

**Comment by DanielRuf** [comment]
> We load it in the head but with the `defer` tag applied.

Not a good solution and not recommended and does not work reliably as the browser decides when he loads the files - which produces these inconsistencies.

**Comment by DanielRuf** [comment]
I closed this issue as we did not receive any further feedback and the used code is an antipattern in my opinion.
