### ISSUE TITLE
SmoothScroll options can't be set

### ISSUE THREAD

**Issue by Renkas** [zurb/foundation-sites#11620]
## What should happen?
I should be able to set smoothScroll options via data attributes.
`data-offset="100" data-animation-duration="1"`

## What happens instead?
These attributes are ignored

## Possible Solution
I believe problem is in `_handleLinkClick` method https://github.com/zurb/foundation-sites/blob/develop/js/foundation.smoothScroll.js#L60
`this` is always undefined. So `this.options` is also undefined. So only default options will ever be used.

## Test Case and/or Steps to Reproduce (for bugs)
Codepen in Foundation 6.5.1: https://codepen.io/anon/pen/QJPpbQ
Note that there is no offset and the scroll does take 500ms - instead of 1ms.
Also the scroll stops before actually reaching the element.

## Your Environment

- Foundation version(s) used: 6.5.1

**Comment by ncoden** [comment]
Hi @Renkas 👋,

Thanks to @ben-z, this should be fixed by https://github.com/zurb/foundation-sites/pull/11622.
