### ISSUE TITLE
The "open.zf.reveal" event is fired before the reveal modal has opened.

### ISSUE THREAD

**Issue by ozzywadd** [zurb/foundation-sites#11625]
## What should happen?
The "open.zf.reveal" event should only be fired once the reveal modal has opened.

## What happens instead?
The "open.zf.reveal" event is fired before the reveal modal has opened.

## Test Case and/or Steps to Reproduce (for bugs)
https://codepen.io/anon/pen/dwYmOB?editors=1010

## Context
I need to target the reveal modal contents to initiate more js once it's open. The "open.zf.reveal" event seems like the logical extension point here but for some reason, the reveal modal is not present at the time this event is triggered.

**Comment by DanielRuf** [comment]
We might have to introduve the `closed` here too. See https://github.com/zurb/foundation-sites/pull/10949#issuecomment-366695985

**Comment by DanielRuf** [comment]
We might have to introduce the `closed` here too. See https://github.com/zurb/foundation-sites/pull/10949#issuecomment-366695985

**Comment by ozzywadd** [comment]
I figured that the reason for this was the delay on the animation. I believe even the default duration of show() is 400ms although, adding any amount of duration in a setTimeout function seemed to prove successful for me. Far from ideal though.

**Comment by DanielRuf** [comment]
Why not chain the close event chsck with a check for `animationend`? We also have utils for this. You can nest the .on() checks like we do in some of our tests.

**Comment by DanielRuf** [comment]
Why not chain the close event check with a check for `animationend`? We also have utils for this. You can nest the .on() checks like we do in some of our tests.

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-sites/blob/develop/test/javascript/components/offcanvas.js#L209-L217

**Comment by DanielRuf** [comment]
Closing this issue as we did not receive any further feedback. Let us know if we should reopen this.
