### ISSUE TITLE
SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.

### ISSUE THREAD

**Issue by benekex2** [zurb/foundation-sites#11628]
## What happens instead?

`SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.`

in

` var _this = this;
      // Motion UI method of reveal
      if (this.options.animationIn) {
        function afterAnimation() {
          _this.$element.attr({
            'aria-hidden': false,
            'tabindex': -1
          }).focus();
          _this._addGlobalClasses();`

## Your Environment

- Foundation version(s) used:  6.5.1
- Browser(s) name and version(s): all
- Device, Operating System and version: all

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Please provide steps which lead to this error.

**Comment by ncoden** [comment]
@benekex2 Please add more informations about your bug, how to reproduce it and format your code.

**Comment by benekex2** [comment]
This is syntax in your code. You declare function in if statement. This is not allowed in strict mode.

`/node_modules/foundation-sites/js/foundation.reveal.js` on `256 line`

``` 
// Motion UI method of reveal
    if (this.options.animationIn) {
      function afterAnimation() {
        _this.$element
          .attr({
            'aria-hidden': false,
            'tabindex': -1
          })
          .focus();
        addRevealOpenClasses();
        Keyboard.trapFocus(_this.$element);
      }
      if (this.options.overlay) {
        Motion.animateIn(this.$overlay, 'fade-in');
      }
      Motion.animateIn(this.$element, this.options.animationIn, () => {
        if (this.$element) { // protect against object having been removed
          this.focusableElements = Keyboard.findFocusable(this.$element);
          afterAnimation();
        }
      });
    }
```

**Comment by DanielRuf** [comment]
> This is syntax in your code. You declare function in if statement. This is not allowed in strict mode.

We never had this issue with our webpack builds in projects.
Please provide the steps to reproduce this error with a fresh project and config files.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
