### ISSUE TITLE
"border-none" on "tabs" works in official file, but not in compiled file from SASS?

### ISSUE THREAD

**Issue by namvt13** [zurb/foundation-sites#11631]
## What should happen?

"border-none" should remove "tabs" border, no matter which version is being used (official or compiled).

## What happens instead?

Using compiled file from SASS (Includes everything, I was testing sass features) in my project, I noticed that the borders are back.

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Compile everything using SASS CLI
2. Add it to a project with "tabs" element
3. Add "border-none" to the "tabs" element

## Context

...

## Your Environment

- Foundation version(s) used: 6.5.1
- Browser(s) name and version(s): Chrome (v71.0.3578.98), can't confirm on others
- Device, Operating System and version: Ubuntu 64 18.10
- Link to your project: Small testing project, so no link

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Can you provide a codepen which reproduces this?

**Comment by DanielRuf** [comment]
In general I see no `.border-none` in the dist files.

**Comment by DanielRuf** [comment]
In general you have to enable the prototyping classes / mixins through settings.scss.

Also see https://github.com/zurb/foundation-sites/blob/develop-6.5/dist/css/foundation-prototype.css

**Comment by DanielRuf** [comment]
In general you have to enable the prototyping classes / mixins through settings.scss.

Also see https://github.com/zurb/foundation-sites/blob/develop-v6.5/dist/css/foundation-prototype.css

**Comment by DanielRuf** [comment]
https://foundation.zurb.com/sites/docs/prototyping-utilities.html#enabling-prototype-mode describes the needed steps.

**Comment by DanielRuf** [comment]
In general you have to enable the prototyping classes / mixins.

Also see https://github.com/zurb/foundation-sites/blob/develop-v6.5/dist/css/foundation-prototype.css and https://github.com/zurb/foundation-sites/blob/develop-v6.5/scss/foundation.scss#L82

https://foundation.zurb.com/sites/docs/prototyping-utilities.html#enabling-prototype-mode describes the needed steps.

> Prototype mode is disabled by default!
