### ISSUE TITLE
slider not working in chrome

### ISSUE THREAD

**Issue by rushikeshk-gdb** [zurb/foundation-sites#11649]
## What should happen?
progress bar background color dose not change according to value .

## What happens instead?
I need to change progress bar color changes according to value 

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:
1.create and html input type="range" tag
2.provide the css for progress bar and progress bar thumb.
3.

## Context
need to fill the progress bar background according to thumb position value.
but input[type="range"] parameter take an overflow:"hidden" option .
i didn't want this i need to support progress bar like it works in other browsers.

## Your Environment
- Foundation version(s) used: 
- Browser(s) name and version(s): Version 71.0.3578.98 
- Device, Operating System and version: windows 8
- Link to your project:

**Comment by DanielRuf** [comment]
Please provide a codepen with your code or link to your project so we can see the problem. And please provide the used Foundation Sites version.

**Comment by rushikeshk-gdb** [comment]
sorry I am new on git
i will provide code that i am using 
i have added and comment for that option parameter


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
    height: 100vh;
    margin: 0;
}

.slidecontainer{
    position: relative;

}

input[type="range"] { 
    margin: auto;
    -webkit-appearance: none;
    position: relative;
    overflow: hidden;  /// if i remove this line then it not working properly in chrome /////
    height: 2px;
    width: 100%;
    cursor: pointer;
    border-radius: 0; 
}

::-webkit-slider-runnable-track {
    background: #ddd;
}

::-webkit-slider-thumb {
    -webkit-appearance: none;
    width: 20px; /* 1 */
    height: 40px;
    background: #fff;
    border-radius: 50%;
    background-color: blue;
    box-shadow: -100vw 0 0 100vw blue;
    border: 2px solid #B90A0A;
}

::-moz-range-track {
    height: 4px;
    background: #ddd;
}

::-moz-range-thumb {
    background: #fff;
    height: 40px;
    width: 20px;
    border: 3px solid #999;
    border-radius: 0 !important;
    box-shadow: -100vw 0 0 100vw dodgerblue;
    box-sizing: border-box;
}

::-ms-fill-lower { 
    background: dodgerblue;
}

::-ms-thumb { 
    background: #1F08E7;
    border: 2px solid #999;
    height: 40px;
    width: 20px;
    box-sizing: border-box;
}

::-ms-ticks-after { 
    display: none; 
}

::-ms-ticks-before { 
    display: none; 
}

::-ms-track { 
    background: #ddd;
    color: transparent;
    height: 4px;
    border: none;
}

::-ms-tooltip { 
    display: none;
}
</style>
</head>
<body>

<div class="slidecontainer">
  <input type="range" min="1" max="100" class="slider" value="50">
</div>
</body>
</html>

**Comment by rushikeshk-gdb** [comment]
Foundation Sites version -
 not getting this

**Comment by DanielRuf** [comment]
Not sure but this does not look like you use Foundation and wrote your own code.

**Comment by DanielRuf** [comment]
https://foundation.zurb.com/sites/docs/progress-bar.html

https://foundation.zurb.com/sites/docs/slider.html

**Comment by rushikeshk-gdb** [comment]
I need to google it .
Thanks
I will try to use foundation

**Comment by asecondwill** [comment]
@rushikeshk-gdb  - you should probably close this right?
