### ISSUE TITLE
Develop branch seems to behind latest release (v6.5.1)

### ISSUE THREAD

**Issue by olthof** [zurb/foundation-sites#11656]
## Description

Recently I was checking the latest version of the settings/_settings.scss file on develop (https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss) and I noticed that it was missing $button-responsive-expanded. I thought this was weird as it's in the documentation. Upon switching the branch to v6.5.1, (https://github.com/zurb/foundation-sites/blob/v6.5.1/scss/settings/_settings.scss), I noticed that it was present there. I checked latest edit and it seems the develop version of the settings file was latest edited Jun 29, 2018, but the v6.5.1 branch more recently on Nov 13, 2018.

Maybe this is a misunderstanding on my behalf but shouldn't develop be the latest version of the code, and therefore be ahead of v6.5.1?

Maybe $button-responsive-expanded has been lost in a merge or maybe I'm not understanding the way releases work here, or maybe something else? Sorry if this question is in the wrong place or worded incorrectly, it's the first issue I've reported.

**Comment by DanielRuf** [comment]
Also see https://github.com/zurb/foundation-sites/blob/develop/CONTRIBUTING.md#git-workflow

**Comment by olthof** [comment]
Hi @DanielRuf, thanks for the quick response.

I did have a look at the git workflow link you send and under develop it states "It always contains all the new features and bug fixes, and is the most up-to-date version of Foundation". So I would assume that all files, include the settings file, would be the latest version, ahead of the v6.5.1 branch.

If the settings file is generated by a gulp task however, I guess I'm wondering when the settings file is updated on develop. Is it just updated on the next release and then left, possibly for months and out of since with the rest of develop?

As a side question, do you know of any other files that are generated in this way? Thanks again for your help.

**Comment by DanielRuf** [comment]
> include the settings file

The settings file only extracts the default variable settings from the Sass files and can be updafed by running the release task (which we only do for releases). The variables and settings should be still in their Sass files.

**Comment by DanielRuf** [comment]
> any other files that are generated in this way?

Basically all dist files.
