### ISSUE TITLE
[Starter Projects] Zurb Foundation template does not refresh pages when /src/data/*.yml is changed

### ISSUE THREAD

**Issue by kosmiq** [zurb/foundation-sites#11660]
## Expected Behavior

Using an .yml file in /src/data to produce content should refresh the page where that data is outputted when adding/removing/changing objects in the .yml file.

## Current Behavior

Changing the content of an .yml file does not trigger a page refresh with the updated content.

## Possible Solution

Adding the below line to the watch() function in gulpfile.babel.js solves this issue.

`gulp.watch('src/data/**/*.yml').on('all', gulp.series(resetPages, pages, browser.reload));`

(note that "resetPages" is required for the data to actually be loaded)

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:

1. Create an .yml file and place it in /src/data
2. Add some objects to it (like the Custom data instruction at https://foundation.zurb.com/sites/docs/panini.html)
3. Use the data on a page
4. Run foundation watch
5. Update said data in the .yml file, like adding "- sausage" and save the file
6. Nothing happens on the page
7. Quitting foundation watch (ctrl+c) and starting it again will produce an updated page with the new object.

## Context

By refreshing pages with updated .yml data I can skip the step of stopping and starting foundation watch while doing minor changes to content defined in .yml files.

## Your Environment

- Foundation version(s) used: 6.4.1
- Browser(s) name and version(s): not applicable
- Device, Operating System and version: not applicable
- Link to your project: not public

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] This is a bug report or a feature request.
- [X] There are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
So far the watch task was only meant to watch styles and some other things.

You can add the aforementioned line if it's needed.

**Comment by DanielRuf** [comment]
Which template do you use?

https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js contains a line in the watch task which watches data files.

**Comment by DanielRuf** [comment]
Which template do you use and when did you bootstrap the project from the templates?

https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js contains a line in the watch task which watches data files.

**Comment by kosmiq** [comment]
So I checked. I started this project sometime in July. And you are correct, I can see that the data watcher lines were merged in September from a pr.

Thanks for the quick reply. I'll make sure to look a little closer next time. :)
