### ISSUE TITLE
OffCanvas transition-time value incorrectly listed as number instead of string

### ISSUE THREAD

**Issue by noahheck** [zurb/foundation-sites#11666]
## Description

Currently, the information in the Sass reference for this option states the data should be a number and that number will be understood to be milliseconds: 

data-transition-time | number | null | Amount of time in ms the open and close transition requires. If none selected, pulls from body style.
-- | -- | -- | --

The `transition-time` attribute is passed directly to the element css (https://github.com/zurb/foundation-sites/blob/develop/js/foundation.offcanvas.js#L136) without appending the `ms` string to the value. The only way I was able to modify the value was by adding the units to the option as well (e.g. `100ms` or `.3s`).

## Possible Solution

The __Type__ value should be listed as `string` instead of `number` and the __Description__ updated to reference including the units in the configuration value. I would have submitted a pull request doing this, but the Reference sections don't appear to be a part of the repo (perhaps auto-generated from elsewhere in the repo?). If I'm wrong about this, please let me know and I'm happy to submit a pull request.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi, you can find it in https://github.com/zurb/foundation-sites/blob/develop/js/foundation.offcanvas.js at the bottom as `transitionTime`.
