### ISSUE TITLE
 Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by vinuengico** [zurb/foundation-sites#11674]
## Description

I am using Amcharts in my site which is built using Foundation. Whenever I move my mouse on the page   after calling the Amcharts I keep getting this error logged into my console- "Right-hand side of 'instanceof' is not callable"

Somehow I was able to get this solved with foundation.min.js version- 6.5.1.

However I am surprised to see that the same issue is happening again if I am using the 6.5.2 or the latest 6.5.3 or older version (any other version 6.5.0-rc.2/4 etc)

I am not sure if this is an issue which was solved earlier but got reverted. Not an expert here but someone please look into this.

![image](https://user-images.githubusercontent.com/39088074/52693408-a9128180-2f8c-11e9-9388-b82b3ef44301.png)

**Comment by DanielRuf** [comment]
Hi @vinuengico,

please provide a codepen so we can reproduce it on our side.

**Comment by DanielRuf** [comment]
In my opinion this is a conflict / issue in amCharts. See https://github.com/amcharts/amcharts4/blob/fae94eaaf1d7c85de73838da4fe857285e660c6b/src/.internal/core/interaction/Interaction.ts#L2412
