### ISSUE TITLE
date-close / data-closeable not closing container

### ISSUE THREAD

**Issue by Chris--S** [zurb/foundation-sites#11678]
## What should happen?

Following the html structure described in the documents here, https://foundation.zurb.com/sites/docs/toggler.html#mark-as-closable the dev.callout should close when the close button is clicked.

## What happens instead?

dev.callout is not closing when the close button is clicked.

On clicking the close button, I can see js does modify div.callout leaving it with the classes, mui-leave & mui-leave-active set.  This seems to be a half-way state.

## Possible Solution
(work-around)

I can get closeable to work by adding the class="fade-out" to div.callout.   This isn't required on the examples in the documentation.

Note, in investigating this, I also tried the following, none of which worked.
data-animate="fade-out"
data-closeable="fade-out"
upgrading foundation-sites to 6.5.3
using the pre-prepared ./lib/foundation-explicit-pieces rather than importing Foundation as described above.

## Environment

- Foundation version(s) used:   Zurb template 1.0.0, Foundation Sites 6.5.1,
- Browser(s) name and version(s):  n/a
- Device, Operating System and version: n/a 

Foundation is correctly initialized on the page and motion-ui is loaded (app.js imports  "Foundation from 'foundation-sites')".

**Comment by DanielRuf** [comment]
Hi @Chris--S, did you already try the mixins from https://foundation.zurb.com/sites/docs/xy-grid.html#sass-reference?

**Comment by DanielRuf** [comment]
Please fill out our issue template with all relevant details.

**Comment by DanielRuf** [comment]
Hi @Chris--S,
Please fill out our issue template with all relevant details.

**Comment by DanielRuf** [comment]
> and motion-ui is loaded

You have to import it too. It is not directly loaded by foundation-sites.

**Comment by Chris--S** [comment]
> Hi @Chris--S,
> Please fill out our issue template with all relevant details.

revised

**Comment by Chris--S** [comment]
> > and motion-ui is loaded
> 
> You have to import it too. It is not directly loaded by foundation-sites.

I think you might be wrong there.  

> Motion UI is already included in both starter projects.
[ref.](https://foundation.zurb.com/sites/docs/motion-ui.html)

It is included in my setup.  orbit, reveal, toggler & responsive toggler (other components which depend on motion-ui) all work fine.

**Comment by DanielRuf** [comment]
Also please provide a working reproducible setup (codepen or Git repository).

**Comment by t3rminus** [comment]
@Chris--S I was having the same problem, and I think (based on your original issue template) that you might have made the same mistake I did:

The correct attribute is `data-closable`, and *not* `data-closeable`. Note the lack of "e" in "closable".

Both spellings appear to be correct and valid English (yay, English 😖), and Foundation has settled on "closable" (without the "e") according to this: https://github.com/zurb/foundation-apps/issues/358

As soon as I removed the "e", everything worked fine.

**Comment by DanielRuf** [comment]
> Both spellings appear to be correct and valid English (yay, English 😖), and Foundation has settled on "closable" (without the "e") according to this: [zurb/foundation-apps#358](https://github.com/zurb/foundation-apps/issues/358)

Foundation Apps is not maintained anymore.

Right, we use `closable` in Foundation Sites, see https://github.com/zurb/foundation-sites/search?l=JavaScript&q=closable

**Comment by DanielRuf** [comment]
I guess we can close this then as resolved.
Let us know if the docs are unclear.

**Comment by DanielRuf** [comment]
> To create an element that can be closed once, add the attribute data-closable. Then add a click trigger inside the element using data-close.

The current documentation should be clear enough.
