### ISSUE TITLE
ResponsiveAccordionTabs add possibility to set accordion content before title

### ISSUE THREAD

**Issue by Renkas** [zurb/foundation-sites#11670]
## What is missing?
Would like to use "reverse accordion". So that content comes before title.

**Comment by DanielRuf** [comment]
Hi @Renkas, what did you try so far? Did you already try the CSS property `order`?

**Comment by Renkas** [comment]
@DanielRuf well - no :)

Ofcourse I can use flexbox there with order. Thanks. This works well. I'll close the issue.
