### ISSUE TITLE
[Abide] Required on Radio Group doesn't work

### ISSUE THREAD

**Issue by warriotox** [zurb/foundation-sites#11683]
Looking at the documenttion page for Abide https://foundation.zurb.com/sites/docs/abide.html
at the very top you have a demo, one part of it is three radio buttons ([name="pokemon"]) which are meant to demo required on a group of radio buttons. You do this by setting "required" on the second radio button (#pokemonBlue). But this doesn't work as expected.

## Expected Behavior
When I click submit without selecting any of the Pokemon radios all of the inputs turn red OR the fieldset legends turns red.
When I click submit with any of the radio buttons selected the submit goes through.

## Current Behavior
When I click submit without selecting any of the Pokemon radios only input that had "required" on it turns red
When I click submit with the first or the third radio selected the submit doesnt go through and it marks the second one as in error. With the second radio selected the submit works fine

## Possible Solution
I've been working around this with a custom validator. This requires adding [data-validator="toggle_req"] on every radio element from the group and they need to be children of a fieldset. But I'm guessing this solution is far from optimal
```
Foundation.Abide.defaults.validators['toggle_req'] = function foundationToggleMinValidator( $el, required, parent ){
					var group = parent.closest( 'fieldset' );
					var min = group.attr( 'data-validator-min' );
					var checked = group.find( ':checked' ).length;
					if( checked >= 1 ){
						//legend unhighlight
						group.find( 'label' ).removeClass( 'is-invalid-label' );
						group.removeClass( 'is-invalid-input' );
						group.find( 'span.form-error' ).removeClass( 'is-visible' );
						return true;
					}
					else{
						//legend highlight
						group.find( 'label:first' ).addClass( 'is-invalid-label' );
						// checkbox error
						group.find( 'span.form-error' ).addClass( 'is-visible' );

						group.addClass( 'is-invalid-input' );
						return false;
					}
				};
```

## Test Case and/or Steps to Reproduce (for bugs)
Test Case: Go to: https://foundation.zurb.com/sites/docs/abide.html follow steps in current/expected behavior above

## Context
I've been using foundation for two years now. Two years ago I found this issue, found the workaround somewhere on the web and didn't look back. Today I noticed this has never been fixed. I'm surprised no one else has reported it. 

## Your Environment
- Foundation version(s) used:  https://foundation.zurb.com/sites/docs/abide.html
- Browser(s) name and version(s): Chrome

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by SassNinja** [comment]
Hi @warriotox 

I'm unable to reproduce your issue.

> When I click submit without selecting any of the Pokemon radios only input that had "required" on it turns red

Can't confirm this – when I submit the empty form all radio inputs in the group turn red.

![abide_radio_issue](https://user-images.githubusercontent.com/19912475/53015394-4a954980-344b-11e9-8fd4-fcc04190789b.gif)

**Comment by warriotox** [comment]
Hi @SassNinja thanks for the quick response as always! Ehrm I am so so sorry, I was actually talking about the checkboxes. You can see it in your gif as well the Checkbox 2 stays red. Everything I wrote above is about the checkboxes not the radio buttons. Can I edit the post? Also, how come your radio buttons and checkboxes look so nice and I have native? See my [screenshot](https://puu.sh/COxWV/68eaac79c5.png) this is in Google Chrome Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by warriotox** [comment]
To clarify a bit more, if you fill in correctly all the required fields in the demo, expect the Checkboxes and hit sobmit Checkbox 2 turns red. Then if you select Checkbox 1 or 3 and click submit nothing happens and it stays red. If you select Checkbox 2 and click submit the form submit actually fires and the page is reloaded.

**Comment by SassNinja** [comment]
> Everything I wrote above is about the checkboxes not the radio buttons.

ah ok, I didn't pay attention to it but you're right, the checkboxes don't behave as expected.
The reason is Abide simply has no checkbox group support yet.

Ironically I made a PR about two years ago to fix this but I lost track of it (the git history got messed up and a new clean PR has obviously never be done).

I'll take care of it!

**Comment by SassNinja** [comment]
> Also, how come your radio buttons and checkboxes look so nice and I have native?

You can get the same – all you need is a Mac ;)

**Comment by warriotox** [comment]
> Ironically I made a PR about two years ago to fix this but I lost track of it (the git history got messed up and a new clean PR has obviously never be done).
> 
> I'll take care of it!

Wow, what are the odds! Thank you!
