### ISSUE TITLE
Issue Anchor links and Accordion

### ISSUE THREAD

**Issue by JBaumann73** [zurb/foundation-sites#11685]
## What should happen?

If you call a Url. With Anchor. On the Accordion the CSS tag "is-active" is removed.
The cursor should jump to the appropriate position. And the Accoridon should remain active.

## What happens instead?

The cursor should jump to the corresponding anchor and the accordion should remain active.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://www.weltbild.de/artikel/deko-trends/lichtwecker_24725596-1#comments

## Your Environment

- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): FIrefox, Chrome

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @JBaumann73,

> What happens instead?

I guess you forgot to describe the current behavior.

Did you already try the `data-deep-link` attributes?

**Comment by JBaumann73** [comment]
I have set the deep-link.

`<ul class="tabs"
        data-responsive-accordion-tabs="accordion large-tabs"
        data-allow-all-closed="true"
        data-deep-link="true"
        data-deep-link-smudge="true"
        id="product-info">`

**Comment by DanielRuf** [comment]
I'll check it later in detail.

**Comment by JBaumann73** [comment]
Thanks

**Comment by DanielRuf** [comment]
@JBaumann73 can you test my changes on your side?

**Comment by JBaumann73** [comment]
yes, it works. 

When does the change go live?

**Comment by DanielRuf** [comment]
When it is approved by the others and merged and a new release cut. So far you can apply the changes to the generated files or source files and regenerate the dist files (from the node_modules directory) by using `patch-package`.
