### ISSUE TITLE
Upgrading from 6.2 to >=6.3 got error

### ISSUE THREAD

**Issue by AliNL** [zurb/foundation-sites#11702]
## What should happen?
webpack runs successfully.

## What happens instead?
      &.#{$-zf-size}-horizontal {
      ^
      Invalid CSS after "&.sl-remove": expected selector, was "(small medium large"
      in .../node_modules/foundation-sites/scss/components/_menu.scss (line 277, column 8)

## Possible Solution
no solution yet

## Test Case and/or Steps to Reproduce (for bugs)
Here is an initial react app with the configuration of our project.
https://github.com/AliNL/foundation-sites-issue

Test Case: 
Should run webpack successfully.

How to reproduce:
1. npm install (it's v6.2 in the package.json currently)
2. npm run bundle (successful)
3. change the version to >= 6.3 and install
4. npm run bundle

## Context
We want to upgrade it because of the high vulnerability issue of jquery.
But currently our project decided to keep using 6.2 for now, and we are working on other priorities.

## Your Environment
- Foundation version(s) used: 6.3.1
- Browser(s) name and version(s): Chrome 71
- Device, Operating System and version: MacOS 10.14
- Link to your project: https://github.com/AliNL/foundation-sites-issue

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi,

can you share a small reproducible test case (a Git repository)?
It seems like your `sass-loader` is not loaded.
Loaders in webpack are loaded from bottom to top so it show be after / under `css-loader` and other loaders for `*.scss` files.

**Comment by DanielRuf** [comment]
And please do not delete the issue template.
Can you edit your comment and add all the relevant details and the steps that you have done (like `npm install` and others)? This would be awesome.

**Comment by AliNL** [comment]
Sorry, I will collect all the info and get back to edit it.
Thanks for your quick response.

**Comment by DanielRuf** [comment]
Hi @AliNL,

Was this resolved or why did you close it?

**Comment by AliNL** [comment]
Hi @DanielRuf, 
I was thinking of reopen it when I have enough information. 
I hope I didn't bother you.

**Comment by DanielRuf** [comment]
Thanks for the link to the demo project. The issue is reproducible. Not sure why this happens but I think it is an issue with the loaders (tehe error also says that).

**Comment by DanielRuf** [comment]
Thanks for the link to the demo project. The issue is reproducible. Not sure why this happens but I think it is an issue with the loaders (the error also says that).

I will investigate this further in the next days (starting this evening).

**Comment by DanielRuf** [comment]
>   Invalid CSS after "&.sl-remove": expected selector, was "(small medium large"

This is because the SassyLists functions are not imported.

The following fixes this:
```
@import '~foundation-sites/scss/foundation';

@include foundation-label;
@include foundation-table;
@include foundation-menu;
@include foundation-flex-grid;
```

See https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/scss/app.scss#L4 and https://github.com/zurb/foundation-sites/blob/develop/scss/foundation.scss#L14

**Comment by DanielRuf** [comment]
Closing as this should be fixed with the right imports.
