### ISSUE TITLE
work on design

### ISSUE THREAD

**Issue by broros** [zurb/foundation-sites#11701]
foundation is very ugly, if you want foundation to be-more successful you need to work more on aesthetics

**Comment by DanielRuf** [comment]
Hi,

Foundation Sites is an enterprise 

https://foundation.zurb.com/

> A Framework for any device, medium, and accessibility. Foundation is a family of responsive front-end frameworks that make it easy to design beautiful responsive websites, apps and emails that look amazing on any device. Foundation is semantic, readable, flexible, and **completely customizable**. We’re constantly adding new resources and code snippets, including these handy HTML templates to help get you started!

https://foundation.zurb.com/sites.html

> **The base styles act as a coded wireframe rather than a final design. Simpler CSS styles allow you to more easily modify them to fit your brand.**

> **Foundation was built to be easily restyled**. You can even customize the framework on download.


It is just a foundation for your projects. You have to apply your design.

https://zurb.com/blog/the-framework-bill-of-rights

**Comment by DanielRuf** [comment]
Hi,

Foundation Sites is an enterprise 

https://foundation.zurb.com/

> A Framework for any device, medium, and accessibility. Foundation is a family of responsive front-end frameworks that make it easy to design beautiful responsive websites, apps and emails that look amazing on any device. Foundation is semantic, readable, flexible, and **completely customizable**. We’re constantly adding new resources and code snippets, including these handy HTML templates to help get you started!

https://foundation.zurb.com/sites.html

> **The base styles act as a coded wireframe rather than a final design. Simpler CSS styles allow you to more easily modify them to fit your brand.**

> **Foundation was built to be easily restyled**. You can even customize the framework on download.


It is just a foundation for your projects. You have to apply your design.

https://zurb.com/blog/the-framework-bill-of-rights

It is also a prototyping framework.
