### ISSUE TITLE
Foundation.MediaQuery.is('breakpoint down')) doesn't work with keyword 'down'

### ISSUE THREAD

**Issue by Lefthandmedia** [zurb/foundation-sites#11713]
## What is missing?

Foundation.MediaQuery.is('medium down')) doesn't work it returns the opposite of what is expected because there is no check on keyword 'down'
...

## What is wrong now ?

Maybe there is a workaround but the documentation mentions the use of 'up' or 'down' so it is to be expected people will use the keyword 'down'
...

## Possible Solution

in foundation.util.mediaQuery.js on line 124 is(size){} there should also be a check on keyword 'down'
...

## Context

im trying to find a range of custom mediaqueries from one custom MQ to smallest
...

## Your Environment

- Foundation version(s) used: 6.4.4-rc1
- Browser(s) name and version(s): all
- Device, Operating System and version: all

## Checklist

- [ x] I have read and follow the CONTRIBUTING.md document.
- [ x] here are no other issues similar to this one.
- [ x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-sites/issues/11122

I think this is a duplicate.

**Comment by Lefthandmedia** [comment]
true, sorry didn't see that one
