### ISSUE TITLE
[Orbit] doesn't slide manually

### ISSUE THREAD

**Issue by miessix** [zurb/foundation-sites#11714]
On previous versions it was possible to slide with a smartphone. This is actually not possible. Even on the documentation page: https://foundation.zurb.com/sites/docs/orbit.html

It was very usefull, so will it be fixed??

**Comment by DanielRuf** [comment]
Please provide the needed information.

It seems ou have deleted our issue template.

**Comment by blendjasper** [comment]
On my phone, I can not swipe Orbit going to the documentation page. I have the same problem on several page builds on a live website.

**Comment by DanielRuf** [comment]
> Please provide the needed information.
> 
> It seems you have deleted our issue template.

**Comment by DanielRuf** [comment]
It seems it worked in RC .3 and is broken since RC .4.
I will do some further bisecting.

**Comment by DanielRuf** [comment]
Seems https://github.com/zurb/foundation-sites/compare/v6.5.0-rc.3...v6.5.0-rc.4#diff-fbf8d86efce458b962f498ea49c8df16 is the cause which may have broken all components with swipe.

cc @ncoden

**Comment by sti-web** [comment]
I have the same issue, an orbit slider doesn't work with swipes events on mobile devices. Just open https://foundation.zurb.com/sites/docs/orbit.html on any touch device and try to swipe the slider, doesn't work :(

**Comment by DanielRuf** [comment]
Hi @sti-web,

i you alreay try https://github.com/zurb/foundation-sites/pull/11716?

**Comment by DanielRuf** [comment]
Hi @sti-web,

did you alreay try https://github.com/zurb/foundation-sites/pull/11716?

**Comment by sti-web** [comment]
@DanielRuf Thanks, #11716 works for me ;)

**Comment by DanielRuf** [comment]
> @DanielRuf Thanks, #11716 works for me ;)

Thanks for testing and the feedback =)
