### ISSUE TITLE
<img> Interchange nested in 'background-image' Interchange fail on iOS 12

### ISSUE THREAD

**Issue by AlexLaforge** [zurb/foundation-sites#11719]
## What should happen?

When specifying a [data-interchange] attribute on a `<img>` tag, the `<img>` [src] attribute should be populated.

## What happens instead?

When this `<img data-interchange>` is nested into a DOM container specifying a [data-interchange] attribute, in charge of changing the 'background-image" attribute, the `<img>` interchange instance does not change the [src] attribute of the `<img>` tag.

## Possible Solution

The nested `<img data-interchange>` conflicts with the parent's [data-interchange] attribute. Therefore, the parent 'background-image' CSS property is set, but the nested `<img data-interchange>` [src] attribute is not set.

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:
1. Include this source code in HTML :

```
<div class="testContainer" data-interchange="[BG-small.jpg, small], [BG-medium.jpg, medium], [BG-large.jpg, large]">
	<img class="testImage" data-interchange="[IMG-small.jpg, small], [IMG-medium.jpg, medium], [IMG-large.jpg, large]">
</div>

```

2. View the page on Safari (iOS 12)

3. The **'.testContainer'** background-image CSS property is changed.

4. The **'.testImage'** [src] attribute is not set.

## Context

N/A

## Your Environment

- Foundation version(s) used: 6.4.3
- Browser(s) name and version(s): iOS 12.0 Safari
- Device, Operating System and version: iPhone SE iOS 12.0
- Link to your project: N/A

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @AlexLaforge,

please provide a working codepen or project where we can reproduce and test this.
Also please make sure if this still occurs with Foundation Sites 6.5.3.

**Comment by AlexLaforge** [comment]
I am sorry, the problem does not come from Foundaiton, but from some custom javascript code of my own, which conflicted.
Consequently, This bug report is null and void.
Again, sorry for this false positive. I am closing this issue now.

**Comment by DanielRuf** [comment]
No problem. Thanks for the clarification and letting us know.

If you face any issues which we can prevent / solve in Foundation Sites, please let us know.
