### ISSUE TITLE
Smooth Scroll works, but not the Options

### ISSUE THREAD

**Issue by pcross1986** [zurb/foundation-sites#11722]
## What should happen?

Here is my markup for a simple link that when clicked, should scroll down to a section with an ID.

`<a href="#google-map" data-smooth-scroll>Directions</a>`

Works as expected...

Id like to edit the options as your documentation states that I have that ability.

**This does not work:**

`<a href="#google-map" data-smooth-scroll data-offset="400">Directions</a>`

## What happens instead?
 I would think the offset would change by 400pixels..... But nothing changes...
...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi, please try
`data-offset=400`

**Comment by DanielRuf** [comment]
It sees you did not fill out our issue template.
