### ISSUE TITLE
White or Reversed Buttons for use on Dark Backgrounds

### ISSUE THREAD

**Issue by mjatharvest** [zurb/foundation-sites#11724]
## What is missing?

Hey there, I would love to use a white Foundation Button over top of a dark background but don't know of any way to do it other than creating more button styles manually.
...

## What is wrong now ?

...

## Possible Solution

Notice how Buzz Feed solid has white modifier classes for their buttons here: https://solid.buzzfeed.com/buttons.html
...

## Context

...

## Your Environment

- Foundation version(s) used: latest
- Browser(s) name and version(s): N/A
- Device, Operating System and version: N/A

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by SassNinja** [comment]
Hi @mjatharvest

Foundation provides all you need to easily create a white button.
You can either adjust/extend `$foundation-palette` or create the styling yourself with the available mixins:

```scss
.button {
    &.white {
        @include button-style(#fff, #ccc, #000);
    }
}
```

The latter is recommended if you only need a white button (the palette is used for much more than buttons)

**Comment by mjatharvest** [comment]
Thanks for the reply @SassNinja 

Do you think that because white buttons on a dark background are potentially a common use case that it merits requesting them to be a core part of Foundation. (Similar to how we have clear and hollow buttons already).

I think they have value, but of course my experience may not be typical.

**Comment by SassNinja** [comment]
Foundation's (default) button names are not related to any color.
There's a primary button, not a blue button.

Thus it's not consistent to implement color specific names in Foundation. Some users may need white buttons, others may need light gray buttons.
I've mentioned the two possibilities above (palette or mixin).
