### ISSUE TITLE
Columns not working in 6.5.1

### ISSUE THREAD

**Issue by KevinWaterson** [zurb/foundation-sites#11725]
## Expected Behavior
Columns to be left and right (side-by-side)
...

## Current Behavior
Columns stacked as rows.

...

## Possible Solution

Works as expected with https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.min.css
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 
https://codepen.io/kevinwaterson/pen/WmgoLW

## Context

A registration and login page, with two forms, one in each column, which collapse to a single column for mobile.

## Your Environment

- Foundation version(s) used:  6.5.1
- Browser(s) name and version(s): Firefox 61.0.1
- Device, Operating System and version: Ubuntu 18.04
- Link to your project:  https://kirtan.fm

- The expected behavior of two columns works when using https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.min.css

## Checklist

- [x ] I have read and follow the CONTRIBUTING.md document.
- [ x] This is a bug report or a feature request.
- [x ] There are no other issues similar to this one.
- [ x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi, the default grid is now the new XY Grid which uses grid / cell.
See https://foundation.zurb.com/sites/docs/grid.html and https://foundation.zurb.com/sites/docs/xy-grid.html and also https://codepen.io/DanielRuf/pen/LaJxer

> From Foundation v6.4, the Float Grid is disabled by default, replaced by the new XY Grid. Unless you need to support IE 10, it is recommended to use the XY Grid.

You might want to use foundation-float.css.
