### ISSUE TITLE
[Off-canvas] Disable the closing on ESCAPE keyDown

### ISSUE THREAD

**Issue by Gianglo** [zurb/foundation-sites#11728]
## Description

I don't find written anywhere how to disable the closing of the off-canvas on ESCAPE keyDown, how can I do that?

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi, this is an accessibility feature and should not be disabled.
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html#kbd_label


Escape | Closes the dialog.
-- | --

**Comment by Gianglo** [comment]
Ok thank you
