### ISSUE TITLE
Slider not dragable on iPad

### ISSUE THREAD

**Issue by asecondwill** [zurb/foundation-sites#11733]
## What should happen?

I should be able to drag the slider around

## What happens instead?
It doesn't drag the slider thumb
...

## Test Case and/or Steps to Reproduce (for bugs)
EDITED:
Add a slider to your app.  See comment below for more detailed instructions. Can recreate it with a simple foundation-rails app wich is probably more helpful than a link to my project.

```
<div class="slider" data-slider data-initial-start="50" data-end="200">
  <span class="slider-handle"  data-slider-handle role="slider" tabindex="1"></span>
  <span class="slider-fill" data-slider-fill></span>
  <input type="hidden">
</div>
```

Demo app:
https://github.com/asecondwill/demosliders
...

## Your Environment
Foundation 6.5.3 via Foundation Rails.
Error happens in firefox simulator for ipads, plus my real ipad ios 12.2

**Comment by asecondwill** [comment]
thiI get an error on line 133 of foundation.util.touch.js

Error is 

> TypeError: touches is undefined on line 133 foundation.util.touch.js

https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.touch.js#L133 

This does seem to be an error as the touches var is declared and used in the same line, which I don't think is possible.

**Comment by asecondwill** [comment]
To recreate you can do these steps

```
rails new slider
cd slider
edit gemfile add these:
```

```
gem 'jquery-rails', '~> 4.3', '>= 4.3.1'
gem 'foundation-rails'
gem 'autoprefixer-rails'
```

then do
`rails g foundation:install`

then edit application.js to add

```
//= require jquery
//= require foundation

```

Then add this to a page
```
<div class="slider" data-slider data-initial-start="50" data-end="200">
  <span class="slider-handle"  data-slider-handle role="slider" tabindex="1"></span>
  <span class="slider-fill" data-slider-fill></span>
  <input type="hidden">
</div>
```

switch to ipad simulator or real and try and move the slider.  Doesn't work. error about touches as above.

**Comment by DanielRuf** [comment]
Duplicate of #11714.
See https://github.com/zurb/foundation-sites/pull/11716

**Comment by DanielRuf** [comment]
Can you try https://github.com/zurb/foundation-sites/pull/11716?

**Comment by DanielRuf** [comment]
Can you share a normal codepen with us?

**Comment by DanielRuf** [comment]
> This does seem to be an error as the touches var is declared and used in the same line, which I don't think is possible.

This is possible. Try `var a = 123, b = a * 2; console.log(b);`

**Comment by DanielRuf** [comment]
Can you try https://github.com/zurb/foundation-sites/pull/11716?

Can you share a normal codepen with us?

> This does seem to be an error as the touches var is declared and used in the same line, which I don't think is possible.

This is possible. Try `var a = 123, b = a * 2; console.log(b);`

Not reproducible in the current docs in Browserstack on an iPhone.

**Comment by asecondwill** [comment]
I resolved this  - It needs jquery 3 to work.  Rails-Jquery was delivering jquery1 by default.
