### ISSUE TITLE
[Orbit] Add init event trigger

### ISSUE THREAD

**Issue by tohvanah** [zurb/foundation-sites#11742]
## What is missing?

Add an event after Orbit slider initialization.

Alternatively instead of a JS event, could just add a "initialized" class to the Orbit element.

## What is wrong now ?

Currently I'm binding to the `beforeslidechange.zf.orbit` event to add a "initialized" class to the Orbit element, in order to apply `height: 100%;` to orbit-slide elements. The problem is that this only fires after the first slide change! I would like to fire after Orbit has done it's initialization.

**Comment by pprossi** [comment]
Maybe the same problem as in https://github.com/zurb/foundation-sites/issues/11743
An orbit init event should be presented by the fondation core plugin loader. 

It works in the unminified Version. 
https://codepen.io/rero/pen/NmoRoa

**Comment by tohvanah** [comment]
Is there documentation for these plugin loader init events? I wasn't aware of them. I do have two concerns with that:

The first may be the same as in #11743: the trigger `init.zf.orbit` does not fire for me

Second, it's critical that I can hook in *after* Orbit has actually initialized sliders, I don't know the mechanics of the plugin loader init events, so this may or may not be a solution. It would be ideal to fire the events on the individual slider elements.

**Comment by pprossi** [comment]
maybe your events are documented in here https://foundation.zurb.com/sites/docs/orbit.html#js-events

I've added an examle to the unminified example of event test.
https://codepen.io/rero/pen/NmoRoa

Obviously some functions stop working after first action as in the tabs, after switching to another tab nothing more happens on the assigned containers. Or in Orbit, only the first slide change is performed and after that the progress seems to be broken.

May be it is a codepen issue, not sure.

**Comment by DanielRuf** [comment]
> May be it is a codepen issue, not sure.


You have forgotten to add Motion UI.
I have forked your codepen and added the CSS file to it. See https://codepen.io/DanielRuf/pen/Ybaqjj

This is also described in the docs and intended:
https://foundation.zurb.com/sites/docs/orbit.html

> Please note that apart from Javascript, Motion UI is a dependency for Orbit to work properly. If in case, you don't want any animations within your Carousel, you can always disable the animation.

**Comment by pprossi** [comment]
Ok, i've updatd the pens.

**Comment by tohvanah** [comment]
> maybe your events are documented in here https://foundation.zurb.com/sites/docs/orbit.html#js-events

The slide change events are documented on the page, but there is no documentation of `init.zf.orbit`. I haven't found documentation of any Foundation `init` events at all.

**Comment by DanielRuf** [comment]
> I haven't found documentation of any Foundation `init` events at all.

They are documented in some. See https://foundation.zurb.com/sites/docs/tooltip.html#js-class and https://github.com/zurb/foundation-sites/blob/eb500f60c2b750653b9297a72c6e2a0ec2812d9a/js/foundation.tooltip.js#L23

The docs are generated from the JS and SCSS components.

**Comment by DanielRuf** [comment]
And compare this to the Orbit components which has only one SassDoc `@fires` annotation https://github.com/zurb/foundation-sites/blob/80cc5700b9c68e69d266ab049c8c2e97f6df0fb7/js/foundation.orbit.js#L310

See the used documentation template: https://github.com/zurb/foundation-docs/blob/34f7beab89610c9a528c46fc6267e92a90a96c93/templates/partials/javascript-reference.hbs#L41

**Comment by DanielRuf** [comment]
And compare this to the Orbit components which has only one SassDoc `@fires` annotation https://github.com/zurb/foundation-sites/blob/80cc5700b9c68e69d266ab049c8c2e97f6df0fb7/js/foundation.orbit.js#L310

See the used documentation partial: https://github.com/zurb/foundation-docs/blob/34f7beab89610c9a528c46fc6267e92a90a96c93/templates/partials/javascript-reference.hbs#L41

**Comment by pprossi** [comment]
got it from the code of 
https://github.com/zurb/foundation-sites/blob/39056a7e821e052c1f7026505a4bbb748996d838/js/foundation.core.plugin.js#L22
https://github.com/zurb/foundation-sites/blob/36fd87851f8975ea26618291777fc180ff564252/js/foundation.core.js#L58
https://github.com/zurb/foundation-sites/blob/39056a7e821e052c1f7026505a4bbb748996d838/dist/js/plugins/foundation.core.js#L241

and more

the documentation is a bit confusing to me as there is 'Tooltip#init'

the foundation core says in registerPlugin function plugin.$element.trigger('init.zf.' + pluginName);

so it seemes to trigger an init event for every plugin on every element.

**Comment by DanielRuf** [comment]
> so it seemes to trigger an init event for every plugin on every element.

Right, but the docs could be better here and also the annotations should be there imo.

**Comment by tohvanah** [comment]
I agree the documentation should describe the `'init.zf' + pluginName` events.

So it appears that, based on the unminified CodePen example, this issue can be closed. I am using the minified scripts in production, so this remains a problem as per #11743.
