### ISSUE TITLE
[Dropdown] Opening dropdown with JS impossible without a data-toggle on another element

### ISSUE THREAD

**Issue by SinusPi** [zurb/foundation-sites#11741]
## Expected Behavior

`<div id="my-dropdown" data-dropdown>I AM A DROPDOWN</div>`
...
`$("#my-dropdown").foundation("open"); // should open the dropdown.`

## Current Behavior

app.js:1 Uncaught TypeError: t.getBoundingClientRect is not a function

## Possible Solution

Adding a data-toggle="my-dropdown" to a random element fixes the problem, but my dropdown is never going to be opened by simply clicking another element, so it's redundant.

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://jsfiddle.net/SinusPi/pw7vn6Lj/2/

## Context

I'm using the Dropdown as a pop up info box, appearing wherever the user interacts with the page. It's positioned dynamically and popped via script, not bound to a button or form field.

## Your Environment

- Foundation version(s) used: 6.x
- Browser(s) name and version(s): Chrome, likely irrelevant
- Device, Operating System and version: Windows, ditto
- Link to your project: 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @SinusPi,

It seems you use Foundation Sites 6.4.3.

Did you also test this with 6.5.3?

**Comment by DanielRuf** [comment]
Hi @SinusPi,

It seems you use Foundation Sites 6.4.3.

Did you also test this with 6.5.3?

**Comment by DanielRuf** [comment]
> To create the dropdown trigger, add data-toggle to a <button>. The value of data-toggle is the ID of the dropdown.

> Dropdown panes are little happy sprites which can be revealed on click or hover.

https://github.com/zurb/foundation-sites/blob/develop-v6.5/js/foundation.dropdown.js#L119
https://github.com/zurb/foundation-sites/blob/develop-v6.5/js/foundation.positionable.js#L124
https://github.com/zurb/foundation-sites/blob/develop-v6.5/js/foundation.util.box.js#L76

Well, the anchor is needed as the pane is bound to a toggle element.

https://github.com/zurb/foundation-sites/blob/develop-v6.5/js/foundation.dropdown.js#L52

**Comment by DanielRuf** [comment]
`<div id="bad-dropdown" data-dropdown data-toggle="bad-dropdown" class="dropdown-pane">I AM A BAD DROPDOWN</div>` works as workaround.

**Comment by SinusPi** [comment]
I guess it wasn't entirely clear to me that the dropdown NEEDS an anchor and won't function without one, seeing as JS makes it possible to pop the dropdown without any anchor clicking. Very well, "working as intended" it is. Thanks for the clarification. :)

I'll now go figure out how to reanchor the dropdown (already figured that out, basically) AND have it open and close on demand, as it's oddly only appearing on exactly every other .foundation("open") call. Cheers.
