### ISSUE TITLE
Version 4 docs broken

### ISSUE THREAD

**Issue by xamount** [zurb/foundation-sites#11749]
## Description

Foundation version 4 documentation is located at https://foundation.zurb.com/sites/docs/v/4.3.2/index.html. If you go there you'll see it it completely broken, it is just a wall of text only, none of the styles/scripts work.
...

## Possible Solution

Please update the v4 docs page to reflect correct location of js and css assets?

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] here are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @xamount,

we are aware of this. So far there are only working Docsets for Zeal, Dash (by Kapeli) and so on.

Also see https://github.com/zurb/foundation-sites/issues/9512
