### ISSUE TITLE
Improve integrations with WordPress Gutenberg editor by separating CSS resets

### ISSUE THREAD

**Issue by oxyc** [zurb/foundation-sites#11740]
## What is missing?

At the moment there's a few CSS reset styles hidden in big mixins that cannot be easily separated without duplicating code. These should be identified and split out to a separate _resets_/_element_ mixin so they can be excluded from stylesheet builds loaded for example into the WordPress Gutenberg page builder editor.

## What is wrong now ?

The WordPress Gutenberg page builder editor allows themes to include theme styles and does this by running the entire stylesheet through postcss and prefixing each selector with a class. This causes a high specificity on some Foundation styles that break the UI of Gutenberg.

After building a theme where I split out the broken parts I've identified the following mixins as problems:

1. [`@mixin foundation-global-styles`](https://github.com/zurb/foundation-sites/blob/92b2f187cd8f9c6b243bf06756beac960dae22df/scss/_global.scss#L136) mixes CSS resets with foundation styling as well as hardcoded opinionated styling.

2. [`@mixin foundation-typography-base`](https://github.com/zurb/foundation-sites/blob/38df69abec71b3dd34afd57315a3ade4cc7b3cf4/scss/typography/_base.scss#L226) likewise mixes resets with styling.

3. [`@mixin foundation-forms`](https://github.com/zurb/foundation-sites/blob/38df69abec71b3dd34afd57315a3ade4cc7b3cf4/scss/forms/_forms.scss#L25) haven't really looked at this, I just excluded it from the editor stylesheet and I don't think there's any other way of fixing it, most of these need to be global to all input elements.

## Possible Solution

I suggest moving the CSS reset parts out of the above mixins so the user can choose to exclude only the resets in a Gutenberg stylesheet build.

In `@mixin foundation-global-styles` move out everything _except_ the following which I consider styling, the rest are resets that could cause havoc when prefixed with a parent selector:

- `html` font-size. This is styling for sure but maybe belongs in the typography mixins?
- `body` styling (the margin and padding I would move out too as I'd class them as resets). This would maybe fit better in the typography mixins too.
- `.is-visible`, `.is-hidden`, definitely styling and should maybe go somewhere entirely different.

In `@mixin foundation-typography-base` again move out all resets and keep only the actual stylings.

## Context

Essentially I'd like to have two stylesheets compiled.

One `frontend.scss` with

```scss
@include foundation-resets;
```

And then one `main.scss` with:

```scss
@include foundation-everything($resets: false);
```

On my last site which used Foundation 6.5.3 I duplicated a lot of the code and did something like this as a quick fix https://gist.github.com/oxyc/622a9b85b48590f517ac1743ec033872

## Your Environment

Foundation 6.5.3 but I've based my comments on the `develop` branch.

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Planned for v7
