### ISSUE TITLE
Error in JS bundled with webpack using Foundation 6.4.4-rc1

### ISSUE THREAD

**Issue by sampathkumarm** [zurb/foundation-sites#11751]
## What should happen?
The same code works fine in Chrome without any issues hence it should also work the same in IE too.
...

## What happens instead?
I get below error when run my website using the webpack bundled JS which is using Foundation 6.4.4-rc1.

```
Error:
SCRIPT1014: Invalid character

Error Detail:
/***/ "./node_modules/foundation-sites/js/foundation.core.js":
/*!*************************************************************!*\
  !*** ./node_modules/foundation-sites/js/foundation.core.js ***!
  \*************************************************************/
/*! exports provided: Foundation */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"Foundation\", function() { return Foundation; });\n/* harmony import */ var
...
```

## Possible Solution
Please provide a the right documentation to import foundation JS in JavaScript modules.

Currently i am importing foundation JS as below:
```
import $ from 'jquery';
global.$ = $;
global.jQuery = $;
import 'foundation-sites';

$(document).foundation();

<MY JS CODE>
...
```

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 6.4.4-rc1
- Browser(s) name and version(s): IE, Chrome
- Device, Operating System and version: Windows 7
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi,

Did you add and configure Babel and use `preset-env` to transpile your code to ES5?

**Comment by DanielRuf** [comment]
Also there are newer relwases, the latest is 6.5.3.

**Comment by DanielRuf** [comment]
Also there are newer releases, the latest is 6.5.3.

**Comment by sampathkumarm** [comment]
Yes, below is my babelrc config
{"presets": ["@babel/preset-env"]}

Yes, I am aware of the latest version. But we are using 6.4.4-rc1 for the project and the team is not ready to update it right now. Hence i need the fix.

**Comment by DanielRuf** [comment]
The fix is to configure `babel-loader`. How does your webpack config look like? `harmony` in webpack is ES6.

**Comment by sampathkumarm** [comment]
Webpack Config Below, Its a very simple one.

const glob = require('glob');
const path = require('path');
const webpack = require('webpack');

module.exports = {
  mode: 'development',
  entry: {
    'innovators': glob.sync('./Websites/Innovation/Assets/theme-innovation/js/**/*.js')
  },
  output: {
    filename: 'app-[name].js',
    path: path.resolve(__dirname, './Websites/Innovation/Assets/theme-innovation/dist')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        loader: 'babel-loader'
      },
    ]
  },
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.$': 'jquery'
    }),
  ]
};

**Comment by DanielRuf** [comment]
Did you also set the needed browserslist for Babel (the `targets`)?

https://babeljs.io/docs/en/babel-preset-env

**Comment by sampathkumarm** [comment]
No, But is it mandatory? If yes what should the setting be?

**Comment by DanielRuf** [comment]
Can you provide a small setup which reproduces this?
Also as far as I know there were also issues in the version that you use regarding treeshaking and transpilation.

**Comment by sampathkumarm** [comment]
Yes you were right, seems to be the issue with the version 6.4.4-rc1. I updated it to 6.5.3 and now it works fine.

**Comment by DanielRuf** [comment]
Hi @sampathkumarm,

Thanks for the feedback that it works now.
I'll close this issue. Feel free to reopen if the new version does not fix your issue.
