### ISSUE TITLE
npm start fails because .eslintrc is missing; ENOENT no such file or directory

### ISSUE THREAD

**Issue by activedecay** [zurb/foundation-sites#11752]
## What should happen?
Following the introduction for running the foundation-sites locally, I hit an error.

`Error: ENOENT: no such file or directory, open '/home/myself/loopy/node_modules/foundation-sites/.eslintrc'

## What happens instead?
No error should be present.

## Possible Solution

echo {} > node_modules/foundation-sites/.eslintrc

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: no test case; it's easy to reproduce.

How to reproduce:
1. npm install foundation-sites
2. cd node-modules/foundation-sites
3. npm install
4. npm start -- this is where the error happens

## Context

Running the foundation-sites documentation site, locally.

## Your Environment

- Foundation version(s) used: latest install from npm at this date
- Browser(s) name and version(s): n/a
- Device, Operating System and version: Ubuntu 16.04
- Link to your project: n/a

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
> * npm install foundation-sites
> * cd node-modules/foundation-sites
> * npm install
> * npm start -- this is where the error happens

Why would you want to do that? npm and yarn already install all the dependencies.
https://unpkg.com/foundation-sites@6.5.3/

The file is not published. Please use the Git remote URL or `zurb/foundation-sites` if you want to develop in a Node module - but this is discouraged.

**Comment by DanielRuf** [comment]
You might want to use https://github.com/zurb/foundation-zurb-template or the Foundation CLI.

**Comment by activedecay** [comment]
That is definitely my oopsie. I misunderstood the documentation; it felt weird `cd`-ing to the node_modules and doing something in there. I misread the readme.md at the root of this project. My mistake
