### ISSUE TITLE
[Base Typography] The terms "heading" and "header" are conflated.

### ISSUE THREAD

**Issue by AndrewKvalheim** [zurb/foundation-sites#11757]
## Expected Behavior

Headings are called [headings](https://www.w3.org/TR/html50/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements).

## Current Behavior

Headings are called [headers](https://www.w3.org/TR/html50/sections.html#the-header-element).

## Possible Solution

Avoid conflating terms.

## Test Case and/or Steps to Reproduce (for bugs)

See the [Base Typography](https://foundation.zurb.com/sites/docs/typography-base.html) documentation.

## Context

The fundamentalness and pervasiveness of this inaccuracy leads me to question the correctness of the entire project. ¹

## Your Environment

n/a

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

---

¹ Reworded; see history.

**Comment by DanielRuf** [comment]
Hi @AndrewKvalheim,

Can you point to the code parts in foundation-sites which are problematic?

If these are SCSS variables we should not change them as this would be a breaking change.

It's a bit comparable to referer vs referrer and other things in tech.

**Comment by AndrewKvalheim** [comment]
> Can you point to the code parts in foundation-sites which are problematic?

I'm not sure what you're asking of me. There's no code involved in this bug report.

  1. The documentation repeatedly makes an embarrassing mistake.
  2. The documentation solicits bug reports from readers.

        > ![screenshot_2019-05-23-0802-38](https://user-images.githubusercontent.com/1844746/58263605-2f2f2880-7d31-11e9-854d-ab9f79cc37cc.png)

  3. I responded to the solicitation.

How you resolve the problem internally is beyond my role here.

I see that the Sass public API is also affected. This problem will not be trivial to solve.

**Comment by DanielRuf** [comment]
> 1. The documentation repeatedly makes an embarrassing mistake.

I do not find it _embarrassing_.

> I see that the Sass public API is also affected. This problem will not be trivial to solve.

Exactly.

> How you resolve the problem internally is beyond my role here.

Well, you can provide a PR and suggest a better wording and doc =)

**Comment by AndrewKvalheim** [comment]
I don't understand why you're treating me like I have some kind of stake in this.

Sorry, but this is not my problem to solve. I've already done you the courtesy of pointing out the metaphorical spinach stuck your teeth. Where you take it from here is up to you.

**Comment by DanielRuf** [comment]
So far no one had an issue with these parts in the docs afaik so I see no real reason to change internal things and the docs =)

**Comment by AndrewKvalheim** [comment]
<details>
<summary>Meta</summary>

In case you're interested in a postmortem on the "too heated" conversation, here's how I interpreted it:

A: The documentation contains a problem.  
D: Please indicate where in the software the problem is located.  
A: No, that's out of scope for me.  
D: I suggest that you volunteer to fix the problem.  
A: No, that's not my job.  
D: Okay.

</details>

**Comment by DanielRuf** [comment]
My biggest problem (@ncoden and I have worked really hard on the last releases) is your feedback:

> This kind of sloppiness undermines my trust in the correctness of the entire project.

Which js not great feedback for us maintainers.

Still, so far the tone in your replies is unnecessary hard.

> Sorry, but this is not my problem to solve. I've already done you the courtesy of pointing out the metaphorical spinach stuck in your teeth. Where you take it from here is up to you.

And I guess you already know that we are very happy when people help us by providing the right solutions as PRs and help us.

As a sidenote: the docs live in all components (they are generated from the js and scss components too) and also from https://github.com/zurb/foundation-docs.

With

> code parts in foundation-sites

I mean https://github.com/zurb/foundation-sites/blob/develop/docs/pages/typography-base.md and https://github.com/zurb/foundation-sites/blob/develop/docs/ in general.

**Comment by DanielRuf** [comment]
My biggest problem (@ncoden and I have worked really hard on the last releases) is your feedback:

> This kind of sloppiness undermines my trust in the correctness of the entire project.

Which is not nice or great feedback for us maintainers.

Please try to understand how that makes us feel. You are free to use any other CSS framework if you think that foundation-sites does not suit your requirements, especially the docs which were written by many people over the last years.

Still, so far the tone in your replies is unnecessary hard.

> Sorry, but this is not my problem to solve. I've already done you the courtesy of pointing out the metaphorical spinach stuck in your teeth. Where you take it from here is up to you.

And I guess you already know that we are very happy when people help us by providing the right solutions as PRs and help us.

As a sidenote: the docs live in all components (they are generated from the js and scss components too) and also from https://github.com/zurb/foundation-docs.

With

> code parts in foundation-sites

I mean https://github.com/zurb/foundation-sites/blob/develop/docs/pages/typography-base.md and https://github.com/zurb/foundation-sites/blob/develop/docs/ in general.

**Comment by DanielRuf** [comment]
> This kind of sloppiness undermines my trust in the correctness of the entire project.

And this undermines my trust that you want to help us but I justu see you blaming us.

Please read our Code of Conduct:
https://github.com/zurb/foundation-sites/blob/develop/code-of-conduct.md which is linked in CONTRIBUTING.md

> Every participant is expected to follow the project's Code of Conduct so please be courteous and respectful.

And you have checked

> I have read and follow the CONTRIBUTING.md document.

Your behavior does not really reflect this imho.

**Comment by DanielRuf** [comment]
And because of such feedback maintainers often stop working on projects.

**Comment by reinhardmohr** [comment]
Hi, DanielRuf,
thanks for helping everybody here! I often got help from these threads and we can be more than glad that people like you offer help for free for a project that we got for free!
Thank you a hundred times

Reinhard

**Comment by JeremyEnglert** [comment]
> I don't understand why you're treating me like I have some kind of stake in this.
> 
> Sorry, but this is not my problem to solve. I've already done you the courtesy of pointing out the metaphorical spinach stuck in your teeth. Where you take it from here is up to you.

You opened the issue. Generally, people who open issues want to see the issue fixed or be involved with the process. This is an open source project that is maintained by the community. 

Honestly, your stake in this is just as high as the maintainers. And if one - seemingly minor mistake - ruins your trust in the entire project, your happy to find another framework to use.

In the meantime, I'm going to close this as I don't see it being fixed in V6 as it would be a rather large breaking change over semantics.
