### ISSUE TITLE
Zurb 'load.' triggers cause 'load' listeners to fire multiple times

### ISSUE THREAD

**Issue by ChadwellD** [zurb/foundation-sites#11766]
## What should happen?
Foundation triggers should not cause unintended listeners to fire on events

## What happens instead?
In jQuery, events with periods in them are namespaced: they trigger things listening on `load.zf.sticky`, but also things listening on `load`.  So effectively this is triggering extra `window.load` events.  Chrome appears to prevent this from working, presumably because multiple `load` events are very unexpected.  But Firefox allows it, so any code that is set to run when a page loads using `window.onload` (like many of the third party scripts my companies site runs) will run multiple times on Firefox.

## Possible Solution
reverse order events.  Instead of `load.zf.sticky` use `sticky.zf.load` or maybe even better `zf.sticky.load` so people must explicitly listen for events in the foundation event namespace to act on them

## Test Case and/or Steps to Reproduce (for bugs)
How to reproduce:
1. use firefox
2.load a foundation sticky and initialize it by triggering a `(window).trigger("load.zf.sticky")`
3.create a function that listens for the window.onload event
4.see that the function will fire on window load and also on the window triggering the sticky

## Context
We use several third party javascript packages in our website, some of them load themselves on the window.onload event.  We're running into a problem where they load themselves multiple times because multiple load events are firing in firefox.

## Your Environment
- Foundation version(s) used:6.4
- Browser(s) name and version(s): firefox latest
- Device, Operating System and version: windows/mac/all 
- Link to your project: 

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @ChadwellD,

thanks for reporting this.

Can you reproduce this in 6.5.3?

**Comment by DanielRuf** [comment]
In general, this is how the events are filtered in jQuery.

**Comment by ChadwellD** [comment]
am I blind or is there not an equivalent for the load.zf.sticky event in the 6.5.3 docs?

**Comment by DanielRuf** [comment]
Ah, I found it. See https://github.com/zurb/foundation-sites/issues/11708

**Comment by DanielRuf** [comment]
Closing as duplicate. You can check the namespace of the event in your listeners.

**Comment by mathiasha** [comment]
@ChadwellD Were you able to find a solution on this issue? We are running in to the same issue after updating from 6.3.0 to 6.6.3.
I quickly tried to update to 6.7.2 but that did not seem to have fixed the issue.

@DanielRuf Is anyone working on this?
