### ISSUE TITLE
(compiling sass) Invalid CSS after "...N THE SOFTWARE."

### ISSUE THREAD

**Issue by Bestulo** [zurb/foundation-sites#11762]
## What should happen?

When I import foundation like this on Vue:

```scss
<style lang="scss">
@import 'sass/_settings.scss';
@import 'sass/foundation-sites/scss/foundation.scss';
</style>
```
I would expect that Foundation is loaded into my website.

## What happens instead?

Instead, I get this error: 

```
Failed to compile.

./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=1!./src/App.vue
Module build failed: 
// Copyright Joyent, Inc. and other Node contributors.
^
      Invalid CSS after "...N THE SOFTWARE.": expected 1 selector or at-rule, was "var getOwnPropertyD"
      in /home/besto/projects/sites/vue/foundation/founcho/node_modules/util/util.js (line 1, column 1)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=1!./src/App.vue 4:14-359 13:3-17:5 14:22-367
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

## Test Case and/or Steps to Reproduce (for bugs)
I'm unable to provide a test case because it's serverside and the error is in the build stage, so there's no web result yet. I uploaded my folder to a [GitHub repo](https://github.com/Bestulo/founcho) in case it's useful for anyone.

How to reproduce:
1. Install nodejs and npm
2. Prepare the vue project folder
`npm i -g vue vue-cli`
`vue init webpack project-name`
`cd project-name`
`npm i -s foundation-sites node-sass sass-loader style-loader`
3. Add the imports to App.vue
&nbsp;
*Note: I moved the foundation-sites folder from `node_modules` into `src/foundation-sites` for easier access from `src/App.vue`*
```scss
<style lang="scss">
  @import 'sass/foundation-sites/scss/settings/_settings.scss';
  @import 'sass/foundation-sites/scss/foundation.scss';
</style>
```
4. Try to compile
`npm run dev`

## Context

I'm trying to build a dynamic e-commerce website and thought that Vue would be the best choice for this, but given these problems, I'm not sure if I should keep going this way or look for another more complicated way that actually works.

## Your Environment

I'm using the latest version of foundation, node 11, vue 3.6.
Link to the Github repo: https://github.com/Bestulo/founcho

## Checklist
- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @Bestulo,

this looks like your sass-loader or config is not correct as these are comments from Node. You probably want to exclude `node_modules` and so on.

So far this is not a direct bug in Foundation Sites.

**Comment by Bestulo** [comment]
Alright. I guess this issue should be closed. Do you know how to configure that? I've been googling but I haven't found proper results. Thank you for your advice.

**Comment by DanielRuf** [comment]
I have no experience with Vue so I would have to debug this using the linked repo.

**Comment by Bestulo** [comment]
Thank you for your time. I'll switch to Vuetify for now as I can't find a way to solve the problem.

**Comment by WrapTheCode** [comment]
Solved by:

1. Remove 
`@import 'util/util'; `
**from " _settings.sass"**

2. Move
`@import 'util/util';`
before
`@import 'settings/settings';`
**in "foundation.scss:**

3. And in my sass entrypoint:
```
@import '~foundation-sites/scss/foundation';
@import '~motion-ui/src/motion-ui';
@include foundation-everything;
@include motion-ui-transitions;
@include motion-ui-animations;
```

**Comment by gwenevieve** [comment]
@WrapTheCode This worked for me! Using WordPress w/ Webpack 4 + Foundation. Cheers!

**Comment by alexkuc** [comment]
Alternatively, you can include path to `…/node_modules/foundation-sites/…` to have shorter import statements in your `scss` files:

```javascript
{
  loader: 'sass-loader',
  options: {
    sassOptions: {
      includePaths: [
        './node_modules/foundation-sites/scss',
      ],
    },
  },
},
```

Then you import `foundation` like so:

```javascript
@import '_settings'; // file in your src/ i.e. src/_settings.scss
@import 'foundation'; // node_module/
```

**Comment by lexprimost** [comment]
simply replace

- `@import 'util/util';`
  **`from _settings.scss`**
by
- `@import '~foundation-sites/scss/util/util';`

Never modify the package's file directly because, you changes will be replaced when package get updated

**Comment by DanielRuf** [comment]
@lexprimost it's because of the missing includePaths setting.
