### ISSUE TITLE
Foundation css validation errors

### ISSUE THREAD

**Issue by anaelleltd** [zurb/foundation-sites#11773]
## What should happen?

I have made some amendments to the app.css file of my Foundation 6 Zurb template through the settings.scss AND a separate .scss file.

## What happens instead?

It all compiles and runs without problems, however, the CSS validator (W3C) throws an error: "too few values for the property [width]".

## Possible Solution

I have looked at the app.css and the error is locate on this line: 
**@media screen and (min-width: 0\0) {**

Am I right to think that the CSS hack introduced in Foundation 6 is not yet recognised by the W3C standardised automated tools?

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

I don't want to ignore this issue because there are some irregularities in media queries that affect the rendering of my topbar nav when browsing with IE...
[CSSerrorvalidation.zip](https://github.com/zurb/foundation-sites/files/3269294/CSSerrorvalidation.zip)

## Your Environment

- Foundation version(s) used: Foundation 6
- Browser(s) name and version(s): IE 11.765.17134.0
- Device, Operating System and version: Windows 10 64-bit
- Link to your project: N/A (local host)

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.
THANK YOU! :)

**Comment by DanielRuf** [comment]
Hi @anaelleltd,

Which exact version of Foundation Sites 6 do you use?

**Comment by DanielRuf** [comment]
Hi @anaelleltd,

See http://browserbu.gs/css-hacks/media-min-width-0-backslash-0/, so IE is still affected and needs this. The code is automatically generated.

**Comment by DanielRuf** [comment]
Please provide some infos about which exact check and settings including profile you use at https://jigsaw.w3.org/css-validator/#validate_by_uri+with_options

**Comment by anaelleltd** [comment]
Hi DanielRuf,

Thanks for the info.
I used the basic settings of CSS validator (see snip attached).

Cheers! :)
![CSSerror Foundation6 validatorsettings](https://user-images.githubusercontent.com/44770354/59158673-35265700-8af0-11e9-9576-d95b4f5c4812.JPG)

**Comment by DanielRuf** [comment]
In general you can ignore it as it is a valid browserhack.

**Comment by anaelleltd** [comment]
Thanks a lot for the follow up.
I'm closing the issue.  :)
