### ISSUE TITLE
Accordion CSS dependency?

### ISSUE THREAD

**Issue by Gilipe** [zurb/foundation-sites#11774]
## What should happen?

The accordion should still have the JS events fired, whether the accordion is styled or not.

## What happens instead?

Nothing. No classes added or removed.

## Possible Solution

I searched online and couldn't really find a reason/explanation as to why or how the CSS is required/a dependency. Don't have the CSS as a dependency.

## Test Case and/or Steps to Reproduce (for bugs)

https://codepen.io/Gilipe/pen/ProweL

## Context

I still want the expected default functionality while applying my own design to the accordion (without having to remove with a find comb/override CSS).

## Your Environment

- Foundation version(s) used: Latest
- Browser(s) name and version(s): Google Chrome, Latest
- Device, Operating System and version: MBP, MacOS, Latest

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @Gilipe,

which events do you mean?

**Comment by DanielRuf** [comment]
Hi @Gilipe,

a normal accordion works. See https://codepen.io/DanielRuf/pen/pXoJNP

What you use is the responsive accordion tabs element which has to check the current mediaquery using a CSS font rule. See https://github.com/zurb/foundation-sites/blob/develop/js/foundation.responsiveAccordionTabs.js#L4 and https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.mediaQuery.js#L97 and also https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.mediaQuery.js#L113

**Comment by DanielRuf** [comment]
https://foundation.zurb.com/sites/docs/media-queries.html#javascript

> The MediaQuery utility uses the Sass breakpoint settings and requires the Foundation CSS to be imported. For Sass users, you need to include either foundation-everything() or foundation-global-styles().

**Comment by rafibomb** [comment]
I would categorize this as a feature request. An accordion with no styles kind-of defeats the purpose of  a framework. The CSS is required to show and hide the containers of the accordion.

I can a need for being able to use any HTML elements (which is a feature) and having it minimally styled. Maybe this is more of a Foundation 7 direction.

**Comment by Gilipe** [comment]
@DanielRuf Sorry but that's not really answering why the JS would not function without CSS in place, at least for the accordion. It's adding/removing classes, why is CSS a dependency here? https://codepen.io/DanielRuf/pen/pXoJNP First accordion doesn't work at all, 2nd accordion click **Accordion 1**, then **Accordion 3** as an example. I'd get it if both 1/2 slid up/closed but it feels like weird/unexpected/buggy behaviour.

@rafibomb But *why* is the CSS required for the JS to function? It's not a feature request, I just don't understand why a visual representation is required for JS to work behind the scenes. In my example at least, it just flat out doesn't work without the foundation CSS.

> I can see a need for being able to use any HTML elements (which is a feature) and having it minimally styled. 

How about just not styled at all, if the CSS is supposed to handle the visuals and JS is adding active states, allow the user to decide **how** the accordion looks without having to fight/overwrite against the default CSS.

**Comment by Gilipe** [comment]
I'm still not understanding the difference, why would the responsive accordion break without CSS? DOM events should still occur, no?

**Comment by DanielRuf** [comment]
Hi @Gilipe,

Please see https://github.com/zurb/foundation-sites/issues/11774#issuecomment-500611600

**Comment by Gilipe** [comment]
Hey @DanielRuf,

Thanks for helping out with this.

I've updated my codepen to have one with the *data-responsive-accordion-tabs* and *data-accordion*. 

*data-accordion* still has events fire off, CSS or not. But not *data-responsive-accordion-tabs* without CSS.

https://codepen.io/Gilipe/pen/ProweL

**Comment by DanielRuf** [comment]
> data-accordion still has events fire off, CSS or not. But not data-responsive-accordion-tabs without CSS.

Because the responsive utility methods initialize the needed components and registers the needed event listeners so this is expected.

**Comment by Gilipe** [comment]
1 more question for clarification and then I'll mark this topic closed, but I'm still confused why if I removed *only* the CSS styling, it stops the JS from working?

> Because the responsive utility methods initialize the needed components and registers the needed event listeners so this is expected.

This just doesn't answer that question. Sorry for my ignorance.

**Comment by DanielRuf** [comment]
As explained in https://github.com/zurb/foundation-sites/issues/11774#issuecomment-500610783, the current Foundation breakpoint settings are set as font-family and read by the JS utilities. The JS part does not have the breakpoint setting which is generated from _settings.scss.

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/develop/dist/css/foundation.css#L434-L435
