### ISSUE TITLE
Button margin-bottom should scale with button size classes.

### ISSUE THREAD

**Issue by scottsawyer** [zurb/foundation-sites#11775]
## What is missing?
$button-margin defaults to 0 0 $global-margin 0.  To me, this doesn't make sense for all button sizes to use the same bottom margin.  Rather, I think it should scale with the size of button.  
...

## What is wrong now ?
If the $global-margin is 1em, 16px, then a .tiny button has a margin-bottom of 1em ( 16px ).  $button-sizes defaults to 0.6rem,  the .tiny margin-bottom should be 0.6rem as well.  

...

## Possible Solution

```
@mixin foundation-button {
  .button {
    @include button;

    // Sizes
    @each $size, $value in map-remove($button-sizes, default) {
       &.#{$size} {
          font-size: $value;
          margin-left: calc(get-side($button-margin, left) * $value);
          margin-right: calc(get-side($button-margin, right) * $value);
          margin-bottom: calc(get-side($button-margin, bottom) * $value);
          margin-top: calc(get-side($button-margin, top) * $value);
          }
      }
  }
}
```
Completely untested, probably a better approach, but what the thought process is, if a .tiny button is 60% smaller than a normal button, so to should it's margin.
...

## Context
Adding a tiny button inline with some small text is throwing it's visual alignment off, it's just weird to work around.
...

## Your Environment

- Foundation version(s) used: 6.5.3

## Checklist

- [X] I have read and follow the CONTRIBUTING.md document.
- [X] here are no other issues similar to this one.
- [X] The issue title and template are correctly filled.

**Comment by rafibomb** [comment]
What if buttons had no margin bottom?

**Comment by JeremyEnglert** [comment]
> To me, this doesn't make sense for all button sizes to use the same bottom margin. Rather, I think it should scale with the size of button.

I disagree. Bottom margins needs to stay consistent otherwise the vertical flow feels off. 

I don't think this is worth changing at this point.

**Comment by rafibomb** [comment]
In my experience implementing over 50 designs in code, there is almost never a consistent margin bottom for buttons.

**Comment by JeremyEnglert** [comment]
> In my experience implementing over 50 designs in code, there is almost never a consistent margin bottom for buttons.

Is that a design choice we want to make as a framework? Maybe it is.

Personally, I like knowing that all of my buttons are going to keep consistent margins as I use them. Especially inside content areas. But I see the argument for either way.

But I don't think it's a change we'd make in 6. But maybe open for discussion in 7?

**Comment by rafibomb** [comment]
No - I agree with your first statement to leave it as is.
