### ISSUE TITLE
[Accordion] List items (<li>) are not contained within <ul> or <ol> parent elements.

### ISSUE THREAD

**Issue by philiprabbett** [zurb/foundation-sites#11778]
## What should happen?
Using the example markup (https://foundation.zurb.com/sites/docs/accordion.html) the `ul` has a `role` attribute added as does the `a` attribute and the `data-tab-content` container. Running an audit on the markup should be ok. (Running an audit using chrome developer tools)
...

## What happens instead?
Audit returns the following:
> List items (`<li>`) are not contained within `<ul>` or `<ol>` parent elements.

...

## Possible Solution

> What you need to do is set role="presentation" on all the structures that are not one of the tablist specific roles.
> - https://stackoverflow.com/a/27475768

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: https://foundation.zurb.com/sites/docs/accordion.html

How to reproduce:
1. Open Developer Tools in Chrome
2. Navigate to the Audits tab
3. Run Audit for mobile

## Context

To improve the experience of reading tabular or list data using assistive technology, like a screen reader.
...

## Your Environment

- Foundation version(s) used: 6.5.1
- Browser(s) name and version(s): Google Chrome Version 75.0.3770.80 (Official Build) (64-bit)
- Device, Operating System and version: Macbook Pro, MacOS Mojave 10.14.3
- Link to your project: N/A

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @philiprabbett,

in general they are in a `ul`, see

![image](https://user-images.githubusercontent.com/827205/59358966-ce8e7c80-8d2d-11e9-8d42-667450049db0.png)

Also see https://github.com/zurb/foundation-sites/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aaccessibility and https://github.com/zurb/foundation-sites/issues/11659

Which has a related PR at https://github.com/zurb/foundation-sites/pull/11681

I am not an a11y expert so I linked @Owlbertz who is an expert in this and who should decide this with the others too.

I am going to close this as duplicate. Please try to check if there is already a related issue or PR when you create an issue.
