### ISSUE TITLE
Need to update package.json file for Foundation for Emails to work - Bug and Solution 

### ISSUE THREAD

**Issue by dtlevin** [zurb/foundation-sites#11786]
## What should happen?

npm install should install npm

## What happens instead?

install npm breaks and nothing installs
...

## Possible Solution

in the package.json file you need to change 
this     
"gulp": "git+https://github.com/gulpjs/gulp.git#4.0",
to this 
"gulp": "4.0",
...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.run the foudation cli to set up a new email template
2. cd into the new directory and run npm install
3. watch install break

## Context

create email templates
...

## Your Environment

- Foundation version(s) used: 2.2.5
-  Browser(s) name and version(s): Chrome 
- Device, Operating System and version: Mac OS Mojave 
- Link to your project: n/a

## Checklist

- [ x] I have read and follow the CONTRIBUTING.md document.
- [ x] There are no other issues similar to this one.
- [ x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @dtlevin,

Please check the other issues. Afaik we have multiple issues about this.

The gulp devs deleted the tag.

See https://github.com/zurb/foundation-emails/issues.

The right solution is `"gulp": "^4.0.0"`.
