### ISSUE TITLE
Current page in pagination is hidden on mobile devices

### ISSUE THREAD

**Issue by sashabeep** [zurb/foundation-sites#11784]
## What should happen?

Current pagination page should always be visible

## What happens instead?

Only previous/next links is shown

## Possible Solution

addition to my app.css
```css
.pagination .current{
	display: inline-block;
}
```
![fixed](https://user-images.githubusercontent.com/5689796/60537555-78e83700-9d11-11e9-9ec6-28c5567ce7bd.png)

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:
1. Download any build from https://foundation.zurb.com/sites/download.html/
2. Paste sample code from https://foundation.zurb.com/sites/docs/pagination.html
3. Change window size to mobile

## Context

Our website users didn't see the current page in pagination, which is should be highlighted
![unfixed](https://user-images.githubusercontent.com/5689796/60537539-71c12900-9d11-11e9-8dac-b180dffd156f.png)

## Your Environment

any browser/os 

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @sashabeep,

It seems the setting `$pagination-mobile-current-item` is not set to `true` by default.

See https://github.com/zurb/foundation-sites/blob/develop/scss/components/_pagination.scss#L107 and https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss#L547

**Comment by sashabeep** [comment]
> Hi @sashabeep,
> 
> It seems the setting `$pagination-mobile-current-item` is not set to `true` by default.
> 

What's about online customizer?

**Comment by DanielRuf** [comment]
There are not many options as you can see: https://foundation.zurb.com/sites/download.html/#customizeFoundation

The current solution would be to use the Sass version. The defaults are documented as `false`.

**Comment by rafibomb** [comment]
Or some CSS will work, like 

```
.pagination li {
  display: inline-block;
}
```

https://codepen.io/rafibomb/pen/BgxOLV?editors=1100
