### ISSUE TITLE
Your whole foundation.zurb website is going down

### ISSUE THREAD

**Issue by jackelynkjerstie** [zurb/foundation-sites#11783]
## What should happen?
I should be able to access your website and building blocks and internal links
...

## What happens instead?
I get sent to a 502 bad gateway page
...

## Test Case and/or Steps to Reproduce (for bugs)
Just try and access your website none of the links are working

How to reproduce:
1. https://foundation.zurb.com/
2. you will get the 502 bad gateway
3.

## Context
really hard to use your wonderful foundation when I can't get to documentation or anything

## Checklist

- [x ] I have read and follow the CONTRIBUTING.md document.
- [ x] There are no other issues similar to this one.
- [ x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @jackelynkjerstie,

I can not reproduce this. Does it still happen for you?

Related: https://techcrunch.com/2019/07/02/a-cloudflare-outage-is-impacting-sites-everywhere/

See https://bgp.he.net/dns/foundation.zurb.com#_ipinfo

**Comment by jackelynkjerstie** [comment]
Hi Daniel,

It looks like it's been resolved. Thank you for your help
