### ISSUE TITLE
Approval with remarks pop up goes in backgroud IE 11 in windows 8

### ISSUE THREAD

**Issue by bhiseweb** [zurb/foundation-sites#11781]
Steps to reproduce

    Step 1
    Open any PO where Invoice is already uploaded
    Click on Preview
    Step 2
    Click on Approval with Remarks

Expected Behaviour

                Pop up should come in foreground in IE 11

Actual Behaviour

                Pop up is coming  in backgound in IE 11

image:
![image](https://user-images.githubusercontent.com/31177960/60186114-cf083680-9848-11e9-8aa2-c42f504c2725.png)

**Comment by DanielRuf** [comment]
Hi @bhiseweb,

thanks for creating the issue.
Unfortunately you did not use our issue template so we miss many important information (the used version of Foundation Sites, a codepen with a siple reduced and reproducible testcase and so on).

Please edit your issue description and add the needed information.

**Comment by SassNinja** [comment]
> Steps to reproduce
> 
> Step 1
> Open any PO where Invoice is already uploaded
> Click on Preview
> Step 2
> Click on Approval with Remarks

How the hell are we supposed to be able to reproduce that?!

1. as @DanielRuf said don't just delete the issue template and provide code to reproduce (codepen preferred)
2. use the framework's component name (your `pop up` probably means `reveal`)

Otherwise we cannot help you!

**Comment by rafibomb** [comment]
Not sure if this is even related to Foundation. If it is, please open a new issue and follow this issue template. Thanks!
