### ISSUE TITLE
How to Choose Template for creating a wordpress website ?

### ISSUE THREAD

**Issue by Vishnu93939** [zurb/foundation-sites#11799]
## Expected Behavior

...

## Current Behavior

...

## Possible Solution

...

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1.
2.
3.

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 
- Link to your project: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] This is a bug report or a feature request.
- [ ] There are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @Vishnu93939,

please fill out the issue template.
Foundation Sites is a standalone framework. There is no template for creating a WordPress website as this is not part of the things that we provide.

There are many WordPress themes which use Foundation Sites.
