### ISSUE TITLE
Release 6.5.3 missing normalize

### ISSUE THREAD

**Issue by jgomesmv** [zurb/foundation-sites#11793]
## What should happen?

The normalize dependency should be part of the vendor dependencies.
Is it supposed to? 

## What happens instead?

It's no longer part of the foundation npm package

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:
1 - Install the foundation-sites package: npm install foundation-sites
2 - Run the app and the normalize import fails: @import "../node_modules/foundation-sites/_vendor/normalize-scss/sass/normalize";

## Your Environment
- Foundation version(s) used: 6.5.3
- Browser(s) name and version(s): Chrome Version 75.0.3770.142 (Official Build) (64-bit)
- Device, Operating System and version: Windows 10
- Tech Stack: Angular 8.1.2

**Comment by DanielRuf** [comment]
Hi @jgomesmv,

The vendor dir is not part of the distribution package.

**Comment by DanielRuf** [comment]
Hi @jgomesmv,

Thanks for reporting this. We will check this.

**Comment by DanielRuf** [comment]
Hi @jgomesmv,

Thanks for reporting this. We will check it.

**Comment by blynnc** [comment]
Addendum:

http://necolas.github.io/normalize.css/
Version 8.0.1 is the current version

Foundation 6.5.3 is using 
/*! normalize.css v8.0.0 | MIT License | github.com/necolas/normalize.css */
html {

@charset "UTF-8";
/**
 * Foundation for Sites by ZURB
 * Version 6.5.3 (It is so nice to have the version number here!)
 * foundation.zurb.com
 * Licensed under MIT Open Source
 */
@media print, screen and (min-width: 40em) {
  .reveal, .reveal.tiny, .reveal.small, .reveal.large {
    right: auto;
    left: auto;
    margin: 0 auto; } }

/*! normalize.css v8.0.0 | MIT License | github.com/necolas/normalize.css */
html {

**Comment by DanielRuf** [comment]
We include normalize as node_module. See https://github.com/zurb/foundation-sites/blob/develop/scss/vendor/normalize.scss

You should be able to find it in the local directory, see https://unpkg.com/browse/foundation-sites@6.5.3/scss/vendor/

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/blob/develop/scss/vendor/normalize.scss

You should be able to find it in the local directory, see https://unpkg.com/browse/foundation-sites@6.5.3/scss/vendor/

**Comment by DanielRuf** [comment]
This was changed about 1 year ago and there should be no reference to the old normalize file in the root _vendor folder.

See https://github.com/zurb/foundation-sites/commit/6e72435b29d7b75be91e7ea5c256efc126392b7f

**Comment by jgomesmv** [comment]
Yes you are correct I just checked the file path scss/vendor/normaliza.scss and the file it's there, but for some reason some foundation styles are not being loaded on my angular solution.

Like this on an anchor tag:
![image](https://user-images.githubusercontent.com/8100887/62043351-05462680-b1f8-11e9-9e63-8f378cb0b93a.png)


I'm loading the foundation.scss and my settings file after:
![image](https://user-images.githubusercontent.com/8100887/62043284-e0ea4a00-b1f7-11e9-8402-6ccac81a73f8.png)

Am I doing something wrong?

**Comment by DanielRuf** [comment]
> Like this on an anchor tag:

Did you add these? It looks like they are applied.

**Comment by jgomesmv** [comment]
No. This is an example in another solution were we are also using foundation-sites :)

**Comment by DanielRuf** [comment]
So far it is still there in scss/vendor, see https://unpkg.com/browse/foundation-sites@6.5.3/scss/vendor/ and it's still part of the released files.

https://unpkg.com/browse/foundation-sites@6.5.3/dist/css/foundation.css

**Comment by DanielRuf** [comment]
Can you try the following?

https://foundation.zurb.com/sites/docs/sass.html#adjusting-css-output

https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/scss/app.scss

**Comment by DanielRuf** [comment]
Also can you share the full error regarding
> Run the app and the normalize import fails: @import "../node_modules/foundation-sites/_vendor/normalize-scss/sass/normalize";

Because this should not be referenced anywhere.

**Comment by DanielRuf** [comment]
Also can you share the full error regarding
> Run the app and the normalize import fails: @import "../node_modules/foundation-sites/_vendor/normalize-scss/sass/normalize";

Because this should not be referenced anywhere.

**Comment by DanielRuf** [comment]
Closing as inactive. If the issue still exists, please let us know and we'll reopen it.
