### ISSUE TITLE
No mixin included in a bootstrapped foundation basic template project.

### ISSUE THREAD

**Issue by justinemar** [zurb/foundation-sites#11807]
## What should happen?
Should have mixins included inside `app.scss` but only got these two imports
`@import "settings";
@import "foundation";`
...

## What happens instead?
No mixin is included inside `app.scss` , including a mixin throws an error.
```
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: client\assets\scss\app.scss
Error: no mixin named foundation-global-styles

       Backtrace:
        client/assets/scss/app.scss:3
        on line 3 of client/assets/scss/app.scss
>> @include foundation-global-styles;
   ---------^
```

This is a basic template generated by `foundation-cli`.
Is this an expected behaviour?? How do i resolve this?

**Comment by DanielRuf** [comment]
Hi @justinemar,

which steps did you took and which exact template do you use?

The ZURB template has these, see https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/scss/app.scss

**Comment by justinemar** [comment]
> Hi @justinemar,
> 
> which steps did you took and which exact template do you use?
> 
> The ZURB template has these, see https://github.com/zurb/foundation-zurb-template/blob/master/src/assets/scss/app.scss

I followed the `foundation-cli` installation and proceeded to create a new project using the basic template.
https://foundation.zurb.com/sites/docs/installation.html 
I tried to re-install and still having the same behaviour.

**Comment by DanielRuf** [comment]
Do you mean https://github.com/zurb/foundation-sites-template/blob/master/scss/app.scss?

**Comment by justinemar** [comment]
> Do you mean https://github.com/zurb/foundation-sites-template/blob/master/scss/app.scss?

Yes this one and i chose the basic template

**Comment by DanielRuf** [comment]
Please create a small reproducible testcase repository so we can reproduce it with your configuration and setup.

**Comment by DanielRuf** [comment]
> Yes this one and i chose the basic template

This is the basic template afaik. These two repos are used for the CLI projects.

**Comment by DanielRuf** [comment]
Closing as we did not receive the needed information so far. Also please use our original issue template.

Please let us know when you have new information for us and we will reopen it.
