### ISSUE TITLE
Compiling foundation.scss for a static page, but the compiled foundation.css is empty

### ISSUE THREAD

**Issue by besseddrest** [zurb/foundation-sites#11808]
## What should happen?

Download scss files and compile manually, new css file should contain all compiled SCSS

## What happens instead?

I downloaded the latest tar.gz, and copied the files to a directory named scss/foundation for a static page I'm creating. I also included the _vendor directory as a sibling to scss/foundation.

When I compile the file with:
```
sass --watch scss/foundation/foundation.scss:css/fdn.css
```

My new fdn.css file doesn't contain any css:
```
/**
 * Foundation for Sites by ZURB
 * Version 6.5.3
 * foundation.zurb.com
 * Licensed under MIT Open Source
 */

/*# sourceMappingURL=fdn.css.map */
```

I was also able to replicate this simply by compiling the scss folder within the extracted folder.

Can the SCSS files only be used in a project that uses a bundler?

## How to reproduce:
1. download the latest Foundation version
2. compile the contents of the scss folder to a new CSS file
3. open the new CSS, it will contain no rules

## Context

I'm developing a simple page for a client and doing so with just a simple file structure: index.html, css & scss directories. The index.html file includes the path to the compiled css file.

## Your Environment

- Foundation version(s) used: latest 
- Browser(s) name and version(s): Chrome
- Device, Operating System and version: macOS Mojave

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi besseddrest,

Did you check the config file for the needed dependencies?

https://github.com/zurb/foundation-sites/blob/develop/gulp/tasks/sass.js

https://github.com/zurb/foundation-sites/blob/develop/gulp/config.js#L28

Normally you should run `npm install` or `yarn` and then have them.

**Comment by DanielRuf** [comment]
Hi @besseddrest,

Did you check the config file for the needed dependencies?

https://github.com/zurb/foundation-sites/blob/develop/gulp/tasks/sass.js

https://github.com/zurb/foundation-sites/blob/develop/gulp/config.js#L28

Normally you should run `npm install` or `yarn` and then have them.

**Comment by besseddrest** [comment]
I already have sass installed, and when I use it on my other site files like app.scss it compiles fine to app.css.

If I didn't, then I think my terminal would throw an error and tell me I don't have it installed, or just simply not know how to interpret the command `sass`.

**Comment by DanielRuf** [comment]
I do not mean sass but sassy-lists and more from `node_modules` which are needed.

**Comment by DanielRuf** [comment]
The steps to reproduce are missing some important details.

> download the latest Foundation version

Which exact variant, how and from where? Did you use `git clone`? Did you use the Foundation CLI?

See https://foundation.zurb.com/sites/download.html/

**Comment by besseddrest** [comment]
@DanielRuf I just downloaded the Source Code (tar.gz) v6.5.3 here:
https://github.com/zurb/foundation-sites/releases/tag/v6.5.3

It looks like everything works correctly by compiling /assets/foundation.scss instead of /scss/foundation.scss.

Problem solved!
