### ISSUE TITLE
Gulpfile.js is not compile my custom SCSS codes.

### ISSUE THREAD

**Issue by ntdvl** [zurb/foundation-sites#11805]
I have some problem Foundation CLI. My custom SCSS codes does not compile by Gulpfile.js. Interestingly, when I make changes in any HTML files or Foundation's own SCSS files, files is quickly compiling. However, when I write my own SCSS code, it doesn't compiling. Probably there is some problem my gulpfile.js

I use Foundation CLI version 2.2.5, node is v10.16.1.

Gulpfile.js
var gulp          = require('gulp');
var browserSync   = require('browser-sync').create();
var $             = require('gulp-load-plugins')();
var autoprefixer  = require('autoprefixer');

var sassPaths = [
  'node_modules/foundation-sites/scss',
  'node_modules/motion-ui/src'
];

function sass() {
  return gulp.src('scss/app.scss')
    .pipe($.sass({
      includePaths: sassPaths,
      outputStyle: 'compressed' // if css compressed **file size**
    })
      .on('error', $.sass.logError))
    .pipe($.postcss([
      autoprefixer({ Browserlists: ['last 2 versions', 'ie >= 9'] })
    ]))
    .pipe(gulp.dest('css'))
    .pipe(browserSync.stream());
};

function serve() {
  browserSync.init({
    server: "./"
  });

  gulp.watch("scss/*.scss", sass);
  gulp.watch("*.html").on('change', browserSync.reload);
}

gulp.task('sass', sass);
gulp.task('serve', gulp.series('sass', serve));
gulp.task('default', gulp.series('sass', serve));

**Comment by DanielRuf** [comment]
I think you already posted this on StackOverflow.
Please prevent cross-posting and use our issue template.

https://stackoverflow.com/questions/57528370/why-my-gulpfile-js-doesnt-compile-only-my-custom-scss

Please edit your post and include a link to a repo which reproduces it.
