### ISSUE TITLE
State Of Branches - Updates and Unverified Commits

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites#11803]
Question.  I want to update my branch with the latest version of the master branch. In investigating / comparing  commits -- I see  that some commits have been verified and several that have not been verified.

Is it wise to merge unverified commits to my branch ? What does verified mean really ? Who or whom are the verificators - Are there official Yetinauts ?

...

## Possible Solution

...

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] here are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
Hi @blynnc,

The verified means only that these were digitally signed using PGP. Either by GitHub when the website is used or by the user when Git is configured to sign every commit.

See https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work and https://help.github.com/en/articles/signing-commits

We do not enforce or check this.

Please also use the `develop` branch as this is our default (master) branch.

**Comment by DanielRuf** [comment]
It makes not much difference and you can safely pull all commits.
It just prevents impersonification and additional security in some context and when everyone signs their commits (manipulated commits by others would be visible when the used signing key or verified status would change).

**Comment by DanielRuf** [comment]
Closing as resolved. If your questions are not answered, please let us know.
