### ISSUE TITLE
Specific breakpoint XY Grid alignment

### ISSUE THREAD

**Issue by mihail-minkov** [zurb/foundation-sites#11815]
## What is missing?

What I am referring to is the specific grid alignment option `align-center`, `align-right`, `align-left`. While those work fine, I haven't found breakpoint specific classes for this. 

For example `align-center medium-align-left large-align-right`.

## What is wrong now ?

If I use `align-center medium-align-left` on a parent element it sets:

```
   -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
```
for all breakpoints because the breakpoint specific class doesn't exist. I have to manually add the medium-align-right and force it for the breakpoints.

## Possible Solution

Combine the breakpoint class generation with these alignment classes so we can have predefined alignment classes for specific viewports.

## Your Environment

- Foundation version(s) used: Foundation for Sites 6.5.1 using the foundation-cli
- Browser(s) name and version(s):  Chrome 76.0.3809.132 64-bit
- Device, Operating System and version: WIndows 10 Enterprise 1809

**Comment by DanielRuf** [comment]
Hi @mihail-minkov,

You can use the [`flex-align`](https://github.com/zurb/foundation-sites/blob/develop/scss/util/_flex.scss#L37) mixin or directly `justify-content`.

> The horizontal alignment classes are shorthands for the justify-content CSS property. Learn more about justify-content.

**Comment by blynnc** [comment]
Viewports are subjective and constantly evolving, therefore in my opinion specificity in this day and age is subjective. Sure, there are a few standards --- and the existing foundation breakpoints work well for me -  however,  for those anomalies, I just add my own breakpoints depnding on what my content dictates.

**Comment by DanielRuf** [comment]
And this is perfectly fine. Foundation is not meant to cover every edge-case. You should still write CSS for them. And you can add more breakpoints in the scss version.

**Comment by DanielRuf** [comment]
Closing as the mixin is meant to be used here. General utility classes are just simple helpers.
