### ISSUE TITLE
feature request: srcset / interchange background images set in CSS

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites#11812]
## What is missing?

How the feature should work / how you would use it ?

Background images established in css or scss.

1 - The contain, cover, object-fit, percentage and so forth  methods to responsively size  background images for different screen sizes /devices
that are established in CSS / SCSS code lacks finessse.

2 -  Using media queries is one-way to do it and thats ok - but
there's got to be an easier way -

Interchange was way ahead of it's time and there is also (SRCSET) - but it doesnt work for background images background-image set in css / scss 

For example
background-image: url("paper.gif");
 

3 - REQUEST --- INTERCHANGE  (SRCSET) background images set in css

## What is wrong now ?

Responsively sizing background images is a  neccessary task. The method to responsively size (background images that are established in CSS code ) could be improved.

I have seen this wish stated many times - throughout github.

## Possible Solution

POSSIBLE SOLUTION

Javascript Plugin

## Context

...

## Your Environment

- Foundation version(s) used: 
- Browser(s) name and version(s): 
- Device, Operating System and version: 

## Checklist

- [ ] I have read and follow the CONTRIBUTING.md document.
- [ ] here are no other issues similar to this one.
- [ ] The issue title and template are correctly filled.

**Comment by JeremyEnglert** [comment]
This is the best way to handle that: https://foundation.zurb.com/sites/docs/interchange.html#use-with-background-images

**Comment by DanielRuf** [comment]
Exactly, this can be done with the documented way + a bit CSS.

**Comment by DanielRuf** [comment]
Closing as this should be already possible.
