### ISSUE TITLE
iOS crash due to off-canvas kill-flicker mixin

### ISSUE THREAD

**Issue by albertoperego** [zurb/foundation-sites#5205]
After some deep digging in the code, I found that the mixin "kill-flicker" is causing Webkit browsers to crash on iOS devices. A simple zoom on a page immediately crashes it. This is happening consistently, even on your site. By commenting out the "-webkit-backface-visibility: hidden;" property, all work fine.

**Comment by zurbchris** [comment]
So sorry for the level of stale this issue has achieved. If this is still an issue at all, please feel free to reopen, and we can look at setting the backface-visibility to a variable or something optional (I think, I do JS mostly).
