### ISSUE TITLE
Slider.js, firefox do not setup value in input

### ISSUE THREAD

**Issue by vladyslav2** [zurb/foundation-sites#5322]
OS: FreeBSD 9.2
Firefox: 27

Hello. Firefox will not pull value to input, because of:

    $(settings.display_selector).each(function(){
          if (this.hasOwnProperty('value')) {  // IS ALWAYS FALSE IN FF
            $(this).val(value);
          } else {
            $(this).text(value);
          }
     });

HTML:

     <input type="text" id='unit_price__lte' name="price_to" value="100">
            <div class="filter-col">
                <div class="range-slider" data-options="start: 20; end: 120; step: 5; display_selector:#unit_price__lte;" data-slider>
                    <span class="range-slider-handle"></span>
                    <span class="range-slider-active-segment"></span>
                </div>
            </div>

**Comment by coorasse** [comment]
this now affects chrome too (v43)

**Comment by zurbchris** [comment]
So this was fixed a while ago, the JS is 
```js
if (settings.display_selector != '') {
        $(settings.display_selector).each(function () {
          if (this.hasAttribute('value')) {
            $(this).val(value);
          } else {
            $(this).text(value);
          }
        });
      }
```

Thanks for the input, sorry about the stale issue. :+1:
