### ISSUE TITLE
RTL option broken in customizer

### ISSUE THREAD

**Issue by tomji** [zurb/foundation-sites#5646]
Hi,

I downloaded Foundation today, and followed instructions here:
http://foundation.zurb.com/docs/components/rtl.html
to the letter. HTML tag is now:
`<html class="no-js" lang="he" dir="rtl">`
(I am not using SASS, just editing the code directly in Notepad++).

result: text is aligned to right, but other than that - nothing happens. 
Please see screenshot before/after:
![foundation_rtl](https://cloud.githubusercontent.com/assets/6509281/3985907/8be0312c-2896-11e4-9af6-e965f7b03357.png)

As you can see, all the elements that float left still float left even after the change. Which means that all the columns are in the wrong order. 
(For example - the column of blue/green/red buttons should have been on the right.)

I've tried playing with the CSS a bit, but there isn't a simple answer. Without major changes to the CSS this is not really RTL support... Is there a *foundation-rtl.css* file somewhere? Please advise. 

Thanks
Tom

**Comment by rafibomb** [comment]
We're building a new customizer for Foundation 6 - looking to address this there so we'll keep this open.

**Comment by gakimball** [comment]
We deployed a new customizer today which should fix this issues.
