### ISSUE TITLE
Clearing Lightbox "data-options" for 'close_selectors' do not work

### ISSUE THREAD

**Issue by toobulo** [zurb/foundation-sites#6012]
According to the documentation, specifically:  http://foundation.zurb.com/docs/components/clearing.html#optional-javascript-configuration

It claims we should be able to set specific classes or ID's to close the clearing lightbox if clicked without touching any javascript, but utilizing the "data-options".  For some reason these do not do anything, as seen here:  http://jsfiddle.net/schwarzarbyter/o6d92y8k/

**Comment by rafibomb** [comment]
Have you tried it like this?

```
$(document).foundation({
  clearing : {
    close_selectors : '.clearing-close', 
  }
});
```

**Comment by ncoden** [comment]
@rafibomb I think it is high time to close this issue

**Comment by ncoden** [comment]
Thanks @rafibomb
