### ISSUE TITLE
Tabs: "toggled" event is triggered multiple times when using data-options="deep_linking:true"

### ISSUE THREAD

**Issue by ghost** [zurb/foundation-sites#6447]
The issue mentioned at #5383 still occurs even when using the foundation.tab.js file from af00955 fix (per https://github.com/zurb/foundation/issues/5383#issuecomment-73919364).

Screenshot added (I clicked each tab once starting with the second one and then looping through them):
![tabs_deep_linking_bug](https://cloud.githubusercontent.com/assets/7942119/7047774/66c16d5c-de17-11e4-972d-888825527b00.png)

To me it doesn't look like that fix can influence the apparent cause of the issue: the function triggering the tab's "toggled" event (on line 220 in foundation.tab.js from latest release or on line 233 from af00955 version) is called twice in a row from two different sources - one is the listener for the click event on the tab button and the other is an event listener for the location hash change event (as clicking also changes the hash).

**Comment by proimage** [comment]
I've got a situation where this is wreaking absolute havoc on a page's behavior. I hope they can fix this soon!

**Comment by wandl** [comment]
+1 Please fix this Zurb I have abandoned the Foundation 5 tabs as this keeps coming back for us and is wreaking havoc on our application...

**Comment by rafibomb** [comment]
A PR will be merged for this. Otherwise closing as it's not an issue in F6.
