### ISSUE TITLE
Reveal removes all listeners on init

### ISSUE THREAD

**Issue by sandermarechal** [zurb/foundation-sites#6469]
When the reveal JS component is initialized on a specific element, all listeners in the `.reveal` namespave are removed, even those that were added by the user.

The culprit is the `.off('.reveal')` on this line: https://github.com/zurb/foundation/blob/master/js/foundation/foundation.reveal.js#L50

That causes code like this to fail:

    var elem = $('<div data-reveal />');
    $('body).append(elem);
    
    // Attach a listener
    elem.on('opened.fndtn.reveal', function () { console.log('Reveal was opened'); });

     // This causes an init, which clears all listeners on elem
    elem.foundation('reveal', 'open', { url: 'http://example.org' });

**Comment by rafibomb** [comment]
If you have a solution, a PR would really help people out. We are working on a release for next week.

**Comment by sandermarechal** [comment]
I don't have a solution unfortunately. I worked around the problem by manually initializing the reveal before I add my own listeners.

I suspect that `init` is only called once for each element, even if you call `$(elem).foundation('reveal')` multiple times. If that is the case, the `.off('.reveal')` can probably simply be removed.

But I'm not sure that's the case. https://github.com/zurb/foundation/commit/711a594e3325dca941d9e865490c6870e8980c4a seems to indicate it can be called multiple times (but that was Foundation 4). If that is the case, you should keep a list of all registered event handlers, and on subsequent inits, only remove the listeners that were added during the previous init, instead of removing all listeners.

**Comment by jeanieshark** [comment]
@sandermarechal Typically, those event listeners are placed after Foundation has been initialized in the document. Alternatively, your callback function can be passed as an argument in the settings for reveal. Is there a specific reason for this particular use case?

**Comment by sandermarechal** [comment]
Yes, DOM-manupulating libraries such as React.js, Ractive and many more. They all cause new elements to be added to the page. In that case, events may be added before the element is initialized. Foundation shouldn't throw away those listeners.

**Comment by olivermg** [comment]
I agree with @sandermarechal , as I'm having the same problem of discarded event listeners after Foundation's init.
