### ISSUE TITLE
Tabs Deep Linking href="URL+Hash" fails

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#6511]
my anchor tags have the following format

``` html
<a href="http://example.com/#hash">hash</a>
<a href="http://example.com/#hash1">hash1</a>
```

not only #hash like in dokumentation

``` html
<a href="#hash">hash</a>
<a href="#hash1">hash1</a>
```

so the handle_location_hash_change function sends undefined to the toggle_active_tab funtion wich returns in a exeption

``` html
TypeError: c.attr(...) is undefined
```

my workaround for that is to take the contains selector in line 106,112,118

``` javascript
106
self.toggle_active_tab($('[' + self.attr_name() + '] > * > a[href=' + hash + ']').parent());
112
self.toggle_active_tab($('[' + self.attr_name() + '] > * > a[href=#' + hash_tab_container_id + ']').parent(), hash);
118
self.toggle_active_tab($('[' + self.attr_name() + '] > * > a[href=' + self.default_tab_hashes[ind] + ']').parent());
```

changed to

``` javascript
106
self.toggle_active_tab($('[' + self.attr_name() + '] > * > a[href*=' + hash + ']').parent());
112
self.toggle_active_tab($('[' + self.attr_name() + '] > * > a[href*=#' + hash_tab_container_id + ']').parent(), hash);
118
self.toggle_active_tab($('[' + self.attr_name() + '] > * > a[href*=' + self.default_tab_hashes[ind] + ']').parent());
```

also the ends with selector for me works fine

``` javascript
106
self.toggle_active_tab($('[' + self.attr_name() + '] > * > a[href$=' + hash + ']').parent());
112
self.toggle_active_tab($('[' + self.attr_name() + '] > * > a[href$=#' + hash_tab_container_id + ']').parent(), hash);
118
self.toggle_active_tab($('[' + self.attr_name() + '] > * > a[href$=' + self.default_tab_hashes[ind] + ']').parent());
```

i think the contains or end with selector is the better way to check the anchor tag

**Comment by gakimball** [comment]
Why are you using the entire URL instead of just the hash?

**Comment by designerno1** [comment]
Interesting Question
i had upgraded a older shopping system to Responsive Design with Zurb Foundation
This system uses the base href tag to the src of images and linking
```html
<base href="http://www.example.com/" />
```
now if i'am in http://www.example.com/dir/dir/ for example and using
```html
<a href="#hash">Test</a>
```
the browser links to http://www.example.com/#hash insead of http://www.example.com/dir/dir/#hash

for this reason i used full qualified href's

Greet J

**Comment by johannesx75** [comment]
We have the same issue with SilverStripe CMS. It uses the base tag in its templates.
