### ISSUE TITLE
Right to left horizontal scrollbar in chrome

### ISSUE THREAD

**Issue by mhabibi** [zurb/foundation-sites#6529]
When I use dir='rtl' in html tag, a horizontal scrollbar appears in the bottom in google chrome. I used custom download and set "TEXT DIRECTION" on Right-to-left.

**Comment by rafibomb** [comment]
Not sure the RTL option is fully working from the customizer https://github.com/zurb/foundation/issues/5646

You might try the Sass version instead.

**Comment by rafibomb** [comment]
New customizer should resolve this.
