### ISSUE TITLE
hide-for-large-up is not working on <th> 5.4.5.0

### ISSUE THREAD

**Issue by vanboom** [zurb/foundation-sites#6545]
For <th> elements, hide-for-large-up is not working.  Using the css inspector in Chrome, it seems the @media block for min-width: 64.063em is not superceding the @media block for the lower screen sizes.  

Therefore, the element gets

``` css
    display: table-cell !important;
```

instead of

``` css
    display: none !important;
```

**Comment by DUznanski** [comment]
th.hide-for-large-up and td.hide-for-large-up are still not working on 5.5.2; such elements remain visible in large, xl, and xxl locations. Checked in chrome, ff, and ie11 on Windows 7.

**Comment by rafibomb** [comment]
This is resolved in F6. A PR would be merged for this. We'll close this here - thanks!
