### ISSUE TITLE
Foundation.utils.image_loaded callback called twice

### ISSUE THREAD

**Issue by maiolica** [zurb/foundation-sites#6551]
Since version 5.5.2 Foundation.utils.image_loaded calls the callback function twice.
Here's the code working with 5.5.1:
```javascript
            var imgs = $("#box").find("img");
            Foundation.utils.image_loaded(imgs, function() {
                console.log("Finish!");
            });
```

**Comment by dragthor** [comment]
Here is a CodePen - http://codepen.io/anon/pen/avBOqx

I am only seeing it called once.

Is your code within a document.ready or something?

**Comment by zurbchris** [comment]
I'm not seeing this issue either. That, and it's been many moons since the issue filing, sorry about that.
