### ISSUE TITLE
Abide EqualTo and Required, required doesnt fire.

### ISSUE THREAD

**Issue by dobromir-hristov** [zurb/foundation-sites#6561]
Ok so if a RepeatPassword field has both Required and equalTo parameters, it will not fire an error if it is empty. 
Example:
Submit empty from, and only first password field gets error event, the repeat pass that is technically equal to the first one doesnt get an error because the equalTo is true, but it ignores the required attribute.
a simple fix is

``` javascript
if(required && to == ''){
          valid = false;
 }
```

But i`m not sure if this is proper to do.

**Comment by zurbchris** [comment]
You could say 
`if(required && !to){ valid = false; }` as the empty string will register a falsey value.
If you want to submit a pull request, I'd like to have a look at it.

**Comment by rafibomb** [comment]
This is resolved in F6. A PR would be merged for this. We'll close this here - thanks!
