### ISSUE TITLE
Offcanvas opening on search (ctrl + f)

### ISSUE THREAD

**Issue by fclaussen** [zurb/foundation-sites#6563]
Hey guys, I don't know if you already know about this but if a user makes a search the offcanvas menu pops open when it shouldn't.

Search for **emergency** for example at http://dawsondental.ca

However, on another site done by my company using an older version of foundation this was not happening. I asked around and the guy who did the site said he did not do anything special to prevent this behavior.

This search bug does not happen when searching for example **press** at http://olympic.ca

I'm not sure if this is something that happened somewhere along the updates or if this have something to do with the right nav.

**Comment by WerewolfCustoms** [comment]
I also experienced this issue on one of the sites that I worked on. Switching the menu to the left, using the same markup solved this issue. Of course, this is only a temporary fix.

The same behavior can be noticed on Foundation Off-canvas docs page when searching for "Hari Seldon". Right-side off-canvas demo menu will come into sight when users loop trough search results.

Although not many people use their browsers search function on mobile devices, I would love to see this issue resolved, so I can move my menu to the right side.

**Comment by fclaussen** [comment]
@WerewolfCustoms Oh, so it is really something with the right side, huh?
I hope to see this fixed soon :+1:

**Comment by zurbchris** [comment]
Delayed response, sorry. This is a known issue, and it has to do with the off-canvas not being hidden and merely translated out of the view. For some reason or another, browsers handle translating to the left or right differently, believe me, we spent quite a bit of time trying to rectify bugs in F6 and it still isn't perfect. That being the case, this isn't a bug we'll be fixing in F5, and we'll be improving the functionality of off-canvas for F6 as we can. Thanks for the input.
