### ISSUE TITLE
Stacked reveal modals re-adjust the first modal when the second modal is closed

### ISSUE THREAD

**Issue by estebanms** [zurb/foundation-sites#6583]
I tried stacking a reveal modal over another one using the procedure explained here: http://foundation.zurb.com/docs/components/reveal.html (Intermediate section)

It worked like a charm (setting `reveal.multiple_opened` to `true`) and I was able to see the new modal with its "parent" in the background. However, when I closed the new modal, the parent re-adjusted its size automatically, making it shorter and disarranging some of the elements inside it.

I haven't looked deeply into it, but it seems like it's adjusting its size to the element (div) where it was originally opened from and not the full width of the browser, as it should be.

I'm using Foundation 5.5.1.2 (through the foundation-rails gem)

**Comment by hraynaud** [comment]
Hi @estebanms 

How did you set reveal.multiple_opened?  I can't get this functionality to work at all

**Comment by estebanms** [comment]
@hraynaud if I remember correctly, it was in the options you can send to the `foundation` method call. For example:

```
$('#myModal').foundation('reveal', 'open', {
    multiple_opened: true
});
```

However, this will only work if you open the modal via Javascript (check the "Advanced" section from http://foundation.zurb.com/docs/components/reveal.html)

**Comment by hraynaud** [comment]
Hi @estebanms Thanks for the quick reply. I've tried every possible way and it just doesn't work. The second modal always replaces the first. I'm wondering if you would mind sharing an actual gist with the relevant code?

**Comment by estebanms** [comment]
@hraynaud it's weird because in my app I'm doing something very similar to this: http://jsfiddle.net/cqog0y5b/4/ and yet that JSFiddle is not working for me. I even tested the same code in my app and it worked there.

The problem could be that the versions I'm using in my app are not the same to the ones I'm using in the fiddle. If it helps, I have a Rails app using the following gems:

- jquery-rails (4.0.3)
- jquery-ui-rails (5.0.3)
- foundation-rails (5.5.1.2)
- rails (4.2.1)

**Comment by hraynaud** [comment]
Hi @estebanms  Thanks for following up.  I realized that the issue was related to a bunch of problems with my app including both version 4 and 5 of foundation being accidentally loaded.

I think I've got a handle on it now. Did you ever resolve your initial issue? 

Thanks again.

**Comment by estebanms** [comment]
Not really, I'm still able to reproduce this issue with the versions that I'm using. I ended up implementing a different approach, but this bug is still valid

**Comment by koolfreak** [comment]
Hi,
Having issue multiple_openede modal, when i try to open the modal in bottom page, the second modal is opened at top of page, which i cannot see it anymore, any ideas how to solve this issue?
thanks.

**Comment by rafibomb** [comment]
This is resolved in F6. A PR would be merged for this. We'll close this here - thanks!
