### ISSUE TITLE
opened.fndtn.reveal event binding not triggering on multiple modals

### ISSUE THREAD

**Issue by whithajess** [zurb/foundation-sites#6600]
When opening a second modal with `reveal.multiple_opened` as `true` the `opened.fndtn.reveal` event binding is not called.

**Comment by suexID** [comment]
We're experiencing the very same issue but the namespaced event doesn't get called even if there's only one reveal modal present. Any suggestions on that? Does anyone have issues like this?

http://foundation.zurb.com/forum/posts/24752-reveal-modal-events-not-firing-openfndtnreveal

**Comment by rafibomb** [comment]
This is resolved in F6. A PR would be merged for this. We'll close this here - thanks!
