### ISSUE TITLE
Support for multiple error messages

### ISSUE THREAD

**Issue by sveinburne** [zurb/foundation-sites#6603]
Here is the idea : 
    
    <input data-abide-validator="projectExists" pattern=".{3,10}" type="text" maxlength="10" required="true"/>
    <small class="error" data-abide-validator="@type,@pattern">3 chars minimum, 10 maximum</small>
    <small class="error" data-abide-validator="projectExists">A project holding the same acronym already exists!</small>

`@` stands for default abide validators

**Comment by gaurishpatil** [comment]
thanks,
but how we can dive a separate message like below,
required="true" -    this is required.
pattern=".{3,10}" -  3 chars minimum, 10 maximum
projectExists   -   A project holding the same acronym already exists!

**Comment by gakimball** [comment]
We'll look at this for Foundation 6. There's probably some interesting things we can do with defining global error messages for validators, instead of having to define them on individual fields.

**Comment by pedzed** [comment]
Any updates on this? I am thinking about whether to use Abide or not. I need this feature.

**Comment by prcongithub** [comment]
+1
