### ISSUE TITLE
tooltip is not scrolling with element in tab content

### ISSUE THREAD

**Issue by horans** [zurb/foundation-sites#6605]
[foundation version 5.5.1]
if you add a tooltip to a element in tab content (both horizontal and vertical ),
it will stay the first place as the page has been load,
it will not scroll with the element.

![foundation-tooltips-in-tabs](https://cloud.githubusercontent.com/assets/12060804/7976398/06a1505a-0aad-11e5-8ea3-2112e061a3b2.png)

**Comment by rafibomb** [comment]
Can you provide a code example or steps to reproduce? 

I created this demo and it seems to work as expected - http://codepen.io/rafibomb/pen/xwrpOv?editors=100

**Comment by horans** [comment]
finally located the weird 'bug' with additional css
```
html {
	overflow-x:hidden;
}

body {
	overflow-y: scroll;
}
```
http://codepen.io/horan/pen/jPBKNv

**Comment by rafibomb** [comment]
Thanks for the example! I think we solved this for Foundation 6. Testing to make sure before we close this.
