### ISSUE TITLE
Range slider triggers change event without any change

### ISSUE THREAD

**Issue by jekuno** [zurb/foundation-sites#6606]
Range sliders trigger a change event when foundation is initialized even though there hasn't been any change. See: http://jsfiddle.net/snvy2vrz/2/
This even applies for disabled range sliders. See this fiddle: http://jsfiddle.net/snvy2vrz/1/

Change events should only be emitted on changes, not on initialization.

**Comment by vita10gy** [comment]
I think you can argue the change is setting it from min to initial (in this case 2), and this is desired functionality, or at least in line with other things like it. What ever you want to happen by virtue of it being changed to 3 you probably want to have happen with it being 2. (Approached this way you don't have to have one set of things for the initial and one set of things for the change.)

Of course maybe I'm talking out of my hiney.

**Comment by jekuno** [comment]
Thanks for your answer.

As you can see at http://jsfiddle.net/snvy2vrz/4/ the event even triggers for "start: 1; end: 1; initial: 1;" although there haven't been any changes at all.
   * IMHO when I initially render a slider it simply is meant to be a visual representation of the current state of the according model i.e. there shouldn't be triggered any change event.

I added another fiddle which shows two other issues: http://jsfiddle.net/snvy2vrz/5/
   * If you call 'set_value' the change is triggered twice (instead of once). I also think there should be a 'silent' option to disable triggering of change events at all.
   * If you resize the window a change event is triggered as well. This shouldn't happen at all.

I think those issues are related to each other. If you prefer I can create separate issues for this as well.

**Comment by kashifnaseer** [comment]
I've same issue. any update/workaround on this ?

**Comment by MarcGuay** [comment]
I have nothing to add except that I'm running into the same problem illustrated by http://jsfiddle.net/snvy2vrz/4/.

**Comment by MarcGuay** [comment]
Something else I've noticed is that if you have multiple sliders on a page, the change even gets triggered multiple times *per* slider.  Example with 2 sliders on the page, the change event of the first slider gets fired twice on page load: http://jsfiddle.net/snvy2vrz/6/

**Comment by MarcGuay** [comment]
Looking at the code a bit, it seems like the source of this issue is that "resize.fndtn.slider" is triggered on pageload line 347 of foundation/js/foundation/foundation.js.  Not sure if this is essential, I've removed it and played around a bit and haven't noticed anything broken.

**Comment by dragthor** [comment]
Here is some more info - https://github.com/zurb/foundation/issues/6737

**Comment by csaftoiu** [comment]
+1, I noticed the same bug [here](http://jsfiddle.net/gRtrX/359/). I have three sliders, `#slider1`, `#slider2`, `#slider3`. I do:

    $("#slider1").on('change.fndtn.slider', function () {
        var val1 = $("#slider1").attr('data-slider');
        $("#slider2").foundation('slider', 'set_value', val1);
        $("#slider3").foundation('slider', 'set_value', val1);
    });

This causes an infinite triggering of change events.

**Comment by LichP** [comment]
A similar problem occurs when the change originates from an input linked via the display_selector setting: 

```
// update slider value as users change input value
this.S('[' + this.attr_name() + ']').each(function () {
  var slider = $(this),
      handle = slider.children('.range-slider-handle')[0],
      settings = self.initialize_settings(handle);

  if (settings.display_selector != '') {
    $(settings.display_selector).each(function(){
      if ($(this).attr('value')) {
        $(this).off('change').on('change', function () {
          slider.foundation("slider", "set_value", $(this).val());
        });
      }
    });
  }
});
```

Invoking `set_value` causes a reflow which calls set_ui for all sliders and triggers the change events for every slider on the page, meaning that the change event of the target control is always triggered _after_ the change of some other slider if it isn't the first slider on the page. This can be corrected by calling `set_ui` directly, so the `slider.foundation("slider", "set_value", $(this).val());` line becomes `self.set_ui($(handle), $(this).val());`

**Comment by rafibomb** [comment]
A PR would be merged for this. We'll close this here - thanks!
