### ISSUE TITLE
Magellan scroll and links with anchors not at the same position

### ISSUE THREAD

**Issue by Aetles** [zurb/foundation-sites#6688]
If you access the anchor directly by the URL, the target is hidden beneath the Magellan fixed meny because the browser scrolls directly to the anchor position. Would it be possible to correct this somehow?

Click on "Arrival" in the Magellan menu and you will be scrolled to this position:
![skarmavbild 2015-07-09 kl 13 08 57](https://cloud.githubusercontent.com/assets/429202/8593867/ea21179e-263b-11e5-9b69-b8591de0c425.png)

But if you click this link: 
http://foundation.zurb.com/docs/components/magellan.html#arrival
you will be scrolled to this:
![skarmavbild 2015-07-09 kl 13 08 28](https://cloud.githubusercontent.com/assets/429202/8593886/0b293e26-263c-11e5-83a3-eab3f395fa3e.png)

**Comment by rafibomb** [comment]
So the issue only occurs when you are accessing the URL from another page? We've re-written much of how Magellan works in the next version (Foundation for Sites 6) and this has been addressed there. 

A pull request would be helpful here fro people still using Foundation 5.

**Comment by Aetles** [comment]
Yes, that is the issue. Great to hear about the re-written Magellan in Foundation 6!

**Comment by adrianpauly** [comment]
Just for the record, I'm still having this same issue
