### ISSUE TITLE
Collapsed Sticky Top Bar issue: When I click on the menu icon, it goes to the top. Doesn't happen when expanded.

### ISSUE THREAD

**Issue by arielnoname** [zurb/foundation-sites#6696]
Images for showing the problem.
Tested on Chrome for Mac and Lollipop 5.1.1. Safari
Images from Foundation's Docs, so I assume is the last version (5.5.2)

![sticky1](https://cloud.githubusercontent.com/assets/11996305/8631376/27ff6560-274b-11e5-8b5d-201e934f7587.gif)

![sticky2](https://cloud.githubusercontent.com/assets/11996305/8631379/324aa9bc-274b-11e5-8f82-7db670b42aa7.gif)

**Comment by rafibomb** [comment]
Hmmm, looking at the history, nothing changed on this. The click should override the default behavior.

**Comment by tengbretson** [comment]
As far as I can tell this bug goes back to 4.3, possibly even farther.

**Comment by arielnoname** [comment]
I was checking this today, I think I was wrong the whole time.

Check 
scrolltop : true
On topbar docs
