### ISSUE TITLE
range-slider options cannot be changed after reflow

### ISSUE THREAD

**Issue by dmamolina** [zurb/foundation-sites#6701]
I have a range slider that defines the memory value for an input. This value can be provided in MB or GB. When the user changes the unit value (a select option), the start, end and step values of the range slider should change. 

After dynamically adding the range slider to the dom and calling the reflow method, everything works ok. When the unit value is changed the new data-options are provided using the following code:

```
$( ".memorySlider", context).attr('data-options', 'start: 0; end: 1024; step: 128');
context.foundation('slider', 'reflow');

context.on('change', '.memoryUnit', function() {
  if ( ...
    ...
    $( ".memorySlider", context).attr('data-options', 'start: 0; end: 16; step: 1');
    context.foundation('slider', 'reflow');
  }
}
```

But when the slider is moved the step value didn't change.

The only way to achieve this is removing the range slider from the dom and adding (+reflow) it again.

Foundation: 5.5.2
Chrome: 43.0.2357.132

Cheers

**Comment by rafibomb** [comment]
Hi - just wondering if you found a solution to your use case?

We're going through the code and it doesn't appear to be a use case that was originally developed for. We'd be open to a Pull Request on this if you or anyone else has a solution.

**Comment by zurbchris** [comment]
This is a `reflow` vs `reinitialize` conversation, which I've tried to improve for F6. I realize that's not helping you here, but you could try calling the `init` method via 
```js
context.foundation('slider', 'init');
```

In any case, this issue seems abandoned and I'm closing it, sorry about the delay.
