### ISSUE TITLE
Dropdowns hover issues

### ISSUE THREAD

**Issue by brianlenz** [zurb/foundation-sites#6704]
There seem to be two small issues with Foundation's dropdowns:

1) It's very reasonable that you might want to have a single dropdown that can be displayed at various positions on the page (i.e. triggered from multiple elements). Currently, when you take this approach and hover over the dropdown, the dropdown will move to the position of the first element. It will actually flicker and perform very strangely.

2) The mouseenter event seems to trigger multiple times as you move your mouse around. This leads to the open/opened events being triggered multiple times (unnecessarily).

The fixes are quite simple, so I will be creating a pull request with the fixes.

**Comment by rafibomb** [comment]
Saw the PR here https://github.com/zurb/foundation/pull/6705

It would be awesome if you can rework it so we can merge it in. Would help lots of people. Thanks!

**Comment by brianlenz** [comment]
I'd be happy to, but it's unclear to me what the issues are that need to be fixed? We are using the changes from the pull request, and it's working great for us.

**Comment by dragthor** [comment]
@brianlenz I think @rafibomb is talking about changes to dropdown since your PR.

**Comment by dragthor** [comment]
I have tested https://github.com/zurb/foundation/pull/6705 with these changes and all seems well.

:thumbsup:

**Comment by jamilservicos** [comment]
Dropdowns hover is running on version 6.3.0.

**Comment by ncoden** [comment]
@brianlenz Can we close this issue ?

**Comment by brianlenz** [comment]
Sure; we are still using Foundation 5, so we've not had a chance to test on 6.x yet. If/when we upgrade to 6.x, we can deal with any issues separately at that point...

Thank you.
