### ISSUE TITLE
"scroll_to_content:" option on tabs can be problematic with sticky header

### ISSUE THREAD

**Issue by marcelnl1** [zurb/foundation-sites#6718]
When using tabs while using a sticky header, something very common these days, using "scroll_to_content:true" in data-options will result in somewhat unexpected behaviour: clicking on a tab item will scroll to content just fine but it will hide the tab list under the sticky header.

I believe this is caused by the scrollIntoView method called in the toggle_active_tab function. Since the scrollIntoView method does not allow the offset to be defined (e.g. top:50), i believe foundation would be better off using another method for performing this action.

**Comment by rafibomb** [comment]
Interesting. What other method can you suggest? We're interested in hearing more about this.
