### ISSUE TITLE
input[type="text"] should not get width set to 100% when size attribute is present

### ISSUE THREAD

**Issue by ghost** [zurb/foundation-sites#6739]
foundation applies width=100% to every input text element. There is however the size attribute that might be used in cases where I need only a small input. For those cases, the width=100% should not apply.

The browser does a fine job sizing input elements with a size attribute.

So you might want to add :not([size]) to those selectors?

**Comment by rafibomb** [comment]
I think the idea is to use the grid to size these elements. Thoughts?

**Comment by thkoch2001** [comment]
```html
<label>name<input type="text" /></label>
<label>4-letter-code<input type="text" size="4" /></label>
```
It doesn't make any sense for an input field for a 4-letter-code to span the whole width.

Actually I added something like the following to our CSS, because it also doesn't make sense for input fields or paragraphs to be too large:
```CSS
p, input, select, textarea, label  {
  max-width: 55em;
}
```

**Comment by amosuro** [comment]
The recommendation is to use the grid to determine the input widths, hence the `width: 100%` property - this is my preferred method. Although is not ideal for whatever reason, then scoping with `:not([size])` sounds like a good fix

**Comment by rafibomb** [comment]
We can see your use case. Using the grid is the preferred method. The selector would end up being more specific than we'd like. It's not a change we're going to make but if you have a CSS solution with the :not selector please share it for people it will help. Thanks!

**Comment by yuriiz** [comment]
If idea is to use the grid for sizing why not apply width=100% only to elements which are immediate children of .cell?
There are many cases where browser already does a good job at autosizing and width=100% is not desired.
- number inputs with range, phone inputs etc where maximum width is known and set;
- select inputs which by default have width to fit contents.

Suppose one wants to have just one inline `select` fit to minimum width like language switcher in top bar or footer. Or Mr/Mrs `select` switcher + First Name `input` in one row. How to do it if you have foundation css included in page?
Create full grid markup around just to limit one `select`'s width?
Create special rule for it just to overcome this "feature" of foundation? And then do the same again for every other similar case?
Looking at competitors, for example, Bootstrap has inline forms to do this:
https://getbootstrap.com/docs/4.1/components/forms/#inline-forms
But in Foundation there is absolutely no built-in way to make inline form.
Please consider re-opening this issue and making better solution.
