### ISSUE TITLE
Joyride does not remove 'joyride-modal-bg' on end

### ISSUE THREAD

**Issue by xsegrity** [zurb/foundation-sites#6863]
When the joyride is ended it is not completely cleaning up after itself. The modal background (joyride-modal-bg) is left on the DOM. This causes issues with custom styling, as well as just being kinda dirty.

In v5.5.2 the last line of 'end' is `$('.joyride-tip-guide').remove();`. Perhaps it should be `$('.joyride-tip-guide, .joyride-modal-bg').remove();`? This seems to fix the issue although I am not sure if it creates new issues that I have not noticed.

**Comment by rafibomb** [comment]
Your solutions seems to work well. Can you submit a Pull Request for it so we can merge it in?

**Comment by dragthor** [comment]
@xsegrity is you just call Foundation.libs.joyride.off() it will remove that .joyride-modal-bg element.

And if you utilize this pull request https://github.com/zurb/foundation/commit/125c8f0fd7530183b3f70f59210854b73e073df2 you can always Foundation.libs.joyride.restart()

**Comment by xsegrity** [comment]
@dragthor Yea, calling off along with that pull request for sure will take care of it, as that pull request solves the settings being blown away issue (I logged that one as well and thanks for the fix). It would still be nice if 'end' removed the element though unless I am missing some underlying intent behind keeping it on the DOM?

**Comment by rafibomb** [comment]
Since there is newly re-written version of Joyride we'll close this here: https://github.com/zurb/joyride
