### ISSUE TITLE
Trigger multiple abide events

### ISSUE THREAD

**Issue by caycek** [zurb/foundation-sites#6865]
I found a weird bug that I don't know how to approach right now.. If you have a triggering event in your validation it will work if you plan to trigger only 1 other abide event.

```
triggerValidator: function(el, required, parent){
    var $this = $(el),
          target = $this.data('trigger').split(' ');

    $.each(target, function(id, val){
        $this.closest('form').find('[data-abide-validator="'+ val +'"]').trigger('change');
    });

    return true;
}
```

This is a custom validator I'm attempting to use in my project. It works in the sense of targeting a single element, but if I create more than one target it fails and will not trigger ANY of them. Remove the second it works again. Add `$this.closest('form').find('[data-abide-validator="secondValidator"]').trigger('change')` it fails just the same. I haven't found where it is located, but I want to see if anyone has had this issue or resolved it yet... I have been bashing my head against it for half the day and thought it was a logic error on my side.

Can someone help me verify this bug and see if they can find the root of the issue?

**Comment by rafibomb** [comment]
This has been addressed in Foundation 6. We'll leave it open here so that someone can offer a solution for Foundation 5 as tons of people still rely on it.

**Comment by caycek** [comment]
I don't have a lot of time myself to try that right now, but what was the overall solution for 6? Complete overhaul?


Sent on a Sprint Samsung Galaxy Note® 3

-------- Original message --------

**Comment by rafibomb** [comment]
It's not an issue on Foundation 6.
