### ISSUE TITLE
select dropdown is not aware of contents width, and showing arrow in the table td

### ISSUE THREAD

**Issue by allen-ecu** [zurb/foundation-sites#6917]
issue in IE 9, 10, 11

https://jsfiddle.net/nx6ft9LL/2/

**Comment by allen-ecu** [comment]
![untitled](https://cloud.githubusercontent.com/assets/650887/10280890/eae373e6-6ba2-11e5-9b2e-f3041bee4304.png)

**Comment by rafibomb** [comment]
Testing on the docs in IE 10 and 11, can't replicate this. I searched other IE forums and couldn't find any reports of this either.

<img width="901" alt="screen shot 2015-10-08 at 8 56 49 am" src="https://cloud.githubusercontent.com/assets/5652085/10371974/b15159dc-6d9a-11e5-8ebe-0409664c46fa.png">

<img width="831" alt="screen shot 2015-10-08 at 8 52 49 am" src="https://cloud.githubusercontent.com/assets/5652085/10371977/b7e4d256-6d9a-11e5-9778-d725b49a63d8.png">

**Comment by zurbrandon** [comment]
Is the comment that there should be padding on the right of the form to account for the arrow?

**Comment by slavanga** [comment]
I agree that some padding should be added to prevent an overlap with the select icon. With the recent [change](https://github.com/zurb/foundation-sites/commit/ecae14b48f7ed209685b99bc40cb134a0f98d871) to ```background-origin: content-box``` that could be pretty tricky though.
