### ISSUE TITLE
Dropdown double-tap in mobile view with is_hover:true option

### ISSUE THREAD

**Issue by nacesprin** [zurb/foundation-sites#6919]
If set is_hover:true, in mobile version is double-tap needed to display the dropdown.

```
<a data-dropdown="drop" data-options="is_hover:true;">Drop</a> 
<ul id="drop" class="f-dropdown" data-dropdown-content tabindex="-1">
  <li><a href="#">Opt1</a></li>
  <li><a href="#">Opt2</a></li>
  <li><a href="#">Opt3</a></li>
</ul>
```

**Comment by rafibomb** [comment]
I think this is the code that needs to be looked at. If Modernizr detects a touch device, the hover should be removed.

<img width="867" alt="screen shot 2015-10-07 at 10 38 49 pm" src="https://cloud.githubusercontent.com/assets/5652085/10358539/3dfadbda-6d44-11e5-8884-6cc8bb0c8519.png">

**Comment by zurbchris** [comment]
I was not able to reproduce this in the docs. Any chance for a codepen?

**Comment by nacesprin** [comment]
Open this with a mobile:
http://codepen.io/anon/pen/QjgByN

**Comment by dragthor** [comment]
Mobile as in iPhone? Android? Or just small?

**Comment by nacesprin** [comment]
In a tap device. Whatever size.
