### ISSUE TITLE
#{data('abide')} creates "[data-abide]"

### ISSUE THREAD

**Issue by airtonix** [zurb/foundation-sites#6957]
https://github.com/zurb/foundation/blob/master/scss/foundation/components/_forms.scss#L550

This creates invalid css and throws errors in `analyze-css`.

ends up being: 

```
...
"[data-abide-]" .error small.error 
...
```

**Comment by gakimball** [comment]
Tested in Libsass 3.3.0 (which is what our Libsass template ships with) and Ruby Sass 3.4.20, and both output `[data-abide]` without quotes.

Mostly likely this was an issue in older versions of Libsass, but the bug was fixed.
