### ISSUE TITLE
Topbar Submenu not working on Tablet, FD greater 5.3

### ISSUE THREAD

**Issue by ThomasJanotta** [zurb/foundation-sites#6966]
As described in my post:
http://foundation.zurb.com/forum/posts/35604-topbar-submenu-not-working-on-tablet-fd-greater-53

there is a bug after FD 5.3. On touchscreens with e.g. Android 4.4.2/4.4.3, Chrome 45 (or windows touch-pc) on tablets in e.g. landscape mode (where you can see all 1.-level items) you cannot reach the 3.level of navigation, because the click on the 2. level already goes to the page instead of only opening the submenu.

This is a real problem for multilevel-menus.

I tested it with the out-of-the-box downloads of FD53 and FD546 and the navi from the docs.
Here is a link:
http://www.thomasjanotta.de/f546

**Comment by jarrydfillmore** [comment]
I'm also having the same issue! Hopefully this can be resolved.
