### ISSUE TITLE
Joyride with Expose enabled will not scroll (5.5.3)

### ISSUE THREAD

**Issue by chiss22** [zurb/foundation-sites#6977]
I have noticed an issue with Joyride: With expose enabled, scrolling no longer works. I have tried 5.5.0 and 5.5.3.

**My code:**

```
    $(document).foundation({
        joyride: {
            expose : true,
            modal : true
        }
    });
    $(document).foundation('joyride', 'start');
```

**Comment by rafibomb** [comment]
Hmm, interesting. Do you have any suggestions to resolve it? A PR would really help.

**Comment by rafibomb** [comment]
A new (re-written) version of Joyride exists now https://github.com/zurb/joyride
