### ISSUE TITLE
Orbit Slider Speed Control via Jquery + Range Sliders

### ISSUE THREAD

**Issue by igolden** [zurb/foundation-sites#6991]
Hey there Zurbians!

I'm a huge fan of Foundation, and use it daily at our company. We build tons of static websites each month using it as our framework of choice. 

I'm trying to build out some unique funcitonliaty into Orbit, to give the user more control over their slideshow experience. In a nutshell, we want the user to be able to control the speed of the slideshow by dragging a range slider left or right. I've been able to gett he slider to stop/start via jquery, but can't seem to figure out how to control the speed from a range knob.

How would I go about doing this? I've attached an image from our PSD of how the design will work (and look). I'd like the user to have control over the slideshow.

Thanks in advance!
Ian

![screen shot 2015-11-08 at 1 31 51 am](https://cloud.githubusercontent.com/assets/12289711/11019507/88420998-85b8-11e5-8ce2-470f910a47e9.png)

**Comment by igolden** [comment]
I've been looking into this, and after opening up the javascript of orbit, i feel like i could key up the value of the range slider to the timer_speed variable.

Is this as simple as calling 'reflow' on orbit? The other option I was thinking was working in a call in the 'before-slide-change' event, so that when they change the speed of the timer, it changes on next slide change.

Thanks in advance for your help -- I'd be happy to put this functionality up on a Codepen or Repo after I get it put together.

**Comment by zurbchris** [comment]
While this is a *super* nifty feature, Orbit was deprecated for Foundation 5, and so won't get any new features. It was, however, resurrected for Foundation 6 as a very simple prototyping tool, feel free to play around with it and add features if you would like. I wouldn't mind seeing a pr for this feature there.

**Comment by igolden** [comment]
Still getting into F6 stuff, wouldn't mind submitting that myself either.
I'll see what I can do this month
