### ISSUE TITLE
Abide reflow, tabs, live validation and event handlers

### ISSUE THREAD

**Issue by jagreehal** [zurb/foundation-sites#6993]
In this jsbin (https://jsbin.com/dasurayozo/1/edit?html,js,console,output) I've got two tabs that both contain a form in their content.

On tab 1 live validation is fine, when I switch 2 two live validation doesn't work (try tabbing off the input element).

I can get the live validation back by calling  $('#form2').foundation('abide','reflow'); but then the valid.fndtn.abide event handler is lost.

Is there a way to get live validation to work on hidden (assuming that is what the problem is) forms or calling reflow with losing the event handlers?

**Comment by fesja** [comment]
I'm having the same problem. If I do:

    $(document).foundation('abide', 'reflow');

then the event `invalid.fndtn.abide` is not fired.

    $('#job-form').on('invalid.fndtn.abide', function () {...});

Do we have to change something on our code or is it a bug?

thanks

**Comment by juliopalro** [comment]
After searching all interner and not find a sprinkling response and almost failing to believe in miracles I thought to modify the Foundation code. The quickest solution I could give you is to remove from the **foundation.abide** code the options you put to the search fields and they are validated and removed **:hidden** from those parameters and everything runs, <0 / lucky.
