### ISSUE TITLE
Nav bottom bar would be very good

### ISSUE THREAD

**Issue by bjedrzejewski** [zurb/foundation-sites#6994]
At the moment there exist `topbar` but it is quite difficult to get it to stick to the bottom of the page.

I think this is a common requirement, so having this component (or similar component that sticks to the bottom) out of the box would be very beneficial.

This is how bootstrap handles this usecase:

http://getbootstrap.com/components/#navbar-fixed-bottom

**Comment by zurbchris** [comment]
While I don't disagree with you that a footer nav bar is useful, it won't be a feature add for Foundation 5. If you would like to see something like this for Foundation 6, please take a look at it, I think you should be able to do it without much difficulty.
