### ISSUE TITLE
Download generator not working any more

### ISSUE THREAD

**Issue by Tommuh** [zurb/foundation-sites#7000]
Hello,

The CSS files are missing rems identifiers. Just noticed when I downloaded a new version of the code via the website.

For example:

.row {
  margin: 0 auto;
  max-width: 62.5; 
  width: 100%; }

.column,
.columns {
  padding-left: 0.9375;
  padding-right: 0.9375;
  width: 100%;
  float: left; }

**Comment by zepfan** [comment]
This is happening to me as well. Using the custom generator while selecting only the grid, block grid, and form components produces a build with no units for multiple properties in the CSS file.

**Comment by Floristeady** [comment]
Now nothing works, CSS files are empty, when you download custom files.

**Comment by gakimball** [comment]
The Foundation 5 customizer has been replaced by a rewritten Foundation 6 customizer. If y'alls see any issues with the new downloads, let us know.
