### ISSUE TITLE
Suggestion for customizing Foundation breakpoints...

### ISSUE THREAD

**Issue by dan-at-unkubed** [zurb/foundation-sites#7001]
Found this page:

https://zurb.com/university/lessons/change-foundation-s-default-breakpoints

But didn't like the fact that I would have to edit Foundation files directly to affect these changes.  Did some searching and found the "global-variable-exists" function in Sass >= v3.3.

Changing the file _settings.scss (lines 154 to 157 in Foundation v5.5.3 from bower install) from:

// $small-breakpoint:  em-calc(640);
// $medium-breakpoint: em-calc(1024);
// $large-breakpoint:  em-calc(1440);
// $xlarge-breakpoint: em-calc(1920);

to this:
// @if(not global-variable-exists($small-breakpoint)) $small-breakpoint:  em-calc(640);
// @if(not global-variable-exists($medium-breakpoint)) $medium-breakpoint: em-calc(1024);
// @if(not global-variable-exists($large-breakpoint)) $large-breakpoint:  em-calc(1440);
// @if(not global-variable-exists($xlarge-breakpoint)) $xlarge-breakpoint: em-calc(1920);

allows me to make the following custom foundation scss file with a custom breakpoint:

@charset "utf-8";

@import '/bower_components/foundation/scss/foundation/functions';
$medium-breakpoint: em-calc(1200);
@import '/bower_components/foundation/scss/foundation/components/grid';
@import '/bower_components/foundation/scss/foundation/components/block-grid';

Everything seems to work fine with or without the custom breakpoint defined, but I'm not very deeply versed in Foundation's functionality, so I could very well be missing something big.  Kinda new to the whole Foundation scene, but it's pretty freaking cool.

Anyhow, I thought I'd make this suggestion for a change to the core Foundation files as it *seems* to allow for a "better" (non-invasive to core files) way to customize breakpoints.

Thanks, all.  Keep up the good work.  Looking forward to getting into Foundation 6.

**Comment by gakimball** [comment]
In Foundation 6 we made changing breakpoints a lot easier. It's just a Sass map, which means you can add, edit, or rename any breakpoint:

```scss
$breakpoints: (
  small: 0,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
```

**Comment by dan-at-unkubed** [comment]
Sweet.  Thanks for the info.
