### ISSUE TITLE
Problem with the Custom Download for Foundation for Sites 5.5.3

### ISSUE THREAD

**Issue by jsmackey** [zurb/foundation-sites#7003]
When you customize the Max-Width to 75, for example, then click download, the package that you get is somehow corrupted. The Row class comes out as "75" instead of "75rem" (like it would for the default download of 62.5rem). There may also be issues with the customizer and width settings for the Top Bar...

**Comment by gakimball** [comment]
The Foundation 5 customizer has been replaced with the Foundation 6 customizer.
