### ISSUE TITLE
A minor spelling mistake in the website

### ISSUE THREAD

**Issue by bragboy** [zurb/foundation-sites#7004]
Don't know where exactly to report this, but I found a spelling mistake in the site. 

![image](https://cloud.githubusercontent.com/assets/1298587/11159864/75644bf8-8a89-11e5-967a-3429b2818920.png)

URL: http://foundation.zurb.com/emails.html

It should be `inconsistent` as opposed to `inconsistant`. Note the paragraph has the same word but spelled correctly but not the title.

**Comment by gakimball** [comment]
A new marketing site is being deployed today, so this content might not exist anymore. Guaranteed though it'll have some typos here and there for folks to help us find ;)

**Comment by bragboy** [comment]
(y) looks good now
