### ISSUE TITLE
Foundation Joyride Never show again

### ISSUE THREAD

**Issue by mohsinali1317** [zurb/foundation-sites#7006]
I am using Foundations Joyride plugin in my web app. What I am trying to achieve is something like where the user can say that never show me again button on each step.

For example I am on the first item their I want two buttons, Next/Don't show again.

Is there a way to get that?

**Comment by zurbchris** [comment]
Yes, but not with Foundation. You'd have to use a cookie, maybe local storage, or some data sent/stored on your backend. In any case, I'm closing this because this isn't a Foundation specific issue.
