### ISSUE TITLE
Modernizr 3 has no more 'touch' property

### ISSUE THREAD

**Issue by sbaechler** [zurb/foundation-sites#7008]
In Modernizr 3, the `touch` property has been replaced by the `touchevents` property.
https://modernizr.com/news/modernizr-3-new-release-site

Foundation uses the `touch` property in several scripts which makes it impossible to use a custom build of Modernizr unless one re-maps the `touch` property to `touchevents`.

A possible quick solution would be to replace all occurences of `if(Modernizr.touch)` with `if(Modernizr.touch || Modernizr.touchevents)`.

**Comment by gakimball** [comment]
Foundation 5 won't be supporting Modernizr 3. We did make the mistake in our `bower.json` of allowing for Modernizr 3 to be installed, even though it's only compatible with 2. In version 5.5.3 we fixed the `bower.json` to lock to a specific version of Modernizr: `2.8.3`.

Foundation 6 doesn't require Modernizr.
