### ISSUE TITLE
Range-slider doesn't work if the value is changed when the slider is hidden via display: none

### ISSUE THREAD

**Issue by csaftoiu** [zurb/foundation-sites#7011]
See [this jsfiddle](http://jsfiddle.net/gRtrX/356/) which reproduces the bug precisely. To describe it here: if a slider's value is changed via `.foundation('slider', 'set_value', value)` while it is hidden, it doesn't look right when it is showing again. Specifically:

* If the slider itself is hidden, the slider handle is slightly off.
* If a container the slider is in is hidden, then the slider handle is really off, and the active-segment remains where it was when it was hidden.

Update: this doesn't come up if the hiding is done via `visibility: hidden`, only if via `display: none`.

Possibly related: #6702

**Comment by csaftoiu** [comment]
I've created [a workaround](http://jsfiddle.net/gRtrX/388/) using `MutationObserver`. It appears to be fairly well-supported. It works, but it's probably not the best approach. It basically monitors the entire `document` for changes and, if something went from `display: none` to `display: [not-none]`, it sets all the sliders to their current values. 

The workaround even checks the `style` attribute changing directly, but it'd be much more efficient, and perhaps sufficient, to just notice that `class` changed. As it is now I use jQuery to parse the `style` attribute, which adds a lot of overhead, especially as it's called every time a slider moves (since that causes the slider's `style` property to change). 

[Here it is](http://jsfiddle.net/gRtrX/393/) with only checking changes on the `class` attribute. The code is:

    mutationObserver = new MutationObserver(function () {
        $('[data-slider]').each(function (i, element) {
            $(element).foundation('slider', 'set_value', 
                                  $(element).attr('data-slider'));
        });
    });
    mutationObserver.observe(document, {
        attributes: true, subtree: true, attributeFilter: ['class']
    });

**Comment by zurbchris** [comment]
I'm glad you found a workaround for this problem! Since this isn't a use case we had planned for, we won't be fixing this issue within Foundation, but kickass use of MutationObservers!
