### ISSUE TITLE
Update License section in Package.json

### ISSUE THREAD

**Issue by jmbarlow** [zurb/foundation-sites#7014]
Minor one, but npm moaned at me that the licenses section in package.json is deprecated. 

I've stuck in a Pull request #7013 to use the new format.

**Comment by gakimball** [comment]
Your PR went stale with the shift from 5 to 6, so I implemented it myself: f4aecd0c49403b7db66fc8c4dd0ba6df15b612cc

The license file is still valuable to have, however, since the framework is deployed to multiple package managers.
