### ISSUE TITLE
Documentation/forms: No docs on input errors

### ISSUE THREAD

**Issue by joallard** [zurb/foundation-sites#7022]
I see Sass variables [on the page][1] for `$input-error-*`, but I would have expected examples on input with errors, if present at all in Fdn 6.

Cheers!
[1]: http://foundation.zurb.com/sites/docs/forms.html

**Comment by gakimball** [comment]
The [Abide docs](http://foundation.zurb.com/sites/docs/abide.html) show how form errors work. To be sure, though, you don't need to use Abide to use the styles themselves.

**Comment by gakimball** [comment]
Although to your point, those variables should probably be on the Abide page, not the forms page.

**Comment by joallard** [comment]
Don't error styles/states belong on the Forms page? Putting them on the Abide page would suggest they somehow need Abide to show, whereas one may want to generate that markup server-side.

**Comment by McRip** [comment]
:+1:
