### ISSUE TITLE
Docs for Sites - All older versions are 404 Not Found HELLLLLLLP!

### ISSUE THREAD

**Issue by thekirk** [zurb/foundation-sites#7025]
**How can we reproduce this bug?**

Click on any of the links under "Older Versions" on the current page...

http://foundation.zurb.com/sites/docs/

I'm not ready to move to 6 and need my kitchen sink!!!

**Comment by gakimball** [comment]
Fixed via 1a50ca96450d64d7fd08688a1ac314c4e834c866

Just deployed a new version, so the fix is there.

And here's the link: <http://foundation.zurb.com/docs/v/5.5.3/>

**Comment by thekirk** [comment]
nope. still 404 for all older versions.

**Comment by gakimball** [comment]
The links should work now, there was a server issue.

**Comment by thekirk** [comment]
Yep. Thanks!!
