### ISSUE TITLE
no class for radius and round button in F 6

### ISSUE THREAD

**Issue by dougolena** [zurb/foundation-sites#7026]
On the generic index page supplied with Foundation 6 for sites, there is neither a displaying radius nor round button. In foundation.css there is no .round class or .radius class and all border-radius are set to 0.

![screen shot 2015-11-19 at 3 14 42 pm](https://cloud.githubusercontent.com/assets/15932467/11284595/505a5d3e-8ed0-11e5-9599-53ba17dc1514.png)

**Comment by zurbchris** [comment]
The .round and .radius classes were dropped for Foundation for Sites 6. You can now instead use the sass variable `$global-radius` to adjust the border radius of any element that supports it, and easily over ride that with your own styles for things you want to have more or less radius.

**Comment by gakimball** [comment]
We're getting those extraneous buttons removed from the customizer, so any ZIP file you download from the Foundation site won't have those anymore.

And like @zurbchris said, `.radius` and `.round` are gone from the framework entirely.

**Comment by dougolena** [comment]
Thanks, that was really what was on my mind. 

I have enjoyed the changes in F 6 Thanks for everything.

Doug

-----
Douglas F. Olena
doug@olena.com
http://olena.com/blog/
417-988-4337 c
-----

"The greatest achievements of philosophy are the formulation of questions that haven’t occurred to scientists " — Alex Rosenberg

**Comment by padmacnu** [comment]
_settings.scss
$global-radius: 0; // I cant change it because it affects all the elements

I want radius for buttons and Callouts(panels)
$callout-radius: 3px; // 3px is applied to all the elements, instead on callout with radius class

Unable to figure why?

**Comment by gakimball** [comment]
There are no `.radius` and `.round` classes any more—those styles are now universal for each component.

**Comment by scottkoons** [comment]
So does anyone have a solution?  I tried changing the $global-radius to 5px and I don't see any change.

**Comment by gakimball** [comment]
@scottkoons What component did you not see a change on?

**Comment by scottkoons** [comment]
@gakimball I think I am having some issues with YetiLaunch not recompiling the SCSS.  I'm looking into it today, but other code is not compiling.  YetiLaunch says it is compiling, so I'm not sure what is going on.  The radius works when I go into the CSS file and force the change.

I'll post again if I'm still having problems.  Thanks for the reply.

**Comment by driekus77** [comment]
What about people who don't use Sass? Do I have to style the Rounded cornes myself?

**Comment by denisahac** [comment]
@driekus77 yes those folks who don't want to use SASS they have to override the component they'd like to have rounded radius.

**Comment by fairps** [comment]
So as a newbie I'll just say this sucks.  Your documentation clearly references these and I have spent a large amount of time trying to get them to work.  One of the reasons I am using foundation is because it makes it easier for me as a newbie so throwing comments about just reworking things in SCSS is a lot like telling me to "rewire the blue tree with a towel".  Just sayin...

**Comment by IamManchanda** [comment]
Hey we now have it actually 
foundation.zurb.com/sites/docs/prototyping-utilities.html#component-styling
