### ISSUE TITLE
[Interchange] Issue Name

### ISSUE THREAD

**Issue by xadz** [zurb/foundation-sites#7029]
**How can we reproduce this bug?**

1. Load this page on desktop view: http://foundation.zurb.com/sites/docs/interchange.html
2. Shrink window to mobile size
3. Graphical error

**What did you expect to happen?**

The site to fold responsively.

**What happened instead?**

The sidebar overlaps the main content.

**Test case**

Chrome (latest) on OSX (latest).

![screen shot 2015-11-19 at 22 14 21](https://cloud.githubusercontent.com/assets/6561655/11286122/2874fd2a-8f0b-11e5-8835-243465210a21.png)

**Comment by zurbrandon** [comment]
This was an issue with the docs sidebar, it's been fixed. I'll close this out. Thanks!
