### ISSUE TITLE
Motion-UI Styles Not Included by Deault

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites#7030]
Motion-UI JS is included by default, but it appears the only way to get the styles to work is to import them from a vendor/bower file.

This is the only way I could get Motion-UI to work.
![screen shot 2015-11-19 at 3 54 49 pm](https://cloud.githubusercontent.com/assets/6110968/11287010/e66a3290-8ed5-11e5-9577-284ffec947ca.png)

**Comment by gakimball** [comment]
Is this the CSS download?

**Comment by JeremyEnglert** [comment]
I'm using the Sass version. I don't see an include for Motion-UI Scss files included in foundation-sites/scss.

**Comment by gakimball** [comment]
Motion UI is a separate library, not imported by Foundation itself. Our two templates (which can be installed from Yeti Launch or the CLI) have both Foundation and Motion UI imported already.

The way you're doing it works just fine. If you want to make the `@import` statements shorter, you can configure load paths for your Sass compiler, so then you just write `@import 'foundation'` and `@import 'motion-ui'`.

**Comment by JeremyEnglert** [comment]
I thought Motion-UI was going to be included with F6?

https://github.com/zurb/foundation-sites-6/issues/268

The Motion-UI JS is required for Orbit to function correctly.

**Comment by gakimball** [comment]
`foundation.util.motion.js` is the same as the library that shipped with Motion UI last month.

The idea is for Foundation for Sites and Apps to each have their own integration. Sites has the motion library we wrote, and Apps uses angular-animate.

**Comment by JeremyEnglert** [comment]
Got it! Thanks @gakimball!

By the way, I think there is an extra motion-ui JS file included with F6.

https://github.com/zurb/foundation-sites/tree/develop/js

foundation.util.motion.js and motion-ui.js are both included.

**Comment by gakimball** [comment]
Yep, got rid of that.
