### ISSUE TITLE
Dropdown: child elements of anchor doesn't toggle the submenu

### ISSUE THREAD

**Issue by imranomari** [zurb/foundation-sites#7031]
```html
<ul class="dropdown menu align-right" data-dropdown-menu data-disable-hover="true">
    <li class="has-submenu">
        <a href="#">
            <i class="fa fa-user"><!-- can't toggle --></i>
            can toggle
            <span>can't toggle</span>
        </a>
        <ul class="submenu menu vertical" data-submenu>
            <li><a href="#">One</a></li>
            <li><a href="#">Two</a></li>
        </ul>
    </li>
</ul>
````

**Comment by zurbchris** [comment]
Thanks for that. It had to do with how we prevent default on item clicks. I'm making a fix and that'll be in the first patch.

**Comment by zurbchris** [comment]
Just to note, not actually fixed in the master branch yet. We'll be putting out a patch late today or tomorrow that will include this.

**Comment by yeetien** [comment]
Hi @zurbchris 

I'm using the version on https://raw.githubusercontent.com/zurb/foundation-sites/develop/js/foundation.dropdownMenu.js.

Submenu links are not working. Have to comment `e.preventDefault();` on line 184 for the links to work.
