### ISSUE TITLE
[The Grid]  grid column alignment

### ISSUE THREAD

**Issue by jaames** [zurb/foundation-sites#7034]
I may be doing something incorrectly, but grid columns don't seem to align properly when using the grid scss mixins.

Using the following scss:
```
@import 'foundation';

.main {
  @include grid-row(12) {    
    .main-content {
      @include grid-column(8);
      background: #ea9373;
    }
    .sidebar {
      @include grid-column(4);
      background: #9b9bf7;
    }
  }
}
```
I expected that .main-content and .sidebar would be inline with each other, since their combined width is 100%. This is what happened instead:
<img width="625" alt="screen shot 2015-11-19 at 23 24 18" src="https://cloud.githubusercontent.com/assets/9112876/11287589/c0c87396-8f14-11e5-90be-9db485634f54.png">
Adding ```box-sizing: border-box;``` to .main-content and .sidebar like so appears to solve this:

```
@import 'foundation';

.main {
  @include grid-row(12) {    
    .main-content {
      @include grid-column(8);
      box-sizing: border-box;
      background: #ea9373;
    }
    .sidebar {
      @include grid-column(4);
      box-sizing: border-box;
      background: #9b9bf7;
    }
  }
}
```

Which then produced the expected result: 
<img width="626" alt="screen shot 2015-11-19 at 23 32 05" src="https://cloud.githubusercontent.com/assets/9112876/11287726/cf67a8d0-8f15-11e5-8884-9b94d17688c6.png">

Have I missed something that should have added the box-sixing property here?

**Comment by gakimball** [comment]
You're missing Foundation's global styles, which set `box-sizing: border-box` for you. Add them with this line:

```scss
@import foundation-global-styles;
```
