### ISSUE TITLE
Media object not stacking in example 'Product Page'

### ISSUE THREAD

**Issue by moondawg69** [zurb/foundation-sites#7035]
http://foundation.zurb.com/sites-templates-previews/product-page.html

Seen on iPhone 5s, doesn't stack and causes side scroll.

<img width="308" alt="screen shot 2015-11-20 at 00 08 29" src="https://cloud.githubusercontent.com/assets/1304000/11288540/d5248340-8f1c-11e5-8068-9e105ae7f823.png">

**Comment by gakimball** [comment]
Those templates are maintained in a separate, private codebase for our marketing site. We'll get it fixed soon.

**Comment by rafibomb** [comment]
Media objects are made to NOT stack unless the stack-for-small class is applied. This is a design decision. For the template, we'll add the class so it looks better. Thanks!
