### ISSUE TITLE
Yeti Launch JavaScript error on launch

### ISSUE THREAD

**Issue by memoht** [zurb/foundation-sites#7038]
**How can we reproduce this bug?**

1. Get a Mac running OS X El Capitan
2. Download Yeti Launch
3. Open app

**What did you expect to happen?**
I expected it to work properly.

**What happened instead?**
JavaScript error dialog popped up. See screenshot.
<img width="420" alt="yeti-error" src="https://cloud.githubusercontent.com/assets/492691/11289345/e76e6c6e-8ef9-11e5-8612-797630b3c32c.png">

**Comment by Ne-Ne** [comment]
Same here, fails to startup without this error message.

**Comment by gianpaj** [comment]
Where did you download it? the download link is broken :cry:

**Comment by zzplab** [comment]
[Download page Yeti](http://foundation.zurb.com/develop/yeti-launch.html)

**Comment by gianpaj** [comment]
thanks @zzplab . the link is fixed now

**Comment by erikmellum** [comment]
We are in the process of QAing the patch for this bug. Thanks everyone for letting us know!

**Comment by erikmellum** [comment]
Hello everyone,

The patch been released! You can download it at http://foundation.zurb.com/develop/yeti-launch.html.

### The patch addresses:
* Javascript error on startup
* Scss error reporting @blynnc
* Glitch for users with a space in their path trying to open an editor

### Big enhancement:
* Hosted code integration

### A few other minor enhancements:
* Allow underscores in project names @blynnc 
* Change editor button in settings sidebar

Thanks everyone for your patience,
Erik

**Comment by rockstarwebdesign** [comment]
Total fail. Can't even start the app.
