### ISSUE TITLE
_banner.scss does not exist

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#7040]
Following a `git clone` of this repo and `npm install`, I get the following when I run `npm start`:

```
Error in plugin 'sass'
Message:
    docs/assets/scss/docs.scss
Error: File to import not found or unreadable: banner
       Parent style sheet: stdin
        on line 26 of stdin
>> @import 'banner';
   ^
```

I don't see a `_banner.scss` file in that folder.

**Comment by anik786** [comment]
This issue has been fixed in the following pull request: https://github.com/zurb/foundation-sites/pull/7051
Hopefully will be merged soon!

**Comment by gakimball** [comment]
When we merged the Foundation 6 branch into 5, somehow the `docs` folder ended up in `.gitignore`. By removing that, I was able to commit three files that were only on my computer as a result.
