### ISSUE TITLE
Javascript events are not firing

### ISSUE THREAD

**Issue by andrewjschmitt** [zurb/foundation-sites#7043]
My tabs are wrapped with:
`<ul class="tabs" data-tabs id="page-nav">`

but when I have this code listening for them to change nothing happens:
```
$("#page-nav').on('changed.zf.tabs', function() {...
```

**Comment by andrewjschmitt** [comment]
I'm using foundation.js ver 6.0.1

If I try going the using foundation.core.js with foundation.tabs.js method I get the following js error:
`Uncaught TypeError: Cannot read property '_init' of undefined ... foundation.core.js:245`

**Comment by andrewjschmitt** [comment]
Found the issue. If you are using foundation.js v6.0.1 go to line 6780 and uncomment 
`// Foundation.reflow(this.$element, 'tabs');`

**Comment by zurbchris** [comment]
You shouldn't need to reflow the tabs to get the event to fire. Can you give me a little more detail on what you're trying to do?

**Comment by andrewjschmitt** [comment]
I think the wrong JS file was in my cache. It works if the reflow is uncommented or not now. Thanks.
