### ISSUE TITLE
Reveal.modal issue

### ISSUE THREAD

**Issue by DrustZ** [zurb/foundation-sites#7046]
Hi, I'm using reveal.modal in 6.0.0, and find that I can't trigger the modal when I include the 'foundation.min.js', but when I use 'foundation.js' and remove all the " 'use strict;' " code lines, it works. 

Just want to notify this bug.

**Comment by zurbchris** [comment]
Update to 6.0.1
We had an issue with the mangle feature on minify. It was resolved and pushed to master yesterday.
