### ISSUE TITLE
[Dropdown Menus] Issue Name

### ISSUE THREAD

**Issue by collserola** [zurb/foundation-sites#7047]
**How can we reproduce this bug?**

1. Got a version of foundation.
2. Added the code you show in the documentation
3. All the navigation displays mixed up

**What did you expect to happen?**
That it displays a dropdown menu as in the example.

**What happened instead?**
It shows a messed up menu. (No erros on my console)

**Test case**

```html
<ul class="dropdown menu" data-dropdown-menu>
   <li><a href="#">item 1</a></li>
   <li><a href="#">Item 2</a></li>
   <li>
     <a href="#">Item 3</a>
     <ul class="menu">
          <li><a href='#'>Sub item</a></li>
     </ul>
   </li>
</ul>
```
Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by gakimball** [comment]
Dropdowns were refactored significantly in a recent patch and are now much more stable. I tested your exact code sample and it worked totally fine. If you run into any other problems, let us know in a new issue. Thanks! :)
