### ISSUE TITLE
Website links not working

### ISSUE THREAD

**Issue by jeanleonino** [zurb/foundation-sites#7048]
The links [FAQ](http://foundation.zurb.com/learn/faq.html), [Features](http://foundation.zurb.com/learn/features.html), [Website Examples](http://foundation.zurb.com/learn/website-examples.html), [Videos](http://foundation.zurb.com/learn/video-started-with-foundation.html), and [Training](http://foundation.zurb.com/learn/training.html) from the "learn menu" (check image) are actually not working, returns 404.

![learn-zurb](https://cloud.githubusercontent.com/assets/1311402/11296490/2522dc28-8f51-11e5-9167-e2ebc338348f.png)

**Comment by anik786** [comment]
what site are you on, cause those links don't even exist in http://foundation.zurb.com/

**Comment by anik786** [comment]
Yeah the issue is on forum side: http://foundation.zurb.com/forum/signin

but not so much the main site: http://foundation.zurb.com/

**Comment by gakimball** [comment]
The forum's top bar has been updated to match the main Foundation site.
