### ISSUE TITLE
The downloadable version on the website was not updated

### ISSUE THREAD

**Issue by PeterDaveHello** [zurb/foundation-sites#7049]
I downloaded from http://foundation.zurb.com/sites/download/assets/complete-f6.zip

The version string is still:
```js
var FOUNDATION_VERSION = '6.0.0-alpha.1';
```

in js/foundation.js, is that correct?

Thanks!

**Comment by cjmaxik** [comment]
6.0.1 n the way, I see.
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.core.js

**Comment by PeterDaveHello** [comment]
There is 6.0.0/6.0.1 branch, and the website didn't talk about that's a beta.

**Comment by zurbchris** [comment]
https://github.com/zurb/foundation-sites/issues/7088

**Comment by PeterDaveHello** [comment]
hmmm ... now v6.0.1 on website, but seems there is v6.0.2 and 6.0.3 branch on GitHub.

**Comment by nqv** [comment]
@zurbchris Is there any ways that I can download latest release version without checking out the git repo? The v6.0.4 has been available on github, but complete-f6 contains only v6.0.1.

**Comment by PeterDaveHello** [comment]
That's the problem I have.
