### ISSUE TITLE
Overlap main menu to code copy button in documentation

### ISSUE THREAD

**Issue by muhammadcahya** [zurb/foundation-sites#7050]
![67677640-8f6d-11e5-96c7-efa414ad5675](https://cloud.githubusercontent.com/assets/4241620/11297271/cded400c-8fa9-11e5-8526-6f51370d7151.jpg)
Note :
Chrome
Firefox

Give same result

**Comment by gakimball** [comment]
Fixed via c9f828e13810b1eeeca5649e4c17dafd8b0a926b
