### ISSUE TITLE
[Reveal] Missing ajax load

### ISSUE THREAD

**Issue by dasmikko** [zurb/foundation-sites#7052]
Foundation 5 had Modal ajax, foundation 6 does not.. 

Can we have this feature back?

**Comment by zurbchris** [comment]
We intentionally left this feature out of Foundation 6. However, we did make it very easy to do on your own. Here is a sample of how it works, though you'll have to fill in your own ajax call correctly.
```js
var $modal = $('#modal');

$.ajax({'/url'})
  .done(function(resp){
    $modal.html(resp.html).foundation('open');
});
```

**Comment by dasmikko** [comment]
Thanks! Works wonderfully!
