### ISSUE TITLE
variables in /proj/scss/_settings.scss are overriding by /proj/bower_components/foundation-sites/scss/_settings.scss

### ISSUE THREAD

**Issue by nacesprin** [zurb/foundation-sites#7053]
When create new project with "$foundation new" command and then execute "$proj/foundation watch", the customized values in /proj/scss/_settings.scss are compiled with the custom value only the first time. The next attempts are always overrided by the default value defined in /proj/bower_components/foundation-sites/scss/_settings.scss

To get compiled successfully, I need to run "$gulp sass" everytime I make any change in /proj/scss/_settings.scss

So, something is wrong in the watch task, because the next attempts are unsuccessfull.

**Comment by gakimball** [comment]
I went ahead and removed the settings file in this repo, as it's not necessary anyway. bd0d54731d49c36c7f735f7b4532d14daa4b4d7a

**Comment by nacesprin** [comment]
This is not working yet. When I execute "foundation watch" and change any /proj/scss/_setttings.scss variable, that variable is being overrided by /bower_components/foundation-sites/scss/_global.scss;

For example, the variable $primary-color in /proj/scss/_settings.scss is always overrided by the one defined in /bower_components/foundation-sites/scss/_global.scss

As I said in my first message, only the first time the global vars in /proj/scss/_settings.scss are compiled successfully. The next ones are overrided by /bower_components/foundation-sites/scss/_global.scss

So this is not resolved yet.

**Comment by gakimball** [comment]
I just created a new project using `foundation new` and was able to change the global variables.

See if your project is on version 6.0.3 of Foundation, which was published on Friday. Run `bower update` to get it.

**Comment by nacesprin** [comment]
Yes. I downloaded (manually) the 6.0.3 version and located in proj/bower_components/

So i saw the sentence "var FOUNDATION_VERSION = '6.0.3';" in the file /proj/bower_components/foundation-sites/dist/foundation.js

Is it completely neccesary run "bower update" to get working this issue?

My reason to question that is due to I have another F5 projects running and I don't want to "replace" any other bower component unless the F6 works fine.

**Comment by gakimball** [comment]
`bower update` only updates projects in your current folder—it doesn't affect anything else. Every project has its own versions of the framework, that are completely separate.

But it sounds like you're already on 6.0.3, so let's try this. Open `Gulpfile.js`, and on lines 10, 18, and 22, remove the `./` from the beginning of the file path. So it'll look like the below. I think there's a difference in watching behavior if you have that dot at the beginning or if you don't.

```js
gulp.task('sass', function() {
  return gulp.src('scss/app.scss')
    .pipe($.sass({
      includePaths: sassPaths
    })
      .on('error', $.sass.logError))
    .pipe($.autoprefixer({
      browsers: ['last 2 versions', 'ie >= 9']
    }))
    .pipe(gulp.dest('css'));
});

gulp.task('default', ['sass'], function() {
  gulp.watch(['scss/**/*.scss'], ['sass']);
});
```

**Comment by nacesprin** [comment]
:-( I have the gulpfile.js as you mentioned and when running "gulp" in the project directory the app.css compiled still overrides the bower_components/foundation-sites/scss/_global.scss

This is the bower update command result:

javier@localhost:/var/www/pruebas/foundation-tests/foundation6/f6_4$ bower update
bower cached        git://github.com/zurb/motion-ui.git#1.1.0
bower validate      1.1.0 against git://github.com/zurb/motion-ui.git#~1.1.0
bower cached        git://github.com/zurb/foundation-sites.git#6.0.3
bower validate      6.0.3 against git://github.com/zurb/foundation-sites.git#~6.0.0
bower new           version for git://github.com/zurb/motion-ui.git#~1.1.0
bower resolve       git://github.com/zurb/motion-ui.git#~1.1.0
bower download      https://github.com/zurb/motion-ui/archive/v1.1.1.tar.gz
bower cached        git://github.com/ten1seven/what-input.git#1.1.2
bower validate      1.1.2 against git://github.com/ten1seven/what-input.git#~1.1.2
bower cached        git://github.com/jquery/jquery.git#2.1.4
bower validate      2.1.4 against git://github.com/jquery/jquery.git#~2.1.0
bower extract       motion-ui#~1.1.0 archive.tar.gz
bower resolved      git://github.com/zurb/motion-ui.git#1.1.1
bower install       jquery#2.1.4
bower install       motion-ui#1.1.1

jquery#2.1.4 bower_components/jquery

motion-ui#1.1.1 bower_components/motion-ui
└── jquery#2.1.4

######################################
So. Do you have tried to change var value, then save, then change var value, then save, then change var value and then save?

It fails to me when saving from the second time.

**Comment by nacesprin** [comment]
In a fresh installation in another server, it works fine. So, what could be happening in the first machine which causes the compiler "foundation watch" overrides the values?

I had installed previously F5 CLI and then uninstalled it, but is still overriding the variables when run "foundation watch".

Do I only have this issue?

**Comment by gakimball** [comment]
@nacesprin Sorry for not getting back to you sooner! In a recent patch we moved the location of the framework's internal settings file, to prevent a Sass compiler from trying to load two competing `_settings.scss` files. Now it will *only* load the `_settings.scss` within your project.
