### ISSUE TITLE
Breadcrumb Variables in Settings.css not working as they should?

### ISSUE THREAD

**Issue by p-h-i-l** [zurb/foundation-sites#7054]
*app.scss*
```scss
@import 'settings';
@import '../bower_components/foundation-sites/scss/foundation';
@include foundation-everything;

// other changes to css
...
```

can't use the breadcrumb variables in my custom `_settings.scss` this way, all others work just fine!!!
If i want to change the `margin`, `font-size etc`. i need to import `foundation` before `settings`.

Is this intended? @gakimball [refering to this topic] (https://github.com/zurb/foundation-sites/issues/7024#issuecomment-158244841)

Thanks you for your time and help! :+1: 
Philipp Hilpert

edit: may also be related to [this](https://github.com/zurb/foundation-sites/issues/7053)
edit2: also to [this](https://github.com/zurb/foundation-sites/issues/7056)

**Comment by gakimball** [comment]
The variables were just missing their `!default` flags. We'll probably put out another patch today which would include this fix, but in the mean time, you can get around this by placing the breadcrumb variables between `@import 'foundation'` and `@include foundation-breadcrumbs`. That should work.
