### ISSUE TITLE
[Foundation for Sites] Custom download didn't work

### ISSUE THREAD

**Issue by MadMantis** [zurb/foundation-sites#7055]
**How can we reproduce this bug?**

1. Downloading a custom-build of foundation 6 has no css-files included. It seems that it doesn't matter wich features are choosen. 

**What did you expect to happen?**
Getting a custom-build of foundation 6

**What happened instead?**
After extracting the zip i've only got the index.html and some .js-files 

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by martinoroma88** [comment]
It happened the same to me!

**Comment by gakimball** [comment]
Paging @erikmellum.

We had some issues with blank files but they may have been resolved last week.

**Comment by gakimball** [comment]
Custom downloads won't have missing files anymore. If you encounter any other issues, let us know. Thanks! :)
