### ISSUE TITLE
Rem-calc in _settings.scss doesn't work

### ISSUE THREAD

**Issue by svkarpovich** [zurb/foundation-sites#7056]
Solution: 
In app.scss move @import 'foundation'; above @import 'settings';.

**Comment by jonathanmelville** [comment]
Was going to submit a PR for this but can't figure out there this file resides in the repo...

**Comment by gakimball** [comment]
Does your settings file have `@import util/util` in it? That's what brings in those functions. It should be on line 41 or so.

**Comment by jonathanmelville** [comment]
The problem is that when the app.scss file is created, `@import 'foundation';` comes after `@import 'settings';`

As @svkarpovich mentioned, fixing the order solves this and other problems that were cropping up.

Didn't see how the `app.scss` file is generated though.

**Comment by jonathanmelville** [comment]
@gakimball To answer your question, my settings file doesn't import anything.

**Comment by colin-marshall** [comment]
The settings files in the repos for the basic template and the zurb template don't have that import util statement and the globals are not at the top like in this repo. If it's just a matter of copying the settings file from here to those other repos I can take care of that.

**Comment by gakimball** [comment]
Ah yes, definitely do that. I'll make sure both templates are up to date.

**Comment by gakimball** [comment]
Alright, both templates have an updated settings file to match Foundation 6.0.1.

**Comment by jonathanmelville** [comment]
@gakimball Awesome. So we just redownload? Or fix manually?

**Comment by gakimball** [comment]
You can do either, everything else about the template is the same.

**Comment by jonathanmelville** [comment]
:thumbsup:
