### ISSUE TITLE
abide plugin input element will throw error in some case

### ISSUE THREAD

**Issue by futurist** [zurb/foundation-sites#7060]
fundation.abide.js
  Foundation.libs.abide = {
    name : 'abide',
    version : '5.5.3',

```
var el = el_patterns[i][0],
                   required = el_patterns[i][2],
LINE229            value = (el.value||'').trim(),
```

line 229 will throw error in some case when input is disabled, since el.value is undefined in some platform.

```
value = (el.value||'').trim(),
```

maybe a fix?

**Comment by rafibomb** [comment]
A PR would be merged for this. We'll close this here - thanks!
