### ISSUE TITLE
[The Grid] Large block grid maxes out at 6 across?

### ISSUE THREAD

**Issue by anthonywjackson** [zurb/foundation-sites#7061]
I created a block grid using the new mark up:

    <div class="row small-up-2 medium-up-4 large-up-7">

    <div class="column">
    <p class="text-center">
    <a href="#">link</a>
    </p>
    </div>
    ...
    <div class="column">
    <p class="text-center">
    <a href="#">link</a>
    </p>
    </div>

    </div>

And the grid shows up four links across on large screens. When I change `large-up-7` to `large-up-6` I get 6 across. Is the block grid set to max out at 6 across? `large-up-8` and `large-up-9` etc also show up four links across on large screens (grabbing from `medium-up-4`).

**Comment by anik786** [comment]
the image is not showing

**Comment by gakimball** [comment]
If you're using the CSS version of the framework, you'll be locked as 6 max. As for the Sass version, I just added a `$block-grid-max` variable to make that cap customizable. We'll probably put out a 6.0.2 patch today or Monday, so this addition will be in the framework soon.
