### ISSUE TITLE
[F6] [Dropdown Menu] Dropdown opens off-screen with right-aligned menu (not RTL text)

### ISSUE THREAD

**Issue by CodeGordon** [zurb/foundation-sites#7067]
When using right-aligned menus, but not RTL text orientation (not using the .align-right class), dropdown menus still open aligned to their parent's left side. Such dropdowns should align instead to their parent's right side to appear on-screen as expected. This worked just fine in Foundation 5 without additional markup on any involved elements.

The following code will reproduce the issue with Foundation v6.0.1
```html
<nav class="title-bar" role="navigation">
    <section class="title-bar-left">
        <span class="title-bar-title"><a href="/">Example Right Dropdown</a></span>
    </section>
    <section class="title-bar-right">
        <ul class="dropdown menu align-right" data-dropdown-menu role="menubar">
            <li class="has-submenu">
                <a href="javascript:void(0);">Menu</a>
                <ul class="submenu menu" data-submenu role="menu">
                    <li><a href="/menu-item">Menu Item</a></li>
                </ul>
            </li>
        </ul>
    </section>
</nav>
```

Included CSS: Foundation v6.0.1, Normalize v3.0.3
Included JS: Foundation v6.0.1, jQuery v2.1.4

**Comment by zurbchris** [comment]
![screen shot 2015-11-20 at 10 06 15 am 2](https://cloud.githubusercontent.com/assets/13631168/11307672/962cfa76-8f6e-11e5-912e-0d1b2b5816fa.png)


Is the result of your code on my machine. What exactly is it doing on yours?

**Comment by CodeGordon** [comment]
My mistake. The example code still had the .align-right class applied. A live version of this issue is below. In addition, I've noticed that the link in the dropdown doesn't seem to work.

```html
<nav class="title-bar" role="navigation">
    <section class="title-bar-left">
        <span class="title-bar-title"><a href="/">Example Right Dropdown</a></span>
    </section>
    <section class="title-bar-right">
        <ul class="dropdown menu" data-dropdown-menu role="menubar">
            <li class="has-submenu">
                <a href="javascript:void(0);">Menu</a>
                <ul class="submenu menu" data-submenu role="menu">
                    <li><a href="/menu-item">Menu Item</a></li>
                </ul>
            </li>
        </ul>
    </section>
</nav>
```

http://new.codegordon.com/

**Comment by zurbchris** [comment]
You will need the align-right class applied, as that implies all sub-menus should attach to their parent from the submenus right side.

**Comment by CodeGordon** [comment]
This also makes everything render in reverse order, which is not desirable. The classes .top-bar-right and .title-bar-right should do this, and as mentioned above, used to do exactly that.

We shouldn't need to add additional markup and shuffle around the menu lists, especially for functionality Foundation had in v5.

**Comment by CodeGordon** [comment]
After digging through the CSS a bit, it looks like the right-aligned bar used to apply the following to dropdowns, but no longer does.

```css
position: absolute;
left: auto;
right: 0;
```

**Comment by CodeGordon** [comment]
The code below was sufficient to get it working like Foundation 5 used to. I'm not sure how to do this in SCSS format, though.

```css
.top-bar-right .dropdown.menu .menu,
.title-bar-right .dropdown.menu .menu {
	position: absolute;
	left: auto;
	right: 0;
}
```

**Comment by zurbchris** [comment]
This should be fixed now, please reopen if still an issue.

**Comment by CodeGordon** [comment]
There's still an issue with v6.0.4, though a slightly different one. The menu opens with its right side aligned to the left side of the parent. Before, the right side of the menu was aligned with the parent's right side.

![image](https://cloud.githubusercontent.com/assets/7526525/11408504/847ffafe-9387-11e5-8928-d02e6e146a8c.png)

**Comment by zurbchris** [comment]
You still need to add the `align-right` class to have it position where you want it. I added the class on your live site and this is what you get:
<img width="223" alt="screen shot 2015-11-25 at 12 23 34 pm" src="https://cloud.githubusercontent.com/assets/13631168/11408649/60eae3aa-936f-11e5-86b5-9bb2a9c5eccb.png">

**Comment by CodeGordon** [comment]
Again, not only is that a redundant class to add, given the .top-bar-right/.title-bar-right class above it, but it uses float, which reverses the order of the bar-level menu items. This is most definitely not desired behavior.

**Comment by zurbchris** [comment]
I'm going to leave this one for @gakimball to resolve this in the scss, but here's a working solution for now:
apply the `align-right` class to your dropdown menu, then in your own sass/css target `.menu.align-right > li` with `float: left;`.
This is not an ideal solution, but that's what I have for you for now. This is the result: 

<img width="245" alt="screen shot 2015-11-25 at 1 54 23 pm" src="https://cloud.githubusercontent.com/assets/13631168/11410430/27c86c84-937c-11e5-84ea-fc23c7289350.png">

Cheers.
