### ISSUE TITLE
Off Canvas not triggering with custom build js

### ISSUE THREAD

**Issue by naileditdesign** [zurb/foundation-sites#7072]
Hello

A few of the docs Zurb have supplied don’t quite add up with what is downloaded in a custom build. So until they fix it up which Zurb will do eventually. But until its fixed theres a couple of things to note.

foundation.min.js – Doesn’t Work

Use -> foundation.js

jquery.js – Doesn’t work 

Use -> jquery.min.js

I cant quite give you an example of which parts of these are incorrect i think some classes are missing from the trigger 'button' http://foundation.zurb.com/sites/docs/off-canvas.html

I wrote a blog with a code snippet of working code here:
http://naileditdesign.com/foundation-6-off-canvas/

**Comment by zurbchris** [comment]
I don't see the issue with offcanvas not opening on the live docs, can you explain the problem in more detail?

**Comment by zurbchris** [comment]
https://github.com/zurb/foundation-sites/issues/7088
