### ISSUE TITLE
DROP DOWN MENU -  VERTICAL - DOCS - BUG

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites#7074]
http://foundation.zurb.com/sites/docs/dropdown-menu.html

Same issue using mac El Capitan - latest version of Safari, chrome and Firefox browsers

Drop Down Menus Vertical -  buggy - several issues 

1.  Arrows are way off on the right side of page.
2. There are 2 item 1 in the list - last Item 1 should technically say Item 4
3. Rollover Item 1 on the left. Submenu appears under
If the arrows are pointing right, shouldn't the sub menu fly out to the right of the parent instead of under ?

Also See attached screen shot

![drop down menu vertical bug](https://cloud.githubusercontent.com/assets/14908417/11309051/db602162-8f7e-11e5-8f77-9bc09ecc8ad3.jpg)

**Comment by colin-marshall** [comment]
There is also no code example for the vertical dropdowns.

**Comment by blynnc** [comment]
There are  several issues related to vertical drop down menus across the board as reported in issues

https://github.com/zurb/foundation-sites/issues/7087
https://github.com/zurb/foundation-sites/issues/7099
https://github.com/zurb/foundation-sites/issues/7105
https://github.com/zurb/foundation-sites/issues/7074

**Comment by gakimball** [comment]
I cleaned up the examples for dropdown menus to make everything more clear. I also added more code samples so you can see what's going on.
