### ISSUE TITLE
[Reveal] Not Working In Foundation 6

### ISSUE THREAD

**Issue by mgblow** [zurb/foundation-sites#7080]
using code below

```html
<p><a data-open="exampleModal1">Click me for a modal</a></p>

<div class="reveal" id="exampleModal1" data-reveal>
  <h1>Awesome. I Have It.</h1>
  <p class="lead">Your couch. It is mine.</p>
  <p>I'm a cool paragraph that lives inside of an even cooler modal. Wins!</p>
  <button class="close-button" data-close aria-label="Close reveal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
```

doesnt work

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by gakimball** [comment]
Are you using a CSS Download or the Sass version?

**Comment by ruraldreams** [comment]
js from zurb.com didn't work for me (downloaded an hour ago) - js from github does work - no sass here

**Comment by zurbchris** [comment]
the .min is still not working if pulled from foundation.zurb.com
We should have that fixed before end of day.

**Comment by marti1125** [comment]
@zurbchris is the same case with accordion doesn't work :(

**Comment by zurbchris** [comment]
none of the js plugins will work if you use the .min.js file if pulled from the zurb website.

**Comment by marti1125** [comment]
ok, thanks! :D

**Comment by zurbchris** [comment]
https://github.com/zurb/foundation-sites/issues/7088

**Comment by mgblow** [comment]
Soryy To Be late :). Yep, as zurbchris said after a moment  I discovered it too. js plugins wont work if you include the min package of foundation.so you have to change the code and include the normal package to get them run.thanks to all.

**Comment by philliptmaddox** [comment]
The 5.* docs seemed to suggest that a workaround to importing each required plugin is to include the 'foundation.min.js' so I had been assuming that this was the case for v6.4.3 all day. Changing to 'foundation.js' did the trick but it would be nice to update the new v6 docs to warn of this.

**Comment by dagostinelli** [comment]
+1 to updating the web site.  The examples as stated on the web site do not work. 2-3 hours of playing with it -- is it a bug or am I doing it wrong?

I'm writing this in April 2018 -- c'mon guys. Fix the site.

**Comment by TrueJedi** [comment]
The reveal still does not work.  The documentation is incomplete
