### ISSUE TITLE
Foundation 6 upgrade docs

### ISSUE THREAD

**Issue by OtaK** [zurb/foundation-sites#7084]
Hi there Zurbians!

I noticed that there are no upgrade docs for upgrading from Foundation 5 to 6.
Did I miss something or they're still in the TODO list?

Thanks,
Mathieu Amiot

**Comment by zurbchris** [comment]
On the todo list

**Comment by soulcreate** [comment]
+1

**Comment by anik786** [comment]
+1

**Comment by gakimball** [comment]
Closing in favor of #7318. We know we need to get it done soon.
