### ISSUE TITLE
F6 Sites Motion UI: slide-out-down is not working correctly

### ISSUE THREAD

**Issue by AnselmMarie** [zurb/foundation-sites#7086]
When I use the slide-out-down animation on my local foundation and the foundation website it's animating just like the slide-out-up motion. Go to this url http://foundation.zurb.com/sites/docs/motion-ui.html#built-in-transitions and toggle between the two motions to see. Thanks.

**Comment by jamesstoneco** [comment]
Bugfix in motion-ui repo [PR 48](https://github.com/zurb/motion-ui/pull/48)

**Comment by gakimball** [comment]
Merged zurb/motion-ui#48
