### ISSUE TITLE
[Responsive Navigation] empty space below menu items

### ISSUE THREAD

**Issue by zzplab** [zurb/foundation-sites#7087]
**How can we reproduce this bug?**

1. On mobile view (small) both using Safari/Chrome on iMac and iOS Safari iPhone:
2. Go to page [responsive-navigation](http://foundation.zurb.com/sites/docs/responsive-navigation.html)
3. Look at the second Responsive Menu example below:
<ul class="vertical menu" data-responsive-menu="drilldown medium-dropdown" style="width: 300px;">
See image below.

**What did you expect to happen?**
On level 1 and 2 of the menu I expect the menu and the hr below it to be normally close together.
**What happened instead?**
On level 1 and 2 of the menu I see the large vertical white space below the menu and above the hr line.

**Test case**
[responsive-navigation](http://foundation.zurb.com/sites/docs/responsive-navigation.html)

This is causing the issue, the 3rd level menu m3:
```
<ul class="vertical submenu menu" data-submenu id="m3">
          <li><a href="#">Item 1A</a></li>
          <li><a href="#">Item 1B</a></li>
          <li><a href="#">Item 1C</a></li>
          <li><a href="#">Item 1D</a></li>
          <li><a href="#">Item 1E</a></li>
        </ul>
```
Making the menu much longer will make it more obvious:
```
<ul class="vertical submenu menu" data-submenu id="m3">
          <li><a href="#">Item 1A</a></li>
          <li><a href="#">Item 1B</a></li>
          <li><a href="#">Item 1C</a></li>
          <li><a href="#">Item 1D</a></li>
          <li><a href="#">Item 1E</a></li>
          <li><a href="#">Item 1E</a></li>
          <li><a href="#">Item 1E</a></li>
          <li><a href="#">Item 1E</a></li>
          <li><a href="#">Item 1E</a></li>
          <li><a href="#">Item 1E</a></li>
          <li><a href="#">Item 1E</a></li>
        </ul>
```
Below 3 screenshots on 'small' screen from the issue with all 3 menu levels:
![responsive-issue](https://cloud.githubusercontent.com/assets/7559497/11313643/b40930c6-8fde-11e5-8ce5-e9afe97463c3.jpg)

**Comment by blynnc** [comment]
There are a couple of issues with vertical drop down menus as reported in issues

https://github.com/zurb/foundation-sites/issues/7087
https://github.com/zurb/foundation-sites/issues/7099
https://github.com/zurb/foundation-sites/issues/7105
https://github.com/zurb/foundation-sites/issues/7074

**Comment by gakimball** [comment]
This fixed height is currently a "feature" of drilldowns—the height of the tallest menu is applied to the whole container, so the height doesn't jump around as the user navigates it.

However, we've had multiple developers ask to change this, or make it customizable.

Going to roll this into #7821, which has some discussion going around this.
