### ISSUE TITLE
Customizer foundation.min.js files fixed!

### ISSUE THREAD

**Issue by zurbchris** [zurb/foundation-sites#7088]
## If you download a copy of Foundation for Sites 6 from the [customizer](http://foundation.zurb.com/sites/download.html/), you can now use the foundation.min.js file it creates.
We're really sorry about the issues we had with that. 
![sorry](https://cloud.githubusercontent.com/assets/13631168/11314157/d815eafa-8f97-11e5-9a24-48f5378fb880.gif)

**Comment by marti1125** [comment]
:+1:

**Comment by Lynda333** [comment]
Thank You!

**Comment by DrustZ** [comment]
cool

**Comment by gccumber** [comment]
I'm using 6.1.2 for sites DL version. Is this still a nagging issue? I can't seem to get modals working at all.

**Comment by gakimball** [comment]
@gccumber Could you open a new issue with a code sample and a more detailed explanation of the issue? Thanks :)

**Comment by iampstew** [comment]
Still having problems with this...

**Comment by gccumber** [comment]
Sorry, I've been traveling. Yes I am, I'll open an issue later today.

**Comment by iampstew** [comment]
@gccumber its cool, I just realised my cache on my browser was for some reason referring to me to the V5 doc's and not V6... #AmAIdiot
