### ISSUE TITLE
[Sass] Docs Displaying Incorrect Install Instructions For NPM

### ISSUE THREAD

**Issue by weblee** [zurb/foundation-sites#7091]
**How can we reproduce this bug?**

1. Just viewing the docs markdown is rendering the sass install npm command incorrectly
2. See: http://d.pr/i/NS4j
3, Viewing the docs source its correct!!

I tried in my markdown editor and it does render correctly.

**Comment by gakimball** [comment]
Fixed via 67d45170f80a38043eb3dffe66cfd823a3e0b635

This change was deployed to the live docs last week.
