### ISSUE TITLE
[F6] Close button doesn't work in callouts

### ISSUE THREAD

**Issue by YuriGor** [zurb/foundation-sites#7096]
This issue can be reproduced just in [documentation](http://foundation.zurb.com/sites/docs/kitchen-sink.html#close-button)

**Comment by kennethlove** [comment]
Same issue here

**Comment by dasmikko** [comment]
Still an issue with 6.0.4

**Comment by gakimball** [comment]
That's an intentionally static example, as we don't necessarily want to imply that Callout or Close Button are inherently closable components. It's other JavaScript plugins that enable that functionality.

I updated the wording in the example callout to emphasize that the example is static.

**Comment by matanster** [comment]
Well then, how does one make it "not static", but actually working? :)
