### ISSUE TITLE
[F6][Top Bar][Responsive] Top bar does not collapse into hamburger at small screen

### ISSUE THREAD

**Issue by YuriGor** [zurb/foundation-sites#7097]
[Top Bar](http://foundation.zurb.com/sites/docs/kitchen-sink.html#top-bar) does not collapse into hamburger at small screen, as it did in F5.

**Comment by Lynda333** [comment]
Top Bar is different in F6. You have to use [Responsive Toggle](http://foundation.zurb.com/sites/docs/responsive-navigation.html#responsive-toggle) to achieve the same effect.

**Comment by YuriGor** [comment]
Oh thank you, missed this plugin. 
I don't know should this plugin be added to the Kitchen Sink or not, so i will leave this issue open.

**Comment by zurbrandon** [comment]
We're updating it on the licthen sink for the next release. I'll close this for now :)
