### ISSUE TITLE
[Sass] Not compiling properly

### ISSUE THREAD

**Issue by metaloha** [zurb/foundation-sites#7098]
On OSX, I have Ruby SASS 3.4.19 and Compass 1.0.3 installed. Using Grunt with `grunt-compass` helper, I have the following config:

	all: {
		options: {
			importPath: [
				'./node_modules/foundation-sites/scss'
			],
			sassDir: ['./src/sass/'],
			cssDir: ['./src/css/vendor/'],
			environment: 'development',
			force: true,
			sourcemap: true,
			relativeAssets: true
		}
	}

My main SCSS file (`./src/sass/foundation6.scss`) is:

	@import "settings";
	@import "foundation";
	.testRule {
		display: none;
	}

I expect the output to be a complete Foundation CSS file. Instead, `./src/css/vendor/foundation6.css` consists of the `normalize.scss` contents, the `body.is-reveal-open` rule from line 153 of `./node_modules/foundation-sites/scss/components/_reveal.scss`, and the `.foundation-mq` rule from line 51 of `./node_modules/foundation-sites/scss/foundation.scss`, and my `.testRule` rule. Nothing else. No other Foundation CSS to be seen anywhere.

This has been tested on both OSX 10.10 and 10.11

**Comment by colin-marshall** [comment]
Since you're using Compass, did you add the following line to `config.rb`?:

```ruby
 add_import_path "node_modules/foundation-sites/scss"
```

**Comment by metaloha** [comment]
I do have the following in my Gruntfile:

    importPath: [
        './node_modules/foundation-sites/scss'
    ]

If the import path wasn't working, I wouldn't see the Normalize rules.

**Comment by colin-marshall** [comment]
True. I was just asking because you said you were using Compass and in the docs it says to add that line if you're using Compass.
 http://foundation.zurb.com/sites/docs/sass.html#compiling-manually

I missed the part where you said you were using `grunt-compass` so I guess that means you wouldn't need to add it to `config.rb` too.

What happens when you change your main scss file to the following?:

```scss
@import "settings";
@import "foundation";
@include foundation-everything;
.testRule {
    display: none;
}
```

**Comment by metaloha** [comment]
That seems to have worked!

Now that I look at the `foundation.scss` file a bit close, I notice that `foundation-everything` is a mixin.

And now that I read that page a bit closer, I see where it actually says to add `@include foundation-everything`. Geez.

Thanks Colin!
