### ISSUE TITLE
[Global Styles] Variable '$global-margin' described twice in docs

### ISSUE THREAD

**Issue by YuriGor** [zurb/foundation-sites#7101]
variable '$global-margin' [described](http://foundation.zurb.com/sites/docs/global.html#sass-variables) twice with different description:

Name | Type | Default Value | Description
-------- | ------- | ------------------ | ---------------
$global-margin | Number | 1rem	 | Global value used for margin on components.
$global-padding | Number | 1rem | Global value used for padding on components.
$global-margin | Number | 1rem	 | Global value used for margin between components.

Same issue at _settings.scss itself:
```scss
$global-margin: 1rem;
$global-padding: 1rem;
$global-margin: 1rem;
```

**Comment by gakimball** [comment]
Merged in #7107
