### ISSUE TITLE
Responsive Menu - Vertical Drop Down - Bug

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites#7105]
In the Docs
http://foundation.zurb.com/sites/docs/responsive-navigation.html

The Responsive  Vertical Drop Down Menu  is misbehaving badly.

This is a similar issue to  the Vertical Drop Down menu I posted earlier

https://github.com/zurb/foundation-sites/issues/7074
![responsive menu](https://cloud.githubusercontent.com/assets/14908417/11317052/da9a7a9a-8fdb-11e5-80d9-d64f78048d21.jpg)

**Comment by gakimball** [comment]
We fixed many issues with the responsive Menu classes and Responsive Navigation in 6.2, including this. :)
