### ISSUE TITLE
F6 Flex grid alignmet with sass using custom css styles

### ISSUE THREAD

**Issue by sashafokin** [zurb/foundation-sites#7106]
Hello! I got a promblem with flex colum alignment. Now i trying to use Foundation 6 with new feature called Flex Grid.

I sure, that is a great thing, but i need help. I want to use custom CSS classes:

.custom{@include flex-grid-column(6);}

And also i need keep it middle. I tried to use some combinations like:
.custom{@include flex-grid-column(6); @extend .align-middle;}
.custom{@include flex-grid-column(6); @include align-middle;}
etc...

I know, that is very important feature, please fix this bug!

**Comment by gakimball** [comment]
We added two new mixins for alignment of columns in the flex grid.

```scss
.custom-row {
  // You can use $x, $y, or both
  @include flex-grid-row-align($x: center, $y: stretch);
}

.custom-column {
  // Columns use the same vertical alignment terms as rows
  @include flex-grid-column-align(middle);
}
```

These new mixins will land in 6.1, which we're releasing tomorrow.

**Comment by sashafokin** [comment]
Yay! Thanks, guys! Love u, zurb:)
