### ISSUE TITLE
Javascript error at Yeti Launch startup

### ISSUE THREAD

**Issue by pentool** [zurb/foundation-sites#7110]
1. Download Yeti Launch
2. Open the DMG archive
3. Copy Yeti Launch into application folder
4. Launch Yeti Launch
5. See attached javascript error right at the start

Mac mini late 2012
El C(r)apitan 10.11.1

![screen shot 2015-11-21 at 5 50 40 am](https://cloud.githubusercontent.com/assets/1972916/11318759/28475f28-9014-11e5-860f-7a5719711abb.png)

**Comment by blynnc** [comment]
Also reported here

https://github.com/zurb/foundation-sites/issues/7090

**Comment by frankspin89** [comment]
Also reported here

https://github.com/zurb/foundation-sites/issues/7038

**Comment by erikmellum** [comment]
We are in the process of QAing the patch for this bug. Thanks everyone for letting us know!

**Comment by erikmellum** [comment]
Hello everyone,

The patch been released! You can download it at http://foundation.zurb.com/develop/yeti-launch.html.

### The patch addresses:
* Javascript error on startup
* Scss error reporting @blynnc
* Glitch for users with a space in their path trying to open an editor

### Big enhancement:
* Hosted code integration

### A few other minor enhancements:
* Allow underscores in project names @blynnc 
* Change editor button in settings sidebar

Thanks everyone for your patience,
Erik

**Comment by zzplab** [comment]
Sorry Erik, but I removed the old version, downloaded the new one, but still get the same javascript error.
Is the download not updated or still a bug?

**Comment by erikmellum** [comment]
@zzplab,

It is possible that the link took a second to update, especially if the page was cached. I'd recommend clearing cache, and downloading again. I downloaded again on a new mac running 10.11 and saw the updated version. Please let me know if you are still encountering this issue. I'll be happy to work with you till it is resolved.

Thanks,
Erik

**Comment by zzplab** [comment]
Cache is usually frequently deleted wit today's data, just now did a full history clean up. Never happy with that, but:
Now it works fine and I get the new version. Thanks!

**Comment by erikmellum** [comment]
@zzplab,

Thanks for checking again. I've heard a few people run into this and I know its frustrating. Good to know that a full history clean up / cache clear will resolve it. I'll also see if this is something we can solve from our end so that users aren't required to take the extra steps. At any rate, thanks for letting me know!

- Erik

**Comment by zzplab** [comment]
No problem, happy to help.
I saw that the DMG was passed trough cloudfront. Maybe that cache was not updated (yet) when trying before...
I download from Europe.
