### ISSUE TITLE
Foundation 6 inline buttons broken when using <button> or <input> tag

### ISSUE THREAD

**Issue by rushmorem** [zurb/foundation-sites#7116]
Foundation 6.0.3 [Inline Labels and Buttons](http://foundation.zurb.com/sites/docs/forms.html#inline-labels-and-buttons) break when one uses a `<button>` or an `<input>` tag instead of an `<a>` tag.

**Comment by proimage** [comment]
Can confirm. This is pretty big; the standard button for performing an action in a form is an `<input>` or `<button>` tag, NOT an `<a>` tag.

**Comment by andycochran** [comment]
It's also a best practice to use `<button>` anytime you make something look like a button (outside of forms). So an inline list of `<button>` elements should be fairly common.

**Comment by gakimball** [comment]
See #7278. The HTML example has been updated, and a fix for `<button>` (and `<input>`) will land in the next patch.
