### ISSUE TITLE
Passing options to plugins

### ISSUE THREAD

**Issue by cbrunet** [zurb/foundation-sites#7120]
In the documentation, it is stated (javascript.html) we can pass options like this:

    <div data-accordion data-slidespeed="500" data-multiexpand="true"></div>

However, it seems the correct syntax is:

    <div data-accordion data-slide-speed="500" data-multi-expand="true"></div>

Furthermore, I wasn't able to use `data-options` to pass options (I tried with orbit slider). In that case, I'm not sure if it is a documentation problem or a JavaScript problem.

**Comment by bwydev** [comment]
I'm seeing the same thing. For example on dropdown menu data-disable-hover="true" works, not data-disableHover="true".

**Comment by zurbchris** [comment]
That's an error on the docs. Everything in Foundation 6 is camelCased, and javascript natively will change that to kebab-case for data attributes. So, if you are setting options with data tags, use kebab-case, if you're programmatically generating plugins with JS, you can use the markup syntax, or pass an options object who's keys are camelCase. The `data-options="option1: true; option2: false;"` method from Foundation 5 is not currently implemented, though it's a future feature. Sorry it's in the docs and causing confusion.

**Comment by gakimball** [comment]
Updated the documentation to:
- Fix that Accordion example
- Clarify the camelCase -> hyphens mechanics
- Remove references to `data-options`

We'll get `data-options` re-added soon.
