### ISSUE TITLE
What About Foundation-Rails for Version 6 ?

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#7122]
Just wanna know how early we can expect Foundation 6 for Ruby on Rails ?

**Comment by cveneziani** [comment]
+1 :smile:

**Comment by gakimball** [comment]
We're working on it this week and next week!

**Comment by gakimball** [comment]
Update: the gem is almost ready, just have a few kinks to work out.

**Comment by gakimball** [comment]
We shipped the gem last week :) [foundation-rails](https://rubygems.org/gems/foundation-rails)

Foundation 6.1.1 is the first version to work with it.
