### ISSUE TITLE
Extra wrong title tag on website (emails.html)

### ISSUE THREAD

**Issue by GBratsos** [zurb/foundation-sites#7123]
Hello,
I do not know if this is the right issue tracking to open this issue. Correct me if i am wrong.

ISSUE:
There is an extra wrong title tag on this web page
http://foundation.zurb.com/emails.html

**Comment by IamManchanda** [comment]
Though this a coding bug , this will work bro 

    <title><title>Foundation for Emails | A Responsive Email Framework from ZURB</title></title>

**Comment by GBratsos** [comment]
I know this will work, but i do not know where to find the emails.html file and if this is the right Issue tracking list.

**Comment by zurbrandon** [comment]
This is all fixed up! Thanks :)
