### ISSUE TITLE
[Download/Docs] Few bad things on the Foundation website

### ISSUE THREAD

**Issue by NicolasGraph** [zurb/foundation-sites#7125]
Thank you guys for F6.
I saw few bad things in the docs and on the following page ckeckboxes are in mess: http://foundation.zurb.com/sites/download.html/ 
The *Typography* box is under *Navigation*, the *Drill menu* box is under *Typography*, *Forms* and *Buttons* are also switched, *Sticky* is not under *Javascript Components* and the first box which should enable or disable others don't work on Firefox. Moreover, on this page, the topbar link to the *Docs* is also wrong and through *Not found*…
In the docs, I c'ant see any mixins for forms to update prefix/postfix elements, is that normal?
…And if you are on a *Sites Docs* page, the *Develop* link generate a 404 error.

**Comment by eniosan** [comment]
Hi,
Yes, I noticed that too!
But not just that... 
If you wish to customize your F6 download by unchecking some components and options, it wont actually do that... it ends up removing components you wanted and keeping others you didnt want... colors wont work either. Tried it in Firefox and Chrome.
So you have no other option but to download the complete version... which by the way, is not complete, for it lacks many CSS classes and a few JS lines as well.

**Comment by Lynda333** [comment]
There are [several problems](https://github.com/zurb/foundation-sites/issues/7033) with the customizer page. Hope they get it fixed soon.

**Comment by zurbrandon** [comment]
These have been fixed, some deployed and some waiting in queue till tomorrow. I'll close this for now but feel free to update if you still notice something wrong.

**Comment by NicolasGraph** [comment]
Most of the previous problems are now solved but the *All Foundation Components* checbox still not works, and mainly, the downloable version is 6.0.1 while the current one is 6.0.5. I had a time with an off-canvas because of that.
