### ISSUE TITLE
[Equalizer] Equalizer return empty arrays as heights in tabs

### ISSUE THREAD

**Issue by marco8757** [zurb/foundation-sites#7126]
Data equalizer returns a list of empty arrays when data equalizers are being used in tabs that not having 'is-active' by default.

To replicate the error, please construct a multiple tabs html, and place content with data-equalizer on second or third tab and set first tab with 'is-active'

**What did you expect to happen?**
Data equalizer works on when tab is activated.

**What happened instead?**
Heights of data equalizers item are not equalized, requiring user to resize the window to trigger the data-equalizer to work again.

**Comment by zurbchris** [comment]
If you want your tabs to be equal height, set the attribute `data-match-height` to true in your markup. No need to bring Equalizer into it :smile:

**Comment by zurbrandon** [comment]
Looks like this is solved, so i'll close this.
