### ISSUE TITLE
[Abide] Form + abide validation does not submit

### ISSUE THREAD

**Issue by zzplab** [zurb/foundation-sites#7127]
**How can we reproduce this bug?**

I've tested locally with Prepos, Yeti launch and online on my web server and jsfiddle, all with the same result. I cannot submit the form with abide validation.
I think my setups have been good (otherwise any tips are welcome).
I've made a basic test at jsfiddle to show the same result.

1. Go to:
[example jsfiddle](http://jsfiddle.net/ZZPdev/xgyr4bLt/)
2. Submit the form with abide validation without a value present.
You ll see the normal validation error.
Fill in a value.
Submit the form.
3. Or directly fill in a value and submit.
4. The second form is for comparison only, the only difference is it has no validation.

**What did you expect to happen?**
If no value is present abide prevents the form being submitted. That works fine.
If a value is present in the abide form > the form should be submitted when Submit is clicked.
**What happened instead?**
Nothing when a value is present on submit. No error is shown and cannot submit.
**Test case**
[example jsfiddle](http://jsfiddle.net/ZZPdev/xgyr4bLt/)

**Comment by robbyrice** [comment]
After upgrading to Foundation 6 I have run into this same problem.  Using the Abide plugin on a form prevents the form from being submitted, even when validation criteria have been met.  Additionally, the validation does not work on any other kind of input than type="text".  Hoping this gets resolved quickly because it is a big deal breaker.

**Comment by anothergituser** [comment]
Same here! After validation the form will not submit.

**Comment by zzplab** [comment]
@anothergituser Great! This [#7357](https://github.com/zurb/foundation-sites/issues/7357) solves the issue.

**Comment by zurbchris** [comment]
Should be fixed with #7590, please comment and submit pr's to the `abide` branch until 6.1 release.
