### ISSUE TITLE
Foundation tabs are broken

### ISSUE THREAD

**Issue by matt3224** [zurb/foundation-sites#7128]
Please see screenshot, this is breaking the foundations tabs.
![screen shot 2015-11-22 at 18 18 45](https://cloud.githubusercontent.com/assets/2401925/11325430/80534984-9145-11e5-9a3c-cde33235e803.png)

**Comment by zurbchris** [comment]
That's how the tabs are initialized, you must include an href value in your tab link in order for the js to know where to look for your corresponding tab.
