### ISSUE TITLE
[JS] [Dropdown Menu] submenu links doesn't work

### ISSUE THREAD

**Issue by imranomari** [zurb/foundation-sites#7129]
Submenu links in the dropdown menu doesn't work, clicking the links closes the dropdown and doesn't redirect to the url.

Tested using version 6.0.3, Chrome  46.0.2490.86, OSX 10.11.1

**Comment by kapooostin** [comment]
I have the same issue.

6.0.3, Chrome 49.0.2572.0 canary (64-bit), OSX 10.10.5/

**Comment by cabdesigns** [comment]
A slight fix is to move the e.prevent/stop in this recent commit:

https://github.com/zurb/foundation-sites/commit/1de4ee9e14d043a6b32b16f852c7cee878949c14#diff-4cf6360d3bca32bd9c93c4f8d96ead70R184

and put it into the else block (effectively !hasClicked). However, this means the close link on the submenu will follow through, usually taking you through to #, so it's not an ultimate fix.

I don't know the code well enough, but it needs a way of determining if the link click is a submenu child link or just the submenu toggle (which should prevent default). Hope that's helped.

**Comment by kapooostin** [comment]
Thanks! Meanwhile I took DropdownMenu.js from [this](https://github.com/zurb/foundation-sites/commit/630b0eacc2651716a51e55749555687cac703b8c) commit and it works fine so far.

**Comment by matzidis** [comment]
Hi I downloaded the complete version of foundation6 from the download page on the foundation site and I only have foundation.js and foundation.min.js and then a vendor folder with jquer.min.js and what-input.min.js. How do I go about updating my files so that my dropdown works? Any assistance will be appreciated.

**Comment by matzidis** [comment]
I found the 6.0.4 versions of the js files on github and updated my docs. dropdown working fine now.
