### ISSUE TITLE
[Docs] Making “Number” a bit more precise

### ISSUE THREAD

**Issue by HugoGiraudel** [zurb/foundation-sites#7130]
What about making *Number* from SassDoc comments a bit more precise by using *Length* for actual lengths, such as `42px`, *Integer* for integer such as `42`, and *Duration* for time-based values such as `42ms`?

Happy to make a PR if needed.

**Comment by gakimball** [comment]
Yep, that makes sense—I noticed you did the same thing with Motion UI. I also generally find them more readable. For example, `Shadow` or `Transition` would be more descriptive than `List`, even if that's what the proper Sass value is.

**Comment by gakimball** [comment]
Going to close this due to lack of activity.

We're doing a hardcore issue burn-down this week. Once the issue tracker is more stable, we'll have a bit more leeway to make codebase improvements like this.
