### ISSUE TITLE
Field group is broken due to input margin

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#7145]
I have some form field with prefixes and suffixes so I have altered the html to reflect the "Inline Labels and Buttons" section in here http://foundation.zurb.com/sites/docs/forms.html
But it turned out that the input has bottom margin(the $form-spacing variable) that is not reflected in the .input-group-label or .input-group-button classes. So the result is:
![margin](https://cloud.githubusercontent.com/assets/3159095/11337088/8a06e634-91ea-11e5-8757-ef4c454b6b97.png)

**Comment by gakimball** [comment]
The class does have a bottom margin, which overrides the normal `<input>` styling.

![screen shot 2015-12-03 at 3 53 57 pm](https://cloud.githubusercontent.com/assets/1142001/11577932/1fd0644a-99d6-11e5-935f-52a1c3dab8f9.png)

Can you post a code sample so we can recreate this?

**Comment by ivanjaros** [comment]
![ff-input](https://cloud.githubusercontent.com/assets/3159095/11585482/a86f1792-9a6c-11e5-92d0-58666c726117.png)

**Comment by ivanjaros** [comment]
I cut the image a bit too much. The elements are wrapped in .input-group

**Comment by gakimball** [comment]
`.input-group-field` is applied directly to `<input>`. Only `.input-group-button` requires a wrapper.

**Comment by ivanjaros** [comment]
You are correct, I have removed the wrapper and it works as designed. Thank you.
