### ISSUE TITLE
Pagination has wrong documentation

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#7146]
On the pager example page the "current" class is said to be applied to the li element. But it breaks the visual. Instead it should be applied to the link itself.

Foundation 6.0.3.

**Comment by gakimball** [comment]
I'm not seeing the issue you describe—the code and the rendered example in the live docs look fine to me.

The current page intentionally doesn't have a link inside of it for accessibility reasons.

**Comment by ivanjaros** [comment]
You are correct. I'm on Drupal 8 and it displays links for all items, even for the current page. I have changed the template and now it's fine. Thanks for pointing out the issue.
