### ISSUE TITLE
Callout - Closable Plugin link missing

### ISSUE THREAD

**Issue by anismashku** [zurb/foundation-sites#7147]
On Callout docs page Closable Plugin link missing.
Plus in the Complete (Download Everything) version the Callout with Closable feature doesn't work.
Page is missing: http://foundation.zurb.com/sites/docs/closable.html

**Comment by colin-marshall** [comment]
Good find, that should be a link to the [Close Button](http://foundation.zurb.com/sites/docs/close-button.html).

What version of Foundation 6 are you using? Update to 6.0.3 if you're not already there. Also, what browser is the callout with close button not working in?

**Comment by gakimball** [comment]
Merged in #7167 which resolves this.
