### ISSUE TITLE
[CSS] hr left and right borders

### ISSUE THREAD

**Issue by NicolasGraph** [zurb/foundation-sites#7151]
On Firefox, dividers are displayed with a black dot on the left, coming from the left border. Removing the left border fixed this bug for me. You could also use a 1px height on dividers with a background-color instead of border-top…

**Comment by andycochran** [comment]
Not just FF; there's a dot there in Chrome too. And there's a dot on the right (tho it's a lighter, less noticeable color). You can see them both clearly if you change the `height` of the `<hr>` to `10px`. need the following added to the `hr{}` rule: 
```
border-right: 0;
border-left: 0;
```

**Comment by andycochran** [comment]
Fixed in #7153.
