### ISSUE TITLE
[Off-canvas] reveal-on-large obscured by off-canvas-wrapper-inner

### ISSUE THREAD

**Issue by paulterry** [zurb/foundation-sites#7154]
I am just updating a project to F6 and have come across a small issue.
This project uses an off-canvas menu for small screen navigation, this works fine in F6. However, on large screens I have a secondary menu which mimics the off-canvas menu but is always visible down the left of the screen. Upon downloading starting to use F6, i notice there is a fantastic class named "reveal-for-large" as part of the off-canvas element. Obviously, this class made me very excited as I would no longer need to duplicate the menu. However, in the small amount of testing I have done with this class, it appears the links within the menu are not clickable - they are obstructed by the .off-canvas-wrapper-inner element .

The same problem exists on the Foundation Docs site for Off-Canvas - http://foundation.zurb.com/sites/docs/off-canvas.html , for the off-canvas menu featured there.

**Comment by paulterry** [comment]
For anyone coming across this. It can be resolved by changing a z-index:
```
@media only screen and (min-width: 64em) {
    .off-canvas
    {
        z-index:1;
    }
}
```
I'd rather there was a more elegant - non z-index solution as I'd rather not have to give my content block a left margin to be fully-visible. But I guess this will do for now.

**Comment by gakimball** [comment]
`z-index: auto;` also works, so I went with that. Also added a Sass variable to enable or disable having the menu be fixed-position when it's revealed.

We'll have a patch out today with this fix!
