### ISSUE TITLE
Disabled <button> elements doesn't get styled 

### ISSUE THREAD

**Issue by JoelESvensson** [zurb/foundation-sites#7160]
I've included the button mixin but my `<button>` element doesn't get the `button[disabled]` style

**Comment by ocularrhythm** [comment]
I tried reproducing this bug using Foundation 6.0.5 but the button imports the correct styling.

**Comment by JoelESvensson** [comment]
Are you really sure that you get the styling from `[disabled]` and not `.disabled`?

**Comment by ocularrhythm** [comment]
I created a test class `.testbutton` and inside the rule I included the mixin `@include button-disabled;`

I then created a button element `<button class="button testbutton">Test</button>` which had the CSS properties of `opacity: 0.25` `cursor: not-allowed` `pointer-events: none`.

If you are expecting the mixin to add a `disabled` attribute to the button, that is not what it does. This only adds the three CSS properties to the rule. From the docs `Adds disabled styles to a button by fading the element, reseting the cursor, and disabling pointer events.`

**Comment by JoelESvensson** [comment]
Okay. My main point is that I expected `@include foundation-button;` to include that styling for the disabled attribute as well. In my opinion it should because it seems like a very standard use case to add that

**Comment by JoelESvensson** [comment]
(I accidentally clicked close)

**Comment by ocularrhythm** [comment]
My mistake, I totally misunderstood what you meant. Looking in the `_buttons.scss` it is clear that there is no styling being given to the `disabled` attribute. I'm not sure how Zurb wants to approach this, but I have made a [fix](https://github.com/zurb/foundation-sites/pull/7485).

**Comment by JoelESvensson** [comment]
:) Thanks!

**Comment by zurbrandon** [comment]
Merged this in @ocularrhythm . We'll close out this issue. Thanks!
