### ISSUE TITLE
[JS][Dropdown Menu] Submenu anchor won't close dropdown

### ISSUE THREAD

**Issue by cabdesigns** [zurb/foundation-sites#7161]
Because of a very recent commit, isTouch evals to true in Chrome on desktop:

https://github.com/zurb/foundation-sites/commit/f06ff18233083a130c85bc8dceed343282d235a5#diff-4cf6360d3bca32bd9c93c4f8d96ead70R178

This results in the method short circuiting, and not being able to close the menu.

In Chrome, window.ontouchstart is set to null (not undefined). A potential fix would be to change the check to be !== undefined && !== null, but I don't know how this would impact other browsers.

Reproduced using following markup:
```
<ul class="dropdown menu" data-dropdown-menu data-disable-hover="true">
    <li class="has-submenu">
        <a href="#">
            Menu
        </a>
        <ul class="submenu menu vertical" data-submenu>
            <li><a href="#">One</a></li>
            <li><a href="#">Two</a></li>
        </ul>
    </li>
</ul>
```

**Comment by zurbchris** [comment]
There's a new version of dropdown menu coming out soon that should clear up the jank of the current version.

**Comment by cabdesigns** [comment]
Hey @zurbchris, is this now fixed in a branch somewhere?

**Comment by zurbchris** [comment]
6.0.4 was launched yesterday evening. New dropdown, totally different javascript, totally backwards compatible with your existing markup and other stuff. Should be fixed now, if not, open a new issue for the new plugin. Thanks!
