### ISSUE TITLE
Yeti Launch Global Defaults Stale

### ISSUE THREAD

**Issue by getup8** [zurb/foundation-sites#7166]
Sorry, wasn't sure where to post this, might just be a small bug with Yeti Launch.  I think the default values that are all commented out in the basic template (/scss/_settings.scss) are stale.

e.g. // $global-radius: 3px;

Doesn't affect the styles since the actual files seem right but would be nice to correct this since the purpose is to be able to reference what the default is.

**Comment by erikmellum** [comment]
@getup8,

A new version of Yeti Launch has been released. I created a basic project, and used the settings to successfully change the primary color. I believe that the basic projects were not switched to use the most up to date version. We fixed this in the new version, apologies for any inconvenience that caused you. Let me know if you have any more trouble, I'd be happy to help you get it all going!

Thanks,
Erik
