### ISSUE TITLE
Hover Dropdown Has a Problem...I cannot interact with the dropdown. 

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#7168]
I am using a hover dropdown to add some content into the dropdown. In F5 I could use this and when I moused into the dropdown it would stay open. In F6 it doesn't do this. The moment you mouse out of the element that opens the dropdown (after the set delay) it closes even if the mouse is inside the dropdown. 

For me, with the way I use hover dropdowns, makes it almost useless. 

Is this a bug or intended behavior?

Toggle dropdown works as expected. 

(Note: I am using v6.0.3 of the JS.)

**Comment by Lynda333** [comment]
@zurbchris - Any ideas when this may be fixed or updated to work? I have a site I want to upgrade to F6 as it is still in development but need this working before I do. Thank You!

**Comment by simar88** [comment]
Hi everyone, any news about this bug?

**Comment by bwydev** [comment]
This is an important issue for me as well. Any workarounds?

**Comment by Lynda333** [comment]
@bwydev - Thank you for the tip. This should be added to the docs. This does seem to help, however, I'm still running into problems with it not staying open properly as well as z-index issues. If I increase the z-index the dropdown pane loses it's width and becomes full width! I've never seen that happen.

**Comment by Lynda333** [comment]
By adding the data parameter `data-hover-pane="true"` I can get it to work, however, there is an issue and I'm unsure if it is a Foundation issue or a problem with my code. 

When I hover over a dropdown it pops open and I can interact with it, as expected. When I hover out of the dropdown pane, it closes but there is a moment where the contents of the dropdown pane are still visible for a second, then the content hides as well.

Since the site is still in development and not public yet, here is a video of the issue: http://screencast.com/t/zcPzdzan

Here is the code I am using: 

    <div class="text-center">
        <button href="#" type="button" data-toggle="involved" class="button brand dropdown header-button">Get Involved</button>
    </div>
    <ul id="involved" data-dropdown data-hover="true" data-hover-pane="true" class="dropdown-pane">
        <li><a href="#">Item 1</a></li>
        <li><a href="#">Item 2</a></li>
        <li><a href="#">Item 3</a></li>
        <li><a href="#">Item 4</a></li>
        <li><a href="#">Etc.</a></li>
    </ul>

**Comment by rafibomb** [comment]
Not seeing that happen here http://codepen.io/rafibomb/pen/KVYPrJ I wonder what would cause that.

**Comment by Lynda333** [comment]
@rafibomb - I just sent you an email with a URL that shows the problem. The site is still under development so I don't want to post a link here in Github.

**Comment by Lynda333** [comment]
@rafibomb - I found the problem: 

   a {
      -webkit-transition: all .5s; 
      transition: all .5s;
    }
Removing this code fixes the problem but should a fix for this be applied in the Foundation framework? I ask that because I've seen this same code as part of other systems and it would be great if Foundation can account for this code?

Here is a fork of your pen showing the problem: http://codepen.io/Lynda333/pen/MKRXgV

**Comment by rafibomb** [comment]
I don't understand. The transition on the `<a>` is not part of the framework, right?. If you're looking to animate the dropdown, there is a different way. In the last comment here - John was able to use MotionUI to create the animation http://foundation.zurb.com/forum/posts/37397-animation-for-dropdown-menus

**Comment by Lynda333** [comment]
@rafibomb - The transition is for my links throughout the site, not the dropdown. It creates a smooth transition for any links on the site, which looks and works well. This is the first time I've ran into problems with any Foundation element. For some reason the transition on my links conflicts with the drop down causing it to display weird.
