### ISSUE TITLE
Links not working at dropdown submenus (Foundation 6.0.1)

### ISSUE THREAD

**Issue by igll** [zurb/foundation-sites#7171]
The links at dropdown submenus do not work completely:
- You can right-button-click "Open at new tab" and it opens the link.
- But if you click directly the link nothing happens.

The same link works OK when placed at the top leve of the topbar.

You can test it now at http://www.universalexport.es/

You can drop down "Popular" and then clic at "Google at submenu"

----------------------------------------------------------------
FULL SOURCE:

<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="css/app.css" />
  </head>
  <body>

    <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
      <div class="title-bar-title">Menu</div>
    </div>
    
    <div class="top-bar" id="example-menu">
      <div class="top-bar-left">
        <ul class="dropdown vertical medium-horizontal menu" data-dropdown-menu>
          <li class="menu-text">Search engines example</li>
          <li class="has-submenu">
            <a href="#">Popular</a>
            <ul class="submenu menu vertical" data-submenu>
              <li><a href="http://www.google.com">Google at submenu</a></li>
              <li><a href="http://www.bing.com">Bing at submenu</a></li>
            </ul>
          </li>
          <li><a href="http://www.google.com">Google at toplevel</a></li>
          <li><a href="http://www.bing.com">Bing at toplevel</a></li>
        </ul>
      </div>
    </div>
    
    <div class="row">
      <div class="large-12 columns">
        <h1>Foundation for Sites 6</h1>
        <h2>Possible bug Links at menues not working</h2>
      </div>
    </div>
  
    <script src="js/vendor/jquery.min.js"></script>
    <script src="js/vendor/what-input.min.js"></script>
    <script src="js/foundation.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>

**Comment by imranomari** [comment]
duplicated with #7129 and #7143 and #7172 , zurbchris is working on a whole new branch to fix dropdown menu issues b9f581c

**Comment by aibrean** [comment]
Drilldown also might be related to this... https://github.com/zurb/foundation-sites/issues/7099
