### ISSUE TITLE
[Dropdown Menus] Dropdown Menus links won't click

### ISSUE THREAD

**Issue by paulterry** [zurb/foundation-sites#7172]
I have noticed an issue when using Dropdown Menus in Foundation 6.

When hovering/clicking/tapping on the Dropdown Menu menu link it opens fine, but then the links contained within this dropdown menu will not work. You can click but that appears to close the menu rather than follow the link.
Again, this behaviour is also apparent on the Foundation 6 Docs Page.
http://foundation.zurb.com/sites/docs/dropdown-menu.html
The links on the Foundation Page above are admittedly onto to "#", but that should move to the top of the screen - which it does not.

**Comment by imranomari** [comment]
duplicated with #7129 and #7143 , looks like @zurbchris is working on a whole new branch to fix dropdown menu issues b9f581c3c09e1c82e3f7dfa41b45c7993d7820a7
