### ISSUE TITLE
[JS] Sticky + off-canvas

### ISSUE THREAD

**Issue by NicolasGraph** [zurb/foundation-sites#7173]
Take a look at the docs page for off-canvas. Click the *Toggle off-canvas* button and scroll the page. The right sticky sidebar get a strange position when it starts to stick; and it keep this position when you close the off-canvas untill you scroll to the top again to 'unstick' it.

**Comment by 5ulo** [comment]
mine sticky bar is having class "sticky is-stuck is-at-top" for about 600px scroll and then suddenly class changes to "sticky is-anchored is-at-bottom". Sticky bar isn't anymore at the top..
