### ISSUE TITLE
Off-Canvas variables are not customizable

### ISSUE THREAD

**Issue by agoradesign** [zurb/foundation-sites#7174]
We're currently working on our first site with Foundation 6 and we've found a quite serious bug. None of the scss variables used by off-canvas are marked as "!default", so none of them are overridable with  custom settings.

best regards,
Andreas

**Comment by NicolasGraph** [comment]
I can't use scss off-canvas settings neither.

**Comment by gakimball** [comment]
Fixed! We'll have a patch out today to address it.
