### ISSUE TITLE
Block Grid in Foundation 6

### ISSUE THREAD

**Issue by ceehaupt** [zurb/foundation-sites#7177]
Hi,

I was looking for the block grid in foundation 6 and couldn't find it. Any solution in the new foundation to grid a list?

**Comment by zzplab** [comment]
See: [Grids](http://foundation.zurb.com/sites/docs/grid.html)
Scroll down to Blockgrids.

**Comment by ceehaupt** [comment]
Thanks. Haven't seen it.
