### ISSUE TITLE
Component event handlers should be live

### ISSUE THREAD

**Issue by fergaldoyle** [zurb/foundation-sites#7181]
In F5 the `tab` click events were live, meaning after the plugin was initialized, you could add more tabs markup and the plugin could handle it nicely.

In F6, the click event is bound directly to a tab anchor on `_init`.
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.tabs.js#L142

To enable easier integration of other libraries, (specifically data binding libraries) I think in cases like this a "live" click handler should be used, bound to the overall tabs element.

e.g. `this.$element.on('click.zf.tabs', '.' + this.options.linkClass, handler)`

**Comment by gakimball** [comment]
I believe this was addressed via 19ef54216da4be5d30e2e6c87874a42bb8668496, but the issue wasn't closed.
