### ISSUE TITLE
Why we need padding-top for .flex-video?

### ISSUE THREAD

**Issue by marek95** [zurb/foundation-sites#7184]
hi,
why there is a need to define padding top for .flex-video class (padding-top: rem-calc(25)) ? youtube videos fits better without it. without black space on the top and bottom. isnt it just a leftover since old youtube player style?
thanks!

**Comment by zurbrandon** [comment]
We'll take a look. If i remember correctly we did this prior to the new youtube, so there's a chnace this is wrong in the framework.
