### ISSUE TITLE
[Dropdown Menus] Docs example don't have code samples

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#7185]
**How can we reproduce this bug?**

The docs examples for the vertical menu do not have examples.

![screen shot 2015-11-24 at 12 33 49 pm](https://cloud.githubusercontent.com/assets/5652085/11379991/4615b748-92a8-11e5-9acb-900e7a8b9684.png)

**Comment by zurbchris** [comment]
Addressed by 034f962
