### ISSUE TITLE
[Responsive Navigation] Responsive navigation is not responsive

### ISSUE THREAD

**Issue by ibovangeffen** [zurb/foundation-sites#7186]
**How can we reproduce this bug?**

1. Step one
Place the responsive code in your site, make the menu text some longer, so it wont fit the mobile screens.
2. Step two
Refresh the page

**What did you expect to happen?**
I expected a menu which would fit onto a screen of a full-hd phone.

**What happened instead?**
The menu doesn't fit ont the screen, you have to scroll to the right to see the full menu.
**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.
http://jsfiddle.net/w88x4jkh/ it's not as it should be because of the missing css/javascript files from foundation, but this code will generate the error

**Comment by zurbrandon** [comment]
The responsive navigation uses a series of plugins designed to allow you to customize the responsive nature to fit your navigation. 

Here's an example of one set up to both collapse and turn into a drilldown vertical menu on mobile screens. 

http://codepen.io/zurbrandon/pen/QyNKjV
