### ISSUE TITLE
Docs: Magellan Sticky Navigation not working

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7187]
i can't find a working example of a sticky magellan in the docs
```html
<div data-sticky="header">
  <ul class="horizontal menu" data-magellan>
    <li><a href="#first">First Arrival</a></li>
    <li><a href="#second">Second Arrival</a></li>
    <li><a href="#third">Third Arrival</a></li>
  </ul>
</div>
```

**Comment by zurbchris** [comment]
This one works.
<img width="765" alt="screen shot 2015-11-24 at 1 56 05 pm" src="https://cloud.githubusercontent.com/assets/13631168/11381855/693fdbda-92b3-11e5-8e1f-f9fc0e472e22.png">

**Comment by zurbchris** [comment]
Though, I'm guessing you're referring to a header bar specifically, and in that case, it's a known issue. I'm trying to get some minor updates to how sticky calculates break points to make it more usable for nav bars. Thanks for lookin' out!

**Comment by designerno1** [comment]
yes i am thinking about a header bar, as described in the code "horizontal menu"

**Comment by zurbchris** [comment]
Did you see this update? Code samples included.

<img width="740" alt="screen shot 2015-11-25 at 11 05 42 am" src="https://cloud.githubusercontent.com/assets/13631168/11406889/801691a8-9364-11e5-9c0d-ca1a34288295.png">

**Comment by designerno1** [comment]
thumbs up
i check it with my implementation tomorrow
