### ISSUE TITLE
[Responsive Navigation] vertical medium-horizontal menu expanded

### ISSUE THREAD

**Issue by zzplab** [zurb/foundation-sites#7188]
**How can we reproduce this bug?**
[see vertical medium-horizontal menu expanded > JSFiddle](http://jsfiddle.net/ZZPdev/9x55rxv5/)
1. This is the menu I want to build.
```
<ul class="vertical medium-horizontal menu expanded">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
    <li><a href="#">Link 3</a></li>
    <li><a href="#">Link 4</a></li>
    <li><a href="#">Link 5</a></li>
    <li><a href="#">Link 6</a></li>
</ul>
```
**What did you expect to happen?**
On medium-up screens I want to build a horizontal expanded menu.
On a small screen I want the menu to be a vertical menu **full width**.
I would expect that "vertical expanded" would automatically do this.
**What happened instead?**
On a small screen the menu is vertical but not full width as I would expect with a vertical menu.
**Test case**
I've tried to solve it in _menu.scss, but couldn't figure it out. Sorry.
Is it a bug?
This css solves the issue:
```
@media only screen and (max-width: 40em) {
    .menu.expanded li {
        width: 100% !important;
    }
}
```
I would expect it to work without this extra css.
[see vertical medium-horizontal menu expanded > JSFiddle](http://jsfiddle.net/ZZPdev/9x55rxv5/)

**Comment by zurbchris** [comment]
I see the problem, I'll see if one of our sass guys can do a patch on this or explain why we aren't. Expanded adds a percentage width to each `li`, and doesn't clear when it goes to vertical.
@gakimball  or @tdhartwick  wanna take a look at this?

**Comment by rafibomb** [comment]
It should be full width. We'll dig into the mixin to improve that.

**Comment by gakimball** [comment]
As of Foundation 6.1 this issue has been resolved. Check out [this CodePen](http://codepen.io/anon/pen/adEpdq) to see.

**Comment by chrischen** [comment]
Issue still exists with Flex mode.
