### ISSUE TITLE
Idea To Optimize css output

### ISSUE THREAD

**Issue by IllusionPerdu** [zurb/foundation-sites#7189]
It's not a beug but i find this :
https://www.npmjs.com/package/gulp-combine-media-queries 
I think you sould use this to minize the css file in your gulp task and it sould do a good reduce of size

**Comment by zurbrandon** [comment]
Will this not reorder how the cascade?

**Comment by IllusionPerdu** [comment]
I have not tested. If you want I can do some tests.

**Comment by gakimball** [comment]
@IllusionPerdu That would be helpful. We've gotten this request a few times, and I've never been able to get a definitive answer in terms of how it affects the cascade.

**Comment by zurbrandon** [comment]
We'd love some tests on this, but we'll close this for now. Feel free to reopen if you have any additional insights on it.
