### ISSUE TITLE
[Typography Helpers] Can't combine .text-center & .medium-text-right

### ISSUE THREAD

**Issue by drivingmenuts** [zurb/foundation-sites#7190]
**How can we reproduce this bug?**

    <div class="large-4 columns text-center medium-text-right">
        <p>Copyright 2015, Some Company Here<br>
            All Rights Reserved</p>
    </div>

**What did you expect to happen?**

On a mobile device, the text should be centered. On a desktop, the text should be right-aligned.

**What happened instead?**

Centered in both cases.

**Test case**

http://codepen.io/anon/pen/WQBLzY

**Comment by zurbrandon** [comment]
Looks like this has been all fixed up in 6.0.5

http://codepen.io/zurbrandon/pen/NxGNbR
