### ISSUE TITLE
Hex color convertion when downloading foundation 6

### ISSUE THREAD

**Issue by jonas89** [zurb/foundation-sites#7193]
Hi, is there any special reasson as to why all colors requested when setting up the template before downloading foundation 6, ends up beeing totaly different hexcode values after the custom-f6 is downloaded?

**Comment by erikmellum** [comment]
Hey @jonas89,

You ran into a bug I think we have since fixed This bug caused the settings to not be updated. We updated the customizer since then. Do you think you  could give it a try and see if that has fixed your issue? 

http://foundation.zurb.com/sites/download/

- Erik

**Comment by jonas89** [comment]
Hi there @erikmellum thx for the reply. I still have the save problem. Here u can see the template beeing downloaded, and the produced result.
![foundationdl](https://cloud.githubusercontent.com/assets/3840738/11436216/fa4f3ec8-94e2-11e5-8587-c843266bc65c.PNG)
![result](https://cloud.githubusercontent.com/assets/3840738/11436217/00634fb6-94e3-11e5-95ae-d8083a6009b7.jpg)

**Comment by zurbrandon** [comment]
@erikmellum can you confirm this has been fixed?

**Comment by jonas89** [comment]
Still got the same problem :/ 
![foundation](https://cloud.githubusercontent.com/assets/3840738/11530625/6b6c8680-98f6-11e5-880f-236395f25db3.jpg)

**Comment by jonas89** [comment]
Tested again today, seems like you guys patched the issue? Everything is working as intended now

**Comment by zurbrandon** [comment]
Awesome, yeah we've done a couple pushes of it. Thanks for reporting back!
