### ISSUE TITLE
$global-margin declared twice in settings.scss

### ISSUE THREAD

**Issue by MikeHarrison** [zurb/foundation-sites#7197]
$global-margin is declared twice in the settings.scss file, quick fix I am sure!

```
$body-antialiased: true;
$global-margin: 1rem;
$global-padding: 1rem;
$global-margin: 1rem;
$global-weight-normal: normal;
```

**Comment by NicolasGraph** [comment]
[v6.0.4](https://github.com/zurb/foundation-sites/releases/tag/v6.0.4) fixed that.

**Comment by IllusionPerdu** [comment]
In 6.0.4 it's not fixed !

**Comment by colin-marshall** [comment]
This was previously fixed but it looks like it got added back in by accident in the 6.0.4 commit: https://github.com/zurb/foundation-sites/commit/8ff8ba68f1d1b0b4c6299e0e1e6fee2b5999fcbe#diff-35a517bca933d90868763d8450d1da1e
