### ISSUE TITLE
[Toggler] Does not show up when using search

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#7198]

**Comment by zurbchris** [comment]
Shows up fine for me. What browser are you using?

<img width="293" alt="screen shot 2015-11-25 at 11 01 00 am" src="https://cloud.githubusercontent.com/assets/13631168/11406752/de10980e-9363-11e5-9450-01233326548c.png">

**Comment by phifa** [comment]
Ok I just realized something strange: When I type "togg", it does not show up. When I type "toggler”, it shows up?

**Comment by zurbrandon** [comment]
Yeah, this is a know issue with our search for some reason if you are typing 3-4 letters. We have this documented and are working on a fix.

**Comment by gakimball** [comment]
It was a bug with Typeahead, the autocomplete/search library we use.

Fixed via zurb/foundation-docs@83fe96ed4f3880c74e31f53642cee924c531ec1c
