### ISSUE TITLE
F6 block grid and sass promblems

### ISSUE THREAD

**Issue by sashafokin** [zurb/foundation-sites#7200]
hello, i need help with new grid system:
i need to use custom classes in foundation 6. 
Example:
.gl{@include grid-row(3); border: 1px solid green;}
.wp{@include grid-column; border: 1px solid orange;}
it looks like: http://awesomescreenshot.com/0225fm6u1e
at the bottom i show a example from docs. so where is the problem?

**Comment by zurbrandon** [comment]
The column needs to be nested inside to define 

.gl {
  @include grid-row(3) {
    .wp {
      @include grid-column(1);
    }
  }
}

I'll close this as it should solve your issue, but feel free to reopne if it hasn't
