### ISSUE TITLE
Compliling SCSS to CSS

### ISSUE THREAD

**Issue by jhibbeard89** [zurb/foundation-sites#7201]
When 'foundation watch' is typed in terminal in the file directory it is not creating new .css files from .scss folder.

**Comment by Lynda333** [comment]
Try `foundation build`. I've been using that to compile the css.

**Comment by NicolasGraph** [comment]
`foundation watch` works for me. Did you try to open and save `_setting.scss` or `_app.scss` and look at the terminal what happens in the terminal?

**Comment by zurbrandon** [comment]
Did you get this working?

**Comment by zurbrandon** [comment]
Looks like we haven;t heard back on this one. Seems to work on our end, but feel free to reopen if you're still having issues.
