### ISSUE TITLE
Foundation 6 - callout font color not used

### ISSUE THREAD

**Issue by escapedcat** [zurb/foundation-sites#7202]
Seems like `$callout-font-color` isn't being used at the moment:
https://github.com/zurb/foundation-sites/blob/develop/scss/components/_callout.scss
I searched the whole project but only find these definition, no actual use.
I only realized it because I wanted to modify the font color of a callout.

Let me know if I'm missing something. Thanks

**Comment by dherran** [comment]
It is actually not being used at all. Seems like a TODO in the list.
