### ISSUE TITLE
F6 Slider ignores decimal setting

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#7203]
I have double range slider on number inputs that have step set to 10 and the configuration of the slider has decimal set to 0 but when I move the handles it always uses two decimal places.

**Comment by ivanjaros** [comment]
I think this:
this.options = $.extend({}, Slider.defaults, this.$element.data(), options);

should be this:
this.options = $.extend({}, Slider.defaults, this.$element.data('options'), options);

**Comment by zurbchris** [comment]
It does not yet work with stepping, it's a near-future feature, expect that some time next week.

Also, it is definitely the first one. The `$element.data('options')`  is processed through Foundation.core

**Comment by zurbrandon** [comment]
@zurbchris I think this has been fixed as of 6.0.6, yes?

**Comment by zurbchris** [comment]
the decimal issue yes, the stepping, no

**Comment by gakimball** [comment]
Implemented with #7910
