### ISSUE TITLE
The Off-canvas menu didn't work on 6.0.4

### ISSUE THREAD

**Issue by rspt** [zurb/foundation-sites#7206]
With Foundation-sites v.6.0.4, the off-canvas didn't work anymore.

- It didn't change the left/right position
- The z-index is fixed at -1

---

My code is the following:
```
<div class="off-canvas-wrapper">
  <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
    <div class="off-canvas position-left" id="offCanvas" data-off-canvas>Off-canvas!</div>
    <div class="off-canvas-content" data-off-canvas-content>
      <button type="button" class="button" data-toggle="offCanvas">Open Menu</button>
    </div>
  </div>
</div>
```

**Comment by zurbchris** [comment]
What's not working? I just tested it on the live docs page, which was deployed on 6.0.4 last night, and everything seems to be working as it should.

**Comment by rspt** [comment]
The off-canvas never shows up. It stays hidden (in the left).

Do you have an idea from where this can come?

**Comment by rspt** [comment]
This is my code once I've toggled the off-canvas menu after pressing the button:

```
<div class="off-canvas-wrapper">
  <div class="off-canvas-wrapper-inner is-off-canvas-open is-open-left" data-off-canvas-wrapper="">
    <div class="off-canvas position-left is-open" id="offCanvas" data-off-canvas="" aria-hidden="false" data-offcanvas="d7ysz3-offcanvas">Off-canvas!</div>
    <div class="off-canvas-content" data-off-canvas-content="">
      <button type="button" class="button" data-toggle="offCanvas" aria-expanded="true" aria-controls="offCanvas">Open Menu</button>
    <div class="js-off-canvas-exit"></div></div>
  </div>
</div>
```

I'm using Safari 9

**Comment by rspt** [comment]
Okay I think it's me having a problem. Either with my Sass compilation or my JS compilation. It works well when I integrate distribution of Foundation.

I will investigate more and open a specific issue, if there is.

Thanks

**Comment by zurbchris** [comment]
Please do. We appreciate your efforts!
