### ISSUE TITLE
Drilldown didn't work with link, link are off

### ISSUE THREAD

**Issue by xfifix** [zurb/foundation-sites#7207]
the links are off, we can't click on it when it is the last one in the tree... it's a shame for a navigation menu ...

**Comment by zurbchris** [comment]
Can you show me an example or more specifically describe this problem?

**Comment by zurbchris** [comment]
Nevermind, I see the issue.... drilldowns are killing me

**Comment by zurbchris** [comment]
I'll get this patched asap

**Comment by aibrean** [comment]
Related: #7099

**Comment by zurbchris** [comment]
Should be fixed now, please reopen if not. :smile:
