### ISSUE TITLE
[Flex Grid] Initial instance of column width needs to be noted for FF

### ISSUE THREAD

**Issue by aibrean** [zurb/foundation-sites#7208]
**How can we reproduce this bug?**
If you use the following markup:

```html
<div class="row">
<div class="columns">
<img src="http://placehold.it/1350x350">
</div>
</div>
```

You will see the image overlaps past the row container in Firefox. 

Works perfectly:
```html
<div class="row">
<div class="columns small-12">
<img src="http://placehold.it/1350x350">
</div>
</div>
```

This is more or less an issue with the Foundation 6 documentation as there is not the explicit specificity on defining column width for small (especially in the alignment area). It could be additional markup is needed for images that reside in flex grid containers.

- See codepen
http://codepen.io/aibrean/pen/XmLbrd

**What did you expect to happen?**
The column image would constrain to the row width.

**What happened instead?**

The column expands to be larger than the row to allow for 100% width of the image.

**Comment by gakimball** [comment]
We had this issue in Foundation for Apps, see [here](https://github.com/zurb/foundation-apps/commit/ba78792c5373b4508795bccf6bdbb12297465a57#diff-3d390aacda1f31a9ad4d06d5971820e4). There's a fix we implemented that has some other side effects.

Looking into it further!

**Comment by gakimball** [comment]
Following up on this:
- We can't add an intrinsic size to the plain `.columns` class, because it needs to expand.
- Putting `max-width: 100%` on `img` elements doesn't fix it unfortunately.
- Putting `width: 100%` on `img` *does* fix it, but then we're assuming you want images to be full-width by default. The selector (`.column img`) would also be difficult to override.

I'll see what the team thinks.

**Comment by gakimball** [comment]
After looking over this, doing `.column img { width: 100%; }` is a little spooky, so instead we're adding a note to the top of the flex grid docs explaining how to get around this. Until Firefox fixes this bug, developers will need to manually size images inside of flex columns, either with a specific width, or 100%.
