### ISSUE TITLE
Abide's validateForm doesn't fire an event

### ISSUE THREAD

**Issue by nviitala** [zurb/foundation-sites#7209]
Currently there is no way to see if the form is valid, when handling a form submission via JS (using data-abide="ajax" novalidate). validateForm method doesn't seem to return a value or fire an event.

On Foundation 5 I used on('valid.fndtn.abide') which was fired after form submission. In Foundation 6 it fires every time a single field is validated.

**Comment by zurbchris** [comment]
Should be fixed with #7590, please comment and submit pr's to the `abide` branch until 6.1 release.
