### ISSUE TITLE
some bugs in RTL

### ISSUE THREAD

**Issue by hsen-dev** [zurb/foundation-sites#7211]
![image](https://cloud.githubusercontent.com/assets/838769/11409161/33ed142c-93d3-11e5-94fa-1d4b546180a6.png)

**Comment by gakimball** [comment]
Both of those components have RTL support. Make sure you have the `$global-text-direction` variable set to `rtl` in your Sass files. Here's what I see in our documentation:

![image](https://cloud.githubusercontent.com/assets/1142001/11578706/b63b858a-99dc-11e5-9539-3c29350cd0a4.png)

![image](https://cloud.githubusercontent.com/assets/1142001/11578715/c3617616-99dc-11e5-892e-7bf9fd99acb1.png)

If you're still having issues, could you post a code example we can test? Thanks!

**Comment by gakimball** [comment]
Actually, on closer inspection, I realize the actual issue. The customizer was not properly setting up RTL downloads, which is why the files you got don't work. We just deployed a fix for this today, so all new downloads will have the proper RTL CSS.
