### ISSUE TITLE
F6 6.0.4 Foundation.Equalizer.destroy missing

### ISSUE THREAD

**Issue by shawnnaquin** [zurb/foundation-sites#7212]
line 143 foundation.equalizer.js
      Equalizer.prototype.destroy = function(){
        //TODO this.
      };

**Comment by agoradesign** [comment]
Same problem for me... Equalizer is always very important for us! :-(

**Comment by shawnnaquin** [comment]
for now I'm working around like this: 
    init: function(){
        $('#js-eq').attr('data-equalizer','');
    },
    destroy: function(){
        $('#js-eq').removeAttr('data-equalizer');
    }
might get tricky if you have more than one instance.

**Comment by zurbrandon** [comment]
This is all fixed up in the 6.1 branch, so i'll close this out now.
