### ISSUE TITLE
[Accordion] Wrong handle js functions "toggle", "up", "down"

### ISSUE THREAD

**Issue by zaharsk** [zurb/foundation-sites#7220]
# HTML
	<ul id="acc" class="accordion" data-accordion role="tablist">
		<li id="data_header" class="accordion-item is-active">
		<a href="#data_panel" id="data_heading" class="accordion-title" role="tab" aria-controls="data_panel">Data</a>
			<div id="data_panel" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="data_heading">
				
			</div>
		</li>
		<li id="main_header" class="accordion-item">
			<a href="#main_panel" id="main_heading" class="accordion-title" role="tab" aria-controls="main_panel">Main charts</a>
			<div id="main_panel" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="main_heading">
				
			</div>
		</li>
		<li id="levles_header" class="accordion-item">
			<a href="#levels_panel" id="levels_heading" class="accordion-title" role="tab" aria-controls="levels_panel">Levels charts</a>
			<div id="levels_panel" class="row large-up-2 accordion-content" role="tabpanel" data-tab-content aria-labelledby="levels_heading">
				
			</div>
		</li>
	</ul>
# JS
	$('#acc').foundation('toggle', $('#main_header'));	
# Rendered before js
	<ul id="acc" class="accordion" data-accordion="" role="tablist" data-i="tmti6f-i">
		<li id="data_header" class="accordion-item is-active" aria-expanded="true" aria-selected="true">
			<a href="#data_panel" id="data_header" class="accordion-title" role="tab" aria-controls="data_panel" aria-expanded="false" aria-selected="false">Data</a>
			<div id="data_panel" class="accordion-content" role="tabpanel" data-tab-content="" aria-labelledby="data_header" aria-hidden="false" style="display: block;">
				
			</div>
		</li>
		<li id="main_header" class="accordion-item">
			<a href="#main_panel" id="main_header" class="accordion-title" role="tab" aria-controls="main_panel" aria-expanded="false" aria-selected="false">Main charts</a>
			<div id="main_panel" class="accordion-content" role="tabpanel" data-tab-content="" aria-labelledby="main_header" aria-hidden="true">
				
			</div>
		</li>
		<li id="levles_header" class="accordion-item">
			<a href="#levels_panel" id="levles_header" class="accordion-title" role="tab" aria-controls="levels_panel" aria-expanded="false" aria-selected="false">Levels charts</a>
			<div id="levels_panel" class="row large-up-2 accordion-content" role="tabpanel" data-tab-content="" aria-labelledby="levles_header" aria-hidden="true">
				
			</div>
		</li>
	</ul>
# Rendered after js
	<ul id="acc" class="accordion is-active" data-accordion="" role="tablist" data-i="tmti6f-i">
		<li id="data_header" class="accordion-item" aria-expanded="false" aria-selected="false">
			<a href="#data_panel" id="data_header" class="accordion-title" role="tab" aria-controls="data_panel" aria-expanded="false" aria-selected="false">Data</a>
			<div id="data_panel" class="accordion-content" role="tabpanel" data-tab-content="" aria-labelledby="data_header" aria-hidden="true" style="display: none;">
				
			</div>
		</li>
		<li id="main_header" class="accordion-item" aria-hidden="false" style="">
			<a href="#main_panel" id="main_header" class="accordion-title" role="tab" aria-controls="main_panel" aria-expanded="false" aria-selected="false">Main charts</a>
			<div id="main_panel" class="accordion-content" role="tabpanel" data-tab-content="" aria-labelledby="main_header" aria-hidden="true">
				
			</div>
		</li>
		<li id="levles_header" class="accordion-item">
			<a href="#levels_panel" id="levles_header" class="accordion-title" role="tab" aria-controls="levels_panel" aria-expanded="false" aria-selected="false">Levels charts</a>
			<div id="levels_panel" class="row large-up-2 accordion-content" role="tabpanel" data-tab-content="" aria-labelledby="levles_header" aria-hidden="true">
				
			</div>
		</li>
	</ul>
# Problems
	<ul id="acc" class="accordion is-active" - no reasons for "is-active" for ul
	<li id="main_header" class="accordion-item" aria-hidden="false" style=""> - panel "main_header" don`t down, but panel "data_header" is up

**Comment by zurbchris** [comment]
Wait, what's the problem? Can you link to an example so I can have a look?

**Comment by zaharsk** [comment]
https://jsfiddle.net/1bkLbaoc/5/
JS just collapse first tab of accordion, add "is-active" to <ul>

**Comment by zurbchris** [comment]
You're passing the wrong thing back. The `$target` used by the toggle method is a content pane, not a heading tab. Here is your fiddle, fixed: https://jsfiddle.net/z7j8k642/
