### ISSUE TITLE
DropDown always visible

### ISSUE THREAD

**Issue by xfifix** [zurb/foundation-sites#7221]
DropDown is always visible and is it possible to have the functionality mega menu like in the version 5 of Foundation ?

**Comment by xfifix** [comment]
<nav class="top-bar show-for-large" role="navigation">
  <ul class="menu">
<li>
<a href=".." data-toggle="xxxx" data-hover="true">xxxx</a>
</li>
</ul>

<div  data-dropdown id="xxxx">
<div class="row">
....
</div>
</div>
</nav>

**Comment by aibrean** [comment]
Mega menu is possible because I've done it. I have mine hidden when it hit the row width so I didn't have to do any further meddling to get it to scale.

**Comment by zurbrandon** [comment]
not 100% sure what you're stating here, do you have an illustration or code example you can show?

**Comment by zurbrandon** [comment]
I'll close this since we haven;t heard back, but feel free to reopen if you have additional info for us.
