### ISSUE TITLE
[Forms] Inline Labels and Buttons

### ISSUE THREAD

**Issue by therealbenhogan** [zurb/foundation-sites#7222]
How do you create an inline submit button for a form?

The code on http://foundation.zurb.com/sites/docs/forms.html shows this:

    <div class="input-group">
    <span class="input-group-label">$</span>
    <input class="input-group-field" type="url">
    <a class="input-group-button button">Submit</a>
    </div>

However, I don't want to use a submit button to submit a form, but can't see how to this and still have the button inline as the example above shows.

Can achieve the effect I want by collapsing the containing row but is there a better way in Foundation6?

        <div class="row collapse">
		<div class="small-10 columns">
		<input type="text" name="q" placeholder="Search...">        
		</div>
		<div class="small-2 columns">
		<button type="submit" class="button" style="border:none">GO</button>
		</div>
		</div>

**Comment by gakimball** [comment]
See #7278. The HTML example has been updated, and a fix for `<button>` (and `<input>`) will land in the next patch.
