### ISSUE TITLE
[Equalizer] Plugin Option equalizeOnStack defined but not used in js

### ISSUE THREAD

**Issue by stargOOse** [zurb/foundation-sites#7223]
Plugin Option equalizeOnStack is defined but not used in JS and therefore does not work.
Setting equalizeOnStack to false does not result in not stacking the elements on small screens.

Foundation: 6.04
Plugin: foundation-sites/js/foundation-euqalizer.js

**Comment by danielnr87** [comment]
I second this. Doesn't seem to be working for me either.

**Comment by ithic** [comment]
+1

**Comment by PeterMuusers** [comment]
+2 ;)

**Comment by henrikhaugboelle** [comment]
+1

**Comment by zurbrandon** [comment]
This has been all fixed up and is sitting pretty on the 6.1 branch. We've updated how equalizer will choose when to equalize by adding a data-equalize-on="[breakpoint]" attribute.
