### ISSUE TITLE
[Sticky] data-stickyOn="small" 

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#7225]
is not working. breakpoint remains "medium"

**Comment by designerno1** [comment]
i think its because of the camelCase vars .data() it has to be data-sticky-on="small"

**Comment by phifa** [comment]
data-sticky-on="small" works. How is this bug related to the fact in Orbit for example the data-attributes are not working, even with lowercase and minus?

**Comment by gakimball** [comment]
@zurbchris Can you verify the docs are correct here?

**Comment by zurbchris** [comment]
A link to relevant the [JavaScript Reference](http://foundation.zurb.com/sites/docs/javascript.html#configuring-plugins) page in Foundation 6 docs.
