### ISSUE TITLE
Abide Validation Validates hidden fields

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7226]
i got a form with a hidden fild in first place, and abide tries to validate this hidden field
maybe changing
```js
inputs = $form.find('input'),
inputCount = $form.find('input').length,
```
to
```js
inputs = $form.find('input:not(:hidden)'),
inputCount = $form.find('input:not(:hidden)').length,
```
will be an oppinion?

**Comment by zurbchris** [comment]
Use `data-abide-ignore` on input elements in abide forms you want ignored.
Should be fixed with #7590, please comment and submit pr's to the `abide` branch until 6.1 release.
