### ISSUE TITLE
Abide Validation Pass or Register own patterns

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7228]
is there a way in foundation 6 to pass own patterns via a data-attribute to the input field, or to register own patterns via the plugin api?
in Foundation 5 there was a way by adding p.a. 
```html
pattern="^(.{2,})$"
```
to the input field but that was not quit perfect maybe using a data-pattern would be better solution because of
https://github.com/zurb/foundation-sites/issues/6501
???

**Comment by zurbchris** [comment]
Should be fixed with #7590, please comment and submit pr's to the `abide` branch until 6.1 release.
