### ISSUE TITLE
Abide Submit not fired even if valid

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7230]
the form isn't submit fired even if there is no error
i think it's because the event handler gets preventDefault and nowhere fired in the code
```js
.on('submit.fndtn.abide', function(e) {
        e.preventDefault();
        self.validateForm(self.$element);
      })
```

**Comment by zurbchris** [comment]
Should be fixed with #7590, please comment and submit pr's to the `abide` branch until 6.1 release.
