### ISSUE TITLE
[Accordion] does not work with "any element you want"

### ISSUE THREAD

**Issue by evanlask** [zurb/foundation-sites#7232]
The documentation states you can use the accordion with any element you want but currently that is not the case.
http://foundation.zurb.com/sites/docs/accordion.html

foundation.accordion.js is looking specifically for "li" elements. I have create a pull request with a fix https://github.com/zurb/foundation-sites/pull/7231

**Comment by rafibomb** [comment]
Thanks for the PR @evanlask 

Closing in favor of https://github.com/zurb/foundation-sites/issues/8013
