### ISSUE TITLE
[Dropdown Menus] Vertical sub-menu appearance

### ISSUE THREAD

**Issue by foodgy** [zurb/foundation-sites#7233]
Browser: Chrome 46
URL: http://foundation.zurb.com/sites/docs/dropdown-menu.html#vertical

It's very odd that vertical menu dropdown pane appears from the bottom, rather than the right. Even menu arrows show right direction (not bottom).

Bug?

**Comment by foodgy** [comment]
```alignment``` option changes only triangle position near menu item.

**Comment by foodgy** [comment]
Link: https://jsbin.com/jotupemema
Screenshot: ![untitled](https://cloud.githubusercontent.com/assets/706377/11492228/28822952-97fb-11e5-8deb-c6fd011d41f9.jpg)

**Comment by Gacnt** [comment]
:+1:

**Comment by gakimball** [comment]
This issue was fixed in the last release of Foundation, but it introduced a new issue, #7978. Fun!
