### ISSUE TITLE
[menu] proposal way to break horizontal menu in multiple rows

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7238]
is there a way to break the horizontal orientation after x menu items into a second row, it would be a nice to have.

sometimes menus have many 1st level Items, breaking them into 2 menus don't close the other menu on entering the other menu, so it would be great if it could be splitable after x items for example

**Comment by zurbrandon** [comment]
I'm not 100% sure i understand the request, do you have a visual you can show me?

**Comment by designerno1** [comment]
i can make a visual tomorrow
i mean having a horizontal menu with more than one row, i figured it by changing the li display to block and float it left, because having a menu ul with 20 li and the horizontal table-cell not breaking into rows

**Comment by zurbrandon** [comment]
@designerno1 Do you have any additional thoughts on this?

**Comment by zurbrandon** [comment]
I'll close this for now, but feel free to reopen if you can provide more insight.
