### ISSUE TITLE
[Sticky] data-sticky-container height recalc on resize

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7241]
maybe data-sticky-container height needs a recalc on resize

**Comment by designerno1** [comment]
closed it gets resize ;-)

**Comment by designerno1** [comment]
reopen it sometimes it gets recalced ometimes it seams to update to the initial height

**Comment by foodgy** [comment]
For me sticky block keep be sticking (huh) only after window resize.
And on page load (F5) sticky block don't follow page scroll at all.

**Comment by zurbchris** [comment]
Hmm, that should recalc every 10 ms during resize events, not sure what is causing the problems you're having.

**Comment by designerno1** [comment]
i take a deeper look tomorrow

**Comment by andrewfrankel** [comment]
+1 on what @foodgy sees. Tried Safari, Chrome, Firefox on a Mac. On initial load sticky behaves erratically (or not at all). Once the browser is resized, works exactly as expected. This includes testing again my own site and the documentation page: http://foundation.zurb.com/sites/docs/sticky.html

Even tired adding sticky through the JS function (Foundation.Sticky) on finalize, incase it were a page load timing issue.

Happy to provide additional info or testing if needed.

**Comment by cpence** [comment]
I'm seeing a slightly different behavior. I have a sticky top bar with `stickyOn` set to `medium`, and when the window is resized through the medium breakpoint, the height of the `data-sticky-container` isn't updated, so the content (which in this case is turning from a single row to a stacked top bar) is cut off. Same cluster of bugs, though, I think. Something's off with the resize hook for sticky.

In my case, it works fine if loaded in a `small` window, and dragged out to `medium` size, but *not* if it's loaded in a `medium` window and dragged in to `small` size.

**Comment by zurbchris** [comment]
So, if the viewport is smaller than the minimum `stickyOn` breakpoint, the calc function kicks out before it starts, thus the failure to resize the container appropriately. I'll take a look at remedying that in the new year, plus some other minor optimizations for sticky.

**Comment by andrewfrankel** [comment]
@zurbchris, thanks for looking into this! I've also noticed that the width of the sticky content doesn't fix within the column paddings. See screenshot from foundation docs.

BTW, is there a recommended method to force the sticky to recalculate if for example late loading content changes the size (height) of the sticky element?

![screen shot 2015-12-24 at 9 25 53 am](https://cloud.githubusercontent.com/assets/1470345/11996459/9aa5f752-aa20-11e5-8deb-725369cf4665.png)

**Comment by zurbchris** [comment]
@andrewfrankel sorry for the delay, the answer to your btw question:
```js
$('.sticky').foundation('_calc', true);
```

**Comment by andrewfrankel** [comment]
@zurbchris, thanks, but still no luck... 

I upgraded to Foundation 6.1.2 and tried out your suggestion including using setTimeout to delay the _calc call and executing manually from the console - neither helped. I'm wondering if my issues (mostly) stem from the fact that I have late loading content (ads, etc) within the sticky element. Could that be causing issues given that the height changes? Is there another approach that should be taken given the late loading content?

**Comment by lktl** [comment]
Hi, I have the same problem as @andrewfrankel 

width of the .sticky is always c.a. 15px (padding-right?) wider than the container (column)
![s1](https://cloud.githubusercontent.com/assets/8727347/13106973/770f5cd6-d56b-11e5-8455-0019bcf69485.jpg)

same at F6 Docs
![s2](https://cloud.githubusercontent.com/assets/8727347/13106983/890c03d0-d56b-11e5-99e7-2c0da43e73f7.jpg)


is it bug or is it on purpose ?

**Comment by andycochran** [comment]
@andrewfrankel That width bug is addressed in #9298.

**Comment by andrewfrankel** [comment]
@andycochran thanks for the update!

**Comment by kball** [comment]
#9298 just got merged, which addresses the width... wondering if the rest of this bug can be addressed by plugging in the data-mutate stuff from https://github.com/zurb/foundation-sites/issues/9320 - what do you think @coreysyms

**Comment by coreysyms** [comment]
@kball @andycochran Seems like its a few different things going on here... but lazy loading images will trigger a mutation event.

**Comment by saqueib** [comment]
@andycochran @coreysyms @zurbchris  I am facing a similar issue, When I am hiding some of the elements using $('.grid-item').hide(), the sticky element is not recalculating height, but when I resize window by mouse, it's updating and fixing the overlap issue.

Is there any other way I can call some method to do the recalculation, I tried triggering window resize but it's not working.

```
$('.team-filter-nav a').on('click', function(e){
       // filter boxes
        $('#filterable-grid > .grid-item').show().not(filterdBy.replace('#', '.tp-')).hide(200);

        $('.sticky').foundation('_calc', true); // this dont work

        $(window).trigger('resize'); // niether this 
});
```

**Comment by coreysyms** [comment]
@saqueib your issue has been addressed here. https://github.com/zurb/foundation-sites/pull/9462 although not merged yet, feel free to pull it down.

**Comment by saqueib** [comment]
@coreysyms I tried pulling updated file from [here](https://github.com/coreysyms/foundation-sites/blob/74556f18dfcf300d7a2c366e2bddd9dcaee9fb8b/js/foundation.sticky.js) and build it, now I am getting this error.

```
foundation.js:8225 Uncaught TypeError: Cannot read property 'on' of undefined
    at Sticky._events (foundation.js:8225)
    at foundation.js:8133
    at fn (vendor.js:4496)
    at dispatch (vendor.js:4737)
    at elemData.handle (vendor.js:4549)

foundation.js:8225 Uncaught TypeError: Cannot read property 'on' of undefined
    at Sticky._events (foundation.js:8225)
    at foundation.js:8133
    at fn (vendor.js:4496)
    at dispatch (vendor.js:4737)
    at elemData.handle (vendor.js:4549)
```

**Comment by coreysyms** [comment]
@saqueib sorry, I assumed you were on 6.3.0.
Foundation 6.3.0 is a dependency of the #9462

**Comment by JeremyEnglert** [comment]
This no longer appears to be an issue. Closing.
