### ISSUE TITLE
media-object-section incorrect markup?

### ISSUE THREAD

**Issue by amnuts** [zurb/foundation-sites#7245]
The _media-object.scss file contains the line:

`&:last-child:not(+ &:first-child) {`

When compiled it translates to the rule:

`.media-object-section:last-child:not( + &:first-child) {`

Now, this doesn't seem at all valid CSS to me, but maybe I'm misinterpreting/not getting something?  Don't think it's just my compilation, though, as it's the same on the Zurb site.

**Comment by filipekiss** [comment]
Yeah, I just came across this as well. It's a problem on the rule itself because `&` selectors are only interpolated at the beginning of the compound. So that second `&` will never be replace. I'm making a pull request to fix this.

**Comment by filipekiss** [comment]
Made the pull-request that solves this issue. I haven't found any other place where the `&` was used anywhere but the beginning so I guess this should be enough. :)

**Comment by rafibomb** [comment]
Thanks!

**Comment by D1M** [comment]
Can't compile scss on my Mac. scss -v :: Sass 3.4.19.
Error -  error foundation-6/components/_media-object.scss (Line 38: Invalid CSS after "...st-child:not(+ ": expected ")", was "$selector:first...")

**Comment by filipekiss** [comment]
@D1M There's a new PR that solves this. There seems to be an inconsistence on Sass end that some places it will work with `$selector` and some need the variable to be interpolated. PR #7346 aims to fix this. :)

**Comment by D1M** [comment]
Thanks!

**Comment by amnuts** [comment]
Thanks for woking on this!

**Comment by mrosata** [comment]
The invalid css is still being served from the CDNs, for instances at `2193:43` on http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.css. I ran across this while looking through the layouts at zurb.com - http://foundation.zurb.com/templates.html
