### ISSUE TITLE
Where's the changelog for foundation sites 6 ?

### ISSUE THREAD

**Issue by muhammadcahya** [zurb/foundation-sites#7246]
In foundation 5 I see the changelog every version, but where for foundation (6) for sites ?

**Comment by Renkas** [comment]
You can see it in the Releases tab on Github: https://github.com/zurb/foundation-sites/releases

But I would prefer a changelog inside the package.

**Comment by muhammadcahya** [comment]
Yes I know in github, but
I mean in documentatio, like foundation 5 :
![untitled-1](https://cloud.githubusercontent.com/assets/4241620/11432743/199e4568-94e7-11e5-84c9-782d291356f1.png)

**Comment by aibrean** [comment]
I'd expect to see that when they get to a version that's not as bug-laden.

**Comment by mafrosis** [comment]
A changelog would have been very useful. Like, `panel` has been renamed to `callout` etc. I expect we'll get that between minor versions - but not major ones

**Comment by rafibomb** [comment]
@Renkas What's the advantage to have the changelog in the docs instead of on GitHub?

@mafrosis I think you're referring to a migration guide for moving an existing codebase from 5 to 6? That is coming soon!

**Comment by Renkas** [comment]
For me documentation is first place I look at for changelog. It took me a while to find it by change in the releases tab here.

**Comment by muhammadcahya** [comment]
@Renkas :+1:

**Comment by malymato** [comment]
+1

**Comment by Skai** [comment]
+100500 For anything, what can help with upgrading from 5 to 6. Because It didn't go smoothly. We have some components like 'Clearing', 'Dropdown Buttons', JS utilities(Foundation.utils.S, Debounce, etc) which have been removed in the new version.
Other than that we're using 'reveal' and 'abide' together with JS  for them. In the new version  'reveal' and 'abide' initialization and all related calls were changed as well.

So.., nothing is working after update :)

**Comment by focusedonfit** [comment]
Coming along for the ride. Looking for a 5-6 migration guide.
Thank you

**Comment by KevinAdu** [comment]
I'm waiting for this guide as well.
A lot of stuff ends up broken when I tried to upgrade to 6.

Thanks for your time

**Comment by CYRIAQU3** [comment]
Still Waiting.

+1

**Comment by tyteen4a03** [comment]
+1

**Comment by tomByrer** [comment]
The [F6.2](https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2) upgrade guide is a great example of what I'd hope for in a F5x to F6.x entry.

**Comment by tomByrer** [comment]
May have some useful info: http://stackoverflow.com/questions/36558589/work-needed-to-upgrade-zurb-foundation-v5-to-v6-2

**Comment by kengreer** [comment]
6 months and still waiting for a 5 -> 6 upgrade guide. What's up? Has anything at all been done to date? If so, why not release a partial document? I've been waiting to upgrade my sites for 6 months.

**Comment by david-nguyen** [comment]
+1 would be nice to get some official documentation on this

**Comment by chiss22** [comment]
+1 for this!

**Comment by prshreshtha** [comment]
>rafibomb commented on Nov 30, 2015

> I think you're referring to a migration guide for moving an existing codebase from 5 to 6? That is coming soon!

ಠ_ಠ

**Comment by Cyriaqu3** [comment]
"soon"
( ͡° ͜ʖ ͡°)

**Comment by aleksystem** [comment]
looking forward to it

**Comment by kengreer** [comment]
8 months and still waiting for a 5 -> 6 upgrade guide.

**Comment by tomByrer** [comment]
My SO link above is the only one I know of; feel free to add your tips there, or collate into some docs here.

**Comment by chiss22** [comment]
@tomByrer thanks!

**Comment by nathanh0** [comment]
Can we at least get a partial change log? Or can someone email me the unfinished upgrade docs? I am having trouble even finding basic information on some items from the Foundation 6 docs.

**Comment by kengreer** [comment]
10 months and still waiting for a 5 -> 6 upgrade guide.

**Comment by brendo** [comment]
I've started on this journey and will keep a 'dot' point reference of things I've had to change to achieve it. The client's site was using F5 w/ Sass.

- I have noticed that there was a mention to upgrading in the Foundation 6 docs for [Media Queries](http://foundation.zurb.com/sites/docs/media-queries.html#upgrading-from-foundation-5), but this is the only instance I've seen at the moment.
- The introduction of `autoprefixer` has meant that a number of utility SASS mixin's are no longer required as well. Just write standard CSS and let the build process handle this for you.
- If you are using custom colours such as `$white-smoke`, most of these have been removed in favour of [`foundation-palette`](http://foundation.zurb.com/sites/docs/global.html#colors)
- The [side nav](http://foundation.zurb.com/sites/docs/v/5.5.3/components/sidenav.html) component is gone, I think [vertical menu](http://foundation.zurb.com/sites/docs/menu.html#vertical-menu) is the closest thing in F6.
- There's a number of SASS variables which are now 'maps' instead, so `map-get` and `map-has-key` are needed to access the maps (if you wish to use them).
- `$column-gutter` is gone, `$grid-column-gutter` now exists (a map).

I'll try to keep updating this as I go. From the initial play, I'd say it's a significant upgrade and I'll probably revisit a lot of my styling (and some markup) to make the transition.

**Comment by minexew** [comment]
It's not coming, is it?
lol

**Comment by tomByrer** [comment]
I think F7 beta is coming soonish.   Likely before the changelog for v6 ;)

**Comment by sebastian-marinescu** [comment]
I would also be interested in a migration-guide!

Right now I stumbled upon the reveal-component: In FS5 it was opened like
`$modal.foundation('reveal', 'open');`

Now in FS6 it's a little different: 
`$modal.foundation('open')`

Maybe this helps someone.

**Comment by JeremyEnglert** [comment]
Sorry everyone. An upgrade guide to go from 5 to 6 most likely isn't going to happen. 

But to be honest, there really isn't ever a need to update a project.

**Comment by IamManchanda** [comment]
Sorry everyone but as much it hurts but we don't think 5 to 6 migration guide isn't possible now
That said, we will try to do our best for f7 and surely have a migration guide in the docs for the same!
