### ISSUE TITLE
[Slider] Two Handles Slider with Visible Inputs

### ISSUE THREAD

**Issue by foodgy** [zurb/foundation-sites#7247]
This works fine with input outside slider container (<a href="http://foundation.zurb.com/sites/docs/slider.html#two-handles">link</a>):
```
<div class='small-10 columns'>
<div class="slider" data-slider data-initial-start='50' >
  <span class="slider-handle"  data-slider-handle role="slider" tabindex="1" aria-controls='sliderOutput1'></span>
  <span class="slider-fill" data-slider-fill></span>
</div>
</div>
<div class='small-2 columns'>
  <input type="number" id='sliderOutput1'>
</div>
```

But this doesn't work:
```
<div class='small-10 columns'>
<div class="slider" data-slider data-initial-start='25' data-initial-end='75'>
  <span class="slider-handle"  data-slider-handle role="slider" tabindex="1" aria-controls='sliderOutput1'></span>
  <span class="slider-fill" data-slider-fill></span>
  <span class="slider-handle"  data-slider-handle role="slider" tabindex="1" aria-controls='sliderOutput2'></span>
</div>
</div>
<div class='small-2 columns'>
  <input type="number" id='sliderOutput1'>
  <input type="number" id='sliderOutput2'>
</div>
```
Update: numbers are changing only in first input, ignoring the other one.

**Comment by megakoresh** [comment]
Can confirm. Furthermore: it will work if you move all the inputs inside the slider container (the div with "slider" class), but that messes up the styling.

**Comment by megakoresh** [comment]
Any progress on this? I tried to find what was causing the issue, but can't, the code is a bit weird and there aren't any obvious problems.

**Comment by zurbchris** [comment]
the code for this definitely got murky, and it needs a further work to totally lock it down. Believe it or not, there's a quite a lot that needs to be accounted for, based on the requested features for this plugin, and it's been my Moby Dick of sorts... Apologize for the delay, at this time, I'm going to throw on the help wanted tag and see if anyone else can tackle this an another issue or two related to slider. I'm just one guy, and there's a lot cookin' over here at ZURB.

**Comment by dragthor** [comment]
This one sounds familiar.

**Comment by Owlbertz** [comment]
Seems to be fixed already, see http://codepen.io/Owlbertz/pen/RRQyZX.

**Comment by megakoresh** [comment]
That link has nothing to do with the issue this thread is about.

**Comment by Owlbertz** [comment]
I am sorry, seems like my CodePen forking has been messed up. Please see: http://codepen.io/Owlbertz/pen/KroPQo.

**Comment by megakoresh** [comment]
Yeps that's a correct link, seems like the issue was indeed resolved. Well done!

**Comment by andycochran** [comment]
😀 Can we close this one?

**Comment by megakoresh** [comment]
We can and we should, there's enough of these around to last a lifetime without fixed ones staying up.
@foodgy 
@zurbchris 
Please close this one.

**Comment by Owlbertz** [comment]
Aaaaaand it's closed.
