### ISSUE TITLE
Orbit module doesn't work after build

### ISSUE THREAD

**Issue by helgeohl** [zurb/foundation-sites#7257]
When I'm building a site for deployment,
the orbit module doesn't work anymore.

Steps to reproduce:
1. foundation new 
2. choose website
3. choose ZURB Template
4. insert code from http://foundation.zurb.com/sites/docs/orbit.html in index.html
5. foundation build
6. open dist/index.html

**Comment by zurbchris** [comment]
Orbit docs have been cleaned up a bunch and I'm hoping you've resolved this issue by now. Please reopen if not the case.

**Comment by Jura** [comment]
Same problem here - Orbit works fine with the code from docs in "watch" mode but all controls (arrows and bullets) become disabled after running "foundation build".
