### ISSUE TITLE
[Callout] data-closable not working

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7260]
**How can we reproduce this bug?**
in docs
http://foundation.zurb.com/sites/docs/callout.html#making-closable
data-closable not working

**What did you expect to happen?**
Callout to be closing on click the close button

**What happened instead?**
nothing

**Comment by darles** [comment]
+1

**Comment by esbenbjerre** [comment]
+1

**Comment by Knight-Yoshi** [comment]
I ran into this as well. :-1:

**Comment by opetrone** [comment]
+1

**Comment by rafibomb** [comment]
Thanks for the PR - Merged! https://github.com/zurb/foundation-sites/pull/7453
