### ISSUE TITLE
Off canvas wrapper min-height issue 

### ISSUE THREAD

**Issue by jimthegit** [zurb/foundation-sites#7261]
Currently when using off canvas if the last child element (say for example a div) has a bottom margin applied it does not push the off canvas wrapper to the bottom of the page. See screen grab for what I mean.

I've worked around the issue by setting min-height:0 and height:100% to .off-canvas-content

<img width="1440" alt="off-canvas-min-height" src="https://cloud.githubusercontent.com/assets/9253831/11440452/6470fa78-94fa-11e5-85af-5377b7d070d8.png">

**Comment by zurbrandon** [comment]
This should be fixed as of 5.0.4, but let me know if you're still experiencing it.
