### ISSUE TITLE
[Forms inline-labels-and-buttons] input-group formating issue with <button>

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7263]
**How can we reproduce this bug?**
```html
<div class="input-group">
  <span class="input-group-label">$</span>
  <input class="input-group-field" type="url">
  <button class="button input-group-button" type="submit" value="Submit">Submit</button>
</div>
```
http://foundation.zurb.com/sites/docs/forms.html#inline-labels-and-buttons

**What did you expect to happen?**
looks not the same with
```html
<div class="input-group">
  <span class="input-group-label">$</span>
  <input class="input-group-field" type="url">
  <a class="input-group-button button">Submit</a>
</div>
```

**Comment by imaia** [comment]
I also had this issue. It is also broken with input field of type button or submit.

**Comment by gakimball** [comment]
See #7278. The HTML example has been updated, and a fix for `<button>` (and `<input>`) will land in the next patch.
