### ISSUE TITLE
Flex box grid does not support offsets

### ISSUE THREAD

**Issue by alexmorris** [zurb/foundation-sites#7266]
As per the float based grid - we need the ability to offset columns to position content on the grid

**Comment by rafibomb** [comment]
Sounds like it would be useful. We'll tag it as a feature for a upcoming release.

**Comment by ivanjaros** [comment]
Flexbox uses SIZE-order-N classes. Is that what you're after?

**Comment by alexmorris** [comment]
@ivanjaros no - offsetting the columns as per this example 

@rafibomb all you need to add is this to get it back. I found the mixin architecture a bit baffling or I would have added myself and made a PR :)

`/* offsets */

.large-offset-1, .medium-offset-1, .small-offset-1 {
  margin-left: 8.333%; }

.large-offset-2, .medium-offset-2, .small-offset-2 {
  margin-left: 16.667%; }

.large-offset-3, .medium-offset-3, .small-offset-3 {
  margin-left: 25%; }

.large-offset-4, .medium-offset-4, .small-offset-4 {
  margin-left: 33.333%; }

.large-offset-5, .medium-offset-5, .small-offset-5 {
  margin-left: 41.667%; }

.large-offset-6, .medium-offset-6, .small-offset-6 {
  margin-left: 50%; }

.large-offset-7, .medium-offset-7, .small-offset-7 {
  margin-left: 50%; }

.large-offset-8, .medium-offset-8, .small-offset-8 {
  margin-left: 66.667%; }

.large-offset-9, .medium-offset-9, .small-offset-9 {
  margin-left: 75%; }

.large-offset-10, .medium-offset-10, .small-offset-10 {
  margin-left: 83.333%; }

.large-offset-11, .medium-offset-11, .small-offset-11 {
  margin-left: 91.667%; }`

**Comment by zurbrandon** [comment]
While we may need to add them we saw the spacing options as a pretty good replacement since thats how we tended to use offsets. We're discussing adding it back for simple feature parody.

**Comment by Deracination** [comment]
Please add it back. It doesn't appear possible to achieve some layouts using spacing instead of offsets.

For example, the following layout on a medium screen places all the inputs on a single line and on a small screen positions inputs 'two' and 'three' nicely aligned under input 'one':

```html
           <div class="row valign-center">
                    <div class="columns small-6 medium-4 text-right">
                       label text
                    </div>
                    <div class="small-6 medium-4">
                        <input name="one/>
                    </div>
                    <div class="columns small-offset-6 small-6 medium-4">
                        <input name="two"/>
                        <input name="three"/>

                    </div>
                </div>
```

**Comment by gakimball** [comment]
Done! I think eventually I'll find a way to reuse that code between the two grids, so it's not just being copied and pasted.

**Comment by michaelBenin** [comment]
If you want to use it as a mixin: `@include grid-column-offset($o);`
