### ISSUE TITLE
[Docs] Off-canvas close icon shows then disappears

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#7273]
Scale browser down to small - then open offcanvas and look in top right of menu.

https://twitter.com/KimD1Petersen/status/670153358645321728

**Comment by zurbchris** [comment]
No need to scale the browser down. It's focusing that element when the off-canvas opens, and the `:hover` state color is the same as the off-canvas background. Probably ought to change the color selection there.

**Comment by zurbrandon** [comment]
All fixed on on develop
