### ISSUE TITLE
Placeholder almost indistinguishable from regular text again

### ISSUE THREAD

**Issue by ion1** [zurb/foundation-sites#7275]
#6968 seems to be back in Foundation 6. The input color is `#8a8a8a` which is really close to the light gray placeholder text color. This can be seen by typing into [the text fields in the documentation](https://foundation.zurb.com/sites/docs/forms.html#text-inputs).

* [`$input-color: $dark-gray !default;`](https://github.com/zurb/foundation-sites/blob/v6.0.4/scss/forms/_text.scss#L11)
* [`$dark-gray: #8a8a8a !default;`](https://github.com/zurb/foundation-sites/blob/v6.0.4/scss/_global.scss#L51)

Is there a reason for input-color not to be `$black`?

**Comment by gakimball** [comment]
Good call, those should definitely be black. I updated the default value.
