### ISSUE TITLE
Inline Labels and Buttons

### ISSUE THREAD

**Issue by Knight-Yoshi** [zurb/foundation-sites#7278]
If you use a button instead of an anchor for the inline form fields the button is not inline.

**Comment by TvrtkoM** [comment]
setting *"display: table-cell"* property to button element doesn't work as expected. You can wrap a button in a div to render a button as anchor element

    <div class="input-group-button button"><button>Submit</button></div>

**Comment by gakimball** [comment]
Because both `<input>` and `<button>` act up with `display: table-cell`, I updated the markup recommendation to use a separate wrapper and button:

```html
<div class="input-group">
  <span class="input-group-label">$</span>
  <input class="input-group-field" type="number">
  <div class="input-group-button">
    <input type="submit" class="button" value="Submit">
  </div>
</div>
```
