### ISSUE TITLE
Reveal modals are not opening correctly in Safari 9 on OSX 10.11 using Foundation 6.0.4

### ISSUE THREAD

**Issue by rickcurran** [zurb/foundation-sites#7279]
Reveal modals are not opening correctly in Safari 9 on OSX 10.11 using Foundation 6.0.4, the background overlay appears but the actual popup modal itself doesn't appear. Resizing the browser window usually makes them appear.

This is happening in my own usage but you can see the same behaviour on the Reveal Docs page:

http://foundation.zurb.com/sites/docs/reveal.html

**Comment by zurbrandon** [comment]
This looks to be all fixed up in 6.0.6. I'll close this out
