### ISSUE TITLE
Reveal modals are not opening correctly in Safari on iOS 9 using Foundation 6.0.4

### ISSUE THREAD

**Issue by rickcurran** [zurb/foundation-sites#7280]
Reveal modals are not opening correctly in Safari on iOS 9 using Foundation 6.0.4, the background overlay appears but the actual popup modal itself doesn't appear. Changing orientation of the device sometimes makes them appear. Please see issue #7279 which is for the same issue on OSX: https://github.com/zurb/foundation-sites/issues/7279

This is happening in my own usage but you can see the same behaviour on the Reveal Docs page:

http://foundation.zurb.com/sites/docs/reveal.html

**Comment by aibrean** [comment]
![reveal-zindex](https://cloud.githubusercontent.com/assets/6740252/11573831/567daf5c-99d6-11e5-9c5a-6e57e0c52497.png)

**Comment by rickcurran** [comment]
I was getting this issue without off-canvas in my page. One other thing to note is that on iOS all browsers use the same browser framework underneath (part of the deal with being on iOS) so this issue should happen in all iOS browsers.

**Comment by aibrean** [comment]
There is a PR right now to resolve this although it looks like offcanvas specific.

**Comment by zurbrandon** [comment]
This looks to be all fixed up now in 6.0.6.
