### ISSUE TITLE
Reveal modal pop z-index incorrect on Safari on iOS 8 using Foundation 6.0.4

### ISSUE THREAD

**Issue by rickcurran** [zurb/foundation-sites#7281]
Reveal popups are appearing incorrectly in Safari on iOS8, there appears to be a z-index issue and the modal is appearing behind the overlay. This is Foundation 6.0.4

**Comment by aibrean** [comment]
I noticed that while using reveals in tabs.

**Comment by zurbrandon** [comment]
All fixed up in 6.0.6

Thanks for all the Issues on this and being so thorough, man!
