### ISSUE TITLE
[Orbit] Issue in css.

### ISSUE THREAD

**Issue by StiveAZ** [zurb/foundation-sites#7286]
Hi guys...

I download the complete option of F6: http://foundation.zurb.com/sites/download.html/

Next, I copy the orbit markup in my HTML, and Orbit fail after y click one bullet

To solve it i do a test:

I replace the code in foundation.css for your .css code in the foundation site: http://foundation.zurb.com/sites/docs/assets/css/docs.css?hash=5462fb05cc3d8f84c4953152a682e5e1

And Orbit run perfectly

Note: the error obviously is in the css.

Thanks.

**Comment by xfifix** [comment]
nice ! are you compare the two css code for the purpose of find the probleme of .scss file ?

**Comment by Knight-Yoshi** [comment]
@StiveAZ I don't think the issue is in the CSS at all, because the active class never changes in the DOM when you click the arrow/dots.

**Comment by zurbchris** [comment]
Do you have the motion ui css loaded in the head of your document?

**Comment by Knight-Yoshi** [comment]
After importing and then including the Motion UI library/classes it works fine. Seems that is the issue. 
The Orbit docs say (in the Motion UI tooltip at the top) it supports Motion UI, not that it requires it.

**Comment by Knight-Yoshi** [comment]
After importing and then including the Motion UI library/classes it works fine. Seems that is the issue. 
The Orbit docs say (in the Motion UI tooltip at the top) it supports Motion UI, not that it requires it.

**Comment by zurbchris** [comment]
Curious question indeed @Knight-Yoshi ! I'll defer to @gakimball or @zurbrandon for that answer. And motion-ui is not *required* for Orbit, only highly encouraged. As of 6.0.4, setting the option `data-use-m-u-i="false"` would cause a transition/animation-free fallback to take over.
