### ISSUE TITLE
[F 6.0.1] Submenu links not working.

### ISSUE THREAD

**Issue by Gacnt** [zurb/foundation-sites#7289]
I have switched over to Foundation 6 and I'm trying to make a submenu in the top-bar like so:
```
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text"><i class="fa fa-users"></i> FULL5IVE</li>
            <li><a href="#">Home</a></li>
            <li><a href="#">Queue</a></li>
        </ul>
    </div>
    {{ if not authenticated }}
    <div class="top-bar-right">
        <ul class="menu">
            <li class="steam-button">
                <a href="/auth/steam"></a>
            </li>
        </ul>
    </div>
    {{ else }}
    <div class="top-bar-right">
        <ul class="dropdown menu" data-dropdown-menu>
            <li>
                <a>{{username}}</a>
                <ul class="menu">
                    <li>
                        <a href="/auth/logout">Logout</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    {{ end }}
</div>
```
Which works good, but when I go to click the link in the dropdown nothing happens it just acts like its disabled or something. But I know the link works if I manually put it into my address bar. Any information would be nice.

I downloaded F6 from the website by clicking Download Everything and I've included, in order: `Jquery > what-input > Foundation.min.js`

**Comment by rickcurran** [comment]
The latest Foundation build from this Github repository is 6.0.4, I'd recommend downloading that and seeing if that makes any difference, there's definitely a load of glitches that have been fixed since the launch version.

**Comment by zurbchris** [comment]
:+1: @rickcurran
