### ISSUE TITLE
Cant download Flexgrid optional component

### ISSUE THREAD

**Issue by simonrcodrington** [zurb/foundation-sites#7290]
Hi.

On your download page you list your new 'Flex Gird' component for inclusion. (http://foundation.zurb.com/sites/download.html/) 

If I remove all other items and just select this new grid and proceed to generate the custom build, it just doesn't seem to work. 

Inside the non minified version of the CSS there is nothing for the flexible grid, just a series of basic resets. I've checked the Flex Grid docs on your website and it's inclusion talks about importing it to replace the current grid (http://foundation.zurb.com/sites/docs/flex-grid.html). I thought choosing this option would automatically do this for me. 

I've tried also to include along with the Flex Grid, the Standard Grid in hopes that when the custom build is created it uses this new grid. This doesn't seem to work as only the standard grid is included. 

I can't see any way for me to use this new grid. I can't use the Sass version, I need just the standard complied CSS for use in a demo. 

Am I doing this incorrectly?

Simon

**Comment by IamManchanda** [comment]
You Should select other components too

**Comment by simonrcodrington** [comment]
I shouldn't have to select other components in order to make the optional flexbox grid work. That doesn't make any sense at all.

**Comment by ivanjaros** [comment]
Don't bother. Flex is mostly not working at this time anyway :(

**Comment by gakimball** [comment]
Closing in favor of #7033, where we're tracking a bunch of these issues.

**Comment by Lynda333** [comment]
As a work around until they fix the issue, select Flex Grid and Badge. This will download the required resets (normalize.css), the flex grid and badge CSS. Then you can remove the last few lines of CSS to remove the unneeded badge CSS and you have the flex grid CSS ready to use.
