### ISSUE TITLE
[docs] Different Markup Menu - Responsive Navigation

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7291]
in docs Dropdown menu the markup of the submenu is
```html
<ul class="menu">
```
in Responsive menu the markup is
```html
<ul class="vertical submenu menu" data-submenu id="m2">
```
which one is correct or whats the difference

**Comment by gakimball** [comment]
The simpler one is correct. The menu plugins add the necessary structural classes for you. Sorry for the inaccuracy!

Fixed in master and deployed to the live docs: 5606925cdee4b425b7231523f3046255a2f53823
