### ISSUE TITLE
[Off-canvas] Shadow appear if last el is a <p> tag

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7292]
```html
<div class="off-canvas-wrapper">
    <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
      <div class="off-canvas position-left" id="offCanvas" data-off-canvas>left</div>
      <div class="off-canvas position-right" id="offCanvasRight" data-off-canvas data-position="right">right</div>
      <div class="off-canvas-content" data-off-canvas-content>
<p>some text</p>
      </div>
    </div>
  </div>
```
i see the shadow of the off canvas below the "some text" p tag

**Comment by rafibomb** [comment]
I've seen this with a missing div tag. How can we replicate this? Is it on the docs?

**Comment by designerno1** [comment]
hi just use the html i wrote in the issue or add a
```html
<p>text</p>
```
to the docs as the last element of the off-canvas-content div

**Comment by gakimball** [comment]
I'm not sure if the `<p>` tag is the issue, it might just be that the main content area is very short. `.off-canvas-content` has a box shadow, so if that box is really small, you're going to see the box shadow.

**Comment by designerno1** [comment]
Hm
But if i Chang the p-tag to a div-Tag the content is also very short and the border don't appear

**Comment by zurbrandon** [comment]
I'm wondering if this is due to the bottom margin of these items? Some sort of margin collapse issue possibly?

**Comment by designerno1** [comment]
yes it's the margin-bottom of the p tag but why this happens i don't know

**Comment by gakimball** [comment]
Adding any padding to the bottom of the `.off-canvas-content` container prevents the margins from collapsing, which is what reveals the box shadow.

So I added the *teeniest tiniest* bottom padding of `0.1px`, and the box shadow disappeared.
