### ISSUE TITLE
Hardcoded Colour in Title bar for Responsive Navigation

### ISSUE THREAD

**Issue by asecondwill** [zurb/foundation-sites#7294]
The Hamburger colour is hardcoded as white within the titlebar mixin.  Also the TitleBar mixin uses $white and $black for other colour settings, making it hard to set properly without changing those colours which are used elsewhere.   

There should be settings just for those items?

This is all from line 9 in _title-bar.scss

**Comment by designerno1** [comment]
+1

**Comment by gakimball** [comment]
I added a slew of Sass variables for the title bar, as well as the menu icon inside of it.
