### ISSUE TITLE
Refactor breakpoint file

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#7297]
In the breakpoint file there is this piece of code at the end of the file:
<code>
// These styles are applied to <meta> tags, which are read by the Foundation JavaScript
.foundation-mq {
  font-family: '#{-zf-bp-serialize($breakpoints)}';
}
</code>

The breakpoint file is being loaded by the util file. The util is being included in many places.
I have a custom configuration and I have to be veeery careful about how I load certain files, otherwise I will end up with a ton of aforementioned css rules in my final css file.
I cannot call util anywhere for this reason. Instead I have to call particular util files, except the breakpoint of course, to avoid this issue.

Could you possibly move this code in some mixin so it is not printed right away? It would make my life much easier :)

**Comment by gakimball** [comment]
The framework is meant to be imported all at once, just with `@import 'foundation'`. Just importing the framework doesn't print any CSS, as that's what the mixins do, like `@include foundation-grid`. Is there a reason you can't import the whole framework at once, versus using individual pieces?

**Comment by ivanjaros** [comment]
I have a config file that imports the util files. As I have mentioned, not everything because it caused the aforementioned error.

This config file is being called throughout my sass files. In my main file I have this config, then foundation, then my files/customizations.

And so since I am calling the config in every file everything that is not a mixim will get printed. Which is this case. So I had to call just the unit and color files specifically to skip loading the breakpoint one that is called from util/util.

**Comment by gakimball** [comment]
You don't technically need to do that since Sass scope is automatically global, no matter where you import something. It's not like Node (or any other language), where when you `require()` a library in a file, only that file can see it.

*However*, the selector should be moved because it is breaking our rule that `@import`s don't print CSS. I'm going to move it to global styles, because that code is considered mandatory for the framework to function.
