### ISSUE TITLE
[The Grid] Block grid limits to max 6 columns

### ISSUE THREAD

**Issue by bwydev** [zurb/foundation-sites#7298]
Block grid columns greater than 6 break, and drop the column count to the next media breakpoint smaller. 

Example:
`<div class="row small-up-2 medium-up-6 large-up-8">`
will show 6 columns on large view. 
`<div class="row small-up-2 medium-up-7">`
will show 2 columns on medium or above view.

You can inspect and edit and try this on the grid docs page http://foundation.zurb.com/sites/docs/grid.html .

**Comment by designerno1** [comment]
Block grid columns can be set in _settings.scss
```scss
$block-grid-max: 6;
```

**Comment by bwydev** [comment]
Thanks, missed that. A note about the variable in the docs description of Block Grids would be helpful.

**Comment by klihelp** [comment]
For custom download Foundation website should have a setting for block-grid-max next the nr of columns. For some websites I have used block grid 7 before updating it to Foundation 6 ..

**Comment by gakimball** [comment]
We bumped the default up to 8 to give developers more flexibility, but we're not going to go all the way up to 12 for the CSS version.
