### ISSUE TITLE
[Dropdown Menus] links in dropdown not working

### ISSUE THREAD

**Issue by mochnacki78** [zurb/foundation-sites#7299]
**How can we reproduce this bug?**

paste docs code

**What did you expect to happen?**

after click change page

**What happened instead?**

nothing

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

http://www.studio-jeden.com.pl/m4/

**Comment by mochnacki78** [comment]
6.0.4 fix the problem

**Comment by mochnacki78** [comment]
Well, just download newest dropdownmenu.js and it works, but only a first click, after that nothing happens, can't use dropdown menu. Refresh doesn't work.

**Comment by zurbchris** [comment]
This is very odd, I don't know what the problem could be, as dropdown menu is used on our docs page, and is working as intended. From what I can tell on your demo page, it seems to be working there as well. Can you explain, in greater detail, what is not working? I seem to be clicking through links just fine.

**Comment by mochnacki78** [comment]
Works fine now, had to add new java files after main foundation.js,

**Comment by zurbchris** [comment]
Thanks for following up, I'm going to close this issue now :smile:
