### ISSUE TITLE
[JS][Dropdown Menu] Submenu anchor won't close dropdown on touch devices

### ISSUE THREAD

**Issue by cabdesigns** [zurb/foundation-sites#7301]
In 6.0.4 the submenu anchor won't close the dropdown - it instead follows the link set (which in my case is just #).

Tested on iPhone 5S in Chrome. Also able to reproduce in device mode of Chrome developer tools. Anchor works fine in regular desktop browser mode.

```
<ul class="dropdown menu" data-dropdown-menu data-disable-hover="true">
    <li class="has-submenu">
        <a href="#">
            Menu
        </a>
        <ul class="submenu menu vertical" data-submenu>
            <li><a href="#">One</a></li>
            <li><a href="#">Two</a></li>
        </ul>
    </li>
</ul>
```

**Comment by zurbchris** [comment]
This is an area of debate, some want it to close, some want it to follow the link. I guess the only thing to do is to make it an option.
Thoughts?

**Comment by aibrean** [comment]
I prefer hover and then followed on click or double-click.

**Comment by Knight-Yoshi** [comment]
@zurbchris I'd say add the option to data-options. Something like data-options="followLink:true/false"

**Comment by zurbchris** [comment]
After a quick discussion with the rest of the Foundation team, the decision has been made: Dropdown Menu links will open the submenu on initial click if on mobile or click open === true, on second click, will follow the link. There will be an additional option added, soon(ish), to add an event listener to the body, to close the menu if clicked(tapped) outside.

**Comment by roba91** [comment]
I'd still like to see an option to close the dropdown on second touch…
