### ISSUE TITLE
Update bower package zurb/bower-foundation for Foundation 6

### ISSUE THREAD

**Issue by mortenson** [zurb/foundation-sites#7302]
I noticed that https://github.com/zurb/bower-foundation has not been updated to reflect the Foundation 6 release. Are there any plans to start packaging Foundation 6 tags in the same way Foundation 5 tags were done?

**Comment by Renkas** [comment]
I believe it was written somewhere that this package will stay at ver 5. And I think that it should be this way.

ver 6 is available in bower as: foundation-sites

**Comment by zurbchris** [comment]
@Renkas  :+1: 
Indeed, the bower-foundation repo will remain v5.
