### ISSUE TITLE
Abide required textarea always invalid

### ISSUE THREAD

**Issue by ariordan** [zurb/foundation-sites#7304]
If a textarea is created empty, then abide will always report the textarea as invalid, even when it has a value. However, if there area is created with a value, validation will subsequently operate as expected, even when empty.

This appears be caused by the call "$el.is(':empty')" at line 154 of foundation.abide.js, returning true.

foundation - 6.0.4
jquery - 2.1.4

**Comment by zurbchris** [comment]
Should be fixed with #7590, please comment and submit pr's to the `abide` branch until 6.1 release.
