### ISSUE TITLE
[Orbit] on mobile blocks scrolling

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#7305]
**How can we reproduce this bug?**
1. Open http://foundation.zurb.com/sites/docs/orbit.html on a touch device
2. Try to scroll/drag down on the orbit slider. Scrolling is blocked. 
3. This is problematic on mobile, where the slider takes 100% width! 

**What did you expect to happen?**
That it scrolls down. 

**What happened instead?**
Nothing. 

**Test case**
http://foundation.zurb.com/sites/docs/orbit.html

**Comment by Owlbertz** [comment]
This comes from `foundation.util.touch.js` line 29: 
```js
if ($.spotSwipe.preventDefault) { e.preventDefault(); }
``` 
I am not sure why this is needed, but when commented out, the swiping on Orbit works as expected.

**Comment by phifa** [comment]
nice @Owlbertz. Hoping nothing else breaks with this fix :wink:

**Comment by Owlbertz** [comment]
As far as I saw this doesn't even prevent the default at all, so I think it that this may be removed in the future. However, since I am not fully aware of where this util is used I feel like @zurbchris should have a look when he has some minutes to spend.

**Comment by snielson-dyn** [comment]
Thought I'd chime in that I am experiencing this same problem on iOS 8.1.2 for the iPad.  In my case I am getting just the regular page scrolling being blocked the majority of the time and I do not have the orbitz plugin included.  Following @Owlbertz suggestion of setting preventDefault to false fixed the problem and I am back to smooth scrolling.  I'm on release 6.0.6 at the time of this posting.  

Searching through the foundation.js file it looks like this utility is only being used for the orbitz plugin.

Also the commented out jquery code which appears to have inspired this utility on lines 1221 - 1441 of foundation.js appears to only use preventDefault to handle a small scroll suppression threshold (ie you don't want scrolling to occur if the user inadvertently jars the screen across 10-15 pixesl).  The code for this is on line 1381-1383.  

Unless the utility is going to reproduce the same threshold suppression effect it looks like the preventDefault could be removed all together.

**Comment by gakimball** [comment]
I tested the swiping behavior in iOS 9 (iPhone and iPad), Android 2, 4, and 5, and Windows Phone, and couldn't recreate the issue where swiping vertically is blocked. In every browser I was able to start a drag on the slider itself, and if the drag went up or down, the page scrolled fine. [Here's the page used to test this.](https://github.com/zurb/foundation-sites/blob/develop/test/visual/orbit/touch.html) This is also with or without the fix proposed by @Owlbertz.

The only problem I encountered was that Windows Phone would block swipes to the *left*, which it reserves for going back a page in the browser. This means you can't go back in slides, only forward. That's not related to this issue, however.

@phifa, I know this is a pretty old issue, but if you can tell me what mobile device, browser, and page can recreate the bug, let me know, and we can look at it again. :)

**Comment by AndresCampuzano** [comment]
The bug still remains until today.

**Comment by DanielRuf** [comment]
Hi @andersonaguiar,

Please open a new issue and use the latest version of Foundation Sites (6.6.1).
