### ISSUE TITLE
hello, foundation new ProjectName

### ISSUE THREAD

**Issue by wuchuguang** [zurb/foundation-sites#7306]
report !
            .
           /|     ,
      , /|/  \/| /|       Slow down there, friend!
     /|/       |/ |       ------------------------
 |___|            |___|   Running this installer as an administrator can cause problems.
 \___|  ^^   ^^   |___/   Try running this command again without "sudo" or administrator rights.
     | -[O]--[O]- |
     |    ___,    |
     |    ...     |
      \__________/

I can only use common user login, to create a project?

**Comment by wuchuguang** [comment]
current root user

**Comment by gakimball** [comment]
Yes, you can't use `sudo` or admin rights. The commands the CLI runs must be run as a normal user, to avoid permissions issues with the files.
