### ISSUE TITLE
Flex box does not support SIZE-up-N and collapse classes

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#7310]
There is no integration for these classes in flexbox mixin at all.

**Comment by aibrean** [comment]
Block grids aren't a part of flexbox.

**Comment by ivanjaros** [comment]
Yes, I can see that.

**Comment by ivanjaros** [comment]
Ok, I see now that in order to make Flex grid work one has to use "SIZE-N column/s" classes just like with normal grid.
So I would suggest updating the documentation page to make it more clear since it only says that it can be swapped for the normal grid and it adds more functionality but nothing about doing things differently compared to the normal grid.

The collapse classe issue still stands though and it's annoying.

**Comment by aibrean** [comment]
Well the docs for flex don't mention anything about block grids. It does say to not include the regular grid (comment out the include). I think that's pretty clear.

@cveneziani had this:

```scss
.row {
  // Collapsing
  &.collapse {
    > .column { @include grid-col-collapse; }
  }

  // Responsive collapsing
  @each $size in $breakpoint-classes {
    @include breakpoint($size) {
      &.#{$size}-collapse {
        > .column, .columns { @include grid-col-collapse; }
      }

      &.#{$size}-uncollapse {
        > .column, .columns { @include grid-col-uncollapse; }
      }
    }
  }
}
```

**Comment by ivanjaros** [comment]
Not true. This is from the flex page.
"The flex grid works very similarly to the standard float grid, but includes a number of useful features only possible with flexbox."

"The flex grid is not enabled by default. To use the default CSS, add the export mixin for the flex grid, and remove the default grid."

"The standard grid and flex grid use the same classes, namely .row and .column, and don't play nice together. If you want to use both in the same project, we recommend using the Sass mixins for each grid, instead of the default CSS."

**Comment by aibrean** [comment]
"To use the default CSS, add the export mixin for the flex grid, and remove the default grid."

It says "remove the default grid".

And yes, the standard and flex use the same classes. The block grid is not technically the same.

**Comment by ivanjaros** [comment]
"It says "remove the default grid"." -- yes, and flex one is not coming with collapse class support.

**Comment by zurbrandon** [comment]
The lack of collapse looks like an oversight more than anything, if you feel comfortable a PR would be appreciated, but if not we'll add it to our Sass todos.
