### ISSUE TITLE
[F.6.0.4] slider-fill for Slider does not "fill"

### ISSUE THREAD

**Issue by imaia** [zurb/foundation-sites#7311]
Slider, with two handles, does not fill the whole area between handles (slider-fill) when loaded. 

![slider](https://cloud.githubusercontent.com/assets/14771411/11470834/c038e1ee-973f-11e5-8868-f6202a4f04c5.png)

**Comment by zurbchris** [comment]
I'm not getting this issue anywhere on the docs or locally on my machine. Can you provide a link to a codepen or fiddle?

**Comment by imaia** [comment]
=D
