### ISSUE TITLE
[F.6.0.4] Reveal animation is not working

### ISSUE THREAD

**Issue by imaia** [zurb/foundation-sites#7314]
I'm using foundation from custom download (all options checked) and the reveal example from the site. If I set an animation with my modal, like:

```
<a class="button" data-toggle="my-id" aria-controls="confirm-delete" aria-haspopup="true">
        {% trans "Do Stuff" %}
</a>
<div id="my-id" class="reveal medium"
         data-reveal data-close-on-click='true'
         data-animation-in='fade-in' data-animation-out='fade-out'></div>
```

The modal box stays hidden after my toggle click. If data-animation is removed, modal appears.

**Comment by zurbchris** [comment]
Do you have the motion ui css included in the head of your document?

**Comment by imaia** [comment]
Yes I do, as it comes with custom foundation css. Do you need a snippet?

**Comment by zurbchris** [comment]
It actually doesn't... we're getting that fixed hopefully today. Something with the customizer not including it. Motion UI is bower-installable and all you need is the .css or .min.css linked in the head of your document.

**Comment by imaia** [comment]
Even using motion-ui from bower and foundation-sites from bower, reveal animation does not work. Background shades, but the modal itself never shows up. 

My modal looks like this:

```
<a data-open="contact-info">Contact</a> ...
<div class="reveal" id="contact-info"
     data-reveal data-animation-in="fade-in" data-animation-out="fade-out"> ... </div>
```

**Comment by zurbchris** [comment]
Could be the ordering of your stylesheets or script files? 
Have you resolved this issue on your own yet, or do you still need help?

**Comment by imaia** [comment]
I did resolve it on my own, but the example from docs does not work.

**Comment by zurbchris** [comment]
The docs need a bit of refinement, I'll agree. Glad you got it sorted though, and thanks.

**Comment by niklasp** [comment]
how did you fix it?

**Comment by jphase** [comment]
@niklasp you can fix this by including the motion-ui CSS. I included the one from the CDN just after my foundation.css in the <head>:

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.1.1/motion-ui.min.css">
