### ISSUE TITLE
Migration Guide Please - Foundation 5 - 6

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites#7318]
A migration guide is needed sooner rather than later.

**Comment by kokujin** [comment]
+1

**Comment by jivedog70** [comment]
+1 (x 1000)

**Comment by weiserma** [comment]
+1

**Comment by gakimball** [comment]
Rolling this into #7246. We're still working on it!

**Comment by jamJamDev** [comment]
Has a 5 to 6 guide been created yet?

**Comment by ncoden** [comment]
- [Migrating from v4 to v5](https://foundation.zurb.com/sites/docs/v/5.5.3/upgrading.html)
- [Migrating from v5 to v6 (unofficial compilation)](http://www.alwaysrightinstitute.com/foundation6/)
- [All Foundation releases](https://github.com/zurb/foundation-sites/releases)

**Comment by JeremyEnglert** [comment]
> @ncoden thanks! these are actually resources I have compiled on my on as well. Do you happen to know if there are plans for an 'official' guide?

Highly doubt an "official" guide will happen.

My best advice? Don't migrate an existing project to a new version of Foundation unless you're planning a redevelopment/redesign. There's really not much of a point.

**Comment by rgaufman** [comment]
Yes, we tried to migrate from 5 to 6 and after a week of effort, we gave up and moved back to Foundation 5 :(

We will eventually migrate to Bootstrap4 as it seems easier than upgrading to Foundation6.

**Comment by DanielRuf** [comment]
See https://getbootstrap.com/docs/4.0/migration/

Migrating now to a totally different framework is much more work.
