### ISSUE TITLE
F6.0.4 | Responsive Menu & Drill down, double bug

### ISSUE THREAD

**Issue by proov** [zurb/foundation-sites#7320]
Hey :)

Double bug here.. sorry :D

- Foundation 6.0.4 SASS
- Gulp 3.9.0
- gulp-sass 2.1.0
- Mac OS 10.10.5 Yosemite
- Chrome 46 
- Safari 9.01
- Firefox 41 & 42

Here is a code pen : http://s.codepen.io/proov/debug/EVqmPP

##### Span bug
In the responsive menu, in drilldown mode, when i have a `<span>` inside `<a>`, i have some strange click behavior.. I removed them and then i was able to click nicely on the links, to go to the 2nd level and go back.

##### 2nd level links
Strange bug here.. Still in drilldown mode, i can click on the root level links, but when i click on the 2nd level links (i didn't tried deeper levels), nothing happens... 

I did something wrong ?

Many thanks!! This feature is really impressive !

**Comment by zurbchris** [comment]
Drilldown links are broken for the moment. It's my highest priority to fix, so expect a solution soon.

**Comment by proov** [comment]
Ah great :)

**Comment by zurbchris** [comment]
Should be out today with 6.0.5 :ok_hand:

**Comment by proov** [comment]
Wow!! Many thanks, i can't wait to try :heart_eyes:

**Comment by zurbchris** [comment]
Do believe this has been fixed, please reopen if you still have issues :smile:

**Comment by MetalG3arSo1id** [comment]
On older iPhones like the iPhone 4s on 9.1iOS the drilldown menu top level links do nothing still. Works lovely on iPad's, iPhone 5 and 6 though : /

**Comment by MetalG3arSo1id** [comment]
Figured out why this doesn't work becuase the css transform value didn't have the -webkit- vendor applied:

These classes in _drilldown.scss need changing to:

    &.is-active {
      z-index: 1;
      display: block;
      transform: translateX(if($global-text-direction == ltr, -100%, 100%));
      -webkit-transform: translateX(if($global-text-direction == ltr, -100%, 100%));
    }

    &.is-closing {
      transform: translateX(if($global-text-direction == ltr, 100%, -100%));
      -webkit-transform: translateX(if($global-text-direction == ltr, 100%, -100%));
    }

**Comment by zurbchris** [comment]
those are added via auto-prefixer, we don't need to hard code them in.
<img width="274" alt="screen shot 2015-12-16 at 9 27 03 am" src="https://cloud.githubusercontent.com/assets/13631168/11848433/33c42242-a3d7-11e5-881e-7b7f09bf6d93.png">

**Comment by MetalG3arSo1id** [comment]
Yeah I figured that would be a standard thing added by the framework, just for some reason when debugging on safari through the iphone the -webkit-transform was not added.

**Comment by Saturn2888** [comment]
Could you put up an example in the docs of doing a drilldown with a responsive menu? I can't seem to get it to work; in fact, I get an error on invoking the Foundation plugin twice on the top-bar.
