### ISSUE TITLE
TopBar .contain-to-grid not available in Foundation 6 anymore?

### ISSUE THREAD

**Issue by R4c00n** [zurb/foundation-sites#7325]
Is there a special reason why the `.contain-to-grid` class doesn't exist in foundation 6 anymore? Or is there a new way to fit the top-bar into the grid?

**Comment by ScottyZA** [comment]
In the Foundation 6 docs, you can can give a full-width column a container class `column row` which will give the same behaviour as `contain-to-grid`. 

````
<nav class="column row">
  <div class="top-bar">
    ...
  </div>
</nav>
````

**Comment by gakimball** [comment]
@ScottyZA That's the solution, thanks :)

**Comment by R4c00n** [comment]
Thanks @ScottyZA :)

**Comment by zacksmash** [comment]
I did it a little bid differently, so I could keep the full width nav color.

```
<nav class="top-bar">
  <div class="row">
    ...
  </div>
</div>
```

**Comment by simonh1000** [comment]
thanks @zacksmash

**Comment by juchom** [comment]
Actually, this is working with the normal grid, but using flex doesn't work anymore. You have to set width : 100% in the div containing top-bar.

**Comment by SalahAdDin** [comment]
Will be great that the example have to nav instead div, and the Top bar should works with navbars.

**Comment by madhanan** [comment]
Am also facing the same problem, It doesn't work with "Flex Grid", I wish they had "contain-to-grid" in F6 also. so many features from F5 is lost.. :(

Top-Bar-Left takes the full width, forcing Tob-Bar-Right to go Below.. which is bad when using Flex-Box Grid. Whereas, in Normal grid - its fine.

Hope they fix such issues in F6

@zacksmash : Have you tried Responsive toggle in Flex-Box ??

**Comment by SalahAdDin** [comment]
@madhanan Yes,  you are right.
