### ISSUE TITLE
Drilldown backButton option

### ISSUE THREAD

**Issue by cbrunet** [zurb/foundation-sites#7334]
The example in documentation should clearly show HTML markup, i.e., `<li class="js-drilldown-back" tabindex="0"><a>Back</a></li>`.

IMHO, it would be simpler if the option would modify only what is inside the `a` tag (i.e., always include the `li` and the `a` tags). Is there a use case to modify the `li` and/or the `a` tag in this case?

**Comment by zurbchris** [comment]
That's a super fun issue with our docs compiler... it reads html examples written in the .js file and turns it in to markup. Sorta kinda solved it, for the moment.
