### ISSUE TITLE
bower.json 's main does not point to valid file or not ready for browser

### ISSUE THREAD

**Issue by pwang2** [zurb/foundation-sites#7336]
In bower.json, the main field shows as below. Here the `js/foundation.js` does not exists, `scss/foundation.scss` need to be transpiled for browser, when use automated tool like wiredep or other package resolver, this breaks the workflow. 
```
 "main": [
    "scss/foundation.scss",
    "js/foundation.js"
  ],
```

To solve this, we could have some branch or repo just for package version publish, then we could provide browser ready artifact there.  There are 2 references.
1. jquery team build and push special artifact (`/dist`) folder only to tagged version.
2. angular team use separate repo for angular and its components(animation,cookies)

**Comment by gakimball** [comment]
Per the [bower.json spec](https://github.com/bower/spec/blob/master/json.md) on `main`:

> Use source files with module exports and imports over pre-built distribution files.

The Sass file path is correct. For the JS, none of the source files really work as an entry point, so in that case I believe we'll use the compiled file in `dist/`. (This is what [Bootstrap 4](https://github.com/twbs/bootstrap/blob/v4-dev/bower.json) does.)

**Comment by pwang2** [comment]
@gakimball ,  if the main purpose of this is for build tools, at least the tool could **think** to figure out in the case of the entry js file.  But sadly, it can't.  If we planned to use the `dist/` file, we still have to commit `dist/` folder to remote. Best practice would be keep the dist folder on a version tag only.  That's what jquery team and angular team are doing. I will suggest that as well.

For the scss file, I partially agree with you.  Exception is what if we want to use a tool like `wiredep` to automate the dependencies for browser script include----this is a much more common scenario we have in our development.  For the smart guys who is using SCSS, they could totally figure out what is the entry file on his own.  Putting the entry file here may not help too much.  If then, why not give the benefit to the script include guys(via wiredep)?

Just some humble opinions FYI.

**Comment by pwang2** [comment]
@gakimball, the sass entry file should be `foundation-sites.scss`
