### ISSUE TITLE
[Responsive Navigation] Drilldown doesn't work with visibility class

### ISSUE THREAD

**Issue by Grafikart** [zurb/foundation-sites#7337]
**How can we reproduce this bug?**

1. Create a menu using `data-responsive-menu`, but hide one of the `<li>` using `.show-for-medium`
2. Open the page on small screen

**What happened instead?**

The menu has now a 0px height

Here is a codepen to see this nasty bug in live ^^ http://codepen.io/anon/pen/MKgwVW

**Comment by Grafikart** [comment]
In my opinion this bug is quite specific but come from 

https://github.com/zurb/foundation-sites/blob/develop/js/foundation.drilldown.js#L297

The menu height is calculated from the first element height (with is 0 since it's hidden for small screens).

**Comment by zurbchris** [comment]
Awesome. Thanks for pointing this out.
