### ISSUE TITLE
Toggler Not Working?

### ISSUE THREAD

**Issue by twd3** [zurb/foundation-sites#7338]
Why doesn't toggler work for me like it does in the docs? I searched and I can't find a current issue? Using full 6.0.4 from here...
```
<p><a data-toggle="panel">Toggle Panel</a></p>

<div class="callout" id="panel" data-toggler data-animate="hinge-in-from-top spin-out" data-closable>
<button class="close-button" data-close>&times;</button>
<h4>Hello!</h4>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta quas optio alias voluptas nobis iusto mollitia asperiores incidunt reprehenderit doloribus voluptatibus officiis minus, inventore, quasi nisi. Consequuntur, quidem. Sint, dictsdsa?</p>
</div>
```
I've tried:

data-toggler data-animate="hinge-in-from-top spin-out" << In docs example code...

data-toggler-animate="hinge-in-from-top spin-out" << In docs example description...

**Comment by Grafikart** [comment]
Could you do a codepen so we can see the bug easier ?

**Comment by gakimball** [comment]
Try removing `data-closable` and see if that does anything. `data-closable` is for elements that are dismissible once, while `data-toggler` is for elements that can be opened and closed repeatedly.

**Comment by twd3** [comment]
Good call gakimball, I tried that already as I was thinking the same thing. Didn't work. I have it uploaded to a dev server here if you want to check it: http://2016d3start.businesscatalyst.com/toggler.html

**Comment by zurbchris** [comment]
@twd3 nice smart menu, I wouldn't mind seeing that as a submission to building blocks :wink:
It seems the issue is you don't have the Motion UI css loaded anywhere. The classes are being applied correctly, but the animations are never occurring.

**Comment by twd3** [comment]
Wow really? But I download the full package? Isn't motion ui in that? I just added the "foundation.util.motion.js" file just in case it wasn't in the full package and it's still not working. Do you think I'm missing the motion UI css? Take a look I just updated dev page.

Thanks for the smart menu comment. I love that menu. The new menu in v6 just didn't suit my needs. I also opted to dump accordion and tabs and replaced with Easy Responsive Tabs to Accordion.

**Comment by zurbchris** [comment]
Motion UI is a stand-alone lib, we just happen to have built in (js) methods to utilize the animations, should you choose to include them. That being said, yes, you need to include `motionui.css` or the .min version for this example to work.

**Comment by twd3** [comment]
I am so confused. I have been using Foundation for years (thanks you guys RULE) and haven't run in to this. Where would I get the motion ui css? I don't see it anywhere in this complete package? Also, from what you just said...do I need to include that "foundation.util.motion.js" file or if I download the full version is it already there?

**Comment by twd3** [comment]
Wow, ok, I just got this working but no one ever told me that I had to go download the motion ui starter kit and include the css file for it to work. I assumed that if it was "included" it would have both the javascript AND css to work. It looks like the full package only has the JS...

ZurbChris, thanks a ton! All of you over there are the best and I owe you all big time.

**Comment by zurbchris** [comment]
Glad to hear you got it going. We know it's not always clear when you need to bring in motion ui, but just generally, if you're animating something through Foundation, you need the Motion UI css included in the head of your document.
