### ISSUE TITLE
Equalizer: collapsed margins break equalizing effect

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7340]
I'm not sure what *exactly* causes this bug, but I think it's collapsed margins. You can see it on the current docs for Equalizer:

![image](https://cloud.githubusercontent.com/assets/1142001/11510185/46e4814e-9817-11e5-8111-d814a1e520f7.png)

If we inspect the first column, it's the right height, but the bottom margin of its last child is collapsing into the bottom margin of the column, creating a height mismatch.

![image](https://cloud.githubusercontent.com/assets/1142001/11510241/92f513a0-9817-11e5-93f7-6d21720703c6.png)

Also need to figure out if it's a bug we can fix, or just something we need to tell people about so they can work around it.

**Comment by jordybell** [comment]
Make a '.callout .bar' sub-class w/ an adjusted 'margin-bottom'-The border of the initial box is rendering short because the border of the parent box is relational to 'bar' border..
![screen shot 2015-12-01 at 3 48 22 pm](https://cloud.githubusercontent.com/assets/5220505/11518165/f1fc10c0-9843-11e5-96df-f42fcbb472d5.png)

**Comment by Grafikart** [comment]
I don't get the docs, why the ` data-equalizer-watch="foo"` is on the `.medium-4.columns`  div instead of the `.callout` div ? 

For the other columns the data-equalizer-watch is on the `.callout` div. (Maybe I got the exemple wrong)

**Comment by jordybell** [comment]
Not 100% clear on  the rationale there either… but it seems pretty clear that the first collumn border is inheriting margin rules from the article boxes..Seems like using flex on those boxes instead of using JS to calculate margins would eliminate the conflicting CSS.

**Comment by zurbchris** [comment]
This issue has been addressed and will be resolved with the new equalizer coming soon, to a repo near you!! Also, for posterity, in this specific example @Grafikart was correct. Cheers!
