### ISSUE TITLE
Why is hide-for-small Excluded in Visibility?

### ISSUE THREAD

**Issue by merlinpatt** [zurb/foundation-sites#7343]
https://github.com/zurb/foundation-sites/blob/develop/scss/components/_visibility.scss#L71

Why is the `hide-for-small` class excluded?

If there is a good reason, then this needs to be mentioned on the [visibility docs page](http://foundation.zurb.com/sites/docs/visibility.html).

**Comment by gakimball** [comment]
`.hide-for-x` means "hide for x and up", so `.hide-for-small` is basically just the `.hide` class. I added a note to the docs clarifying this.
