### ISSUE TITLE
Add file input styling

### ISSUE THREAD

**Issue by imaia** [zurb/foundation-sites#7347]
It would be great to have a file input styling for foundation. Example: http://materializecss.com/forms.html#file

**Comment by JeremyEnglert** [comment]
@imaia, check this out: http://zurb.com/building-blocks/file-upload-button

**Comment by zurbrandon** [comment]
Yeah, this is the type of thing we'd keep in a building block rather than the codebase as a whole. Thanks @JeremyEnglert for finding it.

**Comment by imaia** [comment]
Thanks @JeremyEnglert
