### ISSUE TITLE
F6.0.4 button tag in input-group do not work as input-group-button

### ISSUE THREAD

**Issue by artisson** [zurb/foundation-sites#7348]
Hi all,

I've encountered a problem with input-group when using a <button> as input-group-button.
It got no height, and doesn't position after the field.

For example : http://codepen.io/artisson/pen/adoywX

I managed to give a correct height and width giving it the same height calculated for the input and a `width:auto;`
Curiously, place after another a.input-group-button it aligns correctly.

Did i found a bug ? Or the button tag has a behaviour that breaks the input group ?

**Comment by designerno1** [comment]
#7263

**Comment by gakimball** [comment]
See [my comment](https://github.com/zurb/foundation-sites/issues/7278#issuecomment-160790323) on #7278 for an explanation of how this is being fixed. Version 6.0.5 is being released today which will included these fixes and updated markup examples.
