### ISSUE TITLE
[Off-canvas] On Mobile - Multiple Menu - Right Menu Shows By Default (and Never Hides)

### ISSUE THREAD

**Issue by andrewbiddinger** [zurb/foundation-sites#7350]
Hello!

How To Reproduce: I've tested Foundation 6's "Off-Canvas Multiple Menu" on an Android and iPhone.
The Bug: The Off-Canvas "Right Menu" shows by default and never hides on mobile.

Note: It even has this bug on the Zurb Foundation page (http://foundation.zurb.com/sites/docs/off-canvas.html)

![screenshot_2015-12-02-13-31-40](https://cloud.githubusercontent.com/assets/6351977/11540157/3b7d9808-98f9-11e5-9a14-55b05f201c65.png)

**Comment by zurbchris** [comment]
Grumble, thought we had this fixed @gakimball . We'll look into it.

**Comment by andrewbiddinger** [comment]
Thank You!

**Comment by zurbrandon** [comment]
This looks to be all fixed up in 6.0.6, let me know if you're still seeing it. If you are if you could give me browser specs.

**Comment by zurbrandon** [comment]
I'll close this for now, but please reopen if it's still an issue.
