### ISSUE TITLE
[Slider] Problem in the Slider with Two Handles

### ISSUE THREAD

**Issue by Popdelite** [zurb/foundation-sites#7351]
In the slider with Two Handles, there is a problem: 
On moving the first handles down to the "0" and after this moving the second handles, the fill slider does not work well.

![foundation-fix](https://cloud.githubusercontent.com/assets/5438935/11541577/3a9992d6-9933-11e5-96c0-2ab779550461.jpg)

The problem is also visible on the site:
[http://foundation.zurb.com/sites/docs/slider.html#two-handles](http://foundation.zurb.com/sites/docs/slider.html#two-handles)

P.S. Ciao & thank you all, for all the great work you do

**Comment by zurbchris** [comment]
Ah, bugger. Thanks for pointing this out, cant believe I missed this.
