### ISSUE TITLE
More Flexible Plugin Calls - allow for DOM Elements and strings

### ISSUE THREAD

**Issue by merlinpatt** [zurb/foundation-sites#7352]
I think it would be great if the plugin calls were more flexible so you could do things like the below. This is particularly useful in Meteor because you can use a template's `instance.find` to only get elements within that template.

Currently I'm wrapping `instance.find` in a jQuery call but it looks a little ugly, so this would simplify things.

```
// in Meteor with DOM element
new Foundation.OffCanvas(instance.find('.off-canvas'));
// with string
new Foundation.OffCanvas('#offCanvas');
```

I believe this could be easily done by adding the following code to each plugin. I'd be willing to do this work myself but I want to get the okay before I do and it gets turned down.

```
if (! element instanceof jQuery) {
  element = $(element);
}
```

**Comment by zurbchris** [comment]
I thought about doing this, but it seemed a little unnecessary at the time. What would be a little simpler (code wise) would just default all elements to a jQuery call. Though this adds a function call to jQuery on every plugin init, I'm wondering what the perf penalty would actually look like.
currently it looks like `this.$element = element;` so it would just be `this.$element = $(element);`

**Comment by merlinpatt** [comment]
I feel like perf shouldn't increase at all since devs are already having to make the jQuery call themselves.

**Comment by zurbchris** [comment]
There's always going to be a minor perf drop with any additional calls to jQuery, but I think it's so minor it won't matter unless you're trying to initialize a couple hundred plugins in a loop or something.

**Comment by juliancwirko** [comment]
If I understand well you need this: `this.$('.dom-elem')` It is implemented in Meteor: http://docs.meteor.com/#/full/template_$

**Comment by merlinpatt** [comment]
Oh that's useful to know. Thanks @juliancwirko.

**Comment by zurbchris** [comment]
I'm going to close this for now, I don't think it's a bad idea, but I don't think it's necessary. Seems @juliancwirko pointed you in the right direction?

**Comment by merlinpatt** [comment]
Yes, he was able to help. Thanks!
