### ISSUE TITLE
[Off-canvas] Multiple Right or Multiple Left Menus - Feature Request

### ISSUE THREAD

**Issue by andrewbiddinger** [zurb/foundation-sites#7355]
Would it be possible to have two Off-Canvas menus (right and left) with multiple menus on the right or left with 3+ reveal buttons? 

A possible example: 
A single menu on the left off-canvas area (with a reveal button) and two menus on the right (with two reveal buttons).

Thanks so much!

**Comment by zurbrandon** [comment]
This isn't something we're planning to support since it would make more sense from a page architecture standpoint to use the same off-canvas right box, but then just conditionally show and hide content inside that box.

**Comment by zurbrandon** [comment]
I'll close this for now but feel free to reopen if you can provide more insights on this.
