### ISSUE TITLE
Foundation 6 Tab incorrect documentation

### ISSUE THREAD

**Issue by Ggpsv** [zurb/foundation-sites#7358]
The basic example for Tabs is incorrect in the Foundation 6 documentation.
http://foundation.zurb.com/sites/docs/v/5.5.3/components/tabs.html#vertical-tabs

`<ul class="tabs" data-tab>

    <li class="tab-title active"><a href="#panel1">Tab 1</a></li>
    <li class="tab-title"><a href="#panel2">Tab 2</a></li>
    <li class="tab-title"><a href="#panel3">Tab 3</a></li>
    <li class="tab-title"><a href="#panel4">Tab 4</a></li>
</ul>

`tab-title` class doesn't exist, 'tabs-title` does exist thought. The correct example would be:

`<ul class="tabs" data-tab>

    <li class="tabs-title active"><a href="#panel1">Tab 1</a></li>
    <li class="tabs-title"><a href="#panel2">Tab 2</a></li>
    <li class="tabs-title"><a href="#panel3">Tab 3</a></li>
    <li class="tabs-title"><a href="#panel4">Tab 4</a></li>
</ul>

**Comment by IllusionPerdu** [comment]
Your link is for foundation 5.5.3

**Comment by andrewbiddinger** [comment]
Yes, that confused me at first. Check the v6 Documentation. A few classes haved been minorly changed.

**Comment by zurbchris** [comment]
Closing this.
