### ISSUE TITLE
[Responsive Navigation] sub menu arrows

### ISSUE THREAD

**Issue by therealbenhogan** [zurb/foundation-sites#7361]
Using the latest version 6.0.5

I am trying to create a drop down menu for standard screen sizes and the drill down for smaller screens - the same as the standard menu in Foundation 5. Using the mark up shown below.

It works (navigation links) but 

(a) how do we get the top level nav arrows on the dropdown menu for larger screens to be positioned down as opposed to the right. If you remove the vertical class from the parent ul (done) below, this gets the arrows pointing down but messes up the display of the drill down menu on smaller screens  and 

(b) unless you style the menu to have a fixed width (as shown in the code example on the site (and included below), I can't get the nav arrows to show on the drill down for smaller screens, and as the menu has been given a fixed width, the arrows won't be positioned correctly across all smaller screen sizes.

      <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
        <button class="menu-icon" type="button" data-toggle></button>
        <div class="title-bar-title">Menu</div>
      </div>

      <ul class="medium-horizontal menu" id="example-menu" data-responsive-menu="drilldown medium-dropdown" style="width:320px;">
        <li class="has-submenu">
          <a href="#">Item 1</a>
          <ul class="vertical submenu menu" data-submenu id="m2">
            <li class="has-submenu">
              <a href="index-inline-form.html">Item 1A</a>
              <ul class="vertical submenu menu" data-submenu id="m3">
                <li><a href="#l">Item 1A</a></li>
                <li><a href="#">Item 1B</a></li>
                <li><a href="#">Item 1C</a></li>
                <li><a href="#">Item 1D</a></li>
                <li><a href="#">Item 1E</a></li>
              </ul>
            </li>
            <li><a href="#">Item 1B</a></li>
          </ul>
        </li>
        <li class="has-submenu">
          <a href="#">Item 2</a>
          <ul class="vertical submenu menu" data-submenu>
            <li><a href="#">Item 2A</a></li>
            <li><a href="#">Item 2B</a></li>
          </ul>
        </li>
        <li class="has-submenu">
          <a href="#">Item 3</a>
          <ul class="vertical submenu menu" data-submenu>
            <li><a href="#">Item 3A</a></li>
            <li><a href="#">Item 3B</a></li>
          </ul>
        </li>
      </ul>

**Comment by equimed** [comment]
You can see this side-pointing arrow issue for the dropdown on the Foundation website sample HTML template for News or Magazine style website. See http://foundation.zurb.com/templates-previews-sites-f6/news-magazine.html

**Comment by rafibomb** [comment]
I think this example highlights the issue: http://codepen.io/rafibomb/pen/ZQEGog?editors=1100

**Comment by SalahAdDin** [comment]
:+1:

**Comment by gakimball** [comment]
With the 6.2 release out tomorrow, we made a number of refinements to dropdown menus, including fixing many issues with menu logic, including arrow positioning. You can preview the fixes on the `6.2-stable` branch: <https://github.com/zurb/foundation-sites/tree/6.2-stable>

**Comment by therealbenhogan** [comment]
Many thanks for letting me know Geoff!

[image001]

Paul Sawyer
Web Preference Ltd
14 Oakdale Road
Weybridge
Surrey KT13 8EJ

Telephone: 01932 424242
Mobile: 07968 164104
Web: http://web-preference.co.uk<http://web-preference.co.uk/>

Registered in England & Wales No. 5426254 VAT registration no. GB 860 5011 58
