### ISSUE TITLE
[Top Bar] ISSUE NAME HERE

### ISSUE THREAD

**Issue by alinarisku** [zurb/foundation-sites#7366]
**How can we reproduce this bug?**

1. Step one
copy paste top bar code
2. Step two
add href where the link should point
3. Step three
loading in browser, link does not work when clicked

**What did you expect to happen?**
I expect a link to open

**What happened instead?**
it does not open on click, however it opens if I right click --> Open in new tab

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.
https://codepen.io/alinariskute/pen/VeZROg

**Comment by zurbchris** [comment]
That pen doesn't have the Foundation JS loading on my end, can you double check and get back to me when it works?

**Comment by zurbrandon** [comment]
Looks like this is just an issue with codepen, just tested it out on my local and it works, but on codepen they're blocking opening in the iframe.
