### ISSUE TITLE
[Button] why margin-right

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7367]
why the .button class has a margin-right?

**Comment by andrewbiddinger** [comment]
Very good question! I was bothered by this myself.

**Comment by andycochran** [comment]
:ear: I'd also like to know.

**Comment by zurbchris** [comment]
@zurbrandon or @gakimball have an answer for this?

**Comment by gakimball** [comment]
So when you put multiple buttons next to each other, they space out automatically.

**Comment by andrewbiddinger** [comment]
I understand that and it makes sense for solving that issue. But, what if you are wanting to put a button within something (Example: Panel, Nav Menu..ect) that the margin causes problems? It seems like this is a big assumption on a very generic .button class.

When a button is displayed as "inline-block" a simple space character " " between an "a" or "button" tag will add sepperation. Any other button margin should be a custom class, in my opinion. What do you think @gakimball ?

**Comment by designerno1** [comment]
but if you float the button right you have extra space to the right
in F5 buttons have no margin right as far as i know

**Comment by andycochran** [comment]
"Multiple buttons next to each other with margin" seems like an app-specific customization— for which you could do `.component .button + .button { margin-left: ... }`. Also, is this not what button groups are for?

**Comment by designerno1** [comment]
also seen here http://foundation.zurb.com/sites/docs/float-classes.html#float-left-right
i also think the right margin should be app specific and not in foundation core

**Comment by simonrcodrington** [comment]
I can see why it's been built that way (so buttons are spaced out). However I also thought that's what a button group should be used for (so it's implicit that you're going to show a group of buttons)

A quick thought is to set the margin on the left normally (so they work in a group and space out), but then remove the margin left on the first child so that when they sit by itself it doesn't set a margin.

**Comment by designerno1** [comment]
zurb please remove the margin-right as it is equal to F5

**Comment by andrewbiddinger** [comment]
@designerno1 Agreed!

**Comment by zurbrandon** [comment]
This has been fixed on develop, thanks all.
