### ISSUE TITLE
[Customizer/Download] Downloadable version is 6.0.1…

### ISSUE THREAD

**Issue by NicolasGraph** [zurb/foundation-sites#7368]
As said [here](https://github.com/zurb/foundation-sites/issues/7125), the downloadable version on the Foundation website (complete, essential or customized) is 6.0.1 while the current one is 6.0.5.

**Comment by gakimball** [comment]
Paging @erikmellum

**Comment by erikmellum** [comment]
Looking into it! Thanks!

**Comment by erikmellum** [comment]
@NicolasGraph @gakimball  We are running the most up to date version on the customizer now. Also looking into the auto update process and making sure it runs smoothly so it updates itself!
