### ISSUE TITLE
[JavaScript] Orbit control doesn't work

### ISSUE THREAD

**Issue by nire0510** [zurb/foundation-sites#7370]
**How can we reproduce this bug?**

1. Download Foundation's complete css zip folder and extract
1. Clone index.html and replace its body content with the [orbit markup from the documentation website](http://foundation.zurb.com/sites/docs/orbit.html)
1. Open page in browser

**What did you expect to happen?**
Orbit should work similar to the demo

**What happened instead?**
1. Orbit automatically switches to slide #2 after few seconds, but what is happened actually is that the content of slide #2 is drawn above slide #1
1. Orbit bullets are not clickable

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by zurbchris** [comment]
You don't have Motion-UI css installed/linked in head of your document. If you choose not to use Motion-UI, set `data-use-m-u-i="false"`

**Comment by zurbrandon** [comment]
I'll close this oiut, since it looks like it was a motion ui issue. If i'm incorrect let me know and reopen. Thanks!
