### ISSUE TITLE
[Reveal] JS Documentation missing options

### ISSUE THREAD

**Issue by DataTables** [zurb/foundation-sites#7371]
**How can we reproduce this bug?**

1. Load [the Javascript reference for [Reveal](http://foundation.zurb.com/sites/docs/reveal.html)

**What did you expect to happen?**

The code to create a new instance shows:

    var elem = new Foundation.Reveal(element);

Below `element` and `options` are defined. There is no `options` in the construction - presumably it should be the second parameter.

**What happened instead?**

Missing second parameter.

**Test case**

Docs page.

Trivial bug, sorry!

**Comment by Owlbertz** [comment]
The options are listed right at the end of the page.

**Comment by DataTables** [comment]
Sure - they are there, but the constructor doesn't show where to use them. It just needs to be:

    var elem = new Foundation.Reveal(element, options);

Or perhaps more correctly:

    var elem = new Foundation.Reveal(element [, options] );

since they are optional.

It might be worth noting in the documentation that the element needs to be in the document as well as it is not automatically added like it was in v5.

**Comment by Owlbertz** [comment]
Yes, sorry, I misunderstood the problem. You are right, the options should be included in the example constructor.

**Comment by gakimball** [comment]
Updated via zurb/foundation-docs@36411a5e2cd624d9dcb31783e58ce4f04419baa3
