### ISSUE TITLE
Problem with input types when compiling scss.

### ISSUE THREAD

**Issue by TheCopartnery** [zurb/foundation-sites#7375]
When compiling from scss (i'm using Django Libsass - https://github.com/torchbox/django-libsass), the resulting css generates invalid output that can't be read by the browser, ie: 

```[type=\'text\'], [type=\'password\'], [type=\'date\'], [type=\'datetime\'], [type=\'datetime-local\'], [type=\'month\'], [type=\'week\'], [type=\'email\'], [type=\'number\'], [type=\'search\'], [type=\'tel\'], [type=\'time\'], [type=\'url\'], [type=\'color\'],```

Expected behaviour... output should be stripped of all backslashs, making it the same as is found in foundation.css, ie:

```[type='text'], [type='password'], [type='date'], [type='datetime'], [type='datetime-local'], [type='month'], [type='week'], [type='email'], [type='number'], [type='search'], [type='tel'], [type='time'], [type='url'], [type='color'],```

The relevant line from _utils/_selector.scss is:

`$return: append($return, unquote('[type=\'#{$type}\']'), comma);`

**Comment by AgentPL** [comment]
I experienced the same issue with the official SASS compiler and Leafo's scssphp. It works fine when replacing this line to:
$return: append($return, unquote('[type="#{$type}"]'), comma);

**Comment by zzplab** [comment]
Duplicate from [#7204](https://github.com/zurb/foundation-sites/issues/7204) and [#7312](https://github.com/zurb/foundation-sites/issues/7312). See answers from @gakimball

**Comment by gakimball** [comment]
Yeah, django-libsass might be out of sync with the newest version of Libsass. You need a compiler referencing Libsass 3.3. Make sure you're using the newest versions of django-libsass (and python-libsass, which this library uses).

**Comment by robocoder** [comment]
Please see if this is fixed by https://github.com/leafo/scssphp/commit/c727c14ddd0de785af5dcc26c90422f361adf5f3

**Comment by AgentPL** [comment]
Works fine, thanks!

**Comment by zzplab** [comment]
Yep, works fine! Great.

**Comment by gakimball** [comment]
@robocoder That's for putting a fix in! Much appreciated :)
