### ISSUE TITLE
[Reveal][Off-Canvas] Z-index issue on iOS (v9 iPhone 6 tested on Chrome)

### ISSUE THREAD

**Issue by aibrean** [zurb/foundation-sites#7380]
**How can we reproduce this bug?**
F6.0.5
Use the actual device (I know it definitely is a bug with iOS 9 on an iPhone 6). The Chrome emulator doesn't replicate it. I was running Chrome on there. Seems to be iOS specific rather than browser in iOS.

I'm thinking that: 
+ it's directly related to having `off-canvas` on the site 
+ it's related to where `reveal-overlay` is inserted - specifically outside of the off-canvas wrappers.

**What did you expect to happen?**

Proper z-indexing so the reveal is above the overlay. Seems to be isolated on sites using off-canvas.

**What happened instead?**

Everything is darkened.

**Test case**

![reveal-zindex](https://cloud.githubusercontent.com/assets/6740252/11572507/b39b360c-99cf-11e5-9091-2cf514988a42.png)

**Comment by Owlbertz** [comment]
This has already been reported in #7280. However, this seems to be a tough one. This also happens on iOS 8.3 as well by the way.

**Comment by aibrean** [comment]
@Owlbertz it's not specific to Safari.

**Comment by Owlbertz** [comment]
Yep that's true. It becomes even weirder if you try http://codepen.io/Owlbertz/pen/eJOQVv?editors=101 on your iPhone.

**Comment by aibrean** [comment]
That codepen works for me.

**Comment by Owlbertz** [comment]
That's what I meant. Modals do work in Codepen and JSbin...

**Comment by aibrean** [comment]
http://codepen.io/aibrean/pen/LGYExq

It's the off-canvas doing it.

**Comment by Owlbertz** [comment]
Alright, that is what causes it, but the question why this only happens on iOS remains.
I will try to find a fix based on your findings.
