### ISSUE TITLE
off-canvas - main content-class

### ISSUE THREAD

**Issue by mmjaeger** [zurb/foundation-sites#7381]
Hello
In the off-canvas settings you allow the following class setting - however, it is not used further down:
/// CSS class used for the main content area. The off-canvas mixins use this to target the page body.
$maincontent-class: 'off-canvas-content' !default;

 // Container for page content
  .off-canvas-content {
    min-height: 100%;
    background: $body-background;
    transition: transform $offcanvas-transition-length $offcanvas-transition-timing;
    backface-visibility: hidden;
    z-index: 1;

    @if has-value($maincontent-shadow) {
      box-shadow: $maincontent-shadow;
    }
  }

**Comment by zurbrandon** [comment]
Looks like a PR #7486 fixes this, so I'll close it, but feel free to reopen if i was mistaken. 

Thanks for reporting the issue!
