### ISSUE TITLE
Generated CSS is invalid. Firefox warning: Ruleset ignored due to bad selector (&)

### ISSUE THREAD

**Issue by felipsmartins** [zurb/foundation-sites#7382]
I don't know if that's a real error, but  as Firefox as WebStorm has been issuing regards `&` selector, see:

![foundation](https://cloud.githubusercontent.com/assets/454116/11572766/abb42752-99e1-11e5-819d-3383da28509f.png)

Is not supposed `&` symbol to be a Sass selector only?

**Comment by aibrean** [comment]
Yes, it's proper. However, note you're looking at CSS. It shouldn't be compiled that way.

**Comment by felipsmartins** [comment]
@aibrean In fact, it is generated by sass, not me. Even though you download foundation-sites, you can see it in dist file with this error.

**Comment by gakimball** [comment]
Going to see if we can get this fixed in the next day or so.

**Comment by aibrean** [comment]
@felipsmartins I realize that. My point is using the & is proper for SCSS, however your example was from CSS which made me look into the SCSS file itself and that's where I noted the error. It could compile, but it compiled an output that wouldn't be recognized by browsers.

**Comment by IllusionPerdu** [comment]
The fix is hear https://github.com/zurb/foundation-sites/pull/7346

**Comment by felipsmartins** [comment]
@IllusionPerdu mmmm.... It's true.

**Comment by gakimball** [comment]
Fixed via b53e0b539e9d3c5002c445e73067fa62168d4f89

Instead of assigning `&` to a `$selector` variable, I just interpolated `&` directly.

**Comment by felipsmartins** [comment]
@gakimball It'll be available on the next release only? I've installed foundation-site v6.0.5 via bower and it seems like doesn't receive any updates regarding the issue.
Anyway, many thanks! ;)

**Comment by gakimball** [comment]
Yep, it'll be in 6.0.6, which will likely come out Friday.

**Comment by felipsmartins** [comment]
@gakimball Thanks a lot, mr. Kimball! ;)
