### ISSUE TITLE
Don´t use variables for black and white

### ISSUE THREAD

**Issue by jmartsch** [zurb/foundation-sites#7383]
They are absolute colors and not to be redefined.
So please remove them from _global.scss and use other variables instead.

If someone wants to use another color, the variable name would not match and isn´t semantically correct.

**Comment by aibrean** [comment]
The only reason I can see for using them as variables is lighten/darken.

**Comment by zurbrandon** [comment]
The reason we do this is because white and black are both subjective colors in a sense. It makes it easier for someone to use #fefefe as their main white, if they choose as we do this often.

**Comment by gakimball** [comment]
We're giving developers the flexibility to modify what "black" and "white" mean in their design. They might not be semantic names like `$primary-color`, but the key is that they're *constants*. We don't use hex colors anywhere in the default framework styles, to ensure that we're using a small, consistent color palette.
