### ISSUE TITLE
foundation.util.triggers.js strict bug

### ISSUE THREAD

**Issue by rolandschuetz** [zurb/foundation-sites#7384]
when opening on an iPhone, foundation.util.triggers.js fails on line 2755 with the error:
SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.

**Comment by zurbchris** [comment]
This issue should have been fixed with 7c8ad67, can you verify this is still an issue you're having? I know it's a month on, sorry about that.

**Comment by gakimball** [comment]
Going to close this as the issue has definitely been resolved. If you're still running into a strict mode error with the latest Foundation, let us know :)

**Comment by rolandschuetz** [comment]
I con confirm, it works with the current version.

**Comment by lspoor** [comment]
This is occurring for my on the latest version, any updates?
