### ISSUE TITLE
Remove settings file from published packages

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7385]
Our Bower, npm, etc. packages should ignore the file `scss/settings/_settings.scss`. It's just there as a reference, and the framework doesn't use it directly. Some developers are confused by the presence of this file along with the `_settings.scss` that ships with a blank project.

**Comment by michaelrshannon** [comment]
@gakimball I'm just getting up to speed on Foundation 6, so apologies if this is a stupid question: our Foundation 5 workflow was set up to install Foundation via Bower, and then copy `foundation/scss/foundation/_settings.scss` to our sass folder, and `@import` before `foundation/scss/foundation.scss`. 
I'm struggling to see where in the folder Bower downloads we can find a similar file - the ignored file referenced in this issue doesn't quite seem to be the same (the F5 settings file had everything commented out, allowing us to selectively override where necessary), and I'm now confused as I can't find the `_settings.scss` file you referenced that ships with a blank project.

Any help greatly appreciated!

**Comment by gakimball** [comment]
@michaelrshannon You can always find an up-to-date settings file here: <https://github.com/zurb/foundation-sites-template/blob/master/scss/_settings.scss>

This is a bit tricky. We removed the file from the package contents because we don't want developers trying to import it, because you shouldn't be editing any files within a dependency package directly. At the same time, maybe we're not adequately addressing the use-case of developers who load the framework into their own stack and need a settings file.

I'll add some stuff to the documentation to make this more clear. Specifically, we have a section in the docs on [manually loading Sass](http://foundation.zurb.com/sites/docs/sass.html#loading-the-framework), and we can add some explanation there.

**Comment by ivanjaros** [comment]
Damn. I had build a Drupal theme on F6 few weeks ago, now I wanted to make a new one and the settings file is gone. Very confusing.

**Comment by gakimball** [comment]
We added it back in 6.1.
