### ISSUE TITLE
[Warning] EBUNDLEOVERRIDE Replacing bundled foundation-cli > bower > fs-write-stream-atomic with new installed version

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation-sites#7390]
I have installed foundation-cli with npm as tutorial says and i have these warning:
```bash
EBUNDLEOVERRIDE Replacing bundled foundation-cli > bower > fs-write-stream-atomic with new installed version
```

I haven't problemes with foundations buti think that will be verify and fix this warning.

In addition i cand see these lines:

```bash
WARN deprecated exec@0.1.4: deprecated in favor of builtin child_process.execFile


fs-write-stream-atomic@1.0.4-fix  (git://github.com/sheerun/fs-write-stream-atomic.git#ac0f001d165564b3763da3252d5bff327c26aea9)
```

Thank you very much!

**Comment by gakimball** [comment]
Just released version 2.0.1 which removes both of these warnings. [Here's the full changelog.](https://github.com/zurb/foundation-cli/releases/tag/v2.0.1)

**Comment by SalahAdDin** [comment]
It's ok, but, your changelog it's wrong and cli commands too:

```bash
tulipanrog@tulipanrog-G771JW:~$ foundation --version
Foundation CLI version 2.0.1
tulipanrog@tulipanrog-G771JW:~$ foundation -v

Commands:
  new       Create a new Foundation project
  update    Update an existing Foundation project
  watch     Watch a project's files for changes
  build     Build a project's files for production
  help      Show this screen
  -v        Display the CLI's version

To learn more about a specific command, type foundation help <command>

Need more help? Ask a question on the Foundation Forum: foundation.zurb.com/forum
```

**Comment by gakimball** [comment]
What's wrong about the changelog?

**Comment by SalahAdDin** [comment]
```bash
Removed the --version and --edge flags, which weren't being used. They'll be back eventually!
```

This, --version works yet.

**Comment by gakimball** [comment]
Right, there were two uses for the `--version` flag. One is just to show the version of the CLI. The other is to specify a specific version of Foundation when you're installing a new project. *That* flag use was removed, because the functionality was buggy, and the feature itself not super critical at the moment.

**Comment by SalahAdDin** [comment]
Ah, i understand, thanks.
