### ISSUE TITLE
[F 6.0.4] Dropdown is running off the right side of the page

### ISSUE THREAD

**Issue by Gacnt** [zurb/foundation-sites#7391]
Not sure how I can prevent this I've tried `data-alignment="left"` but this is what I have
```
<ul class="dropdown menu" data-dropdown-menu>
	<li>
		<a href="#">{{ username }}</a>
		<ul class="menu">
			{{ if admin }}
			<ul class="dropdown menu vertical" data-dropdown-menu style="max-width: 200px;">
				<li>
					<a href="#">Admin</a>
					<ul class="menu">
						<li><a href="#">Manage Forum</a></li>
					</ul>
				</li>
			</ul>
			{{ end }}
			<li><a href="/logout">Logout</a></li>
		</ul>
		</a>
	</li>
</ul>
```

It is the `Manage Forum` link runs off the right side of the page.

**Comment by foodgy** [comment]
Looks like ```data-alignment``` work. I've tried ```left|right``` and the only change was the position of the submenu arrow. https://github.com/zurb/foundation-sites/issues/7233

**Comment by rafibomb** [comment]
Thanks @foodgy We'll close in favor of #7233
