### ISSUE TITLE
Button Group - Can't use .stacked-for-small and .expanded for the same group

### ISSUE THREAD

**Issue by mediamr** [zurb/foundation-sites#7393]
If i use .stacked-for-small and .expanded for the same button group, the group is expanded, but the stacking-option for small is broken.
Problem: button group sticks with the calculated width on small (e.g. 4 items = 25% width)
Should be: stacked with 100% width

**Comment by rafibomb** [comment]
Sounds like the expanded class needs to extent into the small styles. A Pull Request for this would really help.

**Comment by andycochran** [comment]
Does this help? #7566
