### ISSUE TITLE
[Dropdown] Pressing space in an input in a DD causes page to scroll

### ISSUE THREAD

**Issue by jnpoyser** [zurb/foundation-sites#7394]
**How can we reproduce this bug?**

Even exists in docs:
1. Go to http://foundation.zurb.com/sites/docs/dropdown.html
2. Click on 'toggle dropdown' button
3. Enter text in input, press space

**What did you expect to happen?**
The page not to scroll

**What happened instead?**
The page scrolled :-)

**Comment by Owlbertz** [comment]
Issue seems to be that the focus shifts to the dropdown when space is pressed, causing the scrolling behavior. I will fix this.

**Comment by rafibomb** [comment]
@Owlbertz Awesome!

**Comment by gakimball** [comment]
Fixed via #7416
