### ISSUE TITLE
This is not an issue but a reflection about name class and size

### ISSUE THREAD

**Issue by IllusionPerdu** [zurb/foundation-sites#7395]
in the grid system you also let the class "column" and "columns"

Case 1: the character size "column" is 6
in the css file generated with the default parameter 112 times it is repeated
=>
it occupies (6 * 112 =) 672o if it was repeated only without any class.
(If used with another character class 7: (6 + 7) * 112 = 1456o)

Case 2: The character size "columns" is 7
in the css file generated with the default parameter 112 times it is repeated
=>
it occupies (7 * 112 =) 784o if it was repeated only without any class.
(If used with another character class 7: (7 + 7) * 112 = 1568o)

I think we must achieve the size 2ko less if only one of the grammar is used.

I think it should have is therefore only one possible view that grammar is webdeveloper to the good name of different class. And that the size of the file is important (especially for those who pay the bandwidth)

What do you think ?

**Comment by zurbrandon** [comment]
Yeah, i understand this and to be honest the column columns thing is there mainly due to legacy. We removed a ton of redundancy grammer classes from 5 to 6 like we used to spell leed and lead for P tags, but got feedback that remove this may screw with too many peoples brains.
