### ISSUE TITLE
[Sticky improvement] don't stick immediately if sticky container height is greater than screen height…

### ISSUE THREAD

**Issue by NicolasGraph** [zurb/foundation-sites#7396]
…but scroll the container and stick it when its bottom is riched (like in [Sticky-kit](https://github.com/leafo/sticky-kit)).

**Comment by rafibomb** [comment]
Having a hard time visualizing this request. Do you have an example where it could work better with this change?

**Comment by NicolasGraph** [comment]
[Here](http://leafo.net/sticky-kit/), in the fourth exemple, the *Very tall sidebar* sticks only when ist bottom appears. With Foundation Sticky it wouldn't scroll and we couldn't see the entire content of the *Very tall sidebar*.

**Comment by andycochran** [comment]
I think this is an edge case. Closing. Can reopen if others think this feature necessary.
