### ISSUE TITLE
cannot get sass working without adding prefix to foundation.scss

### ISSUE THREAD

**Issue by partnuz** [zurb/foundation-sites#7397]
grunt-contrib-sass throws an error stating missing path in foundation-sites.scss I must add scss dir mention file to make it work. Is it default behaviour or bug ? How to I overcome it without adding dir everytime bower updates foundation

I use newest versions ( just checked ) of
grunt-contrib-sass
ruby
git
compass
win7x64

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.
