### ISSUE TITLE
[Orbit] Question : How to get an existing instance

### ISSUE THREAD

**Issue by bnbc** [zurb/foundation-sites#7398]
To create a new instance we do this : var elem = new Foundation.Orbit(element);

How to get an instance created by $(document).foundation(); and HTML attributes ?

Thanks !

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.
