### ISSUE TITLE
Modal z-index issue on older ipads....

### ISSUE THREAD

**Issue by jeffdingwell** [zurb/foundation-sites#7400]
On older ipads (iOS8) modals are sitting behind the darker overlay.

http://foundation.zurb.com/sites/docs/reveal.html

**Comment by aibrean** [comment]
Yep...we know :) #7380 #7281

**Comment by jeffdingwell** [comment]
Sorry. I’m a loser for not checking.  :(

Good job on Foundation 6! Looks great.

J.

**Comment by gakimball** [comment]
@jeffdingwell Don't be so hard on yourself! We have a *lot* of issues open right now, so we get duplicates all the time. Thanks for contributing! :)

Closing in favor #7380
