### ISSUE TITLE
[Reveal] Modal not working

### ISSUE THREAD

**Issue by asfo** [zurb/foundation-sites#7401]
**How can we reproduce this bug?**

1. Copy / paste the code found in the docs
2. Click on the "Click me for a modal"
3. Nothing happens

**What did you expect to happen?**

Opens a modal

**What happened instead?**

Nothing

**Test case**

![image](https://cloud.githubusercontent.com/assets/829964/11598805/a18902cc-9a89-11e5-885c-5ea5b3dd9343.png)
![image](https://cloud.githubusercontent.com/assets/829964/11598828/c6ed44a6-9a89-11e5-9f00-21ff96e9f184.png)

**Comment by aibrean** [comment]
Where is the modal code itself located (i.e. the one with the ID of `reveal`)?

**Comment by asfo** [comment]
I tried it in a new file (clean file) and still nothing...I tried to comment everything so I left the code for the modal only, but still, nothing.

![image](https://cloud.githubusercontent.com/assets/829964/11599251/5957fccc-9a8b-11e5-940b-35dc1f4dbd8a.png)

**Comment by aibrean** [comment]
And you're using 6.0.5?

**Comment by asfo** [comment]
Yes, and I did that, but still nothing. :\ ...I think I'm going to use a jQuery plugin ...

**Comment by gakimball** [comment]
Are you initializing Foundation in your `app.js` file? If so, do you get any console errors?

**Comment by aibrean** [comment]
Did you try the non minimized foundation file?

**Comment by asfo** [comment]
Yes, I had the $(document).foundation(); on it... the fix, simply: i tried the non minimized file :S and now is working, but the minimized is bugged (on chrome only, in firefox works), at least, for me.

**Comment by aibrean** [comment]
@asfo there has been ongoing disparity between minified and non-minified since the release. It's worth noting those issues continue to creep.
