### ISSUE TITLE
[Installation] foundation command not found

### ISSUE THREAD

**Issue by benjamin-derepas** [zurb/foundation-sites#7402]
**How can we reproduce this bug?**

1. Step one
2. Step two
3. Step three

**What did you expect to happen?**

**What happened instead?**

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by benjamin-derepas** [comment]
Hello world, i can't install the new foundation CLI.
I've remove old cli, and tried "npm install foundation-site" or "npm install --global foundation-cli", no error when installing, but my cli doesn't find "foundation" command, could i have some help please ?

**Comment by gakimball** [comment]
Type `which foundation` and see if anything comes up.

Also, what operating system and command line do you use? What are your Node and npm versions? Lastly, how do you install Node (Homebrew, nvm, etc.)?

**Comment by benjamin-derepas** [comment]
I'am on windows 8.1 Pro, wich cmd does'nt exist.
Node : V 4.1.2
Npm : 2.14.4
I've installed Node with Node installer.

But, on my mac os, foundation cli works

**Comment by benjamin-derepas** [comment]
Problem solved. Remove node , npm and re-installing all on stable version

**Comment by gakimball** [comment]
Nice, good to hear! If you have any other issues with the CLI, let us know in a new issue :)
