### ISSUE TITLE
Menu simple always overwritten if not in menu-text

### ISSUE THREAD

**Issue by jfalk** [zurb/foundation-sites#7404]
It seems that adding the 'simple' class to a menu does not work as intended unless it is inside a li with menu-text.

`.menu > li:not(.menu-text) > a {
    display: block;
    padding: 0.7rem 1rem;
    line-height: 1;
}`

overrides the padding in

`.menu.simple a {
    padding: 0;
    margin-right: 1rem;
}`

The result is that the padding is not removed.

**Comment by gakimball** [comment]
Closing in favor of #7892. Looking to resolve the specificity issue.
