### ISSUE TITLE
Can't use Type in Abide Validation

### ISSUE THREAD

**Issue by calmass** [zurb/foundation-sites#7406]
Validation with Abide only works with the "pattern" attribute set, not based on the type. In fact, when the "type" attribute is anything other than "text", the validation always fails.  I know you guys are going for code reduction, but the behavior should be to attempt to read the pattern  first, then the type to check for special validation.  I'll write my own javascript shim and use that for now, but out-of-the-box would be prettier and make updates easier.  I'll repost when complete and tested.

**Comment by zurbchris** [comment]
Should be fixed with #7590, please comment and submit pr's to the `abide` branch until 6.1 release.
