### ISSUE TITLE
[sticky] Width of sticky item

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites#7409]
I've been playing around with the sticky plugin and not sure if this is a bug or me not understanding how to use it correctly.

Here's a Codepen I setup so I could help some people on the Foundation forum who were asking for a sticky top-bar: http://codepen.io/brettsmason/pen/adbYXV

Basically I would of expected the top bar to be 100% width of the page, but as you can see it isn't. If I set the top-bar to 100vw or a value other than a % it seems to work.

Is this a bug or am I doing something wrong?

**Comment by colin-marshall** [comment]
I asked this on Gitter the other day and @zurbchris informed me that the Sticky plugin doesn't work with the top-bar out-of-the-box yet. It's on the roadmap to be added. He pointed out that right now you can use Magellan and Sticky together for a sticky navigation bar.

You can see our conversation about this on the [Foundation-Sites Gitter](https://gitter.im/zurb/foundation-sites) channel if you scroll up to Dec. 3rd.

**Comment by brettsmason** [comment]
Thanks Colin good to know. It seems (from my testing at least) that percentage width items seem to cause sticky some issues. Overall seems really great though other than this.

**Comment by zurbchris** [comment]
Sooooo, sorry for the delay. Sticky nav bars totally work, I have a few pens up with different examples, and there will be an example on the docs soon, just have to set up an iframe (and they are annoying).

In the meantime, here's a pen with the markup and a minor css addition needed. http://codepen.io/zurbchris/pen/wMdpzL
