### ISSUE TITLE
[The Grid] Breakpoints not same in FF5.X and FF6.X

### ISSUE THREAD

**Issue by srikanth912** [zurb/foundation-sites#7410]
**How can we reproduce this bug?**
1. Create simple grid
2. Open page in browser and resize window to 640px and 1024px (resizing to 639px and 1023px is not an issue)

```
<div class="row">
    <div class="small-12 medium-9 large-8 columns">Content</div>
    <div class="small-12 medium-3 large-4 columns">Sidebar</div>
</div>
```

**What did you expect to happen?**
When resized to 640px, I expect to see *Content* and *Sidebar* in two different lines. (like 5.X)
When resized to 1024px, I expect *Content* to *Sidebar* ratio to be 9:3 (like 5.X)

**What happened instead?**
When resized to 640px, *Content* and *Sidebar* are on same line and grid ratio is 9:3
When resized to 1024px, *Content* and *Sidebar* are on same line and grid ratio is 8:4

**Comment by aibrean** [comment]
You can change them.

```scss
$breakpoints: (
  small: 0px,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
```

**Comment by srikanth912** [comment]
Yes we can change (and I did that in my project) but wanted to make sure it is intentional as it's not mentioned in the docs (or may be I missed).  

I'm happy for this to be closed if it is intentional.

**Comment by aibrean** [comment]
Yes it's intentional...
http://foundation.zurb.com/sites/docs/media-queries.html

"Foundation for Sites has three core breakpoint ranges.

- Small: any screen.
- Medium: any screen 640 pixels or wider.
- Large: any screen 1024 pixels or wider."

**Comment by gakimball** [comment]
Is is indeed intentional. The new breakpoint model makes it really easy to add, remove, change, and rename breakpoints.
