### ISSUE TITLE
[Accordion Menu] Animation loop

### ISSUE THREAD

**Issue by Vincent-P** [zurb/foundation-sites#7413]
**How can we reproduce this bug?**

1. Just take an accordion menu
2. Double click on a link
3. And the open/close animation loop

**What did you expect to happen?**

Just a open/close animation

**What happened instead?**

The menu keeps opening / closing.

**Test case**
http://codepen.io/anon/pen/gPOjYz
or just the one in the docs (http://foundation.zurb.com/sites/docs/accordion-menu.html#)

**Comment by TvrtkoM** [comment]
the commit seem to fix the problem problem partially. Specific toggle tempo can still be achieved to keep animation loop going and it also delays the animation start a bit.
Setting the time-out time to 300 seems to prevent it completely but the delay seem to long.

**Comment by TvrtkoM** [comment]
seems like just checking for animation state on toggle trigger eliminates the repeating loop :D
