### ISSUE TITLE
[rtl-support] topbar direction doesn't changes

### ISSUE THREAD

**Issue by farzadfaal** [zurb/foundation-sites#7417]
I have a custom _setting.scss file in my projects folder and I'm using compass for my project. When I change the $global-text-direction to 'rtl' every thing works fine with changing the direction except the direction of the top-bar menu which I change manually. Is there anyway to make doing this autonomous as well?

**Comment by zurbrandon** [comment]
For RTL we never change anything that is specified as being right or left to then mean the opposite. So if a menu is called left menu it will always float left. We found it can get super confusing to alter that behavior for specific elements. 

I'll close this for now, but feel free to reopen if you want to chat about it more. Thanks!
