### ISSUE TITLE
[Accordion] When used in Meteor, doesn't work when used through a {{#each}} loop

### ISSUE THREAD

**Issue by cvax** [zurb/foundation-sites#7420]
On Foundation 6.0.5, the sample accordion code works in Meteor as long as it is static content. However, the moment you try to wrap that code inside a `{{#each}}` loop, the accordion is incapable of expanding anymore. The issue seems to be with the `<div class="accordion-content" role="tabpanel">` item. Any ideas?

Here is the sample accordion that works fine.
``` javascript
<template name="questions">
    <ul class="accordion" data-accordion role="tablist" data-allow-all-closed="true">
        <li class="accordion-item">
            <!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
            <a href="#panel1d" role="tab" class="accordion-title" id="panel1d-heading" aria-controls="panel1d">Accordion 1</a>
            <!-- The content pane needs an ID that matches the above href, role="tabpanel", data-tab-content, and aria-labelledby. -->
            <div id="panel1d" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="panel1d-heading">
                Panel 1. Lorem ipsum dolor
            </div>
        </li>
    </ul>
</template>
```
Here it is inside a `{{#each}}`. We are only creating the `<li>`s by looping through our database. I'm not even populating the accordion with dynamic data, but it already fails to expand. The only difference is the use of `{{#each}}`.
``` javascript
<template name="questions">
	<ul class="accordion" data-accordion role="tablist" data-allow-all-closed="true">
		{{#each questions}}
			<li class="accordion-item">
				<!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
				<a href="#panel1d" role="tab" class="accordion-title" id="panel1d-heading" aria-controls="panel1d">Accordion 1</a>
				<!-- The content pane needs an ID that matches the above href, role="tabpanel", data-tab-content, and aria-labelledby. -->
				<div id="panel1d" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="panel1d-heading">
					Panel 1. Lorem ipsum dolor
				</div>
			</li>
		{{/each}}
	</ul>
</template>
```
Any help would be appreciated. Thanks a lot.

**Comment by zurbchris** [comment]
If you aren't changing the id's of the content div's and the href attributes of the anchors appropriately, like in your example, that could cause problems.

**Comment by cvax** [comment]
Hi Chris,

In my original example before I stripped it down I had unique ids and divs.
It didn't seem to make a difference. Hm.

**Comment by zurbchris** [comment]
are you calling $(document).foundation() after?

**Comment by cvax** [comment]
Hi Chris,

I am using the Foundations plugins API technique described in the Javascript guide here: https://atmospherejs.com/zurb/foundation-sites

The `<ul>` with `id="test"` doesn't expand while `id="test2"` does.
``` html
<template name="questions">
	<ul id="test" class="accordion" data-accordion role="tablist" data-allow-all-closed="true">
		{{#each questions}}
			<li class="accordion-item">
				<!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
				<a href="#panel-{{i}}" role="tab" class="accordion-title" id="panel-{{i}}-heading" aria-controls="panel-{{i}}">Accordion 1</a>
				<!-- The content pane needs an ID that matches the above href, role="tabpanel", data-tab-content, and aria-labelledby. -->
				<div id="panel-{{i}}" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="panel-{{i}}-heading">
					Panel 1. Lorem ipsum dolor
				</div>
			</li>
		{{/each}}
	</ul>

	<ul id="test2" class="accordion" data-accordion role="tablist" data-allow-all-closed="true">
	  <li class="accordion-item">
	    <!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
	    <a href="#panel2d" role="tab" class="accordion-title" id="panel1d-heading" aria-controls="panel2d">Accordion 1</a>
	    <!-- The content pane needs an ID that matches the above href, role="tabpanel", data-tab-content, and aria-labelledby. -->
	    <div id="panel2d" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="panel2d-heading">
	      Panel 1. Lorem ipsum dolor
	    </div>
	  </li>
	  <li class="accordion-item">
	    <!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
	    <a href="#panel2d" role="tab" class="accordion-title" id="panel2d-heading" aria-controls="panel2d">Accordion 2</a>
	    <!-- The content pane needs an ID that matches the above href, role="tabpanel", data-tab-content, and aria-labelledby. -->
	    <div id="panel2d" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="panel2d-heading">
	      "Panel 2. Lorem ipsum dolor"
	    </div>
	  </li>
	</ul>
</template>
```

Here is the Foundations plugin API approach I am using
``` javascript
Template.questions.onRendered(function(){
	this.layoutInstance = new Foundation.Accordion($('#test'));
	this.layoutInstance2 = new Foundation.Accordion($('#test2'));
});

Template.questions.onDestroyed(function() {
	let accordion = this.layoutInstance;
	if (accordion) {
		accordion.destroy();
	}

	let accordion2 = this.layoutInstance2;
	if (accordion2) {
		accordion2.destroy();
	}
});
```

However, following your suggestion, if I went back to the catch-all `$(document).foundation()` both accordions do expand nicely. Hmm. Not sure why the plugin API approach doesn't work

**Comment by juliancwirko** [comment]
Using `$(document).foundation()` with Meteor isn't a good idea :/ This is a global initialization of everything and there could be many calls in many part of the app (in many templates). It could be very problematic because every plugin behaves differently. I encounter many problems when using `$(document).foundation()` in Meteor app. There are some overwrite problems with this approach. Many elements are not destroyed, many DOM nodes are leave in the DOM. This is realy messy with Meteor.

In your case it wont work because you probably try to initialize the plugin before all the items from `{{#each}}` are in the DOM. Your template is rendered, but your `each` loop isn't finished. This is how it works in Meteor. You should initialize the Foundation plugin when you are sure that all the items are in the dom. This is always tricky with any jQuery plugin and Meteor not only Foundation. This is because the jQuery plugins and Meteor are working in a little different way.

In this case you could check if you have rendered the last element from `each` loop by counting items checking if the item index is equal the count of the items and then setting a [ReactiveVar](http://docs.meteor.com/#/full/reactivevar_pkg). Then in the `questions` template you can check if the ReactiveVar is set and only then initialize the Foundation plugin (the way you are doing it right now). Altought this is quite problematic. You can also try to play with [Blaze API] (http://docs.meteor.com/#/full/blaze) for some different approaches you could think.

**Comment by cvax** [comment]
@juliancwirko Thanks so much for the detailed analysis. The issue was exactly as you described and I have solved it working off of your suggestions.

Here is the solution I used:

**Blaze**
``` html
<template name="questions">
	<ul id="test" class="accordion" data-accordion role="tablist" data-allow-all-closed="true">
		{{#each questions}}
			<li class="accordion-item">
				<!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
				<a href="#panel-{{i}}" role="tab" class="accordion-title" id="panel-{{i}}-heading" aria-controls="panel-{{i}}">{{question}}</a>
				<!-- The content pane needs an ID that matches the above href, role="tabpanel", data-tab-content, and aria-labelledby. -->
				<div id="panel-{{i}}" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="panel-{{i}}-heading">
					{{answer}}
				</div>
			</li>
		{{/each}}
	</ul>
	{{#if accordionDataLoaded}}
		{{initializeAccordion '#test'}}
	{{/if}}
</template>
```
**Javascript**
``` javascript
Template.registerHelper('accordionDataLoaded', function() {
	return Session.get('accordionDataLoaded');
});

Template.questions.helpers({
	questions: function() {
		return Questions.find({}).map(function(question, index) {
			// Session.set('counter', Session.get('counter') + 1);
			question.i = index;
			if (index === Questions.find().fetch().length - 1) {
				Session.set('accordionDataLoaded', true);
			}
			return question;
		});
	},

	initializeAccordion: function(accordionId) {
		this.layoutInstance = new Foundation.Accordion($(accordionId));
	},
});

Template.questions.onDestroyed(function() {
	let accordion = this.layoutInstance;
	if (accordion) {
		accordion.destroy();
	}
});
```
