### ISSUE TITLE
Standard grid nested inside block grid broken?

### ISSUE THREAD

**Issue by designchief** [zurb/foundation-sites#7421]
Just using the standard block grid sample from the docs (see below). 

If I want to add a standard nested .row within the block grid column the .columns pull in their widths from:

```css
.large-up-4 .column, .large-up-4 .columns {
    width: 25%;
    float: left; }
```

and as such, breaks the layout. The buttons should be small-6 size and they are expanded.

```html
<div class="row small-up-1 medium-up-2 large-up-4">
  <div class="column">
    <img src="//placehold.it/300x300" class="thumbnail" alt="">
	<div class="row">
				<div class="small-6 columns"> <a class="button expanded">Button</a> </div>
				<div class="small-6 columns"> <a class="button expanded">Button</a> </div>
			</div>
  </div>
  <div class="column">
    <img src="//placehold.it/300x300" class="thumbnail" alt="">
  </div>
  <div class="column">
    <img src="//placehold.it/300x300" class="thumbnail" alt="">
  </div>
  <div class="column">
    <img src="//placehold.it/300x300" class="thumbnail" alt="">
  </div>
  <div class="column">
    <img src="//placehold.it/300x300" class="thumbnail" alt="">
  </div>
  <div class="column">
    <img src="//placehold.it/300x300" class="thumbnail" alt="">
  </div>
</div>`
```

Is this a bug or expected behaviour?

there seems to be confusion between the .column class used in the block grids and the standard grid.

**Comment by gakimball** [comment]
Not seeing this behavior in Foundation 6.0.5. The block grid classes use the `>` selector, so the column width CSS can't leak into nested grids.

Here's what I see when I paste your code sample. The nested columns have `width: 50%;` like they should. If this doesn't look right, let me know what you expected it to look like, and I can help you further. Thanks! :)

![image](https://cloud.githubusercontent.com/assets/1142001/11664838/c9e97d8e-9d98-11e5-9f65-bbfc1685f969.png)

**Comment by designchief** [comment]
Hi Geoff, when I update to 6.0.5 the grid was working as expected. Thanks
