### ISSUE TITLE
[Abide] Password type fields couldn't passed the required rule

### ISSUE THREAD

**Issue by jurerick** [zurb/foundation-sites#7424]
**How can we reproduce this bug?**

1. Use a type "password" into input fields with required attribute <input type="password" name="password"  required />
2. Put a value to the password input
3. Submit the form. It's always throws an error and form can't pass

**What did you expect to happen?**
It should pass the validation since It's already has a value

**What happened instead?**
Did not pass the form validation

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by briantan888** [comment]
#7407 fixed this and many other abide issues.

**Comment by zurbchris** [comment]
Should be fixed with #7590, please comment and submit pr's to the `abide` branch until 6.1 release.
