### ISSUE TITLE
[Dropdown] Allow for multiple anchor toggles.

### ISSUE THREAD

**Issue by tjhiggins** [zurb/foundation-sites#7433]
v5 allowed you to have multiple anchors for the same dropdown. Simplifies the code to only allow one, but is much more efficient to reuse a dropdown with knockoutjs etc.

**Comment by zurbchris** [comment]
How would you see that implemented in 6? A single dropdown pane that will attach to whichever anchor point was clicked? Then which one does it anchor to for a programmatic open? It also makes `aria` attributes much more difficult to manage.

**Comment by tjhiggins** [comment]
@zurbchris 
<b>A single dropdown pane that will attach to whichever anchor point was clicked?</b>
Yes

<b>Then which one does it anchor to for a programmatic open?</b>
Default to first anchor, but open could optionally take an anchor?

<b>It also makes aria attributes much more difficult to manage.</b>
True, but our use case cannot afford to recreate essentially the same dropdown multiple times. The cleanup logic could be kept generic for all anchors. You would probably need to have a this.$anchors and this.$active_anchor. I was working on a potential pr, but decided to wait until https://github.com/zurb/foundation-sites/pull/7353 was resolved. 

It might be too heavy handed, but we currently utilize that functionality with v5.

**Comment by andycochran** [comment]
@tjhiggins Now that #7353 is closed, does that help with your PR? I'm going to close this for now. Please reopen if you'd like to submit that PR.
