### ISSUE TITLE
NPM Run Build Breaks Top-bar Dropdown Menu

### ISSUE THREAD

**Issue by bahart** [zurb/foundation-sites#7435]
Zurbians - take a bow. ZF 6.x is a major milestone! Full unit testing (SCSS, build, minify, etc.) over a week: incredible performance, perfection itself!

Here are two anomalies (CLI 2.14.7 / ZF-S 6.05) encountered:

(1) [NPM Start] {ROOT} command generates html code with: backslash and forward slash
[dot][dot][backslash] [dot][dot][forward slash]
Example: a href="[dot][dot][backslash] [dot][dot][forward slash]solutions/visual/some.html">Media
same for all use cases: <img src="[dot][dot][backslash] [dot][dot][forward slash]
Top Bar Nav and Image source files render OK in browser (Chrome, FF Win) 

(2)  [NPM run-script Build] -> Top Bar Menu breaks:
generates html code as above 
Top Bar Nav - falls apart
image sources: render OK, even with  [dot][dot][backslash] [dot][dot][forward slash]

Barbara
B-ZF / ZF-Tzero

**Comment by zurbchris** [comment]
Thanks! Unfortunately, your markdown didn't get rendered correctly, so I'm not quite certain what is going on.

**Comment by bahart** [comment]
Chris: I'll fix the rendering in forum issue later. Here is the anomaly. 

When using {{Root}} on Top Bar Dropdown Nav and image source, the generated code for file location contains: ..Backslash..ForwardSlash when directory depth is two or more levels...

A Build results in Top Bar Nav failing to render (falls apart as text).

Are you experiencing same result on: Generated & Build
Presume this issue (backslash and forwardslash) is throwing the Build process for Top Bar Nav.
Image source renders with the slash going both ways for depths of 2 or more.

Barbara

**Comment by bahart** [comment]
Chris: Here is a sample  from my src/partials/navigation.html (sorry for the length)
while working locally (npm start) menu renders properly
after I do npm run build, the menu fails to render properly (renders horizontally across the screen no submenus)

    <div class="top-bar">
      <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <a>Digital Solutions</a>
        <ul class="menu">
        <li class="nlabel">Digital Deli Solutions &there4; B4B</li>
          <li>
            <a href="{{root}}solutions/window/index.html" >smART Window Into Your World&trade;</a>
            <ul class='menu'>
            <li class="nlabel">Next Generation Always On Strategies</li>
             <li><a href="{{root}}solutions/window/nxgen.html">Next&ndash;Gen On Demand Interactive Engagement</a></li>
              <li><a href="{{root}}solutions/window/mmap.html">Multimedia Marketing, Advertising &amp; Promotion</a></li>
    <li>        
            <a href="{{root}}solutions/window/enkt.html">Educational Nourishment / Knowledge Transfer</a>        
            </li>        

            <li>        
            <a href="{{root}}solutions/window/bse.html">Branding Strategy and Execution</a>        
            </li>
            <li>        
            <a href="{{root}}solutions/window/bric.html">Brand Re&ndash;Imagining Campaigns</a>        
            </li>        
            <li>        
            <a href="{{root}}solutions/window/tba.html">Tourism and Business Attraction</a>        
            </li>
            </ul>
          </li>      
          <li>
            <a href="{{root}}solutions/visual/index.html">smART Media Visual Solutions&trade;</a>
            <ul class='menu'>
            <li class="nlabel">Visual & Spatial Themes &there4; M2M</li>
            <li>        
            <a href="{{root}}solutions/visual/svs_interior.html">smART Interior Fine Art&trade;</a>        
            </li>                                                            
            <li>        
            <a href="{{root}}solutions/visual/svs_event-exhibit.html">smART Event / Exhibit Media&trade;</a>        
            </li>                             
                <li>            
                <a href="{{root}}solutions/visual/svs_ad-mkt.html">smART Advertising / Marketing Media&trade;</a>        
            </li>
                <li>            
                <a href="{{root}}solutions/visual/svs_public.html">smART Media for Public Spaces&trade;</a>        
            </li>
            </ul>
          </li>
        </ul>
      <li>
        <a>Digital Deli Studios&trade;</a>
        <ul class="menu">
        <li class="nlabel">Media Content Creation</li>
          <li>
        <a href="{{root}}studios/mm-lab.html">Mixed Media Lab</a>
        <ul class='menu'>
        <li>                                              
          <a href="{{root}}studios/mm-lab.html" >Professional Digital Image Capture</a>                                                  
        </li>                                                                    
        <li>                                                  
          <a href="{{root}}studios/mm-lab.html" >Advanced Image Sensor Rendering</a>                                                  
        </li>
            <li>                                              
          <a href="{{root}}studios/mm-lab.html" >Multimedia Design and Development</a>                                                  
        </li>                                                                             
        <li>                                                  
       </ul>
      </li>    
        </ul>
      </li>
      <li>
      <a>Digital Deli Pipeline</a>
        <ul class="menu">
    <li class="nlabel">A Pure Digital Pipeline</li>    
          <li>
            <a href="{{root}}pipeline/index.html">Publishing</a>
            <ul class='menu'>
                <li class="nlabel">Edu-tainment Multimedia | Cinema / Video</li>                 
            <li>                 
            <a href="{{root}}pipeline/index.html">Digital Deli Archive&trade;</a>                 
            </li>                                                              
            <li>                 
            <a href="{{root}}pipeline/index.html">The National Treasure Series&trade;</a>                 
            </li>                                    
            <li>                 
            <a href="{{root}}pipeline/index.html">smART Media for the Classroom&trade;</a>                 
            </li>
            <li class="divider">                 
            </li>                                            
                <li class="nlabel">Digital Deli Photographic Fine Art&trade;</li>                 
            <li>                 
            <a href="{{root}}pipeline/index.html">The National Treasure Series Gallery&trade;</a>                 
            </li>                                    
            <li>                 
            <a href="{{root}}pipeline/index.html">Digital Deli Fine Art&trade; | Collections</a>                 
            </li>
            <li>                 
            <a href="{{root}}pipeline/index.html">smART Health Therapeutic Art&trade;</a>                 
            </li>
            <li>                 
            <a href="{{root}}pipeline/index.html">Digital Deli Archive&trade;</a>                 
            </li>         
            </ul>
          </li>
          </li>      
        </ul>
      </li>
     </ul>
      </li>
      </div>
    </div>

**Comment by gakimball** [comment]
I think I see the issue. It has to do with Node's use of `\` to separate paths, versus a web browser's use of `/`. We should be able to fix that shortly.

**Comment by bahart** [comment]
Here are the results after updating: processRoot.js and loadHelpers.js
NPM Start> fixes the backslash in generated code: OK
NPM run Build>  top-bar dropdown menu still falls apart (renders horizontally across the screen no submenus), even though backslash issue fixed: Build Breaks Menu

Let me know if you need further details. Thank you.
--Barbara--

**Comment by gakimball** [comment]
@bahart Can you post a full code sample for the top bar with dropdowns? You can leave the `{{root}}` stuff in there.

**Comment by bahart** [comment]
Debugging results: compared generated npm start and npm build. The html files are an exact match. The CSS files on build contain no instances of: dropdown.menu

FYI, when orbit slider is 1st item after "navigation partial" it is no longer responsive (build only).

Navigation Menu as requested below:

[navigation-sample.txt](https://github.com/zurb/foundation-sites/files/56412/navigation-sample.txt)

Barbara

**Comment by gakimball** [comment]
Hm, could be UnCSS messing up the final output. Try removing `.pipe(uncss)` from the build process in `Gulpfile.js` by commenting it out. Here's the line: <https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.js#L120>

**Comment by johnellison** [comment]
I am experiencing a similar problem with uncss stripping out the styles related to the dropdown menu in my top bar.

My markup: 

`<header class="site-header" >
  <nav class="top-bar" id="site-nav">
    <section class="top-bar-left">
      <ul class="vertical medium-horizontal menu">
        <li><a href="/" class="logo">prosper</a></li>
        <li><a href="https://blog.prosper.community">blog</a></li>
        <li><a href="/playbook.html">playbook</a></li>
      </ul>
    </section>
      <section class="top-bar-right">
        <ul class="vertical medium-horizontal menu" data-responsive-menu="drilldown medium-dropdown">
          <li class="has-submenu">
            <a href="/#about">about</a>
            <ul class="vertical submenu menu" data-submenu id="m2" >
              <li><a href="/#who-we-are">who we are</a></li>
              <li><a href="/journey.html">our journey</a></li>
            </ul>
          </li>
          <li class="has-submenu">
            <a href="/#initiatives">initiatives</a>
            <ul class="vertical submenu menu" data-submenu>
              <li><a href="/#projects">projects</a></li>
              <li><a href="/academy.html">academy</a></li>
            </ul>
          </li>
          
          <li><a href="/volunteer.html#form" class="button">join now</a></li>
          
          <li><a href=""></a></li>
        </ul>
      </section>
    </ul>
  </nav>
</header>
`

Gulpfile.js:

`
gulp.task('sass', function() {
  var uncss = $.if(isProduction, $.uncss({
    html: ['src/**/*.html'],
    ignore: [
      new RegExp('^meta\..*'),
      new RegExp('^\.is-.*')
    ]
  }));

  var minifycss = $.if(isProduction, $.minifyCss());

  return gulp.src('src/assets/scss/app.scss')
    .pipe($.sourcemaps.init())
    .pipe($.sass({
      includePaths: PATHS.sass
    })
      .on('error', $.sass.logError))
    .pipe($.autoprefixer({
      browsers: COMPATIBILITY
    }))
    .pipe(uncss)
    .pipe(minifycss)
    .pipe($.if(!isProduction, $.sourcemaps.write()))
    .pipe(gulp.dest('dist/assets/css'))
    .pipe(browser.reload({stream: true}));
});
`

When I run `foundation watch`, the dropdown menu works fine. But when I run `foundation build`, the styles relating to the dropdown are stripped out.

If I simply run `gulp sass` my app.css file is 329573 kb. If I run `foundation build` my app.css is 17765kb. Given the huge discrepancy, I assume there is more than just the dropdown related imports being stripped by uncss.

For now I am removing the `.pipe(uncss)` line of my gulp task, but it would be great to get this resolved so my foundation 6 site is as snappy as it should be!

**Comment by gakimball** [comment]
@johnellison 329573KB would be over 300MB! Are you sure the count isn't in bytes? Although that's still over 300KB, and Foundation is only 78KB uncompressed.

Removing UnCSS is our recommendation until we can fix the issues with state classes. In the mean time, make sure you're commenting out the `@import`s for any components you aren't using. That'll help keep your file size low.

**Comment by gakimball** [comment]
As this is an UnCSS issue, I'm going to close it and roll it into #7909. I just posted [a comment](https://github.com/zurb/foundation-sites/issues/7909#issuecomment-178217096) with a possible solution.
