### ISSUE TITLE
[Accordion] Content Hidden When Not Initalized

### ISSUE THREAD

**Issue by avr** [zurb/foundation-sites#7439]
**How can we reproduce this bug?**

1. If an accordion has the correct markup but doesn't include 'data-accordion', it won't be initialized and `.accordion-content` won't be displayed

**What did you expect to happen?**

1. `.accordion-content` visibility should be controlled by the plugin - not CSS

**Test case**
http://codepen.io/avr/pen/WrbOgV

**Comment by gakimball** [comment]
`.accordion-content` visibility *is* controlled by the plugin—it uses jQuery's `.slideUp()` and `.slideDown()` methods to manage visibility. This differs from the majority of other plugins in the framework, which prefer a class-based approach to managing UI state.

The fact that the accordion doesn't work without `data-accordion` isn't a bug—it's a JavaScript plugin, so we don't tend to consider use-cases that involve not using the JavaScript bits.
