### ISSUE TITLE
[Accordion] Update UX When Using `multiExpand`

### ISSUE THREAD

**Issue by avr** [zurb/foundation-sites#7440]
**How can we reproduce this bug?**

1. Set `Foundation.Accordion.defaults.multiExpand = true;`
2. Open first tab
3. Arrow down to second item
4. Arrow up to first item

**What did you expect to happen?**

1. First item should have focus and allow tabbing to related `.accordion-content` within first item.

**What happened instead?**

1. First item receives focus and triggers click event - closing the first item.

**Test case**

http://codepen.io/avr/pen/EPaXdW (the `keyboard` component isn't working in Codepen)

**Comment by gakimball** [comment]
Fixed via 4060b578ed5d99a2862f0f276c06038da19c9fd1. [Here's a test case.](https://github.com/zurb/foundation-sites/blob/develop/test/visual/accordion/focus.html)
