### ISSUE TITLE
[Accordion] Accordion can only use <ul> and <li>

### ISSUE THREAD

**Issue by oolongcha** [zurb/foundation-sites#7441]
**How can we reproduce this bug?**

Tried to make an accordion with dl and dd. Would not work until I changed it all to ul and li

**What did you expect to happen?**

I expected the accordion to work with dl and dd, as stated in the docs, "we use ul, but you can use any element you want"

http://foundation.zurb.com/sites/docs/accordion.html

**What happened instead?**

Accordion would only display first panel and none of the others.

**Comment by Knight-Yoshi** [comment]
If you're using Foundation 6 the accordion component is apart of the general menu component which uses unordered lists.
http://foundation.zurb.com/sites/docs/accordion-menu.html

**Comment by oolongcha** [comment]
Ah, right, I should clarify, this is not a bug for the accordion menu. Thanks for pointing that out.

**Comment by Knight-Yoshi** [comment]
Yeah the accordion doesn't seem to work with anything other than lists

**Comment by ocularrhythm** [comment]
I created a pull request for this issue. Line 58 of `foundation.accordion.js` was using a general `li` selector, instead of the `accordion-item` class. I changed it and tested it with nested divs and it worked correctly.
