### ISSUE TITLE
Top-Bar Link Color is White

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites#7443]
By default, $topbar-link-color is white - which is really hard to see on the topbar which is also a light color. 

![screen shot 2015-12-07 at 9 08 39 pm](https://cloud.githubusercontent.com/assets/6110968/11647688/4860a32a-9d28-11e5-8b98-d7e7ee54aa39.png)

**Comment by twd3** [comment]
Yeah, that was added in 6.0.5 for some reason. It comes from:
```.top-bar li > a, .top-bar ul li > a {
      color: #fff; }```

**Comment by gakimball** [comment]
Yep, this has been fixed but hasn't landed in a release yet. We'll likely do 6.0.6 by the end of the week. 9bf0552ef5f737c1e209e9efd5c2e76b05afbdbe
