### ISSUE TITLE
[Accordion] Accordion throws JavaScript error on opening

### ISSUE THREAD

**Issue by TobiasMalikowski** [zurb/foundation-sites#7445]
**Description:**
I'm using the minified version of Foundation 6.0.5. When I click an Accordion panel it opens but the following error is thrown in the console: "Uncaught TypeError: this.rules.split is not a function". If I use the non-minified version no error is thrown. However the Accordion itself is working fine.

**How can we reproduce this bug?**
Include the minified version of Foundation 6.0.5. Insert the default Accordion code from the docs (http://foundation.zurb.com/sites/docs/accordion.html) open an Accordion panel and watch the console.

**Comment by ocularrhythm** [comment]
I was unable to reproduce this bug. Tried using the minified version 6.0.4 as well as 6.0.5 but received no console errors.

**Comment by TobiasMalikowski** [comment]
If no one else can reproduce this bug it's possible that the bug is caused through concatenating and minification. I'm using gulp-concat and gulp-uglify to grab all non minified JS files and concat and minify them into one single file.

**Comment by ocularrhythm** [comment]
Are you using the default gulp tasks that are created with the ZURB Template using the Foundation CLI, or are these tasks wrote yourself?

**Comment by TobiasMalikowski** [comment]
I've used the gulp tasks from the JointsWP package (Foundation 6 template for WordPress) but I modified them for my own needs. So you could say that I've written them by myself.

Does it help, if I post the task here?

**Comment by ocularrhythm** [comment]
I suspect the issue is not with Foundation source. Since I can't reproduce it, perhaps you should attempt to recreate the bug using a fresh JointsWP copy. If it compiles and throws no error using Accordion, you'll have isolated it to your Gulp task at the very least.

**Comment by TobiasMalikowski** [comment]
Okay I found out, that the following JS file creates the error: 
foundation-sites/js/foundation.**responsiveMenu.js**

If I exclude the named file from the gulp task no errors are thrown.

Since you can't reproduce the error. Do I have to include the responsiveMenu.js in any particular order?

**Comment by ocularrhythm** [comment]
The script order (as far as plugins are concerned) should compile and work correctly in the default alphabetical order. The `foundation.core.js` and `foundation.util.*.js` will need to come before the plugins, which looks like JointsWP does in their gulpfile. I'm somewhat at a loss as to what to have you try next, perhaps someone from Zurb can help you at some point. 

Did you attempt at compiling a fresh copy and reproducing the error? Is that what had you conclude it was the `reponsiveMenu.js`?

**Comment by TobiasMalikowski** [comment]
You can have a look at my gulpfile.js (I uploaded it 2 comments before). I tried fresh copies because i updated Foundation. If I exclude (comment out) responsiveMenu.js in my gulpfile.js everything is fine, no errors etc. So I'm wondering if the concatenating order is correct.

**Comment by ocularrhythm** [comment]
I notice you combined the `site-js` and `foundation-js` tasks and have included a `jquery` and `whatinput` to the top of the list. In your `assets/functions/enqueue-scripts.php` are you still enqueuing those scripts as well? (whatinput, foundation, site-js) WordPress loads jQuery by default, sometimes if you load it twice, it will cause some really strange behaviors. The Foundation enqueue states jQuery as a dependency. This is assuming you haven't altered that file though.

**Comment by TobiasMalikowski** [comment]
Thanks for your help. It's true I combined the two tasks, because JointWP includes 3 or 4 JS files (Foundation, What Input, jQuery, Custom JS). So I wanted to save HTTP requests and combined them.

JointsWP uses "wp_deregister_script('jquery');" to make sure jQuery doesn't get loaded twice. Also I'm only loading one script (scripts.min.js) in my enqueue-scripts.php.

I still think it has to do with the ordering, will look for this.

Btw. how do u markup files with that Markup language? Looked at the docs but couldn't find anything. Want to make my comments better to read ;) Thanks again.

**Comment by ocularrhythm** [comment]
No problem, I'm glad you are on top of it all. I'm using backticks to style inline-code, it's just standard markdown but the Github docs are [here](https://guides.github.com/features/mastering-markdown/)

**Comment by zurbchris** [comment]
was this issue resolved or do you still need help?

**Comment by TobiasMalikowski** [comment]
Hi Zurbchris,

the issue is still open. As you can see in the comments before I now know which file produces the error but I don't know why or how I can solve this. I think that comes from the order of the file but couldn't solve it. Any help is appreciated.

**Comment by zurbrandon** [comment]
@TobiasMalikowski does this seem like an error with hoe WPjoints is importing and concating or with how Foundation files are working. If it seems like a WPJoints issue you may want to open an issue with Jeremy.

**Comment by TobiasMalikowski** [comment]
Hi there, just wanted to let you know, that this issue was resolved by updating to the current release (6.1.2).

**Comment by julian-rare** [comment]
nope, still broken in 6.3.0
