### ISSUE TITLE
[Slider] Page Edit

### ISSUE THREAD

**Issue by YuvalKaplan** [zurb/foundation-sites#7447]
1. When attempting to Edit the Page I could only edit the top half of it.
2. In the page I wanted to correct the "Javascript Refrence: section:
    a. In the http://foundation.zurb.com/sites/docs/slider.html#js-class 
          "Creates a new instance of a drilldown menu." -> "Creates a new instance of a Slider."
    b. http://foundation.zurb.com/sites/docs/slider.html#js-events 
         The name of the event should be "moved.zf.slider" - lower case 's'

**Comment by gakimball** [comment]
The "JavaScript Reference" section is generated through JSDoc comments. To change the text, change it in `js/foundation.drilldownMenu.js`.
