### ISSUE TITLE
F6 button toggle with dropdown-pane in top-bar: pane misalignment? + incorrect form fields width

### ISSUE THREAD

**Issue by nska02** [zurb/foundation-sites#7451]
Hi all,

I'm trying to achieve something (I would assume "pretty simple") but can't figure out why it's not working: toggle button with bottom-right alignment dropdown-pane in top-bar-right (F6). 

Facing two issues: 
1. **pane "misalignment"** when toggle button is located at top-bar extreme right side (ie. automatic pane left positioning overlay on top-bar when I would expect a bottom-right alignment, as it is done in Bootstrap) 
2. **form input fields width incorrect** (ie. fields are overlaying each other and changing class medium-6 to medium-4 for instance has no effect on their width)

Ultimate goal is a simple login button toggle which displays a dropdown-pane with username, password fields and submit button. Nothing complex.
As a simplified approach, I integrated (copy/pasted) here below the standard top-bar and button dropdown-pane code from the docs.

```html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Site Title</li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li>
        <button class="button" type="button" data-toggle="example-dropdown">Toggle Dropdown</button>
        <div class="dropdown-pane" id="example-dropdown" data-dropdown data-auto-focus="true">
          Example form in a dropdown.
          <form>
            <div class="row">
              <div class="medium-6 columns">
                <label>Name
                  <input type="text" placeholder="Kirk, James T.">
                </label>
              </div>
              <div class="medium-6 columns">
                <label>Rank
                  <input type="text" placeholder="Captain">
                </label>
              </div>
            </div>
          </form>
        </div>
      </li>
    </ul>
  </div>
</div>
```

Maybe I'm doing it wrong?
I apologise in advance if there is somewhere an ongoing similar raised issue but after few hours browsing, I couldn't find anything explicitly related AND fixed.
Thanks.

**Comment by gakimball** [comment]
Issue #1 I've seen in my own code, makes sense. Dropdown panes should probably only flip axis, not origin point, when doing collision detection. @zurbchris thoughts?

So if a pane is anchored to the bottom left, a collision would cause it to flip to the bottom right. At the moment, the anchor point changes to a different side of the button.

Issue #2 is happening because top bar adds a 200px width to `<input>` elements, for use with search bars and such. That style is cascading down to an input that you want to be fluid. Here's a temporary fix:

```css
.dropdown-pane input {
  width: 100%;
}
```

**Comment by sg1303** [comment]
+1 on dropdown pane alignment. Any workaround to prevent the dropdown changing its anchor position?

**Comment by gakimball** [comment]
Alright, for the first issue (dropdown pane alignment on flip), we'll close in favor of #7392, which is an open feature request.

As for the first issue (inputs inside a top bar too wide), the CSS is being changed from `width` to `max-width`. That way it can restrain super long inputs by default, which is what we wanted, without stretching out short inputs. c8eedec2aafcef7ba7ada8eaf4ed5af6198a38d3
