### ISSUE TITLE
*-uncollapse causes double padding

### ISSUE THREAD

**Issue by tamcy** [zurb/foundation-sites#7452]
Please refer to this example:
http://codepen.io/anon/pen/rxaZvp

If I understand correctly, the `*-collapse` class in the grid (and its corresponding mixin) removes the left and right gutter/padding of a column, while `*-uncollapse` class restores it. So for the code above, I expect to see:
(1) No gutter in small screen size.
(2) The gutter should be restored in medium and large screen size, i.e. it should align with the second row without any `*-collapse` or `*-uncollapse` class. 

However, in reality, (2) behaves differently than what I expected. It looks like double padding is added to the `medium-uncollapse` columns, which makes it narrower than the row below it.

The same markup with foundation 5.5.0 seems to behavior more properly:
http://codepen.io/anon/pen/jWEvxV

As I am completely new to foundation I'm not sure whether this change is intended or not, but the doc leads me to think the new behavior isn't that correct. Thanks.

**Comment by zurbrandon** [comment]
This has been fixed by a PR, so i'll close this out. Thanks!
