### ISSUE TITLE
[Off-canvas] reveal-for-x double up on browser resize

### ISSUE THREAD

**Issue by EHackettTriCore** [zurb/foundation-sites#7455]
**How can we reproduce this bug?**

1. Create an "off-canvas position-left reveal-for-medium" and add a toggle button for small-only to open it.
2. Scale browser down to small
3. Tap button to open off canvas
4. Scale window back up to medium or large and now you have a margin on the left and no off canvas panel.

**What did you expect to happen?**
 I expect when going from small to medium the offCanvas margin on the left would automatically close since it's empty.

**What happened instead?**
When I scale the browser window back up the off canvas margin on the left is still visible instead of being removed.

**Test case**
Adding demo gif
![offcanvas](https://cloud.githubusercontent.com/assets/16137890/11666253/96408178-9db9-11e5-8030-fe3f14db46b0.gif)

HTML Code:

```
<div class="title-bar">
  <div class="title-bar-left">
    <button class="menu-icon show-for-small-only" type="button" data-open="offCanvas"></button>
    <span class="title-bar-title">Foundation</span>
  </div>
</div>

<div class="off-canvas-wrapper">
  <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
    <div class="off-canvas position-left reveal-for-medium" id="offCanvas" data-off-canvas>
      left
    </div>
    <div class="off-canvas-content" data-off-canvas-content>
      content
    </div>
  </div>
</div>
```

**Comment by gakimball** [comment]
I think the problem stems from the off-canvas staying open when a larger breakpoint is reached. If possible, we need to detect when that threshold is crossed and then automatically close the menu. @zurbchris thoughts?
