### ISSUE TITLE
[Reveal] Cannot change the animation speed of Reveal open/close

### ISSUE THREAD

**Issue by chuntley** [zurb/foundation-sites#7458]
We are having a hard time figuring out how to change the animation speed of the Reveal open/close events. Added a "fast" class to the element does not change the speed, and we cannot find documentation on it as well.

I looked through the source and noticed that in the `foundation.util.motion.js` file, line 57, the duration options are commented out:

```javascript
var Motion = {
  animateIn: function(element, animation, /*duration,*/ cb) {
    animate(true, element, animation, cb);
  },

  animateOut: function(element, animation, /*duration,*/ cb) {
    animate(false, element, animation, cb);
  }
};
```

Is this a planned feature for the future?

**Comment by gakimball** [comment]
The speed classes (`.slow` and `.fast`) work, which means you can also apply `transition-duration` to a specific modal and change the speed.

*However*, the modal overlay doesn't get the speed change—it transitions at the standard speed. Since there's just one overlay that every modal uses, in theory you'd need the overlay to read the transition speed off the incoming modal, so the speed could be mimicked. @zurbchris thoughts?

**Comment by zurbchris** [comment]
Seems pretty simple. I could run a check in the overlay creation fn to also add speed classes, if present. Wouldn't have any effect if not included.

**Comment by gakimball** [comment]
@zurbchris I'd prefer not to hardcode a check for "fast" and "slow", because it's always possible the `transition-duration` comes from another class.

**Comment by zurbchris** [comment]
Sense you are making, easier you are not...

**Comment by gakimball** [comment]
@zurbchris ;) <3

**Comment by ruudvanham** [comment]
Currently i've the same problem.

I've added the class .fast and changed the duration in css. This works for the modal but not for the overlay. Also it seems the modal is waiting for the overlay animation, it starts mid way it seems.
Possible solution?

**Comment by mattems** [comment]
:100:  @ruudvanham definitely need to be able to start the reveal overlay and the modal at the same time.

**Comment by gakimball** [comment]
Changed the open/close methods so the overlay and the modal start their animations at the same time: 1c9a12dc9711b85f566d603defe190e62cf416c1

As for syncing up the animation speeds, still working that out.

**Comment by arielnoname** [comment]
I think this is the right place to put this:

I managed to change the duration of the animation of the modal window using the helper classes (fast, slow) and even further in **motion-ui/src/_settings.scss** , but still I would like to the **reveal-overlay** to be faster, goes to black a little slow for my taste.

Maybe it could be some **data-reveal-overlay-speed** attr?

Thanks for the code

**Comment by Larzans** [comment]
+1 I absolutely agree that there should be an option for that.
As a workaround one can use the following code to change for example the fade-in speed:
```
    .reveal-overlay.fade-in {
      transition-duration: 0.25s;
    }
```

**Comment by arielnoname** [comment]
Whoa! Thanks @Larzans ! That worked like a charm

**Comment by Larzans** [comment]
your very welcome :)

**Comment by HanlonCreative** [comment]
Also for me when I use the 'fast' class, on mobile the reveal modal is off to the side, basically it breaks the responsiveness of the site as you have to swipe right to see the rest of the modal.
![img-reveal-fast-class-issue](https://cloud.githubusercontent.com/assets/14078585/13370548/19743932-dcd9-11e5-9f78-baf889fce941.jpg)


Also to the comment from Larzans, if you are using a different animation e.g. slide-in-up then that trick does not work, but you can speed up the overlay itself to .25s, anything lower gets/glitchy or breaks the animation:

`.reveal-overlay {transition-duration: 0.25s;}`

**Comment by andycochran** [comment]
@kball You wanna take a stab at implementing @Larzans' workaround?

**Comment by kball** [comment]
@andycochran the workaround isn't configurable, and I don't see a straightforward way to implement the general case alluded to by @gakimball but I can make sure 'slow' and 'fast' get applied to the overlay as well as the modal, and that should address most cases
