### ISSUE TITLE
[Flex Grid] ISSUE NAME HERE

### ISSUE THREAD

**Issue by juliopalro** [zurb/foundation-sites#7460]
**How can we reproduce this bug?**

1. Step one
.row .row,
  .column-row .row {
    margin-left: -0.9375rem;
    margin-right: -0.9375rem; }
2. Step two
In google chrome it creates problems the margins of the sides give problems to view devices.

**What did you expect to happen?**
Delete or change the line so that it does not generate the error and you can see perfectly on mobile devices or small screen.

**What happened instead?**

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by gakimball** [comment]
That CSS is necessary to properly nest grids. Can you post a code sample that illustrates the error?

**Comment by zurbrandon** [comment]
Looks like we can't recreate this without a code sample, so i'll close this but feelfree to reopen it if you have any more details.
