### ISSUE TITLE
offCanvasRight very fast double click bug

### ISSUE THREAD

**Issue by mochnacki78** [zurb/foundation-sites#7462]
There is a bug with offCanvasRight. Click very fast couple of time to open it and you won't be able to close it. Works same on all browsers.

**Comment by designerno1** [comment]
+1

**Comment by zurbchris** [comment]
Is that clicking in the off-canvas area itself?

**Comment by mochnacki78** [comment]
fast double button click.
![bez nazwy-1](https://cloud.githubusercontent.com/assets/16029423/11792739/e53fbec2-a2a7-11e5-9ee6-991896187a4c.jpg)

**Comment by mochnacki78** [comment]
everything shifts 50% left and stays that way.

**Comment by designerno1** [comment]
also here
http://foundation.zurb.com/sites/docs/off-canvas.html
double click the open right menu buttonand it happens

**Comment by tbredin** [comment]
I've got the same bug on the left menu. To replicate; click a toggle to open the menu, and then click again before the animation finishes. The menu will now be trapped in the open state, with no way to close it (normally I'm clicking outside the menu with `data-close-on-click:true` to close it)

**Comment by JeremyEnglert** [comment]
Looks like this issue was fixed (https://github.com/zurb/foundation-sites/issues/9253).

Closing.
