### ISSUE TITLE
foundation-cli run errors

### ISSUE THREAD

**Issue by huphtur** [zurb/foundation-sites#7467]
Used `npm install --global foundation-cli` to install foundation cli (received 0 error messages during the install) however with `foundation new` I get the following error:
```
/Users/mappelman/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'foundation' (>= 0) among 171 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/mappelman/.rvm/gems/ruby-2.2.3:/Users/mappelman/.rvm/gems/ruby-2.2.3@global', execute `gem env` for more information
	from /Users/mappelman/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /Users/mappelman/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /Users/mappelman/.rvm/rubies/ruby-2.2.3/bin/foundation:22:in `<main>'
	from /Users/mappelman/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mappelman/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

Anyone that could give me a hand with fixing this please?

**Comment by gakimball** [comment]
Your system's PATH puts Ruby gems before Node modules, and because you have the old CLI installed, the `foundation` command is still pointing to it.

If you can live without the Foundation 5 CLI (it's only needed to set up new projects, not run existing ones), run `gem uninstall foundation` to remove it. Then the Foundation 6 CLI will work.

If you anticipate needing both in the near future, there's a way to create a command alias that points to the F6 CLI. I can break that down for you if you'd like.

**Comment by huphtur** [comment]
Running `gem uninstall foundation` did not do much, still get those same errors as above. If you could point me to some docs on how to fix that, that be great.

**Comment by rjgdesign** [comment]
I'm getting the same issue too! Ran `gem uninstall foundation` but still get the error :(

**Comment by gakimball** [comment]
Right when you uninstall something, sometimes you have to open a new command line window to get everything up to date. Also, if you're using rbenv, you have to run `rbenv rehash` to update global gem commands. I'm not sure if RVM does the same thing.

**Comment by rockstarwebdesign** [comment]
I still get the same error. I think the gem is cached or something... I can;t get the CLI to work...

**Comment by huphtur** [comment]
@rockstarwebdesign I got the CLI working by doing the following:
```bash
gem uninstall foundation
rvm get stable
rvm reset
npm install --global foundation-cli
```

**Comment by rockstarwebdesign** [comment]
My rvm is somehow not working or not installed. Seems weird... do you know how can I solve that? Do I need to reinstall OS X again?
