### ISSUE TITLE
[Top Bar] Doc example is difficult to see

### ISSUE THREAD

**Issue by beryllium** [zurb/foundation-sites#7472]
**How can we reproduce this bug?**

1. Load the Top Bar docs in Chrome
2. Scroll down to Top Bar example
3. Observe that the font colour is white, which is difficult to read on the background

**What did you expect to happen?**

I expected the text to be a readable colour.

**What happened instead?**

The text was not easy to read.

<img width="803" alt="screen shot 2015-12-09 at 11 00 34 pm" src="https://cloud.githubusercontent.com/assets/602491/11709023/e24043aa-9ec8-11e5-8525-96b36a67baec.png">

**Comment by gakimball** [comment]
Fixed via 9bf0552ef5f737c1e209e9efd5c2e76b05afbdbe

We'll have a patch out soon that will include this fix.
