### ISSUE TITLE
Uncss strips essential classes injected dynamically

### ISSUE THREAD

**Issue by jasonhick** [zurb/foundation-sites#7473]
Hi,

Running gulp --production runs Uncss. 
This removes css classes that are injected dynamically, many of which are needed by Foundation components. We've tested this with the dropdown menu component and it breaks in the production build.

To get this working I had to edit the regular expressions to be:

```
new RegExp('^meta\..*'),
new RegExp('.*\.is-.*'),
new RegExp('.*\.js-.*'),
new RegExp('.*\.has-.*'),
new RegExp('.*\.pr-.*'),
new RegExp('.*menu.*')
```

**Comment by zurbchris** [comment]
I see the issue for Dropdown Menu, the Sass wasn't updated to use the `.is-dropdown-submenu` class and is instead still using `.submenu`. We'll get this updated soon-ish, unless you want to drop a sweet pr :smile_cat:

**Comment by jasonhick** [comment]
Thanks for coming back to me! I'll take a look and see if I can get a pull request before Xmas ;))

**Comment by gakimball** [comment]
Rolling this into #7909 

We'll make sure we have this resolved before our next minor release.
