### ISSUE TITLE
[Accordion] 6.0.5 - Docs - Accordion js-events

### ISSUE THREAD

**Issue by gabrielolnunes** [zurb/foundation-sites#7477]
Documentation describes event name as uppercase on the first letter of element field. 
**down.zf.Accordion**

Actually, all the letters in the event fired is in lowercase.
**down.zf.accordion**

1. Check [docs](http://foundation.zurb.com/sites/docs/accordion.html#js-events) page for **up** and **down** events fired by accordion element 
2. Where you see **down.zf.Accordion**, it should be **down.zf.accordion**

There is other problems (maybe i post it in other issues): 
1. Each event is being fired twice (i need to debounce it)
2. Nested accordions **up** and **down** events are not distinguishable from parent to child. A child accordion when fires an **up** event for example, triggers the **up.zf.accordion** event listener of the parent. My solution for this was to use **event.target.id**.
3. Double click in a collapsed accordion makes it to bounce for a little on desktop and bounces forever on iPad.

**What did you expect to happen?**
**down.zf.Accordion** fired when accordion tab is done opening.

**What happened instead?**
**down.zf.accordion** is fired instead.

**Comment by zurbchris** [comment]
It's more than just Accordion, and it's the docs generator that's causing the issue. Generally speaking, all events being fired are formatted like `event.zf.pluginname` all lowercase.

**Comment by gabrielolnunes** [comment]
>Nested accordions **up** and **down** events are not distinguishable from parent to child. A child accordion when fires an **up** event for example, triggers the **up.zf.accordion** event listener of the parent. My solution for this was to use event.target.id.

Except for this, Accordion **up** and **down** seems to be ok now, i'm on version **6.1.1**. The description of events on documentation is correct, the bouncing effect is gone and there is no double fired events. 
As this last point that remained is not the main subject of this issue, i will close it.
Thank you!
