### ISSUE TITLE
[DropdownMenu] can't navigate with up down key on keybord in input fields

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7489]
i use a dropdown menu for hiding a login box which works fine but i can't navigate in the input fields autocomplete list with the up/down/left/right arrow on keyboard to choose an entry i made previously, or to change position of the cursor

also enter does not work

**Comment by designerno1** [comment]
maybe an option to disable keyboard controll for all plugins where it is used would be great

**Comment by designerno1** [comment]
or adding
```js
this.$menuItems.on('keydown.zf.dropdownmenu', function(e){
      if ($(e.target).is('input,select,textarea')) return;
...
```
to the bindings

**Comment by designerno1** [comment]
or generally don't use it on input elements

**Comment by gakimball** [comment]
It makes sense to not capture the keyboard event if a text field has focus. Going to roll this into #8011, as it's the same issue.
