### ISSUE TITLE
F6 - Get height of container after interchange init

### ISSUE THREAD

**Issue by wgstjf** [zurb/foundation-sites#7491]
Hi guys,

I have a jquery function to calculate the height of a container that adds the height of two nested divs to get the total height.  These nested divs contain images that utilise interchange.  

My question is how can I ensure that interchange has completed before the function queries the height of the nested divs?

I am using Foundation 6 and my jquery function is shown below.

Cheers,

Will

```js
  function sliderHeight() {
      if ($('#slider-wrapper').length) {
        Foundation.Interchange;  // Something here presumably...
        var height1 = $('#slide-calc-height').height();
        var height2 = $('#slide-calc-height2').height();
        var totalHeight = height1 + height2;
        $('#slider-wrapper').css('height',totalHeight + 'px');
      }
  }
```

**Comment by Knight-Yoshi** [comment]
Use a MutationObserver and watch for when the image source changes?

**Comment by zurbchris** [comment]
Or use the Interchange event emitters... they fire when the element's contents have been replaced.
```js
$('#slider-wrapper').on('replaced.zf.interchange', function(){
  //height changing logic...
});
```

**Comment by gakimball** [comment]
What @zurbchris said. All three Interchange types (HTML, images, background images) fire that event once the new content is done loading.

*However*, the `replaced` event wasn't in our docs, so I added it.

**Comment by wgstjf** [comment]
Thanks everyone, very helpful.  The 'replaced' event was exactly what I was after :-)

**Comment by wgstjf** [comment]
Hi guys,

Since updating to 6.1.1 the above solution's no longer working for me...it could of course be something I have changed also...but just in case it is something foundation related I thought I'd try here first...

The following is a function that I call on load and references an element with the id 'product-info'.  Within that element there are numerous instances of images which all use interchange.  This was working as shown but is now not.  The console.log is my debugging line to see if we get past the replaced.zf.interchange trigger...we do not and as such the nothing is output to the console.  Any thoughts??

``` js
function stickyAddToCart() {
  $('#product-info').on('replaced.zf.interchange', function(){
    console.log('product interchange completed...');
    var lastPanel = $( ".panel-wrapper" ).last().attr('id');
    var bar = new Foundation.Sticky($('#sticky-add-to-cart-bar'), {
      marginTop: 0,
      marginBottom: 0,
      topAnchor: 'page-header-wrapper:bottom',
      btmAnchor: lastPanel + ':top'}
    );
});
}
```

Cheers in advance,

Will

**Comment by gakimball** [comment]
@zurbchris Thoughts?

**Comment by andycochran** [comment]
@wgstjf I'm going to close this for now. Please reopen and provide a [CodePen](http://codepen.io/rafibomb/pen/xVVGOB) if this is still an issue with v6.2.1.
