### ISSUE TITLE
[Global Styles] ISSUE NAME HERE

### ISSUE THREAD

**Issue by therealbenhogan** [zurb/foundation-sites#7492]
**How can we reproduce this bug?**

1. Step one
2. Step two
3. Step three

**What did you expect to happen?**

**What happened instead?**

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by gakimball** [comment]
Please fill in the issue next time. ;)

**Comment by therealbenhogan** [comment]
Sorry – that was an oversight – didn’t realise I had done this!

[image001]

Paul Sawyer
Web Preference Ltd
14 Oakdale Road
Weybridge
Surrey KT13 8EJ

Telephone: 01932 424242
Mobile: 07968 164104
Web: http://web-preference.co.uk<http://web-preference.co.uk/>

Registered in England & Wales No. 5426254 VAT registration no. GB 860 5011 58

**Comment by gakimball** [comment]
No worries, if you run into any trouble with the framework, let us know in a new issue :)

**Comment by therealbenhogan** [comment]
Thanks Geoff - much appreciated!

[image001]

Paul Sawyer
Web Preference Ltd
14 Oakdale Road
Weybridge
Surrey KT13 8EJ

Telephone: 01932 424242
Mobile: 07968 164104
Web: http://web-preference.co.uk<http://web-preference.co.uk/>

Registered in England & Wales No. 5426254 VAT registration no. GB 860 5011 58
