### ISSUE TITLE
Drilldown menu and sub-menu styling

### ISSUE THREAD

**Issue by simonrcodrington** [zurb/foundation-sites#7495]
Hey there guys,

Firstly thanks for Foundation 6, it's pretty awesome overall.

In the drilldown menu, it seems that a vertical menu works best. My question is, if I set the top level menu to have the `vertical` class and add the `data-drilldown` to the top level, I would expect each of the inner sub-menu items to inherit the layout of the parent menu. Basically unless I add the `vertical` class to each of my sub-menus it reverts back to the standard horizontal menu style. 

I'm just not sure why its necessary to add the vertical class to the sub-menu items when using the drilldown menu it should just default the sub-menus to match the parent (I can't imagine any scenario where you would want a vertical top level menu and then inside it's sub-menus are horizontal)

Let me know if you guys want a CodePen of what I mean if you want any clarification. 

Thanks again guys!

**Comment by zurbrandon** [comment]
Yeah, this makes sense as a desired results i suppose. I feel like we had a reason why they shouldn't cascade, but we just has a discussion and couldn't think of any.  A PR would be appreciated, but if not we can get to it soon.

**Comment by simonrcodrington** [comment]
Thanks for the response.

Let me have a look into it and offer a pull request back to you guys for consideration. 

Thanks again :)

**Comment by zurbrandon** [comment]
Thanks Simon! Looking forward to it

**Comment by gakimball** [comment]
Implemented in the `6.2` branch: 8cb890c375afe5b146443386933b3e3370ccb383
