### ISSUE TITLE
[Off-canvas] off-canvas-wrapper showing scroll bar

### ISSUE THREAD

**Issue by deepakSP** [zurb/foundation-sites#7497]
when using off canvas in f6

off-canvas-wrapper showing scroll bar
![off-can](https://cloud.githubusercontent.com/assets/11506967/11745913/43012384-a041-11e5-859b-606a3aca0d82.PNG)

1st scrollbar is visible when I am using off-canvas-wrapper .

Note - removing off-canvas-wrapper doesn't show scrollbar

**Comment by Groschenroman** [comment]
I've got the same issue.
Using Foundation 6.0.3 and Angular2

The scrollbars disappear within the range of tablet viewports though – they re-appear in small and large views when resizing the window.

![screen shot 2015-12-11 at 16 52 54](https://cloud.githubusercontent.com/assets/7312890/11748738/017af334-a02a-11e5-9b16-86ae6dcda015.jpg)

**Comment by gakimball** [comment]
To confirm, you're seeing this on Chrome in Windows?

**Comment by deepakSP** [comment]
yes at least for me chrome only

**Comment by Groschenroman** [comment]
@gakimball I'm on a Mac 10.10.5 and I get the double scrollbars in Chrome, Firefox, Safari (didn't test Opera). All browsers in latest version.

**Comment by gakimball** [comment]
@deepakSP Can you post a code sample? We're using the off-canvas on several internal projects, including the F6 docs, and haven't seen this issue.

**Comment by deepakSP** [comment]
can the link be enough ??
https://www.picsinhd.com/gitTest

CSS n js is cached so you may see no issue on a page in that case

open a home link and hit back button n u will see a scroll bar

**Comment by deepakSP** [comment]
ok, I think adding overflow-y: hidden to off-canvas wrapper is hiding scrollbar. 
is there any downside ???

**Comment by gakimball** [comment]
@deepakSP Potentially, yes, we'd need to do thorough testing. Off-canvas falls victim to many fun bugs, mostly from Safari, both on OS X and iOS. But we can look into it as a potential solution for sure.

**Comment by rafibomb** [comment]
Has anyone used the change @deepakSP has proposed? adding overflow-y: hidden to off-canvas wrapper seems like a good solution but we'd like it fully tested in more situations.

**Comment by foodgy** [comment]
@gakimball confirm double scrollbar on Win/Mac OS Chrome and FF.

I figured out that on my project second scrollbar appears if there is a dropdown on the page.
Example: http://codepen.io/anon/pen/jqEJvB
Remove dropdown and scrollbar will dissappear.

**Comment by Kwbmm** [comment]
I have the same issue in a page where I'm using tabs.. Is there any known fix?

**Comment by andycochran** [comment]
@foodgy Interesting! The second scrollbar will disappear if you toggle the Dropdown.

**Comment by EspadaV8** [comment]
@foodgy We have just noticed the same issue using dropdowns on our site. Any chance you found a reliable fix?

**Comment by ultra86** [comment]
I personally am giving up Foundation 6. It's one problem after another between this issue, Ajaxy modal mayhem, and broken drop-downs, it's costing me piles of cash to develop with this broken, forgotten (seemingly) framework. I know my comment may not seem to be helpful at first, but it honestly is. The solution to Foundation 6 is to go back to Foundation 5.5.3.

**Comment by ineptian** [comment]
Adding overflow-y: hidden to the off canvas wrapper successfully fixes this problem and from what I can tell does not cause any conflicts.

**Comment by ultra86** [comment]
Not when used in conjunction with a sticky header that changes height on scroll, which on tablets does not un-stick properly when scrolling back to the top of the page. This issue is also apparent on desktop in approx. 1/10 scrolls. Perhaps others have had better luck, but I've designed dozens of sites in Foundation 5.5.3 and the three I've created in Foundation 6.latest have all been a nightmare. Not to sound harsh, but the state of the current F6 build has cost my company a lot of dough and it's extremely frustrating it was released in this state w/ docs that are fundamentally errant in many cases.

**Comment by brettsmason** [comment]
This should now work correctly in version 6.3. We no longer force 100% height, and the wrappers have been cut down, so this should no longer be a problem.
The release candidate is currently out for testing, with the final version out in a few weeks.

Closing this, but if you have any issues with this in 6.3 please re-open.
