### ISSUE TITLE
grid-row() sass mixin not working fine anymore

### ISSUE THREAD

**Issue by christophediprima** [zurb/foundation-sites#7498]
This i not working anymore since 6.0.5 as been released !

```sass
ul
  @include grid-row(17)
  li:not(.item)
    @include grid-column(5)
    &:last-child
      @include grid-column(2)
```

Grid columns keep using 12 as reference...

**Comment by gakimball** [comment]
The `grid-column()` class need to go inside `grid-row()`. In SCSS it looks like this. In Sass you probably just need to shift the indent over by one where `li:not(.item)` is.

```scss
ul {
  @include grid-row(17) {
    li:not(.item) {
      @include grid-column(5);

      &:last-child {
        @include grid-column(2);
      }
    }
  }
}
