### ISSUE TITLE
Foundation.utils not available in foundation6

### ISSUE THREAD

**Issue by confile** [zurb/foundation-sites#7499]
I searched for ``random_str`` in the foundation.js of foundation version 6 but this function does not exist.

Also ``Foundation.utils`` is reported as undefined when doing: 

```
console.log(Foundation.utils);
```
I have initialized foundation6 before with: 

```
<script type="text/javascript">   
   $(function(){
   	 $(document).foundation();	
   }); // end jquery
</script>
```

**Comment by zurbchris** [comment]
This isn't a bug, we simple changed the structure of our utils, removed quite a few things and added a few others. I would recommend checking out [Foundation JS Utilities](http://foundation.zurb.com/sites/docs/javascript-utilities.html) page on our docs to see what is available.
