### ISSUE TITLE
Callout Alert Data Dismissable not working

### ISSUE THREAD

**Issue by jurerick** [zurb/foundation-sites#7501]
**How can we reproduce this bug?**

1. Add "data-closable" attribute to alert callout
```
<div class="alert callout alert-box" data-closable>
 ...
```
2. Add the close-button for the alert
```
<button class="close-button close" aria-label="Dismiss alert" type="button">
	    <span aria-hidden="true">&times;</span>
  	</button>
```
**What did you expect to happen?**
The alert should close / dismiss

**What happened instead?**
Nothing happened

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by ocularrhythm** [comment]
Confirmed with `6.0.4` and `6.0.5`, no console errors were displayed.

**Comment by gakimball** [comment]
Add the attribute `data-close` to the `<button>`. That's the click trigger.

Pull request #7453 fixed the HTML example in the docs to add the missing attribute, so we'll have that deployed to the live docs soon.
