### ISSUE TITLE
Top Bar stack breakpoint

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#7502]
If your inline menu items list is too wide to fit on medium screens, you may want to stack it on both medium and small screens. Currently… 

> A top bar (.top-bar) can have two sections: a left-hand section (.top-bar-left) and a right-hand section (.top-bar-right). On small screens, these sections stack on top of each other.

I don't see a way to set the breakpoint at which the Top Bar stacks. Could we create a variable for this?

**Comment by andycochran** [comment]
I'm trying to do this: 

```
<div class="top-bar">
	<button id="mainMenuToggler" class="hide-for-large float-right" type="button" data-toggle="mainMenu"><span class="show-for-sr">Menu</span></button>
	<div class="top-bar-left">
		<ul class="menu">
			<li><a href="#">Site Name</a></li>
		</ul>
	</div>
	<div id="mainMenu" class="top-bar-right show-for-large" data-toggler=".show-for-large">

		...

	</div>
</div>
```

Maybe I'm going about it wrong? Is there a better F6 way?

**Comment by TvrtkoM** [comment]
maybe this could help. added classes 'stacked', 'stacked-for-small' and 'stacked-for-medium'.

top bar doesn't stack sections default with this and 'stacked' class should be applied in order to work

**Comment by andycochran** [comment]
Relatedly, #7566 will allow you to stack your menus at the same breakpoint at which your top bar stacks.

**Comment by gakimball** [comment]
Added a `$topbar-unstack-breakpoint` variable to make the shift from mobile to desktop mode configurable.
