### ISSUE TITLE
installation issues on windows10

### ISSUE THREAD

**Issue by geraldinethomas5** [zurb/foundation-sites#7503]
hello, I'm getting this error when running the install command $npm install --global foundation-cli as follows: 

PS C:\Users\geraldine> npm install --global foundation-cli
C:\Users\geraldine\AppData\Roaming\npm\foundation -> C:\Users\geraldine\AppData\Roaming\npm\node_modules\foundation-cli\bin\foundation.js
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "foundation-cli"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package yo does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-fa@1.3.0 wants yo@>=1.0.0
npm ERR! peerinvalid Peer generator-zf5@1.0.0 wants yo@~1.4.8

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\geraldine\npm-debug.log

any Ideas what this might mean? thank you so much.

**Comment by gakimball** [comment]
That's pretty bizarre—you're getting an error related to `yo` (Yeoman), which the Foundation CLI doesn't reference at all.

If you run `foundation` what happens?

**Comment by geraldinethomas5** [comment]
hi thanks for your response it run $foundation here is the following:

PS C:\Users\geraldine> foundation

Commands:
  new       Create a new Foundation project
  update    Update an existing Foundation project
  watch     Watch a project's files for changes
  build     Build a project's files for production
  help      Show this screen
  -v        Display the CLI's version

To learn more about a specific command, type foundation help <command>

Need more help? Ask a question on the Foundation Forum:
foundation.zurb.com/forum


Thanks

**Comment by gakimball** [comment]
Alright, then it works! Run `foundation new` to set up a new project.
