### ISSUE TITLE
[Callout] Not closable 

### ISSUE THREAD

**Issue by conrman** [zurb/foundation-sites#7504]
1. Install & setup Foundation via Bower
2. Include all javascript files
3. Add markup to page

**Expected behavior**: callout box close when clicking 'x'

**Problem behavior**: callout box doesn't close

Here is a [CodePen](http://codepen.io/conrman/pen/Ywyygr), I couldn't find a CDN for foundation 6 css.

**Comment by gakimball** [comment]
Add `data-close` to the `<button>` to create the close trigger.

The docs for Callout are currently incorrect, but there's a fix in place that corrects the code sample. That fix should land in the live docs today.

**Comment by conrman** [comment]
Could you provide a working example? The example code in the documentation doesn't show the use of `data-close` and when I tried it [here](http://codepen.io/conrman/pen/Ywyygr) it didn't work either.
