### ISSUE TITLE
[Installation] Install Command-Line Tool doesn't work for me

### ISSUE THREAD

**Issue by TomSwan** [zurb/foundation-sites#7507]
**How can we reproduce this bug?**

1. Install npm (success)
2. Follow steps under "Command-Line Tool" in <http://foundation.zurb.com/sites/docs/installation.html> (success with a warning, see below)
3. Foundation new fails to operate

**What did you expect to happen?**

Foundation.js and the link to it seem correct.

**What happened instead?**

    $ foundation new
    /usr/bin/env: node: No such file or directory

**Test case**

Here are some of the lines from the install:

$ sudo npm install --global foundation-cli
npm http GET https://registry.npmjs.org/foundation-cli
npm http 304 https://registry.npmjs.org/foundation-cli
npm WARN engine foundation-cli@2.0.1: wanted: {"node":">=0.10.33"} (current: {"node":"v0.10.25","npm":"1.3.10"})
...
/usr/local/bin/foundation -> /usr/local/lib/node_modules/foundation-cli/bin/foundation.js
...
$ foundation new
/usr/bin/env: node: No such file or directory

**Comment by gakimball** [comment]
Looks to be an issue with your Node install; the `node` command is not in your shell's $PATH.

You'll need to find the folder that Node was installed in, and then create an alias command called `node` that points to that folder. [Here's a GitHub comment](https://github.com/nodejs/node-v0.x-archive/issues/3911#issuecomment-8956154) answering the exact issue you're having.

**Comment by TomSwan** [comment]
Thanks. This is what I did to get foundation working:
    ln -s /usr/bin/nodejs /usr/local/bin/node 


> On December 14, 2015 at 12:00 PM Geoff Kimball <notifications@github.com>
> wrote:
> 
> Looks to be an issue with your Node install; the node command is not in your
> shell's $PATH.
> 
> You'll need to find the folder that Node was installed in, and then create an
> alias command called node that points to that folder. Here's a GitHub comment
> answering the exact issue you're having.
> 
> —
> Reply to this email directly or view it on GitHub.
>  

http://www.tomswan.com
