### ISSUE TITLE
JS assets path in foundation-zurb-template gulpfile.js file still broken?

### ISSUE THREAD

**Issue by David-van-den-Bor** [zurb/foundation-sites#7508]
```
-    'src/assets/js/**/*.js',
+    'src/assets/js/!(app.js)**/*.js'
```

The latest [update/commit](https://github.com/zurb/foundation-zurb-template/commit/c8ae999e689c697b781845febb734212473a0a56) with the negated path glob didn't solve the issue for me. Is ```src/assets/js/!(app.js)**/*.js``` a valid way to negate single files? I trIed other ways of globbing, like ```!src/assets/js/app.js, src/assets/js/**/*.js``` but that didn't work. Also tried updating NMP and Gulp to their latest versions, but that didn't help either. Did others experience the same issue?

When I fire up the **javascript** gulp task, all the foundation js files are combined, **except** for the ```src/assets/js/**/*.js``` files. The **app.js** file is also added, but the other globbed files ``` **/*.js ``` in the same directory are just ignored.

Regards and thanxx in advance, David :-)

**Comment by gakimball** [comment]
Hmm, I'll look into it further.

**Comment by eblin** [comment]
@gakimball, @David-van-den-Bor 
same thing was happening to me I managed to fix it with the following glob
```
  'src/assets/js/**/{!(app.js),*.js}',
  'src/assets/js/app.js'
```

That finally included all the js files and then app.js at the end.

**Comment by David-van-den-Bor** [comment]
**Wow! Good catch!** :-) I'll leave it to Geoff to test it and close the issue(?)

**Comment by gakimball** [comment]
@eblin @David-van-den-Bor The pattern `src/assets/js/**/{!(app.js),*.js` still catches `app.js` in my environment. I'm on Node 0.12, and Gulp's vinyl-fs uses glob 5.0.

**Comment by gakimball** [comment]
This pattern worked for me. The pattern `!(app)` means "match anything but `app`".

```
'src/assets/js/**/!(app).js',
'src/assets/js/app.js'
```

**Comment by eblin** [comment]
Nice! thanks for the update
