### ISSUE TITLE
[Top Bar] Docs link color

### ISSUE THREAD

**Issue by TvrtkoM** [zurb/foundation-sites#7509]
link color on live foundation sites docs render white
![TopBar](http://i.imgur.com/p89xINH.png)

strange that's not the case in my local docs after *gulp build*. it renders white again if foundation.css is used.

**Comment by gakimball** [comment]
Fixed via 9bf0552ef5f737c1e209e9efd5c2e76b05afbdbe

We'll have a patch out soon to address it.
