### ISSUE TITLE
Foundation 6 - css validation errors

### ISSUE THREAD

**Issue by alexrois** [zurb/foundation-sites#7511]
When using W3C validation service with Foundation 6 there are 15 errors.

Results of validation foundation.css from develop branch [see here.](https://cloud.githubusercontent.com/assets/16092409/11759762/dee20256-a08b-11e5-9b56-16ef537d9123.jpg)

**Comment by gakimball** [comment]
The only thing in there that is a legitimate issue is the presence of the `&` selector, which was fixed via b53e0b539e9d3c5002c445e73067fa62168d4f89. That fix will land in the next patch.

To summarize everything else:
- `optimizeLegibility`, `pointer-events`, `user-select`, and `touch-action` are all real, albeit experimental CSS properties. In most browsers they're still prefixed.
- The use of string concatenation in the `content` property is allowed. [Here's an example from MDN.](https://developer.mozilla.org/en-US/docs/Web/CSS/content#CSS_Content_4)
- The `Unknown dimension 0\0` error comes from a browser hack we use to target IE only.
- Not sure why it's choking on the embedded PNG.
- The use of `calc()` is also valid.
