### ISSUE TITLE
[Bugs] - Off Canvas settings not working in Yeti Launch projects only

### ISSUE THREAD

**Issue by paper9oll** [zurb/foundation-sites#7513]
Off Canvas styles not applying after changing the variables in `_settings.scss` file located under src/assets/scss.

**Note** - This does not affects users that created their projects via Packages Manager, I have not verify if this bugs affects users that created their projects via CLI.

**Comment by gakimball** [comment]
The projects the CLI creates are identical to the ones in Yeti Launch.

Try this: start running a project, change a variable. Then stop running the project, start it again, and see if the variable changed.

If the value changes, then it's an issue with the watcher tasks in the Gulpfile.

Also, for good measure, which specific off-canvas variables were you changing?

**Comment by paper9oll** [comment]
@gakimball I tested out using Yeti Launch ... reproduce using the steps you mentioned and the values still doesn't change.

I changed `$offcanvas-size` from **250px** to **300px** and `$offcanvas-background` from **$light-gray** to **$black**

**Comment by CobraClutch** [comment]
I'm having this same issue. Yeti project doesn't seem to want to change the $offcanvas variables.

**Comment by gakimball** [comment]
Alright, found the issue. Your project probably has a slightly outdated version of the framework.

Open `bower.json` in your editor and change the version number for `foundation-sites` to `~6.1.0`. Then run `bower update foundation-sites` to get it synced up. There was a bug that prevented some off-canvas settings from applying properly, but those were resolved in a more recent version of the framework.
