### ISSUE TITLE
flex box - how to properly use?

### ISSUE THREAD

**Issue by mmjaeger** [zurb/foundation-sites#7517]
```
<div class="site-container">
	<div class="footer-widgets">
		<div class="wrap"> /* needs to be horizontally centered with max-width */
			<div class="row">
				<div class="widget-area"> /* one-third */
					Widget 1
				</div>
				<div class="widget-area"> /* one-third */
					Widget 2
				</div>
				<div class="widget-area"> /* one-third */
					Widget 3
				</div>
			</div>
		</div>
	</div>
</div>
```

That's what I came up with to make it work - if I do not apply the flex-grid-column mixin to .row, the .row doesn't take the full width of the .wrap container. However, it applies negative margin on the left and right and padding left and right. margin and padding left and right could be omitted all together.

```
.wrap {
	@include flex-grid-row;
}

.row {
	@include flex-grid-row(nest);
	@include flex-grid-column(12);	
}

.widget-area {
	@include flex-grid-column(12);
}
```

Hello

I'm kind of struggling how to properly set up the above layout/structure using flexbox.

Is there a mixin that would apply only max-width per breakpoint and maybe margin auto to .wrap - doesn't need to be a flexbox, right?
The .wrap div determines the width of the page and whether it's centered or not.

The row needs to be a flexbox with its three columns.

What's the proper way to set this up using mixins only? Are there any examples out there?

**Comment by aibrean** [comment]
You haven't defined your columns.

```html
<div class="site-container">
    <div class="footer-widgets">
        <div class="wrap"> /* needs to be horizontally centered with max-width */
            <div class="row">
                <div class="widget-area columns small-4"> /* one-third at small and up */
                    Widget 1
                </div>
                <div class="widget-area columns"> /* one-third */
                    Widget 2
                </div>
                <div class="widget-area columns"> /* one-third */
                    Widget 3
                </div>
            </div>
        </div>
    </div>
</div>
```

**Comment by mmjaeger** [comment]
Thanks for replying but the columns are not the issue - furthermore the columns are defined using the statement above: @include flex-grid-column(12);

**Comment by aibrean** [comment]
My eyes glassed over that one...You would still (most likely) need to have breakpoint part added (small-4). I noticed a disparity in some browsers not recognizing the width without at least one defined.

**Comment by mmjaeger** [comment]
as I said, the issue is not the column width - what I'm struggling with is
how to properly nest the rows, starting with the .wrap container which
defines the page width but doesn't need to be a flex-container - I'm trying
just to use mixins - no inline classes. I guess I should not use the
grid-row mixin for .wrap and apply max-width manually?



On Sun, Dec 13, 2015 at 8:09 AM, April Sadowski <notifications@github.com>
wrote:

> My eyes glassed over that one...You would still (most likely) need to have
> breakpoint part added (small-4). I noticed a disparity in some browsers not
> recognizing the width without at least one defined.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zurb/foundation-sites/issues/7517#issuecomment-164267174>
> .
>



-- 
Marco M. Jaeger
http://net4visions.com

**Comment by gakimball** [comment]
Sorry for not getting back to you sooner! Let's break it down.

In your first example, you've defined `.wrap` and `.row` as flex rows, and `.widget-area` as flex columns. However, like with the float grid, you shouldn't nest rows inside rows, or columns inside columns. To nest grids, you alternate row and column.

The flex row already has a `max-width` and `auto` margins added, so it will horizontally center on its own.

As for the columns, if you want them all to be the same width, use `@include flex-grid-column` with no parameters. This applies `flex: 1 1 0px`, which means "share the space equally".

Without knowing exactly what your CSS looks like, my best guess is that your markup will look like this. Note that I've removed the `.wrap` class, as the `.row` will handle sizing and alignment for us.

```html
<div class="site-container">
  <div class="footer-widgets">
    <div class="row"> <!-- @include flex-grid-row; -->
      <div class="widget-area"></div> <!-- @include flex-grid-column; -->
      <div class="widget-area"></div> <!-- @include flex-grid-column; -->
      <div class="widget-area"></div> <!-- @include flex-grid-column; -->
    </div>
  </div>
</div>
```

Let me know if that helps, or if you have any more questions! :)
