### ISSUE TITLE
Joyride expose should ignore margin on target elements.

### ISSUE THREAD

**Issue by quinncomendant** [zurb/foundation-sites#7518]
See screenshot below: buttons have bottom margins which make an unsightly white gap below them. 

![screen shot 2015-12-12 at 14 25 56](https://cloud.githubusercontent.com/assets/6884276/11763553/fcaee41e-a0dd-11e5-8583-07ffd0074eb7.png)

**Comment by gakimball** [comment]
Fixed in the `V5` branch: 78c00ff22ab3e3d5a0310cb2d0f3f527c7ac0af4
