### ISSUE TITLE
Customize Foundation does not output foundation css and js files

### ISSUE THREAD

**Issue by confile** [zurb/foundation-sites#7520]
I tried the custom generator here: http://foundation.zurb.com/sites/download.html/

The result I get is this: 

![downloads](https://cloud.githubusercontent.com/assets/64265/11769613/1b83d32c-a1ec-11e5-9e82-e93f94d6e4f6.jpg)

The foundation js and css files are missing.

**Comment by gakimball** [comment]
What settings did you use? Not seeing this behavior if I leave every component turned on.

**Comment by gakimball** [comment]
Rolling this into #7033
