### ISSUE TITLE
documentation on foundation cli up to date?

### ISSUE THREAD

**Issue by pniederlag** [zurb/foundation-sites#7522]
On http://foundation.zurb.com/sites/docs/v/5.5.3/sass.html#cli I do see this command to install the cli tool `gem install foundation`, from my understanding this is old/obsolete and replaced by `gem install foundation-cli`. Could you please update the doc or clearify this matter?

Thx and Greets,
Peter

**Comment by TomSwan** [comment]
The former (`foundation`) works for me; the latter (`foundation-cli`) doesn't:

> $ sudo gem install foundation-cli
> ERROR:  Could not find a valid gem 'foundation-cli' (>= 0) in any repository
> ERROR:  Possible alternatives: foundation-css, foundationapi, foundation, foundation-sass, codelation-cli

> $ sudo gem install foundation
> Fetching: thor-0.19.1.gem (100%)
> Fetching: foundation-1.0.4.gem (100%)
> Successfully installed thor-0.19.1
> Successfully installed foundation-1.0.4
> 2 gems installed

**Comment by pniederlag** [comment]
https://github.com/zurb/foundation-cli is a nodes module and not a gem package, so I'd like to rephrase my question to this:

Is `gem install foundation` replaced by `npm install -g foundation-cli'?

**Comment by gakimball** [comment]
@pniederlag The new CLI doesn't install Foundation 5 projects, so if you need to do that, stick with the Ruby CLI for now.

We'll update the F5 docs with a note about this.

**Comment by gakimball** [comment]
Added that note: 7ad066ee81e1c26e4ee8ac87a186a112ca61291c

Deploying to the live docs shortly!
