### ISSUE TITLE
[Sticky] Foundation.Sticky not passing correctly object

### ISSUE THREAD

**Issue by tipo94** [zurb/foundation-sites#7524]
**How can we reproduce this bug?**
Try to create an instance of a sticky object using 
var elem = new Foundation.Sticky(element);

**What did you expect to happen?**
I expect the instance of the sticky object called with:
$(document).foundation(); 

to work the same as the one called with:
var elem = new Foundation.Sticky(element);

**What happened instead?**
The sticky object just disappear.

It works fine when loading with 
$(document).foundation(); 
However when loaded this way if you try to access your sticky object with:
var elem = Foundation.Sticky(element);
The console throw this error:
TypeError: this._init is not a function

**Test case**
I'm sorry I wasn't able to set up a jsfiddle however it happens on every element I try so it should be easy to reproduce

**Comment by zurbchris** [comment]
If you're trying to access a JS plugin initialized with `$(document).foundation()` you would do so with the `$('selectorOfPlugin').foundation('methodToInvoke' [,arg1, arg2..])`, if you're trying to access methods on a plugin created programmatically, you would do so directly: 
```js
var sticky = new Foundation.Sticky($('#stickyThing'), options);

sticky.methodToInvoke();
```

**Comment by tipo94** [comment]
Thank you I understand I made to make a mistake trying to access the plugin this way.
However I'm still not able to initialize the plugin programmatically.
`var sticky = new Foundation.Sticky($('#stickyThing'), options);` will make stickyThing disapear.

I usually initialize my plugins like this (accordion, reveal) and don't have this problem.
I'm pretty new at foundation so forgive me if i'm missing something obvious but the fact I get the initialization right for the other plugins make me wonder if there is not something wrong with the sticky plugin.

**Comment by zurbchris** [comment]
Send me a link to a fiddle or codepen and I'll take a look.

**Comment by tipo94** [comment]
Thanks.
I have up a fiddle that reproduce this problem:
http://jsfiddle.net/tipo94/5690g3k8/

**Comment by zurbchris** [comment]
Your id and selector are pointed at the wrong element. Should be on the data-sticky element, not sticky-container.

**Comment by tipo94** [comment]
Doing so will not make the sticky element disapear but it won't stick either
updated version:
http://jsfiddle.net/tipo94/5690g3k8/1/

**Comment by zurbchris** [comment]
You still need to initialize foundation for sticky. I've tweaked your fiddle to a working version: 
http://jsfiddle.net/kho7xns3/1/

**Comment by tipo94** [comment]
Ah ok, since you can initialize the other plugins without initializing foundation I thought this was unexpected behavior.

I have a page with element that can be dynamically load by users and some plugins might be attached on the fly to those element. I was initializing them separately after ajax callback and having to initialize foundation for the sticky made all the reveal load a second time so I was trying to avoid it.

I guess  I will have to find another way to code this. 
Thanks for the clarification and your time.

**Comment by zurbchris** [comment]
If you're loading things in via programmatic construction, you don't need the data-plugin name attribute, that's why your reveal is getting double loaded with `$(document).foundation()`. Those attributes are there so our JS can find them and initialize them, but if you're doing that yourself, don't use the attribute tag.

**Comment by tipo94** [comment]
That's what I was missing.
Sorry for the confused question and thanks for the awesome support

**Comment by zurbchris** [comment]
cool, I'm going to close this then if you're squared away. Thanks and you're welcome!
