### ISSUE TITLE
[Abide] Submit doesn't work

### ISSUE THREAD

**Issue by carloast82** [zurb/foundation-sites#7527]
after input field check (if all fields are correct) submit do nothing.
tha action attribute is ignored and the form don't submit.

**Comment by MikePugs** [comment]
+1

**Comment by dherran** [comment]
Current status is that Abide is getting an overhaul as per: #7519

**Comment by zurbchris** [comment]
Should be fixed with #7590, please comment and submit pr's to the `abide` branch until 6.1 release.
