### ISSUE TITLE
[Accordion] Double click results in 8 toggles!

### ISSUE THREAD

**Issue by tlimited** [zurb/foundation-sites#7528]
**How can we reproduce this bug?**

1. Go to either http://foundation.zurb.com/sites/docs/accordion.html or http://codepen.io/avr/pen/EPaXdW
2. Double click to open one Foundation 6.x Accordion multi-expand

**What did you expect to happen?**
Should toggle accordion on or off once.

**What happened instead?**
It slidetoggles the accordion about eight times on and off – quite crazy.

**Comment by barrard** [comment]
did this get fixed?
