### ISSUE TITLE
[Equalizer] act_on_hidden_el issue

### ISSUE THREAD

**Issue by smoizs** [zurb/foundation-sites#7530]
Hi,

When the following code is placed 

```javascript
$(document).foundation({
  equalizer : {
    // Allow equalizer to resize hidden elements
    act_on_hidden_el: true
  }
});
```

an error is generated in the console - which is **"Uncaught TypeError: We're sorry, 'object' is not a valid parameter. You must use a string representing the method you wish to invoke."**

Basically, I want equalizer to watch hidden elements too.

**Comment by smoizs** [comment]
Just wanted to add that this is being notice in Foundation 6.

**Comment by zurbchris** [comment]
Two things: that is not the correct way to pass in new default values to plugins in Foundation 6, see: [Configuring Plugins](http://foundation.zurb.com/sites/docs/javascript.html#configuring-plugins),
and that isn't an option available in equalizer in Foundation 6, If the element is `visibility: hidden;` it will still work, but if it's `display: none;` it will not.

P.S. All Foundation 6 variables are camelCased now, that snake_case bugged me...
