### ISSUE TITLE
[Forms] Inline Label and Button 1px larger than the input 

### ISSUE THREAD

**Issue by sajtosnorbert** [zurb/foundation-sites#7533]
As you can see in the foundation 6 docs Inline Labels and Buttons section, the height of the label and the button is 1px larger than the input.

Tried in chrome and edge too, the heights are not the same.

I think the 22px height is only 21px for the input (possible rem calculation bug, or something else...).

Thanks,
Norbert.

**Comment by tdhartwick** [comment]
Thanks! I think we fixed it in this commit 0bf07a2b0f801d6636e3e5cb41dbbb482ce765cd.
