### ISSUE TITLE
replaced.zf.interchange JS event not fired for background images

### ISSUE THREAD

**Issue by cpence** [zurb/foundation-sites#7534]
If you check the code [here,](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.interchange.js#L156) you can see that the `replaced` event is never fired if Interchange is changing background images. I know that you can't hook on the "completed" change of background-image, so technically the event will fire earlier than the other two cases, but I really need that JS event, and it worked in F5.

Thanks for the hard work on F6!

**Comment by cpence** [comment]
Thanks so much!

**Comment by zamson** [comment]
Sorry reopen this. But I can't seem to get this to work. Is it commented out in the code?

` /**
     * Fires when content in an Interchange element is done being loaded.
     * @event Interchange#replaced
     */
    // this.$element.trigger('replaced.zf.interchange');
  }`

**Comment by DanielRuf** [comment]
Which Foundation Sites version do you use and can you provide a codepen which reproduces / shows this?

**Comment by DanielRuf** [comment]
That's good that it is resolved with the new version.

It was and is still closed ;-)

**Comment by CHEWX** [comment]
It's still commented out for those of us that install singular plugins — https://github.com/zurb/foundation-sites/blob/develop/dist/js/plugins/foundation.interchange.js#L341

Please re-open.

**Comment by DanielRuf** [comment]
The dist files are not the latest files. Please check the source files.
You can also clone foundation-sites and compile it to get fresh dist files.

**Comment by DanielRuf** [comment]
cc @ncoden hm, it is still not activated here: https://github.com/zurb/foundation-sites/blob/develop/js/foundation.interchange.js#L179

Any reasons to not activate it? Or is this line obsolete and can be removed?

**Comment by CHEWX** [comment]
@DanielRuf If the dist files are not the latest, then `.gitignore` them, however, I think every release should have updated dist files, as I personally use `bower` and then just include the plugins I want, I don't want to have to build dependancies.

Either way, it's not triggering correctly.

**Comment by DanielRuf** [comment]
fyi: bower is dead in general, you should use npm

**Comment by DanielRuf** [comment]
Each tagged release includes the dist files and should include them as these are provided with the npm releases so ignoring them is not an option.

**Comment by CHEWX** [comment]
If that's the case, they should be kept up to date with any source file changes. It's only one command. 

It may be dyeing, but my workflow keeps bower files and npm files separate. I hate opening up `node_modules`, it's a dependancy mess. And when you want to reference something, I can ignore `node_modules`, from my Sublime, but open up `bower_components` at ease. Each to their own, but I see no benefit in dropping bower at the moment.

**Comment by DanielRuf** [comment]
https://bower.io/blog/
https://snyk.io/blog/bower-is-dead/
https://community.plone.org/t/bower-is-now-officially-dead/4246
