### ISSUE TITLE
[Keyboard access] uglify version "Component not defined!"

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7536]
if i uglify the output with gulp-uglify
Keyboard access not works error in Console:
Component not defined!
```js
var uglify = require('gulp-uglify');
gulp.task('javascript:foundation', function() {
  return gulp.src(FOUNDATION)
    .pipe(concat('foundation.js')).pipe(uglify())
    .pipe(gulp.dest('_build/assets/js'));
});
```
http://localhost:3000/dropdown-menu.html
press tab several times and then the info in the console appears

in normal version it seams to work fine but not in uglifyed version

**Comment by Owlbertz** [comment]
Are you using the latest version? I am almost sure this has already been fixed some time ago...

**Comment by designerno1** [comment]
i use develop branch.
i also think this has been fixed but now it reappears

**Comment by Owlbertz** [comment]
So you are using version 6.0.5? Strange... I will check this.

**Comment by Owlbertz** [comment]
Works for me with the latest version. Could you come up with an example page?

**Comment by designerno1** [comment]
for me if i uglify it via gulp, see first comment, and then press tab in the docs the console log appears and the tab does not respond to foundation

**Comment by Owlbertz** [comment]
I copied the `foundation.min.js` from the dist folder to replace the `foundation.js` file in the docs on my machine, which works good. Did you try the minified version from dist?
Do you have the possibility to provide me your minified version?

**Comment by designerno1** [comment]
i send you an email on your company info@address

**Comment by designerno1** [comment]
i compared my min file with the min file from dist and it's the same

**Comment by Owlbertz** [comment]
What browsers are you testing with?

**Comment by designerno1** [comment]
Firefox 42.0

**Comment by designerno1** [comment]
now on Firefox 43.0 same issue

**Comment by Owlbertz** [comment]
I can now reproduce this as well. Will work on a fix.

**Comment by designerno1** [comment]
great, a global to switch off the keyboard bindings would also be nice

**Comment by designerno1** [comment]
Or a component switching off

**Comment by Owlbertz** [comment]
Well I guess you can always call ```Foundation.Keyboard.register('DropdownMenu', {});``` after initialization to overwrite the default bindings.
