### ISSUE TITLE
[Top Bar] topbar-link-color too close to topbar-background color

### ISSUE THREAD

**Issue by craigjackson** [zurb/foundation-sites#7539]
**How can we reproduce this bug?**

1. From the first code example on the Sites Doc: http://foundation.zurb.com/sites/docs/top-bar.html#basics

Specifically:
```html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Site Title</li>
      <li class="has-submenu">
        <a href="#">One</a>
        <ul class="submenu menu vertical" data-submenu>
          <li><a href="#">One</a></li>
          <li><a href="#">Two</a></li>
          <li><a href="#">Three</a></li>
        </ul>
      </li>
      <li><a href="#">Two</a></li>
      <li><a href="#">Three</a></li>
    </ul>
  </div>
</div>
```

**What did you expect to happen?**

I expect to be able to clearly see the links: "One", "Two", "Three"

**What happened instead?**

Instead I can barely see the difference between the top bar background (#eeeeee) and top bar links text color (#ffffff).

I am using foundation-sites: https://www.npmjs.com/package/foundation-sites and building with SASS.

**Comment by gakimball** [comment]
This was fixed in version 6.0.6 via 9bf0552ef5f737c1e209e9efd5c2e76b05afbdbe
