### ISSUE TITLE
Tab error on jquery ajax

### ISSUE THREAD

**Issue by bruteforcehub** [zurb/foundation-sites#7543]
I have saved my tab as a separate resource and tried to load it via jquery ajax function. I am now getting errors "TypeError: n is undefined".  To be more specific, the error occurs on hover and on click of the tabs.

I have tried to include the resource on one of my php files and it works well, though i get bugs when I load it via ajax.

Error show is below:

TypeError: e is undefined
	

...e()+"]").data(t.attr_name(!0)+"-init");e.is_hover&&t.toggle_active_tab(i(this).p...

**Comment by bruteforcehub** [comment]
I finally resolved the issue. Though I already initialized foundation on my main js script file. I have tried to enclose the file response with foundation. Code is below:

success: function (response) {
                $(document).foundation(function(){
                    $(target).html(response);
                });
            },

**Comment by bruteforcehub** [comment]
It seems that it works now, after loading my resource via ajax I have tried to initialize foundation again. Everything runs smoothly now. Code is below:

$(target).html(response);
$(document).foundation();

**Comment by zurbchris** [comment]
Seems that you resolved this issue? I would be interested to see what you did, as this could help others with similar issues.

**Comment by bruteforcehub** [comment]
Basically I am working to load my tab file on my php page via jquery ajax. All of my other foundation elements are working except for the tab file which is loaded via ajax. I thought of re-declaring foundation on my ajax call after the response has been laid out and it worked.


Tab File:
```
<ul class="tabs" data-tab>
    <li class="tab-title active"><a href="#panel1">label</a></li>
    <li class="tab-title"><a href="#panel2">label</a></li>
    <li class="tab-title"><a href="#panel3">label</a></li>
    <li class="tab-title"><a href="#panel4">label</a></li>
    <li class="tab-title"><a href="#panel5">label</a></li>
</ul>
<div class="tabs-content">
    <div class="content active" id="panel1">
        <?php require_once 'form/file.php'; ?>
    </div>
    <div class="content" id="panel2">
        <?php require_once 'form/file.php'; ?>
    </div>
    <div class="content" id="panel3">
        <?php require_once 'form/file.php'; ?>
    </div>
    <div class="content" id="panel4">
        <?php require_once 'form/file.php'; ?>
    </div>
    <div class="content" id="panel5">
        <?php require_once 'form/file.php'; ?>
    </div>
</div>
```
######################################
JS File:
```
function ajax(type, resource, target) {
        $.ajax({
            type: type,
            url: resource,
            dataType: "html",     
            success: function (response) {
                    $(target).html(response);
                    $(document).foundation();
            },
            error: function (xhr, ajaxOptions, thrownError) {
                /*some code*/
            }
        });
    }
```
