### ISSUE TITLE
Off-Canvas: Sub-menu doesn't working

### ISSUE THREAD

**Issue by Joci933** [zurb/foundation-sites#7544]
The old (5.5.3) Foundation has contains the following Off-Canvas  commands:
<pre>
"has-submenu"
</pre>
 Now this isn't working with the new (6.0) Off-Canvas. :(

**Comment by gakimball** [comment]
The multi-level menu function off off-canvas was split into a separate plugin, called [Drilldown Menu](http://foundation.zurb.com/sites/docs/drilldown-menu.html). You can easily drop one of those into an off-canvas menu to get the same effect as Foundation 5.
