### ISSUE TITLE
[Accordion] Accordion Content Background

### ISSUE THREAD

**Issue by boneyebc** [zurb/foundation-sites#7545]
**How can we reproduce this bug?**

1. Change $accordion-content-background to "yellow"
2. Complile SCSS File
3. Check to see if color of this element has changed to yellow

**What did you expect to happen?**
Background color of Content change color to yellow

**What happened instead?**
Nothing... The color does not change

**Test case**
// 7. Accordion
// ------------

// $accordion-background: $white;
// $accordion-plusminus: true;
// $accordion-item-color: foreground($accordion-background, $primary-color);
// $accordion-item-background-hover: $light-gray;
// $accordion-item-padding: 1.25rem 1rem;
$accordion-content-background: yellow;
// $accordion-content-border: 1px solid $light-gray;
// $accordion-content-color: foreground($accordion-background, $primary-color);
// $accordion-content-padding: 1rem;

**Comment by ocularrhythm** [comment]
This should have been fixed when the `default` flag was added to the `$accordion-background` variable. The specific commit is [here](https://github.com/zurb/foundation-sites/commit/46c4bf76ae04cd41718a318dc5a6f8658c147243) . I believe this was fixed around 6.0.4.
