### ISSUE TITLE
Title Bar for small screens

### ISSUE THREAD

**Issue by strelnikov** [zurb/foundation-sites#7547]
Guys, I do not understand how you can brake this simple functionality just going from version 6.0.0 to 6.0.5.
It's already mine 3rd time I'm try to give a change to Foundation, but all the time get in trouble with some basic feature like collapsing or something similar.

http://foundation.zurb.com/templates-previews-sites-f6/real-estate.html windows resizing works great, but if you link it with latest Foundation version, it doesn't. WHY?

**Comment by JeremyEnglert** [comment]
The issue is with the template, not the framework.

Change `data-hide-for="small"` to `data-hide-for="medium"`
