### ISSUE TITLE
[Orbit] slide and container height on resize

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7551]
Slide and container height doesn't get refreshed on resize

**Comment by designerno1** [comment]
a autoHeight function for each slide would be great

**Comment by zurbrandon** [comment]
This isa known issue we're hoping to get to soon, if you have expercine with this at all a PR would be super helpful.

**Comment by designerno1** [comment]
a very very simple workaround is to set .orbit-container to height: auto !important;

**Comment by SimonHeimberg** [comment]
related: #7815 #7982

**Comment by kball** [comment]
@designerno1 @SimonHeimberg I took a pass on fixing this in #9317.  Would appreciate if you could take a look and see if it addresses your issues.

**Comment by kball** [comment]
Fixed in #9317
