### ISSUE TITLE
Gulp not copying images from src to dist on Windows

### ISSUE THREAD

**Issue by tallchap67** [zurb/foundation-sites#7552]
Vanilla Zurb Master Template watch on images not copying from src to dist.  Images are copied if you restart or run a production build, but not being copied over in normal workflow.

**Comment by gakimball** [comment]
What version of Windows, what command line, and what version of Node do you use?

**Comment by tallchap67** [comment]
Windows 7 SP1
Standard Command prompt, or Node.JS Command prompt
Upgraded npm yesterday to v3.5.2, was using 3.3.x previously.
 
I’ve got it working now (of sorts) by installing and using Foundation CLI.  After npm upgrade it still didn’t work without the CLI.

**Comment by gakimball** [comment]
Strange, how did you set it up initially? By cloning the template from GitHub?

**Comment by tallchap67** [comment]
Downloaded the latest zip from Github and unpacked into a new folder.
 
npm install
Bower install
npm start

**Comment by gakimball** [comment]
We had a few other reports about this issue, and I believe zurb/foundation-zurb-template#25 is the solution. You can look at the [diff](https://github.com/zurb/foundation-zurb-template/pull/25/files) of the PR to see what change is necessary.
