### ISSUE TITLE
Dropdown menu - alignment issue when not enough room

### ISSUE THREAD

**Issue by tamcy** [zurb/foundation-sites#7555]
Hello,

Consider this dropdown menu example (items copied from the foundation website):
http://codepen.io/anon/pen/jWWBvO

Normally, subitems are left aligned with the parent item. However, when there is not enough room for the subitems to appear (try shrink the window), the box is placed so that its right border touches to left border of the parent item, which gives a somewhat weird result:

![dropdown-menu-issue](https://cloud.githubusercontent.com/assets/959433/11818005/cc5e4c20-a392-11e5-9fe5-6e2bc170e5f5.png)

I suppose the expected behavior should be right aligned, as indicated in the screenshot?

**Comment by designerno1** [comment]
#7251

**Comment by gakimball** [comment]
These issues were resolved in Foundation 6.2. If I update your CodePen to use the 6.2.0 CSS and JavaScript, the flipped menus align properly.
