### ISSUE TITLE
[Flex Grid] Flex-Grid Distributed CSS File (Feature)

### ISSUE THREAD

**Issue by andrewbiddinger** [zurb/foundation-sites#7556]
Would it be possible to have a compiled/disributed version of foundation that has "flex-grid" enabled as the default grid? 

I ask so that CDNs serving up foundation core would also include the Flex-Grid version. 

Example:
foundation.flex-grid.css
foundation.flex-grid.min.css

**Comment by rafibomb** [comment]
I can see how it would be useful. We have it in the customizer http://foundation.zurb.com/sites/download.html/

**Comment by gakimball** [comment]
Yep, we can generate a new pair of CSS files for our `dist/` folder, and have the jsDelivr folks host them for us.

**Comment by andrewbiddinger** [comment]
Sweet! Thanks so much.

**Comment by gakimball** [comment]
Done! In 6.1 (out next week), the `dist/` folder will include two new files, `foundation-flex.css` and `foundation-flex.min.css`.

I'll hit up our friends at jsDeliver and see about getting these files added to our official CDN.

**Comment by OAOD-iNspire** [comment]
Has this been added to the cdn now ? Because request to /foundation-flex.css curretly returns a 404 error.

**Comment by OAOD-iNspire** [comment]
currently using version v6.4 of foundation

**Comment by ncoden** [comment]
@OAOD-iNspire From Foundation `v6.4`, flex mode and the new XY Grid are used by default (`foundation.min.css`). The previous "float" mode is availaible as `foundation-float.min.css`.

**Comment by OAOD-iNspire** [comment]
Please see this code block below. When using the cdn, using flex grid is not responsive however, switching to XY classes works fine. 


<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dsuonenergy-prototype</title>
    
   
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.4.3/dist/css/foundation.min.css" integrity="sha256-GSio8qamaXapM8Fq9JYdGNTvk/dgs+cMLgPeevOYEx0= sha384-wAweiGTn38CY2DSwAaEffed6iMeflc0FMiuptanbN4J+ib+342gKGpvYRWubPd/+ sha512-QHEb6jOC8SaGTmYmGU19u2FhIfeG+t/hSacIWPpDzOp5yygnthL3JwnilM7LM1dOAbJv62R+/FICfsrKUqv4Gg==" crossorigin="anonymous">

     

    <link rel="stylesheet" href="css/app.css">
    <link rel="stylesheet" type="text/css" href="css/styles.css">
  </head>
  <body>
  <div class="top-bar top-nav-border">


    <ul class="dropdown menu top-nav-border" id="" data-dropdown-menu>
      <li class="menu-text-size">
         <a href="">
         <figure class="center-align"> 
        <img src="images/community-icon-menu.png" alt="social community" width="50" > 
        <figcaption class="menu-text-style"> Community </figcaption>
      </figure>
         </a>
      </li>
      <li class="menu-text-size">
         <a href="">
         <figure class="center-align"> 
        <img src="images/product-icon-menu.png" alt="social community" width="50" > 
        <figcaption class="menu-text-style"> Products </figcaption>
      </figure>
         </a>
      </li>


      <li class="menu-text-size ">
      <a href="#0">

       <figure class="center-align"> 
        <img src="images/service-icon-menu.png" alt="social community" width="50" > 
        <figcaption class="menu-text-style"> Services </figcaption>
      </figure>

      </a> 

      </li>
      <li class="menu-text-size">
      <a href="#0">

       <figure class="center-align"> 
        <img src="images/cv-icon-menu.png" alt="social community" width="50" > 
        <figcaption class="menu-text-style"> Portfolio </figcaption>
      </figure>
        
      </a> 
      </li>
       <li class="logo-container-size"> <a href="" class=right-align>
        <figure> 
 <img src="images/logo.png">
 <figcaption class="vision-style"> Sustainable energy for all </figcaption>
        </figure>
         </a>

        </li>
     <hr class="nav-bottom mOff"> 
     </ul>
</div>
  
   
   <div class="row ">
  <div class="columns small-6">
  <h6 class="inner-text-style"> Community <h6> 
 
  </div>
  <div class="columns small-6">I am as well, but I have so much text I take up more space! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis facere ducimus earum minus, inventore, ratione doloremque deserunt neque perspiciatis accusamus explicabo soluta, quod provident distinctio aliquam omnis? Labore, ullam possimus.</div>
</div>

      </div>
    </div>

 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="js/vendor/what-input.js"></script>
<script src="js/vendor/foundation.js"></script>
<script src="js/app.js"></script>
 
  </body>
</html>

**Comment by ncoden** [comment]
@OAOD-iNspire Flex Grid is not included in `foundation.min.css`. You have to install and configure Foundation locally if you want to continue using the legacy Flex Grid.

See https://foundation.zurb.com/sites/docs/flex-grid.html#importing
