### ISSUE TITLE
Dropdown adjustments for RTL

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7560]
These adjustments need to be made to the Dropdown Pane plugin on RTL:

- Top- and bottom-aligned dropdowns should fan out to the left by default, not the right. (So they fan out towards the reading direction.)
- Left- and right-aligned dropdowns should not automatically flip on RTL. In RTL mode, anything tagged as "left" or "right" retains that meaning, and doesn't automatically flip.

**Comment by apolun** [comment]
For me everything is ok unless right arrow which should be "<"  not ">" 
Also this is not work  http://zurb.com/university/lessons/how-to-re-create-top-bar-with-foundation-6
and show me left and write arrow but the demo picture shows dropdowns

**Comment by abdullahsalem** [comment]
@gakimball any update?

**Comment by kball** [comment]
I believe the dropdown issue is addressed, but dropdown menu still needs some work.  I"m going to close this and create a new issue.
