### ISSUE TITLE
[Orbit] Simple verbiage error in orbit docs

### ISSUE THREAD

**Issue by empirenine** [zurb/foundation-sites#7562]
**How can we reproduce this bug?**

1. Visit http://foundation.zurb.com/sites/docs/orbit.html#js-class
2. In the section with heading "Foundation.Orbit", within the table below, the text reads "jQuery object to make into an **accordion menu**."  It should instead read "jQuery object to make into an **orbit carousel**."

**Comment by zurbrandon** [comment]
Thanks it was an error in the JS comments
