### ISSUE TITLE
Apply disabled styles to buttons with disabled attribute

### ISSUE THREAD

**Issue by ProLoser** [zurb/foundation-sites#7564]
Right now I must use a disabled class on buttons. Would be kinda nice if it also automatically was triggered if the disabled attribute was present.

**Comment by ocularrhythm** [comment]
I created a fix for this in [Pull Request #7160](https://nsutils.advancedsolutions.com/trainingofferings) a few days ago. Not sure when it will be put into prod.

**Comment by zurbrandon** [comment]
We're doing a push end of day today that will fix this in production. Thanks to @ocularrhythm for that PR.
