### ISSUE TITLE
[Responsive Navigation] ISSUE NAME HERE

### ISSUE THREAD

**Issue by daren8888** [zurb/foundation-sites#7565]
**How can we reproduce this bug?**
1. Step one
Simply copy the code (into a basic html file) you have at http://foundation.zurb.com/sites/docs/responsive-navigation.html & http://foundation.zurb.com/sites/docs/top-bar.html

2. Step two
View the file in a browser. Look, menu doesn't work, The top <li> doesn't hide the <ul> below it.
3. Step three
Check the .../sites/docs/ page and then send Foundation a message

**What did you expect to happen?**

The drop down menu (this site uses Foundation 5) works: audreywingodds.com
The drop down menu (this site uses F 6) DOESN'T WORK gary.web4uinc.com

**What happened instead?**

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by kushalj** [comment]
this was working in 6.0.0:

```javascript
 * ResponsiveToggle module.
 * @module foundation.responsiveToggle
 * @fires ResponsiveToggle#init
function ResponsiveToggle(element, options) {
  this.options = $.extend({}, ResponsiveToggle.defaults, options);
ResponsiveToggle.defaults = {
ResponsiveToggle.prototype._init = function() {
ResponsiveToggle.prototype._events = function() {
  this.$toggler.on('click.zf.responsiveToggle', this.toggleMenu.bind(this));
ResponsiveToggle.prototype._update = function() {
 * @fires ResponsiveToggle#toggled
ResponsiveToggle.prototype.toggleMenu = function() {
     * @event ResponsiveToggle#toggled
    this.$element.trigger('toggled.zf.responsiveToggle');
ResponsiveToggle.prototype.destroy = function(){
Foundation.plugin(ResponsiveToggle);
```

but this isn't working in 6.0.5:
```javascript
 * ResponsiveToggle module.
 * @module foundation.responsiveToggle
 * @fires ResponsiveToggle#init
function ResponsiveToggle(element, options) {
  this.options = $.extend({}, ResponsiveToggle.defaults, this.$element.data(), options);
ResponsiveToggle.defaults = {
ResponsiveToggle.prototype._init = function() {
ResponsiveToggle.prototype._events = function() {
  this.$toggler.on('click.zf.responsiveToggle', this.toggleMenu.bind(this));
ResponsiveToggle.prototype._update = function() {
 * @fires ResponsiveToggle#toggled
ResponsiveToggle.prototype.toggleMenu = function() {
     * @event ResponsiveToggle#toggled
    this.$element.trigger('toggled.zf.responsiveToggle');
ResponsiveToggle.prototype.destroy = function(){
Foundation.plugin(ResponsiveToggle, 'ResponsiveToggle');
```

May be unrelated. Can't find anything else.

**Comment by pzi** [comment]
Codepen can be found here: http://codepen.io/anon/pen/QyOXdK

**Comment by rafibomb** [comment]
An example of the issue would really help determine a solution for this. Blank codepen http://codepen.io/rafibomb/pen/mVGEKm

**Comment by pzi** [comment]
Fair enough, looks like all my example needed was `$(document).foundation()`. Missed that section from [the docs](http://foundation.zurb.com/sites/docs/javascript.html#initializing) when I was setting it up.
