### ISSUE TITLE
[Button Proposal] add support for small-expanded...

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7570]
it would be nice to have classes for expanded on small medium large etc

**Comment by IamManchanda** [comment]
Even i think the same

**Comment by zurbrandon** [comment]
Do you have a usecase for this at all, It seems like a bit of an overkill for responsive sizes?

**Comment by designerno1** [comment]
2 buttons on medium and large in one row left and right on small expanded 2 rows

hm we could use normal grid with pull push.......

**Comment by zurbrandon** [comment]
This feels more like button groups with stacking, no?

**Comment by designerno1** [comment]
ok i see one case you have an button on medium and large left not full width and want to expand it for small because it looks great then it would be fine to have a breakpoint expanded classes you could use something like .row>.small-12.medium-2.columns and give the button expanded but thats 4 lines extra markup for a button
or do some extra scss with a breakpoint width 100% thats the simples way i think

**Comment by andycochran** [comment]
I can imagine a layout where a single button would only look good expanded on small and/or medium screen sizes. e.g.: On small, button expands to fill width screen. On medium, button expands to match width of sidebar. On large, the button looks ridiculous on the extra-wide sidebar.

**Comment by gakimball** [comment]
After discussing this internally, we decided we aren't interested in adding responsive versions of the stacking or expanding classes for button groups at the moment.

However, to make button groups a little more flexible, we will add a `.stacked-for-medium` class to button groups.
