### ISSUE TITLE
[Reveal] unexpected token when Ajax url 

### ISSUE THREAD

**Issue by Nikolaus91** [zurb/foundation-sites#7574]
**How can we reproduce this bug?**

1. Setup test modal
2. Paste ajax code sample from here: http://foundation.zurb.com/sites/docs/reveal.html
3. Watch

**What did you expect to happen?**

I want to display wordpress post in modal usiing ajax function. Post is under known url address

**What happened instead?**

Console returned an error: scripts.js:13 Uncaught SyntaxError: Unexpected token }

**Test case**
http://funlam.beectrl.com/
http://funlam.beectrl.com/statut-fundacji    <--- this should be inside modal
Click on the circle with "STATUT FUNDACJI" inside, what I want to do is to display post as modal content but console returns error instead.

My jQuery Code:

    jQuery('#statut').click(function() {
		var $modal = jQuery('#animatedModal1');

		jQuery.ajax({'/statut-fundacji'})
			.done(function (resp) {
				$modal.html(resp.html).foundation('open');
			});

	});

My HTML:

    <a id="statut" class="myCircle float-right trans20ms" data-toggle="animatedModal1" data-ajax="true"><span class="text-center"><?php the_title()?></span></a>

        <div class="reveal" id="animatedModal1" data-reveal data-close-on-click="true" data-animation-in="spin-in" data-animation-out="spin-out">
            <h1>Whoa, I'm dizzy!</h1>
            <p class='lead'>There are many options for animating modals, check out the Motion UI library to see them all</p>
            <button class="close-button" data-close aria-label="Close reveal" type="button">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

**Comment by zurbchris** [comment]
When using `jQuery.ajax()` you need to specify your method and a few other things. See [jQuery's Ajax Docs](http://api.jquery.com/jquery.ajax/) for more. It should probably look something like
```js
$.ajax({
  url: "test.html",
  context: document.getElementById('someReveal')
}).done(function(resp) {
  $( this ).html( resp );
});
```
