### ISSUE TITLE
Select Form Field CSS Double Border-Radius Property and Wrong Background Color

### ISSUE THREAD

**Issue by twd3** [zurb/foundation-sites#7576]
In the Foundation CSS the Select has some issues. Border-Radius is doubled up and this is the only form item with a background color set to #fafafa. I'm thinking that the background color by default should be #fefefe like all the rest and the doubled-up border-radius should be deleted.

**Comment by ocularrhythm** [comment]
Added a [pull request](https://github.com/zurb/foundation-sites/pull/7577)

**Comment by zurbrandon** [comment]
All fixed up! Thanks :)
