### ISSUE TITLE
How to create sticky topbar?

### ISSUE THREAD

**Issue by anik786** [zurb/foundation-sites#7578]
I wish to create a sticky topbar in Foundation 6.

In foundation 5 this was easy; simply add the "sticky" class to the top bar.

In Foundation 6 I believe you have to use the new "sticky" attribute like so:

```html
     <div data-sticky-container>
        <nav class="top-bar sticky" data-topbar role="navigation" data-sticky>
            <div class="top-bar-left">
                <ul class="menu">
                    <li class="menu-text"><a href="#">Website Name</a></li>
                </ul>
            </div>

            <div class="top-bar-right">
                <ul class="menu">
                    <li class="active"><a href="/">Home</a></li>
                    <!-- ... -->
                </ul>
            </div>
        </nav>
    </div>
```

However the top bar looks weird as it doesn't take the full width of the webpage.

What is the correct way of creating a sticky topbar in Foundation 6?

**Comment by zurbchris** [comment]
I've created a [demo codepen](http://codepen.io/zurbchris/pen/VeajrY) for this as well as a few other things. Please follow me on CodePen as I do several demos there, as well as tinkering of my own.

**Comment by anik786** [comment]
Thanks a lot, I'll check it out!

**Comment by hassanbinsafdar** [comment]
I found a solution and i hope you will enjoy it . what i find solution you can use this freely anywhere in page and it will work like foundation 5. foundation 6 is just bit tricky in sticky option okay here is code.

    <div id="try">
      <nav class="sticky-container" data-sticky-container>
        <div class="sticky" data-sticky data-top-anchor="try" data-btm-anchor="destroy:bottom" data-margin-top="0" data-margin-bottom="0">
        <div class="row columns">
            <div class="top-bar-left">
                love
            </div>
            <div class="top-bar-left">
                love
            </div>
            <div class="top-bar-left">
                love
            </div>
        </div>
        </div>
    </nav>
</div>

as you can i see i add a parent div like "try" you must have to do it to tell the sticky where sticky have to start so i used data-anchor-top="try" ok but if you only add this and leave it will go on top just scroll a page just a bit . for more i added data-btm-anchor="destroy:bottom" else your settings .

for bottom anchor you just have to add a div

<div id="destroy">
    finsihed
</div>

better this id you used in footer or use footer id if you want sticky have to move until end of page else anything you like hope you understand .

**Comment by karland** [comment]
@zurbchris Your [demo codepen](http://codepen.io/zurbchris/pen/rxMaoX) loses ist stickyness if you make the window narrower than 640px. The same holds for the example on the [sticky section](http://foundation.zurb.com/sites/docs/sticky.html) foundation website, where this example also sits. It also loses its stickyness, when you narrow the window such that the frame becomes smaller then 640px.

**Comment by karland** [comment]
OK, my fault. I found the solution to this as described in the docs. One need to define in the options, when sticky actually becomes sticky (default: medium):

```html
<div class="sticky" data-sticky data-options = "stickyOn: small">
```
