### ISSUE TITLE
Switch to clipboard.js

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7581]
Switch from ZeroClipboard to [clipboard.js](https://www.npmjs.com/package/clipboard-js) for the documentation code copy button.

**Comment by zurbrandon** [comment]
If anyone would like to add this into the docs to replace the former flash based one we'd love a PR.

**Comment by zenorocha** [comment]
+1 ;)

**Comment by colin-marshall** [comment]
@zenorocha great JS plugin! That was a painless transition and I was able to reuse the code from ZeroClipboard with a couple small tweaks.

**Comment by zenorocha** [comment]
Awesome, that's great to hear ;)

**Comment by gakimball** [comment]
Merged #7643 which implements this.

**Comment by zenorocha** [comment]
https://twitter.com/zenorocha/status/684424518782169088 ;)
