### ISSUE TITLE
Not Sure if This Media Object CSS is Right?

### ISSUE THREAD

**Issue by twd3** [zurb/foundation-sites#7583]
In the default CSS this media object css may be wrong:  

.media-object-section:last-child:not( + .media-object-section:first-child) {
    padding-left: 1rem; }

I am getting a unexpected token "+" error...around line 2285 in foundation.css.

While I'm here (sorry don't know if this is proper) I also found these in the foundation.css file:

.slider-handle -- position: absolute is doubled-up.

.button.dropdown::after -- is it display:block or display: inline-block? There is two...

**Comment by zurbrandon** [comment]
What are you using to compile your sass?

**Comment by twd3** [comment]
I'm going old school and just downloading the complete package from github. I'm using 6.0.5 but these have been in the foundation.css since v6.

**Comment by gakimball** [comment]
Yep, `:not(+ .class)` is invalid CSS. Replaced it with a functionally equivalent selector.
