### ISSUE TITLE
Equalizer: column heights incorrect on page load

### ISSUE THREAD

**Issue by tmartinco** [zurb/foundation-sites#7584]
Equalizer doesn't seem to be balancing my columns correctly when the page loads. It is adding unnecessary space to the bottom of each column. If I resize my browser window, the columns recalculate and all is kosher.

Columns on page load: https://i.imgur.com/ZX3VcqV.png
Columns after window resize: https://i.imgur.com/mjatdoa.png

Any ideas?

I asked ZURB via Twitter and was told the following could work:

`$('equalizerSelector').foundation('_reflow')`

I added a .reflow class to my data-equalizer div:

`<div class="row reflow" data-equalizer>`

And then added the suggested reflow to my $(document).ready():

`$(document).ready(function() {
	$('.reflow').foundation('_reflow');
});`

But it doesn't seem to be working.

Have I added that reflow correctly? Or is this a bug?

Running 6.0.6 – updated this morning.

:)

**Comment by twd3** [comment]
This is working without any added bottom space for me. Can you do a codepen or something because I'm thinking that it is your code.

**Comment by zurbrandon** [comment]
We have a big update coming to equalizer thats currently sitting on the 6.1 branch, if you'd like to check that out.

**Comment by zurbrandon** [comment]
I'll close this for now since it's been fixed up on the 6.1 branch that will be out soon! Thnaks for the report :)

**Comment by mdmullins** [comment]
This issue has returned for me on 6.2.3

**Comment by matthewhegarty** [comment]
I have similar issue in 6.2.0 - have posted to [forum](http://foundation.zurb.com/forum/posts/44948-data-equalizer-doesnt-work-on-page-load) but blocked by spam filter.

I am using jQuery to add to DOM after document ready (see [codepen](http://codepen.io/mash909/pen/vKkZmz)) - although this doesn't reproduce the issue, it shows what I am doing.

On page load: http://pasteboard.co/7JTe4mYqN.png

After resize event:  http://pasteboard.co/7JTZcTnWF.png

**Comment by mdmullins** [comment]
My solution to this was to workaround the jquery 3.0 deprecation of the .load(function in Foundation.js.
All incidents of this need to be replaced with on("load", function 
There is a fix for the next version of Foundation 6.x but for the time being you need to either replace this or downgrade Jquery to the 2.2.x version
