### ISSUE TITLE
Browsersync reloading for SCSS changes

### ISSUE THREAD

**Issue by neil-s** [zurb/foundation-sites#7585]
I don't have a complete understanding of this issue, so please forgive me if the following assumptions are wrong:

1) In normal usage, browsersync reloads the page if there have been changes to the HTML or JS, but injects the changes if they were purely CSS changes.
2) The Gulp file provided in the Zurb template calls the `browser.reload` task after every task, and this causes Browsersync to override the default behaviour.

The two points above are assumptions, but what I do know is that while the out-of-the-box Browsersync setup got me really excited at first, having the entire page reload and lose my position on the page because I change the color of an element, is frustrating. 

I imagine there was some reason for forcing a reload after each of the tasks?

**Comment by gakimball** [comment]
There's a pull request open at zurb/foundation-zurb-template#23 that addresses this. It's about there, just one pending issue with how BrowerSync works.
