### ISSUE TITLE
Equalizer: Cannot turn stacking off?

### ISSUE THREAD

**Issue by tmartinco** [zurb/foundation-sites#7586]
I've tried switching stacking off inside 6.0.6 by setting all equalizeOnStack references to false in the default files, but my columns are still stacking.

Is this a bug? I noticed @zurbrandon mentioned that Equalizer was being rewritten for 6.1, but figured I'd mention it just in case.

:)

**Comment by zurbrandon** [comment]
Yeah, this is currenrt;y sitting on the 6.1 branch if you'd like to check it out. 

We're adding a data-equalize-on="[breakpoint]" so you can use the Foundation named breakpoints to controll this.

**Comment by tmartinco** [comment]
That's awesome. Love your work!

:)

**Comment by zurbrandon** [comment]
Thanks! I'll close this now, since it's all sitting pretty on the 6.1 branch. 

Keep the bugs and PRs coming!

**Comment by Ne-Ne** [comment]
Hey @zurbrandon does this mean the equalize feature: 

```html
data-equalize-on="[breakpoint]"
```

Include medium up / small only / large only etc?

Also where does the 6.1 branch reside, if public?
