### ISSUE TITLE
Hollow button styles compiling when $button-fill = solid

### ISSUE THREAD

**Issue by umutahmet** [zurb/foundation-sites#7591]
_button.scss:228
```
@if $button-fill != hollow 
```
should probably be
```
@if $button-fill == hollow
```

**Comment by ocularrhythm** [comment]
I just set `$button-fill` to both `hollow` and `solid` and it compiled the buttons accordingly. This was on version `6.0.6`, what version are you using?

**Comment by umutahmet** [comment]
It's a weird one. This currently works fine for the docs but doesn't make sense when you only want one type of button. I would expect hollow buttons to only compile when $button-fill is set to hollow

I guess if both are required then maybe a third option "both" should be introduced to compile both solid and hollow?

**Comment by gakimball** [comment]
This is intentional. If `$button-fill` is `solid` (the default), we still give you `.hollow` as a secondary style so you can mix them. If `$button-fill` is `hollow`, hollow becomes the new default, and the dedicated `.hollow` class goes away.
