### ISSUE TITLE
Gutter size setting in custom download has no effect

### ISSUE THREAD

**Issue by two2clicks** [zurb/foundation-sites#7593]
Changing gutter size setting on custom CSS download shows no effect in the compiled CSS

http://foundation.zurb.com/sites/download/#customizeFoundation

**Comment by gakimball** [comment]
Paging @erikmellum

**Comment by gakimball** [comment]
Rolling this into #7033

**Comment by mizukimadness** [comment]
Changing the gutter size setting doesn't work for me. I've tried downloading with Firefox and Chrome several times over the past few weeks. Changing the max width works, though!

**Comment by erikmellum** [comment]
@mizukimadness I will take a look at this on Monday evening. Unfortunately I won't be able to fix it before then. Sorry for any inconvenience there, but be patient and I'll get it fixed for you as soon as I can!
