### ISSUE TITLE
flex-grid: -webkit -and -ms-prefix for flex-properties

### ISSUE THREAD

**Issue by codemonkey1988** [zurb/foundation-sites#7594]
Because of missing -webkit- and -ms- prefixes, the flex-grid does not work in IE10 or Safari 8.

**Comment by gakimball** [comment]
Your build process needs [Autoprefixer](https://github.com/postcss/autoprefixer). If you're using one of our starter project templates, it's built-in. If not, you need to add it to your build process. The Autoprefixer README has a big list of integrations.
