### ISSUE TITLE
Strange problem with border divs in different sizes

### ISSUE THREAD

**Issue by jesusruiz** [zurb/foundation-sites#7599]
Hello and congratulations for the work done with Foundation.

I have a strange problem, which occurs with the borders of DIVS together. But this problem only occurs in certain sizes (resizing the viewport). In the picture you can see the detailed problem.
I do not know if this problem is a bug.
The design is outdated designs for today, but I think it should not be problems.

![error](https://cloud.githubusercontent.com/assets/1318254/11876048/ed75545c-a4e7-11e5-9c5f-107d5765537b.png)

The problem occurs when a div has a different size to the other divs. The other option is that occurs when using the "end" class for DIV4. It might also be a bug in the browser to redraw widths.

URL to see the problem:
http://centronovalaser.com/foundation606/index-test-error.html

Code:
http://codepen.io/drlynch/pen/YwqqOg

Download Code:
http://centronovalaser.com/Foundation606code.zip

A greeting.

**Comment by zurbrandon** [comment]
I'm not 100% sure how to solve this, since it's a browser rounding issue.

You can read about how browsers do pixel rounding here
http://cruft.io/posts/percentage-calculations-in-ie/
