### ISSUE TITLE
[Dropdown] Doesn't work with absolutely-positioned elements

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7601]
If a dropdown trigger is `position: absolute`, the dropdown won't be able to anchor to it properly. In my testing, the dropdown becomes full-width and anchors to the top-left of the page. Even if you restrain the width in CSS with an `!important` `width` setting, the dropdown is still sitting to the far left.

**Comment by Owlbertz** [comment]
Seems to be fixed already, see http://codepen.io/anon/pen/LkQmVd.
