### ISSUE TITLE
Cannot import _settings.scss file using zurb:foundation-sites meteor package

### ISSUE THREAD

**Issue by zayaisshawn** [zurb/foundation-sites#7602]
This meteor package bundled with latest version of fourseven:scss package. I followed the instructions on how to import _settings.scss file. Gives me this error.
media query expression must begin with '('

**Comment by juliancwirko** [comment]
I have copied the _settings.scss file to my project (from the new 6.0.6 version). 
In the `_settings.scss` file I have changed the `util` import to `@import '{zurb:foundation-sites}/scss/util/util';` Then in my main.scss file I have:

```
@import 'settings';
@import '{zurb:foundation-sites}/scss/foundation';
@include foundation-everything;
```
And it works as it should. 

Maybe you have some errors with your custom styles? I think there is needed more info from you in this case.

**Comment by zayaisshawn** [comment]
Sorry my bad, it is working now. Can I ask, how do you autoprefix your generated css? 'fourseven:scss' package doesn't include autoprefixer anymore. Any idea? I'll close this issue now.

**Comment by juliancwirko** [comment]
You can use my package for PostCSS. Autoprefixer is just a PostCSS's plugin. https://atmospherejs.com/juliancwirko/postcss 

Or you can use the same approach but only with Autoprefixer without the possibility to use other PostCSS plugins: 
https://atmospherejs.com/seba/minifiers-autoprefixer

**Comment by zayaisshawn** [comment]
Right now I'm using https://atmospherejs.com/stolinski/stylus-multi. This stylus package comes with nib and postcss and bunch others. Seems to be working fine. Thank you for your help.

**Comment by juliancwirko** [comment]
This package will only autoprefix your css code from `.styl` files. If this is what you need it's ok. The packages which I linked above will autoprefix all css no matter which preprocessor you will use. Also standard CSS. 

Also stolinsky:stylus-multi is based on an old build plugin, you can compare the new one from official stylus package: https://github.com/meteor/meteor/blob/devel/packages/stylus/plugin/compile-stylus.js and the one from stolinski:stylus-multi: https://github.com/stolinski/meteor-stylus-multi/blob/master/plugin/compile-stylus.js
