### ISSUE TITLE
Foundation-cli watch project - question

### ISSUE THREAD

**Issue by vallyol** [zurb/foundation-sites#7607]
Hi all!
In my OS installed the following components:
![zf-cli192](https://cloud.githubusercontent.com/assets/11002949/11890814/947046be-a569-11e5-84f1-f872a395cb07.png)
When you create a new project using the basic template, the terminal throws an error and hangs:
![zf-cli187](https://cloud.githubusercontent.com/assets/11002949/11890848/eae5d43c-a569-11e5-9523-50bad8682b0a.png)
If I use the Zurb template, the project started to work. But the same error is present:
![zf-cli193](https://cloud.githubusercontent.com/assets/11002949/11890900/60066b32-a56a-11e5-8b3a-b1cd5a8498a6.png)
I tried delete the row util/util. 
Tried to set the path to the directory util in the _settings file.scss when working with zurb template... (../../libraries/foundation-sites/scss/util)
The result - zero :(
But... If I intend to use a basic template... What to do? No util directory when you create a new project in the project folder does not appear.

**Comment by gakimball** [comment]
Can you verify that Foundation was installed through Bower? In your project folder, you should have a folder called `bower_components/foundation-sites`.

**Comment by vallyol** [comment]
**gakimball**, thanks!
The directory structure in the project folder:
![zf-cli195](https://cloud.githubusercontent.com/assets/11002949/11906007/af5b425a-a5da-11e5-851f-4d7023868665.png)
Libraries Folder is the work of bower (v. 1.5.3).
I renamed it to the bower_components - the problem disappeared. Thanks!

P.S. As to why on my system the packages are downloaded to the directory libraries - I will understand. As I recall, it was since installing bower...

**Comment by gakimball** [comment]
@vallyol Some folks' Bower is configured to name the folder something different, like `vendor`, `libraries` in your case, etc.

I updated the [Basic](309b518b2eebf8b24a831bcf4d77de23128aa3ac) and [ZURB](https://github.com/zurb/foundation-zurb-template/commit/195c7d28f3d2306a2eb005186316de52058d0334) templates with a `.bowerrc` file, which will make dependencies always install in a folder called `bower_components`, regardless of how your Bower is configured globally.

**Comment by vallyol** [comment]
**gakimball**
Thank you! Your team is the best!
**To All**
If you have the same problem with the default directory for bower components, see the file ~/.bowerrc. In my case it was so:
```
{
  "directory": "libraries"
}
```
