### ISSUE TITLE
[Orbit] why bullets have to be button

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7609]
```js
Orbit.prototype._loadBullets = function(){
    this.$bullets = this.$element.find('.' + this.options.boxOfBullets).find('button');
  };
```
maybe we could specify a option for bullet element or class?

**Comment by zurbrandon** [comment]
This is for accessibility reasons, so we're not too keen on making it an option. We chat about this a bit here: http://foundation.zurb.com/sites/docs/button.html
