### ISSUE TITLE
[Breakpoint] small down works no longer

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7613]
```scss
@include breakpoint(small down) {
}
```
works no longer for me

**Comment by Ne-Ne** [comment]
I think there is an issue open already for this https://github.com/zurb/foundation-sites/issues/7587.

**Comment by designerno1** [comment]
thanks
ok we can use
```scss
@include breakpoint(small only) {
}
```
but small down should also work

**Comment by Pautomagi** [comment]
Sorry for asking, but in what context would you use small down ? Or do you mean that small down should be the same as small only ?

**Comment by designerno1** [comment]
small down and small only is thematically the same, i just used small down, and wonder why it isn't working any more

**Comment by TvrtkoM** [comment]
@Pautomagi there's this sass code for top-bar which is already pushed to develop branch:

    @ each $size in $breakpoint-classes {
        .stacked-for-#{$size} {
            @ include breakpoint($size down) {
            @ include top-bar-stacked;
         }
      }
    }


The way breakpoint mixin works now one more scss rule would need to be written specifically for 'small only'

Currently ,there's also inconsistency between sass ports. 'stacked-for-small' transpiles to css without media query when ruby-sass is used, although node-sass transpiles to media query css - Foundation.

**Comment by gakimball** [comment]
The `x down` breakpoints mean "x *and* down", so yeah, `small down` is functionally identical to `small only`. The issue of `small down` not printing a breakpoint has been fixed I believe, so I'm going to close this in favor of #7587.
