### ISSUE TITLE
Creating custom Media query between $breakpoints

### ISSUE THREAD

**Issue by Ne-Ne** [zurb/foundation-sites#7614]
I am trying to find a way to turn this into the correct em media query, min = 640px & max = 1199px:

```scss
@media screen and (min-width: map-get($breakpoints, medium)) and (max-width: map-get($breakpoints, xlarge) - 1px){...}
```

or

```scss
@media screen and #{breakpoint(medium)} and #{breakpoint(xlarge)}{...}
```

or

```scss
@media screen and (min-width: -zf-bp-to-em(map-get($breakpoints, medium))) and (max-width: -zf-bp-to-em(map-get($breakpoints, xlarge)){...}
```

While I am new to core sass functions I want to use foundation as much as possible and leverage the $breakpoints as much as possible. However apart from creating my own px media query, there doesn't seem to be much support to target css selectors between ranges.

Unless I have not read the documentation properly...

**Comment by gakimball** [comment]
Here's how you can do it. Note that the second breakpoint is `xlarge down`, which creates an upper bound for the media query. The way your second example is written, both media queries are `min-width`, but to create a range, you need a `min-width` and a `max-width`.

```scss
$query: 'screen and #{breakpoint(medium)} and #{breakpoint(xlarge down)}';

@media #{$query} {
}
```

Eventually the `breakpoint()` mixin will be updated to allow for multiple ranges, which you'd write like this:

```scss
// Range includes medium, large, and xlarge
@include breakpoint(medium, xlarge) {
}
```

Some differences in behavior between Ruby Sass and Libsass prevented the feature from shipping right away.

**Comment by Ne-Ne** [comment]
Thanks for the response @gakimball, would it worth adding this to the docs?

It seems very simple to understand after a written example.

**Comment by gakimball** [comment]
Good idea! Done: c6f2e635b5dde29e5e67557d76fec201fcb2bcc9
