### ISSUE TITLE
[The Grid] Uncentering is not working properly

### ISSUE THREAD

**Issue by kurzweg** [zurb/foundation-sites#7616]
**How can we reproduce this bug?**
1. Step one
Create a new foundation for sites project

2. Step two
Use the following HTML
<div class="row">
	<div class="small-9 small-centered medium-6 medium-uncenter large-4 large-uncenter columns">
		<div style="height: 300px; background: red;" ></div>
	</div>
	<div class="small-9 small-centered medium-6 medium-uncenter large-4 large-uncenter columns">
		<div style="height: 300px; background: green;" ></div>
	</div>
	
	<div class="small-9 small-centered medium-6 medium-uncenter large-4 large-uncenter columns">
		<div style="height: 300px; background: blue;" ></div>
	</div>
</div>

**What did you expect to happen?**
On small-screens:
1 row and 3 centered blocks that each span 9 columns

On medium-screens:
2 row one with 2 blocks and one with 1 blocks on the left. Each block spans 6 columns

On large-screens:
1 row one with 3 blocks each block spans 4 columns

**What happened instead?**
See screenshot
<img width="1616" alt="bildschirmfoto 2015-12-18 um 14 30 03" src="https://cloud.githubusercontent.com/assets/805481/11897913/e91023ae-a593-11e5-9d74-43ddbcebea89.png">

**source of issue**
My guess ist that the issue comes from the "small-centered" class come directly withe the "column" class attached ( .column.small-centered) while the "xxx-uncenter" class comes with no attached class.

**Comment by Pautomagi** [comment]
This is already reported in  #7183 and fixed for the v6.1

**Comment by kurzweg** [comment]
Awesome, thanks!
