### ISSUE TITLE
[Dropdown] Incomplete doc page

### ISSUE THREAD

**Issue by AlexLaforge** [zurb/foundation-sites#7617]
**How can we reproduce this bug?**
The link to "Learn more about how JavaScript plugins are initialized." leads nowhere.
This Help page should be updated. As many many others in ZF6 : clearly incomplete. Missing references, like data-is-click="false" and so on ....

**What did you expect to happen?**
Have complete doc.

**What happened instead?**
Have partial doc.

**Comment by zurbchris** [comment]
Should be fixed!
