### ISSUE TITLE
Move from Ruby scss-lint to Node sass-lint

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7620]
There's now a Node-powered Sass linting library, appropriately called [sass-lint](https://github.com/sasstools/sass-lint). Right now we're using gulp-scss-lint, which is a wrapper around the Ruby-based [scss-lint](https://github.com/brigade/scss-lint).

Let's migrate our linting config file to sass-lint and drop that Ruby dependency.

**Comment by colin-marshall** [comment]
I'm on it.

**Comment by colin-marshall** [comment]
Using this: http://sasstools.github.io/make-sass-lint-config/

It came back that these are not supported yet in sass-lint:
```yml
# The following scss-lint Linters are not yet supported by sass-lint:
# ElsePlacement, PropertyCount, SelectorDepth, UnnecessaryParentReference
# VendorPrefixes, Compass::*
# 
# The following settings/values are unsupported by sass-lint:
# Linter Indentation, option "allow_non_nested_indentation"
# Linter Indentation, option "character"
# Linter PropertySortOrder, option "separate_groups"
# Linter SpaceBeforeBrace, option "allow_single_line_padding"
```

Should I still proceed or should we wait until these are added to sass-lint?

**Comment by gakimball** [comment]
Hmm, I like SelectorDepth, but maybe if a big open source project adopts sass-lint we can press them to add more linters ;)

Go ahead and keep working on the implementation. I'll do some linting with the existing file today just so everything is up-to-date.

**Comment by colin-marshall** [comment]
I know they plan on adding PropertyCount: https://github.com/sasstools/sass-lint/issues/406

I will open an issue over there and see what's up.

**Comment by colin-marshall** [comment]
@gakimball: We got a great response from @DanPurdy: https://github.com/sasstools/sass-lint/issues/457#issuecomment-165935624

I can open up some new issues over there for specific Linter requests. Besides SelectorDepth are there any other important ones you would like before the switch can happen?

**Comment by gakimball** [comment]
We can do the switch right now and I'll keep tabs on the library as it develops.

**Comment by gakimball** [comment]
Also it looks like `nesting-depth` covers what `SelectorDepth` is doing.

**Comment by colin-marshall** [comment]
There is a problem with making the switch right now. sass-lint throws a parse error when there is a string interpolated on a CSS property so it doesn't complete the linting process. I opened a new issue on the gonzales-pe repo to get this fixed: https://github.com/tonyganch/gonzales-pe/issues/140

**Comment by gakimball** [comment]
Thanks man! Loving your dedication :)

Have you gotten any swag from us? Email me at geoff@zurb.com your home address and I can hook you up in the next few weeks.

**Comment by colin-marshall** [comment]
No problem! Glad I can help out on an amazing project like Foundation :)

Rafi shot me an email earlier this month asking for my address to send me a t-shirt. Looking forward to receiving it. Thanks @gakimball!

**Comment by SalahAdDin** [comment]
:+1:

**Comment by colin-marshall** [comment]
Update: I think when the PR https://github.com/sasstools/sass-lint/pull/459 gets merged we should be able to use this.

**Comment by gakimball** [comment]
@colin-marshall Looks like that issue was merged! I'm itching to remove this Ruby dependency :) You want to finish the integration?

**Comment by colin-marshall** [comment]
@gakimball it was more complicated than I initially thought. That PR was merged but now instead of breaking during linting when it comes across an SCSS file with string interpolation, it gives an error and processes the next file. So close to half of the files aren't linted at all and show a fatal error.

The AST sass-lint uses ([gonzales-pe](https://github.com/tonyganch/gonzales-pe)) fixed the interpolation issue for us (https://github.com/tonyganch/gonzales-pe/issues/140), but sass-lint is using an older version of `gonzales-pe` and is nearly ready to update to the latest version. I was waiting until the issue https://github.com/sasstools/sass-lint/issues/495 is resolved which will allow sass-lint to use the latest version of gonzales-pe. It should be any day now.

I'll put in a PR tomorrow so you can see if you want to merge it as is or wait until sass-lint gets updated to 1.6.0.

**Comment by DanPurdy** [comment]
Hi guys, yeah just to add that the delay in 1.6 is currently down to me updating the last rule to the new gonzales structure. I'm hoping to find some time this week / weekend to update it and then 1.6 should be released. I would hold off until 1.6 is out as it does fix a lot of the main issues we have with parsing files etc.

**Comment by gakimball** [comment]
@DanPurdy Awesome, thanks for the update :)

**Comment by colin-marshall** [comment]
@DanPurdy thanks for the hard work you guys have been putting in to get the update out!

**Comment by colin-marshall** [comment]
**Update:** Shout out to @DanPurdy, @bgriffith, and the @sasstools team for their hard work to finish and release v1.6 of sass-lint. I just added 1.6 to my node-sass-lint branch and lots of files that were throwing fatal errors are now being linted. We're still experiencing fatal errors with 6 of our files, so I'm going to hold off on merging my branch until we can get the rest of those linting.

I've opened these 2 issues on sass-lint:
https://github.com/sasstools/sass-lint/issues/643
https://github.com/sasstools/sass-lint/issues/644

And @DanPurdy opened this one up for me on https://github.com/tonyganch/gonzales-pe:
https://github.com/tonyganch/gonzales-pe/issues/169

**Comment by colin-marshall** [comment]
Merged and closed.
