### ISSUE TITLE
Bower ignores settings.scss file

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites#7622]
In 6.0.6, Bower is set to ignore the settings.scss file. This causes the settings.scss file not to update.

**Comment by paper9oll** [comment]
@JeremyEnglert same issue here

**Comment by ErykJaroszewicz** [comment]
And here! Why settings.scss is now set to ignore in installation?

**Comment by geraldnako** [comment]
I have the same problem.
I think if someone wants to change settings.scss it need to be copied inside your assets or somewhere else outside bower_components.

There is no reason to add this file inside .gitignore
