### ISSUE TITLE
[Responsive Navigation] accordion medium-dropdown is-active

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7625]
**How can we reproduce this bug?**
use a responsive menu with accordion medium-dropdown and add "is-active" class to a submenu

**What did you expect to happen?**
the is-active ul to be open on resize from medium to small

**What happened instead?**
 is-active ul is closed on resize to small if you start on small the is-active is open

i think it's becaus when loaded in medium the dropdown removes the is-active class

**Comment by zurbchris** [comment]
This was intentional, because the responsive nav relies on each plugin's `destroy` method to clean up everything. That being the case, a solution to this issue would be tricky and probably require a lot of code.

**Comment by designerno1** [comment]
ok i close this, because this is also an very very special usecase
