### ISSUE TITLE
Custom $global-font-size and $rem-base

### ISSUE THREAD

**Issue by RustBeard** [zurb/foundation-sites#7626]
If I set `$global-font-size` and `$rem-base` to custom value, e.g. `14px`, I have two (now noticed) problems: 
1. Bad calculated grid
2. Bad calculated breakpoints

To fix it: 
1. In _settings.scss paste `$global-font-size` and `$rem-base` before `@import 'util/util';`
2. Also in _settings.scss in `$breakpoints();` change breakpoint value to `((val_in_px / 16) * 1rem)`

**Comment by ocularrhythm** [comment]
This is a known bug that is being addressed internally. The `_settings.scss` is generated through octophant. [Read more about it here](https://github.com/zurb/foundation-sites/pull/7496#event-492552960)

**Comment by gakimball** [comment]
#7580 addresses this. `$rem-base` is being removed in favor of using `$global-font-size` for everything. In addition, `$global-font-size` can be changed without affecting the widths of breakpoints or the grid.

We're putting out 6.1 tomorrow, which will include this fix.
