### ISSUE TITLE
Basic Foundation 6 Install with SASS

### ISSUE THREAD

**Issue by webkenny** [zurb/foundation-sites#7627]
Ok, so I have pored over the documentation and searched the corners of the web but I can't wrap my head around what feels like it should be simple. I am building a site using Drupal 8 and would like to use Foundation 6 as the basis for my custom theme. I prefer SCSS over vanilla CSS.

What are the bare minimum files I should be downloading? I don't need a compiler or templates or any of that. Just the SCSS and JavaScript. I would like to have the entire framework available to me and I'll just load what I need as I need it.

In other words, is there some kind of zip file I can just download and stick somewhere without all of these myriad node_modules folders, etc? jQuery is already part of Drupal so I don't need that either. Just Foundation as it stands.

This was a cinch with Foundation 5 but with 6 it seems so convoluted. Maybe I'm just not understanding? (Very possible, nay likely. :) )

Thanks much!

P.S. Of course ideally I would have used Composer for this, since Drupal 8 does, but as another issue points out, Packagist isn't cooperating with Zurb on that.

**Comment by SalahAdDin** [comment]
Did you see in the documentation? You can install foundation with npm and then use it for create a basic or full foundation build.

**Comment by vallyol** [comment]
As well?
```
php composer.phar require zurb/foundation-sites
```
https://github.com/zurb/foundation-sites#setup
You will receive all scripts and components... No?

**Comment by webkenny** [comment]
I did end up finding my way by picking apart the Foundation for Sites download. :) Thanks very much for your reply. When composer finally gets worked out, I'll switch to that method. Thanks again!

**Comment by featherbelly** [comment]
Any pointers as to how you "picked it apart". I'm about to do the same thing... Want to use as much of the built in Foundation goodness as possible...
