### ISSUE TITLE
[Abide] Textarea tag not supported

### ISSUE THREAD

**Issue by foodgy** [zurb/foundation-sites#7638]
```<textarea required></textarea>``` not supported by Abide.
Why so? It's valid html5 attribute.

**Comment by briantan888** [comment]
Abide is incomplete 6.0.x. Will be addressed in 6.1 together with many other issues.

**Comment by gakimball** [comment]
Yep, we have a few open PRs which will address this and many other issues. 6.1 is coming out tomorrow!

**Comment by zurbchris** [comment]
Fixed with 6.1
