### ISSUE TITLE
[Reveal] Wrong position calcultion when AJAX

### ISSUE THREAD

**Issue by Nikolaus91** [zurb/foundation-sites#7639]
**How can we reproduce this bug?**

1. Set a modal
2. Remove static content
3. Add ajax content call

My modal HTML:

 <a id="statut" class="myCircle float-right trans20ms" data-toggle="statut_fundacji"><span class="text-center"><?php the_title()?></span></a>

        <div class="reveal" id="statut_fundacji" data-reveal style="min-height: 200px">

            <button class="close-button" data-close aria-label="Close reveal" type="button">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

I have expected modal to load in correct position, about 100px from window's top, instead modal was displayed in the middle. I figured out that's happening beacuse of ajax call for content in the modal. Modal is empty once it's triggered by the button, and the content is displayed after the modal calculate it's position (thanks to AJAX call) in about 40% of cases. For static content this issue did not occured.

![show](https://cloud.githubusercontent.com/assets/10107362/11925476/f193f4fe-a7bb-11e5-813a-935785f7c22a.png)

Here's how i call for content when the button is clicked:

//Ajax call for content dla Statut Fundacji
    $("#statut").click(function () {

        $("#statut_fundacji").load("/statut-fundacji #statut_fundacji");

    });

**Test case**

Push the orange circle with "Statust fundacji inside":

http://funlam.beectrl.com/

**Comment by phenix-factory** [comment]
The doc is really poor on Ajax and reveal. But you should try this:

```javascript
$("#statut").click(function () {
    e.preventDefault();
    e.stopPropagation();

    $("#statut_fundacji").load("/statut-fundacji #statut_fundacji", function () {
          $(this).foundation("open");
     );
});
```

**Comment by Nikolaus91** [comment]
Seems to work fine! Thank you :+1:

**Comment by phenix-factory** [comment]
Nice, i have add somes comments in the code. It look better now :)

**Comment by Nikolaus91** [comment]
There is one bracket - } missing at the end, right after ("open");

**Comment by phenix-factory** [comment]
Right, my bad. Just updated the code :)

**Comment by gakimball** [comment]
@phenix-factory Thanks so much for your help!

@zurbchris If we can borrow any of this code to improve our Reveal/AJAX example, let's do it.

**Comment by Nikolaus91** [comment]
I found another issue on mobile, while testing in chrome I am not able to scroll down (setttings for iphone 5), on real iphone 5 - Safari & Chrome I am able to scroll through content but the whole modal has very weird position - top: --371px and it looks like z-index never worked before because of this you are able to read only part of modal content, the rest of it is behind the window edges.

Here's my JS for modal:

     var $loading = $('#loadingDiv').hide();
    $(document)
        .ajaxStart(function () {
            $loading.show();
        })
        .ajaxStop(function () {
            $loading.hide();
        });

    //Ajax call for content dla Statut Fundacji
    $("#statut").click(function (e) {

        // Stop everything, including the reveal openning even
        e.preventDefault();
        e.stopPropagation();

        // Ajax, load the content in the reveal modal
        $("#statut_fundacji").load("/statut-fundacji #statut_fundacji", function () {
            // Tell foundation to open the reveal now
            $(this).foundation("open");
        });
    });

You can still view it here: http://funlam.beectrl.com   <--- Click on "Status Fundacji" circle

I tried to mess with css a little but without any success.

**Comment by foodgy** [comment]
Don't know why, but my modals with ajax loaded content are not properly vertically centered even with this <a href="https://github.com/zurb/foundation-sites/issues/7639#issuecomment-166226999">solution</a>. Foundation 6.1.2.

**Comment by Nikolaus91** [comment]
Same trouble here, with or without Ajax there is something wrong. Tried to add modal with DotPay form, but even withuot the form, with only pure html it positions itself in the center of the whole page not window as it should.

@zurbchris any ideas what can be wrong, I guess you made some tests during development so you may have a tip or an answer.

Best regards

**Comment by zurbchris** [comment]
Try using the update-reveal branch. I changed how the modal is positioned. 
If using bower:
```bash
$ bower install foundation-sites#update-reveal --save
```

**Comment by foodgy** [comment]
@zurbchris same result for me

**Comment by Nikolaus91** [comment]
@zurbchris not tried yet, I will give a response till end of week

2016-02-08 15:07 GMT+01:00 foodgy <notifications@github.com>:

> @zurbchris <https://github.com/zurbchris> same result for me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zurb/foundation-sites/issues/7639#issuecomment-181384101>
> .
>



-- 
Z poważaniem,

Mikołaj Koropecki


Design & Software
Development House
----------------------------
mob: +48 500 401 730
e-mail: mk@beectrl.com

**Comment by foodgy** [comment]
@zurbchris update: works fine :)
