### ISSUE TITLE
[Accordion, SCSS] item padding is applied only

### ISSUE THREAD

**Issue by LeRisto** [zurb/foundation-sites#7640]
I'm just starting to use Foundation (6.0.6) with SCSS, so bear with me if i'm totally wrong here.

I observed that the `$accordion-item-padding` option is applied to both the accordion items `a` and `content` node, while `$accordion-content-padding` is ignored. Thus it is not possible to style both items padding independent.

**Comment by gakimball** [comment]
Typos! Thanks for catching that. :)
