### ISSUE TITLE
[general] Outputting Foundation credits/charset rule

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites#7641]
I'm working on a WordPress Foundation starter theme which I hope to release soon!
I have 2 issues that I want to try and solve, purely for aesthetic reasons really.

### Foundation credits
When importing the foundation file through Sass, we get the version and credits as a comment. I understand the reason for this, but I credit Zurb elsewhere in the project, and its being output in the stylesheet when I'd prefer not to (I have the WordPress theme details, description at the top already). I have a patch ready to submit for a PR for this, pending a response from point 2...

### charset rule
The other issue I can't work out is the `@charset "UTF-8";` declaration that appears at the top of the stylesheet (above the WordPress required theme details). Is there any way we could choose where to include this, or include it in global styles? I'm sure there's a good reason not to do this but I'd love to know either way!

**Comment by gakimball** [comment]
The version is necessary for our CSS/custom downloads, as it helps us figure out what version someone is using when debugging issues. Would your patch just remove the comment? Unfortunately it would be difficult for us to justify that for one use-case.

The `@charset` [declaration](https://developer.mozilla.org/en-US/docs/Web/CSS/@charset) has to be the very first thing in a stylesheet. For that reason, we don't put it in Foundation itself; however, in our template projects, we put it at the very top of the `app.scss` entry file. (See an example [here](https://github.com/zurb/foundation-sites-template/blob/master/scss/app.scss).)

**Comment by brettsmason** [comment]
Thanks @gakimball - I fully understand about the comment and why you would need it. My idea was this [commit](https://github.com/brettsmason/foundation-sites/commit/f8851ebf2c2997cd82d978204948b8903463b008). Basically a variable that if true (on by default) would output the comment. I thought this would cover the css/custom downloads as it would be there by default. What do you think?

Thats strange about the `@charset` - I don't define it anywhere in a stylesheet, but its appearing at the top of the compiled stylesheet. Not to worry I'll investigate further!

I have another question about the Motion UI includes (`@include motion-ui-transitions;
@include motion-ui-animations;`) but I guess thats better to raise over there? They seem to be outputting the css at the top of my stylesheet, even though they are at the bottom.

I look forward to giving back by releasing my theme soon!

**Comment by gakimball** [comment]
Looking forward to seeing your theme for sure :) We're building up a new list of F6-specific resources and we can add it there.

As for the poster comment thing, it's just too specific of a feature to justify having in the codebase. If you need to remove the comment, there are tools that can strip CSS comments, either standalone or as part of a code compressor.

The Motion UI thing is an unfortunate side-effect of how `@extends` works. There might be a way to fix it, though. If you want to open an issue at zurb/motion-ui we can discuss it.
