### ISSUE TITLE
Magellan not working on devices smaller than 768px

### ISSUE THREAD

**Issue by paper9oll** [zurb/foundation-sites#7655]
Hi All,

Magellan is not working properly on device smaller than 768px in viewport sizing ... magellan will display just like a static top bar on device smaller than 768px but works just fine when viewport is above 768px.

One can reproduce the problem using your device (don't use tablets) by heading to [foundation magellan documentation] (http://foundation.zurb.com/sites/docs/magellan.html) and just scroll down.

I have tried out using rMBP, iPhone 6 Plus and iPad Air.

Feel free to comment if this affects you or not.

**Comment by zurbchris** [comment]
I don't know that this is a bug. It's sticky default settings to stick on medium-up, that's probably what's causing it.

**Comment by paper9oll** [comment]
@zurbchris is there a way to change the settings?

**Comment by zurbchris** [comment]
for sticky:
```html
<div class="sticky" data-sticky data-options="stickyOn: small;"> ...
```
or with JS
```javascript
  Foundation.Sticky.defaults.stickOn = 'small';
  $(document).foundation();
```

**Comment by paper9oll** [comment]
alright thanks you

**Comment by Arkentus** [comment]
zurbchirs tank you a lot !
