### ISSUE TITLE
[reveal] keystrokes not working in form inputs inside a reveal.

### ISSUE THREAD

**Issue by idybil** [zurb/foundation-sites#7657]
Hi, 

I have a form in a reveal modal, but I can types any words in input boxes anyone has the problem ?

**Comment by idansh** [comment]
Yes, it happens to me the second time the modal is opened. I am searching for a quick fix for this.

**Comment by idybil** [comment]
As a temporary workaround, I commended everything about Foundation.Keyboard.* in the foundation.reveal.js javascript code.

**Comment by idybil** [comment]
The problem seems to be fixed with the release of version 6.1.0

**Comment by zurbchris** [comment]
Not seeing this issue. Can you verify with a codepen or fiddle?

**Comment by idybil** [comment]
Hi @zurbchris , I think you can close this issue since version 6.1, the bug does not appear anymore.

**Comment by jacobalvarez** [comment]
@zurbchris I replicated the issue with [this CodePen](http://codepen.io/anon/pen/qbpyPM).

**Comment by bevdam** [comment]
Yeah @jacobalvarez  That is the same issue. I am having , Where you able to find anything?
