### ISSUE TITLE
Inconsistent use of column/columns in flex-grid

### ISSUE THREAD

**Issue by DerFrenk** [zurb/foundation-sites#7658]
In the flex-grid docs, the [Automatic Stacking](http://foundation.zurb.com/sites/docs/flex-grid.html#automatic-stacking) part contains the following HTML example:

    <div class="row medium-unstack">
      <div class="columns">One</div>
      <div class="columns">Two</div>
      <div class="columns">Three</div>
      <div class="columns">Four</div>
      <div class="columns">Five</div>
      <div class="columns">Six</div>
    </div>

In the example the column classname is ``columns``, but when I check https://github.com/zurb/foundation-sites/blob/master/scss/grid/_flex-grid.scss#L145 only ``.column`` will be generated.

This problem also applies to this [recently merged pull request](https://github.com/zurb/foundation-sites/commit/22fc8c1d6716c3f7c0d2fd9d11e02f09fdbe8705). Only ``.column`` classes are generated, while the [docs pull request](https://github.com/zurb/foundation-sites/commit/f85727f4eab7cea8b90fe4100d89431e2d382c57) contains ``.columns`` in the code example.

**Comment by gakimball** [comment]
Good catch, I'll get this fixed before 6.1 is out today.
