### ISSUE TITLE
Second slider handle exceeds container dimensions

### ISSUE THREAD

**Issue by JoshFabian** [zurb/foundation-sites#7660]
When the second handle is at the far right side of the slider, it doesn't align as neatly as the first (left-hand) handle does.

In the following image, you can see how neatly the left-side aligns with the horizontal rule, particularly compared to the right-side.
![](http://cl.ly/1t2l291P2Y0g/Screenshot%202015-12-22%2016.49.58.png)

**Comment by andycochran** [comment]
Something like this would fix it… 
```
.slider {
  margin-right: $slider-handle-height*0.5;
  box-shadow: $slider-handle-height*0.5 0 0 $slider-fill-background;
  &.vertical {
    margin-bottom: $slider-handle-height*0.5;
    box-shadow: 0 $slider-handle-height*0.5 0 $slider-fill-background;
  }
}
```
