### ISSUE TITLE
[Kitchen Sink] Add missing components

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7661]
These components are missing from the kitchen sink in the docs:

- Grid
- Flex grid
- Visibility classes
- Magellan
- Responsive menu
- Responsive toggler
- Off-canvas
- Reveal
- Progress bar
- Abide
- Equalizer
- Interchange
- Toggler
- Sticky

**Comment by zurbrandon** [comment]
Looks like @TvrtkoM crushed this one :)

**Comment by TvrtkoM** [comment]
hey people! thanks, but it's issue is complete. some items are still missing in kitchen sink - the once i didn't know how to put in (grid, flex grid, magellan, off-canvas, sticky). 
I should have probably posted some kind of comment about this earlier. oops.

**Comment by gakimball** [comment]
- For grid and flex grid, borrow the examples from the grid and flex grid docs page. They add extra styling to visualize the grid.
- For off-canvas, add a static HTML example and a click trigger underneath that opens the docs's off-canvas menu.
- For magellan, add an example as-is and see what happens. Even if it sticks to the top that's probably fine?
- For sticky, there's an example in the docs you could borrow with an image floating next to text.
