### ISSUE TITLE
JavaScript not working in production

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7664]
Reopening issue 348 by @iz5clj from the old foundation-sites-6 repo.

> I have installed the zurb template:
$ foundation new --framework sites --template zurb
Running the watch task works perfectly:
$ foundation watch
I have added a simple tooltip, and everything is just fine.
Then I build for production:
$ foundation build production
And now javascript is not working.
What am I missing?

@iz5clj, can you tell us if you see any JavaScript errors?

**Comment by TvrtkoM** [comment]
tried commands above, after installing foundation-cli and running _foundation build production_ or simply _foundation build_  getting

>[20:34:42] Finished 'copy' after 127 ms
/home/tvrtko/programming/foundation-test/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/home/tvrtko/programming/foundation-test/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/tvrtko/programming/foundation-test/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:79:21)
...

also _foundation -v_ shows help screen and not version or anything similar. (installed foundation-cli version is 2.0.1, foundation in bower_components is 6.1)

>$ npm -v
1.4.28
$ node -v
v0.10.37

**Comment by Owlbertz** [comment]
May be related to https://github.com/postcss/postcss/blob/f2a78af88e405419a4974a2cbb21293a41fa6108/CHANGELOG.md#50-president-valac
> Remove Promise polyfill for node.js 0.10.

**Comment by gakimball** [comment]
Yeah, it looks like PostCSS (used by Autoprefixer) dropped Node 0.10 support. If you can upgrade to 0.12, or straight all the way to 5.x (the newest release) that would be good.
