### ISSUE TITLE
[Documentation] Improve search

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7667]
Our search on the documentation is good, but it's got some kinks we need to work out. Can *you* help us write a better search algorithm?

Current issues:
- All search results show up twice in the results.
- Sometimes search terms that clearly should match, don't. Examples:
  - `mage` will return Magellan, but not `magel`, `magell`, or even `magellan`.
  - `int` or `interc` will match Interchange, but not `inte` or `inter`.

Here are the files that manage search:
- [buildSearch.js](https://github.com/zurb/foundation-docs/blob/master/lib/buildSearch.js): builds the JSON file used in search.
- [search.js](https://github.com/zurb/foundation-sites/blob/develop/docs/assets/js/docs.search.js): the Typehead instance that makes the search go.

**Comment by colin-marshall** [comment]
After some testing I've narrowed the duplicate results bug down to Supercollider or what is being passed into Supercollider. Everything appears twice in `supercollider.tree`.

**Comment by natewiebe13** [comment]
In regards to the duplicate results, it looks like it's caused by the build task calling `docs:all` and `docs:search`, then `docs:search` calls `docs` and supercollider runs through the pages twice.

**Comment by natewiebe13** [comment]
Displaying no results when there should be seems to be happening when there is the same number of results as the limit. (Example, when searching `magel`, there are 10 results which is also the limit)
This appears to be the issue: twitter/typeahead.js#1415

**Comment by colin-marshall** [comment]
@natewiebe13 good eye! I can't believe I overlooked that `docs:search` had the `docs` task as a dependency. Removing `docs:all` from the `build` task fixes the duplicate problem. Couldn't we just combine the `docs`, `docs:all`, and `docs:search` tasks into one task?

**Comment by gakimball** [comment]
Yeah, I've realized Supercollider can't handle an incremental change to the tree. The fix @colin-marshall suggested will work for now, because when we deploy the docs, it only generates the tree *once*.

However, if you're working on the docs locally, every time you change a page, that page's search results are stacked on to the tree again, so you get 2, 3, 4, etc. copies of the same results over time.

**Comment by gakimball** [comment]
For a little more context, `Supercollider.tree` is an array, so to detect duplicate pages, you'd either need to convert `tree` to an Object, or loop through the array looking for a duplicate, so you can remove it if it exists.

**Comment by colin-marshall** [comment]
What if we modified SuperCollider so that `.pipe(supercollider.init())` starts off the initialization process by clearing the contents of `supercollider.tree`? Or is it too time-consuming to rebuild the tree every time?

Another possible approach would be to use something like [gulp-changed](https://github.com/sindresorhus/gulp-changed) to pass through only the changed files. If the changed page(s) is/are new pages it will add them into `supercollider.tree` and if preexisting pages are modified it will replace the old version of the page in `supercollider.tree` with the new one.

**Comment by gakimball** [comment]
@colin-marshall The tree wipe is necessary for full rebuilds. However, sometimes only a single file goes through, so the tree shouldn't be cleaned in those cases. Instead, that one page in the tree should be replaced with a new item.

**Comment by gakimball** [comment]
I replaced Twitter's Typeahead package with a fork that includes the bug fix for result count. So we good!

**Comment by gakimball** [comment]
@colin-marshall FYI going to track the incremental build issue here: gakimball/supercollider#5

**Comment by colin-marshall** [comment]
:+1:
