### ISSUE TITLE
[Compatibility] Click behavior of the title-bar/Dropdown Menu in IE Mobile 

### ISSUE THREAD

**Issue by cogtail** [zurb/foundation-sites#7668]
**How can we reproduce this bug?**
1. Use IE 11 in Windows Phone or Windows Tablet
2. Open Drop-down Menu or Title-bar
3. Click on a Link in this open sub menu

The problem is, that you have to "click" (or better: to touch) two times until the link works, I reproduced this bug not only with my Foundation 6 installation but also with http://jointswp.com/demo/title-bar/ 

The "two touch" bug could be used as a feature only for parent items, when I touch first to open the dropdown menu and then to choose a link in the open sub menu or choose the activated link of the parent item (extra doubleTapToGo-Feature?). It should behave like http://www.smartmenus.org/.

**Comment by flobauer** [comment]
+1

**Comment by flobauer** [comment]
I debugged a little -> the reason lies in the foundation.dropdownMenu.js File and there in the Eventlistener.

I am currently testing a solution, but the Event listener doesn't react on the touchstart event...

**Comment by flobauer** [comment]
Ok, appearantly some IE Versions behave different when the aria-haspopup attribute is given: https://msdn.microsoft.com/en-us/library/jj152141(v=vs.85).aspx

I ended up checking for IE and if so, enforcing a redirect:
```php
if(hasSub){
    //...
}else{ 
    if (isIE) {
      window.location.href = $(e.target).attr('href');
    }
    return; 
}
```
I added this in the file foundation.dropdownMenu.js file in the Event Handling section on the `click.zf.dropdownmenu touchstart.zf.dropdownmenu` event

**Comment by cogtail** [comment]
Unfortunately, there is currently no fix for the TOUCH twice to follow links bug.

**Comment by flobauer** [comment]
I guess, this won't be fixed anytime soon...

**Comment by ncoden** [comment]
@flobauer Hi, sorry for the late reply. We recently released `v6.3.0`, did you tried with this last version ? I remember we fixed some issues with the Dropdown menu.

Poke @kball. There is so many issues with the dropdown menu on touch devices. See #9484, #9464, #9322, #8843

**Comment by kball** [comment]
Yeah, there are a ton.  I don't have a bunch of time for debugging this week and I'm off the following week but I'll take these on as a priority for 6.3.1 and tackle them first thing in Jan.

**Comment by JeremyEnglert** [comment]
This is no longer an issue on devices I tested. Please re-open if anyone notices otherwise.
