### ISSUE TITLE
menu-icon.dark class not in _title-bar.scss

### ISSUE THREAD

**Issue by rickcurran** [zurb/foundation-sites#7670]
I just upgraded my project to the 6.1 branch and the .menu-icon.dark class is no longer in the _title-bar.scss sass file. Is this is an oversight or has something changed in the way the dark menu-icons are handled now?

**Comment by gakimball** [comment]
We hadn't documented it, so we quietly removed it. Just for you, though, we'll re-add it ;)

I think in the future I'd like to move those `.menu-bar` classes to a separate file, but we'll do that later.
