### ISSUE TITLE
Alias .no-bullets for .no-bullet

### ISSUE THREAD

**Issue by pedzed** [zurb/foundation-sites#7671]
You can add `.no-bullet` to a `li`, but also to a `ul`.

```css
<ul>
    <li class="no-bullet">bulletless</li>
    <li class="no-bullet">bulletless</li>
    <li class="no-bullet">bulletless</li>
</ul>

<ul class="no-bullet">
    <li>bulletless</li>
    <li>bulletless</li>
    <li>bulletless</li>
</ul>
```
In case of an ul, it makes more sense to have `.no-bullets`. It would be nice to have an alias like `column` and `columns`.

```css
<ul class="no-bullets">
    <li>bulletless</li>
    <li>bulletless</li>
    <li>bulletless</li>
</ul>
```

**Comment by gakimball** [comment]
We're not interested in doing more plural classes beyond `.column` and `.columns`, which are mainly there for legacy reasons.
