### ISSUE TITLE
.button-group list-style

### ISSUE THREAD

**Issue by sebastiansulinski** [zurb/foundation-sites#7673]
I seem to be having problems with .button-group - I've included all foundation components, but it gives me grouped buttons with bullet points - see attached. Seems like there's missing css definition to remove list-style etc.
![screen shot 2015-12-23 at 16 47 38](https://cloud.githubusercontent.com/assets/2211203/11980792/5000340a-a995-11e5-8b8b-4200ec408dc8.png)
![screen shot 2015-12-23 at 16 48 01](https://cloud.githubusercontent.com/assets/2211203/11980793/50054724-a995-11e5-9291-c47030b6c5e7.png)

**Comment by gakimball** [comment]
You can just use a plain `<div>`. You also then don't need `<li>`s inside, just nest the buttons directly inside the button group, like so:

```html
<div class="button-group">
  <a class="button">One</a>
  <a class="button">Two</a>
  <a class="button">Three</a>
</div>
```

**Comment by andycochran** [comment]
You could also just add a `.no-bullet` class to the `<ul>`.
