### ISSUE TITLE
[Button] Text color not customizable through button-style() mixin

### ISSUE THREAD

**Issue by gabrielolnunes** [zurb/foundation-sites#7678]
**How can we reproduce this bug?**
```scss
.fashion-style {
  @include button-style( pink, red, blue);
}
```
```html
<a class="button fashion-style" href="#">Fashion</a>
```

**What did you expect to happen?**
Button text to be blue.

**What happened instead?**
Button text keeps _settings.scss `$button-color` value.

**My suggestion:**
Remove lines `112, 113, 114` from _button.scss file.

**Other issue in the same file:**
As already mentioned here, apparently there is a mistake on line `228` in _button.scss file.
Where you read ``!=``, i think it should be ``==``.

**Comment by gakimball** [comment]
Going to roll this into #7688
