### ISSUE TITLE
[Request] Please make it easier to add sticky to the navigation, like it was in F5.

### ISSUE THREAD

**Issue by jdfweb** [zurb/foundation-sites#7680]
In F5, it was simple. Add "sticky". Done.

In F6, it's a nightmare. I don't understand why the dev team decided to make it less efficient, and more difficult to implement this. "If it ain't broke, don't fix it". Why you guys changed it from the get-go is beyond me - it was already working perfectly.

An upgrade from F5 to F6 shouldn't make developer's lives more difficult. It should be more efficient. I'm building an internal site for our company, and it looks like I have to switch back to F5 because it works there.

I've already looked at Magellan, tried it out, and that doesn't work. This shouldn't be this difficult.

An "upgrade" shouldn't upset it's user base. I've read countless posts about this, it's clearly an issue so it would probably be in your best interests to make it easier (aka how it was).

**Comment by zurbchris** [comment]
While I feel your pain on the extra steps necessary to accomplish certain things, there are reasons why we did this. Mostly related to reducing the code base, which involves reusing as much code as possible.

The Sticky plugin makes it pretty easy to make a sticky nav bar, not just the old TopBar plugin. Not only that, but the method for making a nav bar sticky is *far* more flexible, with easily configurable anchors and breakpoints, margins, and event triggers. What is lacking, we admit, is documentation to support this. Take a look at http://codepen.io/zurbchris/pen/rxMaoX for an example of your sticky nav pattern. It requires a bit more from you as a developer, and in return, our js doesn't have to repeat code all over the place. And, nearly any element can utilize the Sticky plugin, not just TopBar.

**Comment by bbcreatv** [comment]
I think the documentation at the moment is poor for this, that's the problem. For me anyway.

**Comment by zephyrus23** [comment]
I'm fine with how Zurb has changed how things work concerning navigation and sticky. And that's fine that I have to type some more to get the effect done, but as stated, this needs to be documented better with examples. I'm trying to convert a rather large app over to Foundation 6 and a sticky header with navigation in it is pretty important. So, I'd be grateful for more information on the official documentation site.

**Comment by brettsmason** [comment]
@zephyrus23 @jdfweb It looks like a sticky header example was added to the sticky docs at some point since this issue - http://foundation.zurb.com/sites/docs/sticky.html#sticky-navigation

Do you think this is clear enough or do you think it needs more explanation? If you think this is sufficient I'll close the issue.

**Comment by zephyrus23** [comment]
Yeah, this looks good to me. A lot more clear on how things are working there. Thanks, @brettsmason!

**Comment by colin-marshall** [comment]
Closing this since it has been implemented.
