### ISSUE TITLE
[Off-Canvas] Events in docs don't match up with JS

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#7681]
The [Off-Canvas Events](http://foundation.zurb.com/sites/docs/off-canvas.html#js-events) in the docs include a hyphen that is not present in the actual JavaScript. I would put in a PR to fix this but I'm not sure which one is correct.

Events in the JS:
* `opened.zf.offcanvas` https://github.com/zurb/foundation-sites/blob/develop/js/foundation.offcanvas.js#L236
* `closed.zf.offcanvas`https://github.com/zurb/foundation-sites/blob/develop/js/foundation.offcanvas.js#L314

Events in the docs:
* `opened.zf.off-canvas`
* `closed.zf.off-canvas`

**Comment by AlexLaforge** [comment]
up

**Comment by colin-marshall** [comment]
Where/How are the events sections for a component created in the docs? I am pretty sure the hyphen in the docs is incorrect so I tried to fix it with a PR but couldn't figure out where it was created in the first place.

**Comment by gakimball** [comment]
The way the docs are generated is a bit complicated ;) I'll try to write some documentation on it soon for contributors.

The component template is stored in an external repo called [foundation-docs](https://github.com/zurb/foundation-docs). This code will eventually be shared between all three Foundation frameworks.

There's a shell script in the docs repo you can run, `./docslink.sh`, which will download it and link it locally to your Foundation repo. Then you can mess around with the contents.
