### ISSUE TITLE
small-centered medium-centered

### ISSUE THREAD

**Issue by cedarbrook** [zurb/foundation-sites#7682]
I upgraded from v6.0.6 to v6.1.1.   small-centered and medium-centered classes stopped working. I am using gulp. I added the classes to the bottom of my app.scss file:

.small-centered {
float: none;
margin-left: auto;
margin-right: auto; }

.medium-centered {
float: none;
margin-left: auto;
margin-right: auto; } 

The classes started working again in my project.  However, my app.css file now shows the classes, along with their css declarations, twice.  Once at line 722 and 927 and once at the end.  Any idea why this happened?

**Comment by gakimball** [comment]
Can you post a code sample illustrating how they don't work?

**Comment by cedarbrook** [comment]
```html
<div class="row">

<div class="large-8 columns">  
    <div class="row callout secondary" >  
        <div class="small-12 callout alert columns" >
        	<br><br><br><br><br><br><br><br><br><br><br><br>
        </div>
    </div>	
</div>

<div class="large-4 columns" > 
	<div class="row callout secondary">
		<div class="small-10 small-centered text-center callout alert columns" >    
 			<br><br><br><br><br><br>
            This box should be centered?
            <br><br><br><br><br><br>
		</div>
	</div>
</div> 

</div> 
```

**Comment by gakimball** [comment]
The `.callout` class adds its own margin, which is overriding margin needed to center the column.

I'd recommend putting `.callout` inside `.column`—sometimes when you mix components, weird things can happen.

**Comment by cedarbrook** [comment]
Thank you!  I did what you recommended and that fixed the issue.  The callout classes are after the centered classes in the app.css file.  It did not occur to me that the css cascade might be the culprit. You're the best!
