### ISSUE TITLE
Tooltips: Event tooltip.zf.tooltips in doc should be closeme.zf.tooltips (js)

### ISSUE THREAD

**Issue by briantan888** [zurb/foundation-sites#7691]
Events section: tooltip.zf.tooltips should be closeme.zf.tooltips

Functions section: .show 
Fires these events: Closeme#event:tooltip Tooltip#event:show 
should be
Fires these events: Tooltip#event:closeme Tooltip#event:show

Would create a PR if I know where to update it :)

**Comment by gakimball** [comment]
I went ahead and made the fix :)

For future reference, we use JSDoc to generate the JavaScript docs. Each method has `@fires` annotations which indicate what events that function can fire. The calls to `.trigger()` are annotated with `@event`, which is the name of the event.

**Comment by briantan888** [comment]
Thanks for the pointer.

What about http://foundation.zurb.com/sites/docs/dropdown-menu.html#js-events 

Where do the spaces in "show.zf.dropdown menus" and "hide.zf.dropdown menus" came from? 

dropdownMenu.js @event does not has spaces in it, or has that been fixed already?

**Comment by gakimball** [comment]
@briantan888 The formatting is handled with a Handlebars template in the repo [foundation-docs](https://github.com/zurb/foundation-docs). I went ahead and made the fix.

The way those events render is *really* hacky right now, we just need to put the work in to rename all of the `@event` annotations in our JavaScript.
