### ISSUE TITLE
Top Bar submenus are misaligned

### ISSUE THREAD

**Issue by aldees** [zurb/foundation-sites#7693]
Submenus in the right section of the top bar are misaligned.  The Item 3 submenu should be positioned below Item 3, not to the left.  Also, the arrow for Item 3B points to the right, however the submenu is displayed on the left.

![topbar](https://cloud.githubusercontent.com/assets/16446568/12007573/fad84548-abcf-11e5-9528-ee3d5f0b6ed7.png)

HTML - [topbar.txt](https://github.com/zurb/foundation-sites/files/72502/topbar.txt)

**Comment by JeremyEnglert** [comment]
Same issue as this: https://github.com/zurb/foundation-sites/issues/7251

I thought I saw a note saying it was fixed in 6.1, but I'm still experiencing the issue as well.
