### ISSUE TITLE
[Foundation 6 for Sites] BrowserSync not work

### ISSUE THREAD

**Issue by steponavichus** [zurb/foundation-sites#7694]
Hi.
Install on Windows 10.
Run "foundation watch".
When you change the files (scss,html) in the "src" - BrowserSync not work.

In gulpfile.js replace:
```javascript
gulp.run('pages', 'cb');
```

on

```javascript
gulp.run('pages');
cb();
```

That all works fine.

Foundation version 6.1 (installed by npm)

**Comment by gakimball** [comment]
I believe zurb/foundation-sites-template#23 will help with this. To update your Gulpfile, add the new `reload` task and then edit all of the `gulp.watch` calls to match what changed in the PR. [Here's the diff between the two.](https://github.com/zurb/foundation-zurb-template/pull/23/files)

**Comment by gakimball** [comment]
Closing this as we have a solution in the works.
