### ISSUE TITLE
[Installation] node not found on linux mint 17.1

### ISSUE THREAD

**Issue by timabell** [zurb/foundation-sites#7696]
I'm running linux mint 17.1, I already have node installed, but for some reason mint installs it as `nodejs` and not `node`, which breaks your `foundation` cli thing.

Following the instructions on http://foundation.zurb.com/sites/docs/installation.html I ran `npm install --global foundation-cli` which worked (after adding `sudo` to the front, you might want to mention that).

Then I tried it out and got this:

    $ foundation
    /usr/bin/env: node: No such file or directory

I've fixed it up by running

    cd /usr/bin
    sudo ln -s nodejs node

which works but perhaps isn't ideal.

Don't know how you might improve this, but although it didn't cause me much of an issue I can imagine a less experienced linux user being stumped and frustrated.

Thanks for everything you've created and shared for free, it's amazing. :-)

**Comment by timabell** [comment]
next problem:

    $ npm install
    npm WARN package.json panini@1.1.1 No repository field.

and then it dropped back to a shell.

stumped.
maybe my node/npm is too old?

    $ node -v
    v0.10.25
    $ npm -v
    1.3.10

**Comment by timabell** [comment]
I hope you don't mind me just putting my whole experience here, I thought it might be useful to see how someone who's never used foundation before flails around tripping over everything :-D

Next up:

	tim@sammy:~/repo/xchain/www/xchain-www(foundation-cdn)% foundation watch

	> foundation-zurb-template@1.0.0 start /home/tim/repo/xchain/www/xchain-www
	> gulp

	[22:26:08] Using gulpfile ~/repo/xchain/www/xchain-www/gulpfile.js
	[22:26:08] Starting 'build'...
	[22:26:08] Starting 'clean'...
	[22:26:08] Finished 'clean' after 2.56 ms
	[22:26:08] Starting 'pages'...
	[22:26:08] Starting 'sass'...
	[22:26:10] Starting 'javascript'...
	[22:26:10] Starting 'images'...
	[22:26:11] Starting 'copy'...
	[22:26:11] Finished 'images' after 656 ms
	[22:26:11] Finished 'pages' after 2.6 s
	[22:26:11] Finished 'copy' after 72 ms
	[22:26:11] Finished 'javascript' after 1.18 s

	/home/tim/repo/xchain/www/xchain-www/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157
		this.processing = new Promise(function (resolve, reject) {
				      ^
	ReferenceError: Promise is not defined

I seem to have broken it. :-/

**Comment by timabell** [comment]
I've now tried purging the apt installed nodejs and npm; installed nvm following the instructions on https://github.com/creationix/nvm then ran `nvm install v5.3.0`, started a fresh console and now I get this:

    tim@sammy:~/repo/xchain/www/xchain-www(foundation-cdn)% foundation watch
    /usr/bin/env: node: No such file or directory

It seems that because nvm is installing node just into my home dir `env` doesn't know about it. :-/ This is proving to be a real pain in the ass. I was hoping it would be more convenient than just adding the tags manually myself but it's not really worked out that way. Not that I'm ungrateful.

I should mention I'm using zsh not bash, wouldn't expect that to matter though. Just about all of my local config is available at https://github.com/timabell/dotmatrix if you need any details of shell config etc.

**Comment by timabell** [comment]
had to run `npm install` again, and `npm rebuild node-sass` as per an error message, but finally `foundation watch` has built and run the template site. hurrah.

**Comment by gakimball** [comment]
Sorry for the late response! We were all on vacation. Glad to see you got things fixed. :) To clarify a few things:

- Node 0.10 should have worked fine, although over time libraries will drop support for it in favor of 0.12 and 4.0+.
- Your npm being at 1.x might have been causing some issues. Using 2.x or 3.x can alleviate that.
- Good call installing nvm, as it makes it super easy to install a new Node version in case a specific project requires it.
- A project can only work with one Node version at a time. So if you `npm install` to setup a project on, say, 4.0, and then upgraded Node to 5.0, you would need to delete your `node_modules` folder and start over.
