### ISSUE TITLE
[Off-canvas] closeOnClick not working when set to 'false'

### ISSUE THREAD

**Issue by andrewf137** [zurb/foundation-sites#7697]
1. Set a simple left and right off-canvas menu.
Set `closeOnClick: true` for left menu
Set `closeOnClick: false` for right menu

2. Click on button that opens left menu: everything ok (however, a js error arises).
Click on button that opens right menu: it does not work.

3. [Link to JSFiddle](https://jsfiddle.net/andrewf137/oy7y7267/)

4. My workaround:

Line 143 of **foundation.offcanvas.js**

Changed this:

    if (this.$exiter.length) {
        var _this = this;
        this.$exiter.on({'click.zf.offcanvas': this.close.bind(this)});
    }

for this:

    if (typeof this.$exiter !== 'undefined')
    {
        if (this.$exiter.length) {
            var _this = this;
            this.$exiter.on({'click.zf.offcanvas': this.close.bind(this)});
        }
    }

**Comment by zurbchris** [comment]
Couple things, it's erroring out Foundation due to the bug you pointed out. As for the exiter problem, that's a sass issue specifically and now resolved, at least in development.
