### ISSUE TITLE
[Orbit] Slide change event fires too often

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#7699]
This event fires multiple times between every slide change. It should fire once per slide change.

```javascript
$('[data-orbit]').on('slidechange.zf.orbit', function() {
    console.log('I changed slides!');
});
```

**Comment by zurbchris** [comment]
I'm not getting this error on my local clone or live on the docs page. Do you have multiple orbits on the same page?

**Comment by colin-marshall** [comment]
(Facepalm)

Multiple orbits on the same page was exactly why this was happening.
