### ISSUE TITLE
Sass Error: Invalid Null Operation

### ISSUE THREAD

**Issue by TheAggressive** [zurb/foundation-sites#7700]
I'm getting this on _grid.scss 

anyone know what could cause this and how to correct the issue?

Thanks!

**Comment by EricRihlmann** [comment]
Are you doing any calculations on `$grid-column-gutter`?

It recently changed from 
`$grid-column-gutter: 30px !default;`
to
`$grid-column-gutter: null !default;`

**Comment by gakimball** [comment]
We're shifting the way the gutters work to allow for responsive gutters—check out the [6.1.0 changelog](https://github.com/zurb/foundation-sites/releases/tag/v6.1.0) for more info.

Can you post a full error message so we can see what's going on in more detail?

**Comment by andycochran** [comment]
I'm getting a similar error: 
```
vendor/foundation-sites/scss/grid/_grid.scss
Error: invalid operands for multiplication
        on line 19 of vendor/foundation-sites/scss/grid/_grid.scss
>> $grid-column-gutter: null !default;
   ---------------------^
```
:cry:

**Comment by andycochran** [comment]
^ @JeremyEnglert, my error is after changing `bower.json` to use `"foundation-sites": "~6.1.0"` and doing a `bower update` in JointsWP. Could it be a problem with JointsWP?

**Comment by andycochran** [comment]
Ack! I _was_ performing a calculation using `$grid-column-gutter`. :innocent:

**Comment by gakimball** [comment]
@andycochran *Oh*. Sorry, we hadn't considered that as an issue. As long as `$grid-column-gutter` is still using a pixel value in your settings file, you should be fine.

**Comment by EricRihlmann** [comment]
@gakimball would there be an issue with just setting `$grid-column-gutter` to `0 !default` instead of `null !default`?

**Comment by andycochran** [comment]
I don't think my issue/error is something that needs to be addressed. The culprit was a custom style in the app, not the framework. Keep up the great work, y'all!

**Comment by gakimball** [comment]
@andycochran Sounds good!

@TheAggressive I'd still like to see a full stack trace so we can better identify the issue. Can you paste a complete Sass console error? Thanks :)

**Comment by TheAggressive** [comment]
@gakimball It was as @EricRihlmann pointed out. I was doing a calculation with $grid-column-gutter variable. Once removed the scss compiled fine.

Thank you for all the help! I'm going to have to read up on responsive gutters in the change log.

**Comment by TheAggressive** [comment]
So I can just use `$grid-column-responsive-gutter` in place of `$grid-column-gutter`?

or do you have to state which value you want? if so how do you select? 
`$grid-column-responsive-gutter(small)`?

**Comment by gakimball** [comment]
To pull a value out of the map, use `map-get($grid-column-responsive-gutter, small)`. Verbose? Yes, unfortunately. I think in 6.2, when we drop the old gutter method entirely, we can make `$grid-column-gutter` the new map variable.
