### ISSUE TITLE
Documentation page for the 'Interchange' plugin

### ISSUE THREAD

**Issue by simonrcodrington** [zurb/foundation-sites#7701]
Hey guys,

Looking at the 'Interchange' plugin docs page, it seems a little confusing (http://foundation.zurb.com/sites/docs/interchange.html)

For example when you click on the link that says **'Named breakpoints below'** it tries to go to #named-breakpoints instead of #named-media-queries

Also down the bottom of the page, when you click on the **'Learn more about how JavaScript plugins are initialized'** link, I expect to be taken to here: 

http://foundation.zurb.com/sites/docs/javascript.html#initializing

However when I press it, it wants to take me here: 

http://foundation.zurb.com/sites/docs/interchange.html#

Also, on a quick related note; In the **'Javascript Reference'** page it would be good to expand on the example so it's something people could copy and use. 

For example if I just set up the JS buy calling this

`$(document).foundation();`

Interchange works perfectly

However if I manually try and set up interchange by doing this

```
var elements = $('img'); 
var elem = new Foundation.Interchange(elements );
```

Nothing happens (I'm loading the full minified version of the Foundation JS)

I would have thought if I included the full JS file I could just call Interchange and it would work.

Thanks again for all your effect and work with Foundation 6 guys :)

Cheers

Simon

**Comment by zurbchris** [comment]
Fixed the Named Breakpoints one, the javascript.html#initializing one is a head scratcher though. Handlebars is doing something weird that it shouldn't be doing. We'll try to get this fixed soon.
As for the programmatic creation of an Interchange element, you would need a little more investment on your part, as you're not assigning any rules there, also, the `$element` parameter of the plugin is the container for the plugin, not the container's contents. 
This would look more like:

```js
var photoFrame = $('#some-container');
var interchange = new Foundation.Interchange(photoFrame, {rules: "[path/to/default.jpg, small], [path/to/medium.jpg, medium], [path/to/large.jpg, large]"});
```

**Comment by joeravgiala** [comment]
In this scenario is $element the image tag? or the container for the image tag?

**Comment by arjanceelen** [comment]
The rule feeded to the Interchange function is a String instead of a object. This is why it's not working.

use 
`var interchange = new Foundation.Interchange(photoFrame, {rules: ['[path/to/default.jpg, small]','[path/to/medium.jpg, medium]','[path/to/large.jpg, large]']});
`

Here a [demo](https://embed.plnkr.co/amSXyTTAhNYdYbAnmbvQ/)

**Comment by josephnvn** [comment]
Thanks arjanc. 
I was trying to use data-interchange in orbit. It works fine if the data-interchange is provided in html. However, if we use js to add data-interchange dynamically, the code fails. Trick is the id's on image tags.. with different id's for images the code works perfectly.
