### ISSUE TITLE
All CSS is missing in the "Essential" download of Foundation

### ISSUE THREAD

**Issue by Aetles** [zurb/foundation-sites#7702]
I don't know if this should be reported here on Github or elsewhere, but the "Essential" download of Foundation for Sites (at http://foundation.zurb.com/sites/download/assets/essential-f6.zip) is missing all CSS right now. 

The `css` folder used to have a `foundation.css`, a `foundation.css.map` and a `foundation.min.css`. But now there's only the empty `app.css`.

**Comment by rafibomb** [comment]
Thanks for the report! We're looking into it. It will likely be Monday for a patch on this. The full download seems to right.

**Comment by rafibomb** [comment]
https://twitter.com/Aetles/status/682148984203403264

**Comment by gakimball** [comment]
Rolling this into #7033
