### ISSUE TITLE
Responsive Toggle Navigation not working on Official ZURB Template build

### ISSUE THREAD

**Issue by huphtur** [zurb/foundation-sites#7703]
Manually set up the [Official ZURB Template](https://github.com/zurb/foundation-zurb-template). Everything works fine during development but the build version breaks the [Responsive Toggle Navigation](http://foundation.zurb.com/sites/docs/responsive-navigation.html). As in: the tab bar is always visible, no matter the screen size. Here's an [live test](http://zurbtestcase.s3-website-us-east-1.amazonaws.com/) from a fresh install.

**Comment by huphtur** [comment]
Found the culprit, it's [uncss](https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.js#L100-L105). now to figure out why...

**Comment by jonbramble** [comment]
I was looking at this too and also found that I could make my site functional if I skipped uncss, but then found out later that if I skipped minifyCss but kept uncss it also works fine. The file size is not much smaller for my test code though. I might try a different css minify system.

**Comment by jonbramble** [comment]
I found a fix to this by adding <meta class="foundation-mq"></meta> into the head section of the layout file. This seems avoid to uncss problem but I'm not sure if this is a good idea.

**Comment by huphtur** [comment]
@jonbramble Indeed not recommended to put body markup in the header. 

I guess for now it's probably best to comment out the ```.pipe(uncss)``` line from ```gulpfile.js``` and also comment out any includes you don't need from ```app.scss``` this saves considerable amount of css filesize.
