### ISSUE TITLE
html is extremely verbose

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation-sites#7706]
writing accordions and tabs are a nightmare. look at this, its horrible:
```
<li class="accordion-item">
	<a href="#panel6e" role="tab" class="accordion-title" id="panel6e-heading" aria-controls="panel6e">Experience</a>
	<div class="accordion-content" role="tabpanel" id="panel6e" data-tab-content aria-labelledby="panel6e-heading">			
	</div>
</li>
```

the markup should be:
```
<li>
	<a>Experience</a>
	<div class="accordion-content">						
	</div>
</li>
```
the needed attributes can be generated programmatically at run time.

**Comment by andycochran** [comment]
Of note: [ARIA Properties, DOM, and Graceful Degradation](http://stackoverflow.com/questions/6901724/aria-properties-dom-and-graceful-degradation)

**Comment by QWp6t** [comment]
> the needed attributes can be generated programmatically at run time.
...so generate them programmatically at run-time. What's the problem?

This isn't a bug. :-1:

**Comment by austinpray** [comment]
Your proposed markup looks like it would have lots of specificity required in the backing CSS. Just use classes and be done with it. :-1:

**Comment by r3wt** [comment]
It should be documented what is automatically scabbed in at runtime.

**Comment by zurbchris** [comment]
So, everything you're asking for, (with one exception), is already managed by Accordion JS. This is a docs issue more than anything, as there's a lot of gaps in documentation coverage in a lot of places. I've gone through the docs for accordion and updated them with the proper notations. This fix will be published the next patch, which will hopefully have a lot more info in the docs.
