### ISSUE TITLE
pure css file input cloaking

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation-sites#7707]
http://codepen.io/anon/pen/yeVOVr

not sure if desired, but others might find useful.

**Comment by colin-marshall** [comment]
Thanks for sharing! It's probably worthwhile to submit this as a Building Block. Not totally sure how you do that though.

**Comment by natewiebe13** [comment]
A better solution would be to set a z-index on the file input. Then it will work in browsers that don't support `pointer-events`.

**Comment by r3wt** [comment]
@natewiebe13 updated.

**Comment by andycochran** [comment]
I like to use a `<label for="#file-input" class="button">` 
and hide the `<input type="file" name="file-input" class="show-for-sr" />`.

**Comment by gakimball** [comment]
@andycochran With this method, would our `<label>` CSS conflict with the `.button` CSS?

**Comment by gakimball** [comment]
@andycochran Also, is one approach or the other better for accessibility, do you think?

**Comment by andycochran** [comment]
To be honest, I've yet to use this method with F6. 

Just tried a quick experiment and it seems to work fine: 
http://codepen.io/anon/pen/MKpLNx

I'm not sure which is better for accessibility. The `label` method might be more semantic tho. And simpler (zero custom CSS).

**Comment by r3wt** [comment]
i like andy's solution the best, since it doesn't interfere with hover/active/focus states like mine did.

**Comment by andycochran** [comment]
Thinking about accessibility, it should be noted that any solution that hides the `input` disables browser functionality that displays the chosen filename. So you also need a client-side solution to show the action. Something like: 

```js
var fileLoader = $('#file-input')[0];

fileLoader.addEventListener('change', handleFile, false);

function handleFile(){
  // do something with the chosen file
}
```

**Comment by gakimball** [comment]
@andycochran Does hiding with `opacity: 0` count?

**Comment by andycochran** [comment]
I'd say so. You can't see it if it's transparent. :smile: 

This is really more UX than accessibility—I think `.show-for-sr` takes care of a11y.

**Comment by gakimball** [comment]
@andycochran Ah well specifically I was wondering if a file input with `opacity: 0` actually becomes non-interactive. But it seems like the `clip()` method works fine, and a screen reader still reads the element.

I do like this approach because it doesn't even appear to require any extra CSS.
