### ISSUE TITLE
Allowing SVG partials

### ISSUE THREAD

**Issue by yakou32** [zurb/foundation-sites#7710]
Quite new to github, so I hope this is the good way to propose suggestions.

The easiest way to handle SVG styles through CSS is to have the SVG code directly within the page.
However, doing so, the code gets really ugly. And the page becomes quite difficult to maintain, especially when several identical SVG images need to be updated.

Therefore, I'm using the new Foundation 6 partial with SVG images. This is just great, as SVG code does not pollute the page edition  any more, and SVGs are much easier to update, and their styles can be handled through CSS.

To do so, I replace the svg extension by html, so that Panini can handle those files as if they were html chunks. But renaming extensions is not so elegant, as svg files look like html stuff in the project directory.
So, my suggestion is, would it be possible to make Panini handle `.svg` as well as `.html` (or just not care of files extension?)

Also, it seems that Panini can't access subfolders in the partials directory, as a `svg` folder could be created there to have a cleaner structure...

**Comment by gakimball** [comment]
Panini only searches for `.html`, `.hbs`, and `.handlebars` files. I suppose adding support for XML files like `.svg` isn't a huge deal, but there are also some quicker ways to do what you want to do.

There's a great JavaScript library called [SVGInjector](https://github.com/iconic/SVGInjector) which takes `<img>` tags with SVGs and converts them to inline SVG when the page loads.

Going to close this, but feel free to continue the discussion :) You could also use [gulp-inject](https://github.com/klei/gulp-inject) to inject the SVGs, but you'd have to write your own custom code for that, which is maybe not worth the time.

**Comment by tourtools** [comment]
a quick working workaround is to place the svg code inside an .html partial
