### ISSUE TITLE
[Media Queries] Error on xxlarge

### ISSUE THREAD

**Issue by Nikolaus91** [zurb/foundation-sites#7711]
**How can we reproduce this bug?**

1. Set up a page with F6
2. Make an html element
3. Try to use xxlarge call

**What did you expect to happen?**

I'd like to replace background in my parallax scrolling div.

**What happened instead?**

I did add empty @include's with desired breakpoints:

    #h1s1.myBanner{

    background: url('../images/002_O_NAS/images/dzieciaki.jpg') no-repeat;
    background-attachment: fixed;
    background-position: 0px -275px !important;

    background-size: cover;

    @include breakpoint(medium down) {

    }

    @include breakpoint(xlarge down) {

    }

    @include breakpoint(xxlarge down) {

    }
    }

After adding the last one for xxlarge devices i have the following error in my CSS:

![screenshot-funlam beectrl com 2015-12-29 12-32-40](https://cloud.githubusercontent.com/assets/10107362/12033826/531eedb0-ae28-11e5-9a81-e991a9797016.png)

Have you encountered such behavior ever before or it's some kind of my mistake?

**Comment by gakimball** [comment]
`xxlarge down` doesn't work because it's the biggest breakpoint. The term specifically means "xxlarge screens *and down*", and that won't work because there's not a bigger breakpoint to reference.

**Comment by Nikolaus91** [comment]
Thank you!

2016-01-05 1:24 GMT+01:00 Geoff Kimball <notifications@github.com>:

> xxlarge down doesn't work because it's the biggest breakpoint. The term
> specifically means "xxlarge screens *and down*", and that won't work
> because there's not a bigger breakpoint to reference.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zurb/foundation-sites/issues/7711#issuecomment-168852641>
> .
>



-- 
Z poważaniem,

Mikołaj Koropecki


Design & Software
Development House
----------------------------
mob: +48 500 401 730
e-mail: mk@beectrl.com
