### ISSUE TITLE
closeOnClick won't close dropdown

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#7713]
I have this structure:

```
<button class="dropdown success small button" type="button" data-toggle="local-actions-dropdown">{{ 'Actions'|t }}</button>
            <ul class="dropdown-pane" id="local-actions-dropdown" data-dropdown data-auto-focus="true" data-close-on-click="true">
                {{ content }}
            </ul>
```

According to documentation in here http://foundation.zurb.com/sites/docs/dropdown.html the dropdown should close automatically if user clicks outside but that is not happening.

<code>closeOnClick 	Allows a click on the body to close the dropdown. 	true</code>

I tried to manually set this to true just in case(as you can see in the code) but nothing changed.

**Comment by tjhiggins** [comment]
This dropdown will close on a click on the body that isn't the dropdown itself or the anchor.
http://codepen.io/TJHiggins/pen/NxbgLx

**Comment by zurbchris** [comment]
What version of Foundation are you on? This feature was added in with #7353 and pushed out with 6.1, if I remember correctly.

**Comment by gakimball** [comment]
Yep, this is definitely fixed in the latest version of Foundation. Here's a test case that illustrates it working: <https://github.com/zurb/foundation-sites/blob/develop/test/visual/dropdown/close-on-click.html>
