### ISSUE TITLE
6.1.1 Flex Grid SCSS compile issue

### ISSUE THREAD

**Issue by dlewand691** [zurb/foundation-sites#7714]
Using Codekit on a Mac, get this error when trying to use Flex Grid:

	Error: Undefined variable: "$gutter".
	
	on line 250 of /Users/DannyL/Dropbox/__RAND SITE 2015 F611/bower_components/foundation-sites/scss/grid/_flex-grid.scss, in 'grid-col-uncollapse'
	
	from line 250 of /Users/DannyL/Dropbox/__RAND SITE 2015 F611/bower_components/foundation-sites/scss/grid/_flex-grid.scss, in '@content'

        from line 220 of /Users/DannyL/Dropbox/__RAND SITE 2015 F611/bower_components/foundation-sites/scss/util/_mixins.scss, in '@content'

        from line 133 of /Users/DannyL/Dropbox/__RAND SITE 2015 F611/bower_components/foundation-sites/scss/util/_breakpoint.scss, in 'breakpoint'

        from line 219 of /Users/DannyL/Dropbox/__RAND SITE 2015 F611/bower_components/foundation-sites/scss/util/_mixins.scss, in '-zf-each-breakpoint'

        from line 193 of /Users/DannyL/Dropbox/__RAND SITE 2015 F611/bower_components/foundation-sites/scss/grid/_flex-grid.scss, in 'foundation-flex-grid'

        from line 9 of /Users/DannyL/Dropbox/__RAND SITE 2015 F611/scss/app.scss

**Comment by metaloha** [comment]
Patched in PR #7704.

**Comment by gakimball** [comment]
Fixed via 5388206ef4c6dd9e08372f599a821f4da8659c45
