### ISSUE TITLE
Form input-group-label wraps with space

### ISSUE THREAD

**Issue by marcusconnor** [zurb/foundation-sites#7715]
In Foundation 6.1.1 if a form label using `.input-group-label` contains a space (more than one word) then the label wraps to 2 lines. I applied `white-space: nowrap;` as a fix.

Both the issue, and the fix may be seen here:
http://codepen.io/marcusconnor/pen/MKbvJV

**Comment by rafibomb** [comment]
Makes sense to have this as a default. Are you able to submit a PR for it so we can add it in?

It should go in the @mixin form-label mixin.

**Comment by marcusconnor** [comment]
Pull request made.

**Comment by gakimball** [comment]
Merged #7769
