### ISSUE TITLE
Flex-Grid full width row issue

### ISSUE THREAD

**Issue by yogiderek** [zurb/foundation-sites#7718]
In the documentation for the foundation grid, it states that you can now use ` <div class="row column"></div> ` to get a full width row. This works okay in the foundation grid, however if you try it in the flex-grid it does not work as expected. In the following code snipet, the result is shown below. Classes section-title and section-subtitle both include `text-align:text-center`

```html
	<div class="row column section-header">
		<h2 class="section-title">This is what <span>we love to do</span></h2>
		<h5 class="section-subtitle">"<span>Love</span> what you do. Do what you <span>love</span>"<br /> - Ray Bradbury</h5>
	</div>
```
Is the above foundation grid method meant to work with the flex-grid, if not can the docs be updated to state this, else can flex-grid be updated.

Thanks

Not Expected (flex-grid)

![bad](https://cloud.githubusercontent.com/assets/2614368/12041991/89c3fcca-ae6e-11e5-807b-27b7c758db58.png)

Expected (foundation grid result)

![good](https://cloud.githubusercontent.com/assets/2614368/12042009/afca7bf6-ae6e-11e5-8c77-9a3b316f56ac.png)

**Comment by gakimball** [comment]
The flex grid was actually missing that feature, so I added it.

We'd like to take some steps to better share code between the two grids, specifically the class output, which is similar in some areas but different in others.
