### ISSUE TITLE
how do I use data-options on dropdown-menu?

### ISSUE THREAD

**Issue by Blackvibes** [zurb/foundation-sites#7719]
I'm sorry, but the documentation is way too small.

I'm figuring out how to create a dropdown-menu with a few submenu's that
a) do only open on click, not when hovering
b) autoclose when an another menu is opened.

Whatever I try with data-options is not working.
I'm using Foundation 6.x.x

My HTML is pretty easy.
````html
<ul class="vertical dropdown menu" data-dropdown-menu data-options="disablehover:true" aria-options="disableHover:true" data-disable-hover=false>
  <li>
    <a href="#">Item 1</a>
    <ul class="menu submenu is-dropdown-submenu vertical" data-submenu aria-hidden="true" data-options="disablehover:true" data-disable-hover=false>
        <li><a href="#">Sub 1</a></li>
        <li><a href="#">Sub 2</a></li>
        <li><a href="#">Sub 3</a></li>
    </ul>
  </li>
  <li>
    <a href="#">Item 2</a>
        <ul class="menu submenu is-dropdown-submenu vertical" data-submenu aria-hidden="true" data-options="disableHover:false" data-disable-hover=false>
        <li><a href="#">Sub 1</a></li>
        <li><a href="#">Sub 2</a></li>
        <li><a href="#">Sub 3</a></li>
    </ul>
  </li>
  <li><a href="#">Item 3</a></li>
</ul>  
````

**Comment by ivanjaros** [comment]
USe JSON format data-options="{disablehover:true}" for multiple settings or data-disable-hover="true" for single setting.

**Comment by zurbchris** [comment]
It needs to be properly camelCased to use `data-options` e.g.
```html
data-options="disableHover: true;"
```
Please note you also need the semicolon at the end of *all* `data-options` attributes.

**Comment by zurbchris** [comment]
If you still have questions, feel free to jump into gitter. Closing.

**Comment by stevepiercy** [comment]
FTR, this works for me. `disableHover: true;` alone did not work. I had to also set `clickOpen: true;`.

```html
<ul class="dropdown menu" data-dropdown-menu data-options="disableHover: true; clickOpen: true;">
```

**Comment by dave547** [comment]
so I had to do it this way. `data-disable-hover="true;"` and set it ` data-click-open="true;"`

`<ul id="main-nav" class="medium-horizontal menu dropdown" data-responsive-menu="accordion medium-dropdown" data-disable-hover="true;" data-click-open="true;">`
