### ISSUE TITLE
[Responsive Navigation] ISSUE NAME HERE

### ISSUE THREAD

**Issue by angecorse** [zurb/foundation-sites#7721]
**How can we reproduce this bug?**

data-hide-for="medium"

seems not to work

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by trinode** [comment]
you actually starting foundation?

```
          <script type="text/javascript">
            $(document).foundation();
          </script>
```

**Comment by zurbchris** [comment]
The `data-hide-for="foo"` attribute is for Responsive Toggle, not Responsive Navigation. They share a docs page, but make sure you're using the correct plugin.

**Comment by gakimball** [comment]
What @zurbchris said. We'd need a code sample to help you further. Feel free to reopen this issue with more details when you have time :)
