### ISSUE TITLE
[Dropdown] Click Event not registering on dropdown button in jqMVC

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation-sites#7722]
in this type of setup, we would bind foundation like this:

``` js
$.jqMVC.bind('foundation',function(){
    $(document).foundation();
})
```

so for every time `$.jqMVC.done()` is called, this code above, and any other "default bindings" would run. you can think of these bindings as a sort of document.ready that happens for each request. the best way to describe the framework is a webserver+mvc framework running inside of a browser.

this works great with most jQuery plugins. it doesn't play nice with foundation though, in particular the click event doesnt register on dropdowns for some reason.

![img](http://s23.postimg.org/vwgg2fpa3/ss_2015_12_29_at_09_17_29.png)

reproducing it might be tedious, but if needed i'll try to write up a quick seed app with jqmvc + foundation. obviously this would probably not function correctly in a jsfiddle/plunkr.

**Comment by r3wt** [comment]
ok, so i tried to work around it like so:
```js
$.jqMVC
.bind('foundation',function(){
	$(document).foundation();
	$(document).on('click','.button[data-toggle]',function(){
		$(this).focus().trigger('keydown');
	});
})
```

this causes the following message to appear in the console:

![img](http://puu.sh/mexK2/3fd96b5d09.png)

**Comment by zurbchris** [comment]
I'm not familiar with jqMVC, if it's possible for you to create a demo app, it would make it much easier for me to assist you. That error is being thrown by our keyboard util library, so there's something going wrong with the initialization of foundation by the looks of it.

**Comment by r3wt** [comment]
@zurbchris i got a demo up:

http://f6dev.openex.info/

drilldown, topbar, slider, tabs, and accordion work fine.

two components not working:

Dropdown and Reveal.

**Comment by zurbchris** [comment]
I have no earthly idea why this isn't working correctly. The only thing I can think of is a name collision with the `data-toggle` attribute. Though it's a pain, try replacing `data-toggle="example-dropdown"` with:
```html
data-open="example-dropdown"
```
and see if that makes it go. 
Alternatively, I made this work: 
```html
<button ...
onclick="$('#example-dropdown').foundation('toggle');"...
</button>
```

**Comment by r3wt** [comment]
I feel like i should mention as well, a slider with multiple handles doesn't seem to work either, atleast its very buggy and winds up the cpu on my lappy.

**Comment by zurbchris** [comment]
I won't lie, Slider has been a thorn in my side for a while now. Thought I had the crazy cpu use curtailed.

**Comment by r3wt** [comment]
@zurbchris 

just to rule out my framework as the culprit, can you see any thing wrong with how i'm augmenting `$.fn.init` here?

https://github.com/r3wt/jqMVC/blob/master/src/events.js#L2-L17

also, does foundation use jQuery to bind events or does it use vanilla js in some places?

**Comment by r3wt** [comment]
shit i wish there was a fix for this so bad.

**Comment by zurbchris** [comment]
Sorry it took so long to get back to you, last week I was on a different project. 
To answer your question, I just don't know. Sorry it's a lame answer...
Everything uses jQuery for event binding except for the touch events, which are custom events triggered with vanilla js.
