### ISSUE TITLE
Custom breakpoints

### ISSUE THREAD

**Issue by RustBeard** [zurb/foundation-sites#7724]
When I have `@include breakpoint(brkpt_name) { }` everything works fine. But when I use `@include breakpoint(brkpt_name `**`down`**`) { }` sass generates in css `@media screen and (max-width: ) { }`
http://foundation.zurb.com/sites/docs/media-queries.html#the-breakpoint-mixin

**Comment by gakimball** [comment]
This happens if `brkpt_name` is the largest breakpoint in the list. There's no higher breakpoint to use as the ceiling of the media query. I added a warning to the `breakpoint()` function to explain this behavior.

**Comment by designerdean** [comment]
This seems to be happening in the Foundation files—in _top-bar.scss:

![screen shot 2016-02-11 at 2 57 51 pm](https://cloud.githubusercontent.com/assets/729893/12992259/818c58c0-d0d0-11e5-96cf-10122614fc8d.png)
![screen shot 2016-02-11 at 3 03 43 pm](https://cloud.githubusercontent.com/assets/729893/12992286/ac19cdac-d0d0-11e5-822a-b3b2939236f4.png)

**Comment by gakimball** [comment]
@designerdean Fixed in the `develop` branch via 8252c2ba8f2703a377dc0cf594aa5a2e3ab2ad7a and 8b2f710a9dd3ebd6bf194b5e561c46ef0acf016c

**Comment by designerdean** [comment]
Thanks, @gakimball! Loving the quick responses to all the issues. Will this fix be in the version 6.2 release?

**Comment by gakimball** [comment]
Yep! We just published a [release candidate for 6.2](https://github.com/zurb/foundation-sites/releases/tag/v6.2.0-rc.1) if you want to give it a try.
