### ISSUE TITLE
Label Right not working

### ISSUE THREAD

**Issue by cavpollo** [zurb/foundation-sites#7726]
Checking the Foundation Kitchen Sink (http://foundation.zurb.com/sites/docs/kitchen-sink.html) I noticed that the form's label right alignment apparently wasn't working.

This code claims that the input's label will be right and middle aligned:

    <div class="row">
      <div class="small-3 columns">
        <label for="middle-label" class="right middle">Label</label>
      </div>
      <div class="small-9 columns">
        <input type="text" id="middle-label" placeholder="Right- and middle-aligned text input">
      </div>
    </div>

But my browser shows it middle left aligned:

![Left Aligned Label](http://i.imgur.com/tWRYttb.png)

Could it be a typo and it was meant to be `float-right` instead of just `right`, or is the class `right` not working?

**Comment by andycochran** [comment]
Looks like a typo on the Kitchen Sink page. It should be `text-right`, according to the [forms documentation](http://foundation.zurb.com/sites/docs/forms.html).

**Comment by cavpollo** [comment]
Yeah, you are right. The docs/form example works correctly.

**Comment by zurbrandon** [comment]
Got this all fixed up on the develop branch. Thanks for the catch!
