### ISSUE TITLE
"Complete" download of F6 is missing the block-grid

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#7729]
If you go [here](http://foundation.zurb.com/sites/download.html/) and [download the Complete edition](http://foundation.zurb.com/sites/download/assets/complete-f6.zip) of Foundation 6, the `block-grid` component (and possibly others) is missing from `foundation.css`.

**Comment by tjhiggins** [comment]
http://foundation.zurb.com/sites/docs/grid.html#block-grids

**Comment by badcat** [comment]
There's a difference from the various ways to get Foundation - Download page variations as well as version releases and incomplete CSS.  I just mentioned this to Rafi via email.

To note:  http://foundation.zurb.com/sites/download.html/

1)  Suggest putting the version number of Foundation that will get downloaded somewhere on this page or on the download buttons.  For example, "Download Everything" is only v 6.0.5, while "Custom Download" uses v 6.1.1

2) "Download Essentials" includes no usable CSS  :(   only an empty app.css file

**Comment by colin-marshall** [comment]
This was my fault. Somebody on StackOverflow posted [this question](http://stackoverflow.com/questions/34540065/how-to-use-block-grid-classes) about the Foundation 6 block-grid and then they linked to the Foundation 5 docs regarding the block-grid. I looked at the docs without realizing they linked the wrong version. Thanks @tjhiggins!
