### ISSUE TITLE
Foundation.Slider: miscalculation of left handle with nonzero `start` value

### ISSUE THREAD

**Issue by NuckChorris** [zurb/foundation-sites#7730]
Reproduction of error as well as demonstration of expected results: http://codepen.io/anon/pen/RrodPJ

It appears that a nonzero `start` value isn't taken into account when calculating the left handle's position on Foundation.Slider, resulting in (in some cases) a completely unusable slider.

Additionally, during creation of the reduced test cases, I noticed that the default options (start: 0, initialStart: 0, end: 100, initialEnd: 100) result in a missing fill upon initial render of double-sided sliders

EDIT: might actually be more weird math since `data-initial-start="0" data-initial-end="200" data-start="50" data-end="100"` doesn't result in the second quarter being filled, it results in the 50%-150% range being filled.

**Comment by zurbchris** [comment]
Interesting, if you have a solution, I'd love to see a pr for this.

**Comment by kball** [comment]
Fixed by https://github.com/zurb/foundation-sites/pull/8506, will be in 6.2.1

**Comment by metinglc** [comment]
hi,

the problem continues in the last version.

my solution:
slider.js line 178

- dim = movement - (isNaN(handlePos) ? this.options.initialStart/((this.options.end-this.options.start)/100) : handlePos) + handlePct;
+ dim = movement - (isNaN(handlePos) ? ((this.options.end - this.options.initialStart) / 100) / ((this.options.end - this.options.start) / 100) : handlePos) + handlePct;
