### ISSUE TITLE
[Dropdown Menus] docs: space between dropdown and menus (Events section)

### ISSUE THREAD

**Issue by briantan888** [zurb/foundation-sites#7737]
show.zf.dropdown menus
hide.zf.dropdown menus

**Comment by rafibomb** [comment]
Can elaborate on this issue a bit so we can tackle it? Thanks!

**Comment by briantan888** [comment]
Just typo in the doc. http://foundation.zurb.com/sites/docs/dropdown-menu.html last 2nd section Events

**Comment by gakimball** [comment]
Fixed via zurb/foundation-docs@dd5c4513d446ce771bbe51af75214c9be3cd376d

You can see the fix on the live docs.
