### ISSUE TITLE
[Material Foundation] Broken checkbox icon on Ubuntu

### ISSUE THREAD

**Issue by MichalZalecki** [zurb/foundation-sites#7740]
There is a problem with checkboxes at least on Ubuntu Linux, Chrome and Firefox.

![checkboxes](https://pbs.twimg.com/media/CXGdEJ4UkAAKlVv.png)

**Comment by gakimball** [comment]
We don't maintain Material Foundation; I'd recommend hitting up the folks over at [eucalyptuss/material-foundation](https://github.com/eucalyptuss/material-foundation).
