### ISSUE TITLE
Foundation init

### ISSUE THREAD

**Issue by nimaen** [zurb/foundation-sites#7741]
Hi,

I'm new to foundation (6), and I had some newbie problems with the library initialisation.
I now know that you need to call `$(document).foundation();` to init the library but I could not find any reference in the documentation.

If I'm mistaken, I'd gladly have someone showing me where I can find this information :)
If not, please make it obvious in the documentation.

**Comment by colin-marshall** [comment]
It's in the JavaScript page of the docs:
http://foundation.zurb.com/sites/docs/javascript.html#initializing

**Comment by nimaen** [comment]
Thank you @colin-marshall :+1: 
I thought it would be easily found, like on top of a `Getting Started` page.

**Comment by colin-marshall** [comment]
Ya it would probably help to have something like a "Project Setup" page under the "Getting Started" section.
