### ISSUE TITLE
How to combine named breakpoint with type of orientation?

### ISSUE THREAD

**Issue by evanre** [zurb/foundation-sites#7743]
Hi, I need to combine named breakpoint with orientation. Somthing like this: `@media breakpoint(medium portrait) {}` To obtain `@media screen and (min-width: 640px) and (orientation: portrait) {}`. How I can do this? 

Thanks for help.

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by gakimball** [comment]
We were working on a feature to combine media queries, but differences between Libsass and Ruby Sass made it too difficult to implement before 6.0.0 shipped. The syntax would look like this (note the comma separation):

```scss
@include breakpoint(medium, landscape) {
}
```

In the mean time, you can get the behavior you want by using `breakpoint()` as a function:

```scss
@media screen and #{breakpoint(medium)} and #{breakpoint(landscape)} {
}
```

**Comment by havutcuoglu** [comment]
**Question:** when will the implementation of cobined breakpoints like width and modus are done?
`@include breakpoint(medium, landscape) {}`

Thanks a lot.

**Comment by DanielRuf** [comment]
@havutcuoglu it seems it was never implemented.

Not sure if there is / was a specific branch for this or some PR.

See https://github.com/foundation/foundation-sites/blob/v6.6.3/scss/util/_breakpoint.scss#L52

**Comment by havutcuoglu** [comment]
> @havutcuoglu it seems it was never implemented.
Not sure if there is / was a specific branch for this or some PR.
See https://github.com/foundation/foundation-sites/blob/v6.6.3/scss/util/_breakpoint.scss#L52

Yes I checkend it before. Also it is not possible to get 'Portrait' or 'Landscape' modus in javascript. 
That's not nice. I think the orientation is an important breakpoint.

**Comment by DanielRuf** [comment]
PRs which add this are very wlcome.

**Comment by havutcuoglu** [comment]
@gakimball is this possibility combined breakpoints like width and orientation in your example are implemented now?
```
@media screen and #{breakpoint(medium)} and #{breakpoint(landscape)} {
}
```
If yes, in which version of foundation?

Thank you very much and best regards
