### ISSUE TITLE
_settings.scss cannot import util/util

### ISSUE THREAD

**Issue by sfarbota** [zurb/foundation-sites#7744]
The folder structure under `/scss` is currently as follows:

    /scss
        /settings
            _settings.scss
        /util
            _util.scss
        (other directories and files)

However, [line 42 of _settings.scss](https://github.com/zurb/foundation-sites/blob/fdd38a922c8d6bef7759c1f40109b72074872395/scss/settings/_settings.scss#L42) currently tries to import _util.scss like so:

    @import 'util/util';

So when I try to import _settings.scss into my project, it fails since it can't find _util.scss. Shouldn't this line be changed to this?:

    @import '../util/util';

If so, I'd be happy to send a pull request for this. I just wanted to check first to make sure I wasn't misunderstanding something.

**Comment by colin-marshall** [comment]
You're supposed to have `foundation-sites/scss` in your include/import paths when you compile the Sass. So if you installed Foundation through npm, you would need to add `node_modules/foundation-sites/scss` to the paths.

This is discussed in the [Compiling Manually Section of the Docs](http://foundation.zurb.com/sites/docs/sass.html#compiling-manually).

**Comment by sfarbota** [comment]
Ahh got it. Thanks for the explanation!

**Comment by ch-tactica** [comment]
Documentation implies you can simply copy the file into your scss directory from the `node_modules` directory. This is a filthy lie!

**Comment by ncoden** [comment]
Hi @ch-tactica! If you have any idea how to improve the documentation on this issue, feel free to open a pull request! I'd be glad to merge it.
