### ISSUE TITLE
[Reveal] $reveal-offset's value ignored

### ISSUE THREAD

**Issue by kty** [zurb/foundation-sites#7747]
Reveals always have a top margin of 100px regardless of `$reveal-offset`'s value. In fact `$reveal-offset` isn't used anywhere.

**Comment by rafibomb** [comment]
You're right! Are you able to help with a PR to add this into the reveal-modal-base? Thanks!

**Comment by martinplateado** [comment]
Any fix? I've the same issue

**Comment by designerdean** [comment]
The $reveal-offset is now getting applied to the margin-top and margin-bottom of .reveal. However, it makes no difference if it's 0 versus if it's 500. No matter what, the modal is vertically aligned to the center of the viewport. What do I have to do to move the modal up higher? I like it only about 100px from the top of the screen, I think modals that are perfectly centered vertically look odd.

**Comment by robeasthope** [comment]
Lokk slike a bug in the javascript - Attempting to override the css just results in Reveal adding the 100px offset back in via the top positioning

**Comment by MikePugs** [comment]
@designerdean I have the following code which positions a reveal at the top of the window (regardless of scroll position).

Customizing to make it 100px from the top should be pretty straight forward.

`
$('[data-reveal]').on('open.zf.trigger', function () {
            var $element = $(this);
            var eleDims = Foundation.Box.GetDimensions($element[0]);
            $element.css('top', $(window).scrollTop() - (eleDims.offset.top - $element.position().top) + 'px');
            $element.css('max-height', eleDims.windowDims.height + 'px');
}
`

**Comment by gakimball** [comment]
The `$reveal-offset` variable is being removed from the codebase in 6.2. Reveal's positioning logic has been reworked to fix a lot of existing issues, and as part of that, it's handled in JavaScript rather than CSS.
