### ISSUE TITLE
How to use HTML in tooltips?

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#7748]
How can I use HTML tags in Tooltips?

**Comment by andycochran** [comment]
Tooltips are just for text. You'll want to use a [dropdown pane](http://foundation.zurb.com/sites/docs/dropdown.html) instead.

**Comment by zurbchris** [comment]
What @andycochran said :+1:

**Comment by FabKos** [comment]
Thx @andycochran for the hint! But I still think it's bad to change so much, i ruins my flow, i don't know what was so wrong with html in tooltips... but - i'll change the code, once again. Thx zurb -.-
