### ISSUE TITLE
header tags within <li> has extra spacing in Firefox

### ISSUE THREAD

**Issue by captaincoffee** [zurb/foundation-sites#7751]
<hx> tags within a list display extra space and are misaligned with the disk/other. This happens in Firefox, but not Chrome or Safari.

**Comment by zurbrandon** [comment]
Can you elaborate on this a bit? headers inside lis become their own lines since they're block elements, are you expecting something differently? 

http://codepen.io/zurbrandon/pen/OMWema

**Comment by captaincoffee** [comment]
That's what I was seeing but only on Firefox. We had the same discussion, but as it worked in some instances thought it was an issue. Thanks for replying, sorry for the trouble.
