### ISSUE TITLE
[Building Blocks] F6 Top-Bar with Centered Logo 

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#7756]
Not sure if this is the correct place to put this, but I didn't see any way that I could submit a Building Block. Somebody on StackOverflow asked how to make the [Top-Bar with Centered Logo & Buttons](http://zurb.com/building-blocks/top-bar-with-a-centered-logo-and-buttons) work on F6 so I migrated it for them. Here's the link to my pen: http://codepen.io/colin-marshall/pen/obBVgW

BTW, should the title of this Building Block really have the word "buttons" in it? There are only dropdown menus and no buttons.

**Comment by rafibomb** [comment]
Nice! We'll add this in and credit you on it! I'll close the issue here with a link to it soon - Thanks!

**Comment by colin-marshall** [comment]
Updated the Pen with variables for easy adjusting of the logo width and the space between the logo and the menu text.

**Comment by gakimball** [comment]
Added! <http://zurb.com/building-blocks/centered-top-bar-with-logo>

Thanks for the contribution :)
