### ISSUE TITLE
[Abide] $input-background-invalid variable not being applied

### ISSUE THREAD

**Issue by devjoseluis** [zurb/foundation-sites#7761]
**How can we reproduce this bug?**

1. Go to [this](https://github.com/zurb/foundation-sites/blob/develop/scss/forms/_error.scss#L19) line when  $input-background-invalid variable is defined.
2. Then the [form-input-error mixin](https://github.com/zurb/foundation-sites/blob/develop/scss/forms/_error.scss#L40) does not apply the variable. The variable is never used.

**What did you expect to happen?**
The variable will be applied to the input

**What happened instead?**
The variable does not apply

**Comment by rafibomb** [comment]
Thanks for the report! Are you able to submit a PR so we can add this feature in? It should be in the form-input-error mixin.

**Comment by gakimball** [comment]
I got you, Rafi ;)
