### ISSUE TITLE
[Forms] Forms documentation reuses checkbox ids, wreaking havoc with labels

### ISSUE THREAD

**Issue by nanodeath** [zurb/foundation-sites#7765]
**How can we reproduce this bug?**

1. Go to http://foundation.zurb.com/sites/docs/forms.html#fieldset-styles in say, Firefox 43.
2. Click on any of the labels, e.g. "Checkbox 1"

**What did you expect to happen?**

The checkbox next to the clicked label to be toggled checked or unchecked.

**What happened instead?**

A checkbox from the previous section, "Checkboxes and Radio Buttons", got toggled instead.

**Comment by gakimball** [comment]
Fixed via cdc30367cd3804f3568cf201546c613498306a12

It's on the live docs now.
