### ISSUE TITLE
[Toggler] reflow problem

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7767]
is there a way to reflow toggler i call Foundation.reflow() after added elements to dom but toggler not init on the new elements

**Comment by briantan888** [comment]
I had success with this syntax

$('#foo').html(data).foundation();

.html can be .append etc.

**Comment by designerno1** [comment]
hm ok i now do
$('#foo').foundation(); after inserted to dom

**Comment by gakimball** [comment]
@designerno1 That's the right way to do it!
