### ISSUE TITLE
[Reveal] Changing data reveal id and using reflow does not open new modal

### ISSUE THREAD

**Issue by Dwyguy** [zurb/foundation-sites#7772]
I have a button that opens a modal, and that modal contains a button to a open a second modal. Let's say the first modal contains some terms to agree to, and after the user accepts it, I don't want it to appear again. So I change the `data-reveal-id` of the button that opened the first modal so it directly opens the second modal. However, the button still opens the first modal.  I have tried using `reflow`, but it does not seem to work.

I have a fiddle set up here: http://jsfiddle.net/wy6mj790/

Am I just missing something here, or is this a bug?

**Comment by zurbchris** [comment]
There's not a super easy way to do this in F5, as this wasn't a use case it was designed for, so far as I can tell. That doesn't necessarily make it a bug either, it just wasn't built to do what you want it to without some finagling. There's no baked in method for destroying a Reveal plugin in F5, so you can't just call that method. 

I tinkered with it for a few minutes on your fiddle, but didn't really get anywhere, other than disposing of the first modal. Your goal could probably be accomplished in about 10 lines or less of JS, but I realize that's less than ideal.

Unfortunately, Reveal isn't flexible enough out of the box to do what you are looking for.

**Comment by Dwyguy** [comment]
Fair enough, I appreciate your looking into it.  My work around as of now is to manually trigger the modals and set a few attributes to detect when one has been closed.  It's not what I was hoping for but it's still doable.  Thank you for your response

**Comment by zurbchris** [comment]
Closing this, thanks for your time.
