### ISSUE TITLE
[Global Styles] Update documentation to reflect removal of $rem-base

### ISSUE THREAD

**Issue by dchekanov** [zurb/foundation-sites#7775]
`$rem-base` variable was removed in [6.1](https://github.com/zurb/foundation-sites/releases/tag/v6.1.0), but [documentation](http://foundation.zurb.com/sites/docs/global.html) still instructs users to use it, which is confusing. Please update docs (I am not yet familiar enough with the project to do it myself).

**Comment by gakimball** [comment]
Done! And deployed to the live documentation.
