### ISSUE TITLE
[Off-canvas] Page height not 100%

### ISSUE THREAD

**Issue by Websitescity** [zurb/foundation-sites#7776]
Hello,
there an issue with height 100% when I use off-canvas. The page is not on height 100%. 
![off-canvas](https://cloud.githubusercontent.com/assets/13006439/12140315/2d9c4f70-b467-11e5-89c7-8788b4868764.png)

To fix it I use:

.off-canvas-wrapper, .off-canvas.position-left, .off-canvas-wrapper-inner  {
  height: 100%;
}

**Comment by tdhartwick** [comment]
This is posing to be more complex than the snippet provided. We're still getting box shadows beneath the body content. Also getting some funky rendering issues when using the `height` property. `min-height

**Comment by colin-marshall** [comment]
@Websitescity @tdhartwick I'm closing this issue until we have a reproducible case to test against. Please reopen with the info requested here:
https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md
