### ISSUE TITLE
Reveal width not calculated correctly in IE

### ISSUE THREAD

**Issue by eliotc1986** [zurb/foundation-sites#7777]
The full-width reveal modal width doesn't account for the scroll-bar in IE. Does it makes sense to change the logic in foundation.reveal.js (line 222) 

from:

```
'width': eleDims.windowDims.width
```
to:

```
'width': eleDims.windowDims.outerWidth
```

outerWidth calculates the full-width of the browser window including the scrollbar.

**Comment by eliotc1986** [comment]
Any thoughts on how to improve this? Not just for IE but for windows users browsing on Chrome as well

**Comment by christianmagill** [comment]
I have the same issue on Chrome for Mac OSX

**Comment by christianmagill** [comment]
The issue seems to resolve for me on Mac by adding

`html{ overflow-y: scroll; }`

**Comment by rafibomb** [comment]
Looks like there are a few issues happening there. We've started a conversation and we're going to create a lot of traction from this to get more bugs fixed and get more people involved.

I'm wondering if you have some more specific ideas or workarounds to share post we put up? http://foundation.zurb.com/forum/posts/38459-f6-reveal-modal-suggestions

Thanks!

**Comment by kball** [comment]
There were substantial changes to reveal in v6.2 which fixed a number of issues.  @eliotc1986 @christianmagill can you confirm if this is still an issue for you today?  Thanks

**Comment by colin-marshall** [comment]
@eliotc1986 @christianmagill I'm going to close this issue. Feel free to reopen it if the problem still exists in v6.2 or later.
