### ISSUE TITLE
foundation6 - Responsive templates to kick off your projects news-magazine layout

### ISSUE THREAD

**Issue by peterstouw** [zurb/foundation-sites#7778]
Hi Foundation6 users,
I'm using the layout news-magazine.html from http://foundation.zurb.com/templates.html in the zurb template environment downloaded with yetilaunch. The _settings.scss file dowloaded with yetilanch is missing a lot of settings to get the news-magazine layout display correctly.
Does anybody have the correct _settings.scss and maybe other _xxxx.scss files needed?
Now I'm using the .css file used by the demo (http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css) and it's working, but I need the .scss files to improve my layout based on the news-magazine template.

Thanks,
Peter Touw.

**Comment by PurpleBracket** [comment]
I've downloaded the template and everything works just fine, please make sure you're including all the scss and javascript components for foundation. Also I don't believe that the settings.scss would have setting specific to this template, the settings.scss allows you to style all the components individually, if you do that and maybe write some of your own css to polish it it should be enough.

Hope this helps

**Comment by peterstouw** [comment]
Hi PurpleBracket,

Thank you for your good response. You are right it works without exta .scss files. 
For some reason, when I run >npm run build< the app.css is only 5kb. When I run >npm start< the app.css is 515kb (uncompressed, multiple lines) and works fine. I did some adjustments in the gulpfile.js. So the problem must be in the gulpfile, my fault.
Still strange, that >npm start< will not compress the file. So running >npm run build< is needed.
