### ISSUE TITLE
Issue using javascript utilities

### ISSUE THREAD

**Issue by PurpleBracket** [zurb/foundation-sites#7779]
Hey, 

I ran into a problem trying to implement a sticky nav using foundation's sticky component, after several tries with no success I went to try using any of the javascript utility scripts and non worked for me.

The sticky javascript ads all relevant tags and html, but won't update the top position on the sticky element.

And when I tries to use box on multiple items I got this error:
foundation.util.box.js:49 Uncaught TypeError: elem.getBoundingClientRect is not a function

Any help would be appreciated

**Comment by gakimball** [comment]
Can you post the HTML you wrote?

**Comment by zurbchris** [comment]
For an example of a sticky nav, take a look at this pen: http://codepen.io/zurbchris/pen/rxMaoX

**Comment by PurpleBracket** [comment]
I finally got the sticky to work after finding @zurbchris pen this morning. But I can't figure out what I was doing wrong. Trying to get multiple sticky elements on one page and running into issues there, I like the  new sticky plugin. Is it better to initialize everything in js? Or would it make no difference?

this is what I was playing with.
http://codepen.io/jxtposed/pen/mVWpoy

and here's the forked version of @zurbchris pen.
http://codepen.io/jxtposed/pen/wMJEXM

 But no luck with Box yet. 

Thanks guys!

**Comment by zurbchris** [comment]
So, Foundation.Box.GetDimensions only works for a single element at one time, so if you're passing a jQuery collection or something from querySelector that has a length property, only the first element will have a value returned. If you want an array of sizes, you'd have to map over a collection, like so: 
```js
    var foo = Array.prototype.map.call(document.getElementsByClassName('bar'), Foundation.Box.GetDimensions);
```

Other than that, I have no earthly idea what would be causing that error, assuming you're passing in a valid DOM element.

**Comment by PurpleBracket** [comment]
Still no luck with Box.

http://codepen.io/jxtposed/pen/XXMvrp

Sorry if I am missing something obvious. 

Appreciate the help

**Comment by IAmEddieDean** [comment]
You need to pass in a DOM Object, not a selector string. This could be fixed by adding a jQuery call, or using `document.getElementById('some-element')`.

**Comment by PurpleBracket** [comment]
awesome, thank you @zurbchris
