### ISSUE TITLE
[Slider] Wrong thumb position at the right

### ISSUE THREAD

**Issue by ArtemZag** [zurb/foundation-sites#7782]
**How can we reproduce this bug?**
Just move the slider thumb to the most right

**What did you expect to happen?**
I expect the thumb right border to be on the same line where the slider line ends

**What happened instead?**
The thumb position gets a bit more to right (~10px)

**Test case**
you can use your own page with examples: http://foundation.zurb.com/sites/docs/slider.html

**Comment by andycochran** [comment]
Related to #7660.

**Comment by gakimball** [comment]
Duplicate of #7660

**Comment by ArtemZag** [comment]
Thanks, guys :) And sorry for the duplicate.

**Comment by gakimball** [comment]
No worries!
