### ISSUE TITLE
[Installation] HTML Starter Template Needed in Docs

### ISSUE THREAD

**Issue by andrewbiddinger** [zurb/foundation-sites#7783]
Could there be added to the docs a HTML starter template for easy referencing?

**Comment by gakimball** [comment]
Would linking to [these](http://foundation.zurb.com/templates.html) be helpful?

**Comment by andrewbiddinger** [comment]
Templates are helpful. But the problem I was running into was not finding a standard canonical source for a simple page. I added a pull request with a suggested change to the docs: #7785

**Comment by andrewbiddinger** [comment]
Similar to bootstraps: http://getbootstrap.com/getting-started/#template
