### ISSUE TITLE
[Reveal] Reveal Modal Stays Hidden With Animation and Flexbox

### ISSUE THREAD

**Issue by andrewbiddinger** [zurb/foundation-sites#7786]
Reveal's modal window stays hidden when 1. You are using animation (data-animation-in="spin-in" data-animation-out="spin-out") and 2. flexbox  is enabled. 

![screen shot 2016-01-06 at 12 47 07 pm](https://cloud.githubusercontent.com/assets/6351977/12149795/b15bff98-b473-11e5-96a5-103b961f8dfb.png)

**Comment by andrewbiddinger** [comment]
Or, "doesn't ever appear" is anothe way to say it. If I inspect the modal after the reveal button has been hit, the modal has the style="display: hidden" on it.

**Comment by zurbchris** [comment]
Is Motion-UI included? It's not by default, and is only an optional add-on package.

**Comment by andrewbiddinger** [comment]
I am using the foundation.min.js distributed version. I believe that has motion-ui built in, right @zurbchris ?

**Comment by zurbchris** [comment]
No, Motion-UI is an independent animation library. It's made by us, but we ship it separate from Foundation. If you're using bower, you can `$ bower install motion-ui` and link the css file in the head of your page. There's also a cdn, available here: https://cdnjs.com/libraries/motion-ui

**Comment by andrewbiddinger** [comment]
Ahhh...yes, you are right :+1: I wonder if this could be a bit more clear in the documentation. Thanks!
