### ISSUE TITLE
Can't find Python executable "python", you can set the PYTHON env variable.

### ISSUE THREAD

**Issue by curtisblack2004** [zurb/foundation-sites#7788]
These are the errors I get when trying to install foundation 6 on windows 10 64bit:

I am using:
Ruby 2.2.3
Node.js 5.3.0
Git 2.7.0
NPM 3.3.12 (ran the global command: npm install --global foundation-cli).

If windows users need to install python to path shouldn't that be mentioned somewhere?

c:\wamp\www\utahreia3.1\webroot\utahreia\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Curtis Black\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Curtis Black\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\Curtis Black\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Curtis Black\\AppData\\Roaming\\npm\\node_modules\\foundation-cli\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\wamp\www\utahreia3.1\webroot\utahreia\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

> utf-8-validate@1.2.1 install c:\wamp\www\utahreia3.1\webroot\utahreia\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

c:\wamp\www\utahreia3.1\webroot\utahreia\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\Curtis Black\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Curtis Black\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\Curtis Black\AppData\Roaming\npm\node_modules\foundation-cli\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Curtis Black\\AppData\\Roaming\\npm\\node_modules\\foundation-cli\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\wamp\www\utahreia3.1\webroot\utahreia\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

 ✓ New project folder created.
 ✗ Node modules not installed. Try running npm install manually.
 ✓ Bower components installed.

**Comment by zurbchris** [comment]
This is a node-gyp issue, it's a command line tool that a ton of node modules use, not just us. You will need Python to take advantage of some of the features we have in the full stack. Check out [Node-Gyp's](https://github.com/nodejs/node-gyp#installation) installation guide for Windows and see if that helps. 

If you don't want to go through setting this up, you'll have to utilize the CSS-only version of the framework, as Node-Sass (libsass), BrowserSync, and several others all rely on node-gyp, which relies on Python.

Hope that helps you, closing the issue, as it's not a Foundation bug.

**Comment by miukki** [comment]
i have just updated python  -- and problem is gone

**Comment by DanielRuf** [comment]
For Windows try [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) with `npm install --global --production windows-build-tools`
