### ISSUE TITLE
F6 - button-group not last button has border-right

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#7789]
Why the button has a right border in a button-group? It is pretty ugly while other buttons outside the group doesn't have such border-right. Could this border-right be removed in the next release?

http://nl.tinypic.com/r/ibmeeo/9

**Comment by gakimball** [comment]
The `border-right` is necessary to separate multiple buttons in a button group. If you just have one in there, you're going to get that visual bug.
