### ISSUE TITLE
anyway to include off-canvas menus outside of zurb foundation?

### ISSUE THREAD

**Issue by xstortionist** [zurb/foundation-sites#7791]
I want to use the off-canvas menu outside of the zurb foundation framework inside a little site I'm working on. Is this possible to compile just the off canvas menu only?

**Comment by gakimball** [comment]
If you're using the Sass version, you can print out just the global styles and off-canvas styles:

```scss
@import 'foundation';

@include foundation-global-styles;
@include foundation-off-canvas;
```

**Comment by xstortionist** [comment]
is there a way to print out the off-canvas javascript as well?

**Comment by gakimball** [comment]
Load just these four files (borrowed from [the documentation](http://foundation.zurb.com/sites/docs/off-canvas.html#js-module)):

- `foundation.core.js`
- `foundation.util.triggers.js`
- `foundation.util.motion.js`
- `foundation.offcanvas.js`

The individual utility files are very small.

**Comment by xstortionist** [comment]
@gakimball thank you for the information. I'm going to play around with this tonight within my project. Can't wait!

**Comment by gakimball** [comment]
No problem! :)
