### ISSUE TITLE
Yeti Launch installs old version

### ISSUE THREAD

**Issue by derekbadsky** [zurb/foundation-sites#7792]
Yetti Launch installs 6.0 even though 6.1.1 is the, as of now, current version. It should always install the current master branch otherwise users don't get all the latest bug fixes and feature improvements.

**Comment by zurbrandon** [comment]
We have this documented on the yetilaunch tracker now. We hoped to be able to run commands to update , but this won't work without NPM and git installed globally on your machine. We're working on a fix currently. Sorry for the setback on that.

https://github.com/zurb/yeti-launch-tracker
