### ISSUE TITLE
[DOCS] Data options need documentation

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#7793]
How to use the data options

`data-reset-on-close="true"`

or like 

`data-options="animInFromLeft:fade-in;`

Each component needs to have these examples, or a page needs to be added to explain these.

**Comment by gakimball** [comment]
Explaining `data-options` on the JavaScript overview page is preferable.

**Comment by gakimball** [comment]
Done! And the "Plugin Options" section of each component page already links to the JavaScript overview page.
