### ISSUE TITLE
Where to download zurb foundation 5 with sass included?

### ISSUE THREAD

**Issue by xstortionist** [zurb/foundation-sites#7796]
Where to download zurb foundation 5 with sass included?

**Comment by colin-marshall** [comment]
You can clone this repo and then do: `git checkout -t origin/V5`

**Comment by xstortionist** [comment]
thank you sir

**Comment by gakimball** [comment]
You can also clone the Foundation 5 templates: [Compass](https://github.com/zurb/foundation-compass-template) or [Libsass](https://github.com/zurb/foundation-libsass-template).
