### ISSUE TITLE
jQuery doesn't work after Foundations 6 build

### ISSUE THREAD

**Issue by jrock17** [zurb/foundation-sites#7797]
I found a few posts with this same problem. It looks like there is some sort of conflict when the JS files are compiled/minified that prevents jQuery from working properly after building.

To test, I did this on a fresh install. I created a new instance and only made one change: added a reveal modal to the index page. It works fine when I preview locally. But when I run "foundation build", the jQuery calls no longer work in the output files in /dist.

I posted the test site here so you can see: http://zurbtest.site44.com/

There are no errors in the console. But if you click on the button up top "Click here to test the modal/jQuery" you will see the panel opens but none of the jQuery effects work.

I can get everything to work by re-including jQuery again on it's own but that's not ideal. Looks like other users had success with removing the listeningElementsMutation function but that didn't work for me.

Some other topics with a same issue: 
http://foundation.zurb.com/forum/posts/36149-jquery-is-not-working-in-foundation-6
http://stackoverflow.com/questions/34293365/foundation-6-core-js-error
http://foundation.zurb.com/forum/posts/36878-foundation-6-javascript-not-working

Thanks!

**Comment by LanceGundersen** [comment]
I as well just noticed this on a test run of build and no errors in console.

**Comment by gakimball** [comment]
@zurbchris Are we aware of any lingering mangling issues?

**Comment by zurbchris** [comment]
Not to my knowledge, but visiting that test site I see it's on v 6.0.3, which still had an issue or two.

**Comment by zurbchris** [comment]
Uncss strikes again! I think it's stripping `.foundation-mq` which is required by Foundation.MediaQuery, which controls all sorts of things indirectly, including the size and placement of Reveal...

**Comment by LanceGundersen** [comment]
Looks like that was the culprit (only console errors are the images URL's).

**Comment by gakimball** [comment]
@zurbchris Our UnCSS config is currently ignoring `meta` tags:

```js
ignore: [
  new RegExp('^meta\..*'),
  new RegExp('^\.is-.*')
]
```

**Comment by zurbchris** [comment]
So, the issue stems from UnCss stripping out a couple of classes that are relied upon by the Foundation JS, which causes the script load to silently fail. A temporary solution to this is to comment out line 126 from the Zurb Template gulpfile.js
```js
.pipe(uncss)
```
This will prevent uncss from doing it's thing, so make sure you are commenting out any unused components from your import statements.

**Comment by jrock17** [comment]
Thanks @zurbchris. I came to the same conclusion and it's working with UnCss commented out.

Definitely a silent killer.
