### ISSUE TITLE
[Tooltip] Font Weight

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#7798]
What do y'all think of adding a `_settings.scss` variable for `$tooltip-font-weight`? 

Currently, `font-weight: bold` is hardcoded into `@mixin has-tip`. :disappointed: 

Using both underline and bold draws a lot of attention to `.has-tip`. This seems heavy-handed to me. Designers should choose if `.has-tip` is bold or normal. For an app I'm working on, bold is too much, and a custom style to override this seems silly. 

I'll PR if the idea is acceptable.

**Comment by zurbrandon** [comment]
Sounds good to me, Andy!

**Comment by gakimball** [comment]
If `normal` is still readable enough, I'd be fine with removing `font-weight: bold;`, as then we don't need a setting at all. The type might be too small, though.

**Comment by andycochran** [comment]
@gakimball I think that depends on how noticeable the tooltip needs to be. If you want to notice tooltips while scanning the page, they probably need to be bold. But if you only want them noticeable while actually reading the content, a normal weight will suffice. 

I think I'll use `$has-tip-font-weight` (not `$tooltip-font-weight`), as it's more semantic.

**Comment by gakimball** [comment]
Ohhh, y'know I didn't read close enough, I thought you were talking about the tooltip itself. ;) Bold is a sensible default for `.has-tip` I'd say, so having a variable would be good.

**Comment by andycochran** [comment]
@gakimball I totally understand the confusion—we all use "tooltip" loosely to mean both the definition and the defined term. Which is why my PR also clarified the docs to not say, "a tooltip appears below the the definition." Huh? It appears below the defined term. :confused:
