### ISSUE TITLE
Build for Production Javascript Issue

### ISSUE THREAD

**Issue by LanceGundersen** [zurb/foundation-sites#7800]
Upon running npm run build and pushing to the dev site it appears there is something happening with the Javascript as if its not even there.

First place I noticed was on on the post build site the three "tiles" aren't moving as they should (just hidden). Take a look at the homepage on the dev vs the post build.

npm -v
2.14.12
node -v
v4.2.4
bower -v 
1.7.2

Here is the dev site http://www.mikelinc.com/dev/

Here is the post build site http://www.mikelinc.com/dev/production/

**Comment by gakimball** [comment]
This site is on Foundation 6.0.6. @zurbchris were any more mangling issues fixed in 6.1 do you recall?

**Comment by zurbchris** [comment]
This could be related to not including the media query util lib. That's
been an issue for others.

**Comment by zurbchris** [comment]
This is a strange one, it seems uncss is stripping out the Motion-UI classes, and quite possibly the classes for their additional parallax plugin. Which is causing more than a couple problems...

**Comment by LanceGundersen** [comment]
@zurbchris anything I should try to either help you or attempt to fix on my end?

**Comment by gakimball** [comment]
@LanceGundersen In `gulpfile.js`, comment out the call to `.pipe(uncss)` and see if that fixes anything.

**Comment by zurbchris** [comment]
What @gakimball said... as I was typing the same thing.

**Comment by LanceGundersen** [comment]
Looks like that was the culprit, the only console errors are due to my urls not being correct. I pushed it to the post build url above.

**Comment by zurbchris** [comment]
Thanks for that, now we know we missed a couple exceptions for uncss. We'll get a fix pushed out as soon as we can.

**Comment by LanceGundersen** [comment]
@zurbchris @gakimball Thanks for the help! A sigh of relief over here!

**Comment by gakimball** [comment]
If you're concerned about file size and aren't already trimming your CSS and JavaScript, here's how:

- In `src/assets/scss/app.scss`, comment out any `@include` for a component you aren't using.
- In `gulpfile.js`, in the variable `PATHS.javascript`, comment out plugins you aren't using.
