### ISSUE TITLE
Block Grid - Centering trailing blocks

### ISSUE THREAD

**Issue by Ne-Ne** [zurb/foundation-sites#7807]
Hi All,

I am trying to get any trailing blocks to center. Such as a 3 column block grid, with 8 blocks.

I am using wordpress WP_Query and wish to use css as adding push classes seems inefficient.

I have found this:

http://foundation.zurb.com/forum/posts/2567-choose-block-grid-alignment

Which lead me to this:

https://github.com/coreysyms/FoundationGridBalancer

As it was for an old version of Foundation I forked it and made some changes:

http://codepen.io/Ne-Ne/pen/YwVqOq

It seem like a strong feature for a grid, unless I count using nth-child and hack at some css..

Many thanks.

**Comment by andycochran** [comment]
Nice!

**Comment by gakimball** [comment]
Very interesting! We'd like to find a solution that doesn't require JavaScript if possible. I believe there's a way to generate the code with Sass mixins, but it may not be a feature we can bundle with the default CSS, because it's a lot of extra code due to the complexity of the selectors required.

**Comment by Ne-Ne** [comment]
Well from what I can see you would need to count and find the remaining columns to create the offset.

I think that a data attribute would be a great feature as in my example I need to turn the functionality off in mobile. @gakimball what do you think about building it into Equaliser?

With some additional data attr you could make it responsive..

**Comment by gakimball** [comment]
Through some intense CSS trickery I was able to write a mixin that does this in pure CSS. It's in the `6.2` branch: f2528364469b42b31170e23a22b177fee6443a67

Because it generates a lot of extra CSS, it's just going to be a mixin you can apply to an existing block grid. It works like this:

```scss
// With the built-in grid classes
.row.up-3 .column {
  @include grid-layout-center-last(3);
}

// With a custom class
.gallery-item {
  @include grid-layout-center-last(5);
}
```

**Comment by Ne-Ne** [comment]
While I read the sass and love the pure CSS aspect @gakimball. My only worry is that it only works if block grid is going to be static.

In my situation I am using wordpress to query and return objects from the users point of view. This mixin will only work if either I set a minimum in the query or I upload a new css file on every time more elements get added or removed.

Additionally I could created number classes but as you said that will create many classes, which I many not use. Unless I am reading this wrong?

**Comment by gakimball** [comment]
The mixin is looking for the total number of items *per row*, not the total number of items in general. So it will work fine with lists that have a variable number of items.
