### ISSUE TITLE
Multiple Abide validation after each submit

### ISSUE THREAD

**Issue by bruteforcehub** [zurb/foundation-sites#7811]
I have this code below, which is triggered once my ajax form gets submitted, it works well after on first run but after modifying the content on the form and try to click the submit button again it will trigger two instance of "valid.fndtn.abide" which results to multiple call on the form submission. As you click the submit the number of instance call multiplies.

```
$(entry[0]).on("submit", function (event) {       
                $(this).on("valid.fndtn.abide", function(){
                    // Handle the submission of the form
                });
               event.preventDefault(); 
            });
```

I was thinking if I can reset the abide validation after successful validation so it won't be triggered multiple times. I hope you can help me on this issue.

**Comment by zurbchris** [comment]
Abide already has a listener for the `submit` event, so you're listening and reacting to it, as is the abide plugin.

**Comment by bruteforcehub** [comment]
I have just tried to use the Submit and remove the valid.fndtn.abide. What happened is that the form continues to submit even though some other requirements failed.

``            $(entry[0]).on("valid.fndtn.abide", function (event) {
                    // Handle the submission of the form
                    console.log("good");
               event.preventDefault(); 
``

**Comment by silentmiles** [comment]
This is old, but I think what you want is:

`$(entry[0]).on("submit", function (event) {                       
               event.preventDefault(); 
});

$(entry[0]).on("valid.fndtn.abide", function(){
     // Handle the submission of the form
});`

I.e, listen to Abide's valid event, and separately listen to the form's submit event, and prevent it's default action.
