### ISSUE TITLE
DropdownMenu.defaults.clickOpen seems broken for Chrome

### ISSUE THREAD

**Issue by imaia** [zurb/foundation-sites#7812]
Hello folks;

I have a dropdown menu and a clickOpen = true configuration here within my website. My development went on using firefox. Everything was fine, until I test it with chrome. It happens that, when I click in the dropdown anchor, using chrome, it won't follow the link unless I click once more, which is quite weird. Seems like a bug to me. I'm using firefox 43 and chrome Versão 47.0.2526.106 (64-bit).

**Comment by zurbchris** [comment]
Can you post the options used for this menu or a link to a live page/codepen? Seems like you're getting the expected interactions on chrome and firefox is doing something strange.

The clickOpen option will retain the open state of the menu until you click outside it  (if closeOnClick = true, default settings) or the parent link again, on browsers with an `ontouchstart` event will cause a slightly different action, as a failsafe for mobile devices.

**Comment by JeremyEnglert** [comment]
No reply. Closing.

**Comment by IamManchanda** [comment]
@imaia Is it still an issue... please let us know? 
We are closing it for now but feel free to reopen!
