### ISSUE TITLE
Scrolling reveal doesn't work on latest Chrome for Android

### ISSUE THREAD

**Issue by JoelESvensson** [zurb/foundation-sites#7816]
This should be reproducible by simply creating a reveal that is larger than the screen

**Comment by JoelESvensson** [comment]
Just found out that this also happens on Chrome for OSX – when you open the reveal while on a small screen. If window gets resized to medium and then back to small again, the scrolling will work. The main difference seems to be that the reveal doesn't have a max-height if opened on a small screen

**Comment by zurbchris** [comment]
@JoelESvensson please checkout [this branch](https://github.com/zurb/foundation-sites/tree/update-reveal), it dramatically changes the positioning algorithm for reveal. More accurate, more performant through value caching, and more!

**Comment by JoelESvensson** [comment]
Scrolling works now! Unfortunately the top is not visible anymore as I have a fixed top bar that is positioned in a layer above it. This might be something I have to fix myself though. Is there any solution you'd suggest?

**Comment by zurbchris** [comment]
fortunately, there's a variable for that. line 441 of _settings.scss : 
```scss
$reveal-zindex: 1005;
```
You should be able to update that value to something higher than whatever your top bar z-index is.

**Comment by gakimball** [comment]
Fixed via 330018d577bfbdaf30dad96fa6a05e4a074419e6
