### ISSUE TITLE
[Reveal] Long Modal's Positioning On Mobile Blocks Content

### ISSUE THREAD

**Issue by andrewbiddinger** [zurb/foundation-sites#7817]
On mobile only - My modal that is ```height: 2539px``` in height has a top value of ```top: -1147.5px;``` which hides a good portion of the content above the browser (Centering It) and it is not possible to scroll up to it. This seems to happen with any modal that is longer than the viewport. One device I tested it on allows scrolling to the top after you have scroll to the very bottom. Weird.

Any thoughts?

**Comment by andrewbiddinger** [comment]
Lots of issues with longer modals on mobile when scrolling. The modal jumps around when you get to the bottom or top.

**Comment by zurbchris** [comment]
@andrewbiddinger if you have a chance, checkout [this branch](https://github.com/zurb/foundation-sites/tree/update-reveal) and play around with / test / break the updates to the positioning algorithm there. I've tested it with modals several thousand pixels tall both on mobile and desktop, and aside from being faaaar less code than the previous version, it also seems way more accurate and consistently positions modals in the center (horizontally), and offset from the top appropriately (no offset if the modal overflows). I'm very interested in community feedback for this, esp for certain Safari specific issues that crop up with this plugin.

**Comment by andrewbiddinger** [comment]
Sweet, I will test it and get back with you on the results. Thanks!

**Comment by gakimball** [comment]
Fixed via 330018d577bfbdaf30dad96fa6a05e4a074419e6
