### ISSUE TITLE
Foundation for Sites Custom Download With No Grid Not Working

### ISSUE THREAD

**Issue by LukePettway** [zurb/foundation-sites#7819]
I'm not sure if it is just me but I was recently trying to download a few of the styles for Foundation for Sites at this url: http://foundation.zurb.com/sites/download.html/#customizeFoundation

All I needed was the form styles, so I deselected everything, selected No Grid and pressed on download custom build. After opening the zip, There was only one CSS file, app.css but it is a zero-byte file. 

Enabling the grid allows the download the happen, so I'm not 100% sure if there is something I'm doing wrong, or if there is a bug where you can't download styles without having a grid option. 

If you go to the page, select No Grid and then download it with everything checked, it also produces the same issue.

**Comment by gakimball** [comment]
Yep, confirmed. The package should have two other files, `foundation.css` and `foundation.min.css`, but those are both missing. `app.css` is always empty, since it's meant to be the user-edited file.

Rolling this into #7033
