### ISSUE TITLE
Foundation for Sites Custom Download Checkbox Issue

### ISSUE THREAD

**Issue by LukePettway** [zurb/foundation-sites#7820]
I decided to create this as a separate bug. On this page http://foundation.zurb.com/sites/download.html/#customizeFoundation, if you uncheck a specific checkbox such as Typography and then click the All Foundations Styles checkbox, it will reselect anything unchecked. Further clicks will make the checkboxes opposite of the state of that checkbox (if it is checked, the rest of the styles will be unchecked.

**Comment by gakimball** [comment]
Confirmed, rolling this into #7033
