### ISSUE TITLE
[Abide] Radio/Checkbox Error colors 

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#7822]
Go to [docs/abide.html](http://foundation.zurb.com/sites/docs/abide.html) and click submit. You'll notice not every radio/checkbox turns red. Technically, you only need `required` on one of the `<input>` tags with the same name. However, Abide seems to only style whichever one has the `required` and those following it. If `required` is on the first one, they all get styled appropriately.

**Comment by ipixel** [comment]
I concur, thought I was doing it wrong, but Abide is not placing the error classes in correctly. Also when you do choose a radio options prior to submission, if you choose the non-required specified option, the option gets the invalid class applied. How did this one get through testing?

**Comment by gakimball** [comment]
Fixed via cc2f2c668bb4f795cfad130915baf1b5f45fd79b

See my closing comment on #7196 for more details.
