### ISSUE TITLE
[Orbit] Swipe not working Android

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7827]
for me swipe on android not working in orbit

**Comment by gakimball** [comment]
What version of Android?

**Comment by designerno1** [comment]
Galaxy S5. Android 5.0 Stock browser

**Comment by zurbchris** [comment]
Confirmed, and annoying...
Reverting to the jQuery Mobile swipe event still works. I'll talk to the team about it to see what we want to do.

**Comment by gakimball** [comment]
Couldn't recreate this on a Galaxy S6 with the Android 5.0 browser. @designerno1 Were you seeing this in the Foundation documentation?

**Comment by designerno1** [comment]
Yes in docs none of the example could be swiped on Galaxy S5 Stock browser

**Comment by designerno1** [comment]
seems to be fixed now in 6.2.1
