### ISSUE TITLE
Visibility classes on Fountation 6 not working

### ISSUE THREAD

**Issue by antopossegithub** [zurb/foundation-sites#7828]
Hi guys...I'm an Italian designer and I was trying Foundation 6 for site!
I've a problem with the visibility classes, show or show-for-medium and hide or hide-for-medium doesn't work!! 
Writing these classes, nothing happens!
Practically in CSS it adds no rule that generates the show or hide parameter.

thanks for the help. 
Hello!

**Comment by Ne-Ne** [comment]
Are the classes located in the .css file?

It sounds like the visibility mixin has not been included.

**Comment by antopossegithub** [comment]
I work with the css version, I think I don't have mixin

**Comment by Ne-Ne** [comment]
Can you post your .css and or sass files?

I'm sure it is a simple fix.

**Comment by gakimball** [comment]
Can you post a code sample also?

**Comment by antopossegithub** [comment]
I'm sorry guys :( I was working with the essential version and not with the complete version.
I'm really sorry....but thank you everybody!!!

I have another problem and I asked for help if you like to take a look. thank you!
https://github.com/zurb/foundation-sites/issues/7842
