### ISSUE TITLE
Block-grid with UL and OL in FS6

### ISSUE THREAD

**Issue by dbig** [zurb/foundation-sites#7829]
Hello,
I can't imagine this was an oversight within the development team, but all examples I've seen of the new block-grid in FS6 seem to ignore the ordering nature of OL and UL.

When there's no structure to the block items, like DIV, all seems fine (I guess), but with OL and UL, the row renders first, then the column.

For example…
```html
<ol class="small-up-3">
    <li class="column">item1</li>
    <li class="column">item2</li>
    <li class="column">item3</li>
    <li class="column">item4</li>
    <li class="column">item5</li>
    <li class="column">item6</li>
</ol>
```

renders in FS6 as…

    1. item1    2. item2    3. item3
    4. item4    5. item5    6. item6

But with the block-grid in F5, they rendered (properly) by column, then row, as…

    1. item1    3. item3    5. item5
    2. item2    4. item4    6. item6

What's needed to properly render OL and UL in FS6?

Thanks,
Doug

**Comment by Ne-Ne** [comment]
Hey @dbig can you create a codepen.io?

**Comment by dbig** [comment]
Sure thing @Ne-Ne, thanks…

http://codepen.io/dbigca/pen/wMeoQd

Doug

**Comment by Ne-Ne** [comment]
Sorry it took me longer to get back.

Hopefully this helps! I put it down to the default behaviour of the `<ol>` & `<ul>` & `<li>` elements. What do you think @gakimball?

From what I can see it is due to the list position is default outside. To fix this issue I did the following (see below) - http://codepen.io/Ne-Ne/pen/RrZpjy

```html
<ol class="list__ol row small-up-3 clearfix">
  <li class="list__li column">item1</li>
  <li class="list__li column">item2</li>
  <li class="list__li column">item3</li>
  <li class="list__li column">item4</li>
  <li class="list__li column">item5</li>
  <li class="list__li column">item6</li>
</ol>
```

```css
.list__li{
  list-style-position: inside;
}
```

I also added a `.clearfix` to sort out clearing issues (as I do on most `<ol>` or `<ul>` elements). I also added `.row` as this has to be added for the block grid as per the docs (http://foundation.zurb.com/sites/docs/grid.html#block-grids)

Let me know what you think :+1:

**Comment by dbig** [comment]
Thanks @Ne-Ne,
I made your updates to my pen, and looked at your pen, but - in both pens - the code is still rendering the row first.

It goes across then down...

1. item1    2. item2    3. item3
4. item4    5. item5    6. item6

but I want it to go down then across...

1. item1    3. item3    5. item5
2. item2    4. item4    6. item6

There must be a way for the <OL> / <UL> structure/order to be retained.

Thoughts anyone?

Thanks,
Doug

**Comment by zurbrandon** [comment]
Hm block grid never rendered by columns first then row, it's always used floats, which wouldn't have been able to do this. 

I'd say nothing is broken with Foundation here, but it's possibly not the component you're looking for. Flex box could do this, but floats wouldn't make this super easy.

**Comment by gakimball** [comment]
@dbig The block grid is now built around generic `<div>`s over list elements, so if you use `<ul>` or `<ol>` you'll need to add `list-style-type: none;` if you don't want those styles.

Like @zurbrandon said, it's never been possible to order block grid items vertically—CSS doesn't work that way. You can do it with flexbox, but the container needs a specific height so the items know where to wrap. There's not a construct in CSS that can auto-balance a gallery of items.
