### ISSUE TITLE
Support configurable background printing

### ISSUE THREAD

**Issue by josh-h** [zurb/foundation-sites#7830]
I'd like to support printing of reports with background colors, but the typography group forces transparent backgrounds for print. I propose adding a variable that conditionally resets background colors, e.g. something like this:

    $print-transparent-backgrounds: true;

and _print.scss would be revised to include something like this:

    @if $print-transparent-backgrounds {
      @media print {
        * { backgrounds: transparent !important; }
      }
    }

Would you be open to a PR with such a change?

**Comment by zurbrandon** [comment]
Seems reasonable. If you could do a PR it would be appreciated.

**Comment by gakimball** [comment]
Added in the `6.2` branch: dba26f62a185b99bc557caea34d5912358cfadaa
