### ISSUE TITLE
[Callout] Demos does not work..

### ISSUE THREAD

**Issue by Ne-Ne** [zurb/foundation-sites#7837]
**How can we reproduce this bug?**

Visit page, click first demo

**What did you expect to happen?**

Callout event

**What happened instead?**

Hash appears in url. Chrome dev tools shows no errors

Live on docs site.

**Comment by andycochran** [comment]
I think the links with the Zelda quote are only there to show how text/links are formatted within callouts. There's no event associated with them.

**Comment by gakimball** [comment]
Yep, those links are static. Originally links inside callouts were colored to match the background, but we removed that feature because the visual contrast was way too low. The links remain in the examples just to show what they look like.
