### ISSUE TITLE
Class .button does not work for links in Firefox

### ISSUE THREAD

**Issue by alexrois** [zurb/foundation-sites#7843]
When using Foundation 6 (version 6.0.5) for default buttons it does not show any text before you point cursor to the button (in case of using `<a>` tag, tested in the newest version of Firefox, not tested in other browsers). Next image shows how it looks without covering of button:
![f6s1](https://cloud.githubusercontent.com/assets/16092409/12245641/7901b884-b8b2-11e5-8820-29eaab95e4c0.jpg)

Next image with covered button:
![f6s2](https://cloud.githubusercontent.com/assets/16092409/12245656/985dc790-b8b2-11e5-9def-b36d9a7b3906.jpg)

So text appears only when user moves mouse cursor to cover this button.

It doesn't work only for `<a href="#" class="button">Log In</a>`. If you change `<a>` tag to `<button>` it works correct. Or if you add to `button` class one of `success` or `alert` class it also works correct.

It also works [in this example](http://foundation.zurb.com/sites/docs/button.html) in Foundation docs site.

Example of nonworking code you can see [in this repo](https://github.com/alexrois/appspoint) in file *index.html* (line 25).

**Comment by andycochran** [comment]
Not just Firefox. Chrome too. Probably all browsers.
It's 'cause the specificity of `.top-bar a` is higher than `.button`. 
Ugh, I hope we can avoid an `!important`. 

We could change `.button { … }` to `.button, a.button { … }`.

**Comment by PurpleBracket** [comment]
Hey, in the repo you included the issue is that the link tag has the same color and background color properties. You should change one. The reason it shows up on hover because the color is different on hover. 

<img width="633" alt="screen shot 2016-01-12 at 4 03 16 am" src="https://cloud.githubusercontent.com/assets/16170878/12259149/b1dbb1bc-b8e1-11e5-857f-6a275a44f1ac.png">

**Comment by gakimball** [comment]
I could see dropping that property (`.top-bar a`) entirely and just having top bar links inherit the default link color. We do the same thing for menu, tabs, accordions, and so on—if the link is going to be blue anyway, we just borrow that style from the base `a` rules.

**Comment by andycochran** [comment]
:+1: to dropping `.top-bar a`.
