### ISSUE TITLE
Expanded button-group does not work for <button> in non-IE browsers

### ISSUE THREAD

**Issue by arangas** [zurb/foundation-sites#7844]
I'm using an expanded button-group. It works great using a button of form `<a class="button">` but not for `<button type="button" class="button">`.

I made a [CodePen here](http://codepen.io/alexangas/pen/JGJMqv) to demonstrate.

IE 11 works as expected. Firefox doesn't do the expanding. Chrome renders the buttons on top of each other.

**Comment by andycochran** [comment]
Hmm. Looks like `display:table-cell` will not work on the `<button>` element because it has a "[special box type](https://bugzilla.mozilla.org/show_bug.cgi?id=960512)." 

The table cell technique for `.button-group` isn't gonna work for `<button>` elements. :disappointed:

**Comment by arangas** [comment]
Great find! I could not work out what was going on using the dev tools.

Do you think a message could be added to the docs for Button Group so users are aware and don't waste their time?

**Comment by gakimball** [comment]
@arangas We can add a temporary note to the docs, but we really want people to use `<button>` over `<a>` when it makes sense, so it may be worth going back to the old float model.

**Comment by gakimball** [comment]
Fixed via #7933
