### ISSUE TITLE
How to expose Foundation to Wappalyzer?

### ISSUE THREAD

**Issue by PurpleBracket** [zurb/foundation-sites#7845]
So I use [Wappalyzer](https://wappalyzer.com) chrome plugin religiously to better understand the components of an existing web project. This helps in research as well as any migration effort if you're putting together a pitch for the client before you can discuss details about their current stack. When I visit http://foundation.zurb.com/learn/brands.html I can see Zurb Foundation as a component on it. But this doesn't happen for any of the websites I built on Foundation. 

I know this might not seem like a big thing, but I would like to see if a solution could be available. Here are the screenshots. 
<img width="904" alt="screen shot 2016-01-12 at 3 56 51 am" src="https://cloud.githubusercontent.com/assets/16170878/12259045/ee028860-b8e0-11e5-9c58-2fb202bc5f5b.png">
![screen shot 2016-01-12 at 3 57 07 am](https://cloud.githubusercontent.com/assets/16170878/12259054/fc349b9e-b8e0-11e5-9efc-f31dc80340b2.jpg)

Thanks in advance!

**Comment by PurpleBracket** [comment]
Doesn't show up on the pixar or mini cooper websites featured in the brands on zurb either.

**Comment by gakimball** [comment]
We expose the Foundation version through `Foundation.version`, and we've been doing that for the past few major releases.

This is an issue on Wappalyzer's end, so I'd recommend contacting them and asking them about it.
