### ISSUE TITLE
Motion UI - Not loading

### ISSUE THREAD

**Issue by Ne-Ne** [zurb/foundation-sites#7849]
Trying to get Motion UI to work in my sass project.

Created a test codepen - http://codepen.io/Ne-Ne/pen/wMeEPZ?editors=110. Did not work..

I have included the whole CDN JS file, and triggered Foundation:

```js
$(document).foundation();
```

All the classes are present and I get no mixin errors, so I know sass is being found and complies well.

The error I get:

![screen shot 2016-01-12 at 13 40 25](https://cloud.githubusercontent.com/assets/2177851/12264954/1950df66-b932-11e5-9c93-96cc99a67783.png)

**Comment by gakimball** [comment]
Try `Foundation.Motion.animateIn()` instead and see if that works.

**Comment by Ne-Ne** [comment]
Hey @gakimball that seems to have worked. Can I ask what I did wrong? Or is there something missing in the docs?

**Comment by zurbchris** [comment]
The JS from Motion-UI was slightly retooled for Foundation 6 purposes, so it has it's own small util library baked in. So, you didn't do anything wrong, just called the wrong function.

**Comment by Ne-Ne** [comment]
Have any foundation doc's been updated @zurbchris?
