### ISSUE TITLE
Dropdown Component, Pane initial top value.

### ISSUE THREAD

**Issue by atilkan** [zurb/foundation-sites#7853]
Dropdown component initial value calculated wrong. 
First time after page load. Clicking a pane to open looks like this.
![screen shot 2016-01-12 at 17 22 14](https://cloud.githubusercontent.com/assets/1254613/12267535/447ce652-b951-11e5-91d3-36242b218ccd.png)

Second time it looks correct. Top value changing. 
![screen shot 2016-01-12 at 17 22 30](https://cloud.githubusercontent.com/assets/1254613/12267550/516a4fa8-b951-11e5-8a3e-c650a18803e8.png)

But if there is an element below it. It works as expected.
![screen shot 2016-01-12 at 17 27 03](https://cloud.githubusercontent.com/assets/1254613/12267644/d287c674-b951-11e5-894f-20f0e6b47eb0.png)

Any clue?

**Comment by atilkan** [comment]
After adding this line it worked. 
```var elem = new Foundation.Dropdown("options");```
Without this line why it half-works i don't understand.

**Comment by atilkan** [comment]
It works but throws error. What is this?
![screen shot 2016-01-12 at 17 54 18](https://cloud.githubusercontent.com/assets/1254613/12268451/907ccb7c-b955-11e5-8de2-82c967fbf0fa.png)

**Comment by zurbchris** [comment]
If you're using the complete file, it includes all js and sass/css files concatenated. Those lines in the docs are for folks using a build system or linking independent files. 

Are you initializing Foundation with `$(document).foundation()` or are you programmatically creating all your components?

**Comment by atilkan** [comment]
I use raw css files from custom build. All files comes probably. 
And i init as $(document).foundation() 
Most component works witout writing any ekstra code. But here there is something wrong. Provably i don't have add that code. But then it does not work in first try as expected.

**Comment by zurbchris** [comment]
can you create and link to a codepen or fiddle? I would like to see if there's something I can tweak to make it work for you.

**Comment by atilkan** [comment]
It behaves as expected on windows. I experienced this problem on mac. My mac is not near me right now, i can't test.
Here is my test file. There is no extra code rather than foundation init. 
http://fantasycore.com/clients/hosting/app/a-class-ip-hosting-usa.html

**Comment by zurbchris** [comment]
I have not one clue as to why you're getting the error. Your markup looks correct, I inspected and compared your source html files before Foundation added attributes. So, the error is completely baffling. As for the positioning bug, I did not get that on my machine.

**Comment by atilkan** [comment]
Positioning bug doesn't happen anymore. I did not change a thing on that part. 
May be cause of my gulp built system i suppose. Thanks for your time.

**Comment by calderJamNet** [comment]
@atilkan @zurbchris I just noticed that this same this is happening to me right now, and it didn't used to be.

the `top` value is being set to `-148 pixels`. If I uncheck this style in chrome dropdown-pane displays correctly and top is set to `top: 39px; `.

Any idea how I can I can fix this?  Overriding the style with `top:39px !important` works but I would rather find another way that doesn't seem so likely to cause problems down the line.

**Comment by atilkan** [comment]
@calderJamNet I don't know the reason. I suspect Zurb changes the code, and look at it again without understanding, then change it again.
