### ISSUE TITLE
Handle fixed tooltips

### ISSUE THREAD

**Issue by HugoHeneault** [zurb/foundation-sites#7864]
Hello, 

I'm trying to add a tooltip on a fixed item, and it works if I add a `position: fixed` style to the tooltip.
But the position of the tooltip is wrong if I scroll before opening the tooltip.

Any ideas? 
Thanks!

**Comment by zurbchris** [comment]
Oof, that wasn't a use case that was planned. One thing you might be able to do is trigger an open/close cycle on page load, which would trigger the positioning functions. Other than that, it'll be pretty tricky.

**Comment by HugoHeneault** [comment]
An open/close cycle? How do I do that? 

```
tooltip.show()
tooltip.hide()
tooltip.show()
```

**Comment by HugoHeneault** [comment]
That seems to work. It's quite a tricky workaround, but it works!
Thanks.
