### ISSUE TITLE
iOS scrolls full page when Reveal Modal is open

### ISSUE THREAD

**Issue by designerdean** [zurb/foundation-sites#7866]
The attached screenshot should be self explanatory.

![screenshot](https://cloud.githubusercontent.com/assets/729893/12300926/d415d308-b9da-11e5-9655-a43ab829c463.jpg)

**Comment by Ne-Ne** [comment]
Getting the same issue as well (https://github.com/zurb/foundation-sites/issues/7548).

@gerardkcohen provided a great example which works.

**Comment by gakimball** [comment]
Closing in favor of #7548. We've also got PR #7847 open which we'll be reviewing soon.
