### ISSUE TITLE
 CLI installed F6.1.1 watch doesn't update partial or layout files after initial build

### ISSUE THREAD

**Issue by t-fulton** [zurb/foundation-sites#7867]
Observed behavior: 
With a fresh install of 6.1.1 done through the CLI and running 'foundation watch', changes I make to Panini elements from partials folder or anything from the layouts/default.html don't make it to the dist folder after initial watch is set.

I have a file in src/partials/nav.html and refer to it with {{> nav}} in src/pages/index.html.

The only way to get the updated Panini elements into the dist folder is to CMD-C and restart with 'foundation watch'. This builds out everything as expected. The crazy part is that I can make just ONE change to a panini element (e.g. nav.html) and have it build out to dist as expected (and automatically reload in the browser with the change), but only once.

The same type of behavior occurs when I try to modify simple html in layouts/default.html.

Expected behavior: 
To be able to make a change to panini elements and have it build to the dist folder without having to stop the process.

Thanks!

Mac 10.8.5 | Chrome Version 47.0.2526.106 (64-bit) | node v0.12.0 | npm 2.5.1

**Comment by rafibomb** [comment]
We have a solution for this slated to go out with 6.2. It should and did watch for changes in those partials.

**Comment by t-fulton** [comment]
Awesome, thanks for the heads up.

**Comment by gakimball** [comment]
I made some adjustments to the Gulpfile, and after thorough testing, every lingering issue with auto-refresh appears to have been resolved. See [this comment](https://github.com/zurb/panini/issues/10#issuecomment-172692241) for an explanation of the fixes, and a link to the relevant commit.

You can update your template through a simple cut-and-paste.
