### ISSUE TITLE
F6 - Accordion failure inside a new div

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#7869]
Found again a bug when you put the content of the "Accordion"-component inside a extra div.

http://codepen.io/anon/pen/obeGeQ

**Comment by zurbchris** [comment]
Looking at your pen, this isn't a bug, it's intended behavior in the case of nested accordions or other plugins inside an accordion content pane. You're blocking the the parent `<li>` from finding it's immediate child `[data-tab-content]`.

**Comment by Silvester20** [comment]
In my opinion it is a bug. This way did worked for F5 which searched for the closest data-tab-content, instead of the immediate child.

Anyway, is there a way to archieve the exact same layout as in the pen, so a "button" next each accordion tab and at the same time a working accordion menu too in F6?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by andycochran** [comment]
The markup is bad too. It's missing `data-accordion-item`, `.row` elements, closing `</p>` tags, etc. This isn't a bug. There's probably better way to hack the layout you're shooting for. Maybe something like this? http://codepen.io/andycochran/pen/rxgxqp?editors=1100

**Comment by Silvester20** [comment]
I created a very quick pen but anyway, your solution is fine so gonna use this I guess. Thanks!
