### ISSUE TITLE
Browser-sync not reloading browser after CLI update

### ISSUE THREAD

**Issue by adolfobarreto75** [zurb/foundation-sites#7870]
I updated Foundation CLI yesterday and now file changes don't update in browser. The browser looks like it's refreshing but it the changes don't come through. I have to refresh the browser manually to see the changes. Thanks-Adolfo

**Comment by gakimball** [comment]
Strange, the CLI just runs the template, it doesn't affect how the template works. When did you create the project? (Asking so I can figure out if you're missing any recent bug fixes to the template.)

**Comment by adolfo75snip** [comment]
Updated on the twelve. I downloaded everything over on the 13th and started a new site. I'm not sure when the new fixes where issued. Could there be something wrong with my node files?

**Comment by adolfobarreto75** [comment]
Hi, Here is the response from the folks at Gulp.js: https://github.com/gulpjs/gulp/issues/1489 ... They are saying that is not a gulp.js.

**Comment by adolfobarreto75** [comment]
Hi, I reached out to the folks at gulp.js: https://github.com/gulpjs/gulp/issues/1489 and they say it is not a gulp.js issue. Any Ideas?

**Comment by gakimball** [comment]
Oh actually, what types of files are you changing and then not getting a refresh? HTML pages, partials, layouts? Sass? JavaScript?

**Comment by adolfobarreto75** [comment]
Hi,
HTML pages and Sass.

**Comment by gakimball** [comment]
I made some adjustments to the Gulpfile, and after thorough testing, every lingering issue with auto-refresh appears to have been resolved. See [this comment](https://github.com/zurb/panini/issues/10#issuecomment-172692241) for an explanation of the fixes, and a link to the relevant commit.

You can update your template through a simple cut-and-paste.

**Comment by adolfobarreto75** [comment]
Yes! Thank you so much. That did it! Thanks - Adolfo
