### ISSUE TITLE
[Off-canvas] long list menu is cutted

### ISSUE THREAD

**Issue by guinody** [zurb/foundation-sites#7872]
**How can we reproduce this bug?**

1. make a long list menu itens ( like 40 li - item - /li )

**What did you expect to happen?**

i think that menu height iss fixed because itens is there but was cutted.

**Comment by rafibomb** [comment]
An example would really help here. Can you add it to this codepen and post it here? http://codepen.io/rafibomb/pen/gPxVBd

**Comment by rafibomb** [comment]
I made demo - looks like you can scroll to get the menu items that are off screen. http://codepen.io/rafibomb/pen/adxRoP

If you see there is still an issue, please open a new issue with an example so we can dig into it. Thanks!
