### ISSUE TITLE
[Sticky] Sticky does not work after minification

### ISSUE THREAD

**Issue by alanontheweb** [zurb/foundation-sites#7874]
1. *Runs sticky default code from docs with gulp default* - it works
2. *Runs sticky default code from docs with gulp default --production - doesn't work

The "is-stuck is-at-top" classes don't get appended to the "sticky" markup, so it doesn't seem like an UNCSS ignore issue that the regex "is-" didn't catch.

The rest of the page works identical.

**Comment by rafibomb** [comment]
@zurbchris Did we have the is-state ignore in the build?

**Comment by zurbchris** [comment]
yeah, but that doesn't seem to be the issue. Our JS minification is causing some issue and the boolean that allows a sticky thing to stick is not getting set to true even when it should. As it's minified and mangled code, it's pretty hard to sort out why exactly, without spending quite a long time sorting through it. 

I would recommend, until we can figure out a fix for this, going into the gulpfile.js and commenting out line 144: `.pipe(uglify)`

**Comment by gakimball** [comment]
We're going to audit our codebase to make sure every state class is properly tagged with `.is-`, so UnCSS doesn't remove them. We're tracking that issue here: #7909
