### ISSUE TITLE
Dropdown unusable with foundation for apps

### ISSUE THREAD

**Issue by fhackenberger** [zurb/foundation-sites#7876]
A button with a dropdown attached is not positioned correctly if it is placed within a flex layout and content container which is scrolled down.

See http://codepen.io/anon/pen/EPvGYa for the broken version. You have to resize the part where the list with the car icons is displayed so that it scrolls, scroll down a little and click one of the "Actions" dropdowns. The dropdown popup is placed too high up on the screen.

If the container is a regular div, this works correctly. See http://codepen.io/anon/pen/YwxdKZ

Seems to be fixed in foundation 6 though: http://codepen.io/anon/pen/adyPOv

**Comment by rafibomb** [comment]
Not sure what the bug is. Are you using a Foundation for Sites 5 dropdown in Foundation for Apps? Not sure that is a use case in the framework right now.

**Comment by zurbchris** [comment]
What @rafibomb said about use case. If you want dropdown-like functionality in Foundation for Apps, use the Popup component.

**Comment by fhackenberger** [comment]
Ok, so foundation for apps `replaces` the basic foundation, ok I got it. That was very unclear, before the rename to `Foundation for Sites`, which was when I started working with `... for Apps`.
