### ISSUE TITLE
[Global Styles] Bring back $info-color variable?

### ISSUE THREAD

**Issue by Deckluhm** [zurb/foundation-sites#7877]
Hey,

In Foundation 5, there used to be a `$info-color` variable, used by multiple components like `buttons` and `labels`.

It has been removed in Foundation 6. Is it an intended change?

It was pretty convenient to be able to have an `info` color (often blue) different than the `primary` one (which can be pretty much any color).

**Comment by gakimball** [comment]
We don't plan on re-adding `$info-color`, *but*, in Foundation 6.2 we're introducing the concept of flexible color palettes. [This comment](https://github.com/zurb/foundation-sites/issues/7219#issuecomment-166990006) gives an overview of how it will work.

**Comment by Deckluhm** [comment]
That's awesome news!

I checked Foundation sources to understand the way you are using `$*-color` variables and I was hoping for something like this.

Can't wait for 6.2!
