### ISSUE TITLE
bower-foundation still on 5.x version

### ISSUE THREAD

**Issue by tomByrer** [zurb/foundation-sites#7883]
I was trying to get Foundation v6.1.x via ` bower install foundation --save` but I get `bower install       foundation#5.5.3`.  Seems your [TravisCL isn't building since v6](https://github.com/zurb/bower-foundation/blob/master/package.json#L3).  Is this intentional, expecting users to use Node tool instead of Bower?

**Comment by gakimball** [comment]
A new package was created called `foundation-sites`, to go with the new branding. This worked out pretty well because we also needed to shift the Git endpoint for the Bower package.

**Comment by tomByrer** [comment]
Awesome, thanks @gakimball.  Yes I agree a new package name is more reasonable.

But can you please reopen & assign someone to update the [`README.md`](https://github.com/zurb/bower-foundation/blob/master/README.md) there to point at [this repo](https://github.com/zurb/foundation-sites#setup)?  Googling "bower foundation" still bring us to that old repo.  I didn't know there was a v6 until visiting the main Foundation website, & finding the bower instructions is tricky (4th click-though in the middle of a page, & very easy to miss).

Would be even better if `bower install foundation` would notify users that v6 has changed package names, but a README warning is good enough.

**Comment by gakimball** [comment]
@tomByrer Bower supports post-install hooks, but I don't know if putting in `echo The Foundation package has been renamed to...` will work cross-platform.

Either way, I added a note to the v5 readme about the package name change: 19d16c99b9538cf80fa369ca056b6323767ec06d

**Comment by tomByrer** [comment]
Cool, thanks for the docs update.  Is it possible to update also [zurb/bower-foundation](https://github.com/zurb/bower-foundation) since that is the top Google hit for "foundation bower"?

**Comment by gakimball** [comment]
@tomByrer Travis should be automatically updating bower-foundation, but it doesn't appear to be. I'll look into it.
