### ISSUE TITLE
[Dropdown Menus] Destroy does not work

### ISSUE THREAD

**Issue by bnbc** [zurb/foundation-sites#7886]
When i do :

```javascript
$('#navigation-menu').addClass('dropdown menu');
var elem = new Foundation.DropdownMenu($('#navigation-menu'));
$('#navigation-menu').foundation('destroy');
``` 

The dropdown menu is created correctly but the destroy function give me an error : 
```javascript
ReferenceError: We're sorry, 'destroy' is not an available method for this element.
throw new ReferenceError("We're sorry, '" + method + "' is not an available meth...
``` 
So why, i do a mistake ?

Thks !

**Comment by zurbchris** [comment]
You're either on a an older version of F6, or something else is broken. c5d08ca was the commit that added the ability to call `.foundation('method')` on programmatically created plugins, which was part of 6.1

**Comment by zurbchris** [comment]
If you're on an older version, you can call the method directly:
```js
elem.destroy();
```

**Comment by bnbc** [comment]
Thks for speed reply :) I up to 6.1 and it works !
