### ISSUE TITLE
6.1.1 _accordion.scss  $accordion-item-padding should be replaced with $accordion-content-padding

### ISSUE THREAD

**Issue by partnuz** [zurb/foundation-sites#7889]
On scss/components/_accordion.scss line 90

@mixin accordion-content {
  padding: $accordion-item-padding;
  display: none;
  border-bottom: $accordion-content-border;
}

$accordion-item-padding should be replaced with $accordion-content-padding

**Comment by gakimball** [comment]
Fixed in the latest version of Foundation: 836776f6a900383fec2dfdd9494b922c947a87a4
