### ISSUE TITLE
[Dropdown menu] First level submenu (with border) aligned too high

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites#7891]
I already added a [PR for this](https://github.com/zurb/foundation-sites/pull/7851), but thought I should explain the issue. A photo makes it easier to explain:

![dropdown-alignment](https://cloud.githubusercontent.com/assets/73229/12356384/57458e06-bb9a-11e5-9093-b28e49172ddf.jpg)

Basically if a border is set, the top level dropdown sits the width of the border too high up.

**Comment by gakimball** [comment]
Merged #7851, thanks! :)
