### ISSUE TITLE
Using Menu for Inline List in F6 

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#7892]
The docs say the following: 

> Add the `.simple` class to a Menu to remove the padding and color change. This style imitates the inline list from Foundation 5.

This is fine if your inline list has links, however, there are cases where in F5 I would use inline list that contained just text. If you use just text it loses some styles in my experience. 

It would be great if this would work with just text.

**Comment by andycochran** [comment]
Actually, it looks like the `.simple` documentation is all wrong. 
Or it's broken.  :confused: 

* The `.simple` class doesn't remove padding; it adds padding.
* What color change? 
* The basic `.menu` is already an inline list. 

This feature needs some clarification.

**Comment by Lynda333** [comment]
@andycochran - Thanks for pointing that out. I noticed that as well but was busy and forgot to add it.

When you look at the CSS for `.simple`, this is all it is:   

    .menu.simple a {
        padding: 0;
        margin-right: 1rem;
     }

However, when applied in use, the padding is overrode by this styling: 

    .menu > li:not(.menu-text) > a {
        padding: 0.7rem 1rem;
    }

It appears to be a bug as padding should be removed, then a margin added. 

But as you point out, the docs are incorrect, there is no color change. 

For ease of use, and for solving the reason I posted, why not remove the .simple class from the menu (or leave it for those who are using it) and just add back in inline list? I realize F6 had major code reduction but the code for inline list isn't that much. 

In fact, for my project I just added it back in and dropped trying to use the "simple menu".

**Comment by gakimball** [comment]
If we can cut back the specificity of `.menu > li:not(.menu-text) > a`, that would be ideal. It's too specific as is.

**Comment by gakimball** [comment]
Fixed by moving the margin from the `<a>` to the `<li>` (so it doesn't matter if the item is plain text or a link), and cut back the specificity of `.menu > li:not(.menu-text) > a`, which was causing problems with dropdowns also. 0ce09db0424dae44868ae5e0b5fc2218bcfd51e2
