### ISSUE TITLE
Why different jquery versions?

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#7893]
in package.json
```
"jquery": "^2.1.0",
"what-input": "^1.1.2"
```
results in 2.2.0

in bower.json
```
"jquery": "~2.1.0",
"what-input": "~1.1.2"
```
results in 2.1.4

**Comment by gakimball** [comment]
The `^` in `package.json` was allowing it to bump the middle version number. Switching to `~` locks it to version 2.1.x.
