### ISSUE TITLE
[Off Canvas] isSticky

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#7895]
I'm working with the Off Canvas menu and noticed this phrase in the docs: 

> isRevealed - Allow the offcanvas to remain open for certain breakpoints. Can be used with `isSticky`.

Well, I didn't see an option `isStick` so I thought I would check the JS and I found this: 

	/**
	* Allow the offcanvas to be sticky while open. Does nothing if Sass option `$maincontent-prevent-scroll === true`.
	* Performance in Safari OSX/iOS is not great.
	*/
	// isSticky: false,

I assume it's commented out because of the performance issues referenced. 

Is there a timeline to add this into Off Canvas? I'd like to use it.

**Comment by zurbchris** [comment]
Until Safari can work smoothly with scroll events, I don't know that we'll get this in there. It worked great on Firefox and Chrome, hell, even IE9 was ok, but Safari was totally broken. By default, if you use a reveal-for class, it becomes position fixed *when* it's revealed, but for some reason making that work any other time is difficult.

**Comment by Lynda333** [comment]
@zurbchris - Thank you for the information.
