### ISSUE TITLE
Dropdown Menu not in right location when float-right

### ISSUE THREAD

**Issue by Woolworths** [zurb/foundation-sites#7902]
```
<div class="float-right">
  <ul class="dropdown menu" data-dropdown-menu>
    <li>
      <a href="#">Click</a>
        <ul class="menu submenu" data-submenu>
          <li><a href="#">First link in dropdown</a></li>
          <li><a href="#">Active link in dropdown</a></li>
       </ul>
    </li>
  </ul>
</div>
```

Will misplace the submenu and make it 20 - 40px from the edge of the screen. Makes it impossible to sustain when data-closing-time="0" as the submenu is not below the text/button.

**Comment by Woolworths** [comment]
This is my bad. I should have put "align-right" on the ul (after "dropdown menu").

**Comment by zurbchris** [comment]
I'll close this. Keep on keepin' on!
