### ISSUE TITLE
Build task (uncss) strips out Motion UI CSS

### ISSUE THREAD

**Issue by brightonmike** [zurb/foundation-sites#7906]
Hello.

How can I stop uncss stripping out all the Motion UI CSS?

The default build task is doing this, and thus the orbit slider doesn't work when you build, because all the Motion UI CSS is missing.

The only fix I can think of so far is to remove the uncss task. But that doesn't sit well with me, I'll just end up with bloated CSS files again.

I thought a regex might work - but not all of the classes contain "mui".

**Comment by brightonmike** [comment]
new RegExp('mui*') - works mostly - but I'm pretty sure we're still losing some important rules.

**Comment by gakimball** [comment]
You can also add `^\.(fade|slide|hinge|scale|spin)`. That catches the transition classes.

If it becomes too much of a hassle, I'd recommend removing UnCSS from your build process, which you can do by commenting out `.pipe(uncss)` from your template's `gulpfile.js`.
