### ISSUE TITLE
please, add some event that will fired after tabs plugin initialized

### ISSUE THREAD

**Issue by oleg-jomedia** [zurb/foundation-sites#7908]
this will be useful for cases when we need to execute some code on document ready, but have to wait for plugin code to be executed first, 'cause it changes DOM

**Comment by zurbchris** [comment]
it's there, and for all plugins: `init.zf.pluginname`, so tabs would be `init.zf.tabs`.

**Comment by oleg-jomedia** [comment]
thanks, for answer, and sorry for disturbing you
