### ISSUE TITLE
Audit state classes

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7909]
We need to audit our dynamically-added CSS classes and ensure they're all prefixed with `.is-`. We're getting a lot of issues reported around UnCSS stripping dynamic classes because they aren't properly marked.

Let's see if we can do it by 6.2, which we're shipping at the end of February.

**Dropdown menu**
- `.align-right`
- `.first-sub`
- `.opens-inner`
- `.opens-left`

**Orbit:**
- `.no-motionui` ?

**Comment by gakimball** [comment]
@zurbchris This is less than I thought, but I think it's all of them?

The UnCSS config will also need to be updated to ignore `.js-` classes, but that's easy.

**Comment by gakimball** [comment]
We also need to resolve the issues with Responsive Menu, which dynamically applies the classes `.dropdown`, `.drilldown`, and `.accordion-menu`. They aren't normally state classes, so they don't have `.is-`, so they don't get whitelisted by UnCSS.

Now, dropdown and drilldown already add state classes to the parent container: `.is-dropdown-menu` and `.is-dropdown-submenu`. We could do the same for accordion menu with `.is-accordion-menu`. Then, we shift all of the CSS from `.dropdown.menu` to `.is-dropdown-menu`, and from `.drilldown.menu` to `.is-drilldown-menu`.

I don't believe it would be a breaking change, because none of the menu plugins have mixin libraries—right now you have to use all of the CSS as-is.

Going to investigate this.

**Comment by phifa** [comment]
i just did a `foundation build` and my sticky top bar is not sticky anymore. when i go back to `foundation watch` everything works.

**Comment by matticusfinch** [comment]
The issue currently persists with the Reveal overlay as well

**Comment by rafibomb** [comment]
All the `.is-*` should be in the ignore config. Can you see anything missing there?

**Comment by JeremyEnglert** [comment]
No reply. Closing this issue out.

**Comment by IamManchanda** [comment]
@gakimball @phifa @matticusfinch Is this issue still remains? For now we are closing this but we will be happy to reopen if this issue is still there 
Let us know!
