### ISSUE TITLE
[Top Bar] overlay opacity with background color

### ISSUE THREAD

**Issue by bordat** [zurb/foundation-sites#7921]
When I type in the file settings.sass:
$topbar-background: rgba(12, 12, 12, 0.85);

the result is in the css
  .top-bar ul {
    background-color: rgba(12, 12, 12, 0.85); }

This code create an overlay with opacity,  with .topbar and ul .

demo:
http://codepen.io/bordat/pen/NxwyKo

**Comment by zurbrandon** [comment]
For this use case it may make sense just to set the ul to transparent, we add backgrounds to these so dropdowns inherit them.
