### ISSUE TITLE
[Top Bar] .top-bar a color overrides .button color

### ISSUE THREAD

**Issue by einfallstoll** [zurb/foundation-sites#7925]
The "bug fix" introduced in 6.0.6 overrides the color of the specified class.

> Top Bar: switched link color from white to $primary-color.

Since I explicitly declared the `.button` class on an anchor in the `.top-bar` I expected it to look like a button. Actually the globally declared rule overrides the class color.

I request to revert this "bug fix" since it declares a global behaviour that should get overridden from every more explicit declared rule.

**Comment by gakimball** [comment]
Fixed via 8cd80adff63ed50a1e735c9c5b981b084c36e977
