### ISSUE TITLE
Dropdown issue with more then 42 items

### ISSUE THREAD

**Issue by keinchy** [zurb/foundation-sites#7926]
I was creating a form with Birthday dropdowns, and while adding the "Year" dropdown, after adding the 42nd item, the dropdown breaks, the width of the dropdown becomes the entire width of the window.

**Comment by zurbchris** [comment]
Can I get a codepen or fiddle to look at?

**Comment by keinchy** [comment]
I will create a codepen for it, and message when it's ready to view,

**Comment by zurbchris** [comment]
thanks

**Comment by tjhiggins** [comment]
Assuming this is a similar issue to this codepen.
http://codepen.io/TJHiggins/pen/vLgwEL

https://github.com/zurb/foundation-sites/pull/7911

**Comment by keinchy** [comment]
here is the link:http://codepen.io/Keinchy/pen/adVQVa

I also notice that it has something to do with the height of the Dropdown Pane vs the height of the browser. Take a look let me know. 

Thanks in advance

**Comment by zurbchris** [comment]
Based on your pen, you're trying to use a dropdown as a selector of sorts. This is definitely not a use case it was designed for, and dropdowns were never designed to contain so much content. I would recommend using `<select>` elements or [jQuery-Selectric](https://github.com/lcdsantos/jQuery-Selectric) to customize selection inputs.

**Comment by keinchy** [comment]
understood, i may have to revisit all of the dropdowns on my current project, since i can't rely on this dropdown. Thanks for looking into it.
