### ISSUE TITLE
[Dropdown menu] alignment and arrow have an issue in RTL mode

### ISSUE THREAD

**Issue by abdullahsalem** [zurb/foundation-sites#7930]
`Dropdown menu`'s alignment and arrow have an issue in `RTL` mode, you can see that clearly in the following snapshot

![dropdown-menu-alignment-rtl](https://cloud.githubusercontent.com/assets/177020/12431471/a4abe694-bf06-11e5-909a-16f044fa177c.png)

 and it should appear as the following

![dropdown-menu-alignment-rtl-new](https://cloud.githubusercontent.com/assets/177020/12431519/eea6e848-bf06-11e5-91fa-d40cacc31d35.png)

**Comment by gakimball** [comment]
Merged in #7931, thanks!
