### ISSUE TITLE
table should have width:100%

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation-sites#7937]
seems to be missing from f6, but was there in f5.

**Comment by r3wt** [comment]
@gakimball  thanks geoff! i appreciate it. as an aside, I would like to be able to submit pull requests, but the documentation provided is too disruptive to my work flow (sprinting 24/7), which seems counter productive to what a productivity tool should be. Is there a "short" command to compile foundation changes without all the headache?

**Comment by gakimball** [comment]
@r3wt What do you mean the documentation is disruptive to your workflow?
