### ISSUE TITLE
[Responsive Navigation] Using Responsive Toggle with Motion UI

### ISSUE THREAD

**Issue by shaunmorrison** [zurb/foundation-sites#7940]
Hi,

Through the docs I can't figure out how to use the Responsive Toggle (http://foundation.zurb.com/sites/docs/responsive-navigation.html) with Toggle animations (http://foundation.zurb.com/sites/docs/toggler.html) – at the moment they seem mutually exclusive, unless there's some wizardy markup I'm missing out on?

Thanks!

**Comment by zurbchris** [comment]
Responsive Toggle is for hiding a menu or content in a dropdown panel on small screens. Toggler is a tiny plugin to toggle a class or state of an element. So they are completely separate plugins, but not necessarily mutually exclusive. 
What exactly are you trying to do?

**Comment by shaunmorrison** [comment]
I'm just trying to animate the toggled menu in and and out using something like the animation options in Toggler e.g. data-animate="hinge-in-from-top hinge-in-from-top  spin-out". 

At the moment the responsive toggled menu just displays: block and :none. Unfortunately the responsive toggled menu doesn't seem to have a toggled class or data attr to tie into either.

**Comment by gakimball** [comment]
I could see adding Motion UI support, right now it just uses jQuery `.show()` and `.hide()`.

**Comment by nachtwandler** [comment]
I've tried to add Motion-UI support. So far it works, but I don't know if it's a good solution. It's the first time I've changed something on the Foundation code.

**Comment by mica16** [comment]
Same issue for me, data-responsive-toggle isn't compatible currently with animation from motion-ui.

**Comment by rafibomb** [comment]
We'll call this a feature request.

@nachtwandler Awesome! Where can we check this out?

**Comment by nachtwandler** [comment]
@rafibomb There is a pull request #8001

**Comment by domwhooley** [comment]
Changing line 6286 of foundation.js:
`this.$targetMenu.toggle(0);`
to:
`this.$targetMenu.slideToggle()`
gives the desired result for me. 

I know you shouldn't really mess withe core files but it's only a minor change innit.

**Comment by JeremyEnglert** [comment]
Looks like this may have been addressed in 6.2 or 6.3, If not, it will have for wait for F7.
