### ISSUE TITLE
Last column to the right

### ISSUE THREAD

**Issue by vedran-milic** [zurb/foundation-sites#7942]
How to override this feature?!

Last element floats right in foundation 6.

**Comment by andycochran** [comment]
> In order to work around browsers' different rounding behaviors, Foundation will float the last column in a row to the right so the edge aligns. If your row doesn't have a count that adds up to 12 columns, you can tag the last column with a class of `.end` in order to override that behavior.

http://foundation.zurb.com/sites/docs/grid.html#incomplete-rows

**Comment by vedran-milic** [comment]
If I do it through SASS and if I have grid-column 10 with offset 1, instead of center column will be aligned to the right.

**Comment by vedran-milic** [comment]
Found it $grid-column-align-edge: false
