### ISSUE TITLE
Grid collapse gets reapplied

### ISSUE THREAD

**Issue by vedran-milic** [zurb/foundation-sites#7943]
@include grid-column-collapse; Gets reapplied on the next breakpoint although I don't have any css at all.

<code>.some-class {
    @include grid-column(12);
    @include grid-column-collapse;
}
</code>
In the next break point this class has right and left padding, and it should not have.

**Comment by gakimball** [comment]
Currently looking into it. We introduced responsive gutters in 6.1, but new issues with the feature are cropping up.

**Comment by gakimball** [comment]
Actually, you can just do this:

```scss
.some-class {
  @include grid-column(12, 0);
}
```

The second parameter is a number, so setting it to zero removes padding entirely.

We'll update the documentation to make this distinction more clear.
