### ISSUE TITLE
'order' class doesn't have CSS behind (misleading documentation ?)

### ISSUE THREAD

**Issue by switowski** [zurb/foundation-sites#7946]
Hey,

I just noticed that the 'order' class doesn't have any CSS styling, so in "Source ordering" part of the documentation (http://foundation.zurb.com/sites/docs/flex-grid.html#source-ordering), when you are adding classes like "order-1" and "order-2", it's a bit misleading (since it doesn't have absolutely any effect on the code).

**Comment by gakimball** [comment]
Sorry, that's a typo. The "default" class is `.small-order-[n]`.

Fixed in master and deployed to the live documentation: 49fa63e6d7b4f4f26af6bc93b957bf64b310d270
