### ISSUE TITLE
Reveal Animation Bug

### ISSUE THREAD

**Issue by sharkoman** [zurb/foundation-sites#7947]
Hi,
I downloaded the latest complete css version, In Reveal Plugin when i tried to add data-animation attribute it doesn't work, I coped the same code in the docs and it doesn't work ether, just the gray overlay show up!

**Comment by zurbchris** [comment]
You need to include [Motion UI](https://github.com/zurb/motion-ui), it's a separate plugin.

**Comment by sharkoman** [comment]
ya, its working now! it doesn't mentioned clearly in reveal docs, do i have to include Motion UI files in sass version too ?

**Comment by zurbchris** [comment]
Yes. Because Motion UI is an independent package usable anywhere, the only thing baked in to Foundation 6 is a custom function to hook MUI into F6 easier.
