### ISSUE TITLE
Gulp accessibility plugins for foundation-zurb-template?

### ISSUE THREAD

**Issue by erutan** [zurb/foundation-sites#7950]
I'm just starting to use them, but the following could be nice to have baked in given the focus on a11y in F6. I'll give some more feedback as I use them (and others can chime in). Sort of a tentative feature request pending validation.

https://github.com/Charca/gulp-arialinter
https://github.com/yargalot/gulp-accessibility

**Comment by erutan** [comment]
gulp-arialinter wants NPM4.

```
node_modules/gulp-arialinter/node_modules/arialinter/node_modules/jsdom/lib/jsdom.js:3
() => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
 ^
SyntaxError: Unexpected token )
```

gulp-accessibility is working with the current stack, but pretty verbose by default. Having a separate task might be good, I just tossed it in `pages` to kick the tires.

**Comment by gakimball** [comment]
Very interesting! We'd like to keep Node 0.12 support for now, though, so gulp-accessibility would probably be the way to go. I'm going to roll this into our main feedback thread: #7760
