### ISSUE TITLE
Foundation Sticky - Docs help

### ISSUE THREAD

**Issue by Ne-Ne** [zurb/foundation-sites#7955]
Hi All,

I was trying to get the marginTop value to be removed or 0. After finally figuring out the means to apply it to my code, which is very simple it seems. The documentation does not reflect this...

Is there any referance to examples (see below) on the docs site? I am at a lost.

```html
data-options="marginTop:0;"
```

I think it would great support developers when a use case such as site navigation bar would be a great addition.

**Comment by zurbchris** [comment]
Please see the [JavaScript Reference](http://foundation.zurb.com/sites/docs/javascript.html#configuring-plugins) section of the documentation. It's linked in the table of contents on the left of the page.

**Comment by zurbchris** [comment]
Fixed with ea537f6

**Comment by Ne-Ne** [comment]
Thanks @zurbchris, where does ea537f6 link?
