### ISSUE TITLE
[DropdownMenu] Destroy function not removing bodyHandler (TypeError: _this.$element is null)

### ISSUE THREAD

**Issue by Baedda** [zurb/foundation-sites#7956]
I´ve got a problem using the ResponsiveNavigation. I am using a DrilldownMenu for mobile and a DropdownMenu for bigger viewports. I am using the ResponsiveNavigation plugin to switch between the two plugins:

`data-responsive-menu="drilldown large-dropdown"`

As I can see in the code of the **foundation.responsiveMenu.js** it checks for the MediaQuery, initializes the plugin that should be active for the current viewport and destroys the instances of the unused plugins. The destroying is done by calling the destroy method of the corresponding plugin.

```javascript
ResponsiveMenu.prototype.destroy = function() {
    this.currentPlugin.destroy();
```
Inside of **foundation.dropdownMenu.js** there is a handler that is (sometimes) added to the body:

```javascript
DropdownMenu.prototype._addBodyHandler = function(){
  var $body = $(document.body),
      _this = this;
  $body.off('mouseup.zf.dropdownmenu touchend.zf.dropdownmenu')
       .on('mouseup.zf.dropdownmenu touchend.zf.dropdownmenu', function(e){
         var $link = _this.$element.find(e.target);
         if($link.length){ return; }

         _this._hide();
         $body.off('mouseup.zf.dropdownmenu touchend.zf.dropdownmenu');
       });
};
```

But this handler is not removed in the destroy function of **foundation.dropdownMenu.js**

```javascript
DropdownMenu.prototype.destroy = function(){
  this.$menuItems.off('.zf.dropdownmenu').removeAttr('data-is-click')
      .removeClass('is-right-arrow is-left-arrow is-down-arrow opens-right opens-left opens-inner');
  Foundation.Nest.Burn(this.$element, 'dropdown');
  Foundation.unregisterPlugin(this);
};
```

So if this handler has been added to the body and ResponsiveNavigation switches to the drilldownMenu and I click somewhere on the body a JS error is thrown:
`TypeError: _this.$element is null`

The $element that is null is the $element variable that is defined inside of the addBodyHandler method.

I don´t know how exactly to reproduce this issue, but it sometimes happens after using the large dropdownMenu for a while and then switching to the mobile drilldownMenu. For me it was possibly to reproduce this bug on the Foundation website as well.
http://foundation.zurb.com/sites/docs/responsive-navigation.html

Hope you can help :)

**Comment by zurbchris** [comment]
Thank you for a well formatted and documented issue. Seriously, thanks :smile: :+1: 

Your issue is a known one, and has actually already been fixed, though we haven't deployed a patch version to include it in `master`. View the change here 4954e3f

Thanks, just one more time.

**Comment by uncleoptimus** [comment]
Ditto for regular ol' Dropdown?
```
/**
   * Destroys the dropdown.
   * @function
   */
  destroy() {
    this.$element.off('.zf.trigger').hide();
    this.$anchor.off('.zf.dropdown');
    // I think this is needed here, too
    $(document.body).off('click.zf.dropdown');

    Foundation.unregisterPlugin(this);
  }
```

Encountered when using Foundation in conjunction with React components. 

Issue occurred in conjunction with setting the `closeOnClick` option to `true` while also assigning the `onClick` of the nested elements to do something custom.

We have a Dropdown nested in a Modal/Reveal. That Reveal gets destroyed on `click` of some button inside it. That click also triggers `body click.zf.dropdown' handler, but by the time that function runs the target ref is dead, resulting in an error:

```
foundation.js:3212 Uncaught TypeError: Cannot read property 'is' of null
```

Pointing to this line:
```
...
 Dropdown.prototype._addBodyHandler = function(){
   ...
          .on('click.zf.dropdown', function(e){
            if(_this.$anchor.is(e.target) || _this.$anchor.find(e.target).length) {
...
```

Worse, this click handler on body never gets properly cleaned up, meaning every click thereafter results in the error until another dropdown is clicked/closed normally. It ended up breaking some other click functionality we have going on.

We were able to fix the issue on our end by explicitly removing the handler in our component's `componentWillUnmount` but maybe having it in the `destroy` function itself will be more robust.

(btw, bugs and all, Big Thanks for the excellent and massively helpful library!)
