### ISSUE TITLE
Long dropdown being rendered full width of window

### ISSUE THREAD

**Issue by jnpoyser** [zurb/foundation-sites#7957]
In 6.1.1

**Reproducing:**
* Create a dropdown element 
* Contents of dropdown needs to be higher than the height of the window
* Open the dropdown
* The dropdown is rendered with a *width* that matches the width of the window, so it appears super-wide

**What I'd expect**
I would expect the DD to keep it's native size, overflow past the bottom of the window, thus allowing the browser scrolling to be used. Or even better, supporting scrolling inside the DD using overflow css setting.

It looks like it's an issue in Dropdown.prototype._setPosition, but not knowing the history of the function I'm reluctant to offer a fix

**Comment by olefredrik** [comment]
I'm having the same issue. Any progress on this?

**Comment by olefredrik** [comment]
A temporary fix could be to add a max-height and overflow attribute to the .dropdown-pane. 

```
.dropdown-pane {
  max-height: calc(100vh - 80%) // could also be a pixel or rem value
  overflow: auto; // display a scroll bar if the content in the dropdown exceeds the max-height
}
```

I've verified that this works in Chrome, Firefox and IE.

**Comment by spencern** [comment]
Having the same issue.
