### ISSUE TITLE
Different _settings.scss files available from Zurb

### ISSUE THREAD

**Issue by peterstouw** [zurb/foundation-sites#7960]
Hi,

Why is the _settings.scss file (most recent) downloaded from
https://raw.githubusercontent.com/zurb/foundation-sites/master/scss/settings/_settings.scss
see included file: _mostrecentsettings.scss

different from the _settings.scss created by Yeti Launch Version 1.0.1 (1.0.1)?
see included file: _yetilaunchadvancedsettings.scss

Compare, see included file: _settings compare.pdf

Thanks in advance,
Peter Touw
[foundation - settings files.zip](https://github.com/zurb/foundation-sites/files/99841/foundation.-.settings.files.zip)

**Comment by gakimball** [comment]
There's a known issue with Yeti Launch not correctly downloading the latest settings file. We're working on it!
