### ISSUE TITLE
Foundation._activePlugins object remains empty

### ISSUE THREAD

**Issue by manugill** [zurb/foundation-sites#7962]
In 6.1.1

The _activePlugins object doesn't store any active plugins.

Comment on registerPlugins function in foundation.core.js:
* Creates a pointer to an instance of a Plugin within the Foundation._activePlugins object.

But I couldn't find it manipulating _activePlugins at any point.

**Comment by zurbchris** [comment]
Yeah, that object is no longer being used. I'll pull it out.

**Comment by gakimball** [comment]
Removed in d1f79fd515c719106e4d43c02865fe8b743b3468
