### ISSUE TITLE
Build brakes combined svg files

### ISSUE THREAD

**Issue by markorosic** [zurb/foundation-sites#7964]
It seems that imagemin task doesn't handle combined svg files right (used [svgstore](https://github.com/w0rm/gulp-svgstore) to create the file in question), resulting in almost empty svg file containing only `<svg xmlns="http://www.w3.org/2000/svg">` line. Is there a way to at least ignore certain svg file minimization or to turn it off?

**Comment by gakimball** [comment]
You'd need to ask the folks at [gulp-imagemin](https://github.com/sindresorhus/gulp-imagemin) why the output is messed up.

In the mean time, you can use [gulp-filter](https://github.com/sindresorhus/gulp-filter) to prevent SVGs from going through the compressor. They still get copied at the end, but they skip over gulp-imagemin.
