### ISSUE TITLE
Equalizer: Height equalisation only occurs developer tools are open

### ISSUE THREAD

**Issue by dcpomfret** [zurb/foundation-sites#7965]
Height equalisation only occurs developer tools are open in any browser.

**Comment by zurbchris** [comment]
Chrome, FireFox, and Safari, no dev tools. Seems to be working fine. Do you have JavaScript disabled for some reason?
![screen shot 2016-01-22 at 10 17 37 am](https://cloud.githubusercontent.com/assets/13631168/12519095/84b39d54-c0f1-11e5-9551-4ca4301b351c.png)

**Comment by dcpomfret** [comment]
I do not. I've seen similar posts on the Foundation Forum without response. Here is a video example on some tabs. However the bug is not limited to just tabs.

https://www.dropbox.com/s/tsbid2li4jjw60x/equalizer.mov?dl=0

**Comment by dcpomfret** [comment]
Just updated to the latest version of Foundation 6 and this is even buggier than before. Applying height 0px the majority of the time.

**Comment by dcpomfret** [comment]
Solved this issue. It was due to me fading elements in and it calculating the height during the fade-in which results in it calculating a height of 0. Any ideas how I can still fade my elements in without this being an issue?
