### ISSUE TITLE
[Magellan] Sticky magellan styles disappearing

### ISSUE THREAD

**Issue by johanhatlehols** [zurb/foundation-sites#7966]
**How can we reproduce this bug?**

1. Create a magellan nav with sticky
2. Use anchorTop and anchorBtm
3. Style magellan-nav.sticky

**What did you expect to happen?**
I expected to style the magellan nav and for the style to stay like that when it's anchored at the top, as well as before it's anchored.

**What happened instead?**
The styles was applied and works great when the page loads. The nav correctly stick to the top of the page when you scroll past it. But when you scroll back up, the nav loses it's styling. See attached images.

Page load
![magellan-sticky on page load](https://cloud.githubusercontent.com/assets/11923309/12510827/f6ffc4c6-c10c-11e5-8b99-335279fbb2d0.png)

Magellan stuck at top
![magellan-sticky-at-top](https://cloud.githubusercontent.com/assets/11923309/12510836/0389340c-c10d-11e5-87a2-2167f5e3c528.png)

Scrolling back up
![magellan-sticky-when scrolling-up](https://cloud.githubusercontent.com/assets/11923309/12510830/fb90d516-c10c-11e5-9124-9e8fc28eb17a.png)

![magellan sticky html css](https://cloud.githubusercontent.com/assets/11923309/12510849/1e707d16-c10d-11e5-975c-8e5a279f41cb.png)

**Comment by johanhatlehols** [comment]
Another issue with the same code is that sometimes the magellan-nav is correctly destroyed and put on the bottom of the magellan-section, but sometimes it's destroyed and ends up in the middle of the magellan section. See images.

![skjermbilde 2016-01-22 kl 13 37 26](https://cloud.githubusercontent.com/assets/11923309/12510893/79e2ec42-c10d-11e5-93c6-613c1924699e.png)

![skjermbilde 2016-01-22 kl 13 37 45](https://cloud.githubusercontent.com/assets/11923309/12510894/79e344ee-c10d-11e5-8422-0c83d94b3993.png)

**Comment by zurbchris** [comment]
On the destroy issue, that looks like it might be that you're not *also* destroying the sticky it's wrapped in. 
For your styles issue, what element are you applying your styles to, and can I get an html and css code snippet or codepen?

**Comment by johanhatlehols** [comment]
I'm a bit of a rookie so I struggle to see the bigger picture. How would I go about destroying the sticky it's wrapped in?

Here's a codepen with my exact html and scss code, does that help? http://codepen.io/anon/pen/XXZKJp

**Comment by zurbchris** [comment]
If you could clean it up to provide compiled html instead of handlebars, that would help a lot.

**Comment by johanhatlehols** [comment]
Sorry, of course. How about now?

**Comment by zurbchris** [comment]
A little fuzzy on what exactly you want to happen here, so I'll just tell you your styles were on the wrong element. Ignoring the horrendous color that was used for contrast: http://codepen.io/zurbchris/pen/KVQMNV

**Comment by johanhatlehols** [comment]
I'm sorry I may have rushed my explanation due to time restraints. I will give it a go with styles on the right element first thing monday.

Thanks!

**Comment by rafibomb** [comment]
We'll close this here. Please open a a new issue if you still see this happening along with details. Thanks!
