### ISSUE TITLE
Some error on 6.1.1.

### ISSUE THREAD

**Issue by mmjaeger** [zurb/foundation-sites#7968]
Error: Invalid null operation: "null plus "2"".
        on line 19 of Users/Marco/Sites/cms/wp-genesis-starter/wp-content/themes/genesis-foundation/assets/scss/vendors/foundation/grid/_grid.scss
>> $grid-column-gutter: null !default;
   ---------------------^

**Comment by Deckluhm** [comment]
Please provide more information if you want help.

Are you trying to override the `$grid-column-gutter` variable?

(you should rename your issue, almost everyone creating an issue have "Some error on 6.1.1" ;-))

**Comment by EricRihlmann** [comment]
You can find the answer here, https://github.com/zurb/foundation-sites/issues/7700

**Comment by gakimball** [comment]
Ensure that `$grid-column-gutter` is set to a numeric value in your settings file and you should be good.

If you need more help, we'll need more information :)
