### ISSUE TITLE
[Sticky] Positioning Issues on Resize

### ISSUE THREAD

**Issue by quesako** [zurb/foundation-sites#7969]
**How can we reproduce this bug?**
1. Step one
   scroll on page
2. Step two
   First sticky is start, scroll agin the second is start and the the first is still visible
3. Step three
   refresh the page at this moment

**What did you expect to happen?**
After refresh, the first Sticky not working fine. The second work ( is the current) work normally
![capture d ecran 2016-01-22 a 16 47 56 copie](https://cloud.githubusercontent.com/assets/9018890/12515468/cd68215a-c128-11e5-873f-3aa631c0d1b2.jpg)

**What happened instead?**
Resize the window initialize the bug

**Test case**
http://foundation.zurb.com/sites/docs/sticky.html

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by JeremyEnglert** [comment]
I was able to reproduce this issue. Sticky appears to have issues with the browser window being resized.

**Comment by kball** [comment]
I believe this is connected to https://github.com/zurb/foundation-sites/issues/9047.  @colin-marshall when you take a look at that fix, can you check this one as well?

**Comment by colin-marshall** [comment]
Closing this one out. I believe this was fixed in v6.2.2 by @gehasia. Feel free to reopen if you are still seeing this issue.
