### ISSUE TITLE
[Accordion Menu] Error in code

### ISSUE THREAD

**Issue by samcpt** [zurb/foundation-sites#7974]
**How can we reproduce this bug?**

1. Step one
2. Step two
3. Step three

**What did you expect to happen?**
```
<ul class="menu vertical nested">
```
**What happened instead?**
```
<ul class="menu veritcal nested">
```

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by gakimball** [comment]
Can you describe your problem in more detail?

**Comment by zurbchris** [comment]
it's a docs issue. I found it.
