### ISSUE TITLE
Customized Foundation zip file does not contain foundation.css or foundation.min.css

### ISSUE THREAD

**Issue by mapx** [zurb/foundation-sites#7976]
0. Open http://foundation.zurb.com/sites/download/
1. Choose `Flex Grid`, leave everything else default
2. Press download button.

In the zip file, css folder only contains `app.css`.

**Comment by radimhornicek** [comment]
Hi it doesn't matter if you choose Flex Grid or just Grid. It's broken :(

**Comment by astro-fobi** [comment]
plz fix this i need 24 columns grid creating manually is pain in ass and also i am too lazy to do all sass setup...

**Comment by gakimball** [comment]
It's a known issue we're working to resolve. I'm rolling this into #7033, where we're tracking other issues with the customizer.
