### ISSUE TITLE
The calculation of the maximum height of any container

### ISSUE THREAD

**Issue by vallyol** [zurb/foundation-sites#7982]
When testing the written code revealed a strange problem. 
If your code has an element for which the calculated maximum height of the container, the height of the container is not recalculated when you change the width of the browser. It also appears when changing orientation from portrait to landscape. Moreover, not only in desktop browsers, but also on real mobile devices. 
I've seen this behavior for two elements: responsive sticky topbar and orbits. For both the script calculates the maximum height of the container. And if topbar problem is not always (I didn't understand what is the cause: geomagnetic field, solar activity or the browser cache), for slider this behavior constantly.
Small screencast: https://youtu.be/L00NnYwg8AE

**Comment by xfifix** [comment]
I have the same problem.

**Comment by kball** [comment]
The orbit case should be addressed by #9317.  Will have to independently look at the topbar issue.

**Comment by vallyol** [comment]
OK. Thank you!
Now orbits looks very decent.
There is one problem that I do not know how to resolve ... See - [http://codepen.io/Val_Ery/pen/PGPLmE](url)
If I open a page on the iPhone in the orientation of "Landscape", the slider is scaled when the screen is rotated. But ... If the page opens in the orientation "Portrait" image height does not change.
I understand that it can be set by using media queries. But not yet obtained :(

**Comment by vallyol** [comment]
I think the solution is to use Interchange. (http://codepen.io/Val_Ery/full/WoeZGr/)
Maybe I'm wrong :(
