### ISSUE TITLE
 The functionality of what-input.min.js

### ISSUE THREAD

**Issue by dily86** [zurb/foundation-sites#7983]
Hello,

Id like to know the functionality of what-input.min.js include in Zurbs foundation-6 framework , in the js/vendor directory, please.

Thanks for your answers,

**Comment by gakimball** [comment]
All of our components add outlines to focus/active states to make them accessible to keyboard users. *However*, designers find those outlines ugly, but they're necessary for accessibility.

what-input watches for what input device the user is using, mouse or keyboard. If it's a mouse, the outlines are removed in the CSS. If it's a keyboard, the outlines are kept as a navigational aid.

It's technically an optional dependency—you can remove it if you want. However, we highly recommend keeping it.

**Comment by dily86** [comment]
ok, thanks a lot. ;-)
