### ISSUE TITLE
Flex grid and pull/push columns

### ISSUE THREAD

**Issue by keul** [zurb/foundation-sites#7984]
I was using  the [source ordering](http://foundation.zurb.com/sites/docs/grid.html#source-ordering) feature of the Foundation grid system but I was not able to make it work properly.

After a while I noted that the issue came from the flex support which I activated. It seems that flex grid and pull/push can't work together.

Is this a know limit or an issue?

**Comment by gakimball** [comment]
Refer to the [source ordering section](http://foundation.zurb.com/sites/docs/flex-grid.html#source-ordering) of the flex grid docs. Source ordering is thankfully easier with the flex grid.

**Comment by keul** [comment]
@gakimball oh my...
Sorry for the noise. It's *a lot* easier :smile:
