### ISSUE TITLE
[Sticky, Magellan, Docs] navigation not working

### ISSUE THREAD

**Issue by TvrtkoM** [zurb/foundation-sites#7986]
Clicking on navigation link inside documentation pages will not scroll to anchor location or change to active

![...](http://img.ctrlv.in/img/16/01/24/56a526d41d73b.png)

**Comment by rafibomb** [comment]
I'm seeing it working correctly on a Chrome. What browser are seeing this on?

**Comment by TvrtkoM** [comment]
it seems to be working on chromium and chrome, not on firefox 43.0.4 - Ubuntu or WIndows.
dev console shows warning:

> Tried to initialize magellan on an element that already has a Foundation plugin.

**Comment by rafibomb** [comment]
Ok, see the issue in Firefox. We'll close in favor of this one for the description https://github.com/zurb/foundation-sites/issues/7990 Thanks!
