### ISSUE TITLE
Pagination with Display Block?

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#7988]
I am working on a site and my CMS automatically generates pagination. Their pagination code looks like so: 

    <p><a id="previouspage" href="#" style="display:none" >Previous</a>
    <span class="pagination" id="pagination" > 1  
        <a href="#" title="2">2</a>
        <a href="#" title="3">3</a>
        
    </span>
    <a id="nextpage" href="/colorado-news/page/2/" style="display:inline">Next</a></p>

With Foundations default styling it stacks my pagination vs being an inline list. In looking to fix this I realized Foundation has the following style: 

    .pagination a, .pagination button{
	    display:block;
    }

If I change that it works fine. 

While this isn't a Foundation issue, I'm wonder why is there a `display:block;` for `.pagination a` or `.pagination button`? It doesn't appear to be needed and by removing that, it solves problems like this. 

Is there a reason it is needed?

**Comment by rafibomb** [comment]
Display: block; on anchor tags will make it take up all of it's available space. Removing it causes the hover effect to not fill the background as expected: 
<img width="427" alt="screen shot 2016-01-24 at 8 46 19 pm" src="https://cloud.githubusercontent.com/assets/5652085/12542732/c54a96e2-c2db-11e5-924d-0aa96b9c8858.png">

**Comment by Lynda333** [comment]
@rafibomb - Ah okay! Thank you for the clarification and example. Makes sense. :)
