### ISSUE TITLE
Magellan not working on Firefox

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#7990]
Clicking links on Magellan nav does nothing in Firefox Mac or Windows.

Error in console: Tried to initialize magellan on an element that already has a Foundation plugin.

**Comment by gilkudik** [comment]
Still not working on Firefox Mac or Windows. I tested with the last develop branch and same result.

**Comment by mica16** [comment]
Same issue on Safari..

**Comment by zurbchris** [comment]
Uh, this should totally be working if using the `develop` branch. It definitely works on my machine. The issue was using `document.body` for the scrolling element, which was changed to `$('html, body')`.

**Comment by mica16** [comment]
Indeed, changing to $('html,body') makes the whole works on Firefox :)
Thanks a lot.
