### ISSUE TITLE
jQuery not working except for in Chrome

### ISSUE THREAD

**Issue by dcpomfret** [zurb/foundation-sites#7991]
Chrome 47.0.2526.111 on OS X works perfectly. All other browsers are not loading jQuery.

SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function

function "listeningElementsMutation(mutationRecordsList)" is the issue

Using Foundation 6

**Comment by gakimball** [comment]
What version of Foundation 6? I believe we fixed this in a recent version.

**Comment by zurbchris** [comment]
What version? This is an old issue, that should have been fixed back in November.

**Comment by dcpomfret** [comment]
True, you have fixed this in the latest version. What's the best way to update an exisiting project? I don't see anything in the changelog or documentation.

**Comment by dcpomfret** [comment]
Ah yes, I needed to upgrade. Might be worth adding something to your docs/change log that makes it clear on how to upgrade. I had to run bower install foundation-sites again and choose option 2, rather than just running 'foundation update'.
