### ISSUE TITLE
Major issue: Custom Download - emtpy?

### ISSUE THREAD

**Issue by Benboe** [zurb/foundation-sites#7992]
Hi everyone!

I've been using Foundation for a looong time.. but today I came across a problem. I wanted a custom download of foundation, so entered all the settings.. yet when I downloaded the file I got a zip file, with no foundation css or javascript.. the app.css is totally empty.. help!!

I'm guessing this is a major bug, can it be fixed asap pretty please? :-)

I love foundation and I'm dying to start on my next project!

take care 
Ben

![screen shot 2016-01-25 at 08 25 00](https://cloud.githubusercontent.com/assets/3709877/12544934/4b8bbc88-c33e-11e5-9d09-45dbcb03c70a.png)
![screen shot 2016-01-25 at 08 25 07](https://cloud.githubusercontent.com/assets/3709877/12544935/4b8e9ca0-c33e-11e5-981f-6de27109ea30.png)

ps: sorry for the typo

**Comment by Dephora** [comment]
I'm getting empty app.css files and missing foundation.css files in the custom, essentials, and CLI. The complete seems to be in tact.

**Comment by Benboe** [comment]
Dephora, me too! Glad I'm not the only one :)

**Comment by muralee** [comment]
same for me also, tried all browsers and from different OS same

**Comment by muralee** [comment]
there are some JS errors on this download, may be is this affecting the build and download process.

**Comment by Edorka** [comment]
+1

**Comment by howks** [comment]
I have the same problem. I tried to generate custom build with a different configurations for the whole weekend - always fail.

**Comment by gakimball** [comment]
We're aware of the issue and working on a fix. Going to roll this into #7033 where we're tracking all issues with custom downloads.
