### ISSUE TITLE
[MediaQuery] JS MediaQuery util is not calling _init Method

### ISSUE THREAD

**Issue by zauni** [zurb/foundation-sites#7994]
Hello,

I noticed that the MediaQuery util class is not calling the `_init` method and I have to call this method myself, even if it is marked as `@private`. Is this intentional or is it a bug, because I thought that just plugins have a _init Method and utils don't.

Maybe someone knows why it is like that :)

**Comment by TvrtkoM** [comment]
Foundation.MediaQuery objects acts as a singleton and it's created automatically with

    $(document).foundation();

Now you can do something like

      console.log(Foundation.MediaQuery.current);

to get current screen size, breakpoint name

**Comment by gakimball** [comment]
What @TvrtkoM said. Foundation's initialization code turns on the plugin for you.

**Comment by zauni** [comment]
Okay, thanks for the explanation.

I'm initializing every plugin by myself and I'm not using the `$(document).foundation();` function and then it's necessery to call the _init method to use for example the equalizer plugin with the `equalizeOn` option. 

```
Foundation.MediaQuery._init(); // the next line is not working correctly without this
var equalizer = new Foundation.Equalizer($('.foo'), { equalizeOn: 'medium' });
```

Anyways thanks for the explanation and maybe someone has also the problem when he/she is not using the `.foundation()` function.
