### ISSUE TITLE
[Visibility Classes] Zero max-width

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#7995]
Can the useless `@media screen and (max-width: 0em)` be nixed from the `.show-for-small-only` visibility class? I'm not quite sure how to keep that out of the show-for-only mixin.

**Comment by gakimball** [comment]
@andycochran Yes, this is a bug. If the `breakpoint()` function lands on "small up" or "small down", it should remove the media query entirely and just print the CSS.

**Comment by gakimball** [comment]
Actually, is this happening in Ruby Sass or Libsass?

**Comment by andycochran** [comment]
@gakimball Dunno. Whichever `npm start` uses by default.

**Comment by gakimball** [comment]
Gotcha. I did some refactoring of `breakpoint()` earlier in the week (8252c2ba8f2703a377dc0cf594aa5a2e3ab2ad7a 8b2f710a9dd3ebd6bf194b5e561c46ef0acf016c) which resolved a number of issues including this one. `small only` will now output `(max-width: 39.9375em)` only, no `min-width`. [Here's the test](https://github.com/zurb/foundation-sites/blob/develop/test/sass/_breakpoint.scss#L29) that checks the output.

**Comment by andycochran** [comment]
Noice.
