### ISSUE TITLE
.menu-text gets doubled padded

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites#8002]
This was fixed before, but it looks like it's popped back up. I'll submit a PR if someone doesn't beat me to it.

If the .menu-text class has a link, it receives padding twice. 

![screen shot 2016-01-25 at 2 18 53 pm](https://cloud.githubusercontent.com/assets/6110968/12564836/ba2761a8-c36e-11e5-8372-023b57e9241d.png)

**Comment by gakimball** [comment]
The cut back in specificity was intentional. So this happens when you have an `<a>` inside `.menu-text`? The purpose of that class is to style an `<li>` that doesn't have an `<a>`, so the padding matches.

**Comment by JeremyEnglert** [comment]
I see. I guess I miss understood the use of .menu-text.

I always treated it more like a "site title" class because it also made the text bold.

But you're correct, it occurs when there is an `<a>` inside of `.menu-text`

**Comment by gakimball** [comment]
Definitely get that use case, but we had a slightly more generic use case in mind for the class.

To clear up that confusion, I added a section to the menu docs explaining `.menu-text`: 9d0a6ff7b8fa83183c920cf42a0efff3c65aa6a8
