### ISSUE TITLE
Foundation 6 custom generating empty files

### ISSUE THREAD

**Issue by Madredchris** [zurb/foundation-sites#8004]
Hi guys,

Im trying to generate a custom foundation 6 build. 
All I'm getting is an empty [APP.CSS] and an empty .JS file...

HELP! 

These are my settings: 

![93572473907a8d98e6e0dabf6ff65dce](https://cloud.githubusercontent.com/assets/7989568/12565342/6d8215be-c3b4-11e5-9497-78538d9e1fe4.png)
![8329eb84f8259ceac4847ff46a7aa09c](https://cloud.githubusercontent.com/assets/7989568/12565343/6e3dbc38-c3b4-11e5-91c3-049ad500c441.png)

**Comment by gakimball** [comment]
We're aware of the issue and working towards a resolution. Going to roll this into #7033
