### ISSUE TITLE
Dropdown doesn't work: 'id' of undefined

### ISSUE THREAD

**Issue by jiv-e** [zurb/foundation-sites#8005]
Hi!

Reproduce
---------------
1. Download Foundation 6 for sites: http://foundation.zurb.com/sites/download/assets/complete-f6.zip
2. Unzip the file.
3. Cd into the folder.
4. Run: $ python -m SimpleHTTPServer 8000
5. Goto http://localhost:8000.
6. Ensure that the site renders fine.
7. Add this to the HTML markup: (Copied from http://foundation.zurb.com/sites/docs/v/5.5.3/components/dropdown_buttons.html)
```
<button href="#" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false" class="button dropdown">Dropdown Button</button><br>
<ul id="drop1" data-dropdown-content class="f-dropdown" aria-hidden="true">
  <li><a href="#">This is a link</a></li>
  <li><a href="#">This is another</a></li>
  <li><a href="#">Yet another</a></li>
</ul>
```
--> It doesn't seem to work. See the console for error: TypeError: Cannot read property 'id' of undefined(…)
![image](https://cloud.githubusercontent.com/assets/831144/12566280/87c8283e-c3c1-11e5-8f26-31baa38c2a83.png)

**Comment by tsquez** [comment]
I believe because you stated that you used HTML markup from 5.5.3 and your using 6. The way drop down buttons worked in 5 was rewritten in 6.

**Comment by gakimball** [comment]
Yep, here's the new markup for Foundation 6:

```html
<button class="button" type="button" data-toggle="example-dropdown">Toggle Dropdown</button>
<div class="dropdown-pane" id="example-dropdown" data-dropdown>
  Dropdown!
</div>
```

**Comment by jiv-e** [comment]
Oh snap! I ended up to Foundation 5 page by googling: http://foundation.zurb.com/sites/docs/v/5.5.3/components/dropdown_buttons.html

Didn't notice the version. Is it possible to be more explicit of the version on the older doc pages?

Thanks for the help and great work with Foundation! :)
