### ISSUE TITLE
[GRID] Where is $include-html-grid-classes variable?

### ISSUE THREAD

**Issue by sebastianromero** [zurb/foundation-sites#8006]
I'm using Foundation 6 and I can't find a way to turn off the CSS grid classes just as we did in the previous version of Foundation.
The default classes keep appearing, even when setting $include-html-grid-classes to false. Am I doing anything wrong? Thanks in advance.

**Comment by gakimball** [comment]
Comment out `@include foundation-grid-classes` in your Sass files.

Every component now has its own `@include`, which prints the CSS for that component. Check out our starter project's [app.scss](https://github.com/zurb/foundation-sites-template/blob/master/scss/app.scss) to see what a full base file looks like.
