### ISSUE TITLE
[Reveal] Reveal problem when using deepLink and more nested modal windows

### ISSUE THREAD

**Issue by martinpesout** [zurb/foundation-sites#8012]
**How can we reproduce this bug?**
1. Implement more nested modal windows http://foundation.zurb.com/sites/docs/reveal.html#nested-modal
2. Enable deepLink for all modals
3. Try nested modals and try browser "back button" to return to previous state.

**What did you expect to happen?**

When you go from the first modal window to another, I'd like to see URL with appropriate hash, like `#modal-1`. But because we have 2 nested modals, new modal will change current URL by https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L277 but previous modal will be closed right after opening. So URL will be changed again by https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L471

**Possible solution**

My temporary solution is replace this part of code https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L469-L475 with something like this: 

```
    setTimeout(function() {
        if ($('.reveal').filter(':visible').length === 0) {
            if(_this.options.deepLink){
              if(window.history.replaceState){
                window.history.replaceState("", document.title, window.location.pathname);
              }else{
                window.location.hash = '';
              }
            }
        }
    }, 200);
```

I know that it isn't ideal but it's working for now.

**Comment by DanielRuf** [comment]
Thanks for reporting this. I guess we have to refctor this a bit to get this case working like it should work.

**Comment by DanielRuf** [comment]
What do you think @ncoden ? Revisit this for v7?

**Comment by ncoden** [comment]
@DanielRuf  I don't even understand what the issue is :/

**Comment by DanielRuf** [comment]
The issue is that nested reveals do not open when you go back in the history like they were opened but in reverse. It stops after the first last reveal.

**Comment by DanielRuf** [comment]
Try seeing all previously opened reveals by hitting the history.back button.

https://codepen.io/DanielRuf/pen/OvPpzb

**Comment by ncoden** [comment]
Ok thanks, it's _after_ modals got closed. I'll take a look at it tomorrow.

**Comment by ncoden** [comment]
> tomorrow.

Ahah. On it.

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11093
