### ISSUE TITLE
[Accordion] Accordion-Item won't work with other elements than <li>

### ISSUE THREAD

**Issue by TobiasMalikowski** [zurb/foundation-sites#8013]
Hi together, I found a Bug with the current version (6.1.2).
Accordion-Items won't open or close when you use another element than li for the Accordion-Items.
However I found out, that updating jQuery to version 2.2.0 solves this issue.

I created a Fiddle to demonstrate the issue. The Fiddle includes two Accordions, the first is build with ul and li markup. The second one is build with div markup. As long as jQuery 2.2.0 is included both versions work. If you change jQuery to the current version which is required by Foundation the second example will break.

https://jsfiddle.net/tobiasmalikowski/fd2av3r7/

Here is the link to the docs:
http://foundation.zurb.com/sites/docs/accordion.html

Quote from docs: Note that the data-accordion-item attribute on each list item is required when not using li.

**Comment by rafibomb** [comment]
I'm seeing this was patched in 6.0.6 and works in the codepen http://codepen.io/rafibomb/pen/XXQWBM

The current tested version is jQuery 2.2 - we'll be testing an upgrading to 3.0 in a later release.

For now staying on 2.2 is best
`bower install jquery#2.2 --save`

**Comment by gakimball** [comment]
I put together a [test case](https://github.com/zurb/foundation-sites/blob/87fe59f19e47e37395a6a4a38aca04e673775ac7/test/visual/accordion/item-attributes.html) for accordion item attributes. It verifies that each of these use cases are working:

- Items as `<li>`s
- Items with `data-accordion-item`
- Accordions that mix both methods

The way the initializer code was written, if you had *any* `<li>`s, it would skip checking for `data-accordion-item`, but now it just checks for both at the same time.

I also tested in jQuery 2.1.4 and 2.2.0 and saw no differences.
