### ISSUE TITLE
[Sticky] Simple sticky won't work without an anchor

### ISSUE THREAD

**Issue by amosmos** [zurb/foundation-sites#8014]
**How can we reproduce this bug?**

1. Step one - follow instructions for basic sticky

Unless you set a data-anchor, the sticky won't work and will just be fixed to the window.

**Comment by zurbchris** [comment]
Here's a [codepen](http://codepen.io/zurbchris/pen/wMdpzL?editors=1111) of it working as expected. What version of Foundation are you on?

**Comment by amosmos** [comment]
In your codepen you are showing a sticky that starts and stick to the top. I guess that for that you don't need an anchor at all.

But take a look at the code example in the doc and try it out and you'll see it doesn't work as it should. The docs are missing the instruction to add an anchor (as the code itself below the instructions actually does).

In any case there is no explanation of the data-anchor on the docs. It jumps from no anchor at all to having two anchors.

Amos

**Comment by zurbchris** [comment]
Ahh, true. That line was removed at some point, and probably by me. Apologies.
If you just want to anchor to a single element, say a `main-content` div, you would just pass it `data-anchor="id-of-main-content"` or `data-options="anchor: id-of-main-content;"`

**Comment by amosmos** [comment]
Yeah, I figured it out by looking at the source code of the doc page itself, to see what is the difference between the instructions and the demo :-)

**Comment by zurbchris** [comment]
I'll add that back into the docs before the next deploy.

**Comment by JeremyEnglert** [comment]
Looks like this was added to the documentation. Closing.
