### ISSUE TITLE
[Off-canvas] Bug iOS translateX

### ISSUE THREAD

**Issue by guoni** [zurb/foundation-sites#8015]
Hi,

If you check the following zurb doc on an  iPhone (i have tried on iPhone 6) and click on the open right menu, you can see a bug. The menu expand too much (x2) et come back in the normal expand state.

http://foundation.zurb.com/sites/docs/off-canvas.html

Have you got a solution ?

Thanks,
Guillaume

**Comment by zurbchris** [comment]
![img_0133](https://cloud.githubusercontent.com/assets/13631168/12622543/b767cfd0-c4da-11e5-88c3-42dbfd4ddde3.jpg)
Can you link an image? this is what I'm getting right now on an iPhone 6s.

**Comment by guoni** [comment]
You can try on a iPhone 6 ( the menu left is more fluid than the right). Try also iPhone 4 Safari (iOS 7.1.2).
I can’t send you a photo : the final state is good. just the translate movement of the menu is not fluid and too large
Thanks


Le 27 janvier 2016 à 18:46:55, Chris Oyler (notifications@github.com) a écrit:


Can you link an image? this is what I'm getting right now on an iPhone 6s.

**Comment by rafibomb** [comment]
I'm seeing 2d transforms work in that browser http://caniuse.com/#feat=transforms2d

The Sass version runs autoprefixer. Can you make sure the vendor prefixes are there in your compiled CSS?

**Comment by JeremyEnglert** [comment]
@guoni, I'm having issues reproducing this as well. For now, I'm going to close this.

However, if you want to reopen it using the new issues template, that would be extremely helpful: https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md

Thanks!
