### ISSUE TITLE
Missing JS when downloading from zurb.com

### ISSUE THREAD

**Issue by jerauf** [zurb/foundation-sites#8020]
I'm missing everything in js/foundation when I download from foundation.zurb.com. I've tried downloading everything and tried the custom download. Neither has that folder.

Anyone else have that problem?

**Comment by gakimball** [comment]
I'm seeing the correct file structure on all three downloads. There's no folder called `foundation/` in the new ZIP file download structure.

![screen shot 2016-01-27 at 9 17 16 am](https://cloud.githubusercontent.com/assets/1142001/12621778/01ddaf7a-c4d7-11e5-8ed0-704219de5656.png)
