### ISSUE TITLE
[Accordion] Accordion stops functioning when appending an item dynamically.

### ISSUE THREAD

**Issue by r3wt** [zurb/foundation-sites#8021]
how can i make accordion work with dynamic `.accordion-item` being appended.

**Comment by r3wt** [comment]
I tried the most logical thing, which would be to reinitialize foundation, however:

![img](http://puu.sh/mLpmD/d46988b020.png)

**Comment by zurbchris** [comment]
You need to reinitialize the plugin, not all of Foundation. What you're looking for is:
```js
$('.accordion').foundation('_init');
```
