### ISSUE TITLE
[Feature Request] Portrait/Landscape in JavaScript Media Queries

### ISSUE THREAD

**Issue by DaSchTour** [zurb/foundation-sites#8022]
I think it would be great to have all the media queries that are available in SASS would also be available in JS. For example a check for portrait or landscape would be great. I know that is really easyto make such a check. But it would be nice to have it available in a set of function where it makes sense.

**Comment by gakimball** [comment]
You're thinking in the `Foundation.MediaQuery` library?

**Comment by DaSchTour** [comment]
Yes exactly

**Comment by gakimball** [comment]
Tagging as Help Wanted in case anyone wants to jump in.

The simplest API would be:

```js
Foundation.MediaQuery.orientation; // => "portrait" or "landscape"
```

**Comment by JeremyEnglert** [comment]
Lets talk about this for F7.
