### ISSUE TITLE
Margin grids instead of padding grids

### ISSUE THREAD

**Issue by corysimmons** [zurb/foundation-sites#8024]
Do you guys have a good reason for using padding grids?

http://codepen.io/corysimmons/pen/dGmEBW?editors=1100

Let me know if you want a PR.

**Comment by corysimmons** [comment]
I don't want to duplicate this discussion in two places, and since you and Bootstrap both have the same grid system, could you guys just follow along here? https://github.com/twbs/bootstrap/issues/19026

**Comment by gakimball** [comment]
There are a few quirks with the `calc()` approach, although probably the same number of quirks with our current approach. For example, you can't define the width of a column independently of its gutter, which makes the collapse/uncollapse classes weird. We also now support responsive gutters, which makes that logic *even more* confusing.

We're actually still holding out on Android 2.3, so `calc()` isn't an immediate option anyway.

I like Mark's [comment](https://github.com/twbs/bootstrap/issues/19026#issuecomment-175749492) on your issue: "I'd rather say `25%` and get exactly `25%`". Padding grids require a little extra markup in some cases, but they're *way* easier to write, maintain, and reason about.

**Comment by corysimmons** [comment]
Alrighty. Let me know if you guys change your mind.

**Comment by IamManchanda** [comment]
Yes Yes, we changed our mind :wink: .... Added in #10017

**Comment by kball** [comment]
@gakimball wasn't wrong... the logic around responsive gutters and responsive collapse for margin classes is pretty darned confusing... but it works. Will see if we can simplify it as we dig into this more.

**Comment by corysimmons** [comment]
>the logic around responsive gutters and responsive collapse for margin classes is pretty darned confusing

???

https://codepen.io/corysimmons/pen/NgKYRZ?editors=1100

**Comment by kball** [comment]
Responsive gutters => a map of gutters sizes per breakpoint:

e.g.
```
$margin-gutters {
  small: 20px,
  medium: 30px
}
```
ie for small sizes have 20px gutters, medium and up have 30px gutters.

Since the grid sizes have to include the gutter, that means that that for e.g.
`.small-1` you need to redefine the size for each breakpoint where there exists an entry in the gutters map

**Comment by corysimmons** [comment]
Ahhh, gotcha 👌
