### ISSUE TITLE
SASS Usage

### ISSUE THREAD

**Issue by robertmain** [zurb/foundation-sites#8025]
I'm interested in the idea of using foundation for a sass project at work....

...however, from what I can tell `@import foundation` seems to just generate foundation.css in your stylesheet...at which point that kinda defeats the point of using the sass version, surely?

**Comment by Deckluhm** [comment]
As described [here](http://foundation.zurb.com/sites/docs/sass.html#compiling-manually), you need to `@import settings` before `@import foundation`.

Then, just edit the `_settings.scss` file to customize Foundation.

If you are using Rails, you can use the [`foundation-rails`](https://github.com/zurb/foundation-rails) gem which does this automatically.

**Comment by robertmain** [comment]
Right, I get that - but what if I don't want to import the entirety of foundation? What if I just want to import say the buttons or the form elements?

**Comment by npapazian** [comment]
`@import foundation` just calls this file (https://github.com/zurb/foundation-sites/blob/develop/scss/foundation.scss) which has all the component imports & includes listed. Editing this file will let you configure which components you want to include.

**Comment by robertmain** [comment]
Yes it would but I have a setup where dependencies (including SASS libraries) are downloaded with bower and compiled(sass include paths are accounted for). Basically, what I'm saying is that I can't really edit that file because it's vendor code and is liable to be removed and redownloaded at any given point...

Therefore, it would be nice to be able to just include the ~~stylesheet~~ mixins for creating buttons from my own stylesheet.

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by robertmain** [comment]
I was trying to find out if this was how foundation behaved because that's how bootstrap behaves... But fair enough, I'll make an account and go ask over there. Cheers
