### ISSUE TITLE
[Orbit] Sliders Do Not Work on Mobile devices

### ISSUE THREAD

**Issue by neriticzone** [zurb/foundation-sites#8026]
I am working on a prototype website and noticed that the sliders work on the Desktop but not mobile. I am able to click on parts of the bar and the handle moves accordingly, but you cannot actually move the handle itself.  I have observed this on two different Samsung Android devices running Chrome and FireFox on both my demo page as well as the Zurb Official Slider Documentation for Foundation 6. 

 I saw the issue on www.foundation.zurb.com/sites/docs/slider.html

**Comment by zurbchris** [comment]
This is a known bug with Samsung phones after the recent deploy of Android 5. Somewhere they changed how mouse and touch events are handled. We'll be looking into it, but if you or anyone else thinks they can tackle it, we'd love to see a pr for this.

**Comment by zurbchris** [comment]
@yohio you still interested in maintaining the util you wrote?

**Comment by fkubis** [comment]
Any new to this issue? For me: swipe and orbit-nav-buttons does not work with Andorid Browser (Version 4) at Android 4.3.  .

**Comment by DanielRuf** [comment]
> The problem was not the events (jQuery does all needed). Old Android versions does not support CSS-Transitions. Oribt use motion-ui so you need to add a polyfill for that. Imho could this be closed.

Android 4 is quite old and Google now ships Chrome on new devices.

https://foundation.zurb.com/sites/docs/compatibility.html
> Android Browser | Versions 2.3+

Is the table still accurate for 6.4.3?

https://caniuse.com/#feat=flexbox

**Comment by DanielRuf** [comment]
At least it works in current Android browsers.

**Comment by colin-marshall** [comment]
@DanielRuf I think we can probably close this one out due to how old Android 4 is now. If anybody objects, feel free to reopen.
