### ISSUE TITLE
[CSS compressor] how does it scan and when does it export what to compressed app.css

### ISSUE THREAD

**Issue by peterstouw** [zurb/foundation-sites#8027]
Hi,
I'm using foundation for sites I think… a little bit differently.
For instance, I use php to create html code. In this code I also use classes and id's.
I see that the CSS compressor not always includes these classes and id's in the compressed app.css.
As far as I know the _settings.scss file is not totally leading, the compressor must find the class or id also in the html code also, otherwise it will be skipped and not written to the compressed app.css.
How does the compressor scan the .html files?
When does it stop scanning?
When does it includes a classes or id?

Test example:
This code is an example, both id's are defined in the _settings.scss.

file: body.html
<?php
$adv2head	= '';
$adv2head	.= '<section id="advert1-head">';
$adv2head	.= 'Space Oddity';
$adv2head	.= '</section>';
$adv2body	= '';
//$adv2body 	.= '<div class="row">';
//$adv2body 	.= '<div class="primary callout">';
//$adv2body	.= '<section id="advert2-block">';

compressed: app.css
@charset "UTF-8";table,thead{font-weight:400}.callout.primary,table{font-family:'Yanone Kaffeesat <more css> t-size:1.125rem;color:#666}#advert2-block{color:#DB3838}/*! normalize.css v3.0.3 etc

So the compressor picks up advert2-block, but not advert1-head.

file: body.html
<?php
$adv2head	= '';
//$adv2head 	.= '<div class="row">';
//$adv2head 	.= '<div class="primary callout">';
$adv2head	.= '<section id="advert1-head">';
$adv2head	.= 'Space Oddity';
$adv2head	.= '</section>';

$adv2body	= '';
//$adv2body 	.= '<div class="row">';
//$adv2body 	.= '<div class="primary callout">';
//$adv2body	.= '<section id="advert2-block">';

compressed: app.css
@charset "UTF-8";table,thead{font-weight:400}.callout.primary,table{font-family:'Yanone Kaffeesat <more css> t-size:1.125rem;color:#666}#advert1-head,#advert2-block{color:#DB3838}/*! normalize.css v3.0.3 etc

when I nest advert1-head in a 'row' and 'primary callout' class, the compressor picks them up both.

For the time being I use a file to force the compressor to include "forgotten" classes and id's. This file will not be used further, just to trigger the compressor to export to the compressed app.css, but is a little bit quick&dirty.

file: cssforcecompressor.html
<div class="primary callout">
<section id="advert1-head">
<section id="advert2-block">
<section id="cookiewarning">
<section id="cookiescreen">
<section class="large-5 large-6 large-7 large-8 large-11">

Thanks,
Peter

**Comment by gakimball** [comment]
By "CSS compressor" are you referring to the stuff we ship with the ZURB Template? It includes a tool called UnCSS which tries to scan your HTML and remove CSS from your stylesheet that's unused.

If it's giving you trouble, you can comment out [this line](https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.js#L124) in `gulpfile.js`.

**Comment by peterstouw** [comment]
Yes, that is the one. I like the UnCSS tool because it minimises the size of the app.css. But it doesn't includes classes & id's all the time, see previous example. But with an extra .html file, just containing the needed classes & id's, UnCSS does what I want.
