### ISSUE TITLE
Motion UI - Docs

### ISSUE THREAD

**Issue by Ne-Ne** [zurb/foundation-sites#8029]
Hi All,

I have looked through motion ui and love it, however installation was too bad. However my issue is with the documentation or lack of.

In this ticket I found out that I was calling foundation incorrectly https://github.com/zurb/foundation-sites/issues/7849. However looking through the docs this did not seem obvious that this was how you initiate Motion UI.

**What I am trying to do:**

As I am using Wordpress queries which return a list of data, I want a incremental delay across the page as you scroll down. I understand that I need trigger form the JS to initiate the Motion UI library.

**Aim:**

I ideally want to use data attributes to animate / transition them in.

Are there any examples, such as a Codepen with default classes or customisable SCSS settings?

**Comment by gakimball** [comment]
I'm working on a tutorial to show how you can integrate WOW.js and Motion UI to do "animate on scroll". It'll be done by the end of the week. In the mean time, check out [this CodePen](http://codepen.io/gakimball/pen/WrKRRy) to see a working example.

Here's a basic summary:

1. Add WOW.js to your project.
2. Make an animation class using the `mui-animation()` mixin. Motion UI only has four built-in animation classes, so you'll need to make your own. Refer to the docs [here](https://github.com/zurb/motion-ui/blob/master/docs/animations.md).
3. Also add `animation-duration` to the class so it functions properly.
4. Add the class, along with the class `.wow` to an element.
5. Initialize WOW.
6. Profit!
