### ISSUE TITLE
[Off-Canvas] Keydown event not fired

### ISSUE THREAD

**Issue by Baedda** [zurb/foundation-sites#8030]
I am using Foundation 6.1.2 and got a problem with the JavaScript of the Off-Canvas navigation. In the documentation (http://foundation.zurb.com/sites/docs/off-canvas.html) an opened Off-Canvas can be closed by pressing **ESC**. On my enviroment this doesn´t work.

So I took a closer look to the code but I could not find anything wrong. 
```javascript
OffCanvas.prototype._events = function() {
  this.$element.off('.zf.trigger .zf.offcanvas').on({
    'open.zf.trigger': this.open.bind(this),
    'close.zf.trigger': this.close.bind(this),
    'toggle.zf.trigger': this.toggle.bind(this),
    'keydown.zf.offcanvas': this._handleKeyboard.bind(this)
  });
```
At this point the `keydown.zf.offcanvas` is bound to the Off-Canvas element. I logged out `this.$element` and it has been the expected element. Next I added a `console.log` to the `_handleKeyboard`-function but the log didn´t appear. I am not sure whats wrong. Maybe the keydown-listener should be bound to the document instead of `this.$element`

**Comment by Baedda** [comment]
Today I found out, that if there is a focusable element inside my off-canvas (e.g. an input) which has the focus, then the ESC-press is closing the corresponding off-canvas. But is this really the behaviour we want? In my opinion an ESC-press should always close an visible off-canvas.

**Comment by Baedda** [comment]
I brought up an non branded version of the prototype i am currently working on so you can see the bug a little better. The Menu-Button on the left side is opening an Off-Canvas-Navigation. Pressing ESC doesn´t close it. If you open up the Search (at the top) and press ESC this Off-Canvas area is getting closed. This works because I set the focus to the input field inside of the canvas.
Here you can take a look:
http://christopher-canisius.de/website-prototype/

**Comment by JeremyEnglert** [comment]
@Baedda, thanks for reporting this. I think there are some data-options that will allow you to achieve the functionality you are looking for: http://foundation.zurb.com/sites/docs/off-canvas.html#js-options

For now, I'm going to close this - but feel free to reopen it using the new Issues Template: https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md

Thanks!
