### ISSUE TITLE
[Ordered Lists] list-style-type & margins

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#8033]
What do you think about adding a `$ordered-list-style-type: decimal !default;` variable? 

It would be nice to have a simple mixin to enable various ordered list styles. There are [loads of 'em](http://www.w3schools.com/cssref/pr_list-style-type.asp) that would be nice for other languages, making roman/alpha nested lists, etc…

**Comment by andycochran** [comment]
There's a problem with any list of more than 10 items. If you have too many items, the item markers stick out past the left edge of the `<ol>`'s containing element. 

This is especially troublesome for types with wider item markers, like `list-style-type: lower-roman`. A list type mixin could account for and adjust the list margin. But what that amount should be is still unknown, even with the default `list-style-type: decimal`. 

Maybe a fix could be to put the margin on the `<li>` element in stead of the `<ol>` element. Then we could apply more margin for `li:nth-child(10) ~ li`, `li:nth-child(100) ~ li`, `li:nth-child(1000) ~ li`, etc. (Although, that wouldn't solve roman numerals.)

Surely we can avoid lists like this… 
![image](https://cloud.githubusercontent.com/assets/409279/12680948/487b27a6-c67a-11e5-9e01-d821e0af673a.png)

**Comment by andycochran** [comment]
@gakimball If y'all find these acceptable, I'll work on a PR. 

Would you prefer separate PRs for the two issues? 
* variable & mixin to enable user-defined list types
* dynamic margin depending on quantity of list items (this probably needs more discussion)

**Comment by andycochran** [comment]
D'oh! I just realized various list types already work with `<ol type="1|a|A|i|I">`. 

> **type** = "1" or "a" or "A" or "i" or "I" 
Indicates the marker type to use in the list, in the cases where the marker type of matters (for example, if items in the list are meant to be referenced by their number or letter).
__*Note:*__ The type attribute on the ol element was deprecated in a previous version of HTML, but is no longer deprecated, as it has meaning and is not simply presentational. 
https://www.w3.org/TR/html-markup/ol.html

So Foundation doesn't need a `$ordered-list-style-type` variable. 

But there's still the margin issue to consider. Making a codepen…

**Comment by gakimball** [comment]
`<ul>` and `<ol>` have a `margin-left` that is configurable via `$list-side-margin`. Does changing that not fix the issue?

**Comment by andycochran** [comment]
@gakimball That only fixes the problem if your app has one type of ordered list. And you're okay with unordered lists having the same margin. 

Here's a pen showing the problem and a possible solution: 
http://codepen.io/andycochran/pen/JGBKKo 

One caveat: According to CSS, `type` is not a case sensitive attribute. So `ol[type="i"]` is the same as `ol[type="I"]`, which means that lowercase and uppercase roman numeral lists would have to have the same margin even though the CAPS are much wider.

**Comment by gakimball** [comment]
Reviewed this with the team internally. It's *really* impressive, but despite not being a ton of code, it solves a more specific use case than we feel is worth addressing. We're willing to consider this a design issue—you should know what kind of list style you're using, and have a general idea of how many items will be in the list. From there, you make adjustments accordingly. The specificity (3 class, 2 element) also makes it difficult to override the default.

If you're interested in us hosting it on [Building Blocks](http://zurb.com/building-blocks) we can definitely do that. :)
