### ISSUE TITLE
Foundation 6 ZURB Template modal overlay

### ISSUE THREAD

**Issue by kaydwithers** [zurb/foundation-sites#8035]
**How can we reproduce this bug?**

1. Install the Foundation 6 ZURB Template
2. Drop in some modal code
3. npm run build
4. Open the dist index.html file

**What did you expect to happen?**
A modal background overlay just like in "foundation watch"

**What happened instead?**
No modal background overlay

**Comment by zurbchris** [comment]
It won't be in the index.html until it's rendered in the browser as that element is dynamically created on Reveal instantiation. If you view it in dev tools, you'll see it.
