### ISSUE TITLE
[Close Button] Callout doesn't close

### ISSUE THREAD

**Issue by karleKremen** [zurb/foundation-sites#8043]
**How can we reproduce this bug?**

**What did you expect to happen?**

I wanna have closable alert on my page.

**What happened instead?**

Close button doesn't work!

**Test case**

[CodePen](http://codepen.io/kkremen/pen/rxKwXM)

**Comment by karleKremen** [comment]
Issue closed because I'm migrating to F5

**Comment by Deckluhm** [comment]
You are using Foundation 5.5.3.

Here is the same (but working!) CodePen using the latest version of Foundation (`6.1.2`) : http://codepen.io/anon/pen/WryKrK

**Comment by gakimball** [comment]
What @Deckluhm said.

**Comment by matanster** [comment]
That is a a pretty large example. Can anyone please elucidate, what is necessary for the button to close, apart from the trivial button definition in the html:

```
		<div class="callout" data-closable>
			<button class="close-button" data-close>&times;</button>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore praesentium sint alias dolorum qui vel quaerat, libero consequatur non esse asperiores veritatis commodi, odit eum ipsam nemo dicta iste aliquam.</p>
		</div>
```

I am using foundation 6.2.1.
