### ISSUE TITLE
Round Button Dosent work

### ISSUE THREAD

**Issue by amanuel2** [zurb/foundation-sites#8044]
Round Button Dosent work on current foundation version.. Just saying..
`<input type="button" class="round button "/>`
In the previous 5 versions it works like this..
https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.0/css/foundation.css

Just looking out for foundation

**Comment by gakimball** [comment]
The `.radius` and `.round` classes were removed in Foundation 6. Your HTML will be more sustainable if you apply `border-radius` styles globally to components.

**Comment by amanuel2** [comment]
Oh ok i didnt know that...
