### ISSUE TITLE
[F 6.1.2]  is it Possible to use Grid and Flex-Grid  ?

### ISSUE THREAD

**Issue by xfifix** [zurb/foundation-sites#8045]
I try to use grid with parent .no-flexbox for IE 9 and flex-grid with parent .flexbox but didn't work.

can you tell me what other file to edit ?  

example : 
 .flexbox {
    @include foundation-flex-grid;
  }
  .no-flexbox {
    @include foundation-grid;
  }

**Comment by gakimball** [comment]
The grids aren't designed to be mixed, but what you're describing here might work.

Can you post some grid HTML and explain how it's not working?

**Comment by xfifix** [comment]
I think I finally found when i put .flexbox { @include foundation-flex-grid; }  the weight of path css are heavier because they are 2 classes so my css property do not apply because the weight is lower !

**Comment by gakimball** [comment]
Yeah, if you try to add extra classes to modify rows/columns, you're going to run into specificity issues. A base column is `.flexbox .column`, a row is `.flexbox .row`, etc.
