### ISSUE TITLE
[Slider] Custom Range not working

### ISSUE THREAD

**Issue by campsafari** [zurb/foundation-sites#8046]
**How can we reproduce this bug?**

1. Set for example data-start="25" and data-end="75" and data-initial-start="50"
2. Use the slider

**What did you expect to happen?**
I expect to have the possibility to have a range from 25 to 75
with 25 being the left bound and 75 the right bound
**What happened instead?**
Instead the slider can't be moved to the left and right bounds and
that maximum value i can select is 50 and the range is 25 - 50
**Test case**
http://codepen.io/anon/pen/vLaOQL

**Comment by kball** [comment]
I believe this should be fixed by https://github.com/zurb/foundation-sites/pull/8506, fix will be in 6.2.1
