### ISSUE TITLE
outline on switches (improve base CSS or documentation)

### ISSUE THREAD

**Issue by peckjon** [zurb/foundation-sites#8047]
When implementing a Switch (http://foundation.zurb.com/sites/docs/v/5.5.3/components/switch.html) or similar, Chrome will render a blue outline on ay clicked element.  This is undesirable not merely because it doesn't fit the default Foundation styling, but also because the outline can become misaligned with the label's shadow.

This is easily fixed with: `label {outline:0;}`

This CSS could be added to Foundation's base, or simply mentioned on the documentation page for the relevant components.

![screen shot 2016-02-01 at 11 37 50 am 2](https://cloud.githubusercontent.com/assets/5299412/12728801/5cbe2a14-c8d8-11e5-8a74-106ff4756c74.png)

**Comment by gakimball** [comment]
From an accessibility standpoint, the outline is helpful for keyboard users. However, I'm not seeing this behavior in Foundation 5. Can you post the HTML used to create this switch?

**Comment by JeremyEnglert** [comment]
Closing this out. This was address with what-input.

**Comment by peckjon** [comment]
@JeremyEnglert does this mean the outline will automatically *not* show when using mouse clicks?

**Comment by JeremyEnglert** [comment]
Correct. 

Mouse clicks = no outline. 

Keyword actions = visible outline.

**Comment by peckjon** [comment]
Awesome.  Thx.
