### ISSUE TITLE
[Magellan] Active class wrong for navigation link

### ISSUE THREAD

**Issue by TvrtkoM** [zurb/foundation-sites#8048]
Open Foundation docs kitchensink page http://foundation.zurb.com/sites/docs/kitchen-sink.html

On navigation on the right if i click on "Media Object", "Orbit" gets selected as active.
Also, on live docs, the same navigation is not working on Firefox.

**Comment by gakimball** [comment]
Removing the Magellan section from the Kitchen Sink fixes the issue. Hmm.. looking into it!

**Comment by gakimball** [comment]
Fixed in `master`: 192bae6412594aa75c67384044935a18729c60a0

We don't support nesting Magellans, but that's what was happening in the Kitchen Sink.
