### ISSUE TITLE
[Magellan, Kichen-sink] hidden navigation items

### ISSUE THREAD

**Issue by TvrtkoM** [zurb/foundation-sites#8049]
kitchen sink navigation is so tall some items on it are unusable / hidden; can't select anything past progress bar on my screen - navigation doesn't scroll.

**Comment by gakimball** [comment]
It's a limitation of Sticky—you can't scroll within the contents of the sidebar. There might be a way around it, though.

**Comment by zurbchris** [comment]
Duplicate of #7865, which has a long comment thread, closing this one.
