### ISSUE TITLE
Music Template doesn't work on iOS (fixed bottom nav)

### ISSUE THREAD

**Issue by subpublic** [zurb/foundation-sites#8054]
Hello!

I'm trying to do a fixed bottom navigation, using the flexbox grid.
I looked at the Foundation Templates, Music example, which has exactly what i want.
It works fine on my computer, but not on iphone. Is there a solution for this?

![foundation_bottom_nav](https://cloud.githubusercontent.com/assets/54971/12751583/3d15f2c8-c9be-11e5-9f22-76a015d00179.png)

**Comment by subpublic** [comment]
My guess is that it has to do with .grid-frame using height: 100vh.
If I set it to height: 568px, it starts working. Can't tell if it's a bug that needs a specific ios-fix or if it's possible to do some other way.
I'm using iOS9.2 on an iPhone 6.

**Comment by subpublic** [comment]
My fix for now is detecting iOS and setting
`height: calc(100vh - 69px);`
Doesn't feel like a perfect solution, but works as a temporary fix.

**Comment by gakimball** [comment]
Could you repost this issue on the [Foundation for Apps](https://github.com/zurb/foundation-apps/issues) repo? Thanks :)
