### ISSUE TITLE
Magellan scroll action not working on FireFox

### ISSUE THREAD

**Issue by pressoholics** [zurb/foundation-sites#8056]
Hi

Noticed that even in your[ docs example](http://foundation.zurb.com/sites/docs/magellan.html) magellan scroll doesn't work on Firefox.

Found a fix, in **foundation.magellan.js** line 148

Change this:

`$(document.body).stop(true).animate({`

To this:

`$('body,html').stop(true).animate({`

Scroll works in all browsers now

Thanks

**Comment by zurbchris** [comment]
fixed by 8205a21
