### ISSUE TITLE
Foundation 6 Table Scroll

### ISSUE THREAD

**Issue by atilkan** [zurb/foundation-sites#8059]
I loved this feature. I implemented it. It worked. But later stopped working. Even if i delete my own classes it doesn't work.
Here is my demo page. There is a big table there. 
http://fantasycore.com/clients/hosting/app/seo-vps-eu.html

Edit: If i add max-width:100% to container column, it works. 
Also if i add small-12 medium-12 large-12 it works. On F5 if i add large-12 it was ok on small screen. Grid works different then old or this is a flex grid thing.
I will close the issue after some info. There is not good detailed information about this on docs.

**Comment by atilkan** [comment]
I use custom grid exported css. I don't use scss. Sorry i am in love with stylus. :)

**Comment by gakimball** [comment]
When did it stop working? When you updated Foundation versions?

**Comment by atilkan** [comment]
I did not update Foundation. I am aware it is not a good idea to update middle of a project.

**Comment by gakimball** [comment]
Ah okay. In that case, we need to know how you changed your HTML or CSS to make it stop working.

**Comment by atilkan** [comment]
I would say, i did not change a thing but i am not sure. When it was working, i stopped playing on that part. 
As i said it works if i add small-12 to parent column. The problem is column. Large-12 doesn't have max-width or it doesn't do the magic.

**Comment by gakimball** [comment]
In general the grid should work exactly the same as it did in 5. If it doesn't, consider it a bug.

> I will close the issue after some info. There is not good detailed information about this on docs.

What do you need clarity on?

**Comment by atilkan** [comment]
I don't know. Better close this one now. I will make a demo later and put it here.

**Comment by asecondwill** [comment]
I'm having same issue.  can't get .scroll or .table-scroll to work when using flex grid. I've turned off all of my own styles.

**Comment by kball** [comment]
@asecondwill see the workaround in https://github.com/zurb/foundation-sites/issues/9658
