### ISSUE TITLE
Custom Build color fields accept 7 hex characters

### ISSUE THREAD

**Issue by jeffclemens** [zurb/foundation-sites#8061]
It seems these fields expect a 6-digit hex color.  However, they allow 7 digits.  If 7 digits are inadvertently entered, foundation.css will be missing from the downloaded zip file.

![image](https://cloud.githubusercontent.com/assets/5048517/12773815/41ea435e-ca0d-11e5-988d-01be25194ad8.png)

(from http://foundation.zurb.com/sites/download/)

**Comment by gakimball** [comment]
Merging into #7033 where we're tracking customizer issues.

**Comment by jeffclemens** [comment]
The symptoms are the same as #7520.
