### ISSUE TITLE
Not working on click

### ISSUE THREAD

**Issue by hassanbinsafdar** [zurb/foundation-sites#8062]
**How can we reproduce this bug?**

1. Step one
2. Step two
3. Step three

**What did you expect to happen?**

**What happened instead?**

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by gakimball** [comment]
Please fill out the issue form next time :)

**Comment by hassanbinsafdar** [comment]
sorry but issue is when i click on link in magellan nav its not working . in magellan behaviour when you click on link page scroll down to that link but in this case its not happening . in foundation 5 magellan was working cool and great but in f6 its not working

**Comment by gakimball** [comment]
Can you post the HTML used to create your Magellan nav?

**Comment by zurbchris** [comment]
I'm going to venture a guess and say you're on Firefox, if that's the case, see: #8056

**Comment by hassanbinsafdar** [comment]
<ul class="horizontal menu" data-magellan>
        <li><a href="#first">First Arrival</a></li>
        <li><a href="#second">Second Arrival</a></li>
        <li><a href="#third">Third Arrival</a></li>
      </ul>
<div class="sections">
        <section id="first" data-magellan-target="first">First Section</section>
        <section id="second" data-magellan-target="second">Second Section</section>
        <section id="third" data-magellan-target="third">Third Section</section>
      </div>
I am using this html . and i have data in these sections but when i click on first its not move to first . even i try to click on foundation 6 demo page there magellan also not working

**Comment by zurbchris** [comment]
Also, take a look at this [codepen](http://codepen.io/zurbchris/pen/MKBxEL?editors=1010). Someone was having an issue with magellan yesterday and I forked/fixed their example.

**Comment by hassanbinsafdar** [comment]
i got it its working fine its working with me as well but what i am trying to say.
foundation.zurb.com/sites/docs/v/5.5.3/components/magellan.html
if you go on foundation 5 demo page when i click on arrival page scroll down to arrival section when i click on destination page scroll down to destinatino section when i again click on arrival page scroll up to arrival . its like scroll spy i hope now you got it what i want or foundation 6 does not have this feature becoz in foundation 6.1 its was working but in 6.1.2 its not working

**Comment by Sky-Cat** [comment]
Firefox 44.0 - click not working.
Firefox 45b2 x64 - click not working too.

**Comment by hassanbinsafdar** [comment]
@Sky-Cat I found the problem.
    this.$element.on({
      'resizeme.zf.trigger': this.reflow.bind(this),
      'scrollme.zf.trigger': this._updateActive.bind(this)
    }).on('click.zf.magellan', 'a[href^="#"]', function(e) {
        e.preventDefault();
        var arrival   = this.getAttribute('href');
        _this.scrollToLoc(arrival);
    });
  };
its code in foundation.js line number -> 4302 to 4310 and what you need to do on line number 4308 .

remove that function and add this

    this.$element.on({
      'resizeme.zf.trigger': this.reflow.bind(this),
      'scrollme.zf.trigger': this._updateActive.bind(this)
    }).on('click.zf.magellan', 'a[href^="#"]', function(e) {
        e.preventDefault();
        var arrival   = this.getAttribute('href'),
            scrollPos = $(arrival).offset().top - _this.options.threshold / 2 - _this.options.barOffset;

        // requestAnimationFrame is disabled for this plugin currently
        // Foundation.Move(_this.options.animationDuration, $body, function(){
          $body.stop(true).animate({
            scrollTop: scrollPos
          }, opts);
        });
      // });
  };
it will work thanks

**Comment by michaelvolz** [comment]
There seems to be a simpler solution to this problem: https://github.com/zurb/foundation-sites/issues/8056

**Comment by gakimball** [comment]
@michaelvolz Indeed, the fix outlined in #8056 should address this.

We'll have 6.2 out with this fix at the end of the month.
