### ISSUE TITLE
[Responsive Navigation] Second Level is not possitioned correctly

### ISSUE THREAD

**Issue by dtpop** [zurb/foundation-sites#8064]
**How can we reproduce this bug?**

1. Copy the Navigation HTML Code into the index.html of the demo
2. Open the index in a browser

You will see, that the second level of the navigation will not occur just beneeth the first level but over it.

**Comment by rafibomb** [comment]
Can you add the demo of this issue here so we can see what you mean?

http://codepen.io/rafibomb/pen/GoXqKZ

**Comment by gakimball** [comment]
Duplicate of #7978
