### ISSUE TITLE
[Tabs] Inconsistent SASS variables

### ISSUE THREAD

**Issue by aldees** [zurb/foundation-sites#8069]
$tab-item-color-hover variable is missing.  There is a variable for background color on hover so there should be a variable for the foreground as well.

**Comment by gakimball** [comment]
In 6.2 we're removing the `$tab-item-color` variable, and tab links will just inherit from the regular `<a>` styles. With that in mind, we won't have a tab item color hover variable either.

In general we want as few settings variables as possible. We want developers writing CSS, not hunting for variables that may or may not be there.
