### ISSUE TITLE
[Tooltip]: $tooltip-pip-offset not implemented

### ISSUE THREAD

**Issue by fergaldoyle** [zurb/foundation-sites#8071]
I see `$tooltip-pip-offset` in the documentation and see the variable defined in `_tooltip.scss` but it is not put to use.

**Comment by gakimball** [comment]
Removed the variable in the 6.2 branch: 7541beffd5b163e1cd7522652edce27a5e794767

It doesn't make sense anyway, as the pip is always horizontally centered. If we ever add any hooks to re-position the pip on a per-tooltip basis, we'd maybe need a variable like this again.
