### ISSUE TITLE
[Drilldown] Accessibility/Keyboard controls issues

### ISSUE THREAD

**Issue by anthonysimone** [zurb/foundation-sites#8072]
Keyboard control in the drilldown menu component seems to have some issues. This is using the drilldown component in a new project with the basic example markup provided in the documentation.  Focus doesn't move off of the first item. This appears to be because once you are focused inside the component, the keyboard actions are being handled by the component, and they seem to be applying focus to the `<li>` instead of the `<a>`.

Adjusting this in each of the key handlers seems to fix the focus issue. For example, adjust the down method to
`down: function() {
          $nextElement.children('a').focus();
},` 
and adjusting the others accordingly seems to take care of the focus issue. However, there still seems to be some issues with navigating through menu items that have children and the js added back button, along with moving the focus back up a layer.

I'll be looking into this a bit more when I have some time, I like the component, but need a completely accessible menu for the project I'm currently working, so hopefully I can get this sorted.

**Comment by rafibomb** [comment]
It sounds like that is the issue. Were you able to tinker with it more? Any suggestions?

**Comment by kball** [comment]
Fixed in https://github.com/zurb/foundation-sites/commit/ab0f267608e95a9a9ee9d1bbc85746577b756493
