### ISSUE TITLE
Abide validation marks wrong tags with error when using prefixes

### ISSUE THREAD

**Issue by seaneble** [zurb/foundation-sites#8077]
I'm using Foundation 5 to format and validate some form fields like this:

``` html
<div class="element password">
    <label>
        <span>Password</span>
        <input type="password" name="password" autocomplete="off" required="required" value="">
    </label>
    <small class="error">Please fill in the password field</small>
</div>
```

Abide validation sets a class of `error` on the outer `div.element` in case of errors (like forgotten mandatory fields). Works just as advertised!

But some other fields in my form make use of prefixes like this:

``` html
<div class="element text">
    <label>
        <span>Pick a name</span>
        <div class="row collapse">
            <div class="small-2 large-1 columns">
                <span class="prefix">prefix</span>
            </div>
            <div class="small-10 large-11 columns">
                <input type="text" name="name" required="required" value="">
            </div>
        </div>
    </label>
    <small class="error">You haven't picked a name</small>
</div>
```

Abide attaches the error class to the `div.columns.large-11` here and not to the `div.element`. I guess, the JS logic is to find the nearest parent block element, but I'm not that deep into JS code.
The result is that the pretty error message is never shown. :disappointed: 

Is there any supported way in Foundation to combine abide validation and prefixed form fields? If there isn't, I'd like to request it as a kind of feature…

Thanks for reading,

Sebastian

**Comment by colin-marshall** [comment]
@seaneble very sorry for the late response to your issue. We are moving on to Foundation 7, and there will be no more development or support for Foundation 5. I am closing this one out.
