### ISSUE TITLE
[Magellan] links don't work in Firefox 

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#8078]
Click a magellan link in the docs. They do not work in Firefox: 
http://foundation.zurb.com/sites/docs/magellan.html

**Comment by michaelvolz** [comment]
I have the exact same problem. The Magellan links do not work in Firefox. Any suggestions how to fix this?

Just try the example page: http://foundation.zurb.com/sites/docs/magellan.html

Setup
Sticky Navigation
JavaScript Reference

**Comment by phifa** [comment]
see #8056

**Comment by michaelvolz** [comment]
Perfect, thanks!
