### ISSUE TITLE
Foundation namespace

### ISSUE THREAD

**Issue by andre2** [zurb/foundation-sites#8079]
Hi,

Is any option to create global namespace for css?
I want to use foundation in div with class .frame in wordpress admin.

**Comment by gakimball** [comment]
If you use the Sass version of Foundation you can do this. The CSS for each component is a Sass `@include`, which you can put inside of another selector.

```scss
@import 'foundation';

// These have to be root-level
@include foundation-global-styles;

.frame {
  @include foundation-grid-classes;
  @include foundation-typography;
  // ...
}
```
