### ISSUE TITLE
[Reveal] "Open On" option for media queries feature request

### ISSUE THREAD

**Issue by Baedda** [zurb/foundation-sites#8082]
I am having the same issue with Reveal as mentiond in #7817 
As @zurbchris is posting that there is an updated Reveal in the doing - I would love to see a small feature coming with it, that would fix a lot of issues that Reveal has at once.

The JavaScript should have an option called: _openOn_ and should accept a MediaQuery string as a parameter e.g._'large'_.

With this option the Reveal should only open as a Reveal on larger screens and above. For lower screen sizes the original href="" of the trigger element is beeing executed.

In my case I am using Reveal to display content that is placed on an own content page of my website. I just want to show it in a Reveal for larger screens. Mobile user should be redirected to the original page what is an better user experience on small screens.

Actually I have to write my own click listener for that and can not use the easy data-option binding. So it would be great to have that feature as an JS option, so I still can use data-open="" in the markup to create the link to my Reveal :)

**Comment by samcpt** [comment]
this will be a nice addition

**Comment by rafibomb** [comment]
@Baedda and @samcpt That's an interesting suggestion! We started a conversation on the Reveal Modal and would love to hear your struggles with it and suggestions. http://foundation.zurb.com/forum/posts/38459-f6-reveal-modal-suggestions

**Comment by Baedda** [comment]
Allright thank you. I will see what I can do. But because there are many more changes in 6.2 and Babel is a new requirement it will take a little time for the testings. But I am definitly going to write a feedback :)

**Comment by JeremyEnglert** [comment]
We'll discuss this for V7.
