### ISSUE TITLE
OFFCANVAS BUTTON

### ISSUE THREAD

**Issue by lethunder** [zurb/foundation-sites#8083]
Hello,
i recently migrate to foundation 6 but i have some issues. For exemple, i have an offcanvas inside another offcanvas. when i click on my menu-icon button to toggle the first offcanvas left menu it also triggers the left menu on the other offcanvas. both get opened.

**Comment by gakimball** [comment]
Can you post an HTML sample?

**Comment by lethunder** [comment]
<div class="off-canvas-wrapper full_height">
            <div class="off-canvas-wrapper-inner full_height" data-off-canvas-wrapper>
                <div class="off-canvas position-left full_height" id="mainOffCanvas" data-off-canvas>
                   button
                </div>
                <div class="main-content" data-off-canvas-content>

                    <button class="" type="button" data-open="mainOffCanvas">f</button>

                    <div class="row">
                        <div class="large-12 columns">
                            <div class="off-canvas-wrapper">
                                <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
                                    <div class="off-canvas position-left" id="offCanvasLeft" data-off-canvas>left</div>
                                    <div class="off-canvas position-right" id="offCanvasRight" data-off-canvas data-position="right">right</div>
                                    <div class="off-canvas-content" data-off-canvas-content>
                                        content 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>

**Comment by zurbchris** [comment]
Off-canvas was definitely not built for this use case, and likely won't work at all. It seems like a panel might be more of what you need, and you can have as many as you like.

**Comment by gakimball** [comment]
Agreed, we don't support nested off-canvas. There would be a *huge* amount of overhead in getting that to work, and it's also not what the pattern was designed for.
