### ISSUE TITLE
Off Canvas Question

### ISSUE THREAD

**Issue by TheAggressive** [zurb/foundation-sites#8084]
Is there a way to open a off canvas other than using a data attribute? with a class or ID perhaps?

Thanks!

**Comment by gakimball** [comment]
With a little JavaScript, you definitely can.

```js
$('#offCanvasTrigger').click(function() {
  $('#offCanvas').foundation('open');
});
```

**Comment by TheAggressive** [comment]
Awesome!! Thank you!
