### ISSUE TITLE
input submit button does not expand when in button-group expanded

### ISSUE THREAD

**Issue by Yanchek99** [zurb/foundation-sites#8087]
When including an input[type=submit] button in an expanded button-group it does not expand its width.

```
<div class="button-group expanded">
    <input type="submit" name="commit" value="Button 1" class="button">
    <a class="secondary button" href=/path2">Button 2</a>
    <a class="alert button" href="/path3">Button 3</a>
</div>
```

**Comment by andycochran** [comment]
This should be fixed by #7933.

**Comment by gakimball** [comment]
Yep, we had an issue with the `display: table-cell` method of button groups, which has been revised.

**Comment by Yanchek99** [comment]
@andycochran @gakimball Awesome thank you for your response!
