### ISSUE TITLE
[Button Group] Stacked not right aligned

### ISSUE THREAD

**Issue by weiserma** [zurb/foundation-sites#8090]
**How can we reproduce this bug?**

1. http://foundation.zurb.com/sites/docs/button-group.html
2. Make window width small so that buttons stack

**What did you expect to happen?**

buttons aligned same width 

**What happened instead?**

right border of 1px is displayed on non last links

**Test case**

You can use your doc website.

**Comment by andycochran** [comment]
Fixed in #7933.

**Comment by gakimball** [comment]
Indeed! We'll try to get a patch out soon with this fix.

**Comment by weiserma** [comment]
I'm new at this, how will I know when the patch is deployed to foundation-rails?

**Comment by andycochran** [comment]
@weiserma A patch is the last digit in the version number. In 6.1.2, the digits refer to major, minor, and patch revisions. When 6.1.3 is ready, you'll probably see this fix.

**Comment by gakimball** [comment]
If you follow us [on Twitter](https://twitter.com/zurbfoundation) we always post about new versions.
