### ISSUE TITLE
[Responsive Navigation] menu re-orientation

### ISSUE THREAD

**Issue by Ruth-Cantoni** [zurb/foundation-sites#8092]
**How can we reproduce this bug?**

1. Step one
Go to http://foundation.zurb.com/sites/docs/responsive-navigation.html# using Safari Version 9.0.3 (10601.4.4) on a desktop computer
2. Step two
Resize the window making it small and then large again
3. Step three
Observe the first responsive menu example, the <ul class="vertical medium-horizontal menu"> one

**What did you expect to happen?**

The three list items to go into one single line as they were at the beginning

**What happened instead?**

Item 1 is on a separate row with respect to item 2 and 3

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by jtborger** [comment]
I have a different issue and stumbled upon this one. I cannot reproduce it (Chrome Versie 48.0.2564.103 (64-bit))

**Comment by rafibomb** [comment]
Seems like the same issue reported here: https://github.com/zurb/foundation-sites/issues/7235 We'll close in favor of this one. Thanks!
