### ISSUE TITLE
Make Reveal Scrollable

### ISSUE THREAD

**Issue by DaSchTour** [zurb/foundation-sites#8094]
Well, I know there are a lot of issues with the current reveal implementation. One of the biggest challanges for me is, that I have so much content inside the reveal, that it doesn't fit the viewport on small mobile devices. Therefore I would need scrolling inside the reveal, which isn't possible at the moment.
I would suggest to limit the hight of the reveal when loading to amount that is left for the reveal at the bottom of the page. Maybe the behaviour will be better when the top position is improved, but I guess this is something for a later step. Maybe there is also a CSS solution with 100vh.
As I couldn't get the reveal to work properly in my setup I moved to a solution with only full modals and setting the max-height to 100vh. But this is only a temporary workaround as I would like to use normal modals.

**Comment by zurbchris** [comment]
Yep. Duplicate issue, resolved with a feature branch that will be merged soon.
