### ISSUE TITLE
How do I add a pdf to the site structure? (simply!)

### ISSUE THREAD

**Issue by jasonhick** [zurb/foundation-sites#8095]
Hi All,

Just a quick question. How do I add an asset such as a pdf file into my site? Panini doesn't copy the pdf if it's under the pages folder, and in the assets folder it copies it to the wrong place. 

It feels like overkill writing a gulp task just to copy some pdfs into the right place.

Anybody have any solutions?

Kind regards,
Jason

**Comment by gakimball** [comment]
The `assets/` folder is meant for all static content. What do you mean it copies to the wrong place? Where would you rather have it copy?

**Comment by jasonhick** [comment]
Sorted this out now... 
We were copying our assets into a sub folder on the site. Our assets folder needed to match the structure of the main site. Doh!

Thanks for you reply :)
