### ISSUE TITLE
[Forms] Number Input Spinner Bug

### ISSUE THREAD

**Issue by foodgy** [zurb/foundation-sites#8096]
These [sass lines](https://github.com/zurb/foundation-sites/blob/c66d458b24d72f98a830f517878c0909df46016f/scss/forms/_text.scss#L142) should be fixed:

```
  // Number input styles
  [type='number'] {
    @if not $input-number-spinners {
      -moz-appearance: textfield;

      &::-webkit-inner-spin-button,
      $::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
      }
    }
  }
```

Removed nesting ```[type='number']```.

**Comment by colin-marshall** [comment]
@MandiSaeteun I'm going through old issues and noticed you were assigned this one. Was there a reason for that or should we pass it off to somebody else? Thanks!

**Comment by rafibomb** [comment]
Closing for PR - thanks!
