### ISSUE TITLE
Row nested inside collapsed row, misalignment

### ISSUE THREAD

**Issue by andrewcroce** [zurb/foundation-sites#8097]
So I see theres a note in the 6.1.2 changelog "Fix misaligned gutters when nesting a row inside of a collapsed row", which is odd since I now see exactly that issue after upgrading.

Here's a screen of how an example appears since 6.1.2, with some notations roughly marking the grid structure:

![nested_rows_misaligned](https://cloud.githubusercontent.com/assets/474639/12858173/7b2a99aa-cc1c-11e5-9a01-1ca525915278.png)

And here's what the same thing looked like in 6.1.0

![screen shot 2016-02-05 at 3 02 28 pm](https://cloud.githubusercontent.com/assets/474639/12858188/8e662638-cc1c-11e5-9fdd-d5a7a80a2e95.png)

The inner set of rows previously had some negative margins that aligned them with the outer row, which is no longer present.

**Comment by gakimball** [comment]
Could you post a code sample with just the grid syntax used?

**Comment by andrewcroce** [comment]
Sure thing, heres the grid structure with the contents removed. FYI the `.grid-box` is just the white blocks, they only have internal padding, and bottom margin, no left/right margin:

```
<div class='row small-collapse medium-uncollapse large-uncollapse'>
  <div class='small-12 medium-8 large-9 columns'>
    <div class='grid-box'>A</div>
    <div class='row'>
      <div class='small-12 large-5 columns'>
        <div class='grid-box'>B</div>
      </div>
      <div class='small-12 large-7 columns'>
        <div class='grid-box'>C</div>
      </div>
    </div>
    <div class='row'>
      <div class='small-12 medium-4 large-5 columns'>
        <div class='grid-box'>D</div>
      </div>
      <div class='small-12 medium-8 large-7 columns'>
        <div class='grid-box'>E</div>
      </div>
    </div>
  </div>
  <div class='small-12 medium-4 large-3 columns'>
    <div class='grid-box'>F</div>
  </div>
</div>
```

And here are some screens of this markup in action. First using 6.1.0:

![screen shot 2016-02-09 at 2 34 31 pm](https://cloud.githubusercontent.com/assets/474639/12928256/6c2d201e-cf3a-11e5-862d-3c52fb73c363.png)

And using 6.1.2:

![screen shot 2016-02-09 at 2 35 19 pm](https://cloud.githubusercontent.com/assets/474639/12928267/7623444a-cf3a-11e5-9d57-424147fc09c6.png)

Assuming the change is indeed a fix to some otherwise erroneous behaviour, are there any suggestions on how to keep column elements aligned, regardless of the number of nested rows? Otherwise, it seems to me, as you nest deeper and deeper, the left and right paddings build up and the rows get narrower as the depth increases.

Thanks

**Comment by andycochran** [comment]
Looks like a specificity problem. `.small-collapse .row` trumps `.row .row`. 

We could add `!important` to the margins of `.row .row`. Except yuck!

But if we change this… 
```scss
.row .row {
    margin-left: -.9375rem;
    margin-right: -.9375rem;
}
```
to this…
```scss
.row .columns .row, .row.columns .row {
    margin-left: -.9375rem;
    margin-right: -.9375rem;
}
```
it's fixed.

**Comment by rafibomb** [comment]
This is one of the reasons for the new XY-Grid in 6.4. A PR for this will be merged, and we'll close this here since XY Grid resolves these specificity issues.
