### ISSUE TITLE
[Accordion Menu] Accordion & Dropdown Menus

### ISSUE THREAD

**Issue by foodgy** [zurb/foundation-sites#8100]
Accordion Menu inside Dropdown Menu acts like Dropdown Menu 0_o
Example: https://jsfiddle.net/vgeswoka/

**Comment by gakimball** [comment]
The three menu patterns weren't designed to be combined together. You can, however, swap between them at different screen sizes using the [Responsive Navigation](http://foundation.zurb.com/sites/docs/responsive-navigation.html) plugin.
