### ISSUE TITLE
class="clearing-thumbs" missing in Foundation 6

### ISSUE THREAD

**Issue by xanview** [zurb/foundation-sites#8101]
Hi there,

It seems this is missing in Foundation 6: http://foundation.zurb.com/sites/docs/v/5.5.3/components/clearing.html

Is there any temporary workaround other than downgrading? - Any other compatible component that can be used as a drop in replacement until this is implemented?

**Comment by gakimball** [comment]
There's still a `.thumbnail` class (it replaced `.th` from Foundation 5), but there's no Clearing. We have ideas for Clearing, but a full plugin won't land in the near future.
