### ISSUE TITLE
Request: Menu Align Center

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#8103]
I seem to always have the need to center align a menu. It would be very useful to have it as an [alignment option](http://foundation.zurb.com/sites/docs/menu.html#item-alignment). Expand is close but in my case I don't want the menu expanded, just centered.

**Comment by andycochran** [comment]
You can use `<ul class="menu simple text-center">`.

**Comment by gakimball** [comment]
It would be nice to do without `.simple`, in case you want the standard menu look. I wonder if adding a wrapper element is what's necessary?

**Comment by andycochran** [comment]
The `.simple` menu is the only one that doesn't use floats. So it's the only one can can be easily centered.

**Comment by rafibomb** [comment]
@Lynda333 What workarounds have you found or any suggestions?

**Comment by andycochran** [comment]
@gakimball Yeah, I think a wrapping element is required. If `.menu` was `display: inline-block;` all you'd need is a `.text-center` wrapper.

**Comment by gakimball** [comment]
Implemented a `.menu-centered` wrapper. It'll land in 6.2.

Also worth noting, when flexbox mode rolls out in 6.2, if you're using that, you won't need this wrapper class. You can just add the class `.align-center` to the menu for the same effect.

**Comment by andycochran** [comment]
Nice.

**Comment by Lynda333** [comment]
@gakimball - Awesome!
