### ISSUE TITLE
Half Size Gutters

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#8107]
How about having classes for half-sized gutters?

Often in design you want to group things by proximity to show relationships. The addition of half-sized gutters would make this easier to do. Perhaps they could work similarly to how collapsed gutters work currently.

**Comment by christianmagill** [comment]
Maybe something like UI-Kit does with small, medium and large

http://getuikit.com/docs/grid.html#grid-gutter

**Comment by andycochran** [comment]
Is this different than responsive gutters (https://github.com/zurb/foundation-sites-6/pull/191)? Of course, responsive gutters are done with media queries, not a class. But I imagine you could use a class + responsive gutter mixin in your app.

**Comment by christianmagill** [comment]
Well the gutters sizes would be designed to work within the same layout. Having classes generated for them would allow for easier application.

**Comment by gakimball** [comment]
We aren't interested in extending the grid syntax at the moment, especially since the interaction with responsive gutters could get complex. Thankfully, since our grid is padding-based, it's really easy to write those classes yourself.

```css
.half-gutter {
  /* Default gutter size is 15px */
  padding-left: 7px;
  padding-right: 7px;
}
```

**Comment by christianmagill** [comment]
I've started playing with the idea, but it get's much more complex once you start trying to compensate for nested grids to keep things aligned. So far I haven't figured that part out, you need to utilize negative margins for bleeds, but depending on your layout you might need different margins for each side.

I'll start a post on the forum when I get a little further along.

**Comment by christianmagill** [comment]
Here's what I wound up with

https://github.com/christianmagill/foundation--variant-gutter-classes

**Comment by andycochran** [comment]
@christianmagill Could you submit a pull request so we can see the diff?

**Comment by christianmagill** [comment]
Currently it is essentially a Sass mixin that overrides the defaults. I'm sure it could be better integrated but I'll have to find a minute to dig into how foundation builds the grid classes.

Here's the mixin

https://github.com/christianmagill/foundation--variant-gutter-classes/blob/master/scss/mixins.scss
