### ISSUE TITLE
Sticky : scrollValue 

### ISSUE THREAD

**Issue by pymoza** [zurb/foundation-sites#8109]
**Sticky Plugin : **
Is there any possiblities to declare a scrollvalue to start the element to stick ? 
Example : My header is 400px of height. I want to stick it on top at 400px not like 1px after the first scroll.

Thank You!

**Comment by gakimball** [comment]
To clarify, you're asking about the Sticky plugin?

**Comment by pymoza** [comment]
Exactly. Sticky

**Comment by JeremyEnglert** [comment]
Isn't this already possible? 

http://foundation.zurb.com/sites/docs/sticky.html#js-options

If that doesn't fix your issue, can you reopen using the new "Issues Template"? That will help me replicate the issue.

https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md
