### ISSUE TITLE
Docs code samples have wrong indentation

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#8112]
And it's driving me *crazy*. Haven't investigated the cause yet. We haven't made any crazy changes to how the docs work, although I recently started deploying with Node 5.3 instead of 0.10. Not sure if that's what's causing this, though.

<img width="406" alt="screen shot 2016-02-08 at 9 27 32 am" src="https://cloud.githubusercontent.com/assets/1142001/12893502/44eb7888-ce46-11e5-8b5c-7928f01fe0e3.png">

**Comment by ResentedHook** [comment]
@gakimball - I'm just not seeing this; 
In production you have: ![dotcom_docs_menu](https://cloud.githubusercontent.com/assets/3839416/13375225/170a0fb6-dd4f-11e5-8903-5e31bf81c2b1.png)
In my local build, I have: ![local_docs_menu](https://cloud.githubusercontent.com/assets/3839416/13375226/170e004e-dd4f-11e5-974b-67eab2e08183.png)

locally, I'm running:

- nvm v0.25.1
- node v5.3.0
- npm v3.3.12

Looking at [zurb/panini/issues/#36](https://github.com/zurb/panini/issues/36), I also checked the base page markup examples, where I have:
![ruler_overlay](https://cloud.githubusercontent.com/assets/3839416/13375280/f11b7406-dd4f-11e5-9c97-fb2c04a1d948.png)

**Comment by colin-marshall** [comment]
@ResentedHook it looks to have been fixed. It was definitely messed up for awhile.

**Comment by gakimball** [comment]
Yep, it was indeed fixed. I'm... not sure how! But it's fixed.
