### ISSUE TITLE
[Dropdown] [Feature] Prevent Auto-Resizing

### ISSUE THREAD

**Issue by foodgy** [zurb/foundation-sites#8116]
It would be nice to add feature to disable auto resizing dropdown pane if screen height is lower than dropdown itself.

For now i have to comment these lines :| https://github.com/zurb/foundation-sites/blob/develop/js/foundation.dropdown.js#L182

**Comment by chitrag99** [comment]
I m trying to make my pages responsive with different devices like smart phone, tablet etc. I have been using soho sitebuilder ( online ) provided by hosting company. I m trying to use Foundation drop down menu and make responsive but my existing drop down menu got white background.
Example
[http://www.egtours.com/10_days_nepal_trip.php](url)

**Comment by rafibomb** [comment]
I renamed this to dropdown since it's not the menu component. @chitrag99 Unfortunately your example is not accessible anymore. Any example would help us dig into this: http://codepen.io/rafibomb/pen/YwMOaM

**Comment by rafibomb** [comment]
Dropdown has had tons of updates since this, likely resolving the issue. We'll close this here - reopen a new issue with details if you can still replicate using 6.4+.
