### ISSUE TITLE
Documentation Features

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#8117]
Here's a laundry list of nice-to-haves and bug fixes for the Foundation documentation. Some of them are only things ZURB can implement.
- [ ] Search bar: show aliases if a result result is an alias and not a direct result
- [ ] Link to [Building Blocks](http://github.com/zurb/building-blocks) at the bottom of each component's page
- [ ] Create a [Foundation Forum](http://foundation.zurb.com/forum) post from the sidebar nav of a page
- [ ] Sass Reference: split large variable lists into sub-lists (such as forms and typography)
- [ ] Sass Reference: identify the CSS export mixin (such as `@include foundation-grid-classes()`)
- [ ] JavaScript Reference: use `@since` and `@deprecated` in HTML template
- [x] JavaScript Reference: better examples for running plugin methods zurb/foundation-docs@07d5dca0e3ccab6060916ed1584ed85e9a5c17cf
- [ ] Compatibility: make the table prettier
- [ ] Sometimes anchor generation gets weird with special characters **(need an example)**
- [x] Anchor icons overlap with nav, and sometimes it's hard to keep the icon visible when hovering over it zurb/foundation-docs@d4b8fc1b4c65b1768dc19ecfb22ced114f51be45
- [x] Organize the contents of `docs/assets/img` to be more sensible ab8f7d315e923b9b673d37b55d450cbe95159570
- [ ] There's no link to the Index page anywhere

A few notes about how the documentation is built:
- [Supercollider](https://github.com/gakimball/supercollider) generates the pages from the Markdown files.
- [foundation-docs](https://github.com/zurb/foundation-docs) includes the Sass for the documentation, and the Handlebars helpers needed to render the template, as well as the template itself.

Got feedback? Send it our way :)

**Comment by rafibomb** [comment]
It was suggested on Twitter 
Jonathan Eyler-Werve
@EylerWerve

> It would be helpful update would be to link every Foundation 5 page to nearest-neighbor in F6 docs.

**Comment by Jonathan-Eyler-Werve** [comment]
Hi folks! I would love to see a once page reference that I can use while building pages that gives me all the class declarations available in Foundation. Templates fill this need, but a page like this one http://cheat.markdunkley.com/ would be quite welcome. 

As a user story: 

As a person building sites with Foundation, I want to know if `center` or `centered` is the correct class declaration so I can build fast without reading through the full documentation.

**Comment by rafibomb** [comment]
Agreed! A cheat sheet would be nice. For Foundation 5 one of our awesome community members stepped up on this https://sudheerdev.github.io/Foundation5CheatSheet/

**Comment by colin-marshall** [comment]
Noticed the other day that code snippets in the documentation have messed up indentation. First line is correct but the rest of the lines are indented too much. See screenshot:

![screen shot 2016-02-08 at 2 16 46 pm](https://cloud.githubusercontent.com/assets/4453733/12899497/d28764d6-ce6e-11e5-8d9a-9a6ed1c4d1a7.png)

**Comment by gakimball** [comment]
@Jonathan-Eyler-Werve We wanted to add this to our search bar, but a lot of classes are dynamically-generated which makes it difficult.

A page reference would work also.

**Comment by rafibomb** [comment]
I'm seeing the need for concrete example on how to call MotionUI setting for the plugins that have them. Example: http://foundation.zurb.com/forum/posts/38202-f6-orbit-slider

**Comment by kball** [comment]
Javascript reference:  We should have default as well as or instead of example

**Comment by rafibomb** [comment]
JS examples should use data options instead of JS settings in page, defaults should be in the table reference.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by gakimball** [comment]
@kball Change from "example" to "default" implemented via zurb/foundation-docs@2c75efd314c3d2fe014d5a650781196768d3ccac

**Comment by kball** [comment]
on typography page, strong example doesn't actually show strong

**Comment by gakimball** [comment]
@kball Fixed via de9b43260906f13c5c7d8c2ee9569283b16a1ef9

**Comment by kball** [comment]
Explanation of what sizes 'stack' in table works for.

**Comment by gakimball** [comment]
@kball Change to `.stack` class docs implemented via http://86c600d5bc254fd24b8647d81322d05c0352daf8/

**Comment by IamManchanda** [comment]
@kball Is there something still pending in there!
Do we need to reconsider anything or shall we close it?
