### ISSUE TITLE
responsive and navigation

### ISSUE THREAD

**Issue by chitrag99** [zurb/foundation-sites#8118]
Hello,

I m trying to use foundation to make my site responsive. I followed information from [http://wiki.soholaunch.com/index.php?title=Building_a_Foundation_responsive_template](url) since it is my online site builder soho site builder. But I could fix the issues of my existing drop down or megamenu. How can I fix it ? Here is my template file in the following code. index.html

 `<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>#title#</title>
    <link rel="stylesheet" href="sohoadmin/program/modules/site_templates/pages/PHASE2-Dinkin_Flicka-Evergreen/css/foundation.css" />
    <link rel="stylesheet" type="text/css" href="sohoadmin/program/modules/site_templates/pages/PHASE2-Dinkin_Flicka-Evergreen/custom.css" />
<link rel="stylesheet" type="text/css" href="tooltip/themes/2/tooltip.css" />
<link rel="stylesheet" type="text/css" href="lightbox/css/lightbox.css" />
<link rel="stylesheet" type="text/css" href="jsimgslider/themes/8/js-image-slider.css" />
<link rel="stylesheet" type="text/css" href="mactabs/mctabs.css" />
<script type="text/javascript" src="http://www.egtours.com/tooltip/themes/2/tooltip.js"></script>
<script type="text/javascript"src="http://www.egtours.com/sohoadmin/plugins/MegaMenuBuilder/javascripts/jquery-1.10.2.min.js"></script>
<script  type="text/javascript" src="http://www.egtours.com/jsimgslider/themes/8/mcVideoPlugin.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery-migrate-1.1.0.js"></script>
<script type="text/javascript" src="http://www.egtours.com/jsimgslider/themes/8/js-image-slider.js"></script>
<script src="http://www.egtours.com/float-panel.js"></script>
<script type="text/javascript" src="http://www.egtours.com/mactabs/javascript-tabs.js"></script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript" src="http://www.egtours.com/motionpack.js"></script>
<script src="js/vendor/modernizr.js"></script>
  </head>
<body onload="slidedown('featwrapper');">
<div id="headwrapper">
<div id="head" class="clearfix">
<div id="logo_box"><a href="../../../../../../../Home_Page.php"><img id="logo" border="0" alt="Home" width="322" height="118" src="images/_userimg-logo.png" /></a></div>
<div id="tagline"><img border="0" alt="Home" width="468" height="60" src="images/_userimg-ad_banner.png" /></div></div></div>
<div id="trimbar"></div>
<div id="featwrapper" style="display: none; height: 124px; overflow: hidden">
<div id="feat" class="clearfix">
<div id="featleft">#NEWSBOX#</div>
<div id="featright">#PROMOTXT1#</div></div></div>
<div id="navwrapper">
<div id="nav" class="clearfix">
<div id="signup"><a href="javascript:;" onmousedown="toggleSlide('featwrapper');"><img style="border: 0pt" border="0" alt="Toggle the banner up or down" width="110" height="27" src="images/hide-show.png" /></a></div>
<div id="mainnav">#MEGAMENU#</div></div></div>
<div id="contentwrapper">
<div id="maincontent" class="clearfix">
<div id="subnav">#VSUBS#
<div id="belowmenu">#POWERPLUG4#</div></div>
<div id="content">
<div id="date">#AUTODATESTAMP#</div>#CONTENT#</div></div>
<div id="footerwrapper">#COPYRIGHT#<div id="footer">
<table id="table1" border="0" cellspacing="1" width="100%">
<tbody>
<tr>
<td colspan="7" align="left">
<p align="center"><a title="" href="../../../../../../../Our_Policies.php">Our Policies</a>| <a href="../../../../../../../Privacy_Statement.php">Privacy Statement</a></p></td></tr>
<td width="60"><img border="0" alt="coat of arm" width="66" height="56" src="../../../../../../../images/logos/coatofarm.png" /></td>
<td width="152"><img border="0" alt="natta logo" width="53" height="56" src="../../../../../../../images/logos/nattalogo.png" /></td>
<td width="55"><img border="0" alt="uftaa logo" width="80" height="56" src="../../../../../../../images/logos/uftaa.png" /></td>
<td width="71"><img title="" alt="skull logo" width="75" height="36" src="../../../../../../../images/paybyskull.png" /><br />
</td>
<td width="71">
<p><img title="" alt="paypal logo" width="57" height="57" src="../../../../../../../images/paypalv.png" /></p></td>
<td width="26">
<p><img title="" alt="vitof logo" width="97" height="73" src="../../../../../../../images/vitof_logo.png" /></p></td>
<td width="90"><img border="0" alt="SSL" width="90" height="50" src="http://www.egtours.com/images/rapidssl_ssl_certificate.gif" /></td></tbody></table></div></div>
<script type="text/javascript" src="http://www.egtours.com/lightbox/js/lightbox.js"></script>
<div id="backtop">&#9650;</div>

<script>
   	/* Remove the slogan div cleanly if it's not in use */
   $(function () {
   if($(".slogan").html().length === 0) {
   	$(".slogan").remove();
  	}
  	/* Expand the content area out if the sidebar isn't in use */
  	if (!$("#box-one").text().trim().length){
		$(".middle").addClass("large-12").removeClass("large-8");
		$(".box").remove();
		}
  });
</script>
   <script src="js/foundation.min.js"></script>
   <script>
     $(document).foundation();
   </script>
</body>
</html>`

custom.css

`html {
	height: 100%;
	margin-bottom: 1px;
}

body {
	margin: 0px;
	padding: 0px;
	background-color: #CCCCCC;
	
}

body,
td.sohotext,
td.text,
p,
span {
	font-family: sans-serif, Helvetica, Verdana, Arial;
	font-size: 13px;
	color: #525252;
	line-height: 140%;	
}

/* Fixes and hacks */

.clearfix:after {
	clear: both;
	display: block;
	content: ".";
	height: 0;
	visibility: hidden;
}

* html input.quick_signup {
	background-attachment: 100%;
	}

/*END - Fixes and Hacks */

/* Navigation */

#mainnav a:link, #mainnav a:visited  {

	color: #FFF;
	text-decoration: none;
	display: block;
	padding-right: 13px;
	float: left;
	padding-top: 8px;
	padding-left: 13px;
	padding-bottom: 7px;
	background-image: url(images/menu_div.jpg);
	background-repeat: no-repeat;
	background-position: right top;
}

#mainnav a:hover {
	color: #36CC2F;
	background-image: url(images/nav_active.jpg);
	background-repeat: repeat-x;
	background-position: right top;
}

.hmains {
    font-size: 100%;
}
#megamenu {  
        list-style-type:none;  
        width:100%;  
        margin: 3px auto 04px auto;  
        height:40px;  
        padding:2px 0px 3px 0px; 
}
table.vmenu_subs {
    margin-bottom: 30px;
	margin-top: 15px;
}

/*#leftav a:link, #leftnav a:visited, */
   a.vmenu_sub_off:link,
   a.vmenu_sub_off:visited,
   a.vmenu_sub_on:link,
   a.vmenu_sub_on:visited  {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 95%;
	font-weight: bold;
	color: #000;
	background-image: url(images/sideNav_bullet.gif);
	background-repeat: no-repeat;
	background-position: left center;
	padding-top: 5px;
	padding-bottom: 5px;
	border-bottom: 1px solid #acacac;
	text-decoration: none;
	padding-left: 24px;
	display: block;
	width: 150px;
}

/*#leftav a:hover,*/
a.vmenu_sub_off:hover,
a.vmenu_sub_on:hover
a.vmenu_sub_off:active,
a.vmenu_sub_on:active  {
	color: #666;
}

a:link, a:visited {
	color: #00CC00;
	text-decoration: none;
}

a:hover {
	color: #009900;
}

#feat a:link, #feat a:visited {
	color: #fdb417;
	text-decoration: none;
}

#feat a:hover {
	color: #fed27e;
}

/*END - Navigation */

#headwrapper {
	background-image: url(images/top_bg.png);
	background-repeat: 50% no-repeat;
	margin: 0px;
	padding: 0px;
	height: 109px;
	position: relative;
}
#featwrapper {
	background-color: #1e8019;
	height: 124px;
	border-bottom-style: solid;
	border-bottom-width: 1px;
	border-bottom-color: #185d14;
	overflow: hidden;
	border-top-width: 1px;
	border-top-style: solid;
	border-top-color: #2b9d22;
}
#feat {
	width: 880px;
	margin-right: auto;
	margin-left: auto;
	background-image: url(images/feat_bg.jpg);
	background-repeat: no-repeat;
	background-position: left top;
	height: 124px;
	color: #FFFFFF;
}
#navwrapper {
	background-color: #1e8019;
	height: 32px;
	border-top-width: 1px;
	border-bottom-width: 1px;
	border-top-style: solid;
	border-bottom-style: solid;
	border-top-color: #2b9d22;
	border-bottom-color: #185d14;
}
#nav {
	background-image: url(images/nav_bg.jpg);
	background-repeat: no-repeat;
	background-position: left top;
	height: 32px;
	width:880px;
	margin-right: auto;
	margin-left: auto;
	color: #FFFFFF;
}
#contentwrapper {
	background-color: #ededf1;
	margin: 0px;
	padding: 0px;
}
#maincontent {
	background-image: url(images/content_bg.jpg);
	background-repeat: no-repeat;
	background-position: left top;
	width: 880px;
	margin-right: auto;
	margin-left: auto;
	background-color: #ededf1;
}
#mainnav {
	width: 72%;
	float: left;
	padding-left: 5px;
}
#signup {
	width: 25%;
	padding-left: 5px;
	float: left;
	height: 20px;
	padding-top: 2px;
	font-size: 85%;
	color: #cccccc;
	text-align: center;
}

#subnav {
	margin: 0px;
	float: left;
	width: 25%;
	padding-top: 15px;
	padding-right: 5px;
	padding-bottom: 5px;
	padding-left: 5px;

}
#belowmenu {
	display: block;
	float: left;
	width: 210px;
	padding-top: 15px;
	padding-left: 5px;
	
}
div.sidebox {
	display: block;
	float: left;
	width: 210px;
}

#content {
	margin: 0px;
	width: 70%;
	float: left;
	padding-top: 12px;
	padding-right: 7px;
	padding-bottom: 12px;
	padding-left: 7px;
	overflow: hidden;
}
#date {
	font-size: 90%;
	text-align: right;
	color: #858585;
}

#featleft {
	float: left;
	width: 25%;
	padding-left: 5px;
	padding-top: 5px;
}
#featright {
	float: left;
	width: 72%;
	padding-left: 10px;
	padding-top: 5px;
}

#footer {
	text-align: center;
	width: 100%;
	margin-right: auto;
	margin-left: auto;
	padding-top: 10px;
	font-size: 85%;
	padding-bottom: 10px;
	color: #939393;
}

#head {
	height: 109px;
	width: 880px;
	margin-right: auto;
	margin-left: auto;
}
#logo_box {
	height: 109px;
	float: left;
	width: 28%;
}
#tagline {
	float: left;
	width: 70%;
	color: #999999;
	text-align: right;
	padding-top: 22px;
}

#logo {
	position: absolute;
	top: 3px;
}

#trimbar {
	background-color: #000000;
	margin: 0;
	padding: 0;
	height: 7px;
	width: 100%;
	border-top: 1px solid #999999;
	border-bottom: 1px solid #333333;
}

div.newsbox {
    line-height: 115%;
}

/*hiding from IE mac \*/

* html .clearfix {
	height: 1%;
}

.clearfix {
    display: block;
}

/* end hiding from IE mac */

#footerwrapper {
	width: 100%;
	border-top-width: 2px;
	border-top-style: solid;
	border-top-color: #959595;
	background-color: #CCCCCC;
}
/* Integrated Styles */

.portfolio {
	padding-top: 10px;
	padding-bottom: 10px;
	border-bottom: 1px solid #EFEFEF;
	width: 100%;
	overflow: auto;
}

span.alert, 
span.profile,
span.download,
span.search  {
	display: block;
    float: left;
	margin:  10px;
	padding: 10px 10px 10px 45px;
}

span.alert {
	color: #333333;
	background-color: #dddddd;
	border-bottom: 4px solid #b6b6b6;
	border-top: 4px solid #b6b6b6;
	background-image: url(images/span_alert.jpg);
	background-repeat: no-repeat;
	background-position: 7px 12px;
}

span.profile {
	color: #333333;
	background-color: #dddddd;
	border-bottom: 4px solid #b6b6b6;
	border-top: 4px solid #b6b6b6;
	background-image: url(images/span_profile.jpg);
	background-repeat: no-repeat;
	background-position: 7px 12px;
}

span.download {
    width: 100%; 
	color: #333333;
	background-color: #dddddd;
	border-bottom: 4px solid #b6b6b6;
	border-top: 4px solid #b6b6b6;
	background-image: url(images/span_download.jpg);
	background-repeat: no-repeat;
	background-position: 7px 12px;
}

span.search {
	color: #333333;
	background-color: #dddddd;
	border-bottom: 4px solid #b6b6b6;
	border-top: 4px solid #b6b6b6;
	background-image: url(images/span_search.jpg);
	background-repeat: no-repeat;
	background-position: 7px 12px;
}

span.product {
	color: #333333;
	background-color: #fff;
	border: 1px solid #b6b6b6;
	margin:  10px;
	padding: 10px;
	font-size: 10px;
	line-height: 145%;
	display: block;
}

blockquote {
	border-top: 4px solid #D3D3D3;
	border-bottom: 4px solid #D3D3D3;
	margin:  10px;
	padding: 10px 10px 5px 45px;
	background-color: #f5f5f5;
	background-image: url(images/quote1.png);
	background-repeat: no-repeat;
	background-position: 5px 5px;
}

blockquote p {
	padding-right: 35px;
	background-image: url(images/quote2.png);
	background-repeat: no-repeat;
	background-position: 100% 100%;
}
ul
{
list-style-type:none;
padding:0px;
margin:0px;
}
ul li { 
        background-image: url("images/li_bullet.gif");
        background-position: 0px 4px;
        background-repeat: no-repeat;
        overflow: hidden;/* added by dsonesuk as li cannot detect area of    floated 'a' elements*/
        padding-left: 14px;
        margin-left: 0px 4px;
        font-size: 12px;
}
 
ul, li {list-style-type:none !important;}
}

h4 {
	font-size: 115%;
	color: #333;
	margin-bottom: 5px;
	margin-top: 0px;
	padding: 0px;
}

#feat h4 {
	color: #fdb417;
}

h4 {
    font-size: 120%;
	color: #0066FF
}

h3 {
	font-size: 150%;
	color: #1E7D19;
}

h2 {
	font-size: 180%;
	color: #196115;
}
input.login_box {
	border: 0;
	height: 25px;
	width: 122px;
	padding-left: 30px;
	padding-top: 4px;
	background-image: url(images/login_bg.jpg);
	background-repeat: no-repeat;
	background-position: left top;
}

input.pass_box {
	border: 0;
	height: 25px;
	width: 122px;
	padding-left: 30px;
	padding-top: 4px;
	background-image: url(images/password_bg.jpg);
	background-repeat: no-repeat;
	background-position: left top;
}

input.quick_signup {
	border: 0;
	height: 19px;
	width: 168px;
	padding-left: 32px;
	padding-top: 3px;
	margin-top: 4px;
	background-image: url(images/quick_signup_bg.jpg);
	background-repeat: no-repeat;
	background-position: left top;
	background-color: #ededed;
}

div#answer0,
div#answer1,
div#answer2,
div#answer3,
div#answer4,
div#answer5,
div#answer6,
div#answer7,
div#answer8,
div#answer9,
div#answer10 

{
        padding-left: 28px;
	padding-bottom: 10px;
	background-image: url(images/answer.gif);
	background-repeat: no-repeat;
	background-position: 2px 0;
}

table#Search_Form,
table#Search_Form2  {
    
}

table#Detail_Results2,
table#Initial_Results {
    margin-top: 15px;
}

`

If paid answers are needed to rewrite and fix my issues I am willing to buy it.

**Comment by rafibomb** [comment]
The [Foundation forum](http://foundation.zurb.com/forum/) would be a great place to seek some help with troubleshooting what might be going on here. If it turns out to be a defect, you'll have some more info to provide here which will help prioritize and get it fixed.

We're trying to keep the issue list focused on confirmed defects in Foundation, so any help everyone can provide to differentiate between usage / troubleshooting and actual defects is appreciated!

**Comment by chitrag99** [comment]
Hi,

Thank you very much for your prompt reply. I have been using online
site builder called soho site builder provided by my hosting company.
So, it is drag and paste site builder. When I came to make responsive
pages, they have provided tricks and tips using foundation to make
soho build pages responsive.

The information is provided from soho site builder in the following links.

http://wiki.soholaunch.com/index.php?title=Building_a_Foundation_responsive_template

After applying their trick, my pages looks like this.

http://www.egtours.com/Annapurna_Base_Camp_Trek.php

I m just wondering how to fix these issues. Since, white background is
covering my drop down menu, vertical menu, footers and some borders
appearing. I want to fix these or if my template needed to re-write I
ask for the changes where should I make.

If you should have any questions, I will be glad to provide information needed.

Chitra
