### ISSUE TITLE
[Off-canvas] menu opens when tabbed, but user interaction is disabled

### ISSUE THREAD

**Issue by kreddenOnt** [zurb/foundation-sites#8121]
Step to reproduce
1. Navigate to http://foundation.zurb.com/sites/docs/off-canvas.html
2. Press shift + tab until the right hand off-canvas menu opens

Expected result
As a user I should be able to interact with the menu using the mouse or keyboard. If I click on a menu item I should be taken to the relevant page. If I click the close button 'X' the menu should close. If I click on the 'open right menu' button I would expect the menu to either do nothing (as the state is open) or to toggle between open/close state.

Result
The right hand menu opens when tabbed but user interaction is disabled. Menu items are not clickable. The menu cannot be closed by clicking the close button 'X'. Clicking 'open right menu' button when the menu is in this state will create a new instance of the off-canvas menu.

Test case
http://foundation.zurb.com/sites/docs/off-canvas.html

**Comment by JeremyEnglert** [comment]
@kreddenOnt, have you checked out the options available for Off-Canvas?

http://foundation.zurb.com/sites/docs/off-canvas.html#js-options

I think this may allow you to achieve the functionality you are looking for.

**Comment by albertvolkman** [comment]
I'm thinking most people would want it to not be accessible via tab when it shouldn't be displayed. If that's an option, I'm not seeing it?

**Comment by andycochran** [comment]
@brettsmason For consideration in your off-canvas refactoring.

**Comment by brettsmason** [comment]
This should now work correctly in version 6.3 - the user should not be able to tab to the hidden panel. The release candidate is currently out for testing, with the final version out in a few weeks.

Closing this, but if you have any issues with this in 6.3 please re-open.
