### ISSUE TITLE
update bower-foundation repository for v6

### ISSUE THREAD

**Issue by segrey** [zurb/foundation-sites#8122]
Currently, it's impossible to install foundation version 6 using
```
bower install git@github.com:zurb/bower-foundation.git
```

Will this repository be updated?

**Comment by gakimball** [comment]
We switched package names for version 6. Use `foundation-sites` instead.

**Comment by segrey** [comment]
Thanks for the information. Maybe it makes sense to update https://github.com/zurb/bower-foundation/blob/master/README.md to reflect this change.

**Comment by gakimball** [comment]
It's updated in the [readme](https://github.com/zurb/foundation-sites/blob/V5/README.md), but Travis isn't building to the bower-foundation repo for some reason. We'll work on fixing that.

**Comment by segrey** [comment]
Ah, indeed, sorry.
