### ISSUE TITLE
Tabs refresh page

### ISSUE THREAD

**Issue by anothergituser** [zurb/foundation-sites#8123]
**How can we reproduce this bug?**

Make some tabs like this

``` html
<ul class="tabs vertical" id="click-vert-tabs" data-tabs data-autoFocus="true">
    <li class="tabs-title is-active"><a href="#panel1v">Tab 1</a></li>
    <li class="tabs-title "><a href="#panel2v">Tab 2</a></li>
</ul>
```

Notice it has the option `data-autoFocus="true"`.

**What did you expect to happen?**
After clicking Tab 2 and refresh the page, it should stay on Tab 2
**What happened instead?**
Tab 1 was active

**What i did to get the desired behaviour**

Edit foundation.tabs.js, in function _handleTabChange add something like

``` javascript
    if(history.pushState) {
        history.pushState(null, null, hash);
    }
    else {
        window.location.hash = hash;
    }
```

taken from
http://stackoverflow.com/questions/3870057/how-can-i-update-window-location-hash-without-jumping-the-document

and where i use the tabs

``` javascript
if(window.location.hash){
    $('a[role=tab]').each(function(){
        var hash = '#' + $(this).attr('href').split('#')[1];
        if(hash == window.location.hash){
            $(this).click();
        }
    });
}
```

taken from ##3692 @dimaip

_Not pretty.._

**Comment by andycochran** [comment]
This reminds me of https://github.com/zurb/foundation-sites/issues/7606#issuecomment-166391947, and how all components with anchors (like tabs) should have an option to expose the hash change (instead of `preventDefault()`) so that apps can leverage them.

**Comment by abdullahsalem** [comment]
**Note:** @anothergituser any multiaple words property should be separated by hyphen ` - `,so the property you mentioned should be written like this `data-auto-focus`, but not `data-autoFocus`.

According to the documentation, the purpose of this property `data-auto-focus` is
> Allows the window to scroll to content of active pane on load if set to true.

So putting that property on a *Tabs* component means that the window will scroll to the active pane, and I tested that and it works well.

**Test case**
http://codepen.io/abdullahsalem/pen/reoRXB

Therefore, I think this issue shouldn't be labeled neither as a *feature* nor a *bug*.

@andycochran you're right, enabling that option is importing in another cases, in particular the *Deep linking* feature #7652  that should be implemented next release.

**Comment by IamManchanda** [comment]
@anothergituser Does this issue still exists... Please let us know if it does?
