### ISSUE TITLE
Reveal compute wrong screen height and it's positioned relative to body instead of relative to window

### ISSUE THREAD

**Issue by yurimorini** [zurb/foundation-sites#8124]
I've got a Reveal modal windows which disappear in when opened.
The overlay element appear without the modal window.
Inspecting the code you can see that the modal is positioned outside the screen.

Example:
http://codepen.io/yurimorini/pen/obQQNa

In the example body has a very high height, the modal appear but the window is scrolled at half body dimension instead of half window dimension.

If you look at `GetDimension` function:

    var rect = elem.getBoundingClientRect(),
        parRect = elem.parentNode.getBoundingClientRect(),
        winRect = document.body.getBoundingClientRect(),
        winY = window.pageYOffset,
        winX = window.pageXOffset;

winRect here is bodyRect, in fact replacing winRect with this, the modal is positioned in the right place
   
    // not so cross browser
    var winRect = { width: window.innerWidth, height: window.innerHeight };

Tested on Firefox and Chrome on Windows

**Comment by bevdam** [comment]
@yurimorini so did you fix this and create a pull request

**Comment by yurimorini** [comment]
@bevdam GetDimension is used everywhere in the code, maybe I wrongly understand the meaning of the whole code, 'cause i never played with it. So I'm waiting for a feedback (is it a bug? the issues is not labeled as bug) and then, if I can i create a pull request.

**Comment by bevdam** [comment]
@yurimorini  sure thing . Thanks

**Comment by matticusfinch** [comment]
On the actual foundation documentation examples the popup is bugged to begin with. The scroll bar disappears(the track remains) which causes the content behind the modal popup to shift to the right.

**Comment by bevdam** [comment]
Hi, I figured out what was causing my position errors. In foundation 6 they removed the ajax request.
I was ajax to populate the reveal using the open callback assuming it would resize and position  according to the content loaded. It did not. To fix after I change content I trigger resizeme.zf.trigger on the reveal. Problem no Problem. FYI

**Comment by colin-marshall** [comment]
@yurimorini this appears to have been fixed in a recent update. When I bump the versions to 6.2.1 in your CodePen example it doesn't scroll halfway down the page when I close the reveal modal. Feel free to reopen the issue if there's still problems. Thanks!
