### ISSUE TITLE
Slider data-end issue with duel handles

### ISSUE THREAD

**Issue by arelidev** [zurb/foundation-sites#8125]
Data-end with two handles breaks the slider. I set the cap to 20 opposed to 100 and on initialization, the fill does not reach between both handles. Moving the first handle makes the fill span across, but moving the second does not.
![capture](https://cloud.githubusercontent.com/assets/13908167/12924876/90376a34-cf29-11e5-89bb-afc439cb7765.PNG)

**Comment by loficode** [comment]
See pull request
https://github.com/zurb/foundation-sites/pull/8128

**Comment by gakimball** [comment]
Fixed via #8128. Thanks @loficode!

**Comment by arelidev** [comment]
I see this was committed to the master branch but there still seems to be an issue with the fill bar with a custom data-end:

`<div class="slider" data-slider data-start="0" data-end="20" data-initial-start="6" data-initial-end="14">
        <span class="slider-handle" data-slider-handle role="slider" tabindex="1"></span>
        <span class="slider-fill" data-slider-fill></span>
        <span class="slider-handle" data-slider-handle role="slider" tabindex="1"></span>
        <input type="hidden">
        <input type="hidden">
      </div>`
