### ISSUE TITLE
Expanded row causes nested gutter issues

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#8126]
Using the "expanded" class on a row causes potential nested gutter issues.

http://codepen.io/christianmagill/pen/JGeeMw

**Comment by zawilliams** [comment]
Having the same issue. Had to create a custom expanded class that just has max-width set to none.

**Comment by JeremyEnglert** [comment]
I'm not seeing the issue in the provided CodePen link - in fact, I don't see 'expanded' being used at all on that link.

I'm going to close this for now. But if you believe the issue still exists, feel free to open it using the new "Issues Template": https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md

Thanks!
