### ISSUE TITLE
[Fix][Floats] float-center will be up over other classes

### ISSUE THREAD

**Issue by SalahAdDin** [zurb/foundation-sites#8133]
The case is simple:
![seleccion_087](https://cloud.githubusercontent.com/assets/5034215/12961662/b9a0d086-d00f-11e5-904e-c5a3e5a43068.png)
Float classes should have more important over other classes, because when we use this classes we want put the object with these float: center, right or left.

![seleccion_089](https://cloud.githubusercontent.com/assets/5034215/12961771/239fa854-d010-11e5-9431-53fee0af8f14.png)
Here is the finally result that one wait get it. So, i think that float classes, and more float-center, have to important in his display style.

Sorry if i wrote bad, i'm not english native speaker.

Thank you for your great work!

**Comment by andycochran** [comment]
`.float-center` makes me :confounded:.

**Comment by SalahAdDin** [comment]
It have less important than other objects, as .orbit:
![seleccion_091](https://cloud.githubusercontent.com/assets/5034215/12968701/7129f3e4-d043-11e5-8f6e-b76379051c53.png)

**Comment by gakimball** [comment]
Rearranging the order of your CSS exports might be a quick way to fix this.

Move `@include foundation-float-classes` below every other Foundation component so it comes last in the cascade.

**Comment by SalahAdDin** [comment]
And, yes, putting `@include foundation-float-classes` below of other components works fine :D

**Comment by gakimball** [comment]
Awesome! We encountered similar issues with the new flexbox utility classes, so it sounds like our approach needs to be to place all utility classes last in the cascade by default.

**Comment by SalahAdDin** [comment]
Thank you very much man.
