### ISSUE TITLE
 Sticky-Magellan, problem after "foundation.magellan.js 6.1.2" update

### ISSUE THREAD

**Issue by manolenso** [zurb/foundation-sites#8138]
Hi, maybe I missing something!
Sticky-Magellan doesn't work like before after foundation.magellan.js 6.1.2 update
I make an [codepen](http://codepen.io/manolenso/pen/eJbjYg)
I put the lib calling inside the html, so you can change to see

**Comment by pedzed** [comment]
Confirmed. I also noticed this issue after upgrading from `6.0.x` to `6.1.2`. Clicking a link just doesn't make the page scroll.

**Comment by manolenso** [comment]
yes, as you can see at the bottom of html I used magellan 6.1.1
change to 6.1.2, doesn't work

**Comment by manolenso** [comment]
I browsed the history and tried, it working well just before pushing `7a7e60` Convert magellan to ES6 class

**Comment by gakimball** [comment]
Are you seeing this in Firefox specifically, or in other browsers as well? May be a duplicate of #8056, which has been resolved in the `develop` branch.

**Comment by manolenso** [comment]
Hi, 
yes I tried Firefox and IE with the same bad result, I'll look at the `develop`  branch and trying with the last. and I'll look the #8056

**Comment by manolenso** [comment]
can I confirm that last functional version is the `07d4709` `updates docs for magellan`commit by Chris 10 days ago, after there are a lot of changes with the ES6 convert .
Thank's

**Comment by manolenso** [comment]
Pending update, this hack work in IE, Firefox and Chrome.  Thank to jvanv #8147
`function scrollToAnchor(aid){
    var aTag = $(aid);
    $('html,body').animate({scrollTop: aTag.offset().top},'slow');
  }
    $('.menu li a').click(function(){
        scrollToAnchor($(this).attr('href'));
});`

**Comment by manolenso** [comment]
resolved by 6.2.0 update.
