### ISSUE TITLE
F6 - Tooltip bugs

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#8144]
Check this codepen and you will see what I mean.

http://codepen.io/anon/pen/pgGjLR

**Comment by manolenso** [comment]
`<div class="has-tip[tip-left tip-bottom tip-left tip-left]" data-tooltip`?
Try something like the doc:
`<div class="has-tip left" data-tooltip aria-haspopup="true" data-options='show_on:medium' title="Foundation 6.1.2 Tooltip bug">
   <button class="button large">Hover me</button>
							</div>`

**Comment by Silvester20** [comment]
Yes that will work but I want to choose the tooltip directions just the way as in the codepen, which doesn't work.

**Comment by gakimball** [comment]
The class names don't have brackets, and you should pick just one of the directions.

**Comment by Silvester20** [comment]
Still no luck, seems the one which is not working has not enough space and that is why the tooltip is messed up in the codepen. But in my real project there is enough space and the tooltip is messed up too! What do you think?

http://codepen.io/anon/pen/GozmNO

ps: @gakimball thank you so much for working hard on Foundation!

**Comment by Silvester20** [comment]
Seems the team doesn't care much so here is a quick and dirty fix.

`.tooltip.left:before
{
	border-color: transparent transparent transparent #0a0a0a;
	border-left-style: solid;
	border-right-width: 0;
}`

`/* Small only */
@media screen and (max-width: 39.9375em)
{
	.tooltip.top:before, .tooltip:before
	{
		border-color: transparent transparent #0a0a0a transparent;
	}
}`

**Comment by Silvester20** [comment]
Problem still exists in 6.2.0. Here is a updated fiddle: http://codepen.io/anon/pen/dMOxJv

**Comment by Owlbertz** [comment]
Works for me if there is enough space to the top: 
![tooltip](https://cloud.githubusercontent.com/assets/4280373/13828158/716eb89c-ebc0-11e5-91a4-938f87330679.png)

But indeed, there should be a positioning fallback like there is for the dropdowns.

**Comment by kball** [comment]
@owlbertz Are these issues something you can dig into?  If not please assign back to me.

**Comment by Owlbertz** [comment]
Seems like the issue is gone in the latest version somehow... I was not able to recreate it in my local version and also it is gone after updating the Pen to the current build-state: http://codepen.io/Owlbertz/pen/ZWmzbr.

**Comment by Owlbertz** [comment]
@Silvester20 since you upvoted my last comment can I assume that you don't experience the issue anymore as well? If so I'd like to close this issue.

**Comment by Silvester20** [comment]
No problems anymore, can be closed indeed. Thanks for the hard work you guys doing!
