### ISSUE TITLE
[Off-canvas] Titlebar should close after click

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#8145]
I expect that the titlebar closes after I clicked on a link. But instead it stays on the screen. Maybe making it optional?

**Comment by gakimball** [comment]
Can you post a code sample?

**Comment by shoaibik** [comment]
@phifa do you want is for single page application?

**Comment by phifa** [comment]
yes. i am thinking of single page applications. Check out this page where I implemented the title bar in mobile use. 

http://www.bu-hohmann.de/

**Comment by gakimball** [comment]
The responsive toggle plugin is meant to be fairly generic, which is why it doesn't include options like this. However, you can implement the closing functionality very easily:

```js
$('.navmain__list__item').click(function() {
  $('.navmobile').foundation('toggleMenu');
});
```
