### ISSUE TITLE
Permission to zurb/foundation-zurb-template.git denied

### ISSUE THREAD

**Issue by evr01** [zurb/foundation-sites#8146]
Hi, I'm new to Git and I'm trying to use version control for one of my projects. When I try to do a git push, and after I insert my credentials, I receive this error: 

"remote: Permission to zurb/foundation-zurb-template.git denied to evr01.
fatal: unable to access 'https://github.com/zurb/foundation-zurb-template.git/': The requested URL returned error: 403"

Any reason why this would happen? Again, I'm a noob at this.

**Comment by gakimball** [comment]
That template points to our Git repo, which you don't have access to. You need to replace it with your own.

```bash
git remote remove origin
git remove add origin https://github.com/user/repo.git
```
