### ISSUE TITLE
[Reveal] [PC] Content Moves Right on Reveal Open

### ISSUE THREAD

**Issue by foodgy** [zurb/foundation-sites#8149]
Here is F6 Modal: http://foundation.zurb.com/sites/docs/reveal.html

On Reveal open event ```body``` tag gets ```.is-reveal-open``` class, which sets ```overflow: hidden```. But site content also moves to right for ~17px because of scrollbar disappearance.

And here is Bootstrap Modal: http://getbootstrap.com/javascript/#modals

On modal open event ```body``` gets extra 17px padding style which fits disappeared scrollbar.

Could we see something like this in future Reveal updates?
This is all about PC only.

**Comment by rafibomb** [comment]
@foodgy Seems like there are a few different things happening here. We started a conversation on the Reveal Modal and would love to hear your struggles with it and suggestions. http://foundation.zurb.com/forum/posts/38459-f6-reveal-modal-suggestions

**Comment by JeremyEnglert** [comment]
Same as https://github.com/zurb/foundation-sites/issues/7831.

Closing this out as the other thread has a few potential solutions for a fix.
