### ISSUE TITLE
Accordion events double-bound when added via reveal and another accordion already exists on page

### ISSUE THREAD

**Issue by spencercarnage** [zurb/foundation-sites#8151]
Recently upgraded to `5.5.3` and I found a bug that wasn't in the previous version we were using, `5.2.2`. The bug is caused when adding an accordion dynamically via a reveal modal to a page that already has an initialized accordion on it. It appears that click event to toggle the accordion's content is double-bound, causing the accordion to open and close from a single click.

<img width="560" alt="screen shot 2016-02-12 at 10 29 46 am" src="https://cloud.githubusercontent.com/assets/533990/13016561/5c138826-d174-11e5-86c9-f669f0634337.png">
 One listener is added to the `document` when the non-reveal accordion is initialized, while the second listener is added when the reveal modal calls `.foundation()` on it's children [here](https://github.com/zurb/foundation-sites/blob/v5.5.3/js/foundation/foundation.reveal.js#L230). I tried to call `.foundation('accordion', 'reflow')` but the accordion's `reflow` is a [noop](https://github.com/zurb/foundation-sites/blob/v5.5.3/js/foundation/foundation.accordion.js#L123).

To the user, it appears as if it's not working at all when really it's firing the event twice, causing it to open and close. Here's a gif of the click event firing twice.

![foundation-accordion-in-reveal](https://cloud.githubusercontent.com/assets/533990/13016626/cc67e5a4-d174-11e5-9c3e-60e6afa07cbd.gif)

Here's a codepen with a reduced test case: http://s.codepen.io/spencercarnage/debug/rxPWpV. 

I am more than happy to submit a PR with a fix but I'm fairly new with how Foundation works so any general guidance in that direction would help. I assume adding a proper `reflow` implementation to the accordion would be the way to go. In the meantime, I'll dig to see if I can figure something out between. Maybe version `6` has already addressed this and we can possibly back-port this. 

Thanks!

**Comment by spencercarnage** [comment]
Quickest fix I could find is adding `e.stopPropagation()` here https://github.com/zurb/foundation-sites/blob/v5.5.3/js/foundation/foundation.accordion.js#L37. I don't think that should break anything but I could be wrong.

**Comment by gakimball** [comment]
Fixed via #8165

**Comment by spencercarnage** [comment]
@gakimball When could we expect another public release to `5.*`?

**Comment by gakimball** [comment]
@spencercarnage Next month.

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/accordion-in-modal-foundation-5-5-3/2014/5
