### ISSUE TITLE
Ambiguous utility of _settings.scss file

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation-sites#8153]
Hello,

It's been my experience that while changing the values of SASS variables in the _settings.scss file works as expected, the effect of commenting out lines is surprising.

For instance, when I try commenting out all "code" variables ($code-*) and then compile, the pertinent style rules are still generated. However, if I comment out ```@include foundation-typography;``` from my main.scss file, then things do go as expected (sort of) -- those "code" block related style rules to not appear in the output file. Unfortunately, this also means that all typography related variables are not converted into stylerules.

Is this a known issue or just a case of miscommunication? And yes, I RTM :)

EDIT: grammar

**Comment by Deckluhm** [comment]
`_settings.scss` is just a way to override variables default values.

If you don't define them in `_settings.scss`, they are still defined in each module corresponding file 

For example, `typography` styles are defined in [`_typography.scss`](https://github.com/zurb/foundation-sites/blob/develop/scss/typography/_typography.scss) using `!default`.

From [Sass documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_), if you don't know what `!default` does:
> **Variable Defaults: !default**
>
> You can assign to variables if they aren’t already assigned by adding the !default flag to the end of the value. This means that if the variable has already been assigned to, it won’t be re-assigned, but if it doesn’t have a value yet, it will be given one.

**Comment by paxperscientiam** [comment]
Hi @Deckluhm 

So, if I understand you correctly, this isn't about SASS per se; it's about Zurb's implementation.

Given that variable defaults are set, the user *must* specify values in order to override said defaults. If this is the case, the docs should make it clearer.

Thanks.

**Comment by Deckluhm** [comment]
The Sass section of the documentation contains information about that:
- [Compiling Manually](http://foundation.zurb.com/sites/docs/sass.html#compiling-manually)
- [Adjusting CSS Output](http://foundation.zurb.com/sites/docs/sass.html#adjusting-css-output)
- [The Settings File](http://foundation.zurb.com/sites/docs/sass.html#the-settings-file)

Also, don't hesitate to read sources, they are fairly easy to read / understand and it helps you understand how things work.

**Comment by gakimball** [comment]
@Deckluhm covered everything very well, thanks! To reiterate a few things:

- The variables exist so you can override the core structural and visual styles we set. We try to have as few settings variables as possible, so you can spend less time learning our framework and more time building on top of it.
- CSS output is controlled by the various `@import` statements. You can see an example of a Sass entry file that properly imports Foundation in our [Sass template](https://github.com/zurb/foundation-sites-template/blob/master/scss/_settings.scss).
