### ISSUE TITLE
SCSS Compilation Error

### ISSUE THREAD

**Issue by dizzyluo** [zurb/foundation-sites#8154]
Upon compiling beta.css, which looks like this:

```
@import "bower_components/foundation-sites/scss/foundation";

@include foundation-everything;
```

I got an error in my terminal:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: beta.css:7:1: Unclosed block
```

EDIT: Commenting out this line  /scss/forms/_text.scss Line 102 fixes the issue

```
#{text-inputs()}, 
```

Is this just happening for me??

**Comment by SalahAdDin** [comment]
Which compiler are you using? Did you tried using `'foundation';` instead?

**Comment by gakimball** [comment]
Yep, need to know which Sass compiler, either Ruby or Libsass, and what version of the compiler.

We always test in the latest version of either compiler.

**Comment by colin-marshall** [comment]
@dizzyluo, I'm going to close this issue. If you are still experiencing this problem, feel free to reopen the issue with the requested information (which compiler).
