### ISSUE TITLE
[Tabs] How I can access Foundation.Tabs.selectTab() ?

### ISSUE THREAD

**Issue by timaschew** [zurb/foundation-sites#8158]
`Foundation.Tabs.selectTab` doesn't work. either it's a bug or the docs are not obvious.
If you write `Tabs.selectTab` then it looks like a static function where I don't need any instance of the tab.
Otherwise it should be lowercase at the beginning.

Anyway, I can only access to the constructor via `Foundation.Tabs`

http://foundation.zurb.com/sites/docs/tabs.html#selecttab

**Comment by gakimball** [comment]
Call plugin methods using the `.foundation()` jQuery method.

```js
$('#tabs').foundation('selectTab', param1, param2);
```

This is outlined in the [JavaScript overview](http://foundation.zurb.com/sites/docs/javascript.html#programmatic-use) of the documentation, but we don't make it super obvious in individual plugins. We'll work on improving that.
