### ISSUE TITLE
Navigation in Foundation Site

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#8159]
On the Foundation site, http://foundation.zurb.com/, you have a navigation at the top. Under the Docs menu item, you list the documentation links for each section. I have one problem. All of these use `target="_blank"` thus they all open in a new tab. 

This really bugs me (no pun intended). Can it please be changed to work like the rest of the menu (open in same window)? If I really want a new tab open, it's not hard to right click and open in new tab. 

I rarely want to keep the base landing page for Foundation open as I'm attempting to get into the documentation. 

I know this isn't a Foundation for Sites issues and but I thought this may be the best place to post this. 

I also know this is something very minor and more of a personal preference than a "bug" but I thought I would post it nonetheless. :) 

To be clear as to what I'm talking about, here is a screenshot: 

![doc-image](https://cloud.githubusercontent.com/assets/1938824/13031874/dd815a66-d299-11e5-9dee-f2288d403735.jpg)

**Comment by gakimball** [comment]
Agreed. I made the change, and it'll get deployed later today.

**Comment by Lynda333** [comment]
@gakimball - Thank you!
