### ISSUE TITLE
titlebar and topbar

### ISSUE THREAD

**Issue by karland** [zurb/foundation-sites#8161]
I am not sure, why the new F6 offers a `titlebar` and a `topbar` seperately. Both show similar .css classes apart from the hamburger icon. What is the principle and conceptual difference and why is this not integrated into a single topbar. I am happy to add a PR to the documentation once I understand the concept behind. Thanks.

**Comment by SalahAdDin** [comment]
If i'm not wrong in old version they are one single, i don't know why Zurb decide split it.

**Comment by gakimball** [comment]
@SalahAdDin They were separate in 5. There was [`.top-bar`](http://foundation.zurb.com/sites/docs/v/5.5.3/components/topbar.html) and [`.tab-bar`](http://foundation.zurb.com/sites/docs/v/5.5.3/components/offcanvas.html#advanced). The latter is specifically designed to be paired with off-canvas.

I think in the future we could merge the two components, but in the interest of keeping the codebase stable it likely wouldn't happen until the next major version.
