### ISSUE TITLE
Accordion Submenu not displayed correctly / Title-bar

### ISSUE THREAD

**Issue by thomas529** [zurb/foundation-sites#8167]
Hey,

I noticed that the title bar menu seems to be 'broken'. 

If I load the theme on a small screen (or a small browser window) and extend the submenu, the submenu is displayed horizontally:
![direct load](https://cloud.githubusercontent.com/assets/5512313/13054802/dca61d48-d40b-11e5-8912-21d8820bba04.png)

If I load the same page in a large window, resize the window below the small breakpoint, the submenu is display vertically (as expected).
![resize](https://cloud.githubusercontent.com/assets/5512313/13054849/17b2e664-d40c-11e5-9690-080f15d25b50.png)

It seems to be a problem somewhere around .menu.vertical > li { display: block }. If loaded in a small window the display property is set to table-cell. I tried tracking it don't but couldn't find anything. Working around the problem and adding "vertical" to the menu walker helped, but surely isn't "the solution".

Tested in safari and chrome on mac.

Anybody else got any ideas?

thanks in advance

**Comment by rafibomb** [comment]
Looking to dig into this, do you have the code you're using or a demo to share? Blank codepen http://codepen.io/rafibomb/pen/dGLqYj

**Comment by thomas529** [comment]
It's on my password protected dev server. Could I send you an E-Mail with the login?

**Comment by gakimball** [comment]
We just need enough HTML to recreate the bug. Doesn't need extra CSS (it would be better without extra CSS) or any real data.

**Comment by thomas529** [comment]
Problem was with the way the menu was generated. Fixed now, thanks anyway!
