### ISSUE TITLE
Dropdown menus instantiation

### ISSUE THREAD

**Issue by tapmodo** [zurb/foundation-sites#8170]
I don't know if this is a bug or a documentation issue. I spent several hours trying to figure out why my dropdown menus (copying the site example directly) looked like this:

![image](https://cloud.githubusercontent.com/assets/411162/13064568/0fad1d8e-d409-11e5-91ad-c8b76e0885e8.png)

Then I realized I need to manually instantiate them using

```
new Foundation.DropdownMenu($(['data-dropdown-menu']), {});
```

I thought this was the purpose of adding the `data-dropdown-menu` attribute. Am I missing something obvious, or does the documentation need to be more specific that adding Javascript code is necessary to get them to work?!

**Comment by gakimball** [comment]
Your JavaScript might not be initializing properly. Make sure you're calling `$(document).foundation()`. If that doesn't work, check to see if you have any console errors.

**Comment by kball** [comment]
Closing based on lack of response.  If you're still seeing this please reopen with info about how you are initializing the foundation javascript.
