### ISSUE TITLE
Conflict with prototype.js

### ISSUE THREAD

**Issue by svkarpovich** [zurb/foundation-sites#8172]
Hi,

There is a problem with interchange plugin. 
Prototype.js has added methods to array. And var "rules" has many keys, that we shouldn't use.
One screenshot you can see that i == 'each' - ERROR

![2016-02-16 13 00 09](https://cloud.githubusercontent.com/assets/1274165/13073333/27a522c8-d4af-11e5-93f1-d648f6422d80.png)

Please check that property is own.
`if (!rules.hasOwnProperty(i))
          continue;`

**Comment by colin-marshall** [comment]
Closed in #8686. Thanks @svkarpovich!
