### ISSUE TITLE
rem-calc() function in _settings.scss doesn't work

### ISSUE THREAD

**Issue by KevinLandsberg** [zurb/foundation-sites#8173]
Hello guys,

i have set up a new project using the foundation-sites framework v6.1.2 .
I did a copy of the latest _settings.scss file and pasted it into /src/app folder where you can find the app.scss file too. In the app.scss file i am importing the _settings.scss file and everything works fine.
If i uncomment and change some values in the _settings.scss file everything works except the rem-calc() function.
If i uncomment // $global-width: rem-calc(1200); to change the row-width of the grid too 600px, my browser tells me that the rem-calc() function doesnt work. The max-width of the row is still 1200px wide.
Do i have to load any helper functions before the _settins.scss file is imported or is it still a bug?
Can someone help me please?
Thanks ;)

**Comment by karland** [comment]
I understood that you want to build one big `app.scss` that includes F6 and your own styling.

First, have a look at the file `foundation.scss`. What happens there is that all the SASS-functions are imported by help of `@import 'util/util` first. `rem-calc()` for instance sits within `/util/unit`.

The next thing that happens in `foundation.scss` is that all components are imported and then a mixin is defined that includes of the imported components.

Now, if you want to import F6 into your `app.scss` you need to do the following (modify according to your paths.) 

```scss
@import 'foundation';
@import 'settings';
@include foundation-everything;
```
Thus, `foundation-everything` is based on the `settings.scss`.

You can later than in `foundation.scss` modify which components you want by commenting out all unnecessary components and includes. (Do the same for the js-components). Hope this helps.

**Comment by gakimball** [comment]
What @karland said. The settings file is importing the file `util/util`, which loads every helper function, including `rem-calc()`. Make sure you have that `@import` statement at the top of your file, *before* any of the functions are used.

**Comment by KevinLandsberg** [comment]
Now it works for me, thank you very much!

**Comment by gakimball** [comment]
Good to hear!
