### ISSUE TITLE
Abide custom validator seems to ignore pattern validation

### ISSUE THREAD

**Issue by Risto-Stevcev** [zurb/foundation-sites#8174]
I'm using Foundation 5.5.3 [abide](http://foundation.zurb.com/sites/docs/v/5.5.3/components/abide.html). The docs say:

> Additionally, if you are using a custom validator and specify an input type or a pattern on the input, Abide will check both when validating the input.

But when I try the example, it will validate `b.zurb.com`, although it says that Abide should check both the pattern and the custom validator when validating the input, and clearly it's not if `b.zurb.com` is validating.

It seems like when I include a custom validator it actually ignores the pattern validation. I tried using the `pattern="email"` attribute also and it still didn't work.

The example is:

``` html
<input type="email" data-abide-validator="isAllowed">
```

``` js
$(document).foundation({
  abide: {
    validators: {
      isAllowed: function(el, required, parent) {
        var possibilities = ['a@zurb.com', 'b.zurb.com'];
        return possibilities.indexOf(el.value) > -1;
      }
    }
  }
})
```

**Comment by kossmann** [comment]
I've discovered the same issue, any news on that?

**Comment by colin-marshall** [comment]
@Risto-Stevcev very sorry for the late response to your issue. We are moving on to Foundation 7, and there will be no more development or support for Foundation 5. I am closing this one out.
