### ISSUE TITLE
Flexbox Mode - Vertical Menu - Left Align?

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#8179]
I just installed 6.2 RC1 on a site that I'm developing. I have Flexbox mode enabled as I'm already using the flex grid. Ran into one issue that I assume is an easy fix, I'm just not sure of the class. 

I have a vertical menu (inside an off canvas, if that matters). When I updated the items went from being left aligned to center aligned. 

How do I fix this? I tried `align-left` on the `<ul>` tag but it didn't work. Here is my code: 

    <ul class="vertical menu" data-accordion-menu data-multi-open="false">
        <li><a href="/"><i class="ub ub-home-bts ub-fw"></i> Home</a></li>
        <li><a href="#"><i class="ub ub-info-large ub-fw"></i> Breed Info</a>
            <ul class="menu vertical nested">
            <li><a href="#">About Kerries </a> 
            	<ul class="menu vertical nested">
                	<li><a href="/introduction/faq">FAQ </a></li>
                    <li><a href="/introduction/description">Description </a> 
                    	<ul class="menu vertical nested">
                            <li><a href="/introduction/description">Description</a></li>
                            <li> <a href="/introduction/description-detail">Summary</a></li>
                            <li><a href="/introduction/bark">Bark</a></li>
                            
                            

If I add this CSS, I can solve the problem: 

    .vertical > li > a {
        align-items: left;
        justify-content: left;
    }

but is there a class to do this for me?

With this said, should any vertical menu be center aligned by default? I know the ability to center align is needed, but should it be the default setting? In my opinion, left align (or right if using rtl) should be the default for vertical menu items.

**Comment by gakimball** [comment]
Fixed! The issue was with some of the styles meant for icons leaking into the base menu styles.

**Comment by Lynda333** [comment]
Great! Thank You!
