### ISSUE TITLE
Media Object, in Flexbox Mode, Content Overflows 

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#8180]
Using 6.2 rc1 with flexbox mode enabled causes an issue with the media object. I have the following media object code: 

    <div class="media-object">
      <div class="media-object-section">
        <a href="#" class="thumbnail">
            <img src="/images/path-to-image.jpg"/>
        </a>
      </div>
      <div class="media-object-section">
        <p><a href="#">Mission</a> <small>10 February 2016</small></p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris cursus facilisis arcu hendrerit egestas. In rhoncus arcu in magna imperdiet condimentum. Fusce fringilla quis dolor vitae scelerisque. Phasellus vel blandit tellus, ac suscipit mi. Pellentesque rhoncus ante non metus vehicula rutrum.</p>
      </div>
    </div>

The paragraph in the media object section overflows the container. 

In Firefox (v45) it overflows but does wrap eventually, screenshot: 

![FF Screenshot](https://cloud.githubusercontent.com/assets/1938824/13097811/aed92a0a-d4e1-11e5-85b9-db7caa14d578.jpg)

In both Chrome (v48) and Edge (v25) the paragraph doesn't wrap at all and runs off the screen. 

I can fix the issue by changing the CSS some: 

This is the default: 

    .media-object-section {
        flex: 0 0 auto;
     }

Change to this: 

    .media-object-section {
        flex: 0 auto;
     }

I don't fully understand the flexbox properties yet (though I am learning!), so I don't know if that's the solution or if it's something else.

**Comment by gakimball** [comment]
Media Object is the only component that requires a change in markup to work in flexbox mode. You need to add the class `.main-section` to the middle section of the media object, to change its `flex` property.

This is pointed out in the documentation, but it's not very obvious, so I wrapped it in a callout: e59bc2c965ef807ec332de657a79093bfc8b634a

I'm going to test your fix, but cross-browser issues might prevent it from working. Older browsers that implement flexbox have a habit of setting different defaults for various flex values, so sometimes omitting a value gets you into trouble.

**Comment by Lynda333** [comment]
Yes, I missed that. Thank you for adding the callout. It works properly now. :)

**Comment by gakimball** [comment]
I tested your fix, and it doesn't work in Firefox if your media object has thumbnails, because Firefox has some wonky behavior with images inside of auto-sizing flex children. That behavior has been in place for a while in Firefox, but if it's ever fixed we could revisit your approach.

**Comment by Lynda333** [comment]
@gakimball - No worries! Thank you for checking. With `.main-section` I haven't had any problems so all is good. :)

**Comment by Lynda333** [comment]
@gakimball - This needs to be reopened and it is overflowing in IE 10 and 11 (Other browsers work fine.)

I tried changing this: 

    .main-section.media-object-section {
        -webkit-flex: 1 1 0;
        -ms-flex: 1 1 0;
        flex: 1 1 0;
    }

to this:

    .main-section.media-object-section {
        -webkit-flex: 1 1 auto;
        -ms-flex: 1 1 auto;
        flex: 1 1 auto;
    }
 
And it appears to solve the problem but I just don't understand flex enough to fully understand what I'm doing there. 

Is there a better solution?
