### ISSUE TITLE
Offcanvas panel alternative

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites#8183]
Not sure if this is a forum topic or here so chose here.

I saw a [Codepen](http://codepen.io/zurbchris/pen/adEJJg) by Chris a few weeks ago which I thought was fantastic and I think would be a great addition to the framework. Is there any plan to include this as a new component? If you did the only thing I'd say is it probably needs a new name so people don't confuse it with panels from v5 - save yourself some support headaches :smile:.

Would be great to know if this will get included, or if I should just add it myself.

**Comment by gakimball** [comment]
We don't plan on adding it to the core framework, but we should probably get it on [Building Blocks](http://zurb.com/building-blocks).
