### ISSUE TITLE
Sticky.destroy

### ISSUE THREAD

**Issue by tr33m4n** [zurb/foundation-sites#8185]
Hi there,

I'm trying to work out how to use the functions for Sticky plugin in F6... I have a menu that has data options set to make it sticky, however I need to "destroy" that functionality when a certain breakpoint is reached (because I cannot seem to find a way of setting stickyOn: small-only! Not small up).

I've tried daft things like instantiating a new Foundation.Sticky(jQuery('.element').destroy(), any help would be greatly appreciated (or indeed a way of setting a data option to show ONLY on small and not small up!

Cheers

**Comment by gakimball** [comment]
To call plugin methods, do this:

```js
$('#sticky-thing').foundation('destroy');
```

If it's a method with parameters, you can add them as extra parameters on the `.foundation()` function.
