### ISSUE TITLE
Off-canvas: Main content not always 100% in Chrome/Safari OSX

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#8186]
Take a look at this example
http://zurb.com/building-blocks/top-bar-with-off-canvas

If you resize the window in Chrome/Safari OSX so that the Iframe is around 820 there is a weird space that appears on the right hand side at some sizes. Firefox works as expected.

Using Foundation 6.2 RC1

**Comment by kball** [comment]
Not seeing this in the most recent version of the example, so going to close this.  Reopen if you're still seeing.
