### ISSUE TITLE
inline-list

### ISSUE THREAD

**Issue by allaniftrue** [zurb/foundation-sites#8187]
The [inline-list](http://foundation.zurb.com/sites/docs/v/5.5.3/components/inline_lists.html) sass file (`_inline-lists.scss`)is missing.

**Comment by brettsmason** [comment]
The inline list that was in version 5 was replaced with the menu component, specifically the [simple list](http://foundation.zurb.com/sites/docs/menu.html#simple-style).

**Comment by gakimball** [comment]
What @brettsmason said.

```html
<ul class="simple menu">
  <li>Text</li>
  <li><a>Link</a></li>
</ul>
```

**Comment by SalahAdDin** [comment]
Yes, i used it.
