### ISSUE TITLE
Foundation 6.1.2: Added Tag with jQuery doesn't work.

### ISSUE THREAD

**Issue by sklix** [zurb/foundation-sites#8188]
I tried to add a Foundation-Tab using jQuery with this code:

```js
$("#button1").click(function() {
   $("#example-vert-tabs").append('<li class="tabs-title"><a href="#panel7v">Tab 7</a></li>');
   $("#tab_content").append('<div class="tabs-panel" id="panel7v"><p>Test7</p></div>');
   $(document).foundation();
});
```

Complete demo file ist attached.

I got this warning, when I call `$(document).foundation();` a second time: "Tried to initialize tabs on an element that already has a Foundation plugin."

When I click on the new tab I got the followin error:

```
7123TypeError: undefined is not an object (evaluating '$tabLink[0].hash')
_handleTabChangefoundation.js:7122
(anonymous function)foundation.js:7059
dispatchjquery-2.2.0.js:4731
handlejquery-2.2.0.js:4543
```

[test.txt](https://github.com/zurb/foundation-sites/files/135835/test.txt)

**Comment by sklix** [comment]
This Bug is fixed/not a bug. See hiere: http://stackoverflow.com/a/36060286/1740863

**Comment by kball** [comment]
Closing based on last comment.
