### ISSUE TITLE
[Sticky] Anchor points not updating properly when set to an Accordion

### ISSUE THREAD

**Issue by siedentm** [zurb/foundation-sites#8191]
Description: There seems to be an update problem with Anchors when working with dynamic elements (Accordion in my case). I wanted to create a sticky sidebar anchored to an Accordion. After expanding an accordion tab though, the Anchor information did not get updated so after scrolling down, the sidebar stops at the old anchor point. The Anchor point information are getting updated once I change the browser window size and it works for the current Accordion Tab size. This should be solvable relatively quickly by updating the anchor points after the animation finishes.

Code: I attached the whole HTML as a txt
[test.txt](https://github.com/zurb/foundation-sites/files/136091/test.txt)
JS/CSS are the standard ones.

Recreation Process: Set sticky anchors to an Accordion

**Comment by gakimball** [comment]
You'll have to tell Sticky to recalculate its innards manually—the plugin can't automatically detect when its contents have changed.

You should be able to tap into the `up` and `down` events of the accordion, which fire when the animation is finished, and then run Sticky's `_calc()` method, which will recalculate the size of the container.

```js
$('#accordion').on('up down', function() {
  // The "true" parameter tells the plugin to recalculate its dimensions
  $('#sticky').foundation('_calc', true);
});
```

**Comment by Ahnzh** [comment]
i pasted it into the document and this did not solve the problem. I might have the time to look into this a bit later. Since i'm pretty new to foundation it might be a good opportunity to explore.

At least i found the events:
  ```
  /**
     * Fires when the tab is done opening.
     * @event Accordion#down
     */
    this.$element.trigger('down.zf.accordion', [$target]);
  };
```
```
 /**
     * Fires when the tab is done collapsing up.
     * @event Accordion#up
     */
    this.$element.trigger('up.zf.accordion', [$target]);
  };
```

**Comment by kball** [comment]
@colin-marshall @gehasia is this related to the sticky work you've been doing?

**Comment by colin-marshall** [comment]
@kball this was not related, but I can definitely make some visual tests for this.

**Comment by siedentm** [comment]
I was still planning to take a look at it but i've been short on time.

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
