### ISSUE TITLE
component.destroy() causes error on route change (Meteor)

### ISSUE THREAD

**Issue by merlinpatt** [zurb/foundation-sites#8196]
Whenever I change routes in Meteor, I get the below stack trace. From what I can tell, the error happens because the `destroy` call queued and then it is attempting to destroy a plugin which is no longer on the page. This is a huge problem because `Foundation._uuids` array is not being emptied and various nodes are still attached to the DOM

```
Exception in queued task: TypeError: Cannot read property 'constructor' of undefined
    at Object.Foundation.unregisterPlugin (http://localhost:3000/packages/zurb_foundation-sites.js?f0d625ccde0bd87f0af3d3f80f920d2e7cd06fe3:245:79)
    at Tooltip.destroy (http://localhost:3000/packages/zurb_foundation-sites.js?f0d625ccde0bd87f0af3d3f80f920d2e7cd06fe3:7925:16)
    at null.<anonymous> (http://localhost:3000/packages/merlin_foundation-blaze.js?063e3082187e3afe260f9d9941366a764e33e887:136:15)
    at http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:3338:22
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:3679:12)
    at fireCallbacks (http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:3334:12)
    at null.<anonymous> (http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:3440:5)
    at fireCallbacks (http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:1960:26)
    at Object.Tracker.nonreactive (http://localhost:3000/packages/tracker.js?7776276660c988c38fed448d8262b925dffb5bc3:615:12)
    at http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:1957:13
```

**Comment by merlinpatt** [comment]
@juliancwirko Any thoughts on this issue?

**Comment by juliancwirko** [comment]
Do you check if the element still exists before destroing it? Like here: https://atmospherejs.com/zurb/foundation-sites#javascript-part

Hard to say with only this stack trace. 
Could you provide some kind of reproduction repo or code examples?

**Comment by merlinpatt** [comment]
Yeah, I check if the element exists as recommended but it still happens. I think it's because the `destroy` call is being queued.

**Comment by juliancwirko** [comment]
Foundation's component `destroy()` should be fired when a Meteor template is destroyed, maybe the template is not destroyed when you change the route. In that case you need to do this on route change. You can check if the template is destroyed by adding a simple console.log in the onDestroyed hook and then change the route. See if there will be a console.log message.

**Comment by merlinpatt** [comment]
The template's definitely being destroyed on route change. What I was attempting to do was create a block helper that would handle creating, rendering, and destroying for me so I wouldn't have to repeat code for every single Foundation plugin instance. And for some reason, that caused the issue. For now, I'll handle them directly.

**Comment by SierraGolf** [comment]
Hey, I have the same problem. I am using: `zurb:foundation-sites@6.1.1` 
In my case I have a self-contained template 

```xml
<template name="RevealTemplate">
    <div id="someId" class="reveal" data-reveal>
        ...
    </div>  
</template>
```

with the following javascript
```js
Template.RevealTemplate.onCreated(() => {
    const template = Template.instance();
    template.autorun(() => {
        const hasSomeData = !!template.data.someData.get();

        if (hasSomeData && !template.open) {
            template.modal.open();
            template.open = true;
        }
        if (!hasSomeData && template.open) {
            template.modal.close();
            template.open = false;
        }
    });
});

Template.RevealTemplate.onRendered(() => {
    const template = Template.instance();
    const $container = $('#someId');
    template.modal = new Foundation.Reveal($container);
    $container.on('closed.zf.reveal', () => template.open = false);
});

Template.RevealTemplate.onDestroyed(() => {
    const template = Template.instance();
    template.modal.destroy();
});
```

I created this "component" because I am re-using the same modal in 2 places. The respective parent templates embedding the above template just passes in the reactive data and depending on wether the given data is truthy, it opens or closes the modal.

I observed that when the parent is destroyed (which happens before the child is destroyed), e.g. on route change, it messes up the child template so that a destroy call to a reveal object in the child template fails. To be more precise the `Reveal` object is not present on the data object of the element anymore. Since the `unregisterPlugin` method uses the `Reveal` object just to get the string `reveal` in order to remove the data property from the element and send the correct destroyed event, I could hack this by changing the `onDestroy` handler to the following:

```js
Template.RevealTemplate.onDestroyed(() => {
    const template = Template.instance();
    const Reveal = () => {};
    template.modal.$element.data('zfPlugin', Reveal);
    template.modal.destroy();
});
```

I am not sure if this is a foundation or meteor bug.
