### ISSUE TITLE
foundation.js isn't working

### ISSUE THREAD

**Issue by emcyborg** [zurb/foundation-sites#8202]
Foundation.js isn't working of version 6.1.2. But when I put the foundation.js of version 6.1.1 it works fine.

**Comment by gakimball** [comment]
What exactly isn't working? Do you have any errors in your browser console?

**Comment by emcyborg** [comment]
No it has no errors in the console but it isn't working ... I put the standard code in app.js which is $(document).foundation();

**Comment by gakimball** [comment]
What plugins do you use? And what functionality of those plugins doesn't work? We'll need to get more specific to figure out why this isn't working.
