### ISSUE TITLE
Some Issues on Windows 10

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8205]
So i tried to update to 6.2 on my windows machine and i get the error babel-runtime not installed i had to add it manually to the package.json file
```
"babel-runtime": "^6.3.13",
```
trie to compile the docs i get the following errors an warnings
```
Error in plugin 'sass'
Message:
    scss\settings\_settings.scss
Error: File to import not found or unreadable: util/util
       Parent style sheet: C:/gitprojects/foundation-sites/scss/settings/_settings.scss
        on line 43 of scss/settings/_settings.scss
>> @import 'util/util';
   ^

[21:42:51] Finished 'sass:foundation' after 6.73 s
Error in plugin 'sass'
Message:
    scss\settings\_settings.scss
Error: File to import not found or unreadable: util/util
       Parent style sheet: C:/gitprojects/foundation-sites/scss/settings/_settings.scss
        on line 43 of scss/settings/_settings.scss
>> @import 'util/util';
   ^
```
and 
```
» [WARNING] @return must at least have a type. Location: _value.scss:96:101
```

**Comment by gakimball** [comment]
Are you trying to upgrade a ZURB Template project? You say "compile the docs" but the docs should be compiling fine right now.

**Comment by designerno1** [comment]
```
npm start
```
right now i also cant npm start v6.2.0-rc.1 error
```
Error in plugin 'sass'
Message:
    scss\settings\_settings.scss
Error: Undefined variable: "$primary-color".
        on line 140 of scss/settings/_settings.scss
>> $anchor-color: $primary-color;
   ---------------^
```
and
```
» [WARNING] @return must at least have a type. Location: _value.scss:96:101
```
and
```
fs.js:540
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:540:11)
    at OpenReq.process (C:\gitprojects\foundation-sites\node_modules\mocha\node_modules\graceful-fs\graceful-fs.js:55:16)
    at OpenReq.Req (C:\gitprojects\foundation-sites\node_modules\mocha\node_modules\graceful-fs\graceful-fs.js:126:8)
    at new OpenReq (C:\gitprojects\foundation-sites\node_modules\mocha\node_modules\graceful-fs\graceful-fs.js:49:7)
    at Object.open (C:\gitprojects\foundation-sites\node_modules\mocha\node_modules\graceful-fs\graceful-fs.js:41:3)
    at Object.fs.writeFile (fs.js:1137:6)
    at C:\gitprojects\foundation-sites\node_modules\foundation-docs\lib\buildSearch.js:136:8
    at C:\gitprojects\foundation-sites\node_modules\foundation-docs\node_modules\mkdirp\index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
```

maybe it's anissue on win10 or on my specific maschine

**Comment by gakimball** [comment]
- For the settings file error: the settings file has been updated so that shouldn't happen.
- For the SassDoc warning, fixed that: 71b669aad3c9c9ecb13843b861fc423999d2d501
- For the `path must be a string warning`, try updating a few of the framework dependencies:
  - `npm install zurb/foundation-docs`
  - `npm install supercollider`

**Comment by designerno1** [comment]
i did ```npm update```
dosn't this the same as npm install supercollider?

**Comment by gakimball** [comment]
It should, but I guess I never know how `npm update` is going to behave—I've never been totally clear on what exactly it does and when.

But as long as the dependencies for `foundation-docs` and `supercollider` are up to date, the documentation should compile just fine.

And that "can't import" error for `util/util`, are you still getting that?

**Comment by designerno1** [comment]
no errors now but i have to manually add
```
"babel-runtime": "^6.3.13",
```
to the package.json file on my windows 10 PC
