### ISSUE TITLE
[Error] breakpoint(... down) wrong?

### ISSUE THREAD

**Issue by di5abled** [zurb/foundation-sites#8208]
Given I have the following scss:
```
@include breakpoint(mobile) {
    color: #000;
}

@include breakpoint(mobile down) {
    color: #111;
}
```

The generated css looks like this:
```
@media screen and (min-width: 28.125em) {
    color: #000; 
}

@media screen and (max-width: 39.9375em) {
    color: #111; 
}
```

But in my understanding this is not "mobile down". Instead this is the next greater breakpoint down, so all "large" screens also already get this styles!?

I think booth media queries should have the same value of: `28.125em`

**Comment by Ne-Ne** [comment]
Have you tried mobile only?

**Comment by di5abled** [comment]
Nope, but the `only` keyword wouldn't be a fix for this. 
There are cases where I want to style someting `large down` and not `large only`.

**Comment by gakimball** [comment]
`mobile down` means "mobile *and* down". This is a holdover from Foundation 5's `-down` CSS classes, which meant the same thing.

I'd encourage you to write your media queries entirely mobile first if possible, which negates the need for `only` and `down` ranges for the most part.

**Comment by di5abled** [comment]
We try to not use it where possible, but somtimes we have the usecase :)

But when we know that it means `mobile AND down`, which isn't that clear by the docu in my mind, I'm happy ;)

**Comment by lsmatovu** [comment]
I agree. The documentation on what `down` means could actually be better. I just banged my head on why my custom breakpoint wasn't working.

I had ...

```
$breakpoints: (
  small: 0,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
  menu: 1000px,
);
```

I was trying `#{breakpoint(menu down)` and was super confused why it wasn't working.
