### ISSUE TITLE
Positioning the Menu Icon 

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#8210]
When using the Title bar with the following code: 

    <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
        <button class="menu-icon" type="button" data-toggle></button>
        <div class="title-bar-title">Menu</div>
     </div>

The problem I have is I can right align the menu icon. The only way I can move it is to take the `.menu-icon::after` class and manually adjust the `left` property. Of course, this isn't desired. 

How do I right align the menu icon? Please provide a simple way to do this.

Note: The site is not a right to left site, the menu is just right aligned.

**Comment by gakimball** [comment]
If the `.menu-icon` is going to come first in the markup, presumably you'd either need to use `float: right` or `position: absolute`.

**Comment by Lynda333** [comment]
@gakimball - Sorry for my delay in replying. `float` doesn't effect the icon at all. But after doing a bit more digging, I found the issue: 

I'm using flexbox and the `.title-bar` has `display:flex`. The moment I remove that style, the icon will float right as intended. 

How do I solve this issue? Is there an flex align class I can use?

**Comment by gakimball** [comment]
You can use a [vertical alignment class](http://foundation.zurb.com/sites/docs/flexbox.html#vertical-alignment) on the title bar to change around the alignment of things.

**Comment by Lynda333** [comment]
I believe I have this figured out now.

**Comment by anthonymidili** [comment]
Can you post your code please?
