### ISSUE TITLE
$gutter parameter in flex-grid-column mixin errors when zero

### ISSUE THREAD

**Issue by designerdean** [zurb/foundation-sites#8214]
In Version 6.2.0 RC1, this:

`@include flex-grid-column($gutter: 0);`
or
`@include flex-grid-column(4, 0);`

results in "Invalid null operation" error.

<img width="586" alt="screen shot 2016-02-22 at 11 04 20 am" src="https://cloud.githubusercontent.com/assets/729893/13227477/1184704e-d954-11e5-8fc6-2aa3b463e5c6.png">

**Comment by gakimball** [comment]
Fixed in the `6.2-stable` branch: e923b87f8d6e29791e9051a464fb705319a3d50f

**Comment by gakimball** [comment]
Never mind, you meant the *flex* column mixin ;) Here's a fix for that: 979e2a94e893638d5b8199dc29b5c5527403ff59

**Comment by designerdean** [comment]
Now it's acting as though the flex-order mixin doesn't exist.

<img width="713" alt="screen shot 2016-02-24 at 9 57 14 am" src="https://cloud.githubusercontent.com/assets/729893/13293526/3b3be05e-dadd-11e5-8a5a-b3be4c49ef14.png">

**Comment by designerdean** [comment]
Thanks for the commits. After implementing those, I'm getting this error. Any idea what's up?

<img width="546" alt="screen shot 2016-02-24 at 10 54 43 am" src="https://cloud.githubusercontent.com/assets/729893/13295219/0d1f1fda-dae5-11e5-8844-0395147ecb25.png">

**Comment by gakimball** [comment]
Hm, that's going to happen anywhere a responsive gutter definition is accidentally applied to CSS. `$grid-column-gutter` can now either be a number (for one global gutter) or a map (for responsive gutters). Looking into it!

**Comment by designerdean** [comment]
Thanks, @gakimball!

**Comment by designerdean** [comment]
It looks like I was using $grid-column-gutter as a variable and not a sass map. Once I changed that it worked. Not sure it it was supposed to be working like that before or not.

![screen shot 2016-02-24 at 1 30 55 pm](https://cloud.githubusercontent.com/assets/729893/13299977/f865c97a-dafa-11e5-96ba-111f5b1c5c33.png)
