### ISSUE TITLE
Sass for Block Quote

### ISSUE THREAD

**Issue by fallen-rve** [zurb/foundation-sites#8216]
A **question** and a **possible issue**:
Should the **p** be a **q**?
Line 397 in foundation-sites/scss/typography/_base.scss

blockquote {
    margin: 0 0 $paragraph-margin-bottom;
    padding: $blockquote-padding;
    border-#{$global-left}: $blockquote-border;

    &, p { /*HERE*/
      line-height: $paragraph-lineheight;
      color: $blockquote-color;
    }
  }

Thanks!

**Comment by gakimball** [comment]
It's intentional: it's meant for `<p>` tags used inside of block quotes. I'm not sure if you can combine `<q>` and `<blockquote>`, since they're block/inline versions of the same thing.

**Comment by fallen-rve** [comment]
Alright awesome, thanks!

I suppose I should have checked what it compiled first ( I'm learning this sass thing for the first time xD ).

Thanks again.
