### ISSUE TITLE
Drilldown Menu change Heights like Foundation 5?

### ISSUE THREAD

**Issue by KTPH** [zurb/foundation-sites#8217]
In foundation 5 the dropdown menu would change heights to fit whatever amount of links were in the menu, so 3 links would be for example 150px height dropdown, then if the next submenu was 6 links it would expand the height to fit the 6 links for example 500px.

Go here on your phone or make your browser narrow to see what I am referring to, I tried CSS solutions but in Foundation 5 it worked by applying a height dynamically using javascript. 

Curious what the reason for the change is, still love this menu but miss the dynamic height changing/

http://foundation.zurb.com/sites/docs/v/5.5.3/components/topbar.html  (Old menu that changed heights)

Thanks. Let me know if I can clear anything up.

**Comment by KTPH** [comment]
OK still trying to get this to work. Definitely no CSS solution as the way to dynamically change the height of the drilldown menu based on how many elements are in it seems to be a javascript only solution. If anyone knows where to adjust the code in the core files, it would be great to have this added, possible a data-option to dynamically change the drilldown heights.

**Comment by hp7** [comment]
I am having a similar issue this somewhat fixed it
div.is-drilldown {
height:auto;
}

However the the hidden nested menus still take up layout space, so the largest nested menu will push other elements down the page even when it is hidden

**Comment by gakimball** [comment]
Closing in favor of #7821. We've gotten a number of requests for this feature now, so it's looking more and more like something we'll want to implement.
