### ISSUE TITLE
Using grid-column mixin with zero value for gutter causes Invalid null operator

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#8220]
Using the grid-column mixin with a zero value for gutter causes an invalid null operator error.

`
Invalid null operation: "null plus "2"".
        on line 130 of stdin
>>     @include grid-column(5, 0px);
`

Using 6.2 RC 1

**Comment by gakimball** [comment]
Fixed in the `6.2-stable` branch: e923b87f8d6e29791e9051a464fb705319a3d50f
