### ISSUE TITLE
[Drilldown Menu] Hidden menu takes up layout space

### ISSUE THREAD

**Issue by hp7** [zurb/foundation-sites#8223]
**How can we reproduce this bug?**
See sample drill down menu example page

1. Step one
right click the extra space below the drill down menu and Inspect elements.
The menu takes up the space of the tallest hidden nested menu. These hidden elements should not be in the layout taking space.

This screen shows the space taken up
![screen shot 2016-02-23 at 10 55 16 am](https://cloud.githubusercontent.com/assets/786681/13257568/600297e0-da1d-11e5-8088-d38e0aaabc54.png)

This screen shows using the drill down menu in a grid with absolute position which takes it out of layout, but the links under the drilldown menu area will Not work since the nested menu elements are still covering the layout.
![screen shot 2016-02-23 at 11 16 28 am](https://cloud.githubusercontent.com/assets/786681/13257932/ef350e88-da1e-11e5-83de-bb4bc2b4ea4d.png)

**What did you expect to happen?**
Drill down menu hidden nested menu is Not obstructing the layout at all. When active the nested menu slide out over the layout related to the the parent position.

**What happened instead?**
Drill down menu take up full height of hidden nested menu

**Test case**
http://foundation.zurb.com/sites/docs/drilldown-menu.html
http://codepen.io/anon/pen/pgMPdP

**Comment by gakimball** [comment]
Closing in favor of #7821. We've gotten a number of requests for this feature now, so it's looking more and more like something we'll want to implement.
