### ISSUE TITLE
[Forum] Sort search results feature

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#8225]
Search results on http://foundation.zurb.com/forum/ are always sorted by relevance. With no option to sort search results by recent activity or creation date, it makes it difficult to find threads about issues/bugs that come up in the most recent versions of Foundation.

**Comment by gakimball** [comment]
Paging @rafibomb

**Comment by colin-marshall** [comment]
And one more forum issue. The added "Login" option to the navigation menu on forum pages makes the page a little messed up when viewed on tablets.

![screen shot 2016-02-23 at 12 59 29 pm](https://cloud.githubusercontent.com/assets/4453733/13265044/275881b4-da2e-11e5-8037-ef731956a7dd.png)

**Comment by colin-marshall** [comment]
I expect we will be using a new forum platform in the near future, so I'm going to close this out.
