### ISSUE TITLE
Backslash is not removed from form input selectors

### ISSUE THREAD

**Issue by shoaibik** [zurb/foundation-sites#8230]
I am including Foundation sass files in my project and the form input styles are not working. I found that the css has backslashes in it that's why selector is not working.
```css
[type=\'text\'], [type=\'password\'], [type=\'date\'], [type=\'datetime\'], [type=\'datetime-local\'], [type=\'month\'], [type=\'week\'], [type=\'email\'], [type=\'number\'], [type=\'search\'], [type=\'tel\'], [type=\'time\'], [type=\'url\'], [type=\'color\']
```

In the `util/_selector.scss` file if I change the code
```scss
@each $type in $types {
    $return: append($return, unquote('[type=\'#{$type}\']'), comma);
}
```
to 
```scss
@each $type in $types {
    $return: append($return, unquote('[type="#{$type}"]'), comma);
}
```
it works.

and in the `foundation.css` in the `dist `folder it has correct code
```css
[type='text'], [type='password'], [type='date'], [type='datetime'], [type='datetime-local'], [type='month'], [type='week'], [type='email'], [type='number'], [type='search'], [type='tel'], [type='time'], [type='url'], [type='color']
```

I am using it with the latest grunt and grunt-sass

**Comment by gakimball** [comment]
To verify, is it grunt-sass 1.1.0? We're using the latest version of Libsass to compile and not seeing the same behavior.

**Comment by shoaibik** [comment]
grunt-sass was earlier than 1.1.0, I have updated to 1.2.0-beta and the issue is resolved, also when I updated their is issue with libsass 3.3.3 similar to #7602 
```
media query expression must begin with '('
```
but with libsass 3.3.2 it works.
