### ISSUE TITLE
Sticky doesn't move with open off-canvas in IE10

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#8234]
In Internet Explorer 10, if an off-canvas menu is opened while a Sticky sidebar is in "stuck" mode, the sidebar doesn't shift with the rest of the page. This doesn't happen in IE9 or IE11.

![image](https://cloud.githubusercontent.com/assets/1142001/13295963/2096b032-dae0-11e5-8841-ec3c681ddce5.png)

**Comment by kball** [comment]
@colin-marshall @gehasia  is this something you can look at in your work with sticky?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
