### ISSUE TITLE
Hoverable dropdowns can't be closed in iOS

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#8235]
In IOS 9, a hoverable dropdown can be opened by tapping its trigger, but not closed.

**Comment by HanlonCreative** [comment]
Agreed also experiencing this issue, my data options are:

` <ul class="dropdown menu" data-dropdown-menu data-options="disableHover: true;clickOpen: true;" >
`

**Comment by kball** [comment]
I believe this was resolved with https://github.com/zurb/foundation-sites/pull/9174
