### ISSUE TITLE
[Tables] row stripes via class

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#8237]
Should the default style of table rows be striped? Seems like it'd be more useful as a `.striped` class, so it'd work just like `.hover`. 

As-is, if you want some (not all) tables striped, it takes a bit of custom work. 

I propose we ~~add `border-bottom: $table-border` to rows, remove the `border-bottom` on the table, and move the `:nth-child` styles to a `.striped` class~~ add a `$table-is-striped` variable that, if set to `true` creates an .unstriped class, and if set to `false` creates a .striped class. 

If :+1:, I'll PR.

**Comment by erutan** [comment]
It feels like a good default thing to have, e.g. more tables would be striped rather than not. Instead of having to add declarative styles anywhere, perhaps just a `.un-striped` class that could be applied to a `<table>` element that would disable striping for that particular one?

**Comment by andycochran** [comment]
@brettsmason Any thoughts on this?

**Comment by brettsmason** [comment]
@andycochran my preference would be to not have the table striped by default. Its only going by personal experience, but a lot of clients I've worked with have wanted plain tables.

I agree though a striped class would be useful and the way to implement you suggested makes sense. I'd say go for it :smile:

**Comment by kball** [comment]
In order to not change default behavior and not create migration headaches for folks, I'd prefer we go with @erutan's suggestion.

**Comment by andycochran** [comment]
What about a `$table-striped` variable that, if set to `true` creates an `.unstriped` class, and if set to `false` creates a `.striped` class?

**Comment by kball** [comment]
I'm okay with that, my main priority with this is to minimize migration headaches.  If we default to today's behavior and have a variable to change the defaults, that satisfies my desires.

**Comment by kball** [comment]
Addressed in #8656.  This will be in 6.3
