### ISSUE TITLE
[grid] grid-column-unposition

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites#8238]
I'm not 100% sure I'm using this correctly, but I'm trying to do this:

```
.site-branding {
	@include grid-col(6);
	@include grid-column-position(center);

	@include breakpoint(medium) {
		@include grid-column-size(8);
	}

	@include breakpoint(large) {
		@include grid-column-size(3);
		@include grid-column-unposition();
	}
}
```

I was trying to have a small centered logo on small/medium and a smaller logo floating left on large. I expected `grid-column-unposition` to reset the position but it doesn't appear to add the float back. Am I using this correctly or is this a bug?

**Comment by gakimball** [comment]
This is fixed in the `develop` branch: 34cb85622e459cae13aea90252a54fe8a18dc81d

We're releasing Foundation 6.2 on Friday, which will include this fix.
