### ISSUE TITLE
[Menu] + Color Classes vs [Button Group]

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#8239]
It would be rad if you could add classes from the `$foundation-colors` map to get colored menus. Menus would then make button groups redundant. 

@rafibomb, I know there's some thought going into [clarifying Responsive Menus, docs, migration, etc](http://foundation.zurb.com/forum/posts/38403-). This conversation might consider: 
* When does it make sense to use `.button-group` instead of `.menu`? 
* How is a `.stacked-for-small.button-group` different than a `.vertical.medium-horizontal.menu`? 
* Does FS6 need both?

**Comment by erutan** [comment]
Someone could be using `<button>` elements inside a `.button-group` at which point it's useful to have both (the docs just use anchor links, which makes it a purely visual distinction). Having say save and exit, don't save and exit, and cancel buttons next to each other, etc. 

I suppose semantically having button elements inside a menu of options would make sense though, given you'd always be choosing between related options in a given context.

**Comment by andycochran** [comment]
Semantically, I don't see a problem with `<button>` elements inside a `.menu`. A group of buttons is a menu. One component could serve both functions: a set of links and/or buttons styled various ways. 

The Button Group component seems like an unnecessary holdover from F5. 

It could be as simple as adding the `.button-group` class to `.menu` to get a Menu styled like a Button Group—even without having to add the `.button` class to every item.

**Comment by erutan** [comment]
Yeah, most of time it wouldn't be a navigational menu, but a menu of actions/options available, which seems reasonable to me. I'm not sure I see the need for both, unless it's just for intuitiveness / discoverability.

**Comment by kball** [comment]
@andycochran are you still noodling on this?

**Comment by andycochran** [comment]
Yeah, but I'll close it. It's not really a bug. More of a feature request w/ a splash of existentialism.
