### ISSUE TITLE
classes are missing in .min css

### ISSUE THREAD

**Issue by ve3** [zurb/foundation-sites#8242]
I was downloaded from http://foundation.zurb.com/sites/download.html/ in both Complete and Custom section.
The file foundation.min.css don't have some classes.
From currently known:
.dark, .top-bar-title

Please check and fix.

**Comment by shoaibik** [comment]
I can confirm that it does NOT exist, although it exists when foundation is installed via bower.

**Comment by gakimball** [comment]
We're having some issues with the customizer right now, which we're working to resolve. I'm going to roll this into #7033, where we're tracking all issues with the customizer.

**Comment by ve3** [comment]
It is both "Complete" and "Custom" not just "Custom" download.
