### ISSUE TITLE
Scale .callout.large on mobile

### ISSUE THREAD

**Issue by codymorgan** [zurb/foundation-sites#8244]
Currently the .callout.large class applies a deafault of 3rem of padding to the callout regardless of screen size. This translates to around 200 pixels of column width on a 320px wide screen.Would it be advisable to change this class to only apply to medium and up sized screens?

**Comment by gakimball** [comment]
Good point—it's more or less designed for prototype-y hero units, and heros aren't going to have that much padding on mobile.

**Comment by kball** [comment]
@JeremyEnglert can you tackle this?

**Comment by JeremyEnglert** [comment]
No problem. I'll replicate the issue to make sure it hasn't already been fixed and submit a PR if it hasn't.

**Comment by JeremyEnglert** [comment]
So this would be super easy to fix - but I guess it goes back to is it an actual bug or will some people want it to function like this? It doesn't look horrible. See attached.

I think a better solution would be something similar to how the responsive gutters work. `$callout-padding` could become a Sass map variable so padding sizes could be declared for specific breakpoints. 

Or am I overthinking this?

@zurb/yetinauts - thoughts? 

![screen shot 2016-04-28 at 4 40 34 pm](https://cloud.githubusercontent.com/assets/6110968/14904814/0ff8ae8a-0d60-11e6-9d85-248135f7ece5.png)

**Comment by kball** [comment]
I think the defaults are probably not quite right for mobile, but I like the direction of moving to a responsive map-based appraoch.

**Comment by brettsmason** [comment]
I'm happy with the idea of a Sass map if everyone agrees thats the correct approach. It adds more flexibility without too much more complication or code.

**Comment by andycochran** [comment]
:+1: Drop the large class, use a map for callout padding.

**Comment by colin-marshall** [comment]
Sounds like we're all in agreement on the map. I guess the next order of business would be to decide what should we set as the default padding for each breakpoint.

**Comment by andycochran** [comment]
Maybe small as-is, medium and large based off gutter sizes? 

```scss
$callout-padding: (
  small: 1rem,
  medium: rem-calc(15),
  large: rem-calc(30),
);
```

**Comment by mavam** [comment]
@andycochran I was trying to paste your example into my SCSS file, but it doesn't have any effect. I'm using Foundation 6. How can I make this work?

**Comment by markadrake** [comment]
You'll have to excuse me since I'm not 100% familiar with the framework. So if control over padding between breakpoints is a concern for this component, is it fair to assume all of these others need to be updated too?

![image](https://cloud.githubusercontent.com/assets/713355/19200320/694ee50c-8c96-11e6-8bd1-dc4996dbf9e6.png)

- Badge Padding
- Code Padding
- Blockquote Padding
- Keystroke Padding
- Button Padding
- (This) Callout Padding
- Accordion Content Padding
- Topbar Padding
- Dropdown Padding

And is there not a global padding that can simply be applied anywhere? 

Just want to make sure that this solution is carried through to the rest of the framework if it has not already been discussed.

**Comment by andycochran** [comment]
@mavam This code wasn't meant to work. Sorry that wasn't clear. I was suggesting how a map of callout padding might look. You could paste something like this into your code… 

```sass
.callout (
  padding: 1rem;
  @include breakpoint(medium) {
    padding: rem-calc(20);
  }
  @include breakpoint(large) {
    padding: rem-calc(40);
  }
);
```

**Comment by mavam** [comment]
Thanks, this did the trick just fine!

**Comment by colin-marshall** [comment]
@JeremyEnglert I'll let you decide the fate of this issue since you had some prior involvement.

**Comment by DanielRuf** [comment]
What is the current status?

**Comment by ncoden** [comment]
Callout padding was fixed for https://github.com/zurb/foundation-sites/pull/11084. For small inline components there is no point on adding responsive paddings as their content is displayed the same way across devices. But we could add them for Blockquote, Accordion content or Dropdown

**Comment by DanielRuf** [comment]
Closing as https://github.com/zurb/foundation-sites/pull/11084 should fix this.
