### ISSUE TITLE
[Top Bar] ISSUE NAME HERE

### ISSUE THREAD

**Issue by cjburkey01** [zurb/foundation-sites#8246]
**How can we reproduce this bug?**

1. Try to create a menubar with a vertical dropdown menu.

**What did you expect to happen?**

* The vertical dropdown menu to not be shown by default as part of the menu.

**What happened instead?**

* The vertical dropdown menu displayed as part of the menu.

**Test case**

[Here](http://codepen.io/anon/pen/eZOrxJ)

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by gakimball** [comment]
You aren't turning on the Foundation JavaScript in your CodePen. If I add `$(document).foundation()` to the JavaScript section of the CodePen, the menu works fine.
