### ISSUE TITLE
The top position of the dropdown isn't correct in RTL mode

### ISSUE THREAD

**Issue by abdullahsalem** [zurb/foundation-sites#8248]
#7928 #8247 #7560

**Comment by gakimball** [comment]
This is in 6.1.2 or 6.2?

**Comment by abdullahsalem** [comment]
I pulled it from 6.2-stable!

**Comment by abdullahsalem** [comment]
@gakimball I think this issue should be labeled as **scss**

**Comment by abdullahsalem** [comment]
@gakimball I would be grateful, if you take a look at this PR #8247.

**Comment by gakimball** [comment]
Merged #7928 and #8247. Thanks @abdullahsalem!
