### ISSUE TITLE
Zurb Template based site, upgraded from 6.12 to 6.2. Gulp choking on $foundation-palette

### ISSUE THREAD

**Issue by erutan** [zurb/foundation-sites#8253]
If I place `@include add-foundation-colors;` at the bottom of the global section in `_settings.scss` below `@import 'util/util';` I get the following.

```
Error in plugin 'sass'
Message:
    bower_components/foundation-sites/scss/util/_color.scss
Error: Undefined variable: "$foundation-palette".
        on line 45 of bower_components/foundation-sites/scss/util/_color.scss
>>   @if map-has-key($foundation-palette, primary) {
   ------------------^
```

For kicks I added it above `@import 'util/util';`, which doesn't work either:

```
Error in plugin 'sass'
Message:
    src/assets/scss/_settings.scss
Error: no mixin named add-foundation-colors

       Backtrace:
        src/assets/scss/_settings.scss:44
        on line 44 of src/assets/scss/_settings.scss
>> @include add-foundation-colors;
   ---------^
```

It doesn't seem like something that'd be fixed by an updated zurb/foundation-zurb-template gulpfile, but who knows.

**Comment by gakimball** [comment]
You only need that mixin if you're going to use the new `$foundation-palette` variable. The upgrade guide didn't make this clear, so I [updated the guide](https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2#color-palette).

**Comment by erutan** [comment]
Thanks, figured it was something simple like that.

**Comment by ItIsInspiring** [comment]
Hi there,
for me, it still does not working.

**Comment by DanielRuf** [comment]
Hi @ItIsInspiring,

Please open a new issue and provide more details. Also see the issue template for information which we need to reproduce and fix your issue.
