### ISSUE TITLE
[6.2] Small breakpoint not availabe

### ISSUE THREAD

**Issue by cietho** [zurb/foundation-sites#8258]
When I set the following breakpoints:
```
$breakpoints: (
  small: 0,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
$breakpoint-classes: (small medium large);
```
I get this error:

> Invalid null operation: "null plus "2"". on line 233:13 of D:/Documents/foundation/Scss/util/_breakpoint.scss
> D:\Documents\foundation\Scss\app.scss

If I remove the `small` breakpoint from my `$breakpoint-classes`, the app.scss gets successfully compiled but there are no classes like `hide-for-small` or `small-12`.

Edit: Maybe a problem because of hard coded breakpoints? #8257

**Comment by gakimball** [comment]
I believe so—I'm going to close this in favor of #8257, where we're working towards a solution.
