### ISSUE TITLE
The grid-col-uncollapse mixin doesn't work

### ISSUE THREAD

**Issue by mociepka** [zurb/foundation-sites#8259]
It looks like `grid-column-uncollapse` uses not defined variable `$grid-column-gutter` by default. When I don't pass any value `rem-calc` try to calculate gutter from null:
```
Running "sass:default" (sass) task
WARNING: null was passed to rem-calc(), which is not a number.
        on line 75 of node_modules/foundation-sites/scss/util/_unit.scss
        from line 44 of node_modules/foundation-sites/scss/util/_unit.scss
        from line 19 of node_modules/foundation-sites/scss/grid/_gutter.scss
        from line 33 of node_modules/foundation-sites/scss/grid/_gutter.scss
        from line 22 of saleor/static/scss/store/partials/product_page.scss
        from line 140 of node_modules/foundation-sites/scss/util/_breakpoint.scss
        from line 21 of static/scss/page.scss

>> Invalid null operation: "null plus "2"".
>>   Line 19  Column 22  node_modules/foundation-sites/scss/grid/_grid.scss
Warning:  Use --force to continue.
```
I am using foundation-sites 6.1.2, my code:
```sass
  .content {
    padding: 0 $global-padding * 4;

    @include breakpoint(medium) {
      @include grid-col-uncollapse();
    }
  }
```

My solution for this problem:
```sass
  .content {
    padding: 0 $global-padding * 4;

    @include breakpoint(medium) {
      @include grid-col-uncollapse(map_get($grid-column-responsive-gutter, 'medium'));
    }
  }
```

**Comment by gakimball** [comment]
With the switch to responsive gutters, you have to be explicit with `grid-column-uncollapse()` regarding *which* padding value you want to uncollapse back to.

Not sure if there's a sensible default we can put in—maybe just pick the first value in the list if you don't provide one? So if you have:

```scss
$grid-column-gutter: (
  small: 20px,
  medium: 20px,
);
```

And you call with no parameters:

```scss
.thing {
  @include grid-column-uncollapse;
}
```

It just goes with `20px`. The other option is we output a warning.

**Comment by flyingL123** [comment]
Just came across this issue when I encountered the same thing in my project. Why can't the function uncollapse the gutters to the `$grid-column-gutter` value based on the current screen size if no argument is passed in?

Can't the mixin output media queries the same way it does when a column is created?

**Comment by kball** [comment]
@ncoden does this interact with the work you were doing in #8528?  Even if not, do you want to take a look at implementing something along the lines of what @flyingL123 suggested for a default?

**Comment by ncoden** [comment]
@kball Yes, it interact. I'll take a look :)

**Comment by ncoden** [comment]
@kball https://github.com/zurb/foundation-sites/pull/8693

**Comment by ncoden** [comment]
*6 months later*

@mociepka Does https://github.com/zurb/foundation-sites/pull/8693 resolves this issue ?
