### ISSUE TITLE
Dropdown off screen

### ISSUE THREAD

**Issue by jonBitgood** [zurb/foundation-sites#8260]
#4619 -- this seems to have been an issue with Foundation 5 as well.

If the last element in the navigation has a dropdown it cuts off text and a portion appears screen.

Here's an example: https://jsfiddle.net/a5xg4r9f/2/

**Comment by gakimball** [comment]
This was fixed in Foundation 6.2. If I update your JSFiddle to use the `6.2.0` CDN links it works fine. See here: <https://jsfiddle.net/a5xg4r9f/2/>
