### ISSUE TITLE
Code snippets doc page?

### ISSUE THREAD

**Issue by paaljoachim** [zurb/foundation-sites#8263]
Hey

I use the Genesis Framework and one of the things that are cool with it is that there are code snippets for a lot of good stuff such as various phrases be it search, add a comment etc etc.
I also appreciate the copyright code snippet they have and many others.
Another important aspect is widgetizing the front page....

Is there yet a code snippet doc page for making adjustments?
Kinda similar to http://my.studiopress.com/snippets/  ?

Thanks!

Btw
I make WordPress tutorials..... it would be cool to get into Foundation and begin creating some tutorials for it as well. http://easywebdesigntutorials.com/

**Comment by Deckluhm** [comment]
I might have misunderstood your question but if what you are looking for are code examples, the [documentation](http://foundation.zurb.com/sites/docs/) is full of them.

Just click on any component on the left navigation and you will see code snippets for it.

Here are 2 examples:
- `Button` documentation page: http://foundation.zurb.com/sites/docs/button.html
- `Accordion` documentation page: http://foundation.zurb.com/sites/docs/accordion.html

Also take a look at [HTML templates](http://foundation.zurb.com/templates.html) and [Building Blocks](http://foundation.zurb.com/develop/building-blocks.html).

**Comment by paaljoachim** [comment]
Your on the right track...:)
Here is a tutorial I made on Genesis for customizing the comments screen:
http://easywebdesigntutorials.com/customizing-the-blog-post-previews-and-posts-page-of-a-genesis-child-theme/

So I am thinking something similar to the above for Foundation.

**Comment by gakimball** [comment]
We publish a lot of [email lessons](http://zurb.com/university/lessons), as well as the code snippets on [Building Blocks](http://zurb.com/building-blocks), but we don't do a great job promoting them in our documentation.

We have plans to improve this. Namely, in each documentation page, we want to link to relevant lessons or building blocks for that UI element. So that'll be coming soon!

**Comment by paaljoachim** [comment]
Sounds great!
