### ISSUE TITLE
.small, .medium and .large classes in foundation-flex.css

### ISSUE THREAD

**Issue by aruberto** [zurb/foundation-sites#8265]
foundation-flex.css contains these 6 .small classes (similiar classes exist for .medium and .large)

![image](https://cloud.githubusercontent.com/assets/9933826/13376181/fd344204-dd81-11e5-97aa-1232c4a9cacc.png)

Seems they get generated from the following in https://github.com/zurb/foundation-sites/blob/develop/scss/components/_flex.scss:

```
  // Source ordering
  @include -zf-each-breakpoint {
    @for $i from 1 through 6 {
      .#{$-zf-size} {
        @include flex-order($i);
      }
    }
  }
```

Was this meant to generate [size]-order-[n] classes similar to flex grid?

If so I can submit a PR changing .#{$-zf-size} to .#{$-zf-size}-order-#{$i}

**Comment by gakimball** [comment]
Yes, that would be great :) Not sure how that slipped through.

**Comment by aruberto** [comment]
Submitted #8288 which changes .#{$-zf-size} to .#{$-zf-size}-order-#{$i}
