### ISSUE TITLE
meteor add zurb:foundation-sites missing /scss/util/_flex.scss

### ISSUE THREAD

**Issue by kara-todd** [zurb/foundation-sites#8267]
Just tried to run install foundation on meteor using `meteor add zurb:foundation-sites` however the app  throws the error:
`{zurb:foundation-sites}/scss/util/flex`

Checking `~/.meteor/packages/zurb_foundation-sites/6.2.0/web.*/scss/util/` it does indeed appear to be missing. It appears to be there on the 6.2.0 branch on Github so this seems specific to the meteor installer. Maybe it somehow didn't get added? 

Would appreciate a fix or guidance on this as the framework won't build without it. :)

**Comment by juliancwirko** [comment]
Here is a list of files for meteor: https://github.com/zurb/foundation-sites/blob/develop/package.js
Is this something new in 6.2? There are probably changes in the .scss files structure or names. It probably needs to be verified and adjust in `package.js`

**Comment by juliancwirko** [comment]
There is a PR with this fix: https://github.com/zurb/foundation-sites/pull/8269

**Comment by gakimball** [comment]
Merged #8290 which resolves this, and published version `6.2.0_1` which includes the updated package definition.
