### ISSUE TITLE
[Orbit Doc] Code Example not HTML5 confirm

### ISSUE THREAD

**Issue by jdoubleu** [zurb/foundation-sites#8270]
There are a few mistakes I found in the code example when I validated my site. I don't know if you want to be fully HTML5 confirm but this may should be fixed. Just have a look at it.

**Doc Version:** 6.2

The code example from http://foundation.zurb.com/sites/docs/orbit.html has two mistakes:
1. A figcaption must be placed inside a figure tag (see http://w3c.github.io/html/single-page.html#the-figcaption-element)
2. button tags can't be placed inside a ul (see http://w3c.github.io/html/single-page.html#the-ul-element)

**To reproduce:**
Check out the given w3c links and/or validate the code snippet with a validator (e.g. http://validator.w3c.org)

I created a pull request on this (see https://github.com/zurb/foundation-sites/pull/8271).
The orbit slide buttons still work but I'm not sure about the figure tag. The figure tag get's a default margin  of `1em 40px;` which could break the slides. Haven't tested it yet.

Thanks for your attention and your review.

**Comment by jdoubleu** [comment]
Update after some discussion in the PR:

As mentioned [here](https://github.com/zurb/foundation-sites/pull/8271#issuecomment-207775399]) there's already a class `orbit-caption` which prevents the `figcaption` to break the visual.

**Comment by DanielRuf** [comment]
The current docs seem to be fine.

![foundation zurb com_sites_docs_orbit html 1](https://user-images.githubusercontent.com/827205/36341091-2acb832c-13e9-11e8-9bdb-729f687322b7.png)

**Comment by jdoubleu** [comment]
@DanielRuf you're right. For version 6.4.3 this seems to have changed (https://foundation.zurb.com/sites/docs/orbit.html).

I don't know if this issue should be solved for older version (specific 6.2).

**Comment by DanielRuf** [comment]
> I don't know if this issue should be solved for older version (specific 6.2).

If you mean the (online) docs: there is just one docuentation for v5 and one for v6 afaik.

**Comment by jdoubleu** [comment]
Okay.

So closing this issue because it is no longer relevant.
