### ISSUE TITLE
Top Bar List Items Not Wrapping When There Are Many Items

### ISSUE THREAD

**Issue by tsquez** [zurb/foundation-sites#8272]
Not sure if this has been addressed in another issue or not, I searched and couldn't find anything. If it has been addressed, I apologize.

I just recently updated my WordPress theme WP-Forge to 6.2 and I was testing things out and noticed something odd with the top-bar menu.

I have a menu with a lot of test links in it called Long Menu - I use this to see how the top-bar looks when there are a lot of links added. In F5 the list items wrapped nicely, but since F6 i get the following:

![in-line-list-broken](https://cloud.githubusercontent.com/assets/1976117/13380461/3792f09c-de01-11e5-8252-7d5f49f10aa8.jpg)

The list items expand outside of the container. As you can see by the round red circle, I identified the culprit:

`.menu > li {
    display: table-cell;
}`

I changed above to reflect the following:

`.menu > li {
    display: inline-block;
}`

and as you can see by the following screenshot it seems to have corrected the issue:

![in-line-list-fixed](https://cloud.githubusercontent.com/assets/1976117/13380481/bd182796-de01-11e5-9028-4c0b419bc5d9.jpg)

I did some testing and this seems to work fine. I would make a pull request but I have only ever done one and don't want to screw anything up. So if someone could do some additional testing to see if I am right and if I am, maybe get it merged or fixed or whatever...lol (@JeremyEnglert hint hint...hehehe) - That would be awesome.

I added this to my themes style sheet already, but would love to see this fixed in core.

Thanks everyone

**Comment by andycochran** [comment]
:+1: I'm all for getting rid of the `display:table` / `display:table-cell` hack everywhere it's used. It's a heavy-handed style. (It caused problems with buttons, which is why I nixed it in #7933.)

**Comment by gakimball** [comment]
Yeah, I could see going back to floats. The cost savings on the CSS was really nice, but the use of `display: table-cell` has become a hassle as time goes on.

**Comment by andycochran** [comment]
No need for floats.

**Comment by kball** [comment]
@JeremyEnglert or @andycochran do you have a good sense of what needs to be done for this?

**Comment by JeremyEnglert** [comment]
I'm all for swapping out `table-cell` for `inline-block`.

I guess the question becomes: do we want to remove all instances of table-cell across the framework? @andycochran, thoughts?

**Comment by andycochran** [comment]
I'm actually not certain this is a bug. This is the case for every `.menu`, not just Top Bar. Responsive Navigation and the various menu patterns exists to solve this. Or, if your menu doesn't fit, maybe you're using the wrong kind of menu. 

Gonna close this. However, I've been thinking a lot about how Button Groups (which behave as this issue requests, wrapping to multiple lines) and Menus work together and definitely want to address the multi-line problem in that work.
