### ISSUE TITLE
What-input, undefined

### ISSUE THREAD

**Issue by Preen** [zurb/foundation-sites#8273]
Getting this with latest v. of foundation-sites (6.2)
`Uncaught TypeError: Cannot set property 'whatInput' of undefined`

**Comment by ten1seven** [comment]
Submitted a [pull request](https://github.com/zurb/foundation-sites/pull/8279) to resolve.

**Comment by gakimball** [comment]
Thanks @ten1seven! I left [a comment](https://github.com/ten1seven/what-input/issues/18#issuecomment-190297081) in the what-input repository explaining where the bug comes from.

**Comment by gakimball** [comment]
Merged #8279
