### ISSUE TITLE
Suggestion to make background color work in Yahoo mail

### ISSUE THREAD

**Issue by JulesWebb** [zurb/foundation-sites#8276]
Hello

I realize that Yahoo is not on your list of supported clients, but thought this easy to implement tidbit would be worth taking note of.

In order to force a background color in yahoo mail, it needs to be applied to the table class="body" element.  

I successfully tested adding background: #mycolor to .body. ---I did NOT remove the background color from the body element. 

QUESTION: Why isn't there a global variable for the background color in src/assets/scss/_settings.scss?

Cheers!
jules

**Comment by colin-marshall** [comment]
@JulesWebb I think you want to open this issue on the https://github.com/zurb/foundation-emails repo

**Comment by JulesWebb** [comment]
My apologies Colin, I thought that's where I was. I'll take it over there.
