### ISSUE TITLE
$form-label-font-weight also controls weight of <input> contents :(

### ISSUE THREAD

**Issue by erutan** [zurb/foundation-sites#8283]
I just tried bolding my labels and came across this little treat.  Reset it back to normal and inputs changed as well.  Simple enough to override, but somthing that shouldn't happen IMO.

**Comment by gakimball** [comment]
No `font-weight` is applied to `<input>` elements. It might be happening because you're placing an `<input>` inside of a `<label>`, so it's inheriting the font weight. Which, admittedly, is how we recommend doing it in the documentation, so maybe we need some extra CSS or a new Sass variable to get around that.

**Comment by erutan** [comment]
That makes sense!

I really don't think people are going to want to change the weight of input text, so just having a line of CSS setting inputs to normal should be fine. It'd be easy enough to override later if you don't use tons of specificity :)

**Comment by erutan** [comment]
I can submit a PR for this (honest this time!) ;)

**Comment by gakimball** [comment]
Go for it! Just one new variable to set text input weight, set to `$global-weight-normal` by default.

Also, target the `v6.3` branch with your PR. We've decided to now only change/add/remove Sass variables in minor versions, so no upgrades are required in patch versions.

**Comment by erutan** [comment]
I'm not sure we need a new `_settings.scss` variable. Including something in forms (haven't looked at code, so overly naive/simple example) like the following should cover the vast majority of use cases:

```scss
label > input {
  font-weight: $global-weight-normal;
}
```

If someone really wants to have their input weight different from the rest of the site, they can just do that on the side IMO. Preserving expected behaviour makes a bit more sense than baking it in.

**Comment by erutan** [comment]
Any preference on adding a new variable vs just hardcoding in inputs to match body weight?

**Comment by gakimball** [comment]
It'll have to be a new variable. Any time we change a stylistic element like this in CSS, we need a variable so people can change back if they want.

If you want to open a PR, target the `v6.3` branch.

**Comment by erutan** [comment]
Ok, back in civilization and settled down a bit.

**Comment by kball** [comment]
@erutan are you still taking a look at this?

**Comment by erutan** [comment]
Yeah, sorry I was traveling around Patagonia for a while, then jumping around on-site for a client and catching up with folk around California. I'm actually working on my fork of Foundation now, and will try to spend some time on it soon.

**Comment by andycochran** [comment]
Done. 😉
