### ISSUE TITLE
util/util import in settings file causes error

### ISSUE THREAD

**Issue by flyingL123** [zurb/foundation-sites#8293]
Is [this line](https://github.com/zurb/foundation-sites/blob/develop/scss/settings/_settings.scss#L43) supposed to exist? There is no `util/_util.scss` file in the `settings` directory. It's causing an error when I try to `@import '../jspm_packages/github/zurb/foundation-sites@6.2.0/scss/settings/settings';` from my main scss file.

Is this an error or am I not importing the library correctly?

**Comment by gakimball** [comment]
You need to configure your Sass compiler to have Foundation as an import path. Then when Sass sees `@import 'util/util'`, it will be able to check that path, not just the paths of your local files.

The exact option varies depending on if you're using gulp-sass, grunt-sass, etc., but the path you want is something like `jspm_packages/github/zurb/foundation-sites@6.2.0/scss`.

Also, I'd recommend copying the settings file out of the JSPM package and into your project-specific Sass folder. Presumably you don't have your dependencies checked in to version control, but even if you did, the next time you update Foundation, the settings file in there would be overwritten.

**Comment by flyingL123** [comment]
Stupid question, but do you know how I can figure out which sass complier is being used? I'm trying to work with Bigcommerce's new Stencil framework. I see a `Gruntile.js` in the codebase, but the contents are just:

```
module.exports = function(grunt) {
    require('time-grunt')(grunt);
    require('load-grunt-config')(grunt, {
        jitGrunt: {
            staticMappings: {
                scsslint: 'grunt-scss-lint'
            }
        }
    });
};
```
Is this where I can alter the import path?

**Comment by gakimball** [comment]
Assuming it's using the grunt-sass plugin, then the option is `includePaths`. It's an array of strings, and the paths are relative to the directory you run `grunt` inside.

**Comment by flyingL123** [comment]
Thanks so much. Any chance you can also explain how the `_global.scss` file and the `_settings.scss` are supposed to interact? Doesn't the global file set the same values as the settings file? Should they be imported in a certain order?

**Comment by gakimball** [comment]
`_settings.scss` comes *before* anything in Foundation is loaded. It's a file full of overrides.

In Sass, you can do this thing called "guarded assignment", where you only set a variable if it hasn't already been defined earlier. All of our settings variables use this flag—it's called `!default`.

```scss
$global-flexbox: true;
$global-flexbox: false !default;

// $global-flexbox will still be true
```

**Comment by flyingL123** [comment]
Just to make sure I understand, when you say: 

> All of our settings variables use this flag

You are talking about all the variables in the `global` file, not the `settings` file, right?

The `global` file is the one that uses the `default!` flag.

**Comment by gakimball** [comment]
Yes, sorry for the confusion. The framework files set the variables with the `!default` flag—those are the canonical defaults for the framework. The settings file is your overrides.
