### ISSUE TITLE
Cross-Site-Scripting vulnerability in Foundation 5.5.x

### ISSUE THREAD

**Issue by wneessen** [zurb/foundation-sites#8294]
I recently discovered a Cross-Site-Scripting Vulnerablity in Foundation 5.5.3 in the tooltip functionality.

If I put a HTML encoded string like "&lt;script&gt;alert(1);&lt;/script&gt;" into the title parameter of a
<span> Tag and enable the "data-tooltip" parameter for it, Foundation will take the content of the
title parameter and interpret the actual script by ignoring the HTML encoding. So basically it will call
"<script>alert(1);</script>" instead, which then leads to the XSS vulnerablity.

Please find attached screenshots as a proof. Tested with Foundation 5.5.3 in Chrome browser behind a Burp Securiy Scanner Proxy.

**How can we reproduce this bug?**
1. Create a <span> with "data-tooltip" enabled and with encoded JavaScript/HTML in th title section. Like this:
   `<span data-tooltip data-options="hover_delay: 50;" class="has-tip" title="&lt;script&gt;alert(1);&lt;/script&gt;">`
2. Open the website

**What did you expect to happen?**
The tooltip should show the encoded HTML

**What happened instead?**
The tooltip interprets the encoded HTML/JS as if it was unencoded and executes the script in it. An alert window will be presented

**Test case:**

![screenshot_2016 02 26_09h29m25s_006_](https://cloud.githubusercontent.com/assets/542696/13421900/8e514492-df91-11e5-9160-97721f337030.png)
![screenshot_2016 02 26_09h29m53s_008_](https://cloud.githubusercontent.com/assets/542696/13421904/948874ac-df91-11e5-87c8-7b75d5adad9d.png)

**Comment by rafibomb** [comment]
Thanks for the report! @kball Can you have a look?

**Comment by wneessen** [comment]
Any updates?

**Comment by wneessen** [comment]
Still none?

**Comment by wneessen** [comment]
Well, seem like the Foundation team is not interessted in such stuff, so I will close this issue and basically just release it at FD list

**Comment by wneessen** [comment]
Btw. the quickest workaround is:
https://gist.github.com/wneessen/d29586f96f9ee6f99a5b1712126c57b6
