### ISSUE TITLE
Dropdown menu on mobile device not showing completly

### ISSUE THREAD

**Issue by zlatiborac** [zurb/foundation-sites#8298]
**How can we reproduce this bug?**

1. go to the http://foundation.zurb.com/sites/docs/dropdown-menu.html
2. try it on mobile device or use Chrome inspector or whatever you use
3. go to Vertical section and try to tap on any of the links that have sub directory. On smaller screens you can not see sub menu when you open it, on larger only a part of them shows. The same problem I have on my website

**What did you expect to happen?**
Wanted to show sub menu
**What happened instead?**
Unable to see sub menu section
**Test case:**
http://foundation.zurb.com/sites/docs/dropdown-menu.html

**Comment by buddythebeagle-springerspaniel** [comment]
I am having the same problem on my website: [http//www.caamuseum.org]
1. use the website on a computer screen, select each of the dropdown menu items  at the top of the    page and see the list of items
2. Now, use the website on a mobile device, and go to the "menu" list on the top right-side of the screen  and click on each of the vertical lines (representing the menu lists)
3. note that each of the menu lists do not display the last item in the list.

**Comment by zlatiborac** [comment]
Any update on this issue? Am I the only one having the problems with this? I ask because the same example is still not working on F6 doc pages, and this is a crucial feature.

**Comment by buddythebeagle-springerspaniel** [comment]
I have not had any response to my issue.  I am using F5 doc pages.

**Comment by kball** [comment]
@Owlbertz is this something you can take a look at?

**Comment by Owlbertz** [comment]
Yes.

**Comment by Owlbertz** [comment]
Should be fixed with #8712.
@zlatiborac can you pull this down and test?
