### ISSUE TITLE
[Tooltips] Tooltip remains open despite option data-click-open is set to false

### ISSUE THREAD

**Issue by rianne-o** [zurb/foundation-sites#8300]
The documentation of tooltip's data-click-open option says:

> Allows the tooltip to remain open if triggered with a click or touch event.

The default value is set to true.

I've set up a Fiddle to reproduce this issue for you.
https://jsfiddle.net/oagy66s8/5/

As you can see, the anchor has the attribute `data-click-open="false"`. I'd expect the tooltip **not** to remain open after I've clicked on the element, but that's not what happens.

Despite of my false value, the tooltip still remains open after clicking on the element.

**Comment by colin-marshall** [comment]
Closing this out, as I believe this was resolved by @kball in #8691.
