### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#8302]
We're looking to make Foundation more friendly for our .NET/Visual Studio audience, so there's two things we want to do there:

- Publish a NuGet package
- Create a Visual Studio template for Foundation #8303

**Comment by abdullahsalem** [comment]
@gakimball check out this [NuGet package] (https://www.nuget.org/packages/foundation-sites/)
and I hope to work on the template soon

**Comment by gakimball** [comment]
@abdullahsalem Awesome, thank you!

**Comment by gakimball** [comment]
@abdullahsalem You have an invite to the team for this repository if there are any NuGet-specific files that need to be added to the codebase.

**Comment by abdullahsalem** [comment]
Thanks, @ncoden!

**Comment by ncoden** [comment]
@abdullahsalem WTF! I never done that ! o.O

**Comment by tinnvec** [comment]
I use foundation-sites in Visual Studio and am immensely grateful for the official package. However the folders don't match the ones used in the motion-ui, which are more of the standard ones for asp mvc.

Foundation: /js
Motion-ui: /Scripts (mvc default)

Foundation: /scss
Motion-ui: /Content (mvc default)

Normalizing these would be helpful, and a real time saver when updating versions

**Comment by abdullahsalem** [comment]
@tinnvec You are right, the current and next packages will be as described in the documentation [here](http://foundation.zurb.com/sites/docs/installation.html#package-contents), that means the Foundation NuGet package structure is the same of other Foundation packages i.e. Bower, NPM.. etc.
That will give you two ways to benefit this package:
- **Use the already compiled files**: In this case you only need to move the compiled files from `dist/` to your `Scripts` and `Content` folders.
- **Build your own CSS and JavaScript files**: In this case you need to write/use your own building tool to compile the source files that live underneath `Scss` and `js` folders, then move compiled files into `Scripts` and `Content` folders.

That is the current situation, but I will discus that with ZURB to add another feature to this particular package (NuGet), the feature is to copy the compiled files to `Scripts` and `Content` folders, and keep the rest of the package's structure as it is.
