### ISSUE TITLE
Visual Studio Template

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#8303]
We're looking to make Foundation more friendly for our .NET/Visual Studio audience, so there's two things we want to do there:
- Publish a NuGet package #8302
- Create a Visual Studio template for Foundation

Basically, like those Bootstrap templates that already ship with Visual Studio, but with Foundation ;) We can use the basic [index.html](https://github.com/zurb/foundation-sites-template/blob/master/index.html) we ship with our starter projects.

**Comment by Silvester20** [comment]
Why no fixing all the bugs the framework has currently instead of creating new things?

Thanks for the 6.2 btw, Hope the custom download will be fixed soon so I can upgrade.

**Comment by gakimball** [comment]
@Silvester20 We are fixing bugs—these two things are for the community to do.

**Comment by colin-marshall** [comment]
I think it's safe to abandon this for F6. Will look into doing this for F7 when the time comes.
