### ISSUE TITLE
flex grid nesting on fluid layout bug

### ISSUE THREAD

**Issue by takl95** [zurb/foundation-sites#8304]
I just made a new  foundation 6.2 project and enabled the flex-grid
I also changed the width to 100%

With these settings if I created a .row inside a .column div it wont stretch out to the full width. (Nesting)
The moment I changed $global-width to rem-calc(1200) everything works again.

**Comment by gakimball** [comment]
Could you be more specific about what you did to cause the bug?

When you say "changed the width", did you change a Sass variable, or modify the width in CSS?

And could you post the HTML used to create the grid? Thanks :)

**Comment by mmjaeger** [comment]
There's certainly something going on when nesting  - I added flex: 1 0 100% to the nested row and that seems to work?!

**Comment by tinyfly** [comment]
I'm running into this as well. I want to have a 100% fluid-width container.

If you set the Sass Variable `$global-width` to "100% then have a nested flex grid like this:

```html
<div class="row">
  <div class="column">
    <h1>Some content</h1>

    <div class="row">
      <div class="column">...content...</div>
      <div class="column">...content...</div>
    </div>
  </div>
</div>
```

![nested-column-bug](https://cloud.githubusercontent.com/assets/91300/13988152/abcd54cc-f0d8-11e5-9e59-b79b0b3ebb5c.png)

The nested row will not be 100% of the parent column. It'll be too narrow and it'll have some sort of space along the right margin. See the blue bar in the screenshot. It should stretch to the edge of the red parent.

As the original poster mentioned if you set `$global-width` back to a fixed value like `rem-calc(1200)` then the nested row stretches edge-to-edge of its parent column as expected.

**Comment by tinyfly** [comment]
Some more experimenting looks like the Sass variable `$global-width` directly sets the max-width on the `.row` which is true for every row so if I set `$global-width: none` I get a fluid width container and and nested rows are 100% as expected.

So my solution is to add a css class in my site styles of:

```css
.row .row {
  max-width: none;
}
```

This way you can use a percentage value for `$global-width` that doesn't mess with the row width of nested rows.

**Comment by gakimball** [comment]
Yep, nested rows were missing `max-width: none`. Fixed via 3822efecf799fe56d6a8bcfe1a9eb96312b6050e, and I added two test cases ([here](https://github.com/zurb/foundation-sites/blob/3822efecf799fe56d6a8bcfe1a9eb96312b6050e/test/visual/flex-grid/nesting.html) and [here](https://github.com/zurb/foundation-sites/blob/3822efecf799fe56d6a8bcfe1a9eb96312b6050e/test/visual/grid/nesting.html)) to verify both grids work correctly.

**Comment by kball** [comment]
I think this needs to be reopened due to #8886 and #8889

**Comment by colin-marshall** [comment]
@kball did #8889 resolve this?

**Comment by DanielRuf** [comment]
What is the current state of this?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback and the linked PRs were merged.
