### ISSUE TITLE
[6.2] [Dropdown Menu] [Flexbox] Dropdown Menu Always Open

### ISSUE THREAD

**Issue by dougmacklin** [zurb/foundation-sites#8305]
**How can we reproduce this bug?**

1. Create a new Foundation for Sites project (6.2.0) using the CLI
2. [Enable Flexbox Mode](http://foundation.zurb.com/sites/docs/flexbox.html#enabling-flexbox-mode)
2. Add [dropdown menu code](http://foundation.zurb.com/sites/docs/dropdown-menu.html#horizontal) with sub menu items

**What did you expect to happen?**

Dropdown menu works correctly, only opening when user hovers over its parent.

**What happened instead?**

Dropdown menu is always open because it has `display: flex` overriding `display: none`

**Test case:**

Strangely, this issue does not occur when using CDN links: [codepen](http://codepen.io/anon/pen/EKaJVG)

![screenshot](https://cloud.githubusercontent.com/assets/3129463/13442259/24d26b4e-dfb0-11e5-82ea-b9902aad7609.jpg)

**Comment by gakimball** [comment]
In your `app.scss` file, try moving `@include foundation-menu` above `@include foundation-dropdown-menu` and see if that works.

**Comment by dougmacklin** [comment]
Thanks @gakimball that fixed it! Want me to submit a pull request?

**Comment by gakimball** [comment]
We need to make sure it doesn't break anything else menu-related, so if you'd like to submit a pull request, could you also review the docs pages for menu and dropdown menu to ensure nothing else breaks?

**Comment by dougmacklin** [comment]
All of the related components appear to be working fine after the change. I noticed that in [foundation.scss](https://github.com/zurb/foundation-sites/blob/develop/scss/foundation.scss), `@mixin foundation-everything` already includes the components in the following order:

```
@include foundation-menu;
@include foundation-menu-icon;
@include foundation-drilldown-menu;
@include foundation-dropdown;
@include foundation-dropdown-menu;
```

However, above that in the `@imports`, `foundation-menu` is imported after `foundation-dropdown`:

```
@import 'components/drilldown';
@import 'components/dropdown-menu';
@import 'components/dropdown';
@import 'components/flex';
@import 'components/flex-video';
@import 'components/label';
@import 'components/media-object';
@import 'components/menu';
@import 'components/menu-icon';
```

I'm guessing this might be why using the CDN links eliminates this issue.

Should I move the `menu` and `menu-icon` imports above the `drilldown` import in this file to better align with the mixin? I'm just not entirely sure how the CLI install builds out the resulting `app.scss` file and whether or not this will fix it.

**Comment by gakimball** [comment]
The order of the imports doesn't matter, only the `@include`s.

However, I'm guessing the two starter projects haven't been updated. If you want to create pull requests for the `app.scss` on zurb/foundation-sites-template and zurb/foundation-zurb-template, I can pull them in.

**Comment by dougmacklin** [comment]
Ah that makes sense. Created the two pull requests:[foundation-sites-template](https://github.com/zurb/foundation-sites-template/pull/10), [foundation-zurb-template](https://github.com/zurb/foundation-zurb-template/pull/32). Thanks!

**Comment by gakimball** [comment]
Merged both. Thanks friend :)

**Comment by calderJamNet** [comment]
@gakimball this is still happening, is the accepted solution still just to move the location of foundation-menu?

**Comment by maland** [comment]
still happening with 6.4.1, fix is also still the same

**Comment by nikolasgd** [comment]
Second this! Took me and my co-worker hours trying to fix the "stuck" menu in a new Rails 5 app with Foundation 6 (gem version: foundation-rails 6.4.1.2). Is the accepted solution still to move the two lines like in @gakimball's comment?

**Comment by dpassarini** [comment]
Same here. I tried to move the lines as explained above. But I still have the very same problem

**Comment by colin-marshall** [comment]
@nikolasgd @dpassarini were you able to resolve this?
