### ISSUE TITLE
foundation-sites-template doesn't contain menu-icons include needed by 6.2.0

### ISSUE THREAD

**Issue by janslu** [zurb/foundation-sites#8306]
**How can we reproduce this bug?**
1. I have created a new test foundation 6.2.0 sites test folder (foundation new -> sites -> basic template)
2. Simple test of a responsive menu showed up without hamburger menu
3. scss/app.scss doesn't contain the following line:
@import 'components/menu-icon';
included in scss/foundation.scss (line #36). 

**What did you expect to happen?**

I expected the app.scss to contain all necessary includes. 

**What happened instead?**

Hamburger menu doesn't show up in responsive menu

**Test case:**
It's not a sites per se problem - it's a foundation-sites-template problem. Use cli to create a blank new 6.2.0 site and check scss/app.scss file.

**Comment by gakimball** [comment]
Fixed via zurb/foundation-sites-template@555e8f44c6ca97eeb51106df72a69e17e7b79843

Made the same fix to the ZURB Template as well: zurb/foundation-zurb-template@dfd63a823dea2624f10efce22e4c08524bfb559f
