### ISSUE TITLE
[6.2] Compiling foundation-flex.scss fails.

### ISSUE THREAD

**Issue by Archina** [zurb/foundation-sites#8307]
**How can we reproduce this bug?**

Checkout branch development, 6.2 or 6.2-stable.
cd into assets and compile with sass
```
sass foundation-flex.scss test.css
Error: Properties are only allowed within rules, directives, mixin includes, or other properties.
        on line 80 of ../scss/components/_top-bar.scss
  Use --trace for backtrace
```

To me it seems like either `@include top-bar-stacked;`[line 133, _top-bar.scss] should be encapsuled in an attribute or that `@include foundation-everything($flex: true);` [line 3, foundation-flex.scss] should be used differently...

--------------

I cannot really tell what the right fix would be at the moment and will look further into the top-bar.scss and eventually find the fix.

Still a bug like this should probably not exist on a stable branch.

**Comment by gakimball** [comment]
Some errors don't crop up in Libsass, which is why this wasn't caught right away.

**Comment by spark008** [comment]
Can you please release a version 6.2.1 with this fix?

**Comment by shicholas** [comment]
:+1: please release a new version, I'm waiting for this fix too.
