### ISSUE TITLE
Blockgrid: from one column to two columns and e.g. 4 columns

### ISSUE THREAD

**Issue by mmjaeger** [zurb/foundation-sites#8309]
Hello

I assign the following classes to the row element: class="row small-up-2 medium-up-4"

what I was wondering is how to show e.g. one column on iPhone portrait and then start going to 2 and 4 columns - would I need to create another breakpoint - am I missing something here?

Thanks

**Comment by gakimball** [comment]
You can use `.small-up-1` to get 1 item per row, then `.medium-up-2` and `.large-up-4`, for example.
