### ISSUE TITLE
Question on Yeit Launch

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#8314]
Are there any time tables for when Yeit Launch for Windows will be released? Windows is my main platform and I would love to be able to use Yeit Launch on my computer.

**Comment by gakimball** [comment]
We're in the process of putting together a timeline for Yeti Launch, which includes both updates to the existing Mac version, as well as the Windows version. Our best estimate is that a Windows version is a few months out. Thanks for your patience :)

**Comment by Lynda333** [comment]
@gakimball - Thank you for the info. I'll be patient. :) 

(P.S. If you need beta tester for the Windows version, I'd be happy to help!)

**Comment by gakimball** [comment]
I'll keep that in mind :)
