### ISSUE TITLE
Safari does not trigger JS for motion UI on first navigating to web page

### ISSUE THREAD

**Issue by ghost** [zurb/foundation-sites#8315]
**How can we reproduce this bug?**
1. we have example at www.pro-ppm.com.  using a safari browser on any device (iPad, iPhone or mac).  In section with class ID main, and div animation-wrapper, we use the multi animation that fades in content in three columns across the screen (responsive).
2. The animation triggers on all browsers except safari.
3. safari just hangs without doing anything.  it appears that nothing is initially getting the is-animating class.
4.  but if you refresh the page in safari - the animation triggers correctly.

**What did you expect to happen?**

JS ...

$(document).foundation();
document.querySelector('.animation-wrapper').classList.add('is-animating');
$('.animation-wrapper').addClass('is-animating');

_SCSS_*

@include motion-ui-transitions;
@include motion-ui-animations;
@include mui-series {
  .thing-one { @include mui-queue(3s, 0s, fade); }
  .thing-one-sub { @include mui-queue(2s, 0s, fade); }
  .thing-two { @include mui-queue(3s, 0s, fade); }
   .thing-two-sub { @include mui-queue(2s, 0s, fade); }
  .thing-three { @include mui-queue(3s, 0s, fade); }
  .thing-three-sub { @include mui-queue(2s, 0s, fade); }
}

**Test case:**

www.pro-ppm.com/index.html

**Comment by colin-marshall** [comment]
@ghost sorry for the super late response. The test case appears to be down. If this is still an issue, please provide a new test case for us to see. Thanks!

**Comment by DanielRuf** [comment]
The user seems to not exist anymore so we won't likely get any answer.

**Comment by colin-marshall** [comment]
TIL that user @ghost is what all deleted accounts become.

Should we close @ncoden?

**Comment by DanielRuf** [comment]
We support the following browsers by the browserslist config:
```
npx browserslist
npx: Installierte 3 in 2.257s
and_chr 64
and_ff 57
and_qq 1.2
and_uc 11.8
android 62
android 4.4.3-4.4.4
android 4.4
android 4.2-4.3
android 4.1
android 4
android 3
android 2.3
baidu 7.12
bb 10
bb 7
chrome 64
chrome 63
edge 16
edge 15
firefox 58
firefox 57
ie 11
ie 10
ie 9
ie_mob 11
ie_mob 10
ios_saf 11.0-11.2
ios_saf 10.3
ios_saf 10.0-10.2
ios_saf 9.3
ios_saf 9.0-9.2
ios_saf 8.1-8.4
ios_saf 8
ios_saf 7.0-7.1
op_mini all
op_mob 37
op_mob 12.1
opera 50
opera 49
safari 11
safari 10.1
samsung 6.2
samsung 5
```
