### ISSUE TITLE
[JS] error SCRIPT1014 on IE11

### ISSUE THREAD

**Issue by LeG3nDz** [zurb/foundation-sites#8319]
I community,

I've an error JS SCRIPT1014 **only on IE11**, on this line :

    if(!plugin.$element.attr(`data-${pluginName}`)){ plugin.$element.attr(`data-${pluginName}`, plugin.uuid); }

Is ECMAScript 2015 problem on Internet Explorer 11 ?

**Comment by gakimball** [comment]
As of Foundation 6.2 you need to compile the individual JavaScript plugins with Babel, to convert them to ES5. I think in the next release we'll put in pre-compiled versions of each plugin, though.

Either way, that's your issue—IE11 doesn't support much of anything in ES2015, so it's choking on the syntax.

How are you using Foundation? We have an [upgrade guide](https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2) for users of our ZURB Template, but if you use Foundation in your own project I'm happy to help. :)
