### ISSUE TITLE
6.2.0 ResponsiveMenu - this.rules.split is not a function

### ISSUE THREAD

**Issue by dan-def** [zurb/foundation-sites#8321]
If you load a page containing a ResponsiveMenu plugin and then call:

`Foundation.reInit($ul)`

where $ul is a jQuery object containing the ul of the menu, the following error is raised:

> this.rules.split is not a function

This appears to be caused within the foundation.responsiveMenu.js file.

When the constructor is called, this.rules is set to be a string:
`this.rules = this.$element.data('responsive-menu');`

Inside the _init function this is split into an array and parsed into another array called rulesTree which is then assigned back to this.rules. Upon calling reInit(), which in turn calls _init(), the assumption that this.rules is a string is no longer true and the split fails because it is now an array:

```
    var rules = this.rules.split(' ');

    // Iterate through every rule found
    for (var i = 0; i < rules.length; i++) {
      var rule = rules[i].split('-');
      var ruleSize = rule.length > 1 ? rule[0] : 'small';
      var rulePlugin = rule.length > 1 ? rule[1] : rule[0];

      if (MenuPlugins[rulePlugin] !== null) {
        rulesTree[ruleSize] = MenuPlugins[rulePlugin];
      }
    }

    this.rules = rulesTree;
```

For me, this occurs in the non-minified version of foundation.js.

**Comment by gakimball** [comment]
Fixed via 13c278c6d63bc4b54cda1f284277dcdf799096a4

[Here's a test case showing that the issue has been resolved.](https://github.com/zurb/foundation-sites/blob/13c278c6d63bc4b54cda1f284277dcdf799096a4/test/visual/responsive-menu/re-init.html)
