### ISSUE TITLE
Accordion Menu is toggling several times

### ISSUE THREAD

**Issue by SalimFayad** [zurb/foundation-sites#8326]
When the option data-multi-open is set to false, and if we have 2 levels, the menu is toggling several times, especially when we want to open a menu link from the code.

Please check the following reproduced case:

https://jsfiddle.net/4y625yjo/

**Comment by rafibomb** [comment]
I wonder if it's the fiddle because it's not happening on the docs or here: http://codepen.io/rafibomb/pen/jqPdog

**Comment by gakimball** [comment]
Your Fiddle is using Foundation 6.0.1. If you update to 6.2.0 the issue goes away.
