### ISSUE TITLE
F 6.2 - bug orbit navigation

### ISSUE THREAD

**Issue by xfifix** [zurb/foundation-sites#8327]
i can't use the button next and previous to navigate on the slideshow ...

**Comment by xfifix** [comment]
i found the solution, I am going to create a pull request :)

**Comment by xfifix** [comment]
#8328

**Comment by rafibomb** [comment]
I see it's working on the docs. What changes to Orbit prevented you from using the buttons?

**Comment by xfifix** [comment]
I changed nothing, I just updated foundation...

**Comment by gakimball** [comment]
What browser did you encounter this bug in?

**Comment by xfifix** [comment]
I use chrome on linux and on my IPhone.

below my html code reduced : 

 `<div class="orbit" data-orbit>
  <ul class="orbit-container">
      <button class="orbit-previous" aria-label="previous">&#9664;</button>
      <button class="orbit-next" aria-label="next">&#9654;</button>
      <li class="orbit-slide">
        <a href=""><img class="orbit-image" src="" alt=""></a>
      </li>
  </ul>
</div>`

**Comment by gakimball** [comment]
Merged #8328
