### ISSUE TITLE
[Media Queries] Can't add xsmall

### ISSUE THREAD

**Issue by DusanMilko** [zurb/foundation-sites#8329]
When I add a "xsmall" to the breakpoints in settings.scss I get an error because of the added checks in breakpoints.scss:

@else if map-get($breakpoints, small) != 0 {
  @error 'Your "small" breakpoint (defined in $breakpoints) must be set to "0".';
}

There should not be a force with small....

using with foundation scss

**Comment by andycochran** [comment]
There are valid reasons `small` is required. But there's a solution in the works. See #8318.

**Comment by DaSchTour** [comment]
Duplicate of #8257

**Comment by gakimball** [comment]
@DaSchTour Yep yep
