### ISSUE TITLE
null plus "2"

### ISSUE THREAD

**Issue by DusanMilko** [zurb/foundation-sites#8330]
Getting a:

>    Error: Invalid null operation: "null plus "2"".
>    on line 234 of bower_components/foundation-sites/scss/util/_breakpoint.scss
>    @return map-get($map, $anchor);

**Comment by An1mo16** [comment]
check if the variable exists in the $map

**Comment by colin-marshall** [comment]
@DusanMilko sorry for the late response. If this is still an issue after verifying what @An1mo16 said, feel free to reopen the issue with the values you are using that result in this error.
