### ISSUE TITLE
Foundation 5.5.3 topbar not working.

### ISSUE THREAD

**Issue by mxp83** [zurb/foundation-sites#8332]
I know there's been tons of threads and pages to this issue, but I still can't seem to get it working with all the fixes people have suggested.

I pulled Foundation from Bower, and I pretty much copied the code from the docs.  I event went as far as to modify the foundation.topbar.js (I've since reverted it) and yet it still doesn't work on mobile or < 640px width.

```
<link rel="stylesheet" href="css/app.min.css">
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/foundation/js/foundation.min.js"></script>
<script src="bower_components/modernizr/modernizr.js"></script>
<script>
  $(document).foundation();
</script>
```

and then the standard `<nav class="top-bar" data-topbar role="navigation">`

**Comment by gakimball** [comment]
Do you get any console errors?

**Comment by mxp83** [comment]
Nothing at all.  Console is blank.

**Comment by dragthor** [comment]
I am going to look into this (and confirm) this week.

**Comment by IamManchanda** [comment]
@dragthor @mxp83 Are you still facing any issue?
Please let us know

We have closed this for now but feel to let us know and we will reopen
