### ISSUE TITLE
Docs: Column or Columns?

### ISSUE THREAD

**Issue by tomByrer** [zurb/foundation-sites#8337]
Seems most [docs](http://foundation.zurb.com/sites/docs/flex-grid.html) use `.columns`, but [this PR](https://github.com/zurb/foundation-sites/commit/1aae2bf5a6e954c71dcbc9fd3c60b93eb63cc396) made me experiment with `.column` which seems to work fine.  Should this be standardized?

I prefer singular, because I'm more item-focused; I picture a [block](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements) is only one column, even if it may be wider than others.  Though I can understand how some are more grid-focused, where a block may be 2+ 'columns' in the grid.  However with flexbox, blocks may often will not strictly fall into the *8.333% * x* grid width, so I vote `.column`

**Comment by gakimball** [comment]
It's basically a grammar thing, so we're interested in keeping both for now. So in a block grid you can use the singular `.column`, or in the standard grid you can write `.small-6 columns`, as in "this is six columns wide".

Everywhere we use `.column` in CSS, we add a comma and put in `.columns` as well. So the two classes should always work exactly the same.

**Comment by tomByrer** [comment]
Oh I wasn't trying to say Foundation should exclusive to one, but asking if the documentation should conform to one or other.  Can be confusing if both are on the same page.  & if both are used in Deployed HTML, uncss won't optimize as well either.

**Comment by andycochran** [comment]
@gakimball What do y'all think of adding a `$use-plural-columns` settings variable to 6.3 that, if false, doesn't add `, .columns` everywhere `.column` is used? Every byte counts.
