### ISSUE TITLE
Doc: Flex-grid & Flexbox is redundant

### ISSUE THREAD

**Issue by tomByrer** [zurb/foundation-sites#8339]
http://foundation.zurb.com/sites/docs/flexbox.html
is overlapped by
http://foundation.zurb.com/sites/docs/flex-grid.html

Somewhat confusing since they mostly have the same info, though 'flexbox' (or is about to be) more outdated.  I already have [2](https://github.com/zurb/foundation-sites/pull/8336) [PR](https://github.com/zurb/foundation-sites/pull/8338) against flex-grid

I suggest removing 'flexbox' page, add merge in missing content to 'flex-grid' (SEO), & `301` redirect from `flexbox.html` to `flex-grid.html`.

**Comment by kball** [comment]
@rafibomb do you have thoughts on this?

**Comment by andycochran** [comment]
Semantically, it makes more sense to remove `flex-grid.html` and keep `flexbox.html`. The Flex Grid is a flexbox mode component. All the various flexbox components should not be documented on a page about the grid.

**Comment by rafibomb** [comment]
Hmmm, There are enough differences in the two grids that it warrants another page. The Flexbox page might be better as a Flexbox Utilities page.

In Foundation 7, there will only be Flexbox so this is less of an issue.

**Comment by DanielRuf** [comment]
It seems this is already done. It redirects to https://foundation.zurb.com/sites/docs/flexbox-utilities.html so I'll close this issue for now.
