### ISSUE TITLE
Foundation 6.2 Babel breaks browsersync

### ISSUE THREAD

**Issue by alanontheweb** [zurb/foundation-sites#8340]
I upgraded to 6.2 after some issues with Babel and the migration guide not being what ultimately worked. I dug around and found the new babel includes in the package.json from the Zurb 6.2 templates and that did the trick. 

HOWEVER, since upgrading to 6.2, making ANY syntax errors in my JS leads to Babel crashing and me having to restart the browsersync gulp task. Everything works fine until there is a syntax issue.

The error - 

``` js
SyntaxError: src/assets/js/core.js: Unexpected token (20051:4)
    at Parser.pp.raise (.../node_modules/babylon/index.js:1412:13)
    at Parser.pp.unexpected (.../node_modules/babylon/index.js:2895:8)
    at Parser.pp.expect (/.../node_modules/babylon/index.js:2889:33)
    at Parser.pp.parseObj (.../node_modules/babylon/index.js:937:12)
```

Here's my task - 

``` js
gulp.task('javascript', function() {
  var uglify = $.if(isProduction, $.uglify({
    <...>
      }
    })
    .on('error', function(e) {
      console.log(e);
    }));

  return gulp.src('src/assets/js/core.js')
    .pipe($.include())
    .on('error', console.log)
    .pipe($.sourcemaps.init())
    .pipe($.babel())
    .pipe(uglify)
    .pipe($.if(!isProduction, $.sourcemaps.write()))
    .pipe(gulp.dest('dist/assets/js'));
}); 
```

core.js actually contains all the imports (similar to how Sass does imports) using the Gulp Include plugin - https://www.npmjs.com/package/gulp-include

You can see above that .pipe($.include()) concats them, and then I pass babel. If I pass babel before the include, then no JS would be parsed in this method.

Any pointers on how to fix this so babel doesn't terminate the browsersync process? Thanks!

**Comment by kball** [comment]
It looks like the answer for this may involved the `gulp-plumber` plugin (https://www.npmjs.com/package/gulp-plumber).  Will dig into this in the template once we've got the 6.3 RC packaged up

**Comment by colin-marshall** [comment]
@ncoden do you think this is still necessary to keep open since we switched to webpack? This was also a somewhat unique/custom setup.

**Comment by DanielRuf** [comment]
We did not fully switch to webpack. This is normal fur Gulp when the exceptions are not caught by something like gulp-plumber or gulp-notify.

This is a question about a custom implementation.

**Comment by DanielRuf** [comment]
We might close this as this is the same with all Gulp setups.

**Comment by ncoden** [comment]
If I understand correctly this is a problem coming from a custom build setup not using `gulp-plumber`. This should not be related to Foundation.

Closing this issue. @alanontheweb please reopen if we are wrong.
