### ISSUE TITLE
grunt-contrib-uglify fails with foundation.core.js

### ISSUE THREAD

**Issue by erredeco** [zurb/foundation-sites#8342]
I want to use a grunt task to manually concat and uglify the js files from foundation; but it fails 
with the following error:
```
JS_Parse_Error {
  message: 'Unexpected character \'`\'',
  filename: '../../../../../node_modules/foundation-sites/js/foundation.core.js',
  line: 56,
  col: 29,
  pos: 1964,
```
I am using grunt-contrib-uglify 1.0.0
what can I do? Thank you for your support

**Comment by Owlbertz** [comment]
I guess that could be because of Foundation JS using ES6 syntax. You would need to use [Babel](https://babeljs.io/) or something similar before uglifying.

**Comment by erredeco** [comment]
umm... never used babel... is there some grunt task I can use to concatenate the js file and then minify them?

**Comment by erredeco** [comment]
it has been a bit difficult, but eventually after some search I managed to solve it: I had to
1) concat all the files into one
2) pass it trough babel
3) pass it trough uglify
I don't know if there are more clever ways to do that

**Comment by Owlbertz** [comment]
I don't think so, as the uglifying requires "classic" JavaScript, but as mentioned above Foundation 6 uses ES 6 syntax. The "official" build process using Gulp does exactly what you said, so there will always be the additional step with babel as long as ES 6 has become the standard for browsers and build-tools.

**Comment by erredeco** [comment]
@Owlbertz thank you for your support. This ticket was more an help request and can be therefore closed.
the only remark I can do is that if someone don't want to rely on the standard Foundation build stack but wants (or needs) to implements his/her own, it is a bit difficult to do. (but at least, there is some documentation to start with). Have a nice evening.
