### ISSUE TITLE
[Docs] reset-order - classes no longer supported? Still in docs

### ISSUE THREAD

**Issue by FynnZW** [zurb/foundation-sites#8343]
In the docs right [here](http://foundation.zurb.com/sites/docs/grid.html#source-ordering), it says:
 
> Use large-reset-order to reset pushed or pulled columns to their original position on large screens.

This class (or any reset-order-class) is nowhere in the CSS. I am using Version 6.1.2
So, the documentation needs an update. Any alternatives to this class? pull-0?

**Comment by gakimball** [comment]
You're right, `.[size]-push-[n]` and `.[size]-pull-[n]` are the correct classes. Fixed here: 305edc33445913d8cd3b7949ac3694a99405889c
