### ISSUE TITLE
[Reveal] Position is not vertical centered.

### ISSUE THREAD

**Issue by shoaibik** [zurb/foundation-sites#8344]
See it here http://foundation.zurb.com/sites/docs/reveal.html , the reveal modal is not vertically aligned in the center.
This should be in the middle of the page, as I have a fixed top menu, it overlaps it.

If I change 
`top = parseInt((outerHeight - height) / 4, 10);`
to
` top = parseInt((outerHeight - height) / 2, 10);` at https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L117

it then comes in the middle.

I am using Chrome 48.0.2564.116 m on Windows 7.

**Comment by kball** [comment]
The current behavior is deliberate (offset modal in the middle upper part of page) and matches Foundation 5 behavior.  You can explicitly set the vertical offset using a data-v-offset attribute.
