### ISSUE TITLE
[Off-canvas] Force-Top doesn't work in Firefox

### ISSUE THREAD

**Issue by LDigital84** [zurb/foundation-sites#8346]
According to the docs `data-force-top` is set to `true` by default which will `Force the page to scroll to top on open.`.

This doesn't work. It was working prior to 6.2 but appears to be broken in 6.2.

**Comment by Deckluhm** [comment]
Documentation example works as expected: http://codepen.io/anon/pen/ZWbwgE?editors=1100

**Comment by Lynda333** [comment]
@Deckluhm - Actually, it works in Chrome and Edge (both latest versions) but not Firefox (v45). Firefox appears to be broken.

**Comment by kball** [comment]
This is still present in 6.2.1 for firefox.

**Comment by Peeeep** [comment]
Instead of `$('body').scrollTop(0);` it should read `$('html,body').scrollTop(0);` in foundation.offcanvas.js on line 157 because Firefox and IE place the overflow at the `<html>` level (unless otherwise specified) whereas Safari, Chrome, Opera place it at the `<body>` level.

**Comment by brettsmason** [comment]
Off canvas has been completely reworked for 6.3 and this issue should now be solved.
Release candidate is out today, with the full release scheduled for the 15th December.

Closing this, but if you still have issues with 6.3 please re-open.
