### ISSUE TITLE
Nested Accordions Not Working Correctly

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#8349]
I have the following code: 

    <ul id="potenzial" class="accordion" data-accordion data-allow-all-closed="true" data-multi-expand="true">
      <li class="accordion-item is-active" data-accordion-item>
        <a href="#" class="accordion-title accordion-title-first"><span class="text-accord">MEIN CORPORATE DESIGN</span></a>
        <div id="corporate-design" class="accordion-content" data-tab-content>
            <p>Content for first accordion item.</p>
            <button class="next1 button">NEXT ITEM</button>
        </div>
      </li>
      <li class="accordion-item" data-accordion-item>
        <a href="#" class="accordion-title"><span class="text-accord">MEIN KOMMUNIKATIONSDESIGN</span></a>
        <div id="kommunikationsdesign" class="accordion-content" data-tab-content>
            <ul id="kommunikationdesign-sub" class="accordion" data-accordion data-multi-expand="true">
              <li class="accordion-item is-active" data-accordion-item>
                <a href="#" class="accordion-title"><span class="text-accord">MEINE GESCHÄFTSAUSSTATTUNG</span></a>
                <div id="geschaftsausstattungn" class="accordion-content" data-tab-content>
                    <p>Content for nested accordion, first item.</p>
                    <button class="next2 button">NEXT ITEM</button>
                </div>
              </li>
              <li class="accordion-item" data-accordion-item>
                <a href="#" class="accordion-title"><span class="text-accord">MEIN MARKETING UND WERBUNG</span></a>
                <div id="kdmarketing" class="accordion-content" data-tab-content>
                    <p>Content for nested accordion, second item.</p>
                    <button class="next3 button">NEXT ITEM</button>
                </div>
              </li>
              <li class="accordion-item" data-accordion-item>
                <a href="#" class="accordion-title"><span class="text-accord">MEINE WERBEGESCHENKE</span></a>
                <div id="werbegeschenke" class="accordion-content" data-tab-content>
                  <p>Content for nested accordion, third item.</p>
                </div>
              </li>
            </ul>
        </div>
      </li>
    </ul>

This appears to work just fine, until you try to use JS to change accordion items. For example, I run this JS: 

    $(".next2").on("click", function() {
		$("#kommunikationdesign-sub").foundation('toggle',$("#kdmarketing"));
		return false;
    });

It doesn't work. After inspecting the code it appears that Foundation is changing my IDs in the nested accordion. I'm unsure if it's the same issue as #7923 For example, the following code: 

    <div id="geschaftsausstattungn" class="accordion-content" data-tab-content>

becomes: 

    <div id="kommunikationsdesign" class="accordion-content" data-tab-content>

That ID is for the div that contains the nested accordion. 

Again, if you click the divs they appear to work correctly, it's only when you try to trigger them using JS. 

Here is a pen with the problem happening: http://codepen.io/Lynda333/pen/XdmwbO

**Comment by gakimball** [comment]
Fixed via 091d8f01af119d21465b0a724b97dfa8c71694de and 4565482ca6ed9832ae45973cd784a4509aec6767. Our regression tests also now include a test for [nested accordions](https://github.com/zurb/foundation-sites/blob/develop/test/visual/accordion/nested.html).

The fix will be in the next Foundation patch.

**Comment by Lynda333** [comment]
@gakimball - Great, thank you!
