### ISSUE TITLE
[Doc] HTML Templates : E-commerce template footer typo

### ISSUE THREAD

**Issue by pascaloliv** [zurb/foundation-sites#8350]
Hello Zurb friends,

First of all, I can't find the *E-commerce* template open-sourced on Github, but we can download it on the [HTML Templates page](http://foundation.zurb.com/templates.html).

**How can we reproduce this bug?**

1. Go to [HTML Templates page](http://foundation.zurb.com/templates.html)
2. Download E-commerce template
3. Open the ecommerce.html see the glitch in footer

**What did you expect to happen?**

E-commerce template should look fine, same as [live demo](http://foundation.zurb.com/templates-previews-sites-f6/ecommerce.html) page.

**What happened instead?**

The footer is glitched.
![glitched_footer](https://cloud.githubusercontent.com/assets/442681/13556550/7b0fbf7c-e3dc-11e5-98e2-ae1dead6c467.png)

**How to solve**

Just correct the position of the div closing tag.
![code_source](https://cloud.githubusercontent.com/assets/442681/13556556/b9836344-e3dc-11e5-86f8-da60a71a6c3e.png)
Move **the div closing tag** from line 59 to line 75.
The two following **.large-3** div have to be inside the parent **.row** div

That's it ! :+1:

**Comment by gakimball** [comment]
Paging @rafibomb for the typo.

As for the open source-ness of the templates, for now they're baked into our marketing site, which is closed source. We could potentially open source them one day, but there's no plans for that at the moment.

**Comment by gakimball** [comment]
Actually, I'm not seeing this in Chrome. What browser did you take that screenshot in?

![image](https://cloud.githubusercontent.com/assets/1142001/13755872/75f39708-e9da-11e5-879e-1bcd1f381b7d.png)

**Comment by pascaloliv** [comment]
I'm on Chrome Mac / Version 49.0.2623.87 (64-bit)

I'm almost sure that this issue is caused by the closing tag (see my initial issue report).

**Comment by gakimball** [comment]
Ohhh okay, I found it, sorry about that!

The marketing site is closed-source so I can't link the commit. But we'll get the marketing site deployed soon with this fix. Thanks! :)

**Comment by pascaloliv** [comment]
@gakimball Thank you ! ;)
