### ISSUE TITLE
Add babelify to package.json

### ISSUE THREAD

**Issue by dherran** [zurb/foundation-sites#8351]
I've been using Browserify since I started using Foundation 6. However, the latest Foundation 6.2 broke my compilation process as your package.json is not instructing Browserify to Babelify it.

Can the following be added to your package.json so people using Browserify can compile properly?

```
{
  "browserify": {
    "transform": [["babelify", { "presets": ["es2015"] }]]
  }
}
```

For example:

```
{
  "browserify": {
    "transform": [["babelify", { "presets": ["es2015"] }]]
  },
  "_args": [
    [
      "foundation-sites@^6.2.0",
      "C:\\EasyPHP\\data\\localweb\\compassity\\www"
    ]
  ],
......
```

Browserify wont automatically run Babel inside the node_modules folder, unless the module specifically requests it. There is no option to set this Browserify, so it must be explicitly indicated by the module. This entry shouldn't affect at all any other Node tasks.

**Comment by gakimball** [comment]
The template doesn't include Browserify by default, so there's no reason for us to include any Browserify-specific configuration in it.

**Comment by lastobelus** [comment]
> The template doesn't include Browserify by default, so there's no reason for us to include any Browserify-specific configuration in it.

No and it doesn't include webpack either, or any modern js build system. Pretty much everyone on the interwebs who reviewed Foundation 6 called that out as a deficiency.

Since you chose not to include a js build system, could you not at least remove the roadblocks for people who need one?

**Comment by lastobelus** [comment]
@dherran Do you by any chance have an example of adding browserify to a project that started from the Zurb template?

**Comment by dherran** [comment]
@lastobelus you have 2 options:

a) With the newest versions of Foundation you can simply require the JS files inside the dist folder, like so:

`require('foundation-sites/dist/plugins/foundation.dropdownMenu.js');`

b) If you want to transpile Foundation's ES6 yourself, you will need to edit their package.json in the node_modules folder every time you update the package, like so:

```
{
  "browserify": {
    "transform": [["babelify", { "presets": ["es2015"] }]]
  },
  "_args": [
    [
      "foundation-sites@^6.2.0",
      "C:\\EasyPHP\\data\\localweb\\compassity\\www"
    ]
  ],
......
```

This used to be an issue before they started including transpiled JS in the dist folder. Nowadays I would simply go with option (a) and forget about the package.json.

**Comment by lastobelus** [comment]
@dherran Thanks, I'll give option a) a go!
