### ISSUE TITLE
[Accordion Menu] not tabbable/keyboard navigatable

### ISSUE THREAD

**Issue by t22james** [zurb/foundation-sites#8352]
**How can we reproduce this bug?**

1. Tab through webpage tab sequence
2. focus will hit first item of accordian-menu, at which point, tab (and backwards tab/alt+tab) no longer work.
3. left/right arrow keys will open and close that first level item dropdown, however up/down arrows do not work, so keyboard can never access the submenu items, by either up/down or tab

**What did you expect to happen?**
functionality of keyboard should match the standard accordian. Aka, tab sequence should not be interrupted, and tab key should continue to navigate to the (other) visible links/focus points. up/down arrows should also enable user to navigate the menu items, in same manner that a user an do so in standard accordian.

**Test case**

http://foundation.zurb.com/sites/docs/accordion-menu.html
http://foundation.zurb.com/sites/docs/accordion.html

**Comment by Owlbertz** [comment]
I will have  a look.

**Comment by t22james** [comment]
is the referenced issue claiming to fix this issue too? any idea when it might roll out?
