### ISSUE TITLE
[Essential Package] JavaScript not transpiled in download, missing minified version

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#8353]
**How can we reproduce this bug?**

1. Go to http://foundation.zurb.com/sites/download/
2. Download the "Essential" package

**What did you expect to happen?**

1. `foundation.js` should be transpiled 
2. `foundation.min.js` should be present (it's included in the example `index.html`)

**What happened instead?**

1. `foundation.js` should be transpiled
2. `foundation.min.js` is missing from the .zip file

**Comment by gakimball** [comment]
Going to roll this into #7033 where we're tracking all customizer issues. @erikmellum and I are working towards a solution.
