### ISSUE TITLE
Failure in the instruction Upgrading-to-Foundation-6.2

### ISSUE THREAD

**Issue by op-jusi** [zurb/foundation-sites#8354]
https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2

> In gulpfile.js, add the Babel plugin to your javascript task, right above the $.concat() step:
> gulp.task('javascript',
>  function() {
>   return gulp.src(PATHS.javascript)
>     .pipe($.sourcemaps.init())
>     .pipe($.babel()) // <-- There it is!
>     .pipe($.concat('app.js'))
>     .pipe(uglify)
>     .pipe($.if(!isProduction, $.sourcemaps.write()))
>     .pipe(gulp.dest('dist/assets/js'))
>     .on('finish', browser.reload);
> });

This step didn't work for me. Just modifying the file _gulpfile.js_ has caused compiling issues. Only "migration" by cloning the foundation 6.2 and moving _.git_ and _src_ there solved the problem.

**Comment by gakimball** [comment]
Did you run the `npm install` command in step 1?

**Comment by op-jusi** [comment]
Yes I did. The problem is, when compiling other packages are required which are listed in the npm configuration in foundation 6.2 and not in 6.1. So compiling didn't work for me until I solved as described above.

**Comment by shaunmorrison** [comment]
Yes, I have errors using bower + grunt + uglify. Can't see any documentation to get this working. 

e.g.
```
JS_Parse_Error {
  message: 'Unexpected character \'`\'',
  filename: '../../../../bower_components/foundation-sites/js/foundation.core.js',
  line: 62,
  col: 28,
  pos: 2276,
```

**Comment by op-jusi** [comment]
@shaunmorrison 
Looks like you accidentally modified _foundation.core.js_. 
You can try to remove _bower_components/foundation-sites_ and reinstall this component by issuing `bower install`.

**Comment by shaunmorrison** [comment]
I think it's actually because uglify isn't built to handle ES6.

**Comment by shaunmorrison** [comment]
Only way I can get this to work is to include the entire dist/foundation.js file rather than the foundation.core.js + individual components as needed.

**Comment by eriolo** [comment]
I have the same problem with foundation 6.2 and uglify of foundation.core + individual components (using webpack and babel-loader).

```
Unexpected character '`' [../~/exports-loader?foundation=jQuery.fn.foundation!../~/foundation-sites/js/foundation.core.js:56,0]
```

Same settings without uglify works, and running uglify on an individual component with backtick, e.g. foundation.core, works too. Anyone with an idea on how to solve the problem without loading the entire collection of components? :)

**Comment by gakimball** [comment]
@eljojo If Uglify is seeing a backtick character, that sounds like Babel isn't running before Uglify.

**Comment by eriolo** [comment]
@gakimball You're right, I had only included babel-loader for the non-vendor scripts. Thanks!
