### ISSUE TITLE
uncss resluts garbled CSS

### ISSUE THREAD

**Issue by op-jusi** [zurb/foundation-sites#8355]
In _gulpfile.js_ (6.1) _gulpfile.babel.js_ (6.2) uncss is turned on by default when compiling for production. In both versions I have to disable it. Otherwise I get garbled CSS. 

I think it should be disabled by default.

**Comment by gakimball** [comment]
What do you mean garbled? That it's compressed? gulp-cssnano compresses your CSS, while gulp-uncss removes unused CSS classes in your HTML.

**Comment by op-jusi** [comment]
I mean when uncss is applied, my site looks garbled. When I comment unscc out in the gulpfile, than the site looks as it should. In both cases css is compressed. I suppose uncss messes css up or even leaves out some css parts.

**Comment by gakimball** [comment]
Yeah, what UnCSS does is scan your HTML pages and remove any CSS classes that aren't used.

If it's problematic for you, it's totally okay to just remove it entirely. It's a very aggressive optimization, which is cool, but it has its caveats.
