### ISSUE TITLE
flex grid alignment for different sizes

### ISSUE THREAD

**Issue by atilkan** [zurb/foundation-sites#8356]
For flex grid, there is no different alignment options for different sizes. There is a pattern for this framework which starts with sizes (large, medium, small). It is not applied here for flex grid alignment.

I want to align elements 
On large: left
On medium: justify
On small: right

**Comment by atilkan** [comment]
While using, i see other features removed. Forex: `hide-for-large-up`.
50 percent code reduction! This is not cool. Less code or more code doesn't prove anything.

**Comment by Lynda333** [comment]
+1 - this would be nice.

**Comment by colin-marshall** [comment]
Thanks for this feature request. We’re going to close out this ticket, as we will not be adding more features to Version 6, but your request is being considered for Version 7.
