### ISSUE TITLE
foundation.util.mediaQuery.js no longer works with Web Optimization Bundling in ASP.NET

### ISSUE THREAD

**Issue by chrispem** [zurb/foundation-sites#8358]
I Believe that recently the format of the JavaScript has been changed from 

`get: function(size) {`

to 

`get(size) {`

If like me you use Microsoft MVC ASP.NET and choose to bundle your own JavaScript the bundle will now fail because of this function.

I was getting the message "Object reference not set to an instance of an object." which when traced back I found to be the file foundation.util.mediaQuery.js and specifically the function "get", please note if the name is not "get" then the new format works.

I will report the the Microsoft team also.

**Comment by gakimball** [comment]
The codebase is written in ES2015 now. Can you add Babel to your build process?

**Comment by kball** [comment]
Closing based on lack of response.  If this is still an issue with the new codebase please reopen with details to reproduce.
