### ISSUE TITLE
Dropdown panel alignment

### ISSUE THREAD

**Issue by zlatiborac** [zurb/foundation-sites#8359]
1. Manual states: "By default, a dropdown anchors below the button that opened it. Add the class .top, .right, or .bottom to the dropdown to change this."
2. add the code from manual to web page (http://foundation.zurb.com/sites/docs/dropdown.html)
3. try to position drop down panel to bottom right side with "bottom right"
4. it aligns panel to top right, not bottom right 

You can see live example here
http://codepen.io/zlatiborac/pen/wGKNwe

**Comment by Deckluhm** [comment]
You can't combine classes like you do, you need to choose one (and only one) of them.

When you add `bottom` and `right` classes together, `bottom` is ignored and only `right` is taken into account.

If you want to understand how it works: https://github.com/zurb/foundation-sites/blob/develop/js/foundation.dropdown.js#L77

I tried to do the exact same thing 2 days ago and I agree it could be cool to modify how dropdown positioning works to be able to achieve this kind of positioning!

**Comment by zlatiborac** [comment]
If so then I suggest modifying the manual so others don't fall into the same trap.
