### ISSUE TITLE
Accordion Menu events not firing.

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#8363]
**How can we reproduce this bug?**

Create an accordion menu and target container for with events.

**What did you expect to happen?**

The event binding should fire, logging to the console.

**What happened instead?**

Nothing.

**Test case:**

http://codepen.io/christianmagill/pen/GZoxjx

**Comment by colin-marshall** [comment]
You have the wrong element selected in your JavaScript. You need to select the `<ul>` with the `data-accordion-menu` attribute, not the parent container.

That being said, it looks like the events are still not firing when the correct element is selected.

**Comment by christianmagill** [comment]
Updated codepen... Targeting the <ul> doesn't change the situation.

Also I believe the events should bubble. It bubbles properly for the normal accordion component.

http://codepen.io/christianmagill/pen/GZoxjx

**Comment by Deckluhm** [comment]
The documentation is incorrect:
- `down.zf.accordionmenu` should be `down.zf.accordionMenu`
- `up.zf.accordionmenu` should be `up.zf.accordionMenu`

(note the capitalized `M`)

**Comment by christianmagill** [comment]
Thanks

**Comment by rafibomb** [comment]
@Deckluhm Are you able to edit the docs for a quick PR? Thanks!

**Comment by colin-marshall** [comment]
@rafibomb I don't think we can just edit the docs for this because this is a JavaScript event and those are generated automatically from the code.

**Comment by Deckluhm** [comment]
@rafibomb I tried to edit the docs yesterday but I discovered what @colin-marshall said. I will investigate this and submit a PR if I find the culprit.

**Comment by gakimball** [comment]
Thanks for the pull request, @Deckluhm :) The way JSDoc wants you to write events doesn't quite mesh with our namespacing approach, which is why the formatting for the event names are sometimes off.

I just re-deployed the docs with these fixes, thanks all!
