### ISSUE TITLE
[The Grid] No option to add "expanded" as a behavior of a row using the grid-row include values

### ISSUE THREAD

**Issue by lgucci** [zurb/foundation-sites#8365]
Want to write critical-path css for my header where I need the sections to be "full bleed" or 100% of the viewport. The default is to add "expanded" as a class to the row, but I want to write this semantically for my critical path css.

1. http://foundation.zurb.com/sites/docs/grid.html#grid-row - grid row Sass Reference

**What did you expect to happen?**
.my-div {
@include grid-row(null, null, none, true, $grid-column-gutter);
}

= compiler gives error, 5 values defined in line X and only 4 are accepted.
Documentation clearly states 5 values are required in the @include

$width does not accept "none" as a value, which would mimic the "expanded" class.

Question, if we want to use the default, can we just use a regular , comma seperator with no value before it?

**Comment by gakimball** [comment]
I pasted your exact example and didn't get any errors. What version of Foundation are you using?

**Comment by kball** [comment]
Closed based on lack of response.  If you're still seeing this issue, please reopen with more info.
