### ISSUE TITLE
Specificity of the placeholder styles...

### ISSUE THREAD

**Issue by LDigital84** [zurb/foundation-sites#8366]
Is there a reason for the specificity of the placeholder styles? IE:  

```
input::-webkit-input-placeholder,
textarea::-webkit-input-placeholder {
  color: #cacaca; }

input::-moz-placeholder,
textarea::-moz-placeholder {
  color: #cacaca; }

input:-ms-input-placeholder,
textarea:-ms-input-placeholder {
  color: #cacaca; }

input::placeholder,
textarea::placeholder {
  color: #cacaca; }
```

I have to use `!important` to override these styles because I do not use `input` before the style. Is there a reason I should be using `input` to style the placeholder? Why not use this: 

```
::placeholder{
  color: #cacaca; }
```

If there is a reason, I'd love to know so I can improve my code. :)

Also, in my opinion, the color is too light and should be a touch darker.

**Comment by gakimball** [comment]
Makes sense, if you want to write a PR we can pull it in.

As for the color, we have three standard shades of gray we use. As I recall, the `$medium-gray` was too dark, which is why we went with `$light-gray`.

**Comment by Lynda333** [comment]
No worries on the color, that's more of an opinion and one that is easy to override. I'll look at a PR for this but I'm swamped for the next few days so anyone is welcome to go ahead. :)

**Comment by colin-marshall** [comment]
@ncoden @brettsmason is it ok to close this one out?

**Comment by ncoden** [comment]
This is generated there: https://github.com/ncoden/foundation-sites/blob/85c4e889ab8b1ab7ebda94fbc723330402191683/scss/forms/_text.scss#L143

I think we should resolve this issue. I'll submit a PR.
