### ISSUE TITLE
[Toggler] Dropdown Pane not toggling

### ISSUE THREAD

**Issue by EFXPROMedia** [zurb/foundation-sites#8367]
**How can we reproduce this bug?**

If I have 2 or more elements that is hoverable it crashes and cannot toggle for the second time.

I currently have on my page:

1X dropdown menu
1X accordion menu
1x toggle element 

these are all hoverable effects, on my console i have  a message "Tried to initialize toggler on an element that already has a Foundation plugin."

I verified the codes and can really figure out the cause of it.

Any Suggestions?

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.

**Comment by rafibomb** [comment]
Some of the markup would help reproduce it here. Can you add it to this codepen that already has Foundation loaded? http://codepen.io/rafibomb/pen/grrbEp

**Comment by EFXPROMedia** [comment]
I can give you a link to where its having problems..

Please use [this link](http://www.bestkilts.com/best-value-mens-kilts/best-value-scottish-5-yard-kilt-black-watch)

I verified quite all and no errors on log on google inspector.

**Comment by kball** [comment]
Can you explain which elements in that page are misbehaving in what way?  What would be most helpful would be adding an isolated testcase in the codepen

**Comment by claytron5000** [comment]
I have the same issue occurring on a site in development. Unfortunately, it doesn't reproduce in a blank codepen, and the example from the foundation docs doesn't work on my site. Obviously it's something on my site, but I'm unsure how to start debugging the issue. Any suggestions?

**Comment by EFXPROMedia** [comment]
I had a conflict with javascript never found really the exact source of it but I suggest to test all plug ins in the page there will be something conflicting. although since version 6.2.2 it works better

**Comment by claytron5000** [comment]
The solution that worked for me was including the dependent library `what-input` to my build.
