### ISSUE TITLE
Right Side Topbar Menu with Sub Menus Overlays Main Menu 6.2

### ISSUE THREAD

**Issue by 4shoda** [zurb/foundation-sites#8371]
I updated my project to 6.2 and now I have a problem with my top bar menu. Part off my top-bar is a right side menu with a sub menu. For some reason, the sub menu is now popping ON TOP OF the first drop down menu and not all the way to the left as I would like. Is there a setting or is this a bug? 

![3-4-2016 12-48-09 pm](https://cloud.githubusercontent.com/assets/15792665/13579330/c58a1366-e451-11e5-869d-86ffa5a97428.png)
![3-4-2016 12-52-08 pm](https://cloud.githubusercontent.com/assets/15792665/13579331/c58ac63a-e451-11e5-8aa7-bb8d4682eb59.png)

As you can see from the second image, the product support menu now shows up on top of the other menu and it is impossible to access the menu items below it. I suspect there is a js data option I can pass to tell it to go all the way to the edge of the drop down menu and open to the left but I can't seem to figure out where to put it. This should be calculated automatically though? 

Any help please?

**Comment by JeremyEnglert** [comment]
Does it only happen to menus near the edge of the browser or all drop down menus? Could be an edge detection issue.

**Comment by abdullahsalem** [comment]
You are right @4shoda.
@JeremyEnglert It happens wherever the submenu touches the edge.
**Example**: http://codepen.io/abdullahsalem/pen/ONNgJz

**Comment by abdullahsalem** [comment]
@gakimball I think it already has been fixed in the current **develop** branch.

**Here is a quick test**:
![f6-2-1-submenu](https://cloud.githubusercontent.com/assets/177020/13628629/aab8ab58-e5e4-11e5-84e0-93d6105ca6e6.png)

**Comment by gakimball** [comment]
Yep, this test case shows that the issue has been fixed: <https://github.com/zurb/foundation-sites/blob/develop/test/visual/dropdown-menu/basic-dropdown-menu-rtl.html>

**Comment by 4shoda** [comment]
Thanks so much. I will download the patch when it is out. In the meantime I have a lot of other work. Just wanted to be sure it was being fixed. :+1:
