### ISSUE TITLE
Manually trigger invalid event for individual field

### ISSUE THREAD

**Issue by depiction** [zurb/foundation-sites#8378]
I'm trying to do server side validation on two fields within a form on keyup to ensure that the user doesn't already exist. It doesn't look like I'll be able to do this because I can't manually trigger a field as invalid.

I'm using Foundation 5.5.3. If I go to http://foundation.zurb.com/sites/docs/v/5.5.3/components/abide.html, open the console, then type in the following code, nothing happens.

$('input#url').trigger('invalid.fndtn.abide');

The element is printed in the console, but the error state isn't set on the url field in the sample form. I'd expect the url field's label to turn red and it's error message to appear.

**Comment by colin-marshall** [comment]
@depiction very sorry for the late response to your issue. We are moving on to Foundation 7, and there will be no more development or support for Foundation 5. I am closing this one out.
