### ISSUE TITLE
[Reveal] Documentation typo?

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#8381]
I think there is a typo, the comma should be removed by the methods?

For example:  `$('#element').foundation('open', );`

http://foundation.zurb.com/sites/docs/reveal.html#js-functions

**Comment by gakimball** [comment]
That function has no parameters so it shouldn't have a comma at all. The issue will be in the [Handlebars helpers](https://github.com/zurb/foundation-docs/tree/master/lib/handlebars) that build the documentation.

**Comment by gakimball** [comment]
Fixed via zurb/foundation-docs#2. Thanks @Deckluhm!
