### ISSUE TITLE
SyntaxError: class is a reserved identifier

### ISSUE THREAD

**Issue by Silur** [zurb/foundation-sites#8383]
**How can we reproduce this bug?**

1. Step one
include foundation.core.js and foundation.equalizer.js to my project

**What did you expect to happen?**
equalizer loading succesfully
**What happened instead?**
producing error `SyntaxError: class is a reserved identifier` on `class Equalizer {` and completely breaking my site

Firefox 44.0.2, Arch linux

**Comment by gakimball** [comment]
Are you using a build system? As of Foundation 6.2 you'll need to add Babel to it. We have an [upgrade guide](https://github.com/zurb/foundation-sites/wiki/Upgrading-to-Foundation-6.2) that breaks it down.

**Comment by Silur** [comment]
Yes I'm using webpack I've added babel to my vendor dependencies that solved it thanks!

**Comment by gakimball** [comment]
Awesome, good to hear :)
