### ISSUE TITLE
Button groups can't expand if the spacing is zero

### ISSUE THREAD

**Issue by arnaudriegert** [zurb/foundation-sites#8384]
When I set `$buttongroup-spacing` to 0, the width of buttons is defined to `calc(X% - 0)`, which is deemed invalid at least in Google Chrome.
We should consider this special case in the [calculation of the width](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_button-group.scss#L87).

I'd be happy to submit a PR but I'm quite new to contributing to open source projects. If all I have to do is fork the project, update `_button-group.scss`, commit on the `develop` branch and submit the PR, I can do it right away. Otherwise I'd love some guidance. For instance, I don't know if I'm also supposed to update the dist files (the guidelines don't seem to mention it).

**Comment by andycochran** [comment]
Ooh. I wrote that. Guess it's my bug. I'll squish it. Good catch.

**Comment by andycochran** [comment]
Note, zero works when a unit is provided (e.g. `0px`). So we just needed a special case for plain zero.

**Comment by gakimball** [comment]
Merged #8388. Thanks @andycochran!
