### ISSUE TITLE
.bowerrc file is unnecessary.

### ISSUE THREAD

**Issue by echavezNS** [zurb/foundation-sites#8386]
I see that in the `.bowerrc` file there is just one option:

``` json
{
  "directory": "bower_components"
}
```
By default, **bower** install all the dependencies in a **bower_components** folder, if this directory doesn't exist, then It's created. So, I think in this case the file **.bowerrc** is useless.

**Comment by gakimball** [comment]
We've had issues with folks with older versions of Bower (or a version of Bower configured differently) accidentally installing dependencies into a folder with a different name (like `vendor/`) and then committing those files. It *should* be unnecessary, but to be on the safe side we lock the folder name.
