### ISSUE TITLE
[Starter Projects] Node modules not installed

### ISSUE THREAD

**Issue by brightonmike** [zurb/foundation-sites#8392]
**How can we reproduce this bug?**

1. Run: foundation new --framework sites --template zurb

**What did you expect to happen?**

The template would be correctly downloaded.

**What happened instead?**

The installation throws up an error "Node modules not installed".

If you attempt to run Foundation Watch, it bails out and says:
Failed to load external module babel-register
Requiring external module babel-core/register

I've tried installing modules manually, including babel-register. This just causes numerous other issues. I believe this is the same issue as: https://github.com/zurb/foundation-sites/issues/8256

I've ran through that thread but can't resolve.

**Comment by brightonmike** [comment]
Ok - somehow I managed to get things working adding:

`"babel-register": "^6.5.2",`

to package.json straight after babel core.

Previously I was installing babel-register via npm - this does not seem to solve the issue. It installs version 6.7.2 so not sure if that's why.

I still get the error about requiring external module babel-register but gulp seems to run fine.

**Comment by gakimball** [comment]
That error comes up on older Node versions but doesn't affect Gulp.

So it sounds like you got it working? Let me know if you're running into any other issues :)

**Comment by york-xtrem** [comment]
I thought this would solve my problem :(
https://github.com/zurb/foundation-sites/issues/9302
