### ISSUE TITLE
[6.2 Sticky] Destroy errors out when "anchor" is not specified

### ISSUE THREAD

**Issue by acarnwath** [zurb/foundation-sites#8393]
When using something like this:
```
<nav class="sticky-nav" data-sticky-container id="container">
	<div data-stick-to="bottom" data-top-anchor="page" data-btm-anchor="container:bottom">
		Sticky Stuff
	</div>
</nav>
```
```
$('.sticky-nav').foundation('destroy');
```

Get an error:

> Uncaught TypeError: Cannot read property 'off' of undefined

It originates from this line: `this.$anchor.off('change.zf.sticky');`

And can be fixed by checking if $anchor is populated (as is done elsewhere in the code) before removing the event listener 
```
if (this.$anchor && this.$anchor.length) {
    this.$anchor.off('change.zf.sticky');
}
```

**Comment by dragthor** [comment]
I am going to try to look into this and address it. Thanks for let us know.
