### ISSUE TITLE
Abide reflow in F6 not working?

### ISSUE THREAD

**Issue by Boduje** [zurb/foundation-sites#8395]
I have a form for changing the status of a product order.  I have two fields, "Tracking Number" and "Carrier" that are disabled until the option "Shipped" is selected.  Those two fields are also required.

When I select "Shipped", the disabled property is set to false and I run the reflow. Abide correctly shows errors if I leave the two fields blank.

However, if I do not put values in and then change the select option to anything other than "Shipped", the fields' disabled property is then set back to true and the form is reflowed again.

It seems that the second reflow is breaking the form because the submit button does nothing after that.

I could just be overlooking something easy, but it is driving me crazy.

**Comment by colin-marshall** [comment]
@Boduje sorry for _extremely_ late response. Is this still an issue? If so, please provide us with a reproducible test case using one of the following CodePens:

- [CodePen with Foundation 6.4.1, XY Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/EXbGKJ)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with RTL Direction and MotionUI](http://codepen.io/IamManchanda/pen/qjVLoO)
- [CodePen with Foundation 6.4.1, XY Flexbox grid with Prototype Mode and MotionUI](http://codepen.io/IamManchanda/pen/XgzopG)
- [CodePen with Foundation 6.4.1, Float Grid and MotionUI](http://codepen.io/IamManchanda/pen/qjVLrB)

**Comment by ozzywadd** [comment]
Same issue for me.

I rely on the" formvalid.zf.abide" event being triggered in my codebase before calling another submit function but the new implementation of reInit e.g. "Foundation.reInit('abide');" is clearing down the event listeners I have on my forms. NOTE: I apply these listeners directly to the abide form element as there are many cases where I have multiple forms on one page.

Are the abide events not meant to be attached at the form element level? @martinschilliger seems to have done the same as me.

**Comment by martinschilliger** [comment]
IMHO there is no way to prevent reInit of clearing the event listeners – isn't it?. It's because they _are_ attached at the form element level – so with reInit removing and new building the form they get removed. But with the solution I've written this isn't a problem anymore (made it a bit clearer btw.).

**Comment by DanielRuf** [comment]
Is there something that we can do in the core?

**Comment by martinschilliger** [comment]
Since it's IMHO not possible to transfer the event listeners to the new element after`reInit` (and I'm not shure if it would be a good idea anyway) the only thing that could be done is a note in the documentation.

**Comment by DanielRuf** [comment]
> After `Foundation.reInit($("[data-abide]"));` it stopped working, because reInit removed the event-listener from the form element. Binding the event-listener to the document and selecting afterwards did the trick:
> 
> ```js
> $(document).on("formvalid.zf.abide", "#theForm", function() {
>   mySubmitFunction();
> });
> ```

Generally this is the right approach to listen for dynamically added elements.
