### ISSUE TITLE
[Tooltips] Foundation6 Tooltips title doesn't support html content anymore

### ISSUE THREAD

**Issue by manish21sharma** [zurb/foundation-sites#8401]
Hi ,

I have used Foundation5 tooltip and just provide the html content in title element and now we are converting it into Foundation6 and facing issue that title tag is not support html tag any more.

Thanks

**Comment by Deckluhm** [comment]
The solution is pretty simple (replace jQuery `text(content)` by `html(content)`) but there are some security concerns with this solution.

A PR is already opened for this issue (#8075).

**Comment by kball** [comment]
A fix for this as an option was implemented here: https://github.com/zurb/foundation-sites/pull/8527 and will be in 6.3.0.
