### ISSUE TITLE
[Foundation for Sites] title-bar

### ISSUE THREAD

**Issue by daren8888** [zurb/foundation-sites#8407]
**How can we reproduce this bug?**
1. Step one: sjlc.web4uinc.com
2. Step two: shrink browswer til the hamburger comes up
3. Step three: click hamburger

**What did you expect to happen?**
The DARK GREY background to the "menu" should ONLY extend just beyond the last item in the list.

**What happened instead?**
The DARK GREY background to the "menu" is SUPER LONG... it extends to the length of the LONGEST list even when the longest list isn't visible (to see the longest list click CLASSES, then GROUP CLASSES). The menu should only open as much as the VISIBLE LIST

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.www.sjlc.web4uinc.com

**Comment by JeremyEnglert** [comment]
I'm fairly certain this was fixed in an update as I can not reproduce and the test link is working correctly.

**Comment by daren8888** [comment]
www.sanjoselearningcenter.com the above link was for dev. It's live now
