### ISSUE TITLE
Off Canvas like jQuery mmenu

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#8408]
I had always used the the jQuery.mmenu for off-canvas purposes. But I would like to move completely to foundation if possible. How crazy is it to make the off canvas plugin behave more like the mmenu? Like adding options to slide on the canvas as well and having a good integration of a drilldown menu? 
Here you can see the mmenu: http://mmenu.frebsite.nl/ 

:+1:  :-1:  ?

**Comment by gakimball** [comment]
Which features specifically are you looking for?

**Comment by rafibomb** [comment]
The off-canvas menu container is an empty box. The existing drilldown menu, accordion menu integrate nicely in the off canvas. If there is another feature you're missing, let us know in a new issue!
