### ISSUE TITLE
[6.2.0] top-bar-right doesn't work with foundation-flex

### ISSUE THREAD

**Issue by hylke94** [zurb/foundation-sites#8409]
The alignment of the top-bar-right class doesn't work correctly when including the [foundation-flex.min.css](https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.0/foundation-flex.min.css) file.

**How can we reproduce this bug?**
1. Create a div with class "top-bar".
2. Inside top-bar create a div with class "top-bar-title" (or "top-bar-left").
3. Inside top-bar create a div with class "top-bar-right".

**What did you expect to happen?**
The div with class top-bar-right aligns to the right.

**What happened instead?**
The div with class top-bar-right align to the center of the top-bar.

**Test case:**
[JSFiddle](https://jsfiddle.net/1wxvjq4o/)

**Comment by hylke94** [comment]
The same issue is on a "row align-justify" div. The second div doesn't align to the right, but somewhere in the middle ([JSFiddle](https://jsfiddle.net/r9su0wh1/)).
"align-spaced" also doesn't work properly.

**Comment by lucianosemerini** [comment]
It happens to me too, any workaround?

**Comment by sculler** [comment]
You can fix like this:

`.top-bar .top-bar-left, .top-bar .top-bar-right {
    flex: none;
}`

**Comment by hylke94** [comment]
Is this issue fixed in the 6.2.1 release of yesterday?

**Comment by hylke94** [comment]
Nope. The top-bar-right is now full-width (beside the top-bar-left/title) and aligns to the left. And the "row align-justify" acts like "row align-spaced".

**Comment by DaSchTour** [comment]
Time to release 6.2.2 :stuck_out_tongue_winking_eye:

**Comment by hylke94** [comment]
As shown in this [JSFiddle](https://jsfiddle.net/1wxvjq4o/2/), above 'fix' doesn't fix the issue completely. The alignment is somewhat better, but now they also align towards the middle...

The same for the second issue, alignment in a ['align-justify' row](https://jsfiddle.net/r9su0wh1/1/)...

**Comment by cabelodomato** [comment]
Check out the solution given by sculler.

It worked for me!

**Comment by hylke94** [comment]
Not in my JSFiddle tests... 

How is your code, @cabelodomato ?

**Comment by Lesha-spr** [comment]
@hylke94 ,
Seems :before/:after pseudo-elements are the breakers. You should remove non-flex Foundation from Resources.

**Comment by hylke94** [comment]
@Lesha-spr 
That fixed the 'align-justify' indeed, but for the top-bar I still need te set flex to none as show in [this JSFiddle](https://jsfiddle.net/Hylke94/4s3sjy2n/2/).

No idea who writes/updates the docs, but maybe it is a good idea to mention this (removing the standard css sheet) ( @gakimball  or @rafibomb  maybe?)...

**Comment by Lesha-spr** [comment]
@hylke94 ,

Yes, top-bar is still (6.2.3) broken. I was talking about your fiddle where is an extra non-flex Foundation source which breaks the fix.

Also as I can see the fix is already merged to 6.3.

**Comment by rafibomb** [comment]
@hylke94 The docs are in a folder as part of this repo. You can submit PR's to change it or make a suggestion on an issue. Thanks!

**Comment by hylke94** [comment]
My english isn't that good. So maybe someone else wants to edit the docs?
