### ISSUE TITLE
Accordion menu component firing a multitude of events.

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#8411]
**How can we reproduce this bug?**
1. Step one
   Use an accordion menu and setup an event handler for up and down events on a container which logs the event to console. 
2. Step two
   Toggle accordion menu item.
3. Step three
   Look at console

**What did you expect to happen?**
A single event per toggle.

**What happened instead?**
Several events per toggle

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

Simplified
http://codepen.io/christianmagill/pen/QNGQOy

More Complex Example
http://codepen.io/christianmagill/pen/JGeeMw

**Comment by getup8** [comment]
I'm seeing the same behavior for tabs and

```
  $('#tab-container').on('change.zf.tabs', function (event, tab) {
    console.log(event);
    console.log(tab);
  });
```

It fires 3 times on a tab change.

**Comment by DanielRuf** [comment]
I see just one line per toggle. Which browser was used for testing?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback.
