### ISSUE TITLE
[Off-canvas] Exit div not being created

### ISSUE THREAD

**Issue by dmcgrew** [zurb/foundation-sites#8412]
**How can we reproduce this bug?**

Not sure how exactly, but this is what I have for my off-canvas menu..

```
<div class="off-canvas position-right" id="offCanvas" data-off-canvas data-position="right" data-close-on-click="true">
      <!-- menu goes here -->
</div>
```

**What did you expect to happen?**

 I expected to have the following div created with javascript. This functionality works in another Foundation site I created about 2 months ago. That is currently using Foundation version 6.1. The new site I'm working on is using the latest version (6.2). 

```
<div class="js-off-canvas-exit is-visible"></div>
```

**What happened instead?**

The div wasn't created.

**Comment by cereallarceny** [comment]
I can see this as well.  The exit div is created when running `foundation watch` from the CLI, but upon running the `foundation build` command (identical to saying `gulp build --production`) then we notice the issue.  This is a huge problem in my opinion.  It means that all off-canvas menus are completely unusable in production circumstances.

I'd suggest this be hot-fixed.

**Comment by cereallarceny** [comment]
Any news here?

**Comment by brettsmason** [comment]
@cereallarceny Sorry nobody got back to you on this.
Is this still an issue with the current version for you?

**Comment by brettsmason** [comment]
I'm going to close this we we didn't hear back. Off canvas has been re-written for 6.3 and won't have this issue. If you still have an issue please feel free to re-open.
