### ISSUE TITLE
Off-canvas slider + fixed top-bar = problem

### ISSUE THREAD

**Issue by ErnestBrandi** [zurb/foundation-sites#8414]
**How can we reproduce this bug?**

Get an off-canvas slider, get a top-bar, set this top-bar as fixed.

**What did you expect to happen?**

Everything should work fine, but this is not the case in the lastest chrome version!

**What happened instead?**

The top-bar get troubles to follow the slider opening/closing...

**Comment by createproblem** [comment]
:+1: Same issue

**Comment by FauzanKhan** [comment]
@gakimball - I wrote a quick fix for this problem

```javascript

;(function() {
  var $mobileNav = $('.your-fixed-navbar');
  var $offCanvasContent = $('.off-canvas-content');
  var mobileNavHeight = $mobileNav.outerHeight();
  var canvasCloseTimeout;

  $(document).on('closed.zf.offcanvas', function(){
    clearTimeout(canvasCloseTimeout);
    canvasCloseTimeout = setTimeout(function(){
      $mobileNav.css('position', 'fixed');
      $offCanvasContent.css('padding-top', mobileNavHeight);
     }, 500);
    });

    $(document).on('opened.zf.offcanvas', function(){
      $mobileNav.css('position', 'static');
      $offCanvasContent.css('padding-top', 0);
    });
})();

```

Also you might want to close this thread and redirect it [here](https://github.com/zurb/foundation-sites/issues/8803) or vice versa.

**Comment by brettsmason** [comment]
This should now work correctly in version 6.3. The release candidate is currently out for testing, with the final version out in a few weeks.

Closing this, but if you have any issues with this in 6.3 please re-open.
