### ISSUE TITLE
$element is undefined When using Reveal with Animations

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#8415]
I get this error: 

    TypeError: $element is undefined

Anytime I open a reveal modal I get this error. It tells me the problem is at line 661 of the Foundation.js file. This is the code block it says the problem comes from:

       /**
         * Finds all focusable elements within the given `$element`
         * @param {jQuery} $element - jQuery object to search within
         * @return {jQuery} $focusable - all focusable elements within `$element`
         */
        findFocusable: function ($element) {
          return $element.find('a[href], area[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), iframe, object, embed, *[tabindex], *[contenteditable]').filter(function () {
            if (!$(this).is(':visible') || $(this).attr('tabindex') < 0) {
              return false;
            } //only have visible elements and those that have a tabindex greater or equal 0
            return true;
          });
        },

The reveal still works correctly.

I discovered that this doesn't happen when a normal reveal is triggered. This does happen when you are using Motion UI on a reveal. 

Here is the issue recreated: http://codepen.io/Lynda333/pen/BKQEPO

**Comment by Owlbertz** [comment]
I will have a look.

**Comment by gakimball** [comment]
Thanks @Owlbertz :)

**Comment by Owlbertz** [comment]
Yo @gakimball, looks like you fixes this already yourself: https://github.com/zurb/foundation-sites/commit/6df453b555e30c804490d93013216ceb0f7cc2a6. Nothing to do here.

**Comment by gakimball** [comment]
Thought so, didn't have time to check :)
