### ISSUE TITLE
Faulty selector in "on" function in magellan for versions >5.5.1 and <6

### ISSUE THREAD

**Issue by kh0r** [zurb/foundation-sites#8416]
When I click on links I get `Uncaught Error: Syntax error, unrecognized expression: [data-magellan-arrival] a[href*=#]` in current versions of Chrome, Safari and Firefox for version 5.5.3

I found the reason: in [the magellan src file for v5.5.3](https://github.com/zurb/foundation-sites/blob/v5.5.3/js/foundation/foundation.magellan.js#L35) the selector `a[href*=#]` has missing quotation marks. See https://api.jquery.com/attribute-contains-selector/

v5.5.1 had them: https://github.com/zurb/foundation-sites/blob/v5.5.1/js/foundation/foundation.magellan.js#L35

Reverting to v5.5.1 resolved my issue

**Comment by neonardos** [comment]
This solve the issue, thanks!

**Comment by peteroid** [comment]
Confirmed this bug with foundation 5.5.3

**Comment by darolo** [comment]
The correct selector is **a[href*="#"]**. Change it yourself in magellan script.

**Comment by colin-marshall** [comment]
Very sorry for the late response to this issue. We are moving on to Foundation 7, and there will be no more development or support for Foundation 5. I am closing this one out.
