### ISSUE TITLE
Backticks causing issues with JS minification

### ISSUE THREAD

**Issue by dmcgrew** [zurb/foundation-sites#8419]
Not really sure why all of the single quote marks were replaced with backticks. Is there some advantage to doing that? Never saw backticks used like this before. I use Codekit to install Foundation and do all of my SASS and JavaScript compiling/minifying. I just updated one of my projects to 6.2 and now I can't minify my javascript because uglify.js gets hung up on the backtick characters. 

    Minification failed:

    Parse error at /Applications/MAMP/htdocs/project/wp-content/themes/project/bower_components/foundation-sites/js/foundation.core.js:56,29
    Unexpected character '`'

**Comment by colin-marshall** [comment]
@dmcgrew we rewrote the JavaScript in 6.2 with ES6. It now needs to be transpiled back to ES5 using Babel, so you have to add that step in your build pipeline.
http://foundation.zurb.com/sites/docs/javascript.html#babel-required

Here's an article on how to set up Babel with CodeKit:
http://useless.today/codekit-babel/

**Comment by dmcgrew** [comment]
Ugh. Guess I'm screwed until Codekit releases an update. Looks like they're working on including Babel.

**Comment by colin-marshall** [comment]
You can always use Gulp in the meantime, or rollback the Foundation update.

**Comment by gakimball** [comment]
In the next patch (6.2.1) we'll have pre-compiled versions of each plugin, so you'll be good then.

**Comment by michaelaflores** [comment]
I'm unexpectedly experiencing this issue with Foundation 6.3.1 and Foundation 6.4.3 (I have tried both). I have an app set up with `create-react-app` which transpires via Babel with the following Babel config:
```
    "presets": [
      "react",
      "es2015",
      "stage-1"
    ]
```
Builds are no longer successful and instead I get this error:

> Failed to compile.
> 
> Failed to minify the code from this file: 
> 
>  	./node_modules/foundation-sites/js/foundation.util.core.js:24 
> 
> Read more here: http://bit.ly/2tRViJ9
> 
> error Command failed with exit code 1.
