### ISSUE TITLE
[Orbit] ios ipad 1 Safari animation fallback

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8420]
Orbit change slide does not work on ios ipad 1 on stock Safari Browser, maybe a Fallback for not presented css animations would be nice

the orbit without animations on the docs slide works

**Comment by JeremyEnglert** [comment]
Is this still an issue? What version of iOS?

**Comment by DanielRuf** [comment]
Could have been Safari 9 which we do not officially support in 6 I guess.
Safari 9 had many bugs and issues related to CSS transitions.

https://en.m.wikipedia.org/wiki/Safari_version_history

**Comment by DanielRuf** [comment]
Closing as we do not support this old iOS and mobile Safari version.
