### ISSUE TITLE
[F 6.2] disable responsive behaviour

### ISSUE THREAD

**Issue by xfifix** [zurb/foundation-sites#8422]
I want to disable the responsive behaviour in Foundation 6.2, How to do this ??

**Comment by echavezNS** [comment]
You should download a custom Foundation without the grid, select the radius button with the option **No Grid**.

![image](https://cloud.githubusercontent.com/assets/17257421/13842076/8d67894c-ebe9-11e5-8ada-473dece693f7.png)

**Comment by xfifix** [comment]
i want to keep the behaviour in large ...

**Comment by Owlbertz** [comment]
Maybe you could adjust the breakpoints in the SASS so the smallest breakpoint is at 1440px or something.

**Comment by DaSchTour** [comment]
Wait for 6.2.1
Rename your smallest breakpoint to "grid" or what ever you want and just use the smallest grid.

**Comment by echavezNS** [comment]
Add the same amount of columns to each elements in each breakpoint:
```html5
<div class='row'>
   <div class='large-12 medium-12 small-12'>
   </div>
</div>
```

May be this could fit to you, but I'm not really sure of what are you looking for.

**Comment by DaSchTour** [comment]
I think it's enough to only use the smallest breakpoint, as I asume all bigger breakpoints use the values from the smaller if not present.
This
```
<div class='row'>
   <div class='large-12 medium-12 small-12'>
   </div>
</div>
```
can be reduced to this
```
<div class='row'>
   <div class='small-12'>
   </div>
</div>
```

**Comment by echavezNS** [comment]
Is that what you wanted @xfifix ? if yes, can you please close this issue?

**Comment by kball** [comment]
Looks like this has been answered.  If not, please re-ask in the forum rather than on github: http://foundation.zurb.com/forum
