### ISSUE TITLE
Joyride 3.0

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#8423]
@Owlbertz will be leading the charge on shipping a new version of Joyride compatible with Foundation 6. This is the first plugin we'll be maintaining outside of the Foundation core, at [zurb/joyride](https://github.com/zurb/joyride).

Here's what needs to get done before it's finished:
- [x] JavaScript updated to ES2015
- [x] Unit tests written (following the [format](https://github.com/zurb/foundation-sites/blob/develop/test/javascript/components/toggler.js) we've established here)
- [x] Auditing accessibility
- [x] Adding UMD wrapper (added by Owlbertz)

Before the final release is tagged, we'll also need to clean out the existing issue tracker. We no longer maintain the standalone versions of Joyride 1/2 anyway.

**Comment by Owlbertz** [comment]
All these things are addressed in the [Joyride repository](https://github.com/zurb/joyride/tree/develop). I will close this issue since any Joyride related stuff should be discussed over there.

**Comment by celleyes** [comment]
is it compatible with foundation 6?
