### ISSUE TITLE
Request/ Proposal: Add SCSS variables for customizing margins for checkboxes, radiobuttons, inputs and select

### ISSUE THREAD

**Issue by uranuz** [zurb/foundation-sites#8424]
I propose to add seperate SCSS variables for specifying margins for elements like checkbox, radio, file inputs, text inputs and 'select'. So this is where variable $form-spacing is currently used for setting margins. By default these proposed variables would still be equal to $form-spacing, but user could change them in order to customize margin-bottom. For example I hate that margin-bottom is set for checkboxes. I have checkboxlists that are placed verticaly one by another. So the have ugly huge space in between, because of these margins. I think that if someone needs it it's simplier to add it in place where it needed than fight with these margins everywhere, because I need them only in 20% of cases. I could make PR myself if someone interested in this improvement. What do you think?

**Comment by colin-marshall** [comment]
Thanks for this feature request. We’re going to close out this ticket, as we will not be adding more features to Version 6, but your request is being considered for Version 7.
