### ISSUE TITLE
Javascript error in module foundation.util.nest

### ISSUE THREAD

**Issue by jmas** [zurb/foundation-sites#8429]
**How can we reproduce this bug?**
1. Use foundation JS with browserify and babel as `import` dependency
2. Make build, include builded `bundle.js` to web-page
3. Open browser and see javasceript error `foundation.util.nest.js:6 Uncaught SyntaxError: Unexpected token =`

**What did you expect to happen?**

Working `foundation.util.nest` module.

**What happened instead?**

Have javascript error `foundation.util.nest.js:6 Uncaught SyntaxError: Unexpected token =`

**PS**

Problem is described on StackOverflow: http://stackoverflow.com/questions/35705771/foundation-sites-6-javascript-order

**Comment by Owlbertz** [comment]
Well the error message comes definitely from a non-compiles ES6 file. Did import/use the correct plugins/presets for babel?

**Comment by jmas** [comment]
@Owlbertz

> Well the error message comes definitely from a non-compiles ES6 file. Did import/use the correct plugins/presets for babel?

I have following `gulpfile.js`:
```
var gulp        = require('gulp'),
    gutil       = require('gulp-util'),
    sass        = require('gulp-sass'),
    //csso        = require('gulp-csso'),
    //uglify      = require('gulp-uglify'),
    jade        = require('gulp-jade'),
    concat      = require('gulp-concat'),
    livereload  = require('gulp-livereload'), // Livereload plugin needed: https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei
    tinylr      = require('tiny-lr'),
    express     = require('express'),
    app         = express(),
    marked      = require('marked'), // For :markdown filter in jade
    path        = require('path'),
    server      = tinylr(),
    sourcemaps  = require('gulp-sourcemaps');

var browserify = require('gulp-browserify');
var babelify = require('babelify');
var babelPresetEs2015 = require('babel-preset-es2015');
var flatten = require('gulp-flatten');

var NODE_MODULES_PATH = './node_modules';
var FOUNDATION_PATH = NODE_MODULES_PATH + '/foundation-sites';
var FOUNDATION_JS_PATH = FOUNDATION_PATH + '/js';
var MOTION_UI_PATH = NODE_MODULES_PATH + '/motion-ui/src';

gulp.task('css', function() {
    return gulp.src('sources/assets/stylesheets/*.scss')
        .pipe(sourcemaps.init())
        .pipe(sass({
            includePaths: ['sources/assets/stylesheets', 'node_modules/foundation-sites/scss', MOTION_UI_PATH],
            errLogToConsole: true
        }))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('dist/assets/stylesheets/'))
        .pipe(livereload(server));
});

gulp.task('js', function() {
    return gulp.src('sources/assets/scripts/*.js')
        .pipe(sourcemaps.init())
        .pipe(browserify({
            debug: true,
            paths: [ NODE_MODULES_PATH, FOUNDATION_JS_PATH ],
            insertGlobals: true,
            ignore: ['jquery'],
            transform: [
                babelify.configure({
                    sourceMaps: true,
                    presets: [babelPresetEs2015]
                })
            ],
            extensions: ['.js']
        }))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('dist/assets/scripts/'))
        .pipe(livereload(server));
});

gulp.task('images', function() {
    return gulp.src('sources/assets/images/*')
        .pipe(flatten())
        .pipe(gulp.dest('dist/assets/images/'));
});

gulp.task('templates', function() {
    return gulp.src('sources/*.jade')
        .pipe(jade({
            pretty: true
        }))
        .pipe(gulp.dest('dist/'))
        .pipe(livereload(server));
});

gulp.task('express', function() {
    app.use(express.static(path.resolve('./dist')));
    app.listen(1337);
    gutil.log('Listening on port: 1337');
});

gulp.task('watch', function () {
    server.listen(35729, function (err) {
        if (err) {
            return console.log(err);
        }
        gulp.watch(['sources/assets/stylesheets/*.scss', 'sources/assets/stylesheets/partials/*.scss'], {follow:true}, ['css']);
        gulp.watch('sources/assets/scripts/**/*.js', {follow:true}, ['js']);
        gulp.watch(['sources/*.jade', 'sources/partials/*.jade', 'sources/layouts/*.jade'], {follow:true}, ['templates']);
    });
});

gulp.task('default', ['images', 'js','css','templates','express','watch']);
```

**Comment by dherran** [comment]
Your gulpfile looks fine to me. You are using Browserify with Babelify and the es2015 preset, however, you have to know that Babelify wont transpile code inside the **node_modules** folder unless it is specifically requested by the module. This is clearly stated here:

https://www.npmjs.com/package/babelify#why-arent-files-in-node_modules-being-transformed

You can set Babelify to run globally, and exclude the Node modules that you don't want to transpile. This is slow because you can have N+1 number of folders inside node_modules and the transpile task will take forever to finish.

Another option is to manually add Babelify to the package.json inside the node_modules/foundation-sites folder, however, it means that after every Foundation update, you will have to manually change the package.json again.

I have requested this to be looked at in #8351. In the meantime you can have a look at the snippet I pasted there to fix the issue right away.

**Comment by Owlbertz** [comment]
@jmas Any update?

**Comment by kball** [comment]
This should be resolved by the ability to pull things straight from the dist folder now, as described in #8351.
