### ISSUE TITLE
Project problem

### ISSUE THREAD

**Issue by protasisimone** [zurb/foundation-sites#8430]
'm creating a new site and would like to use as a framework Foundation 6.

I install Foundation with Bower and I am managing all from Grunt.

The problem that I see and I can not understand is:
With Bootstrap, always installed by Bower, I was copying the file with the "variables" and the global file of "import" by changing the paths to customize the "native" file that interested me, all to be able to update via the Bower framework without losing changes.

How can I do this with Foundation6?

Thanks for the clarification.

**Comment by jgacuca567** [comment]
@protasisimone please post your issue on Foundation Forum. Also when you do, post with the grunt files, I shall help you set up Foundation 6, with Bower and Grunt.

**Comment by iammichiel** [comment]
You can simply import it from the `bower_components` folder: 


```scss
@import "../js/app/bower_components/foundation-sites/scss/foundation";

// Define your variables here : 

// Core
@include foundation-global-styles;
@include foundation-grid;
@include foundation-float-classes;
@include foundation-visibility-classes;
... 
```

**Comment by protasisimone** [comment]
@iammichiel Thanks for ur reply, but if I don't want import the "grid" for example, I can't choose this, it's exactly?

**Comment by protasisimone** [comment]
@iammichiel Thanks for ur reply, it's all ok!

If i wanna change the global variables? How to do?

**Comment by iammichiel** [comment]
You can edit whatever you want. Read the documentation for more info. For instance, this page.  http://foundation.zurb.com/sites/docs/global.html

**Comment by protasisimone** [comment]
Non capisco, se io voglio modificare il file global.scss, me lo copio nella mia cartella custom e come lo richiamo?

`@import "../bower_components/foundation-sites/scss/foundation";
@import "../global"; // 

// Define your variables here : 

// Core
@include foundation-global-styles;
@include foundation-grid;
@include foundation-float-classes;
@include foundation-visibility-classes;
... `

**Comment by colin-marshall** [comment]
@protasisimone you should check out the [Sass Setup](http://foundation.zurb.com/sites/docs/sass.html) section of the docs. The only file you need to copy out of the `bower_components` directory is the `_settings.scss` file. Leave the `_global.scss` file in place.

**Comment by colin-marshall** [comment]
@protasisimone did this answer your question?

**Comment by protasisimone** [comment]
@colin-marshall sure, thanks for ur help.
Have a nice day.
