### ISSUE TITLE
Topbar unstack breakpoint

### ISSUE THREAD

**Issue by zlatiborac** [zurb/foundation-sites#8433]
If you want to change breakpoints of the top bar and changing default
`$topbar-unstack-breakpoint: medium;`
to
`$topbar-unstack-breakpoint: large;`
nothing happens, breakpoint is still set to medium.

**Comment by David-van-den-Bor** [comment]
Yes! I noticed this too :-)

**Comment by peter-hank** [comment]
@zlatiborac @David-van-den-Bor check the `title-bar` attribute called `data-hide-for`. It was an issue in my case. Should be set to an appropriate value too along with `$topbar-unstack-breakpoint`.

**Comment by brettsmason** [comment]
From looking at the codebase this looks like it should of been fixed so I'm going to close this.
If you are still having issues however please reopen! 😄
