### ISSUE TITLE
Wrong file name/path in the package Essential

### ISSUE THREAD

**Issue by gBaylaender** [zurb/foundation-sites#8439]
Hello, just a small issue when I download the package **Essential**:  http://foundation.zurb.com/sites/download/assets/essential-f6.zip

The script inside HTML index have the wrong name/path, is:  ` js/fondation.min.js `
but have to be: ` js/fondation.js ` because the file JS is ` foundation.js `

![screen-shot-2016-03-21-at-20 32 45](https://cloud.githubusercontent.com/assets/1658712/13931563/34251d04-efa4-11e5-9cc1-8fc77877fefd.jpg)

In any case, thanks!
Nice coding,

**Comment by colin-marshall** [comment]
@gBaylaender there are lots of issues with the Customizer which are being tracked in #7033. There is an open pull request (#8400) which should resolve all the Customizer issues. I'm closing this issue in favor of those. Thanks!
