### ISSUE TITLE
[Reveal] steals focus and key events

### ISSUE THREAD

**Issue by josh-h** [zurb/foundation-sites#8442]
First, thank you for Foundation, I appreciate all the work that you've put into this!

I am using a Reveal modal with the intent to show search results. If you are familiar with search in iOS' calendar then you'll have a good sense of the goal. If you that doesn't clarify then it's sufficient to know that the goal is to open a modal while retaining focus in a text field.

Surprisingly, opening the reveal modal removes the focus from a text input. I've tried to handle the 'open.zf.reveal' event to take focus back, but that results in a warning 'Component not defined!' inside of foundation.util.keyboard.handleKey and causes key events to be lost. Specifically the text input appears to have focus, but all typing is lost.

I understand that taking focus is intended for screen readers, however, I'm wondering if this could be made optional behaviour, or if somehow both goals could be achieved.

To demonstrate see http://codepen.io/anon/pen/LNWaQX and start typing in the text field. The first key press causes a modal to appear after which the text input appears to have the focus, but all key events are lost.

**Comment by josh-h** [comment]
It seems in foundation.reveal.js on line 339 in `_extraHandlers` the call to `e.preventDefault()` is what stops the key events propagating out of the reveal. Is stopping key events strictly necessary?

**Comment by Owlbertz** [comment]
Yes, this behavior is intended to properly support screen readers and keyboard access in general. But I guess that your use case is somewhat special and was therefore not considered during design. 

I will have a look at this one. I guess there should be a way using the events to move the focus back as you tried it or just a property to disable focus management. In either way you would have to track the tab-event by yourself and shift the focus into the modal (if this is a thing for you).

**Comment by Owlbertz** [comment]
Check out #8453. I also made some JS for in [this pen](http://codepen.io/Owlbertz/pen/qZmyoK).

**Comment by josh-h** [comment]
I added the changes from #8453 into my project and it works, thank you.

I had assumed, like you, we'd need to add a property to disable focus management, but with the change above the additional property is unnecessary for my use case. As reassigning focus on the event hook is sufficient.

**Comment by josh-h** [comment]
I've upgraded to 6.2.3 from my previously patched version that resolved the issue above and am seeing the issue described above again. That is, opening a reveal causes focus to be lost on input's that exist outside of the reveal.

I've forked the original pen from this issue to reproduce the problem, http://codepen.io/josho/pen/ezzjrv. This pen changes to the official foundation version and adds in motion-ui animation on reveal open.

When the reveal is animated open changing focus on the open event no longer works because the open event is called after the animation completes. The callback therefore occurs outside of the click event stack and the browser then ignores the javascript focus request.

I think we could fix this in one of two ways.
1. In the Reveal do not set the focus, i.e. starting at foundation.reveal.js:259 on master:
    // handle accessibility
    this.$element
      .attr({
        'aria-hidden': false,
        'tabindex': -1
      })
      .focus(); // Remove this call

The focus is taken for accessibility reasons. So rather than outright removal, perhaps we add a condition on this behaviour (not ideal), so that the focus is assigned to a specified element, e.g. data-open-focus.

2. Add a before open event for the reveal where we can set the focus before the animation occurs. Which opens a larger design question as I believe there are no other 'before' events in Foundation.

In the meantime I have two potential workarounds, I can patch foundation to remove the focus (accessibility is not important for our user base, yet), or disable the animation until this is fixed.

Thanks.

**Comment by josh-h** [comment]
Minor correction.

The line number where focus is stolen from the text field is 240 in the afterAnimationFocus() callback, not the regular accessibility handling as I pointed out above.

**Comment by Owlbertz** [comment]
Hi @josh-h, thank you for the detailed analysis.
If you think you can fix this issue, we are always happy to see a pull request!

**Comment by andycochran** [comment]
Interesting. I hadn't thought about Reveal being used this way. 

But I think the function of a modal inherently steals focus away from the main content. So Reveal probably isn't the right component for this use case. 

It could be done more simply with `.callout .hide` and a function to toggle the hide class. What do you think of an approach like this? http://codepen.io/andycochran/pen/NAjBKd

If the results need to be positioned like a modal, you could do that with app-specific styles (`position:absolute`). But I notice you've actually removed the overlay to make it behave even less like a modal—which again makes me think Reveal is the wrong component. 

Can anyone think of an instance where Reveal would need to behave exactly as it does out-of-the-box, except for stealing focus?

**Comment by kball** [comment]
I would tend to agree that perhaps reveal isn't the right component for this behavior... I'd be inclined towards a callout, though I've also implemented behavior somewhat like this with dropdowns.

My inclination is to close this as a 'wontfix'.  @josh-h I do want to make sure you found a solution for your usecase though... did you get this working in some form?

**Comment by andycochran** [comment]
Agreed, @kball. I'll go ahead and close this. However, @josh-h, please feel free to continue the conversation if you still need help.

**Comment by zacksmash** [comment]
Super late to the party, but I am still having issues with this. I came up with an incredibly lame workaround, if anyone is interested and doesn't have much time to dump into this.

```
$('#your-modal').on('open.zf.reveal', function() {
	var modal = $(this);
        // Set focus
	setTimeout(function() {
		$('#your-input', modal).focus();
	}, 100);

        // Reveal will steal focus after the first one, so set focus again
	setTimeout(function() {
		$('#your-input', modal).focus();
	}, 380);
});
```

Definitely need a better solution natively, though. It's not uncommon to have input fields in modals.
