### ISSUE TITLE
Semantic mixin grid-column error: media query expression must begin with '(' line 145 _breakpoint.scss

### ISSUE THREAD

**Issue by pamrichmond** [zurb/foundation-sites#8446]
I am using the semantic mixins for the grid in Foundation for Sites. I installed using `npm install foundation-sites`. When I use the @include grid-column() mixin, I get the following error:
`Error: media query expression must begin with '(' on line 145 of node_modules/foundation-sites/scss/util/_breakpoint.scss`

``` scss
header {
    @include grid-row; // this works correctly
}
#site-title {
    @include grid-column(85%); // this fails
}
#site-logo {
    @include grid-column(15%);  //this fails
}
```

Line 145 of _breakpoint.scss is:

``` scss
@media screen and #{$str} {
      @content;
}
```

Using:
grunt 0.4.5
grunt-sass 1.1.0
node-sass 3.4.2
foundation-sites 6.2.0

**Comment by kball** [comment]
Just tested - this has been fixed somewhere along the way.
