### ISSUE TITLE
[Reveal] Wrong documentation

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#8450]
Some invalid data-options at: http://foundation.zurb.com/sites/docs/reveal.html#js-options

"data-close-on-click" should be "closeOnClick"
"data-close-on-esc" should be "closeOnEsc"

**Comment by Deckluhm** [comment]
In fact both are correct.

- `data-close-on-click` format is used in your HTML
- `closeOnClick` format is used in your JS

It is explained in details here: http://foundation.zurb.com/sites/docs/javascript.html#configuring-plugins

**Comment by Silvester20** [comment]
You're right, I misunderstood the documentation. Thanks for pointing out.
