### ISSUE TITLE
Animating Offcanvas with Closable Button

### ISSUE THREAD

**Issue by klihelp** [zurb/foundation-sites#8452]
**How can we reproduce this bug?**

```
<div class="off-canvas position-right" id="off-canvas" 
    data-closable="slide-in-down slide-out-up" 
    data-off-canvas data-position="right">
```

**What did you expect to happen?**

Take priority for Closable animation.

**What happened instead?**

Offcanvas will stuck as there is some clashing between Closable and Offcanvas js parts.

**Test case:**

Will update one soon, posted for a quick review, in case someone have the same experience.
- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by paxperscientiam** [comment]
Have you tried closing with custom function?

````
$('#oc-left a').on('click',function(e) {
                                    $('#offCanvasLeft').foundation('close',function(e) {
                                        console.log("holler back");
                                    });
                                });
````

**Comment by kball** [comment]
cc @brettsmason for your offcanvas work

**Comment by brettsmason** [comment]
@kball I'd like to discuss this with you when possible to see how we could handle MotionUI animations

**Comment by klihelp** [comment]
Maybe can be done with the new OffCancas II in Foundation 6.4?

**Comment by DanielRuf** [comment]
Hi, what is the current status?

**Comment by brettsmason** [comment]
I think this is outside the current scope of the off canvas menu - it wasn't really built with this integration in mind, and would require a fair bit of work. I'd suggest we close this and maybe revisit in 7.

**Comment by klihelp** [comment]
I had used twitter/bootstrap since with good luck setting up similarly the project.
