### ISSUE TITLE
Multiple javascript plugins collide

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#8455]
**How can we reproduce this bug?**
Put two plugins on one container like so: 
`<ul id="navmain__list" class="dropdown navmain__list" data-dropdown-menu data-magellan>`

**What did you expect to happen?**
I want to use magallan in my menu, as well as have a dropdown included. 

**What happened instead?**
breaks and console says: 
`Tried to initialize magellan on an element that already has a Foundation plugin.`

**Comment by Owlbertz** [comment]
Wouldn't it be sufficient to just wrap a `div` around the `ul` and use magellan on that?

**Comment by gakimball** [comment]
Two plugins can't be put on the same element—this is intentional, to prevent potential issues.

Like @Owlbertz said, you can make a wrapper to contain the menu.

```html
<div data-magellan>
  <ul data-dropdown-menu>
  </ul>
</div>
```
