### ISSUE TITLE
[Reveal] Positioning properties are ignored

### ISSUE THREAD

**Issue by josh-h** [zurb/foundation-sites#8459]
The data-v-offset, data-h-offset, and data-btm-offset-pct properties for Reveal modal are ignored in 6.2.0. See this [pen](http://codepen.io/josho/pen/NNjoXE) demonstrating the Reveal modal can be positioned using data-v-offset in Foundation 6.0.1. While on v6.2.0 this [pen](http://codepen.io/josho/pen/pyPGpm) shows the property is ignored.

It looks like @gakimball removed support for vOffset, and the other properties in [b99cf40](https://github.com/zurb/foundation-sites/commit/b99cf405bbd03cd1eb284ddc08694ff428b3c9df). 

@kball in [05313e1](https://github.com/zurb/foundation-sites/commit/884b10a845db8ad7b67438070722261bf9c1f72e) added positioning logic in JS. So, it seems the intent is to position in javascript, not CSS.

Was removing the vOffset, btmOffsetPct, hOffset properties intentional, if so the properties listed in the documentation will need to be removed.

**Comment by gakimball** [comment]
@kball It looks like the positioning refactor in 6.2 might make a few of Reveal's plugin options obsolete?

**Comment by Owlbertz** [comment]
Seems to be fixed already: http://codepen.io/anon/pen/ZOAwxm.
