### ISSUE TITLE
[Feature Request] Add javascript function showAll() to Accordion Menu

### ISSUE THREAD

**Issue by crbranch** [zurb/foundation-sites#8460]
Accordion Menu currently has a `hideAll()` function, but there is no `showAll()` function.  This would be helpful when implementing Collapse All / Expand All options.

Current workaround:

Initially I tried to implement `showAll()` using the existing `hideAll()` function as inspiration and simply doing the opposite by calling `slideDown()` on all of the submenu items.  This appeared to work at first glance, but after more careful examination I realized that some of the attributes end up in an inconsistent state.  In particular, `aria-hidden=` is not always reset properly after calling `slideDown()`.

I ended up with the following solution that calls `up()` and `down()` instead of `slideUp()` and `slideDown()`.  I'm not 100% sure this is the best approach, but I haven't run into any issues so far:

            var menu = new Foundation.AccordionMenu($('#myMenu'));

            $("#expandAll").click(function () {
                menu.down(menu.$element.find('[data-submenu]'));
            });

            $("#collapseAll").click(function () {
                menu.up(menu.$element.find('[data-submenu]'));
            });

So, there are two takeaways:

1. It would be helpful to include a `showAll()` in the plugin.

2. The current `hideAll()` function calls `slideUp()` instead of `up()`.  Someone may want to confirm that using `slideUp()` in this situation is not causing any issues that haven't been discovered yet since doing the reverse does seem to cause trouble.

**Comment by kball** [comment]
@Owlbertz @crbranch with #8743 merged into 6.3, can we close this issue?

**Comment by Owlbertz** [comment]
From my understanding, yes.

**Comment by crbranch** [comment]
Looks good to me.  Thanks!
