### ISSUE TITLE
Off-canvas submenus; awesome example uncovered; Feature request

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation-sites#8462]
Hiya, whilst digging around the internet, I found this gem:
http://codepen.io/designsoutheast/pen/ZYERGo

It's a working example of how submenus could be implemented into Foundation 6's offcanvas-menu. It was written with 5 in mind, but, with minor adjustments, works just fine in the new framework.

You'd want to change the class "right" to "float-right" and address submenu indentation.
````
.off-canvas-submenu {
 padding-left:1em;
}
````
EDIT

````javascript
 $(".off-canvas-submenu").hide();
 $(".off-canvas-submenu-call").click(function() {
   var icon = $(".off-canvas-submenu").is(':visible') ? '+' : '-';
   $(".off-canvas-submenu").slideToggle("fast")
   $(this).parent().children().find("span").text(icon)
 });
````
````HTML
<ul class="menu">
<li id="unit"><a href="#" class="off-canvas-submenu-call">United Nations<span class="float-right"> + </span></a>
  <ul class="vertical menu off-canvas-submenu">
    <li><a href="/united-nations.php">Flags</a></li>
    <li><a href="#">Book 1</a></li>
    <li><a href="#">Book 2</a></li>
  </ul>
</li>
</ul>
````

OK, I tweaked the code to match Foundation syntax.

https://codepen.io/paxperscientiam/pen/qZjqKq

EDIT: As is, this does not work with dropdown menu.

**Comment by rafibomb** [comment]
This is cool! Should be able to use the F6 accordion in off-canvas as well out of the box.

**Comment by andycochran** [comment]
Yup, this works out-of-the-box for F6 w/ Off-canvas and Accordion. 

Here's an example: 
http://codepen.io/andycochran/pen/BzxvqZ

Closing.
