### ISSUE TITLE
[Dropdown Menu] error in foundartion.core.js

### ISSUE THREAD

**Issue by Mostafasaffari** [zurb/foundation-sites#8463]
when i use dropdownmenu foundation.core.js and util.nest fire error

foundation.util.nest.js:6 Uncaught SyntaxError: Unexpected token =
foundation.core.js:189 TypeError: Cannot read property 'Feather' of undefined(…)(anonymous function) @ foundation.core.js:189jQuery.extend.each @ jquery.js:365jQuery.fn.jQuery.each @ jquery.js:137(anonymous function) @ foundation.core.js:171jQuery.extend.each @ jquery.js:365Foundation.reflow @ foundation.core.js:163foundation @ foundation.core.js:267(anonymous function) @ adminpanel.html:89

**Comment by Owlbertz** [comment]
Looks like you are not using Babel to convert the ES6 syntax from the JavaScript. See also #8429.
What does your build process, e.g. gulpfile, look like?

**Comment by kball** [comment]
Closing based on previous comment.  In 6.2.1 we include compiled versions of the individual javascript plugins in the dist folder.
