### ISSUE TITLE
abide validateForm not working

### ISSUE THREAD

**Issue by Silur** [zurb/foundation-sites#8464]
**How can we reproduce this bug?**

1. Step one: Create a for set up with abide validation
2. Step two make a button call the  `$('#element').foundation('validateForm');` function on the form

**What did you expect to happen?**
Form to be validated

**What happened instead?**
console output: 
>Error: We're sorry, 'validateForm' is not an available method for this element.

**Test case:**
http://codepen.io/anon/pen/dMRoNO

**Comment by briantan888** [comment]
Your form must be declared with attribute `data-abide`

**Comment by Silur** [comment]
Indeed, seems like I didn't notice this in the documentation, thanks :smile:
