### ISSUE TITLE
foundation.core.js - hyphenate, parseValue, functionName

### ISSUE THREAD

**Issue by dragthor** [zurb/foundation-sites#8465]
Hey guys.  I am circling back to create more test cases for Zurb 6.  And I can easily write tests for hyphenate, parseValue, functionName in foundation.core.js (and I've seen other examples throughout the code too).  Currently these functions are "private" but have seen you guys utilize the underscore convention (ie, _parseValue).  

What are your thoughts on "moving up" these functions to public (with an underscore)?  Or do you prefer I move these over to the Foundation.util namespace (like throttle)?

Please advise.

**Comment by JeremyEnglert** [comment]
Lets open up this discussion for V7.
