### ISSUE TITLE
Missing identifiers - Foundation-flex.css (Full version)

### ISSUE THREAD

**Issue by pisandelli** [zurb/foundation-sites#8467]
The file `foundation-flex.css` (full version) is missing some identifiers. Maybe bad identation in sass files. Error trying to uglify using gulp-csso.

Line: 3686 - 3690

```
[...]
max-width: 100%; } }

-webkit-flex-wrap: wrap;
-ms-flex-wrap: wrap;
flex-wrap: wrap;

.top-bar-left,
[...]
```

Line: 3699 - 3701

```
[...]
@media screen and (min-width: 40em) {
  -webkit-flex-wrap: nowrap;
      -ms-flex-wrap: nowrap;
          flex-wrap: nowrap;
  .top-bar-left,
[...]
```

**Comment by kball** [comment]
I believe this has been resolved, but please reopen if you're still seeing any issues.
