### ISSUE TITLE
[Dropdown Menu] dropdown menu overflows window

### ISSUE THREAD

**Issue by mojouy** [zurb/foundation-sites#8476]
**How can we reproduce this bug?**
1. Create a navigation bar
2. create a dropdown element on the far right
3. add some content

**What did you expect to happen?**
content shouldn't break the dimensions of the screen

**What happened instead?**
Content generates scroll and breaks page

**Comment by gakimball** [comment]
Can you post a code sample?

**Comment by rafibomb** [comment]
Here is codepen with the menu - @mojouy can you modify this to make it happen?

**Comment by kball** [comment]
I believe this has been resolved since 6.2.3.  Closing, please reopen if you're still seeing the bug.
