### ISSUE TITLE
Dropdown Menu overflows the screen

### ISSUE THREAD

**Issue by bergschrat** [zurb/foundation-sites#8480]
If you just change the Partent-Linknames of Rafi Benkuals Dropdown Menu from "Two", "One", "Three" into longer Linknames, for example "Oberlink1", "Oberlink2", "Oberlink3", the dropdown element overflows the screen.
This is Rafis Menu:

http://codepen.io/rafibomb/pen/bpgMRM

This is the code of the broken menu:
```
<div  class="title-bar"  data-responsive-toggle="main-menu"  data-hide-for="medium">
<button  class="menu-icon"  type="button"  data-toggle=""></button>
<div  class="title-bar-title">Menu</div>
</div>
<div  class="top-bar"  id="main-menu">
<div  class="top-bar-left">
<ul  class="dropdown menu"  data-dropdown-menu="">
<li  class="menu-text"><strong>Site Title</strong></li>
</ul>
</div>
<div  class="top-bar-right">
<ul  class="menu vertical medium-horizontal"  data-responsive-menu="drilldown medium-dropdown">
<li><a  href="#">Oberlink1</a></li>
<li  class="has-submenu"> <a  href="#">Oberlink2</a>
<ul  class="submenu menu vertical"  data-submenu="">
<li><a  href="#">One</a></li>
<li  class="has-submenu"> <a  href="#">One</a>
<ul  class="submenu menu vertical"  data-submenu="">
<li><a  href="#">One</a></li>
<li><a  href="#">Two</a></li>
<li  class="has-submenu"> <a  href="#">One</a>
<ul  class="submenu mega menu vertical"  data-submenu="">
<li><a  href="#">One</a></li>
<li><a  href="#">Two</a></li>
<li><a  href="#">Three</a></li>
</ul>
</li>
</ul>
</li>
<li><a  href="#">Two</a></li>
</ul>
</li>
<li><a  href="#">Oberlink3</a></li>
</ul>
</div>
</div>
```
**How can we reproduce this bug?**

1. Step one: User Rafis Dropdown Menu on: http://codepen.io/rafibomb/pen/bpgMRM
2. Step two: Change the Partent-Linknames from "Two", "One", "Three" into longer Linknames, for example "Oberlink1", "Oberlink2", "Oberlink3"
3. Step three: the dropdown element overflows the screen.

**What did you expect to happen?**

**What happened instead?**

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by bergschrat** [comment]
Sorry, this is the correct link:
http://codepen.io/rafibomb/pen/bpgMRM

**Comment by brettsmason** [comment]
@bergschrat It looks that way, but I'm not sure.@Owlbertz @kball are you able to confirm? Looks like a JS issue to me.

**Comment by Owlbertz** [comment]
Yup, seems to be an issue with the collision detection in the box util.

**Comment by kball** [comment]
Yeah... we have a change that will go out in 6.2.1 that fixes a bug in the default direction of menu items in top-bar-right that should fix this specific case, but I think there is an issue in the collision detection that we should track down.

**Comment by bergschrat** [comment]
thank you!

**Comment by Owlbertz** [comment]
I forked and updated the Pen to include the new version, you can check it out here: http://codepen.io/Owlbertz/pen/qZpwex.
I will close this issue and have a separate look on the overall collision detection to fix this in a more generic way.

**Comment by Owlbertz** [comment]
For your information: the issue does not lie within the JavaScript, but within the SASS. Because the selectors were not specific enough, the styles of `.opens-right` set by the JS in case of an overflowing sub-menu  was overwritten by the parent's `.open-left` styles. I will do a PR for that despite this specific issue has been fixed to prevent future problems.

**Comment by bergschrat** [comment]
I think, the arrows are still in the wrong direction. see:
http://codepen.io/Owlbertz/pen/qZpwex

**Comment by Owlbertz** [comment]
They are - but I am only the JS guy :S

**Comment by kball** [comment]
@bergschrat @Owlbertz just to make sure I understand... your sense is the arrows should be on the left?  With the text still left aligned, because this is not an RTL language but just the right side menus, yes?
