### ISSUE TITLE
Gulp Build --Production Breaks Reveal

### ISSUE THREAD

**Issue by btn0s** [zurb/foundation-sites#8481]
**How can we reproduce this bug?**
Use Reveal in development and run `gulp build --production` 

**What did you expect to happen?**
Expected the `.reveal` to function as normal, opening the modal in front of the main site content and allowing for closing by either clicking/tapping outside the modal or on the `data-close` button in the top corner of the modal.

**What happened instead?**
`.reveal` modal opens on page load load vertically below the content of the page, with no overlay.

**Test case:**
Here's what was expected: http://codepen.io/btn0s/pen/MyvpYJ
Here's what happened: https://codepen.io/btn0s/pen/qZXRzo

**Comment by btn0s** [comment]
Just tried this with `gulp build` without the `--production` arg and I got the same broken functionality.

**Comment by pablocrs** [comment]
Are you using motion ui for in an out? take a look at uncss rules.

**Comment by codexnovus** [comment]
Try to disable unCSS in the gulpfile.babel.js (at line 87, just add // to comment it) . I tired of having classes dissapear and since I disabled it I had no more problems.

**Comment by fndaily** [comment]
Try adding this to your config.yml or unccss options:

```!!js/regexp ^\.(reveal)```

if you're using motion-ui:

```!!js/regexp ^\.(dropdown|fade|slide|hinge|reveal|scale|spin)```

**Comment by btn0s** [comment]
ah thank you guys @fndaily @codexnovus @pablocrs ... sometimes it helps a ton just to know what you're looking for! This will solve a lot in the future for me.
