### ISSUE TITLE
Undocumented parameter type in $grid-column-position mixin

### ISSUE THREAD

**Issue by zecipriano** [zurb/foundation-sites#8485]
In the [documentation for the $grid-column-position mixin](http://foundation.zurb.com/sites/docs/grid.html#grid-column-position) it's not mentioned that the $position parameter can also be the string 'center' to center the columns.

**Comment by brettsmason** [comment]
@kball I've created a PR to update the description to include the center option. Not sure how this gets into the docs though so if you could let me know that would be great! (not sure if its a separate repo or generated from this one).

**Comment by brettsmason** [comment]
This has now been merged and will be in the next point release.
