### ISSUE TITLE
[Off-canvas] Off Canvas Won't Close Upon Using Back Button on Mobile

### ISSUE THREAD

**Issue by bahamagician** [zurb/foundation-sites#8486]
**How can we reproduce this bug?**

Okay this is a very specific bug but it breaks my site when it occurs.
1. Visit http://foundation.zurb.com/sites/docs/off-canvas.html on your iPhone
2. Click on the hamburger to open the off canvas 
3. Click on the About Foundation link
4. Press the back button to go back to the off canvas documentation
5. Try to close the menu.

**What did you expect to happen?**
I expected the menu to be able to close

**What happened instead?**
The menu won't close at all!

**Comment by colin-marshall** [comment]
@bahamagician is this still happening? I was not able to reproduce, I could close the menu when I tried just now.

**Comment by bahamagician** [comment]
Yes it's still happening.  When you click over to the "About" page, try scrolling down and then back up before hitting the back button.  I can shoot a video if you need it.

**Comment by rafibomb** [comment]
I can't replicate this either. The menu is still open but tapping the hamburger closes it.

**Comment by bahamagician** [comment]
Okay, try this...

When you get back to the page and close the menu (step 5 above), try opening up the menu again and now you shouldn't be able to close it.

I'll try and make a screencast of it so you can see it happening.

Admittedly it's a small use case but I've been trying to use it with a project in which users use the menu for filtering and the continuous back and forth breaks the menu.

**Comment by bahamagician** [comment]
Here's the video I shot on an iPhone 6s that shows the issue:

https://app.crossbrowsertesting.com/public/if266ff03432abb9/livetests/5615754

**Comment by JeremyEnglert** [comment]
Having a hard time replicating this as well. Off-canvas has received many updates since this issues was opened. Feel free to re-open if you're still having issues.
