### ISSUE TITLE
Ajax and Reveal errors 

### ISSUE THREAD

**Issue by phenix-factory** [zurb/foundation-sites#8487]
**How can we reproduce this bug?**

1. Install Foundation 6.2
2. Use my snippets for ajax and reveal : https://github.com/zurb/foundation-sites/issues/7639#issuecomment-166226999 and open a reveal
3. Open the javascript console

**What did you expect to happen?**

No error :)

**What happened instead?**

Got some errors : 

```
Tried to initialize responsive-toggle on an element that already has a Foundation plugin.
Tried to initialize reveal on an element that already has a Foundation plugin.
TypeError: $element is undefined
```

Due to the ajax setup, i can't really dive any codepen, i didn't find how to use ajax on it.

![selection_051](https://cloud.githubusercontent.com/assets/1810149/14148692/cdee4dea-f6a0-11e5-9677-81dcc3bbeee9.png)

**Comment by phenix-factory** [comment]
I could fix the first two error, it was all my bad.

But the type error remain, and it's because of motion UI.

I found this bug on the foundation doc itself : http://foundation.zurb.com/sites/docs/reveal.html#animations

If you click on the animated modal, the type error happend.

**Comment by Owlbertz** [comment]
I believe this has been fixed in https://github.com/zurb/foundation-sites/commit/6df453b555e30c804490d93013216ceb0f7cc2a6 already. Doesn't happen in the latest development version for me.

**Comment by phenix-factory** [comment]
Well this issue is useless then :)
