### ISSUE TITLE
[Reveal] [Foundation 6.2] TypeError when destroying instance

### ISSUE THREAD

**Issue by canihavesomecoffee** [zurb/foundation-sites#8489]
**How can we reproduce this bug?**

Create a Reveal instance on the fly, and then try to destroy it after closing it.

I believe it is caused because the overlay (and the $element inside it) are being removed from the DOM and then can't be referenced anymore.

**What did you expect to happen?**

No javascript errors.

**What happened instead?**

```TypeError: t.$element.data(...) is undefined```

**Test case:**

http://codepen.io/anon/pen/mPMGWY

**Comment by Owlbertz** [comment]
Will be fixed once #8473 has been merged.

**Comment by Owlbertz** [comment]
Should be fixed now since the PR got merged.
