### ISSUE TITLE
[Dropdown] Dropdown panel does not show

### ISSUE THREAD

**Issue by Jesse-Breuer** [zurb/foundation-sites#8491]
**How can we reproduce this bug?**
Implement a dropdown using foundation-flex.css
1. Step one
duplicated dropdown code from kitchen sink using
https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.0/foundation-flex.css
(jquery)
https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.0/foundation.js
and 
2. Step two
click button to launch
3. Step three
examine console when dropdown fails to launch
**What did you expect to happen?**
dropdown to display
**What happened instead?**
in css:  .dropdown-pane { visibility:hidden } 
did not change.
Then switched foundation-flex.css with foundation.css and it worked properly

**Test case**

Give us a link to a [CodePen](http://codepen.io) or [JSFiddle](http://jsfiddle.net) that recreates the issue.http://codepen.io/anon/pen/EKvBPV

**Comment by colin-marshall** [comment]
Your codepen is missing the JavaScript that initializes Foundation:
```
$(document).foundation();
```

**Comment by colin-marshall** [comment]
@Jesse-Breuer I'm going to go ahead and close this issue. If you still need help, feel free to reopen the it. Thanks for using Foundation!

Colin
