### ISSUE TITLE
[Slider] data-start is breaking the slider drag

### ISSUE THREAD

**Issue by christianallred** [zurb/foundation-sites#8496]
1. Any slider with a data-start value doesn't appear to build properly
2. Try to drag slider it only moves a small amount in the middle of the slider. 

http://codepen.io/EvilEeyore/pen/GZMgvb

**Comment by whokilledtheelectricmonk** [comment]
You need to load jQuery over HTTPS - it is being blocked in your codepen

**Comment by briantan888** [comment]
created PR #8506  to fix the bug. 2 lines fix but it is failing the Travis CI build.

**Comment by kball** [comment]
Fixed in #8506 and will be in 6.2.1
