### ISSUE TITLE
Problem disabling slider with jquery

### ISSUE THREAD

**Issue by jimmy72** [zurb/foundation-sites#8497]
I have an issue with the foundation slider described here:
http://foundation.zurb.com/sites/docs/slider.html
When I add the "disabled" class to the slider directly in HTML it gets disabled as expected. No dragging or clickSelecting of the handle is possible.

But when I do this: `$("#my_slider").addClass("disabled");` the slider gets disabled but it's still possible to drag and clickSelect the slider handle.

Anyone?

Jimmy

**Comment by ncoden** [comment]
:+1:

I first thought it was a normal behaviors, because `.classes` should be reserved for graphical properties, and we should better use something like a `disabled` attribute or `$('#my_slider').foundation('disable')` to change a component behavior.

But Foundation don't follows that norm, **and following the doc and v5 slider, adding the `.disabled` class should disable the slider.**

Please add the **bug** label.

**Comment by jimmy72** [comment]
Thanks for your answer, I'm new to Github...why is there no checkbox next to my issue to apply a label to?

**Comment by ncoden** [comment]
Only a Yetinaute can do it. Thnks @colin-marshall

**Comment by Owlbertz** [comment]
You are right, the slider currently only checks for a disabled state upon initialization. I purposed a fix in #8503. Maybe you can have a look.

**Comment by jimmy72** [comment]
Hi, I also found that for example this code...

`var sld = new Foundation.Slider( $('#my_slider'), {initialStart: 0, draggable: false});`

...is setting the slider's handle in position "0" like it should do, but the "draggable: false" is NOT overwriting the default value "draggable: true". Same for the clickSelect option.

Is there something going wrong when this line of code is being executed? My level of experience with javascript is not advanced enough so that I can understand everything that is going on :). But maybe it helps you guys...

`this.options = $.extend({}, Slider.defaults, this.$element.data(), options);`

The new options are merged together with the defaults values into a new object whereas both objects are preserved but the new set values should overwrite the defaults?

Jimmy

**Comment by ncoden** [comment]
Hi. You are right, on this line (https://github.com/zurb/foundation-sites/blob/develop/js/foundation.slider.js#L23), given `options` should overwrite `$element.datas()` which should overwrite `Slider.defaults`.

> but the "draggable: false" is NOT overwriting the default value "draggable: true"

How did you checked it ? I understand `draggable` as `can move a handler when keeping the click on it`. Is it the behaviour you have ?

**Comment by jimmy72** [comment]
Yes indeed just like you say. You should not be able to swipe the handle with the mouse when keeping the click on it. I tested it by changing the default values of both clickSelect and draggable to false and see what's going on. I'm working (localhost for the moment) on a property site (real estate) site where I need the slider to let the user select the number of bed rooms. Depending on the type of property (land, house, commercial) I need to disable the slider from time to time....

**Comment by jimmy72** [comment]
like so in my code:

`function enable_disable_type_dependent_selectboxes(){
    var slider, pos = 0;
    if( boolIsWoningType === false ){
        slider = new Foundation.Slider( $sliderSlaapkamers, {initialStart: pos});
        $sliderSlaapkamers.addClass('disabled');
    }else{
        pos = parseInt($valueAantalSlaapkamers.val());
        slider = new Foundation.Slider( $sliderSlaapkamers, {initialStart: pos});
        $sliderSlaapkamers.removeClass('disabled');
    }
  }`

**Comment by jimmy72** [comment]
I removed the clickSelect and draggable options from my code because it was not working...and tried to disable by adding the class disabled and setting the slider in zero position...

**Comment by ncoden** [comment]
Please edit your message and use ````` to for your code

**Comment by jimmy72** [comment]
Thanks!
