### ISSUE TITLE
Sticky+Magellan+Dropdown

### ISSUE THREAD

**Issue by Wurstholger** [zurb/foundation-sites#8500]
Hi,

I try to make a sticky navigation with a dropdown AND a magellan, but I can not get the magellan working. all plugins are activated .js.

I tried to write the data-magellan in the ul element aswell as in most div`s.

here is the code:

`<div class="top-bar-container" data-sticky-container>
    <div class="sticky navmain" data-sticky data-margin-top="0" style="width:100%;" data-sticky-on="small" data-anchor="main" data-margin-bottom="0" data-top-anchor="top" data-btm-anchor="bottom" >
        <div class="title-bar navmobile" data-responsive-toggle="top-bar" data-hide-for="xlarge" data-options="closeOnClick:true;">
            <button class="menu-icon" type="button" data-toggle></button>
            <button class="title-bar-title" data-toggle>Menu</button>
        </div>
        <div class="top-bar" >
            <div class="row" id="top-bar">
                <div class="columns">                   
                    <ul id="navmain__list" class="dropdown navmain__list" data-dropdown-menu >
                        <li class="navmain__list__item navmain__list__item--logo"><a href="#header" class="smoothscroll"><img src="{{root}}assets/img/logo.png"></a></li>
                        <li class="navmain__list__item" ><a href="#unternehmen" class="navmain__list__item__link smoothscroll">Unternehmen</a></li>
                        <li class="navmain__list__item"><a href="#kontakt" class="navmain__list__item__link smoothscroll">Kontakt</a></li>
                        <li class="navmain__list__item"><a href="#leistungen" class="navmain__list__item__link smoothscroll">Leistungen</a>
                        <ul class="menu show-for-xlarge">
                            <li class=""><a class="smoothscroll" href="#leistungen__content__section__industriemontage">Montage</a></li>
                            <li class=""><a class="smoothscroll" href="#leistungen__content__section__demontage">Hersteller Service</a></li>
                            <li class=""><a class="smoothscroll" href="#leistungen__content__section__verlagerung">Service Points</a></li>
                            <li class=""><a class="smoothscroll" href="#leistungen__content__section__inbetriebnahme">Engineering</a></li>
                        </ul>
                    </li>
                    <li class="navmain__list__item"><a href="#karriere" class="navmain__list__item__link smoothscroll">Karriere</a></li>
                    <li class="navmain__list__item"><a href="#netzwerk" class="navmain__list__item__link smoothscroll">Netzwerk</a></li>
                </ul> 
            </div>
        </div>
    </div>
</div>
</div>`

**Comment by Deckluhm** [comment]
Please make your code more readable using these markups: https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

Or, event better, provide a [CodePen](http://codepen.io/rafibomb/pen/xVVGOB) that reproduces your issue.

**Comment by JeremyEnglert** [comment]
@Wurstholger, feel free to open this if you are still having issues.

**Comment by tim5chneider** [comment]
```
<div data-sticky-container>
  <div data-sticky data-margin-top="0" id="menu" style="width:100%">
    <div class="menu-centered" data-magellan>
      <ul class="dropdown menu" data-dropdown-menu>
        <li><a href="#top">Top</a></li>
	<li><a href="#first">One</a></li>
	  <li>
	    <a href="#dropdown">dropdown</a>
	      <ul class="menu">
	        <li><a href="#link1">Link1</a></li>
	 	<li><a href="#link2">Link2</a></li>
	      </ul>
	  </li>
	  <li><a href="#link3">Link3</a></li>
	  <li><a href="#link4">Link4</a></li>
      </ul>
    </div>
  </div>
</div>

<div class="sections">
  <section id="first" data-magellan-target="first">...</section>
  <section id="dropdown" data-magellan-target="dropdown">...</section>
  .
  .
  .
</div>
```

**Comment by IamManchanda** [comment]
@Wurstholger / @tim5chneider 
Can you provide codepen ??

---

Fork from these below to provide codepen?

- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

**Comment by tim5chneider** [comment]
look at codepen:

https://codepen.io/tim5chneider/full/pwbmWz/

**Comment by tim5chneider** [comment]
yes, look at the pen!

**Comment by tim5chneider** [comment]
sorry, should have write that this is the solution.
