### ISSUE TITLE
foundation for sites 6.2 -sass- some "flex" settings are added with  flex-grid commented

### ISSUE THREAD

**Issue by joomlolo** [zurb/foundation-sites#8501]
Hello everybody, 
Thanks for your work.
I noticed that some flex settings are added to app.css on a "display:table" even if "//@include foundation-flex-grid;" is commented.

**How can we reproduce this bug?**
Foundation for Sites 6.2 compiled with sass and gulp
1. app.scss, just the grid:
`@charset 'utf-8';

@import 'settings';
@import 'foundation';
//@import 'motion-ui';

//@include foundation-global-styles;
@include foundation-grid;
//@include foundation-flex-grid;
//@include foundation-typography;
//@include foundation-button;
//@include foundation-forms;
//@include foundation-range-input;
//@include foundation-accordion;
//@include foundation-accordion-menu;
//@include foundation-badge;
//@include foundation-breadcrumbs;
//@include foundation-button-group;
//@include foundation-callout;
//@include foundation-close-button;
//@include foundation-menu;
//@include foundation-menu-icon;
//@include foundation-drilldown-menu;
//@include foundation-dropdown;
//@include foundation-dropdown-menu;
//@include foundation-flex-video;
//@include foundation-label;
//@include foundation-media-object;
//@include foundation-off-canvas;
//@include foundation-orbit;
//@include foundation-pagination;
//@include foundation-progress-bar;
// @include foundation-progress-element;
// @include foundation-meter-element;
//@include foundation-slider;
//@include foundation-sticky;
//@include foundation-reveal;
//@include foundation-switch;
//@include foundation-table;
//@include foundation-tabs;
//@include foundation-thumbnail;
//@include foundation-title-bar;
//@include foundation-tooltip;
//@include foundation-top-bar;
//@include foundation-visibility-classes;
//@include foundation-float-classes;
// @include foundation-flex-classes;

//@include motion-ui-transitions;
//@include motion-ui-animations;`

**What did you expect to happen?**
-no flex settings because //@include foundation-flex-grid; 
-no flex settings on "display:table;"

**What happened instead?**

-some "flex settings are added to "app.css" when compiled".
app.css:
`/**
 * Foundation for Sites by ZURB
 * Version 6.2.0
 * foundation.zurb.com
 * Licensed under MIT Open Source
 */
.row {
  max-width: 75rem;
  margin-left: auto;
  margin-right: auto; }
  .row::before, .row::after {
    content: ' ';
    display: table;
    -webkit-flex-basis: 0;
        -ms-flex-preferred-size: 0;
            flex-basis: 0;
    -webkit-order: 1;
        -ms-flex-order: 1;
            order: 1; }
  .row::after {..`
**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

gulp on windows

**Comment by joomlolo** [comment]
in th customizer same problem

.row {
  max-width: 62.5rem;
  margin-left: auto;
  margin-right: auto; }
  .row::before, .row::after {
    content: ' ';
    display: table;
    flex-basis: 0;
    order: 1; }
  .row::after {
    clear: both; }

**Comment by brettsmason** [comment]
This was due to a flex specific check not being present on the clearfix mixin. This was fixed [here](https://github.com/zurb/foundation-sites/commit/32910a6d9f177f2900eeee7dfa07a86936d5a08d) and a few other commits.

If you notice any flex specific properties cropping up in the latest version please re-open this.
