### ISSUE TITLE
[Menu] item height vs button height. 

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#8504]
Striving for visual consistency, I noticed menu items aren't the same height as buttons. At first I thought this was simply 'cause `$menu-item-padding: 0.7rem 1rem;` doesn't match `$button-padding: 0.85em 1em;`. However, it's not that simple. If you change the setting to `$menu-item-padding: $button-padding` they still don't match 'cause buttons have a 1px transparent border. So buttons are still 2px taller. 

I was able to get a height match with this: 

``` scss
$menu-item-padding: (rem-calc(1) + 0.85rem) 1rem;
```

Ew. Can't we get rid of button borders? 

---

_Aside: This issue once again makes me wonder about the functional overlap between menus and button groups, and how Foundation could be simplified even further by merging Button Group into Menu—e.g. add `.button` classes to a `.menu` and get a button group._

**Comment by g12n** [comment]
The `border: 1px solid transparent;` is hard coded within the `@mixin button-base`, making it one of the few visual relevant properties, that are not accessible through the `settings.scss`.

I'd have to guess, but I think this is somehow related to the `.hollow` class. This way, switching from the regular to the hollow style doesn't change the size of the buttons. Which would lead, if done dynamically, the following elements to _jump_ 2px.

This could be avoided by actually setting the `height` property of the buttons and rely on `border-box` to deal with the borders. This would certainly help to make to harmonize the sizing mechanisms of buttons and form elements. But it's quite a can of worms to open. 

This sounds related to https://github.com/zurb/foundation-sites/issues/8507

**Comment by andycochran** [comment]
We can't set an explicit height on buttons, for the reasons outlined in #8507. I'm wondering if can do `.hollow` without borders. Maybe like this: http://codepen.io/andycochran/pen/MyOarM

**Comment by g12n** [comment]
Nice! Works like a treat.

Though box-shadow, like border-radius, is still a quite common tool, to style button. This approach might make it harder to use it.

How about generated placing the border with generated content? http://codepen.io/g12n/pen/ONOyow

Though I am not a fan of resetting the positioning inside a generic element with `position: relative`. But I guess, that not many people use a button as a container for absolute positioned content.

**Comment by andycochran** [comment]
@g12n Ooh! That's even better, and won't conflict with drop shadows everyone puts on buttons. Tho you're right about relatively positioning being undesirable. And buttons having a border is probably also related to them matching the height of inputs. So maybe we're going about this issue backwards. Perhaps menu items should have transparent borders just like buttons.

**Comment by g12n** [comment]
I don't think the relative position isn't much of an Issue. Adding the `.dropdown` class to a button sets the position to relative as well. This is necessary to position the css-triangle. I guess, this one is quite commonly used. 

I was lucky, that the `:before` content was still available and not occupied by `.dropdown`. 

We could actually fix the hollow dropdowns as well at the same moment. Currently the triangle is always white, even on the hollow buttons. A rough fix could look like that: http://codepen.io/g12n/pen/BKmogv

Changing the menu is possible as well. Adding a transparent border around any element, feels wonky to me. But looking at my code here … I would not be able to decide which solution feels wonkier. :|

**Comment by andycochran** [comment]
Yeah, looking at it that way, relative isn't biggie. 
But I still wanna look into how nixing border effects forms.

**Comment by g12n** [comment]
Yeah! Alright! 
Forms are quite hard, since most Form elements have a fixed height. And those values are not linked. Balancing those values will be quite a delicate task. Especially when dealing with those guys here: 

![bildschirmfoto 2016-04-04 um 18 28 58](https://cloud.githubusercontent.com/assets/57556/14255181/2941613c-fa93-11e5-91d6-01b13b81a10a.png)

Looking forward to see your progress. :+1:

**Comment by andycochran** [comment]
Regarding the fixed height of form elements, that could be calculated to match the height of the default size `.button` (not one w/ a class). Right now form element heights are set to: 

```scss
$height: ($input-font-size + ($form-spacing * 1.5) - rem-calc(1));
```
But it could instead be the button font size + the top and bottom button padding (which is unfortunately in a padding shorthand property variable). We'd need to separate the `$button-padding` into something like `$button-height-padding` and `$button-width-padding`. Then we could set form element heights to: 

```scss
$height: (map-get($button-sizes, default) + ($button-height-padding*2));
```

But borders are still tied up in all this. What if I want my buttons to have borders, like on this very site? I can't easily add borders to buttons without effecting other elements. So I also like the idea of introducing these into `_settings.scss`: 

```scss
$button-border-size: 0;
$button-border-color: scale-color($primary-color, $lightness: -14%);
```

Then we could set form element heights to: 

```scss
$height: (map-get($button-sizes, default) + ($button-height-padding*2) + ($button-border-size*2));
```

All that's left to account for now is borders on hollow buttons. To make sure their height matches, we'd have to subtract the button border from all buttons' padding: 

```scss
.button {
  padding: ($button-height-padding - $button-border-size) ($button-width-padding - $button-border-size) ;
}
```

@brettsmason, you have a take on this?

**Comment by andycochran** [comment]
Also related to #8164 (in addition to #8507 mentioned above).

**Comment by brettsmason** [comment]
@andycochran Great writeup with lots of useful ideas. Its a tough call on what the best approach would be...

Could we potentially do something like:
`$button-border: 1px solid blue;` as the variable that users change in the `_settings.scss` file.

Then have some internal variables for `$button-border-size`, `$button-border-style` and`$button-border-color` that aren't used in the `_settings.scss` file. We could then get the values like they are used in the [dropdown menu](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_dropdown-menu.scss#L32)

So we would end up with:

```
/// Button border
$button-border: 1px solid blue !default;

// Border width for buttons.
$button-border-width: nth($button-border, 1);

// Border style for buttons.
$button-border-style: nth($button-border, 2);

// Border color for buttons.
$button-border-color: nth($button-border, 3);
```
Thats assuming we would need all 3 to be seperated of course.

Could we then also do something similar with button padding? So rather than having a map do a similar approach to the dropdown menu and get the nth value? I guess that might get difficult when users only enter 1 value though for example.

I'm up for the idea of the button padding map though if you think that would work better :smile:

**Comment by andycochran** [comment]
@brettsmason I'd forgotten about nth()! That makes this much simpler.

**Comment by JeremyEnglert** [comment]
At this point, this seems like a pretty big rework. Lets open this for discussion for V7.
