### ISSUE TITLE
[Reveal] reveal-overlay is not removed if open more than 1 time

### ISSUE THREAD

**Issue by Alcalt** [zurb/foundation-sites#8505]
When I open and close a modal for the first time everything work correctly but if that modal is open a second time without refresing the page before and I close it the overlay stay on and I can't click on links.

This is what my modal look like :
```
<div class="modal-container">
      <a data-open="exampleModal"><p>This is a example.</p></a>
      
      <div class="reveal" id="exampleModal" data-reveal>
            [gravityform id="1" title="true" description="true"]
            <button class="close-button" data-close aria-label="Close reveal" type="button">
                  <span aria-hidden="true">Close</span>
            </button>
      </div>
</div>
```

After searching for the problem I've found out the overlay was made by the div bellow.

`<div class="reveal-overlay" tabindex="-1" aria-hidden="true" data-close="exampleModal" style="display: block;"></div>`

The first time I close my modal **display: block** change to **display: none**. When I try to open my modal again instead of changing **display: none** back to **display: block** it create a other div above the last one. That mean that instead of having a toggle on display I have 2 div targeting the same modal but one with display: block and the other with display: none.

Example :
```
<div class="reveal-overlay" tabindex="-1" aria-hidden="true" data-close="exampleModal" style="display: block;"></div>
<div class="reveal-overlay" tabindex="-1" aria-hidden="true" data-close="exampleModal" style="display: none;"></div>
```

Did I forgot to add something or is it a bug with reveal? I use the last version of Foundation 6 and Gravity Form. Also I load this modal in a widget using a view (Toolset).

**Comment by FlatspinZA** [comment]
This is a shot in the dark: In Foundation 5 you needed to do a 'reflow', which is now replaced by 'reinit' in version 6. 

"reInit is your consistent replacement for reflow"

http://metroize.com/zurb-foundation-6-whats-new/

**Comment by Deckluhm** [comment]
Here is a CodePen using the code your provided (I just removed the Gravity Form part): http://codepen.io/anon/pen/WwXBvw

It works as expected so I think the issue is with something else (maybe Gravity Form or your own code).

**Comment by Alcalt** [comment]
My bad I found what my problem was. I had custom on('click) function in my app.js. I had a issue with modal and to resolve it I added this function for each modal that I have.
```
$( document ).on( 'click', ".mymodal-reveal-fix", function () {
    var modal = new Foundation.Reveal( $( '#exampleModal' ) );
   modal.open();
} );
```
The problem was each time I clicked to open a modal it created a new one but that modal didn't remove itself when I closed it. When I finally found out what my problem was I just added this small function below my previous function and now that part work like it should.
```
$( document ).on( 'click', ".close-button", function () {
    $('.reveal-overlay').remove();
} );
```

**Comment by Deckluhm** [comment]
Always try to reproduce bug using CodePen (or similar tool), it helps to easily identify issues in your code (or, in some cases, confirm a bug in a library / framework you are using).

**Comment by brettsmason** [comment]
@Deckluhm Thanks for helping on this. I'm going to close as this seems to be resolved.

**Comment by kaktusin** [comment]
This solved my case: duplicated reveal-overlay divs
https://github.com/zurb/foundation-sites/pull/9166/files
