### ISSUE TITLE
[Grid] Responsive Gutters with Unresponsive Gutters

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#8508]
Would it be possible to use responsive gutters with the exception of some rows/columns which you'd always want to use a specific gutter size? 

**Example use case:** 
You want responsive gutters to add loads of space between your content and sidebar on large screens. And your content is two columns. It'd be nice if the content columns were separated by the `small` value in `$grid-column-gutter`, but they're spaced just as far apart as the content is from the sidebar. So you basically just get a three-column layout. 

**Possible solution:**

``` html
<div class="row">
  <div class="large-8 columns">
    <div class="row small-gutters"><!-- .[size]-gutters could force unresponsive gutters -->
      <div class="large-6 columns">Content A</div>
      <div class="large-6 columns">Content B</div>
    </div>
  </div>
  <div class="large-4 columns">
    ...Sidebar...
  </div>
</div>
```

Maybe this is already possible through semantic classes + mixins?

**Comment by ncoden** [comment]
:+1: Can be usefull.
But I prefer the `.gutter-{size}` syntax. What do you think ?

Pull request: https://github.com/zurb/foundation-sites/pull/8528

**Comment by christianmagill** [comment]
I wrote a small mixin that does variant gutters based on multipliers. Right now I am just overwriting the css, but could probably be better implemented within Foundation I am sure.

The idea is that your gutters are still responsive based on breakpoint, however you also have variants that you can select within each breakpoint.

https://github.com/christianmagill/foundation--variant-gutter-classes

**Comment by andycochran** [comment]
@ncoden It looks like you resolved this in https://github.com/zurb/foundation-sites/pull/8528?

**Comment by andycochran** [comment]
Although, there's no mention of `.gutter-{size}` in the docs.

**Comment by kball** [comment]
@andycochran can you verify if this is working and perhaps add to the docs?
