### ISSUE TITLE
Tables with class="stack" and $show-header-for-stacked : true issues in 6.2

### ISSUE THREAD

**Issue by gremmie** [zurb/foundation-sites#8512]
I have noticed two possible issues with tables with the stack class and `$show-header-for-stacked: true;` below. 

**How can we reproduce this bug?**

Use this markup:

```
<table class="stack">
   <thead>
   <tr><th>Title</th><th>Author</th><th>Posts</th><th>Date</th></tr>
   </thead>
   <tbody>
   <tr>
      <td><a href="/">Some title</a></td>
      <td>Author</td>
      <td>42</td>
      <td>August 11, 1967</td>
   </tr>
   </tbody>
</table>

```

And with `$show-header-for-stacked: true;`

**What did you expect to happen?**

When the screen is made small, the first cell in the stacked table would contain all of the table headers (Title, Author, Posts, Date).

**What happened instead?**

Only Title appeared.

---

Second issue:

**How can we reproduce this bug?**

Get rid of the `<thead>` and `<tbody>` tags to see what happens:

```
<table class="stack">
   <tr><th>Title</th><th>Author</th><th>Posts</th><th>Date</th></tr>
   <tr>
      <td><a href="/">Some title</a></td>
      <td>Author</td>
      <td>42</td>
      <td>August 11, 1967</td>
   </tr>
</table>
```

And `$show-header-for-stacked: true;`.

**What did you expect to happen?**

Again, when the screen is made small, the first cell in the stacked table would contain all of the table headers (Title, Author, Posts, Date) aligned to the left.

**What happened instead?**

All table headers did appear this time, but they were centered.  Now maybe this was the intention but it looks kind of strange since the data items in the 2nd cell are left-aligned. So this one is really more of a question. Is it possible to add a Sass variable to control the alignment of the stacked `<th>` items?

**Comment by gremmie** [comment]
So I guess in retrospect I can live with these things, but maybe we could add a note to the documentation about not using markup with `<thead>` and `<tbody>` or it won't work. I can add a pull request for that, unless you feel this is a bug that is worth fixing. Thanks!

**Comment by gremmie** [comment]
I'd really like this to work, so if anyone has any pointers or places to start I'll try to work up a PR.

**Comment by gremmie** [comment]
Hmmm, so looking at the source code it looks like it only displays the first `th` inside a `thead` by design. 

The docs for `$show-header-for-stacked` say: "Default value for showing the header when using stacked tables."  I guess I assumed the "header" was all the `th` tags. 

So I dunno if the docs or the code needs updating. I would prefer all the `th` elements to appear if that flag is true, but not sure if that is the intent.

**Comment by gremmie** [comment]
So I got it to work the way I wanted by adding some of my own rules in my project's sass file:

```
// Foundation's table.stack only shows the first th, but I want all of them.
@mixin my-table-stack {
  thead {
    th {
      display: block;
    }
  }

  tfoot {
    display: none;
  }

  tr,
  th,
  td {
    display: block;
  }

  td {
    border-top: 0;
  }
}

table.my-stack {
   @include breakpoint(medium down) {
      @include my-table-stack;
   }
}
```

Use `<table class="my-stack">` in your code to get it applied.

If anyone on the Zurb project decides that the current behavior of only showing the first `th` in the `thead` is not desired, I can work up a PR.

**Comment by masonhale** [comment]
+1 I also was expecting to see all `<th>` elements displayed when `.stack` is used in combination with `$show-header-for-stacked`

**Comment by rafibomb** [comment]
Also - for 6.4 the class should be renamed to `.stack-for.small` to match other components.

**Comment by rafibomb** [comment]
@gremmie Yes a PR would be awesome! We'll merge it in. The desired behavior should be to show the thead on stack.
