### ISSUE TITLE
[Download] CSS does not include pagination

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#8531]
**How can we reproduce this bug?**

Download the complete CSS

**What did you expect to happen?**

Include Pagination CSS

**What happened instead?**

Pagination CSS not included

**Comment by kball** [comment]
@rafibomb can you point me at the css in question within the repo?

**Comment by lhadjadj** [comment]
hello, i have the same problem , the custom version ( 6.2.0 ) or the full version ( 6.2.0 ) does not have the class pagination in foundation.css file. For cons , the foundation.css file ( 6.2.0 ) available on Git site contains well the css class . The size of the two files ( full version ) is different.

**Comment by rafibomb** [comment]
This appears to be fixed by @kball ! We'll close this, open a new issue if you find anything else with the customizer!
