### ISSUE TITLE
Abide Validation on Radio Buttons doesn't display "Form Error" on error

### ISSUE THREAD

**Issue by justrhysism** [zurb/foundation-sites#8540]
**How can we reproduce this bug?**
1. Create a basic form with radio buttons, each with `required` attribute and a `<span class="form-error">You must select an option</span>`
2. Submit form without selecting an option.

**What did you expect to happen?**

Form error to be displayed.

**What happened instead?**

Form error isn't displayed.

**Test case:**

http://codepen.io/justrhysism/pen/NNXGPa

**Comment by briantan888** [comment]
This will be fixed in foundation 6.2.1 . I've tested the new validateRadio function and it works as expected. It even works with radio in switches.

**Comment by JeremyEnglert** [comment]
Looks like this was fixed.
