### ISSUE TITLE
6.20 Edge Browser - elements with SVG embedded background images not working!

### ISSUE THREAD

**Issue by MetalG3arSo1id** [zurb/foundation-sites#8545]
Things like select boxes have no arrows, as the SVG is not displaying in Edge like the screenshot from foundations own site, yellow highlights no arrow.

I'm guessing any other elements with background SVG's on Edge will not work also.

![image](https://cloud.githubusercontent.com/assets/10776219/14352223/5e38069a-fccb-11e5-924d-fec0770f1397.png)

**Comment by colin-marshall** [comment]
I'm setting up a VM today so I can test on Edge. According to [Can I Use](http://caniuse.com/#feat=svg-css), Edge should have background SVG support.

**Comment by colin-marshall** [comment]
Found the problem. Edge is turing single quotes to double quotes in the CSS, making the `url()` value in the CSS invalid. If you flip all of the quotes to make the surrounding quotes double and the inner quotes single, this solves the problem. I don't know if that introduces problems in other browsers, so I'll have to do more testing.

**Comment by MetalG3arSo1id** [comment]
Cool nice find. Edge does so many odd things, thanks Colin

**Comment by Lynda333** [comment]
I saw this as well. Glad you found a solution.

As FYI: I tested the solution in Edge, Firefox and Chrome (all latest versions) and all work just fine in my test. 

Also, I've reported this bug to Microsoft here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7157459/

**Comment by colin-marshall** [comment]
@Lynda333 thanks for testing and for reporting the bug to Microsoft! I signed up to track progress of it over there. I did some of my own tests and had no issues so I merged the fix into develop.

**Comment by haritha2112** [comment]
2019 Update with Edge 18: 
I guess Edge 18 does not turn single quotes to double quotes anymore in the CSS. With Edge 17 I had that issue and having double quotes solved it. But with Edge 18, having double quotes will recreate the issue :|

So it is safe to say that we can use single quotes in Edge 18.

**Comment by DanielRuf** [comment]
I guess this will not be relevant anymore in the near future when Edge stable uses Chromium.
