### ISSUE TITLE
Of-Canvas is missing in customized flexgrid JS in Foundation 6.2

### ISSUE THREAD

**Issue by sardnailap** [zurb/foundation-sites#8551]
I am trying to download the newest version of Foundation 6.2. When I download the complete I get the off canvas part in the Foundation.js: OffCanvas module, line 4937

When I am downloading the custom version, leaving all the options marked + flex grid the Js file does not contain the Off-Canvas module

I also downloaded the complete JS with standard grid, Off-canvas worked fine on 6.2, so it is only the customization interface and download failing.

Please check the web interface and see what needs to be done to correct this.

**Comment by rafibomb** [comment]
This appears to be fixed by @kball ! We'll close this, open a new issue if you find anything else with the customizer!
