### ISSUE TITLE
[SUGGESTION] Update "-zf-each-breakpoint" and "$breakpoint-classes" to allow breakpoints like "x only"

### ISSUE THREAD

**Issue by alexej-d** [zurb/foundation-sites#8552]
Hey everyone, I was wondering why F6's `-zf-each-breakpoint`-mixin does not have the possibility to create "small-only", "medium-down" etc. classes. Wouldn't it be nicer to let `$breakpoint-classes` be a comma separated list which would allow to define it as follows: `$breakpoint-classes: (small, small only, medium, medium only, large);`?

**Comment by brettsmason** [comment]
@alexej-d From what I understand you want to do only/down breakpoints? If so you can already do this, see [the docs](http://foundation.zurb.com/sites/docs/media-queries.html#breakpoint-function) - just write your breakpoint as `@include breakpoint(small only) {}`.

Does that solve the problem?

**Comment by alexej-d** [comment]
I am using the mixin to generate my own helper classes e.g. `.space-top-2-medium` or `.space-top-3-small-only` (later won't be generated with the F6 mixin) and I don't want to manually define all those classes or create my own mixin/function.

**Comment by DaSchTour** [comment]
As I know from foundation docs everything that starts with -zf is only for internal use and may change at any time, so with every version change it may be removed, renamed or change functionality. So the best way to go is to build your own functionality.

**Comment by alexej-d** [comment]
So maybe create a public mixin for the framework? Of course if I am the only one who would find that handy, this thread is to be ignored and can be closed.

**Comment by JeremyEnglert** [comment]
We'll consider this for V7. Thanks!
