### ISSUE TITLE
[Dropdown Menu] 'enter' keyboard press does not follow link

### ISSUE THREAD

**Issue by joejboland** [zurb/foundation-sites#8555]
**How can we reproduce this bug?**

1. http://foundation.zurb.com/sites/docs/dropdown-menu.html
2. Use keyboard to 'tab' to first example dropdown menu (or any example dropdown menu).
3. Press 'enter' on a menu item

**What did you expect to happen?**

Considering the example menus use empty links (href="#"), if the link was activated, the page would jump to the top and "#" would be appended to the url. This can be confirmed by using the mouse instead of the keyboard. Issue is with keyboard only, mouse clicks are working as expected.

**What happened instead?**

Nothing. Links are not activated.

**Test case**

The topbar for the Zurb Foundation site shares this same issue. Any of the dropdown menus, Learn, Develop, Support, Docs, will reproduce this same issue. Tab to the dropdown menu, and attempt to open any of the submenu items by pressing "enter".

**Comment by Owlbertz** [comment]
I already changed the links for the Drilldown Menu here #8477. I think we should do this for all links to ensure that this works well.

**Comment by totallyspun** [comment]
Hi, this is not resolved, but has been closed for over 2 years. I am unable to open the link of any dropdown menu item which contains a submenu, only trigger the submenu. As mentioned above, this affects even the Zurb website and all the dropdown menu examples in the documentation.

Requesting this be re-opened. Dropdown menu is not fully keyboard accessible and has not been for some time. Thanks.

**Comment by DanielRuf** [comment]
Hi @totallyspun,

please open a new issue, fill out the issue template and also reference this issue here.

**Comment by JeremyEnglert** [comment]
Just did a quick test, it's working fine for me. if you're still having issues, please follow Daniel's advice above and open a new issue so we can get this fixed.

**Comment by totallyspun** [comment]
I played around more and was able to follow the parent link with screen reader, but not simple keyboard nav without opening in new tab. If it was working for you, what is the method to follow link with simple keyboard command?

**Comment by JeremyEnglert** [comment]
Sorry, I misunderstood.

So you want a dropdown menu where the top-level item is also opens as a link? 

Unfortunately, that isn't currently supported. But I think we need to make note of that in the docs. For the dropdown menu to be accessible, the top level dropdown menus need to be empty links.

Any chance you want to take a stab at submitting a doc update PR?
