### ISSUE TITLE
slider with large initial value displays with buttons wedged at right

### ISSUE THREAD

**Issue by pscdodd** [zurb/foundation-sites#8557]
**How can we reproduce this bug?**

1. Step one
(foundation-rails 6.2.0.1)

Add double handled slider with a large starting values i.e. 1840 and end value:
`<div class="slider" data-slider data-start="1840" data-end="2000" data-initial-start="1840" data-initial-end="2000">
  <span class="slider-handle" data-slider-handle role="slider" tabindex="1"></span>
  <span class="slider-fill" data-slider-fill></span>
  <span class="slider-handle" data-slider-handle role="slider" tabindex="1"></span>
  <input type="hidden" />
  <input type="hidden" />
</div>`

2. Step two
View the page

**What did you expect to happen?**

The slider would be displayed proprtionally as with "0" and "100" end/starting values:
[  ]--------------------------------------------------------------------------------------------[  ]

**What happened instead?**
The slider is displayed with both handles at the far right. It is not possible to move the handles to the left.
--------------------------------------------------------------------------------------------[  ][  ]

The reason is probably that somewhere it is assummed that the starting value ist zero. In my case the values are years. OK, I could use calenders instead.

**Test case:**
[CodePen with Foundation 6 and MotionUI](http://codepen.io/pscdodd/pen/pypOvB)

**Comment by briantan888** [comment]
It will be fixed in foundation 6.2.1 as per PR #8506

**Comment by rafibomb** [comment]
Nice fix @briantan888 ! 6.2.1 is out now so we'll consider it fixed.
