### ISSUE TITLE
6.2.1 foundation-zurb-template still babel error? 

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#8560]
i am still getting the babel error. Can I update the foundation cli somehow? Or do I only get version 6.2.1 in a zip and not with the CLI? 
`[21:58:47] Failed to load external module babel-register`

**Comment by rafibomb** [comment]
Still looking for a solution on that one, is it causing any issues?

**Comment by phifa** [comment]
well, i think not so far. but i thought the whole 6.2.1 update was about fixing the babel issues? not sure, if i got this right though?

**Comment by phifa** [comment]
the bower.json still draws the 6.2.0: 

```
{
  "name": "foundation-ssg",
  "version": "1.0.0",
  "authors": [
    "ZURB <foundation@zurb.com>"
  ],
  "description": "Static site generator for Foundation for Sites.",
  "main": "gulpfile.js",
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "foundation-sites": "~6.2.0",
    "motion-ui": "~1.2.2"
  },
  "private": true
}

```

**Comment by colin-marshall** [comment]
@phifa ~6.2.0 will install the latest version between 6.2.0 and 6.2.9. Look inside the bower_components directory to see what version is installed. Are you getting that Babel error on brand new projects or older projects you updated?

**Comment by phifa** [comment]
brand new projects.

**Comment by colin-marshall** [comment]
And is 6.2.1 what's installed when you look in bower_components?

**Comment by phifa** [comment]
Yes, I think it is still 6.2.1. i made a video for you to see it yourself: 

http://recordit.co/nHkB0e0Sxl 

or as a gif: 

http://g.recordit.co/nHkB0e0Sxl.gif

**Comment by colin-marshall** [comment]
@phifa it looks like despite the babel error at the beginning, the javascript task still completes without error. Does the js actually get transpiled to ES5 and work like it's supposed to in the browser?

**Comment by phifa** [comment]
i have no idea. i think all the js works great. so far so good. but why the error?

**Comment by colin-marshall** [comment]
I don't know the exact reason for that error. You can ignore it though because it appears to use a fallback in the babel-core package. That's why it says `Requiring external module babel-core/register` right after the error. It finds the register module, just not on the first try. The most important thing is that the transpiling is working.

**Comment by TheRealDavid** [comment]
I'm on a mac and experiencing the same thing. If I run "foundation watch" on projects downloaded by the CLI, I get the error. If I run it on projects downloaded and installed manually, I don't get the error. I think there's something wrong with the way the CLI installs projects.

**Comment by fndaily** [comment]
Correct me if I'm wrong but you can also run ```bower update``` and pull the latest Foundation 6.2.1 sources into an existing project..

**Comment by colin-marshall** [comment]
I can confirm that the error appears when the project is installed via the CLI, but does not appear when manually cloning a template. Good find @TheRealDavid, we'll look into this issue with the CLI.

**Comment by colin-marshall** [comment]
**Update:** If seeing the error really annoys you, you can run `gulp` instead of `foundation watch` for the time being and it won't be there.

I think it has to do with the `foundation` command being run globally so it looks in the wrong place for `babel-register` at first but then corrects itself.
