### ISSUE TITLE
grid-row-nest mixin output duplicates max-width property per breakpoint

### ISSUE THREAD

**Issue by alexej-d** [zurb/foundation-sites#8566]
[This declaration](https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_row.scss#L88) duplicates the `max-width` property. It should be moved above `@each $breakpoint, $value in $gutter`.

**Comment by colin-marshall** [comment]
Thanks @alexej-d! Care to put in a pull request so you get credit for your contribution?

**Comment by alexej-d** [comment]
@colin-marshall Done :smile:
