### ISSUE TITLE
Updating Foundation version with the Foundation for Sites Template CLI

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#8568]
I have an installation with Foundation for Sites 6.2.0. It's a complete Foundation CLI setup with handlebars. What is the recommended way, concrete steps to update this installation now to 6.2.1? 

The docs only talk about installation, not about update. I think this would be really helpful if it were in the docs: http://foundation.zurb.com/sites/docs/installation.html

**Comment by brettsmason** [comment]
Hey @phifa you just need to run `bower update` from your project folder - this will update everything to the latest version. Also thanks for the feedback on adding some update info - I'll flag this so it gets looked at.

**Comment by phifa** [comment]
so `bower update` does everything? that's it? and when changes on the `settings.scss` or `app.scss` are performed I have to add them manually I guess, right?

**Comment by brettsmason** [comment]
Yes any changes to `_settings.scss` you would need to update manually. They are always detailed in the [release notes](https://github.com/zurb/foundation-sites/releases) though to make that easier.

**Comment by phifa** [comment]
that is great. yeah, so documenting the various update procedures would be super helpful. what is to do when updating a minor/major version, etc. Thanks!
