### ISSUE TITLE
[Tabs] Prevent default browser behavior only if keyboad key press is handled by the plugin

### ISSUE THREAD

**Issue by dchekanov** [zurb/foundation-sites#8569]
Currently Tabs plugin [prevents](https://github.com/zurb/foundation-sites/blob/develop/dist/plugins/foundation.tabs.js#L151) browser from reacting to all keyboard key presses (except for the "Tab") when any tab link has focus.

This negatively affects user experience as it is not clear why nothing happens when I try, for example, to reload a page after clicking on a tab using a keyboard key.

How to reproduce: http://foundation.zurb.com/sites/docs/tabs.html, click on any rendered tab link ("Tab 1", for example) and press F5 (on Windows, Mac users can press whatever button/combo is used to reload a page).

I'd say this plugin (and any other in Foundation) shouldn't prevent default browser reaction to key presses unless that plugin handles those exact events.

**Comment by Owlbertz** [comment]
Hi @dchekanov. Thanks for reporting this. I am currently enhancing the keyboard util to reduce the events handled with `preventDefault()`, so this will be fixed soon. In the meantime I will assign this issue to me to prevent someone else from putting effort into this.

**Comment by kball** [comment]
Fixed in 5a1450d, will be in 6.2.2
