### ISSUE TITLE
[Dropdown] Horizontal position does not work with additional classes

### ISSUE THREAD

**Issue by maggo** [zurb/foundation-sites#8572]
When adding classes after float-left/right the regex in [foundation.dropdown.js#L74](https://github.com/zurb/foundation-sites/blob/7133cd464357e00566efbc2df8549209755f0a8c/js/foundation.dropdown.js#L74) will no longer read the horizontal position correcly. The matched string will be everything till the last space, see this [RegexPal example](http://www.regexpal.com/?fam=94612)

Testing for float-left and float-right explicitly or writing the regex like ```/float-(\S+)\s/``` should fix this.

**Comment by ncoden** [comment]
Pull request: https://github.com/zurb/foundation-sites/pull/8579
