### ISSUE TITLE
Abide - "required" checkboxes do not validate

### ISSUE THREAD

**Issue by Visiluna** [zurb/foundation-sites#8574]
**How can we reproduce this bug?**

1. Create an "abide-ready" form (`data-abide novalidate`)
2. Add a checkbox input with the `required` attribute, a "form-error" `span`, and a submit button.
3. Load the form and submit without checking the checkbox.

**What did you expect to happen?**

Prevent submit and display error.

**What happened instead?**

Form submits anyway, without the checkbox checked.

**Test case:**

- [CodePen with Foundation 6.2.1](http://codepen.io/visiluna/pen/PNQOEW)

**Comment by briantan888** [comment]
Created PR #8576 to fix this requiredCheck. Though a checkbox-group check would be more meaningful than required attribute on individual checkbox input. pr #8542was created to validate checkbox in group.

**Comment by Visiluna** [comment]
My use case it to create a "I have read and agree to the Terms of Service" checkbox. If you don't read and agree, you can't submit.

**Comment by briantan888** [comment]
If you don't want to wait for next release, it's just a 3 lines patch that you can update in foundation.js and/or foundation.abide.js

**Comment by Visiluna** [comment]
Unless the next release is forthcoming, I'd appreciate the patch.

**Comment by briantan888** [comment]
patch foundation.abide.js function requiredCheck.

https://github.com/zurb/foundation-sites/pull/8576/commits/638c06cf20dd617b6ff7a9c39c2d709c4e4a26d2

**Comment by Visiluna** [comment]
Thanks.
