### ISSUE TITLE
[Button Group] margin-bottom

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#8575]
If Button Groups have enough Buttons to wrap to multiple lines, the lines are flush against each other. Should we add `margin-bottom: $buttongroup-spacing`? 

Here's an example showing before/after this proposed fix: 
http://codepen.io/andycochran/pen/jqZYMX

Relatedly, how does this effect button radius (e.g. #8447 Should radius go on the button or the group)?

**Comment by Owlbertz** [comment]
+1 for the `margin-bottom` from my side.
Also, personally I always liked the radius for the whole group better.

**Comment by brettsmason** [comment]
I agree with @owlbertz on everything! Looks good.

**Comment by andycochran** [comment]
I agree, @Owlbertz; radius on the whole group makes sense most of the time. But not all the time. I'm not sure how radius on the group work with this multi-line case.

**Comment by phifa** [comment]
+1 radius on whole group
