### ISSUE TITLE
Nested flex grid set to block display

### ISSUE THREAD

**Issue by sspread** [zurb/foundation-sites#8577]
**How can we reproduce this bug?**
1. Use flex box
2. Create a nested flex grid structure having .row > .row.column > .column

**What did you expect to happen?**

Grandchildren .column would have display flex.

**What happened instead?**

Grandchildren .column have display block

See commit https://github.com/zurb/foundation-sites/commit/207a1b374d625e6af7bc639a29fa036a128b023f

**Comment by sspread** [comment]
@gakimball

**Comment by phifa** [comment]
is this legal? 
.row > .row.column > .column

shouldn't there be another row? 
 .row > .row.column > .row > .column

**Comment by sspread** [comment]
My understanding is that a column can serve as a row `.row.column` for the nested grid. It's possible I've been using it incorrectly, but it's been working as I would expect until the commit above.

**Comment by sspread** [comment]
If I change to `.row > .column > .row > .column` it works as expected with the commit above. This issue can probably be closed.

**Comment by homamghassemy** [comment]
I have the same problem. I upgraded from 6.2 to 6.2.1 and all my application which has too many pages failed to render as it supposed to. now I am going to change all nesting structures.
I had used nesting with float grid and flex grid in foundation for sites 6.2

**Comment by kball** [comment]
closing based on the above conversatino.
