### ISSUE TITLE
Deprecation warning in _button-group.scss // foundation-sites 6.2.1

### ISSUE THREAD

**Issue by Luckyfella73** [zurb/foundation-sites#8580]
I just updated from 6.2.0 to 6.2.1 via bower and get the following deprecation warning while saving:

```
DEPRECATION WARNING on line 81 of
/......./vendor/bower/foundation-sites/scss/components/_button-group.scss:
#{} interpolation near operators will be simplified
in a future version of Sass. To preserve the current behavior, use quotes:

  unquote('#{$buttongroup-spacing} == "0"')
```
 Sass is still able to compile the .css file but who wants to see warnings on every save ;)

Following the console output and replacing line 81 of _button-group.scss

`@if #{$buttongroup-spacing} == '0' {`

with

`@if unquote('#{$buttongroup-spacing} == "0"') {`

let the error message disappear. But I'm not familiar enough with sass so I can't say if that's the way to go.

**Comment by colin-marshall** [comment]
Thanks for pointing this out @Luckyfella73. Care to put in a pull request for it?

**Comment by Luckyfella73** [comment]
@colin-marshall 
I use git for my projects but never made a pull request for github projects. I'm going to research and try if I get I to work ;)

**Comment by Luckyfella73** [comment]
I forked the repo, did the changes and made a pull request (I was asked to do a merge - hope everything went fine with that)

**Comment by magiobus** [comment]
I have the same problem trying to deploy to production, tried replacing the line but it didn't work, any suggestions?

**Comment by colin-marshall** [comment]
@Luckyfella73 sorry that I'm late on this. It looks like you made the pull request on your forked repo instead of on this repo. Please do the following:
- Push the `Luckyfella73-patch-1` branch to your fork on GitHub (again)
- Open https://github.com/zurb/foundation-sites/
- Click the "alert" towards the top of the page about opening a pull request based on the branch you just pushed to your fork

If for some reason that alert isn't there after repushing the branch, you can do the following:
- [Open a new pull request](https://github.com/zurb/foundation-sites/compare) on this repo
- Click the "compare across forks" link
- Change the head fork to `Luckyfella73/foundation-sites`
- Change the branch to `Luckyfella73-patch-1`
- Mention this issue (#8580) in the comment

Thanks!

**Comment by colin-marshall** [comment]
@magiobus @Luckyfella73 are you guys using Ruby Sass?

**Comment by magiobus** [comment]
I'm using the latest versions:
gem 'sass-rails', '~> 5.0'
gem 'foundation-rails', '~> 6.2', '>= 6.2.1.0'

**Comment by colin-marshall** [comment]
@magiobus thanks for doing the pull request! Does it work for you now? Sounded like it made no difference for you upthread.

**Comment by magiobus** [comment]
Don't know cause I'm using foundation-rails gem

Is the foundation-rails gem updated with the develop branch of foundation-sites repo? 
Or they have independent versions ? 

The error only happens to me when I try to deploy to my server, in development is ok.

**Comment by colin-marshall** [comment]
No I do not believe those branches are up to date with each other. I think with every release of Foundation Sites the Rails gem is updated (not sure if manual or automated) but nothing happens between releases to the Rails gem.

For testing purposes can you just go into `vendor/assets/scss/components/_button-group.scss` and try to change it in there? I am not familiar with the Rails gem and have limited Rails knowledge.

**Comment by Luckyfella73** [comment]
@magiobus thanks for doing the pull request for me though I would have liked to do it by myself for the first time here on github ;)

@colin-marshall you asked for ruby and sass - so here is what my terminal says:
`ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]`
`Sass 3.4.22 (Selective Steve)`

**Comment by andycochran** [comment]
This is unnecessary since the `@if` has already been removed from the develop branch.

**Comment by colin-marshall** [comment]
Thanks @andycochran!

**Comment by magiobus** [comment]
It worked after all, I don't know why it showed that error, but after dealing with nginx in production, it succeed to compile foundation without errors. Misteries of the universe jeje. 

Thanks! @andycochran @Luckyfella73  @colin-marshall
