### ISSUE TITLE
[Sticky] Sticky Container not Re-flowing on Resize

### ISSUE THREAD

**Issue by merlihan** [zurb/foundation-sites#8587]
**How can we reproduce this bug?**

1. Step one - Visit this page: http://foundation.zurb.com/sites/docs/sticky.html
2. Step two - Resize the browser (1300 seems to be consistent)
3. Step three - Scroll down to "Advanced"
4. Step four - Scroll up and down repeatedly

**What did you expect to happen?**
I expected the sticky elements to reflow without overlapping.

**What happened instead?**
The Orbit photo overlaps the text above it.

NOTE - This happens intermittently.  

Give us a link to a CodePen or JSFiddle that recreates the issue.
N/A this issue is recreated on the doc page here: http://foundation.zurb.com/sites/docs/sticky.html

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

![image](https://cloud.githubusercontent.com/assets/4990374/14475465/1219e2a2-00d0-11e6-99d9-bf3ad76e103d.png)

**Comment by merlihan** [comment]
Hi there,  Just checking if this ticket is now stable. Looks like it was closed then reopened. :(

**Comment by andycochran** [comment]
@merlihan Did #8715 take care of this?

**Comment by merlihan** [comment]
@andycochran Yes, it did!  Thank you!
