### ISSUE TITLE
Error using repeating-linear-gradient

### ISSUE THREAD

**Issue by Davidrl1000** [zurb/foundation-sites#8596]
When you use the property 'repeating-linear-gradient', for example:

`div{
    background: repeating-linear-gradient( -45deg, #e0e0e0, #e0e0e0 7.5px, #d9d9d9, #d9d9d9 10px);
}`

after that you run 'npm run build' it transform the line and removes its spaces, so the results is this: 

`div{
    background: repeating-linear-gradient( -45deg, #e0e0e0, #e0e0e07.5px, #d9d9d9, #d9d9d910px);
}`

And with that line the linear gradient doesn't work

**Comment by colin-marshall** [comment]
@Davidrl1000 are you using a template to compile the SCSS? It might be a libsass bug.

**Comment by Davidrl1000** [comment]
No I am not using any template, I am building my own template

**Comment by ncoden** [comment]
Hi @Davidrl1000. Sorry for the late reply.

Do you still have this problem ?

**Comment by Davidrl1000** [comment]
No @ncoden I don't having that problem anymore, thanks
