### ISSUE TITLE
Problems with Meteor installation

### ISSUE THREAD

**Issue by fjorgemota** [zurb/foundation-sites#8606]
**How can we reproduce this bug?**

1. Step one
Create a new Meteor project, using latest Meteor release (actually **Meteor 1.3.1**):

```
meteor create foundation-test
```

2. Step two
Enter `foundation-test` directory and try to add `zurb:foundation-sites` package:
```
meteor add zurb:foundation-sites
```

**What did you expect to happen?**
I expect the `zurb:foundation-sites` to be installed and the `meteor add` command to finish correctly.

**What happened instead?**
```
$ meteor add zurb:foundation-sites
 => Errors while adding packages:             
                                              
While checking for zurb:foundation-sites@6.2.1_1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

And the package is not installed.
**Test case:**
I think there's no way to create a Test case for that problem.

**Additional info:**
Initially I think that the problem only affected **Meteor 1.3** projects, but, with a **Meteor 1.2.1** project (created using `meteor create --release 1.2.1 foundation-test` instead of just `meteor create foundation-test`), the problem seems to occur too...

**Comment by kball** [comment]
Taking a look

**Comment by kball** [comment]
Should be fixed.  @fjorgemota can you try now and confirm it works for you?

**Comment by fjorgemota** [comment]
Yeah!

It worked.

Closing issue now.

Thanks, @kball! :)
