### ISSUE TITLE
Bringing "destory" to Zurb 5.5.x - Anyone interested?

### ISSUE THREAD

**Issue by dragthor** [zurb/foundation-sites#8612]
Before I start dedicating time back porting Zurb 6's `destroy` feature to Zurb 5.5.x, is there anyone interested in this feature?  (besides me).

I really like the idea of unbinding events and each component cleaning itself up.

`$(document).foundation('tooltip', 'destroy');`

Let me know.  I would like to gauge whether my effort would be effective and helpful to anyone else.

**Comment by dragthor** [comment]
I'll take the lack of response as a no.  Instead I'll focus on Zurb 6 issues. Hopefully I can help.

**Comment by colin-marshall** [comment]
@dragthor I think in the near future they are planning on revisiting Foundation 5 to fix some bugs for a 5.5.5 release. Obviously there are more pressing issues with v6 at the moment. We will consider this once it's time to revisit v5. Thanks!

**Comment by HansUXdev** [comment]
I'm honestly starting to miss foundation 5.5. It was a bloated beast of a giant but goddamn was it stable...

Anyhow this issue should probably be closed I' guessing?

**Comment by colin-marshall** [comment]
Very sorry for the late response. We are moving on to Foundation 7, and there will be no more development or support for Foundation 5. I am closing this one out.
