### ISSUE TITLE
[Equalizer] not working in Internet Explorer

### ISSUE THREAD

**Issue by mfell** [zurb/foundation-sites#8613]
**How can we reproduce this bug?**

Very simple: Just open your Website in IE :o)
http://foundation.zurb.com/sites/docs/equalizer.html

(Thank's a lot for your work, I love Foundation!)

Bye Marc (info@marc-fell.de)

![unbenannt](https://cloud.githubusercontent.com/assets/6691773/14566620/92e1a23c-0330-11e6-9dc5-82a4059b97e8.PNG)

**Comment by dragthor** [comment]
I just tested.  Here are my results.  Is it a certain break point or something?

Windows 7, IE 11 works fine.
Windows 7, IE 10 works fine.
Windows 7, IE 9 works fine.
Windows 10, Edge 12 works fine.
Windows 10, Edge 13
Windows 10, IE 11 works fine.
Windows 8.1, IE 11 works fine.

**Comment by mfell** [comment]
Shit ... you're right! :o/
After one resizing of the bowser window, it's gone.
I tried it many times before - see my screenshot. Funny.

Sorry for my bug report and thanks a lot for your quick response!
