### ISSUE TITLE
.hide-for-large class has overflow issue on small screen.

### ISSUE THREAD

**Issue by jwfranks** [zurb/foundation-sites#8615]
**How can we reproduce this bug?**

.hide-for-large class has overlfow issue on small media for email templates.
Add class to an item and resize the media to small. Overflow issue is obvious. (It happens in the demo as well http://foundation.zurb.com/emails/docs/visibility.html)

Item with class should display

Item with class displays with issues.

I was able to correct this locally by resetting the max-height back to inherit. There maybe a better way to solve this but following the css order, max-height is set to 0 but never adjusted on small detection.

  @media only screen and (max-width: [width]px) {
    table.body table.container .hide-for-large {
      display: block !important;
      width: auto !important;
      overflow: visible !important;
      max-height: inherit; } }

 

Give us a link to a CodePen or JSFiddle that recreates the issue.

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by colin-marshall** [comment]
@jwfranks I believe this belongs on the Foundation for Emails repo. You should open a new issue over at https://github.com/zurb/foundation-emails/issues instead of here. Thanks!
