### ISSUE TITLE
$primary-color being ignored

### ISSUE THREAD

**Issue by peterbournecommunications** [zurb/foundation-sites#8623]
Problem with using the new $foundation-palette:
I've set a new primary color in this $foundation-palette - and I've included add-foundation-colors. (All in my _settings.scss file).

However - I still get the default Foundation blue for my button backgrounds etc. This is clear from analysing the compiled css etc.

It seems the foundation-palette in _global.scss is overwriting my own _settings.scss file.

Latest Foundation for Sites was installed via bower (6.2.1).

What have I done wrong - or is this a bug?

Here's my  _settings.scss  (the start of...):

```
@import 'util/util';

// 1. Global
// ---------

$global-font-size: 100%;
$global-width: rem-calc(1200);
$global-lineheight: 1.5;
$foundation-palette: (
		primary: #c90105,
		secondary: #a6a6a6,
		success: #3adb76,
		warning: #ffae00,
		alert: #ec5840,
);
$light-gray: #e6e6e6;
$medium-gray: #cacaca;
$dark-gray: #8a8a8a;
$black: #0a0a0a;
$white: #fefefe;

$body-background: $white;
$body-font-color: $black;
$body-font-family: 'Noto Sans', 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;
$body-antialiased: true;
$global-margin: 1rem;
$global-padding: 1rem;
$global-weight-normal: 400;
$global-weight-bold: 600;
$global-radius: 0;
$global-text-direction: ltr;
$global-flexbox: false;
$print-transparent-backgrounds: true;

@include add-foundation-colors;

/* rest of scss _settings here.... */
```

And here's my app.scss that pulls things together (it does compile successfully via gulp)...
```
@import url(https://fonts.googleapis.com/css?family=Noto+Sans:400,400italic,700,700italic);

@import 'foundation';
@include foundation-everything;

@import 'settings';

/* rest of css here... */
```

Anythoughts - is it my implementation or a bug?

**Comment by Deckluhm** [comment]
`_settings.scss` should be imported before any Foundation file:
```Sass
@import 'settings';

@import 'foundation';
@include foundation-everything;
```

**Comment by peterbournecommunications** [comment]
Well that's me being stupid then.

Many thanks  Deckluhm - apologies... new to SASS and this way of working with Foundation!

Thankyou again.
