### ISSUE TITLE
[Accordion] destroy js error

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8624]
calling
```js
$('[data-accordion]').foundation('destroy');
```
results in a js error
TypeError: _this2.$element is null
http://192.168.0.2:3000/assets/js/foundation.js
Line 2523

**Comment by denisahac** [comment]
Try to be specific in your selector, change it with the ID instead. [Foundation Accordion](http://foundation.zurb.com/sites/docs/accordion.html)

**Comment by designerno1** [comment]
ok thats strange why?

**Comment by designerno1** [comment]
i reopen this
also calling
```js
$('#accordion-test').foundation('destroy');
```
results in the error
in codepen not every time but on normal sites more often
http://codepen.io/designerno1/pen/mPKzaK

**Comment by denisahac** [comment]
@designerno1 What's the error? What do you expect to happen after calling `$('#accordion-test').foundation('destroy');`?

**Comment by designerno1** [comment]
```js
TypeError: _this2.$element is null
http://192.168.0.2:3000/assets/js/foundation.js
Line 2523
```
i expect to destroy the plugin without an error

**Comment by designerno1** [comment]
ok i addressed the issue
setting data-slide-speed="2000"
to something big causes the trigger function in slideUp(0) called by destroy to generate the error because in destroy the $element is cleaned up and then the trigger function on slideUp callback the $element is null
https://codepen.io/designerno1/pen/GZGYPB
