### ISSUE TITLE
Repeated lines

### ISSUE THREAD

**Issue by ericklarac** [zurb/foundation-sites#8625]
foundation.css has repeated elementes in the following lines:
-447
-1569
-2177
-2765
-2889

**Comment by ncoden** [comment]
@ericklarac Thanks for the issue, but *line numbers in `foundation.css`* isn't helping a lot. Can you give here the repeated elements ?

**Comment by ericklarac** [comment]
Yes, sorry. I'll text you back when I have my computer

**Comment by kball** [comment]
Closing this due to lack of reply. Please reopen if you have more info.
