### ISSUE TITLE
Issue with top-bar and slick carousel 

### ISSUE THREAD

**Issue by barzev** [zurb/foundation-sites#8627]
I am using Foundation 5, a sticky scrollbar and Owl Carousel (I have tried using Slick carousel and the result is the same).

The issue I'm experiencing is that whenever I scroll up/down and the top bar goes over the carousel, the whole page stutters and the scroll bumps and stops shorter than its expected trajectory.

I have tried a lot of solutions including applying z-index and -webkit-transform: translateZ(0) rules to the carousel with no success.

This problem doesn't seem to exist in Firefox or Edge or at least is not as obvious.

Any ideas?

**How can we reproduce this bug?**

Scroll up and down the page. Especially scroll up. Also, carousel would flicker when scrolling down if there is margin between carousel and topbar
**What did you expect to happen?**

**What happened instead?**

The page lags/scroll stutters.

**Test case:**

- [Site I'm working on](http://envirodental.group.shef.ac.uk/test/index.html)

**Comment by colin-marshall** [comment]
What browser/operating system does this appear the worst on? I tried in Chrome and Safari on Mac and couldn't reproduce.

**Comment by barzev** [comment]
Windows 7+, Chrome. You have to scroll up fast and steady. No issues with IE and Firefox.

**Comment by barzev** [comment]
Resolved in the following way:

`body { -webkit-transform: translate3d(0, 0, 0);`
