### ISSUE TITLE
Reveal modal with 'full' class allows page scrolling on iOS

### ISSUE THREAD

**Issue by AndresUnity** [zurb/foundation-sites#8628]
**How can we reproduce this bug?**

1. Create a test with page that has more content than fits in an iPhone viewport. Something that requires scrolling to read.
2. Open a Reveal modal that has the 'full' class on iOS:  `class="reveal full"`
3. Scroll
´
**What did you expect to happen?**

I expect the html and body elements to not scroll. The content beneath the modal should not be visible.

**What happened instead?**

I saw the rest of the content beneath the modal. The modal just scrolled with everything else.

**Fix**

At the moment I've done to the HTML element the same thing Foundation already does for the BODY element: add the class `.is-reveal-open`

```
html.is-reveal-open {
    overflow: hidden;
}

$(document).on('open.zf.reveal', function() {
    $('html').addClass('is-reveal-open');
});
    
$(document).on('closed.zf.reveal', function() {
    $('html').removeClass('is-reveal-open');
});
```

**Comment by Owlbertz** [comment]
Thanks for reporting this. Could you check on how this interferes with #7548 (and the issues that link to this one)? Reveal and scrolling on mobile, especially iOS, was always a bummer. Your solution seems pretty simple, so if you can confirm this works and fixes your issue as well as the one(s) mentioned above, we're happy to see a PR!
