### ISSUE TITLE
[Reveal] Nested reveal with animation auto closes when focus on input field

### ISSUE THREAD

**Issue by phoenixgao** [zurb/foundation-sites#8629]
I have two reveal modal, A and B, both of them contains a form with input fields.

in A there's a button to open B, and in B there's also a button to open A.

So first I open reveal A, then open B from A, then switch back to A from B, and click inside any input field, the reveal dialog will be gone, but the overlay remains and unremovable.

It only happens if I use data-animation on those reveals, without animation they work well.

codepen example:
- [CodePen with Foundation 6.2.1 and MotionUI](http://codepen.io/phoenixgao/pen/ONEydM)

I'm using chrome 49.0.2623.110 on Mac

**Comment by phoenixgao** [comment]
Or, should I report this on motion-ui instead?

**Comment by kball** [comment]
Woah, that's an odd one.  I think it is a reveal bug, not a motion-ui issue.  I don't think we'll get to this for 6.2.2 but should definitely get it for 6.2.3

**Comment by phoenixgao** [comment]
Hello, any news on this bug?

The issue still exists on foundation 6.2.3 with motionui 1.2.2

**Comment by 99M8** [comment]
Hello, is there anyone how's looking into it? If no, I would like to take this on.

**Comment by DanielRuf** [comment]
Hi @99M8, contributions and help are very welcome.

Does the issue still exist in a new build from the current develop branch?

**Comment by DanielRuf** [comment]
Closing as we did not receive further feedback or reports from other users.

**Comment by phoenixgao** [comment]
@DanielRuf 

I created a new codepen with the latest foundation 6.5.3, motion-ui 2.0.3 and the issue still exists.

https://codepen.io/anon/pen/jgaEGQ

**Comment by DanielRuf** [comment]
Hi @phoenixgao,

please open a new issue with all details and fill out our new issue template.

**Comment by DanielRuf** [comment]
Hi @phoenixgao,

thanks for the update.
Please open a new issue with all details and fill out our new issue template.
