### ISSUE TITLE
About the Orbit Slide Direction

### ISSUE THREAD

**Issue by simongcc** [zurb/foundation-sites#8638]
Foundation Version: 6.2

I write customized function to change slide so I use
$('#element').foundation('changeSlide', isLTR, chosenSlide, idx);

I think isLTR read is Left to Right, but inside the code in foundation.orbit.js.
Line 279:

```
dirIn = isLTR ? 'Right' : 'Left',
dirOut = isLTR ? 'Left' : 'Right',
```

That's means, if isLTR == true, direction in is from Right and dirOut is to Left
It seems the direction is negated. Am I correct?

**Comment by Owlbertz** [comment]
LTR refers to [the orientation of your site](http://foundation.zurb.com/sites/docs/rtl.html) and not to the plugin in particular. Maybe that's what seems wrong to you?

**Comment by simongcc** [comment]
LTR and RTL normally refer to website text orientation which I can see..
But in orbit plugin, as I tried by modifying the code, it seems to means the slide motion direction from.
It is to control where should the slide from, from left to right or from right to left.
And it seems the direction is just negated as opposed to the meaning of the variables.

**Comment by ncoden** [comment]
Hi @simongcc, sorry for the late reply.

I agree with you. Left and Right are in the wrong order here. With LTR, `animInFrom${dirIn}` should be `Left` and `animOutTo${dirOut}` should be `Right`.

@Owlbertz I am right ?

**Comment by Owlbertz** [comment]
I don't know who built that, but I think the intention was:
- for LTR sites slides come in from right to left because that's how content is consumed in LTR cultures
- for RTL it's vice versa

I do agree that it is confusing and I tend to agree that you could say it's currently the wrong order.

**Comment by ncoden** [comment]
I understand. It's slides. Maybe we could add a comment here, because `dirIn = isLTR ? 'Right' : 'Left'` seems totally wrong at first.

**Comment by JeremyEnglert** [comment]
@Owlbertz @ncoden - is this a bug or simply a point of confusion? If the latter, we can close.

**Comment by Owlbertz** [comment]
For me it's a point of confusion that we should avoid in future releases, e.g. by introducing an option called slideInDirection or similar.

**Comment by DanielRuf** [comment]
@Owlbertz do you want to provide the PR with the comment and update the docs or can I also do this?

**Comment by Owlbertz** [comment]
Feel free to make a PR.

**Comment by DanielRuf** [comment]
> I agree with you. Left and Right are in the wrong order here. With LTR, animInFrom${dirIn} should be Left and animOutTo${dirOut} should be Right.

Not really.

`isLTR` is true when we click the next button or swipe to the left or click one of the bullets the slide moves from right to left.

**Comment by DanielRuf** [comment]
I've provided a PR which is merged now.

The docs should read then `isLTR - if true the slide moves from right to left, if false the slide moves from left to right.`

Are you all ok with this?

**Comment by DanielRuf** [comment]
Hi @simongcc, thanks for the feedback.
