### ISSUE TITLE
Button Group child-selector via mixin not working

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#8647]
`@include button-group('.group__item');` does not work. Children must have always `.button`. But the docs say that this should work: http://foundation.zurb.com/sites/docs/button-group.html#button-group

**Comment by denisahac** [comment]
Use `@include button-group($child-selector: '.group__item');` instead.

**Comment by JeremyEnglert** [comment]
@phifa please let me know if the above does not fix your issue and i'll reopen this ticket.
