### ISSUE TITLE
.top-bar-left and .top-bar-right don't have the width attribute set to auto on medium & larger screens anymore

### ISSUE THREAD

**Issue by koernchen02** [zurb/foundation-sites#8648]
**How can we reproduce this bug?**

1. I did an `bower update` and got `foundation-sites#6.0.6 bower_components/foundation-sites`
2. I ran gulp 
3. My distributed files don't respect mediaqueries for my topbar sections (.top-bar-left and .top-bar-right ) anymore. The width of both of the elements stays 100% which makes them stack one underneath the other. The css compiled on http://foundation.zurb.com/sites/docs/top-bar.html
does include:
```
_top-bar.scss:119 @screen and (min-width: 40em)

.top-bar .top-bar-left, .top-bar .top-bar-right {
    width: auto;
}
```
I'm positive that I did not overwirte the default top-bar styling in anyway with my additional scss files.
The files I compiled don't have that mediaquery.

**What did you expect to happen?**
I expected the behaviour on screens >= medium to stay the same since I'm using the floats to structure my navigation.

**What happened instead?**
The behaviour changed and I can only assume that breaks at least some Navigations in other projects.

**Comment by denisahac** [comment]
Please use the latest version of ZF which is v6.2.1 instead of 6.0.6.

**Comment by koernchen02** [comment]
Thanks for pointing that out... I'm new to bower etc. and thought that a project created with the foundation-cli would always update against "latest". Doing that manually introduces further problems but this issue is of course pointless know!

Anyways... @denisahac thanks for the quick reply!!!
