### ISSUE TITLE
[NEW FEATURE] ResponsiveAccordionTabs plugin

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8651]
# ResponsiveAccordionTabs

Please give me your opinion:
http://codepen.io/designerno1/full/eZjdJV/
### Features
- [x] Responsive settings `"breakpoint-plugin"`
- [x] Converts Tabs markup to Accordion and vice versa
- [x] Converts Accordion markup to Tabs and vice versa
- [x] correct opened Panel stays open through resize
- [x] Custom linkClass and panelClass supported (data-attributes supported)
- [x] cleanup and optimize code
- [x] write a docs page
- [ ] JS unit tests
- [x] visual tests
#### So please give me a Feedback
- great should be in Foundation Core
- great should be available as a Plugin
- no need for that feature

@zurb/yetinauts

**Comment by Silvester20** [comment]
Totally awesome!. I would like to see this as plugin.

**Comment by andycochran** [comment]
Rad!

**Comment by colin-marshall** [comment]
This is sweet! Here's a few thoughts at first glance:
- I think the name "Responsive Accordion Tabs" is easier to pronounce than "Responsive Tabs Accordion"
- Is this something that could be done without adding a plugin? Would it be better if you could just add the `data-responsive-settings` attribute to any Tabs or Accordion and have it work, without changing anything else?
- Add JS unit tests and visual tests to your checklist, but don't work on those until we decide how this is best implemented.
- Something is wrong with your last 2 examples that deal with `data-link-class` and `data-panel-class`. Accordion is messed up on medium-up and the tabs are messed up on small.

**Comment by designerno1** [comment]
@colin-marshall 
1. ok i could rename the plugin
2. i think about it if it is possible
3. added
4. my custom data-link-class and data-panel-class have no styling only to test if it works ou can toggle tabs so it works only no styling

**Comment by brettsmason** [comment]
Really great work! This is a feature I really miss from Foundation 4 (panels) so I'd like to see this get added. It feels very much like the responsive navigation too which is a good thing.

**Comment by Owlbertz** [comment]
Looks good :+1:.  I almost think this should be part of of F6 core, just like the Responsive Menu thingy.

**Comment by brettsmason** [comment]
Yep agreed I'd prefer it to make it directly into core :thumbsup:

**Comment by kball** [comment]
This feels coherent as something that makes sense in core to me.  @rafibomb what do you think?

**Comment by kball** [comment]
The responsive accordion tabs feature has been merged and released in 6.3!
