### ISSUE TITLE
[Dropdown] Dropdown absolutely doesn't work

### ISSUE THREAD

**Issue by succli** [zurb/foundation-sites#8652]
Tried to make a dropdown to my site, but after I click on the button nothing happens. In Chrome's Developer Tools I see JS is triggered, but the is-open class is missing. I copied the one of the documentation examples to see if I'm mistaking something. Still not works.

The version is the newest 6.2.1.

**Comment by bergschrat** [comment]
For me the foundation.css was broken, which is in the download (Complete download and Essential download). I have the foundation.css replaced by foundation.min.css, now it works. See:
http://www.ringelrose.de/anni/kromis.html

**Comment by andycochran** [comment]
@succli Could you link to an example of it not working? Can you replicate the problem in a codepen?

**Comment by kball** [comment]
Closing this based on lack of response or repro case.  Please reopen if you are still running into this issue...
