### ISSUE TITLE
[JavaScript] Setting of default values like described in docs does not work.

### ISSUE THREAD

**Issue by COLABORATI** [zurb/foundation-sites#8661]
in app.js I want to do this: 
```
Foundation.Sticky.defaults.margin-top = '0';
Foundation.Sticky.defaults.sticky-on = 'small';  
```
but I get a compilation error:
```
[19:55:37] '<series>' errored after 4.62 s
[19:55:37] SyntaxError in plugin 'gulp-babel'
Message:
    /src/assets/js/app.js: Assigning to rvalue (8:4)
```

The setting of default values does not seem to work like described in the docs.

**Comment by IAmEddieDean** [comment]
That's how variables are assigned in html attribute values. You need to use camelCased values here, so:
```js
Foundation.Sticky.defaults.marginTop = 0;
```

**Comment by colin-marshall** [comment]
Thanks @IAmEddieDean! Glad to see you're still around Chris.

Marking this as resolved.

**Comment by COLABORATI** [comment]
Ha! Thanks! Names...
