### ISSUE TITLE
[off-canvas] close callback function from docs missing

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8662]
cb as described in docs missing `optional cb to fire after closure`
open and toggle has no cb but event,trigger
close has no event, trigger.

maybe we should unify those functions to `(event, trigger, cb)`

**Comment by designerno1** [comment]
@zurb/yetinauts 
any thoughts?

**Comment by kball** [comment]
The callback function has been removed from the docs - listening for the events is the preferred mechanism
