### ISSUE TITLE
Error on the title-bar spacing set up for menu-icon

### ISSUE THREAD

**Issue by EduardoAC** [zurb/foundation-sites#8664]
**How can we reproduce this bug?**
1. Step one
2. Step two
3. Step three

**What did you expect to happen?**
Icon spacing should be handle for the same variable for margin-left and margin-right
**What happened instead?**
You defined $tile-icon-spacing only for left side, no option of right margin without broke titlebar structure

``` _title-bar.scss
.menu-icon {
    margin-#{$global-left}: $titlebar-icon-spacing;
    margin-#{$global-right}: $titlebar-padding;
}
```

**Test case:**
Put a menu-icon inside a button

``` example
<div class="title-bar" data-responsive-toggle="main-menu" data-hide-for="medium">
    <button class="secondary button" type="button" data-toggle>
        <i class="menu-icon"></i>
    </button>
</div>
```

Give us a link to a CodePen or JSFiddle that recreates the issue.

http://codepen.io/EduardoAC/pen/BKPEdK

**Comment by colin-marshall** [comment]
Thanks for the report! Fixed in https://github.com/zurb/foundation-sites/commit/ee8cda3dda3967c3d9e773c6cede684dc5d0f455.

**Comment by colin-marshall** [comment]
Reopening this to gather feedback. The padding is even now, but if you have a `.title-bar-title` next to the `.title-bar .menu-icon`, the title is now `.25rem` to the left (closer to the icon).

Should we add `.25rem` to the left margin of `.title-bar-title` to make up for this? I'm not sure if having the title closer to the icon would make the user more likely to touch the title on accident, when they mean to hit the menu icon.

@zurb/yetinauts what do you think?

**Comment by EduardoAC** [comment]
@colin-marshall from my point of view you can go for either of the two options allow customize or the fix, you did right now as far is consistent with the rest of the code. I needed it clean up the styles on the icon without right the rest of the layout. 

if you think spacing left and right is good it may be worth to put a mixing to define the margin to apply in general way. What do you think?

**Comment by kball** [comment]
@colin-marshall @EduardoAC what is the state of this? Did we come to a conclusion?

**Comment by JeremyEnglert** [comment]
@colin-marshall - should this be closed, or is this important enough to address in V6?

**Comment by EduardoAC** [comment]
@kball @JeremyEnglert I am good to close it because this solution gave me at least consistent spacing.

However, I don't if the icons customization is relevant in the new version.
