### ISSUE TITLE
[Slider] Slider bug for mobile devices

### ISSUE THREAD

**Issue by MaximeLassalleHub** [zurb/foundation-sites#8666]
This is the error generated when moving the slider with a mobile device/emulator on the official page
http://foundation.zurb.com/sites/docs/slider.html.

Uncaught TypeError: Failed to construct 'MouseEvent': Please use the 'new' operator, this DOM object constructor cannot be called as a function. foundation.js?hash=713d87598a296bc947803d4689f71045:127

**Comment by Owlbertz** [comment]
There is an open PR #8449. Maybe you can pull that down and give some feedback so this will finally been merged.

**Comment by kball** [comment]
Should be fixed as #8449 is merged.
