### ISSUE TITLE
Jquery-cookie block the installation of Foundation v5

### ISSUE THREAD

**Issue by anaelChardan** [zurb/foundation-sites#8667]
**How can we reproduce this bug?**

1. Bower install
2. See that the dependency : "jquery-cookie" https://github.com/carhartl/jquery-cookie.git does not respond

**What did you expect to happen?**

Installation works great

**What happened instead?**

It's blocked by the Jquery-Cookie dependency

**Comment by moettinger** [comment]
Same here.

**Comment by mjacksonw** [comment]
Same here

**Comment by designerno1** [comment]
why not use https://github.com/js-cookie/js-cookie ?

**Comment by moettinger** [comment]
No longer having the issue on my end. Just started working again, randomly.

**Comment by anaelChardan** [comment]
Yeah it works for me again too, it seems that it was a github problem :)

**Comment by FagnerMartinsBrack** [comment]
This was probably related to https://github.com/js-cookie/js-cookie/issues/186
