### ISSUE TITLE
Expanded Button Group margin missing - foundation-rails (6.2.1.0) gem

### ISSUE THREAD

**Issue by KiraBialczynska** [zurb/foundation-sites#8669]
I'm using Foundation for Sites via ruby gem (foundation-rails (6.2.1.0))
After latest ugrade to 6.2.1 I noticed that Buttons Group margin calculation doesn't include -1px margin part.
Attached is a screenshot comparing my local file downloaded via gem and the one from Foundation sites website. 
Any ideas how to solve that? I tried reinstalling gem, doesn't help. 
![btn-group-margin](https://cloud.githubusercontent.com/assets/12091954/14801227/dd48332c-0b9b-11e6-981d-3b753db43cd5.jpg)

**Comment by andycochran** [comment]
This was fixed in https://github.com/zurb/foundation-sites/commit/0a4f4ca7514ec8abfae07838ecab9b0a9d0c1a71. Should be included in the next patch.

**Comment by andycochran** [comment]
Actually, I'm reopening this 'cause this wasn't a specific bug that was fixed. However, I cannot replicate it locally. @KiraBialczynska, are you maybe using `$global-flexbox: true;` locally?

**Comment by KiraBialczynska** [comment]
Hi Andy,
No I'm not. Actually I cannot find this setting in my _settings.scss. The case might be that although ruby gem updates the version of Foundation the locally linked files like _settings.scss and foundation_and_overrides.scss stay unchanged. After last update I added $foundation-palette manually. How should I approach this? Should I always get the latest _settings when updating Foundation? How to keep track of local changes and make sure I have all the latest settings?

**Comment by KiraBialczynska** [comment]
@andycochran adding $global-flexbox: true; fixed the problem. Please let me know how to approach changing settings and updating it to latest version? What would the best practice be?
Thanks!

**Comment by andycochran** [comment]
When you upgrade, there are sometimes crucial variables in the settings file. Not including those won't always break everything, but you can get undesired results. Part of upgrading Foundation is combing through your settings file. But you should note that setting flexbox to true drops support of certain browsers. Check the docs for more on that.
