### ISSUE TITLE
positionClass option is ignored by Tooltip

### ISSUE THREAD

**Issue by edtownend** [zurb/foundation-sites#8670]
this.options.positionClass is set to the value of _getPositionClass without checking for the prior existance of the option during init of Tooltip.

**How can we reproduce this bug?**

1. Set the positionClass option
2. It has no effect

**What did you expect to happen?**
The position should respect the positionClass option

**What happened instead?**
The position is regexed from the classname instead

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

http://codepen.io/anon/pen/BKOJWN

**Comment by brettsmason** [comment]
I'm hoping someone with more JS knowledge than me can help on this one, but thanks for the detailed report.

**Comment by designerno1** [comment]
this works fine for me in the latest develop branch

**Comment by edtownend** [comment]
Yep, fixed.
