### ISSUE TITLE
Submenu not working properly on small screen in foundation 6 wordpress theme

### ISSUE THREAD

**Issue by onedevteam** [zurb/foundation-sites#8672]
I have this html created by wordpress:

 

```
<li id="menu-item-843" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-843 is-dropdown-submenu-parent opens-left" role="menuitem" aria-haspopup="true" aria-expanded="false" aria-label="Predjela i grickalice" data-is-click="false"><a href="http://localhost:8081/skuvajme/category/predjela-i-grickalice/">Predjela i grickalice</a>
<ul class="vertical menu float-left submenu is-dropdown-submenu first-sub" data-submenu="" aria-hidden="true" role="menu">
	<li id="menu-item-892" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-892 is-submenu-item is-dropdown-submenu-item" role="menuitem"><a href="http://localhost:8081/skuvajme/category/umaci-sosovi-dipovi-i-prelivi/">Umaci sosovi dipovi i prelivi</a></li>
</ul>
</li>
```
 

On large screens, menu shows as it should be, but on smaller, when it folds, instead of showing under parrent menu item, submenu shows on the right side and goes out of screen.

 

Here is uploaded theme i'm working on: http://onedevteam.com/wptest/

How can i fix this?

**Comment by denisahac** [comment]
Please refer to the ZF official documentation for [Responsive Navigation](http://foundation.zurb.com/sites/docs/responsive-navigation.html)

**Comment by brettsmason** [comment]
Just to elaborate, on your menu that is within `top-bar-right` in your code you need to change `data-dropdown-menu` that you have currently to `data-responsive-menu="drilldown medium-dropdown"` but  change according to how you want it to work.

Also try looking at other Foundation themes - [Joints](https://github.com/JeremyEnglert/JointsWP) or [Croft](https://github.com/brettsmason/croft) to see how its done there.

**Comment by andycochran** [comment]
The [Foundation Forum](http://foundation.zurb.com/forum) might also be a good place to seek this kind of help.
