### ISSUE TITLE
[DropDownMenu] _this.hide is not a function

### ISSUE THREAD

**Issue by SierraGolf** [zurb/foundation-sites#8677]
**How can we reproduce this bug?**

1. use version 6.1.2
2. open the drop down menu by hovering
3. force the menu to destroy and re-create e.g. by quickly opening a link on the top navigation outside of the drop down
4. the timeout function defined here: https://github.com/zurb/foundation-sites/blob/v6.1.2/js/foundation.dropdownMenu.js#L185 is called but the hide method does not exist on the object anymore

**What did you expect to happen?**
the menu should gracefully handle a destroy and potential recreate of the plugin in its delayed (setTimeout) methods.

**What happened instead?**
the hide method failed because the plugin is already in the destroyed state and does not have the desired method anymore.

**Comment by Owlbertz** [comment]
Version 6.1.2 is outdated, please try updating to the latest 6.2.1.

**Comment by SierraGolf** [comment]
sadly I cannot try because of #8721

**Comment by SierraGolf** [comment]
I just went through the meteor upgrade (1.3.x) and I can confirm that the bug is fixed with 6.2.1.

**Comment by kevster** [comment]
I just upgraded to Meteor 1.3.3 with Foundation Sites 6.2.3 (latest releases at time of writing) and I'm getting the same error as described by @SierraGolf, also using same reproduction method.
