### ISSUE TITLE
gulp hangs indefinitely after 'default'

### ISSUE THREAD

**Issue by russelpryor** [zurb/foundation-sites#8681]
gulp hangs after 'default' indefinitely. Anyone else having this issue?

```
[19:28:20] Using gulpfile ~/sitetest/gulpfile.js
[19:28:20] Starting 'sass'...
[19:28:21] Finished 'sass' after 991 ms
[19:28:21] Starting 'default'...
[19:28:21] Finished 'default' after 11 ms
```

Reproduced:
1. Running foundation new
2. Starting new foundation site
3. Running foundation watch in the new site directory

**Comment by brettsmason** [comment]
@russelpryor Can you provide some more details.
What operating system are you running?
What version of Gulp are you using - `gulp -v` from the command line.

**Comment by russelpryor** [comment]
@brettsmason here are a few more specifics...

OS: OS X v10.11.4

```
$ gulp -v
[07:56:15] CLI version 0.4.0
[07:56:15] Local version 3.9.1
```

Basic Template is hanging up but not Zurb Templates.

**Comment by brettsmason** [comment]
@russelpryor Could you try updating your Global gulp version? On my system both versions are 3.9.1 so I wonder if that might be causing an issue? Also try clearing out your `node_modules` and running `npm install` again.

Let me know how that goes.

**Comment by russelpryor** [comment]
@brettsmason Thanks for your quick replies on this. My progress below.

Attempt to update CLI gulp
```
$ npm update gulp -g 
$ npm update gulp@3.9.1 -g
```
... to attempt matching the local v `3.9.1`. Did not work. So I reinstalled...
`$ npm install gulp@3.9.1 -g --save`

And now have a good match
```
$ gulp -v
CLI version 3.9.1
Local version 3.9.1
```

What is the best way to clear the node_modules? I've already tried a harsh method which seemed to work getting everything cleared... but did not fix my issue of the hangup:
```
$ rm -rf node_modules/
$ sudo npm install
```

**Comment by brettsmason** [comment]
@russelpryor Hmm have you tried creating a new project just out of interest? It could be one of those weird ones where starting again with a new project might help. If you could confirm if you have tried a new project that would be useful.

**Comment by russelpryor** [comment]
@brettsmason Yes indeed. My first post mentions the flow. It's **only** occurring on new projects at this point. Then again, most of my other projects have been using the Zurb Templates and not the vanilla Sites setup.

**Comment by inou** [comment]
Exactly the same problem here - totally fresh node, npm, gulp, foundation installation. OSX 10.11.4

**Comment by baglio** [comment]
Same problem here. Brand new Foundation-For-Sites project, and gulp task stops at default after compiling "sass". Foundation-Zurb-Template works fine though.

**Comment by daneclarkcollins** [comment]
I'm having this exact problem, suddenly.

**Comment by kball** [comment]
What version of node are ya'all using?  We've seen issues with the 7.x series in a ton of different dependencies

**Comment by baglio** [comment]
I've recently updated to node version v6.9.1. Unfortunately I ran in the same issue.

**Comment by bigheed-21** [comment]
I'm also having the same problem. Was there a solution?

Same as @baglio upgraded Node and stalling on 'default' task

**Comment by bowmanhost** [comment]
I'm also having the same problem.  Same results as @baglio and @daneclarkcollins .

Foundation-Zurb-Template works fine. Foundation-For-Sites projects hang. 

I originally was running node v7.3.0. 
After reading the comments from @kball I downgraded to node v6.9.2 LTS.
I still have the same problem: Foundation-Zurb-Template works fine. Foundation-For-Sites projects hang. 

I am running Manjaro Linux.

**Comment by kball** [comment]
So... I just dug into this some more, and it looks like the sites template is currently doing this _deliberately_.  It includes a watch on the sass files to do a recompile, despite not including a server.  I guess it expects you to be serving the content in some other way, but still wants the default to be watching.

This strikes me as very unintuitive behavior... I see 2 potential fixes.

1.  Change the default task to just compile, add a `watch` task for folks who want the current behavior.
2.  Add a server or browsersync to this template.

I don't personally ever use this template, so I'm not sure what would best match expectations here... any of the folks on this thread have a thought?

**Comment by siddhant92** [comment]
@kball I am having the exact same issues with trying to do an _npm start_
What template/method do you suggest for using the Sass with Foundation?

**Comment by kball** [comment]
@siddhant92 if you want a more full stack that includes it's own dev server, I'd recommend the ZURB stack rather than the basic stack.

That said, I'm leaning towards adding browsersync to the basic template, as folks seem to expect having a dev server built in.  @rafibomb @zurb/yetinauts what do you think?

**Comment by colin-marshall** [comment]
@kball I also don't use this template so it's difficult to say which is better. If people that use it are just clicking refresh manually then I don't think it would be a bad idea if we forced browsersync on them. It's really easy for them to setup, so I don't see why not. That being said, I'm not sure if the manual refresh is the only use case out there.

**Comment by DanielRuf** [comment]
At least we already have it here https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js#L146

gulp itself has some issues with cache warmup or building projects after a cold boot (which looks like it hangs but it does not).

**Comment by DanielRuf** [comment]
I still think this is a Gulp only issue with Vinyl and not directly related to Foundation Sites or its config.

What should we do?

**Comment by DanielRuf** [comment]
> @DanielRuf the issue is described here:
> #8681 (comment)
> 
> It's not "hanging" per se, it's just watching for changes. It's a poor setup of the gulp tasks. I say we just add browsersync and call it a day.

Well, in fact I had very long bootup times after cold boots using Gulp.

https://github.com/zurb/foundation-zurb-template/blob/1952ee3b7fade492f9d99e5d1e019662f5b230c2/gulpfile.babel.js#L36

https://github.com/zurb/foundation-sites-template/blob/3855d1be483ce62cc11b1831a9e2695bb4555efa/gulpfile.js#L23

https://github.com/zurb/foundation-sites/blob/v6.4.3/gulpfile.js#L27

All three are watching for changes.

**Comment by colin-marshall** [comment]
Not sure if what you saw is the same issue. Yes all 3 are watching for changes but the `foundation-sites-template` has no server or browsersync plugin so it's not obvious that it's complete.

```
[19:28:20] Using gulpfile ~/sitetest/gulpfile.js
[19:28:20] Starting 'sass'...
[19:28:21] Finished 'sass' after 991 ms
[19:28:21] Starting 'default'...
[19:28:21] Finished 'default' after 11 ms
```
^^^ It's actually done after this happens, and people are confused because they are expecting something else to happen.

**Comment by DanielRuf** [comment]
There is a big difference between both in general.

https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js
https://github.com/zurb/foundation-sites-template/blob/master/gulpfile.js

See https://foundation.zurb.com/sites/docs/starter-projects.html#basic-template

> Our basic project template is a lot like the Sass template from Foundation 5. The project has a flat directory structure and only compiles Sass. It's great if you want to quickly put together a simple project and only need to use Sass.

See https://foundation.zurb.com/sites/docs/starter-projects.html#zurb-template

> The official ZURB Template includes not only Sass processing, but also JavaScript processing, Handlebars templating, and image compression. We use this exact template at ZURB for our client work!

We also only use the second at work. The first one is just for compiling the Sass so I guess it makes not much sense to add browsersync to this bare template as it is up to the developers and users how they use it and what they do with it.

We should label the zurb template for projects in general and general use and the basic template for just a very template to compile the Sass (and nothing more, as it is described in the docs).

**Comment by colin-marshall** [comment]
We're on the same page about all that stuff. I'm just confused about the "hang" issue you were describing as being related to the problem others experienced in this thread. I was explaining that their problem is a misunderstanding because we setup the gulp tasks on the foundation-sites-template poorly. Your cache warmup issue sounds like a completely different problem.

> The first one is just for compiling the Sass so I guess it makes not much sense to add browsersync to this bare template as it is up to the developers and users how they use it and what they do with it.

Then we should do option 1 in @kball's post:
> Change the default task to just compile, add a watch task for folks who want the current behavior.

**Comment by DanielRuf** [comment]
> Then we should do option 1 in @kball's post:
> 
> > Change the default task to just compile, add a watch task for folks who want the current behavior.

Makes sense to me. What do the others think?

**Comment by DanielRuf** [comment]
> Your cache warmup issue sounds like a completely different problem.

Well, this is Gulp how I know it. It always had its flaws and was slower compared to rollup, parcel and webpack 4 =)

**Comment by DanielRuf** [comment]
I've closed this issue as we did not receive any further feedback. Feel free to reopen if it is still an issue.
