### ISSUE TITLE
[Compatibility] IE11 - Nested Row

### ISSUE THREAD

**Issue by greenlampmarketing** [zurb/foundation-sites#8682]
Layout with nested rows brakes in IE11 (works in other browsers): complied app.css does not have a specified width for .row .row {}.
<div class="row">
<div class="row">
<div class="large-12 small-12 columns">...</div>
</div>
</div>

**How can we reproduce this bug?**

1. Step one
2. Step two
3. Step three

**What did you expect to happen?**

**What happened instead?**

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by phifa** [comment]
nested rows are illegal. please use `row > columns > row > columns`

**Comment by greenlampmarketing** [comment]
​Wow! Every day I learn something new! Thanks for your help!​


<http://www.greenlamp.com.au>

* Alexei Domorev*

* m:* +61 430 128 433

* p:* +61 7 5641 1135

* e: **alexei.domorev@greenlamp.com.au <alexei.domorev@greenlamp.com.au>*

  *w*: *greenlamp.com.au* <http://greenlamp.com.au/>

**Comment by andycochran** [comment]
What @phifa said. Closing this. 😉
