### ISSUE TITLE
[Drilldown Responsive Menu] destroy problem

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8689]
one('transitionend') gets fired after destroy and reinit

https://codepen.io/designerno1/full/VaEeYB/
open the first drilldown menu on small screen, then resize window to medium that dropdown menu gets applied (here the destroy calls _hideAll() this sets a one('transitionend')), but gets not fired.
now resize the window to small and click again the first drilldown menu. now the menu moves but the is-active class from the first menu gets removed by the one('transitionend') handler that executes now.

maybe off the one handler on destroy? can we .zf.drilldown the transitionend handler so we can easy kill them?

**Comment by designerno1** [comment]
i allmost think the
`this._hideAll()` can be removed from destroy because all `is-active` class gets removed through destroy function, maybe replace it with `this.$element.trigger('closed.zf.drilldown');` to trigger that the menu gets closed as in the `this._hideAll()`

**Comment by kball** [comment]
This should get addressed as a part of https://github.com/zurb/foundation-sites/issues/9421

**Comment by JeremyEnglert** [comment]
Closing this in favor of #9421.
