### ISSUE TITLE
Equalizer removes event listeners from element

### ISSUE THREAD

**Issue by flyingL123** [zurb/foundation-sites#8690]
I'm not sure what I'm missing here, but how am I supposed to successfully bind to the `postequalized.zf.equalizer` equalizer event? The equalizer source code contains a `_pauseEvents()` method that contains the line:

    this.$element.off('.zf.equalizer resizeme.zf.trigger');

This removes any previously bound events. In other words, if I bind to the event, then initialize foundation, the event gets removed:

```
$('.productHeader').on('postequalized.zf.equalizer', function() {
  console.log('heights updated');
});

$(document).foundation();
```

In this case, the even never fires since it gets removed when equalizer is initialized. It will also be removed if the screen size changes to below the `equalize-on` value.

Shouldn't there be some sort of logic where the pausing and enabling events methods account for any other listeners that have been bound to the element by the user?

**Comment by designerno1** [comment]
Same issue
http://codepen.io/marvinhuebner/pen/mPzrjN?editors=1111

**Comment by kball** [comment]
I believe this is fixed in #8690 which was merged, and will be in 6.2.2.  We'll be putting out a 6.2.2 release candidate later today so if you want to test with that and verify, that would be great.

**Comment by dioogbento** [comment]
Sorry to post on a closed topic. I've had a similar issue and arrived here while searching for a possible solution. I'm no expert in javascript and would like to understand why the equalizer event has to go before the foundation initialization. Thanks!

**Comment by donaldG** [comment]
With @dgobnto here. I'm having no luck binding to this event or more likely I'm not understanding how to do it correctly. Following the example in the first comment but I get nothing in my console regardless of what element (document, window, div) I use & whether I do it before or after Foundation initialization.
