### ISSUE TITLE
Orbit example in Docs requires Motion UI which is not included in Foundation CSS CDN (Leads to confusion)

### ISSUE THREAD

**Issue by robertwalsh0** [zurb/foundation-sites#8702]
Was helping a newbie learn to make websites and she had trouble getting Orbit to work because of unclear documentation.

She did the initial setup from the docs but the Orbit carousel wasn't working because it required the Motion UI CSS package (which as far as I could tell was not explicitly mentioned in the instructions on the [Foundation Installation Docs](http://foundation.zurb.com/sites/docs/installation.html) page - there were just links to the CDN for `foundation.min.js` and `foundation.css`.

_I'm recommending that Motion UI CSS gets added to the instructions on how to setup Foundation._

---

**How can we reproduce this bug?**

1.Follow the instructions on the [Foundation Installation Docs](http://foundation.zurb.com/sites/docs/installation.html)
2. Copy and paste the [Orbit Example Code](http://foundation.zurb.com/sites/docs/orbit.html)
3. Load the page

**What did you expect to happen?**

You will expect to have a working carousel as in the docs

**What happened instead?**

Instead you will find that the carousel doesn't work. It doesn't go past second slide.

**Test case:**

http://codepen.io/anon/pen/reqqVv

**Comment by seanmavley** [comment]
Added a PR: https://github.com/zurb/foundation-sites/pull/8710

**Comment by brettsmason** [comment]
Thanks to @seanmavley this docs fix has now been merged.
