### ISSUE TITLE
if BrowserSync stops reloading - update your gulp.watch

### ISSUE THREAD

**Issue by fndaily** [zurb/foundation-sites#8703]
browser sync stops reloading today after the initial 1 or 2 reloads - for us this is happening on all projects and looks to be gulp-cli@0.4.0 
 
for anyone else that runs runs into this - modify your watch task as follows:

old: ```gulp.watch('some/files/to/**/*.watch', gulp.series(sass, browser.reload));```

fix: ```gulp.watch('some/files/to/**/*.watch').on('change',gulp.series(sass, browser.reload));```

**Comment by kball** [comment]
@fndaily would you like to submit a PR to the templates for this?

**Comment by fndaily** [comment]
@kball I think I did that correctly? 

https://github.com/zurb/foundation-zurb-template/pull/36/commits/1deac3aa0e99661f73a5e250bda441811a5af0c4

**Comment by kball** [comment]
awesome, thank you.  I'm busy today so wont' be able to jump in and test until later, but we should be able to get that rolled out pretty shortly

**Comment by brightonmike** [comment]
This was the same issue I raised in a previous ticket. Thanks so much, your fix works for me too.

**Comment by fndaily** [comment]
@kball - zurb/foundation-zurb-template@1deac3a

Should that PR have gone to a different branch? I didn't see a dev branch - only: 

- Gulp4
- Master
- Patch-1
- Revert-34-v6.2.1
- v6.2.1

**Comment by fndaily** [comment]
This has been merged into the ```master```
