### ISSUE TITLE
[Tooltip] Can't reopen clickable tooltip until focus is lost

### ISSUE THREAD

**Issue by colin-marshall** [zurb/foundation-sites#8705]
**Note:** You'll currently only see this in the develop branch.

**To reproduce:**
1. Go to Tooltip docs
2. Scroll to Tooltip Clicking secton
3. Click **tooltip will stay open** to open tooltip
4. Click **tooltip will stay open** again to close
5. Click **tooltip will stay open** a third time to try to reopen tooltip

**What did you expect to happen?**
Tooltip would reopen

**What happened instead?**
Tooltip remains closed

**Test case:**
See Tooltip docs on develop branch.

**Comment by nachtwandler** [comment]
Hi, isn't this the same problem as in #8697 ?

**Comment by colin-marshall** [comment]
@nachtwandler it sure is. I was going over a related PR where we mentioned opening a new issue for this but they didn't say it was already done. Thanks for pointing this out! Closing.
