### ISSUE TITLE
[Accordion Menu] down and up fz.accordionmenu fire multiple times

### ISSUE THREAD

**Issue by alanontheweb** [zurb/foundation-sites#8724]
I provided this codepen with the latest foundation css and js included.

http://codepen.io/anon/pen/RaqyVY

Console.log outputs the message 16 times. It changes when I add data-slide-speed = "0" to 2 times. I'm expecting it to run once either way. Is this the intended behavior or is it a bug?

**Comment by kovloq** [comment]
Hi @alanontheweb yes, 

I think it's a bug. I tried to solve the problem but still couldn't figure it out. The callback  function works in accordion. However it doesn't work in accordion menu.

Someone said [http://foundation.zurb.com/forum/posts/36958#comment_27867](http://foundation.zurb.com/forum/posts/36958#comment_27867) it worked, but don't how he did it.
