### ISSUE TITLE
[Offcanvas] closed.zf.offcanvas should fire when animated

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8727]
closed.zf.offcanvas should fired wehen animation is finished
right now closed.zf.offcanvas fires immediately whenn closing starts

**Comment by Owlbertz** [comment]
I agree, according to [the standards](https://github.com/zurb/foundation-standards/blob/master/javascript.md#event-naming) it should be either `close.zf.offcanvas` when the animation starts and `closed.zf.offcanvas` or just the latter one, since this animation is not that complex.

**Comment by DanielRuf** [comment]
Closing as fixed.
