### ISSUE TITLE
[off-canvas sticky] open off-canvas cause wrong sticky position

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8729]
https://codepen.io/designerno1/full/bpQZgL/

open off-canvas menu and scroll down sticky gets wrong position

i expect the sticky has right position

is there a way to prevent this, or reset sticky if off canvas opens?

**Comment by brettsmason** [comment]
Sticky should now play nicely with off canvas with 6.3.
Release candidate is out today, with the full release scheduled for the 15th December.

Closing this, but if you still have issues with 6.3 please re-open.
