### ISSUE TITLE
[Dropdown] dropdown width as data-attribute

### ISSUE THREAD

**Issue by alanontheweb** [zurb/foundation-sites#8734]
Many times I want the width of the dropdown to match the parent anchor, and other times I want it to wildly differ depending on the content inside. Can you add a feature to customize the dropdown's width through a data-attribute, that defaults to the sass width when unconfigured?

**Comment by Owlbertz** [comment]
Sounds like a nice idea for v6.3.

**Comment by JeremyEnglert** [comment]
This will be considered for V7.
