### ISSUE TITLE
TypeError: Foundation.Keyboard is undefined?

### ISSUE THREAD

**Issue by Lynda333** [zurb/foundation-sites#8737]
I'm using Reveal on a page and when it opens I see the following message:

    TypeError: Foundation.Keyboard is undefined
      Stack trace:
      i@http://www.example.com/js/ueber-mich/foundation.min.js:1:13145
      a.reflow/</<@http://www.example.com/js/ueber-mich/foundation.min.js:1:2397
      .each@http://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js:2:2859
      n.prototype.each@http://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js:2:843
      a.reflow/<@http://www.example.com/js/ueber-mich/foundation.min.js:1:2048
      .each@http://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js:2:2859
      a.reflow@http://www.example.com/js/ueber-mich/foundation.min.js:1:1953
      s@http://www.example.com/js/ueber-mich/foundation.min.js:1:3180
      @http://www.example.com/dev/ueber-mich.html:109:5
      n.Callbacks/i@http://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js:2:27146
      n.Callbacks/j.fireWith@http://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js:2:27914
      .ready@http://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js:2:29705
      J@http://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js:2:29890

This is for a one-page site so the Foundation Download is very limited and I assume it's missing something. Here is my selection for the customizer: 

![customizer](https://cloud.githubusercontent.com/assets/1938824/15034307/6ee9429e-1231-11e6-9ef8-8a563aacc34f.jpg)

I assume these options being selected should download everything, correct?

If it's not the download, what is the problem? I should note that I'm using the full download of Foundation on another site without any errors so that is why I believe it's related to the download. 

I'm using v6.2.1.

**Comment by Owlbertz** [comment]
Obviously the keyboard util is not part of the custom download. The configuration for the customizer is wrong as it misses the dependency for Reveal (see https://github.com/zurb/foundation-sites/blob/develop/customizer/config.yml#L170). I'll add that.

**Comment by Owlbertz** [comment]
@Lynda333 So as you can see I added a PR that will cause the Customizer to correctly add the util to the download when Reveal or Slider are selected. If you need some quick solution you could add another plugin that includes this util (e.g. Slider). This will bloat up your code a bit, but allows you to move on with development.

**Comment by kball** [comment]
#8748 has been merged and deployed.  This should be resolved for new downloads.
