### ISSUE TITLE
Media object causes long horizontal scroll bar with `$global-flexbox: true;`

### ISSUE THREAD

**Issue by tbredin** [zurb/foundation-sites#8738]
Just adding a media object with `$global-flexbox: true;` causes a long horizontal scroll.

Seems like an easy fix, just needs 

```
.media-object-section {
    -webkit-flex: 0 0 auto;  
    -ms-flex: 0 0 auto;  
    flex: 0 0 auto;  
}
```

to change to 

```
.media-object-section {  
    -webkit-flex: 0 1 auto;  
    -ms-flex: 0 1 auto;  
    flex: 0 1 auto;   
}
``` 

Here's a codepen that demonstrates the bug, with the suggested fix that I'm using at the moment.

http://codepen.io/tbredin/pen/VaqrZY

**Comment by brettsmason** [comment]
@tbredin Thanks for the bug report.
The fix looks good to me, are you able to submit a PR to fix this?

**Comment by brettsmason** [comment]
Actually I just created a PR to fix this, but thanks for pointing out the issue :+1:
