### ISSUE TITLE
[Media Object] stack-for-small doesn't work with flex grid

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites#8739]
When checking on issue [#8738](https://github.com/zurb/foundation-sites/issues/8738) I noticed the `stack-for-small` class is not working. This is because `flex-wrap: wrap;` is being applied to all breakpoints, not just small. 

See [this codepen](https://github.com/zurb/foundation-sites/issues/8738) and add the `stack-for-small` class.

I'll sort out a PR to fix both these issues now.

**Comment by kball** [comment]
Fixed by #8740
