### ISSUE TITLE
Running the tests under Windows works but only after physically copying the `assets` directory

### ISSUE THREAD

**Issue by karland** [zurb/foundation-sites#8749]
**How can we reproduce this bug?**

Just run `npm run test:visual` under Windows. in case you have this possibility.

**What did you expect to happen?**

I expected `.html`-files to have the correct asset paths

**What happened instead?**

The assets were not loaded, because the asset paths were either wrong or the assets were missing in the paths. 

The asset path seems to be symlinked, which is not working under Windows. 

**The fix for Windows is rather simple:**

For `npm run test:visual` the directory `_build\assets`has to be copied into `test\visual` and for 
`npm run test:javascript` the directory `_build\assets`has to be copied into `test`.

A final remark for the [README.md](https://github.com/zurb/foundation-sites/blob/develop/README.md). Running the Foundation tests requires the documentation to be generated first with `npm start`, which is not explicitely stated. Generating the documentation also requires `npm install bower -g` to be installed (which is probably already installed on most systems, but I mention it anyway).

**Comment by brettsmason** [comment]
Unfortunately you can't (as far as I'm aware) distribute a symbolic link on Windows, hence it doesn't work - see [this file](https://github.com/zurb/foundation-sites/blob/develop/test/visual/assets) (I'm a Windows user myself). However I just create a symbolic link myself. An easy way to do this on Windows is with [Link Shell Extension](http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html).

Alternatively there's a nice guide on symlinks [here](http://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/).

Unfortunately us Windows users get a raw deal sometimes. If you can think of a cross platform way around this do let us know.

**Comment by brettsmason** [comment]
Actually following this up looking at the BrowserSync docs I think it might be possible to set this up in the Gulp `test.js` file so paths work, though I'm not sure. I'll try and have a look.

**Comment by colin-marshall** [comment]
@karland #8752 should fix this. I just removed the symlink and setup a route for the BrowserSync visual test server to point `/assets` on the server to the `_build/assets` directory. Please give it a whirl.

**Comment by karland** [comment]
Well, thanks. I can confirm that this fixes it on my system too.
