### ISSUE TITLE
JS not compiling correctly

### ISSUE THREAD

**Issue by bc-ian** [zurb/foundation-sites#8750]
**How can we reproduce this bug?**
I am doing some more testing on this today as I work but right now its like this:
Using the zurb template for foundation when running foundation watch for the first time, everything works correctly. If I run the build everything works ok. But if I try to run foundation watch again it does not correctly compile the JS and I get this error in my app.js: `Uncaught ReferenceError: $ is not defined`
This also breaks the build process.

When looking my app.js is only one line readying foundation but not including anything else at all.

**What did you expect to happen?**
Expected JS to be compiled Correctly.

I am not the only one with this issue: http://foundation.zurb.com/forum/posts/40938-js-issue

Any help would be much appreciated. I am guessing that this is happening to more than two of us and it's pretty 'game breaking'

Absolutely loving F6 besides the occasional bugs I am running into, but am really excited about the things I will be able to create down the line with the framework!

**Comment by colin-marshall** [comment]
Have you tried deleting your `node_modules` directory, and then run `npm install && bower install`?

**Comment by bc-ian** [comment]
Yesterday i was able to get the first watch to work so I just left it running all day. The first build also worked. But then going foundation run again broke everything.

It looks like there are a few other people also having this problem.

I Have not tried deleting those folders yet but I might give it a go tomorrow if I cant get the first watch to work after deleting my dist again.

Hopefully someone smarter than I can narrow down what is causing this issue as like I said, it may be preventing a good number of people from using the zurb template right now.

**Comment by fndaily** [comment]
Hey guys - there have been quite a few updates to ```babel-plugin-es2015``` modules among others.  
I'm curious if running ```npm update```  fixes your watch tasks?

**Comment by bc-ian** [comment]
running npm update did not fix it unfortunately. @fndaily
@colin-marshall npm -v returns:
[13:06:14] Requiring external module babel-register
[13:06:14] CLI version 1.2.1
[13:06:14] Local version 4.0.0-alpha.2

I have not tried deleting node_modules but I did update it, essentially the same thing right?

I am really confused now because the other day I got it to work upon deleting the dist and running watch, but I cant get that to happen again.

**Comment by fndaily** [comment]
@bc-ian I would definitely try removing the ```node_modules``` & ```bower_components``` dirs, starting over with a fresh install. This is starting to sound like either a (somehow) corrupted node_module or possibly even a permissions problem. 

What's your platform - windows, mac?

Additionally, it won't hurt to add ```"babel-register": "^6.8.0",``` to your devDependencies in your ```package.json``` before you install npm again. I doubt that's whats causing your problem but it may help to narrow things down.

**Comment by huphtur** [comment]
Experiencing the same problem. Did all the ^above updates. Watch still runs fine but a Build ends up with a ton of errors at the top of app.js:

![app js](https://cloud.githubusercontent.com/assets/469438/15266981/27458390-19b5-11e6-8e99-bb2e42e8ea68.png)

```
$ gulp -v
[09:22:09] Requiring external module babel-core/register
[09:22:09] CLI version 3.9.0
[09:22:09] Local version 4.0.0-alpha.2
```

**Comment by kball** [comment]
I believe this has been resolved. Please reopen if you are still seeing this.
