### ISSUE TITLE
[git experts] cannot lock ref

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8753]
Hi i get the error from git when i pull or fetch from origin

```
cannot lock ref 'refs/remotes/origin/V5': ref refs/remotes/origin/V5 is at f8bc2aad4af10c31aa59468fdfab8a88888284b6 but expected 26b31593b4aaa1bbe776e3422b6b8fc9d6ac439d
! 26b3159..66ff76f  V5         -> origin/V5  (unable to update local ref)
```

looks to me as there is a `v5` and a `V5` and that makes problems on my win10 tortoise git machine?

**Comment by colin-marshall** [comment]
Must have happened recently since both branches are pretty much up to date with each other. I know @coreysyms has been doing some work on F5 and could probably shed some light on the situation.

**Comment by coreysyms** [comment]
I've merged 2 PR's over the last week, using the online interface of github so I'm not sure but this google search popped up and seems like a logical explanation.

> Someone has created another branch with the same name, but different case.
> Git for windows isn't case sensitive. So, things just got crazy! Git couldn't distinguish one from another, mistaking the hash of each's head.
> 
> Solution:
> Just cut the evil by it's root. Wrong remote branch was deleted and everything is nice as ever.

**Comment by coreysyms** [comment]
@zurb/yetinauts Can someone with more Github expertise look into this, there are 2 branches (lowercase v5) and (uppercase V5). Not sure if it has always been this way? But someone should make the call to kill one or the other right?

**Comment by colin-marshall** [comment]
Closing out all Foundation 5 issues as it is no longer being developed or supported.
