### ISSUE TITLE
ZURB Template builds broken site

### ISSUE THREAD

**Issue by Larmor27** [zurb/foundation-sites#8754]
**How can we reproduce this bug?**
1. Create a new foundation-site project using the zurb template via `foundation new`
2. Use [this file as layouts/default.html](https://jsfiddle.net/rapvq2rL/) and [this as index.html](https://jsfiddle.net/9q9vzp67/).
3. run `$npm run build` in the project folder

**What did you expect to happen?**
I expected to get a nice compressed build in the dist-folder. 

**What happened instead?**
The build is faulty. The off-page-navigation doesn't work, it only opens and doesn't close once it's opened. All javascript related to foundation seem faulty. Check it out in this [faulty build (dropbox)](https://www.dropbox.com/s/5d370kv18bhdaj5/dist.zip?dl=0)

**System setup**
I have a windows environment.`$ foundation watch` works fine, the uncompressed files are not corrupted. The error is though directly related to `$ npm run build`.

**Background info**
If I run `$ foundation watch` with a fresh installation, I receive a "Failed to load external module babel-register" - error. If I run `$ npm install babel-register babel-preset-es2015` the error disappears, however the builds remain faulty.

I have no idea what is causing this, it seems to be a major bug to me.

**Comment by bc-ian** [comment]
Yeah this is an issue right now. Also trying to get help for the same thing here. https://github.com/zurb/foundation-sites/issues/8750

**Comment by fndaily** [comment]
@Larmor27 - there have been quite a few updates to ```babel-plugin-es2015``` modules among others.  
I'm curious if running ```npm update```  fixes your watch tasks?

**Comment by Larmor27** [comment]
Hey @fndaily thank you for your input. 

I ran `$ npm update` and directly afterwards `$ npm run build`. Unfortunately the built is still faulty, with the same error as described in my first post.

@bc-ian our problems seem related, altough my setup doesn't throw `Uncaught ReferenceError: $ is not defined`, neither do I encounter problems running watches. Curiously enough, my watch works perfectly fine, I even use the watch-output in a productive environment right now as a substitute.

In my case only the compressed builds are causing trouble.

**Comment by brettsmason** [comment]
@Larmor27 So it looks like 2 problems are occuring here. I have installed a fresh copy of the Zurb template and use the code you provided and I have managed to get it working.

The first problem about `Failed to load external module babel-register` seems to be fixed by running `npm install babel-register babel-preset-es2015 --save-dev`. Could you try this and tell me if it fixes that error? If so I think we need to amend the `package.json` file for the template to solve this completely.

The 2nd error is due to UnCSS which is causing a number of problems for users and I think will be removed, at least for now until it can be sorted out fully. To confirm its this causing the issue rather than any Babel specific issue could you try this for me to confirm?

In `config.yml` in the root directory, find `UNCSS_OPTIONS` (line 10 for me).
Under the line `- !!js/regexp ^\.is-.*` can you add `- !!js/regexp js-off-canvas-exit`

From my own testing adding this adds the style for the background overlay (UnCSS is removing it).

**Comment by Larmor27** [comment]
@brettsmason you are definitely on the right track there. First of all `npm install babel-register babel-preset-es2015 --save-dev` solves the error `Failed to load external module babel-register` when running build or watch.

Concerning the other bug, I'm sure now that UNCSS is destroying my builds. It deletes
- sticky-classes like .is-anchored
- reveal-related classes. If I use a reveal on my page UnCSS stripps the classes off of it that take care of positioning
- the styling for the background overlay

... so how do I get rid of UnCSS asap? I'm sporting this ignore-list right now, which is not beautiful but works for my builds. Is there maybe a better expression to just disable UnCSS?
`    - !!js/regexp .*
    - !!js/regexp js-off-canvas-exit
    - !!js/regexp ^.(fade|slide|hinge|reveal|scale|spin|zoom)
    - new RegExp('.foundation-mq'),
    - new RegExp('.is-stuck'), 
    - new RegExp('.is-at-top'), 
    - new RegExp('.sticky'), 
    - new RegExp('.is-anchored'),
    - new RegExp('.svg'),
    - new RegExp('.cssanimations'),
    - new RegExp('.csstransitions'),
    - new RegExp('.multiplebgs'),
`

**Comment by brettsmason** [comment]
@Larmor27 That's good news that we are on the right track.

To remove UnCSS from the production build I think you only need to remove the following:
`.pipe($.if(PRODUCTION, $.uncss(UNCSS_OPTIONS)))` - line 87 in `gulpfile.babel.js`

There are also other traces, like `const { COMPATIBILITY, PORT, UNCSS_OPTIONS, PATHS } = loadConfig();` (remove UNCSS_OPTIONS) and it will be in the `package.json` but that should get it working.

If you can confirm it works that would be great. I can then pass this back to the others so we can look at fixing the issues permanently.

**Comment by Larmor27** [comment]
@brettsmason Okay that did the trick. Here is what I did to get rid of all error-messages and all faulty behavior of foundation:

1. `npm install babel-register babel-preset-es2015 --save-dev` to fix `Failed to load external module babel-register`.

2. Delete `.pipe($.if(PRODUCTION, $.uncss(UNCSS_OPTIONS)))` from the gulpfile to disable UnCSS completely.

Everything else works fine now. Thank you @brettsmason !

**Comment by brettsmason** [comment]
@Larmor27 Brilliant thanks for confirming that this fixed your issues. I'll use this as a reference to hopefully get the templates fixed.

**Comment by kball** [comment]
I believe these have all been fixed in the latest versions of the template.
