### ISSUE TITLE
[Responsive Navigation] Open ResponsiveNavigation JS plugin to extension

### ISSUE THREAD

**Issue by mlang38** [zurb/foundation-sites#8756]
I have my own kind of menu and it would be great if ResponsiveNavigation could handle it too. Would it be possible to extract the [_MenuPlugins_](https://github.com/zurb/foundation-sites/blob/99738a34e5cba799b9c9058ae895c4c9c7dab250/js/foundation.responsiveMenu.js#L130) variable from the factory function to a configuration ? Or have some kind of registration ?

**Comment by kball** [comment]
This would be worth looking at during https://github.com/zurb/foundation-sites/issues/9421

**Comment by colin-marshall** [comment]
Closing in favor of #8784, as it covers the same topic and there seems to be more discussion there.
