### ISSUE TITLE
Settings Overwrite Feature 

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#8761]
For better updating procedure, I would like to have a "settings overwrite solution". I modified my app.scss file like this: 

```
@charset "utf-8";

@import 'settings';

/* Update-Proof Overwriting of Variables */
@import 'settings-overwrite';

@import 'foundation';
@import 'motion-ui';
...
```

In my `_settings-overwrite.scss` I just put the changed variables. 

```

// 1. Global
// ---------
$body-background: $black;
$foundation-palette: (
        primary: #2199e8,
        secondary: #3572C1,
        success: #3adb76,
        warning: #ffae00,
        alert: #ec5840,
);
$global-flexbox: true;
$global-weight-thin: 300;
$global-weight-normal: 300;
$global-weight-bold: 700;

// 2. Breakpoints
// --------------
$breakpoint-classes: (small medium large xlarge xxlarge);

// 4. Base Typography
// ------------------
$header-lineheight: 1.4;
$header-font-weight: $global-weight-thin;
$header-font-family: $body-font-family;

// 31. Table
// ---------
$table-background: transparent;
$table-padding: rem-calc(8 10 10 3);

// Additional
// -----------
$box-shadow: 1px 1px 3px 3px rgba(0, 0, 0, 0.1);

```

This way, updating is super simple. I have a feeling though, that it is not 100% safe, as some variables in the `_settings.scss` file are directly inserted in other variables in the same file? 

Anyways, any smart brains to come up with a good solution?

**Comment by andycochran** [comment]
If you wanna be able to easily update Foundation, it's not a bad idea to leave `_settings.scss` untouched. But if you put your custom variables in another file, including `_settings.scss` is unnecessary. 

Your app doesn't need both `settings` and `settings-overwrite`. Since all variables are declared with `!default` in each component, you don't need to declare a single variable unless you want to override its default. You can have a completely blank settings file, or not include one at all. 

Hope this helps with your workflow.

**Comment by phifa** [comment]
ahhhhhhhhh thanks @andycochran I will give it a try and uncomment the settings.scss in my app.scss.

**Comment by phifa** [comment]
I am running into problems with this config: 

I uncommented my settings.scss and added just the settings_overwrite.scss. Now I get compile errors, since a lot variables are unknown. `$body-background: $black;` for example in my overwrite-file does not work, since the $black is defined in the settings file. 

Interstingly I can get rid of the $black error, by re-declaring the variable in my overwrite file, but primary-color doesn't work, even though the $foundation-palette map is redefined in my overwrite file as you can see in the code above... Any ideas?

**Comment by andycochran** [comment]
Well, of course you can't use any variables that aren't declared. If you want to change a setting that effects other settings, you're gonna need to declare them all. This is why it's easier (best?) to simply use the existing `_settings.scss` file. Sure, you might have to avoid clobbering it when you update Foundation. But part of updating Foundation is combing through your settings to make sure you're still following the current version's methods.

**Comment by phifa** [comment]
Right, and that process takes quite a bit of time. Why does overriding of the sass maps not work?
