### ISSUE TITLE
rem-calc warning

### ISSUE THREAD

**Issue by mmjaeger** [zurb/foundation-sites#8766]
I was wondering why margin: rem-calc(16px auto); issues a warning

**Comment by daveromsey** [comment]
[rem-calc](https://github.com/zurb/foundation-sites/blob/develop/scss/util/_unit.scss#L22) does not accept _auto_ as a parameter.

This will work though:  `margin: rem-calc(16px) auto;`

**Comment by brettsmason** [comment]
Closing this as it has been answered. Any problems though feel free to re-open this issue.
