### ISSUE TITLE
Button transition isn't configurable

### ISSUE THREAD

**Issue by tbredin** [zurb/foundation-sites#8768]
I noticed that there's no way to configure button background and color transitions. I recommend changing the hard-coded line in the `button-base` mixin to reference a variable with a sensible default.  
Current:

``` scss
  // line 67 of components/_button.scss, in mixin button-base
  transition: background-color 0.25s ease-out, color 0.25s ease-out;
```

Suggested change: 

``` scss
  // components/_button.scss
  $button-transition: background-color 0.25s ease-out, color 0.25s ease-out;

  // in button-base mixin
  transition: $button-transition;
```

Furthermore, I'm not convinced on the default; a 0.25s animation on background / color I'd argue isn't entirely expected - this is especially prominent and often not desirable if the button has an inverse color hover or focus state. However I'm weary that this might cause compatibility problems in existing implementations if changed. 
Perhaps better global animation properties could be something to think about as well?

**Comment by OddenCreative** [comment]
Been having this issue myself. Would be nice to have a single button class in the css output and not add in !important, which is lame. The alternative is to have fork the component and alter it.

**Comment by OddenCreative** [comment]
I put this update into the development stream... here's hoping it makes it through... Otherwise, I have have a few sites that will require my fork...

**Comment by tbredin** [comment]
Amazing! Looks great

**Comment by OddenCreative** [comment]
This has been moved into  v.6.3 as new work as requested by @andycochran. New link https://github.com/zurb/foundation-sites/pull/9000

**Comment by OddenCreative** [comment]
This is moving into v6.3 with pull request #9025

**Comment by kball** [comment]
#9025 has been merged, this issue can be closed.
