### ISSUE TITLE
Dropdown parameters allow only vOffset or hOffset, not both.

### ISSUE THREAD

**Issue by stewhouston** [zurb/foundation-sites#8769]
I'm not sure if this is by design, but coming from jQuery UI I find this incredibly restrictive.

Simply moving the menu up 7 pixels (data-v-offset="-7" or margin-top: -7px), seems like a herculean task as the absolute positioning calculated by JavaScript ignores CSS margins, and parameters bound to the element only work on the 'positionClass' axis.

Simple illustration: http://i.imgur.com/nM8uLqM.png

Relevant JavaScript:

```
var elem = new Foundation.Dropdown($('#drawer-games-dropdown'), {
    positionClass: 'right'
    vOffset: -7,
    hOffset: 5,
    closeOnClick: true
});
```

**Comment by DanielRuf** [comment]
This should also work with a `transform: translateXY`.
