### ISSUE TITLE
Mobile menu not working with sticky header on mobile devices

### ISSUE THREAD

**Issue by telliott1** [zurb/foundation-sites#8771]
There seems to be a bug when you use both the mobile menu and sticky header together. The header is only sticky on large screens and above as I'm using the data options attribute. I've tested the mobile menu without using the sticky header and it works fine.

You can reproduce this bug by clicking on the menu icon, scrolling down the page, scrolling back to the top and then by closing the menu. There is now a large white space where the menu was open. If you now scroll again the container jumps back to where it should be.

**Comment by brettsmason** [comment]
@telliott1 Could you [setup a CodePen](http://codepen.io/rafibomb/pen/xVVGOB) to show what the issue is please?

**Comment by telliott1** [comment]
@brettsmason Would it be ok to provide you with the url of the site instead?

**Comment by brettsmason** [comment]
@telliott1 Yes that's fine, just we need more of an idea of what you are trying to do/what's going to help.

**Comment by telliott1** [comment]
@brettsmason http://www.digital-dev.co.uk/on-site-recruitment

**Comment by brettsmason** [comment]
@telliott1 So I can't see an obvious problem whilst looking at the site.
Could you try and explain the problem a bit more. Is the on the large view or small/mobile view? Is this only when using sticky on the menu when setting the data attribute to small?

**Comment by telliott1** [comment]
@brettsmason Were you viewing the site on a mobile?

**Comment by shoaibik** [comment]
I checked it on real phone and also on Chrome device mode, i could not reproduce the issue.

**Comment by telliott1** [comment]
@shoaibik How strange. I've checked it on multiple devices. I've attached some screenshots showing the problem.
![img_0352](https://cloud.githubusercontent.com/assets/12082063/15210738/a12b03a6-182f-11e6-8eb7-e7772a85e5b6.PNG)
![img_0353](https://cloud.githubusercontent.com/assets/12082063/15210739/a12e65c8-182f-11e6-8cb3-c6d0bea0af5d.PNG)
![img_0354](https://cloud.githubusercontent.com/assets/12082063/15210740/a13082f4-182f-11e6-8757-674123d39b33.PNG)

**Comment by brettsmason** [comment]
@telliott1 OK I've managed to replicate the problem on my phone now. Could you confirm if you have tried removing the sticky element completely so we know its definitely this that's the problem?

Also [6.2.2-rc1](https://github.com/zurb/foundation-sites/releases/tag/v6.2.2-rc1) was released yesterday which had a lot of sticky specific bug fixes included. It would be worth you trying it out and seeing if this solves it.

**Comment by shoaibik** [comment]
I think I found the issue, the sticky plugin sets the height of `.sticky-container`, which it might not calculate correctly when menu is closed.

A quick work around is to set its height to auto on small screen.
```
.sticky-container {
    height: auto !important;
} 
```

**Comment by telliott1** [comment]
@brettsmason As per my original post, I've tested the mobile menu without using the sticky header and it works fine. That's useful to know thank you.

@shoaibik That worked. I also had to change the absolute positioning on `.sticky` to static positioning for your code to work.

**Comment by alistairquinn** [comment]
I've got the same issue with Foundation 6.2.4 on WordPress 5.6.1. The sticky container works as it should on desktop but not on mobile. Please see https://www.turnerandlast.com. Any help would be gratefully received.

**Comment by brettsmason** [comment]
@alistairquinn From a quick look it looks like you need to set when the container is sticky.
You need to add `data-sticky-on="small" or `stickyOn: small` to your `data-options`. This defaults to medium: http://foundation.zurb.com/sites/docs/sticky.html#js-options

**Comment by alistairquinn** [comment]
Ah! Thanks. It works perfectly!

**Comment by JeremyEnglert** [comment]
This appears to have been resolved.
