### ISSUE TITLE
[Accordion] $accordion-content-color is not used

### ISSUE THREAD

**Issue by aldees** [zurb/foundation-sites#8772]
The $accordion-content-color SASS variable is supposed to set the default text color of the tab content.   However, it is not actually be used in _accordion.scss

**Comment by brettsmason** [comment]
@aldees This has been fixed in a recent commit - you can see its now set [in the develop branch](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_accordion.scss#L106). This will be included in the point release.
