### ISSUE TITLE
[Tooltip] z-index issue inside a modal

### ISSUE THREAD

**Issue by carlosms** [zurb/foundation-sites#8775]
It looks like issue #5584 is again present in foundation 6.2.1

Tooltips are not visible when placed inside a modal. I updated the jsfiddle in #5584 for the latest version here:

https://jsfiddle.net/carlosms/43eocro9/

**Comment by andycochran** [comment]
Yup. I tried v6.2.3 and Tooltips need `z-index` >= 1005 to work with Reveal. 
https://codepen.io/andycochran/pen/ezZGWm

**Comment by abdullahsalem** [comment]
Thanks @carlosms and @andycochran ,
The issue has been solved here 82ed2d7a67d487b4c516f4c0173c7aca41b11a5f

**Comment by RLaptev** [comment]
@abdullahsalem 
For me only z-index: 1007 worked in version 6.2.4, as .reveal-overlay has a default z-index of 1005 and .reveal class has z-index of 1006.
