### ISSUE TITLE
Stackable buttons (stacked-for-small button-group) are uneven when unstacked

### ISSUE THREAD

**Issue by llamsyneb** [zurb/foundation-sites#8780]
**How can we reproduce this bug?**

1. Create a div with class .button-group
2. Put at least two buttons in it (anchor tags with class .button)

**What did you expect to happen?**

I expected that the bottom of each button would be in line with the others when they are not stacked.
I believe that none of the buttons should have a bottom-border, but I'm not sure that's the right way to go.

**What happened instead?**

Each button _except_ the last button has a 1 px border-bottom, and only the last button has no border-bottom, even when they are not stacked.

**Test case:**

Here's a CodePen: http://codepen.io/anon/pen/wGZaWN
And here's the same behavior in the Foundation docs: http://foundation.zurb.com/sites/docs/button-group.html#stacking

I'm using Google Chrome on Windows 10.

**Comment by DaSchTour** [comment]
I guess this is caused by #8616 
There was a margin-bottom: 0 introduced

**Comment by andycochran** [comment]
Eek! Sorry if my PR introduced this bug. I'll get it fixed…

**Comment by andycochran** [comment]
Actually, this is not an issue in the `develop` branch. So the upcoming 6.2.2 patch should take care of it. Please reopen this issue if you can reproduce this after the next release.
