### ISSUE TITLE
[Documentation suggestion] - Abide patterns

### ISSUE THREAD

**Issue by ghost** [zurb/foundation-sites#8781]
I am missing the "Predefined Patterns" for abide in the docs for Foundation 6. The docs from Foundation 5 has a nice table off all the available patterns, so it would be nice to add this too for the F6 docs.

http://foundation.zurb.com/sites/docs/v/5.5.3/components/abide.html

**Comment by Yanchek99** [comment]
This looks like it has fixed just not deployed? See commit https://github.com/zurb/foundation-sites/commit/195cedd4cd7e09a9547d4475f7671456585425f8

**Comment by rafibomb** [comment]
Thanks @Yanchek99 
Closing!
