### ISSUE TITLE
[Responsive Navigation] responsive menu not possible without plugins

### ISSUE THREAD

**Issue by chrona** [zurb/foundation-sites#8784]
#8462  we have a normal menu without plugins:

```
<ul class="menu">
    <li><a href="#">One</a></li>
    <li><a href="#">Two</a></li>
    <li><a href="#">Three</a></li>
    <li><a href="#">Four</a></li>
</ul>
```

If we wan't to make it responsive we have to give up our "normal" look for medium-up as foundation will always try to check which plugin we are using (even if I don't want one on larger screens).

```
<!-- what foundation expects -->
<ul class="menu" data-responsive-menu="drilldown medium-dropdown">

<!-- solution 1 -->
<ul class="menu" data-responsive-menu="small-only-drilldown">

<!-- solution 2 -->
<ul class="menu" data-responsive-menu="small-drilldown medium-none">

<!-- solution 3 -->
<ul class="menu" data-responsive-menu="small-drilldown medium-custom-plugin-possible?">
```

I know there is a workaround by creating two lists with `show-for-medium`, etc. but i guess extending `data-responsive-menu` would be a better solution.

EDIT: I just saw, that #8756 is referring to the same problem.

**Comment by kball** [comment]
Totally get the custom plugin request (#8756)... trying to understand the non-plugin case... all of the current plugins (dropdown, drilldown, and accordion) are for nested menus... the menu example you show here has no nesting... is that an artifact of the example?  Or are you wanting to somehow make a non-nested menu responsive into a plugin at some sizes?  Can you help me understand what you're trying to accomplish?

Thanks

**Comment by chrona** [comment]
Sorry if my post was a bit confusing, yeah I was talking about a nested menu. This pretty much sums it up:
> Or are you wanting to somehow make a non-nested menu responsive into a plugin at some sizes


As explained [in the docs](http://foundation.zurb.com/sites/docs/responsive-navigation.html#responsive-menu) you can change the behavior of a nested menu, e.g. using drilldown for small screens and a dropdown approach for medium and larger with `data-responsive-menu="small-drilldown medium-dropdown"`.

Using the example above I would like to have the possibility to have a drilldown navigation for small screens only and without any plugin at all (neither dropdown, drilldown or accordion) for medium-up.

It seems to me that currently it is required to always choose one of the three plugins for a certain screensize. 

I hope I could explain it a bit better.

**Comment by IamManchanda** [comment]
Hi @chrona we working on F7 and we will reconsider for v7

For v6, we have decided to stop work on new features but stay there... Your feature will be considered for v7
