### ISSUE TITLE
[Sticky] Sticky causing content below to "jump" on load

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites#8791]
I first reported this on Slack - sorry its taken me so long to write up the issue!
You can see what I mean here: http://recordit.co/4CMl1P4mJB

The markup is:

```
<div data-sticky-container>
<div class="site-header sticky" data-sticky data-options="marginTop: 0; anchor: page;">
</div>
</div>
```

I discussed this with @andycochran on Slack - this is the full conversation:

```
andycochran [3:27 PM] 
@brettsmason: I've noticed that too. Maybe add the .sticky class via js in a .ready()?

brettsmason [3:32 PM] 
@andycochran: thanks for the suggestion. Just tried that and still get the problem though. I think it might be to do with the height being set on `.sticky-container`

[3:35] 
Yep that's whats causing it. I set the height of `sticky-container` in my stylesheet to match what the sticky plugin was setting and the problem goes away. 
I wonder if there's a way to fix this in Sticky? Hopefully a knowledgeable JS Yetinaut may know :smile:

andycochran [4:50 PM] 
@brettsmason: Maybe .sticky shouldn't be `position: absolute;` by default. The plugin could position it.

brettsmason [5:00 PM] 
@andycochran: I like that idea. I'm not very familiar with how Sticky works, but does it even need `position: absolute;` on the base `sticky` class?

andycochran [5:01 PM] 
@brettsmason: Only if we intend to support it being used w/o JS. Which I don't think we do.
```

This issue in summary seems to be coming from the sticky container height/absolute positioning, as setting the `sticky-container` height in my stylesheet sorted out the jump.

**Comment by brettsmason** [comment]
After further testing this seems like its caused by the `position: absolute` set on the `.sticky` class. As Andy said in the chat above, this isn't needed if we only support using `.sticky` through the sticky JS plugin.

@kball @rafibomb What do you guys think? Can we remove the `position: absolute` declaration?

**Comment by kball** [comment]
2 thoughts.

1)  I think it is fine to only support .sticky through the JS plugin.  There's a bunch of behavior in it that requires JS, after all.
2)  I prefer to, as much as possible, have styles applied by classes rather than directly with javascript.  If the active version of sticky needs `position:absolute`, perhaps the plugin should be adding `.is-active` (if it isn't already) and that should apply `position:absolute`

**Comment by brettsmason** [comment]
@kball I agree with you on the class approach.

However from looking at the code isn't this how it already works? When an element becomes stuck it gets the `.is-anchored` [class](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_sticky.scss#L29), which also adds the `position: absolute`. So as far as I can see the styling for the `.sticky` class isn't needed at all - all it does is add the jumping as the element gets taken out of the flow with `position: absolute` until the JS loads.

**Comment by kball** [comment]
Great, so perhaps just removing the position absolute will work.  @colin-marshall put together a set of tests for sticky, so perhaps this is already covered or perhaps not, but lets try and see.

**Comment by brettsmason** [comment]
Yeah Colins opinion would be great as he knows it well. I'm not sure if any of the other styling elements for `.sticky` do anything or not either - I'm thinking they are there purely for non-js use.

I'll try removing all the styles and go through the tests to see if there's any difference.

**Comment by colin-marshall** [comment]
@brettsmason @kball sorry for the late response! All sounds good with this approach. I will test this out this week and report back. Thanks guys!

**Comment by peterbournecommunications** [comment]
I've got a site suffering from this too. Any news on how the tests are going... or how I can implement a temporary fix? Many thanks,

**Comment by ar-rm** [comment]
You guys are 25 days ahead of me.
I just ran into this, tracked it down, and *then* found this issue. Whoops :-)

> @brettsmason:
> So as far as I can see the styling for the .sticky class isn't needed at all - all it does is add the jumping as the element gets taken out of the flow with position: absolute until the JS loads.

I agree completely.
Not sure what the original purpose for `position: absolute` would have been either.

@peterbournecommunications 

The simplest fix is to add an override in your own stylesheet.

```
.sticky {
    position: relative;
}
```

**Comment by kball** [comment]
I believe this was fixed by https://github.com/zurb/foundation-sites/pull/9298
