### ISSUE TITLE
[Compatibility] Webkit prefixes missing

### ISSUE THREAD

**Issue by slavanga** [zurb/foundation-sites#8792]
The [docs](http://foundation.zurb.com/sites/docs/compatibility.html) state that foundation is compatible with Android Browser 2.3+ but prefixes for properties like ```border-box``` are missing.

**Comment by DaSchTour** [comment]
I created a PR #8794
Android was added in a wrong way to the autoprefixer

**Comment by Geczy** [comment]
Autoprefixer?

**Comment by rafibomb** [comment]
autoprefixer is there but it could be solved by @DaSchTour 's PR. Thanks for the PR @DaSchTour !
