### ISSUE TITLE
Sass build differs from dist css file

### ISSUE THREAD

**Issue by christill** [zurb/foundation-sites#8797]
I'm having some difficulty using 'off-canvas' on ios. After a while debugging it appears the css file is the issue.

The sass build I have is:

```
@import "../../components/foundation-sites/scss/foundation";
@include foundation-everything;
```

Using the above creates a different output to:
    https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.1/foundation.css

Whatever is in the difference is causing off canvas to not work on ios.

Thanks

**Comment by kball** [comment]
The issue here is likely to be one of prefixing... make sure your sass build includes autoprefixer.
