### ISSUE TITLE
[Grid] _settings.scss $breakpoint-classes

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#8798]
changing the var

``` scss
$breakpoint-classes: (small medium large xlarge);
```

don't do anything on _build/assets/css/foundation.css
if i change it in _breakpoint.scss direct

``` scss
$breakpoint-classes: (small medium large xlarge) !default;
```

output is generated

**Comment by designerno1** [comment]
@zurb/yetinauts 
can somebody confirm that?

**Comment by kball** [comment]
I believe this is related to https://github.com/zurb/foundation-sites/pull/9396 - the in-framework build process does not actually reference the settings file (which is a generated file updated on deploy).

We have an open issue to look again at how we handle settings (https://github.com/zurb/foundation-sites/issues/9492), I think I will close this in favor of that.
