### ISSUE TITLE
$table-foot-background setting is ignored

### ISSUE THREAD

**Issue by daniel-rikowski** [zurb/foundation-sites#8802]
**How can we reproduce this bug?**

1. In `_settings.scss` assign a color to `$table-head-background`
2. Assign a **different** color to `$table-foot-background`
3. Create a table with a `thead` and a `tfoot` section.

**What did you expect to happen?**

Header and footer should have the two different colors assigned before.

**What happened instead?**

Header and footer have the same color: the header color.

**Test case:**

Cannot create a CodePen because it doesn't allow changing `_settings.scss`

The problem seems to be caused in `_table.scss` around line 80: https://github.com/zurb/foundation-sites/blob/develop/scss/components/_table.scss#L80

**Comment by planetmalone** [comment]
+1

**Comment by brettsmason** [comment]
Closing as #8877 has been merged which fixes this.
