### ISSUE TITLE
Making off-canvas smooth with fixed header

### ISSUE THREAD

**Issue by isomis** [zurb/foundation-sites#8803]
I have a problem with this url: [https://www.dutchbridge.nl/nl](url)

When you are in mobile view and you hit the menu button, the off canvas shows. The problem is that the header is fixed, so the header don't move smoothly to the right. 

You see for example the logo jumping to the correct position. What kind of solution is possible?

**Comment by isomis** [comment]
anybody?

**Comment by nachtwandler** [comment]
Hi,
you could try to use the sticky plugin instead of position: fixed. Haven't tested, but maybe it works nicer with the offcanvas menu.

**Comment by FauzanKhan** [comment]
Hey @isomis 

here's a quick fix that I wrote for smooth transitioning of fixed header with off-canvas 

```
;(function() {
  var mobileNav = $('.header');
  var offCanvasContent = $('.off-canvas-content');
  var mobileNavHeight = mobileNav.outerHeight();
  var canvasCloseTimeout;

  $(document).on('closed.zf.offcanvas', function(){
    clearTimeout(canvasCloseTimeout);
    canvasCloseTimeout = setTimeout(function(){
      mobileNav.css('position', 'fixed');
      offCanvasContent.css('padding-top', mobileNavHeight);
     }, 500);
    });

    $(document).on('opened.zf.offcanvas', function(){
      mobileNav.css('position', 'static');
      offCanvasContent.css('padding-top', 0);
    });
})();
```
I've tried the above code for your website as well and it works like a charm. Hope it helps!

**Comment by brettsmason** [comment]
Off canvas has been completely reworked for 6.3 as well as sticky fixes so this should now be solved from my testing.
Release candidate is out today, with the full release scheduled for the 15th December.

Closing this, but if you still have issues with 6.3 please re-open.
