### ISSUE TITLE
Reveal close when i use .replaceWith or .html (works on 6.1.2)

### ISSUE THREAD

**Issue by qusqui21** [zurb/foundation-sites#8814]
Its strange error couse its only appear in some situation. 
I have reveal, that on first click do  
$(document.body).append(compiledHtml).foundation();
$('#divId').foundation('open');
on second, it do 
$('#divId').replaceWith(compiledHtml).foundation();
and it close modal without any error, but the strange thing is that its only do it on 5/6 appends, with datapicker it reload normal. I can't use version 6.1.2 couse there was error with setting modal on half of  page, but there is no problem with that. I will try to make jsfindle when i will be home. (I think i checked everything, and i am 99% sure that its problem with foundation)

**Comment by JeremyEnglert** [comment]
Can you submit this with a CodePen example?

I'm going to close this. But I'm happy to reopen if you can add an example.
