### ISSUE TITLE
[Responsive Navigation] First example fails on Safari 9.1.1

### ISSUE THREAD

**Issue by cxj** [zurb/foundation-sites#8816]
**How can we reproduce this bug?**
1. Step one - view this page in Safari 9.1.1.
2. Step two - resize browser window smaller than larger.
3. Step three - see the problem.

**What did you expect to happen?**

Expected menu to change to vertical on small (it did) and then back to horizontal on large.

**What happened instead?**

Small window correctly has vertical menu, large window shows item 1 and 2 stacked vertically, while item 3 is to the right of item 2 horizontally, rather than all 3 items being in a horizontal line.

**Test case:**

Test case is this page of documentation:

http://foundation.zurb.com/sites/docs/responsive-navigation.html

**Comment by brettsmason** [comment]
@cxj Thanks for the bug report. Could you confirm which example it is you are seeing this on - is it the very first example below [here](http://foundation.zurb.com/sites/docs/responsive-navigation.html#responsive-menu)? (the one without any dropdowns etc).

**Comment by cxj** [comment]
Yes, that's the one (first example on page you linked).

**Comment by skananitos** [comment]
I have the same issue. Do you have any updates?

**Comment by JeremyEnglert** [comment]
Safari 9 is not supported in V6 anymore. This does not appear to be an issue in Safari 10.
