### ISSUE TITLE
[Switch] size does not match label when using input-group

### ISSUE THREAD

**Issue by jellisii** [zurb/foundation-sites#8818]
**How can we reproduce this bug?**
Use the switch with a input-group.

**What did you expect to happen?**
I expected the switch height to be the same as the label height.

**What happened instead?**
The above was not true.

**Test case:**
http://codepen.io/anon/pen/BKgdvR

**Comment by andycochran** [comment]
I think the default height of a switch should match the default height of a button.

**Comment by andycochran** [comment]
When you put `.input-group-field` on the  `.switch` element, it's set to an explicit height, but the nested `switch-paddle` also has an explicit height which doesn't match. 

You actually don't need `.input-group-field`. You can just use a `.switch` + `margin-bottom:0`. 

http://codepen.io/andycochran/pen/BLXBwQ

@zurb/yetinauts In the spirit of keeping components modular, I'm not sure we should force switch styles to match input group styles. This might be an edge case? Or should we support switches in input groups?

**Comment by jellisii** [comment]
As long as switches doesn't get broken outside of an input group, this would work.

**Comment by JeremyEnglert** [comment]
@andycochran - in the spirit of closing out issues, I think we should revisit this idea for V7. This seems like an edge case.
