### ISSUE TITLE
[Button Group] Stacked - when using stacked-for-small not stacked last button appears larger

### ISSUE THREAD

**Issue by weiserma** [zurb/foundation-sites#8819]
**How can we reproduce this bug?**

1. Goto http://foundation.zurb.com/sites/docs/button-group.html
2. large or medium screen

**What did you expect to happen?**

All buttons should appear the same height

**What happened instead?**

Last button has different color bottom border

**Test case:**

N/A

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by designerno1** [comment]
this should be fixed in #8445 in develop branch and in v6.2.2 coming soon

**Comment by brettsmason** [comment]
As @designerno1 pointed out this has been fixed in the develop branch and will be included in 6.2.2 due for release soon. I'll close this for now, but if you experience the issue after 6.2.2 please re-open this!
