### ISSUE TITLE
Foundation6 reInit with jQuery selector does not work for abide plugin

### ISSUE THREAD

**Issue by carlosms** [zurb/foundation-sites#8822]
**How can we reproduce this bug?**

1. Append a new required input to a form
2. Call reInit with a jQuery selector parameter, as documented here:
http://foundation.zurb.com/sites/docs/javascript.html#adding-content-to-plugins
3. Submit the form

**What did you expect to happen?**

The new required input should be invalid if it's empty

**What happened instead?**

The input is not validated

**Test case:**

The following jsfiddle works only when you uncomment the second reInit call.
https://jsfiddle.net/carlosms/mLrcozak/2/

**Comment by designerno1** [comment]
Hi,
i think because you wan't to reInit the form you have to pass  the form to the reinit function because the plugin is on the form element
`Foundation.reInit($("[data-abide]"));`
https://jsfiddle.net/mLrcozak/3/

**Comment by carlosms** [comment]
You are right. It makes sense now that I see an example, but it wasn't obvious by reading the docs only.

Thank you!

**Comment by eXist73** [comment]
This seems to still be an issue in foundation.

**Comment by lirael** [comment]
@eXist73  I had the similar issue and fixed it by calling 
`Foundation.reInit('abide');`
after I add new elements
