### ISSUE TITLE
data-equalizer-mq not functioning

### ISSUE THREAD

**Issue by thisisblacksmith** [zurb/foundation-sites#8823]
**How can we reproduce this bug?**

1. Use data-equalizer and data-equalizer-mq="medium-up" on the parent row and then data-equalizer-watch on child columns using the latest Foundation and Equalizer files

**What did you expect to happen?**

Height to stop being set on mobile. 

**What happened instead?**

Nothing. Equalizer continues to set height, ignoring the -mq option

**Test case:**

http://codepen.io/anon/pen/pyXqyP

**Comment by designerno1** [comment]
according to the docs http://foundation.zurb.com/sites/docs/equalizer.html#js-options
have you tried `data-equalize-on="medium"` or `data-equalize-on-stack="false"`

**Comment by thisisblacksmith** [comment]
Yep that's it. Thanks. I was pulling data-equalizer-mq from Foundation 5.
