### ISSUE TITLE
[Sticky] Doesn't calculate width and some other css properties properly at Opera

### ISSUE THREAD

**Issue by shlag3n** [zurb/foundation-sites#8824]
Affected at least on Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
CSSStyleDeclaration doesn't support [] operator. 

That means that lines like here - https://github.com/zurb/foundation-sites/blob/develop/js/foundation.sticky.js#L274:
`comp = window.getComputedStyle(this.$container[0]), 
pdng = parseInt(comp['padding-right'], 10);`
will give us pdng = undefined.

To make it work it's enough to replace all calls like above with getting it through property (like `pdng = parseInt(comp.paddingRight, 10);`) or by calling getPropertyValue (like `parseInt(comp.getPropertyValue('padding-right', 10))`)

**Comment by DanielRuf** [comment]
Opera switched to Chromium / Blink.

Opera 12 is very old.

https://en.wikipedia.org/wiki/History_of_the_Opera_web_browser#Version_12

> On November 20, 2012, Opera 12.11 was released. This release was mainly a stability and security improvement over the previous version.[79]
> 
> On December 17, 2012, Opera 12.12 was released. This release is a recommended security and stability update over the previous version.[80]
> 
> On January 30, 2013, Opera 12.13 was released as a recommended stability and security update.[81] A week later, on February 5, 2013, Opera 12.14 was released after the users discovered an autoupdate crash loop bug.[82]
> 
> On April 4, 2013, Opera 12.15 was released. This release is a recommended security and stability update over the previous version.[83]
> 
> On July 4, 2013, Opera 12.16 was released. This release is a recommended security and stability update over the previous version.
> 
> On April 23, 2014, Opera 12.17 was released as a platform-specific security update for Windows to fix the Heartbleed bug in the installer and autoupdater of Opera. The browser itself is not threatened by Heartbleed.[84]
> 
> On February 16, 2016, Opera 12.18 was released for the Windows platform. It adds support for elliptic curve cryptography (ECC) as well as Galois/Counter Mode (GCM) for encrypted connections to enable Opera 12 to connect to servers that don't allow other encryption modes anymore. In addition a security issue in the mail client was fixed.[85]

So these were just security updates for a very old unsupported browser.

https://foundation.zurb.com/sites/docs/compatibility.html

I guess we can close this.
