### ISSUE TITLE
[Sticky] Wrong default value for data-check-every at documentation

### ISSUE THREAD

**Issue by shlag3n** [zurb/foundation-sites#8825]
Default value for `data-check-every` is declared as 50 at http://foundation.zurb.com/sites/docs/sticky.html#js-options.html#js-options, but is -1 at plugin code.

**Comment by denisahac** [comment]
The inconsistency points out to this [line:443](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.sticky.js#L443) of `foundation.sticky.js`. The docs generator reads the value in the **@example** while the hard-coded value for `checkEvery` is -1.

What value should be consider the default?

**Comment by ar-rm** [comment]
I ran into this too via a bug it was causing.

 `-1` will prevent recalc on scroll. Which means that one of the values important to `data-btm-anchor` only calculates on `init` and doesn't update when you start scrolling. And it needs to update as you start to scroll to properly calculate where the stuck element will become unstuck.

In my case that meant the *stuck* element became un-stuck too early. And by *too early* I mean it become unstuck at a distance away from the `data-btm-anchor` (ex: `data-btm-anchor="elem:top"`) that was exactly the height of the stuck element.

Setting `data-check-every` to anything but "-1" resolved the issue.

That means, if `-1` is the default, then out-of-the-box, using `data-btm-anchor` is broken.

Unless I'm misunderstanding something.

**Comment by andycochran** [comment]
@brettsmason Sounds like this is a code bug, not a docs error? 
@colin-marshall You've worked a lot on Sticky, right? Any thoughts on this?

**Comment by shlag3n** [comment]
@andycochran, it seems to be general issue, not only for Sticky. i guess docs are taking default value from @example attribute at comments, but actual value may be different. You can find additional example here -  https://github.com/zurb/foundation-sites/blob/develop/js/foundation.dropdownMenu.js#L393-L398  and http://foundation.zurb.com/sites/docs/dropdown-menu.html#js-options

**Comment by brettsmason** [comment]
@colin-marshall @ncoden Does this look like something we could fix? Fro what I understand it would require checking over all the default options for the JS plugins and confirming they match the comments.

**Comment by ncoden** [comment]
@brettsmason This should already be fixed. See https://github.com/zurb/foundation-sites/pull/9562
