### ISSUE TITLE
[Drilldown] - Back button in data-options not working?

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#8826]
I was trying to convert an older [example](http://codepen.io/rafibomb/pen/mVwwRW) of @rafibomb from overriding the default to using data-options.

But maybe I did something wrong or there is a bug in changing the text of the back button **using data-options**. Can some take a look at the following codepen and tell me why it is not working?

http://codepen.io/anon/pen/jqgEGm

**Comment by denisahac** [comment]
You're using the **data-options** in the wrong way, try the example configuration below, it should work.

`<ul data-back-button='<li class="js-drilldown-back"><a>Custom back text</a></li>'>`

**Comment by Silvester20** [comment]
Thanks for the quick answer and providing the solution. Now it does work indeed!
