### ISSUE TITLE
[MediaQuery] Doesn't initialize as it's supposed at Opera (Linux)

### ISSUE THREAD

**Issue by shlag3n** [zurb/foundation-sites#8827]
**How can we reproduce this bug?**
1. Open any foundation (6.2) site at Opera (tested on Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16)
2. Check value of `Foundation.MediaQuery.queries` and `$('.foundation-mq').css('font-family')` (where it's initialized from)

**What did you expect to happen?**
Extracted styles from `$('.foundation-mq').css('font-family')` should be like at other browsers, smth like `"'small=0em&medium=40em&large=64em&xlarge=76.875em&xxlarge=90em'"`

**What happened instead?**
Extracted styles from `$('.foundation-mq').css('font-family')` are `"'DejaVu Sans'"`

**Test case:**
Check console output at Opera and other browser - http://codepen.io/anon/pen/QNewBM.

**Comment by designerno1** [comment]
checket it in opera 37.0.2178.43 windows
there the media query is correct

**Comment by shlag3n** [comment]
Cool, checked it on Mac - Opera 37.0.2178.43, Mac OS X 10.7.4 64-bit
The media query is correct too.

**Comment by shlag3n** [comment]
Opera/Opera Mini on Adnroid 4.4 is obviously fine too (used this - http://codepen.io/anon/pen/reXLyL to check it).
So it seems that this issue is only about Opera on Linux (tested on Ubuntu 14.04 64 bit), changed title accordingly.

**Comment by andycochran** [comment]
Which version of Opera on Ubuntu? Only last 2 versions are supported.

**Comment by shlag3n** [comment]
It's 12.16, last one.

**Comment by COLABORATI** [comment]
Please check #8659 - are you loading the foundation js async?

**Comment by shlag3n** [comment]
@COLABORATI, thank you, but not. You can check provided [codepen](http://codepen.io/anon/pen/QNewBM). You can reproduce this issue only at Opera and seems only on Ubuntu, other browsers and Opera on Windows/Mac are fine.
But maybe it has same nature, don't know.

**Comment by DanielRuf** [comment]
Does it still occur? Opera now uses Chromium / Blink as engine.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback and we do not support such old browsers anymore.
