### ISSUE TITLE
Magellan Default Documentation Incorrect

### ISSUE THREAD

**Issue by acarnwath** [zurb/foundation-sites#8832]
The documentation for magellan states the following are the default values:
- data-animation-easing: ease-in-out
- data-deep-linking: true
- data-bar-offset: 25

However, based on the code (below), it appears as though those are example values and the values are in fact:
- data-animation-easing: 'linear'
- data-deep-linking: false
- data-bar-offset: 0

```
/**
 * Default settings for plugin
 */
Magellan.defaults = {
  /**
   * Amount of time, in ms, the animated scrolling should take between locations.
   * @option
   * @example 500
   */
  animationDuration: 500,
  /**
   * Animation style to use when scrolling between locations.
   * @option
   * @example 'ease-in-out'
   */
  animationEasing: 'linear',
  /**
   * Number of pixels to use as a marker for location changes.
   * @option
   * @example 50
   */
  threshold: 50,
  /**
   * Class applied to the active locations link on the magellan container.
   * @option
   * @example 'active'
   */
  activeClass: 'active',
  /**
   * Allows the script to manipulate the url of the current page, and if supported, alter the history.
   * @option
   * @example true
   */
  deepLinking: false,
  /**
   * Number of pixels to offset the scroll of the page on item click if using a sticky nav bar.
   * @option
   * @example 25
   */
  barOffset: 0
}
```

**Comment by phifa** [comment]
Can someone please give some feedback on this? Also, how could I actually make `ease-in-out` happen??

**Comment by acarnwath** [comment]
@phifa You can set the data attribute to "ease-in-out" - "linear" is what's happening by default.  The docs are not incorrect in capturing how the functionality works, just what the default values are set to.

**Comment by phifa** [comment]
actually not true for me. when i set `ease-in-out`, i get a console error: 

`jquery.js:6369 Uncaught TypeError: jQuery.easing[this.easing] is not a function`

Without it, it works, but only `linear` - not looking so nice. I am on Foundation 6, downloaded yesterday.

**Comment by ddiomedewaw** [comment]
For anyone having trouble with magellan, I found this on Zurb's building block's library. It was the most straightforward approach, worked right away and probably should be added to the docs.

http://zurb.com/building-blocks/sicky-sidebar-using-magellan

**Comment by brettsmason** [comment]
This has now been fixed in the docs along with any other incorrectly listed defaults.
