### ISSUE TITLE
Fix input-group-label's border-radius when input-group-label is the last child

### ISSUE THREAD

**Issue by johnbacon** [zurb/foundation-sites#8833]
Foundation properly applies border-radius to an `input-group-label` as the first child of `input-group-field`, but when `input-group-label` is the last child of `input-group`, no border-radius is applied.

Working properly as `:first-child`:
![](http://i.imgur.com/hI5ihF8.png)

Working improperly as `:last-child`:
![](http://i.imgur.com/wc3dFwS.png)

Intended behavior as `:last-child`:
![](http://i.imgur.com/sW4fMrE.png)

HTML used as `:last-child`:

``` html
<div class="input-group">
    <input type="number" class="input-group-field">
    <span class="input-group-label">%</span>
</div>
```

This issue is caused by [line 41](https://github.com/zurb/foundation-sites/blob/df4d7d76e97bd934622beacbb65efacd600b2e26/scss/forms/_input-group.scss#L41) of _input-group.scss:

``` scss
> :last-child {
    > * {
        border-radius: if($global-text-direction == rtl, $global-radius 0 0 $global-radius, 0 $global-radius $global-radius 0);
    }
}
```

That line is targeting only children of `input-group`'s last child (rather than the last child itself). This solution seems to be implemented to support `input-group-button` as the last child, [as seen in the Forms documentation](http://foundation.zurb.com/sites/docs/forms.html#inline-labels-and-buttons).

A dirty hack that will solve both cases while not causing visual artifacts is as follows:

``` scss
> :last-child {
    border-radius: if($global-text-direction == rtl, $global-radius 0 0 $global-radius, 0 $global-radius $global-radius 0);
    > * {
        border-radius: if($global-text-direction == rtl, $global-radius 0 0 $global-radius, 0 $global-radius $global-radius 0);
    }
}
```

I'm sure there's a more elegant solution to allow `input-group-label` to be used as the last child.

**Comment by johnbacon** [comment]
After re-reading, I now notice the `Working properly as :first-child` example actually isn't applying the proper border-radius to the top-right and border-radius-top-bottom either.

**Comment by kball** [comment]
@andycochran I know you have opinions about button/input/etc groups... can you take a look at this one?

**Comment by andycochran** [comment]
I've found a solution that works for all four cases (`input-group-button` on right or left, `input-group-label` on right or left). 

![image](https://user-images.githubusercontent.com/409279/38046106-b7a25cfa-328c-11e8-995b-dad5672213b0.png)

```
    > :first-child {
      &:not(.input-group-button){
        border-radius: if($global-text-direction == rtl, 0 $input-radius $input-radius 0, $input-radius 0 0 $input-radius);
      }

      &.input-group-button > * {
        border-radius: if($global-text-direction == rtl, 0 $input-radius $input-radius 0, $input-radius 0 0 $input-radius);
      }
    }

    > :last-child {
      &:not(.input-group-button){
        border-radius: if($global-text-direction == rtl, $input-radius 0 0 $input-radius, 0 $input-radius $input-radius 0);
      }

      &.input-group-button > * {
        border-radius: if($global-text-direction == rtl, $input-radius 0 0 $input-radius, 0 $input-radius $input-radius 0);
      }
    }
```

Working on a PR…
