### ISSUE TITLE
[Orbit] Orbit-Container, Orbit-Slide height

### ISSUE THREAD

**Issue by mrtpain** [zurb/foundation-sites#8835]
**This can be reproduced by viewing any orbit slider on foundation 6.2.1**

**What I expect to happen**
As the browser window scales up and down, the aspect ratio of the slides and content should remain the same. Instead, the width scales perfectly and the height is set at whatever the document loaded at initially.

**What actually happens**
On document load, the height of the slider is added to the orbit-container class. Each slide within is given the same max-height. When scaling the browser up and down, the height of the slider becomes unresponsive while the width is responsive. Cutting off the slides content as the browser scales.

**Test case:**
View the orbit docs or this foundation 6 template to recreate the issue. Load the website on desktop then scale down to mobile to see empty whitespace underneath the slider. Or, load on small mobile window then scale to desktop to see the height of the slider remain the same, cutting off slide contents.
http://foundation.zurb.com/templates-previews-sites-f6/ecommerce.html

**Quick Dirty Fix**
I've adjusted css in my styles to give the orbit-container a height of 100%, also .orbit-class has been given max-height: 100%. This will override the fixed height that orbit.js gives to each slide when the document is loaded. Not a clean fix, but fixed for now.

**Comment by rafibomb** [comment]
@mrtpain Thanks for sharing your solution! It would be best to take this logic out of JS. Right now the height is calculated by JS and the arrows are set on page load. It works well in the real world except if the browser size is changed without refreshing. There is already an open issue on it here https://github.com/zurb/foundation-sites/issues/7815 so we'll close this on favor of it. It'd be great if can work together on a better solution-  Thanks!
