### ISSUE TITLE
[Off-canvas] Fixed menu navigation

### ISSUE THREAD

**Issue by antopossegithub** [zurb/foundation-sites#8836]
Hi, I'm an italian webdesigner and I've this problem,

At present there is no way to fix this thing. I believe you need to create a useful command to resolve this thing, so you can choose whether to leave the menu as it is now, or to follow navigation
Give us a link to a CodePen or JSFiddle that recreates the issue.

Sorry for my english...

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by brettsmason** [comment]
@antopossegithub I don't fully understand what you want to do. Is there any way you could link to example or explain in more detail so I can help out?

**Comment by antopossegithub** [comment]
Yes :) I'm sorry for my English...it's not perfect!

So.... If you go here [http://foundation.zurb.com/sites/docs/off-canvas.html#multiple-menus](http://foundation.zurb.com/sites/docs/off-canvas.html#multiple-menus)
• click OPEN MENU LEFT
• you can see that the menu is fixed on top and for find it you must go on the top of the page.

I think it is a problem and the solution is to make sure that it is always a fixed menu

**Comment by brettsmason** [comment]
@antonioparisi Great thanks for the explanation! :smile: 
I was actually working on a way to change this a few days ago. Do you mean [like this?](http://codepen.io/brettsmason/pen/WxeeNO).

**Comment by antopossegithub** [comment]
Thank you so much @brettsmason this is just what I needed.
😄😄😄😄😄

**Comment by brettsmason** [comment]
@antopossegithub Great!
I'll keep this open as I'll put a PR together to make it work like this in core.

**Comment by antopossegithub** [comment]
I'm very happi it was fixed 👍 💯
