### ISSUE TITLE
[Visibility Classes] ISSUE NAME HERE

### ISSUE THREAD

**Issue by coachie** [zurb/foundation-sites#8837]
**How can we reproduce this bug?**
1. http://foundation.zurb.com/sites/docs/visibility.html states following:
   "_Visibility classes use !important to ensure they aren't overriden by more specific selectors. This is the only component in the framework that uses !important_."
2. http://foundation.zurb.com/sites/docs/drilldown-menu.html uses !important as well. Like:
   .is-drilldown li {
   display: block !important;
   }

**What did you expect to happen?**
I used class="show-for-medium" on a menu-item `(<li>).`

**What happened instead?**
It didn't work, because the use of 'block !important' within drilldown-menu

**Test case:**
Not available.

Give us a link to a CodePen or JSFiddle that recreates the issue.
- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by andycochran** [comment]
I think we're able to just nix the `!important` and this will still work.

**Comment by rafibomb** [comment]
@andycochran Should be right 

@coachie Are you able to remove the !important and see if it works as expected? If so we'd love to see a PR on this one! All for reducing specificity.

**Comment by coachie** [comment]
@andycochran @rafibomb That works fine with me! Thanks!

**Comment by andycochran** [comment]
Hi, @gakimball. It was perhaps you who added that `!important` in [#L31-L33](https://github.com/zurb/foundation-sites/blame/develop/scss/components/_drilldown.scss#L31-L33). Was there any particular reason we should know about before nixing it?
