### ISSUE TITLE
Orbit JS didn't work in fullpage JS

### ISSUE THREAD

**Issue by yeomann** [zurb/foundation-sites#8839]
Orbit js is so buggy, First, upon using orbit js with fullpage js all worked in the start and everything was fine, until, I tried to resize the browser and play with responsiveness and then orbit container was gone :anger: Mind that i was doing this in win 10 chrome and was using FoundationPress template for wp. It was so frustrating. I couldn't see my slider. Whole slider was just fade away. One way to get around was to apply 

```
.orbit-container {
    height: 100vh !important;
}

```

Which solved the issue but still its so frustrating and bad that orbit js just failed miserably and whole slider crashed!
Another problem i had after solving container hack that sometimes orbit just upon clicking right button didn't came back to first slide and instead was showing no image and then next and previous button stopped working.

**Comment by dragthor** [comment]
You were using http://alvarotrigo.com/fullPage/ with an orbit?  Do you have a CodePen?

**Comment by JeremyEnglert** [comment]
Ensuring Orbit works with _every other_ tool (outside of Foundation) is nearly impossible. However, we will keep this in mind when working on V7.
