### ISSUE TITLE
[Top Bar] Foundation Site 6.2.1 NOT WORKING AS ADVERTISED

### ISSUE THREAD

**Issue by superchap** [zurb/foundation-sites#8841]
**How can we reproduce this bug?**

1. CREATE index.html file and put in your code as follows ...

a) take your recommended code from here --> http://foundation.zurb.com/sites/docs/installation.html "HTML Starter Template"
(see 1st attached image: 'Github - Top Bar issue - 1 - HTML starter template code.jpg') and then

b) take your recommended from here --> http://foundation.zurb.com/sites/docs/top-bar.html "Basics" (see 2nd attached image: 'Github - Top Bar issue - 2 - Top Bar Basics code.jpg') ...

c) combined, the code will look simply like what you see in the 3rd attached image: 'Github - Top Bar issue - entire HTML code.jpg'.

d) Finally, Firefox displays the HTML file as you see in the 4th attached image: 'Github - Top Bar issue - 4 -  Resulting Page in Firefox NO DROPDOWN.jpg' ... and sadly ... THERE'S NO DROPDOWN (highlighted for effect). Mind you, note the 'magical' addition of  ' ="" ' {equals/quotation/quotation} right after ' data-dropdown-menu ' ... could those three characters, magically inserted, be the issue here???! If so, what's a guy to do about this?

**What did you expect to happen?**

I expected to see a dropwdown menu.

**What happened instead?**

No dropdown menu and the magical appearance of ' ="" ' (see above)

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

I'm unable to comply with your request as I'm not (yet) that advanced. ["Sorry bout that." -Hagrid]

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)
![github - top bar issue - 1 - html starter template code](https://cloud.githubusercontent.com/assets/6477792/15516560/eeac63ee-21b8-11e6-9bb3-3872deaef937.jpg)
![github - top bar issue - 2 - top bar code](https://cloud.githubusercontent.com/assets/6477792/15516562/eeb02786-21b8-11e6-9922-678cdd2e81f1.jpg)
![github - top bar issue - 3 - resulting html code - note line 18](https://cloud.githubusercontent.com/assets/6477792/15516563/eeb1bfc4-21b8-11e6-97d9-130ac1546ce0.jpg)
![github - top bar issue - 4 - resulting page in firefox no dropdown](https://cloud.githubusercontent.com/assets/6477792/15516561/eeafd45c-21b8-11e6-936b-904f8f8940df.jpg)

**Comment by denisahac** [comment]
I think the issue is not having the correct URL referenced to the `foundation.min.js`. As you can see in your directory structure the `foundation.min.js` is located in `js/vendor/` directory.

So the correct script for referencing the `foundation.min.js` is: 

```html
<script src="js/vendor/foundation.min.js"></script>
```

Instead of
```html
<script src="js/foundation.min.js"></script>
```

Also, please check the **console tab** for any 404 resources that are related to **Foundation**.

I hope that helps.

**Comment by superchap** [comment]
Brilliant! Thank you SO MUCH!!!
I have to run, but will be back.
