### ISSUE TITLE
Add setting variable for cite ::before content

### ISSUE THREAD

**Issue by nessthehero** [zurb/foundation-sites#8845]
Can the content for the ::before for the cite element in typography/_base.scss be specified with a variable, so that we can set an override?

Yes, I can just change it easily in my CSS, but it'd be nice to just be able to set a variable and have the default style be what I want from the start.

**Comment by brettsmason** [comment]
@nessthehero I agree with you on this. Could you put a PR together to fix this?
If not I'll see if I can put something together when I get time. Just let me know.

**Comment by DaSchTour** [comment]
If help is needed just tell me. I'll find some time to make a PR.

**Comment by nessthehero** [comment]
I will try to whip something up!

**Comment by kball** [comment]
Fixed in #9058. Will be in 6.3
