### ISSUE TITLE
Create a Page, Showing how to prevent the import util error

### ISSUE THREAD

**Issue by jgacuca567** [zurb/foundation-sites#8847]
@rafibomb 
@gakimball 

I am requesting you create a page showing how to solve the error 
```css
@import 'util/util' is not found
```

I have seen this question on the forum multiple times and there seems to be no answer when installing with `bower`. 

Please create an example page showing the steps that should be taken if that error occurs.

**Comment by brettsmason** [comment]
@jgacuca567 Could you explain or link to an example forum topic with this issue?
I use Foundation with Bower and don't have a problem, but I'm happy to update the docs with an explanation if you could explain the issue some more.

Would showing an example Gulp task help here? All you should need to add to your Gulp Sass task is:

`includePaths: 'bower_components/foundation-sites/scss'`

But I could add a full example [on this page](http://foundation.zurb.com/sites/docs/sass.html).

**Comment by jgacuca567** [comment]
Hi @brettsmason , I use grunt and have already included the Path, but when I still run `grunt` I keep getting the error.

**Comment by brettsmason** [comment]
@jgacuca567 Could you share the contents of your `gruntfile.js` so I can look into it a bit more? Its been a while since I used Grunt so this would speed up the testing :smile:

**Comment by jgacuca567** [comment]
@rafibomb 
@brettsmason 
@gakimball 

Have you tried installing using `bower` only?

**Comment by brettsmason** [comment]
@jgacuca567 Sorry I've been away for a few days and only just had time to look at this.
Yes I use Foundation via Bower exclusively, mainly in my WordPress starter theme without any problems.

Having just tried it I've got it working correctly. I changed:
`loadPath: ['bower_components/foundation-sites/scss'],` to:
`includePaths: ['bower_components/foundation-sites/scss'],` (or `includePaths: ['bower_components/foundation-sites/scss', 'bower_components/motion-ui/src'],` if using Motion-UI).

Let me know if that works.

**Comment by jgacuca567** [comment]
@brettsmason It is working now. However when I run grunt, the error I get is that the foundation and settings file is not found. 

```css
/** foundation.scss file */
@import 'settings';
@import 'foundation';
@include foundation-everything;
```

And this is the error I get
<img width="639" alt="screen shot 2016-06-07 at 12 31 14 pm" src="https://cloud.githubusercontent.com/assets/4000076/15866293/0cbd1d1c-2cac-11e6-86ce-84346c950511.png">
