### ISSUE TITLE
Error: argument `$list` of `nth($list, $n)` must not be empty

### ISSUE THREAD

**Issue by magic-77** [zurb/foundation-sites#8848]
Hi to all,
running into an issue i can't solve.

Doing an Import with
@import "foundation";
results with this Error Message

`Error: bower_components/foundation-sites/scss/util/_breakpoint.scss
Error: argument `$list` of `nth($list, $n)` must not be empty
        on line 23 of bower_components/foundation-sites/scss/util/_breakpoint.scss
>> @if nth(map-values($breakpoints),1) != 0 {
   ----^`

I'm using a simple Gulp Workflow using "node-sass 3.7.0" and "libsass 3.3.6" on Ubuntu 15.

**Comment by brettsmason** [comment]
@magic-77 Do you have a `$breakpoint` map in your `_settings.scss` file?
You should have something like this:

```
$breakpoints: (
  small: 0,
  medium: 640px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);
```
That error is basically saying your smallest breakpoint doesn't start at 0, but you have to include a breakpoint with a value of 0 for everything to work correctly.

If you can let me know and I can help further if needed.

**Comment by magic-77** [comment]
yes there is such a map. I just copied the Original _settings.scss into my Project Folder and included it.

>     // 2. Breakpoints
    // --------------
    $breakpoints: (
       small: 0,
       medium: 640px,
       large: 1024px,
       xlarge: 1200px,
       xxlarge: 1440px,
    );
    $breakpoint-classes: (small medium large);

I'm using a custom Gulp Workflow like this

> 		var includeSassPaths = [
		  'bower_components/foundation-sites/scss',
		  'bower_components/normalize-css',
		  'bower_components/jQuery.mmenu/src'
		];


>   gulp.task('sass:dev', function() {
      return gulp.src( source_dir+'/scss/'+pkg.name+'.scss' )
        .pipe($.sourcemaps.init())
        .pipe($.sass({
          includePaths: includeSassPaths,
          precision: 10,
          sourcemap: true,
          outputStyle: 'nested'
        }))
        // Catch any SCSS errors and send Notification to OS
        .on('error', $.notify.onError({
          message: 'Error: <%= error.message %>',
          title: 'SCSS Error'
        }))
        .pipe($.autoprefixer({
          cascade: false
        }))
        .pipe($.sourcemaps.write('.', {
          sourceMappingURLPrefix: '/files'
        }))
        .pipe(gulp.dest( build_dir + '/' ));
    });

**Comment by magic-77** [comment]
ok, got it.
I've mixed Foundation and Susy 2 Framework. So including Foundation Mixins before Susy will work for me now.

**Comment by brettsmason** [comment]
Great glad you got everything working :smile:
