### ISSUE TITLE
[Equalizer] data-equalize-on medium is not default

### ISSUE THREAD

**Issue by nicwinn** [zurb/foundation-sites#8849]
**How can we reproduce this bug?**

1. Step one: Implement an equalizer row. 
2. Step two: Add data attribute `data-equalize-on`

**What did you expect to happen?**
Since the default for `data-equalize-on` is `medium` I expect equalizer to not fire on `small` but wait for the `medium` breakpoint.
**What happened instead?**
Nothing changes. `small` continues to equalize.
**Hack**
Just as it is in the Basics example code `data-equalize-on="medium"` the value must be applied.
![image](https://cloud.githubusercontent.com/assets/9751044/15547751/d0b6a022-226a-11e6-8c43-d4a7025c4d2e.png)

**Test case:**

- [CodePen with Foundation 6](http://codepen.io/nicwinn/pen/EyYNWM)
![foundation data-equalizer](https://cloud.githubusercontent.com/assets/9751044/15547490/a5713630-2269-11e6-9740-e93367e67a2a.gif)

**Comment by rafibomb** [comment]
Looks like there is a conflict of default settings. 

<img width="811" alt="screen shot 2016-05-27 at 8 36 20 am" src="https://cloud.githubusercontent.com/assets/5652085/15613236/62a5a9e2-23e7-11e6-93c2-bad440fba4a5.png">

If you add `equalize-on-stack="false"` it should do it. And we'll change the default setting to reflect that to reduce this confusion.

**Comment by rafibomb** [comment]
Done df70a3b`

**Comment by nicwinn** [comment]
Thanks. I discoverd I could use that approach as well. But I couldn't decide which was the better "mobile first" way of attacking the issue. Finally decided that in my case `equalize-on-stack="false"` looked like a mobile hack while `data-equalize-on="medium"` appeared more progressive.

**Comment by simoazzo** [comment]
For me, it is not working.

I set `<div class="business-listing-outer-container" data-equalizer data-equalize-on="medium">`
but on mobile still watching.
