### ISSUE TITLE
[Input Group] Flexbox input group overflows the width of parent containers

### ISSUE THREAD

**Issue by johnbacon** [zurb/foundation-sites#8851]
The flexbox input group overflows the width of any parent container that is smaller than the input group thinks it should be.

Desired behavior (`max-width: 120px;`):
![](http://i.imgur.com/r6MiI96.png)
Actual behavior (`max-width: 120px;`):
![](http://i.imgur.com/GbeQZlu.png)
Here is a Codepen that demonstrates the issue and includes a fix: http://codepen.io/johnbacon/pen/xOKdNG

The root cause is the `width: auto` that was applied to the flexbox-based `.input-group-field` in [this commit](https://github.com/zurb/foundation-sites/commit/4ff0759a6c3abc36c48e0610088b6c0af86b99e0#diff-36a3c48d0968fa90c112e137ecd866ffR91). I'm not sure sure why it was there (if it was done for a reason), so I don't feel comfortable submitting a pull request without further testing. However, removing the `width: auto;` appears to to fix the issue.

**Comment by OverFlow636** [comment]
I stumbled on this issue as well. However its not just max-width that it overflows, it will overflow any parent that is smaller than it thinks it needs to be.

http://codepen.io/OverFlow636/pen/zBajyo

**Comment by johnbacon** [comment]
Thanks for the update on this, @OverFlow636. I've modified the title and content of the issue to match.

**Comment by kball** [comment]
Fixed via #8907, will be in 6.2.4
