### ISSUE TITLE
Top Bar issues

### ISSUE THREAD

**Issue by Knight-Yoshi** [zurb/foundation-sites#8855]
Seems using flexbox with the top bar has a little bit of an issue when resizing, once it's under 1100 the right bar starts to cover up links on the left that do not have a sub-menu

<img width="1072" alt="screenshot 2016-05-26 10 00 46" src="https://cloud.githubusercontent.com/assets/6134576/15577022/bfdbcfc0-2328-11e6-85fa-e6bdf30eb67d.png">
http://codepen.io/KnightYoshi/pen/VjZBBr

Around 860 the right bar links start overlapping the left bar links while completely hiding links that do not have a sub-menu
<img width="837" alt="screenshot 2016-05-26 10 04 05" src="https://cloud.githubusercontent.com/assets/6134576/15577146/374cc74e-2329-11e6-9bd3-02e315c823db.png">

**Comment by andycochran** [comment]
You can fix the overlap with a simple `.top-bar .menu > li { z-index: 1; }`. But the real problem is having more content than will fit into the allotted horizontal space, as menus do not wrap to multiple lines.

**Comment by andycochran** [comment]
And of course, that's an app-specific problem. You have to define the breakpoints at which your menus respond.

**Comment by JeremyEnglert** [comment]
I agree with @andycochran. This is something that will have to be handled at the app/site level. Hard to handle this with the framework.
