### ISSUE TITLE
Site is Down

### ISSUE THREAD

**Issue by atilkan** [zurb/foundation-sites#8858]
15 Mins. CloudFlare can't show it. They did not cache it probably.

**Comment by kball** [comment]
Rackspace has an outage at their entire DFW datacenter, and that is impacting the foundation docs and marketing sites.  We'll have them back up as soon as we can.

**Comment by atilkan** [comment]
Almost 2 hours. Still down.

**Comment by brettsmason** [comment]
Everything appears to be up and running again so closing this.

**Comment by atilkan** [comment]
Why this things happening? This is not the first time i come across.
