### ISSUE TITLE
How to include jquery.js from Bower directory 

### ISSUE THREAD

**Issue by Almodovar** [zurb/foundation-sites#8865]
I am new to foundation and found the file structure is confusing. in Gulf compile document, the root is set as 'src/pages' but why the html uses "{{root}}assets/js/app.js" rather than using "../js/app.js". And if I need download Jquery and include the js file, what does bower_components do for us?

Thanks for answering my question.

**Comment by JeremyEnglert** [comment]
This is particular question is very project specific. Foundation does not come with any HTML. So please reference the necessary files in a way that matches your file structure.
