### ISSUE TITLE
Issue #7129 is back again?

### ISSUE THREAD

**Issue by pluus** [zurb/foundation-sites#8869]
[https://github.com/zurb/foundation-sites/issues/7129](https://github.com/zurb/foundation-sites/issues/7129)  This issue is exactly what im talking about.

I'm currently using Foundation 6.2.2 complete version to build a top-bar navigation menu and keep running into the problem that submenu links are not working. I've checked that <a> is actually being clicked but not redirecting to a page. I guess it must be a e.preventDefault() issue.

I tried using 6.0.4 without changing my nav structure and it worked fine.  Is anyone else having the same issue?

**Comment by brettsmason** [comment]
@pluus I've just downloaded the complete package download and links in submenus seem to work fine. For reference I was using this code to check (you mentioned top bar so I used the code from the docs plus an external link):

```
<div class="top-bar">
  <div class="top-bar-title">
    <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
      <button class="menu-icon dark" type="button" data-toggle></button>
    </span>
    <strong>Site Title</strong>
  </div>
  <div id="responsive-menu">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
          <a href="#">One</a>
          <ul class="menu vertical">
            <li><a href="http://www.google.com">Google (external)</a></li>
            <li><a href="#">Two</a></li>
            <li><a href="#">Three</a></li>
          </ul>
        </li>
        <li><a href="#">Two</a></li>
        <li><a href="#">Three</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Search"></li>
        <li><button type="button" class="button">Search</button></li>
      </ul>
    </div>
  </div>
</div>
```

Could you confirm this is the issue you are having?

**Comment by brettsmason** [comment]
I'm going to assume this is now working correctly as we haven't heard anything and in my testing it worked OK.
Please re-open if that's not the case.
