### ISSUE TITLE
[Magellan] Site Docs - Sticky Navigation "Second Example" doesn't work and its wrong, Please provide correct full code

### ISSUE THREAD

**Issue by madhanan** [zurb/foundation-sites#8870]
## The Second Example for sticky magellan menu bar doesn't work and it's wrong.

Please provide good documentation for magellean sticky menu bar.
### Link : [http://foundation.zurb.com/sites/docs/magellan.html]

`<div data-sticky-container>
  <div class="sticky" id="example" data-sticky data-margin-top="0" style="width:100%;" data-margin-bottom="0" data-top-anchor="topAnchorExample" data-btm-anchor="bottomOfContentId:bottom">
    <nav data-magellan>
      <ul class="horizontal menu expanded">
      <li><a href="#first">First Arrival</a></li>
      <li><a href="#second">Second Arrival</a></li>
      <li><a href="#third">Third Arrival</a></li>
      </ul>
    </nav>
  </div>
</div>`

**Comment by brettsmason** [comment]
@madhanan It looks OK to me - what issue are you having? You need to make sure you change the top/bottom anchors to your actual page markup though for it to work.

If you can let me know what the problem is and we can try and help.

**Comment by JeremyEnglert** [comment]
No response. Closing.

**Comment by IamManchanda** [comment]
@madhanan we are awaiting your reply if you want this thread to be reopened
Does this issue still exists??
