### ISSUE TITLE
[Foundation.Reveal] Unused parameter in _makeOverlay function

### ISSUE THREAD

**Issue by ocularrhythm** [zurb/foundation-sites#8880]
Wasn't sure if this is a bug or by design. There is an `id` parameter that is being passed to the `_makeOverlay` function, but it is not being used. Also, I don't see the value in creating a variable only to return it. Why not just return the jQuery element? I didn't want to create a pull request without knowing more.

```
/**
   * Creates an overlay div to display behind the modal.
   * @private
   */
  _makeOverlay(id) {
    var $overlay = $('<div></div>')
                    .addClass('reveal-overlay')
                    .appendTo('body');
    return $overlay;
  }
```

**Comment by ncoden** [comment]
Fixed in https://github.com/zurb/foundation-sites/pull/9446.
 
@ocularrhythm `_makeOverlay` is useful to keep the DOM stuff encapsulated and separated from the Reveal init logic.

**Comment by ocularrhythm** [comment]
I don't dispute the purpose or intention of the method, rather I was only curious about the points I originally made.

1. Why does an argument exist if it's not being used
2. Why create and return a variable, instead just return the jQuery element

Like so: 
```
  _makeOverlay() {
    return $('<div></div>')
                    .addClass('reveal-overlay')
                    .appendTo('body');
  }
```

**Comment by ncoden** [comment]
@ocularrhythm 
1. I don't know. There is no reason to keep an unused argument in Javascript, so it should be a mistake :)
2. You are right. I will return the JQuery element.
