### ISSUE TITLE
Expanded row children no longer contained to grid in Foundation 6.2.1

### ISSUE THREAD

**Issue by gpspake** [zurb/foundation-sites#8886]
#8304 introduces a pretty significant break to rows nested under a parent row with the expanded class; previously, they were contained to the grid - with the option to add the expanded class to nested rows as needed - but now all nested rows under an expanded row are also expanded and there is no fix once the left and right margin's are set to zero.

See [codepen example](http://codepen.io/nicwinn/pen/VjLZvE) - (change the foundation css version from 6.2.1 to 6.2.0)

I propose rolling back this commit until another solution is found for the original issue.

edit: update with correct issue number

**Comment by gpspake** [comment]
Upon further inspection, it looks like that commit is _not_ the issue since it's limited to collapsed items. The problem seems to be that the `.row .row` has its max-width set to none. Still trying to track down why this is happening.
![image](https://cloud.githubusercontent.com/assets/3385690/15757521/86a6df08-28cb-11e6-879a-c86c81f7bfa3.png)

**Comment by gpspake** [comment]
Ok, [here's where this was introduced](https://github.com/zurb/foundation-sites/commit/3822efecf799fe56d6a8bcfe1a9eb96312b6050e) ( ping @gakimball )

I see the thought process in #8304 - The problem is that once you set the max-width to none for nested rows, you lose the ability to contain them to the grid. We do this a lot; usually to escape the grid and add a full width background behind a contained row.

Isn't this unnecessary since you could just add the .expanded class to nested rows? Sidenote: IIrc there used to be a `contain-to-grid` class as a fix for this in previous versions.

**Comment by rhernandog** [comment]
+1 ti this. I'm also having to add the max-width myself using the mixins in order to go back to the 75rem of the row.

**Comment by gpspake** [comment]
@rhernandog If it's any help, I just added the following as a temporary fix to avoid having to edit the source components and mess with my build scripts:
```css
.row .row {
  max-width: 75rem
}

**Comment by rhernandog** [comment]
@gpspake Thanks. The problem is that I have some nested rows that need to be contained in the grid and others with the max-width to none. So basically I created a class for those and kept the .row .row with the max-width to none:
```css
.row .row {
  max-width: none;
}

.row .my-class {
  max-width: 75rem;
}
```

Then for other classes:
```css
.other-class{
  @extend .my-class;
}
```

**Comment by Aetles** [comment]
Ran into this myself when updating Foundation, broke my layout since I relied on nested rows to be constrained. I added as similar workaround:

`.row .row {
	max-width: $global-width;
}
`
