### ISSUE TITLE
6.2 - Drilldown navigation menu not working on iPad

### ISSUE THREAD

**Issue by MetalG3arSo1id** [zurb/foundation-sites#8887]
The is-drilldown-submenu.is-active class attribute transform: translateX(-100%) does not have the -webkit-kit vendor being pulled through to the browser so it doesn't open on iPad when you click a sub menu parent. 

Same thing with the .is-closing class for the is-drilldown-submenu class

I did raise this issue once before and was said to be then fixed in 6.2 foundation, but it wasn't. 

Is this vendor thing something we need to have set to generate automatically through visual studio or something? And then when compiling they are added into the css file?

Also when I did a hack to make the missing vendors for the translate attribute for the is-active / is-closing classes to show in the browser, the sub menus opened but the is-closing class on the iPad does not get removed after closing the top level menu parent, so you can't ever open up the sub menu ever again without a page refresh. 

I've always needed hacks to make this foundation drill down menu work right for iPhones and iPads. But at least before it was a style hack needed, where as this time the class is-closing is not even being removed from the DOM properly, which seems like a javascript bug?

I saw this when debugging the iPad Air on a MacBook.

Just to add this is all inside the responsive navigation / top-bar / nav-bar foundation components

**Comment by MetalG3arSo1id** [comment]
Just tested the drilldown outside the responsive navigation wrapper and the same bugs happen, can't open the sub menu on the iPad.

This is the code I'm using

`                                                        <ul class="vertical menu SmallNavMenu dropdown" data-responsive-menu="drilldown xlarge-dropdown">
                                                            <li class="nav-li has-submenu is-dropdown-submenu-parent">
                                                                <a href="#" tabindex="0">  
                                                                    <span class="spriteProjectIcons MyAccountIcon"></span>                                                              
                                                                    <span class="MyAccountText">My Account</span>
                                                                </a>
                                                                <ul class="vertical submenu menu dropdown-menu-wrapper is-dropdown-submenu">
                                                                    <li class="is-submenu-item is-dropdown-submenu-item">
                                                                        <a class="sub-menu-title" href="/">Log Out</a>
                                                                        <a class="sub-menu-title" href="/">Address Maintenance</a>
                                                                        <a class="sub-menu-title" href="/">Edit Personal Details</a>
                                                                        <a class="sub-menu-title" href="/">Manage Password</a>
                                                                        <a class="sub-menu-title" href="/">Order History</a>
                                                                        <a class="sub-menu-title" href="/">Statement</a>
                                                                    </li>
                                                                </ul>
                                                            </li>
                                                        </ul>`

**Comment by MetalG3arSo1id** [comment]
Just too let you know, I updated 10mins a go to the latest iOS for the iPad air and now all the above bugs are gone, fantastic! - But obviously people on the previous versions will have trouble still.

**Comment by rafibomb** [comment]
Odd, not sure what version you were on before. We did QA it on IOS 9.2 a few weeks back. Thanks for posting back your solution as it will help others!
