### ISSUE TITLE
[Magellan] sticky and small screens

### ISSUE THREAD

**Issue by paoloantinori** [zurb/foundation-sites#8890]
**How can we reproduce this bug?**

1. resize http://foundation.zurb.com/sites/docs/magellan.html to the size of a small screen
2. scroll down
3. Step three

**What did you expect to happen?**
Top Sticky menu to stay sticky on top

**What happened instead?**
Top menu does not stick

**Test case:**

The original source code of the doc page

**Comment by rafibomb** [comment]
Sticky is a separate plugin that has an option to stick on small. By default it is set to false.
`data-sticky-on-"small"`

**Comment by paoloantinori** [comment]
Found (and understood how to read correctly the docs) Thank you!
