### ISSUE TITLE
[Flex Grid] Bugs in docs

### ISSUE THREAD

**Issue by OndrejVasicek** [zurb/foundation-sites#8893]
**How can we reproduce this bug?**
1. Visit the http://foundation.zurb.com/sites/docs/flex-grid.html page
2. Watch any example with row/columns

**What did you expect to happen?**
Nice columns using the flexbox.

**What happened instead?**
* Last columns has “float: right”, which I believe it’s not necessary with flexbox.
* There is a rule “margin-right: -1px“ on columns, which makes either missing pixel in column (white 1px column without background) or missing right border (column covers it).
  
  ![foundation2](https://cloud.githubusercontent.com/assets/3864012/15799820/f81484b6-2a69-11e6-9bf4-551be89b9b7e.png)

    ![foundation1](https://cloud.githubusercontent.com/assets/3864012/15799819/f7d347d0-2a69-11e6-8581-73b8432c7c00.png)

* The basics example shows “12/6/4 columns“, but there isn’t any “small-12” class. It’s ok in regular grid, where the full width is the default, but not in flex. Here we apply the expand behaviour, as you write further.

  ![foundation3](https://cloud.githubusercontent.com/assets/3864012/15799821/f8529134-2a69-11e6-9637-b0c952e2fd32.png)

**Comment by andycochran** [comment]
Heh. There's a comment in the docs scss: 
```scss
margin-right: -1px; // Not sure why this has to be here
```
I think this can be nixed. Sorting this out…

**Comment by OndrejVasicek** [comment]
And what do you think about the point 1 and 3?

**Comment by rafibomb** [comment]
Looks like this is a docs specific style and @andycochran removed it. I cannot find a float: right property in the flex grid. If you can point out the line that is causing an issue or a bug with the grid, please open a new issue with the example. Thanks!

**Comment by OndrejVasicek** [comment]
There is no need for example or another issue. It’s here:

`Scss/grid/_column.scss:83`

You are probably mixing the regular grid with flex-grid in docs. Something you don’t recommend in docs :).

The point 3 seems to be a clear misunderstanding. There shouldn't be `12/6/4` and `12/6/8`. Just try that on yourself - change the size in docs. On small it's still 6 columns. It doesn't behave like the regular grid. In flex, when it's not defined, the width is let's say fluid, not 12 columns.

So it should be `6/6/4` and `6/6/8`, even if the first 6 aren’t exactly 6 columns (there is no widht set to 50%), but it behaves the same.

Or you can just add class `small-12` into the example. It depends on your point of view.

**Comment by brondsem** [comment]
Point 3 (flex grid example of 12/6/4 and 12/6/8 not going to full 12 on small) is still an issue, I think.  The previous comment explains all the details.  I ran into this on my own work, and then looked at the docs and the docs were misleading.
