### ISSUE TITLE
[Flex Grid] Alignment class missing

### ISSUE THREAD

**Issue by jurerick** [zurb/foundation-sites#8894]
**How can we reproduce this bug?**

1. aligning of grid vertically offers this classes:
align-top, align-middle, align-bottom

Those should align the grid, but nothing happens

Give us a link to a CodePen or JSFiddle that recreates the issue.
I also check the class from the fresh css download but those does not exists.

**Comment by rafibomb** [comment]
Hmm, I see it working here: http://codepen.io/rafibomb/pen/xOwPBo
And in the docs.
Can you describe how you were able to replicate this?
