### ISSUE TITLE
[Sticky] Vague error when bad id used

### ISSUE THREAD

**Issue by latagore** [zurb/foundation-sites#8896]
**How can we reproduce this bug?**
1. With the Sticky plugin, use an id that doesn't exist on the page in the `data-btm-anchor` attribute.

**What did you expect to happen?**
A reasonable error message to appear in the error console.

**What happened instead?**
On Firefox, the error `TypeError: anchor.offset(...) is undefined` appears in the error console instead.

**Test case:**
https://jsfiddle.net/1rpms1ax/ (the id `badid` is used in the `data-btm-anchor` attribute but there is no element in the document that has that id)

**Comment by diaboloshogunate** [comment]
+1

**Comment by JeremyEnglert** [comment]
Better error handling is a discussion for V7. Thanks for this report.
