### ISSUE TITLE
[Foundation for Sites] Correct concatenation order for JavaScript components

### ISSUE THREAD

**Issue by ghost** [zurb/foundation-sites#8909]
I downloaded Foundation 6.2.3 via Bower and would like to selectively concatenate the individual JavaScript components and utlities in `/bower_components/foundation-sites/js` with Gulp instead of adding the complete file (foundation.min.js).

What is the correct order? The only thing I could find in the documentation was jQuery first, followed by `foundation.core.js` and `foundation.util.mediaQuery.js`.

Also in the Bower package, what is the difference between the JavaScript in `/bower_components/foundation-sites/dist/plugins` and `/bower_components/foundation-sites/js` ?

**Comment by andycochran** [comment]
* `foundation.core.js` – Core should be first
* `foundation.util.*.js` – then the utils (in any order)
* `foundation.[component].js` – Then each component (in any order). 

The order of the components shouldn't matter, since they aren't dependent upon each other.

**Comment by dioogbento** [comment]
I would like to concatenate individual JavaScript components (as I only need a few for a small project) with Gulp but I have no knowledge of Gulp… Could someone please guide me on how to do it? Thanks!

**Comment by JeremyEnglert** [comment]
@dioogbento - there are many ways to do it. It will really depend on your setup.

But if you're using the ZURB template, simply comment out the components you don't need from the config file.

https://github.com/zurb/foundation-zurb-template/blob/master/config.yml
