### ISSUE TITLE
[F 6.2.0 Slider] - two slider on the same page did'nt work

### ISSUE THREAD

**Issue by xfifix** [zurb/foundation-sites#8913]
hello, 
i have a problem i have two slider on the same page there are just one who work, one displayed just for mobile and the other on the desktop.
On the loaded page there are just one who work these who is displayed, if i change the format display for see the other slider these didn't work ...

**Comment by xfifix** [comment]
It's work now but when i set the value of slider it's work but when move the cursor the value didn't start with this value enter ... 

i don't know it's clear ...

**Comment by andycochran** [comment]
@xfifix It might help us understand the issue if you could use [this template](https://github.com/zurb/foundation-sites/blob/develop/.github/ISSUE_TEMPLATE.md) to explain. Thanks.

**Comment by Owlbertz** [comment]
@xfifix Were you able to make this work in the mean time?

**Comment by kball** [comment]
Closing based on lack of reply - please reopen if you have more context for reproducing the bug.
