### ISSUE TITLE
Model Reveal for Wordpress + Foundation scrolls to the top before revealing the modal dialog

### ISSUE THREAD

**Issue by Prateek057** [zurb/foundation-sites#8914]
In our company we have integrated Wordpress with Foundation 5.3

I implemented a page in wordpress that provides all images as links.
clicking on image open a modal but it will also scroll to the top.
closing them modal does not lead to scroll back down.

[http://codepen.io/Prateek057/pen/LZpoze]

**Comment by Prateek057** [comment]
Issue seems to be with 
html body {
height: 100% 
}

any work around for this with out and repercussions ?

**Comment by Deckluhm** [comment]
Your CodePen doesn't work, probably because you have PHP code in it.
Can you provide a working one, with just important stuff in it?

Any reason for not using the latest Foundation `5.X` version? (`5.5.3`)
Or even Foundation 6?

**Comment by josh-h** [comment]
I am having similar issues with the Reveal forcing the screen to return to the top. I've isolated the issue to iOS with my iPhone using Foundation 6.2. See http://codepen.io/josho/pen/KMMvGo

The pen running on my iPhone causes the web page to scroll to the top when the reveal is opened. Opening a reveal shouldn't cause the page position to be lost.

Interestingly I can't reproduce on my desktop, so it may be a mobile Safari issue, not simply a small screen issue.

**Comment by SebaTeam9** [comment]
I have fixed this issue by setting the min-height to 100%, overwrite html, body { height: 100%}. Now the position is not lost

**Comment by andycochran** [comment]
@Prateek057 Does Josh's 6.2.1 fix work for you (removing the `href="#"`)? Or Seba's min-height fix? If not, please reopen this issue with a working codepen example so we can investigate the issue?

**Comment by jhafner** [comment]
A note for anyone else looking for this, on 6.2.2 removing `href="#"` doesn't affect anything, but the min-height fix does. Here's what's working for me currently:

```
html, body {
  min-height: 100%;
  height: auto !important; /* Yuck */
}
```
