### ISSUE TITLE
Equalizer should check for presence of at least 2 'watched' elements before executing

### ISSUE THREAD

**Issue by flyingL123** [zurb/foundation-sites#8920]
If an equalizer is set up with 0 or 1 `watched` elements inside of it, an error will occur in the `isStacked()` function, causing all other javascript on the page to break.

You may be asking yourself, why would someone create an equalizer if there aren't at least 2 `watched` elements in it? Well, I have run into this scenario while building an e-commerce website.

I have a generic 'product grid' template which resembles something like this:

```
<ul class="productGrid" data-equalizer></ul>
```

Then, depending on the grid being rendered, for example, related products, or customer also bought, or featured products, the e-commerce server populates the grid with a certain number of 'product cards'. Those cards have their own template, which resembles something like this:

```
<li class="productCard" data-equalizer-watch></li>
```

So, the issue arrises when one of these product grids contains 0 or 1 products, which can happen pretty frequently. I'm happy to create a pull request for this, but I was having trouble figuring out the appropriate place to put this check. If someone can point me in the right direction I can take it from there.

**Comment by andycochran** [comment]
Is it as simple as changing…
```js
this.$watched = $watched.length ? $watched : this.$element.find('[data-equalizer-watch]');
```
to…
```js
this.$watched = $watched.length > 1 ? $watched : this.$element.find('[data-equalizer-watch]');
```
?

**Comment by kball** [comment]
Fixed by https://github.com/zurb/foundation-sites/pull/9323

Will be in 6.3
