### ISSUE TITLE
Clearing lightbox arbitrarily shows wrong image

### ISSUE THREAD

**Issue by rainerm** [zurb/foundation-sites#8921]
Hello,

we use foundation.clearing 5.5.2 with jQuery v1.11.3 and encountered a possible bug, reproducable as follows:
- open a clearing lightbox in IE (9 - Edge), e.g. http://foundation.zurb.com/sites/docs/v/5.5.3/components/clearing.html
- click the same thumbnail and close the lightbox several times
- the lightbox will often show the wrong image (next in sequence)

(Using clearing 6.0 and jQuery v1.12.4 makes no difference)

The more at the start of the sequence the tested thumbnail is located, the greater is the chance to get the wrong image, so presumably there is also some timing/concurrency issue.

We identified one cause for this behaviour in function clearing.is_open(): different browsers will return different results for .prop("style").length, so maybe the used condition is not suitable here.

For our purpose, patching 

Foundation.libs.clearing.is_open = function (t)
{
        return t.parent().prop("style").width.length > 0;
};

for IE led to a reasonable result.

Please let me know, if upcoming versions will deal with this issue.

Thanks,
Rainer

**Comment by brettsmason** [comment]
As we are now working on Foundation 7, we are stopping maintenance of Foundation 5 so our resources can be used for Foundation 6 and 7. I can only suggest you upgrade to the latest version.
