### ISSUE TITLE
[Orbit] SPEED of Transition Orbit 6

### ISSUE THREAD

**Issue by Joseluisblom** [zurb/foundation-sites#8926]
**How can we reproduce this bug?**
1. ussing Orbit

**What did you expect to happen?**
 i would like to control the speed of the transition
**What happened instead?**
just can control data-timer-delay that is time beetwen sliders, but not the time of transition itself

please i need help i think transition time it's too fast, regards.

**Comment by albertvolkman** [comment]
@Joseluisblom I was trying to figure this out as well, and found the answer here-

http://foundation.zurb.com/sites/docs/motion-ui.html#custom-transitions

**Comment by shushugah** [comment]
@albertvolkman Can you explain what that code looks like?

I'm initializing foundation with this line:
`ZDF.globals.$document.foundation();`

and when I try 
```
ZDF.globals.$document.foundation({
      orbit : { animation_speed: 300}
      });
```

> sorry, object is not a valid parameter. You must use a string representing the method you wish to invoke

**Comment by albertvolkman** [comment]
@shushugah you define your transition in your sass file via the Motion UI directions-

https://github.com/zurb/motion-ui/blob/master/docs/transitions.md

And then you add the transition in your constructor. I instantiated mine via attributes, as seen here-

https://github.com/Norstone/norstone.github.io/blob/develop/index.html#L73

and then refer to the first 4 stanzas of this sass file-

https://github.com/Norstone/norstone.github.io/blob/develop/_sass/_modules.scss
