### ISSUE TITLE
WARNING: 20px was passed to rem-calc(), which is not a number error on build

### ISSUE THREAD

**Issue by slarti-b** [zurb/foundation-sites#8927]
This was for a demo of something else, so we didn't both configuring anything in particular, we just wanted "standard" foundation styles to be available and make things look decent.

We installed foundation for sites via bower.  Our bower.json included as a dependency:
`"foundation-sites": "^6.2.3"`
When we build (using grunt and grunt-sass) we get the following warning:
```
WARNING: 20px was passed to rem-calc(), which is not a number.
Backtrace:
	bower_components/foundation-sites/scss/util/_unit.scss:75, in function `-zf-to-rem`
	bower_components/foundation-sites/scss/util/_unit.scss:44, in function `rem-calc`
	bower_components/foundation-sites/scss/typography/_base.scss:310, in mixin `@content`
	bower_components/foundation-sites/scss/util/_breakpoint.scss:143, in mixin `breakpoint`
	bower_components/foundation-sites/scss/typography/_base.scss:307, in mixin `foundation-typography-base`
	bower_components/foundation-sites/scss/typography/_typography.scss:24, in mixin `foundation-typography`
	bower_components/foundation-sites/scss/foundation.scss:64, in mixin `foundation-everything`
	demo_styles.scss:13
```
Our demo_styles.scss (down to line 13 which triggers the error) is simply:
```
@import 'bower_components/foundation-sites/scss/foundation';

$global-font-size: 90%;
$body-background: #f7f7f7;
$header-sizes: (
  'small': (
      h1: '20px'
  )
);

$grid-column-align-edge: false;

@include foundation-everything();
```
Googling I found a similar warning referenced in #8203 but that seemed to be a misconfiguration.  We haven't done any config which should affect this (and the default config should work i assume!) so I'm logging a new issue

**Comment by slarti-b** [comment]
Sorry, I was tired and blind when I wrote that.  The one config we did caused the problem.

**Comment by jgacuca567** [comment]
@slarti-b , could you review Issue #8847 and show how you installed `Foundation` with `bower`
