### ISSUE TITLE
Foundation 6.2.3 minified CSS tooltip issues

### ISSUE THREAD

**Issue by geibi** [zurb/foundation-sites#8929]
**How can we reproduce this bug?**
1. Step one: Download Foundation 6.2.3 and use the min CSS
2. Step two: Create tooltips with classes "left" and "bottom"

**What did you expect to happen?**
Tooltip arrows point to the info text

**What happened instead?**
Arrows are missing and only showing a grey square divided in half diagonally. One side a bit darker.

**Test case:**
http://codepen.io/geibi/pen/qNZyYM

The expanded CSS version does not show these issues.

**Comment by Silvester20** [comment]
It was fixed but now it is here again in the new version, related to https://github.com/zurb/foundation-sites/issues/8144.

So for now you can use this [fix](http://codepen.io/anon/pen/rLeoQR) and hopefully it will be fixed in the core next release @Owlbertz @kball

**Comment by JeremyEnglert** [comment]
Tooltips have been reworked in newer versions. If this is still an issue, feel free to reopen.
