### ISSUE TITLE
Modal reveal not fully closing

### ISSUE THREAD

**Issue by rgreenosborne** [zurb/foundation-sites#8932]
**How can we reproduce this bug?**

1. Install zurbtemplate via git (foundation 6.2.3)
2. Install bower components (jquery 2.2.4 )
3. Create modal dialog
4. Close dialog with any data-close structure

**What did you expect to happen?**

Modal closes 

**What happened instead?**

Modal closes but <body class="is-reveal-open"> isn't removed.  Page is unresponsive.

**Test case:**

http://codepen.io/rgreenosborne/pen/wWGbER

**Comment by rgreenosborne** [comment]
**Partial Solution:**

Regression to Foundation Sites 6.2.1 solves issue.

**Comment by Deckluhm** [comment]
Just remove the `data-closable` attribute from your modal and it works as expected.

`data-closable` is needed for components / elements that are not natively closable (callouts for example).

**Comment by andycochran** [comment]
Yup. @Deckluhm is right. I'm gonna close this.
