### ISSUE TITLE
Cannot use foundation-sites 6.2.3 with Meteor 1.3.3

### ISSUE THREAD

**Issue by kevster** [zurb/foundation-sites#8933]
I just upgraded to Meteor 1.3.3 with Foundation Sites 6.2.3 (latest releases at time of writing) and I'm getting one of the errors described by @SierraGolf in issue #8721, also using same reproduction method:

```
1. meteor create --release 1.3.3 foundation-test
2. cd foundation-test
3. meteor add zurb:foundation-sites
4. meteor

```

```
=> Errors prevented startup:                  

   While computing assigned variables:
   /packages/zurb_foundation-sites/vendor/jquery/src/intro.js: Unexpected token
   (45:0)
   /packages/zurb_foundation-sites/vendor/jquery/src/outro.js: Unexpected token
   (2:0)

=> Your application has errors. Waiting for file change.
```

Perhaps also worth noting, the build process for web.browser is incredibly slow now, taking up to one minute, where before it was just a few seconds.

**Comment by kevster** [comment]
Workaround seems to be downgrading to Meteor 1.3.2:

`meteor update --release 1.3.2` (downgrades at app-level, not system-level)

**Comment by merlinpatt** [comment]
Also getting this issue with 1.3.4.1.

I tried downgrading Foundation first and was able to get it working with 6.1.2. Once it hits 6.2.0, it breaks again.

**Comment by lerayj** [comment]
@merlinpatt How did you manage to downgrade only foundation? I cannot figure out; what I've tried so far:

```
meteor remove zurb:foundation-sites
meteor add zurb:foundation-sites@6.2.0
```

=>Still 6.2.3 when executing meteor list (and still the same error than @kevster  btw)

`meteor add zurb:foundation-sites@6.2.0`

=> Same doesn't fix the version...

**Comment by summanerd** [comment]
I downgraded meteor to 1.3.2.4 to get around this issue. jQuery 1.11.9 seems to be the issue and a few of the packages in meteor rely on it in version 1.3.3.1.

**Comment by benlime** [comment]
@lerayj try adding this to your packages file:

`zurb:foundation-sites@=6.1.2`

it seems that you are missing the 'equal' sign. :)

**Comment by summanerd** [comment]
@lucidmachine. that worked for me. I'm using meteor 1.4.0.1, zurb:foundation-sites@6.1.2. I will note that I also did a direct installation of fourseven:scss 3.8.1, not sure if that mattered.

**Comment by benlime** [comment]
I moved to the npm version of foundation. Works without any problems. Actually I'm not quite seeing the benefit of using the atmosphere package if there is a proper working version in npm.

**Comment by lerayj** [comment]
@benlime I gonna try that too, npm over Amosphere is pretty obvious now.

**Comment by julian-rare** [comment]
same issue, will drop zurb from my project and use one more reliable

**Comment by brettsmason** [comment]
I'm going to go ahead and close this as its quite an old issue and some users identified a workaround.
