### ISSUE TITLE
Cannot install foundation project using the zurb template?

### ISSUE THREAD

**Issue by jaypii** [zurb/foundation-sites#8934]
**How can we reproduce this bug?**

1. Joerg-Polzins-iMac:web jpadm$ foundation new --framework sites --template zurb
? What's the project called? (no spaces) zurb_test

Creation of a project using zurb template. It functions with the standard project

Errors I don't understand fully
            .
           /|     ,
      , /|/  \/| /|       Thanks for using ZURB Foundation for Sites!
     /|/       |/ |       -------------------------------------------
 |___|            |___|   Let's set up a new project.
 \___|  ^^   ^^   |___/   It shouldn't take more than a minute.
     | -[O]--[O]- |
     |    ___,    |
     |    ...     |
      \__________/

Downloading the project template...
Done downloading!

Installing dependencies...

npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-15c23bd3: Cloning into bare repository '/Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-15c23bd3'...
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-15c23bd3: Permission denied (publickey).
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-15c23bd3: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-15c23bd3: 
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-15c23bd3: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-15c23bd3: and the repository exists.

There were some problems during the installation.

 ✓ New project folder created.
 ✗ Node modules not installed. Try running npm install manually.
 ✓ Bower components installed.
 I tried to install npm manually in the project directory.

Joerg-Polzins-iMac:zurb_test jpadm$ npm install

pm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: Cloning into bare repository '/Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb'...
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: Permission denied (publickey).
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: 
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb: and the repository exists.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/jpadm/.npm/_git-remotes/_templates --mirror git@github.com:gulpjs/gulp-cli.git /Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb
npm ERR! Cloning into bare repository '/Users/jpadm/.npm/_git-remotes/git-github-com-gulpjs-gulp-cli-git-4-0-799725fb'...
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Projects430/Development/web/zurb_test/npm-debug.log
**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by passtet** [comment]
+1

**Comment by passtet** [comment]
Removing grunt-cli version from npm config fixes the issue. Packjage json should have grunt-cli line like this:
{
  ...
  "devDependencies": {
    ...
    "gulp-cli": "gulpjs/gulp-cli",
    ...
  },
...
}

**Comment by Myriade** [comment]
Thank you @passtet . I had that same issue and the solution works.  But I think you meant to write _gulp-cli_ in your sentence, instead of _grunt-cli_.

**Comment by jaypii** [comment]
Thank you @passtet.
Now i Could install zurb template in a project.
