### ISSUE TITLE
Font-size accordion item title should not be set to arbitrary font-size

### ISSUE THREAD

**Issue by michaud** [zurb/foundation-sites#8935]
**How can we reproduce this bug?**

in the @mixin accordion-title

`font-size: rem-calc(12);`

**What did you expect to happen?**

The font-size should reference the global style and should be customizable

**What happened instead?**

the font-size is set to an arbitrary size: `font-size: rem-calc(12);`

**Comment by andycochran** [comment]
We'll need a new `_settings.scss` variable for `$accordion-title-font-size`. So this'll have to target v6.3.
