### ISSUE TITLE
Foundation.min.css is not valid when running through W3C CSS validator

### ISSUE THREAD

**Issue by BryanBarrera** [zurb/foundation-sites#8936]
I ran the foundation css library through the W3C CSS Validator and about 13 Errors displayed for me.. Some I can understand why they're errors but some for example is just broken syntax in the library.

The file I used to validate - [link](https://raw.githubusercontent.com/zurb/foundation-sites/develop/dist/foundation.min.css)

Attached is a screenshot of error's I received.

The print.scss file is where its producing error's. Any way to clean these up for the next release?

![screen shot 2016-06-15 at 4 59 46 pm](https://cloud.githubusercontent.com/assets/555895/16097238/d472cc5c-331a-11e6-9abe-ca430f740061.png)

**Comment by metaloha** [comment]
This is typical for all-in-one frameworks. I believe that all of these errors refer to values that only exist or work in certain browsers and aren't part of the standard.

For example, the `optimizeLegibility` value is supported by Webkit (Safari, Chrome) and Gecko (Firefox) browsers, but not IE or Edge, and isn't part of the CSS standard. It may eventually be made a standard value, but currently throws an error in the validator.

The CSS is in no way incorrect or compromised in these cases, the team is simply using features that are commonly available (85% of users will probably benefit from `optimizeLegibility` - http://caniuse.com/#search=optimizeLegibility).

**Comment by kball** [comment]
Closing based on the comment by @metaloha.
