### ISSUE TITLE
Update DropDown Docs for disabling hover

### ISSUE THREAD

**Issue by aviemet** [zurb/foundation-sites#8946]
I added the `data-disable-hover` attribute to my dropdown, which works as explained. However there are no instructions in the docs as to how to trigger an open event on the dropdown.

Could those methods please be added to the documentation? 

On a side note, and I apologize for the whining nature of my comments to follow, can the full list of methods and options available for a component be added to every page of the docs? I find that I have to delve into source more often than not in order to understand how to use this framework. To me, the point of choosing a front end framework is so I don't have to spend time on these things and can instead focus on business logic. It's frustrating to have to spend time making things work as expected when the information isn't readily available in the docs.

**Comment by dantahoua** [comment]
I follow here also... Sometimes a lot of time is wasted to search through the code file... Maybe juste a list of all the methods would be great! :)

**Comment by andycochran** [comment]
[Dropdown](http://foundation.zurb.com/sites/docs/dropdown.html) does not use `data-disable-hover`. Do you mean [Tooltips](http://foundation.zurb.com/sites/docs/tooltip.html)?

**Comment by claytron5000** [comment]
@andycochran it might be a reference to the Dropdown Menu, which does use `data-disable-hover`

**Comment by DanielRuf** [comment]
You should set `data-click-open="true"`. Without this you can just use `focus` and `space` key or `return` key to open it.

https://codepen.io/DanielRuf/pen/OvPYoZ

**Comment by DanielRuf** [comment]
@JeremyEnglert should we mention this in the docs that one of both is at least neededto get a working dropdown menu?

**Comment by DanielRuf** [comment]
@ncoden how should we further progress with this?

**Comment by dirkhacker** [comment]
It would be quite helpful if data-click-open="true" was part of the Dropdown menu documentation.

**Comment by DanielRuf** [comment]
This is probably a different issue. Please open a new one.
