### ISSUE TITLE
F6.2.3 - Drilldown / Position / Reset? 

### ISSUE THREAD

**Issue by jinch** [zurb/foundation-sites#8950]
Ok, so I came across a number of problems related to the F6 Drilldown menu. Attached is a codepen demonstrating some of the issues (http://codepen.io/jinch/pen/qNavpX). If you click around you should see what I'm referring to.

**ISSUE 1**
**If you open an off-canvas element with an embedded drill-down menu...**
a) proceed to scroll down within the off canvas window...
b) close the off-canvas window...
c) than re-open the off-canvas window again...
you are left at the original position of the menu that it was closed at. Meaning, it does not properly reset to the start of the menu. Ideally it would be better to reset the menu to appear the same as it is first opened. _*Apparently this was working with version 6.0.5 so something must have shifted with the latest release of 6.2.3_

**ISSUE 2**
**If you scroll down an off canvas element (or) click an embeded drill-down menu....**
The scroll position does not change. Meaning, it retains the scroll position of the parent and does not reset to the top of the next menu. **_The one exception is on the intial visit - unfortunately after a second visit, this no longer functions properly and this throws off the position of the second drill-down._**

**ISSUE 3**
**The height of a drill-down menu is not proportionally adjusted…**
Instead the height is fixed to the largest size menu, even if that menu is a child of the parent and not visible. This creates awkward white space and throws off the position of any element beneath the drill-down menu. Ideally it would be better to have this auto adjusted to the size of the visible menu.

Please see these examples here demonstrating the above:
http://codepen.io/jinch/pen/qNavpX

If anyone has insight or work around, please post. The off the shelf Drilldown has some noticeable UI bugs that I hope this can be addressed.

**Comment by kball** [comment]
Issues 2 and 3 have been addressed in version 6.3, and Issue 1 sounds to me like it is not necessarily an actual bug - the offcanvas component and the drilldown component are independent, closing and opening the off canvas should not impact the drilldown.  If you want the drilldown to reset on close, you can use javascript to listen for the offcanvas close event (`closed.zf.offcanvas`) and then reset the drilldown using `Foundation.reInit`
