### ISSUE TITLE
Equalizer depends on timerAndImageLoader if images are included

### ISSUE THREAD

**Issue by feeekkk** [zurb/foundation-sites#8951]
The docs essentially state that equalizer can be used out of the box with just `foundation.equalizer.js` and `foundation.core.js` loaded. However, `foundation.util.timerAndImageLoader.js` is also needed if there are images within the equalizer.

If there are images within the elements to be equalilzed, foundation equalizer `_init` calls `Foundation.onImagesLoaded(imgs, this._reflow.bind(this));` which will not exist if `foundation.util.timerAndImageLoader.js` is not included also.

**How can we reproduce this bug?**

1. Load `foundation.equalizer.js` and `foundation.core.js`
2. initialize equalizer on elements with nested images
3. reInit equalizer after the image have loaded

**What did you expect to happen?**
The divs would be equalized

**What happened instead?**
`foundation.core.js:126 TypeError: Foundation.onImagesLoaded is not a function(…)`

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.
http://codepen.io/anon/pen/GqNJGm?editors=1111

**Comment by abdullahsalem** [comment]
Fixed #8974.
Thanks, @feeekkk!
