### ISSUE TITLE
listbox rtl problem 

### ISSUE THREAD

**Issue by hamzehparsi** [zurb/foundation-sites#8954]
hi
preview this problem
![screen shot 2016-06-22 at 10 19 28](https://cloud.githubusercontent.com/assets/13706093/16255954/a45a682e-3863-11e6-913c-28dc854e8eea.jpg)

**Comment by abdullahsalem** [comment]
Hi @hakanensari,
Could you please help me to know:
- Foundation version
- Device
By the way, that pop-up menu (select element) is natively positioned by the browser, therefore Foundation doesn't affect that positioning anyway.

**Comment by JeremyEnglert** [comment]
No response. Closing.

**Comment by IamManchanda** [comment]
Hi @hamzehparsi we are awaiting your reply if you want this thread to be reopened
Does this issue still exists??
