### ISSUE TITLE
Foundation 6 Orbit carousel shrinking in Chrome after page refresh

### ISSUE THREAD

**Issue by rita-patel** [zurb/foundation-sites#8955]
Hi

I am using Foundation 6 starter project to create carousel using Orbit. I have realised that on page refresh in chrome the carousel squeezes. I checked if the same is happening on the example given on Foundation Zurb (http://foundation.zurb.com/sites/docs/orbit.html) and the same happens on there too. 

So if you go to http://foundation.zurb.com/sites/docs/orbit.html where the Orbit example is
Once page is loaded in Chrome refresh page using F5 and the carousel shrinks most of the time.
I was told this is happening on Android however it is happening on Desktop too after refreshing page.

Is this a known bug and is there a fix for this please?

**Comment by sharkyl** [comment]
I'm having the same issue. Anyone have a fix?

**Comment by timdj** [comment]
Same problem here. Seems to have to do with cache. When images are loaded from cache it sometimes miscalculates the height. If I have dev-tools open it works fine.

**Comment by timdj** [comment]
#https://github.com/zurb/foundation-sites/pull/8478

**Comment by kball** [comment]
Should be fixed by #9272
