### ISSUE TITLE
Combined Column/Row  is missing for Flex Grid (mixin as well)

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#8958]
The Float Grid has a .column.row mixin: 
http://foundation.zurb.com/sites/docs/grid.html#grid-column-row
Great! 

But the Flex Grid doesn't. 
http://foundation.zurb.com/sites/docs/flex-grid.html#sass-mixins
Not so great :( 

Or am I missing something? Cheers!

**Comment by AdamBarnwell** [comment]
`flex-grid-row()` is the flex equivalent of `grid-column-row()`.

On a related note, congrats on moving over to flex grid. You won't look back! :-)

**Comment by phifa** [comment]
@AdamBarnwell 
For sure! It is amazing! 
OK, then maybe this should be noted in the docs. So `flex-grid-row()` is used for normal row functionality AND columnrow functionality? Interesting!

**Comment by AdamBarnwell** [comment]
👍 

Basic flex grid row and column should look something like this in your SASS:
```
.row {
    @include flex-grid-row();
}

.row__column {
    @include flex-grid-column();
}
```
You shouldn't need anything else, unless you want to use some of the alignment mixins. In which case you would use `flex-grid-row-align()` or `flex-grid-column-align()`. And that's your lot.

**Comment by phifa** [comment]
No, I think you are misunderstanding me. I just tried it. I am talking about a column-row. 
http://foundation.zurb.com/sites/docs/grid.html#grid-column-row 
`Creates a grid column row. This is the equivalent of adding .row and .column to the same element.`

I am not talking about two divs (.row > .column). I am talking about: 
http://foundation.zurb.com/sites/docs/grid.html#combined-column-row 
```
<div class="column row">
  Row column
</div>
```

**Comment by AdamBarnwell** [comment]
Ah I'm with you now! I'm surprised it works out of the box with the two classes to be honest.

Silly question; Have you tried adding `flex-grid-row()` and `flex-grid-column()` to the same div?

I'm going to tinker and see what's up...

**Comment by phifa** [comment]
Tried it. It sort of worked. Not really though. I think paddings were messed up

**Comment by andycochran** [comment]
I'd love to see a PR for this, y'all. If you need a hand let me know and I'll pitch in.

**Comment by phifa** [comment]
We need a hand :+1: @andycochran

**Comment by AdamBarnwell** [comment]
So, I've been using flex row and col mixins on the same element on a
project recently and it seems to work without any problems.

I will see about getting some tests done and probably abstracting it away
to it's own mixin like the float grid.

**Comment by phifa** [comment]
@AdamBarnwell you got an update on this?  i am still facing problems when combining the mixins. Would be great to hav a PR!

**Comment by AdamBarnwell** [comment]
@andycochran @phifa Just come off an advanced training course with the guys from ZURB and it's something they are actively working on. I will continue to have a play but hopefully more on this soon!

**Comment by Yanchek99** [comment]
Just noticed the same issue documented here by @phifa. Just wanted to say I too would be interested in this as it does help clean up html output.

**Comment by brettsmason** [comment]
Seeing as the flex grid is now marked as legacy and XY Grid is the new default I'm going to go ahead and close this as I can't see this being added to the legacy grid.
