### ISSUE TITLE
Toggler on accordion not show

### ISSUE THREAD

**Issue by LeG3nDz** [zurb/foundation-sites#8959]
I would like use Toggler with Accordion module. But, if `[data-toggle]` is in `.accordion-item`, it's don't work because accordion-item is `display: none;`

Is this a bug or is it impossible to run both ?

**Test case:**

- Example on http://codepen.io/anon/pen/vKyvJv

**Comment by denisahac** [comment]
Instead of declaring the `display: none` directly to the element, you can use the built-in visibility class which is `.hide`. Then you use the `.hide` class as the value of the `data-toggler`, see code sample below.

```html
<div data-toggler=".hide" id="test" class="hide">Hello world !</div>
```

Hope that helps.

**Comment by LeG3nDz** [comment]
Hi @denisahac 

I've test, and it work fine.

But if i add `data-closable` for close Toggler with button, it adds `style="display: none;"`instead of removing .hide classe.

**Comment by denisahac** [comment]
Can you try the code sample below, I think that is something you'd like to accomplish.

```html
<div data-toggler=".hide" id="test" class="hide callout" data-closable="hide">
  Hello world !
  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>
```

Adding the `.hide` class as the value of **data-closable** makes the desired functionality works.

**Comment by LeG3nDz** [comment]
Work nice !

I was try with `data-closable="**.**hide"` when i've test :)

Thank for your help @denisahac

**Comment by denisahac** [comment]
@LeG3nDz You're welcome. I think you should close this issue now. You can still re-open it if you're having issues in the future.

**Comment by andycochran** [comment]
Good solution, @denisahac. I assume this is resolved, so I'm gonna close this issue.
