### ISSUE TITLE
Tooltip steals click event from a href

### ISSUE THREAD

**Issue by COLABORATI** [zurb/foundation-sites#8961]
I have an image inside an ```a href``` that should show some nicely styled tooltip - when I apply the F6 tooltip, the tooltip works fine, but it _steals_ the click event when the user is clicking on the tooltip, so it looks like the image ```a href``` does not work. 

Please imagine a little site with an image that shows a (big) tooltip when hovered (to have good readable metadata for the image visible on hover). The image itself, when clicked, normally will open a gallery link. That will not work anymore, if the tooltip is visible and the user clicks _inside the tooltip area_, what is still _inside the image_  - for a user it is not understandable, why a tooltip blocks the expected click behaviour (real life experience).

I would like to classify this as a bug - the tooltip should only _show_ information, but not interfere with other functionality of the tooltip triggering element, like prevent clicks. From what I understand the tooltip [javascript](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.tooltip.js#L260) actively interrupts the click event propagation - this should be optional behaviour.

**Comment by pymoza** [comment]
Try using a <span> after the <a> instead of the tooltip on the <a> like this : 
<a href="#"><span data-tooltip aria-haspopup="true" class="has-tip"><img /></span></a>

**Comment by andycochran** [comment]
There are a couple ways you can do this, depending on the `cursor` value you want (`pointer` or `help`): 
http://codepen.io/andycochran/pen/YWQAyL
