### ISSUE TITLE
Javascript components won't work when placed inside Interchange

### ISSUE THREAD

**Issue by paper9oll** [zurb/foundation-sites#8966]
Hi Dev,

F6 Javascript components like Accordion Menu won't work when placed inside Interchange, I would work when placed outside Interchange.

**Comment by andycochran** [comment]
You'll have to [initialize](http://foundation.zurb.com/sites/docs/interchange.html#js-module) them when they load.

**Comment by paper9oll** [comment]
@andycochran sorry about that i'm not quite sure what you mean by initialising.

My app.js already imported all javascript library so does it means i have to create a new instance?

**Comment by andycochran** [comment]
So, when your app calls `$(document).foundation();` the component in Interchange don't exist yet. So they don't work. When you dynamically load responsive content, you have to initialize the components once they're in the DOM: 

```js
var elem = new Foundation.component(element, options);
```
Maybe one of the @zurb/yetinauts JS experts can explain that more clearly than I? 

@paper9oll Could you provide a Codepen that reproduces this issue? 
- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by paper9oll** [comment]
@andycochran alright i give a try.

**Comment by Owlbertz** [comment]
In addition to what @andycochran said, you might want to make use of the [interchange event](http://foundation.zurb.com/sites/docs/interchange.html#js-events) in order to dynamically initialize contents automatically. 

If you need additional feedback, please try to provide a Code Pen example as mentioned.

**Comment by paper9oll** [comment]
@Owlbertz thanks you its working now.
