### ISSUE TITLE
Question on Flexbox and aligning content within a column.

### ISSUE THREAD

**Issue by lspoor** [zurb/foundation-sites#8967]
Question on Flexbox and aligning content within a column.

This is the code I'm using. How would I then go about aligning the read more to the bottom of the column containers? (I've attached an image with the code too as the WYSIWYG editor isn't embedding my code correctly.

`<div class="row">
        <div class="what columns">
            <h3>What is a funeral plan?</h3>

            <h6>The only way to guarantee<br class="show-for-medium"> all your funeral costs are covered.</h6>

            
                <p>If you’ve ever had to arrange a funeral for a loved one, you’ll know what an emotional and distressing time it can be. Especially if you have no idea what sort of funeral event your loved one wanted.</p>

                <a href="#" class="read-more">read more</a>
            
        </div>

        <div class="why columns">
            <h3>Why pre-pay for your funeral?</h3>

            <h6>The funeral you want. <br class="show-for-mediun">Exactly how you want it.</h6>

            
                <p>A Funeral Plan from The Midcounties Co-operative provides an easy, cost effective way to organise your arrangements in advance, specify your wishes, and take care of the costs.</p>

                <a href="#" class="read-more">read more</a>
            
        </div>

        <div class="columns">

        </div>
    </div>`

![screen shot 2016-06-24 at 16 41 41](https://cloud.githubusercontent.com/assets/1685176/16342542/9d22338e-3a2a-11e6-979b-e0bd673e57ae.png)

![screen shot 2016-06-24 at 16 39 40](https://cloud.githubusercontent.com/assets/1685176/16342506/744b293e-3a2a-11e6-9060-05cb2dde62d1.png)

**Comment by AdamBarnwell** [comment]
I'm probably over complicating my answer but could you use the [Equalizer Plugin](http://foundation.zurb.com/sites/docs/equalizer.html) to force the columns to match each others height, put a bottom padding of `25px` or so on the columns and then add `position: absolute; bottom: 0;` to the links to align them to the bottom?

**Comment by lspoor** [comment]
I was hoping to hoping to make the .content block to fill the rest of the space after the title then aligning the read more to the bottom of the .content block. All using flex if possible.

**Comment by andycochran** [comment]
Like this? http://codepen.io/andycochran/pen/wWZwzV
(Can be done w/ or w/o Flex.)

**Comment by andycochran** [comment]
I'm gonna close this, as it's not really a bug. But feel free to keep chatting, I'll try to help if I can. Also a good place for how-to questions that aren't bugs is the [Forum](http://foundation.zurb.com/forum/).

**Comment by lspoor** [comment]
Thanks for that! Useful! Is it possible to use it twice within each block though? For example what I explained already works but I'd also like to put the equalizer on the light blue serif text because when moving down in responsive it screws up the layout then!
