### ISSUE TITLE
Only a portion of styles from my main SCSS stylesheet are compiling.

### ISSUE THREAD

**Issue by jarrydfillmore** [zurb/foundation-sites#8969]
**How can this bug be reproduced?**
1. See the _front.scss code
2. Only a portion of it is being compiled
3. Result? Full styles aren't being compiled and ultimately loaded

**What did you expect to happen?**
For all the styles to be loaded and my website to display properly

**What happened instead?**
Not all the styles were loaded

**Please List the Following:**
- OS & version: Mac - OS X Yosemite
- Node version (node -v) [Node v4+ is required] : v4.4.1
- Foundation version (bower list) : Not sure

**Include Test Case** (if applicable):  
Give us a link to a CodePen or JSFiddle that recreates the issue.

http://codepen.io/jdfillmore/pen/wWgyBM

**Summary**

I'm using the _front.scss file to style my site. Only some of the styles from _front.scss are being compiled out. Gulp is giving no errors when compiling.

Image of exactly what's going on:
![untitled-1](https://cloud.githubusercontent.com/assets/15603061/16357039/2e52911c-3ab9-11e6-885d-2cfac4580f28.jpg)

**Comment by AdamBarnwell** [comment]
So, I've come across a similar problem before. It didn't have anything to do with the build process as I found that outputted CSS was what I was after.

The problem was that for some reason the browser wasn't rendering it. I soon found out that my CSS file was simply to long and the browser just gave up rendering styles past a certain line. As soon as I split that file in two, it worked.

I would suggest splitting your _front.scss into two files and include them both and see if you're still getting the same issue.

I would try your CodePen but it doesn't want to play ball at all! :-(

**Comment by artursopelnik** [comment]
@AdamBarnwell Normally that is a problem for older IE's. 
Solution: http://blesscss.com/

@jarrydfillmore Can you explain what tooling are used? ~ libSass? Ruby Sass, Compass? Grunt/Gulp

**Comment by jarrydfillmore** [comment]
@AdamBarnwell I tried your solution and it actually worked! I kept the home page hero styles in _front.scss, and put the other styles in a separate .scss file and boom. But I really do wanna keep everything in one. If I can't figure it out, then I'll keep your suggestion handy.

@artursopelnik Absolutely! I'm using the default compiling tool for FoundationPress, which I believe is Gulp. No errors though, when compiling - which is strange.

**Comment by AdamBarnwell** [comment]
@artursopelnik Yeap, I've usually manually split them out but I've have a look at blesscss, thanks!

@jarrydfillmore Yeap, it's the max selector limit for whatever browser you're using (as @artursopelnik has mentioned, IE9 and below is a devil for this problem). You could try to cut down on the amount of Foundation CSS you're using by only including the elements you need. Or use http://blesscss.com/ solution or split them out which you have just done.

**Comment by andycochran** [comment]
@jarrydfillmore Is this still an issue for you?

**Comment by kball** [comment]
Closing due to lack of reply. Please reopen if you're still running into this issue.
