### ISSUE TITLE
Reveal modal with tab key and locked scroll causes UX issue

### ISSUE THREAD

**Issue by macdabby** [zurb/foundation-sites#8971]
The issue arises in the particular instance that you have an input field in a modal-reveal dialog. Pressing the tab key to move to the next field works. But from the last field in the modal, it can move to a link or field in the main page outside of the reveal modal, which can force the browser to scroll to another position in the page, where the reveal modal is no longer visible. The user can't scroll back to the modal because reveal locks the page from scrolling at all.

This might be taken into consideration when fixing another open issue about how to deal with the reveal scrolling issue on mobile safari.

**Comment by andycochran** [comment]
I tried to recreate this, but it seems to be functioning right (continuous tabbing is contained to the modal). 
http://codepen.io/andycochran/pen/vKkBLz

Is there something missing from my Codepen? Can you fork the Codepen and recreate the bug? 

Not sure which other issue you're referencing. Is this issue's bug only in mobile Safari too?

**Comment by macdabby** [comment]
I had updated most of my code to Foundation v6, but it looks like some elements are still loading from v5. Also this problem does not exist in safari, only in chrome. I am opening the modal manually via a JS call, but I'm not sure if that makes a difference. I will do some more investigation here. Closing this for now.
