### ISSUE TITLE
[Equalizer] Necessary ependencies incomplete

### ISSUE THREAD

**Issue by peterboorsma** [zurb/foundation-sites#8974]
The JavaScript Reference section on the Equalizer docs page (http://foundation.zurb.com/sites/docs/equalizer.html) says:

> The file foundation.equalizer.js must be included in your JavaScript to use this plugin, along with foundation.core.js.

But if you don't want to use the complete foundation.js and just load the core you also need foundation.util.mediaQuery.js and foundation.util.timerAndImageLoader.js to get things working.

**Comment by abdullahsalem** [comment]
Thanks, @pajaroblanco!
