### ISSUE TITLE
Problems with jQuery 3

### ISSUE THREAD

**Issue by tobias-kutter** [zurb/foundation-sites#8975]
**What happend?**
Please update the deprecated method calls.

**e.g.**
`sample.load(fn())` to `sample.on('load', fn())`

**How can we reproduce this bug?**
1. Use Foundation 5 in a project via NodeJs
--> dependency in package.json: jQuery >= 2.x.x 
----> jQuery 3.0.0 is installed (breaking changes)

**What did you expect to happen?**
Foundation should not throw any error. Please update the code so that it don't use deprecated  methods.

**What happened instead?**
Foundation throws error.

Thanks

**Comment by farkel** [comment]
This is also happening in Foundation 6.  Thanks!

**Comment by monkey-tobi** [comment]
Same thing happened to me. Update would be very nice :)

**Comment by pmaceachern** [comment]
![image](https://cloud.githubusercontent.com/assets/7061759/16621353/eba61f10-4363-11e6-83a1-a5acf971b278.png)

Further verification using https://github.com/jquery/jquery-migrate (sorry for the screen grab).

**Comment by pratikpparikh** [comment]
I am running into the same problem, does anyone from foundation team know the best way to solve this problem?

**Comment by DaSchTour** [comment]
I guess this could be solved by adding a jQuery 3 Test, collect the JQMIGRATE Warnings and migrate/change the code step by step.

**Comment by Baedda** [comment]
I got the problem with the deprecated load function in foundation.util.triggers.js, too. It would be really nice to have a fix here with the next version.
If you guys want to include a patch on your side you can change line 65 from:
`$(window).load(function () {`
to:
`$(window).on('load', function () {`
and the triggers util can be used until the fix is coming from Zurb :)

**Comment by Elephant-Vessel** [comment]
Just making some noise here. I have the same problem, inside `init` in foundation.ks:345, there is a call to .load that ends up [here](http://api.jquery.com/load/). Foundation 5.5.3, jQuery 3.1.0.

Hotfixing the file in bower_components in my project for now.

**Comment by samuelmolinski** [comment]
I am having the same issue when bootstrapping it to aurelia.  can we get these load(callback) changed to .on('load', callback)

**Comment by mbrevda** [comment]
should be fixed by https://github.com/zurb/foundation-sites/pull/8923

**Comment by Owlbertz** [comment]
@tobias-kutter can you confirm this has been fixed?

**Comment by max8hine** [comment]
it still occurs in Foundation 6 for site.

**Comment by tobias-kutter** [comment]
It's also not fixed in Foundation 5.5.3...

**Comment by Owlbertz** [comment]
@max8hine what version are you using?

**Comment by max8hine** [comment]
@Owlbertz I am using 6.2.3 i caught it from npm foundation-sites. and binding the main js file with jQuery 3 by using webpack. but i didn't do any testing on this error, but i found the error in Console  panel.

**Comment by ShaneKilkelly** [comment]
Same as @max8hine, tried to use jQuery 3.1 with Foundation (Sites) 6.2.2, which produces the following error:

<img width="526" alt="jquery_error" src="https://cloud.githubusercontent.com/assets/1540054/19447855/36b8b682-9497-11e6-88f3-6c7e4816c354.png">

**Comment by jraack** [comment]
I have the exact same problem.
Any thoughts to fix it?

**Comment by kball** [comment]
This is fixed in 6.2.4, which will be released TOMORROW. :)

**Comment by tobias-kutter** [comment]
Do you also release a fixed version for Foundation 5? We don't migrate to 6 till now...

**Comment by Baedda** [comment]
@kball is this really fixed with 6.2.4? Can´t find anything about this issue in the release notes
https://github.com/zurb/foundation-sites/releases/

**Comment by kball** [comment]
@Baedda It should be. I just update the release notes highlighting this for the PR in question that fixed it.

We decided not to change the default to jQuery 3 until the minor release, but projects using 3 should now work.

**Comment by h0r0man** [comment]
It doesn't work with the latest jQuery 3.1.1 I made [this pen](http://codepen.io/horoman/pen/pNWzMX) to prove it.

**Comment by DaSchTour** [comment]
@h0r0man you are using 6.2.3 in your pen. Changing it to 6.2.4 fixes the errors.

**Comment by memoht** [comment]
I noted that 6.3 still didn't bump to jQuery 3 yet. Was this delayed for some reason?

**Comment by DaSchTour** [comment]
@memoht I think jQuery 3 is supported, but package was not changed. But minimum version should still be jQuery 2

**Comment by user58258** [comment]
After upgrading my test project to latest jquery

    bower i --save jquery

and FS 6.3.0

    bower i --save foundation-sites

verifying

    bower list
        bower check-new     Checking for new versions of the project dependencies...
        test-site /srv/www/test
        ├── foundation-icon-fonts#afed003521
        ├─┬ foundation-sites#6.3.0
        │ ├── jquery#3.1.1 incompatible with ~2.2.0 (2.2.4 available, latest is 3.1.1)
        │ └── what-input#4.0.4
        └── jquery#3.1.1

updating the project still warns about "Code incompatibilities" re: jquery 3 "vs" FS6

    bower update
        bower not-cached    https://github.com/zurb/foundation-icon-fonts.git#*
        bower resolve       https://github.com/zurb/foundation-icon-fonts.git#*
        bower cached        https://github.com/zurb/foundation-sites.git#6.3.0
        bower validate      6.3.0 against https://github.com/zurb/foundation-sites.git#^6.3.0
        bower cached        https://github.com/jquery/jquery-dist.git#3.1.1
        bower validate      3.1.1 against https://github.com/jquery/jquery-dist.git#^3.1.1
        bower download      https://github.com/zurb/foundation-icon-fonts/archive/master.tar.gz
        bower cached        https://github.com/jquery/jquery-dist.git#2.2.4
        bower validate      2.2.4 against https://github.com/jquery/jquery-dist.git#~2.2.0
        bower cached        https://github.com/ten1seven/what-input.git#4.0.4
        bower validate      4.0.4 against https://github.com/ten1seven/what-input.git#~4.0.3
        bower extract       foundation-icon-fonts#* archive.tar.gz
        bower resolved      https://github.com/zurb/foundation-icon-fonts.git#afed003521

        Please note that,
            foundation-sites#6.3.0 depends on jquery#~2.2.0 which resolved to jquery#2.2.4
            test-site depends on jquery#^3.1.1 which resolved to jquery#3.1.1
        Resort to using jquery#^3.1.1 which resolved to jquery#3.1.1
        Code incompatibilities may occur.

What's the current 'official' stance on jQuery?
If it's 'supported', what about these errors/warnings?
If it's NOT supported, what's the target version of FS to get full support?

**Comment by memoht** [comment]
Considering 6.3 was more than a minor release, I am not comfortable implementing jQuery 3 with Foundation until it gets official support. Still, it would be nice to move forward. This is literally the only thing in my app tied to jQuery 2 still.

**Comment by user58258** [comment]
@memoht Some combination of posts, including

https://github.com/zurb/foundation-sites/issues/8834 

led me to understand that it's "Fine(tm)" to use ... and was even kinda-sorta-maybe supported.  ish.  And would be more so with FS >= v630

But since still seeing these warning/complaints, looking for some clarification.

**Comment by user58258** [comment]
@ kball @colin-marshall @Owlbertz 
ping?

**Comment by kball** [comment]
It should "Just work" - all known conflicts have been removed.  It looks like the bower.json dependency spec got missed (It's at `~2.2.0`, and should be `^2.2.0` like in package.json).  I'll submit a PR to fix.

**Comment by kball** [comment]
err, should be >= not ^

**Comment by user58258** [comment]
@kball @rafibomb 
great, thanks.
if this could get merged to _release_ tag, and updates pushed to pkg managers, it'll help with rollout -- without the need for intervention.

**Comment by atrivisano** [comment]
This is not fixed.

`$(window).on("load", function (e) {}) currently does not work with jQuery 3.2.1`

**Comment by rassom** [comment]
@kball I have a Foundation 5 project that's very hard to move to Foundation 6 and latest jQuery 2 (v2.2.4) has security issues. 

You basically just have to replace:
`$(window).load(function() { ... });` 
with
`$(window).on('load', function() { ... });`

Could you release af version of Foundation 5 with the fix, please?
