### ISSUE TITLE
Native textarea resize handle rendering [Firefox Linux]

### ISSUE THREAD

**Issue by iamdey** [zurb/foundation-sites#8976]
**How can we reproduce this bug?**
1. Run a foundation website (eg. http://foundation.zurb.com/sites/docs/forms.html) on Linux Firefox based browser
2. change background-color of a textarea

**What did you expect to happen?**

It should render a native resize handle (and transparent)

**What happened instead?**

Resize handle is not expected (and ugly)

**Test case:**

Here's some screenshots for evidences:
1. Debian 8 iceweasel
   ![debian8-iceweasel_38 8](https://cloud.githubusercontent.com/assets/65737/16384264/8a7a83ac-3c88-11e6-8ae5-9c249efc6172.png)
   ![debian8-iceweasel_38 8-hover](https://cloud.githubusercontent.com/assets/65737/16384265/8a7ade60-3c88-11e6-9d56-5857a3a3f037.png)
2. Debian 8 FF dev ed.
   ![debian8-ff_dev_ed-49 0a2](https://cloud.githubusercontent.com/assets/65737/16384276/91dee0b6-3c88-11e6-8791-f1ee33195fd2.png)
3. Debian 8 FF dev ed. without -moz-appearence
   ![debian8-ff_dev_ed-default-appearence](https://cloud.githubusercontent.com/assets/65737/16384281/96be123c-3c88-11e6-8b56-debc63dbe7f7.png)

In the last example without `-moz-appeareence` property, we can see it works as expected. 

So my question is in what the property `-moz-appeareence` is usefull for ? Can we remove it ?

**Comment by jarrydfillmore** [comment]
=!

**Comment by DanielRuf** [comment]
This is the current state in Firefox 57
![image](https://user-images.githubusercontent.com/827205/36395843-877a751e-15bb-11e8-87e9-71ecd468cf04.png)

https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance

> In older browsers, even the keyword none does not have the same effect on all form elements across different browsers, and some do not support it at all. The differences are smaller in the newest browsers.

> none |   | No special styling is applied. This is the default.

**Comment by DanielRuf** [comment]
I guess this issue is obsolete now after almost two years as we also explicitely support the last two versions of Firefox according to https://foundation.zurb.com/sites/docs/compatibility.html.
