### ISSUE TITLE
[Tooltips] Typo in documentaion

### ISSUE THREAD

**Issue by RLaptev** [zurb/foundation-sites#8981]
**How can we reproduce this bug?**

Access http://foundation.zurb.com/sites/docs/tooltip.html

**What did you expect to happen?**

Events section should read:
tooltip.zf.tooltip, show.zf.tooltip, hide.zf.tooltip

**What happened instead?**
It reads:
tooltip.zf.tooltip**s**, show.zf.tooltip**s**, hide.zf.tooltip**s**

The word tooltips is plural instead of being singular.

**Comment by abdullahsalem** [comment]
Thanks, @RLaptev!
