### ISSUE TITLE
Custom transition breaks drill down menu

### ISSUE THREAD

**Issue by chanwhab** [zurb/foundation-sites#8985]
Thanks for effort first. While battling FOUC, some irrelevant transition breaks drilldown menu

**How can we reproduce this bug?**
1. Have a drilldown menu set.
2. Set up text transition effect (see codepen CSS, simplified)
3. Click menu item multiple times.
P.S. Comment  {transition: opacity .3s ease} to see drilldown menu works normally.

**What did you expect to happen?**
Open and close drilldown menu with menu transition.

**What happened instead?**
No transition. No response after opened once.

**Codepen**
-[Codepen with Foundation 6](http://codepen.io/idolab/pen/vKmNZK)

**Comment by proov** [comment]
I have this issue too on F6.2.3, whatever transition i choose, full `transition` shorthand property or  `transition-timing-function`. However, it breaks only the "go back" transition.

**Comment by DanielRuf** [comment]
In general you have to extend the `transition` property to include the other transitioned properties too. Your custom transition replaces the used transition.

I'm not yet sure if we have a Scss variable for this or if you have to copy paste it.

**Comment by DanielRuf** [comment]
`drilldown-transition` has to be merged with your custom transition.

https://github.com/zurb/foundation-sites/blob/develop/scss/components/_drilldown.scss

**Comment by DanielRuf** [comment]
What do you think about this @SassNinja?

**Comment by SassNinja** [comment]
@DanielRuf I agree, a transform transition has to be merged with the opacity transition to fix the issue.
But I think this should rather be done manually instead of automatic.

@chanwhab you don't want to avoid the transform transition completely, do you?

**Comment by DanielRuf** [comment]
Hi @chanwhab and @proov, is so far clear that transitions have to be merged like other CSS values and is this a viable solution? You can also change `drilldown-transition` to your needs.

**Comment by proov** [comment]
Hi Guys, sorry for the delay. yes the back transition works like a charm. But i tested a recent site i'm working on. The normal transition doesnt work on Safari (Desktop or iOS Safari), you can check the doc on Safari : https://foundation.zurb.com/sites/docs/drilldown-menu.html. You will see the problem. I really dont understand why, i've spent 2 hours to try to find a fix... By the way, the `.active` transform should be translateX(0%) and not 100% (since we already have a left: 100%) 😉

**Comment by proov** [comment]
I found a temporary workaround, it works with `left` (I don't like transitioning other properties than transform and opacity)

```scss
.drilldown .is-drilldown-submenu {
    transition: left 0.5s ease(out-expo);
    background-color: #fff;
    transform: none !important; // Reset transforms

    &.is-active {
      left: 0%;
    }

    &.is-active.is-closing {
      left: 100%;
    }
  }
```

If somebody know why it works with `left` and not `translateX`, i would be very happy :D

**Comment by DanielRuf** [comment]
Hi @proov,

Is this a separate issue?
If so please create a new issue.

Closing this one as the transition can be extended if needed.
