### ISSUE TITLE
Flex grid column alignment classes missing breakpoints

### ISSUE THREAD

**Issue by markv** [zurb/foundation-sites#8989]
Flex grid gives us classes to align columns globally but not responsively.
http://foundation.zurb.com/sites/docs/flex-grid.html#column-alignment

**How can we reproduce this bug?**
Add a breakpoint size to an alignment class eg. `.large-align-center` on a row div

**What did you expect to happen?**
Only apply align-center at large breakpoint and up

**What happened instead?**
Nothing

**Test case:**
http://codepen.io/anon/pen/jAmYwR

**Comment by JBroox** [comment]
Hey @markv, im newer to commenting on these issues and I wanted to see if you found a solution to your problem. Im working on a class based solution, but wanted to see if you thought about the offset column classes. In your example above, I used this code to achieve what you wanted to accomplish:

`<div class="row">
  <div class="column small-4 large-offset-2">Aligned to</div>
  <div class="column small-4">the middle</div>
</div>`

I will keep working on a possible solution as to exactly how you asked the question. Just wanted to provide an alternate route.

**Comment by markv** [comment]
That is a good solution @JBroox.

The problem was that I've built a site framework around foundation 5 so I didn't want to modify every occurrence of the existing classes. It also makes templating harder because you need to calculate the offset for centered divs.

I ended up adding a sass loop to add back in the old functionality.

```
//grid alignment compatibility for foundation 6

@include -zf-each-breakpoint {
  .#{$-zf-size}-centered {
    margin-left: auto;
    margin-right: auto;
  }
}
```

The other issue was that foundation 6 also changed the class naming from `.[breakpoint]-centered` to
`.[breakpoint]-align-center` so the above code uses the old class names as well

**Comment by andycochran** [comment]
I think this issue may be out of date. Columns do accept `.[breakpoint]-align-center`. [This code](https://github.com/zurb/foundation-sites/blob/develop/scss/grid/_classes.scss#L144) does the same thing as your custom loop.
