### ISSUE TITLE
Expanded dropdown  menu caret positioning is too far from menu title text

### ISSUE THREAD

**Issue by gremmie** [zurb/foundation-sites#8994]
**How can we reproduce this bug?**
1. Create a top bar that has dropdown menus with the class `expanded`

**What did you expect to happen?**

The dropdown carets stay close to the menu title text.

**What happened instead?**

The carets get put to the far right of the menu title text; so much that they don't really look like dropdowns anymore. 

Image: https://dl.dropboxusercontent.com/u/15514715/Selection_007.png

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.
- http://codepen.io/anon/pen/xOAwwQ

I'm not exactly sure but maybe a separate div can be created around just the menu link text, and the "after" pseudo element for the caret can be hung on that div instead of on the outer container that gets stretched when `expanded` is applied.

**Comment by jarrydfillmore** [comment]
Interesting

**Comment by andycochran** [comment]
Hmm. I'm having a hard time visualizing what a fix this *should* look like. I'm not sure it's a bug; it might be an edge case where, design-wise, `.expanded` just doesn't work well with `.dropdown.menu`. I don't think keeping the triangles next to the text would make an expanded dropdown menu any less awkward; there'd still be the clickable (yet visually empty) space to the right of each triangle. Maybe this should instead be three dropdown menus in separate columns?

**Comment by gremmie** [comment]
I'm not a designer, but I don't think its too much of a stretch to imagine that only the text and maybe the caret are made clickable. I don't know much about Foundation internals, but it sounds like that would mean special case code for dropdowns?

If you have a work around that would work in the context of the top bar I would love to see it. As it is, many of my users have complained about it, and I'll likely turn off expanded and replace it with centered or something. I don't think this looks as good though.

As an aside, I got the idea for using `expanded` from the foundations template site. However the working example there is so very different from what is displayed in the docs I can only imagine it is some kind of bug or configuration issue? 

http://foundation.zurb.com/templates-previews-sites-f6/news-magazine.html

![image](https://dl.dropboxusercontent.com/u/15514715/zurb-template-news-menu.png)

**Comment by kball** [comment]
Not sure what to do with this one... @andycochran @brettsmason @ncoden @rafibomb do ya'all have thoughts?

**Comment by andycochran** [comment]
Still think this is probably an edge case. But maybe this can be address more easily after v6.4's menu refactor.

**Comment by brettsmason** [comment]
I'm going to go ahead and agree with Andy on this one - I think its an edge case and not something that's easily fixed. I will mark this as something to be considered for V7 though to see if it can be addressed.
