### ISSUE TITLE
[Foundation for Sites] Wont work with Angular 2 rc4

### ISSUE THREAD

**Issue by findjonmos** [zurb/foundation-sites#8995]
**How can we reproduce this bug?**

1) Paste following code into the index.html of an Angular 2 application just before closing body tag

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/foundation/6.2.1/foundation.js"></script>
    <script>
      $(document).foundation();
    </script>

2) create a component that loads the top nav html of foundation 6

3) run the site and notice that whilst the styling is applied the javascript does not work

**What did you expect to happen?**
I expected the dropdown nav to have hidden items that would only appear on hover 

**What happened instead?**
- instead the nav is open as if the js for its behaviour was never applied.

**Comment by findjonmos** [comment]
So I found some info that refers to Foundation 5 but I guess will be relevant for for Foundation 6.

https://github.com/zurb/foundation-sites/issues/4057

Can I ask that if the issues related to the link above are still relevant to Foundation 6 that using delegation be considered unless there is some other fancy method in the pipe line.

Angular 2 is probably going to be massive - and I would much rather use Foundation rather than Bootstrap...but I really don't like the idea that you would have to hack away at Foundation just to ensure that dynamic elements would work.

I was half way through building a nav in Angular 2 with Bootstrap as a test and dropped Bootstrap when I noticed the nav could only be activated on click...I was like sod you Bootstrap I will use my trusty friend Foundation and was excited to use version 6. Then I discovered that to use anything dynamic in Foundation within Angular 2 is just not going to work due to the fact it is a SPA app.

Has everyone really had to hack Foundation for older Angular just so it can be used with SPA apps????

**Comment by Owlbertz** [comment]
Hi, it would be great if you could create a code pen with that issue so we can dig into it more easily:
- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by DaSchTour** [comment]
Is this a RC4 issue? Did it work with an older version of Angular 2?
Is the HTML you have used Foundation Components in present on Document load or is it a component loaded by Angular?
If it's loaded/inserted by Angular you need to init foundation inside the component and not globally. I guess what you are trying now is attaching Foundation to element that are not present at the time you initialize them.

**Comment by findjonmos** [comment]
Thanks DaSchTour I only mentioned rc4 to inform people of the versions I was using just as an fyi.

I went with a lifecycle hook in the end on the actual nav component which seems to have worked. Even though it works it seems annoying that you would have to litter various components with the .foundation() command.

I tried making a component that could be used on its own just to init foundation so that you could import it into any other component you wanted...that way if the implementation of .foundation() changed or needed to be updated for some reason you would not have to look through possibly hundreds of components but this doesn't seem to work. I was using the ngAfterContentInit() but still the order the components are loaded must be stopping this global component from working :(

Any how...still got it working with the below code...just means I have to run the below ngAfterViewInit()


```
export class MainNavComponent implements OnInit {

    constructor(private el: ElementRef) { }

    ngAfterViewInit() {
        $(this.el.nativeElement.ownerDocument).foundation();
    }

}
```

**Comment by DaSchTour** [comment]
Well. That's why everybody is waiting for Foundations Apps 2 or something similar, that implements angular directives for Foundations JavaScript components and eliminates the need of jQuery ;)

**Comment by findjonmos** [comment]
Ah thats interesting...I didnt know that. Thanks for the info I will look into Foundation Apps 2

**Comment by jarrydfillmore** [comment]
Interesting..

**Comment by Owlbertz** [comment]
@findjonmos, as @DaSchTour stated this has to do with the fact that the JavaScript can only be applied to elements that are already in the DOM. I am glad you found a way to ensure that the JavaScript is initialized automatically. (On a side note: your way of initializing only the elements that have changed might show better performance than the one @DaSchTour suggested.)

I will close this issue as a solution has been found
