### ISSUE TITLE
Missing selector: .accordion-title

### ISSUE THREAD

**Issue by rgb4u** [zurb/foundation-sites#8998]
After compilation sass to css i don't get selector class:
 .accordion-title

My output :

/\* missing selector here */:last-child:not(.is-active) > .accordion-title {
  border-radius: 0 0 0 0;
  border-bottom: 1px solid #e6e6e6;
}

It will be propobly this mixin:

components > @mixin accordion-title {...}

**Comment by jarrydfillmore** [comment]
+1!

**Comment by mattferderer** [comment]
This is working for me. What version are you on? Are you including the foundation-accordion like this? @include foundation-accordion;

**Comment by kball** [comment]
I'm seeing this in current dist files and builds, so closing this... please chime in if you're still having a problem.
