### ISSUE TITLE
Missing var in slider.js

### ISSUE THREAD

**Issue by rgb4u** [zurb/foundation-sites#9004]
Hi everyone, I'm using gulp-include to include all js plugins in order
My code editor shows me errror in:
foundation.slider.js
// Line: 331:
offsetPct = percent(barXY, barDim);
After changing  to:
var offsetPct = percent(barXY, barDim);
Error dissapear, even without fixing, my js compilation works fine
Nothing to worry, just a cosmetic change...

**Comment by jarrydfillmore** [comment]
Interesting..

**Comment by Owlbertz** [comment]
Seems to be already addressed in #9006.
