### ISSUE TITLE
Reveal appear without content (white) foundation-sites 6.2.3 on Firefox mobile Android

### ISSUE THREAD

**Issue by reeslo** [zurb/foundation-sites#9005]
I am curently working on new website, I can drop url and access on private message.

The issue are only on Firefox mobile lastest version running on Android 6.
When I switch portrait/landscape reveal content appear and is normal.
I fire whith a <button> element

```html
<button class="button" data-open="modal-footer" data-object="Some text">
    text
</button>
```

I use and include all foundation-site  6.2.3 component installed with bower compiling with gulp-sass
I include also motion-ui 1.2.2 with bower compiling with gulp-sass

```javascript
var gulp             = require("gulp"),
    sass             = require("gulp-sass"),
    uglify           = require("gulp-uglify"),
    rename           = require("gulp-rename"),
    concat           = require("gulp-concat"),
    jshint           = require("gulp-jshint"),
    notify           = require("gulp-notify"),
    plumber          = require("gulp-plumber"),
    order            = require("gulp-order"),
    path             = require("path"),
    gutil            = require("gulp-util"),
    autoprefixer     = require('gulp-autoprefixer'),
    csso             = require('gulp-csso'),
    stripCssComments = require('gulp-strip-css-comments');

gulp.task("styles", function () {
    return gulp.src(["/src/scss/**/*.scss"])
            .pipe(plumber(plumberErrorHandler))
            .pipe(sass({
                relative_assets: true,
                includePaths: [
                    "bower_components/foundation-sites/scss",
                    "bower_components/motion-ui/src"
                ]
            }))
            .pipe(autoprefixer({
                browsers: ['last 2 versions', 'ie >= 9', 'and_chr >= 2.3'],
                cascade: false
            }))
            .pipe(gulp.dest("/assets/css"))
            .pipe(stripCssComments({preserve: false}))
            .pipe(csso())
            .pipe(gulp.dest("/assets/css"));
});
```

I use flexbox-grid

**Comment by abdullahsalem** [comment]
Hi @reeslo,
I'm glad to hear that you are using Foundation to build your new website, and I hope you like it.
I noticed that there is something needs to be fixed in Autoprefixer's configurations, so try to change:
`'and_chr >= 2.3'` to `'Android >= 2.3'`
Let me know if that will work for you, please.

**Comment by jarrydfillmore** [comment]
+1!

**Comment by reeslo** [comment]
Sorry @abdullahsalem I think comeback quickly at work, was for that I dont reply...
I comeback 25 july I check this and I feedback quickly :)

**Comment by abdullahsalem** [comment]
Don't worry @reeslo ,
I hope it works well now?

**Comment by reeslo** [comment]
Hi @abdullahsalem I tell you monday, I am on holiday :)

**Comment by reeslo** [comment]
Hello @abdullahsalem, I changed  `browsers: ['> 0%']` all moz- prefixes are present but no change  :(

**Comment by reeslo** [comment]
@abdullahsalem any news ? :(

**Comment by abdullahsalem** [comment]
Hi @reeslo,
Could you please explain the issue in details and its relation with Foundation?
And by the way, if you are facing any issue that isn't directly relevant to Foundation, try to check out that component's website or documentation to figure out how it should work.
If you only have a problem with `gulp-autoprefixer` look at this page of its options: https://github.com/postcss/autoprefixer#options

**Comment by reeslo** [comment]
you can close this ticket think was an firefox issue it work correcly now. thx
