### ISSUE TITLE
[Installation] gulp-imagemin installs node_modules folders recursively ad infinitum

### ISSUE THREAD

**Issue by vanadu** [zurb/foundation-sites#9012]
1. Install Zurb template as per http://foundation.zurb.com/sites/docs/installation.html
2. Open any subfolder of node_modules/gulp-imagemin. You will find a node_modules folder there.
3. Drill down in the folder structure and try to get to the terminating folder. The folder structure has no end. Example: C:\CORA\vanocular\httpdocs\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\node_modules\logalot\node_modules\squeak\node_modules\lpad-align\node_modules\meow\node_modules

This a huge problem on Windows because of the filename length limit. Long filenames can't be deleted in the file manager. They can be deleted using rimraf but this is completely unnecessary and not documented. This cost me an hour trying to figure out how to simply delete a Foundation installation, needs to be fixed.

**Comment by Owlbertz** [comment]
Hi @vanadu,
this is not an issue with Foundation, it is related how dependency management in NPM 2 works.
Maybe you can have a look at NPM 3, which allows you flat dependency management and therefore should not cause these problems.

**Comment by kball** [comment]
I agree with the response above; this is not a foundation issue but a result of NPM being a clusterF*$#
