### ISSUE TITLE
[Off-Canvas & Reveal] reveal-for-X class overrides off-canvas z-index

### ISSUE THREAD

**Issue by gi** [zurb/foundation-sites#9013]
A `div` with `reveal-for-X` class overrides the `z-index` with `z-index: auto` for content with the `off-canvas` class (`z-index: -1`).This causes the default box-shadow to be occluded.

This seen in Firefox 47 on Ubuntu 16.06 and Chrome 51.0.2704.106 (64-bit) on Mac OS 10.11 but not in Safari 9.1.1.

**Reproduce:**
https://jsfiddle.net/wdh22o9s/2/

``` html
<div class="off-canvas-wrapper">
  <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>

    <!-- off-canvas left menu -->
    <div class="off-canvas position-left reveal-for-medium" id="sidebar-left" data-off-canvas>
      <ul class="menu vertical">
        <li><a href="#">Menu 1</a></li>
        <li><a href="#">Menu 2</a></li>
      </ul>
    </div>

    <!-- main content -->
    <div class="off-canvas-content" data-off-canvas-content>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
        eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
        enim ad minim veniam, quis nostrud exercitation ullamco laboris
        nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
        in reprehenderit in voluptate velit esse cillum dolore eu fugiat
        nulla pariatur. Excepteur sint occaecat cupidatat non proident,
        sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
  </div>
</div>
```

**Expectation:**
The shadow border of the main content overlays the sidebar content.

**Actual**
The sidebar content overlays the main content border.

![screen shot 2016-07-11 at 11 01 47 am](https://cloud.githubusercontent.com/assets/7407551/16741150/e8d580fe-4756-11e6-84f8-c797eee1fdb5.png)

**Comment by andycochran** [comment]
Interesting. I see no reason for `.reveal-for-[size]` to have `z-index:auto`. Maybe that can just be nixed. 

However, this might be an app-specific issue. Your drop shadow creates the illusion of the main content sitting in front of the sidebar. But another designer may want the illusion of of the sidebar sitting in front of the main content.

**Comment by zgianos** [comment]
@andycochran: Very true that another designer may want the sidebar in front of the main content. However, the default behavior is the opposite. I did no extra styling on the document.

**Comment by andycochran** [comment]
Ack! You're right. Sorry about that. I'd assumed that Off-Canvas looks like it does in the docs. I'll look into fixing this.

**Comment by andycochran** [comment]
It looks as if `z-index: auto;` is needed in `@mixin off-canvas-reveal`. Otherwise, you can't interact with the off-canvas area (scroll, click) in Safari. But if I nix _all_ the `z-index` rules from `_off-canvas.scss` it works for me. I'm not certain why the `z-index` rules are needed. 

@brettsmason any idea what's going on here? Wanna take this one? 

_Hint: The easiest way to debug this is by nixing `mobile-ofc` in `docs/partials/off-canvi.html` so you can see the shadow on the left off-canvas._

**Comment by brettsmason** [comment]
@andycochran sure I can take a look. I'm busy completely redoing off canvas at the moment so I can add it to the list of things to look at. I could also use your opinion on some things to do with it 😄

**Comment by brettsmason** [comment]
Off canvas has been completely reworked for 6.3 and this issue should now be solved as there is a new variable to control the revealed z-index.
Release candidate is out today, with the full release scheduled for the 15th December.

Closing this, but if you still have issues with 6.3 please re-open.
