### ISSUE TITLE
[Dropdown Menu] No option to close dropmenu on click

### ISSUE THREAD

**Issue by sujayjaju** [zurb/foundation-sites#9015]
This is not really a bug, but odd behavior for the plugin.

**How can we reproduce this?**
1. Open A Dropdown menu with sub menu
2. Click on a sub menu item

**What did you expect to happen?**
The menu should close on click - especially if the clicked submenu item is a leaf node (no further sub menus).

**What happened instead?**
The menu stays open

The 'data-close-on-click' plugin option is a little misleading. It should be relabeled to 'data-close-on-click-outside'. 'data-close-on-click' should instead close the menu when an item is clicked.

**Test case:**
http://codepen.io/sujayjaju/pen/yJPVdy

**Comment by Owlbertz** [comment]
Seems right to me. May be a good enhancement for 6.4.

**Comment by rafibomb** [comment]
I like it - renaming the plugin option and adding in the configuration.

In F5 it was called `dropdown_autoclose: true` 

I like `data-close-on-click-inside` and `data-close-on-click-outside`

This would be a great feature, @sujayjaju is this something you can jump in on?

**Comment by sujayjaju** [comment]
I can give it a shot.

How should this behave in conjunction with: `data-click-open` ? That one makes the sub menu stick on click. But if we have `data-close-on-click` set as well - which would would take precedence?

**Comment by Owlbertz** [comment]
I don't think that these will interfere because `data-click-open` only targets the sub-menu parents if I understand correctly. `data-close-on-click` should change the behavior of actual links that are clicked. At least this is my understanding of these options.

**Comment by rafibomb** [comment]
Moving this up into sooner milestone.

**Comment by rafibomb** [comment]
Need to make sure dropdown menu has a public close method.

**Comment by kball** [comment]
This was addressed by #9131, will be released in 6.2.4 later today!

**Comment by pedzed** [comment]
@kball What about `data-close-on-click-outside`?

@rafibomb Currently, if you use the toggle menu, you _have to_ reclick the toggle button in order to close the pane/menu. What's the best way to make it close if you click outside?
