### ISSUE TITLE
[bug scss] Hover disabled buttons reset color

### ISSUE THREAD

**Issue by hylke94** [zurb/foundation-sites#9021]
Every button with the class of button and disabled is being reset to the base color when hovering over the button.
For example: a button with classes "button alert disabled" is red with an opacity to show the button is disabled. When you hover over this button the color is turning black to blue.

**What did you expect to happen?**
The button stays red when hovered.

**What happened instead?**
The button turns back to blue when hovered.

**Test case:**
[JSFiddle](https://jsfiddle.net/Hylke94/pyh76hyd/)

**Comment by kball** [comment]
Fixed in #9022.
