### ISSUE TITLE
Problem with Orbit in semantic way.

### ISSUE THREAD

**Issue by sababys** [zurb/foundation-sites#9023]
I have some issue when i use orbit in semantic way.
I try to use @include orbit-slide;  in my own class:

```
widget-carousel__slide{

@include orbit-slide; 

}
```

But it doesn’t work and give me a javascript error:

`foundation.min.js:2 Uncaught TypeError: Cannot read property 'className' of undefined`

have you ever seen this problem?

**Comment by Deckluhm** [comment]
The error must come from something else, since this is a javascript error.

Just tried to `@include` this mixin and it compiled without any problem.

**Comment by JeremyEnglert** [comment]
@sababys, feel free to reopen this. But as mentioned above, it appears you're getting a JS error, not a Sass/CSS error.
