### ISSUE TITLE
In my Meteor.js app, Foundation plugins work only after I refresh the page

### ISSUE THREAD

**Issue by SamuelEarl** [zurb/foundation-sites#9028]
In my Meteor.js app, when I click a link and am taken to a page, the tabs and accordions do not work--nothing happens when I click on them. But after I refresh the page the tabs and accordions work like normal. Does anyone know what is going on and how I can fix this problem? 

Unfortunately my app is located on my local machine right now, so I don't have a demo to show you.

Thank you for your help!

**Comment by Deckluhm** [comment]
Please use [Foundation forum](https://foundation.zurb.com/forum) if you need help on how to do something.

GitHub issues are for bugs only.

**Comment by SamuelEarl** [comment]
No problem. I thought maybe this was a bug. I will try the Foundation forum. Thank you.

**Comment by Deckluhm** [comment]
That said, you should probably take a look at that section of the documentation: http://foundation.zurb.com/sites/docs/javascript.html#adding-plugins-after-page-load

**Comment by SamuelEarl** [comment]
Thank you Deckluhm. That fixed it. I appreciate your help!

**Comment by Owlbertz** [comment]
Thanks @Deckluhm for your help.
