### ISSUE TITLE
Off canvas mobile menu not closing with anchor links

### ISSUE THREAD

**Issue by bryonycritchley** [zurb/foundation-sites#9035]
Hi, 

I'm using the Off canvas top bar nav on my site: http://proplumbco.co.uk it's working fine, however when the mobile menu kicks in and you click on the nav items which are anchors, the menu stays open and covers the content. I'd like it to close when clicking on these options if pos.

Help would be much appreciated!

Thanks 
Bryony

**Comment by stuartstarrs** [comment]
@bryonycritchley Your link doesn't show any nav bars. 
If the anchors are _doing anything other than_ requesting a whole new page from the server, i.e. if they are linking to somewhere within the same page or calling content dynamically, you'll have to toggle the off-canvas yourself.

See: [Off-canvas](http://foundation.zurb.com/sites/docs/off-canvas.html#toggle)

**Comment by bryonycritchley** [comment]
Sorry the nav bar is on http://proplumbco.co.uk/home

**Comment by rafibomb** [comment]
I see it's closing when you click in item. Did you figure it out?

**Comment by stuartstarrs** [comment]
He did this:

`  jQuery('.off-canvas li.menu-item').click(function() {
	   jQuery('.off-canvas').foundation('close');
  });`

**Comment by brettsmason** [comment]
@bryonycritchley It looks like you got this sorted. Do you still need any help with this?
FYI I am completely redoing the off canvas component for inclusion in 6.3 (RC due out the end of next month) which should hopefully be a bit improvement.

**Comment by brettsmason** [comment]
Closing this as not heard back. Please re-open if you still need help! 😄
