### ISSUE TITLE
[Media Object] Mixins not functioning in flex mode

### ISSUE THREAD

**Issue by marcusmoore** [zurb/foundation-sites#9038]
**How can we reproduce this bug?**

_Assuming we are compiling our assets_
1. Enable flex mode via instructions [here](http://foundation.zurb.com/sites/docs/flexbox.html)
2. Create a new component using the SASS mixins (`media-object-container` and `media-object-section()`)
3. Create page with an example code from [docs](http://foundation.zurb.com/sites/docs/media-object.html) and created component

**What did you expect to happen?**
The output from the example code and the component code would be the same.

**What happened instead?**
The required `.main-section` is overridden by the compiled media object mixin.

The 

**Test case:**
Here is a [gist](https://gist.github.com/marcusmoore/afca0fa78ee1c6482b1ae2854c1d90da) with my code and some screenshots demonstrating the issue:
## Desktop

![screenshot 2016-07-20 13 05 26](https://cloud.githubusercontent.com/assets/1141514/17001391/acc311ae-4e7b-11e6-80c7-81a6c1f77e9e.png)
## Mobile

![screenshot 2016-07-20 13 05 59](https://cloud.githubusercontent.com/assets/1141514/17001392/acc4a33e-4e7b-11e6-957f-bd3a4d808fce.png)

**Comment by marcusmoore** [comment]
I may have fixed part of the problem by adding `flex: 1 1 0px;` manually:

```
.MediaObject {
  @include media-object-container;


  &__section{
    @include media-object-section();

    &--main{
      // Pulled from _media_object.scss
      @if $global-flexbox {
          flex: 1 1 0px;
      }
    }
  }
}
```

**Comment by rafibomb** [comment]
I don't think there is any flex mode set up for this component. Should be straight forward to add it though.

**Comment by kball** [comment]
@rafibomb I see you added help wanted so going to assume assigning it to yourself doesn't mean you don't want someone to take it... @marcusmoore would you like to take a crack at a PR to address this?

**Comment by marcusmoore** [comment]
@kball Unfortunately I don't have the time right now. I can take a look in a few weeks if it's still open but I can't commit to it right now.

**Comment by Martskin** [comment]
I took a swing at refactoring the Media Object mixins here: https://github.com/zurb/foundation-sites/pull/10679

**Comment by brettsmason** [comment]
This looks like the PR addressing this was successfully merged into core so closing this.
