### ISSUE TITLE
Dropdown Submenu Data Alignment

### ISSUE THREAD

**Issue by cedarbrook** [zurb/foundation-sites#9042]
**How can we reproduce this bug?**

```
<div class="top-bar-right">
  <ul class="dropdown menu" data-dropdown-menu data-alignment="left" >
    <li>
    <a href="#">Item 1</a>
      <ul class="menu">
         <li><a href="#">Item 1A</a></li>
     <li><a href="#">Item 1B</a></li>
      </ul>
    </li>
    <li><a href="#">Item 2</a></li>
    <li><a href="#">Item 3</a></li>
    <li><a href="#">Item 4</a></li>
  </ul>  
</div>
```

**What did you expect to happen?**

The submenu should open and the data
Item 1
Item 1A
Item 1B
should all be aligned underneath each other

**What happened instead?**

The submenu opens and data is not aligned on the left side.

Give us a link to a CodePen or JSFiddle that recreates the issue.
- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by cedarbrook** [comment]
This code delivers what I am looking for:

```
<div class="top-bar-left float-right">
  <ul class="dropdown menu" data-dropdown-menu data-alignment="left" >
    <li>
    <a href="#">Item 1</a>
      <ul class="menu">
         <li><a href="#">Item 1A</a></li>
     <li><a href="#">Item 1B</a></li>
      </ul>
    </li>
    <li><a href="#">Item 2</a></li>
    <li><a href="#">Item 3</a></li>
    <li><a href="#">Item 4</a></li>
  </ul>  
</div>
```
Using the top-bar-left class and adding the float-right class gets data-alignment="left" to work the way I want it. 

Is this a bug?  
If not, am I doing this correctly?

**Comment by andycochran** [comment]
I'm not sure it's a bug. Hmm… I think this is because `.opens-[right,left]` classes are applied dynamically via JavaScript. And when you float the top bar section to the right the box collapses and the JS tries to prevent the menu from sticking out the left side of its container. The `data-alignment="left"` isn't actually doing anything here.

**Comment by samuelmc** [comment]
I've added a third option, 'auto', as default value for data-alignment so the option 'left' can be used to force the alignment left. (#9950)
