### ISSUE TITLE
[Documentation] Dynamically adding foundation to page can require omitting certain tags [v6.2.3]

### ISSUE THREAD

**Issue by NucleaPeon** [zurb/foundation-sites#9049]
Based on issue #9043 that I recently filed, I was trying to add an equalizer to my code via javascript through underscore templates + jquery. @Owlbertz pointed out that I had to omit the `data-equalizer` tag in order for it to function (and I also found I had to omit `data-equalize-on="medium"` tag for proper functionality).

Looking at the following urls:
- https://foundation.zurb.com/sites/docs/javascript.html#adding-plugins-after-page-load
- http://foundation.zurb.com/sites/docs/equalizer.html#js-module

There is no explicit reference to not having those tags in DOM when using javascript. My example was using the equalizer, but I imagine it might apply to many foundation plugins/elements. 

**Solution**

On the docs javascript page or on every affected element page, it would be beneficial to have a small section saying that foundation element tags (perhaps specify which tags?) that already exist on the DOM will interfere with javascript-created elements on those DOMs.

Thank you.

**Comment by DanielRuf** [comment]
Closing as stale. So far we did not have the desfribed issues in projects.
