### ISSUE TITLE
Add Typography Classes

### ISSUE THREAD

**Issue by lunaroja** [zurb/foundation-sites#9053]
This would generate `.h1, h1 { }` and the rest of the header classes, so that users can use the classes on other elements.

``` scss
@mixin header-classes {
    @each $header, $header-selector in map-get($header-sizes, small) {
        .#{$header} { @extend #{$header}; }
    }
}
@include header-classes;
```

**Comment by DaSchTour** [comment]
@abrahamvelazquez if you don't mind I would this to a project where I build additional functions and components based on foundation

**Comment by kball** [comment]
https://github.com/zurb/foundation-sites/pull/9500

**Comment by brettsmason** [comment]
This was added in the above PR so closing.
