### ISSUE TITLE
Documentation incorrect for Sticky on small breakpoint

### ISSUE THREAD

**Issue by jasonlmann** [zurb/foundation-sites#9059]
I'm not sure how to submit a pull request for the docs, but here's the issue: In the docs, it says to add the following to an element in order to make it sticky at the small breakpoint: `data-sticky-on-small`

That doesn't work. (The sticky element scrolls offscreen on small screen sizes.) Neither does `data-options="data-sticky-on:small;"`

However, when I add `data-options="stickyOn:small;"` to the sticky element, the sticky behavior works on small screens. 

Hope this helps, and if you'd like me to submit it as a PR and can, uh, tell me how to do that, let me know!

**Comment by colin-marshall** [comment]
Either `data-options="stickyOn:small;"` or `data-sticky-on="small"` will work. Feel free to reopen this issue if you have further questions.
