### ISSUE TITLE
Nested expanded rows do not remove outer column padding with negative margin

### ISSUE THREAD

**Issue by Joe-Withey** [zurb/foundation-sites#9062]
I believe this was introduced in issue #7801.

When nesting expanded rows, the margin for each nested row is set to auto. Conversely if the rows do not have the expanded class then negative margin is set and the rows work correctly.

This leads to compound padding for each nested layer which is difficult to manage; should a user desire this behaviour it would be better to opt into it.

I've created a [codepen](http://codepen.io/anon/pen/zBLqGk) to illustrate the issue.

**Comment by andycochran** [comment]
I think this is related to #8889.

**Comment by kball** [comment]
Fixed by #8889
