### ISSUE TITLE
[Sticky] methos emCalc does not exist

### ISSUE THREAD

**Issue by eeliinaaa** [zurb/foundation-sites#9063]
**How can we reproduce this bug?**

Add Sticky method "emCalc"

**What did you expect to happen?**

Calculate em values

**What happened instead?**
ReferenceError: We're sorry, 'emCalc' is not an available method for Sticky.

**Test case:**
https://jsfiddle.net/uL3912au/

**Comment by Owlbertz** [comment]
Your Fiddle seems to miss the Foundation framework.

**Comment by kball** [comment]
emCalc is not exported, it is used internally to sticky. If we wanted it globally accessible it should probably live on `Foundation.util`, most likely defined in `foundation.core.js`.  If you have a usecase where you think it should be exposed, feel free to reopen, especially if you want to also submit a PR exposing it. :)
