### ISSUE TITLE
foundation off canvas forceTop:false does not work

### ISSUE THREAD

**Issue by feeekkk** [zurb/foundation-sites#9064]
**How can we reproduce this bug?**
1. Step one
   create an off canvas
2. Step two
   set forceTop to false
3. Step three
   scroll down the page and open the off canvas.

**What did you expect to happen?**
the page would not scroll.

**What happened instead?**
the page scrolled to top.

It seems as if the dist of the newest version of Foundation has the proper code commented out: https://github.com/zurb/foundation-sites/blob/develop/dist/plugins/foundation.offcanvas.js#L138

Why on earth is this documented feature not present in the distributed source code?!

**Comment by brettsmason** [comment]
@feeekkk I am completely redoing the off canvas component for inclusion in 6.3 (RC due out the end of next month) as we agree its currently a mess and needs reworking. This is a key feature that gets asked about a lot and will be working in the new version.

I'll update this issue to let you know when there's something for you to test if you wanted to.

**Comment by brettsmason** [comment]
Off canvas has been completely reworked for 6.3 and this issue should now be solved.
Release candidate is out today, witht he full release scheduled for the 15th December.

Closing this, but if you still have issues with 6.3 please re-open.

**Comment by feeekkk** [comment]
I also just bumped foundation to 6.2.4 and missing from the docs is that `keyboard` is a dependency of off canvas. Haven't checked out the 6.3.1 rc (it can't be installed via bower due to a bad tag..), but hope that is noted!
