### ISSUE TITLE
[F6][Drilldown Menu] Compatibility with android mobile device browser < 5.6.X

### ISSUE THREAD

**Issue by h8h** [zurb/foundation-sites#9067]
I re-open issue #7099   since this is still a problem for android browser < 5.6.X and I can provide a solution.

**How can we reproduce this bug?**
1. Use an android browser < 5.6.X
2. Click on an item which has submenu-items

**What did you expect to happen?**
See the submenu-items

**What happened instead?**
Nothing happend.

**Test case:**

Referencing to [caniuse](http://caniuse.com/#search=transform) android browsers < 5.6.X needs the `webkit-transform` property to work properly.

I couldn't provide a PR because I don't know if this is a foundation or a sass problem and I'm somewhat a bad sass coder.

I found this line for example: [Line 50 drilldown component](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_drilldown.scss#L50):

```
    &.is-active {
      z-index: 1;
      display: block;
      transform: translateX(if($global-text-direction == ltr, -100%, 100%));
    }
```

after compling it to css the result is:

```
 .is-drilldown-submenu.is-active {
    z-index: 1;
    display: block;
    -ms-transform: translateX(-100%);
        transform: translateX(-100%); }
```

It seems that the necessary `-webkit-transform` property is missing.

If I manually add `-webkit-transform: translateX(-100%);` into the compiled css it worked for my android 4.2.2 browser.

**Comment by mattferderer** [comment]
How are you compiling it to css? 

Typically this is handled in a process with a tool like Gulp, Grunt, Webpack or one of the many others. If you look at [line 84 of the Foundation Template](https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js#L84) you will see them using a package called autoprefixer which takes a list of browsers. This package goes through your CSS output & adds prefixes to CSS items like transform to make them compatible with the browsers you select.

**Comment by kball** [comment]
I believe that this was fixed by https://github.com/zurb/foundation-sites/pull/9296
