### ISSUE TITLE
Sticky (Ver.6.2.2) problem max-width [issue resolved]

### ISSUE THREAD

**Issue by Condecator** [zurb/foundation-sites#9071]
Adds more width.
The unit becomes a max-width: 189 px; but should: 174px
In any Media-query small, medium, large....

![small-col](https://cloud.githubusercontent.com/assets/20755691/17277318/cc0a0560-5748-11e6-8677-8fe3b917cd52.jpg)

if you do not "sticky", the margins have both sides.

![- -4](https://cloud.githubusercontent.com/assets/20755691/17277385/36d57b94-574a-11e6-811f-f6df9b14e813.jpg)

Example:

```
<div class="large-3 columns"></div>
<div id="content" class="large-7 columns" role="content"></div>

            <div class="large-2 columns right" data-sticky-container>
                <div style="background:#ffffff" class="small-12 columns sticky" data-sticky data-anchor="content" data-sticky-on="large" data-margin-top="3.5" >
                    <div class="row small-up-2 medium-up-4 large-up-1">
                        <!-- 6 items per page  ->
                        <div class="column">
                            <a href='http://audi.ru' target="_blank"><img src='/images/banner-left.jpg' /></a>
                            <p class="f12">AUDI Наш генеральный спонсор</p>
                        </div>
                    </div>
                </div>
            </div>
```

One solution:
Fixed: line 7384  (foundation.js)
```
        this.$element.css({
          'max-width': newElemWidth - (pdng + this.options.stickyIndent) + 'px'
        });
```

Append option:
```
Sticky.defaults = {
.......
  stickyIndent: 0
}
```

Add option data-sticky-indent="15" 
`
<div class="small-12 columns sticky bgw" data-sticky-indent="15" data-sticky data-anchor="content" data-sticky-on="large" data-margin-top="3.5" >`

Now when you need padding, it can be set in the options.
Sorry for my bad english. Good luck!

**Comment by andycochran** [comment]
@Condecator, I see that you added "issue resolved" to the title. So I'm going to close this issue. If it is not resolved, please reopen and provide us with a link to a CodePen that recreates the issue.

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)
