### ISSUE TITLE
[DropdownMenu] Invalid ARIA usage

### ISSUE THREAD

**Issue by gerardkcohen** [zurb/foundation-sites#9072]
DropdownMenu widget, following the [Menu](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) ARIA pattern, uses an incorrect property of `aria-expanded` on menu items. [aria-expanded](https://www.w3.org/TR/wai-aria-1.1/#aria-expanded) is not supported on the role of [menuitem](https://www.w3.org/TR/wai-aria-1.1/#menuitem).

There is also an unnecessary `aria-hidden` on inactive menuitem's. The `aria-hidden` is not needed since `display:none` is being used to hide menu items, which enough to hide from assistive technologies.

Lastly, `tabindex` of 0 is being added to the first menu item but is unnecessary because the anchor tag used is already focusable.

**Comment by brettsmason** [comment]
This has been fixed in PR 9073 which was merged.
