### ISSUE TITLE
SCSS Install Button Link Goes to Incorrect Page

### ISSUE THREAD

**Issue by nwittwer** [zurb/foundation-sites#9080]
**How can we reproduce this bug?**

1. [Foundation for Sites: Download](http://foundation.zurb.com/sites/download.html/)
2. Click "Install via SCSS" under Sass

**What did you expect to happen?**
Go directly to the Sass installation page in Docs

**What happened instead?**
Redirected to Docs homepage

**Comment by rspraymond** [comment]
I am not able to locate the download page in the repo. But it seems there are two options for this link.

http://foundation.zurb.com/sites/docs/sass.html
http://foundation.zurb.com/sites/docs/installation.html

**Comment by nwittwer** [comment]
@rspraymond @rafibomb was able to make the edit this morning and change it to the first link you recommended as well (http://foundation.zurb.com/sites/docs/sass.html). Closing.
