### ISSUE TITLE
Foundation sites template gulp process stops at "default"

### ISSUE THREAD

**Issue by baglio** [zurb/foundation-sites#9081]
**How can we reproduce this bug?**

1. git clone foundation-sites-template
2. Run `npm install` and `bower install`
3. Run `npm start`

**What did you expect to happen?**

I expected the gulp process to complete, create the dist folder with compiled sass and copied assets and start the local server.

**What happened instead?**

Gulp process stops at *default* after executing *sass*

**Comment by Deckluhm** [comment]
Duplicate of #8681.
