### ISSUE TITLE
Culture Clash, Foundation JS and TypeScript

### ISSUE THREAD

**Issue by DaSchTour** [zurb/foundation-sites#9086]
I aware of the fact that this may be only an issue for a small subset of foundation users, but I think this didn't get any attention here till now.
We are currently moving to TypeScript in the project I'm working on and I already had several issues with Foundation while trying to use it with TypeScript. 
This might be partially an issue in foundation typings https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/foundation-sites

The main problem is how JavaScript modules are initialized in foundation.
Using `new Foundation.Reveal(el, options)` throws the following errors on compile:
`Error:(45, 13) TS2350: Only a void function can be called with the 'new' keyword.
Error:(45, 13) TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.`
When trying to use it without `new` I get an JavaScript error at runtime `Uncaught TypeError: Cannot call a class as a function`;

As all JS is already ES2015 is would be easy to make it TypeScript. An Alternative would be to deliver typings directly from the project.

I have to say, I'm a bit lost with this, that's why I'm creating this issue here. As everything else works fine with typings and wit typescript that's the last thing that's broken. For general init of all modules the `$(document).foundation()` works fine. But now with reveals it's a real battle and I have no idea how to create a workaround.

**Comment by mattferderer** [comment]
This might be more of an issue to post on that Definitely Typed project. My experience with Typings definitions are that they are often incomplete & rarely done by the authors of the original JS repository.

**Comment by Owlbertz** [comment]
Hi @DaSchTour, I would be happy to help you with your problems.
Could you provide me some more of your TS code so I can see how your project is set up?

**Comment by arunsn43** [comment]
`let revealDlg = **new** Foundation.Reveal($(id), {
                            closeOnEsc: false,
                            closeOnClick: false
                        });  `
and the error appears as "Only a void function can be called with the 'new' keyword"

**Comment by arunsn43** [comment]
Cool.. Got it.. It should be changed to 
`new (<any>Foundation.Reveal)($(id), {
                            closeOnEsc: false,
                            closeOnClick: false
                        }); `
But its a work around to avoid the error. Misleading the typescript compiler here :)

**Comment by Owlbertz** [comment]
Are you using the transpiled JavaScript or the original ES6 files in your TypeScript project?

**Comment by arunsn43** [comment]
I'm using the Typescript definitions in my project with Angular 2

**Comment by DaSchTour** [comment]
Closing in favor of more specific change request #9391
