### ISSUE TITLE
[Drilldown Menu] arrow on back

### ISSUE THREAD

**Issue by lakpo** [zurb/foundation-sites#9088]
There is a problem with version 6.2.3 not present in version 6.1.0

**How can we reproduce this bug?**

check drilldown menu on medium screen ,the arrow of "Back" on him

**Test case:**

http://s.codepen.io/lakpo/debug/vKVbzR

**Comment by abdullahsalem** [comment]
Thanks @lakpo for reporting this, I am going to check it.

**Comment by abdullahsalem** [comment]
Hi @lakpo,
The arrow normally goes up of the rest of the text when there is no space for it, so in this case we need to adjust the text and arrow on the same line by adding `white-space: nowrap`.
You can temporarily add this custom code:
```css
.js-drilldown-back a {
  white-space: nowrap
}
```
Take a look at this http://foundation.zurb.com/sites/docs/drilldown-menu.html#custom-styling

**Comment by lakpo** [comment]
thank you for the support! Sorry for my bad English

**Comment by abdullahsalem** [comment]
My pleasure, @lakpo!
Keep building your awesome website, and enjoy Foundation ;)
