### ISSUE TITLE
Foundation for Meteor 1.4 = Broken -- update meteor-scss->3.8.0 or newer please

### ISSUE THREAD

**Issue by zorrobyte** [zurb/foundation-sites#9091]
1. Step one
   Meteor 1.4
2. Step two
   meteor add zurb:foundation-sites
3. Step three
   Check massive spam that is output in bash

**What did you expect to happen?**
Foundation for sites should have its own repo for Meteor so I can submit a PR (Foundation for Sites fails to install with Meteor 1.4)

**What happened instead?**
Here's the log:
https://github.com/fourseven/meteor-scss/issues/199#issuecomment-238069088

**Comment by metadan** [comment]
Please can we get an update on this, or as @zorrobyte says, a repo that we can submit a PR to.

**Comment by DanielRuf** [comment]
This here is the right repo. fourseven-scss was problematic in other projects too.

**Comment by DanielRuf** [comment]
> Since meteor 1.4.1+ (fourseven:scss 3.9.0+), we do not have prebuild binaries anymore. You are required to set up the required toolchain yourselves.

https://github.com/fourseven/meteor-scss

**Comment by DanielRuf** [comment]
There should be a new release soon https://github.com/zurb/foundation-sites/issues/11048#issuecomment-372386410

cc @colin-marshall

**Comment by colin-marshall** [comment]
I don’t know anything about the meteor stuff, sorry.

**Comment by DanielRuf** [comment]
@ncoden can I assign this to you as you will address some Meteor related stuff?

**Comment by DanielRuf** [comment]
Bump @ncoden let me know if you can take a look or if I should configure the environment on my Mac for this.

**Comment by ncoden** [comment]
👍

**Comment by DanielRuf** [comment]
Closing as this should be resolved now.
