### ISSUE TITLE
[Reveal] Missing ajax load

### ISSUE THREAD

**Issue by slucas-nwx** [zurb/foundation-sites#9095]
Why was this removed with no real substitute?  We are trying to upgrade to Foundation 6 and we extensively use the ajax modal. Adding even more java script just to accommodate the lack of this fundamental feature is really not acceptable.

**Comment by Deckluhm** [comment]
Several thoughts on this:

- I don't think it's Foundation responsibility to handle this kind of feature.
- The Foundation 5 way of loading AJAX content was just useful if you wanted to load a full page.
- To me it seems a bit overkill to load a full page just to load content in a modal.
- It doesn't answer a probably more common use case : grab data from an API and inject it in the modal?
- [Foundation 6 alternative](http://foundation.zurb.com/sites/docs/reveal.html#ajax) isn't that different from Foundation 5 and it gives you way more flexibility.

**Comment by slucas-nwx** [comment]
> It doesn't answer a probably more common use case : grab data from an API and inject it in the modal?

This is the very reason we used it. to load modals and their responses from an api call.
It made the amount of javascript we had to write alot less.

We are working on some global method we can use to make up for the lack of support now, but I'm really surprised of the amount of fundamental changes from 5 to 6.

**Comment by slucas-nwx** [comment]
I'm also wondering if we now have to make a modal element for each ajax call we want to make.  Don't believe this was the case before. Correct me if I'm wrong.

The example in the documentation states: 

```
var $modal = $('#modal');

$.ajax('/url')
  .done(function(resp){
    $modal.html(resp.html).foundation('open');
});
```

Not real sure why response has .html appended to it. Is that dynamically created html file from foundation?

**Comment by Deckluhm** [comment]
> I'm really surprised of the amount of fundamental changes from 5 to 6.

Major versions break things and even if it requires you to update some code, it's necessary to keep projects getting better.

> Not real sure why response has .html appended to it. Is that dynamically created html file from foundation?

I don't think the documentation example is working (correct me if I'm wrong but this `.html` isn't needed / working).

Here is a working example:
```JS
$.ajax('/url').done(function(response) {
  $('#your-modal').html(response).foundation('open');
});
```

> I'm also wondering if we now have to make a modal element for each ajax call we want to make. Don't believe this was the case before. Correct me if I'm wrong.

You don't have to create a `$modal` variable (as you can see in my example above) but it's good practice to put jQuery selectors in variables if you use them more than once (for performance reasons).

**Comment by slucas-nwx** [comment]
Sorry, I meant do we have to make a modal div in html for each modal now like 
<div id="Modal"></div>

I'm pretty sure the old reveal ajax created the entire modal for you, so that you didn't have to litter the html with div elements.

Thanks

**Comment by Deckluhm** [comment]
Foundation 6 modals work the same way than in v5:
- Foundation 5: http://foundation.zurb.com/sites/docs/v/5.5.3/components/reveal.html
- Foundation 6: http://foundation.zurb.com/sites/docs/reveal.html

**Comment by abdullahsalem** [comment]
Hi @slucas-nwx ,
I am sorry to hear that you are facing that troubles in your migration process, and I will do my best to help you.

Foundation 6 Reveal and its events system give the developer variety of options to manipulate the reveal content and control when it should be shown or hidden. And once you deeply understand how it works, hopefully you will like it more than F5 :)

I would assume that you need to issue multiple Ajax requests and show every returned content but in the same reveal, so the reveal would be only one. To accomplish this task, you should do the following steps:
- Create the reveal HTML structure, either programmatically or by copy-and-paste [a code snippet of reveal HTML structure](http://foundation.zurb.com/sites/docs/reveal.html#basics), notice that, in this case you probably don't need to add an HTML element as trigger, while you will programmatically trigger it once the Ajax request is done.
- Initialize that reveal HTML structure, and if you already called `$(document).foundation()`, then your reveal should be initialized.
- Send your Ajax request, then inject the returned data into your reveal.
- Finally, fire the `open` event on that reveal by calling this API and pass `open` to it `$(#yourRevealSelectore).foundation('open')`.

Check out this example I've done for you http://codepen.io/abdullahsalem/pen/gryYpO, also you can check these Reveal tutorials by @kball http://zurb.com/university/lessons

Let me know if you need further help.

**Comment by DanielRuf** [comment]
In general this is a usage question.

I guess this is already answered.
So far this should work.

Is there anything unanswered or unclear?

**Comment by slucas-nwx** [comment]
@DanielRuf Yes, this is answered. Thanks!

**Comment by DanielRuf** [comment]
Thanks for your feedback.

Ok, I'll close this issue then. If you have any other implementation question, do not hesitate to ask on StackOverflow or in our Gitter channel. You can ping us then and we'll try to answer your question as best as possible.

**Comment by Goosub** [comment]
I also faced this issue, here is a small custom function I wrote to get my Foundation 5 HTML to work with Foundation 6 AJAX loaded Reveals. But this after you initialized foundation: $(document).foundation();

/* Foundation 5 to Foundation 6 fix for loading reveals with AJAX */
$( "[data-reveal-ajax]" ).each(function( index ) {
	var el = $(this);
	//console.log( index + ": " + el.attr('data-reveal-id') + " | " + el.attr('href') );
	$(this).on("click", function(){		
		$.ajax( el.attr('href') ).done(function(resp){
			$( '#'+ el.attr('data-reveal-id') ).html(resp).foundation('open');
		});
		return false; // stop defalt onklick fiering
	});
});
