### ISSUE TITLE
Error in path to import scss file

### ISSUE THREAD

**Issue by juanesarango** [zurb/foundation-sites#9097]
I am using foundation-sites as a bower dependency in an Ember Application v2.5.0. I am using also an addon to use saas called ember-cli-saas. And I'm getting a error with the saas compiler from the file `foundation-sites/scss/settings/_settings.scss` as it cannot import `util/util` it must be `../util/util`

I propose a PR to fix this:
https://github.com/zurb/foundation-sites/pull/9096

**Comment by colin-marshall** [comment]
You need to add `bower_components/foundation-sites/scss` to your import paths.

**Comment by juanesarango** [comment]
@colin-marshall indeed this fixed the error. Thanks! 

In case anyone is using also `Ember`. I modified my `ember-cli-build.js` to:
`var app = new EmberApp({
  sassOptions: {
    includePaths: [
      'bower_components/foundation-sites/scss'
    ]
  }
});`

**Comment by colin-marshall** [comment]
@juanesarango no problem!
