### ISSUE TITLE
[Sticky] Docs are misleading/wrong: Padding of sticky container ignored for sticky element

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#9101]
**How can we reproduce this bug?**
When sticky is used, the sticky element does not take the proper sizing of the container into account. You can see it in the screenshots below as well as in the docs here: 
http://foundation.zurb.com/sites/docs/sticky.html
This happens even before the plugin set position: fixed. It already is buggy, when position is set to absolute.

**What did you expect to happen?**
It seems like the padding of the sticky container column should be used, but is ignored. When manually setting the column padding to the sticky element, it sort of works, but feels like a hack. I think it rather is a position/width issue. 

**Test case:**
http://foundation.zurb.com/sites/docs/sticky.html

![screen_1470898741](https://cloud.githubusercontent.com/assets/3061129/17580951/cd21e190-5fa2-11e6-9b10-3dd0f646ee20.jpg)
![screen_1470898935](https://cloud.githubusercontent.com/assets/3061129/17580952/cd256a5e-5fa2-11e6-8975-ff3cb189b33c.jpg)

Actually, this is not a bug in the sticky plugin. You can fix the issue, if you put the the `sticky-container` into another simple `div`, it works. Then the sizing of the container is _without padding!_ 

The docs are wrong here. Or say at least misleading and should be like this: 

```
<div class="columns small-6 right">
 <div data-sticky-container>
  <div class="sticky" data-sticky data-margin-top="0">
    <img class="thumbnail" src="assets/img/generic/rectangle-3.jpg">
    <!-- This sticky element would stick to the window, with a marginTop of 0 -->
  </div>
 </div>
</div>
```

**Comment by JeremyEnglert** [comment]
This appears to be working as expected now. Please re-open if you're still having issues.
