### ISSUE TITLE
FEATURE REQUEST: disable menu effect

### ISSUE THREAD

**Issue by pine3ree** [zurb/foundation-sites#9102]
Hello,
it would be nice to be able to disable menu effects based on screen size (using a special "no plugin" keyword like `none` for instance) 
So far it seems only possible to change menu effect (accordion, dropdown, drilldown)

```
<ul class="vertical medium-horizontal menu" data-responsive-menu="accordion medium-none large-dropdown">
    <!-- menu items here -->
</ul>
```

**Comment by abdullahsalem** [comment]
Hi @pine3ree,
What do you mean by DISABLE here, do you mean only hide the menu or keep it appear but disable its functionality?
And by the way, both scenarios are currently possible:
- To only hide (or show) it at a certain media size, you can use one of [those visibility CSS classes ](http://foundation.zurb.com/sites/docs/visibility.html)
- To disable its functionality, you can destroy the plugin on that element by this statement `$('#yourMenuSelector').foundation('destroy')` and to fully control that depending on the current media size, check this reference http://foundation.zurb.com/sites/docs/media-queries.html#javascript

Let me know if I really got your point :)

**Comment by pine3ree** [comment]
Hello @abdullahsalem,
sorry if I have not been very clear. What i meant is a simpler way to automatically disable all kinds of menu plugins via the "data-responsive-menu" attribute without writing js, the same way menu plugins are now swapped.
As of now if I set data-responsive-menu="(small-)accordion medium-dropdown" i will get a dropdown menu for large window sizes too. It would be nice to have for instance a "large-none" option that automatically destroy the menu plugin for large+ .  I think it would mean just adding a few lines of code in responsiveMenu.js to handle the "none" null plugin name.

kind regards

**Comment by kball** [comment]
Perhaps we can look at this as a part of https://github.com/zurb/foundation-sites/issues/9421

**Comment by abdullahsalem** [comment]
@kball Yes, I agree.
@pine3ree Thanks for the following up, and I'm sorry for the delay in replying. Now, you can follow up with my folks in this relevant issue #9421

**Comment by pine3ree** [comment]
Hello @kball , @abdullahsalem .
Should I close this request and move it to https://github.com/zurb/foundation-sites/issues/9421 ?

best regards and merry xmas time.

**Comment by kball** [comment]
I think it is reasonable to keep this issue separate so we have a reference list of different items to address from #9421 (which now has a tag in from this). However, if you are opinionated on menus in general, much of the discussion on how to move forward with them is likely to happen in that issue.

**Comment by brettsmason** [comment]
Thanks for the feature request. Unfortunately it didn't make it into the menu rework (as that was mainly Sass only). We won't be adding any new features to F6, but we will revisit this request when the time comes to work on Foundation 7. Thanks!
