### ISSUE TITLE
ORBIT carousel inside toggable element and dropdown menu

### ISSUE THREAD

**Issue by pine3ree** [zurb/foundation-sites#9103]
The orbit carousel works fine inside a dropdown pane,(dropdown plugin)  but doesn't work inside a dropdown (initially hidden) menu item (dropdown menu plugin); images disappear and/or bullets/navs clicks have no effect. If the menu item is open while images are loading the carouselt works fine until is closed and re-opened and something else is clicked in between.

I discovered this issue while building a fancy mega menu.

ps
the orbit placed inside the dropdown-pane continues to work after toggling it several times.

kind regards

**Comment by pine3ree** [comment]
updates: when using the opacity property to show/hide the submen the carousel works fine. Using display (none|block) - the default framework behaviour -  breaks the carousel.

**Comment by pine3ree** [comment]
update:
when the orbit or any outer element is toggled (display: none) the orbit stop working (not always at the first toggle).

**Comment by pine3ree** [comment]
update:
the dropdownMenu/drilldownMenu/accordion plugins sometimes utilize jQuery.find('.is-active') and remove the class 'is-active' from all the matching elements, including orbit-slide elements inside menu list item elements. This causes styling issues and js issues (the changeSlide method expects to find a least 1 'is-active' orbit-slide element)

**Comment by pine3ree** [comment]
Disabling mui makes the orbit slider work even after beiing toggled,
see: https://jsfiddle.net/akp40a46/2/

**Comment by pine3ree** [comment]
the bug does not depend on timing function:

see [jsfiddle example no-autoplay](https://jsfiddle.net/akp40a46/5/)

the next-slide button works as well as the other controls until the next button is clicked while the carousel is hidden (via the toggle button).

In my tests I added debugging output and found out that when changeSlide is called while the orbit is hidden current/next slides are left with mui related classes on.

**Comment by pine3ree** [comment]
getting closer:
it appears that after calling changeSlide when the orbit is hidden the foundation.motion finish() method is not called. The transitionend event is triggered, though....

**Comment by pine3ree** [comment]
got it:
i've found that the mui finish() method is never called for elements for which jQuery is(':hidden') is true.
The quicker fix for the orbit carousel would be early return within changeSlide() for those cases.

https://github.com/zurb/foundation-sites/pull/9152

**Comment by pine3ree** [comment]
update: motion-ui related issue when orbit is `:hidden` is now fixed by https://github.com/zurb/foundation-sites/issues/9311

**Comment by kball** [comment]
Great, closing this, fix will be in 6.3
