### ISSUE TITLE
[Top Bar] Broken vertical dropdown menu (v6.2.3)

### ISSUE THREAD

**Issue by dk0r** [zurb/foundation-sites#9112]
## Update: This was not a bug but a user error. Issue closed.

**How can we reproduce this bug?**

1. Go here ([https://jsfiddle.net/4b4sgbfg/6/](https://jsfiddle.net/4b4sgbfg/6/)) to skip steps 2-4.

2. Create a JS fiddle including the following external resources:
 https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.3/foundation.css
 https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.3/foundation.js

3. Paste the 'Basics' example into JS fiddle's html section
 http://foundation.zurb.com/sites/docs/top-bar.html
*_note_ the `<input>` tag on line-19 of the example is not closed

4. Click `Run`

**What did you expect to happen?**
I expect to see this: http://i.imgur.com/FVaEirH.png

**What happened instead?**
Instead I see this: http://i.imgur.com/GqwZo91.png

**Test case:**
This issue was reproduced on several varying versions of Chrome, FF and IE.

**Comment by pine3ree** [comment]
@dk0r 
It seems you forgot to initialize the javascripti framework?

```
$(document).foundation();
```
inside codepen you also need to add jquery (2.2.4) library as a dependency

**Comment by dk0r** [comment]
@pine3ree 
Perhaps you can provide a JSfiddle example showing a solution so I may close this issue?
I tried adding your suggestions as follows but the issue persists:
https://jsfiddle.net/4b4sgbfg/17/

**Comment by pine3ree** [comment]
@dk0r 
there you go: https://jsfiddle.net/uf5hbp37/
check the javascript library button :-)

**Comment by dk0r** [comment]
My bad. I've updated the original post and am closing the `issue` as user error.
