### ISSUE TITLE
[foundation.util.triggers] checkListeners() has to be public

### ISSUE THREAD

**Issue by Baedda** [zurb/foundation-sites#9114]
Many foundation components need the triggers to work correctly. But the triggers only get bound on window load.

This is a problem if you use Foundation in any kind of asynchronous environment (e. g. by using requirejs) because the window load event can be fired before all javascripts have been loaded. As a result the `checkListeners()` function is not called and no trigger will be bound.

Take a look to your code:

```javascript
/**
* Fires once after all other scripts have loaded
* @function
* @private
*/
$(window).load(() => {
  checkListeners();
});
```
The comment says it all - all scripts have to be loaded but if you load scripts asynchronous then 
this condition is not fulfilled. 

I wanted to fix this on my side by calling the `checkListeners()` function for myself after all my scripts have been loaded. This doesn´t work because all the code from foundation.util.triggers is wrapped inside an anonymous function. 

Could you think of making the function public in any way? It would be great if the `checkListeners()` (or the complete triggers) would be registered in the global `window.Foundation` object too, so we could call the function directly.

In the docs there is a `reInit()` function for the plugins. Maybe you could make the utils "reinitable", too. Maybe with a syntax like that: `Foundation.reInit('util', 'triggers');` This would be really helpfull to make Foundation more compatible for asynchronous loading.

**Comment by Baedda** [comment]
Okay at this moment I think I found a solution at the end of the file:
`Foundation.IHearYou = checkListeners;`
Is this the prefered and future safe way to fix the problem I described above? If yes the I feel very stupid right now :D But could you please add this to the docs?

**Comment by Miw0** [comment]
+1 we solved it in our project with the solution @Baedda described. Calling `Foundation.IHearYou()` right after initializing Foundation via `$(document).foundation()` fixes the issue with require.js

**Comment by coreysyms** [comment]
I can confirm for you the Foundation.IHearYou() will (re)initialize the listeners. Closing.
