### ISSUE TITLE
Tooltip doesn't appear inside Reveal

### ISSUE THREAD

**Issue by ableslayer** [zurb/foundation-sites#9122]
**How can we reproduce this bug?**

1. Create a Reveal modal window
2. Create a tooltip inside the modal window
3. hover on the tooltip

I expect the tooltip to appear when hovering inside the modal window.

What happened instead was the tooltip didn't appear.

Link to a CodePen:

- [Foundation 6 Reveal Tooltip bug](https://codepen.io/ableslayer/pen/yJwkWq)

**Comment by abdullahsalem** [comment]
Thanks for reporting this issue, @ableslayer!
I will check it ASAP.

**Comment by kball** [comment]
I think this bug may actually be the same as https://github.com/zurb/foundation-sites/issues/9193

**Comment by abdullahsalem** [comment]
I think #9193 is another story

**Comment by glen-84** [comment]
@kball When will the fix be released? See also #8775.

**Comment by abdullahsalem** [comment]
You're right @glen-84 , it looks the same.
Thanks for pointing that out.
