### ISSUE TITLE
[Abide] Yeti Launch required select not working

### ISSUE THREAD

**Issue by JWhiteford** [zurb/foundation-sites#9133]
**How can we reproduce this bug?**
1. Create new project in Yeti Launch (sites & zurb template)
2. Copy abide template markup & paste into new site
3. Press Submit

**What did you expect to happen?**
The required select should have the classes "is-invalid-label" & "is-invalid-input" added to display error

**What happened instead?**
All other required fields are correct, this one isn't.

**Test case:**
NA

**Comment by kball** [comment]
Sorry, yeti launch is no longer supported, and it pulls down an old version of the framework.  Closing this for that reason - If you still see this in a fresh checkout using 6.2.4 please reopen.
