### ISSUE TITLE
Strange padding around the table on Outlook 2003

### ISSUE THREAD

**Issue by vickiechai** [zurb/foundation-sites#9134]
Everything looks good, except on Outlook 2003, there's a strange padding around the table, the images are 580px wide. 

![issue](https://cloud.githubusercontent.com/assets/21206497/17909774/9c88ea80-694b-11e6-8dd5-9900c1a6b8f7.PNG)

You can find the html code here: https://github.com/vickiechai/email/blob/master/email_to_dealer_announcing_new_referrals.html

Please help!

Thanks!

**Comment by Deckluhm** [comment]
This repository is for [Foundation for Sites](https://foundation.zurb.com/sites/docs).

The repository you are looking for is the [Foundation for Emails](https://foundation.zurb.com/emails/docs) one: [zurb/foundation-emails](https://github.com/zurb/foundation-emails)
