### ISSUE TITLE
Callout - alt font colot not used

### ISSUE THREAD

**Issue by fracsi** [zurb/foundation-sites#9136]
**How can we reproduce this bug?**

Use any dark background (`$callout-background`: #000) for callout, with `$callout-background-fade: 0`.

**What did you expect to happen?**

Callout font color is `$callout-font-color-alt`.

**What happened instead?**

Callout font color is `$callout-font-color`.

**Comment by brettsmason** [comment]
Having looked at the codebase it looks like you are right and this was never fully implemented. This will need reworking a bit by the look of it.

**Comment by kball** [comment]
I believe this was resolved in 6.3, closing.
