### ISSUE TITLE
toggle does not work with animations if using it to add a class.

### ISSUE THREAD

**Issue by calderJamNet** [zurb/foundation-sites#9140]
I'm trying to use toggle to display an initially hidden object, however this gets screwed up if I use any animations and no classes are added

I'm using this scss 

```
        form {
          display: none;
          &.visible {
            display: inline-block;
          }
        }
```

this code works

```
              <button id="add-tag-sub-1" data-toggle="add-tag-sub-form-1"><i class="fi-plus"></i></button>
              <form class="add-tag-sub-form" id="add-tag-sub-form-1" data-toggler=".visible">
                <input type="text" placeholder="tag">
              </form>
```

but this does not

```
              <button id="add-tag-sub-1" data-toggle="add-tag-sub-form-1"><i class="fi-plus"></i></button>
              <form class="add-tag-sub-form" id="add-tag-sub-form-1" data-toggler=".visible" data-animate="hinge-in-from-left hinge-out-from-left">
                <input type="text" placeholder="tag">
              </form>
```

**Comment by andycochran** [comment]
This seems to work for me. http://codepen.io/andycochran/pen/KNpgOE

**Comment by andycochran** [comment]
@calderJamNet Which version of Foundation are you using? I'm gonna close this. But please reopen if you can reproduce the bug in a CodePen.

**Comment by jstoup111** [comment]
Literately copied from here http://foundation.zurb.com/sites/docs/toggler.html

Clicking the toggler does nothing. It should be hiding/showing with the animation.

Foundation 6.3.0

http://codepen.io/anon/pen/WRyKyK

**Comment by kball** [comment]
@jstoup111 The codepen in question is referencing JS links that don't exist. I updated it with working CDN refs and it appears to be working fine: https://codepen.io/kball/pen/JEBKmd

**Comment by jstoup111** [comment]
@kball Thanks for the update. I realized I hadn't included Motion-UI so it didn't work at all if I had `data-animate` (sp).
