### ISSUE TITLE
Composer can not get current stable Version

### ISSUE THREAD

**Issue by RafaelKa** [zurb/foundation-sites#9144]
**How can we reproduce this bug?**
1. fetch this repo with composer `^6.2.3`
2. verify fetched version and current stable release

**What did you expect to happen?**
current stable version must be installed

**What happened instead?**
old(last triggered composer release) installed

**Fix**

Must be done from Repo Admin !
1. remove version from [composer.json line 4](https://github.com/zurb/foundation-sites/blob/develop/composer.json#L4)
2. go to https://github.com/zurb/foundation-sites/settings/hooks
   - add Packagist Hook
   - follow instructions on Github

Packagist will handle the versions automaticly and all are happy.

**Comment by kball** [comment]
Step 1 is complete, step 2 was already in place, doesn't appear to be auto-updating but this should be fixed with next release.

**Comment by kball** [comment]
@RafaelKa this should be working now, can you confirm?

**Comment by RafaelKa** [comment]
@kball yes, it works!

see https://packagist.org/packages/zurb/foundation there is 6.2.4 now

the badge for php should update soonish https://badge.fury.io/ph/zurb%2Ffoundation.svg 

![version badge for PHP](https://badge.fury.io/ph/zurb%2Ffoundation.svg "F6 sites PHP Version") <- shows (php package | ?.?.?) @ 10 Nov 2016 02:42

**Comment by kball** [comment]
great, thanks!
