### ISSUE TITLE
FEATURE REQUEST: js code styling

### ISSUE THREAD

**Issue by pine3ree** [zurb/foundation-sites#9148]
Hello, no bug reporting/ pr  this time.

I am studying the foundation 6.2 javascript code in order to solve a few issues I encountered.
I find the code a little hard to read compared to other projects and also compared to mainstream php code (i am mostly a php developer) (see psr)

I also found examples different styles inside the same file:

``` js
if (a === b) {
  //...
}
if(a === b){
  //...
}
```

i personally regard readability to be an important step/feature in code quality and i am a big fan of spaces (in the end we all use minified files) and skipping them may convey particular meaning like function definitions and function calls ().

Wouldn't it be better to follow (or even create) some guidelines like the well-known @douglascrockford's ones for instance?
http://javascript.crockford.com/code.html

Sorry if there is already a javascript code styling for foundation but i was not able to find it. If that is the case could someone direct me to right place?

kind regards
maks feltrin

**Comment by markadrake** [comment]
It may be easier to incorporate [a gulp plugin](https://www.npmjs.com/package/gulp-jsbeautifier) into the checkin process. Here's a [list of options available](https://github.com/beautify-web/js-beautify#options). Would adding this tool be enough to cleanup the JS source files so it's formatted the same throughout the project?

**Comment by pine3ree** [comment]
Hello @markadrake ,

I was referring mainly to a "zurb foundation" js source code guideline - before any gulp processing - so that the js code of foundation-sites (apps|emails|motion) could be more consistent. I personally like Crockford's, but i believe it's more important to have a code style than which one to use.

kind regards,
maks

**Comment by markadrake** [comment]
@pine3ree I totally agree that all the JS code (CSS too for that matter) should follow a convention of choice set by the team at Zurb - and Corckford's is pretty close to what I follow. I definitely support you on this.

I know that Gulp is typically used for tasks relating to the front-end, but we could make it a part of the build + checkin process. We could utilize a plugin like the one above to define the standards for all the JS files to follow. So before you check in, run the build. The build will reformat all the JS files. 

This would allow people to write the code, initially, however they like. But before submitting a PR it will be formatted to the standard of the project. We do things like this inside of Visual Studio all the time (not with Gulp though). 

Sorry if I'm not making much sense. :)

**Comment by JeremyEnglert** [comment]
Hi everyone,

Guidelines can be found here: https://github.com/zurb/foundation-code-standards

Feel free to make specific recommendations in that repo. 

Big thanks!
