### ISSUE TITLE
[Installation] Possible typo in "Installation" > "HTML Starter Template" doc for js path

### ISSUE THREAD

**Issue by jwatkin** [zurb/foundation-sites#9150]
On this page:
http://foundation.zurb.com/sites/docs/installation.html
in this section:
"HTML Starter Template"
the foundation.min.js file is listed as being in the "js" folder, but it's really distributed in the js/vendor folder for the Foundation 6.2.3 Complete CSS for Sites download at:
http://foundation.zurb.com/sites/download.html/complete,
Perhaps this discrepancy should be fixed, or at least noted.

**Comment by martinlugton** [comment]
Related issue: https://github.com/zurb/foundation-sites/issues/9188

**Comment by brettsmason** [comment]
This has been addressed in a docs update so closing this.
