### ISSUE TITLE
[Drilldown Menu] Wrong JS events listed in Documentation

### ISSUE THREAD

**Issue by callumisitt** [zurb/foundation-sites#9151]
The Javascript events in the documentation for the Drilldown Menu appear to be wrong. I tried the open event, which is listed in the docs as 'open.zf.drilldownMenu', but nothing was happening when I set up a listener for it. Using 'open.zf.drilldown' however, worked as intended. This was with version 6.2.3.

**Comment by ahdigital** [comment]
This is still an issue in version 6.4.

**Comment by ozeone** [comment]
How come this has not been fixed in a release?
Googled for 1h before finding this, and solving my problems.

The event name is still open.zf.drilldownMenu in docs, and needs to be open.zf.drilldown

**Comment by shready** [comment]
Looks like it was fixed in f7e63fd by changing the docs title, but then the title was changed back 72844c8 for consistency. That probably reintroduced the issue.

**Comment by IamManchanda** [comment]
Appologies folks... Have to accept my mistake... I just updated it for the sake of docs search but that was a mistake...

Fixed it now ... Added a PR!
