### ISSUE TITLE
Top Bar with dropdown is disappearing on hover-out

### ISSUE THREAD

**Issue by alen12345** [zurb/foundation-sites#9153]
Dear all,

The Top Bar in Foundation 6.2.3 (installed through bower) is not working as expected. It is disappearing after the mouse leaves a dropdown. JS is adding a display:none to the ul tag.

I can confirm the same issue reported in this post in the forum: http://foundation.zurb.com/forum/posts/46947-top-bar-disappears-on-dropdown-hover-out

This simple snippet of the documentation is affected by this problem, too: http://foundation.zurb.com/sites/docs/top-bar.html

Can anyone confirm this issue? I am on foundation-sites 6.2.3 and jQuery 2.2.4

**Comment by pine3ree** [comment]
@alen12345 
Hello Alessio,
can you post a codepen/jsfiddle for that. I have used dropdown/responsive menu but nevered encounter this issue (using jquery 2.2.4)
http://foundation.zurb.com/sites/docs/top-bar.html works fine on my side too. 
but i confirm i can see the bug reported in http://foundation.zurb.com/forum/posts/46947-top-bar-disappears-on-dropdown-hover-out

**Comment by pine3ree** [comment]
does this work for you?

https://jsfiddle.net/uqc9bx1f/

**Comment by alen12345** [comment]
@pine3ree 
Hello maks,
many thanks for your time. Your fiddle is working perfectly fine for me.

The issue is not related to foundation-sites but arises due to a conflict with mootools which is automatically loaded by the backend of the site I am working on. Disabling mootools solves the problem.

The issue can be closed since it is only affecting this specific conflict.

**Comment by pine3ree** [comment]
@alen12345 
I am glad you solved your iss
ue!

If you need both jQuery and mootools you can use an IIFE

```js
jQuery.noConflict();

(function ($) {
    // $ is jQuery here

    // cache jQuery object for window.document
    var $document = $(document);

    // init foundation js
    $document.foundation();

    // other stuff
    $document.ready(function () {
        //...
    });
}(jQuery));
```

or if you only need to handle document ready

```js
jQuery(function ($) {
    // $ is jQuery here
});
```
kind regards
