### ISSUE TITLE
[Reveal] $('#element').foundation('open') Does Not Open

### ISSUE THREAD

**Issue by nathanh0** [zurb/foundation-sites#9154]
**How can we reproduce this bug?**

1. Install Foundation
2. Use Foundation
3. Try your modal demo

**What did you expect to happen?**
I expected it to work. When I use it, it says "We're sorry, blah blah blah, the "open" method is not accessible or something", I think you guys know what it will say.

**What happened instead?**
I have to use this instead: 
var modal = new Foundation.Reveal($('#modal'));
modal.open();

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by nathanh0** [comment]
Version 6.2.3 - has been a nightmare.

**Comment by coreysyms** [comment]
If you are just trying to open a revel use `$('#element').foundation('open');` Your example code is creating a new instance of Reveal.

Step 1. Create your Reveal Div
`<div class="reveal" id="exampleModal1" data-reveal>`
  `<h1>Awesome. I am a Reveal</h1>`
  `<button class="close-button" data-close aria-label="Close modal" type="button">`
    `<span aria-hidden="true">&times;</span>`
    `</button>`
`</div>`

Then call your reveal div by its ID to open, close, toggle, or destroy.

` $("#exampleModal1").foundation("open"); `

**Comment by nathanh0** [comment]
Hey sorry for sounding like a dick - Just struggling with the changes very quickly. Someone dropped a "We've upgraded to F6, no rush though, we have till next wednesday to upgrade your apps" -- And I'm on vacation next week.

I have only been able to use Foundation Open when instantiating the Class (new Foundation.Method()).

It may be due to the fact that my application runs "after" document.foundation() is run. This is all happening in a Reveal Modal, and previously it was handling it on its own, but I'm guessing something changed in our setup.

If I tell foundation this:

Element:   $('#element')
Call:   .foundation("open")

but I haven't run $(document).foundation()

Couldn't foundation be smart enough to figure out that the element "needs" foundation, and check its classes for "reveal" etc. 

Seems like that's what's going on, but even after performing things like:   $('#reveal-modal').foundation() and then $('#reveal-modal').foundation('open') still returns "We're sorry".

**Comment by coreysyms** [comment]
If you initialize Foundation before you have elements in the DOM to initialize on then Foundation won't initialize anything. Your logic either needs to:

1. Wait to render before initializing Foundation, so just call `$(document).foundation();` later.
2. Write logic to look for the existence of `data-reveal` attribute on the reveal div, if there is use `$("#exampleModal1").foundation("open");` else use `var modal = new Foundation.Reveal($('#exampleModal1'));` to initialize it. But only after you have initialized the Foundation framework.

You can't expect the framework to look for something that either doesn't exist or the framework itself isn't initialized.
