### ISSUE TITLE
F6 - Tooltip reInit doesn't work

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#9156]
After appending a new tooltip to a div using jQuery, I tried to re-intialize the tooltips but for the new tooltip it is not wotking. (No errors in console)

`$('#div').append('<label class="label alert has-tip right" title="Test" data-tooltip aria-haspopup="true">Test tooltip</label>');`
`Foundation.reInit('tabs', 'tooltip');`

**Comment by Silvester20** [comment]
@isaak-ordonez  Thanks for the reply. Your way works fine so for now I will use this! However, Zurb should fix this issue in the next release ofcourse.

**Comment by markadrake** [comment]
I tend to agree with @Silvester20 on this one. Does this codepen represent what you were trying to do? Essentially you want to add additional labels to that page, and calling the **reInit** function should of course initialize any new items on the page. 

https://codepen.io/anon/pen/kkXWrk

You'll see that a console error comes up each time the button is clicked - adding a new label to the page and calling the reInit function immediately proceeding the append.

Can't debug tonight, but maybe over the weekend.

**Comment by IAmEddieDean** [comment]
This isn't an issue with `Foundation.reInit` as that is intended to reinitialize an individual plugin element if the content has changed or some other event that should trigger reinitialization. What you are trying to do is _initialize_ a new Tooltip. I forked @markadrake 's pen and demoed how to accomplish this. https://codepen.io/anon/pen/xEXGZr?editors=1111

**Comment by Silvester20** [comment]
@IAmEddieDean awesome, thanks for the explanation!

**Comment by DanielRuf** [comment]
reInit and reflow are two options, also running `$(document).foundation();`.
