### ISSUE TITLE
Flexbox Grid - Unstacking behavior overrides shrink behavior on columns

### ISSUE THREAD

**Issue by blindside85** [zurb/foundation-sites#9157]
When I have a `.[size]-unstack` class set on my `.row` while I have any `.shrink` classes added to its `.column` children, the shrink behavior is overridden, causing the columns to resume their equally-sized sharing of the row's width, rather than taking up minimal space as desired.

**How can we reproduce this bug?**
1. While using the flexbox grid, create a row with `.medium-unstack` class applied
2. Create at least 3 columns inside the row, adding the `.shrink` class to any of them
3. Resize your browser window from below 40em to anything higher

**What did you expect to happen?**
The columns with the `.shrink` class applied would fit their contents while the other columns would expand to fill the remaining space once the medium breakpoint was reached.

**What happened instead?**
The shrinking behavior was overridden, causing the columns to all equally share the space.

**Test case:**
[CodePen demonstrating the issue](http://codepen.io/blindside85/pen/yayBaG)

**Comment by pine3ree** [comment]
@blindside85 
Hello, I don't think they are compatible. Docs about automatic stacking says:

> ...and then unstack them on a larger screen size, making each one equal-width.

i believe for these cases you need to add small-12 to make them stack for small screen, medium-expand to make them unstack for medium-up and add shrink to the columns that need to be shrinked

http://codepen.io/anon/pen/rrazLz

by default but you also get shrinked stacked columns 

kind regards

**Comment by brettsmason** [comment]
I agree that this is probably outside the use case for the classes and the workaround suggested is the way to go. Also as the flex grid is now legacy I'm going to go ahead and close this.
