### ISSUE TITLE
Sticky menu doesn't work with off canvas on small screen

### ISSUE THREAD

**Issue by qusqui21** [zurb/foundation-sites#9158]
http://codepen.io/rafibomb/pen/MyVWgE?editors=1100
I try to make same think as example show, and when you change size to small, you can see that sticky menu stops working.

**Comment by pine3ree** [comment]
@qusqui21 
Hello, try with  data-sticky-on="small" (default is medium) option inside the [data-sticky] element

**Comment by qusqui21** [comment]
That is correct, sorry for not checking. And thank you.
