### ISSUE TITLE
IE11 Bug - Breakpoint Overlap at 640px

### ISSUE THREAD

**Issue by priedthirdeye** [zurb/foundation-sites#9163]
**How can we reproduce this bug?**
1. Step one
   Visit the following plunk in IE11 and size your window to exactly 640px
   https://run.plnkr.co/plunks/20e8IP6FQji9rwqThqXh/

You will see both the "show-for-medium" element AND the "hide-for-medium" element visible at the same time.

Note that this issue occurs on foundation.zurb.com as well.

**What did you expect to happen?**

There should be no window size possible that renders both of those elements at the same time. This appears to be specific to IE11

**What happened instead?**

Both elements were presented when the window is exactly 640px

**Test case:**

https://run.plnkr.co/plunks/20e8IP6FQji9rwqThqXh/

![foundationbug](https://cloud.githubusercontent.com/assets/5795993/18318659/87d49516-74f0-11e6-93e6-26f75a61ba88.png)

**Comment by markadrake** [comment]
I imagine that IE11 is having issues distinguishing between **39.9375em** and **40em**.

It seems like you have the opposite of the [gap effect here](http://foundation.zurb.com/forum/posts/22514-breakpoint-pixel-gap), you actually have an overlapping issue. 

I won't be on my Windows machine until tomorrow, but I'll try to look at thing more closely then. Could you tell me if you have any settings on your browser other than the default please? Font sizes and zoom are both important to know here.

**Comment by markadrake** [comment]
I have it on good authority that the em value should be at least **0.1** difference between breakpoints. I'll try to look at this tomorrow and offer a PR if it hasn't already been done.

**Comment by andycochran** [comment]
I think this is related to #8811.

**Comment by andycochran** [comment]
Closing in favor of #8811, which has a few ideas for how to fix this issue.
