### ISSUE TITLE
[Accordion Menu] RTL wrong arrow position

### ISSUE THREAD

**Issue by shalawani84** [zurb/foundation-sites#9167]
1. I use RTL veriosn of zurb foundation 6
2. I use Accordion Menu

**I expect to see arrows on the left side of the menu**

**The arrows appears on the right side over the menu items text**

![image](https://cloud.githubusercontent.com/assets/7045417/18381375/91266cd0-7684-11e6-890c-3e8873e96f62.png)

**Comment by Owlbertz** [comment]
Hi @shalawani84, would it be possible for you to create a [Codepen based on this template](http://codepen.io/rafibomb/pen/xVVGOB) that reproduces your issue?

**Comment by andycochran** [comment]
I can confirm this issue. 
http://codepen.io/andycochran/pen/QGbEEE 

It's because `_accordion-menu.scss` uses `right:1rem` instead of `$global-right:1rem`.

I'll fix…
