### ISSUE TITLE
[Button Group] NO EVEN WIDTH BUTTONS

### ISSUE THREAD

**Issue by tonister** [zurb/foundation-sites#9170]
**How can we reproduce this bug?**

1. Add 5 buttons to the expanded button-group and see it works
2. Now add 2 more buttons to the expanded button-group and see it is broken

**What did you expect to happen?**

For starters I expected the expanded button-group to work with more than 5 buttons in it

**What happened instead?**

It doesn't work.

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.

- [CodePen with Foundation 6 and Expanded Button-group with less than 6 buttons](http://codepen.io/rafibomb/pen/grqOvW)
- [CodePen with Foundation 6 and Expanded Button-group with more than 6 buttons](http://codepen.io/tonister/pen/qaObbp)

**Comment by isaak-ordonez** [comment]
This is not a bug.  

You can change the default value on **settings.scss** 

```
// 12. Button Group
$buttongroup-expand-max: 6;
```

**Comment by tonister** [comment]
OH, okay.
Is there a mention of this somewhere in the docs, so people new to foundation could easily find out how to fix/modify this? 
I googled around and was unable to find any tips on it.
Cheers for making it clear.

**Comment by isaak-ordonez** [comment]
yes it is. Here is the link:
 http://foundation.zurb.com/sites/docs/button-group.html#sass-reference
