### ISSUE TITLE
[Off-canvas] code example needed for closing the offcanvas menu with anchor links (onepager)

### ISSUE THREAD

**Issue by moonbeetle** [zurb/foundation-sites#9179]
Just following the online docs for the offcanvas menu didn't help me to find a working solution on how to close the offcanvas menu when clicking #anchor links.

**Comment by Silvester20** [comment]
You can use "data-toggle" on the href element

**Comment by brettsmason** [comment]
@moonbeetle Did you manage to get this working? Is there any other way we can help to close this issue?

**Comment by moonbeetle** [comment]
Hi,

No, I’m sorry. In the end I just replaced that off-canvass menu for a more simplified overlay navigation.
Sure you can close that.

Regards,

Joris
