### ISSUE TITLE
autoprefixer config in template needs update

### ISSUE THREAD

**Issue by kball** [zurb/foundation-sites#9181]
Our autoprefixer config is in both the zurb template and the foundation-sites-template needs an update to better support ios.

Our config in theory handles 2 versions back, but in practice seems to cause some issues for ios8.  For some client projects we've explicitly added `ios >= 7` even though we are only targeting 8 & 9.

Not sure if this is an autoprefixer bug or if it would be sufficient to add `ios >=8`.  Should verify that and then update these templates.

(cc @andycochran based on involvement on #9077)

**Comment by rickcurran** [comment]
Yep, I've had issues with this too, iOS 8 still requires the webkit prefix for transforms, so code like `transform:translate(-50%,-50%);` wouldn't work on iOS8.

**Comment by andycochran** [comment]
I see no problem with adding `ios >= 7` to autoprefixer, even though the framework only supports `>= 8`. Perhaps an inline note would be enough to avoid confusion: 

```js
autoprefixer({
  browsers: ['last 2 versions', 'ie >= 9', 'ios >= 7', 'and_chr >= 2.3']
  // iOS 7 is not supported by the framework, but is needed for autoprefixer 
});
```

**Comment by kball** [comment]
This has been fixed.
