### ISSUE TITLE
this.winHeight not getting correct value (Chrome/FF) in Magellan

### ISSUE THREAD

**Issue by andrewhinde** [zurb/foundation-sites#9182]
Platform: Windows 10 64 bit
Foundation Version: Noticed in both 6.2.1 and 6.2.2

When using console.log on the value of this.winHeight in Magellan's _updateActive function, Chrome (53.0.2785.116) and Firefox (48.0.2) both return the full document height instead of the viewable height.  I think this is caused by the calculation of html.clientHeight, and the fact that when setting this.winHeight, it takes the higher value of window.innerHeight and html.clientHeight.

With the higher value being set on initialization of Magellan, it thinks the document is at the bottom of the page, and will set the last Magellan link as the active link.  Scrolling down will calculate properly, but scrolling to the top of the page again recreates this issue.

I modified calcPoints() in Magellan from:
this.winHeight = Math.round(Math.max(window.innerHeight, html.clientHeight));
to
this.winHeight = window.innerHeight;
and everything works as intended in Chrome 53.0.2785.116 , Firefox 48.0.2, and IE Edge (where it had previously worked properly).

I've attached 2 files.  The first shows the state on initialization. The second is after scrolling down.

![magellan_default](https://cloud.githubusercontent.com/assets/8227269/18595636/9f94daa6-7c13-11e6-96b7-fc96c37ef05f.png)
![magellan_default_2](https://cloud.githubusercontent.com/assets/8227269/18595635/9f936234-7c13-11e6-8b02-dcee7c4d1774.png)

**Comment by DanielRuf** [comment]
Closing as this was in an old version and we have no codepen to reproduce this.
