### ISSUE TITLE
[Visibility Classes] Doesn't work

### ISSUE THREAD

**Issue by javierandresmesa** [zurb/foundation-sites#9184]
**How can we reproduce this bug?**

1. Please use any visibility class (hide-for-large, hide-for-small)
2. Please use any visibility class (show-for-large, show-for-small)

**What did you expect to happen?**
I expect the element hide or show in small devices

**What happened instead?**
Nothing

Why you eliminated the Foundation 5 classes xxx-for-xxx-up? what can i do with these classes in order to upgrade my html from 5 to 6?

Thank you in advance

**Comment by isaak-ordonez** [comment]
Hi @javierandresmesa,

> There's no .hide-for-small class, because that would just permanently hide the element. For that, you can use the plain old .hide class instead.

The classes are working well: http://codepen.io/kaasi/pen/rrLpvB

**Comment by kultz** [comment]
you might need to use `hide-for-small-only` or `show-for-small-only` instead

**Comment by cesaboss** [comment]
another problem is that even the large tag has a limit but xlarge doesn't work anymore and it's not likeable to see hide-for-xxx many times.

**Comment by markadrake** [comment]
@javierandresmesa To migrate your classes from Foundation 5 `show-for-xxx-up` to Foundation 6 `show-for-xxx` just find the equivalent functionality and do a text-find and replace.

- You'll find that the old style includes the postfix `-up` that simply needs to be removed (I think).
- Foundation 6 retained the `-only` postfix.
- Did Foundation 6 remove some breakpoints too? You may need to review your classes and QA your design across breakpoints again. I don't see anything mentioned for `xlarge` and up.


@cesaboss Could you explain your comment further please? I didn't quite understand it. It's definitely **not** fun to write or to see `hide-for-xxx` numerous times on an element.

- I see that if you use the **show-for-xxx** then your DOM element will show for _that breakpoint and larger_.
- I see that if you use the **hide-for-xxx-only** then your DOM element will be hidden _only for that breakpoint_.

In what scenario do you need to use multiple **hide** or multiple **show**? I've never ran into the case where I'm showing something at a small breakpoint only for it to hide at medium and show again at large.

**Comment by cesaboss** [comment]
@markadrake yea, as you said you can fix the problem by simply not using the "-only" in "show-for-large" but the fact is that if higher resolutions were contemplated in F5 then why not using the anymore.
I was only thinking about that because i'd like to let 21:9 monitors see my site in a different way but i can create a class by myself, that's not a serious problem.

**Comment by kball** [comment]
This looks like not an actual issue. Foundation 6 is different than Foundation 5, please refer to the documentation to understand available visibility classes: http://foundation.zurb.com/sites/docs/visibility.html
