### ISSUE TITLE
Proper sort of Grids

### ISSUE THREAD

**Issue by kultz** [zurb/foundation-sites#9185]
I have a problem with sorting grids as you see in the picture below, Green box pushes the Red box down:
![This is what i've done](http://i.cubeupload.com/q27PHD.png)

But actually i need something like this:
![This is what i want](http://i.cubeupload.com/G8ZDDG.png)

I would appreciate if anyone help to solve my problem. (grid classes included in the images)

**Comment by abdullahsalem** [comment]
Hi @kultz ,
Check out this basic layout http://codepen.io/abdullahsalem/pen/qaNrOO, however you can also nest more grids inside those initial columns (red, green and blue).
Let me know if that helps you, please.

**Comment by kultz** [comment]
@abdullahsalem Ok, nice solution. But the trick done with extra classes of "column row". Would you please explain how does it work ?

**Comment by abdullahsalem** [comment]
I believe that it is a convenient way to achieve the layout you drew more than it is a "trick" 😃, and to learn more about layouting using Grids component, check out these resources:
- http://foundation.zurb.com/sites/docs/grid.html
- https://www.youtube.com/playlist?list=PLKlA1QwYBcmfA0tIwFL_LqDeb7EGwo3xu
