### ISSUE TITLE
Off canvas open method overlap for f6

### ISSUE THREAD

**Issue by hoscb** [zurb/foundation-sites#9186]
Hi,

I'm having a bit of problem trying to implement overlap menu for foundation 6. This was a feature in  foundation 5 using:

`$(document).foundation({
  offcanvas : {
    // Sets method in which offcanvas opens.
    // [ move | overlap_single | overlap ]
    open_method: 'move', 
    // Should the menu close when a menu link is clicked?
    // [ true | false ]
    close_on_click : false
  }
});`

I appreciate if anyone can point me to the right direction or documentation. I'm trying to achieve something similar to http://www.dtelepathy.com/

Thanks.

**Comment by brettsmason** [comment]
Hi @hoscb 
Currently this isn't a feature of F6. However I am working on a complete re-write on the off canvas menu system with the aim for inclusing in 6.3 (RC is due to be released next month), and this is one of the features included. I'll update this ticket when I have something I can share with you to test if you would be interested?

**Comment by hoscb** [comment]
Hi Brett,
Thanks for the reply.
Currently I'm using another off-canvas menu.
Sure, would love to test the new feature if is ready and available.

Cheers

**Comment by brettsmason** [comment]
@hoscb The PR for off canvas is now up here: https://github.com/zurb/foundation-sites/pull/9357
Its still got some things to iron out, but the overlap option is working nicely. 
Feel free to test it - I'd welcome the feedback.

**Comment by brettsmason** [comment]
Off canvas has been completely reworked for 6.3 and this issue should now be solved as there is a new `overlap` transition option.
Release candidate is out today, witht he full release scheduled for the 15th December.

Closing this, but if you still have issues with 6.3 please re-open.
