### ISSUE TITLE
'HTML Starter Template' paths needed updating

### ISSUE THREAD

**Issue by martinlugton** [zurb/foundation-sites#9188]
Installed Foundation on node via npm, and the paths given in the "HTML Starter Template" on http://foundation.zurb.com/sites/docs/installation.html were incorrect.

I amended them to the following:

```
<link rel="stylesheet" href="dist/foundation.css" /> 
<script src="vendor/jquery/dist/jquery.min.js"></script>  
<script src="node_modules/what-input/what-input.min.js"></script>   
<script src="dist/foundation.min.js"></script>
```

Related issue: https://github.com/zurb/foundation-sites/issues/9150

**Comment by martinlugton** [comment]
In case it's useful, I've pulled together a skeleton node.js app with foundation, and with the updated paths above: https://github.com/martinlugton/foundation_express_node_heroku

**Comment by brettsmason** [comment]
This has been addressed in a docs update so closing this.
