### ISSUE TITLE
span.form-error will not get is-visble class with input type="submit"

### ISSUE THREAD

**Issue by Lazerproof** [zurb/foundation-sites#9190]
Here is the codepen example with two forms. 
Form with button works great, but form with input.type=submit works partialy.
Form is validated, but form-error span is not shown because is-visible class was not applyed to that span. 

http://codepen.io/anon/pen/BLLdGV

**Comment by denisahac** [comment]
Upon further testing, it turned out that you need to wrap the `<input class="button" type="submit" value="Submit">` with the `<fieldset>` group element tag. Hmmmmm.

**Comment by kobrix** [comment]
@denisahac thanks for the solution. I just encountered the same problem and can confirm that wrapping in `<fieldset>` solves it for `<input>` button. Furthermore, it looks like all form fields must be in field sets to enable the `form-error` to be revealed, but the `<input>` doesn’t actually need to be contained within the _same_ `<fieldset>` as the field being validated.

**Comment by colin-marshall** [comment]
> Furthermore, it looks like all form fields must be in fieldsets to enable the `form-error` to be revealed

@ncoden according to the docs this isn't true for _all_ form fields, like text inputs, right?

**Comment by ncoden** [comment]
@Lazerproof @denisahac @kobrix See the documentation:

> Abide automatically detects Form Errors of an input by their class (.form-error by default, see the formErrorSelector option) when they are siblings of the input or inside the same parent.
>
> When the Form Errors cannot be placed next to its field, like in an Input Group, the relation can be declared with [data-form-error-for] attribute.
>
> -- https://foundation.zurb.com/sites/docs/abide.html#form-errors

This is true for all validated input. Abide will look for `form-errors` next to them and explicitly defined errors `[data-form-error-for]`.

**Comment by ncoden** [comment]
hmmm, actually that's a bug, I did not read the issue correctly at first.

**Comment by ncoden** [comment]
Here are the result of my research. Abide does display the input error correctly, but then consider `input[type=submit]` as a field - without errors - and hide all related errors (even if already "used" by others fields). So a fix could be to:
* Ignore `submit[type=text]` in validation
* Only consider direct childs as related errors and prevent an error to be related to several fields.
