### ISSUE TITLE
Missing info on docs: ResponsiveToggler event

### ISSUE THREAD

**Issue by diniscorreia** [zurb/foundation-sites#9191]
The documentation for Responsive Navigation includes the event `toggled.zf.responsiveNavigation` but omits the specific event triggered by ResponsiveToggler, `toggled.zf.responsiveToggle`.

Should probably be included in the docs, otherwise it seems `toggled.zf.responsiveNavigation` is also triggered with the ResponsiveToggler.

**Comment by schmalli** [comment]
And still no word of it in the docs 🙄

**Comment by colin-marshall** [comment]
This is something to tackle when we revisit the events in #10155

**Comment by DanielRuf** [comment]
This is fixed with https://github.com/zurb/foundation-docs/pull/24/files

![image](https://user-images.githubusercontent.com/827205/36398908-a59df512-15c9-11e8-9bb3-ac095cfdcac9.png)

**Comment by ncoden** [comment]
This was added to `foundation-sites` at https://github.com/zurb/foundation-sites/pull/10942

**Comment by DanielRuf** [comment]
Right. I'll close this issue then as this should be resolved then.
