### ISSUE TITLE
Bad html in Accordion documentation in Kitchen Sink

### ISSUE THREAD

**Issue by stelovsky** [zurb/foundation-sites#9194]
**How can we reproduce this bug?**
1. [http://foundation.zurb.com/sites/docs/kitchen-sink.html#accordion](http://foundation.zurb.com/sites/docs/kitchen-sink.html#accordion)
2. Toggle Code
3. stare at the carelessly cut-and-paste html in wonder asking "is these guys' claim to fame really a web framework"?  (Sorry for the sarcasm:) - But seriously, I just came to Foundation as a newbie hoping that it will be my UI of choice, but seeing such careless code makes me thing twice...). 

**What did you expect to happen?**
See correct html (and, code as described in comments)

**What happened instead?**

1) 
But all tab title 'a's have the same ID "panel1d-heading" (illegal, even though the browsers accept it).

2) Also, all "accordion-content" 'div's have the same ID "panel1d"

3) Of course, the href="#panel1d" will have to be different as well...

4) And, it would be nice if the tabs were called "Accordion 1", "Accordion 2", and "Accordion 3" and not just all of them "Accordion 1"

HTML:

<ul class="accordion" data-accordion role="tablist">
  <li class="accordion-item is-active">
    
    <a href="#panel1d" role="tab" class="accordion-title" id="panel1d-heading" aria-controls="panel1d">Accordion 1</a>
    
    <div id="panel1d" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="panel1d-heading">
      Panel 1. Lorem ipsum dolor
    </div>
  </li>
  <li class="accordion-item">
    
    <a href="#panel1d" role="tab" class="accordion-title" id="panel1d-heading" aria-controls="panel1d">Accordion 1</a>
    
    <div id="panel1d" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="panel1d-heading">
      Panel 2. Lorem ipsum dolor
    </div>
  </li>
  <li class="accordion-item">
    
    <a href="#panel1d" role="tab" class="accordion-title" id="panel1d-heading" aria-controls="panel1d">Accordion 1</a>
    
    <div id="panel1d" class="accordion-content" role="tabpanel" data-tab-content aria-labelledby="panel1d-heading">
      Panel 3. Lorem ipsum dolor
    </div>
  </li>
</ul>

**Comment by abdullahsalem** [comment]
Thank you for this notice, @stelovsky!
I agree with you, all code examples should be valid to ease the developer work, however this framework (**Foundation**) and other open source projects do live here to be regularly developed and fixed by awesome contributors like you, and we would be glad to review your contributions anytime.

**Comment by karland** [comment]
I addressed this in [PR #9329](https://github.com/zurb/foundation-sites/pull/9329).

**Comment by IamManchanda** [comment]
Been adressed again #9882 
( sad that this above PR by @karland wasn't merged till date )

**Comment by kball** [comment]
Clsoed by https://github.com/zurb/foundation-sites/pull/9329
