### ISSUE TITLE
Reveal is outputting debug message to console

### ISSUE THREAD

**Issue by silentmiles** [zurb/foundation-sites#9196]
Reveal is writing "focus" to the console log in the `open()` method: `console.log('focus');` I assume this is a debug message which should not have been included in a production build.

**Comment by abdullahsalem** [comment]
Thanks @silentmiles,
It has been already fixed here https://github.com/zurb/foundation-sites/commit/1e0a3d4da95f25427058d9908fee26be8c75b2c1
