### ISSUE TITLE
Add KSS Documentation

### ISSUE THREAD

**Issue by RobLoach** [zurb/foundation-sites#9200]
[KSS](http://warpspire.com/kss/) provides a way to add CSS documentation, allowing you to expose the components directly in a styleguide, automagically.
## Description

I'd like to see KSS documentation to all the components in Foundation.
## Steps to reproduce the issue
1. Install a KSS client (like [kss-node](https://github.com/kss-node/kss-node))
2. Run KSS on the Foundation source
3. See that the Foundation components are not part of the styleguide
## Additional information

To add KSS documentation directly to the source, we would pretty much write CSS docs for each available component, copying them from the official styleguide, directly inline with the SCSS itself. Then, you could expose each component in a KSS styleguide.

**Comment by Owlbertz** [comment]
Hi @RobLoach, thank you for this suggestion. As we are using gulp, we would most likely add KSS to our gulpfile. Do have any experience with [gulp-kss](https://www.npmjs.com/package/gulp-kss)?

**Comment by RobLoach** [comment]
@Owlbertz At this point, I was just looking to add the KSS documentation, without having the Gulp process in place to build out of the styleguide. Just the CSS docs for now.

Looks like gulp-kss needs an update. I'll see what I can do.

**Comment by colin-marshall** [comment]
@RobLoach we're not adding any features to Foundation 6 so I'm closing this out. Since this is just docs, if you want to put in a PR for it for F6, we can reopen the issue and get it in. If not, we'll revisit for F7 when the time comes. Thank you.
