### ISSUE TITLE
$breadcrumbs-item-color-current	does not appear to do anything. 

### ISSUE THREAD

**Issue by ken-spencer** [zurb/foundation-sites#9203]
Looking at the code, 

  li {
    float: #{$global-left};
    color: $breadcrumbs-item-color-current;

...
}

  a {
    color: $breadcrumbs-item-color;
   }

Setting the color on the LI doesn't seem to do anything as the color is overridden on the A.

**Comment by abdullahsalem** [comment]
@ken-spencer By default, `$breadcrumbs-item-color-current` takes this initial value `$black`, the `$black` is also the default value for the global color, therefore your `li`'s color is still black (`$black`) even if you pass `$breadcrumbs-item-color-current` to it, unless you change the color of `$breadcrumbs-item-color-current` then it will hold the new color wherever you use it.

**Comment by ken-spencer** [comment]
@abdullahsalem don't see how this could override $breadcrumbs-item-color on the a tag.

**Comment by natewiebe13** [comment]
The idea is the current item won't be a link. There is an example of the markup here: http://foundation.zurb.com/sites/docs/breadcrumbs.html

**Comment by ken-spencer** [comment]
Thanks, makes sense now, apologies for bogus report.
