### ISSUE TITLE
[ABIDE][Docs] Should include list of available patterns

### ISSUE THREAD

**Issue by Yanchek99** [zurb/foundation-sites#9205]
I belive the abide documentation should provide a list of available patterns that are included with abide.

 alpha,
alpha_numeric,
integer,
number,
card,
 cvv,
email,
url,
domain,
datetime,
date,
time,
dateISO,
month_day_year,
day_month_yea,
color

**Comment by HediMaiza** [comment]
Hi.
It's true, even if we can find this information in the foundation.js file :

https://github.com/zurb/foundation-sites/blob/develop/js/foundation.abide.js#L493

**Comment by karland** [comment]
I was also missing this a number of times. So I just added [PR #9328] (https://github.com/zurb/foundation-sites/pull/9328).

**Comment by kball** [comment]
Fixed by #9328. Thanks @karland!
