### ISSUE TITLE
Foundation 6 Accordion - Panel not loading closed

### ISSUE THREAD

**Issue by demo38** [zurb/foundation-sites#9217]
Using Foundation 6 complete download with Accordion with just one accordion panel, and wanting the panel to load closed initially. I've followed the docs and using:

```
<ul class="accordion" data-accordion data-allow-all-closed="true">
  <li class="accordion-item" data-accordion-item>
    <a href="#" class="accordion-title">Link Here</a>
    <div class="accordion-content" data-tab-content>
      Content here...
    </div>
  </li>
</ul>
```

I've removed the "is-active" class and added data-allow-all-closed="true", but the panel still loads active upon page load.

Seems it should load closed based on the docs?

Thanks,
Jonathon

**Comment by Deckluhm** [comment]
It works as expected for me using the Foundation 6 complete download (and using Foundation CDNs as you can see in [this CodePen](https://codepen.io/anon/pen/KgvYdj?editors=1010)).

Can you provide a CodePen that reproduces what you describe?

**Comment by demo38** [comment]
Thank you for testing so quickly - I'll download again, I may be running 
6.2.2 and I see that 6.2.3 is out now.


Jonathon Harris, ASAI
demo38 ltd – design visualization
Finding good homes for stray pixels since 1998
c: 614.581.8451
www.demo38.com <http://www.demo38.com> | demo38@demo38.com | 
mailing-list <http://eepurl.com/jci19> | twitter 
<https://twitter.com/demo38> | facebook 
<https://www.facebook.com/demo38ltd> | linkedin 
<http://www.linkedin.com/in/jonathonharris>


Arnaud Thomas Desessarts wrote:

**Comment by Owlbertz** [comment]
@demo38 Were you able to check your version?

**Comment by demo38** [comment]
Yes, thank you for following up - I switched to v6.2.3 and had the same issue - finally tracked down that it was my CSS - I had placed a display:block; on accordion-content so that I could center it, and that was causing the issue with it appearing upon load.

Thanks again,
Jonathon
