### ISSUE TITLE
.menu-icon.dark repeated twice

### ISSUE THREAD

**Issue by erredeco** [zurb/foundation-sites#9230]
As far as I can see, the `.menu-icon.dark` class is repeated twice; it is inserted by:

components/_menu-icon.scss
components/_title-bar.scss

How to reproduce: simply download the complete css file and search for `.menu-icon.dark`

**Comment by ncoden** [comment]
Thank you. I didn't found any reasons for this code duplication. It should be a mistake.

PR: https://github.com/zurb/foundation-sites/pull/9241
