### ISSUE TITLE
JS Files contain improper characters

### ISSUE THREAD

**Issue by iansvo** [zurb/foundation-sites#9231]
After cloning the repo, I was attempting to minify/combine files, but I was met with failure due to a few invalid characters.

These are found throughout the JS files in the repo.

Example:

foundation.core.js Line 56

    if(!plugin.$element.attr(`data-${pluginName}`)){ plugin.$element.attr(`data-${pluginName}`, plugin.uuid);

Effectively, single quotes appear to be inconsistently replaced with backticks.

For instance, the next line (Line 57) uses single quotes as expected:

`if(!plugin.$element.data('zfPlugin')){ plugin.$element.data('zfPlugin', plugin); }`

**Comment by patrys** [comment]
Backtics are JavaScript [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). They are valid ES6 syntax.

**Comment by iansvo** [comment]
Ok. That explains my issue. Thanks!
