### ISSUE TITLE
IE issue equalizer & media queries

### ISSUE THREAD

**Issue by sanderha** [zurb/foundation-sites#9237]
I'm using data-equalizer on 2 columns. Just inside of each column is an <a> tag with height 100%, so it fills up the column. This <a> has padding: 30px 20px; and padding: 60px; on large. For some reason when this padding 60 breakpoint is included in the css, equalizer is not calculated properly on init, on large, in Internet Explorer. I'm using Foundation 6.1.2, and im using SASS.

The problem can be viewed here: [http://din-fonsterputsare.vps3.nobrainer.dk/priser/](url)

**How can we reproduce this bug?**
1. Visit url in IE11. You'll notice that the 2 big blue boxes are equally in height and the content fits inside. 
2. Click on "Priser" in the top navigation. The 2 blue boxes should not be a little messed up, some of the content should be flowing over the bottom.
3. Resizing, refresing (F5) or opening the dev tools will trigger a correct recalculation. 

**What did you expect to happen?**
Columns to be calculated correct height

**What happened instead?**
Wrong calculation, content overflows.

**Test case:**

[http://din-fonsterputsare.vps3.nobrainer.dk/priser/](url)

Broken example : [https://postimg.org/image/8mr3r4hdp/](url)

**Comment by colin-marshall** [comment]
Since this is from an older version of Foundation and the test cases are no longer up, I'm going to close it out. @sanderha feel free to reopen if it's still an issue.
