### ISSUE TITLE
Foundation.reInit('orbit') works incorrectly

### ISSUE THREAD

**Issue by swiftanthony** [zurb/foundation-sites#9245]
See example http://codepen.io/anon/pen/JRLxyX

The issue is in foundation.orbit.js _events() method.
Navigation buttons do not unregister events so when doing re-init the events will be attached again.

For now I am detaching events manually before calling reInit(): 

```
$orbit.off('.zf.orbit').find('*').off('.zf.orbit')
Foundation.reInit($orbit)
```

**Comment by milose** [comment]
@swiftanthony can you confirm #9278 works?

**Comment by swiftanthony** [comment]
@milose Yes. this commit fixes the issue

**Comment by kball** [comment]
Fixed.  Thanks @milose!
