### ISSUE TITLE
[Off-Canvas and Sticky] Sticky Header and Off-Canvas Menu Functionality Issues

### ISSUE THREAD

**Issue by darinronne** [zurb/foundation-sites#9249]
Using Foundation 6 v6.2.3, my site has a header that uses the Sticky plugin and Off-Canvas for the menu.

**Test case:**

http://codepen.io/darinronne/pen/RGybxk

**In Edge, Chrome and Firefox:**

Issue 1
1. Toggle the menu open.
2. Slowly start to scroll down. You will see the top bar jump to the left, creating a gap between the top bar and the off-canvas menu.
3. When you scroll back to the top, the top bar will shift back to the right, closing the gap.

Issue 2
1. Toggle the menu open.
2. Scroll down the page so that the top bar is no longer in view.
3. Click on the content to close the off-canvas menu. 
4. The top bar will reappear, but it will be shifted to the left.

Issue 3
Firefox is not jumping to the top of the page when the off-canvas is opened.

**In IE 10+:**

Issue 4
1. Toggle the menu open.
2. Start to scroll down. The top bar stays sticky. In Edge, Chrome and Firefox the top bar scrolls with the page.
3. Close the off-canvas menu (when further down the page). The top bar will stay shifted to the left, and won't correct itself until you scroll back to the top.

Issue 5
1. Start further down the page, then toggle the off-canvas open. The page does not jump to the top. Also the top bar does not shift over. It fills the entire width of the browser and overlaps the off-canvas menu.
2. Scroll to the top of the page. The top bar will shift to the left where it should be.

**What did you expect to happen?**

I expected the sticky header with off-canvas menu to work consistently across browsers.

I would think it should work like this:
1. Toggle open off-canvas menu.
2. The page jumps to top with the menu open. The top bar is in the correct position and scrolls with the page.
3. Closing the off-canvas menu returns the top bar to its starting position.

Thanks.

**Comment by brettsmason** [comment]
Off canvas and sticky should now play nicely for 6.3, as off canvas has been rewritten.
Release candidate is out today, with the full release scheduled for the 15th December.

Closing this, but if you still have issues with 6.3 please re-open.
