### ISSUE TITLE
React and reveal: Set own overlay

### ISSUE THREAD

**Issue by shtalinberg** [zurb/foundation-sites#9263]
Hi,  
I try use foundation with React 
I have a problem in reveal modal component with overlay
I want create dynamic modal component and have code 

```
  wrapper = document.body.appendChild(document.createElement('div'));
  wrapper.className = "reveal-overlay"
  component = ReactDOM.render(<ZfConfirmModal {...props}/>, wrapper);
```

in componentDidMount

```
componentDidMount() {
    this.reveal = new Foundation.Reveal($('#'+this.props.id));
}
```

But after initial my overlay ignored and created new overlay and all code from my overlay moved to new  - it's destroy React virtual DOM

Maybe you can  change   _makeOverlay  method and allow use own overlay via options in this place https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L85 ?

**Comment by kball** [comment]
Broadly speaking, we don't expect the Foundation Javascript to play super nicely with React, as React expects to have complete control of the DOM.  Have you checked out https://github.com/aruberto/react-foundation-components ?  It is a reimplementation of Foundation JS components within react

**Comment by shtalinberg** [comment]
I try use reveal to create dynamic confirm modal component and I have problem only with overlay after initial. 
If I will have possible use own overlay in component - it's will be nice for play with React for reveal

**Comment by jefsnare** [comment]
@shtalinberg I would suggest turning off overlay with `data-overlay="false"` and adding your own overlay by listening to `open.zf.reveal` and remove the overlay by listening to `closed.zf.reveal`.

**Comment by shtalinberg** [comment]
Thanks, I'll try

**Comment by jefsnare** [comment]
@kball Agree with that, could we close this issue?
