### ISSUE TITLE
Foundation 6 - Issue with Sticky dynamically added, each within its own anchor element

### ISSUE THREAD

**Issue by AidamUnlimited** [zurb/foundation-sites#9264]
Hey,

I've been trying to solve this Sticky issue for the past month.

Foundation sticky div doesn't work when you have multiple sticky added dynamically after page load.

So when you dynamically add a new `<section data-sticky-parent>` with `<div data-sticky>` inside it, it won't work and stick to its parent.

**Comment by zurbrandon** [comment]
Hey! Was this fixed with the latest update? We pushed a bunch of sticky fixes.

**Comment by colin-marshall** [comment]
Closing this out since there was no reply. @AidamUnlimited feel free to reopen if you still have issues. Thanks.
