### ISSUE TITLE
Documentation of smart-scale function is not accurate

### ISSUE THREAD

**Issue by danielnarey** [zurb/foundation-sites#9265]
In `/scss/util/_color.scss`, the documentation for the function `smart-scale` says that it "Scales a color to be lighter if it's light, or darker if it's dark." Actually, as the function is written, it does the opposite: it scales a color to be **darker** if it's light and **lighter** if it's dark.

**Comment by karland** [comment]
Corrected in [PR#9330](https://github.com/zurb/foundation-sites/pull/9330).

**Comment by kball** [comment]
Fixed by #9330.
