### ISSUE TITLE
FS6 available installer versions out of sync

### ISSUE THREAD

**Issue by user58258** [zurb/foundation-sites#9270]
at

  https://github.com/zurb/foundation-sites

FS6 is available via npm installer @ version == 6.2.4rc2

but via bower only at version == 6.2.3

**Comment by kball** [comment]
This has been resolved

**Comment by user58258** [comment]
@kball 

Once again, now,

FS6 is available via npm installer @ version == 6.3.0.rc2
but via bower only at version == 6.2.4

Is this to be regularly the case? That pkging systems are NOT kept in sync?

Some clarification of simply what to expect would be really helpful.

Different devs use different package mgmt tools; not being able to keep them on the same branch causes problems.

**Comment by kball** [comment]
The rcs should only be available with 'beta' tags, they are not true released versions... so in this case bower is actually correct, I'm not sure why npm is making 6.3.0-rc2 available as a non beta.  Looking into it.

**Comment by ncoden** [comment]
@user58258 `6.3.0` has been released. Is it still an issue ?

**Comment by user58258** [comment]
@ncoden 
> Is it still an issue ?
well, it wasn't after @kball 's last comment ... the published pkg mgr were all in-sync at 6.2.x after what I presume to have been some fix.

& yes, NOW, they're all at 6.3.0, which is great.  all devs here are now mindlessly upgrading to the *same version* of the latest-n-greatest ;-)  "Once More unto the Breach!"

We'll see what happens when there's an update ...  until I see otherwise, I'm guessing it's been straightened out.

Thanks.
