### ISSUE TITLE
[Kitchen Sink] ISSUE @ right side navgation bar.

### ISSUE THREAD

**Issue by prudhvips** [zurb/foundation-sites#9276]
**How can we reproduce this bug?**
1. Open kitchen sink
2. Scroll till position of navgation bar at media object (Bug @) 
3. Navgation bar is not responsive over there till tooltip occurs.

We expect to navgation bar should be visible from Media object to tooltip.

The navgation bar is not responsive from media object position to tooltip position while scrolling the page to down.

**Test case:**

**Comment by DanielRuf** [comment]
What exactly do you mean?

The navigation on the right side is a sticky element and uses a magellan component on the inside.

**Comment by DanielRuf** [comment]
Can anyone describe the exact issue?

**Comment by DanielRuf** [comment]
Closing as we did not get the needed details.
