### ISSUE TITLE
Foundation 6.2.3 Cannot find module babelify

### ISSUE THREAD

**Issue by Snead** [zurb/foundation-sites#9281]
I had "^6.2.1", installed on new VM my app, and it installed 6.2.3. Then when running grunt-browserify I had this error: Cannot find module babelify from foundation-sites.
Had to downgrade to 6.2.1 again to make it work

**Comment by colin-marshall** [comment]
@Snead are you using foundation-sites through npm or bower in your project?

**Comment by mpastas** [comment]
Same here.

**Comment by Snead** [comment]
Yes, npm

**Comment by colin-marshall** [comment]
@Snead @mpastas is it safe to assume you guys both installed babelify to your project using `npm install --save-dev babelify`?

**Comment by Snead** [comment]
Nope, I just used browserify which uses babelify as dependency yo convert the files

**Comment by colin-marshall** [comment]
@Snead looking at both browserify and grunt-browserify I do not see babelify listed as a dependency in `package.json`. Please run `npm install --save-dev babelify` and see if that makes a difference.

**Comment by RobDesideri** [comment]
Hi, same error here, in a _gulp_ environment.
If you install babelify, everything works.
@colin-marshall could it be good to put babelify as a dependency directly in the `package.json`?

**Comment by colin-marshall** [comment]
Closing this out since we don't use browserify, there is no reason to add babelify to our `package.json`.

**Comment by stljeff1** [comment]
Here to report that installing latest of Bablify does not fix the issue.

**Comment by DanielRuf** [comment]
> Here to report that installing latest of Bablify does not fix the issue.

Please open a new issue with all relevant details.

**Comment by stljeff1** [comment]
Nevermind... I didn't know I needed to explicitly install @babel/core
