### ISSUE TITLE
Figure in Base.scss

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#9287]
I just wanted to use the `figure` tag and got a weird margin, due to `base.scss`: 

```
  figure {
    margin: 1em 40px;
  }
```

Can we fix this and set `margin: 0`?

**Comment by kball** [comment]
I would tend to agree.  This is aligned with what @ncoden has been advocating in terms of removing all styling on elements themselves and moving it all into class styles. cssreset tends to do margin 0 for figures... does anyone know why we had this instead? (cc @rafibomb @andycochran @brettsmason @gakimball)

**Comment by brettsmason** [comment]
@kball Normalize uses those margin values but to be honest I have no idea why. I'd agree with setting it to 0.

**Comment by andycochran** [comment]
Agreed. Nix the figure margin.

**Comment by kball** [comment]
Fixed in #9416
