### ISSUE TITLE
is-reveal-open class deleted if you call second reveal from other one with MotionUI

### ISSUE THREAD

**Issue by artems-hyuna** [zurb/foundation-sites#9291]
1. Open any Reveal subwindow (.is-reveal-open added to `<body>`).
   `Login` link in example below.
2. Click link or button in this Reveal window to open other Reveal window.
   `Forgot your password?` link in example below.
3. MotionUI features must be added:
   `Foundation.Reveal.defaults.animationIn = "slide-in-left";
   Foundation.Reveal.defaults.animationOut = "slide-out-left";`

**What did you expect to happen?**
`<body class="is-reveal-open">`

**What happened instead?**
`<body class="">`
Result: vertical scroll appear.

[CodePen](http://codepen.io/anon/pen/LRaLor)

**Comment by kball** [comment]
Thanks for the bug report and repro case!  Will take a look.

**Comment by artems-hyuna** [comment]
@kball Tried your solution. It doesn't work.

**Comment by colin-marshall** [comment]
Resolved in #9295
