### ISSUE TITLE
Unable to build Foundation 6.2.4 in meteor on Mac OS X 10.12

### ISSUE THREAD

**Issue by beldougie** [zurb/foundation-sites#9297]
**How can we reproduce this bug?**
1. create a new meteor project
2. run `meteor add zurb:foundation`
3. watch it fail

**What did you expect to happen?**
The zurb:foundation package to be added to the meteor project

**What happened instead?**
The following error was returned

```
While checking for zurb:foundation-sites@6.2.4:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

**Test Case**
You can verify correct behaviour by running `meteor add zurb:foundation@6.2.3` which completes successfully

So can you publish the correct binaries please?

**Comment by kball** [comment]
At last attempt to publish to meteor atmosphere was timing out.  I'll try again.

**Comment by jripmeester** [comment]
Same problem here. Could the correct binaries please be uploaded?

**Comment by kball** [comment]
I believe this should be resolved, can you confirm?

BTW... atmosphere has recently been a major pain, by far the most time consuming and painful package manager to update... can any of the meteor experts on here recommend an alternative approach?  Can we point it somehow to the bower or npm packages?

**Comment by colin-marshall** [comment]
Closing this out. @jripmeester @beldougie feel free to reopen if this is still an issue.
