### ISSUE TITLE
Make color classes so that it can be used on any element

### ISSUE THREAD

**Issue by farooqaaa** [zurb/foundation-sites#9300]
I have a table where the color of a row represents the status. I tried using `.success` and other classes but it didn't work. Turns out you can only use these color classes if you have a button, panel, label or some other predefined class. I know I can easily do this using SCSS but I think this should part of the base. If these simple rules are added:

```
.success { color: $success-color !important }
.alert { color: $alert-color !important }
...
```

It will allow users to use colors from the color scheme anywhere they want without having to specify a class when you don't need like in my case when I had a table row. I can't use label, panel or any other class to make the color classes work.

**Comment by zurbrandon** [comment]
The tradeoff here would be file-size bloat for a more rare usage. This may be better on a per use bases to add the color map to the component. 

Anyone have thoughts?

**Comment by brettsmason** [comment]
The trouble I see with having classes like that is what if I want to set the background colour rather than text colour? I don't think it would be clear what it sets.

**Comment by farooqaaa** [comment]
@brettsmason Sorry! I made a mistake in my first post. It should have been `background-color`.

@zurbrandon I think you're right. But then having global color classes will replace `.button.success` `.alert.success` etc. which might actually save quite a few lines of code.

**Comment by colin-marshall** [comment]
This feature request doesn't look like it went anywhere so I'm closing it out. Will revisit for consideration in F7.

**Comment by IamManchanda** [comment]
Sorry @farooqaaa but semantics of foundations doesn't work like this
We had a deep discussion here #9671 
and this will not be added in foundation in coming future to my best of knowledge

That said, we may consider some JavaScript Abstraction like https://acss.io/ for F7 
but I don't think will happen so adding it as close:invalid

@colin-marshall No need to revisit for f7
