### ISSUE TITLE
Module AMD/CommonJS/Browser Global  not working 

### ISSUE THREAD

**Issue by york-xtrem** [zurb/foundation-sites#9302]
Example scrollmagic module, but it happens with others too.

**How can we reproduce this bug?**
1. Git clone https://github.com/zurb/foundation-zurb-template projectname
2. Install:
   npm install gsap --save-dev
   bower install scrollmagic --save-dev
3. Add text line config.yml:
   - "node_modules/gsap/src/uncompressed/TweenMax.js"
   - "bower_components/scrollmagic/scrollmagic/uncompressed/ScrollMagic.js"
   - "bower_components/scrollmagic/scrollmagic/uncompressed/plugins/animation.gsap.js"
   - "bower_components/scrollmagic/scrollmagic/uncompressed/plugins/debug.addIndicators.js"
   - "bower_components/scrollmagic/scrollmagic/uncompressed/plugins/jquery.ScrollMagic.js"
4. npm start

**What happened instead?**
In console Google Chrome:
`Uncaught TypeError: Cannot set property 'ScrollMagic' of undefined`

I am following this thread but it does not work:
# 8256

Google Chrome:
![captura](https://cloud.githubusercontent.com/assets/14836838/19760197/d32a8d6a-9c30-11e6-9df9-a6808bd650d0.PNG)

Firefox:
![captura2](https://cloud.githubusercontent.com/assets/14836838/19760204/d8533472-9c30-11e6-80e7-105d90807bd6.PNG)

**Comment by york-xtrem** [comment]
I found the problem but not solve it.
 - [1 Answer of Stackoverflow](http://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined)

> When using Babel 6 and babel-preset-es2015 (or Babel 5), Babel by default assumes that files it processes are ES6 modules. The thing that is causing you trouble is that in an ES6 module, this is undefined, whereas in the "script" case, this varies depending on the environment, like window in a browser script or exports in CommonJS code.

The problem is that I have files in ES6 and others not.
Would have to separate files here? How?
```javascript
// Combine JavaScript into one file
// In production, the file is minified
function javascript() {
  return gulp.src(PATHS.javascript)
    .pipe($.sourcemaps.init())
    .pipe($.babel())
    .pipe($.concat('app.js'))
    .pipe($.if(PRODUCTION, $.uglify()
      .on('error', e => { console.log(e); })
    ))
    .pipe($.if(!PRODUCTION, $.sourcemaps.write()))
    .pipe(gulp.dest(PATHS.dist + '/assets/js'));
}
```

# Why wrong? Explanation...
### Change the file javascript.
Change **_this_** to **_undefined_**
## Besides this:
```javascript
} else if (typeof exports === 'object') {
```
```javascript
}(this, function () {
	"use strict";

	var ScrollMagic = function () {
```
to
```javascript
} else if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object') {
```
```javascript
})(undefined, function () {
	"use strict";

	var ScrollMagic = function ScrollMagic() {
```

## Code fragment:
Before doing so:
```javascript
(function (root, factory) {
	if (typeof define === 'function' && define.amd) {
		// AMD. Register as an anonymous module.
		define(factory);
	} else if (typeof exports === 'object') {
		// CommonJS
		module.exports = factory();
	} else {
		// Browser global
		root.ScrollMagic = factory();
	}
}(this, function () {
	"use strict";

	var ScrollMagic = function () {
```
After doing so:
```javascript
(function (root, factory) {
	if (typeof define === 'function' && define.amd) {
		// AMD. Register as an anonymous module.
		define(factory);
	} else if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object') {
		// CommonJS
		module.exports = factory();
	} else {
		// Browser global
		root.ScrollMagic = factory();
	}
})(undefined, function () {
	"use strict";

	var ScrollMagic = function ScrollMagic() {
```

**Comment by colin-marshall** [comment]
@york-xtrem from your stackoverflow link this looks like a good option:

> If you are using Babel, the easiest option is to write your code without the UMD wrapper, and then bundle your file using something like Browserify to automatically add the UMD wrapper for you. 

I don't have any experience in Browserify so I can't tell you how todo that.

One other option I can think of would be to turn the gulp task that builds javascript into 3 tasks like this:

``` javascript
function javascriptEs6() {
  return gulp.src(PATHS.javascriptEs6)
    .pipe($.sourcemaps.init())
    .pipe($.babel())
    // ...
}

function javascriptEs5() {
  return gulp.src(PATHS.javascriptEs5)
    .pipe($.sourcemaps.init())
    // no need to run these through babel
    // ...
}

function javascript() {
  return gulp.src(PATHS.javascript)
    // concat and minfiy the resulting js files
    // from javascriptEs6 and javascriptEs5 tasks
}
```

You would also need to modify the paths in the `config.yml` file to separate out ES6 and ES5 javascript. With this setup you would prevent any javascript not written as an ES6 module from being transpiled by babel, which I think would prevent the errors you are getting.

**Comment by york-xtrem** [comment]
@colin-marshall, I'm working on a solution that preserves the sourcemaps of each file. In a few days I will make a pullrequest if you like.

**Comment by colin-marshall** [comment]
@york-xtrem is your solution similar to what I proposed as far as changing the gulpfile so ES5 files are not transpiled?

**Comment by york-xtrem** [comment]
@colin-marshall
Yes, but there is a problem. When concatenated, SS6 and SS5, the sourcemaps fail. I am testing with:
https://www.npmjs.com/package/gulp-concat-sourcemap
Or
https://www.npmjs.com/package/concat-with-sourcemaps.

But without success...

**Comment by colin-marshall** [comment]
Can you show me what you have for your gulp tasks?

**Comment by york-xtrem** [comment]
The solution is to use Gulp-filter to filter SS5 and SS6. So you preserves the sourcemaps. You have to change config.yml

## gulpfile.babel.js

``` javascript
function javascript() {
  const jsES6 = filter(PATHS.javascriptES6, {restore: true});
  const js = PATHS.javascriptES6.concat(PATHS.javascriptES5);
  return gulp.src(js)
    .pipe(jsES6)
    .pipe($.babel())
    .pipe(jsES6.restore)
    .pipe($.sourcemaps.init())
    .pipe($.concat('app.js'))
    .pipe($.if(PRODUCTION, $.uglify()
      .on('error', e => { console.log(e); })
    ))
    .pipe($.if(!PRODUCTION, $.sourcemaps.write()))
    .pipe(gulp.dest(PATHS.dist + '/assets/js'));
}
```
