### ISSUE TITLE
Responsiveness issue on the main website

### ISSUE THREAD

**Issue by xahon** [zurb/foundation-sites#9305]
I don't know if it is the place where I should leave this question, but I must.

On the main page of [Foundation](http://foundation.zurb.com/) I have seen that
![image](https://cloud.githubusercontent.com/assets/18731681/19799405/da88eebc-9d39-11e6-96fd-c085763539bb.png)

**Comment by kball** [comment]
@rafibomb can you take a look at this?

**Comment by kball** [comment]
This has been fixed
