### ISSUE TITLE
input-group sizing wrong when using the file picking styling suggested

### ISSUE THREAD

**Issue by jellisii** [zurb/foundation-sites#9307]
**How can we reproduce this bug?**
1. Use input-group with a file input type demonstrated https://foundation.zurb.com/sites/docs/forms.html#file-upload-button

**What did you expect to happen?**

I expect the button, label, and textbox to all be the same size.

**What happened instead?**

The button and label are not the same size as the textbox. 

**Test case:**

http://codepen.io/jellisii/pen/dpEayx

This may be related to #8818

**Comment by andycochran** [comment]
This is fixed in #9308.
