### ISSUE TITLE
Responsive Gutters (regression in 6.3?)

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#9309]
Responsive gutters seem to have stopped working. Gutters are getting the largest value in the `$grid-column-gutter` map at every breakpoint. @ncoden, might it be related to #8528?

**Comment by kball** [comment]
@andycochran please confirm this is just in develop/6.3, not in the released 6.2.4?

**Comment by andycochran** [comment]
@kball Yup, develop/6.3.

**Comment by kball** [comment]
Looks like it was actually from https://github.com/zurb/foundation-sites/pull/8693.  Submitting a fix shortly
