### ISSUE TITLE
Dropdown Menus don't close if opening another dropdown menu

### ISSUE THREAD

**Issue by andrewhinde** [zurb/foundation-sites#9313]
I have multiple dropdown menus on a page for contextual menus (delete/export/etc individual items) and I can close the dropdowns when clicking anywhere on the body, however if I open a different dropdown menu, the previous one doesn't close, as it would if clicking anywhere else on the page.

Is this an option I'm missing, a bug, or intended behaviour?

![dropdown_menus_foundation6_full](https://cloud.githubusercontent.com/assets/8227269/19869629/8100ba90-9f83-11e6-9bce-2ad2def405a6.png)

**Comment by mescuderocuu** [comment]
Hi, which version of foundation are you using? i was seen this template: http://foundation.zurb.com/templates-previews-sites-f6/news-magazine.html and there the dropdowns work fine.

**Comment by colin-marshall** [comment]
@andrewhinde I'm closing this out, feel free to reopen if it is still an issue. Thanks.

**Comment by DanielRuf** [comment]
> @andrewhinde I'm closing this out, feel free to reopen if it is still an issue. Thanks.

Was still open ;-)
