### ISSUE TITLE
getBoundingClientRect undefined

### ISSUE THREAD

**Issue by fchengpc** [zurb/foundation-sites#9314]
![screen shot 2016-10-31 at 4 44 57 pm](https://cloud.githubusercontent.com/assets/6640631/19871112/ddbe585e-9f89-11e6-8c81-4516c9a3f905.png)

Getting this error. But not sure what is going on.
using  "jquery": "^2.2.4" & "foundation-sites": "^6.2.0" with node.

**Comment by kball** [comment]
Need more than this to reproduce... can you upload a codepen that reproduces the example?  Here's a template: http://codepen.io/kball/pen/ORdVEq

**Comment by Fequois** [comment]
It's impossible to say given the few details we have, but I can share something that fixed this particular issue for us.

We used to initialise Foundation through `$(document).foundation()` but after updating to 6.2.4 we had to change this to `jQuery(document).foundation()`.

**Comment by fchengpc** [comment]
actually we found the issue it was with `data-equalizer`. must be calculating something when item is not ready yet.

**Comment by kball** [comment]
@fchengpc that's helpful, will dig into it.  The more details you can provide the more likely we'll be able to track it down.  Thanks!

**Comment by fchengpc** [comment]
@kball understood. we are using [EJS](http://ejs.co/) templating to render some data on. and natually we have some `loop` and `if else` statement within the template. The way we used are follows:
```<div class="row" data-equalizer><!--- looping and if else data here --> </div>```

**Comment by kball** [comment]
@fchengpc is the template getting rendered after or before $(document).foundation() ?

**Comment by fchengpc** [comment]
the template is on the server side. We use webpack to init the `$(document).foundation()`

**Comment by fchengpc** [comment]
even with no data with in the `div` it still throwing error. I also trying the following code>
```<div class="row"  data-equalizer data-equalize-by-row="true"></div>``` 
with no data within the div. seeing same issue.

**Comment by kball** [comment]
@fchengpc My suspicion is that the problem is there are no items labeled with `data-equalizer-watch` and Equalizer is choking by not knowing what it is supposed to be equalizing...

**Comment by fchengpc** [comment]
@kball, sry abt the miss info we are using `data-equalizer-watch='row'`. But base on doc if you use `data-equalize-by-row="true"` you dont have to have the labele `data-equalizer-watch` right?

**Comment by kball** [comment]
I wonder if this is a dup of #8920

**Comment by fchengpc** [comment]
hm... very possible. thxs
