### ISSUE TITLE
[Dropdown Menu] Final link is not clickable on touch device.

### ISSUE THREAD

**Issue by unidwell** [zurb/foundation-sites#9322]
**How can we reproduce this bug?**

Observed as of 02.11.2016:

1. Use any device (for instance smartphone) with a touch capability.
1. Visit the foundation sites docs for the [dropdown menu](https://foundation.zurb.com/sites/docs/dropdown-menu.html "Example").
2. Go to any example (for instance horizontal example).
  - Navigate to item **Item 1**.
  - Try to click on **Item 1A**.
3. Observe that the link was not "followed" (the URL has not changed as expected).

**What did you expect to happen?**

After clicking on the final link, the URL was expected to change to _...#Item-1A_

**What happened instead?**

The URL remained the same and the menu closed (should not close instantly in the particular example right after the touch event occurred).

**Test case:**

Your [webpage](https://foundation.zurb.com/sites/docs/dropdown-menu.html "Example") documenting Foundation for Sites.

**Comment by tsquez** [comment]
You may want to look at this thread, may help, may not: https://github.com/zurb/foundation-sites/issues/9293

**Comment by unidwell** [comment]
Thank you, the workaround posted on the mentioned thread has helped. This bug report is a duplicate of #9293 and can be closed.

**Comment by tsquez** [comment]
Awesome, glad it helped.

**Comment by kball** [comment]
I believe this is fixed for good in #9456, will go out in 6.3.1.
