### ISSUE TITLE
[Dropdown Menu] Destroying doesn't remove all dropdown menu classes

### ISSUE THREAD

**Issue by diniscorreia** [zurb/foundation-sites#9339]
I'm programmatically creating (and destroying) a dropdown menu.

I've noticed that with 6.2.4 not all dropdown menu classes are removed when the menu is destroyed - in my test case, `is-dropdown-submenu` isn't removed.

Bug or expected behavior?

**Comment by kball** [comment]
Definitely bug.  Lets see if we can fix this for 6.3

**Comment by kball** [comment]
@diniscorreia would you like to take a pass on a PR to fix this?

**Comment by diniscorreia** [comment]
@kball oops! Took me a while, but just did.

**Comment by kball** [comment]
Given the discussion happening in that PR, this is a loose thread in a very knotty ball of problems. I think this is going to slip out to 6.4 as a part of a full menu refactor.

**Comment by ncoden** [comment]
Merged #9381. This will be released in `v6.4.4`
