### ISSUE TITLE
[Input Group] Flex-mode, input overflowing container in Firefox

### ISSUE THREAD

**Issue by simshaun** [zurb/foundation-sites#9341]
Foundation 6.2.4

In Firefox, with Foundation's flex-mode enabled, an input-group text input can overflow its container.

Check out http://codepen.io/simshaun/pen/MbwbbY

![image](https://cloud.githubusercontent.com/assets/379519/20079795/6b49fffe-a514-11e6-99df-cc423fa641cd.png)

Adding `min-width: 0;` to the `.input-group-field` appears to fix it in Firefox.

# Testing in Browserstack
- Win 10 / Edge **good**
- Win 10 / IE 11 **good**
- Win 7 / IE 10 **good**
- Win 10 / FF 49 **good**
- Win 10 / Chrome 54 **good**
- Win 10 / Opera 41 **good**
- Mac Sierra / Safari 10 **good**
- Mac El Capitan / Safari 9.1 **good**
- Mac Yosemite / Safari 8 **good**

**Comment by ncoden** [comment]
@simshaun Thank you. It's funny, it is an old bug I tried to fix some months ago, with the same solution : https://github.com/zurb/foundation-sites/pull/8511

But @DaSchTour pointed out that it introduce an new bug (see https://github.com/zurb/foundation-sites/pull/8762). Currently, I'm unable to reproduce these bugs. Can you check if `min-width: min-content;`, the solution @DaSchTour proposed, works ?

**Comment by simshaun** [comment]
`min-width: min-content;` does not fix the problem in FF. Nor does the proposed -moz-min-content.

Also, the PR for this fix is targeted solely to `.input-group-field` rather than the grid. I don't know that wrapping is a concern here.
