### ISSUE TITLE
[Input Group] Input group is overflowing parent column in flex mode

### ISSUE THREAD

**Issue by simshaun** [zurb/foundation-sites#9343]
Foundation 6.2.4

This is a vanilla custom download with flex-mode and forms:
http://simshaun-static.s3-website-us-east-1.amazonaws.com/foundation/6.2.4/

I'm seeing the input-group overflow its parent column in both Win 10 Firefox & Win 10 Chrome. The issue is even more pronounced 

It has something to do with row collapsing. Taking the `collapse` class of the parent `.row` makes the problem go away.

![image](https://cloud.githubusercontent.com/assets/379519/20080657/dd631cc0-a518-11e6-8bb9-a6ded8ea5760.png)

# Edit:
This may just be a problem with the demo page not including the `columns` class on the `.row.collapse` element. Adding it solves the issue. In fact, it doesn't seem that `collapse` is doing anything then...

![image](https://cloud.githubusercontent.com/assets/379519/20080781/86b4fce4-a519-11e6-98fe-f4f99cf08643.png)

**Comment by colin-marshall** [comment]
@simshaun do you know if this was corrected in later versions? Thanks.

**Comment by simshaun** [comment]
The issue appears to have been fixed. http://simshaun-static.s3-website-us-east-1.amazonaws.com/foundation/6.4.2/

**Comment by colin-marshall** [comment]
Thank you!
