### ISSUE TITLE
[Button] $button-radius setting is duplicated and overridden in _settings.scss

### ISSUE THREAD

**Issue by nandastone** [zurb/foundation-sites#9345]
Changing the `$button-radius` SCSS setting variable under the "11. Button" settings group (https://github.com/zurb/foundation-sites/blob/master/scss/settings/_settings.scss#L243) has no effect on the compiled component. 

This is because the `$button-radius` variable has been duplicated later in the file, which overrides any change you've just made.

First (correct) definition: https://github.com/zurb/foundation-sites/blame/master/scss/settings/_settings.scss#L243

Second (mistaken) definition: https://github.com/zurb/foundation-sites/blame/master/scss/settings/_settings.scss#L361

I can't imagine any need for the 2nd definition, should be safe to remove.

**Comment by ncoden** [comment]
Fixed in https://github.com/zurb/foundation-sites/pull/9346 then https://github.com/zurb/foundation-sites/pull/9347
