### ISSUE TITLE
[Dropdown Menu] Input field events are blocked inside dropdown list

### ISSUE THREAD

**Issue by losmicar** [zurb/foundation-sites#9350]
When I put input field inside one of the dropdown items (li element), I can't type space, as it looks like you override keydown event or something and space is blocked (ignored).

So if I put search input field inside dropdown list, I can't search terms that contain space.

**How can we reproduce this bug?**

1. Open CodePen link below
2. Hover to display dropdown, and click on search
3. Try typing any term that is "two words" containing space

**What did you expect to happen?**

I expect not to override Input field events.

**What happened instead?**

It looks like it overrides default input field events.

**Here is a CodePen demo**
http://codepen.io/losmicar/pen/BQopLX

**Comment by Lindsor** [comment]
@losmicar @ncoden The pen provided uses foundation 6.2.1 the issue is is not present in 6.2.4
see:

http://codepen.io/Lindsor/pen/dOMRbv/
