### ISSUE TITLE
[Drilldown] Parent link in drilldown back button

### ISSUE THREAD

**Issue by happyimadesignr** [zurb/foundation-sites#9352]
**What did you expect to happen?**
Would be nice to be able to pull parent link into the back button so users can have context of where they navigated from.

**Comment by Lindsor** [comment]
Hey @happyimadesignr care to elaborate? The drilldown button links to within the same page within the dom so what would need to be pulled?

**Comment by rafibomb** [comment]
I think this means adding the ability to pull the parent link (say it was Products) to say "back to Products"

Is that right @happyimadesignr ?

**Comment by rafibomb** [comment]
There is an option for `data-parent-link` that Adds the parent link to the submenu. This feature request is to append it to the back button instead.

**Comment by atomeon** [comment]
@rafibomb Don't know what i'm doing wrong, but when i adding data-parent-link="true" it's only adding one more list element to submenu with parent _name_ which is not clickable but static, looks kinda like this
![image](https://user-images.githubusercontent.com/9414471/28007464-550011d0-6575-11e7-9ee0-7fd775914501.png)
![image](https://user-images.githubusercontent.com/9414471/28007484-67ee735e-6575-11e7-8749-58d199a086ea.png)

**Comment by JeremyEnglert** [comment]
This feature will be considered for the next version of Foundation. I personally think this is a great idea.
