### ISSUE TITLE
Flex grid - Nested rows issue

### ISSUE THREAD

**Issue by Lindsor** [zurb/foundation-sites#9361]
Using the _flex-grid.scss file an element with the classes of 'row' and 'column' have the float set to none and the display set to block which breaks the flex grid.

**How can we reproduce this bug?**

<div class="row column">
  <div class="small-3">Full width but should be 3 columns</div>
  <div class="small-3">Should be next to the above not below</div>
</div>

**What did you expect to happen?**
Expected the '.small-3' element to take up 3 columns.

**What happened instead?**
The '.small-3' took up 100% width.

Give us a link to a CodePen or JSFiddle that recreates the issue.

http://codepen.io/Lindsor/pen/oYbJNa/

**Comment by kball** [comment]
Fixed in #9362.
