### ISSUE TITLE
[Drilldown] Submenus have stopped covering parent menus

### ISSUE THREAD

**Issue by colinmackinlay** [zurb/foundation-sites#9368]
**How can we reproduce this bug?**

1. Create a 6 item menu
2. Create a 2 item submenu for item 1
3. Create a 1 item submenu for item 6

**What did you expect to happen?**
Submenu 1 or sub menu 6 should slide across and obscure whole of main menu. It behaves like this on codepen where foundation.min.css is 6.2.1

**What happened instead?**
Submenus obscure just part of main menu. You can end up with both submenus visible and part of the main menu!

**Test case:**

**Comment by brettsmason** [comment]
I can confirm this by creating a Pen: http://codepen.io/anon/pen/zoBKwE
@colinmackinlay If you could provide a Codepen of the issue next time that would be great.

**Comment by colinmackinlay** [comment]
Thanks for taking the time to look @brettsmason. I didn't know how to change the css in codepen - I'll learn for next time!

**Comment by brettsmason** [comment]
@colinmackinlay no problems! I'll see if we can the default codepen changed too to the right version - @rafibomb

**Comment by kball** [comment]
Looking into this.

**Comment by kball** [comment]
This came from #8320... I think it will be addressed if we can get #9239 updated and merged. If @monosize doesn't end up having time to do that, I'll implement a quick fix for this instead.

**Comment by MaSchw** [comment]
complement
Today i updated to firefox V50.0 and now drilldown menu don't work correct. All is showed as vertical list including the submenu. Explorer Edge work correct (but with the mentioned bug above).
