### ISSUE TITLE
Broken "Tabs and URLs" example in develop branch's docs

### ISSUE THREAD

**Issue by simshaun** [zurb/foundation-sites#9370]
When working on #9369, I noticed this.. The example on Tabs -> Tabs and URLs is broken.

**Comment by colin-marshall** [comment]
@simshaun is this still an issue?

**Comment by ncoden** [comment]
@colin-marshall  I think it would be faster to figure it out by ourselves than to wait a reply on an issue from 18 months ago ;)

**Comment by colin-marshall** [comment]
Haha true. I was going to come back to this one if I didn't hear from him in a day or two.

**Comment by ncoden** [comment]
The example seems to works perfectly btw. @simshaun please reopen if I'm wrong.

**Comment by simshaun** [comment]
Working fine now.
