### ISSUE TITLE
Npm version old

### ISSUE THREAD

**Issue by Lindsor** [zurb/foundation-sites#9371]
Hey guys,

more of a question / heads up.

I downloaded the latest version from npm and it doesnt have some of the fixes done a while back like the accordion title size but its there if you download from the site.

I was wondering if theres a reason? Or a release schedule for npm?

Thanks,

**Comment by kball** [comment]
Hi @Lindsor - the build for the download is slightly different than from npm (for example, the complete contains motion ui classes as well), but all of the fixes should be there... doing a check on a fresh npm install I don't see anything majorly off, can you highlight the exact issues you're seeing?  Also please make sure the version being installed by npm is in fact 6.2.4 (you can look inside the installation folder either at the package.json or one of the package files for the version)

**Comment by kball** [comment]
I believe this has been entirely resolved - please reopen if you are still seeing this.
