### ISSUE TITLE
Using Foundation 6 with requirejs

### ISSUE THREAD

**Issue by iFarmGolems** [zurb/foundation-sites#9375]
Hello,

Is there a way to require foundation and get extended jquery along with Foundation variable?

My config file: 

```javascript
require.config({
	baseUrl: '/scripts',
	paths: {
		foundation: 'foundation.min',
		jquery: 'jquery'
	},
	shim: {
		foundation: {
			deps: ['jquery'],
			exports: 'Foundation'
		}
	}
});

require(['foundation', 'jquery'], function (F, jq) {
	console.log(F); // all good
	console.log(jq); // no jq.foundation present
});
```

Thanks.

**Comment by drnkwati** [comment]
Did you succeed using foundation and requirejs am having same problem

**Comment by iFarmGolems** [comment]
Basically we wrapped whole code in UMD wrapper. So at the beginning:

```
(function (root, factory) {
	if (typeof define === 'function' && define.amd) {
		define(['jQuery_3.1.1'], factory);
	}
}(this, function (jQuery) {
```
Then before closing the UMD wrapper:

`return { Foundation: Foundation, jQuery: jQuery };`

That way you can export an object which has jQuery **enhanced** by Foundation methods and also Foundation variable.

Keep in mind that we have some kind of jQuery factory, I just simplified it but it should work with stock jQuery. The factory is for the purpose of creating new jQuery instances so that they do not touch already present jQuery's scope.
