### ISSUE TITLE
Inconsistency with error input background opacity

### ISSUE THREAD

**Issue by ncoden** [zurb/foundation-sites#9376]
In [scss/forms/_error.scss:46](https://github.com/zurb/foundation-sites/blob/a214c1b12f324ac84cce78908a68d37e1cae0621/scss/forms/_error.scss#L46), `@mixin form-input-error` (used by `.is-invalid-input` for the input error state) uses a partially transparent background.

This allows to use the `alter` color from the global color palette `$foundation-palette`, but it creates an inconsistency between the standard and the error input background color.

![Preview of inputs on different background colors](https://i.imgur.com/TSByDUl.png)
https://codepen.io/ncoden/pen/eBzPBK

**Comment by webdevan** [comment]
I always just over-write the error styles because of this, but I tend to agree that this is a bug that should get fixed. I also feel that the placeholder text (grey by default) contrasts better if it's red, and so I have created a PR: https://github.com/zurb/foundation-sites/pull/9393/files
