### ISSUE TITLE
F6 Abide - force certain hidden field(s) to validate

### ISSUE THREAD

**Issue by wgstjf** [zurb/foundation-sites#9378]
Hi guys,

Bit of a strange one this, not a bug, but instead trying override the default Abide behaviour.  I have some hidden fields such as the one below

```html
<input type="hidden" name="event_class_name" id="event_class_name" value="" required><span class="form-error">Please choose a class</span>
```
These fields are auto-populated (via JS) based on a user's selection within a table of event classes.  I appreciate that the default behaviour of Abide is to ignore 'hidden' fields but is there any way to override this?  If not anyway to hook into the validating (ie. before formvalid or forminvalid) process to get it to manually check these specific required 'hidden' fields?

Cheers,

Will

**Comment by webdevan** [comment]
You can simply hide the input with CSS instead of making it type="hidden":
`<input type="text" class="hide" required><span class="form-error">Error message that is not hidden</span>`

**Comment by wgstjf** [comment]
@webdevan great solution...now why didn't I think of that...? :-)

Thanks,

Will
