### ISSUE TITLE
[Abide] ajax page reload issue for foundation 6

### ISSUE THREAD

**Issue by rlynjb** [zurb/foundation-sites#9380]
Hi all,
So I followed the documentation for Abide version f6. Documentation can be found here: http://foundation.zurb.com/sites/docs/abide.html

After validation success, I want to submit my form via ajax to avoid page reload. I've used this

```
  // form validation passed, form will submit if submit event not returned false
  .on("formvalid.zf.abide", function(ev,frm) {
    console.log("Form id "+frm.attr('id')+" is valid");
    // ajax post form 
  })
```

and I've added my ajax code inside

```
  /*
    Registration Form ajax
  */
  $('#register-form').on('formvalid.zf.abide', function(e, frm) {
    e.preventDefault();

    var theForm = $(this);

    // Insert product registation data to database
    // and send a copy to email
    $.ajax({
      data: theForm.serialize(),
      type: 'POST',
      url: 'insertregister.php',
      success: function(a, b, c) {
        $('.form-wrapper').hide();
        $('.thank-you-message').show();
      },
      error: function(a,b,c) {
        $('.form-wrapper').hide();
        $('.error-message').show();
      }
    });
  });// end - on click
```

I've also defined by form with code below:
```
<form data-abide novalidate id="register-form">
```

So what happens when form is submitted.. data goes through the database but the page reloads.. it seems like ajax is not working.

**Comment by Deckluhm** [comment]
As described in [the same part of the documentation](http://foundation.zurb.com/sites/docs/abide.html#event-listener), you also need this event handler to prevent form from submitting:
```JS
// to prevent form from submitting upon successful validation
.on("submit", function(ev) {
  ev.preventDefault();
  console.log("Submit for form id "+ev.target.id+" intercepted");
});
```

**Comment by rlynjb** [comment]
it works!!! thanks you @Deckluhm

**Comment by Assiel** [comment]
yo hice todo eso y tranquilo el problema que me da es que esta enviando mas veces el ajax, 
ejemplo: de entrada si le doy guardar guarda una sola vez y entra en el ajax una sola vez, si le vuelvo a dar guardar me guarda 2 filas mas tomando lo que tengo seteado en los campos, nuevamente si le doy guardar me guarda 3 filas y asi sucesivamente

**Comment by Deckluhm** [comment]
@Assiel can you please write your comment in english?

**Comment by Assiel** [comment]
ya lo resolvi, el problema era que le habia agregado el evento click al boton submit y agregue el codigoo de formvalid
