### ISSUE TITLE
Dropdown Menu Hover Bug

### ISSUE THREAD

**Issue by innowea** [zurb/foundation-sites#9390]
Hello,

After using Foundation 6 for around one month, I noticed couple of days ago a strange bug for Dropdown Menu. It happens just in certain situation: when hovering over menu items **faster than usual** and changing the focus on other menu items or other content on the site/browser.

It happens even on the Foundation 6 site, on Dropdown Menu page: http://foundation.zurb.com/sites/docs/dropdown-menu.html

In order to reproduce it, I made a GIF where I filmed the screen while using the Dropdown Menu page on Foundation 6 site. Please have a look.

![dropdown_menu](https://cloud.githubusercontent.com/assets/23552890/20428278/d7ae9b80-ad90-11e6-9944-12e49565c65e.gif)

Tested on: Chrome 54, Mozilla 47, Opera 41, Edge 38, Safari 10

Cheers,
Inno

**Comment by tjhiggins** [comment]
+1

**Comment by ncoden** [comment]
Fixed in https://github.com/zurb/foundation-sites/pull/9443.

**Comment by innowea** [comment]
Thank you for your solution! Much appreciated ;)
