### ISSUE TITLE
Ship Typings with foundation-sites

### ISSUE THREAD

**Issue by DaSchTour** [zurb/foundation-sites#9391]
As the procedure for adding typings to DT is really time consuming you would like to suggest to ship typings for foundation within this package similar to moment.js
It's would be just adding the typings link to package.json
example: https://github.com/moment/moment/blob/develop/package.json

The currently best version can be found here: https://github.com/samvloeberghs/foundation-sites-typings

Would be great if somebody could find the time to add this.
I guess this might also help minimize problems described here: #9086

**Comment by kball** [comment]
I believe this is now fixed with #9471
