### ISSUE TITLE
TypeError: this.handles.addTouch is not a function

### ISSUE THREAD

**Issue by RafaMelazzo** [zurb/foundation-sites#9406]
I have just made a custom download of the **Slider** control, but the console is logging the following:

`TypeError: this.handles.addTouch is not a function`

The doc lists the utilities libraries bellow as required, but as I found [here](https://github.com/zurb/foundation-sites/blob/develop/customizer/config.yml#L153), `touch` util is not included, and others not presented in the docs are...

- `foundation.util.motion.js`
- `foundation.util.triggers.js`
- `foundation.util.keyboard.js`
- `foundation.util.touch.js`

Thank you!

**Comment by kball** [comment]
Thanks for the bug report @RafaMelazzo - will try to get this fixed for you this week.

**Comment by kball** [comment]
This should be fixed now.
