### ISSUE TITLE
[Dropdown] Closing event does not fire when dropdown closes

### ISSUE THREAD

**Issue by stljeff1** [zurb/foundation-sites#9414]
Using the following code, I have discovered the closeme.zf.dropdown event does not fire when the dropdown closes. Only when it opens.

			$(document).on('closeme.zf.dropdown', function () {
				console.log('closing...', arguments);

			});

I understand why it fires on open, because you want other dropdowns closed. But why does it not fire again when it actually closes? It should fire whenever the dropdown disappears, even when using the -close-on-click' data option

**Comment by kball** [comment]
@stljeff1 Thanks for the report!  I think this is a actually a problem with the docs... these events are not documented clearly at all.  Putting together a PR to try to address this.

**Comment by kball** [comment]
I've fixed this in the docs, @stljeff1 can you take a look at the new docs and if it doesn't make sense to you, reopen this?  This page: http://foundation.zurb.com/sites/docs/dropdown.html#js-events
