### ISSUE TITLE
flex-grid columns are not wrapping on iOS 8

### ISSUE THREAD

**Issue by oxyc** [zurb/foundation-sites#9417]
**How can we reproduce this bug?**

1. Use Foundation v6.2.4
2. Create a flex grid with two columns which use `small-12`.
3. Look at the page with iPhone 6 and iOS 8

**What did you expect to happen?**

The columns are stacked on two separate rows.

**What happened instead?**

The columns are on the same row overflowing the page.

**Test case:**

http://codepen.io/anon/pen/woPKOZ

Foundation v6.2.4

<img width="394" alt="screen shot 2016-11-29 at 18 18 28" src="https://cloud.githubusercontent.com/assets/302736/20733422/49ae864a-b661-11e6-89d3-3dc788b5a3c4.png">

Foundation v6.2.3

<img width="356" alt="screen shot 2016-11-29 at 18 22 00" src="https://cloud.githubusercontent.com/assets/302736/20733426/4c3f6c62-b661-11e6-8e21-7db31425137a.png">

**Comment by DaSchTour** [comment]
Duplicate of #9290

**Comment by oxyc** [comment]
Seems that is the cause yes. How come https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.4/foundation-flex.min.css wasn't built with the autoprefixer options?

**Comment by DaSchTour** [comment]
Last 2 -> iOS 10 release -> no prefix for iOS 8

**Comment by oxyc** [comment]
Ah, sorry I missed the date on the commit you mentioned, I thought it was already in the release. Thanks.
