### ISSUE TITLE
What happened to the 5.5.4 milestone?

### ISSUE THREAD

**Issue by barrywoolgar** [zurb/foundation-sites#9418]
Hello, I've been waiting for 5.5.4 for quite some time (hoping for #8878 to get merged) but the milestone was removed a couple of days ago by @rafibomb . It appeared largely complete (see [cached copy here](https://webcache.googleusercontent.com/search?q=cache:p5i1mY-xhywJ:https://github.com/zurb/foundation-sites/milestone/23+&cd=1&hl=en&ct=clnk&gl=uk)) so even if no more progress is intended, can the existing fixes be merged and made available in a final release? 

Thanks for your help

**Comment by ncoden** [comment]
@kball

**Comment by kball** [comment]
This is a great question, we should definitely continue to publish patch updates to Foundation 5.  I've been too heads down on 6.3 to think about this until now, but going to take a look now.

**Comment by colin-marshall** [comment]
Very sorry for the late response to this issue. We are moving on to Foundation 7, and there will be no more development or support for Foundation 5. For that reason I am closing this out.
