### ISSUE TITLE
[Grid] 6.3 - Factorize breakpoint list + breakpoint name

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#9425]
Reference merged PR: https://github.com/zurb/foundation-sites/pull/9365

This is to factorize two mixins, using a mixin that handle the "breakpoint list + breakpoint name"

**Comment by andycochran** [comment]
@ncoden You seemed to have an idea for how to do this. If you don't have time, point me in the right direction?

**Comment by ncoden** [comment]
@andycochran I'll take care of this issue tomorrow.
