### ISSUE TITLE
[Starter Projects] Error when bower_components are outside project folder.

### ISSUE THREAD

**Issue by prahladmishra** [zurb/foundation-sites#9434]
**How can we reproduce this bug?**

1. Create a folder in same pace as project i.e as a sibling of project folder eg. common 
2. Move bower_components to this new folder 
3. Change config.yml to use javascripts from "bower_components" in this new folder  eg change "bower_components/jquery/dist/jquery.js" to "../common/bower_components/jquery/dist/jquery.js"
4. run command "foundation watch" things work fine
5. Try to run `npm run build` 

**What did you expect to happen?**
I expected everything to compile properly without error.

**What happened instead?**
Got error while javascript uglify step run.

**Test case:**
I am thinking of using single repository of bower_conponents to be used in multiple projects so that I can just create different setting and apps and don't have to copy bower_components for each project.

**Comment by paxperscientiam** [comment]
@prahladmishra Did you update your `.bowerrc` to reflect this change?

**Comment by prahladmishra** [comment]
Tried that no success.. here is the change i tried in .bowerrc

{
  "directory": "../common/bower_components"
}

**Comment by paxperscientiam** [comment]
Hm, you could try symlinking your common assets directory to your child projects.

I use symlinking to great effect, though not for asset sharing. I'm also not entirely clear on what your desired workflow is.

That said, say you have something like these: 

`/path/to/common/source/bower_components/`
`/path/to/project1/source/`
`/path/to/project2/source/`

You could symlink like this:
````bash
ln -s /path/to/common/source/bower_components/ /path/to/project1/source
ln -s /path/to/common/source/bower_components/ /path/to/project2/source
````
Now, `/path/to/project1/source/bower_components/` and `/path/to/project2/source/bower_components/` will update whenever you run `bower update` in `/path/to/common/source`.

This works for me, but your mileage may vary.

**Comment by prahladmishra** [comment]
@paxperscientiam but i would still have to keep multiple copy of bower_components. I was thinking to have just one copy of it and that will act more like library which no project will change. Project specific files will be in there respective folders. For example setting.scss will define project specific variables and when compiled it will make use of this common files and result in project specific CSS.

**Comment by colin-marshall** [comment]
Closing this one out since it sort of falls out of the scope of our support. Also, we're not using bower anymore so I'm not sure if it still applies.
