### ISSUE TITLE
Gulp Server doesn't run the site 

### ISSUE THREAD

**Issue by lipcanu** [zurb/foundation-sites#9448]
I am trying to clone this repository. I did all the steps indicated with npm, using the `foundation new` command. After everything goes as planned (no errors) and I try to run either `npm start` or `foundation watch` I get this in the console: 
![image](https://cloud.githubusercontent.com/assets/7142655/20870944/79768c28-ba90-11e6-8c06-9ac4740d1395.png)
and nothing in the browser for localhost:8000

I ran other projects I have from the same console that use bower, sass, gulp and they work just fine. 
As i didn't make any changes to the foundation folder, I suppose it may be a bug? 
But I am not sure about it... maybe I just don't get how it should work. 

(p.s. I tried this 3 times in different folders, deleted and started anew, updated npm & node)

**Comment by kball** [comment]
@lipcanu sorry for the issue you're running into... can you let us know what versions of node & npm you are using?

**Comment by lipcanu** [comment]
npm: 4.0.3
node: 6.9.1
Should that be fine?
I recently updated both

**Comment by lipcanu** [comment]
Ok, I think I figured it out. It was just the basic template, not the zurb template, so it didn't have browser sync, even if I expected it to. Silly me :)
