### ISSUE TITLE
Inconsistency in variable names: topbar vs top-bar

### ISSUE THREAD

**Issue by eksperimental** [zurb/foundation-sites#9451]
Hi Everyone,
first issue report here,
I just found inconsistent that you use "topbar" and "top-bar" to refer to the Top Bar component.

Pretty much it is a matter of renaming your setting variables.

```terminal
scss/components/_top-bar.scss
11:$topbar-padding: 0.5rem !default;
15:$topbar-background: $light-gray !default;
17:/// Background color submenus within the top bar. Usefull if $topbar-background is transparent.
19:$topbar-submenu-background: $topbar-background !default;
23:$topbar-title-spacing: 0.45rem 1rem 0 1rem !default;
27:$topbar-input-width: 200px !default;
31:$topbar-unstack-breakpoint: medium !default;
45:  padding: $topbar-padding;
49:    background-color: $topbar-background;
52:  // Check if $topbar-background is differnt from $topbar-background-submenu
53:  @if ($topbar-background != $topbar-submenu-background) {
55:      background-color: $topbar-submenu-background;
61:    max-width: $topbar-input-width;
126:    @include breakpoint($topbar-unstack-breakpoint) {
146:      margin: $topbar-title-spacing;
158:      margin: $topbar-title-spacing;

scss/settings/_settings.scss
592:$topbar-padding: 0.5rem;
593:$topbar-background: $light-gray;
594:$topbar-submenu-background: $topbar-background;
595:$topbar-title-spacing: 0.45rem 1rem 0 1rem !default;
596:$topbar-input-width: 200px;
597:$topbar-unstack-breakpoint: medium;
``` 

I can contribute with a PR, i just need to be guided how to want to deprecate this and if you want to warn users when old-named variables are used

**Comment by kball** [comment]
@ncoden @andycochran @brettsmason what do y'all think?

**Comment by andycochran** [comment]
I'm not sure this is a bug. But this is also the case for `accordionmenu` and `accordion-menu`, `buttongroup` and `button-group`, `closebutton` and `close-button`, `dropdownmenu` and `dropdown-menu`, `helptext` and `help-text`, `mediaobject` and `media-object`, `offcanvas` and `off-canvas` … where we use one word for SASS and two hyphenated words for CSS classes.

**Comment by ncoden** [comment]
If we have to be consistent now, I think we should move to `lisp-case`, because it is the CSS standard. However, the namespace and role of the class/variable/function/mixin can't be easily separated. This is related to the naming problem mentioned in Yetinauts/#18

**Comment by DanielRuf** [comment]
@ncoden what is our plan, how do we handle this?

**Comment by DanielRuf** [comment]
Closing as we will not change this in v6.
