### ISSUE TITLE
Documentation - missing mixin for grid-column-offset

### ISSUE THREAD

**Issue by michaelBenin** [zurb/foundation-sites#9455]
In the foundation-sites docs I'm not seeing any references to `@include grid-column-offset($o);` - only see examples of using classnames.

**Comment by ncoden** [comment]
Documentation about Sass mixins and function can be found at the bottom of the page: http://foundation.zurb.com/sites/docs/grid.html#grid-column-offset. You also have a search bar just below the header.

However, there is no usage examples.

**Comment by ncoden** [comment]
@michaelBenin Is it still an issue ?

**Comment by colin-marshall** [comment]
Closing this out since there was no response from @michaelBenin. Feel free to reopen if it's still of concern.
