### ISSUE TITLE
Parent menu items shown up in drilldown menus

### ISSUE THREAD

**Issue by t3easy** [zurb/foundation-sites#9457]
**How can we reproduce this bug?**

1. Generate a drilldown menu with a submenu that has less menu items than the parent
2. open the submenu with lesser entries
3. parents are still sown

**What did you expect to happen?**
Parent menu items are unvisible.

**What happened instead?**
Parent menu items are visible.

It worked in 6.2.3 but broken in 6.2.4
Broken by https://github.com/zurb/foundation-sites/commit/88d722523db1a510b84feafcea067cfa433ecb57

**Test case:**
http://codepen.io/anon/pen/VmXQaB

**Comment by ncoden** [comment]
Hi @t3easy,

This is a duplicate of https://github.com/zurb/foundation-sites/issues/9368, and has been fixed in https://github.com/zurb/foundation-sites/pull/9423.

**Comment by t3easy** [comment]
Hi @ncoden,
thanks for the hint, your right!
I've added the min-height to my app.scss.
For general: is a v6.2.5 planed or do I have to switch to v6.3 if its out?

**Comment by ncoden** [comment]
The next release is `v6.3`, and there is no `v6.2.5` planed. I don't know why and I will talk about it to the rest of the team.

poke @kball @andycochran @brettsmason @colin-marshall
