### ISSUE TITLE
[Dropdown Menu] The data-options documentation is obsolete

### ISSUE THREAD

**Issue by bechlokza** [zurb/foundation-sites#9464]

**Comment by ncoden** [comment]
I checked.

At http://foundation.zurb.com/sites/docs/dropdown-menu.html#js-option (for `v6.2.4`), we can read:
- `data-click-open`, default `true`
- `data-force-follow`, default `false`

But in the code at https://github.com/zurb/foundation-sites/blob/v6.2.4/js/foundation.dropdownMenu.js#L362 (for `v6.4.2` and currently in `develop`):
- `clickOpen: false,`
- `forceFollow: true`

I've checked the template, and SuperCollider is using the `@example` value to generate what is presented as the "default" value:
```hbs
...
{{#each js.member}}
  <tr>
    <td><code>{{formatJsOptionName this.name}}</code></td>
    <td><code>{{formatJsOptionValue this.examples}}</code></td>
    <td>{{this.description}}</td>
  </tr>
{{/each}}
...
```
https://github.com/zurb/foundation-docs/blob/master/templates/partials/javascript-reference.hbs#L67

So for example when `forceFollow` was added in https://github.com/zurb/foundation-sites/pull/7344, the value of `@example` was set to be _an example_ (obvious things are obvious), different from the variable value.

I'll make a PR.

**Comment by kball** [comment]
Yeah I think this is definitely an issue we need to fix. I think we should have both an example and a default... short path will be having both in comments; I'd like SuperCollider to get the actual option value but this may take some time.  @gakimball do you have any thoughts on how we'd do that?

**Comment by ncoden** [comment]
*JSDoc provide the actual option value.

**Comment by ncoden** [comment]
I made some more tests. The following code ...
```js
DropdownMenu.defaults = {
  ...
  /**
   * Boolean to force overide the clicking of links to perform default action, on second touch event for mobile.
   * @option
   * @default
   */
  forceFollow: true
};
```
... stop the compilations of docs. There is no error, but I think SuperCollider or JSDoc crashed. They do not handle the empty `@default` for an array value. (see http://usejsdoc.org/tags-default.html).

**Comment by kball** [comment]
Given these are docs updates I think this can be accomplished after 6.3 is out the door.

**Comment by ncoden** [comment]
There is also: https://github.com/spacedoc/spacedoc

**Comment by ncoden** [comment]
@kball, So, what do we do for this issue ?

**Comment by kball** [comment]
Improving the docs is going to be a big focus by @rafibomb and I in the first part of the new year.  @gakimball as the primary author on supercollider & spacedoc, how hard do you think it would be to get those libraries to read the actual value for these variables?

**Comment by gakimball** [comment]
@kball It should be possible to get what you need (separate examples and defaults) without modifying Supercollider. I'll do some experimentation with tag parsing and see if we can't come up with something less brittle than the current system.

Having an example and a default in the table might make it too crowded, but needing them separate makes sense. An option might have, say, `null` as a default value and then something else like a function or string as an example.

**Comment by ncoden** [comment]
@gakimball Thank you for your reply. But the main problem here is how to _get_ the default value. It is not provided in the SuperCollider object, maybe because it is an array value and not a variable ?

**Comment by gakimball** [comment]
@ncoden The Supercollider object comes straight from JSDoc and isn't modified in any way. According to the [documentation for the @default JSDoc annotation](http://usejsdoc.org/tags-default.html), it only works with primitive values: string, number, boolean, and `null`. So if a plugin has an array or object as a default value, it won't be picked up.

I'm also wondering if the parser only plucks the default value for variable assignment (`x = 'y'`) versus object property assignment (`{ x: 'y', }`), but that would be weird.

**Comment by ncoden** [comment]
So, we will keep the current solution, but with `@default` instead of `@example`. :/

**Comment by gakimball** [comment]
What's an example of where the default and the example are different enough that you'd need to show both? And how prevalent do you think such instances are?

**Comment by ncoden** [comment]
I never talked about a single example value, but the expected type (keyword, number...) and/or all the possibles values when relevant.

**Comment by gakimball** [comment]
@ncoden When you say "all possible values", I can think of a few scenarios:

One is that a plugin option can accept multiple types. I haven't been in the codebase in a while, but ideally there are as few of those as possible to begin with. If the explanation is too verbose, you might be better off moving that text out of the option table and into the documentation body. For example: "If a number is passed, *x*, if a string is passed, *y*".

Another is that a plugin option can accept one of a set number of values. JSDoc has `@enum` to handle this, but it might be overkill, when in most cases you can just type out the full list in the description of the property. For example:

```js
DropdownMenu.DEFAULTS = {
  /**
    * Position of the menu relative to what direction the submenus should open. Can be `left` or `right`
    * @option
    */
  alignment: 'left',
};
```

**Comment by ncoden** [comment]
Fixed: https://github.com/zurb/foundation-sites/pull/9562
