### ISSUE TITLE
[BUG][off-canvas 6.3] scrollbars

### ISSUE THREAD

**Issue by andreamk** [zurb/foundation-sites#9476]
[CodePen with Foundation 6.3.0.rc2](http://codepen.io/andreamk/pen/XNYLxq)

**When left offcanvas is open appears the bottom scrollbar**
![fnd-offcanvas-test-open-left](https://cloud.githubusercontent.com/assets/12183989/21042138/dbbfd22e-bdef-11e6-92aa-0b898eabab1d.png)

**When right,top,bottom offcanvas has opened two scrollbars are adjacent**

![fnd-offcanvas-test-open-right](https://cloud.githubusercontent.com/assets/12183989/21042141/dbc420cc-bdef-11e6-8c1b-85106b61d608.png)
![fnd-offcanvas-test-open-bottom](https://cloud.githubusercontent.com/assets/12183989/21042137/db5c5cbc-bdef-11e6-97a3-00084ab799f8.png)
![fnd-offcanvas-test-open-top](https://cloud.githubusercontent.com/assets/12183989/21042140/dbc20562-bdef-11e6-96bf-0bc0a93adb65.png)

**Comment by brettsmason** [comment]
@andreamk This isn't actually a bug, but the docs for 6.3 are currently incorrect and haven't been updated to give better guidance.

To avoid scroll bars when an off canvas is open, you need to add `data-content-scroll="false"` (or `contentScroll: false` if you are using `data-options`).

You can also add a wrapper round `.off-canvas` and `.off-canvas-content` to remove scrollbars when closing a off canvas, like so:

```
<div class="off-canvas-wrapper">
  <div class="off-canvas position-left" data-off-canvas data-content-scroll="false">
    off canvas content
  </div>
  <div class="off-canvas-content" data-off-canvas-content>
    off canvas content
  </div>
</div>
```

**Comment by brettsmason** [comment]
@andreamk Here's an example on your codepen (try the left option): http://codepen.io/brettsmason/pen/XNBdmW

**Comment by kball** [comment]
@andreamk Based on @brettmason's feedback and the new (updated) docs, can we close this issue?

**Comment by andreamk** [comment]
Yes thanks
