### ISSUE TITLE
[Responsive Menu] Allow for JS controlled breakpoints or menu breakpoint 

### ISSUE THREAD

**Issue by rafibomb** [zurb/foundation-sites#9493]
In the case of a design needing a responsive menu breakpoint that is different that small, medium, large...and the developer doesn't use Sass (no access to breakpoint mixin)

It would be nice to define a separate breakpoint for the responsive menu for those cases.

In one example, for responsive toggle it could be:
`<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="850px">`

Or we can create a nav specific breakpoint like **nav-breakpoint** which can be used like:
`<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="nav-breakpoint">`
or
`<ul class="vertical menu" data-responsive-menu="drilldown nav-breakpoint-dropdown">`

Naming on the second example doesn't make sense but hopefully the concept does.

Thoughts?
@andycochran @JeremyEnglert @ncoden @brettsmason

**Comment by ncoden** [comment]
> and the developer doesn't use Sass

I agree this would be a cool features for _the developer who doesn't use Sass_, but I think we should be consistent about what we support and doesn't. There is plenty of things we could add to the Js if _the developer doesn't use Sass_.

We provide a ready-to-use JS and CSS for the most common use cases. If the developer needs something custom... he have to use Sass. I think it's the best way to give tons of features _and_ to keep our codebase simple.

**Comment by JeremyEnglert** [comment]
I think this is a great idea. 

I see where @ncohen is coming from in regards to staying consistent, but the menu components always seem to clash the most with the default styles, especially if trying to utilize something like a logo as part of the topbar. 

We also have to remember one of the motos of Foundation which is "prototype to production" - this feature addresses this as it allows less savvy developers and designers to easily adjust the menu breakpoint.

**Comment by kball** [comment]
I think there are multiple possibilities for us to explore here...

1. A set of top-bar/nav specific breakpoints
2. Extend our JS media query utility to allow arbitrary breakpoints as well as the existing media queries
3. ELEMENT QUERIES! :D  (seriously, I've seen some polyfills for this out there, interested in potentially exploring this within Foundation

**Comment by ncoden** [comment]
I don't like the fact of duplicating Sass styling features in the JS. :/

**Comment by andycochran** [comment]
Should this be rolled into #9421?

**Comment by rafibomb** [comment]
Example: http://foundation.zurb.com/forum/posts/50488-custom-data-hide-for-widths

**Comment by IamManchanda** [comment]
> I don't like the fact of duplicating Sass styling features in the JS

I agree with @ncoden

**Comment by ncoden** [comment]
As this is a new feature (and could change the whole framework relation between Sass/JS breakpoints), I close this issue. It will be considered in Foundation 7.

**Comment by besseddrest** [comment]
Hi @ncoden, I'm trying to make sure I understand this correctly because I am running into the same issue:

The Responsive Navigation can only be initialized using the Foundation 6 default breakpoint names, correct? `small`, `medium`, `large`, `xlarge`, 'xxlarge`?

We still have the ability to set these breakpoint names to have custom widths, so `medium: 640px` can be changed to `medium: 600px`, correct? (I've tested and it seems to work still).

Does this also apply to any feature in Foundation 6 that requires JS?

Thanks!

**Comment by MildTomato** [comment]
(Love this project btw :D)

I was a bit confused about being able to make my own custom breakpoint, and then being able to assign it to the responsive nav `data-hide-for`.
Could do with updating the documentation regarding this at https://get.foundation/sites/docs/responsive-navigation.html#responsive-toggle

```"This breakpoint can be changed with the data-hide-for attribute in HTML, or the hideFor setting in JavaScript."```

I had to come to this thread to realise i could just make my own breakpoint

**Comment by SassNinja** [comment]
@MildTomato how should the text look in your opinion to be clearer?

So far it's consistent with the rest of foundation. Adjusting the breakpoints requires to use Sass as explained on the Media Queries page:
https://get.foundation/sites/docs/media-queries.html#changing-the-breakpoints

**Comment by MildTomato** [comment]
so, it's sort of clear how you change the breakpoint for the title-bar to appear.
So i've added a 'mobilemenu' breakpoint, which has a value of 800px.
In html, you can use this with 

`<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="mobilemenu">`

It's not clear though how you can change the contents to show like a mobile menu. As they still just show as normal desktop layout.

**Comment by DanielRuf** [comment]
@MildTomato please open a new issue with all relevant information.
