### ISSUE TITLE
Simple menu with align right still has left margin

### ISSUE THREAD

**Issue by forkiven** [zurb/foundation-sites#9499]
When using align-right I expected the margin to also switch from left to right, so that last child aligns with the outer edge.

```
// Align right and simple
&.simple.align-#{$global-right} {
      > li {
        margin-#{$global-right}: 0;
        margin-#{$global-left}: get-side($menu-item-padding, $global-left);
      }
}
```

Perhaps?

**Comment by ncoden** [comment]
I agree this is an issue.

To resolve it, `@mixin menu-simple` should take a `$direction` parameter and use a `@mixin menu-simple-margin` sub-modifier, to be able to generate a margin at the left or right.

Then, there is two solutions to provide a modifier like this in CSS:
- The simpler but not proper solution: `.simple.align-{left|right}` selector (with a specificity of `0.3.1`):
```html
<ul class="menu simple align-left">...</ul>
```
- The proper but not simpler solution: `.simple-{left|right}` selector (with a specificity of `0.2.1`)
```
<ul class="menu simple simple-left align-left">...</ul>
```

At this point, everyone will think I'm for the second solution. But... the whole menu should be refactored anyway (the specificity goal is `0.1.0`, we are far away from that). So let's go for the simpler solution.
