### ISSUE TITLE
[Dropdown] Dropdown pane will not trigger with data-hover="true"

### ISSUE THREAD

**Issue by jastacdoss** [zurb/foundation-sites#9503]
**How can we reproduce this bug?**
1. Appears to have occurred beginning in version 6.2.4 and has not been resolved as of 6.3.0-rc3
2. Create a dropdown button triggered by hover
3. Hover over the button

**What did you expect to happen?**
Dropdown pane to open

**What happened instead?**
Dropdown pane opens on click, but not on hover

**Test case:**

Give us a link to a CodePen or JSFiddle that recreates the issue.
http://codepen.io/jastacdoss/pen/PbxWyx

**Comment by jamilservicos** [comment]
@jastacdoss 
fixed on 6.3.0 version
see: http://codepen.io/jamilservicos/pen/MbLpva

issue resolved on 6.3.0 version!

**Comment by jastacdoss** [comment]
Thank you! I tried that version and it didn't work, must have had something else going on as well.
