### ISSUE TITLE
Foundation Reveal is removing the reveal component from DOM

### ISSUE THREAD

**Issue by ejlocop** [zurb/foundation-sites#9504]
Hi, foundation's reveals seems a bit off. because when i tried to instantiate element as reveal component. it instantly removes the reveal from DOM.

i cannot recreate the bugs because i just used the common way and it works on most page but not on page1.

see SO question, i posted it there also.
http://stackoverflow.com/questions/41156167/foundation-reveal-is-removing-dom

**Comment by Deckluhm** [comment]
The reveal element is not removed from the DOM but moved in his overlay.

In your browser inspector you can see a new div with the reveal-overlay class with the reveal element inside it.

Here is the code that moved the reveal inside his overlay: https://github.com/zurb/foundation-sites/blob/develop/js/foundation.reveal.js#L68

**Comment by ncoden** [comment]
@Deckluhm Thank you.
@ejholmes Is it still and issue ?
