### ISSUE TITLE
Provide documentation for multiple versions

### ISSUE THREAD

**Issue by ncoden** [zurb/foundation-sites#9512]
Feature request: Provide documentation for multiple versions (`v6.3.0`, `v6.2.4`...), not only the latest.

**Comment by IamManchanda** [comment]
any updates on this @ncoden @kball 

Moreover i think should be also labelled as "Feature request"

**Comment by ncoden** [comment]
Yes

**Comment by webuxr** [comment]
...but still looking for a status. @ncoden and @kball any updates on when we might see version-specific documentation (sites) for 6.3.x and 6.4.x?

**Comment by patricklindsay** [comment]
see https://github.com/zurb/foundation-sites/issues/10190

**Comment by colin-marshall** [comment]
@ncoden are going to be able to get to this before F7?

**Comment by ncoden** [comment]
@colin-marshall I'll try to ;)

**Comment by ncoden** [comment]
> Since the documentation is built _with_ the Foundation version it describe, I think the only way to get multiple versions in docs would be to get multiple doc sites.
I don't know the stack behind the docs site and how it is updated, but I think that keeping a list somewhere of the git references (commit/branch/tag) to clone & install (in their own folder) would not be a bad idea.
>
> The complex thing is about the list of versions that must be the same in all sites. We could add a script in all `foundation-docs` versions used to fetch the list of `foundation-sites` versions from the server and display them in a dropdown.

**Comment by airtonix** [comment]
Netlify is your friend here

**Comment by DanielRuf** [comment]
> Netlify is your friend here

In general not a solution here as it does not solve the generation / our stack.

We host it ourself and some part of the docs are in another repo which is used for the generation.

**Comment by DanielRuf** [comment]
We'll probably solve this with Docusaurus or another solution.

**Comment by JamesVanWaza** [comment]
@DanielRuf how about using [Algolia Doscsearch](https://community.algolia.com/docsearch/ )

**Comment by DanielRuf** [comment]
@JamesVanWaza we will probably selfhost it and use an open source solution, not such a service.
