### ISSUE TITLE
SASS Issues Loading normalize-scss/sass/normalize

### ISSUE THREAD

**Issue by benbabics** [zurb/foundation-sites#9515]
I have a fresh install of foundation-sites v6.3.0, and it is bombing out during my build complaining about being unable to load `../_vendor/normalize-scss/sass/normalize`. 

Please see output below:

```
File: /tmp/sass_compiler-input_base_path-djMaZN2O.tmp/1/foundation.scss (9)
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: ../_vendor/normalize-scss/sass/normalize
Parent style sheet: /tmp/sass_compiler-input_base_path-djMaZN2O.tmp/1/foundation.scss
    at options.error (/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:286:26)
```

Any help is much appreciated. Thanks!

**Comment by ncoden** [comment]
Hi @benbabics,

How did you installed Foundation ? Do you import the standard Foundation file `scss/foundation.scss`, or did you copied it to your own project to manually import some partials ?

**Comment by benbabics** [comment]
Hi @ncoden,

Thanks for the quick reply! I have tried two different ways, both of result in the same issue in my Ember app.

1. Install and manually load the framework:
a. Follow instructions outlined in: http://foundation.zurb.com/sites/docs/sass.html
b. bower install foundation-sites --save
c. Follow instructions from section "Compiling Manually", but do it as outlined in ember-cli-sass (still using "foundation-sites", not "foundation"): https://github.com/aexmachina/ember-cli-sass#example

2. Install using an Ember-CLI ADDON: https://github.com/acoustep/ember-cli-foundation-6-sass/

From what I gather, both of these methods both result errata mentioned above with being unable to load `../_vendor/normalize-scss/sass/normalize`.

Any help is much appreciated.

**Comment by ncoden** [comment]
I think I understand where the error come from, and I am afraid it will be not easy to resolve. ember-cli-sass is copying all the files from `includePaths` (`bower_components/foundation-sites/scss`) into a temporary directory before compiling, and our scss dependencies in `_vendor` are not copied.

You can try to add 'bower_components/foundation-sites/_vendor' to `includePaths`.

**Comment by benbabics** [comment]
Hhmm... good idea. I'll give that a shot and circle back with the result. Thx.

**Comment by bfeltman** [comment]
Same issue here.  Struggling with this for 2 days.  I've added `bower_components/foundation-sites/_vendor` to include path with no luck.

Any other suggestions?

**Comment by benbabics** [comment]
@bfeltman I opened another ticket for **ember-cli-foundation-6-sass** codebase; I would recommend not overlooking this suggestion simply because it's an Ember Addon. He outlined that in this case it's a broccoli issue, but outlined a good _temporary_ solution using `.bower-postinstall.sh`.

If you're interested, you can read more about it here: https://github.com/acoustep/ember-cli-foundation-6-sass/issues/40

This worked for me for the time being. Good luck!

**Comment by ncoden** [comment]
@benbabics Can we close this issue ?

**Comment by benbabics** [comment]
Yes. Thx
