### ISSUE TITLE
Wrong Syntax for grid-column()

### ISSUE THREAD

**Issue by Knight-Yoshi** [zurb/foundation-sites#9517]
So after I updated to 6.3.0 and ran my gulp tasks this error started occurring.

```
[Error running Gulp] Error: node_modules/foundation-sites/scss/grid/_column.scss
Error: Wrong syntax for grid-column(). Use a number, decimal, percentage, or "n of n".
        on line 46 of node_modules/foundation-sites/scss/grid/_column.scss
>>     @error 'Wrong syntax for grid-column(). Use a number, decimal, percentage,
   ----^
```

**Comment by ncoden** [comment]
Hi @Knight-Yoshi,

The error come from the `grid-column` function, which take a number or a list as first parameter.

See the documentation:
```
///   Width of the column. Accepts multiple values:
///   - A percentage value will make the column that exact size.
///   - A single digit will make the column span that number of columns wide, taking into account the column count of the parent row.
///   - A string of the format "x of y" will make a column that is *x* columns wide, assuming *y* total columns for the parent.
```

Also, there was no change on grid-column You probably called the mixins `grid-column`, `grid-column-offset` or `grid-column-size` with an other parameter.

Could you give more informations about how you uses these mixins and functions ? Could you also add `@debug $columns;` at [scss/grid/_column.scss:20](https://github.com/ncoden/foundation-sites/blob/76717702ee348fb065dc337810b11a2ebe9fe312/scss/grid/_column.scss#L20) ?

**Comment by Knight-Yoshi** [comment]
So I found this is what breaks it.

```
	&-details {
		@include flex-grid-column(null);
	}
	
	&-controls {
		@include flex-grid-column(shrink);
	}
```

It worked fine before with 6.2

**Comment by ncoden** [comment]
True. `null` is not a valid value for `grid-column`. You can use:

```scss
@include flex-grid-column();
// Or
@include flex-grid-column(expand);
```

**Comment by Knight-Yoshi** [comment]
Hmm. Well thanks for that. :D
