### ISSUE TITLE
Expanded button group -- does not expand if only 1 button

### ISSUE THREAD

**Issue by weiserma** [zurb/foundation-sites#9521]
**How can we reproduce this bug?**

```
<div class="expanded button-group">
  <a class="button">Expanded</a>  
</div>
```

**What did you expect to happen?**

the button should fill the container

**What happened instead?**

button was regular width

**Test case:**

N/a  --- see code above

**Comment by ncoden** [comment]
https://codepen.io/ncoden/pen/qqLzmO

**Comment by ncoden** [comment]
Hi @weiserma 

Thank you for having reported the bug. I am surprised it was not reported before.
I created a codepen for this issue: https://codepen.io/ncoden/pen/qqLzmO. Please provide it the next time, it really help.

I fixed it in https://github.com/zurb/foundation-sites/pull/9522
