### ISSUE TITLE
Box-sizing inheritance in webkit/blink browsers broken

### ISSUE THREAD

**Issue by alamowo** [zurb/foundation-sites#9535]
`select` Elements that are nested in `details` do not inherit the `box-sizing: border-box;` correctly. All other input elements work because box-sizing is set explicitly.

Tested on Chrome Version 55.0.2883.95 (64-bit) and Safari Version 10.0.1

This is a known bug in Chromium.
[Chromium Issue Tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=589475&q=details%20box-sizing&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

A possible solution would be to set `box-sizing: border-box;` in `_select.scss`.

**Comment by kball** [comment]
Fixed in #9535

**Comment by slavanga** [comment]
From the Chromium Issue:
> Notice that only summary inherits box-sizing correctly. All other elements show "content-box".

If you really want to fix this then ```box-sizing: border-box``` should be set for all elements.
```
details > * {
  box-sizing: border-box;
}
```
