### ISSUE TITLE
CDN Links not populated

### ISSUE THREAD

**Issue by gitwebdevseo** [zurb/foundation-sites#9537]
This page in the documentation:
https://foundation.zurb.com/sites/docs/installation.html
refers to CDN links at jsDelivr, but the links referenced for the 6.3 code are not actually there.

**Comment by ncoden** [comment]
https://github.com/zurb/foundation-sites/pull/9538

**Comment by gitwebdevseo** [comment]
This is only a very minor thing, but the page
https://foundation.zurb.com/sites/docs/installation.html
under the heading 'CDN Links' states "The folks at jsDelivr host the compressed Foundation CSS and JavaScript for us."
Since the links have been changed to point to Cloudflare you should probably give them the credit now.

**Comment by ncoden** [comment]
You are right. I'll update this.
