### ISSUE TITLE
"tr { page-break-inside: avoid }" causing Printing problems in Firefox

### ISSUE THREAD

**Issue by simshaun** [zurb/foundation-sites#9543]
**How can we reproduce this bug?**

1. Create a multiple-row table with one row containing multiple pages of text.
2. Open Print Preview in Firefox

**What did you expect to happen?**

The table should be printed cleanly, with no extraneous page breaks.

**What happened instead?**

The row containing pages worth of text is split to a new page.

# Test case:

http://codepen.io/simshaun/pen/rWRvaX

Change View to *Debug Mode* and open Print Preview.

This is what I see in Firefox:

![image](https://cloud.githubusercontent.com/assets/379519/21377105/13339c82-c709-11e6-8ead-71f8a0962137.png)

# Potential fix:

In [_print.scss](https://github.com/zurb/foundation-sites/blob/develop/scss/typography/_print.scss) take the tr selector out of these lines (or set it to page-break-inside: auto):

    tr,
    img { page-break-inside: avoid; }

http://codepen.io/simshaun/pen/XNGqXr

With `tr` set back to `page-break-inside: auto`, this is what I see in Firefox:

![image](https://cloud.githubusercontent.com/assets/379519/21377153/aff6e740-c709-11e6-9f59-47938b3a14a0.png)

In Chrome:

![image](https://cloud.githubusercontent.com/assets/379519/21377202/67875764-c70a-11e6-9980-7b3029a2b07b.png)

In IE11:

![image](https://cloud.githubusercontent.com/assets/379519/21377194/45714c52-c70a-11e6-8145-13afb02c4ca3.png)

In Edge:

![image](https://cloud.githubusercontent.com/assets/379519/21377219/95e73912-c70a-11e6-974e-e514cad7032a.png)

**Comment by ncoden** [comment]
Hi @simshaun,

I understand why you expect your table to be split between pages. But when there is a lot of small rows, I personally expect my table to break. See: https://codepen.io/ncoden/pen/zobjWq.

On firefox, with `page-break-inside: avoid;`, the `Message` row is moved to the second page on the first table. But with `auto`, a small row is split where is would be better to not to.

So maybe we could provide a modifier (like `.print-table-break`) to allow the table to break on print when wanted. I think this behaviour is expected in very few cases. Tables are most often used with small rows.

**Comment by simshaun** [comment]
I see what you're saying. 

> So maybe we could provide a modifier (like .print-table-break) to allow the table to break on print when wanted. I think this behaviour is expected in very few cases. Tables are most often used with small rows.

A modifier would be fine.

> However, it adds complexity for a very particular case.

Heh. This isn't a very particular case for us since we often have long rows, but I can see your point of this not being needed in some other projects.

Maybe I'm missing something that should be obvious, but I don't understand how adding this as a print-only modifier would add complexity, though. 1) It's opt-in, so no BC break. 2) Foundation doesn't have docs for print, so there's nothing to update there. 3) The behavior is quite specific, so it shouldn't really have to be in the test-suite, right? 4) It wouldn't require maintenance. Either you use the modifier, or you don't.

>  We currently only have .show-for-print and .hide-for-print for print modifiers, so I really don't know if adding .print-table-break would be a good idea.

How is this a reason for not adding another modifier?

I'm not intentionally trying to be difficult, but I guess I don't have the same perspective as you. If this is something that would be a big deal for some reason, we can just override it in all our projects.

**Comment by ncoden** [comment]
By "complexity", I mean we cannot add 45000 modifiers for 45000 specific needs. But you are right, this can not really an uncommon case. If you want you can open a PR, otherwise i'll do it.

**Comment by simshaun** [comment]
Do you think this should be targeted specifically to `tr` tags to counteract the default behavior only on desired rows?

**Comment by ncoden** [comment]
I always say that we should avoid applying properties automatically or from the parent. So yes, I think we should add something like:
```
.print-break-inside {
  page-break-inside: auto;
}
```
It could be used on `tr`, but also `pre` or `blockquote`.
