### ISSUE TITLE
Add Setting To Disable Block Grid CSS

### ISSUE THREAD

**Issue by jhned** [zurb/foundation-sites#9545]
Hey there,

I find that I don't really use the Block Grid these days-- I usually create a flexbox container with `flex-wrap: wrap`.  As such, I'd like to remove the extra styles that come from the Block Grid, but I can't do that without directly editing the Foundation grid files. Would it be ok to create a setting that can totally enable or disable the Block Grid CSS?

**Comment by denisahac** [comment]
Please check the [flexbox](https://foundation.zurb.com/sites/docs/flexbox.html) section of the official documentation.

**Comment by ncoden** [comment]
@jhned Is it still an issue ?

**Comment by jhned** [comment]
Sorry, should've replied earlier. as @denisahac pointed out, I believe you can turn off the block grid styles if you're using the Foundation flexbox grid instead. I prefer to use the standard float grid, and use flexbox styles one-off as needed, rather than going full flexbox grid. So yes, I believe having the option to turn off the block grid styles while still using the standard float grid would be helpful.

**Comment by ncoden** [comment]
@jhned I'll work on this :)

**Comment by jhned** [comment]
You the bomb, mate!

**Comment by ncoden** [comment]
Hi @jhned,

I am sorry, I read your issue quickly and misunderstood it. I agree with you we should be able disable some parts of huge components we do not use. However, I don't know if a single setting would be the good solution, it would not match with the current Foundation approach of component mixins you can manually include or not.

There is already discussions about it at https://github.com/zurb/foundation-sites/pull/9026. I'll see if we can add a proper way do "modularize" components.
