### ISSUE TITLE
No Gutters class for a row without gutters ( no spaces b/w columns )

### ISSUE THREAD

**Issue by RamanCool** [zurb/foundation-sites#9547]
Does zurb have any plan for introducing `.row.no-gutters` like [bootstrap 4 ](https://github.com/twbs/bootstrap/pull/21211)

**Comment by brettsmason** [comment]
It looks like what you are talking about is already here, it's just called collapse: http://foundation.zurb.com/sites/docs/grid.html#collapse-uncollapse-rows

**Comment by RamanCool** [comment]
I am new to zurb foundation so i didn't knew ... thanks a lot
