### ISSUE TITLE
Flip Effect for Foundation Cards 

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9551]
As, Cards is out in Foundation 6.3 
I am proposing this flip effect to foundation cards 

http://codepen.io/IamManchanda/pen/eBoYpM

**Special Note:** Have proposed similar feature in bootstrap too so sorry for any duplication n all. I Just love and use both frameworks in my projects, so a bit neutral and proposing to both :)

**Comment by IamManchanda** [comment]
**Special note** : Work to done on mobile @kball @ncoden ..... 

User experience - Touch interactions

**Comment by kball** [comment]
Are there other components that are likely to want this type of behavior? IE should this generalized beyond cards?

**Comment by ncoden** [comment]
This is a global animation feature. It would be great to make it generic and easy to use for every component (or simple divs).

**Comment by IamManchanda** [comment]
What need to be done with this ??
It can be a great building block 

but global animation and motion-ui was being discussed so what's the current take?

**Comment by rafibomb** [comment]
@IamManchanda Yes a building block, yes an animation mixin for generic components

I think to work well on mobile it needs JS - motion UI can handle this?

As far as a class core to the framework - no

**Comment by JeremyEnglert** [comment]
Lets consider this for F7.
