### ISSUE TITLE
Micro Animation for Buttons 

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9553]
Something like this would be great for the framework--> http://semantic-ui.com/elements/button.html#animated

Codepen --> http://codepen.io/IamManchanda/pen/Pbvmxg

**Comment by Deckluhm** [comment]
If you are talking about adding animations to buttons, I don't think it should be in Foundation core.

You can already use libraries like [Motion UI](https://github.com/zurb/motion-ui) (from ZURB) to add animations to some JS components like [Reveal](http://foundation.zurb.com/sites/docs/reveal.html#js-options) or [Toggler](http://foundation.zurb.com/sites/docs/toggler.html#toggle-with-animation) or even directly in your CSS (for pure CSS components like Buttons).

**Comment by DaSchTour** [comment]
I could try to use animate.css to add animations to buttons.
This is just a short demo as I'm a bit on the rush.
http://codepen.io/DaSch/pen/aBroLw

**Comment by BicanMarianValeriu** [comment]
This will load the framework with features that some users dont need. I dont recommend.
You can always integrate with animate.css or hover.css wich is perfect for your buttons.
Check a demo with animate.css here: http://www.wecodeart.com/

**Comment by IamManchanda** [comment]
I Have added the codepen to let you all understand what i am looking for .... in foundation

**Comment by ncoden** [comment]
I agree this would be very useful in Foundation. Micro animations are what make a design from good to perfect. However, I do not know Motion UI to know if this should added to Foundation or Motion UI.

**Comment by DaSchTour** [comment]
@IamManchanda I perfectly understand what you are looking for. I know the animations from Semantic UI. As I said, I was in a rush and that was just a fast example to show, that this may simple be done by using existing tools like animate.css

**Comment by IamManchanda** [comment]
@ncoden @DaSchTour @zurb 
so question that come in mind is 
what shall i do this with feature request 

1. Keep it open and wait for it to get added in foundation , or
2. Close this ticket and post a ticket in motion ui , or 
3. Close this and look out for doing this in animate css ? 

Any Help will be appreciated 

{ **Special Note : Wow.js is not a option, i want a open source option** }

**Comment by DaSchTour** [comment]
Motion UI wasn't updated since nearly a year, so I would raise the question if it's still active. Foundation Apps is also dead. The [roadmap](https://github.com/zurb/foundation-sites/wiki/Project-Roadmap) contains a note about Motion UI for 6.4.
Keep it open and create a PR ;)

**Comment by IamManchanda** [comment]
> create a PR ;)

I Would love to do that but i dont have the code to do that :smiling_imp:

**Comment by kball** [comment]
Overall improving Foundation's microinteraction capabilities, and specifically with animations, are things I've been thinking about a lot, and definitely going to be a focus this year.  I think that reviving, extending, and improving MotionUI is *probably* the right way to do it. I wasn't involved with the original buildout, but looking into it I think it has many of the right building blocks, it just needs some more polish.  

The current integration with Foundation is... only very minimally taking advantage of the capabilities, and the documentation is poor enough that it's very hard to figure out how to do better yourself. We'll be taking a hard look at this... would love it if there's some folks excited about animation who want to be a part of taking this on...? ( @IamManchanda @DaSchTour)

**Comment by IamManchanda** [comment]
I am on for being part of this  ...... Good on CSS ,  ok on JS

**Comment by JeremyEnglert** [comment]
Lets **seriously** consider this for Foundation 7.
