### ISSUE TITLE
Marking site download "everything" Tab-Accordion does not initalize

### ISSUE THREAD

**Issue by coreysyms** [zurb/foundation-sites#9554]
Most likely an issue with the customizer on the download page but the JS code compiled does not initialize the new tab accordion.

**How can we reproduce this bug?**

Go to the marketing download page > http://foundation.zurb.com/sites/download.html/
Download "Everything"
Open index.html and drop in the code block for a tab accordion.
The tab accordion does not initialize.

**What did you expect to happen?**
For it to initialize and work

**What happened instead?**
It bombed

**Test case:**
See above.

**Comment by kball** [comment]
Fixed
