### ISSUE TITLE
Problem with the alignment of the nested rows with flex grid

### ISSUE THREAD

**Issue by andreamk** [zurb/foundation-sites#9557]
You can see here
http://codepen.io/andreamk/pen/xRepeR

**Comment by ncoden** [comment]
Hi @andreamk,

I made some tests. The problems you encounter come from two incompatibilities with negative margins ([scss/grid/_row.scss:85](https://github.com/ncoden/foundation-sites/blob/develop/scss/grid/_row.scss#L85)) the nested rows have to handle the paddings of its column.

**1/** Every row has a max width (`75rem`, [scss/grid/_row.scss:62](https://github.com/ncoden/foundation-sites/blob/develop/scss/grid/_row.scss#L62)), so when nested, it can't be enlarged with negative margins: the left negative margin has an effect and not the right one. See: https://codepen.io/ncoden/pen/xRNzyL.

**2/** Collapsed rows have negative margins when nested, but columns inside it do not have paddings. This is related to https://github.com/zurb/foundation-sites/issues/9082.

I'm working on a temporary fix, but It makes me think, with the lot of others problems we encountered with grids and flex-grids, that a full rework would be very useful.

**Comment by ncoden** [comment]
Partial fixes: https://github.com/zurb/foundation-sites/pull/9568
