### ISSUE TITLE
faulty documentation

### ISSUE THREAD

**Issue by davicho** [zurb/foundation-sites#9559]
In trying to implement the **responsive navigation** (no dropdowns in my case) [https://foundation.zurb.com/sites/docs/responsive-navigation.html](https://foundation.zurb.com/sites/docs/responsive-navigation.html)

The doc here under JavaScript Reference [https://foundation.zurb.com/sites/docs/responsive-navigation.html#javascript-reference](https://foundation.zurb.com/sites/docs/responsive-navigation.html#javascript-reference) says to:

> **Initializing**
> The file foundation.responsiveMenu.js must be included in your JavaScript to use this plugin, along with foundation.core.js. This plugin also requires these utility libraries:
> 
> foundation.util.triggers.js
> foundation.util.mediaQuery.js
> foundation.util.accordionMenu.js
> foundation.util.drilldown.js
> foundation.util.dropdown-menu.js <--- **(btw -this file is now dropdowMenu I believe)**

But after much tinkering around found out only:
foundation.util.triggers.js
foundation.util.mediaQuery.js
**foundation.responsiveToggle** 

are needed.

Or am I am misinterpreting?

**Comment by ncoden** [comment]
Partially fixed: https://github.com/zurb/foundation-sites/pull/9563

For `foundation.responsiveToogle`, it is not a dependency of `foundation.responsiveMenu` and the current docs template support only one file name (see [foundation-docs:templates/partials/javascript-reference.hbs:8](https://github.com/zurb/foundation-docs/blob/da8388b81b48749ea9fb4e9be398fbd11ba2b889/templates/partials/javascript-reference.hbs#L8)). So it can't be fixed for now. The docs template must be updated. I'll see later what I can do.

**Comment by DanielRuf** [comment]
Friendly bump =)

What do we have to do here?

**Comment by ncoden** [comment]
Resolved in https://github.com/zurb/foundation-docs/pull/18
