### ISSUE TITLE
Color of the .button.success

### ISSUE THREAD

**Issue by BicanMarianValeriu** [zurb/foundation-sites#9564]
**How can we reproduce this bug?**

In foundation 6.2.4 the color of the text of the button was white.
Now the color is black.
It should be as it was in the previous version.

**What did you expect to happen?**
.button.success,
.button.success a
.button.success:hover {color:#fff}

**What happened instead?**
With foundation 6.3.0 the text is black unlike other colored buttons.

**Comment by ncoden** [comment]
> Since v6.3.0, Foundation is using a11y-compliant colors (see #9319). It means that when the background color is too light, we use $dark instead of $white for text color (see scss/components/_label.scss:60).

See: https://github.com/zurb/foundation-sites/issues/9555

**Comment by ncoden** [comment]
@BicanMarianValeriu  I close. Please reopen if you think this is not a duplicate issue.
