### ISSUE TITLE
Full grids rework

### ISSUE THREAD

**Issue by ncoden** [zurb/foundation-sites#9569]
I think about a full rework of grids for a while. I open this issue to start talking about it, collect feedbacks and synthesize changes to do. I plan the rework for `v6.4`, because of I personally do not expect a `v6.5` version. However, I started discussions about the utility of our _scheduled_ releases (see see https://github.com/zurb/foundation-sites/issues/9548), so please understand "the next release with breaking changes).

I think is several problem with the current grids (Grid and Flex-Grid):

1. For both Grid and Flex-Grid, we provide a "component" interface mixed between "base + modifiers" (a set of mixins for base and modifiers) and "variable behavior" (one mixin with or without base and with a configurable behavior). Some properties are defined in modifiers, some others inside the main mixin, and the others only inside classes. So the behavior of the component is not the same (if not bugged) depending on wether we use the _default classes_, generate it with the _main mixin and custom parameters_ or generate it with the _main mixin and modifier mixins_.
2. Because of that, and because of grid and flex-grid are made in a _similar_ but not _equal_ way, bugs, fixes _and_ features are duplicated. Grid has a more "variable bahavior" interface (with `$behavior` parameter and the weird way gutters are handled) while Flex-Grid has a more "base + mixin" interface. So without breaking changes for one or the other component (if not for both), we can only partially factorize fixes and features.
3. We expect grids to do everything, depending on the situation. It must be a container when not expanded, have responsive gutters when not collapsed, prevent side gutters when nested, be pushed, centred. I agree "does-everything" components are very simple to learn and useful to keep a simple markup, but it leads to several problems when they become complex. Firstly, it leads to a _very high_ specificity to handle the most particular case (and some of the most non-particular cases). Then, some mixes of these behavior (that are not meaningless) are bugged or impossible, and unresolvable. While components become complex, the probability to encounter incompatible features increase (collision of properties). For example, a row nested inside an expanded row **cannot be a container**, while it is what we would expect from it (see https://github.com/zurb/foundation-sites/issues/9557).
4. We planned to add [Frame Grid](https://github.com/zurb/foundation-sites/pull/9487) and a support for CSS-native grid. Without a rework, I really don't know how we would integrate these new grids into Foundation without impeding the maintenance of existing grids, and highly complicating the grids interface understanding.

To resolve these problems, I do not expect to do major changes or switch to a perfect approach. I generally push to a SMACSS+ITCSS but in this case it would be difficult to migrate grids and not others components, and it would make sense only with a different naming convention and a lot of too breaking change (see https://github.com/zurb/yetinauts/issues/18). So for the next """minor""" (haha !) release (if we do not change of workflow), I propose the following changes (I'll try to give the global principles behind my proposals, we should reuse them for ZF7):
- Use fully modifier mixins approach. Declare properties only inside the base or modifier mixin corresponsing to the particular behavior they set. Use these mixins to generate the standard base and modifiers classes. All modifier should inherit from the base or others modifiers. No feature should be specific to classes or mixins.
- Modularize grids. Make grids supporting _grid_ features and nothing else. Provide others components for the others features. It means we have rows and columns; columns can have static or responsive gutters, or no gutters at all; columns can be pushed to reorder them or simulate empty columns. Drop the default container behavior or grids and centered columns modifier `.columns.*-centered`. Add a Container component `.container` (auto margins and max-width, maybe responsive like Bootstrap) and a Block Centering `.block-center` (auto margins or flex) utility.

@zurb/yetinauts I would appreciate your opinion on this. Also, please add below the related issues you encountered (or created) which, following you, could be resolved by this rework:

---

Unresolvable bugs:
- https://github.com/zurb/foundation-sites/issues/9557#issuecomment-269123378 (3rd problem).
- #...

Expected behaviors and requested features:
- https://github.com/zurb/foundation-sites/issues/9082
- #...

**Comment by kball** [comment]
@gakimball would very much appreciate your thoughts on this one

**Comment by paxperscientiam** [comment]
With due deference to PR #9487, here is an example of a relatively opinionated template for a newspaper "app". I very much agree with @ncoden wrt to "modularization."

This has the potential to really clean up markup if HTML5 semantic elements are leveraged and encouraged. I cannot help but think that if Foundation for Sites is geared towards _designers_ that the required markup should be as simple as reasonably possible.

[newspaper](https://github.com/paxperscientiam/foundation-sites/tree/newspaper-example)
