### ISSUE TITLE
[Dropdown] Vertical scrollbar is still visible after dropdown pane is closed

### ISSUE THREAD

**Issue by jimmy72** [zurb/foundation-sites#9575]
I added the following style to a dropdown pane to make it scroll vertical in case the content gets too long:

`<div id="j1" style="max-height: 250px; overflow-y: scroll;" class="dropdown-pane" data-dropdown data-auto-focus="false" data-close-on-click="true">`

Everything work as expected but after closing the dropdown, the scrollbar is still visible and does not disappear.

I also tried to add these styles to a container inside this dropdown (not on the dropdown itself) but that doesn't work either.

I cannot figure out if this is a bug or me doing something wrong here?

Thanks

Jimmy

**Comment by ncoden** [comment]
Hi @jimmy72,

I can not reproduce the bug you are describing: https://codepen.io/ncoden/pen/YpmMOP.
Can you provide a codepen ?

**Comment by ncoden** [comment]
There is a bug between `overflow: scoll` and `visibility: hidden`. The component is hidden but not the scrollbar. I was able to reproduce it in [MDN](https://developer.mozilla.org/fr/docs/Web/CSS/overflow-x) but not in codepen, this is weird.

![dec-30-2016 14-51-49](https://cloud.githubusercontent.com/assets/9939075/21566069/94ec341c-ce9f-11e6-8d3f-7e6e98d73247.gif)

I do not know why we use `visibility:hidden` and not `display:none`. @kball Any thoughts on this ?

**Comment by jimmy72** [comment]
Ok I see...

I'll wait for the bug being fixed...

In the meantime I worked around it through jQuery....

$dropdowns.on('show.zf.dropdown hide.zf.dropdown', function(event) {
    event.preventDefault();
    var $thisDropdown = $(this);
    if(event.type == 'show'){
        $thisDropdown.css({
          "max-height": "300px",
          "overflow-y": "scroll"
        });
    }
    if(event.type == 'hide'){
      $thisDropdown.css({
          "max-height": "",
          "overflow-y": ""
        });
    }
  });

Jimmy

2016-12-30 14:53 GMT+01:00 Nicolas Coden <notifications@github.com>:

**Comment by kball** [comment]
I also don't know why we use visibility hidden instead of display:none.. i think I encountered a different bug related to this the other day. Will take a crack on this for 6.4

**Comment by kball** [comment]
Fixed in #10049. Will be in both 6.4 and 6.3.2
