### ISSUE TITLE
[Abide] CSS from npm build does not work correctly for errors

### ISSUE THREAD

**Issue by colinmackinlay** [zurb/foundation-sites#9578]
**How can we reproduce this bug?**

1. create new Zurb template with "foundation new"
2. npm run start
3. change index.html in pages to be:
`<div class="row">`
`  <div class="large-12 columns">`
`    <form id="test" action="/" method="post" data-abide>`
`      <label>Address line 1:`
`        <input id="childaddress1" type="text" required`
`               name="childaddress1" value="Test" size="25" />`
`        <span class="form-error">Please complete this field</span>`
`      </label>`
`    </form>`
`  </div>`
`</div>`
4. view index.html from dist in browser. Abide correctly colours label, input field and error text with error colour
5. npm run build
6. view index.html from dist in browser i.e. with minimised css file. Only the input field is now coloured although error text does display

**What did you expect to happen?**
label and error text to still be coloured using production build

**What happened instead?**
they weren't coloured
**Test case:**
sorry - the error doesn't show in the min.css used in codepen. Attached are two copies of the dist folder which illustrate the effect with the two different css files. One from npm run start, the other from npm run build
[dist.zip](https://github.com/zurb/foundation-sites/files/679404/dist.zip)

**Comment by ncoden** [comment]
Hi @colinmackinlay,

Can you provide an online diff of the two CSS files using https://www.diffchecker.com/ ? It would be simpler.

**Comment by colinmackinlay** [comment]
https://www.diffchecker.com/79BbUxcO
Don't think that helps much!

**Comment by ncoden** [comment]
The error comes from a merge of the `.is-invalid-label` declaration with an invalid `...::placeholder` declaration (`::placeholder` is not standard yet), making the whole final declaration ignored. I reported it at https://github.com/ben-eb/cssnano/issues/297#issuecomment-269845562.

The only other fix I see for now it is to move [scss/forms/_error.scss:69](https://github.com/ncoden/foundation-sites/blob/a87eb5dc02f714f80bd3648151d2c53185827548/scss/forms/_error.scss#L69) away to prevent the others declarations to be merged, or to manually use the placeholder vendors without `::placeholder` in [scss/forms/_error.scss:48](https://github.com/ncoden/foundation-sites/blob/a87eb5dc02f714f80bd3648151d2c53185827548/scss/forms/_error.scss#L48).

**Comment by ben-eb** [comment]
@ncoden Now that postcss-merge-rules@2.1.0 has been released, you should be able to run a new build where `::placeholder` won't be merged, using the default browserslist configuration. That will change as and when the browser support is much stronger for this. 😄

**Comment by ncoden** [comment]
@ben-eb Thank you :D

**Comment by ncoden** [comment]
@colinmackinlay Because `foundation-zurb-template` and `css-nano` use [caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004), you only have to update to the latest version with:

```cli
$ npm update cssnano
```

I tested and the rules with `::placeholder` are not merged. I close this issue, please re-open if it is not resolved.

**Comment by colinmackinlay** [comment]
@ben-eb @ncoden it doesn't change things but I perhaps that's because the zurb template uses gulp-cssnano? Update doesn't change the version which is showing 2.1.2. I've run npm update cssnano with and without -g and also update gulp-cssnano with and without g. I'll try again with a fresh download of the zurb template

**Comment by ncoden** [comment]
@colinmackinlay 
```
foundation-zurb-template@1.0.0
└─┬ gulp-cssnano@2.1.2 (^2.1.0)
  └─┬ cssnano@3.10.0 (^3.0.0)
    └── postcss-merge-rules@2.1.1 (^2.0.3) 
```

All these package use caret ranges for these dependencies' versions, so until you are using yarn, it should be updated automatically (look at the version of the package itself, not the the version of the dependency).

**Comment by colinmackinlay** [comment]
@ben-eb @ncoden My bad - didn't drill down to the local cssnano properly and only updated my global one. All works fine.
