### ISSUE TITLE
[Abide] Disabled fields not being ignored in validation

### ISSUE THREAD

**Issue by colinmackinlay** [zurb/foundation-sites#9579]
**How can we reproduce this bug?**

1. Use the example abide form code from the documentation
2. Add a disabled attribute to the first required field
3. Submit the form for checking

**What did you expect to happen?**
I expected Abode to ignore the disabled field as it does in  in Foundation 5
**What happened instead?**
The disabled field is highlighted with an error
**Test case:**
http://codepen.io/colinmackinlay/pen/PWYZGw

**Comment by ncoden** [comment]
Hi @colinmackinlay,

I agree with you, we can expect disabled fields to be ignored in form validation, this was requested in `v5` (#4109, 5843). I wonder why this behavior has not been ported to `v6`. @rafibomb Any thought on this ?
