### ISSUE TITLE
[Abide] Error problem with input-group

### ISSUE THREAD

**Issue by colinmackinlay** [zurb/foundation-sites#9581]
**How can we reproduce this bug?**

1. Create an input-group as per form documentation
2. Marks as required and put in an Abide form
3. Add span class="form-error" inside label or inside input group

**What did you expect to happen?**
Normal Abide error behaviour with form-error displayed and correctly positioned

**What happened instead?**
error does not display if just inside label. displays but messes up alignments if inside the input-group div

**Test case:**
http://codepen.io/colinmackinlay/pen/XprMXz

**Comment by colinmackinlay** [comment]
Looks like you've now picked this up with #9600 @ncoden ?
If so then close this one down

**Comment by ncoden** [comment]
Hi @colinmackinlay , sorry for not replied before.

You are right, this issue is the same as #9600. I close it.
