### ISSUE TITLE
[Forms] Improvement to File Upload Button - request

### ISSUE THREAD

**Issue by colinmackinlay** [zurb/foundation-sites#9582]
It would be nice if the File Upload button also displayed the filename that has been selected. Something like this:
http://codepen.io/colinmackinlay/pen/wgwJqG

Even nicer if it played nicely with Input Groups - I tried but it doesn't!

Fabulous if it also played nicely with Abide :)

**Comment by rafibomb** [comment]
This seems cool! It's more of a Building Block than a core component of Foundation. Though making the .input-group component less specific so that it works with the .button class and not need input would be a great feature request.
