### ISSUE TITLE
[Off-canvas] off canvas broken in 6.3

### ISSUE THREAD

**Issue by feeekkk** [zurb/foundation-sites#9584]
I've copied and pasted an example included in the docs for 6.3 in the codepen but it doesn't seem to function.

**How can we reproduce this bug?**

1. Step one
include the proper markup and foundation 6.3 js
2. Step two
click a button to open the off canvas
3. Step three
???

**What did you expect to happen?**
the off canvas' would open

**What happened instead?**
nothing.

**Test case:**
Give us a link to a CodePen or JSFiddle that recreates the issue.
http://codepen.io/feeekkk/pen/PWYejw

**Comment by Rand0mGuy** [comment]
That's not a bug. It's just that you forgot to include foundation 6.3.0 css in you codepen link. I've included it for you [http://codepen.io/anon/pen/MJgXqx](http://codepen.io/anon/pen/MJgXqxl)
