### ISSUE TITLE
[Sticky 6.3.0] Sticky element doesn't follow its container top position anymore

### ISSUE THREAD

**Issue by mlang38** [zurb/foundation-sites#9585]
As the GIF below shows, since I upgraded from 6.2.4 to 6.3.0, my sticky menu doesn't follow its container top position anymore. As I mentioned in [#9298](https://github.com/zurb/foundation-sites/pull/9298#issuecomment-269330187), changing the sticky element `position` from `absolute` to `relative` can induce problems.

In this video, the sticky container has light blue background. When the sticky element is not stuck, and when the viewport is shrinked (or when viewed from a narrow device), the container follow the up movement and keep the right height, but the sticky menu doesn't move. So the content below starts to slip under it. **Fixed by making the sticky menu absolutely positioned again, as in 6.2.4**.

![sticky_doesnt_follow_container](https://cloud.githubusercontent.com/assets/1927042/21587583/7862f6e6-d0de-11e6-9844-d40d70035583.gif)

**Comment by ncoden** [comment]
@mafrosis @karland Can one of you open a PR ?

**Comment by mlang38** [comment]
The #9298 PR fixes a FOUC issue, but perhaps could we make position: absolute by JS after the container height is first computed and applied ?

**Comment by mlang38** [comment]
After giving up and trying to remove sticky behavior, I realize that the shown bug was revealed by the #9298 PR but wasn't introduced by it, and actually comes from my own css. Sorry
