### ISSUE TITLE
CSS: Contact Chips or Closable inline component

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9586]
**Feature Request - Contact Chips** 
I Want zurb to add new feature thats very popular after cards in material frameworks after Cards 
But same like cards, chips are awesome for flat design too \
Something like this => http://materializecss.com/chips.html
Codebase => http://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_contact_chips_close

**Special Note**: Have proposed similar feature(s) in bootstrap too so sorry for any duplication n all. I Just love and use both frameworks in my projects, so a bit neutral and proposing to both :)

**Comment by ncoden** [comment]
This is two useful feature. Dropcaps can be added as a simple CSS utility.

For Chips, I wonder if we could implement it in a more generic way. Not a "contact chip", but only a "closable inline component".

**Comment by IamManchanda** [comment]
@ncoden are you accepting css transition tickets ( features ) also ?

asking this coz of Mr. IE 9 :smiling_imp: ?

**Comment by ncoden** [comment]
@kball Do we support IE 9 😈  ?

**Comment by IamManchanda** [comment]
Nice one :smiling_imp: .... 

yes you [support](http://foundation.zurb.com/sites/docs/compatibility.html). But for [Flexbox you dont](http://foundation.zurb.com/sites/docs/flexbox.html) and i am unsure about transitions

**Comment by ncoden** [comment]
So yes, you can open an issue about css transition/animations. :)

**Comment by IamManchanda** [comment]
Thanks a lot, 
But i must say have a thought that even bootstrap removed IE 9,
so how on earth and why on earth is foundation still relying on IE9 Support ?

**Comment by ncoden** [comment]
I have no idea. You can open an issue about it too.

**Comment by IamManchanda** [comment]
No thanks, i dont want to load you all up with too many issue requests :wink: :laughing:

**Comment by ncoden** [comment]
There is no problem with this. Please open an issue for any bug with Foundation or feature/support request.

**Comment by IamManchanda** [comment]
> There is no problem with that. Please open an issue for any bug with Foundation or feature/support request.

I have just did that https://github.com/zurb/foundation-sites/issues/9591

> Also, please open one issue per feature (or group of related features) request.

Do you want me to remove dropcaps and open a new feature request sir @ncoden ?

**Comment by ncoden** [comment]
> Do you want me to remove dropcaps from here and open a new feature request for that sir @ncoden ?

That would be great, yes :)

**Comment by IamManchanda** [comment]
@ncoden can you assign me up this buddy?

**Comment by ncoden** [comment]
@IamManchanda If you are working on an implementation, yes.

**Comment by IamManchanda** [comment]
>  If you are working on an implementation (or plan to), yes.

I plan to !

> Edit: it require you to have write rights on this repo.

Why would i need a write access in a simple PR ? 
any specific reasons ?

**Comment by ncoden** [comment]
No, I need you to have write access to assign you to an issue.

**Comment by kball** [comment]
@IamManchanda are you still interested in tackling this?

**Comment by IamManchanda** [comment]
@kball Yup interested ... thanks for assigning me .... sorry i missed this before .... will look into it soon .... maybe this weekend ... or early next week!

**Comment by IamManchanda** [comment]
Dang i missed this .... Ohk lets see if i can click this out this coming weekend!

**Comment by colin-marshall** [comment]
@IamManchanda good idea! Let's get this in 7!
