### ISSUE TITLE
JS: Smooth Scroll: Only for those links which require smooth scroll ( data attribute )

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9587]
**Feature Request - Smooth Scroll** 
Something like this => http://mdbootstrap.com/javascript/smooth-scroll/
Specially handy for landing pages and Call to action anchor tags 

Codepen => http://codepen.io/IamManchanda/pen/VPZMba

Source: CSS Tricks

**Special Note**: Have proposed similar feature in bootstrap too so sorry for any duplication n all. I Just love and use both frameworks in my projects, so a bit neutral and proposing to both :)

**Comment by ncoden** [comment]
I think this is a useful feature. We could add it in Foundation like this:
```html
<a href="#" data-smooth-scroll">Link</a>
```

However, I don't know if we should also provide an option to enable it by default for all, even without `data-smooth-scroll`. Could it create bugs ?

**Comment by IamManchanda** [comment]
@ncoden I am using this in my company and with a class or id selector just like my example, it dont create bugs, never had any issue but i dont have idea of "data-smooth-scroll" if it create any bugs

**Comment by ncoden** [comment]
@IamManchanda Using `data` attribute to apply JS behavior is proper, because of `.classes` is used for CSS styles and `#IDs` must be unique.

I wonder if there would be bugs with an option to apply smooth scoll by default for all links, because we could apply a smooth scoll where it is not expected.

**Comment by IamManchanda** [comment]
No No ..... with a data-smooth-scroll only would be better .... not to every link 

@ncoden yes For navbars we can do 

Codepen => http://codepen.io/IamManchanda/pen/JEjOmN

```
<ul class="menu" id="smooth-scroll-menu">
  <li><a href="#">One</a></li>
  <li><a href="#">Two</a></li>
  <li><a href="#">Three</a></li>
  <li><a href="#">Four</a></li>
</ul>
```

```
$('#smooth-scroll-menu >li > a[href*="#"]:not([href="#"])').click(function() {
  if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
    var target = $(this.hash);
    target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
    if (target.length) {
      $('html, body').animate({
        scrollTop: target.offset().top
      }, 1000);
      return false;
    }
  }
});
```

**Comment by ncoden** [comment]
Your code works, but we must implement it in a way it can be easily used. In your case, `#smooth-scroll-menu` can't be used twice.

**Comment by ncoden** [comment]
Do you want to open a PR ?

**Comment by IamManchanda** [comment]
Yup exactly thats why i said i am fine with your data-attribute also. Infact would be better. 

Yes i want to open a PR but i am new to `git` and even `data-attributes` so can you please do that from mah side buddy ??

**Comment by kball** [comment]
We could probably refactor out the code that handles this behavior for Magellan and turn it into a unique plugin.  See: https://github.com/zurb/foundation-sites/blob/develop/js/foundation.magellan.js#L111

**Comment by IamManchanda** [comment]
I am totally up for this @kball

**Comment by IamManchanda** [comment]
No No @ncoden i meant i was totally up for the idea of kevin ball
 
I am not that great at javascript at this moment, still learning its bits and pieces so it will be hard for me to do this assignment so please would urge you to unassign me for this 

At the same time i am very happy to have this https://github.com/zurb/foundation-sites/issues/9592 assigned to me and will do my best !

**Comment by ncoden** [comment]
Ok. So I'll take care of this issue. 😄

**Comment by denisahac** [comment]
This would be a great addition to the framework. I've been using Foundation framework for a good amount of time, and still ended up using this code snippet from [CSS-Tricks](https://css-tricks.com/snippets/jquery/smooth-scrolling/) to implement the internal links smooth scrolling.

```javascript
$(function() {
  $('a[href*="#"]:not([href="#"])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html, body').animate({
          scrollTop: target.offset().top
        }, 1000);
        return false;
      }
    }
  });
});
```

As @kball mentioned, the smooth scroll exists in the Magellan module, so making it as a unique module in its own would be a great addition.

Thanks @IamManchanda for bringing this 👍

**Comment by IamManchanda** [comment]
Yup @denisahac ..... Same here buddy .... Same like you !!!

**Comment by IamManchanda** [comment]
closing this as added here #9636
