### ISSUE TITLE
Bordered Buttons : bordered class for foundation

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9588]
To be honest, 
zurb's best quality i feel is that they are the best when it comes to starting from scratch and modify as you want and surely this feature request isn't that type of use case for sure !!!
but still i purpose a `bordered` class for foundation 6 ( tiny border-radius )

**Comment by Deckluhm** [comment]
Foundation's main goal is indeed to give us a set of tools to build our websites / apps "foundation".

Borders are more about **style** than **structure** so I don't think it should be in Foundation core.

It's really important for a framework (and more generally for any product) to stay focus on his main mission (and not to try to do anything to please anyone).

**Comment by IamManchanda** [comment]
ohk @Deckluhm no issue .... I really understand that and will be happy closing this but still i would like as a last cry would want to get @zurb's throughts on this request.

**Reason:** Not to please one but many !!!

cc / @hellapixels @ncoden @rafibomb  @brettsmason guys ...

**Comment by DaSchTour** [comment]
So basically you would like to have hollow buttons with a defined background? I would suggest to add a third variant to `$button-fill`

**Comment by ncoden** [comment]
I agree with @Deckluhm. We cannot add options to support every single CSS property. Tiny border radius require nothing more than a single line of code, there is no reason to add an additional layer with Foundation.

Also, I think we currently have a lot of options to handle properties like this one (for border, background, color...), and should made some cleanup.

**Comment by IamManchanda** [comment]
ohk no issue @ncoden @Deckluhm .... thanks ...closing this ....
