### ISSUE TITLE
CSS3 Transitions & Micro Animations: Motion UI

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9590]
Here are some examples (set of css transitions) to motivate it out and eventually include some of these (if not all) to motion ui !

**Special Note**: All of these micro animations that i am including are only the one that can be useful for most of the modern websites and applications and the one **which make sense to put in on focus**

**Micro Animation for Buttons** #9553 
http://codepen.io/IamManchanda/pen/Pbvmxg

**CSS Hamburger Menu(Open & Close)** #9675 
http://codepen.io/edoardo-bluframe/pen/dMZaMa

**Modal Box Animation**
http://codepen.io/koolhaus/pen/ajwcE

**Animated Input Form on focus**
http://codepen.io/IamManchanda/pen/XpraGx

**CSS Smooth Checkboxes**
http://codepen.io/edoardo-bluframe/pen/yOPjBB

**CSS Drawers**
http://codepen.io/edoardo-bluframe/pen/aNpZBR

**CSS Typewritter effect** 
The same effect that you look up when you open the slack homepage
https://css-tricks.com/snippets/css/typewriter-effect/

**Comment by IamManchanda** [comment]
Awaiting reply @kball

**Comment by kball** [comment]
I'm interested in exploring the bigger picture on this... are there a set of animations that make sense to put in on focus?

**Comment by IamManchanda** [comment]
@kball : Yes there are some

for example :
CSS Typewritter effect ( The same effect that you look up when you open the slack homepage ) 
https://css-tricks.com/snippets/css/typewriter-effect/

But yes a bit unsure whether these type of things should be put up in the core or not ?

**Comment by kball** [comment]
Probably not in core - more likely they'll be a part of MotionUI, if we decide to add them.

**Comment by IamManchanda** [comment]
> Probably not in core - more likely they'll be a part of MotionUI, if we decide to add them.

So so should i forward this one to motion ui and also this typewritter effect ?

**Comment by kball** [comment]
I think eventually yes, that said, there is a larger audience here and this is something I'm interested in more opinions & thoughts on, so lets leave it here for now.

**Comment by IamManchanda** [comment]
> I think eventually yes, that said, there is a larger audience here and this is something I'm interested in more opinions & thoughts on, so lets leave it here for now.

Ohk will leave this open here

**Comment by IamManchanda** [comment]
@kball : With the inspiration from to the mail i recieved from zurb about micro animation, 
i have updated my list ..... hope you will like it!

#MotionUI

**Comment by colin-marshall** [comment]
@IamManchanda closing this one out to possibly revisit in F7.
