### ISSUE TITLE
Why Browser Support is still held for IE 9

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9591]
Last few weeks, even frameworks like bootstrap have taken this big steps like 

1.) Removing IE9 Support 
2,) Make it a flexbox only grid system 
3.) RIPing out any IE9 Crutches like `X-UA-Compatible`

**We all know that semantic ui also only support IE 11+**

Web is moving forward and i feel like foundation should too ?
This will not only help make foundation better but also this will help the old lame browser to be removed from the web like what happened to IE 6-8

**Comment by RamanCool** [comment]
You hit the bulls eye !

**Comment by kball** [comment]
Certainly v7 should not include IE9 support.  I go back and forth about removing it in v6... my inclination would be more to make the flexbox grid the default but still maintain the ability for folks who need it to enable "compatibility mode".  @zurb/yetinauts what do ya'all think?

**Comment by brettsmason** [comment]
I'm conflicted on removing Ie9. I currently have to support it at work due to lots of government clients who are unfortunately still stuck on older versions. If ie9 wasn't supported I would have to find a way to support it, or use something else.

Having said that I would love to move to newer things like flexbox and remove the old, it really is still very client dependent for me though. 

I think @andycochran is in a similar situation if I remember correctly.

**Comment by JeremyEnglert** [comment]
I don't think removing it from 6 would be a good idea - as we can keep 6 available for users who need to support older browsers even after 7 has been released. 

However, I do think the percentage of IE9 users is so low it merits removing it from the next version of Foundation. Especially if this allows us to focus on Flex Box as the primary grid.

**Comment by IamManchanda** [comment]
Let's do it for 7 then ..... How about adding this to roadmap ( foundation 7 ) ? 
1.) Removing IE 9 
2.) Focus on flexbox only grid system
3.) More Focus towards CSS transitions / Animations 
4.) Ripping out any IE 9 Crutches within templates or docs

**Comment by IamManchanda** [comment]
cc / @kball @brettsmason @ncoden @zurb/yetinauts

**Comment by IamManchanda** [comment]
Update: IE9 global browser usage is now just 0.25% ( lower than IE8 ) ...... so it makes more sense to remove IE9 Support!

**Comment by kball** [comment]
I think we can conclusively say we will be dropping IE9 support in 7. For 6.X we're going to continue support at least for all existing components, and new features should degrade gracefully.

**Comment by IamManchanda** [comment]
So does it mean i can use something like `text-noselect` ( for eg prototypes PR ) ??
=> http://caniuse.com/#feat=user-select-none

**Comment by kball** [comment]
@IamManchanda for new features you are welcome to exclude IE9, so long as you indicate it and the degradation is reasonably graceful.

Other than that, I've added removing IE9 and IE10 support to the roadmap for 7, and going to close this issue.

**Comment by IamManchanda** [comment]
@kball Wow IE10 also .... great!!!
