### ISSUE TITLE
Foundation installed through NPM requires global jQuery and $ variables

### ISSUE THREAD

**Issue by WouterFlorijn** [zurb/foundation-sites#9611]
Very simple issue. Using Foundation through Node.js requires you to do something like

```
global.jQuery = global.$ = require('jquery');
require('foundation-sites');
```

Which is bad practice and doesn't work with certain compilers due to execution order. I suggest this to be fixed by simply letting the Foundation package `require('jquery')` on its own.

**Comment by kball** [comment]
We'll be addressing this as a part of https://github.com/zurb/foundation-sites/issues/9438

**Comment by colin-marshall** [comment]
I believe this can be closed now.
