### ISSUE TITLE
Do have any plan for Zurb F and Vue?

### ISSUE THREAD

**Issue by donPuerto** [zurb/foundation-sites#9612]
Well, Zurb Framewok is really awesome. But why not try to use Vue JS instead. ;)

**Comment by DaSchTour** [comment]
Wie Vue JS and not React instead. By I like Aurelia more. Take a look on the [roadmap](https://github.com/zurb/foundation-sites/wiki/Project-Roadmap) and what discussed here #9438 around es2015 modules to bridge to different frameworks

**Comment by IamManchanda** [comment]
Vue because it's very easy together with Laravel ( PHP ) 
Being me a learning PHP developer, I would also like to have something like that but maybe that's just me

**Comment by QWp6t** [comment]
As mentioned above, read the roadmap:

> We don’t think Foundation should pick a javascript framework, rather it should be accessible in every framework. This is learning from challenges and mistakes made while making Foundation for Apps. We believe we should be supporting common Apps use cases but not "picking a winner" in terms of JavaScript framework. Instead we should work with the community to achieve high quality integrations in every framework.

**Comment by colin-marshall** [comment]
This is the direction we are looking to head in for F7. Closing this out.
