### ISSUE TITLE
[Card] Card not in app.scss when using foundation CLI

### ISSUE THREAD

**Issue by daveybrown** [zurb/foundation-sites#9615]
#### How to reproduce this bug:

1. Use foundation CLI to install a foundation site

#### What should happen:

@include foundation-card; should be in scss/app.scss

#### What happened instead:

@include foundation-card; is not in scss/app.scss

#### Test case:

N/A

**Comment by dlewand691** [comment]
Can also confirm this issue.

**Comment by kball** [comment]
Fixed in https://github.com/zurb/foundation-sites-template/pull/15
