### ISSUE TITLE
Off-canvas menu not working with Foundation 6.3 but works with older version

### ISSUE THREAD

**Issue by kelster44** [zurb/foundation-sites#9619]
I had been developing an off-canvas menu that was mostly working (with the exception of the close button on the drill down menu). I changed the link to the updated 6.3.0 version of Foundation and it quits working. Also, my desktop menus require clicks to open instead of hovers. However, if I use version 6.2.4 then the responsive accordion tabs don't work!!

Am I not including something that I should be? I thought foundation.js included all of the files so that I didn't have to import anything.

**Comment by Deckluhm** [comment]
Can you provide a CodePen reproducing the error?

And always be sure to use the latest version of the JS **and** CSS files (some JS components rely heavily on CSS).

**Comment by kball** [comment]
Closing this based on lack of response
