### ISSUE TITLE
Problem with multiple data-toggle buttons in title-bar (responsive navigation)

### ISSUE THREAD

**Issue by mitch827** [zurb/foundation-sites#9621]
Hi all, I encountered what I think is a little bug, but maybe is my code that's plain wrong, so forgive me if that's the case.

#### How to reproduce this bug:
1. Use the "Responsive Toggle" code (as shown here: http://foundation.zurb.com/sites/docs/responsive-navigation.html )
2. Add a Dropdown pane in the title-bar div (code used: http://foundation.zurb.com/sites/docs/dropdown.html )
3. Click on the dropdown toggle

#### What should happen:
Only the dropdown pane should opens.
#### What happened instead:
Both the dropdown pane and the top-bar navigation dropdown open.
#### Test case:
- [Codepen with foundation 6.3](http://codepen.io/mitch827/pen/JEYLKV)

**Comment by kball** [comment]
Interesting... this is definitely a bug in the responsive toggle plugin. It appears to be coming from here: https://github.com/zurb/foundation-sites/blob/develop/js/foundation.responsiveToggle.js#L41

The plugin grabs all toggles inside it, and doesn't pay attention to what the target is for triggering the responsiveToggle.

I think this is kind of silly... that toggle itself should be sufficient if it is pointing to the id in question... the only time the responsive toggle itself should be needed to do the toggling is if the internal toggle doesn't have a target but the responsive toggle does.
