### ISSUE TITLE
Travis recurring failures

### ISSUE THREAD

**Issue by kball** [zurb/foundation-sites#9623]
We're running into recurring "phantom" failures with our travis automated testing, usually related to network problems during NPM install.  I'm not sure what it will take to resolve these, but it looks like some options we can explore are using the

`travis_retry` command (see https://github.com/travis-ci/travis-ci/issues/3130)

Use yarn instead of npm install and utilize the travis install caching features (https://docs.travis-ci.com/user/caching/)

Other thoughts?

**Comment by IamManchanda** [comment]
same here +1

**Comment by IamManchanda** [comment]
what i know with my commits @kball is that .... when its morning in india, travis passes my commits and when its night.... i get network connectivity issues

**Comment by IamManchanda** [comment]
Any updates Kevin sir :disappointed: :disappointed_relieved: ??

**Comment by colin-marshall** [comment]
@IamManchanda any idea if this still applies?

**Comment by DanielRuf** [comment]
I guess this is not relevant anymore. We moved to a headless Chrome solution and I did not see any timeouts directly related to Travis or npm.

**Comment by colin-marshall** [comment]
Thanks @DanielRuf. Closing this one out. If anybody feels I have done so in error, feel free to reopen it.
