### ISSUE TITLE
How do we map-deep-get() values from $header-styles in 6.3?

### ISSUE THREAD

**Issue by erutan** [zurb/foundation-sites#9624]
Before if I wanted to pull a font-size into a custom component I could do something like the following: `font-size: rem-calc(map-deep-get($header-sizes, small, h1));` 

The following (markup might be wrong for nesting another level?) doesn't work in 6.3: `font-size: rem-calc(map-deep-get($header-styles, small, font-size, h1));` gives me the following error:

```
`Error in plugin 'sass'
Message:
    bower_components/foundation-sites/scss/util/_value.scss
Error: argument `$map` of `map-get($map, $key)` must be a map
 
       Backtrace:
        bower_components/foundation-sites/scss/util/_value.scss:104, in function `map-get`
        bower_components/foundation-sites/scss/util/_value.scss:104, in function `map-deep-get`
        bower_components/foundation-sites/scss/ucla/_form-tweaks.scss:7
        on line 104 of bower_components/foundation-sites/scss/util/_value.scss
>>     $map: map-get($map, $key);
   ----------^
```

https://github.com/zurb/foundation-sites/issues/7826

**Comment by ncoden** [comment]
See: [scss/typography/_base.scss:55](https://github.com/zurb/foundation-sites/blob/v6.3/scss/typography/_base.scss#L55):
```scss
$header-styles: (
  small: (
    'h1': ('font-size': 24),
    'h2': ('font-size': 20),
    'h3': ('font-size': 19),
    ...
  ),
  ...
);
```

So you should use: `map-deep-get($header-styles, small, h1, font-size)`.

**Comment by erutan** [comment]
...... yeah I should have caught that.
