### ISSUE TITLE
Drilldown not displaying if used with responsive toggle and data-animate

### ISSUE THREAD

**Issue by brettsmason** [zurb/foundation-sites#9627]
If a drilldown menu is toggled using the responsive toggle plugin, along with the `data-animate` option, the drilldown menu receives the properties which cause it not to be visible:

```
min-height: 0px;
max-width: 0px;
```
The max-width being the one that is causing the menu not to display.
See [this CodePen](http://codepen.io/brettsmason/pen/mOvddr) as an example.

**Comment by kball** [comment]
The main bug appears to be that the animations break if the motion-ui styles are not there, which results in the animation callbacks not being hit and certain triggers never firing.

We do not include the motion-ui styles by default in the distributed foundation.min.css, but if I add https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.2.2/motion-ui.css to the pen in question the bug goes away.

**Comment by besseddrest** [comment]
@kball 

I am experiencing this issue still

```
<div class="title-bar" data-responsive-toggle="burger-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="burger-menu"></button>
</div>
<div id="burger-menu" data-animate="slide-in-left" data-closable="slide-out-left">
  <div id="primary-nav">
    <ul class="vertical menu medium-horizontal">
      <li><a href="#">Item A</a>
        <ul class="nested vertical menu drilldown" data-drilldown data-auto-height="true" data-animate-height="true">
          <li><a href="#">Item 1</a></li>
          <li><a href="#">Item 2</a></li>
        </ul>
      </li>
      <li><a href="#">Item B</a></li>
      <li><a href="#">Item C</a>
        <ul class="nested vertical menu drilldown" data-drilldown data-auto-height="true" data-animate-height="true">
          <li><a href="#">Item 1</a></li>
          <li><a href="#">Item 2</a></li>
          <li><a href="#">Item 3</a>
            <ul class="menu vertical nested hide-for-medium">
              <li><a href="#">Hello</a></li>
              <li><a href="#">World</a></li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>
```
If I load the page in desktop view, shrink the page to a mobile size so the burger-menu icon displays, when I click to toggle the menu, only Item A's sub menu will display.

Neither of the nested menus under Item C will display. 

If I remove `data-animate`, then everything works fine, but no animation.

I am compiling the foundation.scss and app.scss together into a single css file. I include that first, then below that I include the motion-ui.css file.

Any thoughts?
