### ISSUE TITLE
Angular 2 tip: use attr.data, eg. with variables for sticky, magellan

### ISSUE THREAD

**Issue by klihelp** [zurb/foundation-sites#9631]
#use attr.data-anchor for sticky variable to avoid error:
`Can't bind to 'data-anchor' since it isn't a known native property..`

`<div class="sticky" data-sticky data-margin-top="0" attr.data-anchor="post_{{post.id}}">`

**Comment by ncoden** [comment]
Hi @klihelp,

I do not understand your issue very well, or how we could resolve it. Are you sure it relates to `foundation-sites` and not `foundation-apps` ?

**Comment by klihelp** [comment]
It was just a tip for those looking for angular 2 integration in your issues list.
