### ISSUE TITLE
Backwards compatibility with legacy media query variables

### ISSUE THREAD

**Issue by michaelBenin** [zurb/foundation-sites#9637]
After upgrading our app to latest foundation, we were happily greeted with legacy and deprecation warnings for using the `@include foundation-responsive-embed;` But we also had a failing build because of our usage of legacy media query variables such as $large-up etc. 

It's really not a huge deal as we went into our app and changed all the old references.

**Comment by rafibomb** [comment]
Hmmm, I think large-up and medium-up were deprecated from F5 but perhaps a bit after 6 launched. I think the deprecation warning can be done another way. Perhaps only if the component is being used?

**Comment by michaelBenin** [comment]
It's a variable so I'm not sure how you would have a deprecation warning in this case.
