### ISSUE TITLE
Optional extend .column .columns

### ISSUE THREAD

**Issue by IllusionPerdu** [zurb/foundation-sites#9640]
Hello,

In file foundation-sites/scss/grid/_classes.scss they are : 
```sass
@if $column == 'column' {
    .columns {
      // sass-lint:disable-block placeholder-in-extend
      @extend .column;
    }
  }
```

I think it's sould be good if they are a option to extend or not. Advantage : the generate file size reduce if tit's not inculde and the user who use ".columns" can include if they want .

What do you think ?

**Comment by ncoden** [comment]
Hi @IllusionPerdu,

First, please use ` ``` ... ``` ` when you write code. (see https://guides.github.com/features/mastering-markdown/)

Then, I think an option to enable/disable `.columns` extension is a good idea. I personally think this alias should be removed (it is not useful, often not used, and takes a lot of place in the generated CSS), but making it optional is a good start.

**Comment by stefan2** [comment]
filesize... good point.

Make column class variable?

$column-class: 'columns';

What do you think?

**Comment by ncoden** [comment]
@stefan2 

> Make column class variable?

The current standard class name for columns is `.column`. I agree we could make it customizable (like all class names), and this could be a part of https://github.com/zurb/foundation-sites/pull/9513, but this is an other issue.

**Comment by stefan2** [comment]
Just perfectly!

**Comment by IllusionPerdu** [comment]
Sorry for not use of ```code``` ;)

The big job is the doc in many place the exemple was with the alias ```.columns```

The ```.columns``` appear in ```foundation-sites/scss/components/_reveal.scss``` 
```sass
// Make sure rows don't have a min-width on them
  .column,
  .columns {
    min-width: 0;
  }
```
Another argument:
Internet explorer have a limit in number of selector per css file : https://blogs.msdn.microsoft.com/ieinternals/2011/05/14/stylesheet-limits-in-internet-explorer/ 
Deleting this rule allows you to have less chance of crossing this limit

**Comment by ncoden** [comment]
Internet Explorer... 😭
