### ISSUE TITLE
[Global Styles] Mixin paragraph is empty

### ISSUE THREAD

**Issue by massimo-cassandro** [zurb/foundation-sites#9641]
#### How to reproduce this bug:
visit page [http://foundation.zurb.com/sites/docs/global.html](http://foundation.zurb.com/sites/docs/global.html)

The last Paragragh, Mixins, contains only
>>We use these mixins to build the final CSS output of this component. You can use the mixins yourself to build your own class structure out of our components.

any other information is missing

**Comment by colin-marshall** [comment]
@ncoden @IamManchanda is this worth keeping open?

**Comment by ncoden** [comment]
It's a problem with Foundation Docs.
