### ISSUE TITLE
Select styling defect after removing vendor prefixes

### ISSUE THREAD

**Issue by bertfroeba** [zurb/foundation-sites#9643]
#### How to reproduce this bug:

1. Create a `select` box.
2. Open in Chrome (55+) or Firefox (46) 
3. Look at the `select` box

#### What should happen:
You should see a foundation styled `select` box

#### What happened instead:
You see a browser styled `select` box
Chrome Windows: Two arrows will appear
Chrome Mac: Standard Up/Down arrow appears
Firefox: Standard down arrow appears

![capture](https://cloud.githubusercontent.com/assets/20280797/21935192/77509ab4-d9a4-11e6-809a-9bc7771e13ed.PNG)

Introduced in https://github.com/zurb/foundation-sites/commit/90d9810e84c134620c0459fc0d550d1bd2cfb8cd with removal of vendor prefixes.  

#### Test case:

Difficult to do with CodePen as it claims to be `6.3.0` but the static version available does not include the Change mentioned above.

6.3.0 on CloudFlare as this for `select`:
```
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
```

6.3.0 on npm as this for `select`:
```
appearance: none;
```

**Comment by ncoden** [comment]
Hi @bertfroeba

Like mentioned at https://github.com/zurb/foundation-sites/commit/90d9810e84c134620c0459fc0d550d1bd2cfb8cd, we use Autoprefixer (and advise to use it if you compile Sass by yourself), which takes care of appearance vendor.

> 6.3.0 on npm as this for select

Of what file are you talking about ? CSS file or SCSS sources ?

**Comment by bertfroeba** [comment]
SCSS sources are being used.  Like you mentioned about Autoprefixer, looking at incorporating that now.

**Comment by ncoden** [comment]
I close this issue. Please reopen it if you still have a problem with Autoprefixer.

**Comment by bertfroeba** [comment]
Yep, all sorted now with autoprefixer, many thanks.
