### ISSUE TITLE
Social Buttons (CSS Classes)

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9646]
Motivation: http://mdbootstrap.com/components/social-buttons/

Can be a perfect partner to http://zurb.com/playground/foundation-icon-fonts-3

What it will help us achieve 

```html
<button type="button" class="button facebook">
  <i class="fi-social-facebook"></i>
</button>
```

Use Case: Can be very helpful for social login, sharing and more!

{{ **Rest on you guys to decide** }}

**Comment by ncoden** [comment]
This is not a bad idea, but I see a main problem: "Social Buttons" is a design modifier of Button, while social buttons can take _a lot_ of different and various designs.

What design should we provide by default ?
Would most of the users have to customize their design anyway ?

**Comment by IamManchanda** [comment]
Provide a icon with white color and background with the colour of the social brand ..... simple buttons like normal foundation buttons

And let them decide to choose this 

```html
<button type="button" class="button facebook">
  <i class="fi-social-facebook"></i>Facebook 
</button>
```

or this 

```html
<button type="button" class="button facebook">
  <i class="fi-social-facebook"></i>
</button>
```

**Comment by IamManchanda** [comment]
I don't think we need to create different designs .... That's not our goal I guess .... 
=> Structure and not style 
We just need to create structure .... and leave different designs on users

**Comment by IamManchanda** [comment]
To anyone concerned .... moving this to building blocks!
