### ISSUE TITLE
CSS & JS: Waves (Ripple) effects for Foundation Buttons

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9647]
**Motivation:** 

1. https://angular.io/
2. http://materializecss.com/waves.html
3. http://mdbootstrap.com/javascript/waves-effect/

**Past Implementation's** : Google Material Design  

**Codepen Demo** => http://codepen.io/IamManchanda/pen/NdroWz
**Demo Source**: Michal Szymanski's (Founder - MDBootstrap) Codepen's fork

**HTML** i would like for it

```html
<button type="button" class="primary ripple button">Harry loves Creativity</button>
```

Sass Configuration variable i would be looking for 

```scss
$ripple-effect-color
```

**Not a `dumb` idea for flat design and the modern web !!!**

**Comment by ncoden** [comment]
I agree that waves on buttons are a central element in Material Design and seems today like a most-have in "modern" applications. But it is an effect specific to Material Design.

Foundation can not provide utilities and graphical modifiers for every single design, and should only provide _simple_ and _easily customizable_ components. Wave effect on buttons would be a great idea for a _Material theme for Foundation_, but not in _Foundation itself_.

Wave effects are specific to Material Design, not customizable at all, and for these reasons I think it should not be added in Foundation.

**Comment by IamManchanda** [comment]
ohk no issue buddy but still as a last cry....

@kball @brettsmason thoughts ?

**Comment by IamManchanda** [comment]
Also @ncoden , 

> Oh Material specific component, sorry but we can't add 

if that's the case buddy, then what are cards doing in foundation?

**Comment by ncoden** [comment]
Card are not specific to any design. There is a lot of different ways to show and use cards.

**Comment by IamManchanda** [comment]
First of all, I am very sorry for a bit rude and harsh comment above ...... 

--------------------------------------------------------------------------------------------------------------------------------------

I think that this is high time when flat design's should become less flat and less muted for the sake of modern web and user experience! But maybe that's just me !

**Comment by ncoden** [comment]
> First of all, I am very sorry for a bit rude and harsh comment above ......

Not a problem at all. We should be consistent, so it is normal to question the current Foundation's components with the affirmations I made.

> I think that this is high time when flat design's should become less flat and less muted for the sake of modern web and user experience

I totally agree with you. I do not like Flat design at all, and think Material design is still too plat (too "paper"). I would be happy to create a theme for Foundation with a lot of new graphic stuff and effects. The problem is only we cannot add things that are too specific to Foundation, so it give a flat design, but it is not intended.

**Comment by IamManchanda** [comment]
Yup even i don't like material design (specifically for desktop, for mobile i like because you want paper in your small hands not a whiteboard) but my thoughts are still bit different then you for flat or AlmostFlat design.

A Design or simply a designer needs a structure to get started with and what i asked for is a simple `ripple`' class and to provide configuration variables like `$ripple-effect-color` for easy customization ??

**Comment by IamManchanda** [comment]
awaiting thoughts/reply/view @kball ?

**Comment by kball** [comment]
I think we need to keep graphical "flares" like this to themes and building blocks... and to get there we need to make those themes & building blocks more first class citizens in terms of how they are made, distributed, and integrated.

**Comment by IamManchanda** [comment]
ohk no issue kevin sir .... i have a bit different views but thats ohk .... thanks !
