### ISSUE TITLE
ios 8.3 or lower issues with rendering of elements, tested with Foundation switch markup

### ISSUE THREAD

**Issue by otemu** [zurb/foundation-sites#9649]
**How to reproduce this bug:**

Using the switch markup found on the foundation [site](https://foundation.zurb.com/sites/docs/switch.html)

```
<p>Do you like me?</p>
<div class="switch large">
  <input class="switch-input" id="yes-no" type="checkbox" name="exampleSwitch">
  <label class="switch-paddle" for="yes-no">
    <span class="show-for-sr">Do you like me?</span>
    <span class="switch-active" aria-hidden="true">Yes</span>
    <span class="switch-inactive" aria-hidden="true">No</span>
  </label>
</div>
```

The text becomes out of alignment on ios8.3 or lower, tested with Foundation 6 css complete version(6.3.0) and github template https://github.com/zurb/foundation-zurb-template

To replicate this please use a apple device that has ios 8.3 or lower
I got this bug on ipad air 2 (ios8), ipad air (ios7), iphone6s(ios8), iphone6 Plus(ios8) and ipad air(ios8.3)

What should happen:

Elements should render in there correct position on ios, when using downloaded css version or foundation-zurb-template.  I was getting several alignment issues only in ios with foundation, where at times elements would render out of alignment. 

I would expect the default switch markup used on foundation site to vertically align center but the alignment of text goes to the bottom, this only happens on ios8.3 and below, i think fixing this issue should resolve other ios quirks that were happening.

Test case:

The issue however doesn't exist on the foundation 6 site if you view the switch directly on the site using ios8.3 or when using the cdn version from cdnjs 

The issue happens with:
css "complete" downloaded from foundation [site](http://foundation.zurb.com/sites/download.html/)
or template version https://github.com/zurb/foundation-zurb-template

I have created two codepens for the issue to be tested one with working version and other not working

[cdnjs version]( https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.css) 6.3.0 which works
[Foundation 6.3.0 IOS 8 Working](http://codepen.io/creativeo/pen/qRNGLj)

Foundation 6 css version complete which doesn't work
[Foundation 6.3.0 IOS 8 Broken](http://codepen.io/creativeo/pen/bgeyQz)

**Comment by IamManchanda** [comment]
can you specify which code you changed through which the error was corrected ?

**Comment by otemu** [comment]
I didn't change any code, as I got the issue using the github template I attempted as a quick test with a cdn version this one https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.css when I saw it was working with that I than tried with the foundation site complete css version but the issue happened again. The codepen.io I provided is foundation css version which is not working and other is just the copied css from cdn js, I've made no changes

**Comment by kball** [comment]
Ugh it looks like the customizer build (which is used for the complete download) is using a *different* set of config settings than the main build, resulting in a different autoprefixer config.

This definitely should get fixed.

@zurb/yetinauts anyone have bandwidth to take a pass on this in the next day or two?

**Comment by kball** [comment]
@tdhartwick can you take a look at this?

**Comment by DanielRuf** [comment]
Is this fixed?

**Comment by DanielRuf** [comment]
Also which exact Safari version is installed and used?

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
