### ISSUE TITLE
[Menu] Bug with a computer (and tablet) that has a touch screen

### ISSUE THREAD

**Issue by IllusionPerdu** [zurb/foundation-sites#9652]
#### How to reproduce this bug:

1. Go to : http://foundation.zurb.com/sites/docs/
2. with a touch screen tap for exemple "Tutorial"
=> the menu open
3. try to tap a submenu example : "Lessons"
=> the menu close an don't open the page

#### What should happen:
the page sould open the link

#### What happened instead:
=> the menu close and nothing

The problem is reproductible with 
=> chrome on windows 10 
=> firefox on windows 10 
=> edge on windows 10
=> chrome on android device

**Comment by IamManchanda** [comment]
First of all, are you talking about phones or tablets ? 

Because there is no such **`menu -> submenu`** in mobile 
there is only [hamburger menu](https://en.wikipedia.org/wiki/Hamburger_button)  which opens a menu and all the links are there only

**Comment by IllusionPerdu** [comment]
I have view this bug with a computer or tablet no with a tel ;)

**Comment by IllusionPerdu** [comment]
The code example of the page http://foundation.zurb.com/sites/docs/dropdown-menu.html was affected it's don't change the hash with tap

**Comment by IamManchanda** [comment]
Yup this is a issue with touch screen!

**Comment by IamManchanda** [comment]
In short , 

**This is a bug specific to Dropdown Menu. The Links are not clickable on any submenu of the dropdown menu within any Touch Screen devices(mobile, desktop, tablet, etc) !** 

Thanks for reporting.

cc / @kball @gakimball

**Comment by IllusionPerdu** [comment]
I don't know if is oki after this  change in /js/foundation.dropdownMenu.js  aparently it work

```
        // Handle Leaf element Clicks
        if (_this.options.closeOnClickInside) {
          this.$menuItems.on('click.zf.dropdownmenu touchend.zf.dropdownmenu', function (e) {
            var $elem = $(this),
                hasSub = $elem.hasClass(parClass);
            if (!hasSub) {
              return true;      //this is added
              //_this._hide();  //this is remove
            }
          });
        }
```

**Comment by IllusionPerdu** [comment]
in the develop branch it's ok ;)
