### ISSUE TITLE
[Tabs] inconsistent use of active class

### ISSUE THREAD

**Issue by aldees** [zurb/foundation-sites#9657]
The Tab component use .is-active, however the Menu component use .active

Need consistent naming of 'active' class.  I had a scenario where i needed to toggle the active state of both a tab and menu item at the same time.  But, because they use different classes for active, I had to it in two lines instead of one.  Please, update the Tabs component to use 'active' instead of 'is-active'.

Example:
$('my-tab-item, my-menu-item').toggleClass('active');

instead i had to split it up:
$('my-tab-item').toggleClass('is-active');
$('my-menu-item).toggleClass('active');

**Comment by kball** [comment]
I think we should actually move everything to `.is-active`, as these are state classes. Would accept a PR moving menus to `.is-active`.

**Comment by jmp1548** [comment]
Is this still an open issue? I can look into correcting it.

**Comment by IamManchanda** [comment]
> I can look into correcting it.

@jmp1548 .... Sure, why not!

**Comment by colin-marshall** [comment]
I believe @jmp1548 took care of this with #9757, so I'm going to close this out.
