### ISSUE TITLE
Missing centered classes

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#9662]
I have downloaded the latest version of Foundation but there are no centering classes mentioned in the documentation: http://foundation.zurb.com/sites/docs/grid.html

**Comment by ncoden** [comment]
Hi @ivanjaros,

How did you downloaded Foundation ?

**Comment by ivanjaros** [comment]
From the foundation site(custom build - only changed grid to flex). I think this issue might be due to Flex grid. I had missing classes/features with flex grid before so I'm pretty sure that is the case again.

**Comment by ncoden** [comment]
Grid and Flex Grid do not currently provide the same features. Please refer to `http://foundation.zurb.com/sites/docs/flex-grid.html` for the grid documentation if you have flex-grid enabled.

However, I agree that all the Grid features should be provided by Flex Grid too. This can be a part of https://github.com/zurb/foundation-sites/issues/9569.

**Comment by kball** [comment]
@canterberrie can you add this for 6.4?

**Comment by rafibomb** [comment]
The centering docs for the float (default) grid can be found here: http://foundation.zurb.com/sites/docs/grid.html#centered-columns

The flex grid centering classes can be found here: http://foundation.zurb.com/sites/docs/flex-grid.html

**Comment by rafibomb** [comment]
I searched the 6.3.1 download with flex grid enabled and see the classes for centering vertically and horizontally. Was there a particular behavior you are missing? What were you trying to do that didn't work @ivanjaros

**Comment by JeremyEnglert** [comment]
No response from original poster. Closing.
