### ISSUE TITLE
[Abide] liveValidate input no error color

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites#9666]
input is-abide-error class un live validation get overwritten by focus class
see the first input, it's liveValidate true but the input field gets the red background only on lose focus

http://codepen.io/designerno1/full/dNOKYP/

**Comment by ncoden** [comment]
See: [scss/forms/_error.scss:45](https://github.com/ncoden/foundation-sites/blob/7cd9f63372b88aed877cad1b9764a9b5a95f7107/scss/forms/_error.scss#L45).

This is an expected behavior. Do you think we should change the design ?

**Comment by designerno1** [comment]
hmmmm i think error is error so it should turn error state
but why is it an expected behavior what thought
@zurb/yetinauts what do you think

**Comment by DanielRuf** [comment]
@ncoden should we keep the current behavior?

**Comment by DanielRuf** [comment]
I think we should keep it as is for now.
