### ISSUE TITLE
[reveal][>=5.5.1 && <6.x] Configure on the fly not working

### ISSUE THREAD

**Issue by liyaodong** [zurb/foundation-sites#9667]
#### Test case:
http://codepen.io/liyaodong/pen/mROreZ?editors=1010

#### What should happen:
1. click`set js-custom-close-class`, 
2. open the Modal
3. when click `custom close btn`, the Modal should close

#### What happened instead:
Modal not close

#### foundation 5.5.0 doesn't have this issue
http://codepen.io/liyaodong/pen/OWbdRm?editors=1010

**Comment by colin-marshall** [comment]
@liyaodong very sorry for the late response to your issue. We are moving on to Foundation 7, and there will be no more development or support for Foundation 5. I am closing this one out.
