### ISSUE TITLE
normalize.scss is to specific for Foundation

### ISSUE THREAD

**Issue by wolfgang-demeter** [zurb/foundation-sites#9668]
We are using the 6.3.0 SCSS-Version of foundation-sites and ran into an issue, where `_normalize.scss` is to specific for Foundation!

If you set for example `$body-font-family: 'Times New Roman', serif;` one would assume, that the font on a `button` is in serif. Sadly this is not the case, because `_normalize.scss` explicitly sets `button, input, optgroup, select, textarea` to it's default-value which is `sans-serif`. As foundation-sites doesn't reset these Elements, this results in `sans-serif`-Buttons.

#### How to reproduce this bug:
Set `$body-font-family: 'Times New Roman', serif;`

```html
<!-- Anchors (links) -->
<a href="about.html" class="button">Learn More</a>
<a href="#features" class="button">View All Features</a>

<!-- Buttons (actions) -->
<button type="button" class="success button">Save</button>
<button type="button" class="alert button">Delete</button>
```
Results in:
![a-vs-button](https://cloud.githubusercontent.com/assets/4437946/22056985/13a11e04-dd63-11e6-8db3-8916f9eaf8fa.png)
But the Save- and Delete-Button also shoudl be in Times New Roman/serif.

#### Fix/Workaround:
You can workaround this by setting `$base-font-family` which is used by _normalize.scss to `$body-font-family;` after including your `_settings.scss` and before `foundation.scss`.

Maybe that should be the default-behaviour or maybe Foundation should reset the elements to it's desired state, if they are overwritten by `_normalize.scss`. Otherwise it could be a pitfall for some people.

**Comment by sashabeep** [comment]
use the
```
font-family: inherit;
```
for button, input, optgroup, select, textarea at start
