### ISSUE TITLE
Motion UI: Hamburger Menu(Open & Close)

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9675]
Ref: #9590 ( Updated List )
Example Codepen => http://codepen.io/edoardo-bluframe/pen/dMZaMa

I Think this specific feature that should be put on **focus** ( **for motion ui** ) so posting this as a separate ticket. 

This **Feature** is very useful for mobile devices and is used in most modern websites and will be great if zurb can add this in motion ui !
**#MicroAnimations**

**Comment by IamManchanda** [comment]
https://jonsuh.com/hamburgers/

**Comment by JeremyEnglert** [comment]
Lets talk about this for V7.
