### ISSUE TITLE
Tried to initialize ... - disable on production

### ISSUE THREAD

**Issue by drozdzynski** [zurb/foundation-sites#9676]
Hello,

> Tried to initialize reveal on an element that already has a Foundation plugin.

This should be able to disable in production mode.
For example:
```
var webpack = require('webpack')
module.exports = {
  // ...
  plugins: [
    // ...
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    })
  ]
}
```

**Comment by ncoden** [comment]
Hi @drozdzynski,

I do not understand. Are you replying to an other issue ?

**Comment by DaSchTour** [comment]
Even more webpack crap I have to fix with overrides in JSPM 🙈

**Comment by kball** [comment]
These warnings are implemented using `console.warn`; if you wish to disable console warn in production, there are ample mechanisms for doing so (see http://stackoverflow.com/questions/1215392/how-to-quickly-and-conveniently-disable-all-console-log-statements-in-my-code)

Going to close this as wontfix, as at this time I'm pretty confident we should still be warning on usage that can result in unexpected/broken behavior, but if anyone wants to make a proposal for a more pluggable/customizable warning/error system within Foundation we might be interested.
