### ISSUE TITLE
Notifications ( Static/Dynamic) in Foundation sites

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9682]
Example => http://foundation.zurb.com/apps/docs/#!/notification

As foundation apps is [deprecated](https://github.com/zurb/foundation-apps#deprecation-notice) and zurb has plans to be [accesible in every JS Frameworks](https://github.com/zurb/foundation-sites/wiki/Project-Roadmap#70-november-2017) within foundation sites . 

I hereby Propose **notifications** to foundation sites project!

**Comment by IamManchanda** [comment]
@kball : thoughts ?
yes or no ?

**Comment by Vuurvlieg** [comment]
I think this is very nice to have!

**Comment by IamManchanda** [comment]
thanks @Vuurvlieg but this isn't kinda new feature request .... foundation had that already .... just not in this repo .....

**Comment by IamManchanda** [comment]
@brettsmason ..... is this under radar? ....  I mean no labels ?

**Comment by brettsmason** [comment]
@IamManchanda Yes I'm sure its planned. The plan I think is to port missing parts over from Apps, though I guess this probably wont happen until 7.0 (though I'm not sure).

**Comment by IamManchanda** [comment]
i think for this, the label should be **vintage feature request** ..... lol :smile:

**Comment by JeremyEnglert** [comment]
Lets talk about this for V7.
