### ISSUE TITLE
RTL Issue in topbar component

### ISSUE THREAD

**Issue by PayamTH** [zurb/foundation-sites#9684]
I have a problem in creating "RTL" "Top Bar" component. I set lang="fa" dir="rtl" in main HTML file, here is my html code:

```html
  <div class="top-bar">
		<div class="top-bar-title">
			<span data-responsive-toggle="responsive-menu" data-hide-for="small">
				<button class="menu-icon dark" type="button" data-toggle></button>
			</span>
			<strong>عنوان سایت</strong>
		</div>
		<div class="top-bar-left">
			<ul class="menu">
				<li><input type="search" placeholder="جستجو"></li>
				<li><button type="button" class="button">Search</button></li>
			</ul>
		</div>
		<div id="responsive-menu">
			<div class="top-bar-right">
				<ul class="dropdown menu" data-dropdown-menu>
					<li><a href="#">یک</a>
						<ul class="menu vertical">
							<li><a href="#">یک</a></li>
							<li><a href="#">دو</a></li>
							<li><a href="#">سه</a></li>
						</ul></li>
					<li><a href="#">دو</a></li>
					<li><a href="#">سه</a></li>
				</ul>
			</div>
		</div>
	</div>
```
and here is output:

![untitled2](https://cloud.githubusercontent.com/assets/25241932/22160027/e1356e50-df58-11e6-9e91-fa40552875f3.jpg)

What is mising? site title is in left side! Is this a bug?

**Comment by ncoden** [comment]
Hi @PayamTH, welcome on GitHub ;)

Foundation is not watching `dir="rtl"` but uses its own Sass setting: `$global-text-direction`.
See: http://foundation.zurb.com/sites/docs/global.html

Also, please use ````` to create multi-line code in Markdown. See https://guides.github.com/features/mastering-markdown/

**Comment by PayamTH** [comment]
Hi @ncoden, Tnx for your reply
