### ISSUE TITLE
Orbit Instructions unclear - change of docs, or default value for `data-use-m-u-i ` ?

### ISSUE THREAD

**Issue by jordanbrauer** [zurb/foundation-sites#9686]
The first example of Orbit on it's page is a little confusing because it provides broken behaviour of Orbit. What do you guys think of changing the default value for `data-use-m-u-i`? Alternatively, changing the docs first example to include the `data-use-m-u-i="false"` options of the Orbit div, like so,

```
<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit data-use-m-u-i="false">
 <!-- ... -->
</div>
```

It does have a warning later on down the page saying that you require motion-u-i to use it's default behaviour successfully, so I don't know if what I'm proposing is necessary. Thoughts?

**Comment by IamManchanda** [comment]
Sorry but unneccessary
and thing you are requesting is already there within the page  
http://foundation.zurb.com/sites/docs/orbit.html#disabling-animation

**Comment by IamManchanda** [comment]
cc /@kball

**Comment by jordanbrauer** [comment]
@IamManchanda Then how do you propose it is made clearer from the getgo that Motion UI is needed for Orbit to work by default?

**Comment by IamManchanda** [comment]
@jordanbrauer Are you talking about smooth slide in the first example ?

**Comment by jordanbrauer** [comment]
@IamManchanda Yes.

**Comment by IamManchanda** [comment]
Hmmmn.... although i am bit confused but feels like your point is logical !!

**Comment by DanielRuf** [comment]
Not sure what you mean. The first and the other examples do not look broken and there is this note at the top:

> Please note that apart from Javascript, Motion UI is a dependency for Orbit to work properly. If in case, you don't want any animations within your Carousel, you can always disable the animation.

**Comment by DanielRuf** [comment]
@ncoden is this obsolete as we have the notice at the very top now (basics)?

**Comment by ncoden** [comment]
@DanielRuf Looks good for closing. Thank you.
