### ISSUE TITLE
Dropdown Menu: Should .opens-left and .opens-right have to be added manually?

### ISSUE THREAD

**Issue by JeremyEnglert** [zurb/foundation-sites#9688]
If you have a dropdown menu, the class `.opens-left` or `.opens-right` will be added, this element decides which way your dropdown menu sub-items will open. 

However, this class is added via JavaScript with the following logic: If the menu is floating right, add the `.opens-left` class, otherwise add the `.opens-right` class.

Should this element have to be added manually? The drop-down menu is often used inside of `.top-bar-right`, which floats right. This creates the following:

![a5jis6g9ma](https://cloud.githubusercontent.com/assets/6110968/22179471/4be5eb9e-e012-11e6-9f6c-0d9b7adaee92.gif)

As seen in this example, there is plenty of room for the items to open on the right. However, since this menu was built using the topbar, it automatically gets the `.opens-left` class.

Are we assuming since the menu is floating right, it is going to collide with the edge of the screen? Don't we have edge detection to prevent that?

**Comment by wgstjf** [comment]
@JeremyEnglert - same issue at my end.  Did you get any further with this?

Cheers,

Will

**Comment by samuelmc** [comment]
The .opens-left and .opens-right classes are set by the dropdown menu plugin in js. It's the same issue as #9042
With pull request #9950 you'll be able to use data-alignment="left" to force the alignment left.

**Comment by wgstjf** [comment]
Thanks for the quick response on that.  Will take a look.

Cheers,

Will

**Comment by kball** [comment]
I believe this was fixed with #9950
