### ISSUE TITLE
Questions: Hollow Buttons ?

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9689]
Why are Hollow buttons not like the usual ones?

for eg.
- https://codepen.io/ncerminara/pen/qdeVGP/
- https://laracasts.com/ homepage 

Any specific reason ?

**Comment by Deckluhm** [comment]
Why do you mean by "not like the usual ones"? The hover behavior?

**Comment by IamManchanda** [comment]
Yup the hover behaviour

**Comment by Deckluhm** [comment]
There are different behaviors for hollow buttons (the one in your examples is just one of them) and I don't think there is one which is better than the others.

This can be easily customized to meet your needs if you want to reproduce your examples' behavior.

**Comment by IamManchanda** [comment]
but there should be some custom sass variables for that ...... to customize these type of things within the framework

**Comment by rafibomb** [comment]
We will close this since there is a PR for this #9740
