### ISSUE TITLE
Basic F6 Sass Template compiles newly added .scss files in the /scss folder instead of /css

### ISSUE THREAD

**Issue by yhyjy** [zurb/foundation-sites#9690]
#### How to reproduce this bug:
Docs:
http://foundation.zurb.com/sites/docs/starter-projects.html

1. Step one : install basic template using:
 foundation new --framework sites --template basic
2. Step two run gulp 
3. Step three make a new .scss file in /scss

#### What should happen:
 It should compile my newly added .scss file into the /css folder like the rest of the @imports in app.scss

#### What happened instead: 
Instantly creates two .css files in the /scss folder giving gulp this error:
  in scss/app.scss
Error: It's not clear which file to import for '@import "homepage"'.
       Candidates:
         newfile.scss
         newfile.css
[/scss folder after](https://i.gyazo.com/5269c037ccc0fe94be4bf555ca1d8354.png)

One of the first times setting up gulp with F6 for a project so I dont know how to fix this myself.
If more code or info is needed feel free to ask
Thanks,

**Comment by FynnZW** [comment]
Can you please paste the contents of your `gulpfile.js` in here?

And is there maybe any other program watching that folder, like Codekit or Prepros?

**Comment by yhyjy** [comment]
Haven't changed anything in the gulpfile

`var gulp = require('gulp');
var $    = require('gulp-load-plugins')();

var sassPaths = [
  'bower_components/normalize.scss/sass',
  'bower_components/foundation-sites/scss',
  'bower_components/motion-ui/src'
];

gulp.task('sass', function() {
  return gulp.src('scss/app.scss')
    .pipe($.sass({
      includePaths: sassPaths,
      outputStyle: 'compressed' // if css compressed **file size**
    })
      .on('error', $.sass.logError))
    .pipe($.autoprefixer({
      browsers: ['last 2 versions', 'ie >= 9']
    }))
    .pipe(gulp.dest('css'));
});

gulp.task('default', ['sass'], function() {
  gulp.watch(['scss/**/*.scss'], ['sass']);
});
`

**Comment by FynnZW** [comment]
`@import homepage`  will look for a file called `homepage.scss` (or `homepage.css`) in the same folder your app.scss or any of the `sassPaths`. 
Yours is called `newfile.scss`, try changing your import to `@import newfile`, but delete the newfile.*css* before running gulp again.

But still, something must have compiled `newfile.css`in the first place and even created a sourcemap. Are you maybe using Adobe Dreamweaver? It autocompiles any SCSS it finds by default and places the CSS in the same directory.

**Comment by yhyjy** [comment]
Ah sorry that still there from my first import and testing, I created the newfile so it was more clear which files were newly added. 

I found the issue, I am using Brackets and I found out that there was still a compile extension running. So it was a mistake on my end.

Thank you very much for helping me find the problem!
