### ISSUE TITLE
[Dropdown Menu] SubMenu links can not be selected on touch devices.

### ISSUE THREAD

**Issue by devanflaherty** [zurb/foundation-sites#9691]
Using Foundation 6.3 on this site.

http://crossroadschurch.net

When on touch devices, from iPhone, iPad to HP touch screen lap tops, I can activate the drop-down but not select the children links.

**Comment by IllusionPerdu** [comment]
duplicate with this repport #9652 ;)

**Comment by IamManchanda** [comment]
Aprox. duplicate of #7143

**Comment by IllusionPerdu** [comment]
in the develop branch this was fixed...

**Comment by IamManchanda** [comment]
If there is a suggested fix .... create a PR .... you dont need your code to be 100% perfect

**Comment by IllusionPerdu** [comment]
This patch is already in the development branch, I just posted the edit part to be able to fix itself temporarily until the next release comes out;)

**Comment by IamManchanda** [comment]
Seems like its resolved. **Please close issue** if its resolved.

**Comment by kball** [comment]
Fixed in https://github.com/zurb/foundation-sites/pull/9546

This will be in 6.3.1, is targeted to be finalized for QA next week, released about a week after.

**Comment by IamManchanda** [comment]
YAII
