### ISSUE TITLE
Foundation 6.3 cheat sheet

### ISSUE THREAD

**Issue by sashabeep** [zurb/foundation-sites#9692]
Nobody reads/answer to forums
So question 2 all - default DOCS section is kinda unuseful and doesn't contain, for example, all of the classes list. Maybe somebody already did the cheatsheet?

**Comment by IamManchanda** [comment]
For components, we have http://foundation.zurb.com/sites/docs/kitchen-sink.html

**Comment by IamManchanda** [comment]
@kball ..... what's your thoughts ...... because i am pretty sure we can't provide such a cheat sheet?

**Comment by kball** [comment]
We're working on a docs iteration, but I think the kitchen sink is as close as we're likely to get to a "cheat sheet" within them, unless someone has clear in mind what it would look like.
