### ISSUE TITLE
Questions: Why modal and not lightbox for images

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9693]
Just wanna know is there any specific reason/convention that responsive frameworks ( foundation, bootstrap, semantic  ui ) ..... does not include lightbox. I guess image lightbox are more popular and more in demand than modal's ? Then why is it so?

Example => https://sachinchoolur.github.io/lightGallery/demos/

**Comment by IamManchanda** [comment]
And why not having both ?

**Comment by DaSchTour** [comment]
@IamManchanda the example you showed is just a specific incarnation of modals. Adding some styles and function and you will get a lightbox. And I don't think that the demand for lightbox in this extreme feature rich way is that high. I'm sure that there are a lot of pages that don't have such photos to display in a lightbox but a lot of dialogs than need a modal.

**Comment by IamManchanda** [comment]
Yes exactly and i know that but ,
For eg. look at this => http://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_js_lightbox

We have modals, carousel, motion ui .... These 3 blocks can perfectly help us make a **lightbox gallery**??

--------------------------------------------------------------------------------------------------------------------------

But i dont know whether this should be in the core or as a plugin !

**Comment by IamManchanda** [comment]
@kball : Looking for your thoughts, because if this can't be added in the core... would like to close it!

**Comment by kball** [comment]
I concur with @DaSchTour - lightbox is a set of graphical flare built on top of the foundational component of a reveal modal.

I would *love* to see a lightbox "building block" (on the horizon in the next 3months is a revamping of the concept of building blocks to make the site (http://zurb.com/building-blocks) much more navigable, to make it easy to drop them into a project and pick up consistent styles, and to have a more community-submission oriented approach.

however, as a core piece of Foundation I don't think this is a go.
