### ISSUE TITLE
[Off-canvas] toggle not working after window resize with reveal-for-large

### ISSUE THREAD

**Issue by Zausenec** [zurb/foundation-sites#9695]
Load on large or medium size, then resize to small
or
load on small, then resize to medium

```
<div id="offCanvas" class="off-canvas position-left reveal-for-large" data-off-canvas></div>
<div class="off-canvas-content" data-off-canvas-content>
    <button class="button" data-toggle="offCanvas">Toggle</button>
</div>
```

**Comment by brettsmason** [comment]
@Zausenec Thanks for reporting this issue. I have setup [a CodePen](http://codepen.io/brettsmason/pen/rjzQoQ) as you described and can confirm the bug.

@kball Any idea why this might be happening?

**Comment by kball** [comment]
Not sure, but I can dig into it
