### ISSUE TITLE
Nested .row.align-center not centering in flexgrid

### ISSUE THREAD

**Issue by dlewand691** [zurb/foundation-sites#9698]
How to reproduce this bug:

1. create a standard nested row/colum:
```
.row
   .column
      .row.align-center
         .column
```
2. See result
3. Fix result

What should happen:
Nested column should center

What happened instead:
Column has margins forcing it to the left instead

**Comment by IamManchanda** [comment]
Please provide codepen/jsbin ?

**Comment by IamManchanda** [comment]
@dlewand691 As there wasn't a reply ... i made codepen myself .... next time plz provide codepen

So, Here is my codepen => http://codepen.io/IamManchanda/pen/ZLapXm

It works fine, Please close issue if its resolved!

**Comment by kball** [comment]
Closing based on the above conversation; please reopen if you have an example reproducing the bug.

**Comment by IamManchanda** [comment]
**YAII**
