### ISSUE TITLE
[Feature] Add setting for button hollow width

### ISSUE THREAD

**Issue by christianseel** [zurb/foundation-sites#9709]
#### Current situation
Outline buttons with the `hollow` class have a fixed border width of `1px`:
https://github.com/zurb/foundation-sites/blob/develop/scss/components/_button.scss#L151

#### What should happen:
This should be customizable with a variable in the settings. I'd recommend to introduce a `$button-hollow-width` setting.

**Comment by IamManchanda** [comment]
I personally like it very much and it should be there .... have created a PR for the same #9717 
But will let @kball and others decide on it

Thanks a lot @christianseel for the feature. :+1:

**Comment by IamManchanda** [comment]
@christianseel 
**FTFY** at #9717

**Comment by christianseel** [comment]
🙌🏻👌🏻
