### ISSUE TITLE
[Off-Canvas] Add separate transition variables for off-canvas reveal on larger screens

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#9713]
Due to the off and on nature of breakpoint based grids, there should be separate transitions for showing and hiding an off-canvas based on screen size. The margins on the content are modified instantaneously, leaving the transitioning off-canvas playing catch up.

#### How to reproduce this bug:

1. Load http://codepen.io/christianmagill/pen/OWOjbW
2. Size browser small
3. Increase width until it reaches large.

You will see the white space created by the margin before the off-canvas transitions into place. In most instances I'd rather have no transitions for these breakpoint based shows and hides.

**Comment by brettsmason** [comment]
@christianmagill Thanks for raising this issue. Do you see any use cases where you might want to keep the transition? My initial reaction is we could remove it as I cant see it being needed.

**Comment by christianmagill** [comment]
I'm fine with removing it, as long as it doesn't effect transitions when opening and closing regularly
