### ISSUE TITLE
Feature Request: JS Utility for flexbox-based image height matching

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation-sites#9715]
Hello,

I just came across an interesting [blog post](https://kartikprabhu.com/articles/equal-height-images-flexbox) that discusses how to match the heights of images with flexbox.

Here's the trick:
* Image-1 has an aspect-ratio of 1.00.
* Image-2 has an aspect-ratio of 1.50.
* Wrap image-1 in a container with this css: `flex: 1 0 0`.
* Wrap image-2 in a container with this css: `flex: 1.5 0 0`.
* Wrap it all up in a flex container.

So, one could do the aforementioned by hand. But a JS utility could be used on a set of images of unspecified count without having to manually calculate the correct `flex-grow` values for each.

I get the sense that this parallels @rafibomb's masonry idea.

This is not a fully formed idea, but I thought I'd float it.

**Comment by IamManchanda** [comment]
Nice article and thanks for sharing.

But as per me, i dont think this should be added to core. But maybe that's just me.
Poke @kball for deciding on it!

**Comment by kball** [comment]
So there's 2 pieces here... 1 is the css if you already know the aspect ratios... cool, but not really helpful for the framework. the second is a JS that checks aspect ratios and calculates from there...
This is might be an interesting iteration on equalizer... however, if you're already using JS to calculate, not sure what the advantage of this approach would be over equalizer as it stands. Did you have one in mind?

**Comment by paxperscientiam** [comment]
Hey @kball 

> This is might be an interesting iteration on equalizer...

Off the top of my head, I'm not sure to what degree equalizer leverages flexbox; but, this sounds reasonable.


__Another idea...__
What if this were part of the development pipeline? That is, what about generating these `flex` values by retrieving image dimensions and computing ratios with javascript, and -- somehow -- feeding that back into the pipeline as the basis for said values?

**Comment by JeremyEnglert** [comment]
Lets talk about this for V7.
