### ISSUE TITLE
[breadcrumbs] make color for slash variable

### ISSUE THREAD

**Issue by stefan2** [zurb/foundation-sites#9721]
The color for the slash in [breadcrumbs is fixed to $medium-gray (line 70)](https://github.com/zurb/foundation-sites/blob/develop/scss/components/_breadcrumbs.scss#L70). Not really perfect for a breadcrumb on $medium-gray background. :-)

Slash color should be a variable?

**Comment by IamManchanda** [comment]
:+1: This is logical !

**Comment by IamManchanda** [comment]
FTFY #9722 .... Thanks again!

**Comment by stefan2** [comment]
Lightspeed. Thank YOU!

**Comment by IamManchanda** [comment]
@stefan2 
Speed of light =299 792 458 m / s
I am quite sure ... I am not that fast ..... **YAII**
