### ISSUE TITLE
Foundation Tabs - Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by sanderha** [zurb/foundation-sites#9725]
#### How to reproduce this bug:

1. 

I added foundation tabs like so:
```
<ul class="tabs" data-tabs id="dealer-tabs"> </ul> 
```
and
``` 
<div class="tabs-content" data-tabs-content="dealer-tabs"></div>
```
with of course the correct markup inside of these containers.

2. 

Included the foundation tabs mixin:
``` @include foundation-tabs; ```
and the JS
```
'node_modules/foundation-sites/dist/js/plugins/foundation.core.js',
'node_modules/foundation-sites/dist/js/plugins/foundation.util.mediaQuery.js',
'node_modules/foundation-sites/dist/js/plugins/foundation.util.triggers.js',
'node_modules/foundation-sites/dist/js/plugins/foundation.util.timerAndImageLoader.js', 
'node_modules/foundation-sites/dist/js/plugins/foundation.tabs.js',
```

#### What should happen:
No errors in console

#### What happened instead:
**the tabs work** as per usual however i get the following error in console:
```
TypeError: Cannot read property 'register' of undefined
    at new Tabs (compressed.js:1231)
    at HTMLUListElement.<anonymous> (compressed.js:193)
    at Function.each (jquery-2.2.4.min.js:2)
    at n.fn.init.each (jquery-2.2.4.min.js:2)
    at String.<anonymous> (compressed.js:175)
    at Function.each (jquery-2.2.4.min.js:2)
    at Object.reflow (compressed.js:167)
    at n.fn.init.foundation (compressed.js:275)
    at compressed.js:1912
```

I am using jquery 2.2.4 and Foundation 6.3.0 .

**Comment by Deckluhm** [comment]
Can you provide a CodePen reproducing the error?

You can fork [this one](https://codepen.io/ncoden/pen/oYVpMe) (which comes with Foundation 6.3 assets).

**Comment by IamManchanda** [comment]
Hmmmnnn,,,, please follow @Deckluhm instructions and also,

> ```html
> 'node_modules/foundation-sites/dist/js/plugins/foundation.core.js',
> 'node_modules/foundation-sites/dist/js/plugins/foundation.util.mediaQuery.js',
> 'node_modules/foundation-sites/dist/js/plugins/foundation.util.triggers.js',
> 'node_modules/foundation-sites/dist/js/plugins/foundation.util.timerAndImageLoader.js', 
> 'node_modules/foundation-sites/dist/js/plugins/foundation.tabs.js',
> ```

If in case if you want to include only these above js in test case ...... 
You can include these files below within the codepen/jsfiddle settings (and of course remove foundation.min.js) if you wanna include these files only

- https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/plugins/foundation.core.min.js
- https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/plugins/foundation.util.mediaQuery.min.js
- https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/plugins/foundation.util.triggers.min.js
- https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/plugins/foundation.util.timerAndImageLoader.min.js
- https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/plugins/foundation.tabs.min.js

**Comment by sanderha** [comment]
Hey guys I just made a codepan using the HTML from the docs and including the JS I also include:

https://codepen.io/sanderha/pen/BpJYWr?editors=1011#0

I do get an ``` [object Error] ``` error in the console, however there does not seem to be more information.

**Comment by Deckluhm** [comment]
You just have a missing dependency: `foundation.util.keyboard.js`

At the bottom of each JS component you have a list of dependencies (here are tabs ones).

**Comment by sanderha** [comment]
Ah damnit. I see. Thanks. 

I'll go stand in the corner of shame now.

**Comment by IamManchanda** [comment]
YAII .... There is no such corner buddy !

**Comment by kball** [comment]
Dependencies are going to be much easier come 6.4 (yay true dependency management!) see https://github.com/zurb/foundation-sites/issues/9438
