### ISSUE TITLE
Javascript Error handling for foundation

### ISSUE THREAD

**Issue by stanogurnik** [zurb/foundation-sites#9726]
There should be way to handle Javascript errors in foundation. There are multiple places in code which use something like this:

`
try {
    <js_code>
} catch (err) {
    console.error(err);
}
`

Which make impossible to report javascript errors in tools like Bugsnag, not just from foundation itself but many times other code not directly related to foundation.

* there is hacky way to overload console.error but it is somehow risky, and some errors are reported twice - once in window.onerror event and on console.error event.

**Comment by kball** [comment]
This is a great point, I 100% agree.

Do you have any examples of libraries that do this well you can point to?

**Comment by kball** [comment]
(cc @zurb/yetinauts)

**Comment by IamManchanda** [comment]
@stanogurnik @kball 
One article to look into before starting on it!
https://www.sitepoint.com/proper-error-handling-javascript/

**Comment by stanogurnik** [comment]
Yea, you don't need any library for that, simple callback would suffice. Something like 
`Foundation.registerDefaultErrorHandler(function(level, message, err) { doYourStuff(); // throw err; if you want propagate Error etc. });` would be great.

**Comment by colin-marshall** [comment]
Would be good to get this in for 6.4

**Comment by paxperscientiam** [comment]
As an aside, @stanogurnik, maybe we should be thinking about replacing callbacks with promises where applicable and as needed.

**Comment by stanogurnik** [comment]
@paxperscientiam there's no need to use promise there. Promises shine in async code and this is not that case. Only benefit would be common understanding of API but still callback is simpler/better/faster solution.

**Comment by JeremyEnglert** [comment]
Lets get this implemented in V7.
