### ISSUE TITLE
[Reveal] btmOffsetPct being ignored

### ISSUE THREAD

**Issue by diniscorreia** [zurb/foundation-sites#9727]
No matter what value I use in `btmOffsetPct`, the reveal element always stays in the same position (slightly closer to the top of the window).

Looking at the code for the plugin, `btmOffsetPct` doesn't seem to be used anywhere, except when setting the default value.

**Comment by IamManchanda** [comment]
Please provide Codepen ??

**Comment by diniscorreia** [comment]
@IamManchanda oops, sorry. Here you go: http://codepen.io/diniscorreia/pen/KaZeeY

**Comment by IamManchanda** [comment]
Tested it out myself => http://codepen.io/IamManchanda/pen/YNYjKe
Yup i can confirm this is a ~~bug~~ Missing `data-options` setting !!

@kball Kevin sir can you look into it !

**Comment by DanielRuf** [comment]
It is still not used in the component but defined as variable.

**Comment by DanielRuf** [comment]
I guess it was removed in https://github.com/zurb/foundation-sites/commit/e9e3bb9d33ebd7808c47ffcd69a94c867483047f so it might be safe to completely delete the unused variable / option.

**Comment by DanielRuf** [comment]
Closing as the PR is merged.
