### ISSUE TITLE
Separate Prototyping Functionality

### ISSUE THREAD

**Issue by natewiebe13** [zurb/foundation-sites#9736]
Goals:
- Add helper classes for prototyping
- Disabled by default as to not add extra weight to the framework by default, should be able to include with a simple `@include`
- Held in a separate folder (ex: `scss/prototyping/..`) in order to have a clear separation

Thoughts? @kball @rafibomb @ncoden @brettsmason @andycochran @tdhartwick @jnemeth

**Comment by IamManchanda** [comment]
I Dont want my thoughts ? @natewiebe13

**Comment by brettsmason** [comment]
I really like this idea! There's probably a lot of cases where users have no use for the prototype classes, so maybe shouldn't part of the core by default.

**Comment by natewiebe13** [comment]
@IamManchanda yes, forgot to add your name, but everyone is always open to voice their opinion.

**Comment by IamManchanda** [comment]
I really love the idea infact .... that's what i was wanting from day one i came here.....

**Comment by IamManchanda** [comment]
**Some Utilities to consider within this ( ofcourse non-default )**

1. Flex
2. Spacing 
3. Color 
4. Display
5. Text  
6. Overlay  
7. Sizing 
8. Position 
9. Typography ( alignment, transform, font weight etc )

**Comment by kball** [comment]
@natewiebe13 I think this is a very good direction. Will be discussing with the Yetinauts (core team) in a call this Thurs, but if you want to continue refining what might be included here (and what existing things should get moved into this category) that would be excellent

**Comment by IamManchanda** [comment]
@kball Text alignment, flex helpers should be moved .... and I am unsure about visibility classes , float classes and classes like `align-center` because they are very important for responsive web design.

**Comment by IamManchanda** [comment]
**Warn** - I will be doing the PR if this gets approved!

**Comment by IamManchanda** [comment]
Nate... Cheers man... Done! 
Thanks for the help.
