### ISSUE TITLE
[Feature Request] Add additional row padding at mobile/tablet breakpoint.

### ISSUE THREAD

**Issue by danielnr87** [zurb/foundation-sites#9737]
I've always had to add a class with additional padding on the top level row, as I find that the default column gutter padding is too small when the content gets to the edge of the screen. It looks very small on mobile.

Similar effect to this
```@include breakpoint(medium down) {
  .row {
    padding-left:rem-calc(20);
    padding-right:rem-calc(20);
    .row {
      padding-left:0;
      padding-right:0;
      .row {
        padding-left:0;
        padding-right:0;
        .row {
          padding-left:0;
          padding-right:0;
        }
      }
    }
  }
}
```
But much less nasty.

It would be nice to have a additional setting in _settings.scss to add a specified amount of padding to the top level row, rather than column padding, as to not change the standard gutter width.

Thanks

**Comment by IamManchanda** [comment]
@brettsmason thoughts ?

**Comment by brettsmason** [comment]
I'm not sure I see the need for it to be honest. I would of thought you would be better off creating a new class for yourself, something like:

```
.row-padded {
  @include breakpoint(medium down) {
    padding-left: rem-calc(20);
    padding-right: rem-calc(20);
  }
}
```
Then just add that to your top level `.row` (along with the existing `.row` class).
I can't see a need for it in core, but my opinion could be wrong 😄

**Comment by IamManchanda** [comment]
@brettsmason I think the same brett ....  

I am sorry @danielnr87 but feel like **PASS** will be better of for the time being as similar to brett ...  i also dont feel like it to be a part in the core .... a bit of over engineering for the framework ..... but **maybe that's just me** !

@kball for final decision on this!

**Comment by danielnr87** [comment]
Ahh shucks. :) Thanks for your responses.

My only reason for suggesting it in core is it is easy to miss the class on a big site, and its not obvious at desktop resolution to see if it is there.
I will just check more thoroughly on mobile in the future!

Thanks
