### ISSUE TITLE
Dropdown pane align on mobile 

### ISSUE THREAD

**Issue by palaniichukdmytro** [zurb/foundation-sites#9741]
#### How to prevent auto detecting align on mobile with dropdown pane.

I use dropdown-pane.bottom - it's work corectly only on desktop,on mobile the it gets the .left class. How to prevent it. Which data attr. ca 

```
button.small.button.secondary.arrow(type="button"  data-toggle="dropdown-btn-1") dropdown pane

.dropdown-pane.bottom#dropdown-btn-1(data-dropdown data-auto-focus="true" data-v-offset="12" data-position-class='bottom')
      ul.no-bullet.text-left
        li
          a(href="") one
        li
          a(href="") two
        li
          a(href="") three
```

[https://codepen.io/palaniichukdmytro/pen/jyzGLz](url)

**Comment by IamManchanda** [comment]
cc / @brettsmason !

**Comment by brettsmason** [comment]
@kball I'm not sure if this is the same issue I pointed out in QA or not? If not I'll create a new issue.

**Comment by tw42** [comment]
This bug appears when dropdown trigger is close to the right edge of the window. In this case dropdown pane gets .left class and positions incorrectly.

http://codepen.io/tw42/pen/dNEvOJ

**Comment by kball** [comment]
For 6.4 we just merged explicit positioning in dropdowns, which should make it straightforward to resolve this. See: https://github.com/zurb/foundation-sites/pull/10053
