### ISSUE TITLE
[Sticky] Remove sticky on "small" won't work.

### ISSUE THREAD

**Issue by guci0** [zurb/foundation-sites#9748]
Works well on LARGE, but breaks on small and medium with flexbox view changes.

From columns ex. 50% 50%, to 100% (one row, each for example). 

```
<aside id="aside" data-sticky-container>

   <ul data-sticky data-top-anchor="article:top" data-btm-anchor="article:bottom">
      <li>...</li>
   </ul>

</aside>

<article id="article">

    <p>...</p>

</article>
```

Version **6.3.0**

Data option "_stickyOn_" and changes – do not change the behaviour of element.

---
![zrzut ekranu 2017-02-04 o 16 57 27](https://cloud.githubusercontent.com/assets/5683433/22619712/1decbe86-eafb-11e6-917d-a7270b7bf447.png)

**Comment by IamManchanda** [comment]
@guci0 Please give a test case (codepen/jsfiddle/jsbin) .... not screenshots

For your help, 
You can fork these below codepen's for the same 

1. Without flexbox => http://codepen.io/IamManchanda/pen/vgemXR
2. With flexbox => http://codepen.io/IamManchanda/pen/xgXdRq

**Comment by guci0** [comment]
For example, on medium: http://linki.dtl.pl/608f

**Comment by IamManchanda** [comment]
Yup you are right! This really breaks specially on tablets ! 

![screenshot from 2017-02-05 13-01-53](https://cloud.githubusercontent.com/assets/4970624/22624500/719c7384-eba3-11e6-9aab-5c70673baa7b.png)

@guci0 **Although i dont think i can confirm this as a bug unless you provide a test case so please provide**

**Comment by kball** [comment]
@colin-marshall

**Comment by colin-marshall** [comment]
@guci0 can you redo your example with the attribute `data-sticky-on="large"` please?

**Comment by huytrq** [comment]
Same. 
I added the attribute `data-sticky-on="large"`. It works well on the desktop but not correct on small and medium.

**Comment by DanielRuf** [comment]
Closing as we did not get a reproducible testcase (codepen).
