### ISSUE TITLE
Foundation 6.3.0 - MediaQuery issue

### ISSUE THREAD

**Issue by CHEWX** [zurb/foundation-sites#9751]
Getting an error with the new Foundation 6.3.0.

You could just include one file, do you need a dependancy now?

`Foundation.MediaQuery._init();` is the issue, as `Foundation.MediaQuery` object doesn't exist.

#### How to reproduce this bug:

1. Include `<script src="bower_components/foundation-sites/dist/js/plugins/foundation.core.js"></script>`
2. Run `jQuery(document).foundation()`

#### What should happen:

No error.

#### What happened instead:

`foundation.core.js:274 Uncaught TypeError: Cannot read property '_init' of undefined`

**Comment by CHEWX** [comment]
After 2 minutes of digging, it looks like `foundation.core.js` now depends on `foundation.util.mediaQuery.js` — Not sure if it used to do this in 6.2.3 ?

**Comment by IamManchanda** [comment]
@CHEWX => http://foundation.zurb.com/sites/docs/javascript.html#file-structure

If you're only using certain plugins, know that they all require `foundation.core.js` and `foundation.util.mediaQuery.js` to be loaded first. Some plugins also require specific utility libraries that ship with Foundation—refer to a plugin's documentation to find out which plugins require what, and see the JavaScript Utilities page for more information.

**Comment by IamManchanda** [comment]
Please close this if your issue is resolved!

**Comment by CHEWX** [comment]
Ah, thanks @IamManchanda - maybe I subconsciously included it on my other projects and not for this one.
