### ISSUE TITLE
Topic for seo of this repo

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9754]
I think we should create topics like these??

![topics-seo](https://cloud.githubusercontent.com/assets/4970624/22663342/3c084fce-ecd2-11e6-8035-74288621bd29.png)

**Comment by colin-marshall** [comment]
@IamManchanda this sounds like a good idea, but low priority for us at the moment. Should we close this out for now and add the Revisit for F7 tag?

**Comment by IamManchanda** [comment]
sure @colin-marshall
