### ISSUE TITLE
dropdown-container mixin overflows document

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#9756]
I am using Foundation 6.0.3 but the code hasn't changed so - the **dropdown-container** mixin that is used for **.dropdown-pane** has an issue if it is positioned to the far right of the screen and opens to the left(that is my config but most likely the issue is for other combos as well). When the page loads it will cause horizontal scrollbar to appear because the width of the pane content is not properly hidden, only _visually_ and the parent has absolute position so it will overflow the screen.

I tried to play with _display_ setting but I have ended up with setting the position to fixed and for open pane to absolute, which is currently default setting.

```
.dropdown-pane {
  position: fixed;
  &.is-open {
    position: absolute;
  }
}
```

**Comment by IamManchanda** [comment]
@ivanjaros Codepen please!!

**Comment by colin-marshall** [comment]
@ivanjaros please provide a reproducible test case for us. If we don't hear from you in 30 days, we will close out the issue. Feel free to reopen if we close it before you get around to it. Thanks!
