### ISSUE TITLE
Working tabs with Mixins

### ISSUE THREAD

**Issue by CGTS** [zurb/foundation-sites#9758]
I copied the the markup from the tab example here http://foundation.zurb.com/sites/docs/tabs.html and tested it; and everything worked. I then changed the classes in my scss file and used the sass mixins; all the styles checked out. Everything looked like it should but the tab functionality was gone.

Do I need the `tab-title` and `tab-panel` classes for this to work? or do I need to use `var elem = new Foundation.Tabs(element, options);` to create a new tab instance with the plugin options to change the targeted classes? if so, how would I do this and where would I put it?

**Comment by IamManchanda** [comment]
1. If this is a support(plz halp) request and not a bug fix request then plz ask here => http://foundation.zurb.com/forum 
2. Please provide Test case (codepen) for any kind of bug fixes!

**Comment by CGTS** [comment]
Moved the question to http://foundation.zurb.com/forum . Thanks

**Comment by IamManchanda** [comment]
My Pleasure that i could help you @CGTS .....  !!!
