### ISSUE TITLE
[Javascript] Filters for Tables, Lists, Dropdowns, etc!

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9760]
Inspiration/Credits/Motivation => http://www.w3schools.com/w3css/w3css_filters.asp

Please let me know if its a stupid idea/discovery! :smile:

**Comment by IamManchanda** [comment]
Poke @kball ..... javascript guru =D

**Comment by DaSchTour** [comment]
@IamManchanda This part of most application frameworks. Making foundation work with such frameworks like angular, aurelia or react should be the goal and not implementing their features. There should be a clear separation of concerns. Foundation should only care about displaying things and no data logic.

**Comment by IamManchanda** [comment]
I see @DaSchTour ! 
Yup mahbe a stupid idea then .... lol !

But the reason i posted it is because its simple filters and simple js.
Moreover,
Why user need to add a js application framework if foundation can provide filters.
I am Talking static sites here BTW .... for dynamic ones, something like angular be better

**Comment by DaSchTour** [comment]
@IamManchanda I often use angular for static sites and often for totally static sites. The problem about this simple js is, that it's designed for a special usecase. There will soon be people that want additional features and then we end up with a full application framework.

**Comment by IamManchanda** [comment]
Ohk closing this ... if that's the case .... Cool up daniel..... no worries!!!

**Comment by IamManchanda** [comment]
But still i would like to have @kball thoughts on this.
