### ISSUE TITLE
Menu not working with flex?

### ISSUE THREAD

**Issue by ivanjaros** [zurb/foundation-sites#9764]
Hi, I am building foundation 6.3.0 from sass with node-sass and it looks like the menu is not working. I am using flex and the rows are fine but if I assign .menu class to a list, nothing happens. I can see some rules for .menu but nothing for its children. Looking at the code there are $global-flexbox conditions so maybe they are broken somehow?

**Comment by ivanjaros** [comment]
I switched to floating grid and the menu is still not working properly so I guess the bug is somewhere else.

**Comment by IamManchanda** [comment]
From how much i can understand ..... the bug is not related to foundation 
So Please close this 
and you move this to http://foundation.zurb.com/forum if you need some kind of help

**Comment by ivanjaros** [comment]
I checked the generated css and I don't see any rules for child elements in there. I am calling foundation like this:
my variables + '@import "foundation";' + '@include foundation-everything(true);' + custom rules

**Comment by IamManchanda** [comment]
Oh concatenation!

**Comment by ivanjaros** [comment]
OMG, so the issue is that all `>` are converted into `&amp;gt;` for some reason.

**Comment by IamManchanda** [comment]
@ivanjaros ,,,,,, my pleasure that i could help you..... 
=> though you solved it yourself ! :D
