### ISSUE TITLE
Questions/Feature: Responsive Tabs => Select Menu

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9765]
> **Foundation Lesson 143 - Create Modular Responsive Menus with Foundation 6** 
> https://www.youtube.com/watch?v=mLiX230QVRM

Awesome kev @kball ..... but same question/feature :arrow_down_small: like **Justine**..... http://bit.ly/2lvPWxN 

> - What if I want the tabs to become a dropdown instead of an accordion on mobile view? 
> - My tabs are by default on the side, I want them to contain in a dropdown box (**more like a form dropdown box**).
> - http://foundation.zurb.com/forum/posts/50550-turn-side-tabs-to-dropdown-like-a-dropdown-form-on-mobile

--------------------------------------------------------------------------------------------------------------

**Tabs** on Desktop, **Forms Select Menu ([Show Hide](http://www.tutorialrepublic.com/codelab.php?topic=faq&file=jquery-show-hide-div-using-select-box))** on mobile ??? => Responsive Select Menu tabs 

But in my case .... I am also talking about **Horizontal** tabs and not just **Vertical**!

http://foundation.zurb.com/sites/docs/tabs.html
http://foundation.zurb.com/sites/docs/forms.html#select-menus

**Comment by orangedaisy** [comment]
What about using the `.title-bar` component on small screens? [CodePen example](http://codepen.io/reverendgeneral/pen/PWVLzB).

**Comment by IamManchanda** [comment]
Nah @orangedaisy menu's are generally for main navbar 

If you ask me, Things like sidebar's/tabs shouldn't be like navbar!

**Comment by orangedaisy** [comment]
@IamManchanda - It is entirely case-dependent.

The `.title-bar` isn't inherently reserved for a "main navbar," and can readily be styled to fit any context. You could change the background color and use a different icon, for example, and it would appear nearly identical to a select element.

I'm not sure adding more code and complexity is a good idea here, especially when Foundation already has all the necessary components to solve the problem as stated.

**Comment by IamManchanda** [comment]
Sorry @orangedaisy but i disagree with you .... because its still giving that navigation feeling 
and i dont like that navigation thing in sidebars/tabs

I personally will instead use [Responsive accordion tabs](http://foundation.zurb.com/sites/docs/responsive-accordion-tabs.html) if Responsive Select Menu Tabs doesn't get the nod ahead

**Comment by orangedaisy** [comment]
@IamManchanda did you see my updated [CodePen](http://codepen.io/reverendgeneral/pen/PWVLzB)?

![tabs-1](https://cloud.githubusercontent.com/assets/8375612/22943604/1bd9ee02-f2bc-11e6-931d-a78a07d8d8e3.png)
![tabs-2](https://cloud.githubusercontent.com/assets/8375612/22943605/1bdd0128-f2bc-11e6-835e-2451033dfc25.png)

I'm not understanding your concerns about "navigation feeling." The `.title-bar` has absolutely nothing to do with a "main navigation," even if that is its most common context. Even so, this is a navigation scenario, is it not? From the [Tabs description](http://foundation.zurb.com/sites/docs/tabs.html) (emphasis mine):

> Tabs are elements that help you organize and _**navigate**_ multiple documents in a single container. They can be used for switching between items in the container.

Whether you add the select box option or use the solution I've offered, you're performing the same behavior: hiding tabs behind a dropdown at a prescribed breakpoint. I'm missing the value-add in adding the complexities of a select box for navigating tabs.

**Comment by IamManchanda** [comment]
Select menu and nav menu is two different concept altogether when we talk  mobile


![screenshot_2017-02-15-00-44-21](https://cloud.githubusercontent.com/assets/4970624/22944818/fb77fe36-f317-11e6-82b2-73076dc6ff71.png)

![screenshot_2017-02-15-00-40-11](https://cloud.githubusercontent.com/assets/4970624/22944843/0f8b7664-f318-11e6-83b8-98e113af8fa6.png)

**Comment by orangedaisy** [comment]
They're different components, yes. I'm not arguing that. I _am_ arguing that the behavior is so wildly different that we can't reuse existing components. In both cases, you're performing exactly the same actions.

**Comment by IamManchanda** [comment]
@kball ... What are your opinions ??
Is it possible or shall we shelve it and close ??

**Comment by michellechild** [comment]
@orangedaisy thank you for the codepen! This is exactly what I was looking to do.
