### ISSUE TITLE
Website: Update Link

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9772]
This is outside the docs => http://foundation.zurb.com/sites/resources
Multiple `http` in a link. Invalid link. 

Please update this below 

```html
<p>The awesome folks at Pinecone created an <a href="http://http://circlingthesun.github.io/angular-foundation-6/" target="blank">Angular</a> port for Foundation. Angular.js assists with creating single-page applications, one-page web applications that only require HTML, CSS, and JavaScript on the client side.</p>
```

to 

```html
<p>The awesome folks at Pinecone created an <a href="http://circlingthesun.github.io/angular-foundation-6/" target="blank">Angular</a> port for Foundation. Angular.js assists with creating single-page applications, one-page web applications that only require HTML, CSS, and JavaScript on the client side.</p>
```

**Comment by IamManchanda** [comment]
Also remove these below links a 404 now 

1. Clean Yeti by Serene Themes 
2. Green Yeti by Serene Themes 
3. PyroYeti for PyroCMS  by Timothy Asp
4. A Foundation Wrapper for Flask (Python)  by Pedro Baumann  F5
5. Simple user management system  utilizing Slim Framework, Facebook php sdk, Swift Mailer, PHPExcel, Foundation, & jQuery  by Garrett R. Morris
6. PolarCore Theme for Magento  on AddonBakery

**Comment by kball** [comment]
@rafibomb can you take a look at this?

**Comment by colin-marshall** [comment]
Looks like the double http is fixed but now it's missing the colon. Dead links still present.

**Comment by DanielRuf** [comment]
Any update on this? I'll run a big test for invalid / broken links in the next days.

**Comment by DanielRuf** [comment]
I guess we'll address this when we have access to the needed repository.
Should we keep this open or address this in https://github.com/zurb/foundation-sites/issues/11043?

**Comment by DanielRuf** [comment]
cc @JeremyEnglert

**Comment by DanielRuf** [comment]
Seems to be fixed.
