### ISSUE TITLE
Button-Group mixin with $buttongroup-spacing variable

### ISSUE THREAD

**Issue by marvinhuebner** [zurb/foundation-sites#9775]
Sometimes it is helpful to create is own button-group. With the usage from the `include button-group()` mixin this is already possible, but sometimes there is a need for more or less button-space. The mixin takes the global `$buttongroup-spacing`, so there is no possibility to pass his own spacing to the mixin.

It would be great to have this feature implemented.

**Comment by IamManchanda** [comment]
Looks logical to me, created a PR for the same #9779
