### ISSUE TITLE
[Abide] requiredCheck() does not return a boolean as expected.  

### ISSUE THREAD

**Issue by jellisii** [zurb/foundation-sites#9783]
#### How to reproduce this bug:

1. Have an abide form with an arbitrary input.
2. Fire `$('#form').foundation('requiredCheck', $('#input'));`

#### What should happen:

The code indicates it should return a boolean.

#### What happened instead:

The code returns the form object in its entirety. 

#### Test case:

https://codepen.io/jellisii/pen/MJxGGv

Please note that this may be a misunderstanding of the documentation and the code.  If so, I can set up a PR on the docs if I can get a working example.

**Comment by dragthor** [comment]
This works:

> $('#requiredCheck').on('click', function() { 
> var plugin = new Foundation.Abide($('#form'), {});
> var z = plugin.requiredCheck($('#input'));
> // z is a bool
> });

**Comment by dragthor** [comment]
I am seeing this in your CodePen:

Uncaught ReferenceError: We're sorry, 'requiredCheck' is not an available method for this element.

**Comment by jellisii** [comment]
I'm not seeing what you're indicating with the uncaught reference.  In both Chromium and Firefox on Ubuntu, I'm getting back the jQuery form object, which is what I don't expect.  

From the documentation at http://foundation.zurb.com/sites/docs/abide.html:

> Methods
> requiredCheck
> 
> $('#element').foundation('requiredCheck', element);
> 
> Checks whether or not a form element has the required attribute and if it's checked or not
> Name	Type	Description
> element 	Object 	jQuery object to check for required attribute

It's my understanding that `$('#element')` is the form to which abide is attached.  Is this a wrong statement?

**Comment by jellisii** [comment]
I think I've sorted this out for myself.  Apologies.
