### ISSUE TITLE
Context option for Magellan and Sticky

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#9787]
I have multiple full height panels in my layout which have overflow set for vertical scrolling when necessary.

I want to use a magellan based sticky navigation for the left side content panel, but since sticky and magellan are based on the main scrollbar this fails to work.

It would be very useful to have a context option like Waypoints: 
http://imakewebthings.com/waypoints/api/context-option/

This would allow a choice of which container scroll events should be based off of.

**Comment by colin-marshall** [comment]
@christianmagill thanks for the feature request. We won't be adding any features to F6, but we will revisit this request when the time comes to work on Foundation 7. Thanks!
