### ISSUE TITLE
[Equalizer] Image Src ulr parameter interference

### ISSUE THREAD

**Issue by logopogo** [zurb/foundation-sites#9791]
#### How to reproduce this bug:

1. Create markup for a standard Equalizer setup

#### What should happen:
Images left alone or given more consideration.

#### What happened instead:
Elements are Equalized fine, however Foundation seems to be adding a random 13 digit number as a url parameter to any image src url within the parent 'data-equalizer' element.
Generally this might be fine unless your images already utilise url parameters in which case Foundations addition of '?XXXXXX...' breaks the parameter syntax.

If these random numbers are required then perhaps Foundation needs to first check for the existence of any parameters first and if so then add the random digits to the parameter string with '&XXXXX...' instead of '?XXXXXX...' 

#### Test case:
https://codepen.io/logopogo/pen/EZJJeb

This codepen doesn't show any existing use of url parameters on the images but it does show the random digits being added if the DOM is inspected.

NOTE: the random digits aren't added all of the time, but with a few refreshes I found it adding them to one or more images most of the time.
I'm not sure what triggers it.

My use case for using URL parameters on images is a server-side implementation of a thumbnailing function. For example:
/images/my-image-thumb.jpg?Action=thumbnail&Width=594&Height=469&algorithm=fill_proportional

When Foundation adds the random number assuming it's the only parameter in use it breaks this functionality.
Adding it as an additional parameter would be fine though in my case - but other peoples functions may not like it if they try to interpret the parameter.

PS: Foundation 6.2.... didn't seem to do this. I think it's only now in F6.3.0

**Comment by IamManchanda** [comment]
yeah => //placehold.it/600x400?1487314976469

**Comment by dragthor** [comment]
This should be fixed now - https://github.com/zurb/foundation-sites/commit/efcb12ff9f9ffeb470894bae4182b47dfe45fde3

I recommend closing this issue.
