### ISSUE TITLE
Suggestion: some delegation for helping with larger development efforts

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation-sites#9793]
Hello,

So, it seems that there are some major alterations to the grid system under consideration. Considering the size of this task, I think it would be good if there were a bit of delegation.

I definitely want to get my hands dirty, but it is unclear what the progress is on that front.

**Comment by IamManchanda** [comment]
1. #9569 As of v6.4, Full Grids rework is under progress
2. #9591 As of near future, Foundation is moving to flexbox only ( dropping IE9 ) and infact is been more and so decided .... On my latest memories #9776 proves that why it will be a great move.
3. #9699 As of v7, Margin grids ( calc based grids ) is under consideration. 
Some of its benefit => https://github.com/zurb/foundation-sites/issues/9699#issuecomment-275646605, https://imgur.com/a/OWyOQ 

Moreover follow this labels for more => [grid](https://github.com/zurb/foundation-sites/labels/grid), [flex grid](https://github.com/zurb/foundation-sites/labels/flex%20grid) for more

**Comment by paxperscientiam** [comment]
Great references -- thanks for sharing!

**Comment by IamManchanda** [comment]
welcome @paxperscientiam ..... you may close this now.

**Comment by brettsmason** [comment]
I actually think we should keep this open for now as I think it might need discussing some more. You are right in that it should be clearer what's being worked on and how others could help.

@IamManchanda thanks for proving the links by the way :)

**Comment by IamManchanda** [comment]
ohk dok ,,,,,, keep it open then :smile:

**Comment by IamManchanda** [comment]
@paxperscientiam But i must say if you are looking to volunteer.... #9487 can be a good headstart
and with the assignee of that @ncoden absent these days .... i think you should take that up if you are looking to, which i think you are ( https://github.com/zurb/foundation-sites/pull/9487#issuecomment-266176863 ) ...

**Comment by paxperscientiam** [comment]
I will likely start a new thread for this, but here is an example of a relatively opinionated template for a newspaper "app". I very much agree with @ncoden on #9569 wrt to "modularization."

This has the potential to really clean up markup if HTML5 semantic elements are leveraged and encouraged.

[newspaper](https://github.com/paxperscientiam/foundation-sites/tree/newspaper-example)

**Comment by colin-marshall** [comment]
@paxperscientiam I think this is probably ok to close now. Reopen if you feel I have done so in error. Thanks!
