### ISSUE TITLE
Don't reload as well as stream changes to watched Sass in the ZURB template 

### ISSUE THREAD

**Issue by snoopdouglas** [zurb/foundation-sites#9796]
#### How to reproduce this bug:

1. Create a new Foundation for Sites project with the ZURB template
2. `npm start`
3. Change a watched stylesheet

#### What should happen:

Changes should be streamed to the browser without a full reload

#### What happened instead:

The browser fully reloads the page

#### Pull request:

I've created a [PR for the ZURB template](https://github.com/zurb/foundation-zurb-template/pull/54) that fixes this.

**Comment by kball** [comment]
Thanks @snoopdouglas! Just merged that updated.
