### ISSUE TITLE
abide validation not working for iOS

### ISSUE THREAD

**Issue by cranst** [zurb/foundation-sites#9797]
I have a form that I'm working on with Foundation and Abide. I was testing all on desktop to get the form ready, but decided to test Android and iOS. I'm glad I did because I found that iOS treated the form as if Abide was not even there. Submitted without validation. Android and desktop all tested just fine.

submit this form on mobile (iOS) and the form will submit regardless of validity
http://jsfiddle.net/hrvky0pa/

It *should* give an error about filling out the field, but instead it continues without a care in the world.

**Comment by nordanfors** [comment]
Is this fixed or even looked at yet? I'm having the same issue and my client is not impressed to say the least. Is there any workaround to get it working somehow?

**Comment by kball** [comment]
Umm I'm confused as the linked fiddle does not contain any Foundation JS at all... it is using html5 validation attributes which are not cross-browser consistent. If you want to use Abide you will need to

1. Include Foundation
2. disable default html5 validation (`novalidate` on form)
3. Add abide to the form (`data-abide` on the form).

I've just verified the examples in the docs work just fine on my iOS device... maybe you can link an example that is using Foundation but not working for you?

**Comment by IamManchanda** [comment]
@cranst @nordanfors I am closing this as per above comment by @kball but **feel free** to reply if you are still facing issues
