### ISSUE TITLE
[Right-to-Left Support] Page is invisible

### ISSUE THREAD

**Issue by MProG** [zurb/foundation-sites#9798]
#### How to reproduce this bug:

1. In rails 5.0.1 application i add dir="rtl" lang="ar" to html tag.(i try only on local machine)
2. Open application in chrome or opera neon browser(in safari all work fine)

#### What should happen:
User should see page.
#### What happened instead:
Sometimes(more then 50% times) page is invisible. But all links are avaliable. Browser consloe hasn't any errors.
When i resize browser window  page again becomes visible.

**Comment by IamManchanda** [comment]
can you attach screenshots .... also i would need to check out your code @MProG

**Comment by MProG** [comment]
@IamManchanda http://g.recordit.co/s2x2aWlPn2.gif This is gif with behavior.  
<img width="625" alt="2017-02-22 16 06 44" src="https://cloud.githubusercontent.com/assets/8362820/23212709/020de5c4-f919-11e6-9d6e-8a90c72b37d5.png"> and scss 
<img width="302" alt="2017-02-22 16 07 54" src="https://cloud.githubusercontent.com/assets/8362820/23212724/1ceb22e4-f919-11e6-840e-d32a36bbcf17.png">

**Comment by MProG** [comment]
@IamManchanda can you reproduce?

**Comment by IamManchanda** [comment]
@MProG zip ( or google drive ) me your code  please ??
and yeah with a little instructions on installation ( as i use Php Laravel  for backend )

I Might be able to solve as its a frontend issue than of rails .... so i might be able to reproduce and solve it around!

**Comment by DanielRuf** [comment]
Closing as we did not receive any further information.
