### ISSUE TITLE
[Improvement] dropdown position configuration

### ISSUE THREAD

**Issue by SassNinja** [zurb/foundation-sites#9799]
I like the framework's dropdown component. But very often its configuration is much to limited for me and I can't use it. The main issue in my eyes is the limited position configuration.

On the one hand I think it's inappropriate to bind the horizontal position to a float class (I have to use a custom float-none class if I don't need the float but only the position). On the other hand (much more important) I sometimes want to define a horizontal AND a vertical position.
Currently it's either or.

In my opinion it would be better if you can define both positions at the dropdown element. So for example 'left bottom' or 'right top'. Perfect solution would be if you can define a position related to the element (left|top|right|bottom) and as second parameter the horizontal or vertical alignment for it (left|top|right|bottom|center). Attached you can find a quick mock of what I mean.
This would heavily improve the dropdown module and make it super flexible.

I can try to adjust the code to achieve at least parts of my described solution. But since I'm not a javascript ninja this can take a while and may need some reworking.
Did anyone else face the limited options of the dropdown or has maybe already started to work on an improvement? (I couldn't find an issue or PR yet)

Any help on this is appreciated :-)

![dropdown-improvement](https://cloud.githubusercontent.com/assets/19912475/23163513/07d04b00-f833-11e6-9660-1b2bd9436c6b.jpg)

**Comment by kball** [comment]
I agree that dropdown could definitely use an update... do you want to take this on? Happy to consider a much more sass-based approach than the current as well... the current approach uses JS to do a lot that I think could probably be done with SCSS.

**Comment by SassNinja** [comment]
Yes, I'll try to work on this asap.
But talking about more sass-based: do have something particular in mind?

I've seen the whole positioning is done via JS (absolute) instead of CSS that is relative to the dropdown toggle button. But on the other hand this allows more flexibility in the markup since the button mustn't wrap the dropdown pane...
Did you mean this or something else?

**Comment by kball** [comment]
@SassNinja fyi working on this in #10053. If you're interested in taking a look/helping push it forward, I'd be happy for the help

**Comment by kball** [comment]
Implemented and merged in #10053

**Comment by SassNinja** [comment]
@kball sorry for my late reply (I was quite busy with the nested off-canvas feature and lost track on this one)

Thanks for taking care of the dropdown improvement!
Explicit positioning looks good :+1:
