### ISSUE TITLE
Javascript Technical Update: ECMAScript 2016+ in Firefox

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9807]
https://blog.mozilla.org/javascript/2017/02/22/ecmascript-2016plus-in-firefox/

> After the release of ECMAScript 2015, a.k.a. ES6, the ECMAScript Language Specification is evolving rapidly: it’s getting many new features that will help developing web applications, with a new release planned every year.
> 
> Last week, Firefox Nightly 54 reached **100%** on the Kangax ECMAScript 2016+ compatibility table that currently covers ECMAScript 2016 and the ECMAScript 2017 draft.

Source: [FrontEnd Daily](https://twitter.com/FrontEndDaily/status/834780217537347588), Mozilla Blog!

**Comment by IamManchanda** [comment]
https://v8project.blogspot.in/2017/02/high-performance-es2015-and-beyond.html

**Comment by Deckluhm** [comment]
Not sure I understand what this issue is about? Is that a "feature" request?

**Comment by IamManchanda** [comment]
A kind of alhough already under radar #9438 
Basically is a simple update on firefox's 100% compatibility to es2016+ !

That i wanted foundation communtiy to to let know !

**Comment by IamManchanda** [comment]
Closing this now.... I hope this technical update ringed a bit of bells!
