### ISSUE TITLE
Inline email API

### ISSUE THREAD

**Issue by brianbier** [zurb/foundation-sites#9810]
Hi I love foundation for emails.
Do they have an api I can use to inline my html email styles?

**Comment by IamManchanda** [comment]
http://foundation.zurb.com/emails/docs/sass-guide.html

> The ZURB Stack workflow also includes Handlebars, allowing you to write emails as templates instead of static files. Lastly, you can easily make sweeping design changes with the Sass settings file. Here’s everything that’s packaged in this template:
> 
> - Inky HTML
> - Sass
> - Handlebars templates
> - BrowserSync
> - Image compression
> - **Inlining**
> 
> In this Getting Started guide, we'll download Foundation for Emails, construct the basic grid, and then **inline our email** so it's ready to test.

**Comment by IamManchanda** [comment]
http://foundation.zurb.com/emails/docs/sass-guide.html#inlining

**Comment by brianbier** [comment]
@IamManchanda  Thanks for the advice. I remember seeing this option but I am building a specific program and all i want to do is POST to their server and get the inline html. Do you know if this is possible?

**Comment by IamManchanda** [comment]
Sorry but I am not into javascript ( still learning ) .... Poke @kball 

But still as far and as much i know ..... foundation email uses **gulp** to inline the html 
( Though not 100% sure )

**Comment by Deckluhm** [comment]
Note that this is not a forum / place to ask for help (plus this is the Foundation for Sites repository, not the [Foundation for Emails one](https://github.com/zurb/foundation-emails)). If you need help, please use the [Foundation forum](http://foundation.zurb.com/forum).

That said, you can find more information about inlining (and more generally the Foundation for Emails stack) here: http://foundation.zurb.com/emails/docs/zurb-stack.html#inlining (`gulp-inline` is probably what you need)

**Comment by zerodahero** [comment]
I'm in the midst of a PHP project, so we're using https://github.com/Dreamvention/inky-premailer which works quite well for our purposes.

**Comment by brettsmason** [comment]
As others have said this should really be posted on the Foundation forum or the [Foundation for Emails](https://github.com/zurb/foundation-emails) repo. Hopefully the above comments should of answered your question though, so I'm going to close this!
