### ISSUE TITLE
Dropdown Menu parent link ON DESKTOP, takes two clicks to clickthrough

### ISSUE THREAD

**Issue by ramonchito2** [zurb/foundation-sites#9811]
#### How to reproduce this bug:

1. Setup default dropdown menu (vertical or horizontal)
2. While hovering over the dropdown menu and children are displaying, try clicking on the parent link
3. After nothing happens, click a second time and notice how the link now works.

#### What should happen:
Link should be clickable on the first try
#### What happened instead:
Parent link has to be clicked twice in order to navigate to that page, possibly making users feel that the link doesn't work, and never navigating to that page... or that its just buggy.
#### Test case:
This can be tested right on Foundation's site [here](https://foundation.zurb.com/sites/docs/dropdown-menu.html)
If any of the menu links without dropdowns are clicked, notice the url add the hashtag.. the link has been clicked.
However, if you click on any of the dropdown menu links, nothing happens. Click a second time however, and watch the url add the hashtag.

Again, at the time of this posting, this can be tested on Foundation's site
https://foundation.zurb.com/sites/docs/dropdown-menu.html

**Comment by mk1sml** [comment]
I am having almost the same issue. Currently on Microsoft Edge touch screen device, the submenu items do not work correctly when clicked.

Example can be viewed at https://www.bakusa.com

**Comment by kball** [comment]
I'm not able to reproduce this bug... I've tested the current docs, a checked out version of 6.3.0, and the current state of develop, using a range of devices in browserstack... going to close, but if you're still seeing and can set me up with more exact reproduction instructions please reopen.

**Comment by mk1sml** [comment]
Hello, Thank you for taking the time to look into this. I am reopening this because it appears that the touch screen issues are only happening in Microsoft Edge. When the dropdown are 'tapped" the secondary levels are not able to open unless you "long press" on it and open in new tab or window. Again this is only happening on a touch screen pc using Microsoft Edge.

Thank you,
