### ISSUE TITLE
[Abide] URL and Domain Patterns Failed on local Web Server

### ISSUE THREAD

**Issue by rocbar** [zurb/foundation-sites#9815]
#### How to reproduce this bug:

1. Step one
Use your online doc sample code at http://foundation.zurb.com/sites/docs/abide.html
2. Step two
Go to form field: URL Pattern
3. Step three
Enter: http://localhost/

#### What should happen:
Should pass URL or domain validation for localhost
#### What happened instead:
Failed
#### Test case:
The same HTML sample code tested on my local web server also failed when using both URL and domain patterns for Abide validation.

Foundation version use on local web server are:
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/css/foundation.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.1.1/motion-ui.min.css" />
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.0/js/foundation.min.js"></script>

You can recreate the issue on your website doc at:
http://foundation.zurb.com/sites/docs/abide.html

- [CodePen with Foundation 6.2.4 and MotionUI](https://codepen.io/ncoden/pen/gLEoEB)
- [CodePen with Foundation 6.2.4, Flexbox grid and MotionUI](https://codepen.io/ncoden/pen/yVwpZN)

- [CodePen with Foundation 6.3.0 and MotionUI](https://codepen.io/ncoden/pen/oYVpMe)
- [CodePen with Foundation 6.3.0, Flexbox grid and MotionUI](https://codepen.io/ncoden/pen/qqvpQj)

**Comment by jellisii** [comment]
There's a potential workaround for your problem in #9180

**Comment by SassNinja** [comment]
@rocbar I'm wondering if it's a bug at all?
In my opinion http://localhost/ isn't a valid url on  a common website so it's fine to mark it as invalid.

If you really need an input for localhost URLs I'd rather recommend creating a custom pattern for this instead of extending the default url pattern to support localhost without a TLD.

@jellisii no, the alternative regex doesn't match this url either

**Comment by colin-marshall** [comment]
@SassNinja I agree. Custom pattern would be best for this rare case. Closing.
