### ISSUE TITLE
pagination-container mixin uses $global-radius instead of the $radius parameter

### ISSUE THREAD

**Issue by 7oot** [zurb/foundation-sites#9816]
#### What should happen:

Trying to set the link border-radius for pagination be it through the pagination-container mixin or by changing the default $pagination-radius should style the links with the desired radius.

#### What happened instead:

Pagination links always have the $global-radius, since it's directly used inside pagination-container instead of the mixin's $radius parameter.

**Comment by brettsmason** [comment]
@7oot You are correct - this line needs changing: https://github.com/zurb/foundation-sites/blob/develop/scss/components/_pagination.scss#L116

Did you want to submit a PR to fix this?

**Comment by IamManchanda** [comment]
@7oot follow this if you want to know how to do a PR

https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

and here is the solution for that above line brett mentioned!
simply change to,

```scss
border-radius: $pagination-radius
```

**Comment by brettsmason** [comment]
@IamManchanda Thanks for linking to that. It should actually be `border-radius: $radius;` as we are setting `$radius: $pagination-radius` within the mixin 😄

**Comment by IamManchanda** [comment]
Oops sorry i didn't see the arguments ... my mistake @brettsmason :smile:

**Comment by kball** [comment]
@7oot were you interested in doing a PR for this? If not, I have a couple other folks in mind to direct a good beginner issue like this to

**Comment by 7oot** [comment]
@kball sorry for not answering sooner. feel free to forward the issue to whomever you want. thanks for asking :)

**Comment by IamManchanda** [comment]
@kball sorry for interupting but ......

@Vuurvlieg would you like to take this up as a good head start ??
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by Vuurvlieg** [comment]
@IamManchanda Yes, I don;t know how Github works, just created a account to report bugs. When I have time I will read that document, thanks.

**Comment by HeidiEkenstam** [comment]
I submitted a PR for this using the article @IamManchanda recommended, hope I did everything correctly and the issue gets resolved.  PR #10193

**Comment by IamManchanda** [comment]
Great... Will surely look into it
