### ISSUE TITLE
Close all other opened off canvas elements if we open new one

### ISSUE THREAD

**Issue by jack-fdrv** [zurb/foundation-sites#9824]
#### How to reproduce this bug:

I have menu, each element open canvas element.
When I click on menu item 1 it show me the sub menu (of-canvas block), when I click on menu item 2, it show one more of-canvas but it doesn't close the other one, opened of-canvas.

#### What should happen:

Should hide other opened of-canvas elements.

#### What happened instead:

It just show 2 in the same time.

**Comment by jinch** [comment]
I would like this feature as well but unfortunately, I think this is the default behavior. It would be great if that can be built in on future updates but I think we may have to find our own work around for this. Maybe working in some javascript to disable the trigger button if off-canvas is open? If I come across a solution I will post.

**Comment by jinch** [comment]
I'm not that great at Jquery and I am sure there is a more efficient way to do this but see if you can amend the below code to your needs.

This should continually check if a "offCanvaLeft" has the class "is-open" applied to it and disable another button with your unique ID. Change this around as you see fit and if anyone has a better way to go about this, please share. 

`/*START DISABLE BUTTON*/
function isopenLeft($){
	"use strict";
	function check_isopenLeft(){
		if ($("#offCanvasLeft").hasClass("is-open")) {
			$("#Your_Other_ButtonID_here").prop('disabled', true);
			$("#Your_Other_ButtonID_here").css("background-color", "#000");
		}
		else {
			$("#Your_Other_ButtonID_here").prop('disabled', false);
			$("#Your_Other_ButtonID_here").css("background-color", "#999");
		}
	}
     window.setInterval(check_isopenLeft,500);
}

jQuery(document).ready(function ($) {
	"use strict";
        isopenLeft($);
});
/*END DISABLE BUTTON*/`

**Comment by colin-marshall** [comment]
@jack-fdrv this sounds useful for certain situations. It is a feature request, and because we are not adding any features to F6, I am going to close this out for now. We will reopen this to revisit when the time comes to work on Foundation 7. Thanks!

**Comment by carambamoreno** [comment]
I'm happy to finally be able to contribute. 

I solved this by detecting all other canvases with the class ".is-open" and programmatically closing them. 

```
$('.off-canvas').on('opened.zf.offcanvas', function(event) {
      $(".off-canvas.is-open").not(this).foundation('close');
    });
```
