### ISSUE TITLE
Tooltip only accepts one offset direction

### ISSUE THREAD

**Issue by nerdyglasses** [zurb/foundation-sites#9830]
I have prepared a jsFiddle. It ignores the `hOffset` attribute:
https://jsfiddle.net/gambo/khhxdd9e/

It shouldn't only accept EITHER `hOffset` OR `vOffset` based on its direction.

If the user of that tooltip decides to add an offset, then it's probably due to a reason. I don't think this should be something the tooltip lib should decide.

That's the code that is preventing me from setting it:
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.tooltip.js#L146-L147

Should I just send over a PR?

**Comment by nerdyglasses** [comment]
https://github.com/zurb/foundation-sites/pull/9831

**Comment by JeremyEnglert** [comment]
Looks like this was fixed. Closing.
