### ISSUE TITLE
A disabled .hollow button style not consistent when hovered over

### ISSUE THREAD

**Issue by tymothytym** [zurb/foundation-sites#9832]
#### To reproduce:

1. Add classes `button disabled hollow` to a button element e.g. `<button type="button" class="button hollow disabled" id="mybutton">Save</button>`
2. Hover over button with the mouse

Or

1. Add classes `button hollow` to a button element and the attribute `disabled` e.g. `<button type="button" class="button hollow" id="mybutton" disabled>Save</button>`
2. Hover over button with the mouse

#### Expected:

- Button should not change in style.  The hover effect suggests an action can be taken. 
- The button should be displayed in the `hollow` style, even though disabled, to differentiate it from a standard `primary` button which is disabled

#### Happened:

__In v6.3.0__
 When the button is hovered over with the mouse, the button changes to have the background colour `$primary-color` with the text colour set to the best visibility against the new background (with `opacity: 0.25;` inherited).

__In v6.3.1__
Button background colour is set to `$primary-color` and the text colour is set to the best visibility against the new background (with `opacity: 0.25;` inherited) and doesn't change on hover (so a disabled `hollow` button is visually the same as a disabled `primary` button)

#### E.g.s:

- [Foundation Docs v6.3.0 - hollow button disabled example](http://foundation.zurb.com/sites/docs/button.html#hollow-style)
- [JSFiddle v6.3.0](https://jsfiddle.net/tymothytym/pvLqpkob/)
- [JSFiddle v6.3.1](https://jsfiddle.net/tymothytym/1yze6put/)

#### Possibly related:
#9021 and/or #9022

**Comment by tymothytym** [comment]
Can be fixed by changing the `button-disabled` mixin in `scss/components/_button.scss` to:

```
@mixin button-disabled($color: $primary-color) {
  opacity: $button-opacity-disabled;
  cursor: not-allowed;
  &:hover, &:focus {
    background-color: $color;
    color: $button-color;
  }
  &.disabled, &[disabled]  {
    background-color: inherit;
    color: inherit;
  }
}
```

**Comment by IamManchanda** [comment]
The difference in v6.3.0 and 6.3.1 happened here first of all => #9648 

You are correct, i will look into it!

**Comment by IamManchanda** [comment]
@tymothytym i have created a PR #9835 .... Is this what you wanted ?

**Comment by tymothytym** [comment]
@IamManchanda thanks, that looks good!

**Comment by IamManchanda** [comment]
@tymothytym i think you should reopen this untill that PR merges.... as this will get close automatically once that's get merged!

**Comment by tymothytym** [comment]
Sorry, pressed the wrong button...

**Comment by IamManchanda** [comment]
@tymothytym This is fixed now .... most probably 6.3.2 buddy 
and yeah sorry for creating the bug ( but believe me i had no idea about it :smile: )
