### ISSUE TITLE
Off-Canvas Menu Focus - Handicap Accessibility

### ISSUE THREAD

**Issue by frankangelone** [zurb/foundation-sites#9834]
In the example provided, I have two links that would open an `off-canvas` menu when clicked. If I click the first link (called "Quick Links"), the menu opens, but when I click tab (testing that the application is handicap accessible), the focus goes to my second link (called "Info For") rather than the first list item in the "Quick Links" menu.  I'm assuming the example below may not be valid for the expected structure required by Foundation with the `off-canvas` menu.     

Here's an example: 

```
<div class="off-canvas-wrap docs-wrap move-left" data-offcanvas="">
		<div class="inner-wrap">
			<header>
				<div class="large-6 medium-6 small-3 columns secondarylinks">
					<div class="icon-bar-wrapper show-for-large-up">
						<div class="icon-bar three-up">
							<a class="right-off-canvas-toggle" href="#" id="quickLinks" rel="quicklinks-list" aria-expanded="true"><em class="fi-thumbnails"></em><label>Quick Links</label></a> 
							<a class="right-off-canvas-toggle" href="#" id="infoFor" rel="infofor-list" aria-expanded="false"><em class="fi-torsos-all">&#8203;</em> <label>Info For</label></a>
						</div>
					</div>
				</div>
			</header>	

			<aside class="right-off-canvas-menu push off-canvas-visible" id="quicklinks-list">
				<h2>Quick Links</h2>
				<ul>
					<li><a href="#" id="library">Library</a></li>
					<li><a href="#" target="_blank">News</a></li>
					<li><a href="#" target="_blank">Events</a></li>
					<li><a href="#">Directory</a></li>
					<li><a href="#">Give</a></li>
					<li><a href="#">My Portal</a></li>
					<li><a class="exit-off-canvas" href="#" id="quickClose"> <i class="fi-x-circle"></i> Close Menu</a></li>
				</ul>
			</aside>
			
			<aside class="right-off-canvas-menu push off-canvas-visible" id="infofor-list">
				<h2>Info For</h2>
				<ul>
					<li><a href="#" id="prospective">Prospective Students</a></li>
					<li><a href="#">Current Students</a></li>
					<li><a href="#">>Admitted Students</a></li>
					<li><a href="#">Faculty &amp; Staff</a></li>
					<li><a href="#">Alumni</a></li>
					<li><a href="#">Employers</a></li>
					<li><a href="#">Media</a></li>
					<li><a href="#"><i class="fi-x-circle"></i> Close Menu</a></li>
				</ul>
			</aside>
			
			<a class="exit-off-canvas"></a>
		</div>
	</div>
```

If you could let me know whether the HTML structure provided is valid or not for the behavior I'm expecting, that would be most helpful.  Essentially, I'm trying to use `info-bar` and `off-canvas` together.

**Comment by IamManchanda** [comment]
cc / @sethkane @Owlbertz

**Comment by Owlbertz** [comment]
Hi @frankangelone if you could re-create your website in a CodePen (you can use [this template](http://codepen.io/Owlbertz/pen/WpxoGr?editors=1000) I'll be happy to have a look.

**Comment by frankangelone** [comment]
@Owlbertz Here's a link to the CodePen: [http://codepen.io/anon/pen/PpNPLa](url)

You'll see a "Quick Links" and "Info For" button on the page.  After you click "Quick Links, click the tab key.  You'll notice that focus doesn't immediately go to the "library" link in the menu and instead goes to the "Info For" button first.  As you click tab, the focus eventually goes to the "library" link in the menu.  As a side note (my actual project), the second button ("Info For") would have it's own menu too.  I tried to provide a basic example for testing purposes.  

When only using one button ("Quick Links"), everything works as expected.  You can comment out `id="infoFor"` to test with the one button.

**Comment by DanielRuf** [comment]
@Owlbertz do you want / plan to check this and find a proper solution?

**Comment by JeremyEnglert** [comment]
I think this has to do with how it is being used in this particular case. When testing with a clean install, when I click the offcanvas button (or whatever is used to trigger offcanvas), the focus is taken inside of the offcanvas area as expected.
