### ISSUE TITLE
[Button] $offset SASS parameter

### ISSUE THREAD

**Issue by aldees** [zurb/foundation-sites#9836]
$offset parameter is not used in the button-dropdown mixin

This does not change the left margin of the arrow to .4em:
@include button-dropdown($color: $dark-gray, $offset: .4em)

**Comment by kball** [comment]
@canterberrie do you want to take a crack at this one?

**Comment by kball** [comment]
Actually I think this might be a good one for @LaurelBCodin

**Comment by LaurelBCodin** [comment]
resolved with #9982
