### ISSUE TITLE
Patch v6.3.1 Update?

### ISSUE THREAD

**Issue by jinch** [zurb/foundation-sites#9842]
Hi, I just tried updating my foundation 6.3 site to the v6.3.1 patch via terminal. Unfortunately, I was not able ~ error message ~ (nothing to update). Does anyone know how I may be able to patch the 6.3 build of an existing site? Is there a new way to do this?

**Comment by brettsmason** [comment]
@jinch How have you installed Foundation - via Bower or NPM? Will need some more details to be able to help.

**Comment by jinch** [comment]
Initially, I used the terminal to install v6.2 (foundation new). Then I had to manually update that to v6.3 as there was no clear method. I read on the foundation forum if you changed the changed the dependency in bower.json to "foundation-sites": "~6.3.0" you can force the update. 

This worked for 6.2 --> 6.3 but now the 6.3.1 update does not work either for me.
_____________

It may be a different topic but I just noticed even with a clean install of 6.3.1 using the terminal (foundation new) method, for some reason, it no longer recognizes the newly created 6.3.1 build folder in the terminal and will not allow me to watch .scss changes when typing (foundation watch) so the app.css file is never created. : /

**Comment by brettsmason** [comment]
@jinch setting the version to `~6.3.0` if I'm not mistaken will only install that specific version.
You need to set it to`^6.3.0` which will allow you to installed newer versions (version 6.3.0 or newer). Then from the terminal run `bower update` - this should update to 6.3.1.

**Comment by jinch** [comment]
@brettsmason  - Thank you! That worked :)

Do you know if the 6.3 settings.scss or the app.scss files have changed with this update? Did those files automatically update when i did the (bower update)?

Sorry for all the questions... also wondering if this update addressed some of the off-canvas bugs? In particular... [#9696](https://github.com/zurb/foundation-sites/issues/9696) and even more critical to my layout [#9629](https://github.com/zurb/foundation-sites/issues/9629).

**Comment by brettsmason** [comment]
@jinch Great glad that worked.

According to the [patch notes for 6.3.1](https://github.com/zurb/foundation-sites/releases/tag/6.3.1) there were no migration notes, so I dont think there were any changes to `settings.scss`.

#9696 was fixed with the update, however the sticky issue is actually a bit more complicated. A rewrite of sticky is in the works that will solve the issue.

**Comment by jinch** [comment]
@brettsmason - Very cool / thanks again for the help and info.

I'm very eager to see how that sticky icky is resolved. My site navigation is dependent so currently on hold for a solution. I'll keep an eye on that thread and if need be find a workaround if that is something further down the line. This will be a great addition if and when the kinks are worked out.

Regardless, kudos to you and team for your continued efforts in advancing this framework // It's very much appreciated by the community! Many thanks!

**Comment by brettsmason** [comment]
@jinch from my understanding sticky will be using the `position: sticky` functionality in newer browsers along with a polyfill that allows it to work on older browsers.

I'll close this now if you dont mind, but feel free to open another issue if you have problems, and keep an eye out for updates!
