### ISSUE TITLE
[Forms] Incorrect select aligment on rtl chrome

### ISSUE THREAD

**Issue by MProG** [zurb/foundation-sites#9844]
foundation 6.3.0 , chrome
Dropdown list for 'rtl' style format align incorrect. List align by begin of text. 
Expected result(now this is result only for situation when i don't select any variant):
<img width="730" alt="2017-03-06 13 48 40" src="https://cloud.githubusercontent.com/assets/8362820/23606960/1bddbb5a-0274-11e7-9d15-04315ba068c7.png">
Current result:
<img width="1321" alt="2017-03-06 13 48 53" src="https://cloud.githubusercontent.com/assets/8362820/23606998/341ad694-0274-11e7-987f-d5b64dce19f0.png">

In safari all work fine.

**Comment by kball** [comment]
This is kind of bizarre... @abdullahsalem you've done a lot of RTL, any idea what is going on here? Can you take a crack at this?

**Comment by JeremyEnglert** [comment]
Can you provide a CodePen link? This makes it much easier to test/fix.

Closing. Will reopen if a CodePen link is provided.
