### ISSUE TITLE
Flex Grid Column Widths Not Restricted

### ISSUE THREAD

**Issue by natewiebe13** [zurb/foundation-sites#9845]
#### How to reproduce this bug:

1. Using the flex grid, add an item that is wider than the max width
2. The column is now wider than the max width

#### What should happen:

The column should be restricted by the max width

#### What happened instead:

The column was as large as the item. Related to: https://stackoverflow.com/questions/34934586/white-space-nowrap-and-flexbox-did-not-work-in-chrome

#### Test case:

http://codepen.io/natewiebe13/pen/YZGaOy

**Comment by joeworkman** [comment]
This issue has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/column-cell-width-bug-with-min-width/1440/2
