### ISSUE TITLE
Foundation Zurb Template empty /scss folder gets copied into /dist folder 

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-sites#9851]
Title says it all. Set up a new project, foundation new and foundation watch. The dist folder gets an empty scss folder, among all the other ones needed (css, js, etc.). Just a small bug, nothing big, just a bit annoying. can someone confirm? btw. i am on windows.

**Comment by Deckluhm** [comment]
You should open this issue on the [Foundation CLI repository](https://github.com/zurb/foundation-cli).

**Comment by phifa** [comment]
done
https://github.com/zurb/foundation-cli/issues/47

**Comment by IamManchanda** [comment]
@phifa Please close this one!

**Comment by phifa** [comment]
sure.
