### ISSUE TITLE
SASS Compile Error In typography.scss

### ISSUE THREAD

**Issue by coleh33** [zurb/foundation-sites#9855]
I am having an issue with compiling SASS using node-sass and all NPM with no bower.  It appears the issue is within the `@include foundation-typography;` file as when I remove that include everything works.  The error is listed below.  Using Foundation version 6.3.1 and Node SASS version 4.5.0

`{
  "status": 1,
  "file": "node_modules/foundation-sites/scss/util/_unit.scss",
  "line": 129,
  "column": 7,
  "message": "argument `$number` of `unit($number)` must be a number\n\nBacktrace:\n\tnode_modules/foundation-sites/scss/util/_unit.scss:129, in function `unit`\n\tnode_modules/foundation-sites/scss/util/_unit.scss:129, in function `unitless-calc`\n\tnode_modules/foundation-sites/scss/typography/_base.scss:348, in mixin `@content`\n\tnode_modules/foundation-sites/scss/util/_breakpoint.scss:149, in mixin `breakpoint`\n\tnode_modules/foundation-sites/scss/typography/_base.scss:329, in mixin `foundation-typography-base`\n\tnode_modules/foundation-sites/scss/typography/_typography.scss:22, in mixin `foundation-typography`\n\tassets/scss/style.scss:11",
  "formatted": "Error: argument `$number` of `unit($number)` must be a number\n\n       Backtrace:\n       \tnode_modules/foundation-sites/scss/util/_unit.scss:129, in function `unit`\n       \tnode_modules/foundation-sites/scss/util/_unit.scss:129, in function `unitless-calc`\n       \tnode_modules/foundation-sites/scss/typography/_base.scss:348, in mixin `@content`\n       \tnode_modules/foundation-sites/scss/util/_breakpoint.scss:149, in mixin `breakpoint`\n       \tnode_modules/foundation-sites/scss/typography/_base.scss:329, in mixin `foundation-typography-base`\n       \tnode_modules/foundation-sites/scss/typography/_typography.scss:22, in mixin `foundation-typography`\n       \tassets/scss/style.scss:11\n        on line 129 of node_modules/foundation-sites/scss/util/_unit.scss\n>>   @if unit($value) == '%' {\n   ------^\n"
}`

**Comment by kball** [comment]
@coleh33 What does your settings file look like? digging through the backtrace it looks like something's going wrong calculating the header definitions...

cc @brettsmason @karland

**Comment by JeremyEnglert** [comment]
No response after 6+ months. Closing.
