### ISSUE TITLE
expanded columns not taking up all the space

### ISSUE THREAD

**Issue by sanderha** [zurb/foundation-sites#9856]
#### How to reproduce this bug:

1. Create .row.expanded
2. create .small-12.large-7.columns and .small-12.large-5.columns

#### What should happen:
Split the columns perfectly into the width of container

#### What happened instead:
1px of whitespace is leftover on the right side of the columns.

If I then change the large-5 max-width and flex properties from 
``` 
flex: 0 0 41.66667%;
max-width: 41.66667%; 
```
to 
``` 
flex: 0 0 41.668%;
max-width: 41.668%; 
```
Then the tiny whitespace is eliminated. Any ideas to why this happens?

### UPDATE
This only happens in chrome, and only on certain screen sizes / screens.. might just be a browser bug..

**Comment by IamManchanda** [comment]
Please provide test case,

You can fork these below codepen's to provide a test case.

6.3.0
- [CodePen with Foundation 6.3.0 and MotionUI](http://codepen.io/IamManchanda/pen/vgemXR)
- [CodePen with Foundation 6.3.0, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/xgXdRq)

6.3.1
- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

**Comment by JeremyEnglert** [comment]
No test case provided. Closing.
