### ISSUE TITLE
[Foundation6] Undefined mixin 'exports'

### ISSUE THREAD

**Issue by bsmedhabib** [zurb/foundation-sites#9860]
_a-button.scss:.Undefined mixin 'exports'

when : grunt clean build 
Foundation 6 + grunt

//code
$include-html-a-button-classes: $include-html-classes !default;

@include exports("a-button") {
...

**Comment by Deckluhm** [comment]
Probably just me but... can you explain more in details your issue?

What do you try to achieve? What is your code?

**Comment by JeremyEnglert** [comment]
Agree with @Deckluhm. Please provide more details and I'll reopen this issue.
