### ISSUE TITLE
F6 Modal link in Dropdown

### ISSUE THREAD

**Issue by jtoliver** [zurb/foundation-sites#9861]
For some reason, an anchor tag with the data-open attribute will not open a modal in a dropdown menu. I can open the modal in the web console using $(ID).foundation('open'); I'm trying to stick with just using data-attributes. Am I missing something?

**Comment by jtoliver** [comment]
Awe...nobody wants to answer me question...

**Comment by IamManchanda** [comment]
@jtoliver.... Even google gave microsoft 90 days...  please give us some time :D ( Just kidding) 

Please provide test case ?
Here is the codepen from which you can fork => https://github.com/zurb/foundation-sites/pull/9827

**Comment by jtoliver** [comment]
My apologies, after creating a codepen http://codepen.io/anon/pen/OpgZoy I realized that case works here. So i'm going to do some more debugging in my application to see what is up. I'm sure my syntax is correct. I might need to check my version or have some other js getting in the way.
