### ISSUE TITLE
6.3.1 Off-canvas is opening when scrolling the page

### ISSUE THREAD

**Issue by magveda** [zurb/foundation-sites#9863]
I have this problem in Linux using Google Chrome Version 56.0.2924.87 (64-bit)

![image](https://cloud.githubusercontent.com/assets/674574/23797008/7376766a-05a6-11e7-9ef6-f12e02ddbc52.png)

#### How to reproduce this bug:

1. go to http://foundation.zurb.com/sites/docs/
2. scrol the page using mouse wheel or browser scrollbar

#### What should happen:

The page should scroll without any Off-canvas elements open

#### What happened instead:

Off-canvas elements open all at once

**Comment by IamManchanda** [comment]
Can't reproduce 

Using Google chrome 56.0.2924.87
OS: Linux ( Ubuntu )

![cant-reproduce1](https://cloud.githubusercontent.com/assets/4970624/23824179/c6de527c-0697-11e7-87bb-174982f1cd14.png)

**Comment by magveda** [comment]
The problem is gone after removing the Chrome Plugin "Smooth Scrolling"

**Comment by IamManchanda** [comment]
Great @magveda, Happy that we could help!
