### ISSUE TITLE
Error generating breakpoint classes when changing smallest breakpoint

### ISSUE THREAD

**Issue by christianmagill** [zurb/foundation-sites#9865]
#### How to reproduce this bug:

1. Step one

```
$breakpoints: (
  xxsmall: 0px,
  xsmall: 429px,
  small: 640px,
  medium: 832px,
  large: 1024px,
  xlarge: 1200px,
  xxlarge: 1440px,
);

$-zf-zero-breakpoint: xxsmall;
$breakpoint-classes: (xxsmall xsmall small medium large xlarge xxlarge);
```

2. Step two
Compile

#### What should happen:
It should work

#### What happened instead:

Errors compiling 

`null was passed to rem-calc(), which is not a number.`

```
Module build failed: 
        $margin: rem-calc(-zf-get-bp-val($gutters, $-zf-size)) / 2 * -1;
                ^
          Invalid null operation: "null div 2".
          in /Users/christianmagill/Code/Sites/hcpdigestive/wp-content/themes/hcpdigestive/node_modules/foundation-sites/scss/grid/_row.scss (line 83, column 14)
```

I have also tried removing xxsmall from $breakpoint-classes, but it does not resolve the issue. Doesn't compile properly until I remove both xxsmall and xsmall, which defeats the purpose for my application.

**Comment by christianmagill** [comment]
Figured out the issue... I had to also change the grid-column-gutter to reflect xxsmall as the smallest size.

**Comment by IamManchanda** [comment]
Please close the issue if its resolved!

**Comment by stevenson-digital** [comment]
Hi guys,

I'm getting the same issue as this thread but am fairly sure I've got my setup right in terms of making sure the $grid-column-gutter is also reflected. Is there anything wrong here that would be causing the issue:

`$w-container: 1920px;
$grid-column-gutter: (
    xsmall: 20px,
    medium: 40px
);

$global-width: 9999px + map-get($grid-column-gutter, medium);
$grid-column-count: 20;
$global-flexbox: false;
$global-right: left;
$global-left: left;
$breakpoints: (
    xsmall: 0,
    small: 420px,
    meduim: 640px,
    xmedium: 1024px,
    large: 1200px,
    xlarge: 1600px,
    xxlarge: 1800px
);
$-zf-zero-breakpoint: xsmall;
$breakpoint-classes: (xsmall small medium xmedium large xlarge xxlarge);`

Any help on this would be really appreciated! Getting same error message as above post.
