### ISSUE TITLE
Native meters example doesn't work on chrome

### ISSUE THREAD

**Issue by Nimce** [zurb/foundation-sites#9866]
#### How to reproduce this bug:

1. Open Chrome (I use version 56.0.2924.87 at the moment)
2. Navigate here: http://foundation.zurb.com/sites/docs/progress-bar.html#native-meter
3. Watch as the 3 native meters are all grey, instead of with colors.
4. Open another browser (for example, Firefox).
4. Navigate to the same URL, notice the native meters work as expected.

#### What should happen:
Native meters show colors, representing their value.

#### What happened instead:
Native meters show only grey color.

**Comment by IamManchanda** [comment]
Yup was able to reproduce ... 

@kball I confirm this is a bug !

**Comment by IamManchanda** [comment]
**Eureka, Found the issue**
@Nimce This is the line where its happening => [Line 40](https://github.com/zurb/foundation-sites/blob/develop/scss/forms/_meter.scss#L40)

Thanks to autoprefixer (gulp-autoprefixer), this is generating the below code

```scss
meter {
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
}
```

and ` -webkit-appearance: none;` is causing the issue 
Refer => http://stackoverflow.com/a/38892123/3301436

![webkit-appearance-meter](https://cloud.githubusercontent.com/assets/4970624/23830427/8ec48a70-0730-11e7-9409-7534ce2f73f3.png)
