### ISSUE TITLE
Dropdown pane width not correct when floating the trigger to the right

### ISSUE THREAD

**Issue by glen-84** [zurb/foundation-sites#9869]
#### How to reproduce this bug:

(see test case)

#### What should happen:

The pane (of the right-aligned dropdown) should be 300px wide.

#### What happened instead:

It's 100% in width.

#### Test case:

http://codepen.io/glen-84/pen/RpVqjB

**Comment by IamManchanda** [comment]
I dont think we can solve this or foundation has to do anything with it ....

Reason ... There is only difference b/w these two buttons => `float-right` 
Float right is a helper class which only does this 

```scss
.float-right {
    float: right!important;
}
```

I dont think that this can be solved, Width is getting added automatically by the browser but maybe its just me!

**Comment by glen-84** [comment]
@IamManchanda The Foundation JS is setting the pane's `left` and `width` CSS properties, among others.

**Comment by IamManchanda** [comment]
Can you be a little brief @glen-84 ?

{{ As i said i might be wrong!  }}

**Comment by glen-84** [comment]
I don't know what you mean.

**Comment by IamManchanda** [comment]
I meant if you have a brief on how to solve this, then please provide!

**Comment by ricardo-lewis** [comment]
Foundation JS is forcing the width of the dropdown to be the same as the browser window width.

**Comment by JeremyEnglert** [comment]
This is working right in 6.4.3.

https://codepen.io/MateriellJeremy/pen/XZMEXQ
