### ISSUE TITLE
[Abide] URL Pattern not taking **www** into account

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9870]
URL Pattern only takes **http** and **https** into account
but there should be a way to add most common **www** into account

#### How to reproduce this bug:

**1. Step one**
Create a test case similar to
http://codepen.io/IamManchanda/pen/MpoaJY

**2. Step two**
Go to URL Pattern field

**3. Step three**
Type **www.facebook.com**

**4. Step four**
Press on that dreaded **Submit** Button

#### What should happen:
This shouldn't throw error

#### What happened instead:
This throws error

**Comment by IamManchanda** [comment]
Basically looking for a combo of [domain and url pattern](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.abide.js#L547-L549) 

because with a domain patern its opposite situation => http://codepen.io/IamManchanda/pen/pewLvY
I think we need a combo pattern of both domain and url !

**Comment by kball** [comment]
URL is not valid without http or https... perhaps a more general solution would be to allow logical combinations of validatons? e.g. domain OR url ?

**Comment by IamManchanda** [comment]
Yup combination is what i want .... is this possible right now ?? @kball

**Comment by kball** [comment]
Nope. Do you want to implement it? ;)

**Comment by IamManchanda** [comment]
Yup why not @kball but how do i apply it ..... in codes
Looking for something like 

```js
patterns: {
  website: domain || url 
}
```

**Comment by kball** [comment]
There's a couple ways you could do it... you could address the general problem (change abide's `data-validator` option to accept logical sets of validators, and handle that...) or you could simply apply the specific problem by writing a pattern that responds to the 'test' method (either a regex or an object with a test method that does what you want.  You can see how these are being applied here: https://github.com/zurb/foundation-sites/blob/develop/js/foundation.abide.js#L365

So you could probable do something like
```
patterns: {
  website: {
    test: (text) => {return Abide.defaults.patterns['domain'].test(text) || Abide.defaults.patterns['url'].test(text);}
   }
}
```

**Comment by IamManchanda** [comment]
PR is up #9984 .... thanks @kball for your kind help!
