### ISSUE TITLE
6.3.0 Advanced top-bar with flex-box enabled causes the responsive-menu to render to the right

### ISSUE THREAD

**Issue by Yanchek99** [zurb/foundation-sites#9871]
#### How to reproduce this bug:
adjust configuration to enable global flexboxes and import required flex box classes in sass.
Add the advanced top bar menu example per the docs. http://foundation.zurb.com/sites/docs/top-bar.html

#### What should happen:
the top-bar-left container should align to left and the top-bar-right should align to right.

#### What happened instead:
the top-bar-left container is stacked on top of the top-bar-right container.  the entire responsive-menu is aligned to the right with a constrained width. (See code pen)

#### Test case:

http://codepen.io/anon/pen/vxZWed

**Comment by IamManchanda** [comment]
First of all i confirm this as a bug,

Moreover, 
`#responsive-menu` is getting cold as its inheriting `display: block` 

I changed that and its now the left topbar now came from top to left of right topbar
But as you can see still not solved as it should be 
=> http://codepen.io/IamManchanda/pen/QpgQWM 

cc / @ncoden @brettsmason

**Comment by Yanchek99** [comment]
@IamManchanda adjusted the custom styling for the #responsive-menu to include `flex: auto;` which seems to give it proper alignment now.  Perhaps this is a valid fix?
```
#responsive-menu {
  display: flex;
  flex:  auto;
}
```

**Comment by IamManchanda** [comment]
@Yanchek99 Yup updated my [pen](http://codepen.io/IamManchanda/pen/QpgQWM) and you are right

Would you like to create a PR for this ??
Here is the guide => https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by Yanchek99** [comment]
@IamManchanda I can but I am not sure what should be included in this PR.  Looking through the scss it doesn't look like id selectors are used.   Do we need some kind of generic selector to get potential containers inside the top bar?  I don't think the following would be accepted. 
```
#responsive-menu {
    display: flex;
    flex: auto;
}
```

**Comment by IamManchanda** [comment]
cc @ncoden 

My 2 cents, 
You are seeing it as a id selector , but how i see it is 

```html
<div id="responsive-menu">
</div>
```

The problem lies that default css rules is giving `div` a `display: block`
What we can do here is 

https://github.com/zurb/foundation-sites/blob/develop/scss/_global.scss
```scss
div {
  @if $global-flexbox {
     display: flex;
     flex: auto;
  }
}
```

**Comment by kball** [comment]
Moving all divs to display flex is a very very large hammer and not what we want. And broadly, we should always target classes for styles, not elements or ids, for specificity reasons.

You can get the menu to behave as you want by giving it a `.flex-container` class... I'm not sure if there is actually a bug here or responsive nav in flex mode simply needs a better example. @rafibomb what do you think?

**Comment by IamManchanda** [comment]
No flex-container only adds `display:flex` and not `flex:auto` by which both top bar left and right are positioned into right

When 'flex:auto` its works as expected but still has a bug on mobile 
Reported here => https://github.com/zurb/building-blocks/pull/182#issuecomment-298813144

**Comment by kball** [comment]
@IamManchanda do you want to take a pass on fixing this?

**Comment by IamManchanda** [comment]
@kball @Yanchek99 
I think the current docs example and with some tweak to `top-bar-title` fixes this .... What you say ??

Current docs example (float) => https://codepen.io/IamManchanda/pen/LymroM?editors=1000
Example with Title bar tweaks (flex)  => https://codepen.io/IamManchanda/pen/OmBVZE?editors=1100

What you guys say ??

**Comment by Yanchek99** [comment]
I don't think I follow? This is an issue whenever I use the components. Am I understanding the fix to just be a fix on the foundations documentation? Looking at code pens i would expect the docs to mention the custom css needed for the responisve-menu?  Maybe I am not understanding the fix?

**Comment by IamManchanda** [comment]
I see it as "Docs didn't had the correct examples for the top bar that fits for both flexbox and float?

**Comment by Yanchek99** [comment]
I saw the issue being in the advanced top bar with responsive menu, which is discussed in the documentation here http://foundation.zurb.com/sites/docs/top-bar.html. 

Looks like the bug is still present in the latest foundation-sites. https://codepen.io/anon/pen/vxZWed

The Doc code examples posted seem to be using a top bar interchanged with a titlebar?

**Comment by IamManchanda** [comment]
@Yanchek99 Yes in latest because that PR is not been merged yet

If you Run my PR Locally, i have updated the docs example! 
https://github.com/zurb/foundation-sites/pull/10056

----------------------------------------------------------------------------------------------

I by mistake said .... current docs example 
I should have said current codepen example 
If you click this link => http://foundation.zurb.com/sites/docs/top-bar.html#advanced-layout
and click on edit in browser 
The codepen example is an updated one 
https://codepen.io/IamManchanda/pen/LymroM?editors=1000
