### ISSUE TITLE
Tooltips not show in reveal for touch devices

### ISSUE THREAD

**Issue by madbeyk** [zurb/foundation-sites#9872]
Tooltip in Reveal - Foundation 6.3.1
It works nicely for mouse hover, it's not working for touch.

On touch there is some error in calculation of width of tooltip 
_setPosition() in foundation.tooltip.js returns negative number for width,

I have removed overflow:hidden from @mixin foundation-reveal {html.is-reveal-open, html.is-reveal-open body} as a workaround ...

**Comment by IamManchanda** [comment]
Created a test case for your bug 
http://codepen.io/IamManchanda/pen/xqrYQb

If you solved it and have a workaround, please create a pull request 
Here is the guide => https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by JeremyEnglert** [comment]
This is working in 6.4.3. Testing on iPhone X using Browerstack.

Closing.
