### ISSUE TITLE
[Kitchen Sink] Accordion doesn't work

### ISSUE THREAD

**Issue by gmclelland** [zurb/foundation-sites#9876]
#### How to reproduce this bug:

1. Click on the second accordion item on http://foundation.zurb.com/sites/docs/kitchen-sink.html

#### What should happen:
The accordion should open

#### What happened instead:
Nothing happens

**Comment by IamManchanda** [comment]
Thanks for reporting .... Created a PR #9882

**Comment by kball** [comment]
Fixed in #9329
