### ISSUE TITLE
6.3.1 Flex-Grid nested row issue with where content blows out page even with overflow hidden.

### ISSUE THREAD

**Issue by NubSoup** [zurb/foundation-sites#9878]
Hey guys, after upgrading from 6.3.0 to 6.3.1 i am unable to fix a nested row issue i have around the new style added of " .row:not(.expanded) .row { max-width:none} ". This is causing 

#### How to reproduce this bug:

1. Create layout with nested rows
2. Add content in parent with overflow hidden that has larger width window.
3. See things break

#### What should happen:
Overflow hidden should be hiding the content inside it and not stretching out the page

#### What happened instead:
The larger width div is stretching out it's parent and containers.
#### Test case:

Basic Layout with basic CSS to showcase issue

Codepen with Foundation Flex-Grid 6.3.1 (broken layout) --> http://codepen.io/anon/pen/PpJRGj
Codepen with Foundation Flex-Grid 6.3.0 (good layout) -->  http://codepen.io/anon/pen/MpEVmL

**Comment by IamManchanda** [comment]
Here is the issue 

```scss
.row.expanded, .row:not(.expanded) .row {
    max-width: none;
}
```

**Comment by NubSoup** [comment]
@IamManchanda Sorry if i wasn't clear, but that is the issue i was referring to in the opening statement. I'm calling it out as a bug for layouts with content that need widths larger than container and overflow hidden. They just don't work with the max-width: none.

I couldn't find a work around using the class's available, because as long as you have a row in a row, it has no max-width.

**Comment by satyajit11** [comment]
use this class="row expanded page-wrapper" instead class="row page-wrapper"

[codepen](http://codepen.io/satyajit11/pen/yMELmb?editors=1000)

**Comment by kball** [comment]
The core issue is that you are including a row inside a row without any columns. This is not defined behavior... if you add a '<div class="columns"> between `.page-wrapper .row` and `#main-container` it works

**Comment by kball** [comment]
See this codepen which is the "broken" one adjusted with proper markup as mentioned above: http://codepen.io/kball/pen/jBRrxM

Closing this as invalid

**Comment by NubSoup** [comment]
@kball,
Thanks, i was under the impression that i could have multiple rows in a row to be able to define different types of layout without having to create to many extra html elements.

**Comment by kball** [comment]
@NubSoup there are definitely some complexity/verbosity issues with the current grid system. @brettsmason is working on a new grid system that should be simpler.
