### ISSUE TITLE
Outlook 2010 v14.0.7177.5000 width issue

### ISSUE THREAD

**Issue by mtjepson** [zurb/foundation-sites#9880]
In Outlook 2010 v14.0.7177.5000 on installed on 32 bit PC's there seems to be a width issue. Outlook ignores the set px based width which allows all nested tables set to 100% to expand to fit the Outlook viewing window.

#### How to reproduce this bug:

Open a template in Outlook 2010 v14.0.7177.5000

#### What should happen:

Contents within tables set at 100% should only expand to fit the container width.

#### What happened instead:

Contents ignore container width and expand to full width of Outlook viewing window.

#### Test case:

I can not replicate the issue in Litmus. It's client side. However it seems that that Outlook is ignoring the CSS width: declaration set on the container.

**Comment by Deckluhm** [comment]
This is the Foundation for Sites repository, you should reopen this issue in the [Foundation for Emails repo](https://github.com/zurb/foundation-emails).

And please provide some code that reproduces the issue, it helps a lot!

**Comment by Deckluhm** [comment]
Issue reopened [here](https://github.com/zurb/foundation-emails/issues/732).

This one can be closed.
