### ISSUE TITLE
subtree: true in eventsListener method is causing conflict

### ISSUE THREAD

**Issue by gpspake** [zurb/foundation-sites#9884]
I've submitted a [post](http://foundation.zurb.com/forum/posts/51612-change-in-63-eventslistener-breaks-jquery-transition-equalizer) about this on the Foundation Forum but not as many people will see it there and we're moving forward with a hard coded fix for this problem so I wanted to get it over here in case it is a genuine bug (and not just my crappy code 😉 ) .

#### How to reproduce this bug:
We have a navigation that uses equalizer in addition to jQuery slideDown. We're doing some kinda funky stuff for accessibility so it's not exactly straight forward (tl;dr: screen readers can't see stuff that's set to `display: none` and jQuery's slideDown relies on it so we basically copied foundation's undocumented `.invisible` styles so screenreader's can see it, then, on hover, reset invisible and set display to none right before triggering slidedown). You can see the navigation [here](http://uthsc.edu/) (It's the main green one that slides down when you hover)

#### What should happen:
The menu should slide down smoothly

#### What happened instead:
The menu jumps because of some event listener conflict that we've traced to the following line in [foundation.util.triggers.js](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.triggers.js)
`elementObserver.observe(nodes[i], { attributes: true, childList: true, characterData: false, subtree: true, attributeFilter: ["data-events", "style"] });`
In previous versions (<6.3.0), subtree has been set to false there and we fixed our issue by manually hardcoding subtree back to false before building (with no apparent side effects)

So the ultimate question here is: **"Does subtree need to be set to false?"**

I get that the idea is that "whenever the `data-events` or `style` attributes change in any node (or descendent node, hence subtree:true), the function `listeningElementsMutation` gets called" but, as far as I can tell, equalizer and other js components seem to work fine with it set to false.

This is pretty 'under the hood' so I'm curious to know if this has caused issues for anyone else and whether that [value was changed to true](https://github.com/zurb/foundation-sites/commit/e282a16626221a828ddcf3007ace9a3e9e3072cc) deliberately or because it was just the default when that line was refactored. cc @coreysyms

**Comment by kball** [comment]
So I believe subtree was set to true for the new mutation observer code... but @coreysyms would be interested in your thoughts here.

**Comment by coreysyms** [comment]
First, apologies for the delay in my response.
So the big thing with the subTree is the children changing of whatever node is listening for a change. It's really all in how people use it. I intentionally changed in subTree to "true". But these things come with only so much testing. I could make up some examples of an accordion nav block in a sticky right side rail that will bomb out if subTree is not true. But that is really where all this "real world" testing comes into play. Are people doing these kinds of things?

Im glad @gpspake made this post, cause it's not really a bug, as I don't think there is really anything to fix, but this convo should be marked for future discussion on whether Foundation is "doing to much for the coder". It's something I struggled with, with mutation events, it is a fine line. I can assure you that as more people test, "IE build things and report things" the better this will get, and maybe the better version of mutation observers, is without listening to its children.

**Comment by gpspake** [comment]
Thanks for the response! Makes sense. How about this, then... if I _did_ want to set that value to false on a per project basis, what would the the best approach be? Because right now it's hardcoded which is a little too fragile for comfort. If somebody updates and rebuilds without taking this in to consideration, it will be overwritten. So, this might just be a js question, but is there a mechanism in place for setting those values outside of foundation core so that they aren't lost down the road?

**Comment by coreysyms** [comment]
There is no setting for triggers, but triggers is its own js file, so you could compile the js files you needed for your particular install with one “set aside” triggers js file.

**Comment by JeremyEnglert** [comment]
Looks like this was fixed in 6.3.1. Please reopen if this is now the case.
