### ISSUE TITLE
nesting rows inside expanded row

### ISSUE THREAD

**Issue by mrYakamoto** [zurb/foundation-sites#9886]
#### How to reproduce this bug:

1. Step one
create a div with class 'row expanded'

2. Step two
nest a div with class 'row' inside and then another div with class 'row' inside of that one. 

3. Step three
observe that content doesn't align.

#### What should happen:
users should have ability to expand rows nested inside of expanded rows to full width of previous row.

#### What happened instead:
padding compounds and rows nested inside an expanded row don't align.

#### Test case:
-[Click here for CodePen illustrating the issue](http://codepen.io/mryakamoto/pen/zZWBja)

**Comment by gpspake** [comment]
You can use `.collapse` on rows to get rid of that padding 😄 
[codepen](http://codepen.io/gpspake/pen/zZWNWj)
[collapse docs](http://foundation.zurb.com/sites/docs/grid.html#collapse-uncollapse-rows)

**Comment by satyajit11** [comment]
you can use row instead of column in your code to get rid of space

<div class="row expanded outer">
  <div class="row">
    <h2>Expanded Row</h2>
    <div class="row">
      <div class="row">
        <h3>nested row</h3>
          <div class="row">
            <div class="row">
              <h4>second nested row</h4>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

**Comment by gpspake** [comment]
@satyajit11 You get the same [result](http://codepen.io/gpspake/pen/jBKEVm?editors=1100) if you just delete the .columns divs that you changed, so changing them to .row is redundant. It also results in the same problem with using `collapse`; you lose your outer padding in the nested expanded rows.

**Comment by satyajit11** [comment]
try this it will fix padding issue
[codepen](http://codepen.io/satyajit11/pen/PpaoyM?editors=1000)

<div class="row expanded outer">
  <div class="column">
  
    <h1>Expanded Row</h1>
    <div class="row expanded">
      <div class="column">
        <h2>nested row</h2>
          <div class="row expanded">
            <div class="column">
              <h3>nested expanded row</h3>
            </div>
          </div>
      </div>
    </div>
  
  </div>
</div>

**Comment by gpspake** [comment]
@satyajit11 That looks like a different use case. He wants to nest expanded rows in a contained row in an expanded row but, if you do so, the outer padding isn't applied to the nested expanded rows.
In your example, which is correct albeit for a different use case, all of the nested rows are expanded to full width.

**Comment by JeremyEnglert** [comment]
Looks like an answer was provided for this. Closing.
