### ISSUE TITLE
Accordion Example is not working. 

### ISSUE THREAD

**Issue by ercmert** [zurb/foundation-sites#9894]
Your “Accordion” example component on your kitchen sink page is not working. I’m on a Mac with the current version of Chrome.

http://foundation.zurb.com/sites/docs/kitchen-sink.html

**Comment by dragthor** [comment]
Pull request https://github.com/zurb/foundation-sites/pull/9882 fixes this.

Dupe of https://github.com/zurb/foundation-sites/issues/9876

**Comment by IamManchanda** [comment]
@ercmert i think you should close this buddy ... cheers .... thanks a lot for reporting though!!

**Comment by kball** [comment]
This has been fixed
