### ISSUE TITLE
Pagination doesn't work properly

### ISSUE THREAD

**Issue by ivancp** [zurb/foundation-sites#9895]
Hello,
I'm using Foundation 6.3.1, according to documentation the pagination have disable status using class 'disabled', but when I try remove I have estrange behavior.
#### How to reproduce this bug:

1. Use the regular sample in http://foundation.zurb.com/sites/docs/pagination.html
2. Remove the 'disabled' from `<li>` with 'pagination-previous' and add 'disabled' to `<li>` with 'pagination-next'.

#### What should happen:
The prev label must preserve the left arrow indicator and the next label must be disabled.

#### What happened instead:
The result is: the prev label loss the left arrows and the next label still available and it is not grayed.

#### Test case:

https://jsfiddle.net/ivancp/he7vssqx/

**Comment by kball** [comment]
Looking at the example, test case posed, I believe this is an error in the markup... the issue is in the placement of the links. When you remove disabled, you need to add the link inside, and when you add disabled you should remove it.  See this updated fiddle: https://jsfiddle.net/zbo5usaw/

**Comment by ivancp** [comment]
Thank you
