### ISSUE TITLE
.shrink Behaviour on nested column.row on flexbox 6.3.1

### ISSUE THREAD

**Issue by BicanMarianValeriu** [zurb/foundation-sites#9901]
#### How to reproduce this bug:

```
<div class="row">
<div class="column row">
  <div class="column shrink show-for-small-only">
  </div>
  <div class="column">
  </div>
  <div class="column shrink show-for-small-only">
  </div>
</div>
<div class="column">
</div>
</div>
```

#### What should happen:
Shrink should "shrink" the column

#### What happened instead:
Column is expanded to full width

#### Test case:

Here is with Foundation Flexbox 6.3.1
Change the CSS to 6.3.0 and see how it worked!

https://codepen.io/wecodeart/pen/KWBZRm

**Comment by BicanMarianValeriu** [comment]
Also resize the window for small screens to see what I'm talking about.

**Comment by kball** [comment]
@canterberrie can you take a look at this?

**Comment by BicanMarianValeriu** [comment]
Found a problem here:
```
.column.row.row, .row.row.columns {
    float: none;
    display: block; /*here should be flex*/
}
```

**Comment by kball** [comment]
@BicanMarianValeriu a row that is also columns is currently very deliberately set to display block. See the discussion here: https://github.com/zurb/foundation-sites/issues/9857#issuecomment-294941227

**Comment by canterberrie** [comment]
@BicanMarianValeriu If you take a look at this example: https://codepen.io/canterberrie/pen/wdMYJX?editors=1100
.shrink columns are working as expected inside of a .row.column

In your original example you have a .row nested directly inside of a .row, and a .column directly inside of a .column, which is incorrect use of the grid. Going to close this issue, but if have a good use case for using the grid this way we can reopen it.
