### ISSUE TITLE
drilldown-menu auto-height conflict with dynamic back button.

### ISSUE THREAD

**Issue by vikks** [zurb/foundation-sites#9902]
hi, 
i am trying to implement a dymanic back link(i.e., display the parent-link of the opened submenu instead of the standard static link with '< back' text).

```html
<ul class="drillmenu vertical menu" data-drilldown data-auto-height='true' data-parent-link='true'>
  <li>
    <a href="#Item-1">Item 1</a>
    <ul class="vertical menu">
      <li><a href="#Item-1A">Item 1A</a></li>
      <!-- ... -->
    </ul>
  </li>
  <li><a href="#Item-2">Item 2</a></li>
</ul>
```
This is the hack i am using to achive the dynamic back button.
```coffeescript
$('.drillmenu').on 'open.zf.drilldown', (context) ->
    target = $(context).attr('target')
    back_text = $(target).find("[aria-expanded='true']").find(".is-submenu-parent-item a").text()
    $(target).find("[aria-expanded='true']").find(".js-drilldown-back a").text(back_text)
    $(".is-submenu-parent-item").hide()
```
Event with  the  above hack "open.zf.drilldown" event does not fire when the page loads with an already active menu-item.

Is there something much cleaner to achieve the above goal?

**Comment by atomeon** [comment]
i thought  data-parent-link='true' should automatically resolve this problem, but it only adding list element to submenu with parent _name_ and it's not clickable.

**Comment by JeremyEnglert** [comment]
We'll look into ways to natively support this in F7.
