### ISSUE TITLE
[Dropdown Menu] latest Chrome doesnt fire top links

### ISSUE THREAD

**Issue by Geddo** [zurb/foundation-sites#9903]
#### How to reproduce this bug:
1. Install latest Chrome 57.0.2987.110 (64-bit)
2. Go to http://foundation.zurb.com/sites/docs/dropdown-menu.html
3. Click on the top-nav links on the right (Showcase, develop etc.)

#### What should happen:
Top links should be fired (as they do in Chrome 56)

#### What happened instead:
nothing, you have to double-click the link to fire the event

#### Test case:
http://foundation.zurb.com/sites/docs/dropdown-menu.html

**Comment by phifa** [comment]
same here... all my foundation sites have this issue now. is this a chrome bug?

**Comment by Geddo** [comment]
afaik Foundation has this double-click feature built-in for mobile devices to show submenus with the first "tap" AND the possibility to click on the top menu-links with another "tap" - but that should accutally only be enabled for mobile devices ;-)

**Comment by Geddo** [comment]
same problem in 58.0.3029.41 beta (64-bit) :-(

**Comment by phifa** [comment]
it is the same in firefox: try the top bar here: http://foundation.zurb.com/

**Comment by Geddo** [comment]
True, but Firefox ESR (45) is not affected btw. Anyway here is a fix for my problem (thansk to Phifa):
`var navButton = $('.nav__dropdown .is-dropdown-submenu-parent a');
navButton.on('click', function() {
   if (whatInput.ask() === 'mouse') {
      var myLink = $(this).attr("href");
      window.open(myLink,"_self");
  }
});
`

**Comment by kball** [comment]
I'm confused... the links mentioned above show on hover in desktop, and don't show at all on mobile... can you clarify what you're seeing and how to reproduce?

**Comment by JeremyEnglert** [comment]
This no longer appears to be an issue.
