### ISSUE TITLE
[Abide] checkbox validation is not working 

### ISSUE THREAD

**Issue by sunnymesa** [zurb/foundation-sites#9905]
#### How to reproduce this bug:

1. Step one
    click "submit" button, to show error
2. Step two
    enter all the required field shown in error, but in checkbox, do not click the red highlighted checkbox, click "submit" it will still show error
3. Step three
    then click the red highlighted checkbox, submit then would work.
#### What should happen:
    click any checkbox should make error disappear
#### What happened instead:
   intead, only required checkbox has to be checked, this is incorrect.
#### Test case:
    

https://codepen.io/Akarienta/pen/xbXmJw?editors=101, show the behavior, I thought it was fixed in 6, but demo did not work.
- [CodePen with Foundation 6.2.4 and MotionUI](https://codepen.io/ncoden/pen/gLEoEB)
- [CodePen with Foundation 6.2.4, Flexbox grid and MotionUI](https://codepen.io/ncoden/pen/yVwpZN)

- [CodePen with Foundation 6.3.0 and MotionUI](https://codepen.io/ncoden/pen/oYVpMe)
- [CodePen with Foundation 6.3.0, Flexbox grid and MotionUI](https://codepen.io/ncoden/pen/qqvpQj)

**Comment by hikouki** [comment]
Fixed?

It works as follows:
https://codepen.io/anon/pen/dRgWmq

**Comment by JeremyEnglert** [comment]
Looks like this has been fixed. Closing.
