### ISSUE TITLE
Gmail application iOS/Android

### ISSUE THREAD

**Issue by defuzer** [zurb/foundation-sites#9906]
I just added to outlook 2016 sample template: order.html

And see what happens with space between text (Order details). Only on GMAIL app.
![unnamed](https://cloud.githubusercontent.com/assets/1432683/24372838/9a729082-132f-11e7-97f8-9516a1cc2093.jpg)

**Comment by IamManchanda** [comment]
Seems like this regarding foundation for emails 

If yes then please close this and move the issue to https://github.com/zurb/foundation-emails
