### ISSUE TITLE
Create new instance Asynchronous

### ISSUE THREAD

**Issue by stephane-r** [zurb/foundation-sites#9909]
Hi community :)

I would like programmatic use sticky component but asynchronous.
If i run new instance synchronously, the component has been init :

`const sticky = new Foundation.Sticky($('.sticky'));`

But with setTimeout, sticky component isn't init :

```
setTimeout(() => {
  const sticky = new Foundation.Sticky($('.sticky'));
}, 2000);
```

Do you know if is problem with configuration or a bug ?

Thank you community !

#### Test case:

- [CodePen with Foundation 6.3.0](https://codepen.io/anon/pen/pexyOL)

**Comment by DanielRuf** [comment]
This should be already fixed.
See https://codepen.io/DanielRuf/pen/ZEzeJzR
