### ISSUE TITLE
[V5] Topbar Chrome Js Error

### ISSUE THREAD

**Issue by dragthor** [zurb/foundation-sites#9910]
We' ve been seeing this issue in Chrome consistently over the past 15 days.

![v5chrome-error](https://cloud.githubusercontent.com/assets/156634/24422970/6af2d462-13c9-11e7-942a-db07d5d6458a.PNG)

Chrome breakdown:

![v5chrome](https://cloud.githubusercontent.com/assets/156634/24422940/4d13ffb6-13c9-11e7-9be4-effc5e75254f.PNG)

It can be difficult to reproduce, but if you reload a page with a `topbar` enough times you will see the error in the `console`.  The error is within the `resize` event.

Resolution: Pull request coming soon.

**Comment by dragthor** [comment]
Chrome 57.0.2987 released around the same time.

**Comment by JeremyEnglert** [comment]
Looks like a fix for this was merged.
