### ISSUE TITLE
[Tabs] Incorrect use of aria-hidden attribute

### ISSUE THREAD

**Issue by mmieluch** [zurb/foundation-sites#9913]
Visibility of individual tabs is controlled by leveraging the value of the `aria-hidden` attribute. In the current version (`6.3.0`) a tab content container is visible only if it has a `aria-hidden="false"` attribute, which represents an incorrect use of a boolean attribute.

According to the [spec](https://www.w3.org/TR/html5/infrastructure.html#boolean-attributes) all of these should be interpreted as _truthy_:
```html
aria-hidden="true"
aria-hidden="false"
aria-hidden="aria-hidden"
```

For the attribute to be _falsy_, it'd have to be either removed or:

```html
aria-hidden=""
```

Therefore the CSS rule for tabs' panels is invalid:

```CSS
.tabs-panel[aria-hidden="false"] {
  display: block;
}
```

As stated on W3C [website](https://www.w3.org/TR/wai-aria/states_and_properties#aria-hidden):

> Note: Authors are advised to avoid using aria-hidden="false" with styles or attributes that have historically prevented rendering in all modalities, such as display:none or visibility:hidden in CSS, or the hidden attribute in HTML 5. At the time of this writing, aria-hidden="false" is known to work inconsistently when used in conjunction with such features.

**Comment by IamManchanda** [comment]
Thanks .... created a PR fixing this #9916

**Comment by mmieluch** [comment]
Nice work, cheers!
