### ISSUE TITLE
Foundation 6 Sticky element in Angular2

### ISSUE THREAD

**Issue by tschaka1904** [zurb/foundation-sites#9919]
#### How to reproduce this bug:
I'm using Foundation 6.2.4. I'm trying to make Foundations Sticky work in my Angular2 application.  I struggle with the Sticky element in general. What I have is this:
### Component Template
```
<div id="wrapperDiv">
        <div class="columns medium-2 no-pad-left" data-sticky-container>
          <div id="myStickyElement" class="sticky" data-sticky data-top-anchor="wrapperDiv">
            <aside>
              <ul class="menu vertical">
                <li><a href="#elm1">Elm1</a></li>
                <li><a href="#eml2">Eml2</a></li>
                <li><a href="#eml3">Eml3</a></li>
                <li><a href="#eml4">Eml4</a></li>
              </ul>
            </aside>
          </div>
        </div>
</div>
```
It might be important to say that wrapperDiv is loaded directly and has no ngIf condition in it's parents.
In my component I use this in my ngAfterViewInit:
### Component
```
 ngAfterViewInit(): void {
    $('#myStickyElement').foundation();
  }
```
When I do a full page reload on this specific view, everything is super and works! If I navigate to this view, it it doesn't work. Seems to be related with the full page reload

On some point I was creating the Sticky element like this:
`let myStickyElement = new Foundation.Sticky($('#myStickyElement'));
`
Which did not have any impact on the behaviour, but I could print out the object myStickyElement.

On full page reload the object looks like this: 
[Object on full page reload](https://i.stack.imgur.com/0tVLg.png)

And here if I navigate to the page:
[Object if you navigate to page](https://i.stack.imgur.com/scRqw.png)

As you can see, the object of myStickyElement looks way different. Something is missing.

#### What should happen:
It should work always. The sticky element should respond to the`$('#myStickyElement').foundation();`
#### What happened instead:
It only work on a full page reload and not if I navigate to that page/entry. I've tried to execute `$('#myStickyElement').foundation();` in the console, but it didn't make any difference. Also I've tried to execute `$('#myStickyElement').foundation('_calc', true);`, which first didn't make any difference. But once I scroll a bit down and execute `$('#myStickyElement').foundation('_calc', true);` again it work. Kind of.. :( It the sticky element follows my scrolling, but when I go back to the top it doesn't stop at its anchor.

**Comment by rafibomb** [comment]
Thanks for the report! There is already an issue open for this here: https://github.com/zurb/foundation-sites/issues/9047

Please add any suggestions or supporting details there. Closing this one in favor of https://github.com/zurb/foundation-sites/issues/9047
