### ISSUE TITLE
Interchange (destory/update/reInit)

### ISSUE THREAD

**Issue by artursopelnik** [zurb/foundation-sites#9920]
What's up with destory method?
[foundation-sites/js/foundation.interchange.js | line 176
](https://github.com/zurb/foundation-sites/blob/develop/js/foundation.interchange.js)
I try to (reInit/update) my interchange with `Foundation.reInit` but it also fails. What are the possibilities?

**Comment by JeremyEnglert** [comment]
Can you provide a CodePen example with what you're trying to do? i'll be happy to reopen this ticket.
