### ISSUE TITLE
Against #9596: System Font Stacks @font-face

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9922]
This affirmation is against (my own affirmation) #9596 which was merged here => #9644 

https://css-tricks.com/snippets/css/system-font-stack/#article-header-id-2

> The limitation of the [first method](https://css-tricks.com/snippets/css/system-font-stack/#article-header-id-1) is that you have to call the full stack of fonts each time it's used on an element and that can get cumbersome and bloat your code, depending on where and how it's used.
> 
> Jonathan Neal offers an [alternative method](https://github.com/jonathantneal/system-font-css/blob/gh-pages/system-font.css) where system fonts are declared using @font-face.

Biggest benefit of the below code i feel is that designers/developers can use this in **simple css** instead of using sass for such tasks,
and thus can be used in css-only projects also!

```scss
body {
  font-family: "system";
}
```

Please Note that @jonathantneal's full example illustrates the capability to define variations of the system font family to account for italics, bolding, and additional weights.
=> https://github.com/jonathantneal/system-font-css/blob/gh-pages/system-font.css

**Comment by IamManchanda** [comment]
https://jonathantneal.github.io/system-font-css/

> **Is system going to be a thing?**
> Maybe. There are [discussions in the W3C](https://lists.w3.org/Archives/Public/www-style/2015Jul/0169.html) to standardize a generic system family.
>> **Apple proposes adding a new generic font-family named "system".**
> >
> > ```scss
> > body {
> >   font-family: "system";
> > }
> > ```

**Comment by IamManchanda** [comment]
Poke @kball @brettsmason !

**Comment by JeremyEnglert** [comment]
We'll discuss this for F7.
