### ISSUE TITLE
Reinitialize Plugin after PJAX load

### ISSUE THREAD

**Issue by CGTS** [zurb/foundation-sites#9924]
I have a reveal modal that contains a menu. When I click on a menu item it loads a new page using BarbaJS . The problem is the page loads, but the reveal stays open. When I close it, it won't reopen. I tried to trigger a close on a new page load but I get an error message. I've used the following: 

```
Barba.Dispatcher.on('newPageReady', function() {
  $('[data-reveal]').foundation('close');
});
```

I also tried

```
Barba.Dispatcher.on('transitionCompleted', function() {
  $('[data-reveal]').foundation('close');
});
```

Both times I get the following error:

```
foundation.core.js:281 Uncaught (in promise) ReferenceError: We're sorry, 'close' is not an available method for this element.
```

When I try to reinitialize with 

```
Foundation.reInit('reveal');
```

I get this error 

```
TypeError: Cannot read property '_init' of undefined
```

Any ideas on how to fix this? I tried the same thing for a sticky header and got the same result.

**Comment by CGTS** [comment]
I got the reveal to close by reinitializing foundation:

```
Barba.Dispatcher.on('transitionCompleted', function(currentStatus) {
  $(document).foundation();
});
```

of course now that it is re-initializing `foundation` I get a message like this:
``
Tried to initialize accordion-menu on an element that already has a Foundation plugin.
```
for all the plugins I have on a page. This is expected. Is there a way to get around this?

**Comment by phifa** [comment]
see https://github.com/zurb/foundation-sites/issues/9047

**Comment by CGTS** [comment]
Thanks. I've decided not to move forward with Barba for now so ill close this.

**Comment by phifa** [comment]
@cgts may I ask why? Because I wanted to try it out, since it is vanillajs without dependencies. And the Ajax issue with foundation has nothing to do with barba or smoothstate.

**Comment by CGTS** [comment]
@phifa There was nothing wrong with Barba. I know very little javascript and had a limited amount of time to push this project out. I found that I was running into issues like modal windows being re-added (without being removed) whenever they were used. I'm sure these issues could have easily been overcome by anybody who know JS, I just didn't have the time to come up to speed. 

I would definitely recommend it if you know JS.

**Comment by kball** [comment]
@cgts without having a repro case it's hard to say for certain, but my guess is that since you were targeting globally `[data-reveal]`, you were also getting some reveal elements from the NEW page that had not yet been initialized, and that is why you were seeing the error.

**Comment by iamrobert** [comment]
This example here the project owner supplies is useful:
https://plnkr.co/edit/wfgMT7kbvX3mhoGDggli?p=preview

This example ZF6 appears to be working with barba.js - though haven't tested extensively yet.

```javascript
document.addEventListener("DOMContentLoaded", function() {
	pageInit(document);
	//BARBA	INIT
	Barba.Pjax.start();
	Barba.Prefetch.init();
	
	//AFTER PAGE INIT
	Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container, newPageRawHTML) {
		pageInit(container);
	});

	function pageInit(scope) {
		// Init Foundation Plugins
		$(scope).foundation();
	}
	//END DOMContentLoaded
});
```
