### ISSUE TITLE
search when nothing found

### ISSUE THREAD

**Issue by LGT4** [zurb/foundation-sites#9928]
When the search widget entry leads to nothing found  https://domain.com/?s=nothing  then the search widget should not display.  Otherwise you end up with 2 search boxes.

**Comment by IamManchanda** [comment]
@LGT4 Test case please. 
You can fork from these below pens for creating a test case 

- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

**Comment by Deckluhm** [comment]
What "search widget" are you talking about?

**Comment by IamManchanda** [comment]
yup @Deckluhm even i am confused :D

**Comment by LGT4** [comment]
see attached.  The no results template has a search bar.  It duplicates the right side bar search widget.  There is no need for a search bar in the no results template. 

[Search Results for “something real” – FoundationPress.pdf](https://github.com/zurb/foundation-sites/files/894576/Search.Results.for.something.real.FoundationPress.pdf)

**Comment by Deckluhm** [comment]
FoundationPress isn't a ZURB project.

Here is the repository you are looking for: https://github.com/olefredrik/FoundationPress

**Comment by Deckluhm** [comment]
Issue reopened [here](https://github.com/olefredrik/FoundationPress/issues/970).

This one can be closed.
