### ISSUE TITLE
What is the cause of difference between “Complete” version and “Custom version” with “All Foundation Components”?

### ISSUE THREAD

**Issue by Mojtaba-Reyhani** [zurb/foundation-sites#9934]
Is there any difference between `"Complete"` version (In the top section close to the "Essential", "Custom" and "Sass" link) and `"Customize Foundation/custom version"` with `"All Foundation Components"`in [Foundation download page][1]?<br>

See below images:<br>
[![enter image description here][2]][2]<br>
 **With**:<br>
[![enter image description here][3]][3]<br>

I want to download the latest version of foundation 6+ completely with full components of it, but it seems there are many differences between these two versions only in `LTR` Languages without considering the `RTL` matter (for example in style of buttons and width of rows and etc).<br>

Button style in **Complete** version:<br>
[![enter image description here][4]][4]

and that button in **Custom** version:<br>
[![enter image description here][5]][5]

As you can see the `background-color` and `color` (text-color) and `border-radius` are different, But both of them are in RTL (6.3.1) version.<br>

Note: I compared those versions and tested both `LTR` versions. 

I will be grateful if anyone explain the cause of difference between those versions and explain which one of them is more complete and reliable?

  [1]: http://foundation.zurb.com/sites/download.html/
  [2]: https://i.stack.imgur.com/2L7R9.png
  [3]: https://i.stack.imgur.com/qVQS2.png
  [4]: https://i.stack.imgur.com/RFkOO.png
  [5]: https://i.stack.imgur.com/PCKmn.png

**Comment by siddharthashok** [comment]
![screen shot 2017-04-19 at 3 46 25 pm](https://cloud.githubusercontent.com/assets/3031704/25175175/72c7c512-2517-11e7-89ed-02a255714108.png)

@Mojtaba-Reyhani Custom version is based on the settings and components you have selected in the form http://foundation.zurb.com/sites/download.html/#customizeFoundation

**Comment by Mojtaba-Reyhani** [comment]
@siddharthashok: Thank you so much for your help and reply, You are right.

**Comment by Owlbertz** [comment]
@Mojtaba-Reyhani I consider this one as solved. If there are any additional questions, please re-open.
