### ISSUE TITLE
Foundation Docs - Sticky Search Bar

### ISSUE THREAD

**Issue by denisahac** [zurb/foundation-sites#9935]
Well, to start, though it might not be a big deal for most users of the framework. But, I find it very difficult to navigate when I'm at the bottom at the page(e.g. Sass reference/Javascript reference section), then I'm about to look for a plugin options or something that is on another page(In this case, I know what Sass component/Javascript module to look for).

It would be very helpful if the search bar sticks to the top when you start to scroll, in that way it is always accessible without having to scroll back to the top to search for modules/components. I find it very frustrating when you're actually at the bottom of the page, then scroll back to the top to search.

Let me know what you guys think.

**Comment by IamManchanda** [comment]
+1

**Comment by denisahac** [comment]
I love the new Foundation for Sites docs. Awesome work guys. Closing this.

**Comment by IamManchanda** [comment]
Thank you
