### ISSUE TITLE
[Component Request] Add missing List Groups!

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9938]
We miss this component => https://v4-alpha.getbootstrap.com/components/list-group/

**Comment by orangedaisy** [comment]
How is this "missing"? Foundation hasn't had this component, afaik.

Why does Foundation have to have feature-parity with Bootstrap?

**Comment by IamManchanda** [comment]
> Why does Foundation have to have feature-parity with Bootstrap?

@orangedaisy That is not what i am talking about 

The reason i added this request because this group component of a component 

We have: 
- Buttons & Button Group
- Input & Input Group
- Lists & ____ ??

Also, 
We have accordions too => http://foundation.zurb.com/sites/docs/accordion.html#all-closed
of which codebase can be used

**Comment by IamManchanda** [comment]
**How i detected this?** 
Well I am doing a Angular 4 course at [udemy](https://www.udemy.com/the-complete-guide-to-angular-2/learn/v4/) .... although the course uses bootstrap but i challenged myself to use foundation instead
and there i am making a recipe book app 
and this is used there in ShoppingListComponent & RecipeListComponent
where data is outputted to a list group ( design )

As there was no component for the same in foundation .... 
i had to make my own component for the same!
And that is why i said that "**We miss this component**" and asked for the feature

**Comment by orangedaisy** [comment]
> As there was no component for the same in foundation ....
i had to make my own component for the same!
And that is why i said that "We miss this component" and asked for the feature

It's okay to make additions in personal projects, you know. Foundation doesn't need to have a version of every conceivable UI component.

> * Buttons & Button Group
> * Input & Input Group
> * Lists & ____ ??

Lists are already groups.

```
.button-group     # group wrapper
  button
  button
  button

.input-group     # group wrapper
  input.input-group-field
  .input-group-button
    button

ul     # group wrapper
  li
  li
  li
```

If you absolutely have to have a list group, the general idea can be achieved with the existing card component and one extra style rule: http://codepen.io/reverendgeneral/pen/gWYbaB?editors=1100

![list-group](https://cloud.githubusercontent.com/assets/8375612/24890714/78422b06-1e3f-11e7-83be-e2de0e8f376c.png)

**HTML**
```html
<div class="row columns">
  <ul class="card">
    <li class="card-section">"List Group" Item 1</li>
    <li class="card-section">"List Group" Item 2</li>
    <li class="card-section">"List Group" Item 3</li>
  </ul>
</div>
```

**CSS**
```css
.card-section + .card-section {
  border-top: 1px solid #e6e6e6;
}
```

**Comment by IamManchanda** [comment]
Closing this as added in building blocks !
