### ISSUE TITLE
[Feature/Mainly Docs Update] Hamburger Menu - Desktop (Add support)

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9939]
Not fully sure whether a feature request or just a docs update

But,
Hamburger menu's are becoming more popular than ever!

and I think this should not cause big trouble coz thanks to @brettsmason,
We have a very good [offcanvas](http://foundation.zurb.com/sites/docs/off-canvas.html)!  
and yes this [mixin](http://foundation.zurb.com/sites/docs/sass-mixins.html#hamburger) too 

------------------------------------------------------------------------------------------------------------------------

**Update:** As @orangedaisy misunderstood, I want to clear a misconception .... this Feature request is not for the foundation docs site to have a hamburger menu on desktop!!! I am sorry if anyone of you all misunderstood the same. I am talking about the core framework

**Comment by orangedaisy** [comment]
Popular != useful. What do we gain by hiding the sidebar navigation?

**Comment by IamManchanda** [comment]
Hamburger menu is widely used these days even in desktop sites 

For example 
http://citruslabsthemes.com/themes/janus/home-hidden-menu.html
http://demos.creative-tim.com/rubik-agency

**Comment by orangedaisy** [comment]
That doesn't answer the question.

> Popular != useful. What do we gain by hiding the sidebar navigation?

This isn't a marketing site; it's a documentation site. Having all of the navigation links visible gives the user a sense of the size and complexity of the project, as well as immediate access to any items they need. Hiding these items wouldn't improve the user experience; in fact, forcing the user to open a large menu _and_ wait for an animation to complete before they can navigate is annoying and unnecessary flourish.

**Comment by IamManchanda** [comment]
@orangedaisy That open close menu is requested at outside of the core => motion ui ..... These animation's  doesn't have to do anything with foundation core!

**Comment by IamManchanda** [comment]
> This isn't a marketing site; it's a documentation site

@orangedaisy i want to clear misconception .... i am not asking for a docs update to have a hamburger menu on desktop ..... No!!! I am sorry if you misunderstood that!

I am asking for a feature request for hamburger menu on desktop 
The examples i showed you is for the foundation framework (and motion ui) 
not for foundation docs!

**Comment by orangedaisy** [comment]
Gotcha.

So are you talking specifically about an off-canvas menu that takes up 100% of the screen width and height?

**Comment by IamManchanda** [comment]
@orangedaisy Not really (Though i would like ) .... but forget the third example for time being

What my focus is first two 
1. In my first example, there is hamburger menu which open normal top bar 
=> http://citruslabsthemes.com/themes/janus/home-hidden-menu.html
=> Normal Top bar, obviously is already there ... what we are lacking is an hamburger menu to open close

2. In my second example , there is hamburger menu which opens close off canvas on desktop too
=> http://demos.creative-tim.com/rubik-agency
=> We have this offcanvas, but that's for small screens ..... and what we are lacking is desktop screens 

------------------------------------------------------------------------------------------------------

I dont think that 3rd example makes the headline to the core so leave it (100% of the screen width and height?)

**Comment by orangedaisy** [comment]
I believe Foundation already has all the necessary pieces for you to put this together without creating something brand new.

What you need for your first example isn't strictly a "hamburger menu," you need the [Toggler](http://foundation.zurb.com/sites/docs/toggler.html), a [Menu](http://foundation.zurb.com/sites/docs/menu.html), a hamburger icon, and a close icon. That's it.

For the second, the off-canvas component works perfectly well on desktop screens. The documentation site mirrors the functionality in the sample you linked. If you want an off-canvas menu that covered 100% of the screen, you should be able to get there by modifying some settings.

I would implore you dive deeper into the tools a little more before asking others to invent something new. I'm fairly confident you can do all of these things with what Foundation already has.

**Comment by orangedaisy** [comment]
Couldn't resist doing the first example. http://codepen.io/reverendgeneral/pen/zwOLyG?editors=1000

**Comment by IamManchanda** [comment]
@orangedaisy that's why i said it is mainly a docs update ( by which i meant that docs needs to be updated on how to do it )

Also, i have dived deeper already .... i know we have these bits and pieces of this already covered and primarily a docs update!

**Comment by JeremyEnglert** [comment]
It's documented here: http://foundation.zurb.com/sites/docs/responsive-navigation.html#responsive-toggle

"By default, the title bar will be visible on small screens, and the Menu hides. At the medium breakpoint, the title bar disappears, and the menu is always visible. This breakpoint can be changed with the data-hide-for attribute in HTML, or the hideFor setting in JavaScript."

**Comment by orangedaisy** [comment]
The off-canvas component also already functions exactly as shown in the provided example. http://foundation.zurb.com/sites/docs/off-canvas.html

**Comment by IamManchanda** [comment]
Ohk great @JeremyEnglert @orangedaisy
