### ISSUE TITLE
[Query] Gulp - Why don't we use gulp auto loader

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9940]
Looking at the code, 
I wonder, why don't we use [Gulp Auto Loader](https://www.npmjs.com/package/gulp-load-plugins) ?

I think code should be as leaner as it can get, 
so why dont we use it?
Is there any specific reasons around it ??

**Comment by JeremyEnglert** [comment]
Lets discuss this for F7.
