### ISSUE TITLE
Dropdown causing horizontal scrollbar

### ISSUE THREAD

**Issue by mitja-p** [zurb/foundation-sites#9945]
#### How to reproduce:
1. Add a dropdown on the right side of the webpage (float:right will do)
2. Open and close it
3. Resize to smaller width

On smaller browser width sometimes even default dropdown position causes a horizontal scrollbar.

#### Example (borrowed from another issue):
http://codepen.io/tw42/pen/dNEvOJ
1. Just resize to smaller width and notice the empty space on the right.
2. Click the right most button to open and close the menu on desktop width. Now resize to make it mobile width. Horizontal scrollbar appears, because dropdown is only visibility:hidden and therefore stays on the right. Dropdown should move to the left when closed so it does not cause the scrollbar to appear.

#### Partial workaround for one part of the issue:
CSS: 
`// Initially move dropdown to the left and set max width to 100%`
`.dropdown-pane:not(.is-open){`
`  left: 0px; // do not set !important as it won't work on larger screens`
`  max-width: 100%;`
`}`
Problem of opening a dropdown on larger screen and resizing to smaller size still remains.

**Comment by mitja-p** [comment]
Another side effect. When opening the dropdown, the dropdown gets moved to multiple positions to find a position that fits the available space. However on Android (also desktop Chrome in mobile development mode) this causes the page to scroll up. You can try manually settings dropdown element left value to 1500px and then 10px and see the effect.

**Comment by kball** [comment]
Overflow/scrollbar issue should be fixed by #10049, which will be in both 6.4 and 6.3.2. Positioning improvements are also coming for 6.4 with #10053
