### ISSUE TITLE
Foundation 5.2.2 : TypeError: Cannot read property 'css' of undefined

### ISSUE THREAD

**Issue by sanjay-russmediatech** [zurb/foundation-sites#9951]
Hello, 
I'm posting an error for old version so, first of allow me please.
My foundation version is 5.2.2.
I have implement reveal in my project and find a very weird issue. Some time I got the TypeError: Cannot read property 'css' of undefined. Refer the attached screenshot
![error](https://cloud.githubusercontent.com/assets/7358566/25001935/51e1962c-2065-11e7-8fc7-aeba3850ad02.png). Because of this error reveval modal is not opening.
It would be helpful if someone help me.

I'm not in a stage to update foundation framework. so, please don't suggest that.

Regards,
Sanjay

**Comment by Deckluhm** [comment]
You need to provide more than screenshot if you want people to help you.

Can you reproduce the error in a CodePen?

**Comment by sanjay-russmediatech** [comment]
@Deckluhm Thanks for your suggestion but its a intermediate error. It's not reproduce every time thats why I attached screen. Please allow me. I'll try to make codepan as you suggest but not sure it reproduce over there.

**Comment by Deckluhm** [comment]
@sanjay-russmediatech if you isolate the code and can't reproduce the error, that might be a sign that the error is in your code (not a bug in Foundation).

That's why lot of open-source projects ask for reproduction steps (or even better, CodePen / JSFiddle).

**Comment by IamManchanda** [comment]
@sanjay-russmediatech Sanjay bhai, Just fork these from below codepen's and reproduce 

- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)
We unfortunately can't help you with screenshots!

Also if its not a bug related with foundation itself,
The [Foundation Forum](http://foundation.zurb.com/forum) would be a better place to seek help!

**Comment by Deckluhm** [comment]
@IamManchanda the issue is about Foundation 5.2.2, not 6.3.1.

**Comment by IamManchanda** [comment]
Yeah @Deckluhm i have updated my comment .... didn't notice at first !

**Comment by sanjay-russmediatech** [comment]
@Deckluhm @IamManchanda Thanks. I'll try to reproduce in codepan and let you update. I also check in my codebase that if something wrong with my code.

**Comment by IamManchanda** [comment]
@sanjay-russmediatech any updates ??

**Comment by sanjay-russmediatech** [comment]
@IamManchanda I tried in codpan and there is no issue with foundation. It may be due to a older version of jquery used in my project but, thanks for your help. I'm closing this issue.
