### ISSUE TITLE
[Grid] Uncentering columns breaks their float

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites#9952]
How to replicate: 
- At the medium breakpoint, two columns that total > 12 and are both centered
- At the large breakpoint, these columns total ≤ 12 and are both uncentered
- The `.large-uncentered` class does not allow columns to float, as the `.medium-centered` class still applies `float:none;` and `clear:both;` 

https://codepen.io/andycochran/pen/mmyyzj

**Comment by JeremyEnglert** [comment]
Here is a super rough way of fixing this, although, we may be able to make this a bit more generic so it applies to all of these types of instances. I'll give it a shot if we think this is a good path to go down.

```
@include breakpoint(large) {
	.medium-centered {
		&.large-uncentered {
			float: left;
			clear: none;
			&:last-child:not(:first-child) {
				float: right;
				clear: none;
			}
		}
	}
}
```

**Comment by JeremyEnglert** [comment]
This is probably a bit better.

```SASS
.small-centered {
	@include breakpoint(medium) {
		&.medium-uncentered {
			float: left;
			clear: none;
			&:last-child:not(:first-child) {
				float: right;
				clear: none;
			}
		}
	}
	@include breakpoint(large) {
		&.large-uncentered {
			float: left;
			clear: none;
			&:last-child:not(:first-child) {
				float: right;
				clear: none;
			}
		}
	}	
}

.medium-centered {
	@include breakpoint(large) {
		&.large-uncentered {
			float: left;
			clear: none;
			&:last-child:not(:first-child) {
				float: right;
				clear: none;
			}
		}
	}
}
```

**Comment by kball** [comment]
Sigh... feels like we're going down the specificity rabbit hole... @ncoden do you have any better ideas for how to address this?

**Comment by andycochran** [comment]
> specificity rabbit hole

^ Yup. I'm wondering if we should just live with this and be better with specificity in v7.

**Comment by andycochran** [comment]
@ncoden That plan works for me.

**Comment by ncoden** [comment]
Hmmm... `$grid-column-align-edge` is `true` by default. Removing it can be a breaking change.
See https://foundation.zurb.com/sites/docs/grid.html#incomplete-rows

> In order to work around browsers' different rounding behaviors, Foundation will float the last column in a row to the right so the edge aligns. (...)

So this is not only about incomplete grid alignement, but also to "hide" in the gutter some browsers' precision bug.

I found https://github.com/zurb/foundation-sites/commit/f014bcc67134b2293ec9f23fe842c3abc16be1b2 that added back this behavior but I don't understand the meaning of the commit message and there is no previous commits.

I guess this restore a Grid behavior from Foundation 5 but I'm not sure. I have to find which browsers handle grid precisions differently (IE & Edge maybe, this seems related to https://github.com/zurb/foundation-sites/issues/10808) to know if we can (or not) remove this behavior.

**Comment by ncoden** [comment]
Here are the results of my research so far. This precision bug that makes rows in a column not taking the full width (like `99.98%`) and being aligned on the right have two causes:
* We use the Sass maximum 5-digit precision, and this is not enough. Above 1200px the bug become visible, some rows width are 1px less.
* On IE and Edge < 14, all values are truncated at 2 digits after decimal. So it's like if we had a 2-digit precision and the bug appear far more often. See https://github.com/zurb/foundation-sites/issues/10808

I checked how Boostrap works to try to understand how important this is. BS 4 is based on flex grid only (so in most case a row will take all the availaible space), and BS does not resolve this bug (it can be reproduced in their documentation).

So now I understand why this "feature" is enabled by default on all columns. In complete rows this is actually a fix. So I don't like to say that but we may have to keep this behavior and go for the specificity fix....
