### ISSUE TITLE
[Accordion Menu] Page scrolls when opening accordion with space bar

### ISSUE THREAD

**Issue by michaelwayneharris87** [zurb/foundation-sites#9953]
#### How to reproduce this bug:

1. Navigate to a collapsed accordion tab
2. Press the space bar to open the tab

#### What should happen:
The page should not scroll

#### What happened instead:
The page scrolls

#### Test case:

http://foundation.zurb.com/sites/docs/accordion-menu.html

**Comment by IamManchanda** [comment]
Yup i confirm this is a bug with accesibility 
cc / @Owlbertz

**Comment by Owlbertz** [comment]
True, that should not happen. PR is up.

**Comment by IamManchanda** [comment]
Great buddy @Owlbertz

**Comment by kball** [comment]
Fixed with #9956
