### ISSUE TITLE
[6.3.1] Menu that is vertical will not align-center with flexbox

### ISSUE THREAD

**Issue by Yanchek99** [zurb/foundation-sites#9955]
#### How to reproduce this bug:

1. Ensure flexbox is enabled
2. Create a menu with the following classes .vertical and .align-center

#### What should happen:
Vertical Menu should be center aligned.

#### What happened instead:
Vertical Menu is aligned to the left

#### Test case:

http://codepen.io/anon/pen/eWmdJq

**Comment by IamManchanda** [comment]
@Yanchek99 Are you talking 
http://codepen.io/IamManchanda/pen/OmPbeM

**Comment by IamManchanda** [comment]
and there are other option too => http://codepen.io/IamManchanda/pen/OmPWPN

**Comment by Yanchek99** [comment]
@IamManchanda Yes this is what I was looking for.  However I would expect these to be work with foundation-sites out of the box. It seems that all the aligns are failing for vertical menus (ex. align-center, align-right.)

**Comment by IamManchanda** [comment]
Yeah this would .... dont worry @Yanchek99 .... **I am taking this up!**

**Comment by IamManchanda** [comment]
Also @Yanchek99 
Here is the codepen on how to go about it right now on align-right as you mentioned untill this is added up
=> http://codepen.io/IamManchanda/pen/pPvRwL

{ **Sorry I wont be able to take this up right now at the moment .... but will create a patch soon** }
