### ISSUE TITLE
Drilldown Menu doesn't have any 'before-x-happens' events

### ISSUE THREAD

**Issue by joeyfigaro** [zurb/foundation-sites#9957]
#### How to reproduce this bug:
1. Attempt to watch for `before-x-happens` events 
2. Cry

#### What should happen:
Should be able to watch for `before-x-happens` events e.g. `$(x).on('before.open.zf.drilldown')`

#### What happened instead:
Component doesn't support `before-x-happens` events

#### Test case:
Ran into someone trying to style this navigation so the submenus didn't span the entire width of the navigation, which made it possible to open multiple submenus. 

I get that it's not *meant* to be used that way, but `before`/`during`/`after` events would open this guy up and make it a bit more flexible.

- [CodePen with Foundation 6.3.0 and MotionUI](http://codepen.io/IamManchanda/pen/vgemXR)
- [CodePen with Foundation 6.3.0, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/xgXdRq)

- [CodePen with Foundation 6.3.1 and MotionUI](http://codepen.io/IamManchanda/pen/LWGZxR)
- [CodePen with Foundation 6.3.1, Flexbox grid and MotionUI](http://codepen.io/IamManchanda/pen/zZrBEv)

**Comment by kball** [comment]
+100%

@coreysyms I know at some point you were interested in auditing the event lifecycle and improving it... is that still on your radar?

**Comment by JeremyEnglert** [comment]
This is something that will be a lot more consistent and improved in F7. However, I can't see this being added to F6. Closing and labeling this to reopen for F7 discussion.
