### ISSUE TITLE
$color-pick-contrast documentation enhancement suggestion

### ISSUE THREAD

**Issue by blazebarsamian** [zurb/foundation-sites#9964]
I'm just wondering if there was a reason why `$base` was excluded from the example code? 

I feel like it would be helpful to display how the code needs to be written with `$base` included. It was a little confusing to me at first and I'm sure I'm not the only one who was unclear.

I would change:
```
color-pick-contrast($color1, $color2)
```
to:
```
 color-pick-contrast($base, ($color1, $color2));
```

Also, maybe this is overkill but I don't think it would hurt to define `$base` in the parameters table.

<img width="923" alt="screen shot 2017-04-19 at 4 09 15 pm" src="https://cloud.githubusercontent.com/assets/9321193/25202393/d907d1d4-251a-11e7-92ba-79c45192d2c1.png">

http://foundation.zurb.com/sites/docs/sass-functions.html#color-pick-contrast

**Comment by DanielRuf** [comment]
Thanks for reporting this.

The current docs look like this:

![foundation zurb com_sites_docs_sass-functions html](https://user-images.githubusercontent.com/827205/37247199-1d642628-24b8-11e8-8f7d-6a55ac88008b.png)

So I'm gonna close this.
