### ISSUE TITLE
How to check version?

### ISSUE THREAD

**Issue by ob7** [zurb/foundation-sites#9976]
I can run foundation -v to get the command line version, but where in the framework is the version of the framework defined?

**Comment by IamManchanda** [comment]
Look for `package.json`

**Comment by Owlbertz** [comment]
You can also run `Foundation.version` in your browser's dev tools console.

**Comment by IamManchanda** [comment]
Closing this issue now with above 2 comments as reference .... 

@ob7 Please feel free to revert if something's left!

**Comment by ob7** [comment]
My package.json generated by foundation-cli does not actually list the version of the framework itself.
I believe I'm using Foundation 6.3.1.
As for running Foundation.version, that will only work if you are also using javascript, but I'm only using the CSS.

**Comment by IamManchanda** [comment]
Reopening the issue 
Can you brief about your workflow???

**Comment by Deckluhm** [comment]
`bower_components/foundation-sites/bower.json` is what you are looking for.

The version can also be found at the top of these files:
- Any unminified file in `bower_components/foundation-sites/dist/css`
- `bower_components/foundation-sites/scss/foundation.scss`

**Comment by ob7** [comment]
Thank you Deckluhm all others.   The responses cover about every way to get the version.  My  specific need was answered by Deckluhm by showing me where I can find the foundation version in plain text throughout the files.
