### ISSUE TITLE
Feature Request: Add hover to toggler similar to data-toggle-focus

### ISSUE THREAD

**Issue by garrett-eclipse** [zurb/foundation-sites#9978]
Hello,

I would love to see the toggler expanded to include hover actions;
http://foundation.zurb.com/sites/docs/toggler.html

Currently, it supports focus so hover would be an additional item I'd like to see, and I don't think I'm alone;
http://foundation.zurb.com/forum/posts/47695-can-data-toggler-act-on-hover

Thank you

**Comment by IamManchanda** [comment]
cc / @kball .... can we look into this.

**Comment by kball** [comment]
There's two pieces here to look at.. one is the triggers utility, which is how a `toggle` is triggered... the second is the `toggler` (note the additional `r`) plugin which wraps up some common ways to handle a toggle. I think the request here would actually be implemented in the triggers... see for example how toggle-focus is handled here: https://github.com/zurb/foundation-sites/blob/develop/js/foundation.util.triggers.js#L61

If either @garrett-eclipse or @IamManchanda want to take a pass on this, that's where I'd start tinkering...

This being said, I think the ways in which the triggers are handled so differently from the rest of Foundation's plugins can be pretty confusing... we may want to refactor that. (cc @coreysyms)

**Comment by denisahac** [comment]
A very welcome addition. 👍

**Comment by JeremyEnglert** [comment]
We'll look into this for V7. Great suggestion.

**Comment by garrett-eclipse** [comment]
Sounds good, thanks @JeremyEnglert & @IamManchanda. I'll take a stab at this sometime this month
