### ISSUE TITLE
Column .shrink + .small/medium/large-# class behaviour 

### ISSUE THREAD

**Issue by BicanMarianValeriu** [zurb/foundation-sites#9986]
#### How to reproduce this bug:
I have a container with .column.small-12.shrink class
If there is a medium-expand class or large-expand why there is not a .medium-shrink or .large-shrink or there is one and I don't know. Should it be like it is or is a bug? 

#### What should happen:
-- 
#### What happened instead:
--
#### Browser(s) and Device(s) tested on:
not the case
#### Test case link:

No pen for this - busy right now. Sorry :(

**Comment by BicanMarianValeriu** [comment]
In my opinion .shink class should be:

.shrink:not(class^="small"):not(class^="medium"):not(class^="large")

**Comment by JeremyEnglert** [comment]
A cell can also be made to shrink, by adding the .shrink or .[size]-shrink class. This means it will only take up the space its contents need.

https://foundation.zurb.com/sites/docs/xy-grid.html#auto-sizing
