### ISSUE TITLE
[Tooltip] Considering Tether type functionality?

### ISSUE THREAD

**Issue by IamManchanda** [zurb/foundation-sites#9989]
I think my comment was missed so here it is ??

https://github.com/zurb/foundation-sites/issues/9618#issuecomment-292786762

> i think we should seriously consider **[Tether](http://tether.io/)**
> 
> I mean just look at this PR twbs/bootstrap#22264 and changes
> Demo => http://jsbin.com/lijalowata/edit?html,output
> 
> With this all 12 positioning elements can be used
> Default: top | right | bottom | left
> Optional: top left | top right | right top | right bottom | bottom left | bottom right | left top | left bottom

**Comment by IamManchanda** [comment]
if this is a stupid idea or can be done through current JS then let me know!

**Comment by ompmega** [comment]
Support! Please implement this, or if there's a way to implement it ourselves, that would be awesome! +1

**Comment by IamManchanda** [comment]
cc @kball!

**Comment by IamManchanda** [comment]
@ompmega We have started work on it but with current resources instead of tether!
Thanks for the shoutout!

**Comment by IamManchanda** [comment]
Added in #10053 .... closing this!
