### ISSUE TITLE
Documentation for Title Bar component is missing

### ISSUE THREAD

**Issue by Proper-Job** [zurb/foundation-sites#9991]
There is a mixin called `foundation-title-bar` located in foundation-sites/scss/components/_title-bar.scss.  However there is no documentation related to that component.

**Comment by IamManchanda** [comment]
@Proper-Job Do you mean `top-bar-title` ??

**Comment by Proper-Job** [comment]
@IamManchanda No, I don't mean top-bar-title.
In several places the ``.title-bar`` class is mentioned, for instance in:
- [Sticky Navigation](http://foundation.zurb.com/sites/docs/sticky.html#sticky-navigation)
- [Off-canvas](http://foundation.zurb.com/sites/docs/off-canvas.html#combining-with-title-bar)
- [Kitchen Sink](http://foundation.zurb.com/sites/docs/kitchen-sink.html#title-bar)
- [Responsive navigation](http://foundation.zurb.com/sites/docs/responsive-navigation.html#responsive-toggle)
- [foundation.scss](https://github.com/zurb/foundation-sites/blob/v6.3.1/scss/foundation.scss#L109)

However, there is no documentation as to what the title-bar component actually does or how to properly configure it.

**Comment by IamManchanda** [comment]
Sorry... this got missed...
So you basically want the docs for the container of the hamburger menu ??

https://codepen.io/IamManchanda/pen/LymroM?editors=1100
```html
<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>
```

**Comment by Proper-Job** [comment]
@IamManchanda thanks for getting back to me.
It would be nice to have a section explaining what the Title Bar component does and when it should be used.  Hints are scattered throughout the docs, but like I said, searching for "Title Bar" yields no results.
For instance there are the ``.title-bar-left`` and ``.title-bar-right`` classes that, I assume, align content left and right.  However, this information I glean from a section in the docs called: "Sticky Navigation".
I'm also wondering what the difference is between Top Bar and Title Bar and when should I use which.
Forgive me if I'm being obtuse, but I believe a doc section covering the Title Bar component is merited.

**Comment by IamManchanda** [comment]
cc @kball .... shall we have it?? 

PS: I also think the same that we should have it!

**Comment by IamManchanda** [comment]
https://github.com/zurb/foundation-sites/pull/10056#issuecomment-305307281

> What I'd like to see in the future:
> - [ ] title-bar has it's own docs page within navigation
> - [ ] title-bar inherits top-bar styles (height, color, background)
> - [ ] or eliminate the thing altogether and use top-bar on mobile and larger

**Comment by JeremyEnglert** [comment]
https://foundation.zurb.com/sites/docs/off-canvas.html#combining-with-title-bar

The title bar is more of an add-on components in F6. So it's treated as such in the docs. 

We'll be better about this in F7.
