### ISSUE TITLE
fourseven:scss conflict with angular2-compilers package

### ISSUE THREAD

**Issue by kevinklinegargar** [zurb/foundation-sites#9992]
Hi Guys,

I'm new to meteor and angular2 development. I have this app that I will use foundation(zurb) and angular2 framework. But when I install the foundation using this command (meteor add zurb:foundation-sites) and run the app I got a package conflict See the error messages:

> _While determining active plugins:_
> _   error: conflict: two packages included in the app (fourseven:scss and angular2-compilers) are both trying to handle *.scss_
> _   error: conflict: two packages included in the app (fourseven:scss and angular2-compilers) are both trying to handle *.sass_

> _   While determining active plugins:_
> _   error: conflict: two packages included in the app (fourseven:scss and angular2-compilers) are both trying to handle *.scss_
> _   error: conflict: two packages included in the app (fourseven:scss and angular2-compilers) are both trying to handle *.sass_

I tried to remove the fourseven:scss package but it also gives me an error `"fourseven:scss is not a direct dependency in this project."`

**_Is there a way to remove either of the 2 sass compilers?_**

Thanks in advance!

**Comment by Deckluhm** [comment]
That looks more like a Meteor "issue" (not a Foundation / Angular one).

Note that GitHub issues aren't generally the good place for help / support (most open-source projects use GitHub issues for bugs and feature requests).

I see that you already opened a topic on the Meteor forum, you will have more chance there!
And if not already done, check [their documentation](https://docs.meteor.com/).

**Comment by kevinklinegargar** [comment]
Ah yes, I thought this is from meteor packages repo. I will close this issue now.thanks
