### ISSUE TITLE
Orbit scroll issue

### ISSUE THREAD

**Issue by RLHawk1** [zurb/foundation-sites#9993]
#### How to reproduce this bug:

1. Create more than one orbit with auto-play on the same page in a way where they won't both fit entirely on the screen
2. Scroll until they're both partially in view

#### What should happen:
They should auto scroll as usual

#### What happened instead:
The screen jumps up to put the top of the top orbit into view.

#### Browser(s) and Device(s) tested on:
Google Chrome 59 desktop, Google Chrome 57 Android, Mobile Safari

#### Test case link:
http://codepen.io/rlhawk1/pen/ybgbyV

**Comment by JeremyEnglert** [comment]
This appears to be working fine in your pen: https://codepen.io/rlhawk1/full/ybgbyV/

Closing.
