### ISSUE TITLE
Printing Issues with Edge / IE11

### ISSUE THREAD

**Issue by bernhardsturm** [zurb/foundation-sites#9994]
#### How to reproduce this bug:

1. Create a nested class="row" sequence (NOTE: flex-box is used a layout grid method)
2. Add a lot of content in the second class="row" construct
3. Print the page with Microsoft Edge or Internet Explorer 11

#### What should happen:
All content should be printed on multiple pages

#### What happened instead:
Only the first and last page is being printed. Some content is missing on the printout.

#### Browser(s) and Device(s) tested on:
Windows 10: Microsoft Edge (latest flavour), Internet Explorer 11

#### Fixing:
The issue can be fixed by adding the following line to your custom print scss:

`
.row {
  .row {
    display:block !important;
  }
}
`

**Comment by IamManchanda** [comment]
cc / @andycochran @rafibomb

**Comment by DanielRuf** [comment]
Will check it this week if we still need some PR.

**Comment by DanielRuf** [comment]
> Create a nested class="row" sequence (NOTE: flex-box is used a layout grid method)

row in row is not a good idea, it should be row - column - row - column at least

I guess this is due to wrong usage of the classes or how do you see this @ncoden?

**Comment by ncoden** [comment]
Agreed. See https://foundation.zurb.com/sites/docs/grid.html#nesting.
But I'm not sure this is the layout @sultaninen is using.

@sultaninen Could you provide a Codepen to allow us to easily reproduce your bug ?

**Comment by DanielRuf** [comment]
Mh, I'm also seeing some printing issue in Firefox where only the first page is shown and the rest is empty.

**Comment by DanielRuf** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1303221 and https://bugzilla.mozilla.org/show_bug.cgi?id=1411836

**Comment by DanielRuf** [comment]
And see https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?page=1&q=print%20first%20page

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
