### ISSUE TITLE
cli build of tab-content has no definition for display.

### ISSUE THREAD

**Issue by Aaasaasa** [zurb/foundation-sites#9996]
splitted node in content in tab  (e.g. medium-x large-x) not render hight correctly.

#### What should happen:
.tab-content{ display: inline-grid; } // or inline-block

#### What happened instead:
content overflow border 
 no definition
#### Browser(s) and Device(s) tested on:
 ie, ff
#### Test case link:

Foundation 6.3.0 and 3.3.1

**Comment by Deckluhm** [comment]
That may be just me but I have a hard time understanding your issue.

Can you explain more in depth what you are trying to achieve, show us the code you tried (using a CodePen or anything similar) and be clearer about the issue encountered?

Thanks!

**Comment by rafibomb** [comment]
Thanks @Deckluhm! @Aaasaasa Here is a blank codepen to share what the issue is: http://codepen.io/rafibomb/pen/wddYLB

**Comment by Aaasaasa** [comment]
OK, sorry that I wrote it so confused but I haven't have enought time :)
Tomorrow I have more time to better explain what I thought.
Tanks... I have put basic code on codepen

**Comment by Aaasaasa** [comment]
Hier is it:
http://codepen.io/Aaasaasa/pen/MmomXK
floating elements in content of tabs

**Comment by Deckluhm** [comment]
You need to nest your `.columns` inside a `.row` and everything will work as expected.

Here is a quick example:
```HTML
<div class="row">
  <div class="small-5 columns"><!-- CONTENT --></div>
  <div class="small-7 columns"><!-- CONTENT --></div>
</div>
```

Take time to (re)read Grid basics if needed: http://foundation.zurb.com/sites/docs/grid.html

**Comment by Aaasaasa** [comment]
Thanks Deckluhm, you're right. But if I have simple floating elements like this: 
http://codepen.io/Aaasaasa/pen/ybXXvo  
is it not safer if I set the parent tabs container to inline-block?

**Comment by Deckluhm** [comment]
I also recommend to use grid for that use case because your images will be more nicely aligned (thanks to grid gutters) but if you really want to use float classes, don't forget to use `.clearfix` on the parent container as described in the [documentation](http://foundation.zurb.com/sites/docs/float-classes.html).
