### ISSUE TITLE
Off-Canvas Flashing on Page Load

### ISSUE THREAD

**Issue by tsquez** [zurb/foundation-sites#9998]
I just noticed something strange, the Off-Canvas menu seems to flash and disappear on page load.

You can see it happen here https://themeawesome.com/themes/wpforge/

Any idea why it would do something like this? It's never happened before. I have been looking into it but can't figure it out?

Ideas? Any help is greatly appreciated.

**Comment by IamManchanda** [comment]
cc / @brettsmason

**Comment by brettsmason** [comment]
@tsquez I'm not sure this is an issue with off-canvas.
My gut is telling me its some kind of caching on your site that's causing it. It looks like you are using Cloudflare - could you try disabling that (and any other caching plugin/service) and see if it then works as expected? I think there's a delay in your stylesheet loading, as there's also a flicker on the headings and some other elements.

**Comment by tsquez** [comment]
I believe you are correct sir. I didn't even think about that....der!!! See that's why you get paid the big bucks :stuck_out_tongue_winking_eye:

Thanks again for looking into that amigo, greatly appreciated.
